local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Paladin-Holy','DeathKnight-Unholy','DemonHunter-Devourer','Paladin-Retribution','Warrior-Fury','Priest-Holy','Priest-Shadow','Monk-Windwalker','Monk-Brewmaster','Warlock-Demonology','Shaman-Elemental','Hunter-BeastMastery','Unknown-Unknown','Mage-Frost','DeathKnight-Frost','Hunter-Marksmanship','Warlock-Destruction','Paladin-Protection','DemonHunter-Havoc','DemonHunter-Vengeance','Warrior-Protection','Warlock-Affliction','Rogue-Subtlety','Shaman-Restoration','Hunter-Survival','Warrior-Arms','Druid-Restoration','Evoker-Preservation','Evoker-Augmentation','Priest-Discipline','Monk-Mistweaver','Druid-Balance','Druid-Feral','Shaman-Enhancement','Rogue-Outlaw','DeathKnight-Blood','Druid-Guardian',}
local provider = {region='US',realm='Runetotem',name='US',type='daily',zone=46,date='2026-06-07',data={Ab='Abert:BAAALgADCgUJBQAAAA==.Abilify:BAAALgAECgEJAgAAAA==.',
Ac='Acts:BAAALgAECgEJAQAAAA==.',
Ad='Adalinda:BAAALgADCgkJCgABLgAFFAUJGAABABkfAA==.',
Ag='Agnor:BAABLgAECn81AAICAAgJVxpzPQAFAghoDAAACwBBAGkMAAALAEYAawwAAAwAUwBqDAAABQBVAGwMAAAEADEAbQwAAAEAKwDqDAAABwBJAG4MAAACAFYAAgAICVcacz0ABQIIaAwAAAsAQQBpDAAACwBGAGsMAAAMAFMAagwAAAUAVQBsDAAABAAxAG0MAAABACsA6gwAAAcASQBuDAAAAgBWAAAA.',
Al='Alatir:BAAALgADCgcJEQAAAA==.Alticus:BAAALgADCgEJAQAAAA==.',
An='Andrew:BAAALgAECgEJAQABLgAFFAUJDgADANEWAA==.Anien:BAAALgAECgYJEQAAAA==.Anklemauler:BAAALgAECgYJBgAAAA==.Anthem:BAAALgAECgYJBgAAAA==.Antibubble:BAABLgAECn8gAAICAAkJYB5PIQB8AgloDAAABQBYAGkMAAAEAF0AawwAAAQAVABqDAAABABOAGwMAAAEAFsAbQwAAAIAOwDqDAAABQBcAG4MAAADAEEAbwwAAAEALwACAAkJYB5PIQB8AgloDAAABQBYAGkMAAAEAF0AawwAAAQAVABqDAAABABOAGwMAAAEAFsAbQwAAAIAOwDqDAAABQBcAG4MAAADAEEAbwwAAAEALwAAAA==.Antipeta:BAAALgAECgEJAgAAAA==.Anwal:BAACLgAFFH8YAAIBAAUJGR87DgDHAQVoDAAACABSAGkMAAAGAFsAawwAAAMASwBqDAAAAQA+AOoMAAAGAFcAAQAFCRkfOw4AxwEFaAwAAAgAUgBpDAAABgBbAGsMAAADAEsAagwAAAEAPgDqDAAABgBXAC4ABAp/LQADAQAJCVccuyIACQIAAQAICUgbuyIACQIABAAJCUIM03IAfgEAAAA=.',
Ar='Argus:BAABLgAECn8vAAIFAAgJHCN8CQDEAghoDAAACQBdAGkMAAAHAFgAawwAAAcATQBqDAAABQBfAGwMAAAGAF8AbQwAAAMAWQDqDAAABwBYAG4MAAADAF8ABQAICRwjfAkAxAIIaAwAAAkAXQBpDAAABwBYAGsMAAAHAE0AagwAAAUAXwBsDAAABgBfAG0MAAADAFkA6gwAAAcAWABuDAAAAwBfAAAA.Arithana:BAABLgAFFH8IAAMGAAQJaAMnIQCfAARoDAAAAgAAAGkMAAACAAMAawwAAAIAAQDqDAAAAgAdAAYABAloAychAJ8ABGgMAAACAAAAaQwAAAIAAwBrDAAAAQABAOoMAAACAB0ABwABCSAH7ToANwABawwAAAEAEgABLgAFFAQJCAAIAHAJAA==.Arithfury:BAAALgAECgIJAgABLgAFFAQJCAAIAHAJAA==.Arithkick:BAACLgAFFH8IAAMIAAQJcAlsJQC2AARoDAAABAAeAGkMAAACABMAawwAAAEAAQDqDAAAAQAtAAgAAwnrCmwlALYAA2gMAAABABMAaQwAAAEAEwDqDAAAAQAtAAkAAwnJBQs+AKEAA2gMAAADAB4AaQwAAAEADABrDAAAAQABAC4ABAp/IQACCQAICUUZbxQAawIACQAICUUZbxQAawIAAAA=.',
As='Asayo:BAAALgAECgUJEgAAAA==.Asherie:BAAALgAECgQJCQABLgAECggJFAAGAO0RAA==.Aske:BAABLgAECn8kAAIKAAgJIxT+UACjAQhoDAAABgBCAGkMAAAFADEAawwAAAQAMwBqDAAABABeAGwMAAAGAC0AbQwAAAIALQDqDAAABwBBAG4MAAACACQACgAICSMU/lAAowEIaAwAAAYAQgBpDAAABQAxAGsMAAAEADMAagwAAAQAXgBsDAAABgAtAG0MAAACAC0A6gwAAAcAQQBuDAAAAgAkAAAA.Astolan:BAAALgAECgEJAgAAAA==.',
At='Atonga:BAAALgAECgQJBAAAAA==.',
Au='Augtistic:BAAALgAECgcJEQAAAA==.',
Az='Azuresun:BAABLgAECn8fAAILAAkJEAuHMwBhAQloDAAABAAyAGkMAAAEAB8AawwAAAQAHwBqDAAABAAeAGwMAAAEABUAbQwAAAMAEQDqDAAABAAiAG4MAAADABYAbwwAAAEAEAALAAkJEAuHMwBhAQloDAAABAAyAGkMAAAEAB8AawwAAAQAHwBqDAAABAAeAGwMAAAEABUAbQwAAAMAEQDqDAAABAAiAG4MAAADABYAbwwAAAEAEAAAAA==.',
Ba='Ballak:BAABLgAECn8ZAAIMAAcJzRGWVABrAQdoDAAABAA6AGkMAAAFADgAawwAAAUAMQBqDAAABAAsAGwMAAAEADoAbQwAAAEACADqDAAAAgApAAwABwnNEZZUAGsBB2gMAAAEADoAaQwAAAUAOABrDAAABQAxAGoMAAAEACwAbAwAAAQAOgBtDAAAAQAIAOoMAAACACkAAAA=.Barlee:BAAALgADCgEJAQABLgAFFAIJAQANAAAAAA==.',
Be='Beatin:BAAALgAECgUJCgAAAA==.Belenzr:BAAALgADCgEJAQAAAA==.',
Bi='Bigdikley:BAAALgAECgYJEQAAAA==.Biggtater:BAAALgADCgUJBQAAAA==.',
Bl='Bloodywake:BAAALgAECgMJAwAAAA==.Bloopydoo:BAABLgAECn8VAAIOAAYJNgju0ADsAAZoDAAAAgAOAGkMAAAEABIAawwAAAQADwBqDAAAAwAXAGwMAAADAB0A6gwAAAUAGwAOAAYJNgju0ADsAAZoDAAAAgAOAGkMAAAEABIAawwAAAQADwBqDAAAAwAXAGwMAAADAB0A6gwAAAUAGwAAAA==.Blort:BAAALgADCgEJAQAAAA==.Bláckbird:BAABLgAECn8bAAIMAAkJMhrmTwCoAQloDAAABABaAGkMAAADAEoAawwAAAMAQgBqDAAABAA+AGwMAAAFADMAbQwAAAMAWADqDAAAAQAPAG4MAAADAFsAbwwAAAEAOgAMAAkJMhrmTwCoAQloDAAABABaAGkMAAADAEoAawwAAAMAQgBqDAAABAA+AGwMAAAFADMAbQwAAAMAWADqDAAAAQAPAG4MAAADAFsAbwwAAAEAOgAAAA==.',
Bo='Bohliang:BAAALgADCgkJEAAAAA==.Boltywolty:BAAALgAECgYJCgAAAA==.Borim:BAAALgAECgEJAQAAAA==.',
Br='Brandymae:BAAALgAECgMJBQAAAA==.Branholy:BAAALgADCgEJAQAAAA==.Brbpoopin:BAAALgAECgYJBgAAAA==.Brotems:BAAALgAECgkJAQAAAA==.Bruwdflight:BAAALgAECgEJAQAAAA==.',
Bu='Bubblebuster:BAAALgAECgYJDAABLgAECgkJIAACAGAeAA==.Bumwarrior:BAAALgADCgEJAQAAAA==.Burnphase:BAAALgADCgQJBwAAAA==.',
By='Byrdreisyl:BAAALgAECgQJBAAAAA==.',
Ca='Caosgonewild:BAAALgAECgUJBQAAAA==.',
Ce='Celestyal:BAAALgADCgMJAwAAAA==.',
Ch='Chestie:BAABLgAECn8hAAMCAAkJdR2QSwDaAQloDAAABgBQAGkMAAAFAFIAawwAAAQATwBqDAAABABLAGwMAAADAEUAbQwAAAIAVwDqDAAABwBDAG4MAAABAEQAbwwAAAEAQwACAAgJ6x2QSwDaAQhoDAAABgBQAGkMAAAFAFIAawwAAAQATwBqDAAABABLAGwMAAADAEUAbQwAAAIAVwDqDAAABQBDAG4MAAABAEQADwACCTgaiiUAkQAC6gwAAAIAQwBvDAAAAQBDAAAA.Chubbychi:BAAALgAECgIJAgAAAA==.',
Ci='Cinde:BAAALgADCgMJAwABLgAFFAQJCwAMADscAA==.Cindy:BAACLgAFFH8LAAIMAAQJOxw9JgBaAQRoDAAAAwBVAGkMAAADAD8AawwAAAIANgDqDAAAAwBVAAwABAk7HD0mAFoBBGgMAAADAFUAaQwAAAMAPwBrDAAAAgA2AOoMAAADAFUALgAECn8kAAMMAAkJDh4MFQChAgAMAAkJDh4MFQChAgAQAAEJ3gWdkQApAAAAAA==.Cindyx:BAAALgAECgYJDwABLgAFFAQJCwAMADscAA==.',
Co='Coast:BAABLgAECn8VAAIRAAgJ1wdgFwDdAAhoDAAAAwAjAGkMAAADABoAawwAAAMAGQBqDAAAAwAQAGwMAAADAAkAbQwAAAIACADqDAAAAwAfAG4MAAABAAMAEQAICdcHYBcA3QAIaAwAAAMAIwBpDAAAAwAaAGsMAAADABkAagwAAAMAEABsDAAAAwAJAG0MAAACAAgA6gwAAAMAHwBuDAAAAQADAAAA.Coldlock:BAAALgAECggJCAABLgAECgkJMAASAAUaAA==.Coldsore:BAABLgAECn8wAAQSAAkJBRrMCQAlAgloDAAABwA/AGkMAAAHAFIAawwAAAcAWABqDAAABgBDAGwMAAAGAEoAbQwAAAQARADqDAAABgBEAG4MAAADAEIAbwwAAAIAEwASAAkJ4RnMCQAlAgloDAAABgA/AGkMAAAGAFIAawwAAAYAWABqDAAABQBDAGwMAAAFAEoAbQwAAAMARADqDAAABQBEAG4MAAACAEIAbwwAAAEAEQABAAYJ+wY4UQDqAAZoDAAAAQADAGoMAAABABMAbAwAAAEAIQBtDAAAAQAZAOoMAAABAAwAbgwAAAEADAAEAAMJMQefIAGDAANpDAAAAQAdAGsMAAABAAUAbwwAAAEAEwAAAA==.Coldwar:BAAALgADCgcJBwAAAA==.Conjuremoney:BAAALgADCgEJAQAAAA==.Cootpal:BAABLgAECn8+AAIEAAkJDB42GACpAgloDAAACQBcAGkMAAAIAF4AawwAAAgARQBqDAAABwBbAGwMAAAIAF8AbQwAAAYAVQDqDAAABwBTAG4MAAAFAD8AbwwAAAQAHQAEAAkJDB42GACpAgloDAAACQBcAGkMAAAIAF4AawwAAAgARQBqDAAABwBbAGwMAAAIAF8AbQwAAAYAVQDqDAAABwBTAG4MAAAFAD8AbwwAAAQAHQAAAA==.Costcohotdog:BAAALgADCgMJAwAAAA==.',
Cr='Crazyloon:BAAALgAECgUJCQAAAA==.Crewmix:BAAALgAECgEJAQAAAA==.Croe:BAAALgADCgMJAwAAAA==.',
Cy='Cynawyne:BAAALgAECgEJAQAAAA==.Cynthea:BAAALgAECgkJCgAAAA==.',
Da='Dahm:BAAALgAECgMJBgAAAA==.Dalasaurs:BAACLgAFFH8FAAIFAAIJ/BpVOwChAAJoDAAAAwBAAOoMAAACAEkABQACCfwaVTsAoQACaAwAAAMAQADqDAAAAgBJAC4ABAp/MAACBQAICZMYoygAGgIABQAICZMYoygAGgIAAAA=.Dalasnipus:BAAALgADCgMJAwAAAA==.Dalbear:BAAALgADCgYJCQAAAA==.Darkpallas:BAAALgAECgYJCAAAAA==.Darkprophetc:BAABLgAECn8sAAIOAAkJiQsaagCiAQloDAAABgAiAGkMAAAFABkAawwAAAUAHABqDAAABQAWAGwMAAAHADkAbQwAAAUAGQDqDAAABQAPAG4MAAAFACgAbwwAAAEACAAOAAkJiQsaagCiAQloDAAABgAiAGkMAAAFABkAawwAAAUAHABqDAAABQAWAGwMAAAHADkAbQwAAAUAGQDqDAAABQAPAG4MAAAFACgAbwwAAAEACAAAAA==.',
De='Deathfyre:BAAALgADCgQJBAAAAA==.Deluun:BAAALgADCgkJCQAAAA==.Demious:BAABLgAECn8YAAIMAAgJHCAUHQBtAghoDAAAAwBQAGkMAAADAFQAawwAAAMATABqDAAAAQBbAGwMAAABAEoAbQwAAAIAQwDqDAAABgBhAG4MAAAFAF8ADAAICRwgFB0AbQIIaAwAAAMAUABpDAAAAwBUAGsMAAADAEwAagwAAAEAWwBsDAAAAQBKAG0MAAACAEMA6gwAAAYAYQBuDAAABQBfAAAA.Demiurge:BAEALgAECgkJEAAAAA==.Demonfister:BAACLgAFFH8JAAIFAAMJwQwXNgDFAANoDAAABABFAGkMAAACAA4A6gwAAAMADQAFAAMJwQwXNgDFAANoDAAABABFAGkMAAACAA4A6gwAAAMADQAuAAQKfygAAgUACQn+GxEMAKICAAUACQn+GxEMAKICAAAA.Demonkiller:BAABLgAECn8bAAITAAYJHAY/PgCtAAZoDAAABQAMAGkMAAAHABoAawwAAAUAEQBqDAAABAARAGwMAAADAA4A6gwAAAMABwATAAYJHAY/PgCtAAZoDAAABQAMAGkMAAAHABoAawwAAAUAEQBqDAAABAARAGwMAAADAA4A6gwAAAMABwAAAA==.Denastiest:BAABLgAECn8rAAIDAAgJ+Q+RWwBqAQhoDAAABwAhAGkMAAAGADIAawwAAAUAHQBqDAAABQA3AGwMAAAHADcAbQwAAAMAEQDqDAAACAA9AG4MAAACACYAAwAICfkPkVsAagEIaAwAAAcAIQBpDAAABgAyAGsMAAAFAB0AagwAAAUANwBsDAAABwA3AG0MAAADABEA6gwAAAgAPQBuDAAAAgAmAAAA.Denji:BAAALgAECggJEAAAAA==.Devvmonk:BAAALgAECgcJEwAAAA==.',
Di='Dindaratwo:BAAALgAECgEJAQAAAA==.',
Do='Doe:BAABLgAECn8pAAMUAAcJmyNJBQBKAgdoDAAACABiAGkMAAAHAGIAawwAAAgAXgBqDAAABABSAGwMAAABAEQA6gwAAAkAYQBuDAAABABYABQABwmbI0kFAEoCB2gMAAAGAGIAaQwAAAYAYgBrDAAABwBeAGoMAAAEAFIAbAwAAAEARADqDAAACQBhAG4MAAAEAFgAEwADCYYQ/lIAnQADaAwAAAIAFABpDAAAAQA6AGsMAAABADAAAAA=.Dokta:BAAALgAFFAEJAQAAAA==.',
Dr='Draflex:BAAALgAECgMJBAAAAA==.Drathal:BAABLgAECn8vAAIEAAkJoQTargAWAQloDAAABwAJAGkMAAAGAAkAawwAAAgAAwBqDAAACAASAGwMAAAHAA8AbQwAAAMAEADqDAAAAwAJAG4MAAAEAAoAbwwAAAEAEwAEAAkJoQTargAWAQloDAAABwAJAGkMAAAGAAkAawwAAAgAAwBqDAAACAASAGwMAAAHAA8AbQwAAAMAEADqDAAAAwAJAG4MAAAEAAoAbwwAAAEAEwAAAA==.Drjay:BAAALgADCgkJCwAAAA==.',
Dv='Dvergar:BAAALgAECgYJDAAAAA==.',
Ea='Eatshrooms:BAAALgAECgMJBAAAAA==.',
Ed='Edd:BAAALgAECgQJBAAAAA==.Eddiedean:BAAALgAECgYJBgAAAA==.',
El='Elfgonewild:BAAALgAECgUJCgAAAA==.Ellessra:BAABLgAECn8kAAIOAAgJyAIQ0gDqAAhoDAAABQAGAGkMAAAEAAcAawwAAAQABABqDAAABQAQAGwMAAAHAAsAbQwAAAMABADqDAAABgAFAG4MAAACAAgADgAICcgCENIA6gAIaAwAAAUABgBpDAAABAAHAGsMAAAEAAQAagwAAAUAEABsDAAABwALAG0MAAADAAQA6gwAAAYABQBuDAAAAgAIAAAA.Elnegrouno:BAABLgAECn8fAAIVAAcJfR/SCgBjAgdoDAAABgBeAGkMAAAFAFoAawwAAAUAVgBqDAAABQBEAGwMAAAEAD8AbQwAAAIAQADqDAAABABTABUABwl9H9IKAGMCB2gMAAAGAF4AaQwAAAUAWgBrDAAABQBWAGoMAAAFAEQAbAwAAAQAPwBtDAAAAgBAAOoMAAAEAFMAAAA=.Eloper:BAAALgAFFAEJAQAAAA==.',
Em='Emotank:BAAALgAECgUJBgAAAA==.',
Er='Eragone:BAAALgAECgMJBAAAAA==.',
Et='Etoro:BAAALgADCgEJAgAAAA==.',
Ev='Evissier:BAACLgAFFH8OAAIWAAQJZh+sAgBtAQRoDAAABgBdAGkMAAAEAEUAawwAAAEAUQDqDAAAAwBOABYABAlmH6wCAG0BBGgMAAAGAF0AaQwAAAQARQBrDAAAAQBRAOoMAAADAE4ALgAECn8dAAIWAAgJriAHAQACAwAWAAgJriAHAQACAwAAAA==.',
Ex='Exsequor:BAACLgAFFH8RAAISAAQJIiGVAgCDAQRoDAAABwBiAGkMAAACAF8AawwAAAEAPgDqDAAABwBSABIABAkiIZUCAIMBBGgMAAAHAGIAaQwAAAIAXwBrDAAAAQA+AOoMAAAHAFIALgAECn8dAAMSAAYJCyNMEgCYAQASAAYJCyNMEgCYAQAEAAEJcgf7UAErAAAAAA==.',
Ez='Ezuras:BAAALgADCgIJAgAAAA==.',
Fa='Faeyri:BAABLgAECn8rAAILAAgJnxsdFgAqAghoDAAABwA/AGkMAAAGAEIAawwAAAUAQgBqDAAABQBVAGwMAAAHAEcAbQwAAAMAQADqDAAACABVAG4MAAACAEwACwAICZ8bHRYAKgIIaAwAAAcAPwBpDAAABgBCAGsMAAAFAEIAagwAAAUAVQBsDAAABwBHAG0MAAADAEAA6gwAAAgAVQBuDAAAAgBMAAAA.Fassandin:BAAALgAECgIJAgAAAA==.',
Fe='Felli:BAAALgAECgEJAQAAAA==.',
Fi='Fishermon:BAAALgAECgUJCAAAAA==.',
Fl='Flagfarmer:BAABLgAECn8dAAIBAAYJMSZbEACMAgZoDAAABgBiAGkMAAAGAGMAawwAAAUAYgBqDAAAAwBiAGwMAAACAF8A6gwAAAcAYQABAAYJMSZbEACMAgZoDAAABgBiAGkMAAAGAGMAawwAAAUAYgBqDAAAAwBiAGwMAAACAF8A6gwAAAcAYQAAAA==.Flataxe:BAAALgAECgMJAwAAAA==.Flixunt:BAAALgADCgEJAQAAAA==.',
Fo='Foidepas:BAAALgAECgcJDQAAAA==.Fourid:BAAALgAECgQJCgAAAA==.Foxannee:BAAALgAECgMJBgAAAA==.',
Fr='Freezyweezy:BAACLgAFFH8LAAIOAAQJ4RsRRwBOAQRoDAAABABcAGkMAAACAEMAawwAAAEAHgDqDAAABABfAA4ABAnhGxFHAE4BBGgMAAAEAFwAaQwAAAIAQwBrDAAAAQAeAOoMAAAEAF8ALgAECn8fAAIOAAkJ6CMEHACtAgAOAAkJ6CMEHACtAgAAAA==.Frostfirer:BAAALgAECgYJAgAAAA==.',
Fu='Fudgeyenuh:BAAALgAECgkJCQAAAA==.',
Fy='Fyrewar:BAAALgAECgMJAwAAAA==.',
['Fú']='Fúry:BAAALgAECgcJBwAAAA==.',
Ga='Gallyn:BAABLgAFFH8LAAIXAAMJLh1bIgD8AANoDAAABABQAGkMAAADAFAA6gwAAAQAPwAXAAMJLh1bIgD8AANoDAAABABQAGkMAAADAFAA6gwAAAQAPwAAAA==.Gamm:BAAALgADCgcJEQAAAA==.Garaal:BAAALgAECgcJDQAAAA==.',
Ge='Gerel:BAAALgAECgYJBgAAAA==.',
Gi='Ginyu:BAAALgAECgIJAgAAAA==.',
Gl='Glacierrock:BAAALgADCgQJCgAAAA==.Gloria:BAABLgAECn8hAAIYAAkJ1AnaSQB8AQloDAAABQAKAGkMAAAEAA0AawwAAAUADwBqDAAAAwAbAGwMAAADACkAbQwAAAIAGQDqDAAABwAYAG4MAAADADAAbwwAAAEAEwAYAAkJ1AnaSQB8AQloDAAABQAKAGkMAAAEAA0AawwAAAUADwBqDAAAAwAbAGwMAAADACkAbQwAAAIAGQDqDAAABwAYAG4MAAADADAAbwwAAAEAEwAAAA==.',
Go='Gooblicious:BAAALgAECgEJAQAAAA==.Gori:BAAALgAECgIJAgAAAA==.',
Gr='Grail:BAABLgAECn8eAAIEAAcJ4A2PnAAyAQdoDAAAAwAuAGkMAAAGACIAawwAAAQAFwBqDAAAAgAWAGwMAAACAB0A6gwAAAcAFABuDAAABgA6AAQABwngDY+cADIBB2gMAAADAC4AaQwAAAYAIgBrDAAABAAXAGoMAAACABYAbAwAAAIAHQDqDAAABwAUAG4MAAAGADoAAAA=.Grelvisse:BAAALgAECgMJBQAAAA==.Grippywippy:BAAALgADCgYJBAAAAA==.',
Gu='Gudren:BAAALgADCgEJAQAAAA==.Guimon:BAAALgAECgMJBAAAAA==.Gunslinger:BAAALgAECgEJAQAAAA==.',
Gw='Gwenie:BAABLgAECn8mAAIKAAkJYhFnOwDnAQloDAAABgBHAGkMAAAGADYAawwAAAYALgBqDAAABwAvAGwMAAAEACsAbQwAAAEACwDqDAAABABFAG4MAAACACQAbwwAAAIAGAAKAAkJYhFnOwDnAQloDAAABgBHAGkMAAAGADYAawwAAAYALgBqDAAABwAvAGwMAAAEACsAbQwAAAEACwDqDAAABABFAG4MAAACACQAbwwAAAIAGAAAAA==.',
Ha='Halenicion:BAAALgAFFAEJAQAAAA==.Hauntfrost:BAAALgAECgEJAQAAAA==.Hazél:BAAALgADCgYJBgAAAA==.',
He='Helix:BAAALgAECgIJAgAAAA==.',
Hi='Hippoltyos:BAABLgAECn8sAAIGAAkJnA5GJACWAQloDAAABwA0AGkMAAAHACUAawwAAAYANgBqDAAABQAqAGwMAAAGABgAbQwAAAMADwDqDAAABgA2AG4MAAADACYAbwwAAAEADwAGAAkJnA5GJACWAQloDAAABwA0AGkMAAAHACUAawwAAAYANgBqDAAABQAqAGwMAAAGABgAbQwAAAMADwDqDAAABgA2AG4MAAADACYAbwwAAAEADwAAAA==.',
Ho='Honestlee:BAAALgAECgQJBAAAAA==.Honourablee:BAAALgAECgYJCQAAAA==.Hortzul:BAAALgADCgMJAwABLgAFFAUJGAABABkfAA==.Hotsaucce:BAAALgADCgEJAQAAAA==.Hotstheboss:BAAALgADCgYJBgAAAA==.Houe:BAAALgADCgUJCAAAAA==.',
Hu='Huffle:BAAALgAECgEJAQAAAA==.Huntardiness:BAABLgAECn8gAAQZAAgJrhHVIwB8AQhoDAAABQBXAGkMAAAGACwAawwAAAUAHABqDAAABAA6AGwMAAAEACwAbQwAAAIAPQDqDAAABQAfAG4MAAABABIAGQAICRYK1SMAfAEIaAwAAAIAGwBpDAAAAwAsAGsMAAACABcAagwAAAIALgBsDAAAAQAWAG0MAAABAA0A6gwAAAQAHwBuDAAAAQASAAwABwnlEktQAHgBB2gMAAADAFcAaQwAAAMAKwBrDAAAAwAcAGoMAAACADoAbAwAAAIALABtDAAAAQA9AOoMAAABABgAEAABCe4O/ToALgABbAwAAAEAJgAAAA==.Hunterd:BAAALgADCgEJAQAAAA==.',
Hy='Hymnals:BAACLgAFFH8LAAIFAAQJVCY3CAC+AQRoDAAAAwBjAGkMAAADAGIAawwAAAIAYQDqDAAAAwBhAAUABAlUJjcIAL4BBGgMAAADAGMAaQwAAAMAYgBrDAAAAgBhAOoMAAADAGEALgAECn8XAAMFAAgJUSTuDgDcAgAFAAgJUSTuDgDcAgAaAAIJBxrgTwCFAAAAAA==.',
Ia='Ianmaris:BAAALgADCgQJBQAAAA==.',
Ic='Icealia:BAAALgAECgEJAQABLgAFFAQJDwAbAL4HAA==.Icelandite:BAAALgAECgYJBgAAAA==.',
Iv='Ive:BAABLgAECn8fAAQRAAkJ/CF2EQDBAQloDAAABABgAGkMAAAEAEgAawwAAAQAUgBqDAAABABYAGwMAAADAGAAbQwAAAIATADqDAAABgBhAG4MAAADAGAAbwwAAAEATgARAAcJzBp2EQDBAQdoDAAAAwBZAGkMAAACADkAawwAAAEAKwBqDAAAAwBEAGwMAAABADYAbQwAAAIATADqDAAAAQBaAAoACAkYIv9XAJABCGgMAAABAGAAaQwAAAIASABrDAAAAgBJAGoMAAABAFgAbAwAAAEAYADqDAAABQBhAG4MAAADAGAAbwwAAAEATgAWAAIJHBD0JABeAAJrDAAAAQBSAGwMAAABAAAAAAA=.',
Ja='Jackburton:BAAALgAECgIJAgAAAA==.Jaddie:BAAALgAECggJEQAAAA==.Jarnunvosk:BAABLgAECn8iAAMcAAgJOhU4DQD3AQhoDAAABQAyAGkMAAAEADcAawwAAAQANQBqDAAABQAqAGwMAAAGAC8AbQwAAAMAMQDqDAAABQAzAG4MAAACAFQAHAAICToVOA0A9wEIaAwAAAUAMgBpDAAABAA3AGsMAAAEADUAagwAAAUAKgBsDAAABgAvAG0MAAADADEA6gwAAAUAMwBuDAAAAQBUAB0AAQlvA5KWACEAAW4MAAABAAgAAAA=.Jasmindinn:BAAALgADCgcJDgAAAA==.Jayber:BAABLgAECn8iAAMeAAcJSg7KLwBUAQdoDAAABwAxAGkMAAAIAB0AawwAAAYAJABqDAAABQA0AGwMAAAEACwA6gwAAAMAGQBuDAAAAQARAB4ABwlKDsovAFQBB2gMAAAHADEAaQwAAAcAHQBrDAAABgAkAGoMAAAFADQAbAwAAAQALADqDAAAAwAZAG4MAAABABEABwABCZkAMZUABwABaQwAAAEAAQAAAA==.',
Je='Jezadora:BAAALgADCgEJAQAAAA==.',
Jo='Jolkom:BAAALgAECgMJBgABLgAECggJFgAVAEAcAA==.',
Ju='Julantis:BAAALgAECgYJBgAAAA==.',
Ka='Kadri:BAAALgAFFAEJAQAAAA==.Kaffee:BAABLgAECn80AAISAAkJ7A93EgCWAQloDAAABwAtAGkMAAAHADMAawwAAAcAOQBqDAAABgA7AGwMAAAIACQAbQwAAAQAHgDqDAAACAAlAG4MAAAEADQAbwwAAAEADQASAAkJ7A93EgCWAQloDAAABwAtAGkMAAAHADMAawwAAAcAOQBqDAAABgA7AGwMAAAIACQAbQwAAAQAHgDqDAAACAAlAG4MAAAEADQAbwwAAAEADQAAAA==.Kamakaz:BAAALgAECgcJCQAAAA==.Kamasdruid:BAAALgAECgMJBQAAAA==.Kamasmage:BAAALgADCgcJBwAAAA==.Kamasmonk:BAAALgAECgYJBwAAAA==.Kamasux:BAAALgADCgYJBwAAAA==.Kandi:BAAALgADCgQJCgAAAA==.Kaviryon:BAAALgAECgEJAwAAAA==.Kaywhy:BAABLgAECn8UAAIHAAgJVxszNgA1AQhoDAAAAwBBAGkMAAACAEMAawwAAAIAQABqDAAAAgBBAGwMAAABAFQAbQwAAAIAPwDqDAAABQBdAG4MAAADADMABwAICVcbMzYANQEIaAwAAAMAQQBpDAAAAgBDAGsMAAACAEAAagwAAAIAQQBsDAAAAQBUAG0MAAACAD8A6gwAAAUAXQBuDAAAAwAzAAAA.',
Ki='Kichack:BAABLgAECn8rAAMIAAgJ4B9fDAB1AghoDAAABwBUAGkMAAAGAFYAawwAAAUATABqDAAABQBdAGwMAAAHAFUAbQwAAAMAPwDqDAAACABZAG4MAAACAFUACAAICeAfXwwAdQIIaAwAAAYAVABpDAAABQBWAGsMAAAEAEwAagwAAAMAXQBsDAAABQBVAG0MAAADAD8A6gwAAAYAWQBuDAAAAgBVAB8ABgkPFPY9AGEBBmgMAAABADAAaQwAAAEAOQBrDAAAAQAvAGoMAAACACwAbAwAAAIAQQDqDAAAAgAsAAAA.Kitarvie:BAAALgAECgEJAgAAAA==.',
Kj='Kjdh:BAABLgAECn8oAAITAAgJSCIQCQCOAghoDAAABQBdAGkMAAAEAF0AawwAAAQAWwBqDAAABABMAGwMAAAEAFEAbQwAAAIASQDqDAAACgBgAG4MAAAHAFQAEwAICUgiEAkAjgIIaAwAAAUAXQBpDAAABABdAGsMAAAEAFsAagwAAAQATABsDAAABABRAG0MAAACAEkA6gwAAAoAYABuDAAABwBUAAAA.',
Kl='Kladuum:BAAALgADCgYJGQAAAA==.',
Kn='Knuckles:BAABLgAECn8UAAIFAAgJLhaGIADnAQhoDAAAAgBFAGkMAAACADQAawwAAAMANQBqDAAAAwA6AGwMAAADAE8AbQwAAAIAIADqDAAABAA+AG4MAAABAC8ABQAICS4WhiAA5wEIaAwAAAIARQBpDAAAAgA0AGsMAAADADUAagwAAAMAOgBsDAAAAwBPAG0MAAACACAA6gwAAAQAPgBuDAAAAQAvAAAA.',
Ko='Kogun:BAAALgAECgQJBAAAAA==.Kowala:BAABLgAECn8cAAIgAAkJvw8EJgCRAQloDAAABQA9AGkMAAAEADkAawwAAAQAKABqDAAAAwAkAGwMAAADACIAbQwAAAEAEgDqDAAABQA0AG4MAAACACgAbwwAAAEAEAAgAAkJvw8EJgCRAQloDAAABQA9AGkMAAAEADkAawwAAAQAKABqDAAAAwAkAGwMAAADACIAbQwAAAEAEgDqDAAABQA0AG4MAAACACgAbwwAAAEAEAAAAA==.Kowpox:BAAALgADCgkJCgAAAA==.Kozalth:BAAALgADCgEJAgAAAA==.',
Kr='Krabi:BAAALgADCgYJCwAAAA==.Kranks:BAAALgAECgEJAQAAAA==.Kreios:BAAALgAECgYJBwAAAA==.Krelo:BAABLgAECn8kAAIYAAgJ6x1zEwCmAghoDAAABgBEAGkMAAAFAD0AawwAAAQAUABqDAAABABIAGwMAAAGAFIAbQwAAAMATADqDAAABwBWAG4MAAABAFQAGAAICesdcxMApgIIaAwAAAYARABpDAAABQA9AGsMAAAEAFAAagwAAAQASABsDAAABgBSAG0MAAADAEwA6gwAAAcAVgBuDAAAAQBUAAAA.',
Kt='Ktom:BAABLgAECn8zAAILAAkJGiW9AgBDAwloDAAABwBgAGkMAAAHAF8AawwAAAYAYABqDAAABgBiAGwMAAAFAGIAbQwAAAMAXwDqDAAACQBgAG4MAAAFAFwAbwwAAAMAWQALAAkJGiW9AgBDAwloDAAABwBgAGkMAAAHAF8AawwAAAYAYABqDAAABgBiAGwMAAAFAGIAbQwAAAMAXwDqDAAACQBgAG4MAAAFAFwAbwwAAAMAWQAAAA==.',
Ku='Kurimbory:BAAALgAECgUJBQAAAA==.',
Ky='Kyruan:BAAALgADCgEJAQAAAA==.',
['Ký']='Kýlê:BAABLgAECn8ZAAMMAAgJmwdIUgByAQhoDAAABQAmAGkMAAAEABYAawwAAAQAGwBqDAAABAASAGwMAAAEABAAbQwAAAEACQDqDAAAAgARAG4MAAABAAQADAAICZsHSFIAcgEIaAwAAAIAJgBpDAAAAgAWAGsMAAACABsAagwAAAIAEgBsDAAAAgAQAG0MAAABAAkA6gwAAAEAEQBuDAAAAQAEABAABgnqAstZAN0ABmgMAAADAAUAaQwAAAIABgBrDAAAAgALAGoMAAACABEAbAwAAAIACADqDAAAAQAEAAAA.',
La='Lancelot:BAAALgAECgYJCAAAAA==.Lanthuil:BAAALgAECgQJBAAAAA==.',
Li='Lifepooll:BAAALgAECgEJAQABLgAFFAIJAQANAAAAAA==.Lilyselah:BAAALgADCgYJBwAAAA==.Littlelocky:BAAALgADCgcJEwAAAA==.Liv:BAABLgAECn8UAAIHAAgJtQu6LgBsAQhoDAAAAwAbAGkMAAADABsAawwAAAMAFQBqDAAAAgAYAGwMAAABACQA6gwAAAUAIABuDAAAAgAVAG8MAAABACoABwAICbULui4AbAEIaAwAAAMAGwBpDAAAAwAbAGsMAAADABUAagwAAAIAGABsDAAAAQAkAOoMAAAFACAAbgwAAAIAFQBvDAAAAQAqAAAA.',
Ll='Llamallab:BAAALgADCgcJBwAAAA==.',
Lo='Lostmyghoul:BAACLgAFFH8GAAICAAMJTBmlewAAAQNoDAAAAgBhAGkMAAABACgA6gwAAAMAOAACAAMJTBmlewAAAQNoDAAAAgBhAGkMAAABACgA6gwAAAMAOAAuAAQKfycAAgIACQkoH8IUAMQCAAIACQkoH8IUAMQCAAAA.Lostwarrior:BAAALgAECgUJBQAAAA==.Louhi:BAAALgAECgIJAwABLgAECgMJCAANAAAAAA==.',
Lu='Luglug:BAAALgAECgEJAQAAAA==.Lunar:BAABLgAECn8kAAIgAAkJkR8cBwDdAgloDAAABABNAGkMAAAEAFMAawwAAAQAUQBqDAAABQBCAGwMAAAEAFgAbQwAAAQATwDqDAAABQBaAG4MAAAEAEkAbwwAAAIASAAgAAkJkR8cBwDdAgloDAAABABNAGkMAAAEAFMAawwAAAQAUQBqDAAABQBCAGwMAAAEAFgAbQwAAAQATwDqDAAABQBaAG4MAAAEAEkAbwwAAAIASAAAAA==.Lunasea:BAAALgAECgMJAwAAAA==.',
Ly='Lysol:BAAALgADCgUJBQAAAA==.Lystat:BAAALgAECgUJCwAAAA==.',
Ma='Magicfungus:BAAALgADCgUJCQAAAA==.Magno:BAAALgADCgIJAgAAAA==.Magra:BAABLgAECn8YAAIOAAYJnwydvgAIAQZoDAAABQAnAGkMAAAFAC8AawwAAAQAGQBqDAAABAAcAGwMAAADABEA6gwAAAMAHwAOAAYJnwydvgAIAQZoDAAABQAnAGkMAAAFAC8AawwAAAQAGQBqDAAABAAcAGwMAAADABEA6gwAAAMAHwAAAA==.Magêyalook:BAABLgAECn8nAAIOAAgJthmbPAAiAghoDAAABwBMAGkMAAAGAFEAawwAAAYATwBqDAAABABJAGwMAAAEAFIAbQwAAAIALQDqDAAABwBBAG4MAAADABwADgAICbYZmzwAIgIIaAwAAAcATABpDAAABgBRAGsMAAAGAE8AagwAAAQASQBsDAAABABSAG0MAAACAC0A6gwAAAcAQQBuDAAAAwAcAAAA.Mangel:BAAALgADCgYJBgAAAA==.Manzz:BAAALgAECgUJCgAAAA==.Marcelline:BAAALgADCgYJEgAAAA==.Mattob:BAAALgADCgcJDAAAAA==.Maximus:BAAALgADCgkJEAAAAA==.Maznificent:BAAALgADCggJDQAAAA==.Mazyme:BAAALgADCgQJCQAAAA==.',
Me='Meandmypal:BAACLgAFFH8UAAIZAAgJzBknAQBSAghoDAAABgBXAGkMAAADAEoAawwAAAUAXwBqDAAAAQBQAGwMAAABACMAbQwAAAEARQDqDAAAAgBaAG4MAAABAAkAGQAICcwZJwEAUgIIaAwAAAYAVwBpDAAAAwBKAGsMAAAFAF8AagwAAAEAUABsDAAAAQAjAG0MAAABAEUA6gwAAAIAWgBuDAAAAQAJAC4ABAp/LgACGQAJCTgmuwAAfgMAGQAJCTgmuwAAfgMAAAA=.Mello:BAABLgAECn8uAAIaAAkJIBzLBQCeAgloDAAABwBaAGkMAAAGAFYAawwAAAQAQQBqDAAABQBVAGwMAAAHAEgAbQwAAAQAUADqDAAACABRAG4MAAAEADsAbwwAAAEAJwAaAAkJIBzLBQCeAgloDAAABwBaAGkMAAAGAFYAawwAAAQAQQBqDAAABQBVAGwMAAAHAEgAbQwAAAQAUADqDAAACABRAG4MAAAEADsAbwwAAAEAJwAAAA==.Mesteris:BAAALgADCgYJBgAAAA==.',
Mi='Midiane:BAAALgAECgEJAQAAAA==.Milim:BAAALgAFFAIJAgAAAA==.Mirba:BAABLgAECn8nAAIMAAgJZxT7QgDPAQhoDAAABwA1AGkMAAAGAC4AawwAAAUAMQBqDAAABQAzAGwMAAAGACoAbQwAAAIARwDqDAAABwAlAG4MAAABAEAADAAICWcU+0IAzwEIaAwAAAcANQBpDAAABgAuAGsMAAAFADEAagwAAAUAMwBsDAAABgAqAG0MAAACAEcA6gwAAAcAJQBuDAAAAQBAAAAA.',
Mo='Mongo:BAABLgAECn8wAAICAAkJ/R+MDwDpAgloDAAACABdAGkMAAAHAFgAawwAAAcAVwBqDAAABgBVAGwMAAAFAFoAbQwAAAMAUADqDAAABwBRAG4MAAADAFIAbwwAAAIAMwACAAkJ/R+MDwDpAgloDAAACABdAGkMAAAHAFgAawwAAAcAVwBqDAAABgBVAGwMAAAFAFoAbQwAAAMAUADqDAAABwBRAG4MAAADAFIAbwwAAAIAMwAAAA==.Monochrome:BAAALgAECgIJAgAAAA==.Monsterdeath:BAAALgAECgIJAgAAAA==.Moreicepls:BAABLgAECn8bAAIOAAgJ+wn0jgBVAQhoDAAABQAvAGkMAAAFABsAawwAAAMAHgBqDAAABAAbAGwMAAADABkAbQwAAAEADADqDAAABAAcAG4MAAACAAcADgAICfsJ9I4AVQEIaAwAAAUALwBpDAAABQAbAGsMAAADAB4AagwAAAQAGwBsDAAAAwAZAG0MAAABAAwA6gwAAAQAHABuDAAAAgAHAAAA.Morené:BAAALgAECgQJBgAAAA==.Moxxee:BAAALgADCgcJGAAAAA==.',
Mu='Mushhmelu:BAAALgAECgEJAQAAAA==.',
My='Myiko:BAAALgAECgQJBAAAAA==.Mytharu:BAAALgADCgMJAwAAAA==.',
Na='Nareík:BAACLgAFFH8KAAIDAAQJBQaRVgDaAARoDAAAAwATAGkMAAACAAkAawwAAAMACADqDAAAAgAXAAMABAkFBpFWANoABGgMAAADABMAaQwAAAIACQBrDAAAAwAIAOoMAAACABcALgAECn8gAAIDAAgJWRJoVQCjAQADAAgJWRJoVQCjAQAAAA==.',
Ne='Neutrallee:BAAALgAECgEJAQAAAA==.Newa:BAAALgAECgUJCQAAAA==.',
Ni='Nightwater:BAACLgAFFH8PAAIbAAQJvgetNgDQAARoDAAABgAaAGkMAAAFABAAawwAAAEABgDqDAAAAwAdABsABAm+B602ANAABGgMAAAGABoAaQwAAAUAEABrDAAAAQAGAOoMAAADAB0ALgAECn8pAAQbAAkJixfyJQAWAgAbAAkJixfyJQAWAgAhAAIJXwmvPABYAAAgAAEJigiZjAAsAAAAAA==.',
['Né']='Nébulien:BAABLgAECn8dAAIiAAgJNx4BCgAQAghoDAAABQBTAGkMAAAFAFUAawwAAAQAWgBqDAAAAwAvAGwMAAACAEYAbQwAAAEAKgDqDAAABwBXAG4MAAACAFMAIgAICTceAQoAEAIIaAwAAAUAUwBpDAAABQBVAGsMAAAEAFoAagwAAAMALwBsDAAAAgBGAG0MAAABACoA6gwAAAcAVwBuDAAAAgBTAAAA.',
Ok='Okkok:BAABLgAECn8XAAIOAAYJ8hCIwABjAQZoDAAABgA2AGkMAAAFACcAawwAAAQANwBqDAAABAAaAGwMAAACACAA6gwAAAIAIgAOAAYJ8hCIwABjAQZoDAAABgA2AGkMAAAFACcAawwAAAQANwBqDAAABAAaAGwMAAACACAA6gwAAAIAIgAAAA==.',
Or='Orchop:BAABLgAECn8YAAIiAAYJgQmYHwDsAAZoDAAAAwAcAGkMAAAFABIAawwAAAMAFgBqDAAAAgAPAGwMAAAFACAA6gwAAAYAEwAiAAYJgQmYHwDsAAZoDAAAAwAcAGkMAAAFABIAawwAAAMAFgBqDAAAAgAPAGwMAAAFACAA6gwAAAYAEwAAAA==.Orkrist:BAABLgAECn8XAAIMAAcJpRLIYwByAQdoDAAABAA9AGkMAAAEADQAawwAAAUAMwBqDAAAAgAnAGwMAAACACEAbQwAAAEAJQDqDAAABQAyAAwABwmlEshjAHIBB2gMAAAEAD0AaQwAAAQANABrDAAABQAzAGoMAAACACcAbAwAAAIAIQBtDAAAAQAlAOoMAAAFADIAAAA=.',
Oz='Oz:BAAALgADCgUJBQAAAA==.',
Pa='Paado:BAAALgADCgUJBQAAAA==.Pantryraider:BAAALgAECgkJAgAAAA==.Patriqt:BAAALgAECgEJAQAAAA==.Paulterian:BAAALgAECgYJBQAAAA==.Paymeforpi:BAAALgAECgMJAwAAAA==.',
Ph='Phelaeshio:BAABLgAECn8eAAICAAkJOxxUJABtAgloDAAABQBaAGkMAAAEAFoAawwAAAUARQBqDAAABABWAGwMAAADAEQAbQwAAAMASgDqDAAAAwBBAG4MAAACADcAbwwAAAEAPwACAAkJOxxUJABtAgloDAAABQBaAGkMAAAEAFoAawwAAAUARQBqDAAABABWAGwMAAADAEQAbQwAAAMASgDqDAAAAwBBAG4MAAACADcAbwwAAAEAPwAAAA==.',
Po='Poam:BAAALgAECgUJBQAAAA==.Poldalina:BAAALgADCgcJGAAAAA==.Power:BAABLgAECn8UAAICAAcJQQrtnQAnAQdoDAAABAAaAGkMAAAEABkAawwAAAQAFQBqDAAAAQAVAGwMAAABAAcAbQwAAAEAIQDqDAAABQArAAIABwlBCu2dACcBB2gMAAAEABoAaQwAAAQAGQBrDAAABAAVAGoMAAABABUAbAwAAAEABwBtDAAAAQAhAOoMAAAFACsAAAA=.',
Pr='Primevil:BAAALgADCgQJBAAAAA==.Prosthetic:BAAALgAECgEJAQAAAA==.Proverbs:BAAALgAFFAEJAQAAAA==.',
Pu='Pumplord:BAAALgAECgcJEQAAAA==.Punchyou:BAAALgADCgEJAQAAAA==.',
['På']='Pårts:BAAALgAFFAIJAQAAAA==.',
['Pù']='Pùff:BAAALgAECgUJCQAAAA==.',
Qu='Quazeemoto:BAAALgAECgEJAQAAAA==.',
Ra='Raeyna:BAAALgAECgIJAwABLgAECgkJHwARAPwhAA==.Raffern:BAAALgAECgMJAwAAAA==.Rainknuckles:BAABLgAECn8lAAIBAAgJVRaAJADZAQhoDAAABwBQAGkMAAAGAFsAawwAAAUANQBqDAAABQA2AGwMAAAFADEAbQwAAAIAGgDqDAAABQBBAG4MAAACACQAAQAICVUWgCQA2QEIaAwAAAcAUABpDAAABgBbAGsMAAAFADUAagwAAAUANgBsDAAABQAxAG0MAAACABoA6gwAAAUAQQBuDAAAAgAkAAAA.Rayshano:BAABLgAECn8WAAISAAcJBRr8EQCbAQdoDAAAAwBLAGkMAAADAEYAawwAAAIAQABqDAAAAgAtAGwMAAACAD0A6gwAAAkARQBuDAAAAQA6ABIABwkFGvwRAJsBB2gMAAADAEsAaQwAAAMARgBrDAAAAgBAAGoMAAACAC0AbAwAAAIAPQDqDAAACQBFAG4MAAABADoAAAA=.',
Re='Recklessone:BAAALgAECgEJAQAAAA==.Resia:BAAALgADCgQJAQAAAA==.Revocsid:BAAALgADCgcJEwAAAA==.Rezza:BAAALgADCgEJAQAAAA==.',
Ri='Rikka:BAAALgADCgMJAwAAAA==.',
Ro='Rottingtree:BAAALgAECgYJEAAAAA==.',
Ru='Rustynails:BAABLgAECn84AAIjAAkJGSS6AAAjAwloDAAACABjAGkMAAAHAGIAawwAAAgAXwBqDAAABwBhAGwMAAAHAF0AbQwAAAUAYQDqDAAABgBYAG4MAAAFAF8AbwwAAAMARwAjAAkJGSS6AAAjAwloDAAACABjAGkMAAAHAGIAawwAAAgAXwBqDAAABwBhAGwMAAAHAF0AbQwAAAUAYQDqDAAABgBYAG4MAAAFAF8AbwwAAAMARwAAAA==.',
Sa='Saffire:BAAALgADCgcJBwAAAA==.Salina:BAAALgAECgEJAQAAAA==.Saly:BAAALgADCgIJAQABLgADCggJDgANAAAAAA==.Samwitch:BAAALgAECgQJCwAAAA==.Sappaho:BAAALgADCgYJBwAAAA==.Satheirel:BAAALgADCgYJBwAAAA==.Savanti:BAAALgAECgEJAQAAAA==.Sazzul:BAAALgAECggJEgAAAA==.',
Sc='Scott:BAACLgAFFH8VAAIVAAQJvCM+AwBiAQRoDAAABgBTAGkMAAAFAFkAawwAAAUAYQDqDAAABQBfABUABAm8Iz4DAGIBBGgMAAAGAFMAaQwAAAUAWQBrDAAABQBhAOoMAAAFAF8ALgAECn8jAAIVAAgJlyTUAwATAwAVAAgJlyTUAwATAwABLgAFFAUJCwAkAM8QAA==.Screamor:BAAALgAECgEJAQAAAA==.Screams:BAAALgADCgEJAQAAAA==.Screamz:BAABLgAECn8eAAITAAYJ6RjAIwBJAQZoDAAABgBJAGkMAAAGAEMAawwAAAYAMQBqDAAAAwBHAGwMAAACAEQA6gwAAAcAOgATAAYJ6RjAIwBJAQZoDAAABgBJAGkMAAAGAEMAawwAAAYAMQBqDAAAAwBHAGwMAAACAEQA6gwAAAcAOgAAAA==.Scynx:BAAALgAECggJEQAAAA==.',
Se='Seaka:BAABLgAECn8vAAQgAAkJ8RdMEgA7AgloDAAABwBEAGkMAAAFAEgAawwAAAYAVABqDAAACAA7AGwMAAAGACoAbQwAAAQALADqDAAACABRAG4MAAACAC4AbwwAAAEAMQAgAAkJ8RdMEgA7AgloDAAABABEAGkMAAADAEgAawwAAAMAVABqDAAABAA7AGwMAAAEACoAbQwAAAIALADqDAAAAwBRAG4MAAABAC4AbwwAAAEAMQAbAAcJYRYBPgCSAQdoDAAAAwA9AGkMAAACADYAawwAAAMARQBqDAAABAAyAGwMAAACAD8AbQwAAAIAJADqDAAABABBACUAAgnGDhBVAFUAAuoMAAABACYAbgwAAAEAJAAAAA==.Sebas:BAAALgAECgEJAQAAAA==.Sent:BAAALgADCggJDgAAAA==.Serion:BAAALgAECgQJBQABLgAFFAEJAQANAAAAAA==.Sernix:BAABLgAECn8nAAIYAAgJKxz0FACYAghoDAAABgBJAGkMAAAFAE0AawwAAAYAUQBqDAAABABdAGwMAAAGAE4AbQwAAAQAIgDqDAAABQBTAG4MAAADADUAGAAICSsc9BQAmAIIaAwAAAYASQBpDAAABQBNAGsMAAAGAFEAagwAAAQAXQBsDAAABgBOAG0MAAAEACIA6gwAAAUAUwBuDAAAAwA1AAAA.',
Sh='Shadegrim:BAAALgAECgQJBgAAAA==.Shaeia:BAACLgAFFH8IAAILAAMJzxCEEQDcAANoDAAAAwBQAGkMAAACAB8A6gwAAAMAEQALAAMJzxCEEQDcAANoDAAAAwBQAGkMAAACAB8A6gwAAAMAEQAuAAQKfx8AAgsACQn0HLcNAMYCAAsACQn0HLcNAMYCAAAA.Shambat:BAAALgADCgYJBgAAAA==.Shangi:BAAALgADCgMJAgABLgAFFAQJEQASACIhAA==.Shekinah:BAAALgADCgEJAQAAAA==.Shen:BAAALgAECgQJBgAAAA==.',
Si='Siatrath:BAAALgAECgEJAQABLgAFFAQJEQASACIhAA==.Sivtekeda:BAAALgAECgQJCQAAAA==.',
Sk='Sktibrew:BAACLgAFFH8TAAIJAAYJgSF1BACRAQZoDAAABQBbAGkMAAAEAF4AawwAAAMAUgBqDAAAAQBPAGwMAAABAEsA6gwAAAUAVAAJAAYJgSF1BACRAQZoDAAABQBbAGkMAAAEAF4AawwAAAMAUgBqDAAAAQBPAGwMAAABAEsA6gwAAAUAVAAuAAQKfxoAAgkACAmDHRMRAI8CAAkACAmDHRMRAI8CAAAA.',
Sl='Slamin:BAAALgADCggJDwAAAA==.Slash:BAABLgAECn8kAAITAAkJxRe9EgD0AQloDAAABQBHAGkMAAAGAEoAawwAAAYASQBqDAAABQBMAGwMAAAEADoAbQwAAAMAQwDqDAAABQBIAG4MAAABABcAbwwAAAEALQATAAkJxRe9EgD0AQloDAAABQBHAGkMAAAGAEoAawwAAAYASQBqDAAABQBMAGwMAAAEADoAbQwAAAMAQwDqDAAABQBIAG4MAAABABcAbwwAAAEALQAAAA==.Slyavane:BAABLgAECn84AAQWAAkJqBVYBgAKAgloDAAABwBIAGkMAAAIADwAawwAAAgASQBqDAAABwAgAGwMAAAGABoAbQwAAAMANQDqDAAACAAlAG4MAAAGADgAbwwAAAMAPgAWAAkJqBVYBgAKAgloDAAABABIAGkMAAAEADwAawwAAAQASQBqDAAABAAgAGwMAAADABoAbQwAAAMANQDqDAAABAAlAG4MAAAEADgAbwwAAAMAPgARAAcJawd/GgDGAAdoDAAAAQAbAGkMAAACABMAawwAAAIAFABqDAAAAwATAGwMAAADAA0A6gwAAAMAEwBuDAAAAgAMAAoABAlbBAThAJgABGgMAAACABIAaQwAAAIABABrDAAAAgAPAOoMAAABAAYAAAA=.Slyice:BAAALgAECgEJBgAAAA==.',
Sm='Smokess:BAACLgAFFH8NAAMSAAUJtRnvBAAzAQVoDAAABABKAGkMAAAEAEkAawwAAAEANQBqDAAAAQBXAOoMAAADAD0AEgAFCbUZ7wQAMwEFaAwAAAEASgBpDAAAAQBJAGsMAAABADUAagwAAAEAVwDqDAAAAQA9AAQAAwkPFCIWAPsAA2gMAAADAEAAaQwAAAMAPwDqDAAAAgAZAC4ABAp/HwADEgAICeQhiwYAcgIAEgAICcodiwYAcgIABAAICUAZlkoAAwIAAS4ABRQGCQkAFQB1CgA=.',
Sn='Snowwind:BAABLgAECn8fAAIGAAgJfQqZMQA4AQhoDAAABQAlAGkMAAAFABkAawwAAAUAHwBqDAAABAAeAGwMAAADAC4AbQwAAAIADgDqDAAABgARAG4MAAABAAwABgAICX0KmTEAOAEIaAwAAAUAJQBpDAAABQAZAGsMAAAFAB8AagwAAAQAHgBsDAAAAwAuAG0MAAACAA4A6gwAAAYAEQBuDAAAAQAMAAAA.',
So='Solthea:BAAALgAECgkJBwAAAA==.Solymar:BAAALgAECgkJBwAAAA==.Sonar:BAABLgAECn8pAAIMAAkJ8h+eFwCPAgloDAAABgBiAGkMAAAFAFEAawwAAAUANgBqDAAABQBaAGwMAAAFAFcAbQwAAAMAYQDqDAAABgBhAG4MAAAEAEYAbwwAAAIAQwAMAAkJ8h+eFwCPAgloDAAABgBiAGkMAAAFAFEAawwAAAUANgBqDAAABQBaAGwMAAAFAFcAbQwAAAMAYQDqDAAABgBhAG4MAAAEAEYAbwwAAAIAQwAAAA==.Sonasai:BAAALgADCgcJGAAAAA==.Sonnybear:BAAALgADCgUJEQAAAA==.Soulhatcher:BAAALgAECgQJEAAAAA==.Soxs:BAABLgAECn8qAAMfAAkJNBoFDwChAgloDAAABgBEAGkMAAAGAEUAawwAAAYAQABqDAAABgA3AGwMAAAFAEIAbQwAAAMARwDqDAAABQBMAG4MAAAEAEcAbwwAAAEAOgAfAAkJNBoFDwChAgloDAAABgBEAGkMAAAGAEUAawwAAAUAQABqDAAABgA3AGwMAAAFAEIAbQwAAAMARwDqDAAABQBMAG4MAAADAEcAbwwAAAEAOgAIAAIJTg+NbgBnAAJrDAAAAQAZAG4MAAABADQAAAA=.',
Sp='Spookymoo:BAAALgADCgQJBAAAAA==.',
St='Stabbywabby:BAAALgAECgYJBwAAAA==.Stardris:BAABLgAECn8bAAIDAAgJawKIqAC/AAhoDAAABQAEAGkMAAAEAAgAawwAAAQABgBqDAAABAAJAGwMAAAEAAgAbQwAAAEAAwDqDAAAAwAEAG4MAAACAAcAAwAICWsCiKgAvwAIaAwAAAUABABpDAAABAAIAGsMAAAEAAYAagwAAAQACQBsDAAABAAIAG0MAAABAAMA6gwAAAMABABuDAAAAgAHAAAA.Stenaris:BAAALgAECgIJAwAAAA==.Stompygnome:BAAALgAECggJEgAAAA==.Strooth:BAAALgADCgQJBAAAAA==.',
Ta='Talavel:BAAALgADCgIJAgAAAA==.Tartanus:BAABLgAECn8tAAIDAAkJXxd1LAAMAgloDAAABgBQAGkMAAAGAEMAawwAAAYASwBqDAAABQApAGwMAAAFADYAbQwAAAQAKwDqDAAACAAuAG4MAAAEAD8AbwwAAAEALwADAAkJXxd1LAAMAgloDAAABgBQAGkMAAAGAEMAawwAAAYASwBqDAAABQApAGwMAAAFADYAbQwAAAQAKwDqDAAACAAuAG4MAAAEAD8AbwwAAAEALwAAAA==.Taulogit:BAAALgAECgIJAgAAAA==.Tayzetv:BAAALgAECgMJAwABLgAFFAMJBwAiAGcOAA==.',
Te='Teramiah:BAAALgADCgcJFAAAAA==.',
Th='Thanestra:BAAALgAECgkJBwAAAA==.Theadona:BAABLgAECn8nAAIEAAgJNR2mKgBNAghoDAAABwBGAGkMAAAGAFAAawwAAAYARgBqDAAABAA2AGwMAAAFADkAbQwAAAQAWgDqDAAABABVAG4MAAADAEQABAAICTUdpioATQIIaAwAAAcARgBpDAAABgBQAGsMAAAGAEYAagwAAAQANgBsDAAABQA5AG0MAAAEAFoA6gwAAAQAVQBuDAAAAwBEAAAA.Thorall:BAAALgADCgkJDwAAAA==.Thylight:BAAALgADCgMJAwAAAA==.',
Ti='Tikcus:BAAALgADCgcJEAAAAA==.Tils:BAAALgADCggJDwAAAA==.Tippy:BAACLgAFFH8aAAMPAAUJAh2GBwBaAQVoDAAABwBZAGkMAAAHAFgAawwAAAQALABqDAAAAQA9AOoMAAAHAEoADwAECQIdhgcAWgEEaAwAAAcAWQBpDAAABwBYAGsMAAAEACwA6gwAAAYASgAkAAIJuQE1QAAgAAJqDAAAAQA9AOoMAAABAAQALgAECn82AAQPAAkJaCHfAgC/AgAPAAkJECHfAgC/AgACAAMJDQbJAwFwAAAkAAIJdQ6kRwBkAAAAAA==.',
To='Toastedwings:BAAALgADCgcJDwAAAA==.Tombstone:BAAALgAECgYJEgAAAA==.Toowongfoo:BAACLgAFFH8ZAAIIAAUJuh9DCgBtAQVoDAAACABdAGkMAAAGAFsAawwAAAUATwBqDAAAAgA3AOoMAAAEADwACAAFCbofQwoAbQEFaAwAAAgAXQBpDAAABgBbAGsMAAAFAE8AagwAAAIANwDqDAAABAA8AC4ABAp/JwACCAAJCbgjWwMAJwMACAAJCbgjWwMAJwMAAAA=.',
Tr='Trewer:BAAALgADCgIJAgAAAA==.Trisara:BAABLgAECn81AAIgAAkJrwixMgBDAQloDAAABwAjAGkMAAAHABMAawwAAAcAEQBqDAAABgASAGwMAAAHAA8AbQwAAAUADQDqDAAACQAeAG4MAAAEABwAbwwAAAEAEQAgAAkJrwixMgBDAQloDAAABwAjAGkMAAAHABMAawwAAAcAEQBqDAAABgASAGwMAAAHAA8AbQwAAAUADQDqDAAACQAeAG4MAAAEABwAbwwAAAEAEQAAAA==.',
Tu='Tunechi:BAAALgAECgEJAQAAAA==.',
Ty='Tygrana:BAAALgAECgEJAQAAAA==.Tyradora:BAAALgAECgEJAQAAAA==.Tytannia:BAAALgADCgEJAQAAAA==.',
['Tö']='Töteman:BAABLgAECn8pAAILAAcJlBYgKgCUAQdoDAAACABDAGkMAAAIAE4AawwAAAgARwBqDAAABgBSAGwMAAAFADIAbQwAAAEACwDqDAAABQBEAAsABwmUFiAqAJQBB2gMAAAIAEMAaQwAAAgATgBrDAAACABHAGoMAAAGAFIAbAwAAAUAMgBtDAAAAQALAOoMAAAFAEQAAAA=.',
['Tÿ']='Tÿtann:BAAALgAECgMJAwAAAA==.',
Um='Umbranecros:BAAALgAECgEJBQAAAA==.',
Un='Unbok:BAAALgAECgkJAQAAAA==.Underdog:BAABLgAECn8fAAMQAAgJuBQLDgBwAQhoDAAABwA0AGkMAAAFAEEAawwAAAYASgBqDAAABABEAGwMAAADAEcAbQwAAAEABgDqDAAAAwA5AG4MAAACACsAEAAICbgUCw4AcAEIaAwAAAcANABpDAAABQBBAGsMAAAGAEoAagwAAAMAKgBsDAAAAwBHAG0MAAABAAYA6gwAAAMAOQBuDAAAAgArAAwAAQkAAAAAAAAAAWoMAAABAEQAAAA=.',
Up='Upthere:BAAALgADCgQJBAABLgAECgcJEwANAAAAAA==.',
Va='Vaern:BAABLgAECn8dAAIhAAcJhBzYDADbAQdoDAAABgBTAGkMAAAFAFgAawwAAAQATwBqDAAABABbAGwMAAAEAEcAbQwAAAEALQDqDAAABQBGACEABwmEHNgMANsBB2gMAAAGAFMAaQwAAAUAWABrDAAABABPAGoMAAAEAFsAbAwAAAQARwBtDAAAAQAtAOoMAAAFAEYAAAA=.Vagindivin:BAAALgAECgcJDwAAAA==.Valrie:BAAALgAECgMJAwAAAA==.Valyteil:BAAALgAECgQJBAAAAA==.',
Ve='Venngance:BAABLgAECn8rAAQPAAgJnCO2AwCYAghoDAAABwBhAGkMAAAGAFsAawwAAAUAUQBqDAAABQBeAGwMAAAHAGEAbQwAAAMAYADqDAAACABhAG4MAAACAE0ADwAICU4gtgMAmAIIaAwAAAQAUwBpDAAAAwBMAGsMAAACADkAagwAAAMAXgBsDAAABQBeAG0MAAADAGAA6gwAAAUAXQBuDAAAAgBNACQABQlNJNUXAJ0BBWgMAAACAGEAaQwAAAIAWwBrDAAAAQBRAGwMAAABAGEA6gwAAAIAYQACAAYJExSnqAAXAQZoDAAAAQA/AGkMAAABACwAawwAAAIAJgBqDAAAAgBaAGwMAAABAEEA6gwAAAEALAAAAA==.',
Vi='Virus:BAAALgAECggJEQAAAA==.Vitner:BAAALgADCgMJAwAAAA==.',
Vo='Voidkity:BAAALgAECgQJBwAAAA==.Voidpriest:BAAALgAECgEJAQAAAA==.',
Vy='Vyrlet:BAAALgAECgEJAQAAAA==.',
Wa='Walberson:BAAALgADCgYJBgAAAA==.Warfield:BAABLgAECn8fAAMlAAkJYxN5EgC4AQloDAAABQA6AGkMAAAFAFEAawwAAAMAJgBqDAAAAwA7AGwMAAAEADoAbQwAAAMAHgDqDAAABQA/AG4MAAACAC0AbwwAAAEAEwAlAAkJYxN5EgC4AQloDAAABQA6AGkMAAAFAFEAawwAAAMAJgBqDAAAAwA7AGwMAAAEADoAbQwAAAMAHgDqDAAABAA/AG4MAAACAC0AbwwAAAEAEwAhAAEJWgNXWwAcAAHqDAAAAQAIAAAA.',
Wf='Wfbot:BAAALgAECgEJAQAAAA==.',
Wh='Whosbondt:BAAALgAECgYJCQAAAA==.',
Wi='Winafred:BAAALgAECgEJAQAAAA==.Wittwicky:BAAALgAECgEJAQAAAA==.',
Wk='Wkeyonly:BAABLgAECn8fAAIDAAkJYRV8XABoAQloDAAABQBTAGkMAAAEACUAawwAAAQAPABqDAAAAwArAGwMAAADAD0AbQwAAAIAQwDqDAAABgA2AG4MAAACAB8AbwwAAAIAKAADAAkJYRV8XABoAQloDAAABQBTAGkMAAAEACUAawwAAAQAPABqDAAAAwArAGwMAAADAD0AbQwAAAIAQwDqDAAABgA2AG4MAAACAB8AbwwAAAIAKAAAAA==.',
Wo='Woody:BAAALgADCgUJBQAAAA==.Wooter:BAAALgADCgYJDAAAAA==.Worthy:BAAALgAECgkJAwAAAA==.',
Wr='Wrathsome:BAABLgAECn8rAAIbAAgJVxX9KgD3AQhoDAAABwBAAGkMAAAGAEIAawwAAAUAKgBqDAAABQA5AGwMAAAHADQAbQwAAAMAKgDqDAAACAAxAG4MAAACAD4AGwAICVcV/SoA9wEIaAwAAAcAQABpDAAABgBCAGsMAAAFACoAagwAAAUAOQBsDAAABwA0AG0MAAADACoA6gwAAAgAMQBuDAAAAgA+AAAA.',
Wu='Wunderbilly:BAAALgADCgEJAQAAAA==.',
['Wí']='Wísp:BAAALgAECgEJAQAAAA==.',
Xl='Xloon:BAAALgAECgEJAQAAAA==.',
Xy='Xypherus:BAAALgADCgkJDQAAAA==.',
['Xá']='Xándarl:BAAALgAECgMJBAAAAA==.',
Ya='Yakoda:BAAALgADCgUJBQAAAA==.Yaldabaoth:BAEALgAECgcJBQABLgAECgkJEAANAAAAAA==.Yanza:BAAALgAECgIJAgAAAA==.',
Ye='Yello:BAAALgADCgkJEgAAAA==.',
Za='Zaio:BAAALgAECgYJCQAAAA==.Zarkus:BAAALgAECgQJEgAAAA==.',
Ze='Zelphi:BAAALgAECgQJCAAAAA==.Zenha:BAAALgADCgEJAQAAAA==.Zephaadella:BAAALgAECgEJAQAAAA==.',
Zh='Zhuzi:BAAALgADCgkJDwAAAA==.',
Zs='Zshmokez:BAACLgAFFH8JAAIVAAYJdQooEwD/AAZoDAAAAQAZAGkMAAABABIAawwAAAEAEABqDAAAAQA5AGwMAAABAAwA6gwAAAQAPAAVAAYJdQooEwD/AAZoDAAAAQAZAGkMAAABABIAawwAAAEAEABqDAAAAQA5AGwMAAABAAwA6gwAAAQAPAAuAAQKfxoAAhUACQlFHiIGAKQCABUACQlFHiIGAKQCAAAA.',
['Åy']='Åylå:BAAALgAECgEJAQAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
