local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Warrior-Fury','Warrior-Protection','Paladin-Protection','Warlock-Affliction','Priest-Discipline','Priest-Shadow','Priest-Holy','Paladin-Retribution','DeathKnight-Unholy','DeathKnight-Frost','DemonHunter-Havoc','Hunter-BeastMastery','Mage-Frost','DeathKnight-Blood','Unknown-Unknown','Druid-Restoration','DemonHunter-Devourer','Warlock-Demonology','Warlock-Destruction','Mage-Fire','Shaman-Elemental','Evoker-Augmentation','Warrior-Arms','Evoker-Devastation','Hunter-Survival','Hunter-Marksmanship','Shaman-Restoration','Shaman-Enhancement','Rogue-Subtlety','Rogue-Assassination','Druid-Guardian','Monk-Brewmaster','Monk-Windwalker','Evoker-Preservation','Rogue-Outlaw','Paladin-Holy','Druid-Balance',}
local provider = {region='US',realm='TheForgottenCoast',name='US',type='daily',zone=46,date='2026-06-17',data={Aa='Aaricus:BAAALgAECgYJCAAAAA==.',
Ab='Aberdine:BAACLgAFFH8bAAIBAAYJYhJyDwCJAQZoDAAABwBLAGkMAAAGAC0AawwAAAQAHQBqDAAAAwAbAGwMAAABACMA6gwAAAYAMQABAAYJYhJyDwCJAQZoDAAABwBLAGkMAAAGAC0AawwAAAQAHQBqDAAAAwAbAGwMAAABACMA6gwAAAYAMQAuAAQKfy4AAwEACQnlGMUbAA8CAAEACQnlGMUbAA8CAAIAAglnDfJVACsAAAAA.',
Ac='Accar:BAABLgAECn8nAAIDAAgJUxGlFQB4AQhoDAAABgBDAGkMAAAGADUAawwAAAYAMQBqDAAABQBZAGwMAAAFAEUAbQwAAAMAGwDqDAAABwAjAG4MAAABAAcAAwAICVMRpRUAeAEIaAwAAAYAQwBpDAAABgA1AGsMAAAGADEAagwAAAUAWQBsDAAABQBFAG0MAAADABsA6gwAAAcAIwBuDAAAAQAHAAAA.Achu:BAAALgAFFAIJBAABLgAFFAQJHgAEAPMlAA==.Acylies:BAAALgADCgEJAQAAAA==.',
Ae='Aerìth:BAAALgAECgYJCAAAAA==.',
Ag='Agrias:BAABLgAECn8jAAQFAAgJCBinEwBDAghoDAAABQBMAGkMAAAGAFUAawwAAAYAOQBqDAAABQBQAGwMAAAFAD8AbQwAAAEAIwDqDAAABgBQAG4MAAABAAwABQAICQgYpxMAQwIIaAwAAAUATABpDAAABQBVAGsMAAAFADkAagwAAAUAUABsDAAAAwA/AG0MAAABACMA6gwAAAYAUABuDAAAAQAMAAYAAgl9CRRyAFwAAmkMAAABACAAawwAAAEAEAAHAAEJrw4zcQAsAAFsDAAAAgAlAAAA.',
Al='Algodón:BAAALgADCgEJAQAAAA==.Aliera:BAAALgADCgcJCwAAAA==.',
Am='Amaltheah:BAAALgAECgQJBAAAAA==.Ambry:BAAALgAECgQJEgABLgAECgkJKQAIAL8QAA==.Ambryosia:BAABLgAECn8pAAIIAAkJvxD5ZwCfAQloDAAABwBBAGkMAAAGAEEAawwAAAUAHgBqDAAABQAwAGwMAAAEACYAbQwAAAMAEADqDAAABwA+AG4MAAADACsAbwwAAAEAEwAIAAkJvxD5ZwCfAQloDAAABwBBAGkMAAAGAEEAawwAAAUAHgBqDAAABQAwAGwMAAAEACYAbQwAAAMAEADqDAAABwA+AG4MAAADACsAbwwAAAEAEwAAAA==.',
An='Andras:BAAALgAECgMJBAAAAA==.Angerßane:BAAALgADCgMJAwAAAA==.',
Ar='Aradora:BAAALgADCgQJBQAAAA==.Arcanyounot:BAAALgADCgkJEgABLgAECgcJFQAJAPgFAA==.',
As='Aspir:BAEALgAECgcJEwABLgAFFAYJFwAKAMEZAA==.',
Au='Auh:BAAALgAECgMJAwAAAA==.',
Av='Avera:BAAALgAECgIJAgAAAA==.Aviael:BAABLgAECn8eAAILAAYJYBENMwD0AAZoDAAABQAtAGkMAAAGAC8AawwAAAYAMQBqDAAABQAmAGwMAAACACkA6gwAAAYAJQALAAYJYBENMwD0AAZoDAAABQAtAGkMAAAGAC8AawwAAAYAMQBqDAAABQAmAGwMAAACACkA6gwAAAYAJQAAAA==.',
Aw='Awfulshotz:BAABLgAECn8ZAAIMAAkJMCA0LgAjAgloDAAAAgBhAGkMAAADAFgAawwAAAMAUQBqDAAAAwBiAGwMAAACAFQAbQwAAAEAMwDqDAAABQBhAG4MAAAEAFsAbwwAAAIARAAMAAkJMCA0LgAjAgloDAAAAgBhAGkMAAADAFgAawwAAAMAUQBqDAAAAwBiAGwMAAACAFQAbQwAAAEAMwDqDAAABQBhAG4MAAAEAFsAbwwAAAIARAABLgAECgYJIAANAOAUAA==.',
Ba='Badwolf:BAAALgAECgQJBwAAAA==.Bain:BAAALgADCgMJAwAAAA==.Bananabard:BAAALgADCgUJBQAAAA==.Barricade:BAABLgAECn8aAAMCAAkJJBdLFgCrAQloDAAABQBDAGkMAAADADsAawwAAAMAOQBqDAAAAwBaAGwMAAADACcAbQwAAAIAUgDqDAAABABXAG4MAAACADQAbwwAAAEAGwACAAkJJBdLFgCrAQloDAAABABDAGkMAAADADsAawwAAAIAOQBqDAAAAgBaAGwMAAACACcAbQwAAAIAUgDqDAAABABXAG4MAAACADQAbwwAAAEAGwABAAQJKRACcgCfAARoDAAAAQAiAGsMAAABADMAagwAAAEAHQBsDAAAAQAmAAAA.',
Bc='Bcrogue:BAAALgADCgEJAQABLgAECgkJHQAOAG4eAA==.Bcwarrior:BAAALgAECgYJCQABLgAECgkJHQAOAG4eAA==.',
Be='Bearymanalow:BAAALgAECgEJAQAAAA==.Belgrove:BAAALgADCgEJAQAAAA==.',
Bh='Bheap:BAAALgAECgYJDgAAAA==.',
Bi='Bigbaauls:BAAALgAECgYJCQAAAA==.',
Bj='Björk:BAAALgAECgUJBQABLgAECgYJEwAPAAAAAA==.',
Bl='Blizzaga:BAAALgAECgYJDgAAAA==.',
Bo='Bodhì:BAAALgAECgEJAQAAAA==.Boiardi:BAAALgAECgYJEAAAAA==.Bootowsky:BAAALgAECgQJBAAAAA==.Boromen:BAAALgADCgEJAQAAAA==.Boutros:BAAALgADCgYJBgAAAA==.Bowberto:BAAALgAECgEJAwAAAA==.',
Br='Brea:BAAALgADCgEJAQAAAA==.Briélle:BAAALgADCgMJAwAAAA==.Brocephus:BAABLgAECn8ZAAIQAAcJvBLoQgCFAQdoDAAABAA8AGkMAAAGAD8AawwAAAYALQBqDAAAAgA1AGwMAAACACoA6gwAAAQAQwBuDAAAAQACABAABwm8EuhCAIUBB2gMAAAEADwAaQwAAAYAPwBrDAAABgAtAGoMAAACADUAbAwAAAIAKgDqDAAABABDAG4MAAABAAIAAAA=.',
Bu='Burrgold:BAAALgAECggJDgAAAA==.',
Ca='Cadya:BAAALgAFFAIJAgABLgAFFAMJCQARAIMLAA==.',
Ce='Celticwoman:BAABLgAECn8jAAMSAAcJywm3lwAPAQdoDAAABgAZAGkMAAAGACIAawwAAAYAFgBqDAAABQA3AGwMAAAFACwAbQwAAAEACQDqDAAABgAOABIABwnLCbeXAA8BB2gMAAAEABkAaQwAAAQAIgBrDAAABAAWAGoMAAAEADcAbAwAAAUALABtDAAAAQAJAOoMAAAEAA4AEwAFCckEeTsAxgAFaAwAAAIAEgBpDAAAAgAKAGsMAAACAAkAagwAAAEADQDqDAAAAgAKAAAA.',
Ch='Champina:BAAALgAECgYJCQAAAA==.Chaoticelf:BAAALgADCgcJBwAAAA==.Chickenugget:BAABLgAECn8tAAIUAAgJvgZ/CAAEAQhoDAAABwAOAGkMAAAHAA4AawwAAAcADQBqDAAABQAPAGwMAAAGAA0AbQwAAAMAGwDqDAAABwAcAG4MAAADAAgAFAAICb4GfwgABAEIaAwAAAcADgBpDAAABwAOAGsMAAAHAA0AagwAAAUADwBsDAAABgANAG0MAAADABsA6gwAAAcAHABuDAAAAwAIAAAA.Choral:BAAALgAECgMJBQAAAA==.Chubzilla:BAAALgADCgUJBQAAAA==.Chuckwagaon:BAAALgAECgEJAQAAAA==.',
Ci='Cinderdorla:BAABLgAFFH8FAAIQAAIJGCIKPAC9AAJoDAAAAgBQAOoMAAADAF4AEAACCRgiCjwAvQACaAwAAAIAUADqDAAAAwBeAAEuAAUUBAkMABUATxYA.',
Cl='Clockie:BAACLgAFFH8eAAMEAAQJ8yVoBABFAQRoDAAACwBhAGkMAAAGAGIAawwAAAMAXwDqDAAACgBhAAQAAwn2JWgEAEUBA2kMAAAGAGIAawwAAAEAXwDqDAAAAwBhABIAAwlqIctXABcBA2gMAAALAGEAawwAAAIAPgDqDAAABwBgAC4ABAp/OwAEBAAJCd4kQgcA/gEAEgAHCQkkTSYARQIABAAGCVMlQgcA/gEAEwAECQofsyMAOwEAAAA=.Clõüd:BAABLgAECn8hAAIIAAgJMhDUfQBzAQhoDAAABQAmAGkMAAAFACsAawwAAAUAMABqDAAABQAvAGwMAAAFADcAbQwAAAIAEQDqDAAABQAxAG4MAAABACYACAAICTIQ1H0AcwEIaAwAAAUAJgBpDAAABQArAGsMAAAFADAAagwAAAUALwBsDAAABQA3AG0MAAACABEA6gwAAAUAMQBuDAAAAQAmAAEuAAUUBwkTAA0AcgoA.',
Co='Coldarc:BAAALgADCgYJBgAAAA==.',
Cu='Cuitlahuac:BAAALgAECgEJAwAAAA==.Cupra:BAAALgADCgUJBQAAAA==.',
Cy='Cynthigosa:BAAALgAECgQJBAAAAA==.',
['Cô']='Cônky:BAAALgAECgYJEAAAAA==.',
Da='Dade:BAAALgAECgYJCAAAAA==.Dadeleviathn:BAAALgADCgEJAQABLgAECgYJCAAPAAAAAA==.Dagrul:BAAALgADCgUJBQAAAA==.Danteangelo:BAAALgAECgEJAQAAAA==.Darrkmann:BAAALgAECgkJEwAAAA==.',
De='Deathrotull:BAAALgADCgUJBwAAAA==.Deathslice:BAAALgADCgMJAwAAAA==.Deathsprings:BAAALgADCgcJBwAAAA==.Delita:BAAALgAECgUJDQAAAA==.',
Di='Dietdrkelp:BAAALgADCgUJBQABLgAECgEJAQAPAAAAAA==.Dinkster:BAAALgAECgMJBQAAAA==.',
Dk='Dkcloud:BAABLgAECn8eAAIJAAgJ2h3PMQA3AghoDAAABgBTAGkMAAAEAFYAawwAAAQAVABqDAAAAwBIAGwMAAAEAFsAbQwAAAMANQDqDAAABQBSAG8MAAABADUACQAICdodzzEANwIIaAwAAAYAUwBpDAAABABWAGsMAAAEAFQAagwAAAMASABsDAAABABbAG0MAAADADUA6gwAAAUAUgBvDAAAAQA1AAEuAAUUBwkTAA0AcgoA.',
Do='Donella:BAAALgADCgIJAgAAAA==.Doughboy:BAAALgAECgQJBwAAAA==.',
Dr='Drawinddy:BAAALgAFFAIJAgAAAA==.Drifty:BAAALgAECgYJCwAAAA==.',
Du='Duoduo:BAABLgAFFH8MAAIWAAIJMyEKFQDGAAJoDAAABgBcAOoMAAAGAE0AFgACCTMhChUAxgACaAwAAAYAXADqDAAABgBNAAEuAAUUBAkMABUATxYA.Duoduomoney:BAABLgAFFH8JAAMBAAMJlBb2MADqAANoDAAABQBUAGkMAAABACEA6gwAAAMANgABAAMJlBb2MADqAANoDAAAAwBUAGkMAAABACEA6gwAAAEANgAXAAIJ4w7ONwB3AAJoDAAAAgAlAOoMAAACACYAAS4ABRQECQwAFQBPFgA=.',
['Dø']='Dønut:BAAALgADCgUJBQAAAA==.',
Eb='Eboncelest:BAABLgAFFH8MAAIGAAMJlhWyIgDdAANoDAAABwBKAGkMAAABADoA6gwAAAQAIAAGAAMJlhWyIgDdAANoDAAABwBKAGkMAAABADoA6gwAAAQAIAABLgAFFAQJHgAEAPMlAA==.',
Ec='Eclesiastes:BAAALgAECgEJAQAAAA==.',
El='Eldarcirdan:BAABLgAECn8bAAIQAAgJvQf+ZAAFAQhoDAAABAAYAGkMAAADAA8AawwAAAQAFABqDAAAAgAMAGwMAAACAAkAbQwAAAIACADqDAAABwAlAG4MAAADAB0AEAAICb0H/mQABQEIaAwAAAQAGABpDAAAAwAPAGsMAAAEABQAagwAAAIADABsDAAAAgAJAG0MAAACAAgA6gwAAAcAJQBuDAAAAwAdAAAA.',
Es='Esme:BAAALgADCgkJDwAAAA==.',
Et='Etrigon:BAAALgAECgEJAQAAAA==.',
Ev='Evajoh:BAAALgADCgUJBQAAAA==.',
Ex='Executioner:BAAALgADCgcJDwAAAA==.',
Fa='Fartstink:BAAALgADCgYJBwAAAA==.',
Fe='Festuss:BAAALgAECgQJDgAAAA==.',
Fi='Fingrwaglr:BAABLgAECn8gAAIYAAYJkwqfEgDgAAZoDAAABgAuAGkMAAAGABcAawwAAAYAGABqDAAABQAiAGwMAAADABUA6gwAAAYAEgAYAAYJkwqfEgDgAAZoDAAABgAuAGkMAAAGABcAawwAAAYAGABqDAAABQAiAGwMAAADABUA6gwAAAYAEgAAAA==.Fintan:BAAALgADCgMJAwAAAA==.Fizzlebliss:BAAALgADCgYJBgAAAA==.',
Fo='Forlin:BAAALgADCggJEQAAAA==.',
Fr='Frostlowe:BAAALgAECggJCgAAAA==.',
Fu='Fuzziestbutt:BAAALgADCgMJAwAAAA==.',
['Fú']='Fúsion:BAEALgAECgMJDAABLgAECgkJMwARAHoiAA==.',
Ga='Gambokni:BAAALgADCgcJFAAAAA==.Gamebread:BAAALgAECgUJCAAAAA==.Gattzu:BAAALgAECgYJCwAAAA==.',
Gi='Giganate:BAAALgADCgEJAQABLgAECgQJBAAPAAAAAA==.Gixx:BAAALgAECgYJEAABLgAECggJIAAIAM8UAA==.',
Gl='Glorr:BAAALgAECgcJBwAAAA==.',
Go='Gonamanar:BAAALgAECgcJBQAAAA==.Goth:BAAALgADCgEJAQAAAA==.Gourge:BAAALgAECgkJDwAAAA==.',
Gr='Grimfall:BAABLgAECn8sAAQZAAgJ7hxwFAAAAghoDAAACABNAGkMAAAHAFQAawwAAAcAWABqDAAABgBLAGwMAAAFADYAbQwAAAIAMADqDAAABwBcAG4MAAACAEcAGQAICTQbcBQAAAIIaAwAAAQATABpDAAABABFAGsMAAAEAEkAagwAAAQAMgBsDAAABAA2AG0MAAACADAA6gwAAAQAXABuDAAAAgBHAAwABQlyHttAAKwBBWgMAAABAE0AaQwAAAIAVABrDAAAAgBYAGoMAAACAEsA6gwAAAEAPQAaAAUJLBNOTwASAQVoDAAAAwA7AGkMAAABADYAawwAAAEALwBsDAAAAQAcAOoMAAACADYAAAA=.Grimtyr:BAAALgAECgEJAQAAAA==.Grëëdo:BAABLgAECn8gAAMIAAgJzxT4cACNAQhoDAAABQA9AGkMAAAHAEcAawwAAAQAOgBqDAAABABRAGwMAAADADsAbQwAAAEAFgDqDAAABgA6AG4MAAACACgACAAICc8U+HAAjQEIaAwAAAUAPQBpDAAABgBHAGsMAAADADoAagwAAAMAUQBsDAAAAwA7AG0MAAABABYA6gwAAAYAOgBuDAAAAgAoAAMAAwkzBd9LADwAA2kMAAABABQAawwAAAEABgBqDAAAAQAKAAAA.',
Gy='Gylvi:BAAALgADCgMJAwABLgAECgYJHgALAGARAA==.',
Ha='Hastor:BAAALgADCgcJBwAAAA==.',
He='Hellgrazer:BAAALgAECgYJEwAAAA==.',
Hi='Highlowe:BAABLgAECn8WAAQbAAgJfRzoHABkAghoDAAABABcAGkMAAAEAFQAawwAAAMAXABqDAAAAwBfAGwMAAACAGEA6gwAAAQAUgBuDAAAAQAGAG8MAAABACAAGwAGCW4j6BwAZAIGaAwAAAMAXABpDAAAAwBUAGsMAAADAFwAagwAAAMAXwBsDAAAAgBhAOoMAAACAFIAHAADCSkN/CoAnwADaAwAAAEAIwDqDAAAAQAfAG8MAAABACEAFQADCUwHC4EAbQADaQwAAAEAJADqDAAAAQAKAG4MAAABAAkAAAA=.Hikiru:BAAALgAECggJDwAAAA==.',
Ho='Hollowbane:BAACLgAFFH8FAAIdAAMJsQgfKwDUAANoDAAAAgAaAGkMAAACABUA6gwAAAEAEQAdAAMJsQgfKwDUAANoDAAAAgAaAGkMAAACABUA6gwAAAEAEQAuAAQKfygAAx0ACQl3GIYQACYCAB0ACQl3GIYQACYCAB4AAwmkFgMXAMEAAAAA.Holydragonn:BAAALgAFFAEJAQAAAA==.Holylock:BAAALgAFFAIJAgAAAA==.Holylordpig:BAAALgAFFAIJAgAAAA==.Holyshaman:BAABLgAFFH8FAAIbAAIJRQWNdQBSAAJoDAAABAAWAOoMAAABAAQAGwACCUUFjXUAUgACaAwAAAQAFgDqDAAAAQAEAAAA.Holywarrior:BAAALgAFFAMJBAAAAA==.Holyymonk:BAAALgAFFAIJAwAAAA==.Holyyseeker:BAAALgAFFAEJAQAAAA==.Homdantor:BAAALgAECgUJBQAAAA==.Hordeareus:BAAALgADCgUJBQAAAA==.Horse:BAAALgAECgYJBwABLgAFFAgJGAARACEbAA==.Hotyogafire:BAAALgAECgMJAwAAAA==.',
Ia='Iampally:BAAALgADCggJCQAAAA==.',
Im='Imdemonic:BAAALgAECgUJBQAAAA==.Imhim:BAAALgAECgEJAQAAAA==.Imogen:BAAALgAECgcJEgAAAA==.',
Ja='Jadeddruid:BAAALgAECgkJCQAAAA==.Jamieson:BAACLgAFFH8TAAINAAcJcgpXRQBeAQdoDAAABQA2AGkMAAAEACgAawwAAAIADgBqDAAAAQARAGwMAAABABoAbQwAAAEAAADqDAAABQAXAA0ABwlyCldFAF4BB2gMAAAFADYAaQwAAAQAKABrDAAAAgAOAGoMAAABABEAbAwAAAEAGgBtDAAAAQAAAOoMAAAFABcALgAECn9AAAINAAkJoSLGCQAsAwANAAkJoSLGCQAsAwAAAA==.Jand:BAAALgAECgYJDQAAAA==.Jazashi:BAAALgAECgYJFwAAAQ==.',
Jo='Jonesknight:BAABLgAECn8VAAIJAAcJ+AWmwwD5AAdoDAAAAwAHAGkMAAADABEAawwAAAMAEwBqDAAAAgASAGwMAAAEAA0AbQwAAAEADQDqDAAABQAUAAkABwn4BabDAPkAB2gMAAADAAcAaQwAAAMAEQBrDAAAAwATAGoMAAACABIAbAwAAAQADQBtDAAAAQANAOoMAAAFABQAAAA=.Jonnytsunami:BAABLgAFFH8IAAIfAAQJaBkaDQAmAQRoDAAAAgBHAGkMAAABADYAawwAAAEANQDqDAAABABRAB8ABAloGRoNACYBBGgMAAACAEcAaQwAAAEANgBrDAAAAQA1AOoMAAAEAFEAAAA=.',
Ju='Juicycow:BAAALgAECgcJDAAAAA==.',
Ka='Kahoru:BAAALgADCgcJBwAAAA==.Kailler:BAAALgAECgEJAQAAAA==.Kainn:BAAALgAECgYJEAAAAA==.',
Ke='Keg:BAACLgAFFH8pAAIgAAgJtCZNAAAmAwhoDAAACQBkAGkMAAAIAGMAawwAAAYAYwBqDAAABQBhAGwMAAABAGEAbQwAAAEAYQDqDAAACgBjAG4MAAABAGMAIAAICbQmTQAAJgMIaAwAAAkAZABpDAAACABjAGsMAAAGAGMAagwAAAUAYQBsDAAAAQBhAG0MAAABAGEA6gwAAAoAYwBuDAAAAQBjAC4ABAp/IwADIAAICdEmSwIAdwMAIAAICdEmSwIAdwMAIQABCVUhi34AVgAAAAA=.',
Kh='Khakuzu:BAAALgADCgIJAgAAAA==.',
Ki='Kikinak:BAAALgAECgYJCwAAAA==.Killshøt:BAAALgADCgEJAQAAAA==.Kitty:BAACLgAFFH8OAAIfAAQJdgeJHwCgAARoDAAABgAjAGkMAAAEABEAawwAAAEACwDqDAAAAwALAB8ABAl2B4kfAKAABGgMAAAGACMAaQwAAAQAEQBrDAAAAQALAOoMAAADAAsALgAECn8ZAAIfAAgJrhE5DwCIAQAfAAgJrhE5DwCIAQAAAA==.Kittyhawk:BAAALgAECggJEQAAAA==.',
Kk='Kk:BAAALgAECgYJEwAAAA==.',
Kl='Klassic:BAAALgAECgQJBgAAAA==.Klixx:BAAALgAECgYJDAAAAA==.',
Ko='Konexx:BAAALgAECgIJAgAAAA==.',
Ks='Kstab:BAABLgAECn8bAAIdAAcJLBuIGgAuAgdoDAAAAwBKAGkMAAAFAEoAawwAAAUAUgBqDAAABAAvAGwMAAABACEA6gwAAAUAOwBuDAAABABcAB0ABwksG4gaAC4CB2gMAAADAEoAaQwAAAUASgBrDAAABQBSAGoMAAAEAC8AbAwAAAEAIQDqDAAABQA7AG4MAAAEAFwAAAA=.',
Ku='Kuromeow:BAABLgAFFH8HAAINAAIJYRl9NgC9AAJoDAAAAgAoAOoMAAAFAFkADQACCWEZfTYAvQACaAwAAAIAKADqDAAABQBZAAAA.',
La='Lachasis:BAAALgAECgQJBAAAAA==.Larake:BAABLgAECn8jAAMiAAgJdQ+KEgCfAQhoDAAABwAzAGkMAAAFACMAawwAAAYALQBqDAAABgA/AGwMAAAEACIAbQwAAAEABADqDAAABQBFAG4MAAABAAwAIgAICXUPihIAnwEIaAwAAAcAMwBpDAAABQAjAGsMAAAGAC0AagwAAAYAPwBsDAAABAAiAG0MAAABAAQA6gwAAAQARQBuDAAAAQAMABgAAQllCGIpACgAAeoMAAABABUAAAA=.Lazypie:BAAALgAECgUJBQAAAA==.',
Le='Leggomyaggro:BAAALgAECgMJBQABLgAFFAQJFgAOACwmAA==.Lesiania:BAAALgAECgEJAwABLgAECgYJCAAPAAAAAA==.',
Li='Licus:BAAALgADCgkJFAAAAA==.Lightkeeper:BAABLgAECn8oAAMGAAgJShekHgDQAQhoDAAABwBMAGkMAAAHAEgAawwAAAYANQBqDAAABQAYAGwMAAAEADkAbQwAAAMAMwDqDAAABgBOAG4MAAACABoABgAICUoXpB4A0AEIaAwAAAYATABpDAAABgBIAGsMAAAFADUAagwAAAUAGABsDAAABAA5AG0MAAADADMA6gwAAAYATgBuDAAAAgAaAAcAAwnvBO9sAHYAA2gMAAABAAMAaQwAAAEADQBrDAAAAQAUAAAA.Lightning:BAAALgADCgEJAQAAAA==.Limpßrisket:BAAALgAECgMJAgAAAA==.Litdealer:BAAALgAECgYJDgABLgAFFAMJCwAgAFcZAA==.Littlestiffy:BAAALgADCgMJAwAAAA==.',
Lr='Lroux:BAAALgAECggJEQAAAA==.',
Lu='Lucyah:BAAALgAECgcJDgAAAA==.',
Ma='Makshifu:BAAALgAFFAIJAwABLgAFFAQJDAAVAE8WAA==.Malkallam:BAAALgADCgUJBQAAAA==.Manaplague:BAAALgAECgUJCwAAAA==.Manenya:BAAALgAECgYJCAAAAA==.Marotto:BAAALgAECgMJAwAAAA==.Massacar:BAABLgAECn8YAAIRAAYJSgo5igAPAQZoDAAABQArAGkMAAAFACoAawwAAAUAEgBqDAAABAAoAGwMAAACAA4A6gwAAAMADQARAAYJSgo5igAPAQZoDAAABQArAGkMAAAFACoAawwAAAUAEgBqDAAABAAoAGwMAAACAA4A6gwAAAMADQABLgAECggJIAAIAM8UAA==.',
Me='Meatpuller:BAAALgADCgkJDwAAAA==.Megumyxd:BAAALgAECgQJBAAAAA==.Menion:BAABLgAECn8cAAMIAAkJZhuLJgCMAgloDAAABABWAGkMAAAEAF0AawwAAAQAWABqDAAABABQAGwMAAADAD8AbQwAAAEAJQDqDAAABABUAG4MAAADAEQAbwwAAAEAJgAIAAkJZhuLJgCMAgloDAAAAwBWAGkMAAADAF0AawwAAAMAWABqDAAAAwBQAGwMAAACAD8AbQwAAAEAJQDqDAAABABUAG4MAAADAEQAbwwAAAEAJgADAAUJQgykMgCYAAVoDAAAAQAeAGkMAAABAAsAawwAAAEAMwBqDAAAAQAUAGwMAAABACAAAAA=.Meowmeowmeow:BAAALgADCgcJBwABLgAFFAcJIAAJABwfAA==.Mercadius:BAAALgAECgYJEAAAAA==.Metalx:BAAALgADCgkJFQAAAA==.',
Mi='Minkyu:BAAALgAECgQJCAAAAA==.Misha:BAAALgADCgEJAQAAAA==.',
Mk='Mk:BAEALgAECgcJEQABLgAECggJGwAjAMsWAA==.',
Mo='Monkpig:BAACLgAFFH8YAAIgAAQJZx5hGABeAQRoDAAACQBZAGkMAAAFAEwAawwAAAIAQADqDAAACABQACAABAlnHmEYAF4BBGgMAAAJAFkAaQwAAAUATABrDAAAAgBAAOoMAAAIAFAALgAECn8qAAIgAAkJ7R/uDQBZAgAgAAkJ7R/uDQBZAgAAAA==.Mooinator:BAAALgADCgYJBgAAAA==.',
My='Myrai:BAAALgADCgEJAQAAAA==.',
Na='Nanashi:BAABLgAECn8YAAILAAYJTRUSLQAYAQZoDAAABgA2AGkMAAAEADEAawwAAAMAOQBqDAAABAAmAGwMAAAEAD0A6gwAAAMAMQALAAYJTRUSLQAYAQZoDAAABgA2AGkMAAAEADEAawwAAAMAOQBqDAAABAAmAGwMAAAEAD0A6gwAAAMAMQAAAA==.Nannerz:BAAALgAECgYJEQAAAA==.Natenasty:BAAALgADCgUJBQABLgAECgQJBAAPAAAAAA==.Natenomoney:BAAALgAECgQJBAAAAA==.Nathan:BAAALgAECgMJAwABLgAECgQJBAAPAAAAAA==.',
Nd='Ndeh:BAAALgAFFAEJAQAAAA==.',
Ne='Nena:BAAALgAECgEJAQAAAA==.Nermonhunder:BAAALgAECgQJCAAAAA==.',
Ni='Ninjitsû:BAABLgAECn8aAAIRAAgJuBziHQCeAghoDAAABABLAGkMAAAEAEcAawwAAAQAPwBqDAAABABaAGwMAAADAFgAbQwAAAEAMgDqDAAABABTAG4MAAACAFIAEQAICbgc4h0AngIIaAwAAAQASwBpDAAABABHAGsMAAAEAD8AagwAAAQAWgBsDAAAAwBYAG0MAAABADIA6gwAAAQAUwBuDAAAAgBSAAAA.',
Ol='Oldspice:BAAALgAECgMJBwAAAA==.Olex:BAAALgAECgUJBQAAAA==.',
Om='Omgkangel:BAABLgAECn8VAAIOAAYJnBa6HABlAQZoDAAABAAzAGkMAAAEADcAawwAAAQASABqDAAAAwBAAGwMAAACACoA6gwAAAQAQgAOAAYJnBa6HABlAQZoDAAABAAzAGkMAAAEADcAawwAAAQASABqDAAAAwBAAGwMAAACACoA6gwAAAQAQgAAAA==.Omi:BAAALgAECgQJBAAAAA==.Omie:BAAALgAECgEJBAAAAA==.',
On='Onoos:BAAALgAECgMJBgAAAA==.',
Ov='Overpower:BAAALgADCgIJAgABLgAECgkJKwAJAMgUAA==.Ovix:BAAALgADCgMJAQABLgAECgUJDAAPAAAAAA==.',
Ow='Ow:BAAALgADCgEJAQAAAA==.',
Pa='Paulos:BAAALgAECgUJCQAAAA==.',
Pe='Peaf:BAABLgAECn8gAAMBAAYJlyADMgCDAQZoDAAABgBiAGkMAAAGAEAAawwAAAYAXwBqDAAABQBSAGwMAAADAFMA6gwAAAYASwABAAYJlyADMgCDAQZoDAAABQBiAGkMAAAFAEAAawwAAAYAXwBqDAAABABSAGwMAAADAFMA6gwAAAUASwACAAQJnAuXQQBoAARoDAAAAQAbAGkMAAABABkAagwAAAEAEwDqDAAAAQAkAAAA.Petesfeets:BAAALgADCgYJCAAAAA==.',
Pl='Playajizoe:BAAALgAECgQJBwAAAA==.',
Po='Pocketsnacks:BAAALgADCgEJAQAAAA==.Poppabanger:BAAALgAECgQJBwAAAA==.',
Qu='Quill:BAABLgAECn8eAAIJAAcJrB1CSwARAgdoDAAABgBYAGkMAAAFAEoAawwAAAUAPABqDAAABQBRAGwMAAADAEYAbQwAAAEAYADqDAAABQBCAAkABwmsHUJLABECB2gMAAAGAFgAaQwAAAUASgBrDAAABQA8AGoMAAAFAFEAbAwAAAMARgBtDAAAAQBgAOoMAAAFAEIAAS4ABRQDCQQADwAAAAA=.',
Ra='Raythe:BAABLgAECn8iAAILAAcJ6BUNJQBPAQdoDAAABQBFAGkMAAAHAE0AawwAAAUAPQBqDAAABAAXAGwMAAADACwAbQwAAAEAFADqDAAACQA+AAsABwnoFQ0lAE8BB2gMAAAFAEUAaQwAAAcATQBrDAAABQA9AGoMAAAEABcAbAwAAAMALABtDAAAAQAUAOoMAAAJAD4AAAA=.Razzeman:BAAALgAECgEJAQAAAA==.Razzledazzl:BAAALgAECgEJAQAAAA==.',
Ro='Rose:BAAALgAECgcJDgABLgAFFAQJDgAfAHYHAA==.',
Ru='Ruck:BAAALgAFFAEJAQAAAA==.Rucker:BAABLgAECn8pAAMCAAkJmx2NBwCJAgloDAAACABXAGkMAAAIAFwAawwAAAcAUQBqDAAAAwBQAGwMAAAEAFsAbQwAAAIAPgDqDAAABQBdAG4MAAADACcAbwwAAAEAOgACAAkJmx2NBwCJAgloDAAACABXAGkMAAAIAFwAawwAAAYAUQBqDAAAAwBQAGwMAAAEAFsAbQwAAAIAPgDqDAAABQBdAG4MAAADACcAbwwAAAEAOgABAAEJWAIVtQAdAAFrDAAAAQAGAAEuAAUUAQkBAA8AAAAA.Ruckkin:BAAALgAECgMJBgABLgAFFAEJAQAPAAAAAA==.Rucksi:BAAALgAECgQJBAABLgAFFAEJAQAPAAAAAA==.Rucksy:BAABLgAECn8oAAMDAAgJoB0RBQCrAghoDAAABwBcAGkMAAAHAGIAawwAAAgAXwBqDAAABQBXAGwMAAAFAEsAbQwAAAEAKADqDAAABQBbAG4MAAACACMAAwAICaAdEQUAqwIIaAwAAAcAXABpDAAABwBiAGsMAAAHAF8AagwAAAQAVwBsDAAABQBLAG0MAAABACgA6gwAAAQAWwBuDAAAAgAjAAgAAwn+Ebf9AJkAA2sMAAABAB4AagwAAAEAOgDqDAAAAQA9AAEuAAUUAQkBAA8AAAAA.Ruckuhs:BAAALgADCgkJDAABLgAFFAEJAQAPAAAAAA==.Ruxsi:BAAALgAECgUJCAABLgAFFAEJAQAPAAAAAA==.',
Ry='Ryan:BAABLgAECn8iAAMIAAkJvR2uLQBKAgloDAAABQBhAGkMAAAFAGEAawwAAAYAXABqDAAABQBhAGwMAAAEAFwAbQwAAAEAGQDqDAAABQBaAG4MAAACAEwAbwwAAAEAJAAIAAcJnCOuLQBKAgdoDAAAAwBhAGkMAAAEAGEAawwAAAYAXABqDAAAAQBhAGwMAAACAFwA6gwAAAMAWgBuDAAAAQBMACQACAl7IJ8gAP8BCGgMAAACAF0AaQwAAAEAVQBqDAAABABdAGwMAAACAFkAbQwAAAEATQDqDAAAAgBXAG4MAAABAEUAbwwAAAEARAAAAA==.',
['Rì']='Rìptide:BAAALgAECgkJEQAAAA==.',
['Rô']='Rôrônoazoro:BAAALgADCgYJCwAAAA==.',
Sa='Saragdan:BAAALgADCgcJCwAAAA==.',
Sc='Scylla:BAAALgAECgYJBgABLgAECgYJDwAPAAAAAA==.',
Se='Seraphae:BAAALgAECgEJAgAAAA==.Sereb:BAAALgAECgUJBwAAAA==.',
Sh='Shadowscurry:BAAALgAECgQJBwAAAA==.Shankzmcgee:BAABLgAECn8cAAIdAAYJcQoROQDrAAZoDAAABwApAGkMAAAHAB4AawwAAAYAGgBqDAAABAATAGwMAAACABUA6gwAAAIADQAdAAYJcQoROQDrAAZoDAAABwApAGkMAAAHAB4AawwAAAYAGgBqDAAABAATAGwMAAACABUA6gwAAAIADQABLgAECggJIAAIAM8UAA==.Shardik:BAABLgAECn8YAAIlAAYJThEpQAANAQZoDAAABQBAAGkMAAAFACYAawwAAAUALQBqDAAABQAcAGwMAAACACoA6gwAAAIAHwAlAAYJThEpQAANAQZoDAAABQBAAGkMAAAFACYAawwAAAUALQBqDAAABQAcAGwMAAACACoA6gwAAAIAHwAAAA==.Sheero:BAAALgAECgUJBQAAAA==.Sheong:BAAALgAECgkJCwAAAA==.Sheñ:BAAALgAECgcJDAAAAA==.Shiftyone:BAAALgADCgMJAwAAAA==.Shindark:BAAALgAECgEJAgAAAA==.Shivah:BAAALgAECgcJCwABLgAFFAMJBAAPAAAAAA==.Shrus:BAAALgAECgYJBgAAAA==.Shrussy:BAAALgADCgMJAwAAAA==.Shèrlock:BAABLgAECn8yAAISAAkJtRlQHAB8AgloDAAABgBDAGkMAAAHAEsAawwAAAcARgBqDAAABwBZAGwMAAAGAEIAbQwAAAUASgDqDAAABgBEAG4MAAAEAEcAbwwAAAIAHwASAAkJtRlQHAB8AgloDAAABgBDAGkMAAAHAEsAawwAAAcARgBqDAAABwBZAGwMAAAGAEIAbQwAAAUASgDqDAAABgBEAG4MAAAEAEcAbwwAAAIAHwAAAA==.',
Si='Silverfox:BAABLgAFFH8MAAMVAAQJTxZtIQAVAQRoDAAABAA9AGkMAAACADEAawwAAAIANwDqDAAABAA+ABUABAlPFm0hABUBBGgMAAACAD0AaQwAAAIAMQBrDAAAAgA3AOoMAAACAD4AGwACCSgaJF4AjQACaAwAAAIAMADqDAAAAgBVAAAA.',
Sk='Skippydippy:BAAALgAECgQJCwAAAA==.Skye:BAAALgAECgcJBQAAAA==.Skylin:BAAALgAECgEJBAAAAA==.',
Sl='Sleezee:BAAALgAECgQJCQAAAA==.Slushpuppis:BAAALgADCgcJBwAAAA==.',
Sn='Sneeger:BAAALgAECgYJDgAAAA==.',
Sp='Spelldeala:BAAALgAECgYJEAABLgAFFAMJCwAgAFcZAA==.',
St='Stargasm:BAABLgAFFH8LAAIHAAMJKQ5YJACYAANoDAAABAApAGkMAAAFACUA6gwAAAIAHgAHAAMJKQ5YJACYAANoDAAABAApAGkMAAAFACUA6gwAAAIAHgAAAA==.Stdmachine:BAAALgAECgYJDAAAAA==.Stonedstoner:BAAALgAECgUJCAAAAA==.',
Su='Superdump:BAAALgAECgcJAgAAAA==.',
Sw='Swiftmend:BAABLgAFFH8JAAIQAAIJtw5xVwBpAAJoDAAABAAnAOoMAAAFACMAEAACCbcOcVcAaQACaAwAAAQAJwDqDAAABQAjAAEuAAUUAwkLACAAVxkA.',
Sy='Syleyn:BAAALgAECgYJDQABLgAFFAQJFgAOACwmAA==.Syllal:BAAALgADCgQJBAAAAA==.Synisttir:BAAALgAECgYJDQAAAA==.',
Ta='Taft:BAABLgAECn8wAAMlAAkJjBNhHQDdAQloDAAABQA9AGkMAAAIAD8AawwAAAcAOwBqDAAABwA5AGwMAAAGACUAbQwAAAQALQDqDAAABQA4AG4MAAAEADEAbwwAAAIAGwAlAAkJjBNhHQDdAQloDAAABQA9AGkMAAAIAD8AawwAAAcAOwBqDAAABwA5AGwMAAAGACUAbQwAAAQALQDqDAAABAA4AG4MAAAEADEAbwwAAAIAGwAQAAEJDQz73QAoAAHqDAAAAQAeAAAA.Tardis:BAAALgADCgcJCgAAAA==.Taterz:BAAALgADCgQJBAAAAA==.',
Te='Terrá:BAAALgAECgYJCgAAAA==.Teryn:BAAALgAECgEJAQAAAA==.Tesa:BAAALgADCgMJBQAAAA==.',
Th='Thomassian:BAAALgAECgEJAgAAAA==.',
Ti='Timewing:BAAALgADCggJFAAAAA==.Timtoo:BAAALgAECgMJBQAAAA==.',
To='Toborntwob:BAABLgAECn8fAAIBAAcJ2hbzKwCkAQdoDAAABQA+AGkMAAAFAEUAawwAAAUAOwBqDAAABAAmAGwMAAAGACkAbQwAAAEAMADqDAAABQBFAAEABwnaFvMrAKQBB2gMAAAFAD4AaQwAAAUARQBrDAAABQA7AGoMAAAEACYAbAwAAAYAKQBtDAAAAQAwAOoMAAAFAEUAAAA=.Tony:BAAALgAFFAEJAgAAAA==.',
Tr='Transformer:BAAALgAECgQJBgAAAA==.Triblequest:BAABLgAECn8WAAIVAAYJBhXWPQA9AQZoDAAABQBGAGkMAAAEAEYAawwAAAQANQBqDAAAAwBKAGwMAAABAAcA6gwAAAUARAAVAAYJBhXWPQA9AQZoDAAABQBGAGkMAAAEAEYAawwAAAQANQBqDAAAAwBKAGwMAAABAAcA6gwAAAUARAAAAA==.Tritin:BAABLgAECn8XAAIIAAgJmAaNzQD2AAhoDAAAAwAVAGkMAAADABIAawwAAAIADwBqDAAAAgATAGwMAAAEABwAbQwAAAEADgDqDAAABwASAG4MAAABAAEACAAICZgGjc0A9gAIaAwAAAMAFQBpDAAAAwASAGsMAAACAA8AagwAAAIAEwBsDAAABAAcAG0MAAABAA4A6gwAAAcAEgBuDAAAAQABAAAA.Trotndot:BAAALgADCgQJBAAAAA==.',
Tu='Tugginmypuda:BAAALgAECgQJBAAAAA==.',
Tw='Twiltock:BAAALgAECgYJDAAAAA==.Twizztyd:BAAALgAECgYJDgAAAA==.Twocups:BAAALgAECgUJCgAAAA==.',
Un='Underware:BAAALgADCgYJBgAAAA==.',
Va='Valessa:BAABLgAECn8uAAINAAgJVwZ2rAAmAQhoDAAABgAPAGkMAAAGABQAawwAAAcABQBqDAAABgAUAGwMAAAHABIAbQwAAAMAEgDqDAAACAASAG4MAAADAA8ADQAICVcGdqwAJgEIaAwAAAYADwBpDAAABgAUAGsMAAAHAAUAagwAAAYAFABsDAAABwASAG0MAAADABIA6gwAAAgAEgBuDAAAAwAPAAAA.Valiria:BAACLgAFFH8IAAIRAAMJzBaXXgDSAANoDAAAAwA/AGkMAAADAD0A6gwAAAIAMgARAAMJzBaXXgDSAANoDAAAAwA/AGkMAAADAD0A6gwAAAIAMgAuAAQKfx8AAhEACQldGbMrABkCABEACQldGbMrABkCAAAA.Varzul:BAAALgADCgYJCwABLgAECgIJAgAPAAAAAA==.',
Ve='Velieda:BAABLgAECn8mAAMIAAgJ0xFCjQBXAQhoDAAABgAoAGkMAAAGAC0AawwAAAYANABqDAAAAwA6AGwMAAAFAD8AbQwAAAIAFgDqDAAABQAkAG4MAAAFADkACAAICQcOQo0AVwEIaAwAAAIAJwBpDAAAAgAkAGsMAAACACgAagwAAAEAEgBsDAAAAgAiAG0MAAACABYA6gwAAAIAFABuDAAABQA5AAMABgm3EhQhAAsBBmgMAAAEACgAaQwAAAQALQBrDAAABAA0AGoMAAACADoAbAwAAAMAPwDqDAAAAwAkAAAA.',
Vi='Vie:BAAALgAECgYJBgAAAA==.Vindication:BAACLgAFFH8WAAIOAAQJLCb6DACsAQRoDAAACABiAGkMAAAGAGAAawwAAAMAYgDqDAAABQBhAA4ABAksJvoMAKwBBGgMAAAIAGIAaQwAAAYAYABrDAAAAwBiAOoMAAAFAGEALgAECn8vAAIOAAgJiiAtCQB/AgAOAAgJiiAtCQB/AgAAAA==.Vita:BAAALgAECgYJBwAAAA==.',
Wa='Wackah:BAAALgAECgYJCQAAAA==.Wafflez:BAAALgAECgIJAgAAAA==.Wakana:BAAALgAECgIJAgAAAA==.',
We='Wearehorde:BAAALgADCgQJBAAAAA==.',
Wi='Windflower:BAAALgADCgQJBAAAAA==.Winteranne:BAAALgAECgEJAQAAAA==.',
Wo='Wolfcarver:BAAALgAECgYJEAAAAA==.Worldbreakèr:BAAALgAECggJAQAAAA==.',
['Wÿ']='Wÿcked:BAAALgAECgUJCAAAAA==.',
Xi='Xiaobao:BAABLgAFFH8KAAIfAAQJ3Q5rFQDWAARoDAAAAwBEAGkMAAADADsAawwAAAIABgDqDAAAAgASAB8ABAndDmsVANYABGgMAAADAEQAaQwAAAMAOwBrDAAAAgAGAOoMAAACABIAAAA=.Xiaoduoduo:BAACLgAFFH8OAAMIAAMJoB/jXAD1AANoDAAABgBfAGkMAAACAEAA6gwAAAYAUgAIAAMJoB/jXAD1AANoDAAABQBfAGkMAAACAEAA6gwAAAYAUgAkAAEJuCN5QgBZAAFoDAAAAQBbAC4ABAp/KgACCAAJCaIjuhIA0wIACAAJCaIjuhIA0wIAAS4ABRQECQwAFQBPFgA=.Xiaomak:BAAALgADCgQJBAABLgAFFAQJDAAVAE8WAA==.Xiaoxiongmao:BAAALgADCgcJBwAAAA==.',
Xs='Xschaferr:BAABLgAECn8jAAIIAAgJ6giXowAyAQhoDAAABQAUAGkMAAAFABMAawwAAAUAGQBqDAAABgATAGwMAAAGABEAbQwAAAIADwDqDAAABAAQAG4MAAACACwACAAICeoIl6MAMgEIaAwAAAUAFABpDAAABQATAGsMAAAFABkAagwAAAYAEwBsDAAABgARAG0MAAACAA8A6gwAAAQAEABuDAAAAgAsAAAA.',
Za='Zabz:BAAALgAECgYJBwABLgAECgkJOgAIANwhAA==.',
Ze='Zeroskills:BAABLgAECn8kAAMdAAkJ/QeaIwB3AQloDAAABQAdAGkMAAAFACEAawwAAAUAFwBqDAAABAAlAGwMAAADABgAbQwAAAIAAwDqDAAABgAUAG4MAAAEABMAbwwAAAIACQAdAAkJ/QeaIwB3AQloDAAABAAdAGkMAAAEACEAawwAAAUAFwBqDAAABAAlAGwMAAADABgAbQwAAAIAAwDqDAAABgAUAG4MAAAEABMAbwwAAAIACQAeAAIJSwSHIgBPAAJoDAAAAQAHAGkMAAABAA4AAAA=.',
Zu='Zulinar:BAABLgAECn8YAAIbAAcJcArbZgAmAQdoDAAAAwAfAGkMAAAEABQAawwAAAQAIQBqDAAABQARAGwMAAADABoAbQwAAAEACADqDAAABAAwABsABwlwCttmACYBB2gMAAADAB8AaQwAAAQAFABrDAAABAAhAGoMAAAFABEAbAwAAAMAGgBtDAAAAQAIAOoMAAAEADAAAAA=.Zumoku:BAAALgAECgkJBQAAAA==.',
['Às']='Àsmodeus:BAACLgAFFH8GAAIfAAIJvgYlMwBUAAJoDAAAAwAZAGkMAAADAAkAHwACCb4GJTMAVAACaAwAAAMAGQBpDAAAAwAJAC4ABAp/OwAEHwAJCcwTmxEA1AEAHwAJCcwTmxEA1AEAJQACCa4FCIAARwAAEAABCTEKh+EAJgAAAAA=.',
['Æn']='Ænimá:BAAALgADCgEJAQAAAA==.',
['Çr']='Çryptwalkin:BAAALgAECgEJAQAAAA==.',
['ßi']='ßiggysmalls:BAAALgADCgUJBQAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
