local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Mage-Frost','Unknown-Unknown','Shaman-Elemental','DemonHunter-Devourer','Evoker-Preservation','Priest-Shadow','Paladin-Retribution','Hunter-Marksmanship','Druid-Guardian','Warrior-Arms','Warrior-Fury','DemonHunter-Vengeance','Druid-Restoration','Hunter-BeastMastery','Evoker-Augmentation','Hunter-Survival','DeathKnight-Unholy','DeathKnight-Frost','Monk-Mistweaver','Monk-Windwalker','Druid-Balance','DemonHunter-Havoc','Warlock-Demonology','Warlock-Destruction','Evoker-Devastation','Warlock-Affliction','Rogue-Subtlety','Rogue-Assassination','Shaman-Restoration','Druid-Feral','Paladin-Protection','Paladin-Holy','Priest-Holy','Mage-Arcane','Shaman-Enhancement','Priest-Discipline','Mage-Fire','Warrior-Protection','Monk-Brewmaster',}
local provider = {region='US',realm='Nazjatar',name='US',type='daily',zone=46,date='2026-05-10',data={Aa='Aaela:BAAALgADCgUJBQAAAA==.',
Ab='Abrasaxs:BAABLgAECn8iAAIBAAcJdRe1PgCzAQdoDAAABgBOAGkMAAAGAEcAawwAAAYALABqDAAABQBCAGwMAAADAFEAbQwAAAIAHQDqDAAABgA2AAEABwl1F7U+ALMBB2gMAAAGAE4AaQwAAAYARwBrDAAABgAsAGoMAAAFAEIAbAwAAAMAUQBtDAAAAgAdAOoMAAAGADYAAAA=.Absylus:BAAALgAECgQJBAABLgAFFAMJBAACAAAAAA==.',
Ac='Ackerman:BAAALgAECgYJCgABLgAECggJEQACAAAAAA==.Acslater:BAAALgAECgMJAwAAAA==.Actionman:BAAALgAECgkJBgAAAA==.',
Ag='Agoobagoo:BAACLgAFFH8PAAIDAAQJ3iDqBgCKAQRoDAAABABVAGkMAAADAFgAawwAAAQAQQDqDAAABABgAAMABAneIOoGAIoBBGgMAAAEAFUAaQwAAAMAWABrDAAABABBAOoMAAAEAGAALgAECn8XAAIDAAkJwyKQBABSAwADAAkJwyKQBABSAwAAAA==.',
Ai='Aionn:BAAALgAECgMJAwAAAA==.Airrow:BAAALgAECggJEAAAAA==.Aissae:BAACLgAFFH8NAAIEAAQJ7hz6EAB5AQRoDAAABQBRAGkMAAAEAE4AawwAAAIAXQDqDAAAAgAqAAQABAnuHPoQAHkBBGgMAAAFAFEAaQwAAAQATgBrDAAAAgBdAOoMAAACACoALgAECn8mAAIEAAgJQCR2CwAmAwAEAAgJQCR2CwAmAwAAAA==.Aiyama:BAAALgADCgQJBAAAAA==.',
Ak='Akiio:BAAALgAECgMJAwAAAA==.Akumaxl:BAAALgAECgYJBwAAAA==.',
Al='Alexia:BAAALgAECgEJAQAAAA==.Alfrank:BAAALgAECgIJAgAAAA==.Aliasx:BAAALgAECgIJAgAAAA==.Alphrank:BAAALgAECgEJAQAAAA==.Alurie:BAAALgAECgUJBgAAAA==.',
Am='Ambros:BAAALgADCgYJBgAAAA==.Aminatou:BAAALgAECgYJBgAAAA==.',
An='Anheeboan:BAAALgAECgYJCwAAAA==.Anihilated:BAAALgADCgYJBwAAAA==.',
Ar='Aradiax:BAAALgADCgYJBgAAAA==.Arcadavia:BAAALgADCgMJAwAAAA==.Arjentheilus:BAAALgAECgMJAwAAAA==.Arthasl:BAAALgADCgIJAgAAAA==.Arthur:BAAALgAECgQJCQAAAA==.',
As='Asasda:BAAALgADCgMJBAAAAA==.Ashaelra:BAAALgAECgYJCAAAAA==.Astravaritan:BAAALgADCgMJAwAAAA==.',
At='Atherya:BAAALgAECgYJCAAAAA==.Atomixblonde:BAAALgAECgEJAQAAAA==.',
Au='Augonly:BAACLgAFFH8SAAIFAAQJrBV9DgA0AQRoDAAABgAlAGkMAAAFACQAawwAAAMAQADqDAAABABUAAUABAmsFX0OADQBBGgMAAAGACUAaQwAAAUAJABrDAAAAwBAAOoMAAAEAFQALgAECn8jAAIFAAkJ6SAuBgDhAgAFAAkJ6SAuBgDhAgAAAA==.Augy:BAAALgAFFAIJAgAAAA==.Autoshot:BAAALgAECgQJBQAAAA==.',
Av='Averisbelia:BAAALgADCgIJAgAAAA==.',
Ay='Ayowamsley:BAAALgADCgMJAwAAAA==.',
Az='Azalea:BAAALgAECggJEAAAAA==.',
Ba='Babycrock:BAAALgADCgYJBgAAAA==.Back:BAAALgADCgcJDAAAAA==.Bakihanma:BAAALgAECgIJAgAAAA==.Balash:BAAALgADCgUJBQAAAA==.Balerion:BAAALgADCgEJAQABLgADCgMJAwACAAAAAA==.Balthasar:BAABLgAECn8UAAIGAAgJ7g+gGwBrAQhoDAAAAwBFAGkMAAAEADsAawwAAAMAHABqDAAAAgAhAGwMAAABAAwAbQwAAAEALwDqDAAABAAvAG4MAAACABMABgAICe4PoBsAawEIaAwAAAMARQBpDAAABAA7AGsMAAADABwAagwAAAIAIQBsDAAAAQAMAG0MAAABAC8A6gwAAAQALwBuDAAAAgATAAAA.Banjobits:BAAALgADCgIJAgAAAA==.Barhead:BAAALgAECgYJDAAAAA==.Barlow:BAAALgAECgMJAwAAAA==.Barqose:BAAALgADCgMJAwAAAA==.Barryberry:BAABLgAECn8fAAIHAAkJDRGaOACnAQloDAAABQBCAGkMAAAEADgAawwAAAQALgBqDAAAAwBHAGwMAAADACgAbQwAAAIAEQDqDAAABgA9AG4MAAADACkAbwwAAAEAEwAHAAkJDRGaOACnAQloDAAABQBCAGkMAAAEADgAawwAAAQALgBqDAAAAwBHAGwMAAADACgAbQwAAAIAEQDqDAAABgA9AG4MAAADACkAbwwAAAEAEwAAAA==.Barryx:BAAALgAECgIJAgAAAA==.',
Bb='Bbldrizzy:BAAALgAFFAIJAwAAAA==.',
Be='Beastlieduke:BAAALgADCgUJCQABLgAFFAQJCgAGAJUKAA==.Beastlièduke:BAACLgAFFH8KAAIGAAQJlQpwEgABAQRoDAAABAA0AGkMAAADABYAawwAAAEAAADqDAAAAgAfAAYABAmVCnASAAEBBGgMAAAEADQAaQwAAAMAFgBrDAAAAQAAAOoMAAACAB8ALgAECn8oAAIGAAgJth7yDgCUAgAGAAgJth7yDgCUAgAAAA==.Beauslay:BAAALgAECgEJAQAAAA==.Belephon:BAAALgAECgYJEAAAAA==.Bellaruhbz:BAABLgAECn8eAAIIAAkJjA86DQAfAQloDAAABQA6AGkMAAAEACkAawwAAAQAMQBqDAAABAAqAGwMAAACAC4AbQwAAAIAHwDqDAAABgAnAG4MAAACACsAbwwAAAEACAAIAAkJjA86DQAfAQloDAAABQA6AGkMAAAEACkAawwAAAQAMQBqDAAABAAqAGwMAAACAC4AbQwAAAIAHwDqDAAABgAnAG4MAAACACsAbwwAAAEACAAAAA==.Berenstain:BAABLgAECn8fAAIJAAgJ4BIhDgBBAQhoDAAABQA4AGkMAAAEABsAawwAAAQAKQBqDAAAAgAlAGwMAAADAEQAbQwAAAMAIgDqDAAABwBPAG4MAAADAB0ACQAICeASIQ4AQQEIaAwAAAUAOABpDAAABAAbAGsMAAAEACkAagwAAAIAJQBsDAAAAwBEAG0MAAADACIA6gwAAAcATwBuDAAAAwAdAAAA.Bergmire:BAAALgAECgMJBAAAAA==.Berple:BAAALgADCgUJBQABLgAECgIJAgACAAAAAA==.Bestoresto:BAAALgAECggJEAAAAA==.',
Bh='Bhori:BAAALgAECgEJAQAAAA==.',
Bi='Bibahabibi:BAABLgAECn8WAAMKAAYJBxOyGgAdAQZoDAAABQAnAGkMAAAFABUAawwAAAQATABqDAAAAQARAGwMAAACADYA6gwAAAUAMgAKAAYJBxOyGgAdAQZoDAAABAAnAGkMAAAEABUAawwAAAMATABqDAAAAQARAGwMAAACADYA6gwAAAUAMgALAAMJzQiUhwChAANoDAAAAQAYAGkMAAABAA8AawwAAAEAGwAAAA==.Bigpapax:BAAALgAECgEJAQAAAA==.Bigtac:BAABLgAECn8mAAMKAAgJVxzxBAA4AghoDAAABwBHAGkMAAAHAFkAawwAAAYARwBqDAAABQBWAGwMAAAEAEIAbQwAAAEATADqDAAABQBGAG4MAAADAD4ACgAICVcc8QQAOAIIaAwAAAYARwBpDAAABgBZAGsMAAAGAEcAagwAAAUAVgBsDAAABABCAG0MAAABAEwA6gwAAAUARgBuDAAAAwA+AAsAAgneBzaZAFwAAmgMAAABACMAaQwAAAEABAAAAA==.Binggus:BAAALgAECgUJCgABLgAECgkJGgAMAEQjAA==.',
Bl='Blabbybootze:BAAALgADCgEJAQAAAA==.Bladelight:BAAALgAECgUJBgAAAA==.Blighte:BAAALgADCgQJBAABLgAECggJIQANAIIkAA==.Blightfangs:BAABLgAECn8jAAIBAAgJFxD0UwB3AQhoDAAABwAxAGkMAAAFADkAawwAAAQAKgBqDAAABgA5AGwMAAAEACYAbQwAAAEAEQDqDAAABwA5AG4MAAABABgAAQAICRcQ9FMAdwEIaAwAAAcAMQBpDAAABQA5AGsMAAAEACoAagwAAAYAOQBsDAAABAAmAG0MAAABABEA6gwAAAcAOQBuDAAAAQAYAAAA.Blindnautdef:BAABLgAECn8pAAIEAAgJmRC3NwBhAQhoDAAABgArAGkMAAAGAD4AawwAAAYAMABqDAAABQAuAGwMAAAFADkAbQwAAAQADQDqDAAABgAhAG4MAAADACcABAAICZkQtzcAYQEIaAwAAAYAKwBpDAAABgA+AGsMAAAGADAAagwAAAUALgBsDAAABQA5AG0MAAAEAA0A6gwAAAYAIQBuDAAAAwAnAAAA.Bloodluna:BAAALgADCgUJBQAAAA==.',
Bo='Bobman:BAAALgADCgEJAQAAAA==.Bodakye:BAABLgAECn8aAAMOAAgJ0BzEMwDgAQhoDAAABABCAGkMAAADAFIAawwAAAMAUABqDAAAAwBKAGwMAAADAD0AbQwAAAIATwDqDAAABgBTAG4MAAACAD4ADgAICdAcxDMA4AEIaAwAAAMAQgBpDAAAAwBSAGsMAAADAFAAagwAAAMASgBsDAAAAwA9AG0MAAACAE8A6gwAAAUAUwBuDAAAAgA+AAgAAgm0AQ6BAEMAAmgMAAABAAQA6gwAAAEABAAAAA==.Bonkz:BAAALgAECgMJAwAAAA==.Boomtip:BAAALgADCgMJAwAAAA==.Boon:BAAALgADCgYJCQAAAA==.Bordolor:BAAALgADCgYJCQAAAA==.Bowsa:BAAALgAECgkJAQAAAA==.',
Br='Brethathes:BAAALgAECggJCAAAAA==.Brudda:BAAALgADCgUJBQAAAA==.',
Bu='Bubblebun:BAAALgAECgMJBgAAAA==.Bungerhole:BAAALgAECggJEwAAAA==.Butane:BAAALgADCgIJAgAAAA==.',
Ca='Cainn:BAAALgAECgYJBwAAAA==.Cap:BAAALgADCgEJAQABLgAFFAMJCQABAMkYAA==.Capriestsun:BAAALgAFFAIJAgAAAA==.Carridin:BAAALgADCgMJAwAAAA==.Cass:BAAALgAECgEJAQAAAA==.',
Ce='Cernunon:BAAALgADCgEJAQAAAA==.',
Ch='Chaosdemon:BAABLgAECn8fAAIEAAkJOA4OLgCIAQloDAAABQAqAGkMAAAEACMAawwAAAQAIwBqDAAAAwAcAGwMAAADACwAbQwAAAIAIwDqDAAABgAsAG4MAAADACQAbwwAAAEAEQAEAAkJOA4OLgCIAQloDAAABQAqAGkMAAAEACMAawwAAAQAIwBqDAAAAwAcAGwMAAADACwAbQwAAAIAIwDqDAAABgAsAG4MAAADACQAbwwAAAEAEQAAAA==.Chapelgnome:BAAALgAECgIJAgABLgAECggJJQAPAPYPAA==.Charlottea:BAAALgAECgYJDQAAAA==.Chemdra:BAAALgAECgcJEwAAAA==.Chipmonkey:BAAALgADCgMJAwABLgAECggJHgANAJ4NAA==.Chiptime:BAABLgAECn8eAAINAAgJng3DPgAkAQhoDAAABQAjAGkMAAAFACcAawwAAAUAPwBqDAAABAAwAGwMAAAEAB0AbQwAAAEACQDqDAAABQAsAG4MAAABAAkADQAICZ4Nwz4AJAEIaAwAAAUAIwBpDAAABQAnAGsMAAAFAD8AagwAAAQAMABsDAAABAAdAG0MAAABAAkA6gwAAAUALABuDAAAAQAJAAEuAAQKCAkeAA0Ang0A.Chomby:BAAALgAECgEJAQAAAA==.Chriifrio:BAAALgADCgQJBAAAAA==.Chromosomes:BAAALgAECgQJBAAAAA==.Chud:BAAALgAECgQJBgAAAA==.Chudsworth:BAAALgADCgYJCQAAAA==.Chunguhlumpo:BAAALgAECgEJAwAAAA==.',
Ci='Cinnamóróll:BAABLgAECn8WAAIQAAgJOAY3FgBpAQhoDAAAAwALAGkMAAADABoAawwAAAMAHwBqDAAAAwAXAGwMAAADAAkAbQwAAAIAEgDqDAAABAAIAG4MAAABAAQAEAAICTgGNxYAaQEIaAwAAAMACwBpDAAAAwAaAGsMAAADAB8AagwAAAMAFwBsDAAAAwAJAG0MAAACABIA6gwAAAQACABuDAAAAQAEAAAA.',
Cl='Clairity:BAAALgAECgMJAwAAAA==.Cleru:BAABLgAECn8eAAMRAAgJlBJkPQCRAQhoDAAABQA9AGkMAAAGAEIAawwAAAUANQBqDAAAAwA1AGwMAAACADQAbQwAAAIAGQDqDAAABQA+AG4MAAACAAsAEQAICZQSZD0AkQEIaAwAAAQAPQBpDAAABgBCAGsMAAAFADUAagwAAAMANQBsDAAAAgA0AG0MAAACABkA6gwAAAUAPgBuDAAAAgALABIAAQmnAxQaACUAAWgMAAABAAkAAAA=.Cletus:BAAALgADCgcJAgAAAA==.',
Co='Coa:BAAALgAECgkJDAAAAA==.Cocoon:BAABLgAFFH8FAAMTAAQJ3gcHGADOAARoDAAAAQAYAGkMAAABAAcAawwAAAIAAADqDAAAAQAwABMABAneBwcYAM4ABGgMAAABABgAaQwAAAEABwBrDAAAAQAAAOoMAAABADAAFAABCawOESEASQABawwAAAEAJQAAAA==.Comanderkush:BAAALgADCgMJAwAAAA==.Corita:BAAALgAECgIJAgAAAA==.Cowboi:BAAALgADCgMJAwAAAA==.Cowhealer:BAABLgAECn8hAAMNAAgJgiThBAAXAwhoDAAABgBgAGkMAAAGAF8AawwAAAUAWgBqDAAAAwBcAGwMAAADAFsAbQwAAAIAXADqDAAABQBdAG4MAAADAF8ADQAICYIk4QQAFwMIaAwAAAYAYABpDAAABgBfAGsMAAAFAFoAagwAAAMAXABsDAAAAwBbAG0MAAACAFwA6gwAAAUAXQBuDAAAAgBfABUAAQlPBRCBAC8AAW4MAAABAA0AAAA=.',
Cr='Creamypies:BAAALgAECgEJAQAAAA==.Criticaltwo:BAAALgADCgIJAgAAAA==.Crockknight:BAAALgADCgYJBgAAAA==.Crossways:BAAALgAECgYJCQAAAA==.Cræftig:BAAALgADCgIJAgAAAA==.',
Cu='Cursecthree:BAAALgADCgEJAQAAAA==.Cutestxx:BAAALgAECgcJBwAAAA==.',
Cy='Cyxo:BAAALgADCgEJAQABLgAECgEJAgACAAAAAA==.',
Da='Daftxshade:BAAALgAECgQJBAAAAA==.Dandandan:BAAALgADCgMJAwAAAA==.Dapan:BAAALgADCgcJDQAAAA==.Dariaa:BAAALgAECgQJDAAAAA==.Darkcrusader:BAAALgAECgcJCgAAAA==.Darkheal:BAAALgADCgUJBQAAAA==.Darkladie:BAAALgADCgEJAQAAAA==.Darkshadows:BAAALgADCgcJCQAAAA==.Darthsyde:BAAALgAECgMJAwAAAA==.Dasdk:BAAALgAFFAIJAwAAAA==.Daspriest:BAAALgADCgYJDQABLgAFFAIJAwACAAAAAA==.',
De='Deadergriff:BAAALgAECgYJCgAAAA==.Deadhippycb:BAAALgAECgQJBAAAAA==.Deadhippyxy:BAAALgAECgEJAQAAAA==.Deadicated:BAAALgAECgYJDwAAAA==.Deadsies:BAAALgADCgIJAgABLgAECgUJCQACAAAAAA==.Delan:BAAALgAECgQJBQAAAA==.Delveknight:BAAALgADCgYJBgABLgAECgcJFwARAHUdAA==.Demoncox:BAAALgADCgMJAgAAAA==.Demondoc:BAAALgAECgcJCwAAAA==.Desunaito:BAACLgAFFH8SAAISAAUJpiA9AACGAQVoDAAABQBgAGkMAAAFAFcAawwAAAMAOgBqDAAAAQBQAOoMAAAEAFsAEgAFCaYgPQAAhgEFaAwAAAUAYABpDAAABQBXAGsMAAADADoAagwAAAEAUADqDAAABABbAC4ABAp/IgACEgAJCTEltQAAOQMAEgAJCTEltQAAOQMAAAA=.Devious:BAAALgADCgEJAQAAAA==.',
Dh='Dhzilong:BAACLgAFFH8KAAIEAAUJWBMfKwAPAQVoDAAABABCAGkMAAABADUAawwAAAEAAwBqDAAAAQAaAOoMAAADAEoABAAFCVgTHysADwEFaAwAAAQAQgBpDAAAAQA1AGsMAAABAAMAagwAAAEAGgDqDAAAAwBKAC4ABAp/GwADBAAICUchSzgAFAIABAAHCQwgSzgAFAIAFgAFCY0kjx4AygEAAAA=.',
Di='Diddlefiddle:BAAALgAECgQJBwAAAA==.Dihcum:BAAALgAECgEJAQAAAA==.Dimonologist:BAAALgAECgEJAQAAAA==.Dinpala:BAAALgADCgUJBQAAAA==.Dirtycow:BAAALgAECgQJBAAAAA==.',
Dk='Dkzilong:BAAALgAFFAIJAgABLgAFFAUJCgAEAFgTAA==.',
Do='Docholy:BAAALgAECgUJBQAAAA==.Dockson:BAAALgAECgMJAwAAAA==.Docwyle:BAABLgAECn8XAAMXAAgJnxHiOwB9AQhoDAAABAAvAGkMAAAEACoAawwAAAMAKgBqDAAAAgA6AGwMAAACAEcAbQwAAAIACADqDAAABABLAG4MAAACABoAFwAICZ8R4jsAfQEIaAwAAAQALwBpDAAABAAqAGsMAAADACoAagwAAAIAOgBsDAAAAgBHAG0MAAABAAgA6gwAAAQASwBuDAAAAgAaABgAAQm2AtJyADMAAW0MAAABAAYAAAA=.Doobyia:BAAALgADCgEJAQAAAA==.Dorki:BAAALgAECgEJAgAAAA==.Dorlanlemeth:BAAALgAECgYJCAAAAA==.Dormist:BAAALgADCgcJCgABLgAECgkJFQAYAE8SAA==.',
Dr='Dracnogard:BAAALgAECgYJCgAAAA==.Dracowulf:BAAALgAECgcJDwAAAA==.Dragonx:BAABLgAECn8gAAIOAAgJBw7nQwCgAQhoDAAABwAnAGkMAAAGACEAawwAAAYAPQBqDAAAAgAnAGwMAAADACAAbQwAAAEAGADqDAAABgApAG4MAAABABEADgAICQcO50MAoAEIaAwAAAcAJwBpDAAABgAhAGsMAAAGAD0AagwAAAIAJwBsDAAAAwAgAG0MAAABABgA6gwAAAYAKQBuDAAAAQARAAAA.Drakos:BAAALgAECgEJAQAAAA==.Drakowolf:BAABLgAECn8nAAIZAAgJCQS7CgD5AAhoDAAABwAGAGkMAAAHAA8AawwAAAYADwBqDAAABQAPAGwMAAAFAAkAbQwAAAEACQDqDAAABgAHAG4MAAACAAgAGQAICQkEuwoA+QAIaAwAAAcABgBpDAAABwAPAGsMAAAGAA8AagwAAAUADwBsDAAABQAJAG0MAAABAAkA6gwAAAYABwBuDAAAAgAIAAAA.Drenz:BAAALgADCgEJAQAAAA==.Dreorge:BAAALgAFFAMJBAAAAA==.Dreuceratops:BAAALgAECgMJAwAAAA==.Drewceratops:BAABLgAECn8mAAIHAAkJlBPTHQAfAgloDAAABgBMAGkMAAAGAEwAawwAAAYALwBqDAAABQApAGwMAAAFAD0AbQwAAAEAJwDqDAAABAAWAG4MAAAEADcAbwwAAAEAFQAHAAkJlBPTHQAfAgloDAAABgBMAGkMAAAGAEwAawwAAAYALwBqDAAABQApAGwMAAAFAD0AbQwAAAEAJwDqDAAABAAWAG4MAAAEADcAbwwAAAEAFQAAAA==.Driis:BAAALgADCgcJBwAAAA==.Drimchi:BAAALgAFFAMJAwAAAA==.Drizro:BAAALgADCgIJAgAAAA==.Drk:BAAALgAECgEJAQAAAA==.Dromash:BAABLgAECn8VAAMYAAkJTxLaBQCjAQloDAAAAgAvAGkMAAACADkAawwAAAIAOABqDAAAAQAzAGwMAAACADAAbQwAAAIAGQDqDAAABgA8AG4MAAADADMAbwwAAAEAGwAYAAgJLxPaBQCjAQhoDAAAAgAvAGkMAAACADkAawwAAAIAOABqDAAAAQAzAGwMAAACADAAbQwAAAIAGQDqDAAABQA5AG4MAAACADMAGgADCd8PNg0AyQAD6gwAAAEAPABuDAAAAQAhAG8MAAABABsAAAA=.Druidyhealz:BAAALgAECgMJAwABLgAECgcJDwACAAAAAA==.',
['Då']='Dårius:BAAALgAECgYJEQAAAA==.',
Ea='Eaterofpaint:BAAALgAECgYJDgAAAA==.',
Ef='Effloria:BAAALgAECgkJEwAAAA==.Efrideet:BAAALgADCgEJAQAAAA==.',
El='Elegia:BAACLgAFFH8OAAIXAAUJrw1FMAAVAQVoDAAABAA0AGkMAAAEABgAawwAAAIAGABqDAAAAQAHAOoMAAADACcAFwAFCa8NRTAAFQEFaAwAAAQANABpDAAABAAYAGsMAAACABgAagwAAAEABwDqDAAAAwAnAC4ABAp/JwADFwAJCUkbIxkAvgIAFwAJCUkbIxkAvgIAGAABCQAABWYAQwAAAAA=.Elerianor:BAAALgAECgYJDgAAAA==.Ellektra:BAAALgADCgUJBQAAAA==.',
Em='Emadiropilo:BAAALgAECgEJAQAAAA==.Emakaa:BAAALgAECgYJBwAAAA==.',
En='Enash:BAAALgAECgQJBwAAAA==.Engvald:BAAALgADCgUJBQAAAA==.Enjoi:BAAALgAECgEJAQABLgAFFAEJAQACAAAAAA==.',
Er='Eretin:BAAALgADCgEJAQAAAA==.Erismorn:BAABLgAECn8fAAQMAAcJCx1cCwCpAQdoDAAABgBYAGkMAAAGAE4AawwAAAUATgBqDAAABAApAGwMAAADAFQAbQwAAAEAGgDqDAAABgBYAAwABgmcG1wLAKkBBmgMAAAEAFgAaQwAAAUATgBrDAAABABOAGoMAAAEACkAbAwAAAIAVADqDAAAAQAWAAQABQnTE29UAAYBBWgMAAACAEYAaQwAAAEAOgBsDAAAAQAIAG0MAAABABoA6gwAAAUAWAAWAAEJ4RADcAA1AAFrDAAAAQArAAAA.',
Eu='Eudi:BAAALgAECgEJAgAAAA==.',
Ev='Eventhorizòn:BAAALgAECggJDwAAAA==.Evilhoe:BAAALgADCgUJBQAAAA==.Evocation:BAAALgAECggJDgAAAA==.Evoextoons:BAAALgADCgYJDAAAAA==.',
Fa='Fallen:BAAALgAECgYJDgAAAA==.Fallingvoid:BAABLgAECn9gAAIEAAkJJiQZAgC3AwloDAAACgBiAGkMAAAMAGAAawwAAAsAYQBqDAAACwBdAGwMAAAKAFwAbQwAAAoAVgDqDAAADwBhAG4MAAAJAGEAbwwAAAgASwAEAAkJJiQZAgC3AwloDAAACgBiAGkMAAAMAGAAawwAAAsAYQBqDAAACwBdAGwMAAAKAFwAbQwAAAoAVgDqDAAADwBhAG4MAAAJAGEAbwwAAAgASwAAAA==.Fatchungus:BAAALgAFFAMJBAAAAA==.Fatherben:BAABLgAECn8XAAIEAAYJVBU7QgA7AQZoDAAABQBFAGkMAAAHAD4AawwAAAYAOABqDAAAAQA/AGwMAAABAAQA6gwAAAMATwAEAAYJVBU7QgA7AQZoDAAABQBFAGkMAAAHAD4AawwAAAYAOABqDAAAAQA/AGwMAAABAAQA6gwAAAMATwAAAA==.Fatmagus:BAAALgAECgcJBgAAAA==.Favio:BAAALgAECgEJAQAAAA==.',
Fe='Fellbian:BAAALgADCgcJCwAAAA==.Fentanyahu:BAAALgAECgYJBgAAAA==.Ferozz:BAABLgAECn8rAAIIAAgJ5hwnAwA2AghoDAAACABKAGkMAAAHAFUAawwAAAYAVQBqDAAABABOAGwMAAAFAD0AbQwAAAQASgDqDAAABgBWAG4MAAADADIACAAICeYcJwMANgIIaAwAAAgASgBpDAAABwBVAGsMAAAGAFUAagwAAAQATgBsDAAABQA9AG0MAAAEAEoA6gwAAAYAVgBuDAAAAwAyAAAA.',
Fi='Fiercetaco:BAAALgADCgEJAQAAAA==.Finaliter:BAABLgAECn8pAAIHAAgJMCKbEgBvAghoDAAABgBhAGkMAAAGAFQAawwAAAYAVABqDAAABQBUAGwMAAAFAFoAbQwAAAIAUADqDAAACQBTAG4MAAACAFsABwAICTAimxIAbwIIaAwAAAYAYQBpDAAABgBUAGsMAAAGAFQAagwAAAUAVABsDAAABQBaAG0MAAACAFAA6gwAAAkAUwBuDAAAAgBbAAAA.Finatar:BAAALgADCgcJCwAAAA==.Fiora:BAABLgAECn8SAAIEAAcJKx86KQBdAgdoDAAAAwBHAGkMAAADAFQAawwAAAMAVgBqDAAAAwBOAGwMAAADAFsAbQwAAAEAQgDqDAAAAgBOAAQABwkrHzopAF0CB2gMAAADAEcAaQwAAAMAVABrDAAAAwBWAGoMAAADAE4AbAwAAAMAWwBtDAAAAQBCAOoMAAACAE4AAAA=.Fitz:BAAALgADCgEJAQAAAA==.Fiveyears:BAAALgADCgEJAQAAAA==.',
Fk='Fknutmcgee:BAAALgAECgUJBQAAAA==.',
Fl='Flinti:BAAALgAECgUJCQAAAA==.Floggy:BAAALgAECgYJEwAAAA==.',
Fo='Forsight:BAABLgAECn8XAAIRAAgJVxQpQQCEAQhoDAAABAAvAGkMAAAEAEkAawwAAAQAMQBqDAAAAwAwAGwMAAADADcAbQwAAAEAJADqDAAAAwA5AG4MAAABAC4AEQAICVcUKUEAhAEIaAwAAAQALwBpDAAABABJAGsMAAAEADEAagwAAAMAMABsDAAAAwA3AG0MAAABACQA6gwAAAMAOQBuDAAAAQAuAAAA.',
Fr='Fracker:BAAALgAECgcJCAAAAA==.Frankzzorz:BAABLgAECn8qAAMTAAgJER20DACHAghoDAAABQBRAGkMAAAGAEUAawwAAAYATgBqDAAABgBWAGwMAAAFAFAAbQwAAAQAMQDqDAAABwBXAG4MAAADAD4AEwAICREdtAwAhwIIaAwAAAUAUQBpDAAABgBFAGsMAAAGAE4AagwAAAYAVgBsDAAABABQAG0MAAADADEA6gwAAAcAVwBuDAAAAwA+ABQAAglFICw0AL0AAmwMAAABAFMAbQwAAAEAUgAAAA==.Fremder:BAACLgAFFH8IAAIFAAMJgRY8EgD8AANoDAAABABYAGkMAAACABsA6gwAAAIAOAAFAAMJgRY8EgD8AANoDAAABABYAGkMAAACABsA6gwAAAIAOAAuAAQKfyoAAgUACAn2HC8FAFYCAAUACAn2HC8FAFYCAAAA.Fresher:BAABLgAECn8VAAIRAAUJyxydWwA6AQVoDAAABQBOAGkMAAAGAFkAawwAAAQAUgDqDAAABQBbAG4MAAABABoAEQAFCcscnVsAOgEFaAwAAAUATgBpDAAABgBZAGsMAAAEAFIA6gwAAAUAWwBuDAAAAQAaAAAA.Freyjen:BAAALgADCgkJGAABLgAECgcJCgACAAAAAA==.Froboz:BAAALgADCgYJCQAAAA==.Frogevil:BAAALgAECgYJCgAAAA==.Frogtree:BAAALgADCgUJBQAAAA==.Frostygirl:BAABLgAECn8hAAIBAAgJPRB6QACtAQhoDAAABgAwAGkMAAAFACYAawwAAAUAKgBqDAAABQApAGwMAAAEADMAbQwAAAEAEwDqDAAABgAxAG4MAAABACkAAQAICT0QekAArQEIaAwAAAYAMABpDAAABQAmAGsMAAAFACoAagwAAAUAKQBsDAAABAAzAG0MAAABABMA6gwAAAYAMQBuDAAAAQApAAAA.',
Fu='Funeral:BAACLgAFFH8bAAMYAAcJLBpzAQB1AQdoDAAABQBHAGkMAAAFAE8AawwAAAUAYQBqDAAABABEAGwMAAABABoAbQwAAAEAIwDqDAAABgBdABgABAm3HXMBAHUBBGkMAAAFAE8AawwAAAUAYQBtDAAAAQAjAOoMAAAGAF0AFwADCRYTczAAsgADaAwAAAUARwBqDAAABABEAGwMAAABABoALgAECn8rAAQYAAkJMyM+BAChAgAYAAcJ0iA+BAChAgAXAAgJ4BjpRAD9AQAaAAEJCBOAKQBMAAAAAA==.',
['Fà']='Fàstïk:BAAALgAECgEJAQAAAA==.',
Ga='Gallory:BAAALgAECgcJDQAAAA==.Gareeshala:BAAALgAECgIJAgAAAA==.',
Ge='Geomancer:BAAALgADCgQJBAAAAA==.',
Gi='Gimmedatmouf:BAAALgAFFAMJAwAAAA==.Gimmedatneck:BAABLgAECn8VAAMbAAgJTSMfEACtAQhoDAAABQBdAGkMAAADAGIAawwAAAMAYgBqDAAAAgBhAGwMAAADAF0AbQwAAAEAUwDqDAAAAwBdAG4MAAABAEcAGwAICU0jHxAArQEIaAwAAAUAXQBpDAAAAwBiAGsMAAACAGIAagwAAAIAYQBsDAAAAwBdAG0MAAABAFMA6gwAAAMAXQBuDAAAAQBHABwAAQk2Et4cAEMAAWsMAAABAC4AAAA=.Gingy:BAAALgADCgYJCwAAAA==.',
Gl='Glead:BAAALgAECggJEwAAAA==.',
Gn='Gneeduh:BAAALgAECgEJAQAAAA==.',
Go='Gobknight:BAAALgADCggJCAAAAA==.Goldina:BAAALgAECgEJAQAAAA==.Gooklover:BAAALgAECgQJBQAAAA==.Gosupal:BAAALgADCgYJBgAAAA==.',
Gr='Gracious:BAAALgAECgEJAQAAAA==.Graegor:BAAALgADCgEJAQAAAA==.Grastim:BAAALgAECgQJBQAAAA==.Greenfanta:BAAALgADCgYJEAAAAA==.Grill:BAAALgADCgEJAQAAAA==.Grinkle:BAABLgAECn8nAAIdAAgJWhIZJQCgAQhoDAAABgAvAGkMAAAGAEoAawwAAAYANABqDAAABQAzAGwMAAAFACwAbQwAAAQAGgDqDAAABAAiAG4MAAADACwAHQAICVoSGSUAoAEIaAwAAAYALwBpDAAABgBKAGsMAAAGADQAagwAAAUAMwBsDAAABQAsAG0MAAAEABoA6gwAAAQAIgBuDAAAAwAsAAAA.Gripopotamus:BAAALgADCgYJBwAAAA==.Gristle:BAAALgADCgkJFQAAAA==.',
Gu='Gunner:BAAALgAECgQJBQABLgAECgQJCgACAAAAAA==.',
Ha='Hakaishaz:BAAALgADCgMJAwAAAA==.Halfwatt:BAAALgAECgQJCwAAAA==.Hamaddor:BAAALgAECgYJBgAAAA==.Handen:BAAALgADCggJCAAAAA==.Haraldsson:BAABLgAECn8ZAAIHAAgJ/BP1PgCTAQhoDAAAAgBJAGkMAAADAEYAawwAAAQANgBqDAAABABBAGwMAAAFACwAbQwAAAEAKgDqDAAABQA4AG4MAAABAA4ABwAICfwT9T4AkwEIaAwAAAIASQBpDAAAAwBGAGsMAAAEADYAagwAAAQAQQBsDAAABQAsAG0MAAABACoA6gwAAAUAOABuDAAAAQAOAAAA.Harmony:BAAALgADCgcJCgAAAA==.Harrin:BAAALgADCgYJDAAAAA==.Harrydabs:BAABLgAECn8aAAMMAAkJRCNNAACDAwloDAAABABkAGkMAAAEAFYAawwAAAMAYQBqDAAAAwBiAGwMAAACAF4AbQwAAAMAXgDqDAAABABfAG4MAAACAEAAbwwAAAEAWQAMAAkJRCNNAACDAwloDAAAAwBkAGkMAAADAFYAawwAAAMAYQBqDAAAAwBiAGwMAAACAF4AbQwAAAIAXgDqDAAAAwBfAG4MAAACAEAAbwwAAAEAWQAWAAQJJRB4PwD+AARoDAAAAQBNAGkMAAABABMAbQwAAAEAIQDqDAAAAQAjAAAA.Haru:BAAALgAECgYJDwAAAA==.Harvaal:BAAALgAECgUJBQAAAA==.Hasaro:BAABLgAECn8XAAIJAAkJRRLJDQCmAQloDAAAAgAtAGkMAAADADQAawwAAAMAPwBqDAAAAwAsAGwMAAADADMAbQwAAAEAGwDqDAAABQBFAG4MAAACACkAbwwAAAEAFQAJAAkJRRLJDQCmAQloDAAAAgAtAGkMAAADADQAawwAAAMAPwBqDAAAAwAsAGwMAAADADMAbQwAAAEAGwDqDAAABQBFAG4MAAACACkAbwwAAAEAFQAAAA==.Havokvacano:BAABLgAECn8WAAIHAAgJ/BIDOQClAQhoDAAAAgA3AGkMAAACAC4AawwAAAIANgBqDAAAAgBBAGwMAAAEADsAbQwAAAMAHQDqDAAABAA2AG4MAAADACcABwAICfwSAzkApQEIaAwAAAIANwBpDAAAAgAuAGsMAAACADYAagwAAAIAQQBsDAAABAA7AG0MAAADAB0A6gwAAAQANgBuDAAAAwAnAAAA.',
He='Healmachine:BAAALgAECgQJBgAAAA==.Hellbrringer:BAAALgAECgQJBAAAAA==.Helzerx:BAAALgAECgYJBgABLgAECgkJLgAFABkcAA==.',
Ho='Hoely:BAAALgAECgEJAQAAAA==.Hotsordots:BAAALgAECggJCwAAAA==.Hounskul:BAABLgAECn8gAAIXAAkJogeTRABgAQloDAAABQAgAGkMAAAEABUAawwAAAQAFgBqDAAAAwATAGwMAAAEABQAbQwAAAIAEADqDAAABgATAG4MAAADAA0AbwwAAAEACQAXAAkJogeTRABgAQloDAAABQAgAGkMAAAEABUAawwAAAQAFgBqDAAAAwATAGwMAAAEABQAbQwAAAIAEADqDAAABgATAG4MAAADAA0AbwwAAAEACQAAAA==.',
Hu='Hugealien:BAAALgADCgIJAgAAAA==.Hungchungus:BAAALgAECgEJAgAAAA==.Hungwaylo:BAAALgADCgIJAgAAAA==.',
Hw='Hwere:BAAALgAECgUJBgAAAA==.',
Hy='Hypnoticpal:BAAALgAECgkJBwAAAA==.Hystëria:BAACLgAFFH8JAAIRAAMJaRW9VADwAANoDAAABQAxAGkMAAACAEwA6gwAAAIAJQARAAMJaRW9VADwAANoDAAABQAxAGkMAAACAEwA6gwAAAIAJQAuAAQKfzEAAhEACAlyIJMRAHwCABEACAlyIJMRAHwCAAAA.Hyunlix:BAAALgADCgUJBQAAAA==.',
Ia='Iammoo:BAAALgAECgEJAQAAAA==.',
Ig='Igotkappa:BAAALgADCgMJAwAAAA==.Igotyourback:BAAALgAECggJCAAAAA==.',
Il='Ilydris:BAAALgADCgQJBAAAAA==.',
Im='Imadruid:BAAALgADCgQJBAAAAA==.',
Io='Iolyte:BAAALgAECgYJDQAAAA==.',
Ir='Iridellis:BAAALgAFFAEJAQAAAA==.',
Is='Ispankutank:BAAALgADCgQJBAAAAA==.',
It='Itssofluffy:BAABLgAECn8fAAQeAAgJjBRLDABhAQhoDAAABQA+AGkMAAAEAD8AawwAAAUANQBqDAAAAwA4AGwMAAADAEEAbQwAAAEAGgDqDAAABwA+AG4MAAADACIAHgAICUESSwwAYQEIaAwAAAIAOgBpDAAAAgA/AGsMAAADACMAagwAAAIAOABsDAAAAgA1AG0MAAABABoA6gwAAAQANgBuDAAAAwAiAAkABQkGF9sTADIBBWgMAAADAD4AaQwAAAEAMwBrDAAAAgA1AGwMAAABAEEA6gwAAAMAPgAVAAIJUgnuXAAxAAJpDAAAAQAXAGoMAAABABkAAAA=.Itwon:BAAALgADCgcJEwAAAA==.',
Iz='Izzelda:BAAALgADCgQJBAAAAA==.',
Ja='Jacus:BAAALgAECgEJAQAAAA==.Jahumc:BAAALgAECgEJAQAAAA==.Jaycers:BAABLgAECn8dAAMfAAkJ8B9rAQDQAgloDAAABABOAGkMAAAEAGEAawwAAAQAXABqDAAAAwBaAGwMAAADAFQAbQwAAAQAWADqDAAABABZAG4MAAABAD8AbwwAAAIAOgAfAAkJ8B9rAQDQAgloDAAABABOAGkMAAAEAGEAawwAAAQAXABqDAAAAwBaAGwMAAADAFQAbQwAAAQAWADqDAAAAwBZAG4MAAABAD8AbwwAAAIAOgAgAAEJ2AIAnwAqAAHqDAAAAQAHAAAA.Jayclark:BAAALgADCgcJCgAAAA==.',
Je='Jessiriusrex:BAAALgADCgEJAQAAAA==.',
Jo='Joemomma:BAAALgAECgYJDAAAAA==.Jokestarfist:BAAALgAECgQJDwAAAA==.',
Jt='Jtheshadow:BAAALgAECgEJAQAAAA==.',
Ju='Junachan:BAAALgAECgMJBQAAAA==.Jurichan:BAAALgAECgMJCQAAAA==.',
Ka='Kaitokit:BAAALgAECgUJCQAAAA==.Kajamando:BAABLgAECn8eAAIWAAgJ7gctFwA4AQhoDAAABQAZAGkMAAAFAB0AawwAAAUAFABqDAAABAAlAGwMAAAEABUAbQwAAAEACwDqDAAABQAUAG4MAAABAA4AFgAICe4HLRcAOAEIaAwAAAUAGQBpDAAABQAdAGsMAAAFABQAagwAAAQAJQBsDAAABAAVAG0MAAABAAsA6gwAAAUAFABuDAAAAQAOAAAA.Kalith:BAABLgAECn8WAAIQAAgJ+wLvIAAFAQhoDAAAAwAGAGkMAAADAAkAawwAAAMADQBqDAAAAwATAGwMAAADAAgAbQwAAAMABADqDAAAAwAIAG4MAAABAAMAEAAICfsC7yAABQEIaAwAAAMABgBpDAAAAwAJAGsMAAADAA0AagwAAAMAEwBsDAAAAwAIAG0MAAADAAQA6gwAAAMACABuDAAAAQADAAAA.Kallydots:BAAALgADCgcJDQAAAA==.Kayllina:BAABLgAECn8bAAIRAAgJywOcZwAgAQhoDAAABAAHAGkMAAAEAA8AawwAAAQADABqDAAABAAPAGwMAAADAAkAbQwAAAMACADqDAAABAAJAG4MAAABAAUAEQAICcsDnGcAIAEIaAwAAAQABwBpDAAABAAPAGsMAAAEAAwAagwAAAQADwBsDAAAAwAJAG0MAAADAAgA6gwAAAQACQBuDAAAAQAFAAAA.Kayotic:BAABLgAECn8aAAIWAAYJGgXzJADDAAZoDAAABgALAGkMAAAGABcAawwAAAQACgBqDAAAAgAJAGwMAAADAA0A6gwAAAUABgAWAAYJGgXzJADDAAZoDAAABgALAGkMAAAGABcAawwAAAQACgBqDAAAAgAJAGwMAAADAA0A6gwAAAUABgAAAA==.Kayww:BAAALgAECgIJAgAAAA==.',
Ke='Keinarra:BAAALgADCgMJBgAAAA==.Kell:BAAALgADCgcJCAAAAA==.Kelmorphic:BAABLgAECn8VAAIMAAkJkRtPAgBlAgloDAAAAwBXAGkMAAADAEgAawwAAAIATQBqDAAAAwBPAGwMAAACAEAAbQwAAAEAOgDqDAAAAwBTAG4MAAADAD4AbwwAAAEAOAAMAAkJkRtPAgBlAgloDAAAAwBXAGkMAAADAEgAawwAAAIATQBqDAAAAwBPAGwMAAACAEAAbQwAAAEAOgDqDAAAAwBTAG4MAAADAD4AbwwAAAEAOAAAAA==.Keropikapika:BAAALgADCgUJBQAAAA==.',
Kh='Khaali:BAAALgAECgEJAgAAAA==.',
Ki='Kikiana:BAAALgAECgQJBwABLgAECggJJQAhAKUhAA==.Kikstyx:BAAALgADCgYJCAAAAA==.Killerxd:BAAALgAECgcJEQAAAA==.Killesea:BAAALgADCgcJDAAAAA==.Kittfisto:BAABLgAECn8XAAIEAAgJ7hWsXgCFAQhoDAAABABWAGkMAAADAD4AawwAAAQAPABqDAAAAgAgAGwMAAADACsAbQwAAAEAKwDqDAAABAAzAG4MAAACAC0ABAAICe4VrF4AhQEIaAwAAAQAVgBpDAAAAwA+AGsMAAAEADwAagwAAAIAIABsDAAAAwArAG0MAAABACsA6gwAAAQAMwBuDAAAAgAtAAAA.',
Kn='Knitemare:BAAALgAECgEJAQAAAA==.',
Ko='Korivos:BAAALgADCgMJAwAAAA==.Kosmas:BAABLgAECn8VAAMLAAcJxxwaPQCwAQdoDAAABABWAGkMAAAEAFUAawwAAAQAQABqDAAAAwBWAGwMAAACADAA6gwAAAMARwBuDAAAAQBVAAsABwmfGho9ALABB2gMAAABADUAaQwAAAMAVQBrDAAAAwBAAGoMAAADAFYAbAwAAAIAMADqDAAAAgBHAG4MAAABAFUACgAECcsTlSUAqgAEaAwAAAMAVgBpDAAAAQAxAGsMAAABAB4A6gwAAAEAJAAAAA==.',
Kr='Krushgar:BAABLgAECn8UAAMRAAcJsRcDXQDbAQdoDAAAAwBJAGkMAAADADgAawwAAAMARgBqDAAAAwBDAGwMAAADAE4AbQwAAAEACADqDAAABABNABEABwmxFwNdANsBB2gMAAADAEkAaQwAAAMAOABrDAAAAwBGAGoMAAADAEMAbAwAAAMATgBtDAAAAQAIAOoMAAADAE0AEgABCbMQfRgAMwAB6gwAAAEAKgAAAA==.',
Ku='Kuchikopii:BAAALgADCgYJBgAAAA==.Kungfuelf:BAAALgADCgEJAQAAAA==.Kurookami:BAAALgADCgUJBQAAAA==.',
La='Lackluster:BAABLgAECn8fAAIBAAgJTQl+hgANAQhoDAAABQAmAGkMAAAFABcAawwAAAUAIQBqDAAABQAxAGwMAAADAA8AbQwAAAEABADqDAAABQAQAG4MAAACACIAAQAICU0JfoYADQEIaAwAAAUAJgBpDAAABQAXAGsMAAAFACEAagwAAAUAMQBsDAAAAwAPAG0MAAABAAQA6gwAAAUAEABuDAAAAgAiAAAA.Lamatrick:BAAALgAECgUJBwAAAA==.Lanadelslayy:BAAALgAECgMJBAAAAA==.Lasenza:BAAALgADCgQJBAAAAA==.Lavacoomer:BAAALgADCgYJBQAAAA==.',
Le='Lejosh:BAAALgAECgIJAgAAAA==.Lennon:BAAALgAECgkJBgAAAA==.Leona:BAAALgAECgYJCgAAAA==.Lethee:BAAALgAECgEJAgAAAA==.',
Li='Lilithamy:BAAALgADCgYJBgAAAA==.Lilthin:BAAALgAECgQJCAAAAA==.Liore:BAAALgAECgMJAwAAAA==.Lisathe:BAAALgAECgQJBQAAAA==.Littledude:BAAALgADCgQJBQAAAA==.Littlemorsel:BAAALgAECgkJDgAAAA==.',
Lo='Louthar:BAAALgADCgcJAQAAAA==.',
Lt='Ltdapperdan:BAAALgAECgEJAQAAAA==.',
Lu='Lucens:BAABLgAECn8aAAIgAAYJHgxdNAAIAQZoDAAABwApAGkMAAAGAB0AawwAAAYAJABqDAAAAgANAOoMAAAEAEAAbgwAAAEAAQAgAAYJHgxdNAAIAQZoDAAABwApAGkMAAAGAB0AawwAAAYAJABqDAAAAgANAOoMAAAEAEAAbgwAAAEAAQAAAA==.Lunagreed:BAAALgADCgUJBQAAAA==.Lurchn:BAABLgAECn8mAAIBAAkJzgeaVwBuAQloDAAABgAYAGkMAAAFABsAawwAAAYAFABqDAAABgAUAGwMAAACABkAbQwAAAEACgDqDAAABwAZAG4MAAAEABcAbwwAAAEAAQABAAkJzgeaVwBuAQloDAAABgAYAGkMAAAFABsAawwAAAYAFABqDAAABgAUAGwMAAACABkAbQwAAAEACgDqDAAABwAZAG4MAAAEABcAbwwAAAEAAQAAAA==.',
['Lú']='Lúná:BAAALgAECgUJBgAAAA==.',
Ma='Maggieaugers:BAABLgAECn8lAAIPAAgJ9g/WFgCWAQhoDAAABgApAGkMAAAGACoAawwAAAYAJgBqDAAABgA9AGwMAAAFABwAbQwAAAEAFADqDAAABQBaAG4MAAACABcADwAICfYP1hYAlgEIaAwAAAYAKQBpDAAABgAqAGsMAAAGACYAagwAAAYAPQBsDAAABQAcAG0MAAABABQA6gwAAAUAWgBuDAAAAgAXAAAA.Magicmech:BAAALgADCgcJDAAAAA==.Magivacano:BAAALgAECggJEQAAAA==.Mahnon:BAABLgAECn8VAAIOAAkJ8wb2TwAfAQloDAAAAgANAGkMAAABABEAawwAAAIADQBqDAAABAAcAGwMAAAFACAAbQwAAAEACQDqDAAAAwAZAG4MAAACAAgAbwwAAAEAFQAOAAkJ8wb2TwAfAQloDAAAAgANAGkMAAABABEAawwAAAIADQBqDAAABAAcAGwMAAAFACAAbQwAAAEACQDqDAAAAwAZAG4MAAACAAgAbwwAAAEAFQAAAA==.Mandril:BAAALgADCgEJAQAAAA==.Matas:BAAALgAECgQJBwAAAA==.Matias:BAAALgAECgEJAQAAAA==.',
Mc='Mcdeath:BAAALgADCgEJAQAAAA==.',
Me='Metalhedface:BAABLgAECn8YAAMKAAgJaBGeDQB2AQhoDAAABQBRAGkMAAAEAFAAawwAAAQANgBqDAAAAgA1AGwMAAACABcAbQwAAAEABADqDAAABQA2AG4MAAABAAsACgAHCeYTng0AdgEHaAwAAAIAUQBpDAAAAgBQAGsMAAACADQAagwAAAIANQBsDAAAAgAXAOoMAAADADYAbgwAAAEACwALAAUJ4BC/ZAAgAQVoDAAAAwArAGkMAAACAEMAawwAAAIANgBtDAAAAQAEAOoMAAACAC4AAAA=.',
Mi='Mikecoxwall:BAABLgAECn8oAAMBAAkJcg1NMgDfAQloDAAABgAYAGkMAAAGADoAawwAAAYALABqDAAABQAxAGwMAAAEACkAbQwAAAIABgDqDAAABwBAAG4MAAADABAAbwwAAAEAEgABAAkJcg1NMgDfAQloDAAABAAYAGkMAAAEADoAawwAAAQALABqDAAAAwAxAGwMAAACACkAbQwAAAIABgDqDAAABQBAAG4MAAADABAAbwwAAAEAEgAiAAYJ3wj9CgAqAQZoDAAAAgARAGkMAAACACAAawwAAAIAFABqDAAAAgAfAGwMAAACABMA6gwAAAIAFwAAAA==.Mikuru:BAAALgAECgEJAwAAAA==.Milena:BAAALgADCgEJAQAAAA==.Milov:BAAALgADCgUJBQAAAA==.Minarva:BAAALgAECgcJCgAAAA==.Misary:BAAALgAECgQJBAAAAA==.Mischeif:BAAALgAECgQJBAAAAA==.',
Mo='Mojomon:BAAALgADCgYJBgAAAA==.Moltganus:BAAALgAECgMJAwAAAA==.Monkeli:BAAALgAECgcJDQAAAA==.Monkitard:BAAALgAECgMJAwAAAA==.Monkryn:BAAALgAECgUJCAABLgAFFAUJDAAeAPYSAA==.Monkup:BAAALgAECgEJAQAAAA==.Moocifer:BAAALgAECgEJAQAAAA==.Moogrim:BAAALgADCgkJDgAAAA==.Moonsiand:BAACLgAFFH8LAAIQAAQJHgNoDgALAQRoDAAABAALAGkMAAADAAkAawwAAAIABwDqDAAAAgADABAABAkeA2gOAAsBBGgMAAAEAAsAaQwAAAMACQBrDAAAAgAHAOoMAAACAAMALgAECn8hAAQQAAgJXhNbDgDhAQAQAAgJXhNbDgDhAQAIAAEJqgFhmQAcAAAOAAEJjQA01wAKAAAAAA==.Moosafur:BAABLgAECn8bAAMJAAkJdxw5AwB0AgloDAAABABhAGkMAAAEAGAAawwAAAQAYQBqDAAABABfAGwMAAADAFMAbQwAAAIAXADqDAAABABhAG4MAAABAAcAbwwAAAEACgAJAAcJzCQ5AwB0AgdoDAAABABhAGkMAAAEAGAAawwAAAQAYQBqDAAABABfAGwMAAADAFMAbQwAAAIAXADqDAAABABhAB4AAgl5A8c1AC4AAm4MAAABAAcAbwwAAAEACgAAAA==.Mooshoe:BAAALgAECgEJAQAAAA==.Morphyr:BAAALgAECgYJBgAAAA==.Morrigån:BAAALgAECgIJAgAAAA==.Morvoult:BAAALgAECgEJAQAAAA==.Motgus:BAAALgAECgMJBQAAAA==.',
Ms='Mshottie:BAAALgAECgQJBgAAAA==.',
Mt='Mtngrounds:BAAALgADCgIJAgAAAA==.',
Mu='Murkt:BAAALgAECgEJAQAAAA==.Mutuusami:BAAALgAECgEJAgAAAA==.',
Mx='Mx:BAAALgAECgQJBgAAAA==.',
My='Myraine:BAAALgADCgYJBgAAAA==.Myway:BAAALgADCggJCwAAAA==.',
Na='Naari:BAABLgAECn8ZAAMLAAcJ/xK2LQAfAQdoDAAABQAzAGkMAAAFAD4AawwAAAUAMABqDAAAAwAyAGwMAAACAEAAbQwAAAEAEgDqDAAABAAtAAsABgnCEbYtAB8BBmgMAAAFADMAaQwAAAUAPgBrDAAABQAwAGoMAAADADIAbQwAAAEAEgDqDAAABAAtAAoAAQkvGbI5AEkAAWwMAAACAEAAAAA=.Naniwa:BAAALgAECgEJAQABLgAECggJFwAdAN8UAA==.Naoya:BAAALgADCgIJAgAAAA==.Narexia:BAABLgAECn8jAAIjAAYJNxxVCQCUAQZoDAAABwBbAGkMAAAGAEcAawwAAAYAOwBqDAAABQA8AGwMAAAEAEYA6gwAAAcAQwAjAAYJNxxVCQCUAQZoDAAABwBbAGkMAAAGAEcAawwAAAYAOwBqDAAABQA8AGwMAAAEAEYA6gwAAAcAQwAAAA==.Natureboyy:BAAALgADCgcJDAAAAA==.',
Ne='Nekuma:BAAALgAFFAIJAgABLgAFFAUJEgASAKYgAA==.Nellaa:BAAALgAECgcJCgAAAA==.',
Ni='Nightfury:BAAALgAECgcJDQAAAA==.Niklus:BAAALgAECgEJAQAAAA==.Nissanaltima:BAAALgADCgYJCQAAAA==.Nithilis:BAABLgAECn8rAAIGAAkJOBzTBgB0AgloDAAABwBcAGkMAAAHAFUAawwAAAcARQBqDAAABQBTAGwMAAADAD4AbQwAAAMANQDqDAAABgBcAG4MAAAEAEQAbwwAAAEANAAGAAkJOBzTBgB0AgloDAAABwBcAGkMAAAHAFUAawwAAAcARQBqDAAABQBTAGwMAAADAD4AbQwAAAMANQDqDAAABgBcAG4MAAAEAEQAbwwAAAEANAAAAA==.',
No='Noee:BAAALgADCgUJBQAAAA==.Nokkiewae:BAAALgADCgcJEgAAAA==.Nomadic:BAAALgADCgkJCQAAAA==.Nool:BAAALgADCgYJBQAAAA==.Nople:BAABLgAECn8fAAIBAAgJGBZKPgC0AQhoDAAABQBTAGkMAAAEAEQAawwAAAYARABqDAAABgA7AGwMAAADAC0AbQwAAAIAOgDqDAAABAA6AG4MAAABAA0AAQAICRgWSj4AtAEIaAwAAAUAUwBpDAAABABEAGsMAAAGAEQAagwAAAYAOwBsDAAAAwAtAG0MAAACADoA6gwAAAQAOgBuDAAAAQANAAAA.',
Nu='Nutellaa:BAAALgAFFAEJAQAAAA==.',
Ny='Nymueline:BAAALgADCgUJBQAAAA==.',
Ob='Obie:BAAALgAECgUJBgAAAA==.Oborax:BAEBLgAECn8bAAIHAAcJqRbjPACZAQdoDAAABQBJAGkMAAAFADoAawwAAAUAQgBqDAAABABcAGwMAAAEAD0AbQwAAAEAJADqDAAAAwA0AAcABwmpFuM8AJkBB2gMAAAFAEkAaQwAAAUAOgBrDAAABQBCAGoMAAAEAFwAbAwAAAQAPQBtDAAAAQAkAOoMAAADADQAAAA=.',
Od='Od:BAAALgAECgMJBAAAAA==.',
Ok='Okiro:BAAALgAECgMJAwAAAA==.Okoru:BAAALgADCgIJAgAAAA==.',
Ol='Oluun:BAAALgADCgQJBAAAAA==.',
Ot='Otmetka:BAAALgADCgcJAQAAAA==.',
Pa='Palapal:BAAALgAECgYJDgAAAA==.Paldi:BAABLgAECn8WAAIHAAgJORnQKwB0AghoDAAABABLAGkMAAAEAFIAawwAAAQAXABqDAAAAwBKAGwMAAACAFQAbQwAAAEAHwDqDAAAAwBQAG4MAAABAAUABwAICTkZ0CsAdAIIaAwAAAQASwBpDAAABABSAGsMAAAEAFwAagwAAAMASgBsDAAAAgBUAG0MAAABAB8A6gwAAAMAUABuDAAAAQAFAAEuAAUUAwkEAAIAAAAA.Papaozz:BAABLgAECn8WAAIbAAcJjwWWIgDwAAdoDAAABAALAGkMAAAEAAQAawwAAAQAEgBqDAAAAQALAGwMAAABABEA6gwAAAQAFgBuDAAABAAJABsABwmPBZYiAPAAB2gMAAAEAAsAaQwAAAQABABrDAAABAASAGoMAAABAAsAbAwAAAEAEQDqDAAABAAWAG4MAAAEAAkAAAA=.Pawcalypse:BAAALgAECgMJAwAAAA==.Paws:BAAALgAECgcJCwAAAA==.',
Pe='Perelia:BAABLgAECn8gAAIkAAcJrAskGgBtAQdoDAAABwA1AGkMAAAGAB0AawwAAAUAGABqDAAABAAZAGwMAAAEAB4AbQwAAAEADADqDAAABQAgACQABwmsCyQaAG0BB2gMAAAHADUAaQwAAAYAHQBrDAAABQAYAGoMAAAEABkAbAwAAAQAHgBtDAAAAQAMAOoMAAAFACAAAAA=.Pewpewqt:BAAALgAECgUJBgABLgAECgcJJwANACMZAA==.',
Pl='Plaguehammer:BAABLgAECn8VAAIRAAYJtwdNewD3AAZoDAAABgAMAGkMAAADABAAawwAAAMAGwBqDAAAAwASAGwMAAACABMA6gwAAAQAFQARAAYJtwdNewD3AAZoDAAABgAMAGkMAAADABAAawwAAAMAGwBqDAAAAwASAGwMAAACABMA6gwAAAQAFQAAAA==.Playstationn:BAAALgADCgUJBQAAAA==.',
Pn='Pnwbambii:BAAALgADCgIJAgAAAA==.',
Po='Popcola:BAAALgADCgEJAQAAAA==.Popopopopopo:BAAALgAFFAQJBAAAAA==.Portholio:BAAALgAECgYJBgAAAA==.',
Pu='Pubbles:BAAALgAECgYJDAAAAA==.Punizher:BAAALgAECgMJAwAAAA==.Purerage:BAAALgAECgYJDQAAAA==.',
Pv='Pvc:BAAALgAECgYJCQABLgAFFAQJBQATAN4HAA==.',
Py='Pyrella:BAAALgADCgEJAQABLgAECgcJCgACAAAAAA==.Pyyrhadrood:BAAALgAECgMJAwAAAA==.Pyyrhanice:BAAALgAECgUJCgAAAA==.Pyyrhaspice:BAAALgADCgUJCQAAAA==.',
Qu='Quetzlcoatl:BAAALgADCgUJBQABLgAECgcJDQACAAAAAA==.',
Ra='Radiantharm:BAAALgAECgUJCwAAAA==.Raevalinaa:BAAALgAECgMJBgABLgAECggJIQABAD0QAA==.Raevelinaa:BAAALgAECgIJAwABLgAECggJIQABAD0QAA==.Randzmannz:BAAALgAECgMJAwAAAA==.Raph:BAAALgAECgIJAgAAAA==.Rarelootboss:BAAALgADCgcJDAAAAA==.',
Re='Reason:BAAALgAECgYJEQAAAA==.Redbaer:BAAALgADCgUJBQAAAA==.Renair:BAAALgADCgMJAwAAAA==.Renoitukax:BAABLgAECn8gAAMGAAkJ4RUYCwAgAgloDAAABQA/AGkMAAAEAEQAawwAAAQANABqDAAAAwAtAGwMAAADACQAbQwAAAIALADqDAAABwBYAG4MAAADAD8AbwwAAAEAHQAGAAkJ4RUYCwAgAgloDAAABQA/AGkMAAAEAEQAawwAAAQANABqDAAAAwAtAGwMAAADACQAbQwAAAIALADqDAAABgBYAG4MAAADAD8AbwwAAAEAHQAkAAEJdx1QQQBUAAHqDAAAAQBLAAAA.Restorn:BAAALgADCgcJCgAAAA==.Retussy:BAAALgADCgEJAQAAAA==.Reynard:BAAALgAFFAEJAQAAAA==.Rezz:BAACLgAFFH8MAAIBAAQJ7gkJOwA0AQRoDAAABQAbAGkMAAAEACsAawwAAAEADADqDAAAAgARAAEABAnuCQk7ADQBBGgMAAAFABsAaQwAAAQAKwBrDAAAAQAMAOoMAAACABEALgAECn8eAAIBAAgJux+HKQDNAgABAAgJux+HKQDNAgAAAA==.',
Ri='Ridic:BAAALgADCgMJAwAAAA==.Rigour:BAAALgADCgMJAwAAAA==.',
Ro='Rocketpop:BAAALgADCgIJAgAAAA==.Rosiegirl:BAAALgADCgkJCgAAAA==.',
Ry='Ryzen:BAAALgAECgYJBwAAAA==.',
Sa='Salaelana:BAAALgADCgcJCQAAAA==.Saltzpyre:BAAALgADCgYJBAAAAA==.Saninar:BAAALgADCgIJAgAAAA==.',
Sc='Schezmu:BAAALgAECgIJAgAAAA==.Scruffknight:BAAALgAECgYJBgAAAA==.Scrufies:BAAALgAECggJEwAAAA==.',
Se='Seisappho:BAAALgADCgMJAwAAAA==.Senorfiesta:BAAALgAECgQJBAAAAA==.Serenityboop:BAAALgADCgYJCQAAAA==.Sergnocchi:BAAALgAECgcJBwAAAA==.Sethour:BAAALgADCgQJBAAAAA==.',
Sh='Shaee:BAAALgADCgkJDwAAAA==.Shalthender:BAAALgADCgUJBQAAAA==.Shamans:BAABLgAECn8XAAIDAAcJeB5iDQASAgdoDAAABABPAGkMAAAEAFoAawwAAAQARgBqDAAABABTAGwMAAADAEMA6gwAAAMAQwBuDAAAAQBcAAMABwl4HmINABICB2gMAAAEAE8AaQwAAAQAWgBrDAAABABGAGoMAAAEAFMAbAwAAAMAQwDqDAAAAwBDAG4MAAABAFwAAAA=.Shamncheese:BAAALgAECgYJDAAAAA==.Shamorcc:BAAALgADCgQJBAAAAA==.Shasta:BAACLgAFFH8OAAIJAAQJHiKlAQCVAQRoDAAABQBXAGkMAAAEAFEAawwAAAIAVwDqDAAAAwBdAAkABAkeIqUBAJUBBGgMAAAFAFcAaQwAAAQAUQBrDAAAAgBXAOoMAAADAF0ALgAECn8oAAIJAAgJWiVvAQBBAwAJAAgJWiVvAQBBAwAAAA==.Shaulthariel:BAAALgAECgEJAQAAAA==.Shioz:BAAALgADCgQJBgAAAA==.Shisuiuchiha:BAAALgAECgQJBwAAAA==.Shootybithc:BAAALgADCgEJAQAAAA==.Shuhari:BAAALgAECgkJEAAAAQ==.Shyx:BAAALgADCgIJAgAAAA==.',
Si='Siilas:BAACLgAFFH8KAAQXAAQJEgXxXACaAARoDAAABAAEAGkMAAADACcAawwAAAEAAwDqDAAAAgADABcAAwmWAfFcAJoAA2gMAAAEAAQAawwAAAEAAwDqDAAAAQADABoAAQmHD98KAFEAAWkMAAACACcAGAACCe0AvRgAPAACaQwAAAEAAQDqDAAAAQADAC4ABAp/IQADFwAJCW8O0iwAtwEAFwAJCW8O0iwAtwEAGAAECVAHAkEAsQAAAAA=.Sinamon:BAABLgAECn8jAAIHAAcJGSE/GgA2AgdoDAAABwBMAGkMAAAGAFgAawwAAAYAWgBqDAAABABXAGwMAAAEAE4A6gwAAAUAUQBuDAAAAwBdAAcABwkZIT8aADYCB2gMAAAHAEwAaQwAAAYAWABrDAAABgBaAGoMAAAEAFcAbAwAAAQATgDqDAAABQBRAG4MAAADAF0AAAA=.Sinani:BAABLgAECn8UAAIBAAcJAgTw4gAvAQdoDAAABAAFAGkMAAADAA0AawwAAAMAEwBqDAAAAwASAGwMAAADAAsAbQwAAAEABADqDAAAAwAIAAEABwkCBPDiAC8BB2gMAAAEAAUAaQwAAAMADQBrDAAAAwATAGoMAAADABIAbAwAAAMACwBtDAAAAQAEAOoMAAADAAgAAAA=.Sinista:BAAALgADCgkJCQAAAA==.Sinnamon:BAAALgAECgYJDAABLgAECgcJIwAHABkhAA==.',
Sj='Sjdh:BAAALgAECggJEQAAAA==.Sjrogue:BAABLgAECn8mAAIbAAgJ6RNKEACrAQhoDAAABgBBAGkMAAAGAE4AawwAAAYAPABqDAAABQAvAGwMAAAFACkAbQwAAAIAJgDqDAAABgAqAG4MAAACAB0AGwAICekTShAAqwEIaAwAAAYAQQBpDAAABgBOAGsMAAAGADwAagwAAAUALwBsDAAABQApAG0MAAACACYA6gwAAAYAKgBuDAAAAgAdAAAA.',
Sk='Skjolvarn:BAEALgAECgMJBwAAAA==.Skram:BAAALgAECgMJBAAAAA==.',
Sl='Slammydooker:BAABLgAECn8ZAAMbAAkJlhVFCQAVAgloDAAABABGAGkMAAADAD0AawwAAAMAPgBqDAAAAgBYAGwMAAADADQAbQwAAAIAGADqDAAABABBAG4MAAADAC0AbwwAAAEAOwAbAAkJlhVFCQAVAgloDAAAAwBGAGkMAAADAD0AawwAAAMAPgBqDAAAAgBYAGwMAAADADQAbQwAAAIAGADqDAAABABBAG4MAAADAC0AbwwAAAEAOwAcAAEJ1QcKIQAtAAFoDAAAAQAUAAAA.Sleeptoken:BAAALgAECgMJCAAAAA==.Slyphz:BAAALgAECgYJBgAAAA==.',
Sm='Smightymouse:BAAALgADCgEJAQAAAA==.',
Sn='Snoipuh:BAAALgADCgUJBgAAAA==.',
So='Solas:BAAALgAECgQJBwAAAA==.Soletaken:BAAALgADCggJDwAAAA==.Solio:BAAALgADCgYJFQAAAA==.Somberdh:BAAALgADCgcJBwAAAA==.Sonofsand:BAAALgAECgIJAgAAAA==.Soulja:BAAALgADCgEJAgAAAA==.Soulmoethus:BAAALgADCgYJCQAAAA==.',
Sp='Sprayandpray:BAAALgAECgQJBAAAAA==.Sprinklely:BAAALgADCgcJCgAAAA==.',
Sq='Squirtney:BAAALgADCgMJAwAAAA==.',
Ss='Ss:BAABLgAFFH8HAAIYAAMJ6gBHCgCWAANoDAAAAwABAGkMAAACAAQA6gwAAAIAAAAYAAMJ6gBHCgCWAANoDAAAAwABAGkMAAACAAQA6gwAAAIAAAAAAA==.Ssl:BAAALgADCgQJBAAAAA==.',
St='Starrwood:BAABLgAECn8jAAIOAAgJDApJPABfAQhoDAAABgApAGkMAAAFABgAawwAAAYAFwBqDAAABABJAGwMAAAEACAAbQwAAAEACQDqDAAABgAXAG4MAAADABgADgAICQwKSTwAXwEIaAwAAAYAKQBpDAAABQAYAGsMAAAGABcAagwAAAQASQBsDAAABAAgAG0MAAABAAkA6gwAAAYAFwBuDAAAAwAYAAAA.Statik:BAAALgAECgEJAQAAAA==.Statík:BAAALgAECgEJAQABLgAECgEJAQACAAAAAA==.Stepmonk:BAAALgADCgEJAgAAAA==.Stevesharts:BAAALgADCgYJCwAAAA==.Stonedlock:BAAALgADCgcJCAAAAA==.Stonetusk:BAAALgADCgMJAwAAAA==.Stroya:BAAALgAECgUJBgAAAA==.',
Su='Sunpali:BAAALgAECgUJBgAAAA==.',
Sx='Sx:BAAALgADCgIJAgAAAA==.',
Sy='Syaa:BAAALgAECgYJBQAAAA==.Syberis:BAAALgADCgcJDgAAAA==.',
Ta='Tacodaboss:BAAALgAECgUJDwAAAA==.Talelarissia:BAAALgADCgQJBAAAAA==.Talonflame:BAABLgAECn8dAAIQAAgJXhujBwB3AghoDAAABABPAGkMAAAEAE4AawwAAAQAUABqDAAABAA7AGwMAAAEAEcAbQwAAAMAVADqDAAAAwAzAG4MAAADAC0AEAAICV4bowcAdwIIaAwAAAQATwBpDAAABABOAGsMAAAEAFAAagwAAAQAOwBsDAAABABHAG0MAAADAFQA6gwAAAMAMwBuDAAAAwAtAAAA.Tansu:BAAALgAECgYJEwAAAA==.Taupo:BAACLgAFFH8HAAITAAMJIBzKFAD6AANoDAAABABXAGkMAAACADcA6gwAAAEASQATAAMJIBzKFAD6AANoDAAABABXAGkMAAACADcA6gwAAAEASQAuAAQKfycAAhMACQlyH6kNAHoCABMACQlyH6kNAHoCAAAA.',
Tb='Tbanger:BAAALgAECgQJBwAAAA==.Tbh:BAAALgADCgcJBwABLgAFFAQJBQATAN4HAA==.',
Te='Techevo:BAAALgAECgQJBQAAAA==.Techfire:BAABLgAECn8jAAIlAAkJ9hqMAACgAgloDAAABQA+AGkMAAAFAEQAawwAAAUARwBqDAAABQA/AGwMAAAEAFEAbQwAAAMAPwDqDAAABQBUAG4MAAACAEUAbwwAAAEAMwAlAAkJ9hqMAACgAgloDAAABQA+AGkMAAAFAEQAawwAAAUARwBqDAAABQA/AGwMAAAEAFEAbQwAAAMAPwDqDAAABQBUAG4MAAACAEUAbwwAAAEAMwAAAA==.Techsmexx:BAAALgAECgIJAwAAAA==.Tenebron:BAABLgAECn8XAAImAAYJPRE1GAACAQZoDAAABQAzAGkMAAAFADEAawwAAAUANQBqDAAAAgAZAGwMAAABAB0A6gwAAAUAJQAmAAYJPRE1GAACAQZoDAAABQAzAGkMAAAFADEAawwAAAUANQBqDAAAAgAZAGwMAAABAB0A6gwAAAUAJQAAAA==.Tenlucis:BAAALgAECgYJCAAAAA==.',
Th='Thaelyssa:BAAALgAECgEJAQAAAA==.Tharria:BAAALgADCgcJBwAAAA==.Thearia:BAABLgAECn8ZAAMNAAcJ/BR+UgBcAQdoDAAABQAvAGkMAAAFAEsAawwAAAUAOQBqDAAAAwA+AGwMAAACABkAbQwAAAEAIwDqDAAABABIAA0ABwn8FH5SAFwBB2gMAAADAC8AaQwAAAMASwBrDAAAAwA5AGoMAAACAD4AbAwAAAIAGQBtDAAAAQAjAOoMAAACAEgAFQAFCZoOpjIA0QAFaAwAAAIAIgBpDAAAAgAoAGsMAAACACQAagwAAAEAKQDqDAAAAgAmAAAA.Thecanmurk:BAAALgADCgkJEgAAAA==.Thedilf:BAAALgADCgEJAQAAAA==.Thicktotem:BAAALgAECgIJAgAAAA==.Thickumz:BAAALgAECgMJBgAAAA==.Thorenis:BAAALgADCgEJAQAAAA==.Thoryndruid:BAACLgAFFH8MAAIeAAUJ9hKfAQBWAQVoDAAAAwBNAGkMAAACAB0AawwAAAMAHQBqDAAAAgAmAOoMAAACADkAHgAFCfYSnwEAVgEFaAwAAAMATQBpDAAAAgAdAGsMAAADAB0AagwAAAIAJgDqDAAAAgA5AC4ABAp/LQADHgAJCY4iEQMADgMAHgAJCUQiEQMADgMACQAHCbweXQUAGgIAAAA=.Thorïn:BAAALgADCgMJAwAAAA==.Thorýn:BAABLgAFFH8JAAIRAAMJphhZUgD1AANoDAAAAwA6AGkMAAACADMA6gwAAAQATgARAAMJphhZUgD1AANoDAAAAwA6AGkMAAACADMA6gwAAAQATgABLgAFFAUJDAAeAPYSAA==.Thórin:BAAALgAECgcJDQAAAA==.',
Ti='Timakk:BAAALgADCgEJAQAAAA==.Tipsy:BAABLgAECn8YAAIdAAkJmgn8JwCPAQloDAAABAAwAGkMAAADABgAawwAAAMADQBqDAAAAgAOAGwMAAACAAkAbQwAAAIAGgDqDAAABQA2AG4MAAACAAcAbwwAAAEAFgAdAAkJmgn8JwCPAQloDAAABAAwAGkMAAADABgAawwAAAMADQBqDAAAAgAOAGwMAAACAAkAbQwAAAIAGgDqDAAABQA2AG4MAAACAAcAbwwAAAEAFgAAAA==.',
To='Tomfoolary:BAAALgAECgEJAgAAAA==.Toofy:BAAALgAECgEJAQAAAA==.Total:BAAALgADCgkJDAAAAA==.Totembear:BAAALgADCgYJBgABLgAECgcJEQACAAAAAA==.',
Tr='Tralleth:BAABLgAECn8cAAMPAAgJ/hA8GQCBAQhoDAAABAAsAGkMAAAFADAAawwAAAUALQBqDAAABAA7AGwMAAAEADwAbQwAAAEAIwDqDAAABAArAG4MAAABABsADwAICf4QPBkAgQEIaAwAAAQALABpDAAABQAwAGsMAAAFAC0AagwAAAQAOwBsDAAAAwA8AG0MAAABACMA6gwAAAQAKwBuDAAAAQAbAAUAAQkaCHYqADEAAWwMAAABABQAAAA=.Trillbilly:BAAALgAECgEJAQAAAA==.Trinora:BAAALgADCgkJDgAAAA==.Trolltard:BAAALgAECgEJAQABLgAECgMJAwACAAAAAA==.Troxa:BAAALgAECgQJBQAAAA==.',
Tu='Tuskor:BAAALgADCgEJAQAAAA==.',
Tw='Twinklord:BAAALgAECgcJDAAAAA==.',
Ty='Tylolight:BAAALgADCgMJAwAAAA==.Tylototem:BAAALgAFFAEJAQAAAA==.',
Ug='Uglyboi:BAAALgAECggJCQAAAA==.',
Uj='Ujcmonk:BAAALgAECgQJBAAAAA==.',
Ul='Ullbian:BAAALgADCgMJAwAAAA==.Ultramar:BAAALgADCgEJAQAAAA==.',
Un='Uncookedham:BAAALgAECgQJCwAAAA==.',
Ur='Urgh:BAABLgAECn8YAAIGAAgJdA+GGwBsAQhoDAAABAAtAGkMAAADACgAawwAAAMAKwBqDAAAAwAZAGwMAAADACkAbQwAAAIAKADqDAAAAwApAG4MAAADABgABgAICXQPhhsAbAEIaAwAAAQALQBpDAAAAwAoAGsMAAADACsAagwAAAMAGQBsDAAAAwApAG0MAAACACgA6gwAAAMAKQBuDAAAAwAYAAAA.Urk:BAAALgAECgYJBgAAAA==.Urzaa:BAAALgAECgEJAQAAAA==.',
Ut='Uthur:BAAALgAECgMJAwAAAA==.',
Va='Valethales:BAAALgADCgcJBwAAAA==.Vanillaface:BAAALgAECggJDgAAAA==.Vape:BAAALgAECgQJCgAAAA==.',
Ve='Veinripp:BAAALgADCgUJBQAAAA==.Velarael:BAABLgAECn8aAAIXAAYJlApydQDkAAZoDAAABgAiAGkMAAAFABcAawwAAAQADwBqDAAAAwA3AGwMAAACABsA6gwAAAYAIQAXAAYJlApydQDkAAZoDAAABgAiAGkMAAAFABcAawwAAAQADwBqDAAAAwA3AGwMAAACABsA6gwAAAYAIQAAAA==.Velaryn:BAAALgADCgIJAgAAAA==.Veldar:BAAALgADCgIJAgAAAA==.Velekete:BAAALgADCgUJBQAAAA==.Velethei:BAAALgAECgYJDwAAAA==.Velian:BAAALgADCgMJBAAAAA==.Verdesalsa:BAAALgAECgUJBgAAAA==.Verox:BAAALgADCgMJAwAAAA==.',
Vh='Vheckxus:BAAALgAECgYJEwAAAA==.',
Vi='Vicv:BAABLgAECn8PAAIGAAgJSAwVNABIAQhoDAAAAgA2AGkMAAACACIAawwAAAIAGABqDAAAAgARAGwMAAADABwAbQwAAAEAEgDqDAAAAgAoAG4MAAABABQABgAICUgMFTQASAEIaAwAAAIANgBpDAAAAgAiAGsMAAACABgAagwAAAIAEQBsDAAAAwAcAG0MAAABABIA6gwAAAIAKABuDAAAAQAUAAAA.',
Vo='Voidberg:BAAALgADCgYJBgAAAA==.',
Wa='Wachonaso:BAACLgAFFH8IAAIXAAQJlw2oOAD+AARoDAAAAwAyAGkMAAACADQAawwAAAEAAgDqDAAAAgAhABcABAmXDag4AP4ABGgMAAADADIAaQwAAAIANABrDAAAAQACAOoMAAACACEALgAECn8oAAMXAAcJSR+ZIgDpAQAXAAcJMB6ZIgDpAQAYAAYJyBxYFwCPAQAAAA==.Wanbahl:BAAALgADCgMJAwAAAA==.',
Wh='Whatuphuz:BAAALgADCgQJBQAAAA==.Wheresmyjaw:BAACLgAFFH8MAAMXAAQJIhs5IgA5AQRoDAAABQBJAGkMAAAEAEoAawwAAAEAMQDqDAAAAgBQABcABAkiGzkiADkBBGgMAAAFAEkAaQwAAAMASgBrDAAAAQAxAOoMAAACAFAAGgABCUUHtgwARwABaQwAAAEAEgAuAAQKfyAAAxcACAmQIDEtALUBABcACAmQIDEtALUBABgAAgm6DiJSAHcAAAAA.',
Wi='Wildthree:BAABLgAECn8WAAMUAAcJoBweDQDyAQdoDAAABABQAGkMAAAEAEUAawwAAAQANgBqDAAAAwBQAGwMAAADAFEA6gwAAAMAVgBuDAAAAQBCABQABwmgHB4NAPIBB2gMAAADAFAAaQwAAAMARQBrDAAAAwA2AGoMAAADAFAAbAwAAAMAUQDqDAAAAwBWAG4MAAABAEIAJwADCdkUK2IAuQADaAwAAAEANgBpDAAAAQBCAGsMAAABACcAAAA=.Willenda:BAAALgADCgYJBgAAAA==.Willowins:BAAALgAECgEJAQAAAA==.Winterstired:BAACLgAFFH8JAAIhAAQJ8CI9BACaAQRoDAAAAwBaAGkMAAADAF0AawwAAAEASgDqDAAAAgBjACEABAnwIj0EAJoBBGgMAAADAFoAaQwAAAMAXQBrDAAAAQBKAOoMAAACAGMALgAECn83AAIhAAgJ4yXWAgA1AwAhAAgJ4yXWAgA1AwAAAA==.',
Wo='Woen:BAAALgADCggJCQAAAA==.Wolf:BAAALgAECgQJBQAAAA==.Wollffie:BAAALgAECgQJBAAAAA==.',
Wu='Wuinn:BAAALgAFFAEJAQABLgAFFAQJCgANAOYRAA==.Wut:BAAALgADCgcJBwAAAA==.',
['Wõ']='Wõnderful:BAAALgAFFAEJAQABLgAFFAMJCQARAGkVAA==.',
Xc='Xclobber:BAAALgADCgIJAgAAAA==.',
Xe='Xemnass:BAAALgAECgUJBwAAAA==.',
Xi='Xillas:BAAALgADCgUJBQAAAA==.',
Xo='Xoverkll:BAAALgAECgYJBwAAAA==.',
Xy='Xylina:BAAALgADCgEJAQAAAA==.Xyrii:BAAALgADCgEJAQAAAA==.',
Ya='Yadder:BAAALgAECgEJAQAAAA==.Yahro:BAACLgAFFH8JAAIHAAQJhgvXIgAvAQRoDAAABQA9AGkMAAACAB4AawwAAAEAEQDqDAAAAQAIAAcABAmGC9ciAC8BBGgMAAAFAD0AaQwAAAIAHgBrDAAAAQARAOoMAAABAAgALgAECn8iAAIHAAgJoxueJgCLAgAHAAgJoxueJgCLAgAAAA==.',
Ye='Yeahiknow:BAAALgADCgkJDgAAAA==.Yeling:BAAALgAECgEJAQAAAA==.Yep:BAAALgAECgcJBwAAAA==.',
Yi='Yiska:BAAALgADCgcJBwAAAA==.',
Yo='Yoriale:BAAALgAECgYJDgAAAA==.Yotoymuerto:BAAALgAECgMJAwAAAA==.',
Za='Zafra:BAAALgADCgEJAQAAAA==.Zaimara:BAAALgAECgEJAgAAAA==.Zalind:BAAALgAECggJEQAAAA==.Zalvianna:BAAALgAECgQJCAAAAA==.Zarindlina:BAAALgADCgUJBQAAAA==.Zarshx:BAAALgAECgYJCwABLgAFFAMJBAACAAAAAA==.',
Ze='Zemonk:BAAALgAECgYJBgAAAA==.',
Zi='Zilong:BAAALgAFFAEJAQABLgAFFAUJCgAEAFgTAA==.Zilongmage:BAAALgAFFAEJAgAAAA==.Zilongwar:BAAALgAFFAEJAQAAAA==.Zinnia:BAAALgADCgEJAQAAAA==.',
Zo='Zonedk:BAAALgAECgUJDQAAAA==.Zonerg:BAAALgADCgEJAgABLgAECgUJDQACAAAAAA==.Zordak:BAAALgADCgcJCAAAAA==.Zosin:BAAALgAECgEJAQAAAA==.',
Zu='Zugzugzapzap:BAAALgADCgEJAQAAAA==.',
Zy='Zylphanae:BAAALgAECgQJBAAAAA==.',
['Ør']='Ørsted:BAAALgADCgEJAQABLgAFFAMJBwATACAcAA==.',
['ßi']='ßish:BAAALgAECgEJAQAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
