local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Hunter-Marksmanship','Hunter-BeastMastery','Unknown-Unknown','Druid-Restoration','DeathKnight-Unholy','Priest-Shadow','Paladin-Retribution','Warlock-Demonology','Evoker-Devastation','Evoker-Augmentation','Druid-Balance','Priest-Holy','Warrior-Fury','DeathKnight-Blood','Paladin-Holy','Mage-Frost','Warlock-Affliction','DemonHunter-Devourer','Shaman-Enhancement','Druid-Guardian','Shaman-Elemental','Monk-Mistweaver','Mage-Fire','Warlock-Destruction','Warrior-Protection','Hunter-Survival','Rogue-Subtlety','DemonHunter-Havoc','Druid-Feral','Monk-Brewmaster','Rogue-Assassination','Priest-Discipline','Monk-Windwalker','Shaman-Restoration','DeathKnight-Frost','Warrior-Arms','Mage-Arcane',}
local provider = {region='US',realm='Velen',name='US',type='daily',zone=46,date='2026-05-13',data={Ad='Addisyn:BAAALgAECgEJAgAAAA==.',
Ae='Aemetris:BAAALgAECgQJDQAAAA==.Aenicus:BAAALgADCgcJBwAAAA==.Aerina:BAAALgAECgQJCwAAAA==.Aethra:BAAALgADCgYJBgAAAA==.',
Ag='Agamotto:BAAALgAECgYJCgAAAA==.Agromagnetic:BAAALgAECgUJBgAAAA==.Agytha:BAAALgAECgMJAwAAAA==.Agøny:BAAALgADCgMJAwAAAA==.',
Ai='Aidendawn:BAAALgAECgQJBwAAAA==.',
Aj='Ajheria:BAAALgADCgcJCAAAAA==.',
Am='Ameildoran:BAAALgADCgkJCQAAAA==.',
An='Anaru:BAAALgAECgMJBgAAAA==.Anatyriel:BAAALgADCgEJAQAAAA==.Anayanci:BAAALgADCgUJBgAAAA==.Andalaine:BAAALgAECgEJAQAAAA==.Andari:BAAALgADCgEJAQAAAA==.Anoobornot:BAAALgADCgMJAwAAAA==.Anraleth:BAABLgAECn84AAMBAAkJwCQjAQDcAgloDAAABwBjAGkMAAAIAGMAawwAAAUAWgBqDAAABwBiAGwMAAAHAGAAbQwAAAUAXwDqDAAABwBhAG4MAAAFAEwAbwwAAAUAYQABAAgJkiQjAQDcAghoDAAABwBjAGkMAAAIAGMAawwAAAUAWgBqDAAABwBiAGwMAAAHAGAAbQwAAAUAXwDqDAAABwBhAG4MAAAFAEwAAgABCQYmmZ8AbgABbwwAAAUAYQAAAA==.',
Ap='Aponi:BAAALgADCggJIAAAAA==.',
Ar='Ardour:BAAALgAECgMJBgABLgAECgYJCQADAAAAAA==.Arduous:BAAALgAECgMJAwAAAA==.Arihu:BAABLgAECn8fAAIEAAkJlxRgHgDvAQloDAAABQBQAGkMAAAFAEwAawwAAAUARABqDAAABAAmAGwMAAADACsAbQwAAAEAOQDqDAAABQBDAG4MAAACABgAbwwAAAEAEQAEAAkJlxRgHgDvAQloDAAABQBQAGkMAAAFAEwAawwAAAUARABqDAAABAAmAGwMAAADACsAbQwAAAEAOQDqDAAABQBDAG4MAAACABgAbwwAAAEAEQAAAA==.Arkhana:BAAALgADCgEJAQAAAA==.',
As='Ashenaya:BAAALgAECgcJEQAAAA==.Asparagus:BAAALgAECgcJEQAAAA==.',
At='Atlass:BAABLgAECn8YAAIFAAcJ8RmxSQB5AQdoDAAABABbAGkMAAAFAF4AawwAAAUANQBqDAAAAgBPAGwMAAACAEIA6gwAAAUASgBuDAAAAQATAAUABwnxGbFJAHkBB2gMAAAEAFsAaQwAAAUAXgBrDAAABQA1AGoMAAACAE8AbAwAAAIAQgDqDAAABQBKAG4MAAABABMAAAA=.Atrest:BAAALgAECgYJBwAAAA==.',
Au='Augmenter:BAAALgAECgQJBAABLgAFFAYJFQAGABwYAA==.Aust:BAABLgAECn8UAAIHAAgJ6RNKNgC7AQhoDAAABAA9AGkMAAACACsAawwAAAMALwBqDAAAAgApAGwMAAACAFsAbQwAAAIAIQDqDAAAAwAvAG4MAAACAB8ABwAICekTSjYAuwEIaAwAAAQAPQBpDAAAAgArAGsMAAADAC8AagwAAAIAKQBsDAAAAgBbAG0MAAACACEA6gwAAAMALwBuDAAAAgAfAAAA.',
Av='Averlis:BAAALgAECgYJDwAAAA==.Avoiddance:BAAALgADCgEJAQAAAA==.',
Ax='Axee:BAAALgADCgYJBgAAAA==.',
Az='Azima:BAAALgADCggJCAAAAA==.Azura:BAAALgADCgIJAgAAAA==.Azurargentyr:BAAALgAECgYJDQAAAA==.',
Ba='Babeolicious:BAAALgADCgEJAQAAAA==.Bacon:BAABLgAECn8YAAIHAAcJEAgKfQAKAQdoDAAABAAmAGkMAAAEABMAawwAAAQAFABqDAAABAAbAGwMAAADABIAbQwAAAEACADqDAAABAASAAcABwkQCAp9AAoBB2gMAAAEACYAaQwAAAQAEwBrDAAABAAUAGoMAAAEABsAbAwAAAMAEgBtDAAAAQAIAOoMAAAEABIAAAA=.Bambøøze:BAAALgADCgEJAQAAAA==.Bandadi:BAEBLgAECn8wAAIIAAgJox9tFQDVAghoDAAACABjAGkMAAAIAGEAawwAAAgAWQBqDAAABwBjAGwMAAAHAF0AbQwAAAEAEwDqDAAACABfAG8MAAABAEgACAAICaMfbRUA1QIIaAwAAAgAYwBpDAAACABhAGsMAAAIAFkAagwAAAcAYwBsDAAABwBdAG0MAAABABMA6gwAAAgAXwBvDAAAAQBIAAAA.Barbelo:BAAALgAECgcJCgAAAA==.Barely:BAAALgAECgUJBwAAAA==.Barkweldort:BAAALgAECgYJEQAAAA==.Barreled:BAAALgADCgMJAwAAAA==.Batistabomba:BAAALgAECgYJBgAAAA==.',
Be='Beargruk:BAAALgAECgUJBwAAAA==.Beastly:BAAALgAECgUJBgAAAA==.Beeble:BAAALgAECgMJAwAAAA==.Belii:BAAALgAECgUJBgAAAA==.Bepisthepall:BAAALgAECgEJAgAAAA==.Betterkevin:BAAALgAECgQJCAAAAA==.',
Bi='Bigbooty:BAAALgAECgYJEQAAAA==.Bigbootyjudi:BAAALgADCgEJAQAAAA==.',
Bl='Blikey:BAABLgAFFH8GAAIFAAIJfiYFZwDSAAJoDAAAAwBiAOoMAAADAGIABQACCX4mBWcA0gACaAwAAAMAYgDqDAAAAwBiAAAA.Bloodyrott:BAAALgAECgQJCQAAAA==.Bluedrake:BAACLgAFFH8FAAMJAAMJBxUaBADyAANoDAAAAgAmAGkMAAACADEA6gwAAAEASQAJAAMJRBAaBADyAANoDAAAAgAmAGkMAAABAAwA6gwAAAEASQAKAAEJPRMQPgBLAAFpDAAAAQAxAC4ABAp/IQADCQAICV8evgQAugIACQAICYYdvgQAugIACgAICfgVUhkAAwIAAS4ABRQECQ4ACwCrGQA=.Blueparrot:BAABLgAECn8oAAIMAAgJmRT/DgATAghoDAAACABOAGkMAAAIAFAAawwAAAcATABqDAAABgAdAGwMAAAEAEoAbQwAAAEABADqDAAABQA8AG4MAAABABEADAAICZkU/w4AEwIIaAwAAAgATgBpDAAACABQAGsMAAAHAEwAagwAAAYAHQBsDAAABABKAG0MAAABAAQA6gwAAAUAPABuDAAAAQARAAAA.Bluy:BAAALgADCgMJAwAAAA==.Blädèstorm:BAABLgAECn8ZAAINAAgJphzaDwARAghoDAAABABJAGkMAAAEAEgAawwAAAMASwBqDAAAAwBBAGwMAAADAEAAbQwAAAEANQDqDAAABABbAG4MAAADAFMADQAICaYc2g8AEQIIaAwAAAQASQBpDAAABABIAGsMAAADAEsAagwAAAMAQQBsDAAAAwBAAG0MAAABADUA6gwAAAQAWwBuDAAAAwBTAAAA.',
Bo='Bonesnap:BAACLgAFFH8TAAMFAAUJnyMWEwCbAQVoDAAABQBdAGkMAAAFAFwAawwAAAIAWABqDAAAAgBDAOoMAAAFAFoABQAECZ8jFhMAmwEEaAwAAAUAXQBpDAAABQBcAGsMAAACAFgA6gwAAAUAWgAOAAEJAADCLgAAAAFqDAAAAgBDAC4ABAp/IAADBQAJCaohoxcA7gIABQAJCaohoxcA7gIADgAECa4TrCYArwAAAAA=.Bowkatan:BAAALgAECgEJAgAAAA==.',
Br='Brianisita:BAAALgAECgUJBgAAAA==.Brightmane:BAABLgAECn8WAAIPAAYJUx4zJQD8AQZoDAAABQBOAGkMAAAEAFQAawwAAAQASwBqDAAAAwBMAGwMAAABADcA6gwAAAUAXwAPAAYJUx4zJQD8AQZoDAAABQBOAGkMAAAEAFQAawwAAAQASwBqDAAAAwBMAGwMAAABADcA6gwAAAUAXwAAAA==.Bringinlight:BAAALgADCgkJHAAAAA==.',
Bu='Bubbleicious:BAAALgAECgIJAwAAAA==.Bubbletea:BAAALgAECgUJCwABLgAECgkJKQACAIgiAA==.Bulletz:BAABLgAECn8VAAIBAAcJmRrrCQBrAQdoDAAABQA7AGkMAAAEAEwAawwAAAMARQBqDAAAAQATAGwMAAADADQAbQwAAAIAUADqDAAAAwBGAAEABwmZGusJAGsBB2gMAAAFADsAaQwAAAQATABrDAAAAwBFAGoMAAABABMAbAwAAAMANABtDAAAAgBQAOoMAAADAEYAAAA=.Buttfur:BAAALgADCgYJBgAAAA==.',
['Bê']='Bêarwithme:BAAALgAECgIJBAABLgAECgYJCAADAAAAAA==.',
Ca='Caenzo:BAAALgADCgkJCgAAAA==.Casanna:BAAALgADCgYJBgAAAA==.Cassandria:BAABLgAECn8lAAMEAAgJkA5uOwBCAQhoDAAABwAsAGkMAAAGACIAawwAAAYAJABqDAAABgAwAGwMAAAFACYAbQwAAAEAIwDqDAAAAgApAG4MAAAEABIABAAHCasObjsAQgEHaAwAAAEALABpDAAAAQAiAGsMAAACACQAagwAAAIAMABsDAAAAgAmAOoMAAABACkAbgwAAAEAEgALAAgJ2AloKAAYAQhoDAAABgAjAGkMAAAFABcAawwAAAQAGABqDAAABAAdAGwMAAADABoAbQwAAAEAFQDqDAAAAQAXAG4MAAADABUAAAA=.Cassiradra:BAAALgADCgEJAQAAAA==.',
Ce='Cearas:BAAALgADCgkJCQAAAA==.Cedrick:BAAALgADCgcJCQAAAA==.Celiona:BAAALgAECgkJBwAAAA==.Celody:BAAALgAECgYJDAAAAA==.Celticsinsix:BAAALgAECgEJAQAAAA==.',
Ch='Chaoten:BAAALgADCgEJAQAAAA==.Chathlia:BAAALgAECgQJBAAAAA==.Chavdar:BAAALgADCgEJAQAAAA==.Chewster:BAABLgAECn8dAAIQAAcJGgzlbwBEAQdoDAAABQAoAGkMAAAFACEAawwAAAQAFABqDAAABAApAGwMAAADABIA6gwAAAcANgBuDAAAAQASABAABwkaDOVvAEQBB2gMAAAFACgAaQwAAAUAIQBrDAAABAAUAGoMAAAEACkAbAwAAAMAEgDqDAAABwA2AG4MAAABABIAAAA=.Chixie:BAAALgADCgEJAQAAAA==.Choal:BAAALgAECgYJDQAAAA==.Choglana:BAAALgAECgMJAwAAAA==.Chogric:BAABLgAECn8sAAIPAAkJhh+NBQATAwloDAAABgBaAGkMAAADAF8AawwAAAMAXgBqDAAABgBYAGwMAAAHAFQAbQwAAAYAMgDqDAAABQBaAG4MAAAFAE8AbwwAAAMANQAPAAkJhh+NBQATAwloDAAABgBaAGkMAAADAF8AawwAAAMAXgBqDAAABgBYAGwMAAAHAFQAbQwAAAYAMgDqDAAABQBaAG4MAAAFAE8AbwwAAAMANQABLgAECgMJAwADAAAAAA==.',
Ci='Civetta:BAAALgAECgYJDwAAAA==.',
Cl='Clannininick:BAAALgADCgUJBgAAAA==.Clark:BAAALgADCgEJAQAAAA==.',
Co='Cogswell:BAAALgADCgIJAgAAAA==.Comespankit:BAAALgAECgIJAgAAAA==.Convalesor:BAAALgAECgYJDQAAAA==.',
Cr='Crazzywazzy:BAABLgAFFH8HAAIFAAIJJR9AOwCmAAJoDAAABgBYAOoMAAABAEcABQACCSUfQDsApgACaAwAAAYAWADqDAAAAQBHAAAA.Crona:BAABLgAECn8aAAIPAAkJtw4LPACJAQloDAAABABQAGkMAAADACsAawwAAAMAJQBqDAAAAwAMAGwMAAAEABwAbQwAAAEAHgDqDAAABQAqAG4MAAACACgAbwwAAAEAFwAPAAkJtw4LPACJAQloDAAABABQAGkMAAADACsAawwAAAMAJQBqDAAAAwAMAGwMAAAEABwAbQwAAAEAHgDqDAAABQAqAG4MAAACACgAbwwAAAEAFwAAAA==.Crsteel:BAAALgAECgEJAQAAAA==.Crzyblnkrton:BAACLgAFFH8PAAIQAAYJthC6FwCZAQZoDAAABAA1AGkMAAACACMAawwAAAEAIwBqDAAAAQA2AGwMAAABAAwA6gwAAAYATAAQAAYJthC6FwCZAQZoDAAABAA1AGkMAAACACMAawwAAAEAIwBqDAAAAQA2AGwMAAABAAwA6gwAAAYATAAuAAQKfxcAAhAACAnmH2k5AJACABAACAnmH2k5AJACAAAA.Crzzy:BAAALgAECgQJBwAAAA==.',
Cu='Cuddlez:BAABLgAECn8bAAIMAAgJGwz6HgBqAQhoDAAABABDAGkMAAAEABoAawwAAAQAHABqDAAABAAkAGwMAAAEACMAbQwAAAEACQDqDAAABAAUAG4MAAACABcADAAICRsM+h4AagEIaAwAAAQAQwBpDAAABAAaAGsMAAAEABwAagwAAAQAJABsDAAABAAjAG0MAAABAAkA6gwAAAQAFABuDAAAAgAXAAAA.Cultera:BAAALgAECggJEAAAAA==.',
Cy='Cyhyraethia:BAABLgAECn8fAAIRAAgJDB+eAgAkAghoDAAABgBfAGkMAAAFAFcAawwAAAUAVwBqDAAABABdAGwMAAADAD0AbQwAAAEAPADqDAAABABbAG4MAAADAEgAEQAICQwfngIAJAIIaAwAAAYAXwBpDAAABQBXAGsMAAAFAFcAagwAAAQAXQBsDAAAAwA9AG0MAAABADwA6gwAAAQAWwBuDAAAAwBIAAEuAAQKCQk4ABIAQBoA.Cyndera:BAAALgADCgEJAQAAAA==.',
Da='Dagden:BAAALgADCgYJCAAAAA==.Dalaa:BAAALgAECgIJAgAAAA==.Danda:BAAALgAECgUJBQAAAA==.Daricepicker:BAABLgAECn8pAAICAAkJiCJPBQA3AwloDAAABgBfAGkMAAAEAFkAawwAAAMAVgBqDAAABQBbAGwMAAAGAGAAbQwAAAUAVQDqDAAABQBaAG4MAAAEAFcAbwwAAAMATAACAAkJiCJPBQA3AwloDAAABgBfAGkMAAAEAFkAawwAAAMAVgBqDAAABQBbAGwMAAAGAGAAbQwAAAUAVQDqDAAABQBaAG4MAAAEAFcAbwwAAAMATAAAAA==.Darkyn:BAABLgAECn8WAAIIAAgJBA/zOACWAQhoDAAAAwAdAGkMAAADADAAawwAAAMAOwBqDAAAAwAzAGwMAAAEACoAbQwAAAEAFADqDAAABAAmAG4MAAABAB0ACAAICQQP8zgAlgEIaAwAAAMAHQBpDAAAAwAwAGsMAAADADsAagwAAAMAMwBsDAAABAAqAG0MAAABABQA6gwAAAQAJgBuDAAAAQAdAAAA.Davedadude:BAABLgAECn8WAAIHAAgJPx4ZFAByAghoDAAABQBaAGkMAAACAFwAawwAAAMAXABqDAAABABXAGwMAAACAEMAbQwAAAIAQwDqDAAAAgAkAG4MAAACAF8ABwAICT8eGRQAcgIIaAwAAAUAWgBpDAAAAgBcAGsMAAADAFwAagwAAAQAVwBsDAAAAgBDAG0MAAACAEMA6gwAAAIAJABuDAAAAgBfAAAA.',
Dd='Ddeonu:BAAALgAECgEJAQAAAA==.Ddeonuu:BAAALgAFFAIJAgAAAA==.',
De='Deadlysins:BAABLgAECn8WAAIFAAgJ8wvpbACwAQhoDAAABAAsAGkMAAAEACAAawwAAAQAJwBqDAAAAwAhAGwMAAACACcAbQwAAAEAFwDqDAAAAwAXAG4MAAABAAoABQAICfML6WwAsAEIaAwAAAQALABpDAAABAAgAGsMAAAEACcAagwAAAMAIQBsDAAAAgAnAG0MAAABABcA6gwAAAMAFwBuDAAAAQAKAAAA.Deadscar:BAABLgAECn80AAITAAkJUiYYAACNAwloDAAABwBjAGkMAAAGAGMAawwAAAYAYgBqDAAABQBhAGwMAAAHAGMAbQwAAAUAXwDqDAAABwBiAG4MAAAGAGIAbwwAAAMAXgATAAkJUiYYAACNAwloDAAABwBjAGkMAAAGAGMAawwAAAYAYgBqDAAABQBhAGwMAAAHAGMAbQwAAAUAXwDqDAAABwBiAG4MAAAGAGIAbwwAAAMAXgAAAA==.Deathmasterj:BAAALgADCggJCAAAAA==.Deaths:BAAALgAECgcJEwAAAA==.Dedfrosty:BAAALgAECgQJBgAAAA==.Demomcgee:BAAALgADCgEJAgABLgAECgYJDwADAAAAAA==.Demonio:BAAALgADCgQJBgAAAA==.Demonpimp:BAAALgAECgYJBwAAAA==.Deviously:BAAALgADCgQJBAABLgAECgcJFQABAJkaAA==.Dewyhuey:BAAALgADCgIJAgAAAA==.',
Di='Dimpiana:BAAALgAECgQJAwAAAA==.Dithariaa:BAAALgAECgYJDAAAAA==.',
Do='Docryktor:BAABLgAECn8oAAITAAgJyxeHBgDxAQhoDAAABwBMAGkMAAAGAEEAawwAAAYAQwBqDAAABQAzAGwMAAAFADQAbQwAAAIAKADqDAAABgA7AG4MAAADAD8AEwAICcsXhwYA8QEIaAwAAAcATABpDAAABgBBAGsMAAAGAEMAagwAAAUAMwBsDAAABQA0AG0MAAACACgA6gwAAAYAOwBuDAAAAwA/AAAA.Doomgears:BAAALgAECgUJCwAAAA==.Dotsdead:BAAALgADCgYJDgAAAA==.Dotöri:BAAALgAECggJDwAAAA==.',
Dr='Dragonair:BAAALgAECgUJDAAAAA==.Drashta:BAAALgAECgEJAQAAAA==.Drhoe:BAAALgAECgEJAQAAAA==.Drhurtouch:BAAALgAECgUJDwAAAA==.Dro:BAAALgAECgQJBwAAAA==.Drtybear:BAAALgAECgYJEAAAAA==.Drulissa:BAABLgAECn8YAAIPAAgJuxmZLQDNAQhoDAAABABOAGkMAAADACkAawwAAAMAQwBqDAAAAwBVAGwMAAADAEUAbQwAAAEANwDqDAAAAwAxAG4MAAAEAE8ADwAICbsZmS0AzQEIaAwAAAQATgBpDAAAAwApAGsMAAADAEMAagwAAAMAVQBsDAAAAwBFAG0MAAABADcA6gwAAAMAMQBuDAAABABPAAAA.Druu:BAAALgADCgMJAwABLgAECgEJAQADAAAAAA==.',
Du='Duogear:BAAALgADCgIJAgAAAA==.Dusters:BAAALgADCgcJCwAAAA==.',
Eb='Ebonwings:BAAALgAECgYJCgABLgAECgcJAwADAAAAAA==.',
Ed='Ediana:BAABLgAECn8jAAIQAAcJMglGfAAsAQdoDAAABgAnAGkMAAAGABsAawwAAAYAEgBqDAAABQALAGwMAAAEABcAbQwAAAIADADqDAAABgATABAABwkyCUZ8ACwBB2gMAAAGACcAaQwAAAYAGwBrDAAABgASAGoMAAAFAAsAbAwAAAQAFwBtDAAAAgAMAOoMAAAGABMAAAA=.',
El='Elmô:BAABLgAECn8nAAIPAAgJIR54BwC6AghoDAAABwBeAGkMAAAHAFoAawwAAAcAUQBqDAAABABdAGwMAAAEAFYAbQwAAAIAJADqDAAABgBfAG4MAAACACUADwAICSEeeAcAugIIaAwAAAcAXgBpDAAABwBaAGsMAAAHAFEAagwAAAQAXQBsDAAABABWAG0MAAACACQA6gwAAAYAXwBuDAAAAgAlAAAA.Elody:BAAALgADCgYJBgAAAA==.Elvara:BAAALgAECgQJBwAAAA==.',
Eq='Equipwooman:BAAALgADCgIJAgAAAA==.',
Es='Estameling:BAABLgAECn8jAAIUAAgJ/hQfDACCAQhoDAAABgA6AGkMAAAFADsAawwAAAUASQBqDAAABQA/AGwMAAAEAEIAbQwAAAEAEADqDAAABQBBAG4MAAAEACQAFAAICf4UHwwAggEIaAwAAAYAOgBpDAAABQA7AGsMAAAFAEkAagwAAAUAPwBsDAAABABCAG0MAAABABAA6gwAAAUAQQBuDAAABAAkAAAA.',
Ex='Exash:BAABLgAECn8kAAIVAAkJOyEWBgCkAgloDAAABgBaAGkMAAAFAFoAawwAAAUAWwBqDAAABQBbAGwMAAADAFkAbQwAAAIAXADqDAAABQBbAG4MAAAEAEAAbwwAAAEARAAVAAkJOyEWBgCkAgloDAAABgBaAGkMAAAFAFoAawwAAAUAWwBqDAAABQBbAGwMAAADAFkAbQwAAAIAXADqDAAABQBbAG4MAAAEAEAAbwwAAAEARAAAAA==.Excizion:BAAALgAECgcJDAAAAA==.',
Fa='Faelynne:BAAALgADCgUJBQAAAA==.Fari:BAAALgAECgUJBQAAAA==.Fathertim:BAAALgAECgYJDAAAAA==.',
Fe='Feannara:BAAALgAECgYJCQAAAA==.Felar:BAAALgADCgEJAQAAAA==.Feldrena:BAAALgADCgcJDAAAAA==.',
Fl='Flangus:BAAALgADCgMJBAAAAA==.Flappydragon:BAAALgADCgIJAgAAAA==.Floraria:BAAALgADCgYJBgAAAA==.',
Fr='Frostii:BAAALgAECgcJEwAAAA==.',
Fu='Fudestamp:BAAALgADCgQJBQAAAA==.Fufight:BAAALgAECgIJAgABLgAECgkJHAAWAIkhAA==.Fugryktor:BAAALgAECgYJEgAAAA==.',
Fy='Fyrebug:BAAALgAECgUJDwAAAA==.',
Ga='Galandor:BAAALgAECgUJDQAAAA==.Gandaalf:BAABLgAECn8VAAMXAAcJth3XAQBrAgdoDAAABABWAGkMAAAFAFYAawwAAAQARABqDAAAAQBNAGwMAAADADkAbQwAAAEATgDqDAAAAwBPABcABwm2HdcBAGsCB2gMAAAEAFYAaQwAAAUAVgBrDAAABABEAGoMAAABAE0AbAwAAAIAOQBtDAAAAQBOAOoMAAACAE8AEAACCeEPUUYBcwACbAwAAAEALgDqDAAAAQAjAAAA.Garrinda:BAAALgAECgkJDgAAAA==.',
Ge='Geeked:BAAALgADCgUJBQAAAA==.Gemhide:BAABLgAECn8ZAAIYAAgJkApJDQAOAQhoDAAABAAsAGkMAAAEABgAawwAAAQAEgBqDAAAAwATAGwMAAACAB0AbQwAAAEAEQDqDAAABQApAG4MAAACAA0AGAAICZAKSQ0ADgEIaAwAAAQALABpDAAABAAYAGsMAAAEABIAagwAAAMAEwBsDAAAAgAdAG0MAAABABEA6gwAAAUAKQBuDAAAAgANAAAA.Georgharison:BAAALgAECgEJAQAAAA==.',
Gg='Ggwp:BAAALgAECgEJAQAAAA==.',
Gh='Ghae:BAAALgAECgUJBAAAAA==.Ghostsaber:BAAALgADCgEJAQABLgAECggJGQAZAM8cAA==.',
Gi='Gigglyguff:BAABLgAECn8YAAIEAAgJRSCSCQDNAghoDAAAAwBcAGkMAAADAGEAawwAAAQAYABqDAAABABUAGwMAAAEAFMAbQwAAAEAUQDqDAAABABWAG4MAAABACYABAAICUUgkgkAzQIIaAwAAAMAXABpDAAAAwBhAGsMAAAEAGAAagwAAAQAVABsDAAABABTAG0MAAABAFEA6gwAAAQAVgBuDAAAAQAmAAAA.Gimly:BAAALgAECgEJAQAAAA==.Gityahunter:BAAALgADCgcJDgABLgADCgkJHAADAAAAAA==.',
Gl='Glavenus:BAAALgADCgEJAQAAAA==.',
Go='Gobank:BAAALgADCgIJAgAAAA==.Gobanks:BAABLgAECn8wAAIHAAkJLB7YDACyAgloDAAABwBVAGkMAAAHAFoAawwAAAcATABqDAAABwBHAGwMAAAGAEIAbQwAAAQASQDqDAAABwBNAG4MAAACAEYAbwwAAAEATAAHAAkJLB7YDACyAgloDAAABwBVAGkMAAAHAFoAawwAAAcATABqDAAABwBHAGwMAAAGAEIAbQwAAAQASQDqDAAABwBNAG4MAAACAEYAbwwAAAEATAAAAA==.',
Gr='Graycat:BAAALgADCgIJAgABLgAFFAcJEQAaAL0jAA==.Grayele:BAAALgAECgIJAgAAAA==.Grayson:BAAALgAECgQJCgAAAA==.Graysurv:BAACLgAFFH8RAAIaAAcJvSMEAACBAgdoDAAAAgBZAGkMAAADAGEAawwAAAIAWwBqDAAAAgBFAGwMAAABAFAAbQwAAAEAWgDqDAAABgBjABoABwm9IwQAAIECB2gMAAACAFkAaQwAAAMAYQBrDAAAAgBbAGoMAAACAEUAbAwAAAEAUABtDAAAAQBaAOoMAAAGAGMALgAECn8iAAIaAAkJ+iYFAAAUBAAaAAkJ+iYFAAAUBAAAAA==.Gromlin:BAAALgAECgMJAwAAAA==.',
['Gä']='Gäreth:BAAALgADCgYJCwAAAA==.',
Ha='Habachi:BAAALgADCgEJAQAAAA==.Halcrenian:BAAALgAECgIJAgAAAA==.Hamelot:BAAALgADCgMJBAAAAA==.Hamremmi:BAAALgADCggJCAABLgAFFAYJFQAGABwYAA==.Hasalia:BAAALgAECggJCAABLgAECggJGAAPALsZAA==.',
He='Healsforu:BAAALgAECgUJDQAAAA==.Helly:BAAALgAECgEJAQAAAA==.Hemidall:BAAALgADCgMJAwAAAA==.Herbievore:BAABLgAECn8UAAMUAAgJORieEAA3AQhoDAAABABLAGkMAAAEAEUAawwAAAMAPABqDAAAAgBCAGwMAAABAEkAbQwAAAIAMADqDAAAAwBGAG4MAAABACQAFAAFCfEanhAANwEFaAwAAAIASwBpDAAAAgBFAGsMAAABADwAagwAAAIAQgDqDAAAAwBGAAsABgkCEeU2AMkABmgMAAACACoAaQwAAAIAEwBrDAAAAgApAGwMAAABAEkAbQwAAAIAMABuDAAAAQAkAAAA.Heunno:BAAALgADCgYJBgABLgADCgcJBwADAAAAAA==.',
Hi='Hiemy:BAAALgAECgYJBgAAAA==.Hif:BAABLgAECn8YAAIEAAkJTyO0BQAxAwloDAAAAwBgAGkMAAADAGIAawwAAAMAYQBqDAAAAgBbAGwMAAACAF4AbQwAAAIAUwDqDAAABQBfAG4MAAADAFMAbwwAAAEASAAEAAkJTyO0BQAxAwloDAAAAwBgAGkMAAADAGIAawwAAAMAYQBqDAAAAgBbAGwMAAACAF4AbQwAAAIAUwDqDAAABQBfAG4MAAADAFMAbwwAAAEASAAAAA==.Highbrittz:BAAALgAECgYJDQAAAA==.',
Ho='Hoakaren:BAABLgAECn8WAAISAAcJ8BWnLgCXAQdoDAAABQBLAGkMAAAFADYAawwAAAQAMwBqDAAAAQAPAGwMAAABADAA6gwAAAUAVABuDAAAAQAWABIABwnwFacuAJcBB2gMAAAFAEsAaQwAAAUANgBrDAAABAAzAGoMAAABAA8AbAwAAAEAMADqDAAABQBUAG4MAAABABYAAAA=.Hobiscuits:BAEALgADCgQJBAABLgAECgQJBAADAAAAAA==.Hocus:BAAALgADCgYJBgAAAA==.Holde:BAAALgAECgQJBQAAAA==.',
Hu='Hunterzamb:BAAALgAECgEJAQAAAA==.Huntinator:BAAALgAECgYJDgAAAA==.',
['Há']='Hátfield:BAAALgADCgEJAQAAAA==.',
Ih='Ihyo:BAAALgADCgIJAgABLgAECgcJBwADAAAAAA==.',
Il='Illyy:BAABLgAECn8kAAIMAAgJMguXIgBMAQhoDAAABgAmAGkMAAAFADIAawwAAAUAIwBqDAAABQASAGwMAAAFACAAbQwAAAEABgDqDAAABQAWAG4MAAAEABkADAAICTILlyIATAEIaAwAAAYAJgBpDAAABQAyAGsMAAAFACMAagwAAAUAEgBsDAAABQAgAG0MAAABAAYA6gwAAAUAFgBuDAAABAAZAAAA.',
In='Indawhole:BAACLgAFFH8VAAISAAYJ9BcSCQCYAQZoDAAABgBJAGkMAAABACMAawwAAAUAWABqDAAABAA+AGwMAAADACIA6gwAAAIASgASAAYJ9BcSCQCYAQZoDAAABgBJAGkMAAABACMAawwAAAUAWABqDAAABAA+AGwMAAADACIA6gwAAAIASgAuAAQKfxcAAhIACAn4I6sVAC0CABIACAn4I6sVAC0CAAAA.',
Ir='Iridori:BAABLgAECn8pAAIMAAgJmSD6BADYAghoDAAABwBdAGkMAAAGAFoAawwAAAYAUgBqDAAABgBYAGwMAAAFAFgAbQwAAAEARgDqDAAABgBXAG4MAAAEAEIADAAICZkg+gQA2AIIaAwAAAcAXQBpDAAABgBaAGsMAAAGAFIAagwAAAYAWABsDAAABQBYAG0MAAABAEYA6gwAAAYAVwBuDAAABABCAAAA.Irönfist:BAAALgADCgkJEgAAAA==.',
It='Itzzender:BAAALgADCgIJAgAAAA==.',
Iz='Izumiwitabow:BAAALgAECgUJCwAAAA==.',
Ja='Jamerius:BAAALgADCgIJAgAAAA==.Jasmean:BAAALgADCgMJAwAAAA==.Javaluminous:BAABLgAECn8hAAIHAAgJJh6EGABRAghoDAAABQBUAGkMAAAEAE0AawwAAAUATQBqDAAABQBbAGwMAAAEAF0AbQwAAAEALgDqDAAABQBXAG4MAAAEAEoABwAICSYehBgAUQIIaAwAAAUAVABpDAAABABNAGsMAAAFAE0AagwAAAUAWwBsDAAABABdAG0MAAABAC4A6gwAAAUAVwBuDAAABABKAAAA.Jay:BAAALgADCgcJDQABLgAFFAUJEgAbAEQbAA==.Jaytsukitori:BAACLgAFFH8OAAMEAAQJxx4yDwB5AQRoDAAABQBhAGkMAAADAF4AawwAAAIASADqDAAABAAyAAQABAnHHjIPAHkBBGgMAAAEAGEAaQwAAAMAXgBrDAAAAgBIAOoMAAAEADIACwABCYMIuy4ARgABaAwAAAEAFQAuAAQKfx0AAwQACAmKIbkMANcCAAQACAmKIbkMANcCAAsAAQlmED5gADUAAAAA.',
Jh='Jhaeriao:BAAALgAECgQJCgAAAA==.Jhantherox:BAAALgAECgYJBgAAAA==.',
Jo='Joesepi:BAABLgAFFH8RAAIFAAUJ3hZANwBAAQVoDAAABABCAGkMAAAEACoAawwAAAIAHABqDAAAAgBEAOoMAAAFAGEABQAFCd4WQDcAQAEFaAwAAAQAQgBpDAAABAAqAGsMAAACABwAagwAAAIARADqDAAABQBhAAAA.Joham:BAAALgAECgEJAQAAAA==.Jonah:BAAALgAECgUJCAABLgAECggJGAAFAGUjAA==.',
Ju='Juliofoolioo:BAAALgAECgEJAgAAAA==.',
Ka='Kayahli:BAAALgAECgQJBAAAAA==.Kazghul:BAAALgADCgEJAQAAAA==.',
Ke='Kelaeus:BAABLgAECn8VAAIQAAYJUQ5x0ABMAQZoDAAABAA5AGkMAAAEAB4AawwAAAQAGQBqDAAAAwAWAGwMAAACACYA6gwAAAQAHwAQAAYJUQ5x0ABMAQZoDAAABAA5AGkMAAAEAB4AawwAAAQAGQBqDAAAAwAWAGwMAAACACYA6gwAAAQAHwAAAA==.Keyonslayz:BAAALgADCggJCAAAAA==.',
Ki='Killzom:BAAALgADCgEJAQABLgAECgYJFAAUANAjAA==.Kilrah:BAABLgAECn8vAAIcAAkJ1xUTCgAIAgloDAAABgBEAGkMAAAGADsAawwAAAYAQwBqDAAABQAyAGwMAAAGAEcAbQwAAAUAPgDqDAAABwA1AG4MAAAFACUAbwwAAAEAGgAcAAkJ1xUTCgAIAgloDAAABgBEAGkMAAAGADsAawwAAAYAQwBqDAAABQAyAGwMAAAGAEcAbQwAAAUAPgDqDAAABwA1AG4MAAAFACUAbwwAAAEAGgAAAA==.Kirian:BAAALgADCgEJAQAAAA==.Kissmyash:BAAALgAECgQJDwAAAA==.Kissmycrits:BAABLgAECn8UAAICAAQJ/Bm/VAAqAQRoDAAABgBfAGkMAAAGADcAawwAAAQAJwDqDAAABABLAAIABAn8Gb9UACoBBGgMAAAGAF8AaQwAAAYANwBrDAAABAAnAOoMAAAEAEsAAAA=.Kiyana:BAABLgAECn8gAAIcAAcJlAvpHwD3AAdoDAAACAAsAGkMAAAGADAAawwAAAQAGwBqDAAABAAbAGwMAAADAB4AbQwAAAEAAQDqDAAABgAZABwABwmUC+kfAPcAB2gMAAAIACwAaQwAAAYAMABrDAAABAAbAGoMAAAEABsAbAwAAAMAHgBtDAAAAQABAOoMAAAGABkAAAA=.Kiyoine:BAABLgAECn8bAAIdAAgJuRExCgCgAQhoDAAABQA7AGkMAAAEAEIAawwAAAQAKwBqDAAABAA1AGwMAAADADEAbQwAAAEAJgDqDAAABAAuAG4MAAACAA4AHQAICbkRMQoAoAEIaAwAAAUAOwBpDAAABABCAGsMAAAEACsAagwAAAQANQBsDAAAAwAxAG0MAAABACYA6gwAAAQALgBuDAAAAgAOAAAA.',
Kn='Knocksteady:BAACLgAFFH8PAAIHAAUJWBihCgBXAQVoDAAABABHAGkMAAAEAEgAawwAAAIALQBqDAAAAgA5AOoMAAADADsABwAFCVgYoQoAVwEFaAwAAAQARwBpDAAABABIAGsMAAACAC0AagwAAAIAOQDqDAAAAwA7AC4ABAp/FwACBwAHCXMgiyQAlQIABwAHCXMgiyQAlQIAAAA=.Knoxform:BAAALgAECgMJBAAAAA==.Knoxhops:BAAALgAECgMJAwABLgAECgMJBAADAAAAAA==.Knoxreaps:BAAALgAECgIJAgABLgAECgMJBAADAAAAAA==.Knoxstaggers:BAABLgAECn8gAAIeAAgJJCD2EgB6AghoDAAABQBbAGkMAAADAFUAawwAAAMASwBqDAAABQBTAGwMAAAFAFQAbQwAAAEAPADqDAAABgBZAG4MAAAEAFgAHgAICSQg9hIAegIIaAwAAAUAWwBpDAAAAwBVAGsMAAADAEsAagwAAAUAUwBsDAAABQBUAG0MAAABADwA6gwAAAYAWQBuDAAABABYAAEuAAQKAwkEAAMAAAAA.',
Ku='Kuray:BAAALgAECgEJAgAAAA==.',
Ky='Kynbrookera:BAAALgAECggJEwAAAA==.Kyujin:BAAALgADCgEJAQAAAA==.',
['Kì']='Kìnky:BAAALgAECgUJCwAAAA==.',
La='Laetha:BAAALgADCgUJBQAAAA==.',
Le='Lemicall:BAAALgADCgQJCAAAAA==.Lethiferous:BAAALgAECgEJAQAAAA==.Letmespankit:BAAALgADCgYJDAAAAA==.Lezigo:BAABLgAECn8eAAIQAAgJMxOOPgDCAQhoDAAABQBHAGkMAAAFACcAawwAAAUAOgBqDAAABQAvAGwMAAAEADgAbQwAAAEACQDqDAAABABCAG4MAAABACkAEAAICTMTjj4AwgEIaAwAAAUARwBpDAAABQAnAGsMAAAFADoAagwAAAUALwBsDAAABAA4AG0MAAABAAkA6gwAAAQAQgBuDAAAAQApAAAA.',
Li='Licht:BAAALgAECgYJCwAAAA==.Lik:BAAALgAECgQJBwAAAA==.Lilhorror:BAAALgADCgMJAwAAAA==.Lilyheart:BAAALgADCgYJBgAAAA==.Linai:BAABLgAECn8ZAAIfAAgJEQhcCQBOAQhoDAAABAARAGkMAAAEABUAawwAAAQAEABqDAAAAwAXAGwMAAACABIAbQwAAAEAEwDqDAAABQAeAG4MAAACABMAHwAICREIXAkATgEIaAwAAAQAEQBpDAAABAAVAGsMAAAEABAAagwAAAMAFwBsDAAAAgASAG0MAAABABMA6gwAAAUAHgBuDAAAAgATAAAA.Lit:BAAALgAECgEJAgAAAA==.Littledog:BAABLgAECn8sAAMGAAgJbhelEQDbAQhoDAAACABaAGkMAAAIADoAawwAAAgAOgBqDAAABgBVAGwMAAAFADgAbQwAAAIAGQDqDAAABgA4AG4MAAABAEkABgAICW4XpREA2wEIaAwAAAcAWgBpDAAABgA6AGsMAAAGADoAagwAAAYAVQBsDAAABQA4AG0MAAACABkA6gwAAAYAOABuDAAAAQBJACAAAwkdFK09AL8AA2gMAAABABoAaQwAAAIATABrDAAAAgAzAAAA.',
Lo='Loky:BAABLgAECn8cAAMIAAkJvR5QPwAQAgloDAAAAwBjAGkMAAAEAGAAawwAAAMAWgBqDAAAAwBGAGwMAAADAE4AbQwAAAIAPADqDAAABQBbAG4MAAAEACUAbwwAAAEASQAIAAcJvR5QPwAQAgdoDAAAAwBjAGkMAAAEAGAAawwAAAIAWgBtDAAAAQA8AOoMAAAFAFsAbgwAAAQAJQBvDAAAAQBJABgABAl+GMskADUBBGsMAAABAEoAagwAAAMARgBsDAAAAwBOAG0MAAABACIAAAA=.Longshanks:BAAALgADCgUJDAAAAA==.Lorna:BAAALgADCgEJAQAAAA==.Lotten:BAAALgAECgQJBgAAAA==.',
Lu='Luckevin:BAAALgAECgYJDgAAAA==.Lunitari:BAAALgAECgQJBAAAAA==.Luthiean:BAAALgADCgQJBAAAAA==.Luthran:BAAALgAECgUJCwABLgAECggJGAAdAD8PAA==.',
Ly='Lynnali:BAAALgADCggJEQAAAA==.',
Ma='Magedon:BAAALgAECgEJAQAAAA==.Mageyoulaugh:BAABLgAECn8UAAIQAAcJOhcOUQCLAQdoDAAAAwBCAGkMAAAEADoAawwAAAMANQBqDAAAAgBJAGwMAAACADIAbQwAAAEAPgDqDAAABQBAABAABwk6Fw5RAIsBB2gMAAADAEIAaQwAAAQAOgBrDAAAAwA1AGoMAAACAEkAbAwAAAIAMgBtDAAAAQA+AOoMAAAFAEAAAAA=.Magezamb:BAAALgAECgUJDQAAAA==.Magmash:BAAALgADCggJDwAAAA==.Mahito:BAAALgADCgEJAQAAAA==.Mahru:BAAALgADCgYJCAAAAA==.Malafang:BAAALgAECgQJBgAAAA==.Malanah:BAAALgAECgUJCQAAAA==.Marandra:BAAALgADCgcJDAAAAA==.Mathalios:BAAALgAECgIJAgAAAA==.Mathenis:BAAALgAECgQJBgAAAA==.Mattu:BAAALgADCgkJGgAAAA==.Maverick:BAACLgAFFH8SAAIbAAUJRBunCABiAQVoDAAABgBhAGkMAAAFAFgAawwAAAQAWwBqDAAAAQAVAOoMAAACAAAAGwAFCUQbpwgAYgEFaAwAAAYAYQBpDAAABQBYAGsMAAAEAFsAagwAAAEAFQDqDAAAAgAAAC4ABAp/GwADGwAHCVQiwhUAYQIAGwAHCU0iwhUAYQIAHwAECYEilwwAWAEAAAA=.Maxbaba:BAAALgAECgEJAQAAAA==.',
Mc='Mcskittelz:BAAALgADCgQJBAAAAA==.',
Me='Meleshanorak:BAAALgADCgUJCgAAAA==.',
Mi='Michaella:BAAALgAECgUJCAAAAA==.Michartson:BAAALgADCgYJBAAAAA==.Mingres:BAAALgAECgYJEQAAAA==.Miramanie:BAAALgADCgYJBgAAAA==.Misdiagnosed:BAAALgADCgIJAgAAAA==.Mistbrewer:BAAALgADCgIJAgAAAA==.',
Mk='Mk:BAAALgAECgMJAwABLgAECggJNwAhAGsjAA==.',
Mo='Mogar:BAAALgAECgUJBwAAAA==.Mogina:BAAALgADCggJCAAAAA==.Monster:BAAALgAECgUJBQAAAA==.Moonzhine:BAABLgAECn8eAAIOAAgJYxRFDwCeAQhoDAAABQBSAGkMAAAFAD8AawwAAAUAQABqDAAABQAxAGwMAAAEACoAbQwAAAEACQDqDAAABAA0AG4MAAABADEADgAICWMURQ8AngEIaAwAAAUAUgBpDAAABQA/AGsMAAAFAEAAagwAAAUAMQBsDAAABAAqAG0MAAABAAkA6gwAAAQANABuDAAAAQAxAAAA.Moosejaw:BAAALgAECgQJBAAAAA==.Mordread:BAAALgAECgMJAwAAAA==.Morgalruk:BAAALgAECgYJDAAAAA==.',
My='Myriosheal:BAAALgADCgQJBAAAAA==.Mythx:BAACLgAFFH8WAAQCAAYJKR8DAgCBAQZoDAAABAA/AGkMAAAGAGEAawwAAAUAXQBqDAAAAgBFAGwMAAABAGAA6gwAAAQALwACAAUJeR0DAgCBAQVoDAAAAgA/AGkMAAAGAGEAawwAAAQAXQBqDAAAAgBFAOoMAAADAC8AGgADCZANGBMA7wADaAwAAAEAFwBrDAAAAQAhAOoMAAABAC8AAQACCUUUlhcAbgACaAwAAAEABwBsDAAAAQBgAC4ABAp/KwAEAgAICVYjfAgACgMAAgAICVYjfAgACgMAGgAGCfsYiBYAegEAAQAFCQUR7kwAHQEAAAA=.',
Na='Nalanelin:BAAALgAECggJDgAAAA==.Narukin:BAABLgAECn8bAAISAAcJmhmeIwDQAQdoDAAABQBUAGkMAAAEAEwAawwAAAUAUABqDAAABgBHAGwMAAACAEMAbQwAAAMAOQDqDAAAAgAaABIABwmaGZ4jANABB2gMAAAFAFQAaQwAAAQATABrDAAABQBQAGoMAAAGAEcAbAwAAAIAQwBtDAAAAwA5AOoMAAACABoAAAA=.Naturboy:BAAALgADCgYJBgAAAA==.',
Ne='Nessirebette:BAAALgADCgUJCAAAAA==.Netherwalker:BAAALgAECgIJAgABLgAFFAYJFQAGABwYAA==.',
Ni='Nivmizzet:BAABLgAECn8pAAMIAAgJARmoKgDQAQhoDAAABwBOAGkMAAAGAEYAawwAAAYARgBqDAAABgBRAGwMAAAFADQAbQwAAAEALQDqDAAABgBIAG4MAAAEADkACAAHCd4ZqCoA0AEHaAwAAAYASQBpDAAABQBGAGsMAAAEAEYAagwAAAEALgBsDAAABQA0AOoMAAAGAEgAbgwAAAQAOQAYAAUJyBUqLQAJAQVoDAAAAQBOAGkMAAABAC0AawwAAAIANQBqDAAABQBRAG0MAAABAC0AAAA=.',
No='Nolakai:BAAALgAECgEJAQAAAA==.Nomiro:BAAALgAECgYJDAAAAA==.Noradori:BAAALgAECgEJAQAAAA==.Notdip:BAAALgADCgIJAgAAAA==.Novalea:BAABLgAECn9IAAMiAAkJRCOBAQB8AwloDAAACgBhAGkMAAAKAFoAawwAAAcAYQBqDAAACQBeAGwMAAAJAF8AbQwAAAcAXgDqDAAACQBZAG4MAAAGAEkAbwwAAAUAUQAiAAkJRCOBAQB8AwloDAAABgBhAGkMAAAHAFoAawwAAAYAYQBqDAAACABeAGwMAAAIAF8AbQwAAAcAXgDqDAAABgBZAG4MAAAEAEkAbwwAAAUAUQAVAAcJwxv3GwCLAQdoDAAABABZAGkMAAADAEoAawwAAAEASQBqDAAAAQBIAGwMAAABAE0A6gwAAAMAQwBuDAAAAgAsAAAA.',
Nu='Nuru:BAAALgAECgcJEAAAAA==.',
['Nø']='Nøstalgic:BAAALgAECgEJAgAAAA==.',
Ob='Obala:BAAALgADCgIJAgAAAA==.',
Od='Odogaren:BAABLgAECn8ZAAMZAAgJzxxbCwBYAghoDAAABABhAGkMAAAEAFsAawwAAAQAVABqDAAAAwBeAGwMAAADAFMAbQwAAAIAQADqDAAABABSAG4MAAABAAsAGQAHCYAdWwsAWAIHaAwAAAIASQBpDAAAAgBIAGsMAAABAFQAagwAAAIAXgBsDAAAAgBTAG0MAAABAEAA6gwAAAIASwANAAgJhRoVIQBLAghoDAAAAgBhAGkMAAACAFsAawwAAAMARwBqDAAAAQBJAGwMAAABADwAbQwAAAEAOwDqDAAAAgBSAG4MAAABAAsAAAA=.',
Om='Omnithorn:BAAALgAECggJDQAAAA==.',
On='Onei:BAAALgADCgEJAQAAAA==.',
Or='Oramos:BAAALgAECgQJBgAAAA==.Orgóndó:BAABLgAFFH8IAAIOAAQJ+hutDwAEAQRoDAAAAgBTAGkMAAACAFYAagwAAAIAKwDqDAAAAgAtAA4ABAn6G60PAAQBBGgMAAACAFMAaQwAAAIAVgBqDAAAAgArAOoMAAACAC0AAAA=.',
Ox='Oxxo:BAAALgAECgYJDAAAAA==.',
Pa='Palzamb:BAAALgADCgYJCwAAAA==.Pandacillin:BAAALgAECgQJBAAAAA==.Paraggonn:BAAALgAECgYJEgAAAA==.',
Pe='Penoosê:BAAALgADCgEJAgAAAA==.Perlonis:BAAALgAECgYJEwAAAA==.',
Ph='Phatocaster:BAAALgADCgIJBAAAAA==.Phoinyx:BAAALgAECgkJDwAAAA==.Phuriosa:BAAALgAECgQJBAABLgAECggJIQAEABsZAA==.Phury:BAABLgAECn8hAAIEAAgJGxk4GAAgAghoDAAABgBMAGkMAAAGAEsAawwAAAYAVQBqDAAABQA/AGwMAAAEADYAbQwAAAEAOgDqDAAABAA8AG4MAAABACcABAAICRsZOBgAIAIIaAwAAAYATABpDAAABgBLAGsMAAAGAFUAagwAAAUAPwBsDAAABAA2AG0MAAABADoA6gwAAAQAPABuDAAAAQAnAAAA.Physinyx:BAAALgAECgkJCgAAAA==.Physta:BAAALgADCgUJBQAAAA==.',
Pi='Pizza:BAAALgAECgYJDAAAAA==.',
Pl='Plagafel:BAAALgADCgYJBgAAAA==.',
Po='Pomomies:BAAALgAECgMJBAAAAA==.Pooseunpoose:BAAALgAFFAEJBAAAAA==.Porkmancer:BAAALgAECgYJCgAAAA==.Porkslope:BAABLgAECn8fAAIFAAgJtR6PHAA7AghoDAAABQBVAGkMAAAEAE4AawwAAAQANgBqDAAABABbAGwMAAAEAFgAbQwAAAEAXQDqDAAABQBJAG4MAAAEAEwABQAICbUejxwAOwIIaAwAAAUAVQBpDAAABABOAGsMAAAEADYAagwAAAQAWwBsDAAABABYAG0MAAABAF0A6gwAAAUASQBuDAAABABMAAAA.',
Pr='Praahv:BAAALgADCgYJBgAAAA==.Profryktor:BAAALgAECgQJBwAAAA==.',
Pu='Purebloods:BAAALgADCgEJAQAAAA==.',
Qu='Quickben:BAAALgAECgIJAgAAAA==.',
Ra='Raenyx:BAABLgAECn8hAAMIAAgJORopHAAeAghoDAAABQBVAGkMAAAFADUAawwAAAUAQwBqDAAABQBbAGwMAAAEAEoAbQwAAAIARADqDAAABQBNAG4MAAACACkACAAICTkaKRwAHgIIaAwAAAUAVQBpDAAABQA1AGsMAAAFAEMAagwAAAEAWwBsDAAABABKAG0MAAACAEQA6gwAAAUATQBuDAAAAgApABEAAQkAAFEsAEYAAWoMAAAEAEIAAAA=.Raiflock:BAAALgAECgMJAwAAAA==.Ranalastus:BAAALgAECgQJBwAAAA==.Ravenblack:BAAALgAECgEJAQAAAA==.Raveneyes:BAEBLgAECn8eAAIIAAgJDA8yPgCEAQhoDAAABQA6AGkMAAAFAC4AawwAAAUAIwBqDAAABQA7AGwMAAAEADAAbQwAAAEACQDqDAAABAA1AG4MAAABABIACAAICQwPMj4AhAEIaAwAAAUAOgBpDAAABQAuAGsMAAAFACMAagwAAAUAOwBsDAAABAAwAG0MAAABAAkA6gwAAAQANQBuDAAAAQASAAAA.',
Re='Reiena:BAAALgAECgYJCQAAAA==.Relas:BAAALgADCgUJBQAAAA==.Reylilyn:BAABLgAECn8gAAIWAAkJlRTjDAA9AgloDAAABQBAAGkMAAAFAFUAawwAAAUANABqDAAABABHAGwMAAADAC4AbQwAAAEAJADqDAAABQA7AG4MAAADACgAbwwAAAEAEAAWAAkJlRTjDAA9AgloDAAABQBAAGkMAAAFAFUAawwAAAUANABqDAAABABHAGwMAAADAC4AbQwAAAEAJADqDAAABQA7AG4MAAADACgAbwwAAAEAEAAAAA==.',
Rh='Rhaenfyre:BAABLgAECn8YAAISAAcJLhEhWQAKAQdoDAAABQA0AGkMAAAFADgAawwAAAQAHQBqDAAAAgAZAGwMAAABAB0A6gwAAAYAOwBuDAAAAQAkABIABwkuESFZAAoBB2gMAAAFADQAaQwAAAUAOABrDAAABAAdAGoMAAACABkAbAwAAAEAHQDqDAAABgA7AG4MAAABACQAAAA=.',
Ri='Richardhurtz:BAAALgADCgEJAQAAAA==.Ricola:BAAALgAFFAIJBAAAAA==.Rivenel:BAABLgAECn8fAAIYAAgJxyLVAAC6AghoDAAABQBfAGkMAAAFAFIAawwAAAUAUwBqDAAABABYAGwMAAAEAFgAbQwAAAIAUwDqDAAABQBgAG4MAAABAFwAGAAICcci1QAAugIIaAwAAAUAXwBpDAAABQBSAGsMAAAFAFMAagwAAAQAWABsDAAABABYAG0MAAACAFMA6gwAAAUAYABuDAAAAQBcAAAA.Rivèn:BAAALgADCgEJAQAAAA==.',
Ro='Robinvoid:BAABLgAECn8dAAMSAAkJgCAPFQDZAgloDAAABABfAGkMAAAEAF4AawwAAAQAYQBqDAAAAwBMAGwMAAADAFsAbQwAAAIANgDqDAAABQBeAG4MAAACAFQAbwwAAAIANAASAAkJgCAPFQDZAgloDAAABABfAGkMAAAEAF4AawwAAAQAYQBqDAAAAwBMAGwMAAADAFsAbQwAAAIANgDqDAAABABeAG4MAAACAFQAbwwAAAIANAAcAAEJ+RRiaQBAAAHqDAAAAQA1AAAA.Rocksann:BAAALgADCggJDQAAAA==.Rodel:BAAALgAECgEJAQAAAA==.Roquan:BAABLgAECn8pAAIjAAgJ5RsQAwAgAghoDAAABwBJAGkMAAAGAEEAawwAAAYAOgBqDAAABgBAAGwMAAAFAFQAbQwAAAEAQADqDAAABgBUAG4MAAAEAEUAIwAICeUbEAMAIAIIaAwAAAcASQBpDAAABgBBAGsMAAAGADoAagwAAAYAQABsDAAABQBUAG0MAAABAEAA6gwAAAYAVABuDAAABABFAAAA.Roulette:BAAALgAECgQJBAAAAA==.',
Ru='Rubmyrott:BAAALgAECgMJBAAAAA==.Runalot:BAAALgADCgYJBgAAAA==.',
['Rê']='Rêdd:BAAALgAECgYJCAAAAA==.',
Sa='Sabeion:BAAALgAECgYJDAAAAA==.Salswarriah:BAAALgAECgQJCwAAAA==.Sanaku:BAAALgAECgYJCAAAAA==.Sanangra:BAAALgADCgEJAQAAAA==.Santo:BAAALgADCgMJAwAAAA==.Sarlyan:BAAALgADCgkJFwAAAA==.Sassafrazz:BAAALgAECgQJBAAAAA==.',
Sc='Scottee:BAAALgAECgEJAQABLgAECgUJFQAVAF0TAA==.Scottlee:BAAALgADCgIJBAABLgAECgUJFQAVAF0TAA==.Scrumbles:BAAALgAECgcJDwAAAA==.',
Se='Secksytoes:BAAALgAECgMJAwABLgADCgYJCwADAAAAAA==.Seraphim:BAAALgADCgEJAQAAAA==.Serion:BAAALgADCgMJAwAAAA==.Sewerrat:BAAALgADCggJCAAAAA==.',
Sg='Sgtpunchy:BAAALgADCgMJBQABLgAECgUJDQADAAAAAA==.',
Sh='Shakuro:BAAALgAECgEJAgAAAA==.Shallash:BAAALgADCgUJBgAAAA==.Shamageddon:BAAALgAECgIJAgAAAA==.Shamanizim:BAABLgAECn8qAAQVAAgJlBzJCwA4AghoDAAABwBIAGkMAAAGAFIAawwAAAcATgBqDAAABQBeAGwMAAAFAEUAbQwAAAEAPADqDAAABwBNAG4MAAAEAEYAFQAICSkcyQsAOAIIaAwAAAQASABpDAAAAwBSAGsMAAAEAE4AagwAAAQAXgBsDAAABAA9AG0MAAABADwA6gwAAAYATQBuDAAAAgBGABMABwnlFbAKAIYBB2gMAAACAD8AaQwAAAMAQQBrDAAAAwA0AGoMAAABABUAbAwAAAEARQDqDAAAAQAjAG4MAAABADIAIgACCScGFYYAQAACaAwAAAEADQBuDAAAAQARAAAA.Sheeanna:BAAALgAFFAEJAQABLgAECggJGAAPALsZAA==.Shiftmyself:BAAALgADCgkJDgAAAA==.Shinoikari:BAABLgAECn8XAAMjAAgJGgz4CgATAQhoDAAABAAhAGkMAAADADkAawwAAAQAFwBqDAAAAgAMAGwMAAABABEAbQwAAAEAAwDqDAAABgA0AG4MAAACAB4AIwAICRoM+AoAEwEIaAwAAAMAIQBpDAAAAgA5AGsMAAADABcAagwAAAEABABsDAAAAQARAG0MAAABAAMA6gwAAAQANABuDAAAAgAeAA4ABQmFA4YvAHUABWgMAAABAAQAaQwAAAEACQBrDAAAAQANAGoMAAABAAwA6gwAAAIACAAAAA==.Shinotenshi:BAAALgAECgYJDQABLgAECggJFwAjABoMAA==.Shirase:BAAALgAECgkJEgABLgAECgkJSAAiAEQjAA==.Shugarae:BAABLgAECn8VAAMLAAcJdQSzWADBAAdoDAAABAAEAGkMAAADAAwAawwAAAMACgBqDAAABAAJAGwMAAADABEA6gwAAAMADwBuDAAAAQAHAAsABwl1BLNYAMEAB2gMAAACAAQAaQwAAAEADABrDAAAAQAKAGoMAAACAAkAbAwAAAMAEQDqDAAAAgAPAG4MAAABAAcABAAFCXAEr3QAfQAFaAwAAAIADABpDAAAAgAZAGsMAAACAAgAagwAAAIABwDqDAAAAQABAAAA.',
Si='Sionnocht:BAAALgADCgEJAQAAAA==.Sirlemage:BAAALgADCgMJAwAAAA==.',
Sk='Skina:BAAALgAECgEJAQAAAA==.Skreezy:BAAALgAECgcJDAAAAA==.Skuls:BAAALgADCggJCgAAAA==.',
Sl='Slashemup:BAABLgAECn8eAAIcAAgJcxQLDgC+AQhoDAAABQA+AGkMAAAFADwAawwAAAUAOwBqDAAABQA4AGwMAAAEADwAbQwAAAEAIgDqDAAABAA5AG4MAAABAB4AHAAICXMUCw4AvgEIaAwAAAUAPgBpDAAABQA8AGsMAAAFADsAagwAAAUAOABsDAAABAA8AG0MAAABACIA6gwAAAQAOQBuDAAAAQAeAAAA.Slayter:BAABLgAECn8kAAIEAAkJ2B9XEQBlAgloDAAABgBOAGkMAAAGAFQAawwAAAUAYABqDAAABABgAGwMAAACAGMAbQwAAAIAQgDqDAAABwBfAG4MAAADAEoAbwwAAAEAKQAEAAkJ2B9XEQBlAgloDAAABgBOAGkMAAAGAFQAawwAAAUAYABqDAAABABgAGwMAAACAGMAbQwAAAIAQgDqDAAABwBfAG4MAAADAEoAbwwAAAEAKQAAAA==.',
Sm='Smaugin:BAAALgAECgIJAgAAAA==.',
Sn='Snakelazers:BAABLgAECn8cAAIWAAkJiSGzAwAQAwloDAAABABgAGkMAAAEAF8AawwAAAQAYABqDAAAAgBXAGwMAAACAFYAbQwAAAIAUwDqDAAABQBXAG4MAAAEAFMAbwwAAAEANwAWAAkJiSGzAwAQAwloDAAABABgAGkMAAAEAF8AawwAAAQAYABqDAAAAgBXAGwMAAACAFYAbQwAAAIAUwDqDAAABQBXAG4MAAAEAFMAbwwAAAEANwAAAA==.Snufulafagus:BAAALgAECgUJDQAAAA==.',
So='Soju:BAABLgAECn8UAAMiAAcJ4BH8QAAjAQdoDAAABQA8AGkMAAAEAEIAawwAAAQASQBqDAAAAQAgAGwMAAABAAsAbQwAAAEACgDqDAAABABAACIABwngEfxAACMBB2gMAAAEADwAaQwAAAQAQgBrDAAABABJAGoMAAABACAAbAwAAAEACwBtDAAAAQAKAOoMAAADAEAAFQACCesRpFMAdQACaAwAAAEAPwDqDAAAAQAcAAEuAAQKCQkpAAIAiCIA.Songwind:BAABLgAECn8WAAIhAAYJzgZ3NwC7AAZoDAAABQAlAGkMAAAFABwAawwAAAQABwBqDAAAAwAGAGwMAAACAAgA6gwAAAMABAAhAAYJzgZ3NwC7AAZoDAAABQAlAGkMAAAFABwAawwAAAQABwBqDAAAAwAGAGwMAAACAAgA6gwAAAMABAAAAA==.Soonie:BAAALgADCgEJAQAAAA==.',
Sq='Squishypal:BAAALgAECgYJEgAAAA==.',
St='Starfirelmao:BAAALgAECgYJDwAAAA==.Strawdicks:BAAALgAECgcJAQAAAA==.',
Su='Sugma:BAAALgAECgEJAQAAAA==.Suzsette:BAAALgAECgUJDgAAAA==.',
Sy='Sylris:BAAALgADCgkJFgAAAA==.Sylvanthis:BAAALgADCgcJBwAAAA==.',
['Sç']='Sçoxx:BAAALgADCgEJAQAAAA==.',
Ta='Taazdingo:BAAALgADCgEJAQAAAA==.Talnora:BAAALgAECgYJDwAAAA==.Tardovski:BAABLgAECn8bAAMCAAcJRx7fGAAlAgdoDAAABQBXAGkMAAAFAGIAawwAAAUAYgBqDAAAAwBgAGwMAAADAE0A6gwAAAUAUwBuDAAAAQASAAIABwlHHt8YACUCB2gMAAADAFcAaQwAAAMAYgBrDAAAAwBiAGoMAAADAGAAbAwAAAMATQDqDAAAAwBTAG4MAAABABIAAQAECdgT9lYA7AAEaAwAAAIAMABpDAAAAgAuAGsMAAACAEIA6gwAAAIAKQAAAA==.Taurentino:BAAALgAECgkJBQAAAA==.',
Te='Telaris:BAAALgADCgIJAgAAAA==.Telda:BAAALgADCgkJGQAAAA==.Teneturadvós:BAAALgAECgcJAwAAAA==.Tentreeadvos:BAAALgAECgEJAQABLgAECgcJAwADAAAAAA==.Tetris:BAABLgAECn8yAAIQAAkJoCJQBwAPAwloDAAABwBeAGkMAAAIAF4AawwAAAcAWgBqDAAABgBaAGwMAAAGAGEAbQwAAAQASgDqDAAABgBeAG4MAAAEAFYAbwwAAAIATQAQAAkJoCJQBwAPAwloDAAABwBeAGkMAAAIAF4AawwAAAcAWgBqDAAABgBaAGwMAAAGAGEAbQwAAAQASgDqDAAABgBeAG4MAAAEAFYAbwwAAAIATQAAAA==.',
Th='Thraggoar:BAAALgADCgEJAQAAAA==.Thunsar:BAAALgAECgkJDwAAAA==.Thuzzad:BAAALgADCgUJBQAAAA==.',
Ti='Tickler:BAAALgAECgUJEQAAAA==.',
To='Toetem:BAAALgADCgQJBgAAAA==.Tox:BAAALgADCgUJBQAAAA==.Toyotama:BAAALgAECgYJBgABLgAFFAQJDgAEAMceAA==.',
Tr='Trane:BAAALgAECgIJAgAAAA==.Tritoch:BAAALgAECgYJEAAAAA==.Troche:BAAALgAECgkJEAAAAA==.Truthfully:BAAALgAECgYJDwAAAA==.Trávpac:BAAALgADCgEJAQAAAA==.',
Tt='Ttjpll:BAAALgAECgUJCAAAAA==.',
Tu='Tuckncloak:BAAALgAECgIJAgAAAA==.',
Ug='Ugrup:BAAALgAECgUJBgAAAA==.',
Uj='Ujabula:BAAALgAECgUJCwAAAA==.',
Ul='Ulurak:BAABLgAECn8YAAMdAAgJPw8aGwAaAQhoDAAABAAdAGkMAAAEACEAawwAAAMAFgBqDAAAAgARAGwMAAACAA4AbQwAAAIARwDqDAAABgAWAG4MAAABAE8AHQAGCZMJGhsAGgEGaAwAAAQAHQBpDAAABAAhAGsMAAADABYAagwAAAIAEQBsDAAAAQAOAOoMAAADABYABAAECfUKoX4AZgAEbAwAAAEAAgBtDAAAAgAWAOoMAAADACwAbgwAAAEAKgAAAA==.',
Un='Uncleskip:BAABLgAECn8bAAIkAAcJ0wd0FgBJAQdoDAAABQAcAGkMAAAFABYAawwAAAQAFwBqDAAABAATAGwMAAAEAAkA6gwAAAQAEwBuDAAAAQAPACQABwnTB3QWAEkBB2gMAAAFABwAaQwAAAUAFgBrDAAABAAXAGoMAAAEABMAbAwAAAQACQDqDAAABAATAG4MAAABAA8AAAA=.Unhappytoast:BAAALgAECgYJDwAAAA==.Unstobubble:BAAALgAECgYJCQAAAA==.',
Va='Valeriya:BAAALgADCgMJAwABLgAECgEJAQADAAAAAA==.Valisanna:BAAALgADCggJCwAAAA==.Vallorien:BAAALgAECgUJDwAAAA==.Valsharess:BAAALgADCgcJBwABLgAECgkJOAASAEAaAA==.',
Ve='Vegtam:BAAALgAECgEJAQAAAA==.Velnia:BAAALgAECgYJCgAAAA==.Verencia:BAAALgAECgEJAQAAAA==.',
Vi='Vildaren:BAAALgAECgUJCQAAAA==.Vivachel:BAAALgADCgcJCAAAAA==.',
Vo='Vorsan:BAAALgADCgcJBwAAAA==.Vorsane:BAAALgADCgQJBAAAAA==.',
['Và']='Vàli:BAAALgAECgEJAQAAAA==.',
Wa='Wasenshi:BAAALgADCgUJBQAAAA==.',
We='Weeb:BAAALgADCgUJCwAAAA==.Weeny:BAAALgAECgcJCwAAAA==.',
Wh='Wholy:BAAALgAECgIJAgAAAA==.',
Wi='Wickedromeo:BAAALgAECgMJAwAAAA==.',
Wo='Wolfmother:BAABLgAECn8VAAIVAAUJXRMhNQDzAAVoDAAABQAzAGkMAAAFAEIAawwAAAQALQBqDAAAAgA8AOoMAAAFACMAFQAFCV0TITUA8wAFaAwAAAUAMwBpDAAABQBCAGsMAAAEAC0AagwAAAIAPADqDAAABQAjAAAA.',
Xa='Xaanii:BAAALgAECgUJDwAAAA==.Xandius:BAAALgADCgcJDAAAAA==.Xarferrin:BAAALgAECgYJDAAAAA==.',
Xe='Xeeria:BAACLgAFFH8MAAIiAAQJlxBSHgAIAQRoDAAABQBDAGkMAAAEADkAawwAAAEAGQDqDAAAAgATACIABAmXEFIeAAgBBGgMAAAFAEMAaQwAAAQAOQBrDAAAAQAZAOoMAAACABMALgAECn8pAAIiAAgJYiIKDQC1AgAiAAgJYiIKDQC1AgAAAA==.Xenzull:BAAALgAECgIJAgAAAA==.',
Xk='Xkaliber:BAAALgADCgEJAQAAAA==.',
Xu='Xuecat:BAABLgAECn8kAAIEAAgJ3xYQLgD1AQhoDAAABQBLAGkMAAAFAEEAawwAAAYARwBqDAAABQAgAGwMAAAFAEAAbQwAAAIAIgDqDAAABQBBAG4MAAADADoABAAICd8WEC4A9QEIaAwAAAUASwBpDAAABQBBAGsMAAAGAEcAagwAAAUAIABsDAAABQBAAG0MAAACACIA6gwAAAUAQQBuDAAAAwA6AAAA.',
Yn='Yn:BAAALgAECgYJCgAAAA==.',
Za='Zamzak:BAAALgADCgQJBAABLgAECgEJAQADAAAAAA==.Zanthor:BAABLgAECn8VAAIFAAUJbgh8kwDWAAVoDAAABgAWAGkMAAAFABsAawwAAAcAGgBqDAAAAgAVAGwMAAABAAkABQAFCW4IfJMA1gAFaAwAAAYAFgBpDAAABQAbAGsMAAAHABoAagwAAAIAFQBsDAAAAQAJAAAA.Zaralina:BAABLgAECn8lAAIGAAkJsBOgDAAbAgloDAAABwAtAGkMAAAHAEAAawwAAAcAMQBqDAAABAAwAGwMAAADADwAbQwAAAMAOQDqDAAAAwA+AG4MAAACACkAbwwAAAEAFQAGAAkJsBOgDAAbAgloDAAABwAtAGkMAAAHAEAAawwAAAcAMQBqDAAABAAwAGwMAAADADwAbQwAAAMAOQDqDAAAAwA+AG4MAAACACkAbwwAAAEAFQAAAA==.Zartox:BAABLgAECn8UAAIlAAYJCRcyBABsAQZoDAAABABLAGkMAAAEAEQAawwAAAQAMABqDAAAAgAqAGwMAAACADEA6gwAAAQANAAlAAYJCRcyBABsAQZoDAAABABLAGkMAAAEAEQAawwAAAQAMABqDAAAAgAqAGwMAAACADEA6gwAAAQANAAAAA==.Zaryn:BAAALgADCgIJAgAAAA==.Zaryssa:BAABLgAECn8UAAIVAAgJlwQmOQDhAAhoDAAAAwAIAGkMAAADABEAawwAAAMABgBqDAAAAwAJAGwMAAADAB0AbQwAAAIACgDqDAAAAgADAG4MAAABAAYAFQAICZcEJjkA4QAIaAwAAAMACABpDAAAAwARAGsMAAADAAYAagwAAAMACQBsDAAAAwAdAG0MAAACAAoA6gwAAAIAAwBuDAAAAQAGAAAA.Zavinus:BAAALgADCgYJCAAAAA==.',
Ze='Zenzug:BAAALgAECgUJDQAAAA==.Zephystra:BAAALgADCgQJBAABLgAECgkJSAAiAEQjAA==.Zeusqt:BAAALgADCgYJBgAAAA==.',
Zh='Zharfrost:BAAALgADCgkJCwAAAA==.',
Zi='Zicroniah:BAAALgADCgYJCgAAAA==.Ziyuu:BAAALgADCgUJBQAAAA==.',
Zo='Zombiehunter:BAAALgAECggJEwAAAA==.',
Zu='Zuzu:BAAALgADCgMJAwAAAA==.',
['Âr']='Ârc:BAAALgAECgEJAgAAAA==.',
['Èd']='Èddy:BAAALgAECgYJDwAAAA==.',
['Ût']='Ûthèr:BAAALgADCgEJAQAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
