local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Priest-Discipline','Unknown-Unknown','Priest-Holy','Mage-Frost','Paladin-Retribution','Paladin-Holy','Monk-Mistweaver','Priest-Shadow','Warrior-Fury','Monk-Windwalker','DeathKnight-Unholy','Druid-Restoration','Warlock-Demonology','Shaman-Restoration','DeathKnight-Frost','Mage-Arcane','Druid-Balance','Druid-Guardian','Monk-Brewmaster','Druid-Feral','Evoker-Augmentation','Evoker-Devastation','DeathKnight-Blood','Warrior-Arms','Warrior-Protection','DemonHunter-Devourer','Hunter-Survival','Hunter-BeastMastery','Hunter-Marksmanship','Shaman-Enhancement','Shaman-Elemental','DemonHunter-Havoc','DemonHunter-Vengeance','Evoker-Preservation','Mage-Fire','Paladin-Protection',}
local provider = {region='US',realm='Gundrak',name='US',type='daily',zone=46,date='2026-05-23',data={Ad='Adelyne:BAAALgAFFAIJAgABLgAFFAUJDgABAG0SAA==.Adera:BAAALgAECgYJBwAAAA==.',
Af='Aff:BAAALgADCgYJBgAAAA==.',
Ag='Agony:BAAALgAECgQJBgAAAA==.',
Ah='Ahkanon:BAAALgADCgEJAQAAAA==.',
Ai='Aiden:BAAALgAECgEJAgABLgAECgIJAgACAAAAAA==.Aidendk:BAAALgADCgIJAgABLgAECgIJAgACAAAAAA==.Aidenp:BAAALgADCgIJAgABLgAECgIJAgACAAAAAA==.Air:BAAALgADCgcJBwABLgAFFAgJIgADADkbAA==.',
Ak='Aku:BAAALgADCgIJBAAAAA==.',
Al='Aleniastra:BAAALgAECgYJEwAAAA==.Alexyss:BAAALgAECgUJDgAAAA==.Alykard:BAABLgAECn8xAAIEAAkJwhESPwAEAgloDAAABwA3AGkMAAAGADwAawwAAAYAMgBqDAAABgAxAGwMAAAFAEMAbQwAAAMAGwDqDAAABwAcAG4MAAAFADgAbwwAAAQAEAAEAAkJwhESPwAEAgloDAAABwA3AGkMAAAGADwAawwAAAYAMgBqDAAABgAxAGwMAAAFAEMAbQwAAAMAGwDqDAAABwAcAG4MAAAFADgAbwwAAAQAEAAAAA==.',
Am='Amyara:BAAALgADCgEJAQAAAA==.',
An='Andronicas:BAABLgAECn8dAAMFAAkJ6A0BVACvAQloDAAAAwAsAGkMAAAEACsAawwAAAcAOQBqDAAABAAgAGwMAAAEACkAbQwAAAIADADqDAAAAwAoAG4MAAABABcAbwwAAAEAEwAFAAkJ6A0BVACvAQloDAAAAwAsAGkMAAAEACsAawwAAAYAOQBqDAAABAAgAGwMAAAEACkAbQwAAAIADADqDAAAAwAoAG4MAAABABcAbwwAAAEAEwAGAAEJogevnAAtAAFrDAAAAQATAAAA.Aneira:BAABLgAFFH8SAAIEAAQJfQZhbgDYAARoDAAACAAOAGkMAAADABYAawwAAAIABwDqDAAABQAVAAQABAl9BmFuANgABGgMAAAIAA4AaQwAAAMAFgBrDAAAAgAHAOoMAAAFABUAAAA=.',
Ap='Apexis:BAAALgADCgYJCQAAAA==.',
Ar='Ariaa:BAAALgAECgQJCAAAAA==.Arieyri:BAAALgADCgcJBwAAAA==.Artpop:BAAALgAFFAEJAQABLgAFFAYJDwAHALISAA==.',
As='Ash:BAAALgADCgcJCwAAAA==.Ashvira:BAAALgAECgEJAQAAAA==.Aspect:BAAALgADCgcJDgABLgAECgEJAQACAAAAAA==.Astarael:BAABLgAECn8iAAMIAAkJShfzGgDHAQloDAAABQBKAGkMAAAFADsAawwAAAQALABqDAAABABHAGwMAAAEADUAbQwAAAMAJQDqDAAABgBPAG4MAAACAC8AbwwAAAEAUAAIAAgJGhbzGgDHAQhoDAAABQBKAGkMAAAEADsAawwAAAMALABqDAAAAwBHAGwMAAADADUAbQwAAAIAJQDqDAAABgBPAG4MAAABAC8AAwAHCS0O4FoAyAAHaQwAAAEAFwBrDAAAAQAdAGoMAAABACAAbAwAAAEALABtDAAAAQA4AG4MAAABADIAbwwAAAEAEQAAAA==.',
Av='Avi:BAABLgAECn8YAAIBAAgJcxFqGgDPAQhoDAAAAwAoAGkMAAADAC8AawwAAAMAJwBqDAAABAAqAGwMAAAEADAAbQwAAAEAGgDqDAAABQBTAG4MAAABAB0AAQAICXMRahoAzwEIaAwAAAMAKABpDAAAAwAvAGsMAAADACcAagwAAAQAKgBsDAAABAAwAG0MAAABABoA6gwAAAUAUwBuDAAAAQAdAAEuAAQKCQlwAAkAeCAA.',
Ba='Babygurl:BAACLgAFFH8FAAIGAAMJNx9LHAAMAQNoDAAAAgBNAGkMAAABAEMA6gwAAAIAXgAGAAMJNx9LHAAMAQNoDAAAAgBNAGkMAAABAEMA6gwAAAIAXgAuAAQKf3YAAgYACQntJVkBAJUDAAYACQntJVkBAJUDAAAA.Baragas:BAAALgAECgYJDAAAAA==.Bareback:BAAALgAECgQJBAAAAA==.Barney:BAAALgADCgEJAQAAAA==.Battosaî:BAAALgAECgQJBAAAAA==.',
Be='Beeny:BAACLgAFFH8zAAIHAAgJ+SLjAAAgAwhoDAAACABhAGkMAAALAGMAawwAAAcASgBqDAAACABVAGwMAAAEAGEAbQwAAAEASwDqDAAACwBaAG4MAAABAGAABwAICfki4wAAIAMIaAwAAAgAYQBpDAAACwBjAGsMAAAHAEoAagwAAAgAVQBsDAAABABhAG0MAAABAEsA6gwAAAsAWgBuDAAAAQBgAC4ABAp/QQADBwAJCWkjhQgAzAIABwAJCWkjhQgAzAIACgABCWwQCH4ANQAAAAA=.Berat:BAAALgADCgQJBAAAAA==.Berzerker:BAAALgADCgcJEwAAAA==.',
Bg='Bgc:BAAALgADCgUJBQAAAA==.',
Bi='Binari:BAAALgAECgMJAwABLgAFFAMJBQAJACoUAA==.Binlock:BAAALgAECgQJBAABLgAFFAMJBQAJACoUAA==.',
Bl='Bl:BAAALgAECgMJAwAAAA==.Bladebear:BAABLgAECn82AAIEAAkJUxUFPwAEAgloDAAACABNAGkMAAAHAD4AawwAAAcAQgBqDAAABwBKAGwMAAAHAFAAbQwAAAQAKgDqDAAABwA3AG4MAAAEAB8AbwwAAAMAEwAEAAkJUxUFPwAEAgloDAAACABNAGkMAAAHAD4AawwAAAcAQgBqDAAABwBKAGwMAAAHAFAAbQwAAAQAKgDqDAAABwA3AG4MAAAEAB8AbwwAAAMAEwAAAA==.',
Bo='Boose:BAAALgAECgYJBgAAAA==.Bootybreaker:BAAALgADCgcJBwAAAA==.',
Br='Brat:BAAALgAECgEJBAAAAA==.Brewingmist:BAAALgAECgUJBQABLgAFFAMJBQALAEUTAA==.Bréwmaster:BAAALgAECgcJCAABLgAECgkJIgAIAEoXAA==.',
Bu='Bubbelz:BAAALgAECgMJAwAAAA==.Bubbleez:BAAALgADCgUJBQAAAA==.Bubblôseven:BAAALgAECgEJAQAAAA==.Bucklord:BAABLgAECn8iAAMIAAgJjRkAFwAuAghoDAAABQBMAGkMAAAFAFEAawwAAAYAUQBqDAAABQBMAGwMAAAGAFUAbQwAAAEABADqDAAABQBSAG4MAAABAC4ACAAICY0ZABcALgIIaAwAAAUATABpDAAABQBRAGsMAAAGAFEAagwAAAUATABsDAAABgBVAG0MAAABAAQA6gwAAAQAUgBuDAAAAQAuAAMAAQkAGTFdAD0AAeoMAAABAEAAAAA=.Budin:BAAALgAECggJEgAAAA==.Bullmann:BAAALgADCgQJBAAAAA==.',
Ca='Cannibal:BAABLgAECn8nAAIMAAkJ5xqlEACsAgloDAAABgBFAGkMAAAFAEEAawwAAAYAVQBqDAAABQBDAGwMAAAFAFYAbQwAAAIARwDqDAAABgBTAG4MAAADACsAbwwAAAEALwAMAAkJ5xqlEACsAgloDAAABgBFAGkMAAAFAEEAawwAAAYAVQBqDAAABQBDAGwMAAAFAFYAbQwAAAIARwDqDAAABgBTAG4MAAADACsAbwwAAAEALwAAAA==.Caplock:BAABLgAECn8VAAINAAYJoRFohABRAQZoDAAABAA/AGkMAAAEAB0AawwAAAQALABqDAAAAwAnAGwMAAADACgA6gwAAAMALgANAAYJoRFohABRAQZoDAAABAA/AGkMAAAEAB0AawwAAAQALABqDAAAAwAnAGwMAAADACgA6gwAAAMALgAAAA==.Capri:BAAALgAECgUJDQAAAA==.',
Ce='Cellun:BAAALgAECgUJEgAAAA==.Centipede:BAAALgAECgYJCQABLgAECgYJFwAOAIAXAA==.Ceredis:BAAALgAECgUJCwAAAA==.',
Ch='Choomoo:BAAALgADCgcJCwAAAA==.',
Cl='Cleankarma:BAAALgADCgEJAwAAAA==.',
Co='Comet:BAAALgAECgEJAQAAAA==.Cool:BAAALgAFFAMJBAAAAA==.Corwiggs:BAAALgAECgYJCwAAAA==.',
Cr='Crikey:BAAALgAECgYJDAAAAA==.Crimínal:BAAALgADCgcJCwAAAA==.Cripsee:BAAALgADCgMJAwAAAA==.',
Cu='Curbie:BAAALgAECgIJAwAAAA==.',
Cy='Cyndrixx:BAAALgAECgIJAwAAAA==.',
['Cô']='Cônvict:BAAALgADCgYJBgAAAA==.',
De='Deacknight:BAABLgAECn8cAAMLAAgJwRuPLgB+AghoDAAAAwBLAGkMAAADAFgAawwAAAMAXwBqDAAABABPAGwMAAAFAGEAbQwAAAQAJQDqDAAABQBRAG4MAAABABUACwAICcEbjy4AfgIIaAwAAAMASwBpDAAAAgBYAGsMAAADAF8AagwAAAQATwBsDAAABQBhAG0MAAAEACUA6gwAAAUAUQBuDAAAAQAVAA8AAQmKDYEXADIAAWkMAAABACIAAS4AAwoGCQcAAgAAAAA=.Deacmonk:BAAALgADCgYJBgABLgADCgYJBwACAAAAAA==.Definitely:BAACLgAFFH8OAAIEAAMJRB28VwATAQNoDAAABwBfAGkMAAAFAFEA6gwAAAIALwAEAAMJRB28VwATAQNoDAAABwBfAGkMAAAFAFEA6gwAAAIALwAuAAQKfzgAAwQACAlcJGgVAL4CAAQACAlcJGgVAL4CABAAAQkPICobAD8AAAAA.Deki:BAEALgAECgYJBgAAAA==.Dementiaous:BAAALgAECgIJAwAAAA==.Desariana:BAABLgAECn8lAAIFAAkJcxCkTQDAAQloDAAABAA3AGkMAAAGADEAawwAAAYAPgBqDAAABQBCAGwMAAAFADQAbQwAAAEAEgDqDAAABgAqAG4MAAADACUAbwwAAAEAEwAFAAkJcxCkTQDAAQloDAAABAA3AGkMAAAGADEAawwAAAYAPgBqDAAABQBCAGwMAAAFADQAbQwAAAEAEgDqDAAABgAqAG4MAAADACUAbwwAAAEAEwAAAA==.',
Di='Diggitie:BAAALgAECgEJAQAAAA==.Ditto:BAAALgAFFAQJBAABLgAFFAUJIgARAN4aAA==.',
Do='Domtop:BAAALgAFFAMJBAABLgAFFAYJDwAHALISAA==.Dormas:BAABLgAECn8XAAISAAYJhxG+IwDuAAZoDAAABQApAGkMAAAFACwAawwAAAUAOABqDAAAAwAcAGwMAAADABsA6gwAAAIANgASAAYJhxG+IwDuAAZoDAAABQApAGkMAAAFACwAawwAAAUAOABqDAAAAwAcAGwMAAADABsA6gwAAAIANgAAAA==.Doug:BAAALgADCgEJAQAAAA==.Doxy:BAAALgAECgQJBQAAAA==.',
Dr='Drakeon:BAAALgAECgcJEAABLgAECgkJcAAJAHggAA==.',
Ee='Eeryxx:BAAALgAECgEJAQAAAA==.',
El='Eldh:BAABLgAECn8bAAMTAAkJbg4SIwBzAQloDAAABQAaAGkMAAAEACYAawwAAAQAJgBqDAAAAwAkAGwMAAADACoAbQwAAAEABwDqDAAABAAXAG4MAAACAFYAbwwAAAEAIAATAAkJgQsSIwBzAQloDAAABQAaAGkMAAAEACYAawwAAAQAJgBqDAAAAwAkAGwMAAADACoAbQwAAAEABwDqDAAABAAXAG4MAAABABoAbwwAAAEAIAAKAAEJoiEeYgBjAAFuDAAAAQBWAAAA.Eleison:BAAALgADCgMJAwAAAA==.Elendrial:BAAALgAECgIJAgAAAA==.Elendril:BAAALgADCgcJFQAAAA==.Elisoly:BAACLgAFFH8FAAIGAAIJDQyjMgB1AAJoDAAAAwA2AOoMAAACAAcABgACCQ0MozIAdQACaAwAAAMANgDqDAAAAgAHAC4ABAp/HwACBgAGCYIe/RsA/QEABgAGCYIe/RsA/QEAAAA=.',
Em='Emrald:BAAALgAECgYJEwAAAA==.',
En='Endlessly:BAACLgAFFH8PAAIUAAQJ3hSrBABIAQRoDAAABQBOAGkMAAAEADUAawwAAAIAJwDqDAAABAAqABQABAneFKsEAEgBBGgMAAAFAE4AaQwAAAQANQBrDAAAAgAnAOoMAAAEACoALgAECn8iAAIUAAgJnyLpAwDrAgAUAAgJnyLpAwDrAgAAAA==.Enerchi:BAAALgADCgMJAwAAAA==.',
Er='Erivoker:BAAALgAECgYJDAABLgAECgYJEgACAAAAAA==.Errimage:BAAALgAECgYJEgAAAA==.Errishoot:BAAALgAECgUJCQABLgAECgYJEgACAAAAAA==.Ervinia:BAAALgADCgYJCgABLgAECgYJEwACAAAAAA==.',
Ev='Evelinar:BAAALgAECgMJAwAAAA==.Evoslex:BAABLgAECn85AAMVAAkJxCPRAwAdAwloDAAABwBeAGkMAAAHAF8AawwAAAcAXABqDAAABwBhAGwMAAAHAF8AbQwAAAUAYQDqDAAACABVAG4MAAAFAFQAbwwAAAQAVwAVAAkJxCPRAwAdAwloDAAABQBeAGkMAAAGAF8AawwAAAYAXABqDAAABgBhAGwMAAAGAF8AbQwAAAUAYQDqDAAABgBVAG4MAAAFAFQAbwwAAAQAVwAWAAYJzx1vEwCsAQZoDAAAAgBMAGkMAAABAFQAawwAAAEAVABqDAAAAQBCAGwMAAABADgA6gwAAAIATwAAAA==.',
Ex='Exo:BAECLgAFFH8gAAIXAAYJ2RwGBwCxAQZoDAAACABbAGkMAAAGAGAAawwAAAYAUgBqDAAAAwAcAGwMAAABABYA6gwAAAgASwAXAAYJ2RwGBwCxAQZoDAAACABbAGkMAAAGAGAAawwAAAYAUgBqDAAAAwAcAGwMAAABABYA6gwAAAgASwAuAAQKfysAAhcACQkcIhoDAPgCABcACQkcIhoDAPgCAAAA.',
Fa='Facerolleh:BAACLgAFFH8wAAMYAAgJ+CGGAACyAghoDAAABwBfAGkMAAANAGMAawwAAAsAWwBqDAAABQAuAGwMAAADAEEAbQwAAAEAWQDqDAAABwBfAG4MAAABAEcAGAAICbMhhgAAsgIIaAwAAAMAXQBpDAAACQBjAGsMAAAKAFsAagwAAAUALgBsDAAAAwBBAG0MAAABAFkA6gwAAAIAWwBuDAAAAQBHAAkABAlmIYwGAIYBBGgMAAAEAF8AaQwAAAQATgBrDAAAAQBIAOoMAAAFAF8ALgAECn9GAAQJAAkJnSXOBABcAwAJAAgJ9iXOBABcAwAYAAgJfyJyBACsAgAZAAIJjR1zPQBUAAAAAA==.Fatedx:BAAALgADCgMJBgAAAA==.',
Fe='Feelgoodinc:BAAALgADCgkJFAAAAA==.',
Fi='Fidah:BAAALgADCgEJAQAAAA==.Firemagemain:BAAALgADCgUJBQABLgAFFAMJBQAJACoUAA==.',
Fl='Flanann:BAAALgAECgEJAQABLgAECgMJCQACAAAAAA==.Flop:BAAALgAECgUJCQABLgAFFAQJCQAEAC8bAA==.Flora:BAAALgAECgEJAgAAAA==.',
Fr='Frostmere:BAAALgADCggJGQAAAA==.',
Fu='Fuknazum:BAAALgAECgEJAQAAAA==.Furcht:BAABLgAECn8cAAILAAYJGhOqnAAKAQZoDAAABQA1AGkMAAAFACwAawwAAAUANwBqDAAAAwAZAGwMAAADADQA6gwAAAcAJwALAAYJGhOqnAAKAQZoDAAABQA1AGkMAAAFACwAawwAAAUANwBqDAAAAwAZAGwMAAADADQA6gwAAAcAJwAAAA==.',
Ga='Galadar:BAAALgADCgUJBQAAAA==.',
Gi='Giteff:BAABLgAFFH8PAAIaAAcJbiWdAgCcAgdoDAAAAwBhAGkMAAADAGMAawwAAAIAYQBqDAAAAgBYAGwMAAABAFoAbQwAAAIAWwDqDAAAAgBiABoABwluJZ0CAJwCB2gMAAADAGEAaQwAAAMAYwBrDAAAAgBhAGoMAAACAFgAbAwAAAEAWgBtDAAAAgBbAOoMAAACAGIAAAA=.Gitèff:BAABLgAFFH8JAAIaAAUJ9hmnJwBIAQVoDAAAAwBdAGkMAAABADkAawwAAAEALABqDAAAAQBCAOoMAAADAEcAGgAFCfYZpycASAEFaAwAAAMAXQBpDAAAAQA5AGsMAAABACwAagwAAAEAQgDqDAAAAwBHAAEuAAUUCAkPABoAbiUA.Giveroflife:BAAALgAECgUJBQAAAA==.',
Go='Gourdin:BAAALgAECgQJBQABLgAECgYJCAACAAAAAA==.',
Gr='Gramnpa:BAAALgADCgUJBQAAAA==.Grandpriest:BAAALgADCgEJAQABLgAECgkJNQAFAJwdAA==.Gravepriest:BAAALgAECgEJAQAAAA==.Grimtysha:BAAALgAECgYJEAAAAA==.Grimveil:BAAALgAECgYJDQAAAA==.Gromit:BAAALgAECgQJCQAAAA==.Gröuch:BAABLgAFFH8IAAITAAQJZQq7LwDJAARoDAAAAgAeAGkMAAACACoAawwAAAIADQDqDAAAAgAUABMABAllCrsvAMkABGgMAAACAB4AaQwAAAIAKgBrDAAAAgANAOoMAAACABQAAAA=.',
Ha='Harafar:BAAALgAFFAMJAwAAAA==.',
He='Hellbourne:BAABLgAECn8hAAIaAAgJrRfCNADTAQhoDAAABgBBAGkMAAAFAEAAawwAAAUANQBqDAAABAAxAGwMAAAEAEwAbQwAAAIAHgDqDAAABQBJAG4MAAACADsAGgAICa0XwjQA0wEIaAwAAAYAQQBpDAAABQBAAGsMAAAFADUAagwAAAQAMQBsDAAABABMAG0MAAACAB4A6gwAAAUASQBuDAAAAgA7AAAA.',
Hi='Himmel:BAAALgADCgcJCQAAAA==.',
Ho='Hopnhorsé:BAAALgAECgQJBAAAAA==.Hotchoq:BAABLgAFFH8HAAIEAAIJ3QsggwCbAAJoDAAAAwAgAOoMAAAEABwABAACCd0LIIMAmwACaAwAAAMAIADqDAAABAAcAAAA.',
Hu='Huntchoq:BAABLgAFFH8NAAQbAAUJKw8jEAAwAQVoDAAAAwA1AGkMAAADACIAawwAAAIAFQBqDAAAAQAGAOoMAAAEACwAGwAFCU4NIxAAMAEFaAwAAAIANQBpDAAAAgAYAGsMAAACABUAagwAAAEABgDqDAAAAwAkABwAAglVCLplAIUAAmgMAAABAAcAaQwAAAEAIgAdAAEJlBH0KABGAAHqDAAAAQAsAAAA.Huxley:BAAALgADCgMJAwAAAA==.',
Ik='Ikan:BAAALgAECgYJDQAAAA==.',
In='Infest:BAAALgAECgQJCAAAAA==.Inzolethys:BAAALgADCgcJBwAAAA==.',
It='Itchy:BAAALgADCgEJAgAAAA==.Itskiohte:BAABLgAECn8pAAIeAAkJVw70CwC9AQloDAAABQAwAGkMAAAFAD8AawwAAAUALwBqDAAABQAiAGwMAAAFABoAbQwAAAIADADqDAAABgAiAG4MAAAGACEAbwwAAAIAHAAeAAkJVw70CwC9AQloDAAABQAwAGkMAAAFAD8AawwAAAUALwBqDAAABQAiAGwMAAAFABoAbQwAAAIADADqDAAABgAiAG4MAAAGACEAbwwAAAIAHAAAAA==.',
Ja='Jaggernut:BAAALgADCgUJBQAAAA==.',
Ji='Jimmbo:BAAALgAECgQJBAAAAA==.',
Jo='Johnny:BAAALgAECgIJAgABLgAECgkJOQAVAMQjAA==.',
Ju='Judeau:BAAALgADCgEJAQAAAA==.',
Ka='Kaelthuzzad:BAAALgADCgEJAQAAAA==.Kaitza:BAAALgAECgYJCwAAAA==.Kalzaketh:BAABLgAECn8/AAMVAAgJBww8MABOAQhoDAAADAAhAGkMAAAKACIAawwAAAoAJwBqDAAABwAaAGwMAAAHACAAbQwAAAIAHQDqDAAACQATAG4MAAAGABoAFQAICQcMPDAATgEIaAwAAAgAIQBpDAAACAAiAGsMAAAIACcAagwAAAcAGgBsDAAABwAgAG0MAAACAB0A6gwAAAkAEwBuDAAABgAaABYAAwnlBIgzAHkAA2gMAAAEAAUAaQwAAAIADgBrDAAAAgASAAAA.Kashari:BAAALgAECgIJBQABLgAECgkJeQAIABIcAA==.Katali:BAAALgAECgcJEQAAAA==.Kazuggar:BAACLgAFFH8YAAIOAAUJpCJNCADyAQVoDAAABwBbAGkMAAAHAEwAawwAAAQAVQBqDAAAAQBhAOoMAAAFAFwADgAFCaQiTQgA8gEFaAwAAAcAWwBpDAAABwBMAGsMAAAEAFUAagwAAAEAYQDqDAAABQBcAC4ABAp/MgADDgAICYIlbgIAXAMADgAICYIlbgIAXAMAHwADCV4aUl0AzgAAAAA=.Kazzn:BAAALgAECgYJCAAAAA==.',
Ke='Kedar:BAAALgAECgYJEQAAAA==.Keg:BAAALgAECgIJAgAAAA==.Kelabar:BAAALgADCgQJBAAAAA==.',
Ki='Kick:BAAALgADCgQJBAABLgAFFAYJFgAEAFwVAA==.Kiffs:BAAALgAECgcJCgAAAA==.Kill:BAAALgAECgUJDAABLgAECggJBAACAAAAAA==.Killerman:BAABLgAFFH8PAAMPAAcJ4h7qAgCLAQdoDAAAAgBPAGkMAAACAGEAawwAAAMAYABqDAAAAgBPAG0MAAACAD8A6gwAAAIARwBuDAAAAgBBAA8ABQm0IeoCAIsBBWgMAAACAE8AaQwAAAIAYQBrDAAAAgBgAGoMAAABAE8A6gwAAAIARwALAAQJfhyUWgAZAQRrDAAAAQBZAGoMAAABAEwAbQwAAAIAPwBuDAAAAgBBAAAA.Kirâ:BAAALgAECggJEAABLgAECgcJEwACAAAAAA==.',
Kr='Kregnar:BAABLgAECn8mAAIYAAgJlRuBCgAZAghoDAAACABNAGkMAAAGAD0AawwAAAYASQBqDAAABAA5AGwMAAAEAFIAbQwAAAIANQDqDAAABgBJAG4MAAACAEgAGAAICZUbgQoAGQIIaAwAAAgATQBpDAAABgA9AGsMAAAGAEkAagwAAAQAOQBsDAAABABSAG0MAAACADUA6gwAAAYASQBuDAAAAgBIAAAA.Kresh:BAAALgAECgcJCwAAAA==.',
Ku='Kucabara:BAAALgAECgEJAgAAAA==.Kuraiwiggs:BAAALgADCgYJDAAAAA==.',
Kw='Kwichang:BAABLgAECn8ZAAIEAAcJuw/CfgBdAQdoDAAABQAuAGkMAAAFACcAawwAAAUAKgBqDAAAAgA/AGwMAAADAB4AbQwAAAEAFwDqDAAABAA7AAQABwm7D8J+AF0BB2gMAAAFAC4AaQwAAAUAJwBrDAAABQAqAGoMAAACAD8AbAwAAAMAHgBtDAAAAQAXAOoMAAAEADsAAAA=.',
['Ké']='Kélpo:BAAALgADCgMJBAAAAA==.',
La='Lasagne:BAAALgADCgMJAwAAAA==.',
Li='Lickynose:BAABLgAECn8pAAIEAAkJYyGWDgDvAgloDAAABgBbAGkMAAAFAFwAawwAAAQATwBqDAAABQBaAGwMAAAFAFkAbQwAAAQAPwDqDAAABwBdAG4MAAAEAFgAbwwAAAEAVQAEAAkJYyGWDgDvAgloDAAABgBbAGkMAAAFAFwAawwAAAQATwBqDAAABQBaAGwMAAAFAFkAbQwAAAQAPwDqDAAABwBdAG4MAAAEAFgAbwwAAAEAVQAAAA==.Lips:BAAALgAECgEJAQAAAA==.',
Ls='Ls:BAABLgAECn8iAAQgAAkJaiO3BgCfAgloDAAABQBhAGkMAAAEAF8AawwAAAMAVQBqDAAABABeAGwMAAAEAF8AbQwAAAMARgDqDAAABgBaAG4MAAAEAFsAbwwAAAEAYgAgAAgJ3R+3BgCfAghoDAAAAQBeAGkMAAABAF8AagwAAAEAXgBsDAAAAQBfAG0MAAABABoA6gwAAAEAWQBuDAAAAQBHAG8MAAABAGIAGgAICZwhvTEAMwIIaAwAAAMAYQBpDAAAAgBdAGsMAAACAFUAagwAAAIAXQBsDAAAAgBJAG0MAAABAEYA6gwAAAQAWgBuDAAAAwBbACEABwliFaQLAHUBB2gMAAABAF4AaQwAAAEAIQBrDAAAAQBIAGoMAAABAB0AbAwAAAEAKQBtDAAAAQAdAOoMAAABADgAAAA=.',
Ma='Madarabia:BAAALgAECgYJDQAAAA==.Magnius:BAAALgAECgMJAwAAAA==.Mamut:BAAALgAECgEJAQAAAA==.Mantisar:BAACLgAFFH8IAAIFAAMJ5RLKSADxAANoDAAABABQAGkMAAACACcA6gwAAAIAGAAFAAMJ5RLKSADxAANoDAAABABQAGkMAAACACcA6gwAAAIAGAAuAAQKfx4AAgUABwnmHk8vACECAAUABwnmHk8vACECAAAA.Maxsm:BAABLgAECn8XAAIfAAgJrhmSIQACAghoDAAABABWAGkMAAAEAFcAawwAAAMAWABqDAAAAwA0AGwMAAADAEEAbQwAAAEAHgDqDAAABABgAG4MAAABAAQAHwAICa4ZkiEAAgIIaAwAAAQAVgBpDAAABABXAGsMAAADAFgAagwAAAMANABsDAAAAwBBAG0MAAABAB4A6gwAAAQAYABuDAAAAQAEAAAA.',
Me='Melanippe:BAABLgAECn8XAAIMAAYJDxtuPQCuAQZoDAAABAA9AGkMAAAEAEcAawwAAAQAOwBqDAAAAwBEAGwMAAADAFAA6gwAAAUASQAMAAYJDxtuPQCuAQZoDAAABAA9AGkMAAAEAEcAawwAAAQAOwBqDAAAAwBEAGwMAAADAFAA6gwAAAUASQAAAA==.Meleefox:BAAALgADCgUJBQAAAA==.Melethron:BAABLgAECn8+AAIFAAkJgRxOHAB9AgloDAAACQBUAGkMAAAIAE0AawwAAAgAWQBqDAAACABcAGwMAAAIAFIAbQwAAAQAQADqDAAACABEAG4MAAAFAE4AbwwAAAQAJQAFAAkJgRxOHAB9AgloDAAACQBUAGkMAAAIAE0AawwAAAgAWQBqDAAACABcAGwMAAAIAFIAbQwAAAQAQADqDAAACABEAG4MAAAFAE4AbwwAAAQAJQAAAA==.Melioknky:BAAALgAECgYJBgAAAA==.',
Mi='Mid:BAAALgADCgYJBgAAAA==.Mightymage:BAABLgAECn8hAAIEAAgJ4Q1WcAB9AQhoDAAABQAnAGkMAAAFACAAawwAAAUAMABqDAAAAwAxAGwMAAADAB8AbQwAAAEAHQDqDAAABgA1AG4MAAAFAA0ABAAICeENVnAAfQEIaAwAAAUAJwBpDAAABQAgAGsMAAAFADAAagwAAAMAMQBsDAAAAwAfAG0MAAABAB0A6gwAAAYANQBuDAAABQANAAAA.Millionbaby:BAAALgAECgEJAQAAAA==.Milliondruid:BAAALgAECgMJBAAAAA==.Millionsm:BAAALgADCgQJBQAAAA==.Mirrorimage:BAAALgAECgMJBQABLgAFFAYJEgAIAAgVAA==.Mirrorx:BAACLgAFFH8SAAIIAAYJCBWsCACVAQZoDAAABQBBAGkMAAADAD0AawwAAAIAGgBqDAAAAQAjAGwMAAABADMA6gwAAAYAQQAIAAYJCBWsCACVAQZoDAAABQBBAGkMAAADAD0AawwAAAIAGgBqDAAAAQAjAGwMAAABADMA6gwAAAYAQQAuAAQKfzIAAggACQlzIJUGAMsCAAgACQlzIJUGAMsCAAAA.Miy:BAAALgAECgEJAQAAAA==.',
Mo='Mongon:BAAALgAECgYJBgAAAA==.Moogle:BAAALgAECgIJBAAAAA==.Moomie:BAABLgAECn8iAAIMAAgJAxZkMQC3AQhoDAAABQBJAGkMAAAGAEYAawwAAAYARABqDAAABQAuAGwMAAAEAD0AbQwAAAIAGADqDAAABQA0AG4MAAABADYADAAICQMWZDEAtwEIaAwAAAUASQBpDAAABgBGAGsMAAAGAEQAagwAAAUALgBsDAAABAA9AG0MAAACABgA6gwAAAUANABuDAAAAQA2AAAA.Moosfel:BAABLgAECn8jAAIUAAcJGhq2CwDKAQdoDAAABwBSAGkMAAAHAEMAawwAAAcASgBqDAAABQA9AGwMAAADAC8A6gwAAAUAQQBuDAAAAQA/ABQABwkaGrYLAMoBB2gMAAAHAFIAaQwAAAcAQwBrDAAABwBKAGoMAAAFAD0AbAwAAAMALwDqDAAABQBBAG4MAAABAD8AAAA=.',
Mt='Mtzz:BAAALgAECgUJBQABLgAECgYJCAACAAAAAA==.',
Mu='Mudcake:BAAALgAECgEJAQAAAA==.',
My='Mygravebroke:BAAALgADCggJCQAAAA==.Mystdragon:BAACLgAFFH8QAAMiAAUJxRuUDACZAQVoDAAABQBjAGkMAAAEAEcAawwAAAMANgBqDAAAAQAlAOoMAAADAFwAIgAFCcUblAwAmQEFaAwAAAUAYwBpDAAABABHAGsMAAADADYAagwAAAEAJQDqDAAAAgBcABUAAQmdCL1QAD8AAeoMAAABABYALgAECn8wAAIiAAkJuSG9AgAWAwAiAAkJuSG9AgAWAwABLgAFFAgJJAAHAK8aAA==.Mystweaverr:BAACLgAFFH8kAAMHAAgJrxp+AwCEAghoDAAABQBHAGkMAAAHAFEAawwAAAcAWwBqDAAABgA5AGwMAAACAEUAbQwAAAEASwDqDAAABwBiAG4MAAABAAAABwAICa8afgMAhAIIaAwAAAQARwBpDAAABwBRAGsMAAAHAFsAagwAAAYAOQBsDAAAAgBFAG0MAAABAEsA6gwAAAcAYgBuDAAAAQAAAAoAAQn1BKAzADsAAWgMAAABAAwALgAECn8vAAMHAAkJ9x+ACQC5AgAHAAkJ9x+ACQC5AgAKAAIJIyIIRwC5AAAAAA==.',
['Mö']='Mörae:BAAALgADCgEJAQABLgAECgYJFwAMAA8bAA==.',
Na='Naddar:BAACLgAFFH8PAAIGAAUJRha9EgBhAQVoDAAABAA5AGkMAAAEACgAawwAAAMAQQBqDAAAAQA8AOoMAAADAD0ABgAFCUYWvRIAYQEFaAwAAAQAOQBpDAAABAAoAGsMAAADAEEAagwAAAEAPADqDAAAAwA9AC4ABAp/PAACBgAJCd4dzgYA/gIABgAJCd4dzgYA/gIAAAA=.Namadgi:BAABLgAECn8hAAIMAAkJVRrpEQCeAgloDAAABABGAGkMAAAEAFcAawwAAAMARQBqDAAABAA1AGwMAAAEAD0AbQwAAAQAJwDqDAAABgBeAG4MAAADAEYAbwwAAAEAOwAMAAkJVRrpEQCeAgloDAAABABGAGkMAAAEAFcAawwAAAMARQBqDAAABAA1AGwMAAAEAD0AbQwAAAQAJwDqDAAABgBeAG4MAAADAEYAbwwAAAEAOwAAAA==.Nathria:BAAALgAECgIJAwAAAA==.',
Ne='Nesra:BAAALgAECgIJAgAAAA==.Netalis:BAABLgAECn8lAAIMAAgJwxQgKwDcAQhoDAAABgBAAGkMAAAFAEMAawwAAAQALQBqDAAABQA0AGwMAAAFADoAbQwAAAMAGwDqDAAABwA1AG4MAAACADcADAAICcMUICsA3AEIaAwAAAYAQABpDAAABQBDAGsMAAAEAC0AagwAAAUANABsDAAABQA6AG0MAAADABsA6gwAAAcANQBuDAAAAgA3AAAA.',
Ni='Nikonii:BAAALgADCgQJBAAAAA==.',
Nu='Nurckers:BAAALgAECgcJCAAAAA==.',
Oa='Oakinelf:BAAALgADCgcJAQAAAA==.',
Om='Omnishifts:BAAALgAECgEJAgAAAA==.',
Or='Oramo:BAABLgAECn8fAAMXAAgJfCMmBQDwAghoDAAABwBeAGkMAAAFAFwAawwAAAQAYgBqDAAAAwBYAGwMAAADAGEAbQwAAAIAUQDqDAAABQBfAG4MAAACAEsAFwAICcUiJgUA8AIIaAwAAAQAUQBpDAAAAgBcAGsMAAABAGIAagwAAAEAQABsDAAAAQBhAG0MAAACAFEA6gwAAAMAXwBuDAAAAgBLAAsABgmAIphbAJABBmgMAAADAF4AaQwAAAMAWwBrDAAAAwBdAGoMAAACAFgAbAwAAAIAUgDqDAAAAgBPAAAA.',
Ov='Ovaries:BAAALgADCgUJBQABLgAECgQJBQACAAAAAA==.',
Pa='Paktam:BAABLgAECn8XAAIOAAcJzh3CFwBfAgdoDAAAAwBWAGkMAAAEAE0AawwAAAQAWwBqDAAABABcAGwMAAABACQAbQwAAAEAPADqDAAABgBaAA4ABwnOHcIXAF8CB2gMAAADAFYAaQwAAAQATQBrDAAABABbAGoMAAAEAFwAbAwAAAEAJABtDAAAAQA8AOoMAAAGAFoAAAA=.Paméla:BAAALgAECgcJCAABLgAECgkJcAAJAHggAA==.Paradisya:BAAALgADCggJDgAAAA==.',
Pe='Perceptor:BAAALgAECgEJAQABLgAECgkJKQASAJMhAA==.Pets:BAAALgAECgEJAQABLgAECgEJBAACAAAAAA==.',
Pl='Placebo:BAAALgAECgUJBQABLgAFFAQJDwAUAN4UAA==.',
Pr='Prothero:BAACLgAFFH8QAAMEAAUJJiC9KwB0AQVoDAAABABUAGkMAAAEAGIAawwAAAIAPQBqDAAAAQBbAOoMAAAFAFQABAAFCSYgvSsAdAEFaAwAAAQAVABpDAAABABiAGsMAAACAD0AagwAAAEAWwDqDAAABABUABAAAQllGS0DAFIAAeoMAAABAEEALgAECn8WAAMEAAkJxiBkEwDLAgAEAAkJxiBkEwDLAgAQAAgJKxgDAwBQAgAAAA==.Proyo:BAAALgADCgUJBQAAAA==.',
['På']='Påthor:BAACLgAFFH8HAAIRAAIJkw8/LgCOAAJoDAAABQAnAOoMAAACACcAEQACCZMPPy4AjgACaAwAAAUAJwDqDAAAAgAnAC4ABAp/HwADEQAHCTgcbBwAtwEAEQAHCTgcbBwAtwEAEgADCRIS1D8AXgAAAAA=.',
Ra='Raikonnen:BAAALgAECgEJAQAAAA==.Rapidstrikes:BAAALgAECgEJAQAAAA==.Rawtoor:BAACLgAFFH8cAAIaAAYJbRlUGgCHAQZoDAAABgBTAGkMAAAGAF8AawwAAAQALQBqDAAABABBAGwMAAABABUA6gwAAAcATgAaAAYJbRlUGgCHAQZoDAAABgBTAGkMAAAGAF8AawwAAAQALQBqDAAABABBAGwMAAABABUA6gwAAAcATgAuAAQKfyEAAhoACAk4IdInAGUCABoACAk4IdInAGUCAAAA.',
Re='Rebelsister:BAAALgADCgcJEAAAAA==.Refridgerate:BAAALgADCgUJBwAAAA==.',
Ri='Riddagain:BAABLgAECn8bAAMhAAYJeA/1FAAHAQZoDAAABQAZAGkMAAAEADMAawwAAAQAJgBqDAAAAwAMAGwMAAADACwA6gwAAAgAJQAhAAYJTw/1FAAHAQZoDAAABAAZAGkMAAAEADMAawwAAAQAJgBqDAAAAwAMAGwMAAADACwA6gwAAAUAIwAaAAIJwAsO9AArAAJoDAAAAQAWAOoMAAADACUAAAA=.Ridgemonk:BAABLgAECn8zAAMTAAkJiiAfBADvAgloDAAABgBgAGkMAAAHAFwAawwAAAcAUgBqDAAABQBYAGwMAAAGADsAbQwAAAUAUwDqDAAABwBSAG4MAAAFAFcAbwwAAAMAUQATAAkJiiAfBADvAgloDAAABQBgAGkMAAAGAFwAawwAAAYAUgBqDAAABQBYAGwMAAAGADsAbQwAAAUAUwDqDAAABgBSAG4MAAAFAFcAbwwAAAMAUQAHAAQJQAGYYABMAARoDAAAAQAEAGkMAAABAAIAawwAAAEAAADqDAAAAQAEAAAA.Riggsdk:BAAALgADCgcJBwABLgAFFAgJGwAcAKAiAA==.Riggse:BAAALgAFFAEJAQABLgAFFAgJGwAcAKAiAA==.Riggshunt:BAACLgAFFH8bAAQcAAgJoCLTAACrAQhoDAAABgBjAGkMAAAFAGEAawwAAAQAVwBqDAAAAwA2AGwMAAABAFYAbQwAAAEAUgDqDAAABgBjAG4MAAABAEMAGwAGCSwkLgAA+wEGaAwAAAQAYwBpDAAABABhAGsMAAADAFIAagwAAAIANgBsDAAAAQBWAOoMAAAEAGEAHAAGCfEg0wAAqwEGaAwAAAIAYgBpDAAAAQBGAGsMAAABAFcAbQwAAAEAUgDqDAAAAgBjAG4MAAABAEMAHQABCQAAvygASgABagwAAAEADwAuAAQKfx4ABBwACAmrJr0IAAcDABwABwmYJr0IAAcDABsACAmTJIQDAPICAB0AAQmCHGd9AE8AAAAA.Riggspal:BAAALgAFFAIJAgABLgAFFAgJGwAcAKAiAA==.Riggzs:BAAALgAFFAIJAgABLgAFFAgJGwAcAKAiAA==.',
Ro='Roadkill:BAABLgAECn8gAAIXAAgJnSM4BAALAwhoDAAABQBhAGkMAAAFAF8AawwAAAUAXQBqDAAABABcAGwMAAAEAFAAbQwAAAIAWADqDAAABQBiAG4MAAACAFUAFwAICZ0jOAQACwMIaAwAAAUAYQBpDAAABQBfAGsMAAAFAF0AagwAAAQAXABsDAAABABQAG0MAAACAFgA6gwAAAUAYgBuDAAAAgBVAAAA.Rolltoor:BAAALgAFFAIJAwAAAA==.Roonate:BAAALgADCgUJBQAAAA==.Rosemary:BAAALgAECgQJBAAAAA==.',
Ry='Ryujin:BAAALgAECgQJCQAAAA==.',
Sa='Saiko:BAABLgAFFH8RAAIgAAUJ1hgACABKAQVoDAAABABKAGkMAAAEAEUAawwAAAQAOABqDAAAAQASAOoMAAAEADYAIAAFCdYYAAgASgEFaAwAAAQASgBpDAAABABFAGsMAAAEADgAagwAAAEAEgDqDAAABAA2AAAA.Sansa:BAACLgAFFH8TAAIbAAcJZhgFAgDaAQdoDAAABABaAGkMAAAEAFUAawwAAAIAPABqDAAAAgBcAGwMAAABAAAAbQwAAAEAKgDqDAAABQBeABsABwlmGAUCANoBB2gMAAAEAFoAaQwAAAQAVQBrDAAAAgA8AGoMAAACAFwAbAwAAAEAAABtDAAAAQAqAOoMAAAFAF4ALgAECn8jAAIbAAkJZyNNAgAjAwAbAAkJZyNNAgAjAwAAAA==.Saso:BAACLgAFFH8QAAIEAAUJFhsHGwBfAQVoDAAABABAAGkMAAAEAEkAawwAAAMAOQBqDAAAAQBOAOoMAAAEAFEABAAFCRYbBxsAXwEFaAwAAAQAQABpDAAABABJAGsMAAADADkAagwAAAEATgDqDAAABABRAC4ABAp/MwAEBAAJCZQiFRAA4wIABAAJCZQiFRAA4wIAEAADCQMfSAwADQEAIwACCcQIsAsAdwAAAAA=.Sastroll:BAAALgAECgUJBQAAAA==.',
Sc='Scorn:BAAALgADCgcJCAAAAA==.Scroll:BAAALgAECggJEgAAAA==.',
Se='Seluvis:BAABLgAECn8UAAIEAAcJlAHa8gCUAAdoDAAABAAEAGkMAAAEAAUAawwAAAIAAwBqDAAAAgABAGwMAAAFAAQAbQwAAAEAAwDqDAAAAgACAAQABwmUAdryAJQAB2gMAAAEAAQAaQwAAAQABQBrDAAAAgADAGoMAAACAAEAbAwAAAUABABtDAAAAQADAOoMAAACAAIAAAA=.Sentai:BAAALgADCgcJBwAAAA==.Serapayne:BAAALgAECgcJAQAAAA==.',
Sh='Shadow:BAACLgAFFH8WAAIaAAUJ9hlyJABVAQVoDAAABABCAGkMAAAEAF8AawwAAAQAQgBqDAAABgBNAOoMAAAEACUAGgAFCfYZciQAVQEFaAwAAAQAQgBpDAAABABfAGsMAAAEAEIAagwAAAYATQDqDAAABAAlAC4ABAp/XAACGgAJCRAk4AkA5AIAGgAJCRAk4AkA5AIAAAA=.Shandrilah:BAAALgADCgQJBAAAAA==.Shapeshift:BAAALgADCgUJBQABLgAECgIJAgACAAAAAA==.Shialebuff:BAABLgAECn81AAQDAAkJfR+fFwAfAgloDAAABwBXAGkMAAAIAGMAawwAAAgAVQBqDAAABgBAAGwMAAAGAFUAbQwAAAMATwDqDAAACABaAG4MAAAFAFEAbwwAAAIANAADAAkJfR+fFwAfAgloDAAAAwBXAGkMAAAEAGMAawwAAAQAVQBqDAAABABAAGwMAAADAFUAbQwAAAMATwDqDAAAAwBaAG4MAAABAFEAbwwAAAIANAAIAAcJEh2qFwDmAQdoDAAABABTAGkMAAAEAFsAawwAAAQAVABqDAAAAgBCAGwMAAACAEIA6gwAAAUANABuDAAABABEAAEAAQmTBnpmAC4AAWwMAAABABAAAAA=.Shijin:BAAALgAECgQJBQAAAA==.Shortfuze:BAAALgAECgYJDQAAAA==.',
Si='Sindar:BAAALgADCgUJBQAAAA==.Sinfall:BAAALgAECggJDgAAAA==.Siphon:BAAALgAECgEJAgAAAA==.Siscomp:BAABLgAECn9wAAIJAAkJeCD4CwCGAgloDAAADgBWAGkMAAANAFwAawwAAA8ASgBqDAAADQBDAGwMAAANAEwAbQwAAAwAVQDqDAAADgBOAG4MAAALAFQAbwwAAAcAVQAJAAkJeCD4CwCGAgloDAAADgBWAGkMAAANAFwAawwAAA8ASgBqDAAADQBDAGwMAAANAEwAbQwAAAwAVQDqDAAADgBOAG4MAAALAFQAbwwAAAcAVQAAAA==.Sixth:BAABLgAECn8XAAIfAAcJ/BpsHwC7AQdoDAAAAgBIAGkMAAAEAEYAawwAAAUASABqDAAABAAkAGwMAAAEAEoAbQwAAAEAKgDqDAAAAwBSAB8ABwn8GmwfALsBB2gMAAACAEgAaQwAAAQARgBrDAAABQBIAGoMAAAEACQAbAwAAAQASgBtDAAAAQAqAOoMAAADAFIAAAA=.Sizzle:BAAALgADCgMJAwAAAA==.',
Sk='Skateboard:BAAALgADCgEJAQAAAA==.Sky:BAACLgAFFH8eAAIBAAcJdhkbBQB9AgdoDAAABgA/AGkMAAAFAFMAawwAAAYAXwBqDAAABQBeAGwMAAADADEAbQwAAAEAFgDqDAAABAAvAAEABwl2GRsFAH0CB2gMAAAGAD8AaQwAAAUAUwBrDAAABgBfAGoMAAAFAF4AbAwAAAMAMQBtDAAAAQAWAOoMAAAEAC8ALgAECn8UAAMBAAgJcROPHACwAQABAAcJWRKPHACwAQADAAUJ8g+ITAAGAQAAAA==.',
Sl='Sleck:BAAALgAECgYJDAAAAA==.',
Sn='Snappa:BAAALgADCgYJCwAAAA==.Sniped:BAAALgAFFAEJAQAAAA==.Snugglepuff:BAAALgAECgkJEwAAAA==.',
So='Soapfidas:BAAALgADCggJCgAAAA==.Sonarius:BAACLgAFFH8JAAIEAAQJLxu4NQBYAQRoDAAAAwBQAGkMAAACAEkAawwAAAEAPADqDAAAAwA/AAQABAkvG7g1AFgBBGgMAAADAFAAaQwAAAIASQBrDAAAAQA8AOoMAAADAD8ALgAECn8dAAQEAAgJ3R8pPACGAgAEAAgJ3R8pPACGAgAQAAIJAh2TCgCqAAAjAAEJshIPDwA8AAAAAA==.Sophie:BAAALgAECgEJAgAAAA==.',
Sp='Splitterman:BAABLgAFFH8GAAIPAAUJtxK7BwA1AQVoDAAAAQBCAGkMAAABAFIAawwAAAEAGABqDAAAAQA1AOoMAAACABEADwAFCbcSuwcANQEFaAwAAAEAQgBpDAAAAQBSAGsMAAABABgAagwAAAEANQDqDAAAAgARAAAA.',
Su='Su:BAABLgAECn8yAAIHAAcJ4yVlBwDiAgdoDAAACwBhAGkMAAAKAGMAawwAAAoAYQBqDAAACABiAGwMAAAFAGEA6gwAAAUAYQBuDAAAAQBaAAcABwnjJWUHAOICB2gMAAALAGEAaQwAAAoAYwBrDAAACgBhAGoMAAAIAGIAbAwAAAUAYQDqDAAABQBhAG4MAAABAFoAAAA=.Sudno:BAAALgAECgQJCAABLgAFFAYJFQANABYaAA==.Sundae:BAABLgAECn83AAQDAAkJlSFIBgDvAgloDAAACABfAGkMAAAIAFgAawwAAAgAXQBqDAAABwBTAGwMAAAGAFoAbQwAAAIATgDqDAAACABhAG4MAAAGAFsAbwwAAAIANgADAAgJHCNIBgDvAghoDAAABABfAGkMAAADAFgAawwAAAQAXQBqDAAABQBTAGwMAAAEAFoAbQwAAAIATgDqDAAABQBhAG4MAAAEAFsAAQAICYcbLAsAkQIIaAwAAAMAWgBpDAAABABLAGsMAAADAFMAagwAAAIASwBsDAAAAgBQAOoMAAADACQAbgwAAAIAQgBvDAAAAgA2AAgAAwncFnVHAMQAA2gMAAABADAAaQwAAAEASABrDAAAAQA2AAAA.Sunwukong:BAAALgAECgUJCQAAAA==.Supersinpe:BAAALgAECgIJAgAAAA==.',
Sv='Svendlefyre:BAAALgADCgcJDgABLgAECgkJLgAUAIMZAA==.Svholydrag:BAAALgADCgEJAQAAAA==.Svmishima:BAAALgAECgEJAQAAAA==.',
Sw='Swirly:BAAALgAECgEJAQAAAA==.',
Sy='Sylvie:BAABLgAECn8eAAIcAAkJmhGfLwD0AQloDAAAAwAyAGkMAAADADgAawwAAAMAMABqDAAAAwAwAGwMAAADACIAbQwAAAMAJADqDAAABQAxAG4MAAAEADcAbwwAAAMAHQAcAAkJmhGfLwD0AQloDAAAAwAyAGkMAAADADgAawwAAAMAMABqDAAAAwAwAGwMAAADACIAbQwAAAMAJADqDAAABQAxAG4MAAAEADcAbwwAAAMAHQAAAA==.',
['Sý']='Sýlvanas:BAAALgAECgQJDwAAAA==.',
Te='Tealç:BAABLgAECn8gAAIZAAcJpheVGACQAQdoDAAABgBWAGkMAAAGAFAAawwAAAYARQBqDAAABAAxAGwMAAAEACsAbQwAAAEACQDqDAAABQBKABkABwmmF5UYAJABB2gMAAAGAFYAaQwAAAYAUABrDAAABgBFAGoMAAAEADEAbAwAAAQAKwBtDAAAAQAJAOoMAAAFAEoAAS4ABRQECRQAGQAkGQA=.Tekk:BAAALgAECgEJAQAAAA==.Tekkys:BAAALgAECgEJAgAAAA==.Tertle:BAAALgADCgUJBQAAAA==.',
Ti='Tiafinia:BAAALgAECgEJAgAAAA==.Tiggerstripe:BAAALgADCgEJAQABLgAECggJLgAeAIMRAA==.Timmyy:BAAALgAECgYJBgABLgAECgkJFwALAHEcAA==.Timur:BAAALgAECgMJBAAAAA==.Tinara:BAAALgADCgUJBQAAAA==.',
Tr='Trigger:BAAALgAECgIJAgAAAA==.',
Tu='Turlesblows:BAABLgAECn8fAAMJAAgJ4B9gJAA0AghoDAAABQBTAGkMAAAFAFEAawwAAAMAUQBqDAAABABEAGwMAAAGAFoAbQwAAAIAUgDqDAAABQBZAG4MAAABAD0ACQAICeAfYCQANAIIaAwAAAUAUwBpDAAABQBRAGsMAAADAFEAagwAAAQARABsDAAABgBaAG0MAAACAFIA6gwAAAQAWQBuDAAAAQA9ABkAAQk7FZlEADsAAeoMAAABADYAAAA=.',
Tw='Twityy:BAAALgADCgEJAgAAAA==.Twofiveyd:BAABLgAFFH8FAAIVAAQJjA8jJQAIAQRoDAAAAgAzAGkMAAABAC8AawwAAAEACADqDAAAAQAzABUABAmMDyMlAAgBBGgMAAACADMAaQwAAAEALwBrDAAAAQAIAOoMAAABADMAAS4ABRQGCRQAGABnGAA=.',
Ty='Tyladrhas:BAABLgAECn80AAIhAAkJVB+pAgCnAgloDAAACABOAGkMAAAHAFkAawwAAAcASgBqDAAABwA+AGwMAAAFAE0AbQwAAAMAXQDqDAAACwBRAG4MAAADAEQAbwwAAAEATAAhAAkJVB+pAgCnAgloDAAACABOAGkMAAAHAFkAawwAAAcASgBqDAAABwA+AGwMAAAFAE0AbQwAAAMAXQDqDAAACwBRAG4MAAADAEQAbwwAAAEATAAAAA==.Tyrismaximus:BAAALgAECgMJAwAAAA==.',
Ul='Ulkina:BAAALgADCgYJCQAAAA==.',
Va='Vaelith:BAAALgAECgIJAgAAAA==.Valerine:BAABLgAECn8aAAIEAAkJ/wrlagCJAQloDAAABAAqAGkMAAAEACcAawwAAAQAOQBqDAAABQAnAGwMAAAEAC8AbQwAAAEABwDqDAAAAgAOAG4MAAABAAYAbwwAAAEACQAEAAkJ/wrlagCJAQloDAAABAAqAGkMAAAEACcAawwAAAQAOQBqDAAABQAnAGwMAAAEAC8AbQwAAAEABwDqDAAAAgAOAG4MAAABAAYAbwwAAAEACQAAAA==.Vanoran:BAAALgAECgMJBAAAAA==.Varang:BAAALgAECgIJAgAAAA==.Varina:BAAALgAECgcJEwAAAA==.',
Ve='Velsaert:BAAALgADCgcJBwAAAA==.Venki:BAAALgAECgYJBwAAAA==.',
Vi='Vitani:BAAALgADCgEJAQABLgAFFAQJDwAUAN4UAA==.',
Vo='Voidnova:BAABLgAFFH8HAAIEAAMJlRCIagDhAANoDAAAAwBBAGkMAAADAB4A6gwAAAEAHwAEAAMJlRCIagDhAANoDAAAAwBBAGkMAAADAB4A6gwAAAEAHwAAAA==.Voidphayze:BAAALgAECgUJDAABLgAFFAMJBQALAEUTAA==.',
Vu='Vulken:BAABLgAECn9nAAIcAAkJESU+CQDtAgloDAAADgBhAGkMAAAMAF4AawwAAA4AXgBqDAAADgBQAGwMAAANAFoAbQwAAAoAXQDqDAAADgBfAG4MAAAHAGAAbwwAAAUAYAAcAAkJESU+CQDtAgloDAAADgBhAGkMAAAMAF4AawwAAA4AXgBqDAAADgBQAGwMAAANAFoAbQwAAAoAXQDqDAAADgBfAG4MAAAHAGAAbwwAAAUAYAAAAA==.',
['Vê']='Vê:BAAALgAECgkJEQAAAA==.',
Wa='Wallace:BAAALgAECgcJDAAAAA==.Walterlight:BAAALgAECgYJDgAAAA==.Watto:BAABLgAECn8VAAMOAAkJOR+KEQCXAgloDAAAAQBaAGkMAAACAFAAawwAAAIAVwBqDAAAAgBYAGwMAAACAFAAbQwAAAEASwDqDAAABwBYAG4MAAADADkAbwwAAAEASAAOAAkJOR+KEQCXAgloDAAAAQBaAGkMAAACAFAAawwAAAIAVwBqDAAAAgBYAGwMAAACAFAAbQwAAAEASwDqDAAABgBYAG4MAAADADkAbwwAAAEASAAfAAEJMBfufQBEAAHqDAAAAQA7AAAA.',
We='Wemongin:BAAALgADCgUJBQAAAA==.',
Wh='Whimsical:BAABLgAECn8XAAIOAAYJgBd+QgBxAQZoDAAABABEAGkMAAAEAC8AawwAAAQALgBqDAAAAwAzAGwMAAADAFMA6gwAAAUAPwAOAAYJgBd+QgBxAQZoDAAABABEAGkMAAAEAC8AawwAAAQALgBqDAAAAwAzAGwMAAADAFMA6gwAAAUAPwAAAA==.',
Wi='Winnìng:BAABLgAECn8gAAIkAAgJJAzvHQD2AAhoDAAABQA3AGkMAAAEABgAawwAAAQAIQBqDAAABAAgAGwMAAAEAAsAbQwAAAIAEgDqDAAABgAmAG4MAAADACQAJAAICSQM7x0A9gAIaAwAAAUANwBpDAAABAAYAGsMAAAEACEAagwAAAQAIABsDAAABAALAG0MAAACABIA6gwAAAYAJgBuDAAAAwAkAAAA.',
Wu='Wugong:BAAALgADCgEJAQAAAA==.',
['Wó']='Wórkwórk:BAACLgAFFH8FAAIJAAMJKhROFwCsAANoDAAAAgA8AGkMAAACAEAA6gwAAAEAHgAJAAMJKhROFwCsAANoDAAAAgA8AGkMAAACAEAA6gwAAAEAHgAuAAQKfxsAAwkACQk6Gxg3AMsBAAkABwnRGRg3AMsBABgAAwnsGr8fAO8AAAAA.',
Zi='Zich:BAAALgADCgMJAwAAAA==.Zihon:BAABLgAECn8UAAILAAQJTxokyQDFAARoDAAAAwA7AGkMAAAFAEYAawwAAAUASQDqDAAABwBCAAsABAlPGiTJAMUABGgMAAADADsAaQwAAAUARgBrDAAABQBJAOoMAAAHAEIAAAA=.',
Zo='Zodiiak:BAABLgAECn9EAAIeAAkJMR3tBABxAgloDAAACwBOAGkMAAALAFUAawwAAAkAVgBqDAAABwA+AGwMAAAJAFEAbQwAAAQAPgDqDAAACgBRAG4MAAAGAEgAbwwAAAEAMgAeAAkJMR3tBABxAgloDAAACwBOAGkMAAALAFUAawwAAAkAVgBqDAAABwA+AGwMAAAJAFEAbQwAAAQAPgDqDAAACgBRAG4MAAAGAEgAbwwAAAEAMgAAAA==.',
Zu='Zubb:BAAALgADCgYJCQABLgAECggJEAACAAAAAA==.Zuhh:BAAALgAECgEJAQABLgAECggJEAACAAAAAA==.Zupp:BAAALgAECggJEAAAAA==.',
Zx='Zx:BAAALgADCgYJBgAAAA==.',
['Ér']='Ér:BAAALgAECgkJBQAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
