local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Priest-Shadow','Priest-Discipline','Unknown-Unknown','Mage-Frost','Paladin-Holy','DeathKnight-Blood','Priest-Holy','DemonHunter-Havoc','Monk-Mistweaver','DeathKnight-Unholy','DemonHunter-Devourer','Warrior-Fury','Warlock-Demonology','Warlock-Destruction','Warlock-Affliction','Paladin-Retribution','Hunter-Marksmanship','Shaman-Enhancement','Hunter-BeastMastery','Paladin-Protection','Evoker-Devastation','Evoker-Augmentation','Evoker-Preservation','Warrior-Arms','Shaman-Restoration','Warrior-Protection','DeathKnight-Frost','Rogue-Subtlety','DemonHunter-Vengeance','Druid-Restoration','Druid-Balance','Shaman-Elemental','Rogue-Assassination','Druid-Guardian','Druid-Feral','Monk-Windwalker','Mage-Arcane','Monk-Brewmaster','Hunter-Survival',}
local provider = {region='US',realm="Mok'Nathal",name='US',type='daily',zone=46,date='2026-05-20',data={Aa='Aaralia:BAABLgAECn8fAAMBAAkJ/BvqEgBfAgloDAAABQBcAGkMAAAFAE0AawwAAAQAQwBqDAAABABIAGwMAAAEAFMAbQwAAAEAPwDqDAAABgBaAG4MAAABADwAbwwAAAEAJQABAAgJ6B3qEgBfAghoDAAABQBcAGkMAAAFAE0AawwAAAQAQwBqDAAABABIAGwMAAAEAFMAbQwAAAEAPwDqDAAABQBaAG4MAAABADwAAgACCQYM600AbAAC6gwAAAEAKwBvDAAAAQASAAAA.',
Ab='Abovezero:BAAALgADCgYJBgAAAA==.Abyssdark:BAAALgAECgEJAgAAAA==.',
Ac='Achílleus:BAAALgADCgYJBwAAAA==.',
Ad='Adarae:BAAALgAECgcJDQAAAA==.Ademal:BAAALgAECgEJAQAAAA==.Adic:BAAALgAFFAIJAgAAAA==.',
Ae='Aeria:BAAALgAECgEJAgAAAA==.Aerwen:BAAALgAECgYJEQAAAA==.Aeverey:BAAALgADCgcJCgAAAA==.',
Ah='Ahriet:BAAALgADCgMJAwABLgAECggJDwADAAAAAA==.',
Ak='Akadeus:BAAALgAECgEJAQAAAA==.',
Al='Alarielle:BAAALgAECgQJCAABLgAECggJLAAEAIwUAA==.Alearia:BAAALgADCgEJAQAAAA==.Alewynt:BAAALgAECgEJBQAAAA==.Altiv:BAAALgAECgQJBQAAAA==.Altx:BAAALgAECgEJAgAAAA==.Altzilla:BAAALgAECgIJAwAAAA==.',
Am='Amalthea:BAAALgAECgIJAgAAAA==.Amerihc:BAAALgADCgIJAgAAAA==.Amoral:BAAALgAECgYJDgAAAA==.',
An='Andarick:BAAALgADCgkJDQAAAA==.Antipasta:BAAALgADCgcJFAAAAA==.',
Ap='Apoptosis:BAAALgAECgMJAwAAAA==.',
Ar='Aramist:BAAALgADCgUJBAAAAA==.Arkin:BAAALgAECgkJDwAAAA==.Arkinzor:BAAALgAECgQJBAAAAA==.Arroy:BAAALgADCgEJBAAAAA==.Arîane:BAAALgAECgQJBgAAAA==.',
As='Asapferg:BAAALgAECgcJEAAAAA==.Ashaman:BAABLgAECn8bAAICAAYJxAU5QQC3AAZoDAAACAARAGkMAAAGAAcAawwAAAYADwBqDAAAAgAAAGwMAAABACAA6gwAAAQADwACAAYJxAU5QQC3AAZoDAAACAARAGkMAAAGAAcAawwAAAYADwBqDAAAAgAAAGwMAAABACAA6gwAAAQADwAAAA==.Astanah:BAABLgAECn8cAAIFAAgJ5xSRMAC/AQhoDAAABABUAGkMAAAEACsAawwAAAUAOwBqDAAABAAyAGwMAAADAD4AbQwAAAMANgDqDAAABAAzAG4MAAABABUABQAICecUkTAAvwEIaAwAAAQAVABpDAAABAArAGsMAAAFADsAagwAAAQAMgBsDAAAAwA+AG0MAAADADYA6gwAAAQAMwBuDAAAAQAVAAAA.',
Az='Azari:BAAALgAECgQJBAAAAA==.',
Ba='Baneofhorde:BAAALgAECgQJBwAAAA==.Barnigolas:BAAALgADCgMJAwAAAA==.Barricadex:BAAALgADCgcJDAAAAA==.Basatan:BAAALgADCgcJBwABLgAFFAUJDAAGACMVAA==.',
Be='Bearyjane:BAAALgAECgUJBQAAAA==.Beastkraven:BAAALgAECgUJBQAAAA==.',
Bi='Bigspicyd:BAAALgADCgMJAwAAAA==.',
Bl='Blodkuil:BAABLgAECn8WAAIHAAgJjgJ5PADRAAhoDAAABAAEAGkMAAAEAAcAawwAAAQAAwBqDAAAAwAEAGwMAAADABYAbQwAAAEABADqDAAAAgABAG4MAAABAAQABwAICY4CeTwA0QAIaAwAAAQABABpDAAABAAHAGsMAAAEAAMAagwAAAMABABsDAAAAwAWAG0MAAABAAQA6gwAAAIAAQBuDAAAAQAEAAAA.Bloodedge:BAABLgAECn8lAAIIAAkJtx+mAwDoAgloDAAABQBUAGkMAAAFAFIAawwAAAMAVQBqDAAABABMAGwMAAAGAFAAbQwAAAIASADqDAAABgBgAG4MAAAEAEkAbwwAAAIASQAIAAkJtx+mAwDoAgloDAAABQBUAGkMAAAFAFIAawwAAAMAVQBqDAAABABMAGwMAAAGAFAAbQwAAAIASADqDAAABgBgAG4MAAAEAEkAbwwAAAIASQAAAA==.',
Bo='Bobbyswagger:BAAALgAFFAIJBAAAAA==.Bolock:BAAALgADCgYJCwAAAA==.Boomchickeñ:BAAALgADCgEJAQAAAA==.',
Br='Braulter:BAAALgAECgYJBwAAAA==.Brentobox:BAABLgAECn8gAAIJAAcJ4iAIDgB3AgdoDAAABwBYAGkMAAAGAFsAawwAAAYAXABqDAAABABdAGwMAAADAFMA6gwAAAUAXQBuDAAAAQAuAAkABwniIAgOAHcCB2gMAAAHAFgAaQwAAAYAWwBrDAAABgBcAGoMAAAEAF0AbAwAAAMAUwDqDAAABQBdAG4MAAABAC4AAAA=.Brew:BAAALgAECgMJAwAAAA==.Brooceree:BAAALgAECgYJEAAAAA==.Broomkin:BAAALgADCgMJAwAAAA==.',
Bu='Bungeholio:BAACLgAFFH8GAAIBAAIJMANIJQB4AAJoDAAAAwAKAGkMAAADAAYAAQACCTADSCUAeAACaAwAAAMACgBpDAAAAwAGAC4ABAp/HwACAQAICaAOpzEAIAEAAQAICaAOpzEAIAEAAAA=.Bunzzlle:BAAALgAECgYJBwABLgAFFAIJBgABADADAA==.Butterhoof:BAAALgADCgEJAQABLgAFFAUJDAAGACMVAA==.',
Ca='Cabbage:BAAALgADCgEJAQAAAA==.Cakkes:BAAALgADCgcJBwABLgAECgMJBAADAAAAAA==.Caltora:BAAALgAECgMJAwAAAA==.Cannelle:BAABLgAECn8cAAIEAAkJoAeGaACEAQloDAAABQAaAGkMAAAEABIAawwAAAQACQBqDAAAAwAYAGwMAAADABEAbQwAAAIAKADqDAAABAAWAG4MAAACAAgAbwwAAAEADAAEAAkJoAeGaACEAQloDAAABQAaAGkMAAAEABIAawwAAAQACQBqDAAAAwAYAGwMAAADABEAbQwAAAIAKADqDAAABAAWAG4MAAACAAgAbwwAAAEADAAAAA==.Carden:BAABLgAECn8nAAMGAAgJaiJ6BQCjAghoDAAACABTAGkMAAAHAGEAawwAAAcAXgBqDAAABQBfAGwMAAAEAFAAbQwAAAEAWADqDAAABgBXAG4MAAABAFQABgAICWoiegUAowIIaAwAAAgAUwBpDAAABwBhAGsMAAAGAF4AagwAAAUAXwBsDAAABABQAG0MAAABAFgA6gwAAAYAVwBuDAAAAQBUAAoAAQnPCnMfATcAAWsMAAABABsAAAA=.Carimknight:BAAALgAECggJDgAAAA==.Cathraga:BAAALgADCgEJAQAAAA==.',
Ch='Chardh:BAABLgAECn8dAAILAAgJxCR1CwAmAwhoDAAABABjAGkMAAAFAGMAawwAAAQAYwBqDAAABABbAGwMAAAEAGEAbQwAAAIAXADqDAAABQBjAG4MAAABAEcACwAICcQkdQsAJgMIaAwAAAQAYwBpDAAABQBjAGsMAAAEAGMAagwAAAQAWwBsDAAABABhAG0MAAACAFwA6gwAAAUAYwBuDAAAAQBHAAAA.Charlas:BAAALgADCgUJBQAAAA==.Chesstickle:BAABLgAECn8aAAIKAAgJOgUCjwAcAQhoDAAABQAQAGkMAAADAA8AawwAAAMABABqDAAAAwANAGwMAAAEABEAbQwAAAIACQDqDAAABAAQAG4MAAACAA4ACgAICToFAo8AHAEIaAwAAAUAEABpDAAAAwAPAGsMAAADAAQAagwAAAMADQBsDAAABAARAG0MAAACAAkA6gwAAAQAEABuDAAAAgAOAAAA.Chillywillie:BAABLgAECn8hAAIMAAgJ2xDiJQCYAQhoDAAABwAsAGkMAAAFAC8AawwAAAUALgBqDAAABQA4AGwMAAADADoAbQwAAAEADwDqDAAABgAyAG4MAAABACYADAAICdsQ4iUAmAEIaAwAAAcALABpDAAABQAvAGsMAAAFAC4AagwAAAUAOABsDAAAAwA6AG0MAAABAA8A6gwAAAYAMgBuDAAAAQAmAAAA.Chitos:BAAALgAECgYJBgAAAA==.Chosandik:BAAALgAECgcJBwAAAA==.Chrodne:BAAALgAECgMJCAAAAA==.Chromax:BAAALgADCgYJCQAAAA==.Chucknorrîs:BAAALgAECgEJAwAAAA==.',
Ci='Cigam:BAAALgADCgMJAwAAAA==.',
Cl='Clasmind:BAAALgAECgMJBwAAAA==.Cleptodog:BAAALgAECgkJAwAAAA==.Clintbarton:BAAALgAECgYJDwAAAA==.Cloudstrike:BAAALgAFFAIJAwAAAA==.',
Co='Coordination:BAAALgADCggJDQAAAA==.',
Cr='Crend:BAAALgAECgUJCwAAAA==.',
Ct='Cthullu:BAACLgAFFH8MAAIGAAUJIxXsGgC+AAVoDAAABAA/AGkMAAABADMAawwAAAEAEwBqDAAAAQApAOoMAAAFAFEABgAFCSMV7BoAvgAFaAwAAAQAPwBpDAAAAQAzAGsMAAABABMAagwAAAEAKQDqDAAABQBRAC4ABAp/GQADBgAJCS4dSQgAYAIABgAJCV8cSQgAYAIACgAFCTQcw5oASwEAAAA=.',
['Cø']='Cøldshoulder:BAABLgAECn8dAAIKAAgJPxqXTQCwAQhoDAAABABQAGkMAAAEAEcAawwAAAQARgBqDAAAAwBCAGwMAAAEADoAbQwAAAIAIgDqDAAABQBTAG4MAAADAEcACgAICT8al00AsAEIaAwAAAQAUABpDAAABABHAGsMAAAEAEYAagwAAAMAQgBsDAAABAA6AG0MAAACACIA6gwAAAUAUwBuDAAAAwBHAAAA.',
Da='Dabi:BAAALgAECgQJEAAAAA==.Daemon:BAABLgAECn8VAAILAAgJRRu/KwDwAQhoDAAAAwBcAGkMAAADAEQAawwAAAMAKwBqDAAAAwAzAGwMAAAEAEsAbQwAAAIASwDqDAAAAgAzAG4MAAABAFIACwAICUUbvysA8AEIaAwAAAMAXABpDAAAAwBEAGsMAAADACsAagwAAAMAMwBsDAAABABLAG0MAAACAEsA6gwAAAIAMwBuDAAAAQBSAAAA.Dagore:BAAALgADCgYJBgAAAA==.Dailyalice:BAAALgAECgMJBgAAAA==.Danglinwang:BAAALgADCgEJAQAAAA==.Dankwoods:BAAALgAECgUJCQAAAA==.Darcmatter:BAABLgAECn86AAQNAAkJfB3YEQCeAgloDAAABwBRAGkMAAAHAFMAawwAAAcAUABqDAAABgBVAGwMAAAGAFsAbQwAAAUAQgDqDAAACABPAG4MAAAIAD0AbwwAAAQAOwANAAkJfB3YEQCeAgloDAAABwBRAGkMAAAFAFMAawwAAAUAUABqDAAAAgBJAGwMAAAGAFsAbQwAAAQAQgDqDAAACABPAG4MAAAIAD0AbwwAAAQAOwAOAAQJXxLYKAAfAQRpDAAAAQA7AGsMAAACAD8AagwAAAQAVQBtDAAAAQARAA8AAQmyGQQrADsAAWkMAAABAEEAAAA=.Darkemperor:BAAALgADCgEJAQABLgAECgEJAgADAAAAAA==.Dayday:BAAALgAECgIJAgABLgAECggJGgAQAPMTAA==.',
De='Deathsend:BAABLgAECn8eAAIKAAcJ1QQ4qQDwAAdoDAAABwAJAGkMAAAGABAAawwAAAYAEQBqDAAAAwALAGwMAAABABIA6gwAAAUABwBuDAAAAgAEAAoABwnVBDipAPAAB2gMAAAHAAkAaQwAAAYAEABrDAAABgARAGoMAAADAAsAbAwAAAEAEgDqDAAABQAHAG4MAAACAAQAAAA=.Decamoose:BAABLgAECn8eAAIRAAgJIxMRCgCcAQhoDAAABAAnAGkMAAAEACoAawwAAAQAPQBqDAAABAA2AGwMAAAEADEAbQwAAAMAIQDqDAAABAA9AG4MAAADADYAEQAICSMTEQoAnAEIaAwAAAQAJwBpDAAABAAqAGsMAAAEAD0AagwAAAQANgBsDAAABAAxAG0MAAADACEA6gwAAAQAPQBuDAAAAwA2AAAA.Deeboogie:BAAALgAECgQJBAAAAA==.Deepsicks:BAABLgAFFH8FAAISAAIJcgxYCwCSAAJoDAAAAgAjAOoMAAADABwAEgACCXIMWAsAkgACaAwAAAIAIwDqDAAAAwAcAAAA.Deepstate:BAAALgAECgIJAgAAAA==.Deidamia:BAAALgAECgEJAgAAAA==.Deimosz:BAAALgAECgcJEAABLgAFFAQJCwAJAI8XAA==.Demonaholio:BAAALgAECgEJAQABLgAFFAIJBgABADADAA==.Demonicade:BAABLgAECn8eAAMNAAgJQQt0bQBBAQhoDAAABQAnAGkMAAAFAB8AawwAAAUAJwBqDAAABAAgAGwMAAADAC0AbQwAAAEACQDqDAAABgATAG4MAAABABAADQAHCUELdG0AQQEHaAwAAAUAJwBpDAAABQAfAGsMAAAFACcAbAwAAAMALQBtDAAAAQAJAOoMAAAGABMAbgwAAAEAEAAOAAEJAABmdQAvAAFqDAAABAAgAAAA.Demonäde:BAAALgADCgYJBgAAAA==.Desaint:BAAALgAECgQJBAAAAA==.Devana:BAAALgADCgMJAwAAAA==.',
Di='Dima:BAABLgAECn8xAAITAAkJhh/mDQCwAgloDAAACABTAGkMAAAHAFUAawwAAAgATgBqDAAABgA9AGwMAAAGAEEAbQwAAAMAXADqDAAABwBcAG4MAAADAE4AbwwAAAEARAATAAkJhh/mDQCwAgloDAAACABTAGkMAAAHAFUAawwAAAgATgBqDAAABgA9AGwMAAAGAEEAbQwAAAMAXADqDAAABwBcAG4MAAADAE4AbwwAAAEARAAAAA==.Dingler:BAAALgAECgUJBAAAAA==.Dithy:BAAALgAECgQJCgAAAA==.',
Dn='Dne:BAABLgAECn8kAAIKAAgJxQ98YgDMAQhoDAAABgArAGkMAAAFAC8AawwAAAYAIwBqDAAABQAuAGwMAAAFAC4AbQwAAAMAKQDqDAAABAAZAG4MAAACACoACgAICcUPfGIAzAEIaAwAAAYAKwBpDAAABQAvAGsMAAAGACMAagwAAAUALgBsDAAABQAuAG0MAAADACkA6gwAAAQAGQBuDAAAAgAqAAAA.',
Do='Donavon:BAABLgAECn87AAMFAAkJAiFPBAAqAwloDAAACABDAGkMAAAHAEwAawwAAAgAWQBqDAAABwBdAGwMAAAHAGAAbQwAAAgAXgDqDAAABwBIAG4MAAAGAFsAbwwAAAEATwAFAAkJAiFPBAAqAwloDAAABwBDAGkMAAAGAEwAawwAAAcAWQBqDAAABgBdAGwMAAAGAGAAbQwAAAcAXgDqDAAABgBIAG4MAAAFAFsAbwwAAAEATwAUAAgJ3x3eBQBXAghoDAAAAQA6AGkMAAABAGAAawwAAAEAWQBqDAAAAQBfAGwMAAABAEAAbQwAAAEAVwDqDAAAAQBJAG4MAAABAEEAAAA=.Dornnbryda:BAAALgAECggJEAAAAA==.',
Dp='Dpuncher:BAAALgADCgUJBQAAAA==.',
Dr='Drackothyr:BAABLgAECn8sAAQVAAgJPyCRBQDUAQhoDAAABgBaAGkMAAAGAFYAawwAAAYAXQBqDAAABQBfAGwMAAAGAFMAbQwAAAMAQADqDAAACQBaAG4MAAADAEUAFgAICdYcBRQAEAIIaAwAAAEAWgBpDAAAAQBPAGsMAAABADsAagwAAAEASwBsDAAAAwBQAG0MAAACAEAA6gwAAAMASgBuDAAAAwBFABUABgmHIpEFANQBBmgMAAAFAFcAaQwAAAQAVgBrDAAABABdAGoMAAADAF8AbAwAAAIAUwDqDAAABQBaABcABgm4BTAdAOIABmkMAAABABEAawwAAAEAEQBqDAAAAQALAGwMAAABAAgAbQwAAAEAGADqDAAAAQAIAAAA.Drecarus:BAAALgAECggJEwAAAA==.Drgoodvibes:BAAALgADCgYJBgABLgAFFAUJDAAGACMVAA==.',
Du='Duudeimalock:BAAALgADCgYJBgAAAA==.',
Ec='Echidna:BAAALgADCgkJFgAAAA==.',
Eg='Egosnipe:BAAALgADCgEJAQAAAA==.',
El='Elamshinae:BAAALgAECgcJIAAAAQ==.Elementalor:BAAALgAECgQJBAAAAA==.Elizaf:BAAALgAECgEJAQAAAA==.Elizarothgol:BAAALgADCgcJBwAAAA==.Elyia:BAAALgADCgMJAwAAAA==.',
En='Entchen:BAAALgAECgIJAgABLgAECgQJBgADAAAAAA==.',
Ep='Eppey:BAAALgAECgMJAwAAAA==.',
Er='Erragorn:BAABLgAECn8fAAMMAAgJahezGwDfAQhoDAAABwBOAGkMAAAGAEcAawwAAAQAQABqDAAAAgAuAGwMAAACAD8AbQwAAAEADgDqDAAACABYAG4MAAABACUADAAICWoXsxsA3wEIaAwAAAcATgBpDAAABgBHAGsMAAADAEAAagwAAAIALgBsDAAAAgA/AG0MAAABAA4A6gwAAAgAWABuDAAAAQAlABgAAQljAnJoAA4AAWsMAAABAAYAAAA=.',
Es='Estinzione:BAAALgADCgYJBgAAAA==.',
Ex='Exalitor:BAAALgADCgYJEgAAAA==.',
Ey='Eyeguy:BAABLgAECn8VAAMIAAkJewRmQQD0AAloDAAABAAKAGkMAAADABEAawwAAAQACQBqDAAAAgATAGwMAAADABAAbQwAAAEACQDqDAAAAgAGAG4MAAABAAYAbwwAAAEADwAIAAkJewRmQQD0AAloDAAAAwAKAGkMAAACABEAawwAAAQACQBqDAAAAgATAGwMAAADABAAbQwAAAEACQDqDAAAAQAGAG4MAAABAAYAbwwAAAEADwALAAMJHgH62AA+AANoDAAAAQACAGkMAAABAAMA6gwAAAEAAgAAAA==.',
['Eö']='Eöath:BAAALgAECgcJDwAAAA==.',
Fa='Falaurenta:BAAALgAECgYJDAAAAA==.',
Fe='Fea:BAAALgADCgEJAQAAAA==.Feidao:BAAALgADCgcJDAAAAA==.Feltank:BAAALgAECgUJBgABLgAFFAUJDAAGACMVAA==.',
Fr='Francesca:BAAALgAECgIJAwAAAA==.Franck:BAAALgAECgQJCwAAAA==.Frazierr:BAAALgAECgEJAQAAAA==.Freedessert:BAAALgAECgUJBgAAAA==.',
Fu='Fuuke:BAABLgAECn8XAAIBAAgJZQ/jIwB0AQhoDAAABQA7AGkMAAAEADYAawwAAAQAHgBqDAAAAwAqAGwMAAABADQAbQwAAAEAEQDqDAAAAwAiAG4MAAACABoAAQAICWUP4yMAdAEIaAwAAAUAOwBpDAAABAA2AGsMAAAEAB4AagwAAAMAKgBsDAAAAQA0AG0MAAABABEA6gwAAAMAIgBuDAAAAgAaAAAA.',
Ga='Gailinn:BAAALgAECgQJCAAAAA==.Galreth:BAAALgAECgUJCgAAAA==.Ganon:BAABLgAECn8hAAQNAAgJmSEWEgCcAghoDAAABABWAGkMAAAEAFIAawwAAAQAXQBqDAAABABhAGwMAAAFAE0AbQwAAAMAYQDqDAAABwBeAG4MAAACAEQADQAICZkhFhIAnAIIaAwAAAQAVgBpDAAABABSAGsMAAADAF0AagwAAAMAYQBsDAAABQBNAG0MAAADAGEA6gwAAAYAXgBuDAAAAgBEAA4AAgkKEixUAHIAAmoMAAABACgA6gwAAAEALgAPAAEJHRkmKQBNAAFrDAAAAQBAAAAA.',
Go='Gozebo:BAAALgADCgMJBAAAAA==.',
Gr='Greggdshami:BAABLgAECn8fAAIZAAgJORrbIwD6AQhoDAAABAA/AGkMAAAEADkAawwAAAQAPgBqDAAABABXAGwMAAAFAFIAbQwAAAIANADqDAAABgBRAG4MAAACADIAGQAICTka2yMA+gEIaAwAAAQAPwBpDAAABAA5AGsMAAAEAD4AagwAAAQAVwBsDAAABQBSAG0MAAACADQA6gwAAAYAUQBuDAAAAgAyAAAA.Gresh:BAAALgADCgYJBgAAAA==.Gretagobbo:BAAALgAECgYJDQABLgAFFAQJCwAJAI8XAA==.Grimmlockk:BAABLgAECn8fAAINAAcJZxsgLwD5AQdoDAAABgBPAGkMAAAFAE8AawwAAAYATgBqDAAAAwBVAGwMAAADAEUA6gwAAAcAVQBuDAAAAQAdAA0ABwlnGyAvAPkBB2gMAAAGAE8AaQwAAAUATwBrDAAABgBOAGoMAAADAFUAbAwAAAMARQDqDAAABwBVAG4MAAABAB0AAS4ABRQHCRYACwBmHAA=.Grimroc:BAAALgADCgQJBAAAAA==.Grunbeld:BAAALgAECgQJBAAAAA==.',
Gu='Gunblade:BAABLgAECn8vAAIaAAgJPA8sFwBXAQhoDAAABwAwAGkMAAAHACQAawwAAAYAKgBqDAAABgAtAGwMAAAHABgAbQwAAAQAGwDqDAAABwBEAG4MAAADABcAGgAICTwPLBcAVwEIaAwAAAcAMABpDAAABwAkAGsMAAAGACoAagwAAAYALQBsDAAABwAYAG0MAAAEABsA6gwAAAcARABuDAAAAwAXAAAA.Gundin:BAAALgADCgYJBgAAAA==.Gurney:BAAALgADCggJDwABLgADCgkJGAADAAAAAA==.',
['Gü']='Güenhwyvar:BAAALgAECgEJAQAAAA==.',
Ha='Hailprincess:BAAALgAECgMJAwAAAA==.Hanuufalem:BAAALgAECgYJDAAAAA==.Hassad:BAAALgADCgcJDQAAAA==.',
He='Healaton:BAAALgAECggJDwAAAA==.Healmonger:BAACLgAFFH8GAAMHAAMJwwfBGQCxAANoDAAAAwAbAGkMAAABAAgA6gwAAAIAFwAHAAMJwwfBGQCxAANoDAAAAgAbAGkMAAABAAgA6gwAAAIAFwACAAEJ8AHzOAA2AAFoDAAAAQAEAC4ABAp/KwAEBwAJCeYU+hAAKwIABwAJCeYU+hAAKwIAAQAGCWwHsz4A3gAAAgACCbAJRlAAYQAAAAA=.Healpants:BAAALgAECgcJBgAAAA==.Heruin:BAABLgAFFH8HAAMKAAMJ7g9zdgDdAANoDAAAAwAIAGkMAAACAEEA6gwAAAIAMAAKAAMJ7g9zdgDdAANoDAAAAQAIAGkMAAACAEEA6gwAAAIAMAAbAAEJGgODFgBAAAFoDAAAAgAHAAAA.',
Hi='Hilgasmic:BAAALgAFFAEJAQAAAA==.',
Ho='Hohenhaim:BAAALgAECgkJEgAAAA==.Holly:BAAALgAECgcJDAAAAA==.Holykal:BAEBLgAECn8kAAIQAAgJ/B+sHwBiAghoDAAABQBfAGkMAAAFAFQAawwAAAUAWQBqDAAABQBaAGwMAAAFAFUAbQwAAAIAQQDqDAAABwBVAG4MAAACAEMAEAAICfwfrB8AYgIIaAwAAAUAXwBpDAAABQBUAGsMAAAFAFkAagwAAAUAWgBsDAAABQBVAG0MAAACAEEA6gwAAAcAVQBuDAAAAgBDAAAA.Hope:BAAALgADCgYJBgABLgAECggJDAADAAAAAA==.Horse:BAACLgAFFH8qAAIHAAYJEAMPCgBfAQZoDAAACQALAGkMAAAIAAgAawwAAAcABgBqDAAABgADAGwMAAAEAAgA6gwAAAgACAAHAAYJEAMPCgBfAQZoDAAACQALAGkMAAAIAAgAawwAAAcABgBqDAAABgADAGwMAAAEAAgA6gwAAAgACAAuAAQKfz8AAgcACQneFwIPAEYCAAcACQneFwIPAEYCAAAA.',
Ib='Ibelurkin:BAAALgADCgMJAwAAAA==.',
Ic='Icu:BAAALgAFFAIJAgAAAA==.',
Ih='Ihasabukkit:BAAALgAECgEJAQABLgAECgUJBQADAAAAAA==.Ihunt:BAAALgADCgIJAwAAAA==.',
In='Indominus:BAAALgAECgMJAwAAAA==.',
Ja='Jabachi:BAAALgAECgQJCwAAAA==.Jarixx:BAAALgAECgQJBQAAAA==.Jaydubz:BAAALgADCgMJAwAAAA==.Jaysashi:BAABLgAECn8iAAIcAAgJ/BwsCQBkAghoDAAABwBRAGkMAAAGAFYAawwAAAYAUgBqDAAAAgBKAGwMAAACAFIAbQwAAAIAKQDqDAAACABWAG4MAAABADoAHAAICfwcLAkAZAIIaAwAAAcAUQBpDAAABgBWAGsMAAAGAFIAagwAAAIASgBsDAAAAgBSAG0MAAACACkA6gwAAAgAVgBuDAAAAQA6AAAA.',
Ji='Jigsaww:BAAALgADCgYJBgAAAA==.',
Ju='Jun:BAACLgAFFH8hAAMLAAYJsSTTCAAJAgZoDAAABwBhAGkMAAAGAGAAawwAAAUAWABqDAAABQBQAGwMAAAEAF4A6gwAAAYAWwALAAYJsSTTCAAJAgZoDAAABwBhAGkMAAAFAGAAawwAAAQAWABqDAAABQBQAGwMAAAEAF4A6gwAAAYAWwAIAAIJ+h7kEQC9AAJpDAAAAQBNAGsMAAABAFAALgAECn88AAMLAAkJoCWlAgBMAwALAAkJoCWlAgBMAwAIAAcJjCROCQDNAgAAAA==.Justdruid:BAAALgADCgMJAwAAAA==.Juum:BAAALgADCgIJAgAAAA==.',
Ka='Kahla:BAAALgAECgEJAQAAAA==.Kaho:BAAALgAECgQJCQAAAA==.Karkas:BAAALgAECgYJEAAAAA==.Kass:BAAALgADCgMJAwAAAA==.Kasumaus:BAABLgAECn8kAAMKAAkJKgribgBbAQloDAAABgAmAGkMAAAFABkAawwAAAUAGwBqDAAAAgATAGwMAAAFACIAbQwAAAQAEQDqDAAABQAkAG4MAAADAA0AbwwAAAEADQAKAAgJ6gnibgBbAQhoDAAABQAmAGkMAAAFABkAawwAAAUAGwBqDAAAAgATAGwMAAAEABIAbQwAAAQAEQDqDAAABQAkAG4MAAADAA0AGwADCVILqRsAjwADaAwAAAEAJgBsDAAAAQAiAG8MAAABAA0AAAA=.Kateera:BAAALgAECgYJCQABLgAECgkJJQAaAMMWAA==.Kayroonrangi:BAAALgAECgEJAgAAAA==.',
Ke='Kearyn:BAABLgAECn8lAAMaAAkJwxZ+DADwAQloDAAABABOAGkMAAAEADwAawwAAAQAMgBqDAAABABAAGwMAAAGAEIAbQwAAAQAKgDqDAAABgAzAG4MAAAEACcAbwwAAAEASwAaAAkJwxZ+DADwAQloDAAABABOAGkMAAAEADwAawwAAAQAMgBqDAAABABAAGwMAAAFAEIAbQwAAAMAKgDqDAAABQAzAG4MAAADACcAbwwAAAEASwAMAAQJIgpwVADDAARsDAAAAQAaAG0MAAABABwA6gwAAAEAHABuDAAAAQAUAAAA.Keifrene:BAAALgADCgcJCwAAAA==.Keldra:BAAALgAECgcJDgAAAA==.Kelnis:BAAALgAECgQJDAAAAA==.Kelp:BAAALgADCgkJGgAAAA==.Kevrad:BAAALgADCgcJCAAAAA==.',
Kh='Khephris:BAABLgAECn8sAAIEAAgJjBQEbwB1AQhoDAAABwA6AGkMAAAIADMAawwAAAgAQgBqDAAABAAgAGwMAAAHAC0AbQwAAAEAJgDqDAAABwA5AG4MAAACADIABAAICYwUBG8AdQEIaAwAAAcAOgBpDAAACAAzAGsMAAAIAEIAagwAAAQAIABsDAAABwAtAG0MAAABACYA6gwAAAcAOQBuDAAAAgAyAAAA.',
Ki='Kilin:BAAALgADCgEJAQAAAA==.Kiralni:BAAALgAECgEJAQAAAA==.Kiramdh:BAAALgADCgMJAwAAAA==.',
Kn='Knivex:BAABLgAECn83AAIEAAkJxCGsDQDtAgloDAAACABdAGkMAAAIAF0AawwAAAgAUABqDAAABgBeAGwMAAAGAFwAbQwAAAQAUADqDAAACABdAG4MAAAFAFMAbwwAAAIASgAEAAkJxCGsDQDtAgloDAAACABdAGkMAAAIAF0AawwAAAgAUABqDAAABgBeAGwMAAAGAFwAbQwAAAQAUADqDAAACABdAG4MAAAFAFMAbwwAAAIASgAAAA==.',
Ko='Koani:BAAALgADCgEJAgAAAA==.',
Kr='Krazyplaya:BAAALgADCgEJAQAAAA==.',
La='Laceddoob:BAAALgADCgYJBgAAAA==.Lahra:BAAALgAECgIJAgAAAA==.Lalatina:BAAALgAECgEJAQAAAA==.Lambo:BAAALgAECgcJDwAAAA==.Landris:BAAALgADCggJCAAAAA==.Lanel:BAAALgADCgUJBQAAAA==.Lanners:BAAALgAECgQJBwAAAA==.Lazermoose:BAAALgAECgYJDgAAAA==.Lazuleon:BAAALgAECgcJBwAAAA==.',
Le='Leap:BAACLgAFFH8JAAIdAAMJWAoFBwCVAANoDAAAAwARAGkMAAADACcA6gwAAAMAFgAdAAMJWAoFBwCVAANoDAAAAwARAGkMAAADACcA6gwAAAMAFgAuAAQKfx0AAh0ACQl/FOUGAOMBAB0ACQl/FOUGAOMBAAAA.Leonîdas:BAAALgAECgEJAQAAAA==.',
Lf='Lfwowgf:BAAALgAECgcJBwAAAA==.',
Li='Lightbläster:BAAALgAECgYJCgAAAA==.Lightrider:BAAALgAECgUJBQAAAA==.Lionroar:BAACLgAFFH8YAAIeAAUJZRjSEQCHAQVoDAAABgA7AGkMAAAFAFYAawwAAAUAHgBqDAAAAwApAOoMAAAFAF4AHgAFCWUY0hEAhwEFaAwAAAYAOwBpDAAABQBWAGsMAAAFAB4AagwAAAMAKQDqDAAABQBeAC4ABAp/LQADHgAICWEheRIAogIAHgAICWEheRIAogIAHwAGCeoVQDUAaQEAAAA=.',
Ll='Llaothtaed:BAAALgAECgkJDAAAAA==.',
Lo='Locktard:BAAALgAECgYJCQAAAA==.Lokalock:BAAALgADCggJCgABLgAECgkJJgASAM0ZAA==.Lorellei:BAABLgAECn8dAAIHAAcJ7Q0ILQAzAQdoDAAABQAzAGkMAAAFABcAawwAAAYAGgBqDAAABAAuAGwMAAADACsA6gwAAAUANABuDAAAAQAEAAcABwntDQgtADMBB2gMAAAFADMAaQwAAAUAFwBrDAAABgAaAGoMAAAEAC4AbAwAAAMAKwDqDAAABQA0AG4MAAABAAQAAAA=.Lothgow:BAAALgAECgUJCAAAAA==.Lourdes:BAABLgAECn8WAAIEAAgJhgLstgDxAAhoDAAABAAEAGkMAAAEAAkAawwAAAQABQBqDAAAAwAMAGwMAAACAAgAbQwAAAEACADqDAAAAgADAG4MAAACAAQABAAICYYC7LYA8QAIaAwAAAQABABpDAAABAAJAGsMAAAEAAUAagwAAAMADABsDAAAAgAIAG0MAAABAAgA6gwAAAIAAwBuDAAAAgAEAAAA.',
Lu='Luxus:BAAALgADCggJEAAAAA==.',
Lv='Lvispriestly:BAAALgAECgQJBAAAAA==.',
['Lì']='Lìnk:BAAALgADCgIJAwABLgAFFAUJDAAGACMVAA==.',
Ma='Magchro:BAAALgADCgEJAQAAAA==.Maggzz:BAAALgAECgEJAwAAAA==.Magîcpin:BAAALgAECgEJAQAAAA==.Malefiroar:BAAALgADCgUJCAAAAA==.Manticor:BAAALgAECgEJAQAAAA==.Matteas:BAABLgAECn8pAAIQAAkJHyPvBQAmAwloDAAABwBgAGkMAAAFAF8AawwAAAcAXQBqDAAABABCAGwMAAAFAGMAbQwAAAMAUgDqDAAABgBUAG4MAAADAEUAbwwAAAEAYQAQAAkJHyPvBQAmAwloDAAABwBgAGkMAAAFAF8AawwAAAcAXQBqDAAABABCAGwMAAAFAGMAbQwAAAMAUgDqDAAABgBUAG4MAAADAEUAbwwAAAEAYQAAAA==.May:BAAALgAECgMJAQAAAA==.',
Me='Mebbe:BAAALgADCgIJAgAAAA==.Mew:BAAALgADCgUJBQAAAA==.Mewchi:BAAALgAECgEJAQABLgAECgcJHAAFAHYdAA==.Mewzi:BAAALgAECgQJCQAAAA==.',
Mi='Miah:BAABLgAECn8iAAIRAAYJtRnHDQBMAQZoDAAABgBJAGkMAAAGAEsAawwAAAYASwBqDAAABQBJAGwMAAAFADIA6gwAAAYANgARAAYJtRnHDQBMAQZoDAAABgBJAGkMAAAGAEsAawwAAAYASwBqDAAABQBJAGwMAAAFADIA6gwAAAYANgAAAA==.Miip:BAAALgADCgYJCgAAAA==.Mikelock:BAAALgADCgEJAQABLgAFFAEJAQADAAAAAA==.Milkmissile:BAAALgADCgkJFgAAAA==.Milkyflower:BAAALgAECgcJEwAAAA==.Mindbender:BAAALgADCgEJAQABLgAECgcJDgADAAAAAA==.',
Mo='Mograins:BAABLgAECn80AAMNAAgJjR/xKwAGAghoDAAACQBbAGkMAAAKAGEAawwAAAgAUABqDAAABwBUAGwMAAAFAEgAbQwAAAIAPgDqDAAABwBbAG4MAAAEAEUADQAGCb8g8SsABgIGaAwAAAkAWwBpDAAACgBhAGsMAAAIAFAAbAwAAAUASADqDAAABwBbAG4MAAAEAEUADgACCVwYf0MApwACagwAAAcAVABtDAAAAgA+AAAA.Monzcarro:BAAALgAECgYJCgAAAA==.Morgainne:BAAALgAECgQJCgAAAA==.Morpho:BAAALgAECgkJCAAAAA==.Mortmor:BAAALgADCgkJCQAAAA==.',
Ms='Mstrsinister:BAAALgADCgcJBwAAAA==.',
Mu='Muffinn:BAABLgAECn8cAAITAAkJBAkqWwBYAQloDAAABAAVAGkMAAAEAA4AawwAAAQAFgBqDAAAAwALAGwMAAADABQAbQwAAAEACQDqDAAABgAeAG4MAAACADIAbwwAAAEADgATAAkJBAkqWwBYAQloDAAABAAVAGkMAAAEAA4AawwAAAQAFgBqDAAAAwALAGwMAAADABQAbQwAAAEACQDqDAAABgAeAG4MAAACADIAbwwAAAEADgAAAA==.Mugvinx:BAAALgAECgEJAQAAAA==.Munti:BAAALgAECgkJCAAAAA==.',
My='Myko:BAAALgAECgkJEgAAAA==.Mymdos:BAAALgAECgcJDQABLgABCgMJAwADAAAAAA==.',
['Mä']='Mästérdòn:BAAALgADCgQJCAAAAA==.',
['Må']='Måsterdon:BAABLgAECn8UAAIUAAgJXw47FABLAQhoDAAABAAeAGkMAAAEADAAawwAAAQAQwBqDAAAAgApAGwMAAABABMAbQwAAAEAGQDqDAAAAwAhAG4MAAABAB8AFAAICV8OOxQASwEIaAwAAAQAHgBpDAAABAAwAGsMAAAEAEMAagwAAAIAKQBsDAAAAQATAG0MAAABABkA6gwAAAMAIQBuDAAAAQAfAAAA.Måstërdön:BAAALgADCgQJBAAAAA==.',
Na='Nala:BAACLgAFFH8LAAIMAAMJbxr/HwD6AANoDAAABQBOAGkMAAACAEsA6gwAAAQAMQAMAAMJbxr/HwD6AANoDAAABQBOAGkMAAACAEsA6gwAAAQAMQAuAAQKfyIAAgwACQk5IYsJAJ0CAAwACQk5IYsJAJ0CAAAA.',
Ne='Nerc:BAAALgADCgEJAQABLgADCgYJBgADAAAAAA==.Nercos:BAAALgADCgYJBgAAAA==.Neverborn:BAABLgAECn8UAAQHAAcJ6xQkKgBHAQdoDAAABAA9AGkMAAADABQAawwAAAQARABqDAAAAwBUAGwMAAADACgAbQwAAAEAFwDqDAAAAgBLAAcABwnrFCQqAEcBB2gMAAADAD0AaQwAAAMAFABrDAAAAwBEAGoMAAADAFQAbAwAAAIAKABtDAAAAQAXAOoMAAACAEsAAgACCYcEalEARgACaAwAAAEAEwBrDAAAAQADAAEAAQlhA9toACcAAWwMAAABAAgAAAA=.',
Ni='Niame:BAABLgAECn8YAAIgAAYJXA9tQAD1AAZoDAAAAwAlAGkMAAADAA8AawwAAAYALwBqDAAABAA1AGwMAAADAEAA6gwAAAUAIAAgAAYJXA9tQAD1AAZoDAAAAwAlAGkMAAADAA8AawwAAAYALwBqDAAABAA1AGwMAAADAEAA6gwAAAUAIAAAAA==.Nitraina:BAAALgAECgQJBAAAAA==.Niyabelle:BAABLgAECn8kAAMcAAcJ2BsnFwCyAQdoDAAABgBSAGkMAAAGAFkAawwAAAYAOwBqDAAABQBCAGwMAAAEAD4AbQwAAAEAMADqDAAACABVABwABwlUGScXALIBB2gMAAAFAEQAaQwAAAUARgBrDAAABQA7AGoMAAAEAEEAbAwAAAMAOABtDAAAAQAwAOoMAAAHAFUAIQAGCfUXKwsAUQEGaAwAAAEAUgBpDAAAAQBZAGsMAAABAAIAagwAAAEAQgBsDAAAAQA+AOoMAAABAEUAAAA=.',
No='Noether:BAAALgAECggJDwAAAA==.Nolimitation:BAAALgAECgEJAQAAAA==.',
Ny='Nybrax:BAAALgADCgYJBgAAAA==.Nyomi:BAAALgADCgQJBAAAAA==.',
Oa='Oakmane:BAABLgAECn8VAAMiAAcJYxNtGQAuAQdoDAAABAA1AGkMAAAEADMAawwAAAQAOQBqDAAAAwA4AGwMAAACACQA6gwAAAMASgBuDAAAAQAXACIABglmFW0ZAC4BBmgMAAADADUAaQwAAAMAMwBrDAAAAwA5AGoMAAADADgAbAwAAAIAJADqDAAAAgBKACMABQkXCHQvAFgABWgMAAABABYAaQwAAAEAEwBrDAAAAQAWAOoMAAABAA8AbgwAAAEAFwAAAA==.',
Ok='Okamí:BAAALgADCgUJBQABLgAECggJDAADAAAAAA==.Okinawa:BAAALgAECgEJAgAAAA==.',
Ol='Oleevia:BAABLgAECn8iAAIBAAkJlBZBEgAQAgloDAAABgBEAGkMAAAFAEYAawwAAAUASABqDAAABAAiAGwMAAAFADUAbQwAAAEAEgDqDAAABgBNAG4MAAABADMAbwwAAAEAMQABAAkJlBZBEgAQAgloDAAABgBEAGkMAAAFAEYAawwAAAUASABqDAAABAAiAGwMAAAFADUAbQwAAAEAEgDqDAAABgBNAG4MAAABADMAbwwAAAEAMQAAAA==.',
On='Onrangi:BAAALgADCgIJAgAAAA==.',
Or='Oralis:BAAALgADCgUJBQAAAA==.Oraxia:BAAALgAECgEJAQABLgAFFAQJCwAJAI8XAA==.Oreiel:BAAALgAECgEJAQAAAA==.Orgdh:BAACLgAFFH8nAAILAAYJYhjLFQCRAQZoDAAACABCAGkMAAAHAEoAawwAAAcAOABqDAAABgAzAGwMAAAEADYA6gwAAAcAPAALAAYJYhjLFQCRAQZoDAAACABCAGkMAAAHAEoAawwAAAcAOABqDAAABgAzAGwMAAAEADYA6gwAAAcAPAAuAAQKfzYAAgsACQliIXsLAMkCAAsACQliIXsLAMkCAAAA.Orgdynamite:BAAALgAECgUJCAAAAA==.',
Oz='Ozzynäter:BAAALgADCgEJAQAAAA==.',
Pa='Paedragon:BAAALgAECgQJCgAAAA==.Paladareian:BAABLgAECn8uAAMFAAkJzh/6BAAbAwloDAAACABGAGkMAAAHAEoAawwAAAcATQBqDAAABAA2AGwMAAAGAFsAbQwAAAQAWgDqDAAABgBhAG4MAAADAGEAbwwAAAEATwAFAAkJzh/6BAAbAwloDAAABwBGAGkMAAAHAEoAawwAAAcATQBqDAAABAA2AGwMAAAGAFsAbQwAAAQAWgDqDAAABgBhAG4MAAADAGEAbwwAAAEATwAQAAEJJQU5ZwEpAAFoDAAAAQANAAAA.Pandalin:BAABLgAECn8WAAIZAAcJMhByQQBnAQdoDAAABAAYAGkMAAAEABUAawwAAAQAKQBqDAAAAwA1AGwMAAADADoAbQwAAAEANgDqDAAAAwAjABkABwkyEHJBAGcBB2gMAAAEABgAaQwAAAQAFQBrDAAABAApAGoMAAADADUAbAwAAAMAOgBtDAAAAQA2AOoMAAADACMAAS4ABAoICQwAAwAAAAA=.',
Pe='Pejbolt:BAAALgAFFAEJAQABLgAFFAYJIQALALEkAA==.Pennywiseit:BAAALgAECgYJBwAAAA==.Percwalker:BAAALgAECgcJDQAAAA==.',
Ph='Phenomenon:BAAALgAECgcJDQAAAA==.',
Pi='Pinheadd:BAAALgAECgUJDAAAAA==.Pink:BAAALgADCgYJBgAAAA==.',
Pm='Pmsm:BAAALgAECgQJCAAAAA==.',
Po='Powerslavé:BAABLgAECn8cAAQaAAcJSxzDDwC4AQdoDAAABABKAGkMAAAFAFAAawwAAAUAVwBqDAAABABVAGwMAAAEAFQAbQwAAAEALADqDAAABQA+ABoABwlcGsMPALgBB2gMAAADAEkAaQwAAAQAUABrDAAABAA6AGoMAAADAFUAbAwAAAMAVABtDAAAAQAsAOoMAAACAD4AGAAGCXQbbhcAaQEGaAwAAAEASgBpDAAAAQBOAGsMAAABAFcAagwAAAEASwBsDAAAAQA+AOoMAAABADAADAABCYIOK4UAMgAB6gwAAAIAJQABLgAFFAMJCwAEANMXAA==.',
Pr='Priestitoot:BAAALgAECgUJCwAAAA==.',
Pu='Puffpuffpass:BAAALgAECgEJAgAAAA==.Pumkinhead:BAAALgAECgMJAwAAAA==.',
Qu='Quadzilla:BAAALgAECgEJAQAAAA==.Qudenos:BAAALgAECggJDAAAAA==.',
['Qû']='Qûeenpin:BAAALgADCgEJAQAAAA==.',
Ra='Ragous:BAAALgAECgYJEgAAAA==.Raiden:BAABLgAECn8eAAIQAAYJJAv0qQD8AAZoDAAABgAaAGkMAAAHACgAawwAAAYAFgBqDAAABAAZAGwMAAAEABsA6gwAAAMAGAAQAAYJJAv0qQD8AAZoDAAABgAaAGkMAAAHACgAawwAAAYAFgBqDAAABAAZAGwMAAAEABsA6gwAAAMAGAAAAA==.Ralister:BAAALgAECgIJAgAAAA==.Rathis:BAAALgADCgUJBgAAAA==.Ravenkiss:BAAALgAECgMJAwAAAA==.',
Re='Reazzecxan:BAAALgAECgMJAwAAAA==.Reeses:BAAALgADCgYJBgAAAA==.Renniel:BAAALgAECgcJDQAAAA==.Retropâlly:BAAALgAECgIJAgAAAA==.Revoker:BAAALgADCgcJFQABLgAECggJDAADAAAAAA==.Rexarg:BAAALgAECgYJDgAAAA==.',
Rh='Rhysänd:BAAALgAECgQJBwAAAA==.',
Ri='Rielz:BAAALgAECgEJAQAAAA==.',
Ro='Rockbitér:BAAALgAECgMJAwABLgAFFAQJCwAJAI8XAA==.Rockbìter:BAACLgAFFH8LAAIJAAQJjxegFgAxAQRoDAAAAwBSAGkMAAADADwAawwAAAEAIgDqDAAABAA/AAkABAmPF6AWADEBBGgMAAADAFIAaQwAAAMAPABrDAAAAQAiAOoMAAAEAD8ALgAECn8YAAMJAAgJzh/zCwCTAgAJAAgJzh/zCwCTAgAkAAEJAAD0mAAAAAAAAA==.Rockthyr:BAAALgAECgQJBQABLgAFFAQJCwAJAI8XAA==.Rojas:BAAALgAECgcJEwAAAA==.',
['Ré']='Réåper:BAABLgAECn8aAAIQAAgJuxAwZwB3AQhoDAAABAARAGkMAAACADMAawwAAAMADwBqDAAAAwAfAGwMAAAEAC0AbQwAAAIAIgDqDAAABQA2AG4MAAADAFAAEAAICbsQMGcAdwEIaAwAAAQAEQBpDAAAAgAzAGsMAAADAA8AagwAAAMAHwBsDAAABAAtAG0MAAACACIA6gwAAAUANgBuDAAAAwBQAAAA.',
['Rö']='Römana:BAABLgAECn8jAAITAAgJTg5MUAB2AQhoDAAABwAyAGkMAAAGACsAawwAAAYAJQBqDAAABQBbAGwMAAAEACgAbQwAAAEADQDqDAAABQBAAG4MAAABAAYAEwAICU4OTFAAdgEIaAwAAAcAMgBpDAAABgArAGsMAAAGACUAagwAAAUAWwBsDAAABAAoAG0MAAABAA0A6gwAAAUAQABuDAAAAQAGAAAA.',
Sa='Saaran:BAAALgAECggJDAAAAA==.Sandoriel:BAAALgADCgkJGwAAAA==.Sapmedaddy:BAAALgAECgEJAgABLgAECgUJBQADAAAAAA==.Sathenasand:BAAALgAECgYJEgABLgAFFAQJDwAKANESAA==.',
Sc='Scamps:BAAALgAECgEJAQAAAA==.Scarellia:BAAALgAECgUJCwAAAA==.Scarly:BAAALgAECgEJAQAAAA==.Scorch:BAABLgAECn8xAAIEAAkJ0CGWCQARAwloDAAACABbAGkMAAAHAFgAawwAAAgAWwBqDAAABgBQAGwMAAAGAF0AbQwAAAMAQwDqDAAABwBWAG4MAAADAFEAbwwAAAEAXAAEAAkJ0CGWCQARAwloDAAACABbAGkMAAAHAFgAawwAAAgAWwBqDAAABgBQAGwMAAAGAF0AbQwAAAMAQwDqDAAABwBWAG4MAAADAFEAbwwAAAEAXAAAAA==.',
Sh='Shadowkirby:BAAALgADCgUJBQAAAA==.Shadowkushh:BAAALgAECgYJEgAAAA==.Shamwowolio:BAAALgAECgUJBgABLgAFFAIJBgABADADAA==.Shatterfrost:BAABLgAECn8oAAMlAAYJ+RqGCgA1AQZoDAAABwBFAGkMAAAHAFAAawwAAAgAQQBqDAAACABUAGwMAAAEADAA6gwAAAYAUgAEAAYJABkreQBfAQZoDAAABQBFAGkMAAAHAFAAawwAAAcAQQBqDAAABgBUAGwMAAADADAA6gwAAAQAOAAlAAUJIBOGCgA1AQVoDAAAAgAvAGsMAAABADkAagwAAAIAQABsDAAAAQAIAOoMAAACAFIAAAA=.Shayd:BAAALgAECggJDAAAAA==.Shiggles:BAAALgAECgQJBAABLgAECgcJBwADAAAAAA==.Shirraz:BAAALgADCgkJEQAAAA==.',
Si='Sicksdeep:BAACLgAFFH8LAAMYAAMJtQgBGQC8AANoDAAABAAMAGkMAAAFAB0A6gwAAAIAGAAYAAMJOwgBGQC8AANoDAAAAwAMAGkMAAAFAB0A6gwAAAEAFAAMAAIJXgUvPQBEAAJoDAAAAQADAOoMAAABABgALgAECn8dAAMYAAgJ3Bb4CQAKAgAYAAgJ3Bb4CQAKAgAMAAUJbQmdbAAEAQAAAA==.Silverpaws:BAAALgADCgQJBAAAAA==.Silverstorm:BAABLgAECn8VAAITAAYJoA4KcAAlAQZoDAAABAA3AGkMAAAEAC4AawwAAAQAKABqDAAAAwAdAGwMAAADABkA6gwAAAMAEwATAAYJoA4KcAAlAQZoDAAABAA3AGkMAAAEAC4AawwAAAQAKABqDAAAAwAdAGwMAAADABkA6gwAAAMAEwAAAA==.Sister:BAAALgAECgEJAQAAAA==.',
Sk='Skelmirson:BAAALgAECgYJCwAAAA==.Skewpin:BAAALgADCgQJBAAAAA==.Skoomauser:BAAALgAECgQJBAAAAA==.Skÿe:BAABLgAECn8uAAIRAAkJ9yGjAQDdAgloDAAABgBPAGkMAAAGAFoAawwAAAYAYABqDAAABQBfAGwMAAAHAFcAbQwAAAQAWwDqDAAABwBYAG4MAAAEAFAAbwwAAAEAUAARAAkJ9yGjAQDdAgloDAAABgBPAGkMAAAGAFoAawwAAAYAYABqDAAABQBfAGwMAAAHAFcAbQwAAAQAWwDqDAAABwBYAG4MAAAEAFAAbwwAAAEAUAAAAA==.',
Sl='Slamma:BAACLgAFFH8mAAIMAAYJAiY2AQApAgZoDAAACABjAGkMAAAHAGIAawwAAAYAWgBqDAAABgBfAGwMAAAEAGIA6gwAAAcAYwAMAAYJAiY2AQApAgZoDAAACABjAGkMAAAHAGIAawwAAAYAWgBqDAAABgBfAGwMAAAEAGIA6gwAAAcAYwAuAAQKf0EAAwwACQnCJjUAAPgDAAwACQnCJjUAAPgDABgAAQn9JZ9DAHAAAAAA.Slammahd:BAAALgAECgkJCgABLgAFFAYJJgAMAAImAA==.Slicedbread:BAACLgAFFH8QAAIJAAYJ5BHjDgCSAQZoDAAABAA0AGkMAAADACsAawwAAAIAEgBqDAAAAgBJAGwMAAACACkA6gwAAAMALQAJAAYJ5BHjDgCSAQZoDAAABAA0AGkMAAADACsAawwAAAIAEgBqDAAAAgBJAGwMAAACACkA6gwAAAMALQAuAAQKfyQABAkACQnqHDgOAHQCAAkACAl7HTgOAHQCACYABgkNIYUiAG4BACQAAQniF4txAEAAAAEuAAUUBgkUAAUA/BwA.',
Sm='Smokadaganga:BAAALgAFFAIJAgAAAA==.',
Sn='Snoball:BAAALgAECgIJAgAAAA==.',
So='Solarean:BAAALgADCgQJBwAAAA==.Solidarity:BAAALgAECgYJDAAAAA==.Sols:BAACLgAFFH8LAAIEAAMJ0xcXWAAEAQNoDAAABAA6AGkMAAAEAD0A6gwAAAMAPwAEAAMJ0xcXWAAEAQNoDAAABAA6AGkMAAAEAD0A6gwAAAMAPwAuAAQKfycAAgQACQkGH10NAO8CAAQACQkGH10NAO8CAAAA.Sorceroar:BAAALgADCgYJCQAAAA==.Sowet:BAAALgADCgQJBgAAAA==.',
Sp='Sparcyy:BAAALgADCgYJBgAAAA==.Spatula:BAAALgAECgUJEAAAAA==.Speoghii:BAAALgAECgYJEgAAAA==.Spiffjbug:BAAALgADCggJGwAAAA==.Spifftreebug:BAAALgAECgcJEQAAAA==.',
St='Starhoof:BAAALgADCgcJDQAAAA==.Starshine:BAAALgAECgMJAwAAAA==.Steelerschic:BAABLgAECn8WAAIgAAYJ5QPQVgCjAAZoDAAABQAIAGkMAAAFAAoAawwAAAMACQBqDAAAAwAKAGwMAAACAAwA6gwAAAQACQAgAAYJ5QPQVgCjAAZoDAAABQAIAGkMAAAFAAoAawwAAAMACQBqDAAAAwAKAGwMAAACAAwA6gwAAAQACQAAAA==.Stillfrazier:BAABLgAECn8eAAQBAAgJMQreKQBMAQhoDAAABQAZAGkMAAAEACEAawwAAAQALQBqDAAABQAcAGwMAAAFAB8AbQwAAAIAEADqDAAAAwANAG4MAAACAA8AAQAICTEK3ikATAEIaAwAAAIAGQBpDAAAAgAhAGsMAAACAC0AagwAAAIAHABsDAAAAgAfAG0MAAACABAA6gwAAAIADQBuDAAAAQAPAAIABwnhCh81APsAB2gMAAACABkAaQwAAAIAGQBrDAAAAgAcAGoMAAADABsAbAwAAAIAEgDqDAAAAQAvAG4MAAABABUABwACCXUEJXUAVQACaAwAAAEACQBsDAAAAQANAAAA.Stormleader:BAAALgADCgYJBgAAAA==.',
Su='Subcintus:BAAALgAECgcJDQAAAA==.Subterfuge:BAAALgAECgEJAQAAAA==.Surge:BAAALgAECgUJCAAAAA==.',
Sv='Svarog:BAAALgAECgYJEAABLgAFFAMJCwAMAG8aAA==.',
['Sö']='Söphie:BAAALgAECgkJDwAAAA==.',
Ta='Tainema:BAABLgAECn8aAAIQAAYJ8xMRiwAwAQZoDAAABgApAGkMAAAGADUAawwAAAUAMQBqDAAAAwBIAGwMAAACADYA6gwAAAQAOQAQAAYJ8xMRiwAwAQZoDAAABgApAGkMAAAGADUAawwAAAUAMQBqDAAAAwBIAGwMAAACADYA6gwAAAQAOQAAAA==.Talangi:BAAALgAECgkJBwAAAA==.Tallow:BAAALgADCgQJBAAAAA==.Tarheelpally:BAAALgAECgkJBQAAAA==.Taurriel:BAABLgAECn8mAAITAAkJyx2lFQByAgloDAAABgBKAGkMAAAGAEgAawwAAAYASQBqDAAABQBDAGwMAAAFAFcAbQwAAAIAQQDqDAAABQBUAG4MAAACAFAAbwwAAAEARwATAAkJyx2lFQByAgloDAAABgBKAGkMAAAGAEgAawwAAAYASQBqDAAABQBDAGwMAAAFAFcAbQwAAAIAQQDqDAAABQBUAG4MAAACAFAAbwwAAAEARwAAAA==.Tazzm:BAAALgAECgYJBgAAAA==.',
Te='Teranok:BAABLgAECn8gAAIkAAkJsSDfBQDIAgloDAAABABVAGkMAAAEAFcAawwAAAUAXABqDAAABABZAGwMAAACAFgAbQwAAAMATQDqDAAABQBhAG4MAAADAFUAbwwAAAIANwAkAAkJsSDfBQDIAgloDAAABABVAGkMAAAEAFcAawwAAAUAXABqDAAABABZAGwMAAACAFgAbQwAAAMATQDqDAAABQBhAG4MAAADAFUAbwwAAAIANwAAAA==.Terozon:BAAALgAECgYJCwAAAA==.',
Th='Tharianrex:BAABLgAECn8vAAMSAAkJ6CS8AAA5AwloDAAABwBhAGkMAAAHAGEAawwAAAcAYgBqDAAABABeAGwMAAADAGAAbQwAAAQAYgDqDAAABwBiAG4MAAAFAGMAbwwAAAMARAASAAkJ6CS8AAA5AwloDAAABwBhAGkMAAAHAGEAawwAAAcAYgBqDAAABABeAGwMAAADAGAAbQwAAAQAYgDqDAAABgBiAG4MAAAFAGMAbwwAAAMARAAZAAEJMgL2vQAdAAHqDAAAAQAFAAAA.Theacused:BAAALgAECgQJCAAAAA==.Thedreadwolf:BAAALgAECgMJAwAAAA==.Them:BAAALgAECggJEwAAAA==.Thoir:BAACLgAFFH8qAAIZAAYJLyEjAQD/AQZoDAAACQBaAGkMAAAIAF8AawwAAAcAYwBqDAAABgAiAGwMAAAEAFwA6gwAAAgAYAAZAAYJLyEjAQD/AQZoDAAACQBaAGkMAAAIAF8AawwAAAcAYwBqDAAABgAiAGwMAAAEAFwA6gwAAAgAYAAuAAQKf0AAAhkACQl3JPwAAJgDABkACQl3JPwAAJgDAAEuAAUUBgkqAAcAEAMA.Thorodinson:BAAALgADCgYJBgAAAA==.Thyrus:BAAALgADCgcJBwAAAA==.',
Ti='Tiaeda:BAAALgADCgEJAQAAAA==.Tickells:BAABLgAECn8yAAMCAAkJcwn2HACqAQloDAAABwAfAGkMAAAHABUAawwAAAcAGQBqDAAABgAjAGwMAAAGAB4AbQwAAAQAEgDqDAAABwAXAG4MAAAEABAAbwwAAAIADgACAAkJcwn2HACqAQloDAAAAwAfAGkMAAADABUAawwAAAMAGQBqDAAAAgAjAGwMAAACAB4AbQwAAAEAEgDqDAAAAwAXAG4MAAABABAAbwwAAAEADgABAAkJIw1RHQCmAQloDAAABAAkAGkMAAAEABkAawwAAAQAHwBqDAAABAAwAGwMAAAEACYAbQwAAAMAIwDqDAAABAA8AG4MAAADABwAbwwAAAEACwAAAA==.Tipsylorcet:BAABLgAECn8nAAImAAgJuxscEQAJAghoDAAABgBdAGkMAAAGAFIAawwAAAYASgBqDAAABQBCAGwMAAAEAEIAbQwAAAIAJgDqDAAACABPAG4MAAACAD0AJgAICbsbHBEACQIIaAwAAAYAXQBpDAAABgBSAGsMAAAGAEoAagwAAAUAQgBsDAAABABCAG0MAAACACYA6gwAAAgATwBuDAAAAgA9AAAA.Tirohunt:BAAALgAECgYJCwAAAA==.',
Tk='Tkbear:BAAALgADCgUJBAAAAA==.',
Tr='Tricktìckler:BAAALgAECgQJCgAAAA==.Trinestia:BAAALgADCgUJDQAAAA==.Truggrug:BAAALgADCgEJAQAAAA==.Truthstrike:BAAALgADCgEJAQAAAA==.Trvll:BAAALgADCgEJAQAAAA==.',
Tu='Tubylumpkins:BAAALgAECggJEgAAAA==.Tulay:BAAALgADCgQJBAABLgADCggJFAADAAAAAA==.Turiell:BAAALgAECgQJBwAAAA==.',
Ty='Tybird:BAABLgAECn8fAAIbAAgJzSLTBAAnAghoDAAABgBdAGkMAAAFAFoAawwAAAUAXABqDAAAAwBbAGwMAAADAE4AbQwAAAMAWQDqDAAAAwBaAG4MAAADAFgAGwAICc0i0wQAJwIIaAwAAAYAXQBpDAAABQBaAGsMAAAFAFwAagwAAAMAWwBsDAAAAwBOAG0MAAADAFkA6gwAAAMAWgBuDAAAAwBYAAAA.Tyllimath:BAAALgADCgEJAQABLgAECggJHAAFAOcUAA==.',
['Tø']='Tøuchmeeh:BAAALgAECgkJDQAAAA==.',
Uf='Ufug:BAAALgADCgEJAQAAAA==.',
Ul='Ulsull:BAAALgADCgkJGAAAAA==.Ultima:BAAALgADCgkJEwAAAA==.Ulymage:BAAALgADCgUJBQABLgAFFAYJKgABAGUjAA==.Ulyssi:BAACLgAFFH8qAAIBAAYJZSP3AgAJAgZoDAAACQBfAGkMAAAIAGAAawwAAAcAUwBqDAAABgBhAGwMAAAEAFUA6gwAAAgAWwABAAYJZSP3AgAJAgZoDAAACQBfAGkMAAAIAGAAawwAAAcAUwBqDAAABgBhAGwMAAAEAFUA6gwAAAgAWwAuAAQKfz8AAgEACQmYJd0BAEQDAAEACQmYJd0BAEQDAAAA.',
['Uñ']='Uñàble:BAAALgADCgcJBwAAAA==.',
Va='Vadazzle:BAAALgADCgEJAQAAAA==.Valethara:BAAALgAECgEJAQAAAA==.Valkyrr:BAAALgAECgcJDgAAAA==.Valthorin:BAAALgADCgUJCAAAAA==.Vandagylon:BAAALgADCgcJCwAAAA==.Vaniillalate:BAAALgADCgUJCAAAAA==.',
Ve='Velanir:BAAALgAECgQJBQAAAA==.Velkron:BAAALgAECgYJCQAAAA==.Ven:BAABLgAECn8rAAIBAAgJVAhMLAA9AQhoDAAABgAcAGkMAAAGABYAawwAAAYAEABqDAAABQAfAGwMAAAGABQAbQwAAAIAFADqDAAACQARAG4MAAADABUAAQAICVQITCwAPQEIaAwAAAYAHABpDAAABgAWAGsMAAAGABAAagwAAAUAHwBsDAAABgAUAG0MAAACABQA6gwAAAkAEQBuDAAAAwAVAAAA.Venturecap:BAAALgAFFAEJAQAAAA==.Verxina:BAABLgAECn8dAAInAAgJSyLOCwBBAghoDAAABABfAGkMAAAEAFgAawwAAAQAWQBqDAAAAwBfAGwMAAACAE4AbQwAAAIARgDqDAAABwBgAG4MAAADAF8AJwAICUsizgsAQQIIaAwAAAQAXwBpDAAABABYAGsMAAAEAFkAagwAAAMAXwBsDAAAAgBOAG0MAAACAEYA6gwAAAcAYABuDAAAAwBfAAAA.',
Vi='Viltrumite:BAAALgAECgkJCwAAAA==.',
Vl='Vlayne:BAAALgADCgMJAwAAAA==.',
Vo='Voidedkushh:BAAALgAECgYJDgAAAA==.Vondeuce:BAAALgADCgYJBgAAAA==.Voroq:BAAALgAECgIJBQAAAA==.',
Vu='Vullrog:BAABLgAECn8mAAIRAAgJfhafDABjAQhoDAAABwBOAGkMAAAGAFMAawwAAAYATQBqDAAABwBXAGwMAAAFAEQAbQwAAAIAKwDqDAAABAAhAG4MAAABABEAEQAICX4WnwwAYwEIaAwAAAcATgBpDAAABgBTAGsMAAAGAE0AagwAAAcAVwBsDAAABQBEAG0MAAACACsA6gwAAAQAIQBuDAAAAQARAAAA.',
Wa='Warvein:BAAALgAECgEJAQAAAA==.',
We='Weehunt:BAABLgAECn8bAAITAAgJXhqAMADjAQhoDAAABQBCAGkMAAAEAFoAawwAAAMATABqDAAAAwAyAGwMAAADAEkAbQwAAAIAHADqDAAABgA3AG4MAAABAFIAEwAICV4agDAA4wEIaAwAAAUAQgBpDAAABABaAGsMAAADAEwAagwAAAMAMgBsDAAAAwBJAG0MAAACABwA6gwAAAYANwBuDAAAAQBSAAAA.',
Wh='Whez:BAAALgAECgUJBgAAAA==.',
Wi='Wicka:BAABLgAECn82AAIZAAgJwiQNBQAyAwhoDAAACQBjAGkMAAAIAGEAawwAAAgAYQBqDAAABwBfAGwMAAAGAF0AbQwAAAMAVADqDAAACABjAG4MAAAFAFYAGQAICcIkDQUAMgMIaAwAAAkAYwBpDAAACABhAGsMAAAIAGEAagwAAAcAXwBsDAAABgBdAG0MAAADAFQA6gwAAAgAYwBuDAAABQBWAAAA.Widowfang:BAAALgAECgYJCwAAAA==.Wikka:BAAALgAECgYJEQAAAA==.Wildriver:BAABLgAECn8mAAIeAAgJUh8DDQDLAghoDAAABwBVAGkMAAAHAF8AawwAAAcAYQBqDAAABABWAGwMAAADAFcAbQwAAAIAOgDqDAAABgBOAG4MAAACADMAHgAICVIfAw0AywIIaAwAAAcAVQBpDAAABwBfAGsMAAAHAGEAagwAAAQAVgBsDAAAAwBXAG0MAAACADoA6gwAAAYATgBuDAAAAgAzAAAA.',
Xa='Xaehyun:BAACLgAFFH8qAAMkAAYJfSS1AgC9AQZoDAAACQBjAGkMAAAIAGMAawwAAAcAXgBqDAAABgBcAGwMAAAEAFAA6gwAAAgAXAAkAAQJuSW1AgC9AQRoDAAACQBjAGkMAAAIAGMAawwAAAcAXgDqDAAACABcAAkAAgnKJCohAM8AAmoMAAAGAF8AbAwAAAQAXQAuAAQKf0MAAyQACQnPJhAAAAoEACQACQnPJhAAAAoEAAkABQlEHVEhAKkBAAAA.Xalley:BAAALgADCgQJBAAAAA==.Xandrelar:BAABLgAECn8cAAQdAAYJiiCPCACvAQZoDAAABgBPAGkMAAAFAFoAawwAAAUAVABqDAAAAwAnAGwMAAAEAE4A6gwAAAUAUgAdAAUJiiCPCACvAQVoDAAAAQBPAGkMAAABAFoAawwAAAIAVABsDAAABABOAOoMAAACAFIACAAFCYQdLCoAcwEFaAwAAAEATQBpDAAAAgA9AGsMAAACAFEAagwAAAIAJwDqDAAAAwBSAAsABAmhErCbAOEABGgMAAAEADgAaQwAAAIAPABrDAAAAQAaAGoMAAABAB4AAS4ABAoICQwAAwAAAAA=.Xanni:BAABLgAECn8zAAMgAAgJoAy7MAA/AQhoDAAABwAWAGkMAAAHAEEAawwAAAcAPgBqDAAABQAiAGwMAAAHABwAbQwAAAcAEQDqDAAABwARAG4MAAAEAAoAIAAICaAMuzAAPwEIaAwAAAYAFgBpDAAABgBBAGsMAAAGAD4AagwAAAUAIgBsDAAABwAcAG0MAAAHABEA6gwAAAcAEQBuDAAABAAKABkAAwmRA3uJAG4AA2gMAAABAAQAaQwAAAEABgBrDAAAAQAQAAAA.',
Xe='Xellorr:BAAALgAECgYJDAAAAA==.',
Xm='Xmrpdk:BAACLgAFFH8qAAIGAAYJ9SBCBADgAQZoDAAACQBQAGkMAAAIAFcAawwAAAcAWQBqDAAABgArAGwMAAAEAFMA6gwAAAgAUAAGAAYJ9SBCBADgAQZoDAAACQBQAGkMAAAIAFcAawwAAAcAWQBqDAAABgArAGwMAAAEAFMA6gwAAAgAUAAuAAQKfz8AAgYACQkFI+wCADYDAAYACQkFI+wCADYDAAAA.Xmrpdruid:BAAALgAECgMJAQABLgAFFAYJKgAGAPUgAA==.Xmrpmonk:BAAALgAECgcJEgABLgAFFAYJKgAGAPUgAA==.',
Xo='Xohan:BAABLgAECn8qAAIMAAkJBCAGCgCWAgloDAAABQBcAGkMAAAFAGIAawwAAAUAVgBqDAAABQBRAGwMAAAFAE4AbQwAAAUAWgDqDAAABgBUAG4MAAAEAFIAbwwAAAIAKwAMAAkJBCAGCgCWAgloDAAABQBcAGkMAAAFAGIAawwAAAUAVgBqDAAABQBRAGwMAAAFAE4AbQwAAAUAWgDqDAAABgBUAG4MAAAEAFIAbwwAAAIAKwAAAA==.',
Xy='Xyr:BAAALgADCgEJAQAAAA==.',
Ye='Yelizaveta:BAAALgAECgQJBAAAAA==.',
Yn='Ynotna:BAABLgAECn8eAAITAAkJ0hSaJAAYAgloDAAABAA8AGkMAAAEAEoAawwAAAQASgBqDAAABAA2AGwMAAAEAEIAbQwAAAIAMgDqDAAABABEAG4MAAACAAUAbwwAAAIAGgATAAkJ0hSaJAAYAgloDAAABAA8AGkMAAAEAEoAawwAAAQASgBqDAAABAA2AGwMAAAEAEIAbQwAAAIAMgDqDAAABABEAG4MAAACAAUAbwwAAAIAGgAAAA==.',
Yo='Yoyiek:BAAALgAECgEJAgAAAA==.',
Yu='Yukí:BAAALgADCggJFgAAAA==.',
Za='Zacygos:BAACLgAFFH8qAAIXAAYJUR9bBAArAgZoDAAACQBYAGkMAAAIAFUAawwAAAcAVABqDAAABgA2AGwMAAAEAFIA6gwAAAgAVgAXAAYJUR9bBAArAgZoDAAACQBYAGkMAAAIAFUAawwAAAcAVABqDAAABgA2AGwMAAAEAFIA6gwAAAgAVgAuAAQKf0AAAxcACQkII98BAEQDABcACQkII98BAEQDABUABQkeHeUOAPIAAAAA.Zamosc:BAAALgADCgEJAQABLgAFFAMJCwAMAG8aAA==.Zanne:BAACLgAFFH8QAAIRAAQJ4RgqDAA5AQRoDAAABgBRAGkMAAAFAEUAawwAAAEAHQDqDAAABABKABEABAnhGCoMADkBBGgMAAAGAFEAaQwAAAUARQBrDAAAAQAdAOoMAAAEAEoALgAECn8eAAIRAAgJTB38GQBaAgARAAgJTB38GQBaAgAAAA==.Zarellia:BAAALgADCgIJAgAAAA==.Zarthul:BAAALgAECgYJBgAAAA==.',
Zb='Zbämfz:BAAALgAECgEJAQABLgAECgQJCAADAAAAAA==.',
Ze='Zehara:BAABLgAECn8aAAMCAAcJLweZMQAXAQdoDAAABAAPAGkMAAAFAA4AawwAAAQAJgBqDAAAAwAJAGwMAAAFAAQA6gwAAAMAHwBuDAAAAgAPAAIABwkvB5kxABcBB2gMAAADAA8AaQwAAAUADgBrDAAABAAmAGoMAAADAAkAbAwAAAUABADqDAAAAwAfAG4MAAACAA8AAQABCQsBenkAEwABaAwAAAEAAgAAAA==.Zenovesh:BAAALgAECgEJAQAAAA==.Zerraphos:BAAALgADCgcJCgAAAA==.Zezima:BAAALgAECgUJCAAAAA==.',
Zh='Zhaolin:BAAALgADCgcJDAAAAA==.',
Zl='Zlot:BAECLgAFFH8qAAQTAAYJASJ0AwBmAQZoDAAACQBhAGkMAAAIAGMAawwAAAcASwBqDAAABgBFAGwMAAAEAFwA6gwAAAgARgATAAUJgSF0AwBmAQVoDAAABQBhAGkMAAAIAGMAawwAAAUASwBqDAAAAwBFAOoMAAAIAEYAEQAECW4TJxgA0wAEaAwAAAMAKwBrDAAAAQANAGoMAAADABwAbAwAAAQAXAAnAAIJhQ6MHgCeAAJoDAAAAQArAGsMAAABAB8ALgAECn9AAAQTAAkJTiZBBAAoAwATAAkJMiZBBAAoAwARAAcJQCA2GABrAgAnAAIJhBoaPQCbAAAAAA==.',
Zo='Zoblin:BAAALgAECgUJBQAAAA==.',
['Ör']='Öriana:BAABLgAECn8WAAMOAAgJpgxPDABCAQhoDAAABAAnAGkMAAAEACwAawwAAAQAHwBqDAAAAwAYAGwMAAABADgAbQwAAAEACQDqDAAABAAcAG4MAAABABAADgAICaYMTwwAQgEIaAwAAAIAJwBpDAAAAgAsAGsMAAACAB8AagwAAAMAGABsDAAAAQA4AG0MAAABAAkA6gwAAAQAHABuDAAAAQAQAA0AAwnoBjnUAHkAA2gMAAACAA8AaQwAAAIADgBrDAAAAgAXAAAA.',
['Úl']='Úlfa:BAAALgAECggJEwAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
