local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Hunter-Marksmanship','Unknown-Unknown','DeathKnight-Frost','Monk-Mistweaver','Priest-Holy','Paladin-Holy','Druid-Restoration','Druid-Balance','DemonHunter-Devourer','Warrior-Protection','Paladin-Retribution','Priest-Shadow','Warlock-Demonology','Hunter-Survival','Warlock-Destruction','Shaman-Elemental','Mage-Frost','Shaman-Restoration','DeathKnight-Unholy','DeathKnight-Blood','Priest-Discipline','Evoker-Augmentation','Warrior-Arms','Warrior-Fury','Evoker-Preservation','Hunter-BeastMastery','Rogue-Assassination','DemonHunter-Vengeance','Monk-Brewmaster','Rogue-Outlaw','Monk-Windwalker',}
local provider = {region='US',realm='ThoriumBrotherhood',name='US',type='daily',zone=46,date='2026-05-12',data={Ab='Absolver:BAAALgADCgYJCwAAAA==.',
Ad='Addu:BAAALgADCgYJBgAAAA==.Adiforis:BAAALgADCgYJBgAAAA==.',
Ae='Aeralina:BAABLgAECn8VAAIBAAgJmwl/CwBEAQhoDAAAAwAVAGkMAAADABwAawwAAAMAOQBqDAAAAwAbAGwMAAADAAkAbQwAAAIAEwDqDAAAAwAeAG4MAAABAAUAAQAICZsJfwsARAEIaAwAAAMAFQBpDAAAAwAcAGsMAAADADkAagwAAAMAGwBsDAAAAwAJAG0MAAACABMA6gwAAAMAHgBuDAAAAQAFAAAA.Aerandir:BAAALgAECgYJDwABLgAFFAEJAQACAAAAAA==.Aerwyn:BAAALgAECgYJBgAAAA==.',
Ah='Ahmyra:BAAALgAECgYJDAAAAA==.',
Al='Alessar:BAAALgAECgYJDAAAAA==.Allysson:BAABLgAECn8cAAIDAAcJiw/2CAAwAQdoDAAABgA2AGkMAAAFADUAawwAAAUANQBqDAAABAAaAGwMAAADABsAbQwAAAEAEADqDAAABAAhAAMABwmLD/YIADABB2gMAAAGADYAaQwAAAUANQBrDAAABQA1AGoMAAAEABoAbAwAAAMAGwBtDAAAAQAQAOoMAAAEACEAAAA=.Alyestra:BAAALgAECgUJCwAAAA==.',
An='Animyst:BAACLgAFFH8FAAIEAAMJ+R2gFAAKAQNoDAAAAgBHAGkMAAACAD8A6gwAAAEAXwAEAAMJ+R2gFAAKAQNoDAAAAgBHAGkMAAACAD8A6gwAAAEAXwAuAAQKfzYAAgQACAkGI7YEAOoCAAQACAkGI7YEAOoCAAEuAAQKCQktAAUAnSIA.Anipaltu:BAABLgAECn8WAAIGAAYJzR3DFgDqAQZoDAAABABaAGkMAAAEAFoAawwAAAQALwBqDAAABABIAGwMAAADAEMA6gwAAAMAWQAGAAYJzR3DFgDqAQZoDAAABABaAGkMAAAEAFoAawwAAAQALwBqDAAABABIAGwMAAADAEMA6gwAAAMAWQABLgAECgkJLQAFAJ0iAA==.Aniron:BAAALgAECgYJDgABLgAECgkJLQAFAJ0iAA==.Anirot:BAABLgAECn8tAAIFAAkJnSJiAQBnAwloDAAABwBjAGkMAAAHAGAAawwAAAcAWwBqDAAABgBiAGwMAAAEAF0AbQwAAAUAWwDqDAAABABVAG4MAAAEAFYAbwwAAAEAOAAFAAkJnSJiAQBnAwloDAAABwBjAGkMAAAHAGAAawwAAAcAWwBqDAAABgBiAGwMAAAEAF0AbQwAAAUAWwDqDAAABABVAG4MAAAEAFYAbwwAAAEAOAAAAA==.',
Ap='Aphirym:BAAALgAECgEJAQAAAA==.',
Ar='Aranta:BAABLgAECn8aAAMHAAYJmQ7YRAAVAQZoDAAABQAeAGkMAAAFACMAawwAAAUAKQBqDAAABAAxAGwMAAADACcA6gwAAAQAGgAHAAYJmQ7YRAAVAQZoDAAABAAeAGkMAAAEACMAawwAAAQAKQBqDAAAAwAxAGwMAAACACcA6gwAAAMAGgAIAAYJ9Ak1MADlAAZoDAAAAQAiAGkMAAABACYAawwAAAEAHwBqDAAAAQAvAGwMAAABABAA6gwAAAEABgAAAA==.',
As='Astren:BAAALgAECgEJAQAAAA==.Asynsia:BAABLgAECn8hAAIJAAkJZSFuBwDGAgloDAAABQBhAGkMAAAFAGAAawwAAAUAWABqDAAABABeAGwMAAADAFcAbQwAAAMAUADqDAAABABdAG4MAAADADkAbwwAAAEAUQAJAAkJZSFuBwDGAgloDAAABQBhAGkMAAAFAGAAawwAAAUAWABqDAAABABeAGwMAAADAFcAbQwAAAMAUADqDAAABABdAG4MAAADADkAbwwAAAEAUQAAAA==.',
Av='Avamani:BAAALgADCgkJCQAAAA==.',
Az='Azulmoon:BAAALgAECgYJBgAAAA==.',
Ba='Balrogg:BAAALgADCgcJBwAAAA==.Banashain:BAAALgADCgEJAgAAAA==.Bartholomew:BAABLgAECn8gAAIEAAkJvhu2BQDOAgloDAAABQBIAGkMAAAFAEoAawwAAAUAPgBqDAAABABMAGwMAAADAFoAbQwAAAIANwDqDAAABABKAG4MAAADAEcAbwwAAAEAPQAEAAkJvhu2BQDOAgloDAAABQBIAGkMAAAFAEoAawwAAAUAPgBqDAAABABMAGwMAAADAFoAbQwAAAIANwDqDAAABABKAG4MAAADAEcAbwwAAAEAPQAAAA==.Bartno:BAAALgAECgIJAQAAAA==.',
Be='Beefed:BAAALgADCgIJAgAAAA==.Bessie:BAAALgADCgIJAgAAAA==.',
Bi='Bienfaiseur:BAABLgAECn8eAAIFAAgJASRTAgA1AwhoDAAABgBjAGkMAAAFAGAAawwAAAUAXwBqDAAABABiAGwMAAAEAGIAbQwAAAEAVADqDAAABABgAG4MAAABAEIABQAICQEkUwIANQMIaAwAAAYAYwBpDAAABQBgAGsMAAAFAF8AagwAAAQAYgBsDAAABABiAG0MAAABAFQA6gwAAAQAYABuDAAAAQBCAAAA.',
Bl='Bladez:BAAALgAECgEJAQAAAA==.',
Bo='Boombawks:BAAALgADCgUJBQABLgADCgYJAgACAAAAAA==.Boryndin:BAABLgAECn8VAAIKAAgJFBcUDAC0AQhoDAAABABHAGkMAAADAFAAawwAAAMANABqDAAAAgBAAGwMAAACADEAbQwAAAEAOgDqDAAABQBQAG4MAAABABUACgAICRQXFAwAtAEIaAwAAAQARwBpDAAAAwBQAGsMAAADADQAagwAAAIAQABsDAAAAgAxAG0MAAABADoA6gwAAAUAUABuDAAAAQAVAAAA.',
Br='Brad:BAAALgADCgIJAgAAAA==.Breadburn:BAAALgADCggJCAAAAA==.Breezybb:BAABLgAECn8zAAILAAkJfRcsOgA6AgloDAAACABEAGkMAAAHAFQAawwAAAcATgBqDAAABAAnAGwMAAAGAEgAbQwAAAUAKADqDAAACAA3AG4MAAAEAB8AbwwAAAIAMQALAAkJfRcsOgA6AgloDAAACABEAGkMAAAHAFQAawwAAAcATgBqDAAABAAnAGwMAAAGAEgAbQwAAAUAKADqDAAACAA3AG4MAAAEAB8AbwwAAAIAMQAAAA==.',
Ca='Camhawk:BAAALgADCgkJCQAAAA==.Catastrophe:BAAALgAECgEJAQAAAA==.',
Ce='Cearylin:BAAALgADCgcJEwAAAA==.Cering:BAAALgAECgYJBgAAAA==.',
Ch='Cherypoptart:BAABLgAECn8WAAIMAAcJKyI8CABfAgdoDAAABQBgAGkMAAAEAGAAawwAAAQAWwBqDAAAAwBiAGwMAAACAFcAbQwAAAEAPADqDAAAAwBdAAwABwkrIjwIAF8CB2gMAAAFAGAAaQwAAAQAYABrDAAABABbAGoMAAADAGIAbAwAAAIAVwBtDAAAAQA8AOoMAAADAF0AAAA=.Chrismeister:BAAALgAECgMJBgAAAA==.',
Co='Codah:BAAALgAECgEJAgAAAA==.Corbenik:BAAALgAECgIJBAABLgAECgcJGAANAPEHAA==.',
Cr='Creel:BAAALgADCgYJBgAAAA==.Crettephal:BAEALgAECgIJAwAAAA==.',
['Cä']='Cähira:BAAALgADCgUJBQABLgADCgYJCQACAAAAAA==.',
Da='Daellan:BAAALgAECgMJBAAAAA==.Dainaira:BAAALgAECgYJCwAAAA==.Daisia:BAABLgAECn8WAAIOAAYJGQcRIwD/AAZoDAAABQAgAGkMAAAFABMAawwAAAUAEABqDAAAAwAbAGwMAAACAAgA6gwAAAIADgAOAAYJGQcRIwD/AAZoDAAABQAgAGkMAAAFABMAawwAAAUAEABqDAAAAwAbAGwMAAACAAgA6gwAAAIADgAAAA==.Dalarrong:BAAALgAECgIJAgAAAA==.Dasteaire:BAAALgAECgMJBgAAAA==.',
De='Deathdealler:BAAALgAECgEJAQAAAA==.Demonicadhd:BAAALgAECgYJEwAAAA==.Demonsmind:BAABLgAECn8VAAMNAAcJBw+VawAEAQdoDAAAAwAxAGkMAAADACoAawwAAAMAJwBqDAAABAAnAGwMAAADACcA6gwAAAQAMgBuDAAAAQAIAA0ABgn0DJVrAAQBBmgMAAADADEAaQwAAAMAKgBrDAAAAwAnAGoMAAABACcA6gwAAAIAGQBuDAAAAQAIAA8AAwmqES5BALAAA2oMAAADACAAbAwAAAMAJwDqDAAAAgAyAAAA.Derien:BAABLgAECn8fAAIKAAgJ9BbnEAD6AQhoDAAABABJAGkMAAAFAFMAawwAAAUAPABqDAAABAA/AGwMAAADAC4AbQwAAAQAMQDqDAAAAwA7AG4MAAADACUACgAICfQW5xAA+gEIaAwAAAQASQBpDAAABQBTAGsMAAAFADwAagwAAAQAPwBsDAAAAwAuAG0MAAAEADEA6gwAAAMAOwBuDAAAAwAlAAAA.Derienfu:BAAALgAECgYJBgAAAA==.Dezin:BAAALgADCgUJBQAAAA==.',
Di='Dinkeldorf:BAAALgAECgMJBAABLgAECggJEAACAAAAAA==.',
Dk='Dkerien:BAAALgAECggJCAAAAA==.',
Do='Donkeyteeth:BAABLgAECn8XAAIQAAgJHA34IwBKAQhoDAAAAwAnAGkMAAADABMAawwAAAQAGgBqDAAABAAzAGwMAAAEACgAbQwAAAEAIwDqDAAAAwAqAG4MAAABAB4AEAAICRwN+CMASgEIaAwAAAMAJwBpDAAAAwATAGsMAAAEABoAagwAAAQAMwBsDAAABAAoAG0MAAABACMA6gwAAAMAKgBuDAAAAQAeAAAA.Downtownbuu:BAAALgADCgcJDAAAAA==.',
Dr='Dracarian:BAAALgADCgMJAwAAAA==.Dracorz:BAAALgAECgUJCgAAAA==.Dru:BAAALgADCgcJBwAAAA==.Drywater:BAABLgAECn8XAAIRAAYJgQmrjgAJAQZoDAAABAARAGkMAAAFABQAawwAAAQADwBqDAAAAwAUAGwMAAAEACUA6gwAAAMAHAARAAYJgQmrjgAJAQZoDAAABAARAGkMAAAFABQAawwAAAQADwBqDAAAAwAUAGwMAAAEACUA6gwAAAMAHAAAAA==.',
Du='Dura:BAABLgAECn8bAAISAAcJpxV4IQDDAQdoDAAABQBHAGkMAAAFADUAawwAAAQAKgBqDAAABABNAGwMAAADAD4AbQwAAAEAHwDqDAAABQAwABIABwmnFXghAMMBB2gMAAAFAEcAaQwAAAUANQBrDAAABAAqAGoMAAAEAE0AbAwAAAMAPgBtDAAAAQAfAOoMAAAFADAAAAA=.',
El='Eldunari:BAAALgAECgQJBAAAAA==.Elfblood:BAABLgAECn8kAAIPAAgJfgprCwArAQhoDAAABwBHAGkMAAAGABMAawwAAAYAGABqDAAABQAbAGwMAAAFABsAbQwAAAEACQDqDAAABQATAG4MAAABAA8ADwAICX4KawsAKwEIaAwAAAcARwBpDAAABgATAGsMAAAGABgAagwAAAUAGwBsDAAABQAbAG0MAAABAAkA6gwAAAUAEwBuDAAAAQAPAAAA.Elvion:BAAALgAECgMJBQAAAA==.',
Em='Emollama:BAABLgAECn8vAAMTAAkJmAx+LgDXAQloDAAACAAgAGkMAAAIACAAawwAAAcAHQBqDAAABgAcAGwMAAAEACQAbQwAAAIAEgDqDAAABwAxAG4MAAAEACcAbwwAAAEAEgATAAkJmAx+LgDXAQloDAAACAAgAGkMAAAIACAAawwAAAcAHQBqDAAABgAcAGwMAAADACQAbQwAAAIAEgDqDAAABwAxAG4MAAAEACcAbwwAAAEAEgAUAAEJJwJpTQAcAAFsDAAAAQAFAAAA.',
En='Engine:BAAALgADCgQJBAAAAA==.',
Er='Erazer:BAAALgADCgMJAwAAAA==.Erilana:BAAALgAECgEJAQAAAA==.',
Et='Etiimasi:BAAALgADCgYJBwAAAA==.',
['Eï']='Eïr:BAAALgAECgQJCAABLgAFFAIJAgACAAAAAA==.',
Fa='Fabulosa:BAABLgAECn8nAAQVAAgJYgzjLwAhAQhoDAAABgALAGkMAAAGABoAawwAAAUAFQBqDAAABgA3AGwMAAAEABEAbQwAAAEACQDqDAAACABAAG4MAAADAC4AFQAGCdsJ4y8AIQEGaAwAAAEABgBpDAAAAgAaAGsMAAACABUAagwAAAMANwBsDAAAAgARAOoMAAADABcADAAICZoIlCoADwEIaAwAAAIAIABpDAAAAwAZAGsMAAACABQAagwAAAMAFABsDAAAAgAaAG0MAAABAAcA6gwAAAMAJQBuDAAAAQAEAAUABQlgClU8AJcABWgMAAADAAsAaQwAAAEABQBrDAAAAQAEAOoMAAACAEAAbgwAAAIALgAAAA==.Faith:BAAALgAECgYJDwAAAA==.',
Fi='Finiquito:BAAALgADCgMJAwAAAA==.Finite:BAAALgADCgkJEAABLgAECgcJHgALAIgZAA==.Firebug:BAAALgAECgYJEAAAAA==.',
Fn='Fndruid:BAAALgADCgEJAQAAAA==.Fnmage:BAAALgADCgkJFwAAAA==.',
Fr='Frieren:BAAALgADCgkJDgABLgAFFAQJDAAWACEgAA==.',
Fu='Furnok:BAABLgAECn8eAAMQAAgJvAwqJABIAQhoDAAABgAwAGkMAAAFACQAawwAAAUAGABqDAAABAAlAGwMAAAEAB8AbQwAAAEAFwDqDAAABAAgAG4MAAABAB8AEAAICbwMKiQASAEIaAwAAAYAMABpDAAABAAkAGsMAAADABgAagwAAAIAJQBsDAAAAwAfAG0MAAABABcA6gwAAAQAIABuDAAAAQAfABIABAkyEOVeAKcABGkMAAABABIAawwAAAIAKgBqDAAAAgA9AGwMAAABACsAAAA=.Fuzzyshukk:BAAALgAECgQJBwAAAA==.',
Ga='Galethia:BAAALgADCgkJGAAAAA==.Garli:BAAALgADCgMJAwAAAA==.',
Ge='Gerkin:BAAALgADCgcJDwAAAA==.',
Gg='Ggcthulhu:BAAALgAECgMJBAABLgAECgcJCQACAAAAAA==.',
Gh='Ghutz:BAACLgAFFH8FAAIXAAMJfwWYEQC6AANoDAAAAgAKAGkMAAABAA8A6gwAAAIAEAAXAAMJfwWYEQC6AANoDAAAAgAKAGkMAAABAA8A6gwAAAIAEAAuAAQKfzEAAxcACAkUGGYIAOUBABcACAkUGGYIAOUBABgABwmICzZIAIMBAAAA.',
Gl='Glitterhoof:BAAALgAECgYJEAAAAA==.Glorblariirn:BAAALgADCgYJBgAAAA==.',
Go='Goliath:BAAALgAECgUJCwAAAA==.',
Gr='Grimbjorne:BAAALgADCgcJBwAAAA==.Grimmbeardd:BAAALgADCgYJCgAAAA==.',
Gu='Gumbercules:BAABLgAECn8kAAIZAAgJqxAfCwCyAQhoDAAABwA8AGkMAAAGACMAawwAAAYAGgBqDAAABQBHAGwMAAAFAEIAbQwAAAEADgDqDAAABQA9AG4MAAABAAQAGQAICasQHwsAsgEIaAwAAAcAPABpDAAABgAjAGsMAAAGABoAagwAAAUARwBsDAAABQBCAG0MAAABAA4A6gwAAAUAPQBuDAAAAQAEAAAA.',
Ha='Hammie:BAAALgADCgkJCQAAAA==.',
He='Hearthglen:BAABLgAECn8VAAILAAYJWg+YdQAYAQZoDAAABQA0AGkMAAAFADgAawwAAAUAKwBqDAAAAgBFAGwMAAACAAoA6gwAAAIAIQALAAYJWg+YdQAYAQZoDAAABQA0AGkMAAAFADgAawwAAAUAKwBqDAAAAgBFAGwMAAACAAoA6gwAAAIAIQAAAA==.',
Ho='Hollet:BAAALgAECgYJEAAAAA==.Holyblasto:BAAALgADCgEJAQAAAA==.Holyshukk:BAACLgAFFH8HAAIGAAMJXhgwGgDpAANoDAAAAwBMAGkMAAADAEQA6gwAAAEAKQAGAAMJXhgwGgDpAANoDAAAAwBMAGkMAAADAEQA6gwAAAEAKQAuAAQKfyMAAwYACQmRIqEFABIDAAYACQmRIqEFABIDAAsAAQlCB8srAS0AAAAA.',
Hu='Huckk:BAAALgADCgUJBQAAAA==.',
Hy='Hylen:BAAALgAECgcJCQAAAA==.',
Ib='Ibrandul:BAABLgAECn8eAAILAAcJhRGeUABrAQdoDAAABQA6AGkMAAAFAD0AawwAAAYAIwBqDAAAAwAkAGwMAAACACEA6gwAAAgALABuDAAAAQAjAAsABwmFEZ5QAGsBB2gMAAAFADoAaQwAAAUAPQBrDAAABgAjAGoMAAADACQAbAwAAAIAIQDqDAAACAAsAG4MAAABACMAAAA=.',
Ic='Icyveins:BAABLgAECn8UAAIRAAcJ8wH6ugC3AAdoDAAABQAEAGkMAAAEAAcAawwAAAQABgBqDAAAAgAKAGwMAAABAAEA6gwAAAMABABuDAAAAQAEABEABwnzAfq6ALcAB2gMAAAFAAQAaQwAAAQABwBrDAAABAAGAGoMAAACAAoAbAwAAAEAAQDqDAAAAwAEAG4MAAABAAQAAAA=.',
Ir='Ironhuntress:BAABLgAECn8WAAIaAAYJtg0QWAAbAQZoDAAABQAvAGkMAAAFACoAawwAAAUALQBqDAAAAwAkAGwMAAACABEA6gwAAAIAFwAaAAYJtg0QWAAbAQZoDAAABQAvAGkMAAAFACoAawwAAAUALQBqDAAAAwAkAGwMAAACABEA6gwAAAIAFwAAAA==.',
It='Ithro:BAABLgAECn8fAAIbAAgJlRf0AwD3AQhoDAAABQBLAGkMAAAFAEcAawwAAAUATwBqDAAAAwA5AGwMAAAEAEEAbQwAAAIAOwDqDAAABgA8AG4MAAABAAoAGwAICZUX9AMA9wEIaAwAAAUASwBpDAAABQBHAGsMAAAFAE8AagwAAAMAOQBsDAAABABBAG0MAAACADsA6gwAAAYAPABuDAAAAQAKAAAA.',
Iy='Iyachtu:BAAALgAECgkJDwAAAA==.',
Ja='Jarlo:BAABLgAECn8kAAIbAAgJyxKrBADTAQhoDAAABwBKAGkMAAAGAEAAawwAAAYAMQBqDAAABQBGAGwMAAAFACEAbQwAAAEAHwDqDAAABQBCAG4MAAABABEAGwAICcsSqwQA0wEIaAwAAAcASgBpDAAABgBAAGsMAAAGADEAagwAAAUARgBsDAAABQAhAG0MAAABAB8A6gwAAAUAQgBuDAAAAQARAAAA.',
Je='Jeffeory:BAAALgAECgIJAgABLgAECgkJLQALAMUaAA==.',
Jo='Jobu:BAAALgAECgEJAgAAAA==.Jormungandr:BAABLgAECn8cAAIXAAgJKSGoBQAuAghoDAAABABXAGkMAAAEAF8AawwAAAQASgBqDAAAAwBeAGwMAAAEAFkAbQwAAAIASwDqDAAABgBhAG4MAAABAEsAFwAICSkhqAUALgIIaAwAAAQAVwBpDAAABABfAGsMAAAEAEoAagwAAAMAXgBsDAAABABZAG0MAAACAEsA6gwAAAYAYQBuDAAAAQBLAAAA.',
Ju='Juanhunglow:BAAALgADCgcJIwAAAA==.Judgederien:BAAALgAECgIJAgAAAA==.Jularity:BAAALgADCgYJBgAAAA==.',
Ka='Kaeldric:BAABLgAECn8aAAMTAAcJDCLCGwA6AgdoDAAABABaAGkMAAAEAGAAawwAAAQAXQBqDAAABABdAGwMAAAEAFgAbQwAAAIAQwDqDAAABABWABMABwkMIsIbADoCB2gMAAAEAFoAaQwAAAQAYABrDAAABABdAGoMAAAEAF0AbAwAAAQAWABtDAAAAgBDAOoMAAADAFYAFAABCf8PDD4ALgAB6gwAAAEAKAAAAA==.Kaladïn:BAAALgAECgEJAQAAAA==.Kalemshai:BAAALgADCgcJCwAAAA==.Kalinea:BAABLgAECn8fAAIaAAcJRBTlWABdAQdoDAAACABLAGkMAAAGAFAAawwAAAYALgBqDAAABQBDAGwMAAADACQA6gwAAAIAMwBuDAAAAQAUABoABwlEFOVYAF0BB2gMAAAIAEsAaQwAAAYAUABrDAAABgAuAGoMAAAFAEMAbAwAAAMAJADqDAAAAgAzAG4MAAABABQAAAA=.Kazuha:BAAALgAECgYJDgAAAA==.',
Ke='Kellerun:BAAALgADCgIJAgAAAA==.Ketosis:BAAALgADCggJCgAAAA==.',
Ko='Kope:BAABLgAECn8kAAIZAAkJSRrrBABsAgloDAAABQA7AGkMAAAFAEEAawwAAAUARgBqDAAABABHAGwMAAAEAFYAbQwAAAQAMwDqDAAABABGAG4MAAAEAFMAbwwAAAEAMAAZAAkJSRrrBABsAgloDAAABQA7AGkMAAAFAEEAawwAAAUARgBqDAAABABHAGwMAAAEAFYAbQwAAAQAMwDqDAAABABGAG4MAAAEAFMAbwwAAAEAMAAAAA==.',
Kr='Kreltor:BAABLgAECn8cAAISAAcJHiL+CQCiAgdoDAAABQBTAGkMAAAFAFkAawwAAAQAUABqDAAABABZAGwMAAADAF8AbQwAAAEAWADqDAAABgBVABIABwkeIv4JAKICB2gMAAAFAFMAaQwAAAUAWQBrDAAABABQAGoMAAAEAFkAbAwAAAMAXwBtDAAAAQBYAOoMAAAGAFUAAAA=.Kryptikz:BAAALgAECgYJCwABLgAECgYJEAACAAAAAA==.Krystoferson:BAAALgAECggJDwAAAA==.',
La='Largar:BAAALgADCgQJBAAAAA==.',
Le='Leerroyy:BAAALgADCgIJAgAAAA==.Leesoftpaw:BAAALgADCgYJAgAAAA==.Leianii:BAAALgAECgEJAQAAAA==.Lextali:BAAALgAECgQJBAAAAA==.',
Lh='Lhondar:BAAALgAECgQJBAAAAA==.',
Li='Liafail:BAABLgAECn8YAAINAAcJ8QesgwBTAQdoDAAABQATAGkMAAAEABYAawwAAAQAEgBqDAAABAAVAGwMAAADABkAbQwAAAEACgDqDAAAAwAZAA0ABwnxB6yDAFMBB2gMAAAFABMAaQwAAAQAFgBrDAAABAASAGoMAAAEABUAbAwAAAMAGQBtDAAAAQAKAOoMAAADABkAAAA=.Lillat:BAAALgAECgUJCwAAAA==.Liryv:BAAALgADCgYJFAAAAA==.Littlepop:BAAALgADCgEJAQAAAA==.',
Lo='Lollilock:BAAALgAECgcJBAAAAA==.',
Lu='Luena:BAAALgAECgYJEgAAAA==.Lumbre:BAAALgADCgcJCQAAAA==.Luminara:BAAALgADCgkJCwAAAA==.Luuggork:BAAALgADCgYJBgAAAA==.',
Ly='Lyrà:BAAALgAECgQJAwAAAA==.',
['Lá']='Ládydèath:BAAALgAECgYJAQAAAA==.',
['Lì']='Lìesson:BAABLgAECn8cAAILAAgJ+h4XFgBfAghoDAAABABWAGkMAAAEAFkAawwAAAQAQwBqDAAAAwBjAGwMAAAEAE0AbQwAAAIASADqDAAABgBfAG4MAAABAEEACwAICfoeFxYAXwIIaAwAAAQAVgBpDAAABABZAGsMAAAEAEMAagwAAAMAYwBsDAAABABNAG0MAAACAEgA6gwAAAYAXwBuDAAAAQBBAAAA.',
Ma='Mackaroni:BAABLgAECn8UAAIRAAYJHBEjkAAGAQZoDAAABAAzAGkMAAAEACcAawwAAAQAKgBqDAAAAgBaAGwMAAABABkA6gwAAAUAPAARAAYJHBEjkAAGAQZoDAAABAAzAGkMAAAEACcAawwAAAQAKgBqDAAAAgBaAGwMAAABABkA6gwAAAUAPAABLgAECggJEAACAAAAAA==.Madrel:BAAALgADCgUJBQAAAA==.Magesca:BAABLgAECn8jAAIRAAgJkRS6OADTAQhoDAAABwBTAGkMAAAGAEgAawwAAAYAIQBqDAAAAwBGAGwMAAAEAEIAbQwAAAEAEwDqDAAABwBVAG4MAAABAAgAEQAICZEUujgA0wEIaAwAAAcAUwBpDAAABgBIAGsMAAAGACEAagwAAAMARgBsDAAABABCAG0MAAABABMA6gwAAAcAVQBuDAAAAQAIAAAA.Makkagg:BAACLgAFFH8JAAMKAAMJoxNKEADOAANoDAAABABGAGkMAAACACUA6gwAAAMAKwAKAAMJoxNKEADOAANoDAAAAwBGAGkMAAACACUA6gwAAAMAKwAYAAEJAQZhJABLAAFoDAAAAQAPAC4ABAp/LQADCgAICZUg/AMAiQIACgAICZUg/AMAiQIAGAAICVYMxzkAvwEAAAA=.Malamur:BAAALgADCggJEgAAAA==.Malisea:BAABLgAECn8UAAIRAAYJUQX1owDiAAZoDAAABAALAGkMAAAEAAwAawwAAAQACABqDAAAAgAPAGwMAAADABIA6gwAAAMAEAARAAYJUQX1owDiAAZoDAAABAALAGkMAAAEAAwAawwAAAQACABqDAAAAgAPAGwMAAADABIA6gwAAAMAEAAAAA==.',
Mi='Milagrosa:BAABLgAECn8bAAIWAAgJEg6bHABuAQhoDAAABAAWAGkMAAAEADoAawwAAAQANgBqDAAAAwBDAGwMAAAEAC4AbQwAAAEADwDqDAAABgAhAG4MAAABABYAFgAICRIOmxwAbgEIaAwAAAQAFgBpDAAABAA6AGsMAAAEADYAagwAAAMAQwBsDAAABAAuAG0MAAABAA8A6gwAAAYAIQBuDAAAAQAWAAAA.Mirael:BAACLgAFFH8FAAIaAAMJJB3CJQASAQNoDAAAAgArAGkMAAACAF4A6gwAAAEAVgAaAAMJJB3CJQASAQNoDAAAAgArAGkMAAACAF4A6gwAAAEAVgAuAAQKfywAAhoACQnhH8AIAAcDABoACQnhH8AIAAcDAAAA.Mishuntsalot:BAAALgADCgYJCQAAAA==.',
Mo='Molocherx:BAAALgADCgMJAwAAAA==.Mommacoo:BAAALgAECgYJDgAAAA==.',
Mu='Mumsurprise:BAAALgAECgkJAgAAAA==.',
My='Myrmia:BAABLgAECn8WAAIHAAYJQg04SQAEAQZoDAAABQAoAGkMAAAFABgAawwAAAUALQBqDAAAAwAXAGwMAAACADIA6gwAAAIAEgAHAAYJQg04SQAEAQZoDAAABQAoAGkMAAAFABgAawwAAAUALQBqDAAAAwAXAGwMAAACADIA6gwAAAIAEgAAAA==.Mystryx:BAAALgAECgUJCQAAAA==.',
['Mà']='Màck:BAAALgAECggJEAAAAA==.',
Na='Nade:BAAALgAECgcJBAAAAA==.Naldor:BAAALgADCgkJCQAAAA==.Nargul:BAABLgAECn8dAAINAAYJhBOzYgAZAQZoDAAABgBKAGkMAAAGADwAawwAAAUANQBqDAAAAgAiAGwMAAABABEA6gwAAAkAKwANAAYJhBOzYgAZAQZoDAAABgBKAGkMAAAGADwAawwAAAUANQBqDAAAAgAiAGwMAAABABEA6gwAAAkAKwAAAA==.Naturboom:BAAALgAECgEJAQAAAA==.',
Ne='Nekossian:BAAALgAECgYJCwABLgAECgkJLQALAMUaAA==.',
Ni='Nickorvis:BAAALgADCgUJBQABLgAECgcJGAANAPEHAA==.Nirazen:BAAALgAECgIJAgAAAA==.',
No='Nonae:BAEALgADCgYJBgAAAA==.Nota:BAABLgAECn8WAAILAAYJ+wZEogDGAAZoDAAABQAQAGkMAAAFACgAawwAAAUAFQBqDAAAAwAOAGwMAAACAAIA6gwAAAIACAALAAYJ+wZEogDGAAZoDAAABQAQAGkMAAAFACgAawwAAAUAFQBqDAAAAwAOAGwMAAACAAIA6gwAAAIACAAAAA==.',
Oa='Oathmere:BAAALgADCgUJBQAAAA==.',
Og='Ogrusao:BAAALgAECgcJDAAAAA==.',
Pa='Panasaurus:BAABLgAECn8kAAIcAAgJ2xL7BwB/AQhoDAAABwAoAGkMAAAGAEEAawwAAAYANgBqDAAABQAyAGwMAAAFADcAbQwAAAEABwDqDAAABQA3AG4MAAABADoAHAAICdsS+wcAfwEIaAwAAAcAKABpDAAABgBBAGsMAAAGADYAagwAAAUAMgBsDAAABQA3AG0MAAABAAcA6gwAAAUANwBuDAAAAQA6AAAA.',
Pe='Pechuuga:BAABLgAECn8WAAIdAAcJvhmCMgCHAQdoDAAABQBMAGkMAAADACwAawwAAAMAPgBqDAAABABKAGwMAAACADgAbQwAAAEASQDqDAAABABSAB0ABwm+GYIyAIcBB2gMAAAFAEwAaQwAAAMALABrDAAAAwA+AGoMAAAEAEoAbAwAAAIAOABtDAAAAQBJAOoMAAAEAFIAAAA=.Pelli:BAABLgAECn8ZAAIMAAcJlAVeLQD9AAdoDAAABAAQAGkMAAAEABEAawwAAAQACgBqDAAABAAXAGwMAAADAA4AbQwAAAEACADqDAAABQARAAwABwmUBV4tAP0AB2gMAAAEABAAaQwAAAQAEQBrDAAABAAKAGoMAAAEABcAbAwAAAMADgBtDAAAAQAIAOoMAAAFABEAAAA=.Pendraig:BAAALgADCgUJCAAAAA==.',
Pl='Plaza:BAAALgAECgkJCAAAAA==.',
Qu='Quadrilio:BAAALgADCgUJBQAAAA==.Quamutei:BAAALgADCgUJBgAAAA==.',
Ra='Raylisarri:BAAALgAECgEJAgABLgAECgQJDAACAAAAAA==.Rayst:BAAALgAECgQJEAAAAA==.Razìel:BAAALgADCgMJAgAAAA==.',
Rh='Rhalek:BAAALgAECgUJCQABLgAECggJMQAHALUhAA==.Rheunae:BAAALgAECgQJBAAAAA==.Rhykis:BAABLgAECn8WAAIYAAYJ6x/AFQDNAQZoDAAABQBhAGkMAAAFAFsAawwAAAUAPwBqDAAAAwBgAGwMAAACADsA6gwAAAIAYAAYAAYJ6x/AFQDNAQZoDAAABQBhAGkMAAAFAFsAawwAAAUAPwBqDAAAAwBgAGwMAAACADsA6gwAAAIAYAAAAA==.',
Ri='Rilis:BAAALgADCgEJAQAAAA==.Rillyn:BAABLgAECn8gAAIOAAgJaxOyDADtAQhoDAAABQAtAGkMAAAFAD0AawwAAAUALgBqDAAABQAnAGwMAAAFAB8AbQwAAAEARwDqDAAABQAqAG4MAAABADAADgAICWsTsgwA7QEIaAwAAAUALQBpDAAABQA9AGsMAAAFAC4AagwAAAUAJwBsDAAABQAfAG0MAAABAEcA6gwAAAUAKgBuDAAAAQAwAAAA.',
Ro='Rojei:BAAALgADCgYJBgAAAA==.Role:BAAALgADCgEJAQABLgAECggJJgAeADUYAA==.',
Ru='Rubbin:BAAALgAECgEJAQAAAA==.',
Sa='Salindill:BAAALgADCgMJAwAAAA==.Salline:BAAALgAECgQJDgAAAA==.Samanda:BAAALgAECgYJEwAAAA==.Samshir:BAAALgAFFAEJAQAAAA==.',
Sc='Scorned:BAABLgAECn8hAAIJAAcJ4hB4RwA1AQdoDAAABwA/AGkMAAAGAC4AawwAAAYAIgBqDAAABQAXAGwMAAAEADMA6gwAAAQAJgBuDAAAAQAZAAkABwniEHhHADUBB2gMAAAHAD8AaQwAAAYALgBrDAAABgAiAGoMAAAFABcAbAwAAAQAMwDqDAAABAAmAG4MAAABABkAAAA=.',
Se='Sekrain:BAAALgAECgQJBAAAAA==.Seosinz:BAAALgAECgcJBwAAAA==.',
Sh='Shamnasty:BAAALgAECgcJEwAAAA==.Shariaan:BAAALgADCgkJJwAAAA==.Shaylinn:BAAALgADCgcJHwAAAA==.Shukkvoker:BAAALgADCgQJBQABLgAFFAMJBwAGAF4YAA==.',
Si='Siella:BAABLgAECn8bAAIFAAcJ8hNEFwCsAQdoDAAABQBAAGkMAAAFAEUAawwAAAQARwBqDAAABAAfAGwMAAADAD4AbQwAAAEADQDqDAAABQArAAUABwnyE0QXAKwBB2gMAAAFAEAAaQwAAAUARQBrDAAABABHAGoMAAAEAB8AbAwAAAMAPgBtDAAAAQANAOoMAAAFACsAAAA=.Sileves:BAAALgAECgEJAQAAAA==.Sitrom:BAAALgAECgUJCwAAAA==.',
Sn='Snayd:BAABLgAECn8XAAIRAAcJeiCbIAA9AgdoDAAABABQAGkMAAAEAFIAawwAAAQATwBqDAAAAwBhAGwMAAACAFwAbQwAAAEASADqDAAABQBbABEABwl6IJsgAD0CB2gMAAAEAFAAaQwAAAQAUgBrDAAABABPAGoMAAADAGEAbAwAAAIAXABtDAAAAQBIAOoMAAAFAFsAAAA=.',
So='Sonofmums:BAAALgAECgcJBgAAAA==.Sora:BAAALgADCgIJAgABLgAECgEJAQACAAAAAA==.Soulbaine:BAAALgAECgQJCQAAAA==.',
Sp='Spazeric:BAABLgAECn8YAAMEAAgJ5xfBFQDDAQhoDAAABAA6AGkMAAAEADAAawwAAAQAPABqDAAAAwA6AGwMAAAEAE0AbQwAAAEAWwDqDAAAAwA9AG4MAAABACIABAAHCTYWwRUAwwEHaAwAAAMAOgBpDAAAAwAwAGsMAAADADwAagwAAAMAOgBsDAAABABNAOoMAAADAD0AbgwAAAEAIgAfAAQJdRPNWQCpAARoDAAAAQBBAGkMAAABAC0AawwAAAEAGwBtDAAAAQA8AAAA.Spheria:BAABLgAECn8fAAINAAgJgAPGcgD0AAhoDAAABgAGAGkMAAAFAAwAawwAAAUACABqDAAABQAPAGwMAAAFAA8AbQwAAAEABwDqDAAAAwAHAG4MAAABAAMADQAICYADxnIA9AAIaAwAAAYABgBpDAAABQAMAGsMAAAFAAgAagwAAAUADwBsDAAABQAPAG0MAAABAAcA6gwAAAMABwBuDAAAAQADAAAA.',
St='Stalon:BAAALgADCgYJDgAAAA==.Strangeluve:BAAALgAECgcJDAAAAA==.',
Su='Suerte:BAAALgADCggJDQAAAA==.Suzieq:BAAALgADCgMJAwAAAA==.',
Sy='Sysnootles:BAAALgADCgYJBwAAAA==.',
['Sà']='Sàyori:BAAALgAECgUJBwAAAA==.',
Ta='Tabrett:BAAALgAECgIJAgAAAA==.Talashea:BAAALgAECgEJAQAAAA==.Tankdezoe:BAAALgAECgMJBAABLgAECgQJBQACAAAAAA==.Tarall:BAAALgADCgMJAwAAAA==.Taveres:BAAALgADCgEJAQAAAA==.Tax:BAAALgAECgQJEAAAAA==.',
Te='Tenara:BAAALgADCgkJEgAAAA==.Tequ:BAAALgADCgcJFQAAAA==.',
Ti='Timeshadow:BAAALgAECgQJBAAAAA==.Tinakoffee:BAAALgAECgIJAgAAAA==.Tine:BAABLgAECn8hAAIRAAkJZRfvIgAwAgloDAAABQBWAGkMAAAFAEsAawwAAAUAPQBqDAAABAA9AGwMAAADAEUAbQwAAAMAMgDqDAAABAA+AG4MAAADACMAbwwAAAEAJAARAAkJZRfvIgAwAgloDAAABQBWAGkMAAAFAEsAawwAAAUAPQBqDAAABAA9AGwMAAADAEUAbQwAAAMAMgDqDAAABAA+AG4MAAADACMAbwwAAAEAJAAAAA==.',
To='Tope:BAAALgAECgYJCwAAAA==.Toray:BAAALgAECgkJDgAAAA==.',
Tr='Triplesix:BAAALgAECgcJEgAAAA==.Trittia:BAAALgAECgYJEgAAAA==.',
Tu='Tukk:BAAALgAECgYJCQAAAA==.Turtle:BAAALgAECgEJBAAAAA==.',
Tw='Twigatron:BAAALgAECggJEwABLgAECgcJDAACAAAAAA==.Twigdin:BAAALgADCgMJAwAAAA==.Twigdun:BAAALgAECgMJBQAAAA==.',
Ty='Tynk:BAAALgADCgUJBQABLgAECgQJBAACAAAAAA==.',
Ur='Urza:BAAALgAECgUJBwAAAA==.',
Va='Vaewind:BAAALgADCgEJAQAAAA==.Valethus:BAABLgAECn8vAAMaAAkJ5Br+DQB+AgloDAAABwBeAGkMAAAHAFIAawwAAAcAUwBqDAAABgBXAGwMAAAFAEUAbQwAAAQAKADqDAAABgBDAG4MAAAEADwAbwwAAAEANAAaAAkJ5Br+DQB+AgloDAAABwBeAGkMAAAHAFIAawwAAAcAUwBqDAAABABXAGwMAAAEAEUAbQwAAAQAKADqDAAABgBDAG4MAAAEADwAbwwAAAEANAABAAIJVAgefgBNAAJqDAAAAgAHAGwMAAABABUAAAA=.Valmaru:BAAALgADCgEJAQAAAA==.',
Ve='Vesp:BAAALgAECgMJAwAAAA==.Vexxa:BAABLgAECn8QAAIJAAgJIxoiYgB7AQhoDAAAAgBQAGkMAAACADgAawwAAAIAOgBqDAAAAQABAGwMAAABAEgAbQwAAAIAOwDqDAAABQBPAG4MAAABAD0ACQAICSMaImIAewEIaAwAAAIAUABpDAAAAgA4AGsMAAACADoAagwAAAEAAQBsDAAAAQBIAG0MAAACADsA6gwAAAUATwBuDAAAAQA9AAAA.',
Vy='Vynd:BAAALgADCgkJDgABLgABCgMJBAACAAAAAA==.',
Wa='Walkz:BAAALgAECgYJEAAAAA==.Warrockhealz:BAAALgADCgYJBgAAAA==.',
Wi='Wickedlight:BAABLgAECn8eAAIMAAgJGRlKDAAZAghoDAAABgBUAGkMAAAFAEwAawwAAAUATwBqDAAABAAyAGwMAAAEAEwAbQwAAAEAHADqDAAABAA9AG4MAAABACoADAAICRkZSgwAGQIIaAwAAAYAVABpDAAABQBMAGsMAAAFAE8AagwAAAQAMgBsDAAABABMAG0MAAABABwA6gwAAAQAPQBuDAAAAQAqAAAA.Wiggleston:BAAALgAECgYJCgAAAA==.Willscarlet:BAAALgAECgQJBgAAAA==.',
Wy='Wylethia:BAAALgADCgcJCAAAAA==.',
Xa='Xandris:BAAALgAECgEJAgABLgAFFAEJAQACAAAAAA==.',
Yh='Yhana:BAAALgADCggJEwAAAA==.',
Yo='Yozsh:BAAALgADCgkJGAAAAA==.',
Za='Zarathia:BAAALgAECgUJCQAAAA==.Zaritym:BAABLgAECn8WAAMEAAYJ/hoaFgC/AQZoDAAABQA8AGkMAAAFAFAAawwAAAUATABqDAAAAwBGAGwMAAACAFMA6gwAAAIAKwAEAAYJ/hoaFgC/AQZoDAAAAwA8AGkMAAADAFAAawwAAAMATABqDAAAAgBGAGwMAAACAFMA6gwAAAIAKwAfAAQJbw8iPQCfAARoDAAAAgAlAGkMAAACACoAawwAAAIAJgBqDAAAAQA3AAAA.Zarrilin:BAABLgAECn8nAAIRAAkJURc3IAA/AgloDAAABgA/AGkMAAAGAEAAawwAAAYARgBqDAAABQBYAGwMAAAEAFEAbQwAAAMAKgDqDAAABQA+AG4MAAADABoAbwwAAAEAQQARAAkJURc3IAA/AgloDAAABgA/AGkMAAAGAEAAawwAAAYARgBqDAAABQBYAGwMAAAEAFEAbQwAAAMAKgDqDAAABQA+AG4MAAADABoAbwwAAAEAQQAAAA==.',
Ze='Zebop:BAAALgADCgMJBgAAAA==.Zeeley:BAAALgADCgYJCgAAAA==.Zelsada:BAAALgAECgEJAQAAAA==.',
Zi='Zibetha:BAACLgAFFH8GAAIPAAIJ3QvECgCbAAJoDAAAAwAtAGkMAAADAA4ADwACCd0LxAoAmwACaAwAAAMALQBpDAAAAwAOAC4ABAp/QgACDwAJCQ8anAEAcQIADwAJCQ8anAEAcQIAAAA=.',
Zo='Zoeheals:BAAALgAECgQJBQAAAA==.',
Zu='Zuggtmoy:BAAALgADCgkJCQAAAA==.Zulmahn:BAAALgAECgYJEQAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
