local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Priest-Discipline','Unknown-Unknown','Priest-Holy','Mage-Frost','Paladin-Retribution','Paladin-Holy','Monk-Mistweaver','Priest-Shadow','Warrior-Fury','Monk-Windwalker','DemonHunter-Devourer','DemonHunter-Havoc','DeathKnight-Unholy','Druid-Restoration','Warlock-Demonology','Shaman-Restoration','DeathKnight-Frost','Mage-Arcane','Druid-Balance','Druid-Guardian','Evoker-Preservation','Monk-Brewmaster','Druid-Feral','Evoker-Augmentation','Evoker-Devastation','DeathKnight-Blood','Warrior-Arms','Warrior-Protection','Hunter-Survival','Hunter-BeastMastery','Hunter-Marksmanship','Shaman-Enhancement','Shaman-Elemental','DemonHunter-Vengeance','Mage-Fire','Paladin-Protection',}
local provider = {region='US',realm='Gundrak',name='US',type='daily',zone=46,date='2026-05-31',data={Ad='Adelyne:BAAALgAFFAMJAwABLgAFFAUJDgABAG0SAA==.Adera:BAAALgAECgYJBwAAAA==.',
Af='Aff:BAAALgADCgYJBgAAAA==.',
Ag='Agony:BAAALgAECgQJBgAAAA==.',
Ah='Ahkanon:BAAALgADCgEJAQAAAA==.',
Ai='Aiden:BAAALgAECgEJAgABLgAECgIJAgACAAAAAA==.Aidendk:BAAALgADCgIJAgABLgAECgIJAgACAAAAAA==.Aidenp:BAAALgADCgIJAgABLgAECgIJAgACAAAAAA==.Air:BAAALgADCgcJBwABLgAFFAgJIgADADkbAA==.',
Ak='Aku:BAAALgADCgIJBAAAAA==.',
Al='Aleniastra:BAAALgAECgYJEwAAAA==.Alexyss:BAAALgAECgUJDgAAAA==.Alykard:BAABLgAECn8xAAIEAAkJwhGbRAD4AQloDAAABwA3AGkMAAAGADwAawwAAAYAMgBqDAAABgAxAGwMAAAFAEMAbQwAAAMAGwDqDAAABwAcAG4MAAAFADgAbwwAAAQAEAAEAAkJwhGbRAD4AQloDAAABwA3AGkMAAAGADwAawwAAAYAMgBqDAAABgAxAGwMAAAFAEMAbQwAAAMAGwDqDAAABwAcAG4MAAAFADgAbwwAAAQAEAAAAA==.',
Am='Amyara:BAAALgAECgEJAQAAAA==.',
An='Andronicas:BAABLgAECn8gAAMFAAkJqw51XgCcAQloDAAABAAsAGkMAAAFADsAawwAAAgAOQBqDAAABAAgAGwMAAAEACkAbQwAAAIADADqDAAAAwAoAG4MAAABABcAbwwAAAEAEwAFAAkJqw51XgCcAQloDAAABAAsAGkMAAAFADsAawwAAAcAOQBqDAAABAAgAGwMAAAEACkAbQwAAAIADADqDAAAAwAoAG4MAAABABcAbwwAAAEAEwAGAAEJogevnAAtAAFrDAAAAQATAAAA.Aneira:BAABLgAFFH8YAAIEAAQJGglNXAAZAQRoDAAACQARAGkMAAAFACEAawwAAAMAFADqDAAABwAVAAQABAkaCU1cABkBBGgMAAAJABEAaQwAAAUAIQBrDAAAAwAUAOoMAAAHABUAAAA=.',
Ap='Apexis:BAAALgADCgYJCQAAAA==.',
Ar='Ariaa:BAAALgAECgUJDAAAAA==.Arieyri:BAAALgADCgcJBwAAAA==.Artpop:BAAALgAFFAEJAQABLgAFFAYJFQAHAK0TAA==.',
As='Ash:BAAALgADCgcJCwAAAA==.Ashvira:BAAALgAECgQJBAAAAA==.Aspect:BAAALgADCgcJDgABLgAECgEJAQACAAAAAA==.Astarael:BAABLgAECn8iAAMIAAkJShflHQC5AQloDAAABQBKAGkMAAAFADsAawwAAAQALABqDAAABABHAGwMAAAEADUAbQwAAAMAJQDqDAAABgBPAG4MAAACAC8AbwwAAAEAUAAIAAgJGhblHQC5AQhoDAAABQBKAGkMAAAEADsAawwAAAMALABqDAAAAwBHAGwMAAADADUAbQwAAAIAJQDqDAAABgBPAG4MAAABAC8AAwAHCS0Og0wAlwAHaQwAAAEAFwBrDAAAAQAdAGoMAAABACAAbAwAAAEALABtDAAAAQA4AG4MAAABADIAbwwAAAEAEQAAAA==.',
Av='Avi:BAABLgAECn8oAAIBAAkJUhXODwBVAgloDAAABQAvAGkMAAAFAEcAawwAAAUALwBqDAAABgAwAGwMAAAGADoAbQwAAAIAKwDqDAAABwBTAG4MAAADADAAbwwAAAEAKwABAAkJUhXODwBVAgloDAAABQAvAGkMAAAFAEcAawwAAAUALwBqDAAABgAwAGwMAAAGADoAbQwAAAIAKwDqDAAABwBTAG4MAAADADAAbwwAAAEAKwABLgAECgkJcAAJAHggAA==.',
Ba='Babygurl:BAACLgAFFH8FAAIGAAMJNx+fIAAFAQNoDAAAAgBNAGkMAAABAEMA6gwAAAIAXgAGAAMJNx+fIAAFAQNoDAAAAgBNAGkMAAABAEMA6gwAAAIAXgAuAAQKf3YAAgYACQntJbIBAJADAAYACQntJbIBAJADAAAA.Baragas:BAAALgAECgYJDQAAAA==.Bareback:BAAALgAECgQJBAAAAA==.Barney:BAAALgADCgEJAQAAAA==.Battosaî:BAAALgAECgQJBAAAAA==.',
Be='Beeny:BAACLgAFFH80AAIHAAgJCCOCAQALAwhoDAAACABhAGkMAAALAGMAawwAAAcASgBqDAAACABVAGwMAAAEAGEAbQwAAAEASwDqDAAADABbAG4MAAABAGAABwAICQgjggEACwMIaAwAAAgAYQBpDAAACwBjAGsMAAAHAEoAagwAAAgAVQBsDAAABABhAG0MAAABAEsA6gwAAAwAWwBuDAAAAQBgAC4ABAp/QQADBwAJCWkjhQgAzAIABwAJCWkjhQgAzAIACgABCWwQ4osAMwAAAAA=.Belle:BAACLgAFFH8ZAAMLAAgJxBYGCwAlAghoDAAABQBVAGkMAAAFAGAAawwAAAQATQBqDAAAAgAlAGwMAAABABMAbQwAAAEAGgDqDAAABgBjAG4MAAABAAMACwAICcQWBgsAJQIIaAwAAAUAVQBpDAAABABgAGsMAAAEAE0AagwAAAIAJQBsDAAAAQATAG0MAAABABoA6gwAAAYAYwBuDAAAAQADAAwAAQnwFz8MAFYAAWkMAAABAD0ALgAECn8tAAMLAAgJxSYSBACIAwALAAgJhSYSBACIAwAMAAcJPiBSDgB+AgAAAA==.Berat:BAAALgADCgQJBAAAAA==.Berzerker:BAAALgADCgcJEwAAAA==.',
Bg='Bgc:BAAALgADCgUJBQAAAA==.',
Bi='Binari:BAAALgAECgMJAwABLgAFFAMJBQAJACoUAA==.Binlock:BAAALgAECgQJBAABLgAFFAMJBQAJACoUAA==.',
Bl='Bl:BAAALgAECgMJAwAAAA==.Bladebear:BAABLgAECn82AAIEAAkJUxWcRQD0AQloDAAACABNAGkMAAAHAD4AawwAAAcAQgBqDAAABwBKAGwMAAAHAFAAbQwAAAQAKgDqDAAABwA3AG4MAAAEAB8AbwwAAAMAEwAEAAkJUxWcRQD0AQloDAAACABNAGkMAAAHAD4AawwAAAcAQgBqDAAABwBKAGwMAAAHAFAAbQwAAAQAKgDqDAAABwA3AG4MAAAEAB8AbwwAAAMAEwAAAA==.',
Bo='Boose:BAAALgAECgYJBgAAAA==.Bootybreaker:BAAALgADCgcJBwAAAA==.',
Br='Brat:BAAALgAECgEJBAABLgAECgkJUwADAPwUAA==.Brewingmist:BAAALgAECgUJBQABLgAFFAMJBQANAEUTAA==.Bréwmaster:BAAALgAECgcJCAABLgAECgkJIgAIAEoXAA==.',
Bu='Bubbelz:BAAALgAECgMJAwAAAA==.Bubbleez:BAAALgADCgUJBQAAAA==.Bubblôseven:BAAALgAECgEJAQAAAA==.Bucklord:BAABLgAECn8iAAMIAAgJjRkAFwAuAghoDAAABQBMAGkMAAAFAFEAawwAAAYAUQBqDAAABQBMAGwMAAAGAFUAbQwAAAEABADqDAAABQBSAG4MAAABAC4ACAAICY0ZABcALgIIaAwAAAUATABpDAAABQBRAGsMAAAGAFEAagwAAAUATABsDAAABgBVAG0MAAABAAQA6gwAAAQAUgBuDAAAAQAuAAMAAQkAGYNjADwAAeoMAAABAEAAAAA=.Budin:BAAALgAECggJEgAAAA==.Bullmann:BAAALgADCgQJBAAAAA==.',
Ca='Cannibal:BAABLgAECn80AAIOAAkJLhyoDgDRAgloDAAACABTAGkMAAAHAFAAawwAAAgAVQBqDAAABwBDAGwMAAAHAFYAbQwAAAQARwDqDAAABwBTAG4MAAADACsAbwwAAAEALwAOAAkJLhyoDgDRAgloDAAACABTAGkMAAAHAFAAawwAAAgAVQBqDAAABwBDAGwMAAAHAFYAbQwAAAQARwDqDAAABwBTAG4MAAADACsAbwwAAAEALwAAAA==.Caplock:BAABLgAECn8VAAIPAAYJoRFohABRAQZoDAAABAA/AGkMAAAEAB0AawwAAAQALABqDAAAAwAnAGwMAAADACgA6gwAAAMALgAPAAYJoRFohABRAQZoDAAABAA/AGkMAAAEAB0AawwAAAQALABqDAAAAwAnAGwMAAADACgA6gwAAAMALgAAAA==.Capri:BAAALgAECgYJEgAAAA==.',
Ce='Cellun:BAAALgAECgUJEwAAAA==.Centipede:BAAALgAECgYJCQABLgAECgYJFwAQAIAXAA==.Ceredis:BAAALgAECgUJCwAAAA==.',
Ch='Choomoo:BAAALgADCgcJCwABLgAFFAYJFwAHAP8NAA==.',
Cl='Cleankarma:BAAALgADCgEJAwAAAA==.',
Co='Comet:BAAALgAECgEJAQAAAA==.Cool:BAABLgAFFH8FAAIFAAMJ1BMwVgDjAANoDAAAAgAwAGkMAAABAD8A6gwAAAIAKAAFAAMJ1BMwVgDjAANoDAAAAgAwAGkMAAABAD8A6gwAAAIAKAAAAA==.Corwiggs:BAAALgAECgYJCwAAAA==.',
Cr='Crikey:BAAALgAECgYJDAAAAA==.Crimínal:BAAALgADCgcJCwAAAA==.Cripsee:BAAALgADCgMJAwAAAA==.',
Cu='Curbie:BAAALgAECgIJAwAAAA==.',
Cv='Cvdruid:BAAALgAECgQJBAAAAA==.',
Cy='Cyndrixx:BAAALgAECgIJAwAAAA==.',
['Cô']='Cônvict:BAAALgADCgYJBgAAAA==.',
Da='Dargath:BAAALgAECgMJBAAAAA==.',
De='Deacknight:BAABLgAECn8cAAMNAAgJwRuPLgB+AghoDAAAAwBLAGkMAAADAFgAawwAAAMAXwBqDAAABABPAGwMAAAFAGEAbQwAAAQAJQDqDAAABQBRAG4MAAABABUADQAICcEbjy4AfgIIaAwAAAMASwBpDAAAAgBYAGsMAAADAF8AagwAAAQATwBsDAAABQBhAG0MAAAEACUA6gwAAAUAUQBuDAAAAQAVABEAAQmKDYEXADIAAWkMAAABACIAAS4AAwoGCQcAAgAAAAA=.Deacmonk:BAAALgADCgYJBgABLgADCgYJBwACAAAAAA==.Definitely:BAACLgAFFH8SAAIEAAMJgiNMUgAsAQNoDAAABwBfAGkMAAAHAFYA6gwAAAQAWgAEAAMJgiNMUgAsAQNoDAAABwBfAGkMAAAHAFYA6gwAAAQAWgAuAAQKfzoAAwQACQlCJI4JABsDAAQACQlCJI4JABsDABIAAQkPICobAD8AAAAA.Deki:BAEALgAECgYJBgABLgAFFAYJFgAFAG4aAA==.Dementiaous:BAAALgAECgIJAwAAAA==.Desariana:BAABLgAECn8lAAIFAAkJcxB1WgCmAQloDAAABAA3AGkMAAAGADEAawwAAAYAPgBqDAAABQBCAGwMAAAFADQAbQwAAAEAEgDqDAAABgAqAG4MAAADACUAbwwAAAEAEwAFAAkJcxB1WgCmAQloDAAABAA3AGkMAAAGADEAawwAAAYAPgBqDAAABQBCAGwMAAAFADQAbQwAAAEAEgDqDAAABgAqAG4MAAADACUAbwwAAAEAEwAAAA==.',
Di='Diggitie:BAAALgAECgEJAQAAAA==.Ditto:BAABLgAFFH8IAAIHAAQJtA4eKADhAARoDAAAAgAiAGkMAAACACEAawwAAAIAKwDqDAAAAgAmAAcABAm0Dh4oAOEABGgMAAACACIAaQwAAAIAIQBrDAAAAgArAOoMAAACACYAAS4ABRQFCSwAEwDBGwA=.',
Do='Domtop:BAAALgAFFAMJBAABLgAFFAYJFQAHAK0TAA==.Dormas:BAABLgAECn8YAAIUAAcJ3g+WJQADAQdoDAAABQApAGkMAAAFACwAawwAAAUAOABqDAAAAwAcAGwMAAADABsAbQwAAAEAEwDqDAAAAgA2ABQABwneD5YlAAMBB2gMAAAFACkAaQwAAAUALABrDAAABQA4AGoMAAADABwAbAwAAAMAGwBtDAAAAQATAOoMAAACADYAAAA=.Doug:BAAALgADCgEJAQAAAA==.Doxy:BAAALgAECgcJCQAAAA==.',
Dr='Drakeon:BAABLgAECn8UAAIVAAcJ/g7FFQBhAQdoDAAABAA+AGkMAAAEADcAawwAAAQALABqDAAAAgApAGwMAAABABAA6gwAAAQAKQBuDAAAAQAFABUABwn+DsUVAGEBB2gMAAAEAD4AaQwAAAQANwBrDAAABAAsAGoMAAACACkAbAwAAAEAEADqDAAABAApAG4MAAABAAUAAS4ABAoJCXAACQB4IAA=.',
Ee='Eeryxx:BAAALgAECgEJAQAAAA==.',
El='Eldh:BAABLgAECn8fAAMWAAkJbg7NJQBvAQloDAAABgAaAGkMAAAFACYAawwAAAUAJgBqDAAABAAkAGwMAAADACoAbQwAAAEABwDqDAAABAAXAG4MAAACAFYAbwwAAAEAIAAWAAkJgQvNJQBvAQloDAAABgAaAGkMAAAFACYAawwAAAUAJgBqDAAABAAkAGwMAAADACoAbQwAAAEABwDqDAAABAAXAG4MAAABABoAbwwAAAEAIAAKAAEJoiGkbABhAAFuDAAAAQBWAAAA.Eleison:BAAALgADCgMJAwAAAA==.Elendrial:BAAALgAECgIJAgAAAA==.Elendril:BAAALgADCgcJFQAAAA==.Elisoly:BAACLgAFFH8FAAIGAAIJDQx2OABuAAJoDAAAAwA2AOoMAAACAAcABgACCQ0MdjgAbgACaAwAAAMANgDqDAAAAgAHAC4ABAp/JQACBgAGCYIeyh4A+AEABgAGCYIeyh4A+AEAAAA=.',
Em='Emrald:BAAALgAECgYJEwAAAA==.Emridius:BAAALgAECgEJAQABLgAECggJIAAJAGMgAA==.',
En='Endlessly:BAACLgAFFH8QAAIXAAUJ3hREBgAtAQVoDAAABQBOAGkMAAAEADUAawwAAAIAJwBqDAAAAQA4AOoMAAAEACoAFwAFCd4URAYALQEFaAwAAAUATgBpDAAABAA1AGsMAAACACcAagwAAAEAOADqDAAABAAqAC4ABAp/IgACFwAICZ8i6QMA6wIAFwAICZ8i6QMA6wIAAAA=.Enerchi:BAAALgADCgMJAwAAAA==.',
Er='Erivoker:BAAALgAECgYJDAABLgAECgYJEgACAAAAAA==.Errimage:BAAALgAECgYJEgAAAA==.Errishoot:BAAALgAECgUJCQABLgAECgYJEgACAAAAAA==.Ervinia:BAAALgADCgYJCgABLgAECgYJEwACAAAAAA==.',
Ev='Evelinar:BAAALgAECgMJAwAAAA==.Evoslex:BAABLgAECn85AAMYAAkJxCM8BAARAwloDAAABwBeAGkMAAAHAF8AawwAAAcAXABqDAAABwBhAGwMAAAHAF8AbQwAAAUAYQDqDAAACABVAG4MAAAFAFQAbwwAAAQAVwAYAAkJxCM8BAARAwloDAAABQBeAGkMAAAGAF8AawwAAAYAXABqDAAABgBhAGwMAAAGAF8AbQwAAAUAYQDqDAAABgBVAG4MAAAFAFQAbwwAAAQAVwAZAAYJzx1vEwCsAQZoDAAAAgBMAGkMAAABAFQAawwAAAEAVABqDAAAAQBCAGwMAAABADgA6gwAAAIATwAAAA==.',
Ex='Exo:BAECLgAFFH8iAAIaAAcJIhriBgDiAQdoDAAACABbAGkMAAAGAGAAawwAAAYAUgBqDAAAAwAcAGwMAAABABYAbQwAAAEAFwDqDAAACQBUABoABwkiGuIGAOIBB2gMAAAIAFsAaQwAAAYAYABrDAAABgBSAGoMAAADABwAbAwAAAEAFgBtDAAAAQAXAOoMAAAJAFQALgAECn8rAAIaAAkJHCLKAwDvAgAaAAkJHCLKAwDvAgAAAA==.',
Fa='Facerolleh:BAACLgAFFH8wAAMbAAgJ+CEXAQChAghoDAAABwBfAGkMAAANAGMAawwAAAsAWwBqDAAABQAuAGwMAAADAEEAbQwAAAEAWQDqDAAABwBfAG4MAAABAEcAGwAICbMhFwEAoQIIaAwAAAMAXQBpDAAACQBjAGsMAAAKAFsAagwAAAUALgBsDAAAAwBBAG0MAAABAFkA6gwAAAIAWwBuDAAAAQBHAAkABAlmIYwGAIYBBGgMAAAEAF8AaQwAAAQATgBrDAAAAQBIAOoMAAAFAF8ALgAECn9GAAQJAAkJnSXOBABcAwAJAAgJ9iXOBABcAwAbAAgJfyIzBQCiAgAcAAIJjR2/QgBRAAAAAA==.Fatedx:BAAALgAECgEJAQAAAA==.',
Fe='Feelgoodinc:BAAALgADCgkJFAAAAA==.',
Fi='Fidah:BAAALgAECgEJAQAAAA==.Firemagemain:BAAALgADCgUJBQABLgAFFAMJBQAJACoUAA==.',
Fl='Flanann:BAAALgAECgEJAQABLgAECgMJCgACAAAAAA==.Flop:BAAALgAECgUJCQABLgAFFAQJCQAEAC8bAA==.Flora:BAAALgAECgEJAwAAAA==.',
Fr='Frostmere:BAAALgADCggJGQAAAA==.',
Fu='Fuknazum:BAAALgAECgEJAQAAAA==.Furcht:BAABLgAECn8cAAINAAYJGhPLmwAfAQZoDAAABQA1AGkMAAAFACwAawwAAAUANwBqDAAAAwAZAGwMAAADADQA6gwAAAcAJwANAAYJGhPLmwAfAQZoDAAABQA1AGkMAAAFACwAawwAAAUANwBqDAAAAwAZAGwMAAADADQA6gwAAAcAJwAAAA==.',
Ga='Galadar:BAAALgADCgUJBQAAAA==.',
Gi='Giteff:BAABLgAFFH8WAAILAAgJvyRTAQD/AghoDAAABABjAGkMAAAEAGMAawwAAAMAYQBqDAAAAwBYAGwMAAABAFoAbQwAAAIAWwDqDAAAAwBjAG8MAAACAFAACwAICb8kUwEA/wIIaAwAAAQAYwBpDAAABABjAGsMAAADAGEAagwAAAMAWABsDAAAAQBaAG0MAAACAFsA6gwAAAMAYwBvDAAAAgBQAAAA.Gitèff:BAABLgAFFH8QAAILAAcJ0Bo7DQAPAgdoDAAABABdAGkMAAACAF4AawwAAAIAOwBqDAAAAgBCAGwMAAABABMAbQwAAAEASgDqDAAABABHAAsABwnQGjsNAA8CB2gMAAAEAF0AaQwAAAIAXgBrDAAAAgA7AGoMAAACAEIAbAwAAAEAEwBtDAAAAQBKAOoMAAAEAEcAAS4ABRQICRYACwC/JAA=.Giveroflife:BAAALgAECgYJCwAAAA==.',
Go='Gourdin:BAAALgAECgQJBQABLgAECgYJCAACAAAAAA==.',
Gr='Gramnpa:BAAALgADCgUJBQAAAA==.Grandpriest:BAAALgAECgMJAwABLgAECgkJPQAFALMeAA==.Gravepriest:BAAALgAECgEJAQAAAA==.Grimtysha:BAAALgAECgYJEAAAAA==.Grimveil:BAAALgAECgYJDQAAAA==.Gromit:BAAALgAECgQJCQAAAA==.Gröuch:BAABLgAFFH8IAAIWAAQJXQo7KADzAARoDAAAAgAeAGkMAAACACoAawwAAAIADQDqDAAAAgAUABYABAldCjsoAPMABGgMAAACAB4AaQwAAAIAKgBrDAAAAgANAOoMAAACABQAAAA=.',
Ha='Harafar:BAACLgAFFH8FAAITAAUJEAQYLQCpAAVoDAAAAQACAGkMAAABAAQAawwAAAEABgBqDAAAAQAGAOoMAAABABsAEwAFCRAEGC0AqQAFaAwAAAEAAgBpDAAAAQAEAGsMAAABAAYAagwAAAEABgDqDAAAAQAbAC4ABAp/HgADEwAJCe0ZGxQAHAIAEwAJCe0ZGxQAHAIADgADCXkHM5oAbAAAAAA=.',
He='Hellbourne:BAABLgAECn8kAAILAAkJ8hj1JAAmAgloDAAABgBBAGkMAAAFAEAAawwAAAUANQBqDAAABAAxAGwMAAAEAEwAbQwAAAMAKwDqDAAABQBJAG4MAAADADsAbwwAAAEASQALAAkJ8hj1JAAmAgloDAAABgBBAGkMAAAFAEAAawwAAAUANQBqDAAABAAxAGwMAAAEAEwAbQwAAAMAKwDqDAAABQBJAG4MAAADADsAbwwAAAEASQAAAA==.',
Hi='Himmel:BAAALgADCgcJCQAAAA==.',
Ho='Hopnhorsé:BAAALgAECgQJBQAAAA==.Hotchoq:BAABLgAFFH8HAAIEAAIJ3QtIkgCPAAJoDAAAAwAgAOoMAAAEABwABAACCd0LSJIAjwACaAwAAAMAIADqDAAABAAcAAAA.',
Hu='Huntchoq:BAABLgAFFH8NAAQdAAUJKw/xEgAqAQVoDAAAAwA1AGkMAAADACIAawwAAAIAFQBqDAAAAQAGAOoMAAAEACwAHQAFCU4N8RIAKgEFaAwAAAIANQBpDAAAAgAYAGsMAAACABUAagwAAAEABgDqDAAAAwAkAB4AAglVCDF2AIEAAmgMAAABAAcAaQwAAAEAIgAfAAEJlBHqLwA8AAHqDAAAAQAsAAAA.Huxley:BAAALgADCgMJAwAAAA==.',
Ik='Ikan:BAAALgAECgYJEQAAAA==.',
In='Infest:BAAALgAECgQJCAAAAA==.Inzolethys:BAAALgADCgcJBwAAAA==.',
It='Itchy:BAAALgADCgEJAgAAAA==.Itskiohte:BAABLgAECn8pAAIgAAkJVw6nDQC8AQloDAAABQAwAGkMAAAFAD8AawwAAAUALwBqDAAABQAiAGwMAAAFABoAbQwAAAIADADqDAAABgAiAG4MAAAGACEAbwwAAAIAHAAgAAkJVw6nDQC8AQloDAAABQAwAGkMAAAFAD8AawwAAAUALwBqDAAABQAiAGwMAAAFABoAbQwAAAIADADqDAAABgAiAG4MAAAGACEAbwwAAAIAHAAAAA==.',
Ja='Jaggernut:BAAALgADCgUJBQAAAA==.',
Ji='Jimmbo:BAAALgAECgQJBAAAAA==.',
Jo='Johnny:BAAALgAECgIJAgABLgAECgkJOQAYAMQjAA==.',
Ju='Judeau:BAAALgADCgEJAQAAAA==.',
Ka='Kaelthuzzad:BAAALgADCgEJAQAAAA==.Kaitza:BAAALgAECgYJCwAAAA==.Kalzaketh:BAABLgAECn9BAAMYAAkJ7gugMgBMAQloDAAADAAhAGkMAAAKACIAawwAAAoAJwBqDAAABwAaAGwMAAAHACAAbQwAAAIAHQDqDAAACQATAG4MAAAHAC8AbwwAAAEABwAYAAkJ7gugMgBMAQloDAAACAAhAGkMAAAIACIAawwAAAgAJwBqDAAABwAaAGwMAAAHACAAbQwAAAIAHQDqDAAACQATAG4MAAAHAC8AbwwAAAEABwAZAAMJ5QSIMwB5AANoDAAABAAFAGkMAAACAA4AawwAAAIAEgAAAA==.Kashari:BAAALgAECgYJCwABLgAECgkJfAAIABUcAA==.Katali:BAABLgAECn8VAAMFAAcJSQyJnQAhAQdoDAAAAgAMAGkMAAACACYAawwAAAQALgBqDAAABAAbAGwMAAADACgAbQwAAAIAGQDqDAAABAAZAAUABwlJDImdACEBB2gMAAABAAwAaQwAAAEAJgBrDAAAAwAuAGoMAAADABsAbAwAAAIAKABtDAAAAgAZAOoMAAADABkABgAGCQsFXFUAywAGaAwAAAEAFgBpDAAAAQALAGsMAAABAAgAagwAAAEABABsDAAAAQAYAOoMAAABAAYAAAA=.Kazuggar:BAACLgAFFH8eAAIQAAUJ+iLYCgDtAQVoDAAACABbAGkMAAAIAEwAawwAAAUAWgBqDAAAAwBhAOoMAAAGAFwAEAAFCfoi2AoA7QEFaAwAAAgAWwBpDAAACABMAGsMAAAFAFoAagwAAAMAYQDqDAAABgBcAC4ABAp/OAADEAAJCawlbgIAXAMAEAAICYIlbgIAXAMAIQAGCQAVaC4AcQEAAAA=.Kazzn:BAAALgAFFAIJAgAAAA==.',
Ke='Kedar:BAAALgAECgYJEQAAAA==.Keg:BAAALgAECgIJAgAAAA==.Kelabar:BAAALgADCgQJBAAAAA==.',
Ki='Kick:BAAALgADCgQJBAABLgAFFAcJGAAEALcWAA==.Kiffs:BAAALgAECgcJCgAAAA==.Kill:BAAALgAFFAEJAgAAAA==.Killerman:BAABLgAFFH8VAAMRAAgJHCLhAAA8AghoDAAAAwBiAGkMAAADAGMAawwAAAMAYABqDAAAAgBPAG0MAAACAD8A6gwAAAMAYwBuDAAAAwBGAG8MAAACAFIAEQAGCU0l4QAAPAIGaAwAAAMAYgBpDAAAAwBjAGsMAAACAGAAagwAAAEATwDqDAAAAwBjAG8MAAACAFIADQAECRYd5WoADAEEawwAAAEAWQBqDAAAAQBMAG0MAAACAD8AbgwAAAMARgAAAA==.Kirâ:BAABLgAECn8UAAIJAAgJCxygGQAOAghoDAAAAwBaAGkMAAAFAFEAawwAAAMARgBqDAAAAgBUAGwMAAACAEoAbQwAAAEALADqDAAAAwBYAG4MAAABADUACQAICQscoBkADgIIaAwAAAMAWgBpDAAABQBRAGsMAAADAEYAagwAAAIAVABsDAAAAgBKAG0MAAABACwA6gwAAAMAWABuDAAAAQA1AAEuAAQKBwkTAAIAAAAA.',
Kr='Kregnar:BAABLgAECn8pAAIbAAkJBRzLBgB6AgloDAAACABNAGkMAAAGAD0AawwAAAYASQBqDAAABAA5AGwMAAAEAFIAbQwAAAMARwDqDAAABgBJAG4MAAADAE8AbwwAAAEANgAbAAkJBRzLBgB6AgloDAAACABNAGkMAAAGAD0AawwAAAYASQBqDAAABAA5AGwMAAAEAFIAbQwAAAMARwDqDAAABgBJAG4MAAADAE8AbwwAAAEANgAAAA==.Kresh:BAAALgAECgcJCwAAAA==.',
Ku='Kucabara:BAAALgAECgIJAwAAAA==.Kuraiwiggs:BAAALgADCgYJDAAAAA==.',
Kw='Kwichang:BAABLgAECn8ZAAIEAAcJuw9OjABFAQdoDAAABQAuAGkMAAAFACcAawwAAAUAKgBqDAAAAgA/AGwMAAADAB4AbQwAAAEAFwDqDAAABAA7AAQABwm7D06MAEUBB2gMAAAFAC4AaQwAAAUAJwBrDAAABQAqAGoMAAACAD8AbAwAAAMAHgBtDAAAAQAXAOoMAAAEADsAAAA=.',
Ky='Kyndariae:BAAALgAECgUJBQAAAA==.',
['Ké']='Kélpo:BAAALgADCgMJBAAAAA==.',
La='Lasagne:BAAALgADCgMJAwAAAA==.',
Le='Lesley:BAAALgAECgEJAQAAAA==.',
Li='Lickynose:BAABLgAECn8pAAIEAAkJYyF1EQDgAgloDAAABgBbAGkMAAAFAFwAawwAAAQATwBqDAAABQBaAGwMAAAFAFkAbQwAAAQAPwDqDAAABwBdAG4MAAAEAFgAbwwAAAEAVQAEAAkJYyF1EQDgAgloDAAABgBbAGkMAAAFAFwAawwAAAQATwBqDAAABQBaAGwMAAAFAFkAbQwAAAQAPwDqDAAABwBdAG4MAAAEAFgAbwwAAAEAVQAAAA==.Lips:BAAALgAECgEJAQAAAA==.',
Ls='Ls:BAABLgAECn8iAAQMAAkJaiPnBwCYAgloDAAABQBhAGkMAAAEAF8AawwAAAMAVQBqDAAABABeAGwMAAAEAF8AbQwAAAMARgDqDAAABgBaAG4MAAAEAFsAbwwAAAEAYgAMAAgJ3R/nBwCYAghoDAAAAQBeAGkMAAABAF8AagwAAAEAXgBsDAAAAQBfAG0MAAABABoA6gwAAAEAWQBuDAAAAQBHAG8MAAABAGIACwAICZwhvTEAMwIIaAwAAAMAYQBpDAAAAgBdAGsMAAACAFUAagwAAAIAXQBsDAAAAgBJAG0MAAABAEYA6gwAAAQAWgBuDAAAAwBbACIABwliFdUMAHABB2gMAAABAF4AaQwAAAEAIQBrDAAAAQBIAGoMAAABAB0AbAwAAAEAKQBtDAAAAQAdAOoMAAABADgAAAA=.',
Ly='Lythium:BAAALgAECgEJAQAAAA==.',
Ma='Madarabia:BAAALgAECgYJDQAAAA==.Magnius:BAAALgAECgMJAwAAAA==.Makcik:BAAALgAECgEJAQAAAA==.Mamut:BAAALgAECgEJAQAAAA==.Mantisar:BAACLgAFFH8IAAIFAAMJ5RJ9VgDjAANoDAAABABQAGkMAAACACcA6gwAAAIAGAAFAAMJ5RJ9VgDjAANoDAAABABQAGkMAAACACcA6gwAAAIAGAAuAAQKfx4AAgUABwnmHvQ1ABECAAUABwnmHvQ1ABECAAAA.Maxsm:BAABLgAECn8XAAIhAAgJrhmSIQACAghoDAAABABWAGkMAAAEAFcAawwAAAMAWABqDAAAAwA0AGwMAAADAEEAbQwAAAEAHgDqDAAABABgAG4MAAABAAQAIQAICa4ZkiEAAgIIaAwAAAQAVgBpDAAABABXAGsMAAADAFgAagwAAAMANABsDAAAAwBBAG0MAAABAB4A6gwAAAQAYABuDAAAAQAEAAAA.',
Me='Melanippe:BAABLgAECn8XAAIOAAYJDxtuPQCuAQZoDAAABAA9AGkMAAAEAEcAawwAAAQAOwBqDAAAAwBEAGwMAAADAFAA6gwAAAUASQAOAAYJDxtuPQCuAQZoDAAABAA9AGkMAAAEAEcAawwAAAQAOwBqDAAAAwBEAGwMAAADAFAA6gwAAAUASQAAAA==.Meleefox:BAAALgADCgUJBQAAAA==.Melethron:BAABLgAECn8+AAIFAAkJgRwqIQBsAgloDAAACQBUAGkMAAAIAE0AawwAAAgAWQBqDAAACABcAGwMAAAIAFIAbQwAAAQAQADqDAAACABEAG4MAAAFAE4AbwwAAAQAJQAFAAkJgRwqIQBsAgloDAAACQBUAGkMAAAIAE0AawwAAAgAWQBqDAAACABcAGwMAAAIAFIAbQwAAAQAQADqDAAACABEAG4MAAAFAE4AbwwAAAQAJQAAAA==.Melioknky:BAAALgAECgYJBgAAAA==.',
Mi='Mid:BAAALgADCgYJBgAAAA==.Mightymage:BAABLgAECn8hAAIEAAgJ4Q1mfgBiAQhoDAAABQAnAGkMAAAFACAAawwAAAUAMABqDAAAAwAxAGwMAAADAB8AbQwAAAEAHQDqDAAABgA1AG4MAAAFAA0ABAAICeENZn4AYgEIaAwAAAUAJwBpDAAABQAgAGsMAAAFADAAagwAAAMAMQBsDAAAAwAfAG0MAAABAB0A6gwAAAYANQBuDAAABQANAAAA.Millionbaby:BAAALgAECgEJAQAAAA==.Milliondruid:BAAALgAECgMJBAAAAA==.Millionsm:BAAALgADCgQJBQAAAA==.Mirrorimage:BAAALgAFFAEJAgABLgAFFAYJEgAIAAgVAA==.Mirrorx:BAACLgAFFH8SAAIIAAYJCBVmDABzAQZoDAAABQBBAGkMAAADAD0AawwAAAIAGgBqDAAAAQAjAGwMAAABADMA6gwAAAYAQQAIAAYJCBVmDABzAQZoDAAABQBBAGkMAAADAD0AawwAAAIAGgBqDAAAAQAjAGwMAAABADMA6gwAAAYAQQAuAAQKfzIAAggACQlzINoHALsCAAgACQlzINoHALsCAAAA.Miy:BAAALgAECgEJAQAAAA==.',
Mo='Mongon:BAAALgAECgYJBgAAAA==.Moogle:BAAALgAECgIJBAAAAA==.Moomie:BAABLgAECn8iAAIOAAgJAxaINAC4AQhoDAAABQBJAGkMAAAGAEYAawwAAAYARABqDAAABQAuAGwMAAAEAD0AbQwAAAIAGADqDAAABQA0AG4MAAABADYADgAICQMWiDQAuAEIaAwAAAUASQBpDAAABgBGAGsMAAAGAEQAagwAAAUALgBsDAAABAA9AG0MAAACABgA6gwAAAUANABuDAAAAQA2AAAA.Moosfel:BAABLgAECn8jAAIXAAcJGhooDQDEAQdoDAAABwBSAGkMAAAHAEMAawwAAAcASgBqDAAABQA9AGwMAAADAC8A6gwAAAUAQQBuDAAAAQA/ABcABwkaGigNAMQBB2gMAAAHAFIAaQwAAAcAQwBrDAAABwBKAGoMAAAFAD0AbAwAAAMALwDqDAAABQBBAG4MAAABAD8AAAA=.',
Mt='Mtzz:BAAALgAECgUJBQABLgAECgYJCAACAAAAAA==.',
Mu='Mudcake:BAAALgAECgEJAQAAAA==.',
My='Mygravebroke:BAAALgADCggJCQAAAA==.Mystdragon:BAACLgAFFH8TAAMVAAUJxRv3DgCJAQVoDAAABgBjAGkMAAAFAEcAawwAAAMANgBqDAAAAQAlAOoMAAAEAFwAFQAFCcUb9w4AiQEFaAwAAAUAYwBpDAAABABHAGsMAAADADYAagwAAAEAJQDqDAAAAgBcABgAAwmUC0M9ALQAA2gMAAABADoAaQwAAAEACADqDAAAAgAWAC4ABAp/MAACFQAJCbkhHgMAEgMAFQAJCbkhHgMAEgMAAS4ABRQICScABwCaHQA=.Mystweaverr:BAACLgAFFH8nAAMHAAgJmh32AgDFAghoDAAABQBHAGkMAAAHAFEAawwAAAgAYQBqDAAABwBZAGwMAAADAFoAbQwAAAEASwDqDAAABwBiAG4MAAABAAAABwAICZod9gIAxQIIaAwAAAQARwBpDAAABwBRAGsMAAAIAGEAagwAAAcAWQBsDAAAAwBaAG0MAAABAEsA6gwAAAcAYgBuDAAAAQAAAAoAAQn1BLo7ADcAAWgMAAABAAwALgAECn8vAAMHAAkJ9x+ACQC5AgAHAAkJ9x+ACQC5AgAKAAIJIyKJTgC2AAAAAA==.',
['Mö']='Mörae:BAAALgADCgEJAQABLgAECgYJFwAOAA8bAA==.',
Na='Naddar:BAACLgAFFH8QAAIGAAUJKhi3EwB2AQVoDAAABQBSAGkMAAAEACgAawwAAAMAQQBqDAAAAQA8AOoMAAADAD0ABgAFCSoYtxMAdgEFaAwAAAUAUgBpDAAABAAoAGsMAAADAEEAagwAAAEAPADqDAAAAwA9AC4ABAp/QgACBgAJCd4dAggA+QIABgAJCd4dAggA+QIAAAA=.Namadgi:BAABLgAECn8hAAIOAAkJVRpzEwCfAgloDAAABABGAGkMAAAEAFcAawwAAAMARQBqDAAABAA1AGwMAAAEAD0AbQwAAAQAJwDqDAAABgBeAG4MAAADAEYAbwwAAAEAOwAOAAkJVRpzEwCfAgloDAAABABGAGkMAAAEAFcAawwAAAMARQBqDAAABAA1AGwMAAAEAD0AbQwAAAQAJwDqDAAABgBeAG4MAAADAEYAbwwAAAEAOwAAAA==.Nathria:BAAALgAECgIJAwAAAA==.',
Ne='Netalis:BAABLgAECn8lAAIOAAgJwxQULgDcAQhoDAAABgBAAGkMAAAFAEMAawwAAAQALQBqDAAABQA0AGwMAAAFADoAbQwAAAMAGwDqDAAABwA1AG4MAAACADcADgAICcMUFC4A3AEIaAwAAAYAQABpDAAABQBDAGsMAAAEAC0AagwAAAUANABsDAAABQA6AG0MAAADABsA6gwAAAcANQBuDAAAAgA3AAAA.',
Ni='Nikonii:BAAALgAECgEJAQAAAA==.',
Nu='Nurckers:BAAALgAECgcJCAAAAA==.',
Oa='Oakinelf:BAAALgADCgcJAQAAAA==.',
Om='Omnishifts:BAAALgAECgEJAgAAAA==.',
Or='Oramo:BAABLgAECn8fAAMaAAgJfCMmBQDwAghoDAAABwBeAGkMAAAFAFwAawwAAAQAYgBqDAAAAwBYAGwMAAADAGEAbQwAAAIAUQDqDAAABQBfAG4MAAACAEsAGgAICcUiJgUA8AIIaAwAAAQAUQBpDAAAAgBcAGsMAAABAGIAagwAAAEAQABsDAAAAQBhAG0MAAACAFEA6gwAAAMAXwBuDAAAAgBLAA0ABgmAIqljAI8BBmgMAAADAF4AaQwAAAMAWwBrDAAAAwBdAGoMAAACAFgAbAwAAAIAUgDqDAAAAgBPAAAA.',
Ov='Ovaries:BAAALgADCgUJBQABLgAECgQJBQACAAAAAA==.',
Pa='Paktam:BAABLgAECn8XAAIQAAcJzh3XGgBcAgdoDAAAAwBWAGkMAAAEAE0AawwAAAQAWwBqDAAABABcAGwMAAABACQAbQwAAAEAPADqDAAABgBaABAABwnOHdcaAFwCB2gMAAADAFYAaQwAAAQATQBrDAAABABbAGoMAAAEAFwAbAwAAAEAJABtDAAAAQA8AOoMAAAGAFoAAAA=.Paméla:BAAALgAECgcJDgABLgAECgkJcAAJAHggAA==.Paradisya:BAAALgADCggJDgAAAA==.',
Pe='Perceptor:BAAALgAECgEJAQABLgAECgkJKQAUAJMhAA==.Pets:BAAALgAECgEJAQABLgAECgkJUwADAPwUAA==.',
Pl='Placebo:BAAALgAECgUJBQABLgAFFAUJEAAXAN4UAA==.',
Pr='Prothero:BAACLgAFFH8QAAMEAAUJJiDxNgBnAQVoDAAABABUAGkMAAAEAGIAawwAAAIAPQBqDAAAAQBbAOoMAAAFAFQABAAFCSYg8TYAZwEFaAwAAAQAVABpDAAABABiAGsMAAACAD0AagwAAAEAWwDqDAAABABUABIAAQllGQkEAE4AAeoMAAABAEEALgAECn8WAAMEAAkJxiAZFwC7AgAEAAkJxiAZFwC7AgASAAgJKxgDAwBQAgAAAA==.Proyo:BAAALgADCgUJBQAAAA==.',
['På']='Påthor:BAACLgAFFH8HAAITAAIJkw85NQB4AAJoDAAABQAnAOoMAAACACcAEwACCZMPOTUAeAACaAwAAAUAJwDqDAAAAgAnAC4ABAp/IwADEwAHCXocHR8AtgEAEwAHCXocHR8AtgEAFAADCRISF0sAXQAAAAA=.',
Ra='Raikonnen:BAAALgAECgEJAQAAAA==.Rapidstrikes:BAAALgAECgMJBAAAAA==.Rawtoor:BAACLgAFFH8eAAILAAcJYRdKFgDAAQdoDAAABgBTAGkMAAAGAF8AawwAAAQALQBqDAAABABBAGwMAAABABUAbQwAAAEAIQDqDAAACABOAAsABwlhF0oWAMABB2gMAAAGAFMAaQwAAAYAXwBrDAAABAAtAGoMAAAEAEEAbAwAAAEAFQBtDAAAAQAhAOoMAAAIAE4ALgAECn8hAAILAAgJOCHSJwBlAgALAAgJOCHSJwBlAgAAAA==.',
Re='Rebelsister:BAAALgADCgcJEAAAAA==.Refridgerate:BAAALgADCgUJBwAAAA==.',
Ri='Riddagain:BAABLgAECn8bAAMiAAYJeA/1FAAHAQZoDAAABQAZAGkMAAAEADMAawwAAAQAJgBqDAAAAwAMAGwMAAADACwA6gwAAAgAJQAiAAYJTw/1FAAHAQZoDAAABAAZAGkMAAAEADMAawwAAAQAJgBqDAAAAwAMAGwMAAADACwA6gwAAAUAIwALAAIJwAt7BAErAAJoDAAAAQAWAOoMAAADACUAAAA=.Ridgemonk:BAABLgAECn87AAMWAAkJniPaAQA/AwloDAAABwBjAGkMAAAIAF0AawwAAAgAYQBqDAAABgBdAGwMAAAHAFYAbQwAAAYAVwDqDAAACABfAG4MAAAGAFgAbwwAAAMAUQAWAAkJniPaAQA/AwloDAAABgBjAGkMAAAHAF0AawwAAAcAYQBqDAAABgBdAGwMAAAHAFYAbQwAAAYAVwDqDAAABwBfAG4MAAAGAFgAbwwAAAMAUQAHAAQJQAGYYABMAARoDAAAAQAEAGkMAAABAAIAawwAAAEAAADqDAAAAQAEAAAA.Riggsdk:BAAALgADCgcJBwABLgAFFAgJGwAeAKAiAA==.Riggse:BAAALgAFFAEJAQABLgAFFAgJGwAeAKAiAA==.Riggshunt:BAACLgAFFH8bAAQeAAgJoCLTAACrAQhoDAAABgBjAGkMAAAFAGEAawwAAAQAVwBqDAAAAwA2AGwMAAABAFYAbQwAAAEAUgDqDAAABgBjAG4MAAABAEMAHQAGCSwkLgAA+wEGaAwAAAQAYwBpDAAABABhAGsMAAADAFIAagwAAAIANgBsDAAAAQBWAOoMAAAEAGEAHgAGCfEg0wAAqwEGaAwAAAIAYgBpDAAAAQBGAGsMAAABAFcAbQwAAAEAUgDqDAAAAgBjAG4MAAABAEMAHwABCQAAvygASgABagwAAAEADwAuAAQKfx4ABB4ACAmrJr0IAAcDAB4ABwmYJr0IAAcDAB0ACAmTJIQDAPICAB8AAQmCHGd9AE8AAAAA.Riggspal:BAAALgAFFAIJAgABLgAFFAgJGwAeAKAiAA==.Riggswar:BAAALgAFFAEJAQABLgAFFAgJGwAeAKAiAA==.Riggzs:BAAALgAFFAIJAgABLgAFFAgJGwAeAKAiAA==.',
Ro='Roadkill:BAABLgAECn8gAAIaAAgJnSM4BAALAwhoDAAABQBhAGkMAAAFAF8AawwAAAUAXQBqDAAABABcAGwMAAAEAFAAbQwAAAIAWADqDAAABQBiAG4MAAACAFUAGgAICZ0jOAQACwMIaAwAAAUAYQBpDAAABQBfAGsMAAAFAF0AagwAAAQAXABsDAAABABQAG0MAAACAFgA6gwAAAUAYgBuDAAAAgBVAAAA.Rolltoor:BAABLgAFFH8FAAIKAAMJJRZwKgCDAANoDAAAAwBPAGkMAAABADMA6gwAAAEAJwAKAAMJJRZwKgCDAANoDAAAAwBPAGkMAAABADMA6gwAAAEAJwAAAA==.Roonate:BAAALgADCgUJBQAAAA==.Rosemary:BAAALgAECgQJBAAAAA==.',
Ry='Ryujin:BAAALgAECgQJCQAAAA==.',
Sa='Saiko:BAABLgAFFH8SAAIMAAUJdhm9CgA1AQVoDAAABABKAGkMAAAEAEUAawwAAAQAOABqDAAAAQASAOoMAAAFADwADAAFCXYZvQoANQEFaAwAAAQASgBpDAAABABFAGsMAAAEADgAagwAAAEAEgDqDAAABQA8AAAA.Sansa:BAACLgAFFH8TAAIdAAcJZhg5AwDKAQdoDAAABABaAGkMAAAEAFUAawwAAAIAPABqDAAAAgBcAGwMAAABAAAAbQwAAAEAKgDqDAAABQBeAB0ABwlmGDkDAMoBB2gMAAAEAFoAaQwAAAQAVQBrDAAAAgA8AGoMAAACAFwAbAwAAAEAAABtDAAAAQAqAOoMAAAFAF4ALgAECn8jAAIdAAkJZyNNAgAjAwAdAAkJZyNNAgAjAwAAAA==.Saso:BAACLgAFFH8VAAIEAAYJ2xz1KwCNAQZoDAAABQBTAGkMAAAFAFkAawwAAAQAWQBqDAAAAgBOAG0MAAABABkA6gwAAAQAUQAEAAYJ2xz1KwCNAQZoDAAABQBTAGkMAAAFAFkAawwAAAQAWQBqDAAAAgBOAG0MAAABABkA6gwAAAQAUQAuAAQKfzQABAQACQmUIgEQAOkCAAQACQmUIgEQAOkCABIAAwkDH0gMAA0BACMAAgnECLALAHcAAAAA.Sastroll:BAAALgAECgUJBQAAAA==.',
Sc='Scorn:BAAALgADCgcJCAAAAA==.Scroll:BAABLgAECn8bAAIHAAgJPBrZGQAmAghoDAAABQBRAGkMAAAEAE4AawwAAAQAUQBqDAAAAwBIAGwMAAACAEIAbQwAAAIALwDqDAAABABDAG4MAAADACoABwAICTwa2RkAJgIIaAwAAAUAUQBpDAAABABOAGsMAAAEAFEAagwAAAMASABsDAAAAgBCAG0MAAACAC8A6gwAAAQAQwBuDAAAAwAqAAAA.',
Se='Seluvis:BAABLgAECn8WAAIEAAcJ0QGU+wCQAAdoDAAABAAEAGkMAAAEAAUAawwAAAIAAwBqDAAAAgABAGwMAAAGAAYAbQwAAAEAAwDqDAAAAwAEAAQABwnRAZT7AJAAB2gMAAAEAAQAaQwAAAQABQBrDAAAAgADAGoMAAACAAEAbAwAAAYABgBtDAAAAQADAOoMAAADAAQAAAA=.Sentai:BAAALgADCgcJBwAAAA==.Serapayne:BAAALgAECgcJAQAAAA==.',
Sh='Shadow:BAACLgAFFH8aAAILAAYJYhfMHQCRAQZoDAAABABCAGkMAAAEAF8AawwAAAQAQgBqDAAABgBNAGwMAAACAAkA6gwAAAYAPQALAAYJYhfMHQCRAQZoDAAABABCAGkMAAAEAF8AawwAAAQAQgBqDAAABgBNAGwMAAACAAkA6gwAAAYAPQAuAAQKf10AAgsACQlmJBgDAEkDAAsACQlmJBgDAEkDAAAA.Shandrilah:BAAALgADCgQJBAAAAA==.Shapeshift:BAAALgADCgUJBQABLgAECgIJAgACAAAAAA==.Shialebuff:BAABLgAECn9BAAQIAAkJ5xgrDwBMAgloDAAACABTAGkMAAAJAFsAawwAAAoAVABqDAAACABCAGwMAAAIAEIAbQwAAAUAIgDqDAAACAA0AG4MAAAGAEQAbwwAAAMAHQAIAAkJ5xgrDwBMAgloDAAABABTAGkMAAAEAFsAawwAAAUAVABqDAAAAwBCAGwMAAADAEIAbQwAAAEAIgDqDAAABQA0AG4MAAAFAEQAbwwAAAEAHQADAAkJzB+8EABLAgloDAAABABXAGkMAAAEAGMAawwAAAQAVQBqDAAABABAAGwMAAADAFUAbQwAAAQAVgDqDAAAAwBaAG4MAAABAFEAbwwAAAIANAABAAQJFxk2MwAqAQRpDAAAAQArAGsMAAABAEUAagwAAAEANwBsDAAAAgBYAAAA.Shijin:BAAALgAECgQJBQAAAA==.Shortfuze:BAAALgAECgYJDQAAAA==.',
Si='Sindar:BAAALgADCgUJBQAAAA==.Sinfall:BAAALgAECggJDgAAAA==.Siphon:BAAALgAECgEJAwAAAA==.Siscomp:BAABLgAECn9wAAIJAAkJeCBDDgB7AgloDAAADgBWAGkMAAANAFwAawwAAA8ASgBqDAAADQBDAGwMAAANAEwAbQwAAAwAVQDqDAAADgBOAG4MAAALAFQAbwwAAAcAVQAJAAkJeCBDDgB7AgloDAAADgBWAGkMAAANAFwAawwAAA8ASgBqDAAADQBDAGwMAAANAEwAbQwAAAwAVQDqDAAADgBOAG4MAAALAFQAbwwAAAcAVQAAAA==.Sixth:BAABLgAECn8XAAIhAAcJ/BoJIwC2AQdoDAAAAgBIAGkMAAAEAEYAawwAAAUASABqDAAABAAkAGwMAAAEAEoAbQwAAAEAKgDqDAAAAwBSACEABwn8GgkjALYBB2gMAAACAEgAaQwAAAQARgBrDAAABQBIAGoMAAAEACQAbAwAAAQASgBtDAAAAQAqAOoMAAADAFIAAAA=.Sizzle:BAAALgADCgMJAwAAAA==.',
Sk='Skateboard:BAAALgADCgEJAQAAAA==.Sky:BAACLgAFFH8fAAIBAAcJlxrEBwBmAgdoDAAABgA/AGkMAAAFAFMAawwAAAYAXwBqDAAABQBeAGwMAAAEAEUAbQwAAAEAFgDqDAAABAAvAAEABwmXGsQHAGYCB2gMAAAGAD8AaQwAAAUAUwBrDAAABgBfAGoMAAAFAF4AbAwAAAQARQBtDAAAAQAWAOoMAAAEAC8ALgAECn8UAAMBAAgJcROPHACwAQABAAcJWRKPHACwAQADAAUJ8g+ITAAGAQAAAA==.',
Sl='Sleck:BAAALgAECgYJDAAAAA==.',
Sm='Smooth:BAAALgAECgEJAQABLgAFFAYJBwABAEcTAA==.',
Sn='Snappa:BAAALgADCgYJCwAAAA==.Sniped:BAAALgAFFAEJAQAAAA==.Snugglepuff:BAAALgAECgkJEwAAAA==.',
So='Soapfidas:BAAALgADCggJCgAAAA==.Sonarius:BAACLgAFFH8JAAIEAAQJLxs2QwBGAQRoDAAAAwBQAGkMAAACAEkAawwAAAEAPADqDAAAAwA/AAQABAkvGzZDAEYBBGgMAAADAFAAaQwAAAIASQBrDAAAAQA8AOoMAAADAD8ALgAECn8dAAQEAAgJ3R8pPACGAgAEAAgJ3R8pPACGAgASAAIJAh24CwClAAAjAAEJshIPDwA8AAAAAA==.Sophie:BAAALgAECgEJAwAAAA==.',
Sp='Splitterman:BAABLgAFFH8LAAMRAAYJfxN4CAA+AQZoDAAAAgBGAGkMAAACAFIAawwAAAIAIgBqDAAAAQA1AG0MAAABAAQA6gwAAAMAOQARAAUJ+hd4CAA+AQVoDAAAAgBGAGkMAAACAFIAawwAAAIAIgBqDAAAAQA1AOoMAAADADkADQABCZEBgvwAKQABbQwAAAEABAAAAA==.',
Su='Su:BAABLgAECn8yAAIHAAcJ4yVlBwDiAgdoDAAACwBhAGkMAAAKAGMAawwAAAoAYQBqDAAACABiAGwMAAAFAGEA6gwAAAUAYQBuDAAAAQBaAAcABwnjJWUHAOICB2gMAAALAGEAaQwAAAoAYwBrDAAACgBhAGoMAAAIAGIAbAwAAAUAYQDqDAAABQBhAG4MAAABAFoAAAA=.Sudno:BAAALgAECgQJCAABLgAFFAcJGwAPAPAYAA==.Sundae:BAABLgAECn83AAQDAAkJlSF4BwDmAgloDAAACABfAGkMAAAIAFgAawwAAAgAXQBqDAAABwBTAGwMAAAGAFoAbQwAAAIATgDqDAAACABhAG4MAAAGAFsAbwwAAAIANgADAAgJHCN4BwDmAghoDAAABABfAGkMAAADAFgAawwAAAQAXQBqDAAABQBTAGwMAAAEAFoAbQwAAAIATgDqDAAABQBhAG4MAAAEAFsAAQAICYcbwgwAhgIIaAwAAAMAWgBpDAAABABLAGsMAAADAFMAagwAAAIASwBsDAAAAgBQAOoMAAADACQAbgwAAAIAQgBvDAAAAgA2AAgAAwncFpZNALQAA2gMAAABADAAaQwAAAEASABrDAAAAQA2AAAA.Sunwukong:BAAALgAECgUJCQAAAA==.Supersinpe:BAAALgAECgIJAgAAAA==.',
Sv='Svdrag:BAAALgAECgMJAwAAAA==.Svendlefyre:BAAALgADCgcJDgABLgAECgkJLgAXAIMZAA==.Svholydrag:BAAALgADCgEJAQAAAA==.Svmishima:BAAALgAECgMJBQAAAA==.',
Sw='Swirly:BAAALgAECgEJAQAAAA==.',
Sy='Sylvie:BAABLgAECn8nAAIeAAkJwRV+IwBAAgloDAAABAA+AGkMAAAEADgAawwAAAQAOQBqDAAABAAyAGwMAAAEACIAbQwAAAQAOgDqDAAABgBaAG4MAAAFADcAbwwAAAQAHQAeAAkJwRV+IwBAAgloDAAABAA+AGkMAAAEADgAawwAAAQAOQBqDAAABAAyAGwMAAAEACIAbQwAAAQAOgDqDAAABgBaAG4MAAAFADcAbwwAAAQAHQAAAA==.',
['Sý']='Sýlvanas:BAABLgAECn8UAAIfAAUJVxN8FgDuAAVoDAAABgA6AGkMAAAGACsAawwAAAUAJQBqDAAAAgA/AOoMAAABADoAHwAFCVcTfBYA7gAFaAwAAAYAOgBpDAAABgArAGsMAAAFACUAagwAAAIAPwDqDAAAAQA6AAAA.',
Te='Tealç:BAABLgAECn8gAAIcAAcJpheVGACQAQdoDAAABgBWAGkMAAAGAFAAawwAAAYARQBqDAAABAAxAGwMAAAEACsAbQwAAAEACQDqDAAABQBKABwABwmmF5UYAJABB2gMAAAGAFYAaQwAAAYAUABrDAAABgBFAGoMAAAEADEAbAwAAAQAKwBtDAAAAQAJAOoMAAAFAEoAAS4ABRQECRgAHABHHwA=.Tekk:BAAALgAECgEJAQAAAA==.Tekkys:BAAALgAECgEJAgAAAA==.Tertle:BAAALgADCgUJBQAAAA==.',
Ti='Tiafinia:BAAALgAECgEJAgAAAA==.Tiggerstripe:BAAALgADCgEJAQABLgAECgkJMQAgAEMQAA==.Timmyy:BAAALgAECgYJBgABLgAFFAQJCAANAN4MAA==.Timur:BAAALgAECgMJBAAAAA==.Tinara:BAAALgADCgUJBQAAAA==.',
To='Tome:BAAALgAECgEJAQABLgAECggJGwAHADwaAA==.',
Tr='Trigger:BAAALgAECgIJAgAAAA==.',
Tu='Turlesblows:BAABLgAECn8gAAMJAAgJYyBZIQDVAQhoDAAABQBTAGkMAAAFAFEAawwAAAMAUQBqDAAABABEAGwMAAAGAFoAbQwAAAIAUgDqDAAABgBiAG4MAAABAD0ACQAICWMgWSEA1QEIaAwAAAUAUwBpDAAABQBRAGsMAAADAFEAagwAAAQARABsDAAABgBaAG0MAAACAFIA6gwAAAUAYgBuDAAAAQA9ABwAAQk7FZlEADsAAeoMAAABADYAAAA=.',
Tw='Twityy:BAAALgADCgEJAgAAAA==.Twofiveyd:BAABLgAFFH8FAAIYAAQJjA+5KwD6AARoDAAAAgAzAGkMAAABAC8AawwAAAEACADqDAAAAQAzABgABAmMD7krAPoABGgMAAACADMAaQwAAAEALwBrDAAAAQAIAOoMAAABADMAAS4ABRQGCRQAGwBnGAA=.',
Ty='Tyladrhas:BAABLgAECn80AAIiAAkJVB8qAwCeAgloDAAACABOAGkMAAAHAFkAawwAAAcASgBqDAAABwA+AGwMAAAFAE0AbQwAAAMAXQDqDAAACwBRAG4MAAADAEQAbwwAAAEATAAiAAkJVB8qAwCeAgloDAAACABOAGkMAAAHAFkAawwAAAcASgBqDAAABwA+AGwMAAAFAE0AbQwAAAMAXQDqDAAACwBRAG4MAAADAEQAbwwAAAEATAAAAA==.Tyrismaximus:BAAALgAECgMJAwAAAA==.',
Ul='Ulkina:BAAALgADCgYJCQAAAA==.',
Va='Vaelith:BAAALgAECgIJAgAAAA==.Valerine:BAABLgAECn8aAAIEAAkJ/woseABvAQloDAAABAAqAGkMAAAEACcAawwAAAQAOQBqDAAABQAnAGwMAAAEAC8AbQwAAAEABwDqDAAAAgAOAG4MAAABAAYAbwwAAAEACQAEAAkJ/woseABvAQloDAAABAAqAGkMAAAEACcAawwAAAQAOQBqDAAABQAnAGwMAAAEAC8AbQwAAAEABwDqDAAAAgAOAG4MAAABAAYAbwwAAAEACQAAAA==.Vanoran:BAAALgAECgMJBAAAAA==.Varina:BAAALgAECgcJEwAAAA==.',
Ve='Velsaert:BAAALgAECgEJAQAAAA==.Venki:BAAALgAECgcJCQAAAA==.',
Vi='Vitani:BAAALgADCgIJAgABLgAFFAUJEAAXAN4UAA==.',
Vo='Voidnova:BAABLgAFFH8HAAIEAAMJlRBWdwDUAANoDAAAAwBBAGkMAAADAB4A6gwAAAEAHwAEAAMJlRBWdwDUAANoDAAAAwBBAGkMAAADAB4A6gwAAAEAHwAAAA==.Voidphayze:BAAALgAECgUJDAABLgAFFAMJBQANAEUTAA==.',
Vu='Vulken:BAABLgAECn9nAAIeAAkJESUZDADgAgloDAAADgBhAGkMAAAMAF4AawwAAA4AXgBqDAAADgBQAGwMAAANAFoAbQwAAAoAXQDqDAAADgBfAG4MAAAHAGAAbwwAAAUAYAAeAAkJESUZDADgAgloDAAADgBhAGkMAAAMAF4AawwAAA4AXgBqDAAADgBQAGwMAAANAFoAbQwAAAoAXQDqDAAADgBfAG4MAAAHAGAAbwwAAAUAYAAAAA==.',
['Vê']='Vê:BAAALgAECgkJEQAAAA==.',
Wa='Wallace:BAAALgAECgcJDAAAAA==.Walterlight:BAAALgAECgYJDgAAAA==.Watto:BAABLgAECn8VAAMQAAkJOR8yFACSAgloDAAAAQBaAGkMAAACAFAAawwAAAIAVwBqDAAAAgBYAGwMAAACAFAAbQwAAAEASwDqDAAABwBYAG4MAAADADkAbwwAAAEASAAQAAkJOR8yFACSAgloDAAAAQBaAGkMAAACAFAAawwAAAIAVwBqDAAAAgBYAGwMAAACAFAAbQwAAAEASwDqDAAABgBYAG4MAAADADkAbwwAAAEASAAhAAEJMBfkiQBEAAHqDAAAAQA7AAAA.',
We='Wemongin:BAAALgADCgUJBQAAAA==.',
Wh='Whimsical:BAABLgAECn8XAAIQAAYJgBdqSQBvAQZoDAAABABEAGkMAAAEAC8AawwAAAQALgBqDAAAAwAzAGwMAAADAFMA6gwAAAUAPwAQAAYJgBdqSQBvAQZoDAAABABEAGkMAAAEAC8AawwAAAQALgBqDAAAAwAzAGwMAAADAFMA6gwAAAUAPwAAAA==.',
Wi='Winnìng:BAABLgAECn8jAAIkAAkJLQwSGABFAQloDAAABQA3AGkMAAAEABgAawwAAAQAIQBqDAAABAAgAGwMAAAEAAsAbQwAAAIAEgDqDAAABwAzAG4MAAAEACQAbwwAAAEAEgAkAAkJLQwSGABFAQloDAAABQA3AGkMAAAEABgAawwAAAQAIQBqDAAABAAgAGwMAAAEAAsAbQwAAAIAEgDqDAAABwAzAG4MAAAEACQAbwwAAAEAEgAAAA==.',
Wu='Wugong:BAAALgADCgEJAQAAAA==.',
['Wó']='Wórkwórk:BAACLgAFFH8FAAIJAAMJKhROFwCsAANoDAAAAgA8AGkMAAACAEAA6gwAAAEAHgAJAAMJKhROFwCsAANoDAAAAgA8AGkMAAACAEAA6gwAAAEAHgAuAAQKfxsAAwkACQk6Gxg3AMsBAAkABwnRGRg3AMsBABsAAwnsGr8fAO8AAAAA.',
Ze='Zerg:BAAALgAECgIJAgAAAA==.',
Zi='Zich:BAAALgADCgMJAwAAAA==.Zihon:BAABLgAECn8UAAINAAQJTxqC2gDEAARoDAAAAwA7AGkMAAAFAEYAawwAAAUASQDqDAAABwBCAA0ABAlPGoLaAMQABGgMAAADADsAaQwAAAUARgBrDAAABQBJAOoMAAAHAEIAAAA=.',
Zo='Zodiiak:BAABLgAECn9EAAIgAAkJMR3hBQBrAgloDAAACwBOAGkMAAALAFUAawwAAAkAVgBqDAAABwA+AGwMAAAJAFEAbQwAAAQAPgDqDAAACgBRAG4MAAAGAEgAbwwAAAEAMgAgAAkJMR3hBQBrAgloDAAACwBOAGkMAAALAFUAawwAAAkAVgBqDAAABwA+AGwMAAAJAFEAbQwAAAQAPgDqDAAACgBRAG4MAAAGAEgAbwwAAAEAMgAAAA==.',
Zu='Zubb:BAAALgADCgYJCQABLgAECggJEAACAAAAAA==.Zugg:BAAALgAECgIJAgABLgAECggJEAACAAAAAA==.Zuhh:BAAALgAECgEJAgABLgAECggJEAACAAAAAA==.Zupp:BAAALgAECggJEAAAAA==.',
Zx='Zx:BAAALgADCgYJBgAAAA==.',
['Ér']='Ér:BAAALgAECgkJBgAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
