local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Paladin-Protection','Shaman-Restoration','Priest-Shadow','DeathKnight-Blood','DeathKnight-Unholy','Druid-Restoration','Mage-Frost','Mage-Fire','Unknown-Unknown','Monk-Brewmaster','Paladin-Retribution','Warrior-Protection','Evoker-Devastation','DemonHunter-Devourer','DeathKnight-Frost','Hunter-Survival','Monk-Mistweaver','Shaman-Elemental','Warrior-Fury','DemonHunter-Vengeance','Shaman-Enhancement','Evoker-Preservation','Druid-Balance','Hunter-BeastMastery','Hunter-Marksmanship','Monk-Windwalker','Warlock-Demonology','Druid-Guardian','Priest-Holy','Priest-Discipline','Druid-Feral','Warlock-Affliction','Warlock-Destruction','Mage-Arcane','Paladin-Holy','Warrior-Arms','Rogue-Subtlety',}
local provider = {region='US',realm='Rexxar',name='US',type='daily',zone=46,date='2026-05-12',data={Ac='Acile:BAAALgADCgEJAQAAAA==.',
Ad='Adhenar:BAAALgAECgMJAwAAAA==.Adow:BAAALgAECgUJBQAAAA==.Adynne:BAAALgAECgYJBgABLgAECgcJFQABADsfAA==.',
Ae='Aered:BAAALgAECgUJCwAAAA==.Aerylith:BAAALgAECgYJCgAAAA==.',
Ah='Ahira:BAABLgAECn8qAAICAAgJQCKQCAC5AghoDAAABwBjAGkMAAAHAGIAawwAAAYAYgBqDAAABQBbAGwMAAAFAFUAbQwAAAMAOwDqDAAABgBiAG4MAAADAEUAAgAICUAikAgAuQIIaAwAAAcAYwBpDAAABwBiAGsMAAAGAGIAagwAAAUAWwBsDAAABQBVAG0MAAADADsA6gwAAAYAYgBuDAAAAwBFAAAA.',
Ai='Ailov:BAAALgADCgMJAwAAAA==.',
Ak='Akuria:BAABLgAECn8cAAIDAAgJnhLnJQAsAQhoDAAABABCAGkMAAADACsAawwAAAMANQBqDAAABAAqAGwMAAAFADIAbQwAAAEAKQDqDAAABgAkAG4MAAACACgAAwAICZ4S5yUALAEIaAwAAAQAQgBpDAAAAwArAGsMAAADADUAagwAAAQAKgBsDAAABQAyAG0MAAABACkA6gwAAAYAJABuDAAAAgAoAAAA.',
Al='Alahna:BAAALgAECgYJEAAAAA==.Alliesrofl:BAAALgADCgEJAQAAAA==.Aluzan:BAAALgADCgUJBQAAAA==.',
An='Anahera:BAAALgADCgYJCQAAAA==.Anies:BAABLgAECn8qAAMEAAgJAw5bEwBYAQhoDAAABwAZAGkMAAAHADAAawwAAAYAEQBqDAAABQA+AGwMAAAGAFAAbQwAAAMAFADqDAAABwAzAG4MAAABAAYABAAICQMOWxMAWAEIaAwAAAYAGQBpDAAABQAwAGsMAAAFABEAagwAAAUAPgBsDAAABgBQAG0MAAADABQA6gwAAAYAMwBuDAAAAQAGAAUABAlJAlr6AIcABGgMAAABAAQAaQwAAAIABwBrDAAAAQAGAOoMAAABAAQAAAA=.Antamoon:BAAALgADCggJCwAAAA==.',
Aq='Aquarian:BAAALgAECgYJCwAAAA==.',
Ar='Ardcore:BAAALgAECgYJDgAAAA==.Arkæ:BAAALgADCgkJAQAAAA==.Arys:BAAALgAECgEJAQAAAA==.',
As='Asherrylie:BAAALgADCgUJBwAAAA==.Ashtrây:BAAALgADCgMJBAAAAA==.Assasincross:BAAALgADCgUJBAAAAA==.Asseroth:BAAALgAECgEJAQAAAA==.',
At='Atriux:BAAALgAECgYJBgAAAA==.',
Au='Aureline:BAABLgAECn8kAAIGAAgJpBJ2MwBkAQhoDAAABgA/AGkMAAAGADQAawwAAAYANQBqDAAABAAxAGwMAAADADEAbQwAAAMAIgDqDAAABwA9AG4MAAABABAABgAICaQSdjMAZAEIaAwAAAYAPwBpDAAABgA0AGsMAAAGADUAagwAAAQAMQBsDAAAAwAxAG0MAAADACIA6gwAAAcAPQBuDAAAAQAQAAAA.Aurna:BAAALgAECgcJDgAAAA==.',
Ba='Babegnome:BAAALgAECgEJAQAAAA==.Backstrap:BAAALgADCgQJBAAAAA==.Batmuhn:BAAALgAECgYJDwAAAA==.',
Be='Beartank:BAAALgADCgYJBgAAAA==.Beastquake:BAAALgADCgMJAwAAAA==.Beefpunch:BAAALgAECgMJAwAAAA==.Belaseth:BAAALgADCgUJCAAAAA==.Belserion:BAACLgAFFH8MAAIHAAQJVhjWGABnAQRoDAAABQBfAGkMAAABAFIAawwAAAEABwDqDAAABQBAAAcABAlWGNYYAGcBBGgMAAAFAF8AaQwAAAEAUgBrDAAAAQAHAOoMAAAFAEAALgAECn9FAAMHAAkJ9yTdBQClAwAHAAkJ9yTdBQClAwAIAAEJ3SFjCQBhAAAAAA==.Bendoverman:BAAALgAECgEJAQABLgAECgkJGwAHAAoeAA==.Bernir:BAAALgAECgIJAgAAAA==.Berol:BAAALgAECgYJCwAAAA==.Beroldin:BAAALgADCgIJAgABLgAECgYJCwAJAAAAAA==.Bevar:BAAALgADCgYJBwABLgAECgQJBQAJAAAAAA==.',
Bi='Bigboiexx:BAAALgAECgMJAwAAAA==.Biggiebrewz:BAABLgAECn8WAAIKAAYJoB7QJQDVAQZoDAAABABZAGkMAAAEAEkAawwAAAQAUQBqDAAAAwBSAGwMAAADAEUA6gwAAAQATQAKAAYJoB7QJQDVAQZoDAAABABZAGkMAAAEAEkAawwAAAQAUQBqDAAAAwBSAGwMAAADAEUA6gwAAAQATQAAAA==.Biggielocks:BAAALgADCgkJCQAAAA==.Biggiesdk:BAAALgAECgkJDgAAAA==.',
Bl='Blackmaster:BAAALgAECgEJAgAAAA==.Blkrend:BAABLgAECn82AAIEAAkJ9yVWAABrAwloDAAACABiAGkMAAAHAGEAawwAAAcAYwBqDAAABwBjAGwMAAAHAGMAbQwAAAUAYwDqDAAABwBhAG4MAAAEAF4AbwwAAAIAWgAEAAkJ9yVWAABrAwloDAAACABiAGkMAAAHAGEAawwAAAcAYwBqDAAABwBjAGwMAAAHAGMAbQwAAAUAYwDqDAAABwBhAG4MAAAEAF4AbwwAAAIAWgAAAA==.',
Br='Bradycam:BAABLgAECn8lAAILAAgJRhlMHAA0AghoDAAABgBFAGkMAAAGAE8AawwAAAYASABqDAAABQBIAGwMAAAFAEoA6gwAAAYAVgBuDAAAAgApAG8MAAABABwACwAICUYZTBwANAIIaAwAAAYARQBpDAAABgBPAGsMAAAGAEgAagwAAAUASABsDAAABQBKAOoMAAAGAFYAbgwAAAIAKQBvDAAAAQAcAAAA.Braffermac:BAAALgAECgIJBAAAAA==.Brewmaster:BAAALgAECgcJBwAAAA==.Brightwing:BAAALgAECgYJBwAAAA==.Bruceelee:BAAALgADCgIJAQAAAA==.Bruddah:BAAALgAFFAEJAQABLgAFFAMJCgAMAD0KAA==.',
['Bó']='Bóbafett:BAAALgADCgEJAQAAAA==.',
Ca='Cadovenia:BAAALgAECgEJAgAAAA==.Carebeär:BAABLgAECn8aAAIGAAcJ6hcYNgDPAQdoDAAABABHAGkMAAAFAEIAawwAAAUAVwBqDAAABAA5AGwMAAADAEMA6gwAAAQAOwBuDAAAAQASAAYABwnqFxg2AM8BB2gMAAAEAEcAaQwAAAUAQgBrDAAABQBXAGoMAAAEADkAbAwAAAMAQwDqDAAABAA7AG4MAAABABIAAAA=.Casella:BAABLgAECn82AAIKAAkJQCCeAgDxAgloDAAACABRAGkMAAAGAFcAawwAAAcAWgBqDAAABwBRAGwMAAAGAF8AbQwAAAYAWwDqDAAABwBSAG4MAAAFAE4AbwwAAAIAMwAKAAkJQCCeAgDxAgloDAAACABRAGkMAAAGAFcAawwAAAcAWgBqDAAABwBRAGwMAAAGAF8AbQwAAAYAWwDqDAAABwBSAG4MAAAFAE4AbwwAAAIAMwAAAA==.',
Ce='Celissara:BAAALgAECgUJDwABLgAECgcJDgAJAAAAAA==.',
Ch='Chimken:BAAALgADCgMJAwAAAA==.Chogori:BAAALgAECgMJCwAAAA==.Chôsenône:BAAALgAECgUJBgAAAA==.',
Cl='Clawmydia:BAAALgADCgYJBwAAAA==.Cleth:BAABLgAECn8XAAILAAYJ1BYhVQBfAQZoDAAABQA4AGkMAAAFAD0AawwAAAMAIABqDAAAAgBDAGwMAAACAEIA6gwAAAYASgALAAYJ1BYhVQBfAQZoDAAABQA4AGkMAAAFAD0AawwAAAMAIABqDAAAAgBDAGwMAAACAEIA6gwAAAYASgAAAA==.Clouzot:BAAALgADCgMJAwAAAA==.',
Co='Content:BAAALgADCgMJAwAAAA==.Corax:BAABLgAECn8dAAINAAcJQQbdCgD/AAdoDAAABQALAGkMAAAFABkAawwAAAUAFABqDAAAAwAaAGwMAAAEAAsA6gwAAAYACABuDAAAAQARAA0ABwlBBt0KAP8AB2gMAAAFAAsAaQwAAAUAGQBrDAAABQAUAGoMAAADABoAbAwAAAQACwDqDAAABgAIAG4MAAABABEAAAA=.',
Cp='Cptbarnacles:BAAALgAECgYJDwAAAA==.',
Cr='Crane:BAAALgADCgUJBQAAAA==.Crankitty:BAAALgAECgMJBwAAAA==.Crispee:BAAALgADCgEJAQAAAA==.Critshot:BAAALgAECgYJEAABLgAFFAMJBwAOACEdAA==.Crunchylock:BAAALgAECggJDAAAAA==.',
Cy='Cyllar:BAAALgADCgYJBgAAAA==.',
['Cö']='Cösmic:BAAALgAECgIJAgAAAA==.',
Da='Damachi:BAABLgAECn8bAAMFAAgJlREkOwCkAQhoDAAAAwAzAGkMAAADADQAawwAAAQAJABqDAAABAAqAGwMAAAEADIAbQwAAAMAJQDqDAAABAAgAG4MAAACADYABQAICecQJDsApAEIaAwAAAEAMwBpDAAAAQA0AGsMAAABACMAagwAAAEAKgBsDAAAAQAnAG0MAAACACUA6gwAAAIAIABuDAAAAQA2AA8ACAmaDPEIADEBCGgMAAACAB4AaQwAAAIAMABrDAAAAwAkAGoMAAADACIAbAwAAAMAMgBtDAAAAQAJAOoMAAACABMAbgwAAAEAHwAAAA==.Danskan:BAAALgAECgYJDQAAAA==.Darkvale:BAAALgAECgMJAwAAAA==.Darkñess:BAAALgAECggJDQAAAA==.Darmorae:BAABLgAECn8gAAIQAAgJRRZeDQDjAQhoDAAABQBNAGkMAAAFAD0AawwAAAQARQBqDAAAAwA1AGwMAAAEADgAbQwAAAEAGADqDAAABgBFAG4MAAAEACgAEAAICUUWXg0A4wEIaAwAAAUATQBpDAAABQA9AGsMAAAEAEUAagwAAAMANQBsDAAABAA4AG0MAAABABgA6gwAAAYARQBuDAAABAAoAAAA.Dashii:BAAALgAECgEJAgAAAA==.Datewoo:BAABLgAECn8WAAILAAYJLQ9tegAPAQZoDAAABQA1AGkMAAAEACgAawwAAAQAIQBqDAAAAQAnAGwMAAADABwA6gwAAAUAJQALAAYJLQ9tegAPAQZoDAAABQA1AGkMAAAEACgAawwAAAQAIQBqDAAAAQAnAGwMAAADABwA6gwAAAUAJQAAAA==.',
De='Deadstimpy:BAAALgADCgcJBwAAAA==.Deef:BAAALgAECgQJBAAAAA==.Derasande:BAAALgADCgEJAQAAAA==.Desadeness:BAAALgADCgMJBQABLgADCgcJJgAJAAAAAA==.Desertpunk:BAAALgAECgEJAQAAAA==.Devoroyal:BAAALgAECgcJEQAAAA==.',
Di='Diasuke:BAAALgADCgQJBAAAAA==.Dillinquent:BAAALgAECgUJCwAAAA==.',
Do='Donkaßutts:BAAALgAECgQJBQAAAA==.Dooda:BAAALgAECgQJCgAAAA==.Doomclaw:BAAALgADCgQJBAAAAA==.Doomforge:BAAALgAECgUJCQAAAA==.Dorciaa:BAAALgAECgYJBgABLgAECgcJFQABADsfAA==.Dottinstds:BAAALgAECgYJBgAAAA==.',
Dr='Dracbow:BAAALgAECgUJBQAAAA==.Dracfu:BAABLgAECn8XAAIRAAgJpQfOKwAOAQhoDAAAAwAmAGkMAAADABcAawwAAAIACgBqDAAABAASAGwMAAAEABUAbQwAAAEABADqDAAAAwAdAG4MAAADAAoAEQAICaUHzisADgEIaAwAAAMAJgBpDAAAAwAXAGsMAAACAAoAagwAAAQAEgBsDAAABAAVAG0MAAABAAQA6gwAAAMAHQBuDAAAAwAKAAEuAAQKCQkOAAkAAAAA.Dracserion:BAAALgADCgUJCAABLgAFFAQJDAAHAFYYAA==.Dracsknight:BAAALgAECgkJDgAAAA==.Dracslana:BAAALgAECgUJCwABLgAECgkJDgAJAAAAAA==.Draffel:BAABLgAECn8YAAMCAAgJiht/DQB0AghoDAAAAwBIAGkMAAADADsAawwAAAMAQQBqDAAAAwBDAGwMAAADAFUAbQwAAAMATQDqDAAAAwBNAG4MAAADADsAAgAICYobfw0AdAIIaAwAAAMASABpDAAAAwA7AGsMAAADAEEAagwAAAMAQwBsDAAAAwBVAG0MAAADAE0A6gwAAAMATQBuDAAAAgA7ABIAAQnFAS9+ABgAAW4MAAABAAQAAAA=.Drathi:BAAALgAECgYJDwAAAA==.Drestla:BAAALgAECgcJCwAAAA==.Drowgon:BAABLgAECn8WAAMTAAcJYBf6GACxAQdoDAAABABJAGkMAAAEADkAawwAAAMAQABqDAAAAwAzAGwMAAADADwAbQwAAAIAPQDqDAAAAwApABMABwlgF/oYALEBB2gMAAAEAEkAaQwAAAMAOQBrDAAAAQBAAGoMAAABAB8AbAwAAAEAPABtDAAAAQA9AOoMAAABACkADAAGCX8NJiEAvAAGaQwAAAEADQBrDAAAAgA0AGoMAAACADMAbAwAAAIAMQBtDAAAAQAfAOoMAAACABgAAAA=.Druwgon:BAAALgAECgEJAQAAAA==.',
Du='Duartor:BAAALgAECgIJAgAAAA==.Dukalune:BAAALgAECgUJCQAAAA==.Dukaos:BAACLgAFFH8LAAIOAAQJNQ3aLgAKAQRoDAAABQAtAGkMAAACACAAawwAAAEADADqDAAAAwAtAA4ABAk1DdouAAoBBGgMAAAFAC0AaQwAAAIAIABrDAAAAQAMAOoMAAADAC0ALgAECn8kAAMOAAcJPRu5LwA9AgAOAAcJPRu5LwA9AgAUAAQJQg1kGgDBAAAAAA==.Dunzer:BAABLgAECn8pAAMLAAkJyhfZKgDpAQloDAAABwBAAGkMAAAIAEcAawwAAAgAPABqDAAABABYAGwMAAADAEsAbQwAAAEALwDqDAAABgBDAG4MAAADADgAbwwAAAEAKwALAAkJyhfZKgDpAQloDAAABwBAAGkMAAAHAEcAawwAAAcAPABqDAAABABYAGwMAAADAEsAbQwAAAEALwDqDAAABgBDAG4MAAADADgAbwwAAAEAKwABAAIJQwmTLQBUAAJpDAAAAQAZAGsMAAABABYAAAA=.',
['Dé']='Déadeye:BAAALgAECgEJAQAAAA==.',
['Dõ']='Dõrã:BAAALgADCgcJBwAAAA==.',
['Dø']='Døømlørd:BAABLgAECn8YAAIGAAYJ9hsoJAC+AQZoDAAABQBEAGkMAAAFAFAAawwAAAUAOgBqDAAAAgBDAGwMAAABAEYA6gwAAAYAVAAGAAYJ9hsoJAC+AQZoDAAABQBEAGkMAAAFAFAAawwAAAUAOgBqDAAAAgBDAGwMAAABAEYA6gwAAAYAVAAAAA==.',
['Dú']='Dúbs:BAAALgADCgMJAwAAAA==.',
Ea='Earthhammerz:BAAALgADCgUJBQAAAA==.',
Ed='Edithpoothe:BAABLgAECn8bAAIHAAgJCh7wOgCLAghoDAAAAwBRAGkMAAAEAFIAawwAAAQATgBqDAAABQBhAGwMAAAEAEcAbQwAAAIATwDqDAAAAwBQAG4MAAACAEAABwAICQoe8DoAiwIIaAwAAAMAUQBpDAAABABSAGsMAAAEAE4AagwAAAUAYQBsDAAABABHAG0MAAACAE8A6gwAAAMAUABuDAAAAgBAAAAA.',
Ei='Eightt:BAAALgADCgcJCwAAAA==.',
El='Electricks:BAABLgAECn8YAAIVAAkJqh8PBQC6AgloDAAABABbAGkMAAADAGEAawwAAAMAWQBqDAAABABgAGwMAAAEAFcAbQwAAAEANADqDAAAAwBTAG4MAAABADsAbwwAAAEAVwAVAAkJqh8PBQC6AgloDAAABABbAGkMAAADAGEAawwAAAMAWQBqDAAABABgAGwMAAAEAFcAbQwAAAEANADqDAAAAwBTAG4MAAABADsAbwwAAAEAVwAAAA==.Ellaryia:BAAALgADCgMJAwAAAA==.',
Em='Emmii:BAAALgAECgIJAwAAAA==.Emolock:BAAALgAECgUJBQAAAA==.',
En='Endlessbuns:BAAALgAECgUJCwAAAA==.Enset:BAAALgADCgUJBQAAAA==.Enyetia:BAAALgADCgcJBwAAAA==.',
Eo='Eon:BAAALgAECgUJCQAAAA==.',
Ep='Epiphaný:BAAALgAECgQJBQAAAA==.',
Er='Eradoria:BAAALgAECgYJEQAAAA==.Erielea:BAAALgADCgcJCAAAAA==.Erilock:BAAALgAECgQJBAAAAA==.',
Es='Essylt:BAAALgAECgEJAQAAAA==.Este:BAAALgADCgQJBAAAAA==.',
Ev='Evadne:BAAALgAECgYJBgAAAA==.Evalin:BAAALgADCgEJAQAAAA==.Evoken:BAABLgAECn8XAAIWAAgJGAk2EABRAQhoDAAAAwATAGkMAAADAA4AawwAAAQAHwBqDAAAAwATAGwMAAAEACcAbQwAAAIAGQDqDAAAAwAbAG4MAAABAAgAFgAICRgJNhAAUQEIaAwAAAMAEwBpDAAAAwAOAGsMAAAEAB8AagwAAAMAEwBsDAAABAAnAG0MAAACABkA6gwAAAMAGwBuDAAAAQAIAAAA.',
Ex='Exidore:BAAALgAECgcJDAAAAA==.',
Fa='Faant:BAAALgADCgYJCgABLgAECgQJBAAJAAAAAA==.Faeroline:BAAALgAECgYJBwAAAA==.Falchionx:BAAALgAECgUJBgABLgAECgYJGAAGAPYbAA==.Falfogan:BAAALgAECgEJAgAAAA==.Fangy:BAAALgAECgIJAwAAAA==.Fatone:BAAALgAECgQJCAAAAA==.',
Fe='Felserion:BAAALgADCgEJAgABLgAFFAQJDAAHAFYYAA==.Fenn:BAABLgAECn8kAAISAAgJJhRWFgCzAQhoDAAABgBQAGkMAAAGAEUAawwAAAYAPABqDAAABQBBAGwMAAAFADQA6gwAAAYAOgBuDAAAAQAdAG8MAAABAAkAEgAICSYUVhYAswEIaAwAAAYAUABpDAAABgBFAGsMAAAGADwAagwAAAUAQQBsDAAABQA0AOoMAAAGADoAbgwAAAEAHQBvDAAAAQAJAAAA.Fenrìs:BAAALgADCgUJBAAAAA==.',
Fi='Fistantillus:BAAALgAECgcJCgAAAA==.',
Fl='Flane:BAAALgADCggJBQAAAA==.Flopper:BAAALgAECgYJCwAAAA==.',
Fo='Fonddle:BAAALgADCgUJCQAAAA==.Foxyboo:BAABLgAECn8pAAICAAkJ2BgCEQBOAgloDAAABwBYAGkMAAAIAFAAawwAAAgASQBqDAAABAA7AGwMAAADADkAbQwAAAEAEQDqDAAABgBYAG4MAAADAEEAbwwAAAEAKgACAAkJ2BgCEQBOAgloDAAABwBYAGkMAAAIAFAAawwAAAgASQBqDAAABAA7AGwMAAADADkAbQwAAAEAEQDqDAAABgBYAG4MAAADAEEAbwwAAAEAKgAAAA==.',
Fr='Freak:BAABLgAECn8YAAMGAAgJHhIfLACNAQhoDAAABAAnAGkMAAAEAEoAawwAAAMANwBqDAAAAgBDAGwMAAADACsAbQwAAAIAHQDqDAAABAAcAG4MAAACACEABgAICR4SHywAjQEIaAwAAAIAJwBpDAAAAgBKAGsMAAACADcAagwAAAEAQwBsDAAAAgArAG0MAAACAB0A6gwAAAIAHABuDAAAAgAhABcABgmyCTpNAPUABmgMAAACAB8AaQwAAAIAFgBrDAAAAQAgAGoMAAABAAYAbAwAAAEAEwDqDAAAAgARAAAA.Freakpeachh:BAAALgAECgMJAwAAAA==.',
Fu='Fulv:BAAALgAECgUJEAAAAA==.',
['Fâ']='Fâith:BAAALgAECgQJBQAAAA==.',
Ga='Galerodra:BAAALgADCgEJAQAAAA==.Galorani:BAAALgADCgIJAgAAAA==.Gammin:BAAALgAECgEJAQAAAA==.Ganajir:BAAALgADCgcJBwAAAA==.Garalline:BAAALgAECgQJCQAAAA==.',
Ge='Gertroz:BAAALgAECgMJBQABLgAECgcJDgAJAAAAAA==.',
Gn='Gnumb:BAAALgADCgIJAgAAAA==.',
Go='Gooberetta:BAABLgAECn8kAAIYAAgJxyKyCwCXAghoDAAABgBcAGkMAAAGAFoAawwAAAQAVwBqDAAABQBYAGwMAAAFAEYAbQwAAAMAXwDqDAAABABcAG4MAAADAF0AGAAICccisgsAlwIIaAwAAAYAXABpDAAABgBaAGsMAAAEAFcAagwAAAUAWABsDAAABQBGAG0MAAADAF8A6gwAAAQAXABuDAAAAwBdAAAA.Gope:BAABLgAECn8fAAMCAAkJXhXyLgBxAQloDAAABABYAGkMAAADAD8AawwAAAMAOQBqDAAABQA9AGwMAAAFADwAbQwAAAEAEwDqDAAABgBWAG4MAAADAB4AbwwAAAEAFwACAAkJXhXyLgBxAQloDAAAAwBYAGkMAAACAD8AawwAAAIAOQBqDAAABQA9AGwMAAAEADwAbQwAAAEAEwDqDAAABgBWAG4MAAADAB4AbwwAAAEAFwASAAQJ3gZMdgBpAARoDAAAAQARAGkMAAABACQAawwAAAEAAQBsDAAAAQAOAAAA.Gorriten:BAAALgADCgIJAgAAAA==.',
Gr='Green:BAABLgAECn8WAAIQAAgJSxcbCQBUAghoDAAABABUAGkMAAAEAFIAawwAAAQATQBqDAAAAwBYAGwMAAABAEcAbQwAAAEACwDqDAAABAAyAG4MAAABACcAEAAICUsXGwkAVAIIaAwAAAQAVABpDAAABABSAGsMAAAEAE0AagwAAAMAWABsDAAAAQBHAG0MAAABAAsA6gwAAAQAMgBuDAAAAQAnAAAA.Grimdoll:BAAALgAECgEJAQAAAA==.Grmreaper:BAAALgADCgUJBQAAAA==.Gromiir:BAABLgAECn8mAAMQAAkJKx8+BQB6AgloDAAABgBdAGkMAAAGAFoAawwAAAYAWQBqDAAABQBaAGwMAAAFAFkAbQwAAAEAKgDqDAAABgBhAG4MAAACAEoAbwwAAAEAPQAZAAgJ3R0MEgCoAghoDAAABABdAGkMAAAEAFoAawwAAAQARQBqDAAAAwBaAGwMAAADAFYAbQwAAAEAKgDqDAAABQBhAG4MAAABADcAEAAICeYdPgUAegIIaAwAAAIAUwBpDAAAAgA/AGsMAAACAFkAagwAAAIAUABsDAAAAgBZAOoMAAABAEkAbgwAAAEASgBvDAAAAQA9AAAA.Gromyr:BAAALgAECgEJAQABLgAECgkJJgAQACsfAA==.Grr:BAABLgAECn8eAAIOAAkJ7RyFEwA3AgloDAAABQBjAGkMAAAFAGAAawwAAAUATgBqDAAABABjAGwMAAAEAFwAbQwAAAEAOADqDAAABABfAG4MAAABABUAbwwAAAEANQAOAAkJ7RyFEwA3AgloDAAABQBjAGkMAAAFAGAAawwAAAUATgBqDAAABABjAGwMAAAEAFwAbQwAAAEAOADqDAAABABfAG4MAAABABUAbwwAAAEANQAAAA==.',
Gy='Gynchi:BAAALgAECgcJCgAAAA==.Gytha:BAAALgADCgIJAgAAAA==.',
['Gó']='Gójira:BAAALgAECgYJCgAAAA==.',
Ha='Hartis:BAABLgAECn8sAAQYAAkJERCZJADXAQloDAAABgAlAGkMAAAGADMAawwAAAYAMABqDAAABgAjAGwMAAAFADQAbQwAAAQAIQDqDAAABgAeAG4MAAAEADoAbwwAAAEAEQAYAAkJERCZJADXAQloDAAABQAlAGkMAAAEADMAawwAAAQAMABqDAAABgAjAGwMAAAFADQAbQwAAAQAIQDqDAAABQAeAG4MAAAEADoAbwwAAAEAEQAQAAIJqwQhNwBlAAJpDAAAAQANAGsMAAABAAoAGQAECecAXXsAVgAEaAwAAAEAAABpDAAAAQACAGsMAAABAAIA6gwAAAEAAgAAAA==.Hashmal:BAAALgAECgQJBAAAAA==.Hazo:BAABLgAECn8aAAMKAAYJIAmhQwCbAAZoDAAABgA8AGkMAAAGABkAawwAAAUABgBqDAAABAAOAGwMAAABAAcA6gwAAAQAEAAKAAUJDwqhQwCbAAVoDAAABgA8AGkMAAAGABkAawwAAAUABgBqDAAAAwAKAOoMAAACAAoAGgADCagEG2wAXwADagwAAAEADgBsDAAAAQAHAOoMAAACABAAAAA=.',
He='Healingman:BAAALgADCgUJBQAAAA==.Hectabali:BAAALgADCgIJAgAAAA==.Heizou:BAAALgAECgEJAQAAAA==.Hellkat:BAAALgAECgUJBwAAAA==.',
Hi='Higarosa:BAAALgADCgIJAwAAAA==.Highbull:BAAALgAECgEJAQAAAA==.',
Ho='Holiblade:BAABLgAECn8nAAILAAgJaAmqZAA6AQhoDAAABwAtAGkMAAAGABwAawwAAAYADgBqDAAABQAYAGwMAAAEABwAbQwAAAMACADqDAAABgAUAG4MAAACABYACwAICWgJqmQAOgEIaAwAAAcALQBpDAAABgAcAGsMAAAGAA4AagwAAAUAGABsDAAABAAcAG0MAAADAAgA6gwAAAYAFABuDAAAAgAWAAAA.Holyhannah:BAAALgAECgUJBgAAAA==.Holykilla:BAAALgAECgUJDwAAAA==.Holyshiva:BAAALgADCgcJCgABLgAECggJDwAJAAAAAA==.Hooligun:BAABLgAECn8hAAISAAgJzA1fIgBUAQhoDAAABgAqAGkMAAAFACsAawwAAAUANQBqDAAABQAzAGwMAAAEABUAbQwAAAIAEgDqDAAABQAwAG4MAAABABEAEgAICcwNXyIAVAEIaAwAAAYAKgBpDAAABQArAGsMAAAFADUAagwAAAUAMwBsDAAABAAVAG0MAAACABIA6gwAAAUAMABuDAAAAQARAAAA.',
Hu='Huntlord:BAAALgADCgcJBwAAAA==.',
Ia='Iamtrash:BAAALgAECgQJBAAAAA==.Iantha:BAAALgAECggJEgAAAA==.',
Ic='Icyprotoss:BAAALgAECgEJAQAAAA==.',
Ig='Igglybuff:BAABLgAECn8WAAIBAAcJXgsUHADHAAdoDAAAAwAfAGkMAAADABwAawwAAAMAJQBqDAAABQAnAGwMAAABAAQA6gwAAAYAQwBuDAAAAQAEAAEABwleCxQcAMcAB2gMAAADAB8AaQwAAAMAHABrDAAAAwAlAGoMAAAFACcAbAwAAAEABADqDAAABgBDAG4MAAABAAQAAAA=.',
Ij='Ijustshotyou:BAAALgAECgQJDQABLgAECggJLQABAKUYAA==.',
Il='Illyría:BAAALgADCgcJBwAAAA==.',
Ir='Ironlotss:BAAALgADCgkJDQAAAA==.',
Ja='Jags:BAAALgADCgUJBwABLgAECggJJQAbAO4dAA==.Jakob:BAAALgAECgEJAgAAAA==.Jaks:BAAALgADCgEJAQAAAA==.Jardal:BAAALgADCgUJCAAAAA==.Jayyo:BAAALgAECgIJAgAAAA==.',
Je='Jehbodia:BAAALgAECgUJEwAAAA==.Jenanila:BAAALgAECgEJAgAAAA==.',
Ji='Jibbs:BAABLgAECn8eAAMFAAgJxwdsZQAtAQhoDAAABQAfAGkMAAAFABMAawwAAAUACABqDAAABAAQAGwMAAADAB4AbQwAAAEABgDqDAAABgAfAG4MAAABAAoABQAHCaQIbGUALQEHaAwAAAUAHwBpDAAABQATAGsMAAAFAAgAagwAAAQAEABsDAAAAwAeAOoMAAAGAB8AbgwAAAEACgAEAAEJmALLQwAcAAFtDAAAAQAGAAAA.Jimmyhalpert:BAAALgADCgIJAgAAAA==.',
Jn='Jnymango:BAAALgAECgIJBAABLgAECgMJAwAJAAAAAA==.',
Jo='Joanexotic:BAAALgAECgYJDQAAAA==.Johnnysham:BAAALgAECgMJAwAAAA==.Jolah:BAAALgAECgIJAgAAAA==.Jollakeratu:BAABLgAECn8dAAIcAAcJzBHqDwA3AQdoDAAABQA4AGkMAAAFAC8AawwAAAUAJgBqDAAAAwAvAGwMAAAEADQA6gwAAAYANwBuDAAAAQAWABwABwnMEeoPADcBB2gMAAAFADgAaQwAAAUALwBrDAAABQAmAGoMAAADAC8AbAwAAAQANADqDAAABgA3AG4MAAABABYAAAA=.Jonnygordo:BAAALgAECgUJDAAAAA==.Jorahh:BAAALgAECgcJEgAAAA==.',
Ju='Jugram:BAAALgADCgkJHAAAAA==.Jungolv:BAAALgADCgMJAwAAAA==.Jusmissiner:BAABLgAECn8eAAIYAAgJ8h5yFgCEAghoDAAABABeAGkMAAAEAFEAawwAAAQAUgBqDAAABABQAGwMAAAEAE4AbQwAAAMAWQDqDAAABgBPAG4MAAABAC8AGAAICfIechYAhAIIaAwAAAQAXgBpDAAABABRAGsMAAAEAFIAagwAAAQAUABsDAAABABOAG0MAAADAFkA6gwAAAYATwBuDAAAAQAvAAAA.Jussmissiner:BAAALgADCgYJCQAAAA==.Juut:BAABLgAECn8ZAAIEAAgJ/BhsDQC0AQhoDAAABgBfAGkMAAAFAFUAawwAAAUAQgBqDAAAAgAwAGwMAAABABcAbQwAAAEAOQDqDAAABABXAG4MAAABACAABAAICfwYbA0AtAEIaAwAAAYAXwBpDAAABQBVAGsMAAAFAEIAagwAAAIAMABsDAAAAQAXAG0MAAABADkA6gwAAAQAVwBuDAAAAQAgAAAA.',
['Jø']='Jønty:BAAALgADCgUJCAAAAA==.',
Ka='Kaelyra:BAAALgADCgUJCAAAAA==.Kaitenn:BAAALgAECgYJBgAAAA==.Kamehame:BAAALgAECggJEgAAAA==.Kaseus:BAAALgAECgIJAgAAAA==.',
Kb='Kbetty:BAAALgADCgcJBwABLgAECgkJJgACANEeAA==.',
Ke='Keelhorn:BAABLgAECn8iAAICAAkJGRTjGgDzAQloDAAABQBEAGkMAAAFAEcAawwAAAUALQBqDAAABAAsAGwMAAAEAEMAbQwAAAIAGADqDAAABQBNAG4MAAADABAAbwwAAAEALgACAAkJGRTjGgDzAQloDAAABQBEAGkMAAAFAEcAawwAAAUALQBqDAAABAAsAGwMAAAEAEMAbQwAAAIAGADqDAAABQBNAG4MAAADABAAbwwAAAEALgAAAA==.Kevin:BAAALgAECgYJDAABLgAFFAUJBQAXAKoOAA==.Keyadorath:BAAALgADCgIJAgAAAA==.',
Ki='Kibon:BAAALgAECgUJDgAAAA==.Kinkyhawt:BAEALgAECgYJEgAAAA==.Kirio:BAAALgADCgcJCgAAAA==.Kitsunenohi:BAAALgAECgcJEQAAAA==.',
Ko='Kodiakk:BAAALgAECgYJEgAAAA==.Kozilek:BAAALgADCgQJBAAAAA==.',
Kr='Kramden:BAAALgADCgcJDgAAAA==.Krattos:BAAALgAECgIJAwAAAA==.Krimzin:BAAALgAECgEJAQABLgAFFAQJDAAYAHIbAA==.',
Ku='Kuddles:BAAALgADCgEJBAAAAA==.Kumei:BAAALgADCgMJAwABLgAECgkJLAAYABEQAA==.Kural:BAAALgAECgUJBgABLgAECggJJgABALwiAA==.',
Kw='Kwazii:BAABLgAECn8ZAAQdAAcJzxlqJgC5AQdoDAAABABQAGkMAAAEAFYAawwAAAIAPABqDAAABAA8AGwMAAAEAFsAbQwAAAIAHwDqDAAABQAzAB0ABwnPGWomALkBB2gMAAADAFAAaQwAAAMAVgBrDAAAAQA8AGoMAAADADwAbAwAAAQAWwBtDAAAAgAfAOoMAAAEADMAAwAECVUClFUAawAEaAwAAAEABwBpDAAAAQAEAGsMAAABAAYAagwAAAEAAwAeAAEJGwaQUwApAAHqDAAAAQAPAAAA.',
Ky='Kyantzmi:BAAALgAECgMJBAAAAA==.Kyogre:BAAALgAECgYJDAAAAA==.',
La='Laefnia:BAABLgAECn8VAAUGAAcJ4xK0ZQAhAQdoDAAAAwAxAGkMAAAEAFcAawwAAAQAMwBqDAAAAwAiAGwMAAACACAA6gwAAAQANwBuDAAAAQAbAAYABQm+FbRlACEBBWgMAAABADEAaQwAAAEAVwBrDAAAAQAzAGoMAAACACIA6gwAAAQANwAXAAYJmxFaVwDHAAZoDAAAAgA4AGkMAAACACkAawwAAAMAMQBqDAAAAQAmAGwMAAABABIAbgwAAAEAOwAfAAEJNAZ9NQAuAAFpDAAAAQAPABwAAQnyEgAAAAAAAWwMAAABADAAAAA=.Laraydra:BAAALgAECgQJBQABLgAECgcJDgAJAAAAAA==.Lastofgoobs:BAAALgADCgQJBAAAAA==.Latias:BAAALgADCgUJBQABLgAECgcJGQAaAD0QAA==.Lavaburstya:BAAALgAECgcJDAAAAA==.',
Le='Leomist:BAAALgAECgcJCwAAAA==.Leviosä:BAABLgAECn8jAAIHAAgJTBN9RwCkAQhoDAAABQA0AGkMAAAFADwAawwAAAUANgBqDAAABQA7AGwMAAAFADcAbQwAAAMAKADqDAAABQA+AG4MAAACABMABwAICUwTfUcApAEIaAwAAAUANABpDAAABQA8AGsMAAAFADYAagwAAAUAOwBsDAAABQA3AG0MAAADACgA6gwAAAUAPgBuDAAAAgATAAAA.',
Li='Liden:BAAALgADCgMJAwAAAA==.Lildarleena:BAAALgADCgkJHQAAAA==.Lilis:BAAALgADCgcJCwAAAA==.Lilithe:BAAALgAECgIJAQAAAA==.Lillíth:BAABLgAECn8tAAIFAAkJYiTgAgBQAwloDAAABgBiAGkMAAAGAGMAawwAAAYAVwBqDAAABgBjAGwMAAAFAGIAbQwAAAQAXQDqDAAABgBgAG4MAAAEAF4AbwwAAAIASwAFAAkJYiTgAgBQAwloDAAABgBiAGkMAAAGAGMAawwAAAYAVwBqDAAABgBjAGwMAAAFAGIAbQwAAAQAXQDqDAAABgBgAG4MAAAEAF4AbwwAAAIASwAAAA==.Liten:BAAALgADCgUJCAAAAA==.Littlebev:BAAALgAECgQJBQAAAA==.',
Lo='Lockmender:BAAALgAECgMJAwAAAA==.Logonman:BAAALgAECgYJBwAAAA==.Longshankss:BAAALgAECgUJCgAAAA==.',
['Lí']='Lírii:BAAALgAECgcJEQAAAA==.',
['Lô']='Lôôbmeup:BAAALgADCgEJAQAAAA==.',
Ma='Maachen:BAAALgAECgYJCwAAAA==.Maalik:BAABLgAECn8sAAMgAAgJLh0gAwD6AQhoDAAABwBYAGkMAAAJAFIAawwAAAkAVABqDAAAAwAtAGwMAAADAEgAbQwAAAIAJQDqDAAACgBeAG4MAAABAD4AIAAICS4dIAMA+gEIaAwAAAMAWABpDAAABABSAGsMAAAEAFQAagwAAAEALQBsDAAAAgBIAG0MAAABACUA6gwAAAgAXgBuDAAAAQA+ACEABwmEFUwbAHIBB2gMAAAEAEEAaQwAAAUASgBrDAAABQA7AGoMAAACABwAbAwAAAEAKABtDAAAAQAiAOoMAAACADgAAAA=.Magejackky:BAAALgAECgQJCAAAAA==.Magiclaw:BAAALgAECgEJAQAAAA==.Malaurray:BAAALgAECgYJEwABLgABCgQJBgAJAAAAAA==.Mavanta:BAAALgAECgMJBAAAAA==.Mayonæse:BAAALgAECgkJCQAAAA==.',
Mc='Mckennah:BAABLgAECn8VAAMBAAcJOx8jBgAYAgdoDAAAAwBTAGkMAAADAFYAawwAAAQAWgBqDAAAAwBaAGwMAAADAFQA6gwAAAQAVwBuDAAAAQAvAAEABwk7HyMGABgCB2gMAAADAFMAaQwAAAMAVgBrDAAABABaAGoMAAADAFoAbAwAAAMAVADqDAAAAwBXAG4MAAABAC8ACwABCQ4MfhkBNgAB6gwAAAEAHgAAAA==.',
Me='Mereideath:BAAALgADCgMJAwABLgAECgcJIAAHABEVAA==.Mereidith:BAABLgAECn8gAAMHAAcJERVWZQBZAQdoDAAABgBDAGkMAAAFADgAawwAAAYARQBqDAAABAAZAGwMAAADACcAbQwAAAEABgDqDAAABwBSAAcABwkBFFZlAFkBB2gMAAAFADMAaQwAAAUAOABrDAAABgBFAGoMAAAEABkAbAwAAAMAJwBtDAAAAQAGAOoMAAAHAFIAIgABCXIaExkATwABaAwAAAEAQwAAAA==.Meshulk:BAAALgAECgEJAQAAAA==.Mesohungry:BAABLgAECn8pAAMjAAgJrgepMAAnAQhoDAAABgAyAGkMAAAHAAwAawwAAAYADgBqDAAABAAMAGwMAAAGAAQAbQwAAAMACADqDAAABgAlAG4MAAADAA8AIwAICa4HqTAAJwEIaAwAAAYAMgBpDAAABwAMAGsMAAAGAA4AagwAAAQADABsDAAABQAEAG0MAAABAAgA6gwAAAYAJQBuDAAAAwAPAAsAAgnJAZoxASgAAmwMAAABAAQAbQwAAAIABAAAAA==.',
Mi='Mikehunte:BAAALgAECgYJBgABLgAECgkJGwAHAAoeAA==.Miriya:BAABLgAECn8jAAIKAAkJyCSyAABXAwloDAAABQBhAGkMAAAFAGIAawwAAAUAYgBqDAAABQBhAGwMAAAEAGEAbQwAAAMATQDqDAAABABfAG4MAAADAGIAbwwAAAEAWgAKAAkJyCSyAABXAwloDAAABQBhAGkMAAAFAGIAawwAAAUAYgBqDAAABQBhAGwMAAAEAGEAbQwAAAMATQDqDAAABABfAG4MAAADAGIAbwwAAAEAWgAAAA==.Missnoms:BAAALgAECgEJAQAAAA==.',
Mo='Monkeycheese:BAABLgAECn8ZAAIaAAcJPRCwHgBCAQdoDAAABQA2AGkMAAAEADwAawwAAAMAIQBqDAAABAAYAGwMAAAEACsAbQwAAAEAEwDqDAAABAAlABoABwk9ELAeAEIBB2gMAAAFADYAaQwAAAQAPABrDAAAAwAhAGoMAAAEABgAbAwAAAQAKwBtDAAAAQATAOoMAAAEACUAAAA=.Moobáca:BAAALgAECgEJAgAAAA==.Moostradamas:BAABLgAECn8bAAMPAAgJ7wVGCwAAAQhoDAAABAAQAGkMAAAEAA4AawwAAAQADwBqDAAABAAMAGwMAAAEABEAbQwAAAEAAwDqDAAABQASAG4MAAABABMADwAICe8FRgsAAAEIaAwAAAMAEABpDAAABAAOAGsMAAAEAA8AagwAAAQADABsDAAABAARAG0MAAABAAMA6gwAAAQAEgBuDAAAAQATAAUAAgmyAGATASQAAmgMAAABAAEA6gwAAAEAAgAAAA==.Morcilla:BAAALgAECgcJDgAAAA==.',
Ms='Msg:BAABLgAECn8ZAAIGAAgJtBw/EQBeAghoDAAABABVAGkMAAADAEwAawwAAAIAUgBqDAAABABHAGwMAAAFAGAAbQwAAAIAMADqDAAABABWAG4MAAABACgABgAICbQcPxEAXgIIaAwAAAQAVQBpDAAAAwBMAGsMAAACAFIAagwAAAQARwBsDAAABQBgAG0MAAACADAA6gwAAAQAVgBuDAAAAQAoAAAA.',
Mu='Munassa:BAAALgADCgQJBAAAAA==.Muppets:BAAALgAECgUJCQAAAA==.',
My='Myssidia:BAAALgADCgUJCAAAAA==.',
Na='Naleria:BAAALgADCgYJBgAAAA==.Narisa:BAAALgAECgIJAwAAAA==.Nastrodamus:BAAALgADCgYJBgAAAA==.Naturegoob:BAABLgAECn8bAAMGAAgJqBogNADYAQhoDAAABABgAGkMAAAEAFYAawwAAAQAPwBqDAAAAwA+AGwMAAAEAE4AbQwAAAIAPADqDAAABAAzAG4MAAACAC4ABgAICagaIDQA2AEIaAwAAAMAYABpDAAAAwBWAGsMAAADAD8AagwAAAMAPgBsDAAABABOAG0MAAACADwA6gwAAAQAMwBuDAAAAgAuABcAAwnhEWA6ALUAA2gMAAABADMAaQwAAAEAOABrDAAAAQAdAAAA.Naughtynurse:BAABLgAECn8iAAIGAAkJ1w5sMQBuAQloDAAABgAqAGkMAAAFADgAawwAAAUAMgBqDAAABQAwAGwMAAAFAC0AbQwAAAEABgDqDAAABQA9AG4MAAABAAsAbwwAAAEAEwAGAAkJ1w5sMQBuAQloDAAABgAqAGkMAAAFADgAawwAAAUAMgBqDAAABQAwAGwMAAAFAC0AbQwAAAEABgDqDAAABQA9AG4MAAABAAsAbwwAAAEAEwAAAA==.',
Ne='Nemrak:BAAALgAFFAIJAgAAAA==.Neuma:BAAALgAECgQJEwAAAA==.',
Ni='Nicfurry:BAAALgADCgIJAgAAAA==.Nightflower:BAABLgAECn8iAAMiAAkJUQUhDwDRAAloDAAABgAWAGkMAAADAA4AawwAAAMADwBqDAAAAwARAGwMAAAGABYAbQwAAAMABgDqDAAABQANAG4MAAAEAAQAbwwAAAEACQAHAAcJFgWjhAAcAQdoDAAAAwAWAGoMAAABABEAbAwAAAQAFgBtDAAAAwAGAOoMAAADAA0AbgwAAAQABABvDAAAAQAJACIABgkDBCEPANEABmgMAAADAAcAaQwAAAMADgBrDAAAAwAPAGoMAAACAAkAbAwAAAIACADqDAAAAgAEAAAA.',
No='Novadots:BAAALgAECgEJAgAAAA==.',
Ny='Nyxon:BAAALgAECgYJCgABLgAECgYJDQAJAAAAAA==.',
['Nä']='Nätê:BAAALgAECgMJAwAAAA==.',
['Nî']='Nîbbles:BAAALgAECgIJAgAAAA==.',
Ob='Obiejuan:BAABLgAECn82AAILAAkJ6CAABQASAwloDAAACABgAGkMAAAHAF0AawwAAAcAXgBqDAAABwBaAGwMAAAHAFwAbQwAAAUAXQDqDAAABwBXAG4MAAAEAFAAbwwAAAIAIgALAAkJ6CAABQASAwloDAAACABgAGkMAAAHAF0AawwAAAcAXgBqDAAABwBaAGwMAAAHAFwAbQwAAAUAXQDqDAAABwBXAG4MAAAEAFAAbwwAAAIAIgAAAA==.Obietide:BAAALgAECgYJCAABLgAECgkJNgALAOggAA==.',
Od='Oddball:BAABLgAECn8cAAISAAgJgRxsDgAPAghoDAAABABTAGkMAAAEAFQAawwAAAQATwBqDAAAAwBOAGwMAAADAFMAbQwAAAIAJwDqDAAABgBZAG4MAAACADIAEgAICYEcbA4ADwIIaAwAAAQAUwBpDAAABABUAGsMAAAEAE8AagwAAAMATgBsDAAAAwBTAG0MAAACACcA6gwAAAYAWQBuDAAAAgAyAAAA.',
Of='Ofthecircle:BAAALgAECggJDwAAAA==.',
Ok='Okamiblooded:BAAALgAECgIJAwAAAA==.',
Ol='Olly:BAAALgAECgUJBQAAAA==.',
Oo='Oodles:BAAALgAECgYJEQAAAA==.',
Or='Orangekeg:BAAALgAECgUJEQABLgAECggJFgASAGAfAA==.Oritoko:BAAALgAECgQJBAAAAA==.Orthiaa:BAAALgAECgMJBAAAAA==.',
Pa='Palpinaintez:BAAALgAECgYJDgAAAA==.Parras:BAAALgAECgEJAQAAAA==.',
Pe='Penzarion:BAAALgADCgUJBQAAAA==.Perison:BAABLgAECn8tAAIEAAkJiBxIBACTAgloDAAABwBTAGkMAAAGAEsAawwAAAYAUgBqDAAABQBMAGwMAAAGAFMAbQwAAAUAQQDqDAAABABMAG4MAAAEAEIAbwwAAAIAMgAEAAkJiBxIBACTAgloDAAABwBTAGkMAAAGAEsAawwAAAYAUgBqDAAABQBMAGwMAAAGAFMAbQwAAAUAQQDqDAAABABMAG4MAAAEAEIAbwwAAAIAMgABLgAECggJJgABALwiAA==.Peso:BAAALgADCgUJAwAAAA==.',
Ph='Phaidon:BAAALgAECgcJCQAAAA==.',
Po='Pokeylock:BAAALgADCggJCAAAAA==.Polyhedroll:BAABLgAFFH8GAAIRAAQJQQycFQABAQRoDAAAAgAZAGkMAAACACQAawwAAAEAJwDqDAAAAQAXABEABAlBDJwVAAEBBGgMAAACABkAaQwAAAIAJABrDAAAAQAnAOoMAAABABcAAS4ABRQECQgAIwBhEgA=.Postmalorne:BAAALgADCgMJAwAAAA==.Potatopp:BAABLgAECn8YAAIHAAgJOQlbXgBpAQhoDAAABAAuAGkMAAAEACMAawwAAAQAFgBqDAAAAwAiAGwMAAADABYAbQwAAAEAEQDqDAAAAwAPAG4MAAACAAUABwAICTkJW14AaQEIaAwAAAQALgBpDAAABAAjAGsMAAAEABYAagwAAAMAIgBsDAAAAwAWAG0MAAABABEA6gwAAAMADwBuDAAAAgAFAAAA.',
Pp='Ppincoke:BAAALgADCgEJAQABLgAECggJJwACACUiAA==.',
Pr='Primafox:BAAALgAECgQJCgAAAA==.Prkchopxpres:BAAALgAECgYJDgAAAA==.Protoheal:BAAALgADCgEJAQAAAA==.',
Pu='Punchandkick:BAAALgAECgMJBgAAAA==.',
['Pä']='Päw:BAABLgAECn8YAAIFAAgJ8xRBLADhAQhoDAAABABWAGkMAAAEADoAawwAAAQAJABqDAAABAAwAGwMAAADADcAbQwAAAEALwDqDAAAAgA4AG4MAAACACIABQAICfMUQSwA4QEIaAwAAAQAVgBpDAAABAA6AGsMAAAEACQAagwAAAQAMABsDAAAAwA3AG0MAAABAC8A6gwAAAIAOABuDAAAAgAiAAAA.',
Qu='Quetzalcóatl:BAAALgAECgQJBAAAAA==.Quickclaw:BAAALgADCgEJAQAAAA==.Quivermethis:BAAALgAECgEJAgAAAA==.',
Qx='Qx:BAAALgADCggJDgAAAA==.',
Ra='Radge:BAABLgAECn8lAAMkAAgJjiH+AgDkAghoDAAABQBiAGkMAAAIAGAAawwAAAYAVgBqDAAABgBhAGwMAAAFAGAAbQwAAAMAXwDqDAAAAwBdAG4MAAABACIAJAAICVUh/gIA5AIIaAwAAAQAYgBpDAAACABgAGsMAAAGAFYAagwAAAYAYQBsDAAABQBgAG0MAAACAF8A6gwAAAIAWQBuDAAAAQAiABMAAwkpHSt2AOIAA2gMAAABAE0AbQwAAAEANQDqDAAAAQBdAAAA.Rainjar:BAABLgAECn81AAMQAAkJzCEJAgDwAgloDAAACABgAGkMAAAIAGMAawwAAAcAXgBqDAAABwBcAGwMAAAHAF0AbQwAAAQATQDqDAAABgBeAG4MAAAFAGAAbwwAAAEAJwAQAAkJXB8JAgDwAgloDAAABwBgAGkMAAAHAGMAawwAAAYAXgBqDAAABgBcAGwMAAAGAF0AbQwAAAIAJwDqDAAABQBeAG4MAAADAFQAbwwAAAEAJwAYAAgJAiKfCwCYAghoDAAAAQBYAGkMAAABAFEAawwAAAEATQBqDAAAAQBaAGwMAAABAFwAbQwAAAIATQDqDAAAAQBeAG4MAAACAGAAAAA=.Rainne:BAAALgADCgcJCAAAAA==.Raistyn:BAABLgAECn8dAAIBAAgJxx0kCwAaAghoDAAABABXAGkMAAAFAFYAawwAAAUAUgBqDAAABABQAGwMAAADAEgAbQwAAAMAUQDqDAAAAwBQAG4MAAACACsAAQAICccdJAsAGgIIaAwAAAQAVwBpDAAABQBWAGsMAAAFAFIAagwAAAQAUABsDAAAAwBIAG0MAAADAFEA6gwAAAMAUABuDAAAAgArAAAA.Ralanar:BAAALgAECgEJAgABLgAECgcJDgAJAAAAAA==.Raljah:BAABLgAECn8qAAQgAAgJJiSyAADEAghoDAAABwBhAGkMAAAHAFcAawwAAAcAXABqDAAABQBXAGwMAAAEAGEAbQwAAAMAVwDqDAAABwBfAG4MAAACAFkAIAAHCSYksgAAxAIHaAwAAAIAYQBpDAAAAgBXAGsMAAACAFwAbAwAAAEAYQBtDAAAAQBXAOoMAAACAF8AbgwAAAEAWQAbAAcJjR7LEQBnAgdoDAAABABbAGkMAAAEAFEAawwAAAQASgBsDAAAAwBNAG0MAAACAFQA6gwAAAQARwBuDAAAAQBCACEABQkWHX0UAKcBBWgMAAABAFsAaQwAAAEARgBrDAAAAQBFAGoMAAAFAFcA6gwAAAEAQgAAAA==.Ramasus:BAAALgAECgUJBQAAAA==.Rampart:BAABLgAECn8WAAIBAAYJkBR6EgAuAQZoDAAABABGAGkMAAAEAEAAawwAAAQANABqDAAAAwBEAGwMAAADACwA6gwAAAQAHgABAAYJkBR6EgAuAQZoDAAABABGAGkMAAAEAEAAawwAAAQANABqDAAAAwBEAGwMAAADACwA6gwAAAQAHgAAAA==.Rasaltghul:BAAALgADCgQJBAABLgAECgMJBgAJAAAAAA==.Rashomon:BAAALgAECgEJAQAAAA==.Raxxer:BAAALgAECgEJAgAAAA==.',
Re='Recklessfury:BAAALgADCgYJAgAAAA==.Reignasmite:BAAALgAECgcJCgAAAA==.Reiko:BAAALgADCgUJBQAAAA==.Renm:BAAALgAECgYJEgAAAA==.Renpriest:BAACLgAFFH8MAAIeAAMJLhcqGQD5AANoDAAABQAvAGkMAAAFAEsA6gwAAAIANwAeAAMJLhcqGQD5AANoDAAABQAvAGkMAAAFAEsA6gwAAAIANwAuAAQKfxUAAx4ACAmMGVIRAC4CAB4ACAmMGVIRAC4CAAMAAQk4FapUAD8AAAAA.',
Rh='Rhaege:BAAALgADCgUJBgAAAA==.',
Ro='Rokk:BAAALgADCgUJCAAAAA==.Rolemiso:BAAALgADCgEJAQAAAA==.',
Ry='Ryobi:BAABLgAECn8dAAMYAAgJxRNOJwDJAQhoDAAABAAkAGkMAAAEACsAawwAAAQALABqDAAABAAkAGwMAAAEADUAbQwAAAIAUwDqDAAABAAqAG4MAAADADMAGAAICUkTTicAyQEIaAwAAAEAJABpDAAAAQArAGsMAAABACMAagwAAAEAJABsDAAAAQA1AG0MAAACAFMA6gwAAAEAKgBuDAAAAgAzABkABwl2CV0PAAUBB2gMAAADABQAaQwAAAMAIgBrDAAAAwAsAGoMAAADABQAbAwAAAMABwDqDAAAAwAgAG4MAAABAAYAAAA=.',
['Ræ']='Rævena:BAAALgAECgcJCQAAAA==.',
Sa='Sachaann:BAAALgAECgEJAQAAAA==.Salinan:BAABLgAECn82AAMgAAkJliQ1AAArAwloDAAACABiAGkMAAAHAF4AawwAAAcAYQBqDAAABwBYAGwMAAAHAGMAbQwAAAUAXgDqDAAABwBgAG4MAAAEAE0AbwwAAAIAXAAgAAkJliQ1AAArAwloDAAABwBiAGkMAAAHAF4AawwAAAcAYQBqDAAABwBYAGwMAAAHAGMAbQwAAAQAXgDqDAAABwBgAG4MAAACAE0AbwwAAAEAXAAbAAQJqBcBfgDcAARoDAAAAQA7AG0MAAABAEwAbgwAAAIAOwBvDAAAAQAuAAAA.Saltymon:BAAALgADCgYJBgABLgAECgEJAQAJAAAAAA==.Saox:BAAALgAECgYJCAABLgAECgcJGQAlADEYAA==.Saric:BAAALgADCgMJAwAAAA==.Satanownsyou:BAAALgADCgEJAQAAAA==.',
Sc='Schûltz:BAAALgADCgMJAwAAAA==.Scoop:BAAALgAECgYJBQAAAA==.',
Se='Seleñe:BAAALgAECgEJAQAAAA==.Selinedion:BAAALgAECgcJEAAAAA==.Selky:BAAALgADCgcJCgAAAA==.',
Sf='Sfodin:BAABLgAECn8UAAITAAcJ+weRLQAoAQdoDAAABAASAGkMAAAEACEAawwAAAQAGABqDAAAAgAYAGwMAAABAAwA6gwAAAQAEwBuDAAAAQANABMABwn7B5EtACgBB2gMAAAEABIAaQwAAAQAIQBrDAAABAAYAGoMAAACABgAbAwAAAEADADqDAAABAATAG4MAAABAA0AAAA=.',
Sh='Shak:BAAALgAECgYJCAAAAA==.Shalai:BAAALgADCgMJAwAAAA==.Shalynn:BAAALgADCgIJAgAAAA==.Shandra:BAAALgADCgcJCwAAAA==.Shastix:BAAALgAECgYJCgABLgAECggJLAAgAC4dAA==.Shellingtun:BAAALgAECgYJCwAAAA==.Shyandrial:BAAALgADCgcJFQAAAA==.',
Si='Siathena:BAAALgADCgMJAwAAAA==.Sintharia:BAABLgAECn8ZAAIDAAgJjgnrHgBbAQhoDAAABAArAGkMAAAEABcAawwAAAUAEgBqDAAABAAaAGwMAAAEAA8AbQwAAAEAGADqDAAAAgASAG4MAAABABsAAwAICY4J6x4AWwEIaAwAAAQAKwBpDAAABAAXAGsMAAAFABIAagwAAAQAGgBsDAAABAAPAG0MAAABABgA6gwAAAIAEgBuDAAAAQAbAAAA.',
Sk='Skilltotem:BAAALgAECggJDwAAAA==.Skk:BAAALgADCggJCQAAAA==.Sksteve:BAAALgAECgUJDAAAAA==.Skullyy:BAAALgAECgIJBAABLgAECgYJDQAJAAAAAA==.Skychades:BAAALgAECgYJDgAAAA==.',
Sl='Slammajamma:BAAALgAECgkJCQAAAA==.Slowpoke:BAABLgAECn8WAAIXAAcJlw6VLAD6AAdoDAAAAwArAGkMAAADACgAawwAAAMAIQBqDAAABQAwAGwMAAABACwA6gwAAAYAJwBuDAAAAQAVABcABwmXDpUsAPoAB2gMAAADACsAaQwAAAMAKABrDAAAAwAhAGoMAAAFADAAbAwAAAEALADqDAAABgAnAG4MAAABABUAAAA=.Slyfauna:BAAALgAECgEJAQAAAA==.',
Sn='Snorlax:BAAALgAECgEJAQABLgAECgcJFgAXAJcOAA==.',
So='Sofakingroot:BAAALgADCgYJCQAAAA==.Soft:BAAALgAECgIJAgAAAA==.Softpaw:BAAALgADCgYJBgAAAA==.Soulrobber:BAAALgADCgkJCQAAAA==.Soulsrequiem:BAAALgAECgYJDAAAAA==.',
Sp='Spicyblaster:BAAALgAECgUJBQAAAA==.Spookydeath:BAACLgAFFH8JAAIHAAMJbwmpVwDmAANoDAAAAwAQAGkMAAADAA8A6gwAAAMAKAAHAAMJbwmpVwDmAANoDAAAAwAQAGkMAAADAA8A6gwAAAMAKAAuAAQKfycAAgcACQm2D6IsAAICAAcACQm2D6IsAAICAAAA.',
Sr='Srsnacksalot:BAABLgAECn8cAAILAAgJHRRQNgC6AQhoDAAABQAsAGkMAAAFAD4AawwAAAUAOABqDAAAAQA6AGwMAAADACgAbQwAAAEAKgDqDAAABwBEAG4MAAABACwACwAICR0UUDYAugEIaAwAAAUALABpDAAABQA+AGsMAAAFADgAagwAAAEAOgBsDAAAAwAoAG0MAAABACoA6gwAAAcARABuDAAAAQAsAAAA.',
St='Stileto:BAAALgAECgYJCgAAAA==.Stoneydracco:BAAALgAECgYJDwAAAA==.Stoneydragon:BAAALgADCgYJBgAAAA==.Stormpuppy:BAAALgADCgEJAQAAAA==.Sturnguard:BAAALgAECgUJCwAAAA==.',
Su='Sukiliana:BAAALgAECgMJBAAAAA==.Sumtinwng:BAABLgAECn8gAAILAAgJxg0NSACDAQhoDAAABwA3AGkMAAAGACkAawwAAAQAHABqDAAABAAhAGwMAAADABkAbQwAAAIAIwDqDAAABAAjAG4MAAACABYACwAICcYNDUgAgwEIaAwAAAcANwBpDAAABgApAGsMAAAEABwAagwAAAQAIQBsDAAAAwAZAG0MAAACACMA6gwAAAQAIwBuDAAAAgAWAAAA.Supervicious:BAABLgAECn8VAAIMAAgJohMyEABtAQhoDAAABQAyAGkMAAAEAEMAawwAAAMAOABqDAAAAgAjAGwMAAABABYAbQwAAAEAJADqDAAABABDAG4MAAABADIADAAICaITMhAAbQEIaAwAAAUAMgBpDAAABABDAGsMAAADADgAagwAAAIAIwBsDAAAAQAWAG0MAAABACQA6gwAAAQAQwBuDAAAAQAyAAAA.',
Sw='Swiftheålzz:BAAALgAECgYJCwAAAA==.',
Sy='Sydah:BAAALgADCgUJCAAAAA==.Sylenne:BAABLgAECn8tAAIGAAkJDRaaEgBPAgloDAAABgA7AGkMAAAGAFIAawwAAAYAMwBqDAAABgA/AGwMAAAFAD4AbQwAAAQAOwDqDAAABgA/AG4MAAAEACAAbwwAAAIAIQAGAAkJDRaaEgBPAgloDAAABgA7AGkMAAAGAFIAawwAAAYAMwBqDAAABgA/AGwMAAAFAD4AbQwAAAQAOwDqDAAABgA/AG4MAAAEACAAbwwAAAIAIQAAAA==.Sylur:BAAALgAECgQJBQABLgAECgYJGAAGAPYbAA==.',
Ta='Taemea:BAAALgAECggJEQAAAA==.Tahran:BAAALgAECgEJAQABLgAFFAQJDQAeABAYAA==.Tahren:BAACLgAFFH8NAAMeAAQJEBiJEwA+AQRoDAAABQBgAGkMAAAEAC0AawwAAAEAJgDqDAAAAwBCAB4ABAkUFIkTAD4BBGgMAAAEADcAaQwAAAQALQBrDAAAAQAmAOoMAAADAEIAHQABCbwlRB0AbAABaAwAAAEAYAAuAAQKfx4ABB0ACAltIHMQAGECAB0ABwn0IHMQAGECAB4ABQleE1grAEABAAMABAn1DVRJAGYAAAAA.Talanima:BAAALgADCgcJBwAAAA==.Talerion:BAAALgAECgYJEAAAAA==.',
Tc='Tcdots:BAAALgAECgEJAQAAAA==.',
Te='Tens:BAABLgAECn8bAAITAAgJJiNXDAD1AghoDAAABABdAGkMAAAEAGEAawwAAAQAYwBqDAAAAwBfAGwMAAAEAF8AbQwAAAIAWQDqDAAABQBZAG4MAAABAEEAEwAICSYjVwwA9QIIaAwAAAQAXQBpDAAABABhAGsMAAAEAGMAagwAAAMAXwBsDAAABABfAG0MAAACAFkA6gwAAAUAWQBuDAAAAQBBAAAA.',
Th='Thatonemonk:BAAALgAECgUJCwAAAA==.Theafflictor:BAAALgAECgUJBwAAAA==.Theoneshaman:BAAALgADCgQJBAABLgAECgUJCwAJAAAAAA==.Thereaben:BAAALgADCggJCwAAAA==.Thistelbear:BAABLgAECn8cAAIaAAcJ3QV7LADqAAdoDAAABQAKAGkMAAAFABcAawwAAAUAEgBqDAAAAwAXAGwMAAADAA8A6gwAAAYADgBuDAAAAQAHABoABwndBXssAOoAB2gMAAAFAAoAaQwAAAUAFwBrDAAABQASAGoMAAADABcAbAwAAAMADwDqDAAABgAOAG4MAAABAAcAAAA=.Thrallsux:BAAALgAECgEJAQAAAA==.Thraun:BAAALgAECgYJEgAAAA==.Thrâl:BAAALgAECgMJBgAAAA==.Thunderdin:BAABLgAECn8nAAILAAgJOhKiagCpAQhoDAAABwAyAGkMAAAGADoAawwAAAYALQBqDAAABAAvAGwMAAADAFIAbQwAAAIAHQDqDAAABwAnAG4MAAAEABUACwAICToSomoAqQEIaAwAAAcAMgBpDAAABgA6AGsMAAAGAC0AagwAAAQALwBsDAAAAwBSAG0MAAACAB0A6gwAAAcAJwBuDAAABAAVAAAA.',
Ti='Titszilla:BAAALgAECgcJAwAAAA==.',
To='Toki:BAABLgAECn8bAAMRAAYJxxs5FADUAQZoDAAABgBNAGkMAAAGAE8AawwAAAUARwBqDAAAAwBIAGwMAAACADcA6gwAAAUARgARAAYJxxs5FADUAQZoDAAABQBNAGkMAAAFAE8AawwAAAQARwBqDAAAAwBIAGwMAAACADcA6gwAAAQARgAaAAQJqg+ZTQDbAARoDAAAAQAeAGkMAAABAD0AawwAAAEAMgDqDAAAAQASAAAA.Tokidormi:BAAALgADCgkJEwAAAA==.Toralus:BAAALgADCgYJCQAAAA==.Totumm:BAAALgADCgIJAgAAAA==.',
Tr='Tremmørs:BAABLgAECn8XAAISAAcJ0wuHLgAOAQdoDAAABQA6AGkMAAAEACsAawwAAAQAGgBqDAAAAgADAGwMAAACAAoAbQwAAAEAAADqDAAABQAqABIABwnTC4cuAA4BB2gMAAAFADoAaQwAAAQAKwBrDAAABAAaAGoMAAACAAMAbAwAAAIACgBtDAAAAQAAAOoMAAAFACoAAAA=.Trixiie:BAAALgADCgQJBAAAAA==.Truezangetsu:BAAALgAECgcJCwAAAA==.',
Tu='Turnip:BAAALgAECgEJAQAAAA==.',
Tw='Tweak:BAAALgAECgIJAgAAAA==.Tweis:BAAALgADCgUJCAAAAA==.',
Um='Umbrarogue:BAAALgAECggJEgAAAA==.',
Un='Unaires:BAAALgAECgEJAQAAAA==.',
Ur='Urzaa:BAAALgAECgUJEwAAAA==.',
Va='Valaa:BAAALgAECgUJBQAAAA==.Valdan:BAAALgADCgQJBgAAAA==.',
Ve='Veddicus:BAAALgADCgEJAQAAAA==.Velien:BAABLgAECn8VAAILAAkJOg4CcgCYAQloDAAAAgAtAGkMAAACACAAawwAAAIAKgBqDAAAAgAYAGwMAAACACEAbQwAAAIACQDqDAAABAArAG4MAAADADgAbwwAAAIAHQALAAkJOg4CcgCYAQloDAAAAgAtAGkMAAACACAAawwAAAIAKgBqDAAAAgAYAGwMAAACACEAbQwAAAIACQDqDAAABAArAG4MAAADADgAbwwAAAIAHQAAAA==.Vellestrix:BAAALgAECgMJAwAAAA==.Veppy:BAAALgADCgcJBwAAAA==.Vexare:BAAALgADCgYJBgAAAA==.Vexatious:BAAALgADCgUJBgAAAA==.Vexed:BAAALgADCgkJFAAAAA==.',
Vi='Viddysouls:BAAALgAECgUJEgAAAA==.Viscerai:BAABLgAECn8nAAIdAAgJDiZFAQBtAwhoDAAABgBiAGkMAAAFAGMAawwAAAYAYwBqDAAABQBhAGwMAAAEAGEAbQwAAAQAYgDqDAAABgBiAG4MAAADAFoAHQAICQ4mRQEAbQMIaAwAAAYAYgBpDAAABQBjAGsMAAAGAGMAagwAAAUAYQBsDAAABABhAG0MAAAEAGIA6gwAAAYAYgBuDAAAAwBaAAAA.Vite:BAAALgAECgYJDwAAAA==.Vitta:BAAALgAECgMJAwAAAA==.',
Vo='Vonmiller:BAABLgAECn8YAAMgAAcJ+RVABgD5AQdoDAAABAA/AGkMAAAEADgAawwAAAQAOwBqDAAAAwA7AGwMAAAEADwAbQwAAAEAGQDqDAAABABIACAABwn5FUAGAPkBB2gMAAADAD8AaQwAAAIAOABrDAAABAA7AGoMAAADADsAbAwAAAQAPABtDAAAAQAZAOoMAAAEAEgAGwACCRIM9/sAYgACaAwAAAEAIQBpDAAAAgAcAAAA.Vozluz:BAAALgAECgEJAQABLgAECggJLAAgAC4dAA==.',
Vu='Vulpix:BAAALgADCgcJBwABLgAECgcJFgAXAJcOAA==.',
['Væ']='Væda:BAAALgAECgIJAgAAAA==.',
Wa='Wanted:BAABLgAECn8ZAAIlAAcJMRgcEAC1AQdoDAAABABRAGkMAAAEAFEAawwAAAQARgBqDAAABAAvAGwMAAAEAD4A6gwAAAQAQgBvDAAAAQAIACUABwkxGBwQALUBB2gMAAAEAFEAaQwAAAQAUQBrDAAABABGAGoMAAAEAC8AbAwAAAQAPgDqDAAABABCAG8MAAABAAgAAAA=.Warfaxis:BAAALgAECgcJDAAAAA==.',
We='Weird:BAAALgAECgIJAgABLgAECgkJGAAGAB4SAA==.',
Wi='Wiseoldgoob:BAAALgAECgcJCAAAAA==.',
Wr='Wratth:BAAALgAECgUJDQAAAA==.',
Ww='Ww:BAAALgAFFAIJBAAAAA==.',
Wy='Wyldpyre:BAAALgADCgMJCAAAAA==.',
Xe='Xennessa:BAAALgAECgcJCwAAAA==.',
Ze='Zenclaw:BAABLgAECn8bAAIRAAcJdAsNKAAmAQdoDAAABAAiAGkMAAAEACAAawwAAAQAGgBqDAAABQAlAGwMAAAFABoA6gwAAAQAIABvDAAAAQAOABEABwl0Cw0oACYBB2gMAAAEACIAaQwAAAQAIABrDAAABAAaAGoMAAAFACUAbAwAAAUAGgDqDAAABAAgAG8MAAABAA4AAAA=.Zencore:BAABLgAECn8VAAIHAAgJdw+TTgCQAQhoDAAAAwAtAGkMAAADACUAawwAAAQAJQBqDAAAAgAVAGwMAAACADIAbQwAAAEAIADqDAAABQA8AG4MAAABAAwABwAICXcPk04AkAEIaAwAAAMALQBpDAAAAwAlAGsMAAAEACUAagwAAAIAFQBsDAAAAgAyAG0MAAABACAA6gwAAAUAPABuDAAAAQAMAAAA.Zenfaith:BAAALgADCgIJAgABLgAECggJFQAHAHcPAA==.Zenlock:BAAALgADCgIJAgABLgAECggJFQAHAHcPAA==.',
Zi='Ziel:BAAALgAECgkJCgABLgAECgkJIwAKAMgkAA==.',
['Ñö']='Ñövä:BAAALgADCgMJBAAAAA==.',
['ßu']='ßubba:BAAALgAECgQJCQAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
