local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Paladin-Retribution','Paladin-Protection','DeathKnight-Blood','Hunter-BeastMastery','Hunter-Marksmanship','Priest-Discipline','Shaman-Elemental','Evoker-Augmentation','Druid-Balance','Druid-Guardian','Druid-Feral','Druid-Restoration','Unknown-Unknown','Monk-Mistweaver','Warrior-Protection','Paladin-Holy','DemonHunter-Devourer','Monk-Brewmaster','Warlock-Demonology','DeathKnight-Unholy','Mage-Frost','Hunter-Survival','Rogue-Outlaw','Mage-Arcane','Rogue-Subtlety','Rogue-Assassination','Evoker-Devastation','Shaman-Enhancement','Warrior-Fury','DeathKnight-Frost','DemonHunter-Vengeance','DemonHunter-Havoc','Shaman-Restoration','Evoker-Preservation','Monk-Windwalker','Priest-Holy','Warrior-Arms','Priest-Shadow','Warlock-Destruction',}
local provider = {region='US',realm='Spinebreaker',name='US',type='daily',zone=46,date='2026-05-22',data={Aa='Aandidar:BAAALgAECgQJBAAAAA==.',
Ac='Aceroth:BAABLgAECn8rAAMBAAgJGRtXPgDqAQhoDAAABwBcAGkMAAAHAEkAawwAAAcATwBqDAAABgBKAGwMAAAFAD0AbQwAAAIANQDqDAAABgA7AG4MAAADAD8AAQAICWsaVz4A6gEIaAwAAAcAXABpDAAABwBJAGsMAAAHAE8AagwAAAYASgBsDAAABQA9AG0MAAACADUA6gwAAAYAOwBuDAAAAgAzAAIAAQn0GOI7AEUAAW4MAAABAD8AAAA=.',
Ad='Adarus:BAAALgAECgYJCQAAAA==.Addia:BAAALgAECgEJAgAAAA==.',
Ae='Aedran:BAAALgADCgIJAgAAAA==.Aelin:BAABLgAECn86AAIDAAkJaxRyEwCmAQloDAAABwA3AGkMAAAIAE8AawwAAAgAQABqDAAABwAjAGwMAAAHADAAbQwAAAYAIQDqDAAABwA7AG4MAAAFACsAbwwAAAMAIQADAAkJaxRyEwCmAQloDAAABwA3AGkMAAAIAE8AawwAAAgAQABqDAAABwAjAGwMAAAHADAAbQwAAAYAIQDqDAAABwA7AG4MAAAFACsAbwwAAAMAIQAAAA==.',
Ag='Agu:BAAALgAECgEJAgAAAA==.',
Ak='Akinna:BAAALgADCgIJAgAAAA==.',
Al='Alaran:BAAALgAECgEJAQAAAA==.Alaysia:BAAALgAECgUJBQAAAA==.Alestair:BAABLgAECn8eAAMEAAkJBgoUSgCTAQloDAAABQAlAGkMAAAFACMAawwAAAQAGwBqDAAABAAUAGwMAAADABAAbQwAAAIAHwDqDAAABAAWAG4MAAACABAAbwwAAAEAEQAEAAkJBgoUSgCTAQloDAAABQAlAGkMAAAEACMAawwAAAQAGwBqDAAABAAUAGwMAAADABAAbQwAAAIAHwDqDAAABAAWAG4MAAACABAAbwwAAAEAEQAFAAEJqQHimQAaAAFpDAAAAQAEAAAA.',
Am='Ampluslues:BAAALgADCgYJBgAAAA==.',
An='Andayn:BAAALgAECgIJAgAAAA==.Andro:BAAALgAECgcJBwAAAA==.Angelyna:BAAALgAECgYJBgAAAA==.Angrä:BAAALgAECgUJBgAAAA==.',
Ao='Aowynn:BAAALgADCgEJAQAAAA==.',
Ar='Arakfalas:BAAALgAECgYJDAAAAA==.Arise:BAAALgAECgUJBgAAAA==.Artshell:BAABLgAECn8aAAIGAAgJjwh0LgArAQhoDAAABQAVAGkMAAAEABoAawwAAAQAKABqDAAABAAgAGwMAAADABYAbQwAAAEADgDqDAAABAAPAG4MAAABAAEABgAICY8IdC4AKwEIaAwAAAUAFQBpDAAABAAaAGsMAAAEACgAagwAAAQAIABsDAAAAwAWAG0MAAABAA4A6gwAAAQADwBuDAAAAQABAAAA.',
As='Astalos:BAAALgAECgkJCgAAAA==.',
At='Atal:BAAALgADCgcJBwAAAA==.Atlask:BAAALgAECgEJAgAAAA==.Atsidi:BAABLgAECn8zAAIHAAgJahulEgAqAghoDAAACABPAGkMAAAIAFEAawwAAAYASABqDAAABwBCAGwMAAAGAFoAbQwAAAUAKgDqDAAABwBJAG4MAAAEADIABwAICWobpRIAKgIIaAwAAAgATwBpDAAACABRAGsMAAAGAEgAagwAAAcAQgBsDAAABgBaAG0MAAAFACoA6gwAAAcASQBuDAAABAAyAAAA.',
Au='Auran:BAAALgAECgUJBQABLgAFFAcJJwAIAN8cAA==.',
Az='Azaelara:BAABLgAECn8rAAICAAgJmwaiHwDjAAhoDAAABwAbAGkMAAAHAA0AawwAAAcADgBqDAAABgAJAGwMAAAFABAAbQwAAAIADwDqDAAABgAIAG4MAAADABYAAgAICZsGoh8A4wAIaAwAAAcAGwBpDAAABwANAGsMAAAHAA4AagwAAAYACQBsDAAABQAQAG0MAAACAA8A6gwAAAYACABuDAAAAwAWAAAA.Azanie:BAAALgAECgIJAgAAAA==.Azuula:BAAALgAECgcJCwAAAA==.',
Ba='Badmidget:BAAALgAECgQJBAAAAA==.Badmojojojo:BAAALgAECgkJDwABLgAECgkJGQAJAKIFAA==.Bakasura:BAAALgAECgIJAgAAAA==.Bankhand:BAAALgAECgQJBAAAAA==.Bannon:BAAALgAECgQJAwAAAA==.Bartab:BAABLgAECn8xAAQKAAkJERzLBACSAgloDAAABwBRAGkMAAAHAFEAawwAAAcAWQBqDAAABgBQAGwMAAAGAFAAbQwAAAQAPADqDAAACABPAG4MAAADADAAbwwAAAEANAAKAAkJERzLBACSAgloDAAABQBRAGkMAAAFAFEAawwAAAUAWQBqDAAABQBQAGwMAAAFAFAAbQwAAAQAPADqDAAABQBPAG4MAAADADAAbwwAAAEANAALAAUJ5BLFGQArAQVoDAAAAgAyAGkMAAACADgAawwAAAIAKwBqDAAAAQAaAOoMAAADACoADAABCc8CTuEAIwABbAwAAAEABwAAAA==.',
Be='Bearhugs:BAAALgAECgIJAgAAAA==.Beauadin:BAAALgADCgQJCAAAAA==.Beaudacious:BAAALgAECgQJBwAAAA==.Berka:BAAALgAECgMJBwAAAA==.',
Bh='Bhoomi:BAAALgAECgQJBQAAAA==.',
Bi='Bignugs:BAAALgAECgEJAQAAAA==.Bisbird:BAAALgADCgEJAQAAAA==.',
Bl='Blacktips:BAAALgAECgIJAgABLgAECgYJDgANAAAAAA==.Blenny:BAABLgAECn8qAAIMAAgJBwUjYgDrAAhoDAAABwAEAGkMAAAHACcAawwAAAcACABqDAAABgALAGwMAAAFAAkAbQwAAAIABwDqDAAABgAQAG4MAAACAAQADAAICQcFI2IA6wAIaAwAAAcABABpDAAABwAnAGsMAAAHAAgAagwAAAYACwBsDAAABQAJAG0MAAACAAcA6gwAAAYAEABuDAAAAgAEAAAA.Blindpickle:BAAALgAECgQJBgAAAA==.Blitzkriegen:BAAALgADCgEJAQAAAA==.Blitzkrîeg:BAAALgAECgQJBAAAAA==.',
Bo='Boyscourge:BAAALgAECgUJCwAAAA==.',
Br='Breezylock:BAAALgAECgYJCQAAAA==.Brewgar:BAABLgAECn8bAAIOAAkJzQ6mJwB3AQloDAAABQA5AGkMAAAEADIAawwAAAQANwBqDAAAAgAfAGwMAAACACMAbQwAAAEACADqDAAABQA9AG4MAAADABMAbwwAAAEAFAAOAAkJzQ6mJwB3AQloDAAABQA5AGkMAAAEADIAawwAAAQANwBqDAAAAgAfAGwMAAACACMAbQwAAAEACADqDAAABQA9AG4MAAADABMAbwwAAAEAFAAAAA==.Brewogenizer:BAAALgAECgEJAQABLgAECgkJMQAPAHAlAA==.Brightblade:BAABLgAECn8VAAMQAAgJtBB5MAC/AQhoDAAAAwBAAGkMAAADACEAawwAAAQAJwBqDAAAAgA4AGwMAAADAEMAbQwAAAIAJADqDAAAAwAdAG4MAAABAA0AEAAICbQQeTAAvwEIaAwAAAEAQABpDAAAAQAhAGsMAAACACcAagwAAAEAOABsDAAAAgBDAG0MAAACACQA6gwAAAMAHQBuDAAAAQANAAEABQn8Ik6GAG4BBWgMAAACAFAAaQwAAAIAXABrDAAAAgBdAGoMAAABAEYAbAwAAAEAWwABLgAFFAQJAwARAOQOAA==.Brucetea:BAABLgAECn8bAAISAAgJig5BKQBIAQhoDAAABAAZAGkMAAAEADEAawwAAAQAKABqDAAABAAZAGwMAAADADkAbQwAAAMAKgDqDAAAAgAYAG4MAAADABMAEgAICYoOQSkASAEIaAwAAAQAGQBpDAAABAAxAGsMAAAEACgAagwAAAQAGQBsDAAAAwA5AG0MAAADACoA6gwAAAIAGABuDAAAAwATAAAA.Brux:BAABLgAECn8qAAITAAkJ/RNtPwDEAQloDAAABwBXAGkMAAAGADsAawwAAAcAPABqDAAABgBMAGwMAAAFADUAbQwAAAEAJADqDAAABwBKAG4MAAACABIAbwwAAAEAEgATAAkJ/RNtPwDEAQloDAAABwBXAGkMAAAGADsAawwAAAcAPABqDAAABgBMAGwMAAAFADUAbQwAAAEAJADqDAAABwBKAG4MAAACABIAbwwAAAEAEgAAAA==.',
Bu='Bubonic:BAABLgAECn8XAAIUAAgJFgw4ZgB1AQhoDAAAAwAXAGkMAAADACMAawwAAAMAIQBqDAAAAwAgAGwMAAADABoAbQwAAAMAHwDqDAAAAgAkAG4MAAADAB4AFAAICRYMOGYAdQEIaAwAAAMAFwBpDAAAAwAjAGsMAAADACEAagwAAAMAIABsDAAAAwAaAG0MAAADAB8A6gwAAAIAJABuDAAAAwAeAAAA.Burntt:BAAALgAECgcJDgAAAA==.Buttjeans:BAABLgAECn8ZAAITAAkJ6hWPOQDZAQloDAAABAAuAGkMAAAEAE8AawwAAAQAWwBqDAAAAgAlAGwMAAACAFAAbQwAAAIAMQDqDAAABQA5AG4MAAABAAgAbwwAAAEAIwATAAkJ6hWPOQDZAQloDAAABAAuAGkMAAAEAE8AawwAAAQAWwBqDAAAAgAlAGwMAAACAFAAbQwAAAIAMQDqDAAABQA5AG4MAAABAAgAbwwAAAEAIwAAAA==.Buwiz:BAAALgAECgkJCQAAAA==.',
Ca='Calduryn:BAAALgADCgYJBgAAAA==.Calibër:BAAALgAECgQJCwAAAA==.Captchair:BAAALgADCgIJAgAAAA==.Cashis:BAAALgADCgUJBQAAAA==.',
Ce='Celibate:BAAALgADCgYJBQAAAA==.',
Ch='Chainhealman:BAAALgAECgEJAQAAAA==.Chickynuggy:BAABLgAECn8dAAIMAAkJLxLIKgDbAQloDAAABAAxAGkMAAAEAB4AawwAAAQAEgBqDAAAAwA4AGwMAAADADgAbQwAAAEAOwDqDAAABgBFAG4MAAACADAAbwwAAAIAHAAMAAkJLxLIKgDbAQloDAAABAAxAGkMAAAEAB4AawwAAAQAEgBqDAAAAwA4AGwMAAADADgAbQwAAAEAOwDqDAAABgBFAG4MAAACADAAbwwAAAIAHAAAAA==.Chillypickle:BAABLgAECn8YAAIVAAkJchwOaAAGAgloDAAAAwBSAGkMAAADAE8AawwAAAMAWABqDAAAAgBHAGwMAAACAEUAbQwAAAEAJADqDAAABwBgAG4MAAACAEkAbwwAAAEANwAVAAkJchwOaAAGAgloDAAAAwBSAGkMAAADAE8AawwAAAMAWABqDAAAAgBHAGwMAAACAEUAbQwAAAEAJADqDAAABwBgAG4MAAACAEkAbwwAAAEANwAAAA==.Chonkdoggie:BAAALgADCgYJDAAAAA==.Chronicbuds:BAAALgAECgQJBAAAAA==.Chronichit:BAABLgAECn8bAAMWAAcJ6A8OHwCBAQdoDAAABgAgAGkMAAAGADAAawwAAAUALwBqDAAAAgAqAGwMAAACABoA6gwAAAMAFgBuDAAAAwBBABYABwnoDw4fAIEBB2gMAAAFACAAaQwAAAUAMABrDAAABQAvAGoMAAACACoAbAwAAAIAGgDqDAAAAgAWAG4MAAADAEEABQADCfwC8SkAVAADaAwAAAEACgBpDAAAAQAGAOoMAAABAAYAAAA=.',
Cl='Cloudcaller:BAAALgAECgcJEQAAAA==.',
Co='Cobrakai:BAABLgAECn8jAAIXAAgJjRYzBgDJAQhoDAAABgBBAGkMAAAGAE0AawwAAAYAMABqDAAABAAxAGwMAAAEAD0AbQwAAAIAMQDqDAAABQBHAG4MAAACAB8AFwAICY0WMwYAyQEIaAwAAAYAQQBpDAAABgBNAGsMAAAGADAAagwAAAQAMQBsDAAABAA9AG0MAAACADEA6gwAAAUARwBuDAAAAgAfAAAA.Cochuata:BAABLgAECn8ZAAIMAAgJtxxGEgCXAghoDAAABABNAGkMAAAEAFAAawwAAAQAPwBqDAAAAwBNAGwMAAACAFIA6gwAAAQAWgBuDAAAAwBEAG8MAAABAC8ADAAICbccRhIAlwIIaAwAAAQATQBpDAAABABQAGsMAAAEAD8AagwAAAMATQBsDAAAAgBSAOoMAAAEAFoAbgwAAAMARABvDAAAAQAvAAAA.Cowculated:BAAALgAECgMJAwAAAA==.',
Cr='Crabbypatty:BAABLgAECn8eAAMUAAgJLxlPUwClAQhoDAAABwBHAGkMAAAGAFYAawwAAAYALQBqDAAAAgA6AGwMAAABAE8AbQwAAAEAGQDqDAAABgBIAG4MAAABAEgAFAAICQcYT1MApQEIaAwAAAUARwBpDAAABABWAGsMAAAEABgAagwAAAIAOgBsDAAAAQBPAG0MAAABABkA6gwAAAUASABuDAAAAQBIAAMABAlKErYxAKMABGgMAAACAC8AaQwAAAIASABrDAAAAgAtAOoMAAABABUAAAA=.Crane:BAAALgAECgEJAQABLgAFFAUJEAAUAGkbAA==.Cripstaet:BAAALgAECgIJAgAAAA==.Crisp:BAABLgAECn8WAAMVAAYJ1xhpjwC0AQZoDAAABABHAGkMAAAEAEgAawwAAAQAMQBqDAAAAwA1AGwMAAADAEEA6gwAAAQAOwAVAAYJ1xhpjwC0AQZoDAAABABHAGkMAAAEAEgAawwAAAMAMQBqDAAAAwA1AGwMAAADAEEA6gwAAAQAOwAYAAEJZgvpHwAwAAFrDAAAAQAdAAAA.Crow:BAAALgAECgQJBQAAAA==.',
Cu='Curse:BAABLgAECn8XAAITAAgJyxHxSwCeAQhoDAAABAAxAGkMAAAFADsAawwAAAUAPABqDAAAAgA+AGwMAAABABoAbQwAAAEALADqDAAABAA3AG4MAAABABcAEwAICcsR8UsAngEIaAwAAAQAMQBpDAAABQA7AGsMAAAFADwAagwAAAIAPgBsDAAAAQAaAG0MAAABACwA6gwAAAQANwBuDAAAAQAXAAEuAAUUBQkQABQAaRsA.',
Cy='Cyberdramon:BAAALgADCgEJAQAAAA==.',
['Cö']='Cöunter:BAAALgAFFAIJAgAAAA==.',
Da='Daace:BAAALgAECgYJBgAAAA==.Daboomdh:BAAALgAFFAEJAQAAAA==.Daboommg:BAAALgAECgcJBwAAAA==.Dace:BAACLgAFFH8TAAIZAAUJMCA2DQBpAQVoDAAABQBNAGkMAAAFAF0AawwAAAIATABqDAAAAQAIAOoMAAAGAFMAGQAFCTAgNg0AaQEFaAwAAAUATQBpDAAABQBdAGsMAAACAEwAagwAAAEACADqDAAABgBTAC4ABAp/OAADGQAJCZQf7gwAMAIAGQAJCZQf7gwAMAIAGgAECdoM0BMAwwAAAAA=.Daeladus:BAAALgADCgYJBgABLgADCgYJBgANAAAAAA==.Daelandor:BAAALgADCgYJBgAAAA==.Daelthyr:BAABLgAECn8WAAIbAAgJuxjcBAD4AQhoDAAAAwBFAGkMAAADAEwAawwAAAMAKwBqDAAAAwBIAGwMAAADAEMAbQwAAAEAIQDqDAAABQBcAG4MAAABADwAGwAICbsY3AQA+AEIaAwAAAMARQBpDAAAAwBMAGsMAAADACsAagwAAAMASABsDAAAAwBDAG0MAAABACEA6gwAAAUAXABuDAAAAQA8AAAA.Dairydefendr:BAAALgAECgcJDAAAAA==.Damyn:BAABLgAECn8qAAIcAAgJux/gBQBPAghoDAAABwBbAGkMAAAGAFwAawwAAAYAUgBqDAAABQBTAGwMAAAFAGIAbQwAAAMARgDqDAAABwBXAG4MAAADAC4AHAAICbsf4AUATwIIaAwAAAcAWwBpDAAABgBcAGsMAAAGAFIAagwAAAUAUwBsDAAABQBiAG0MAAADAEYA6gwAAAcAVwBuDAAAAwAuAAAA.Daniella:BAAALgAECgcJDAAAAA==.Dart:BAABLgAECn8YAAIPAAgJGAh0IAABAQhoDAAAAwANAGkMAAADABgAawwAAAMAJgBqDAAAAwAjAGwMAAADAA4AbQwAAAMACgDqDAAABQAUAG4MAAABABcADwAICRgIdCAAAQEIaAwAAAMADQBpDAAAAwAYAGsMAAADACYAagwAAAMAIwBsDAAAAwAOAG0MAAADAAoA6gwAAAUAFABuDAAAAQAXAAAA.Daspanktank:BAABLgAECn8YAAIDAAcJRxZSGgBWAQdoDAAABQA8AGkMAAAEAEMAawwAAAQANQBqDAAAAwBHAGwMAAACAC0A6gwAAAUAVQBuDAAAAQAdAAMABwlHFlIaAFYBB2gMAAAFADwAaQwAAAQAQwBrDAAABAA1AGoMAAADAEcAbAwAAAIALQDqDAAABQBVAG4MAAABAB0AAAA=.',
De='Deathsgrace:BAABLgAECn8rAAIVAAgJQCDmJwBdAghoDAAABwBdAGkMAAAHAEkAawwAAAcAUQBqDAAABgBeAGwMAAAFAE8AbQwAAAIAUQDqDAAABgBYAG4MAAADAE8AFQAICUAg5icAXQIIaAwAAAcAXQBpDAAABwBJAGsMAAAHAFEAagwAAAYAXgBsDAAABQBPAG0MAAACAFEA6gwAAAYAWABuDAAAAwBPAAAA.Demark:BAABLgAECn8uAAMdAAcJVx1RGAAFAgdoDAAACABdAGkMAAAKAFQAawwAAAkAQQBqDAAABwBPAGwMAAAEAFkA6gwAAAcASwBvDAAAAQAqAB0ABwktHVEYAAUCB2gMAAAEAF0AaQwAAAYAUQBrDAAABQBBAGoMAAADAEoAbAwAAAMAWQDqDAAABQBLAG8MAAABACoADwAGCfYXBhwAKQEGaAwAAAQAIgBpDAAABABUAGsMAAAEADgAagwAAAQATwBsDAAAAQA5AOoMAAACAEoAAAA=.Demoniccake:BAAALgADCgMJAwAAAA==.Demonicneon:BAAALgAECgcJDwAAAA==.Dergara:BAAALgADCgYJCgAAAA==.Devman:BAABLgAECn8dAAIBAAkJFhhsNgAFAgloDAAABQBAAGkMAAAFAEkAawwAAAQAPQBqDAAAAgAiAGwMAAADAC4AbQwAAAEAEQDqDAAABgBVAG4MAAABAFEAbwwAAAIAPgABAAkJFhhsNgAFAgloDAAABQBAAGkMAAAFAEkAawwAAAQAPQBqDAAAAgAiAGwMAAADAC4AbQwAAAEAEQDqDAAABgBVAG4MAAABAFEAbwwAAAIAPgAAAA==.Dezzolation:BAAALgADCggJCgAAAA==.',
Di='Diekath:BAAALgADCgYJDgAAAA==.Dingus:BAAALgAECgQJBAAAAA==.Dixinmayaz:BAAALgAECgIJBQAAAA==.',
Dk='Dk:BAACLgAFFH8QAAMUAAUJaRu9TwArAQVoDAAABQBUAGkMAAACAEcAawwAAAEAJwBqDAAAAQA1AOoMAAAHAFUAFAAECWkbvU8AKwEEaAwAAAUAVABpDAAAAgBHAGsMAAABACcA6gwAAAcAVQADAAEJAAA+PwAAAAFqDAAAAQA1AC4ABAp/FgADFAAICbUfo0QA0QEAFAAICbUfo0QA0QEAHgACCfIbDhIAcAAAAAA=.',
Do='Dodgeroach:BAAALgAECgYJCQAAAA==.Doody:BAABLgAECn8zAAIMAAkJyxVcHQA0AgloDAAABgA9AGkMAAAGAEgAawwAAAYALgBqDAAABQAiAGwMAAAFAD8AbQwAAAYARQDqDAAABwAxAG4MAAAGAEYAbwwAAAQAIQAMAAkJyxVcHQA0AgloDAAABgA9AGkMAAAGAEgAawwAAAYALgBqDAAABQAiAGwMAAAFAD8AbQwAAAYARQDqDAAABwAxAG4MAAAGAEYAbwwAAAQAIQAAAA==.Dotyew:BAAALgAECgEJAQAAAA==.',
Dr='Dratalis:BAAALgAECgEJAQAAAA==.Dreastotems:BAAALgAECgYJCAAAAA==.Drennifer:BAABLgAECn8bAAIIAAgJUAarOwARAQhoDAAABAAWAGkMAAAEABIAawwAAAQAEgBqDAAABAAWAGwMAAADAAsAbQwAAAMACwDqDAAAAgAPAG4MAAADAA8ACAAICVAGqzsAEQEIaAwAAAQAFgBpDAAABAASAGsMAAAEABIAagwAAAQAFgBsDAAAAwALAG0MAAADAAsA6gwAAAIADwBuDAAAAwAPAAAA.Drgndeeznuts:BAAALgAECgEJAgABLgAECgkJHQABABYYAA==.',
Du='Duskcandin:BAAALgADCgIJAgAAAA==.',
['Då']='Dånny:BAAALgADCgEJAQAAAA==.',
Eb='Ebtyrone:BAABLgAECn8UAAMUAAkJTxwVIQC8AgloDAAAAwBMAGkMAAADAFcAawwAAAMAUgBqDAAAAgBQAGwMAAACADYAbQwAAAIAWwDqDAAAAwBiAG4MAAABABkAbwwAAAEAPQAUAAkJTxwVIQC8AgloDAAAAwBMAGkMAAADAFcAawwAAAMAUgBqDAAAAgBQAGwMAAABADYAbQwAAAIAWwDqDAAAAwBiAG4MAAABABkAbwwAAAEAPQADAAEJRhFFTgArAAFsDAAAAQAsAAAA.',
El='Ellyham:BAAALgADCgMJBQAAAA==.',
Em='Emrys:BAAALgAECgQJBgAAAA==.',
Eq='Equipmunk:BAAALgAFFAEJAQAAAA==.',
Ey='Eyekill:BAAALgADCgQJBAAAAA==.',
Ez='Ezath:BAAALgAECgYJBgAAAA==.',
Fa='Falcorn:BAAALgADCgQJBQAAAA==.',
Fe='Felwolf:BAAALgAECgMJBAAAAA==.',
Fi='Fibderp:BAAALgADCgcJDgAAAA==.Fishtingya:BAAALgAECgEJAQAAAA==.',
Fo='Fooksdk:BAAALgAECgcJCAAAAA==.Fooksdruid:BAAALgAECgUJBQAAAA==.Foxx:BAAALgAECgkJCAAAAA==.',
Fr='Freshdots:BAAALgAECgEJAQABLgAECgIJAgANAAAAAA==.Froolock:BAAALgADCgYJBgAAAA==.Fruvi:BAAALgAECgUJCQAAAA==.',
Fu='Fullometal:BAABLgAECn8zAAMLAAkJIxsYBQB2AgloDAAACABOAGkMAAAIAEcAawwAAAcAVwBqDAAABgBFAGwMAAAGACkAbQwAAAMATwDqDAAACABWAG4MAAAEAC8AbwwAAAEAPgALAAkJIxsYBQB2AgloDAAABwBOAGkMAAAIAEcAawwAAAcAVwBqDAAABgBFAGwMAAAGACkAbQwAAAMATwDqDAAABwBWAG4MAAAEAC8AbwwAAAEAPgAMAAIJSAhZrQBDAAJoDAAAAQAWAOoMAAABABQAAAA=.Furojin:BAABLgAECn8ZAAIJAAkJogXWRADDAAloDAAABQAZAGkMAAAEAAgAawwAAAMAEwBqDAAAAwAOAGwMAAACABAAbQwAAAIAAwDqDAAABAAQAG4MAAABABAAbwwAAAEACAAJAAkJogXWRADDAAloDAAABQAZAGkMAAAEAAgAawwAAAMAEwBqDAAAAwAOAGwMAAACABAAbQwAAAIAAwDqDAAABAAQAG4MAAABABAAbwwAAAEACAAAAA==.',
Ga='Galstad:BAABLgAECn8oAAQWAAkJ9iUuCgBhAgloDAAABwBeAGkMAAAGAGEAawwAAAYAYgBqDAAABQBjAGwMAAAEAF8AbQwAAAEAYgDqDAAABwBfAG4MAAADAGMAbwwAAAEAYgAFAAYJkSWDFQCGAgZoDAAABQBeAGkMAAAFAGEAawwAAAUAYgBqDAAAAwBeAGwMAAAEAF8A6gwAAAUAXwAWAAgJSBwuCgBhAghoDAAAAQAVAGkMAAABAAUAawwAAAEAYABqDAAAAQBjAG0MAAABAGIA6gwAAAIAVwBuDAAAAwBjAG8MAAABAGIABAACCV4Xc9QAMQACaAwAAAEAOwBqDAAAAQBaAAAA.Gazznoogg:BAAALgAECgkJDQAAAA==.',
Ge='Geff:BAABLgAECn8UAAQRAAgJsxdSRwCMAQhoDAAAAwBTAGkMAAACAD0AawwAAAIATQBqDAAAAgA3AGwMAAACAEMAbQwAAAEAFgDqDAAABwBgAG4MAAABAA8AEQAICZEUUkcAjAEIaAwAAAIAUwBpDAAAAgA9AGsMAAACAE0AagwAAAIANwBsDAAAAgBDAG0MAAABABYA6gwAAAIAKABuDAAAAQAPAB8AAQmtJekfAGkAAeoMAAAFAGAAIAABCWQCGXwAJQABaAwAAAEABgAAAA==.',
Gh='Ghostpickle:BAAALgAECgIJAwABLgAECgYJDgANAAAAAA==.',
Gi='Gigariven:BAAALgAECgYJEgAAAA==.Girthhquake:BAABLgAECn8XAAMcAAcJkAp/FwADAQdoDAAABAAtAGkMAAAEACkAawwAAAQAHwBqDAAAAwAcAGwMAAACAA8A6gwAAAUAFABuDAAAAQAIABwABwmQCn8XAAMBB2gMAAAEAC0AaQwAAAQAKQBrDAAABAAfAGoMAAADABwAbAwAAAIADwDqDAAABAAUAG4MAAABAAgABwABCYEBR5sAGwAB6gwAAAEAAwAAAA==.Girumm:BAAALgAECgcJBwAAAA==.Gisokaashi:BAAALgAECgYJDQAAAA==.',
Go='Gooserage:BAAALgADCgQJBAAAAA==.Gothick:BAAALgAECgUJCgAAAA==.',
Gr='Grrshhnak:BAAALgAECgEJAQAAAA==.Grumz:BAABLgAECn8WAAMhAAcJHxThPwCBAQdoDAAABAA/AGkMAAAEAGEAawwAAAQAQQBqDAAAAgAhAGwMAAACACUAbQwAAAEABQDqDAAABQA5ACEABwkfFOE/AIEBB2gMAAADAD8AaQwAAAMAYQBrDAAAAwBBAGoMAAACACEAbAwAAAIAJQBtDAAAAQAFAOoMAAAEADkABwAECVQM0WsAlAAEaAwAAAEANgBpDAAAAQAPAGsMAAABABwA6gwAAAEAHAAAAA==.',
Gu='Guacamolle:BAAALgADCgIJAgAAAA==.Gurrand:BAAALgAECgYJBwABLgAFFAQJBwAVAFoSAA==.',
Ha='Habib:BAAALgAECgYJCgAAAA==.Hamicks:BAAALgAECgIJAgAAAA==.Happyflappy:BAEBLgAECn8nAAMIAAkJNhrsEQAwAgloDAAABgBUAGkMAAAGAEwAawwAAAYAUQBqDAAABQA2AGwMAAAEAFcAbQwAAAIAQQDqDAAABQBAAG4MAAAEACkAbwwAAAEAIQAIAAkJexnsEQAwAgloDAAABgBUAGkMAAAGAEwAawwAAAYAUQBqDAAABAA2AGwMAAADAEgAbQwAAAIAQQDqDAAABABAAG4MAAAEACkAbwwAAAEAIQAbAAMJSxp7KADcAANqDAAAAQAzAGwMAAABAFcA6gwAAAEALgAAAA==.Happyshocks:BAEALgAECgEJAQABLgAECgkJJwAIADYaAA==.Harambe:BAAALgADCgUJBQABLgAECgkJMwAMAMsVAA==.',
He='Healforfun:BAACLgAFFH8JAAIMAAMJ2BGlLwDOAANoDAAABAA8AGkMAAADABUA6gwAAAIANgAMAAMJ2BGlLwDOAANoDAAABAA8AGkMAAADABUA6gwAAAIANgAuAAQKfzgAAgwACQl0HWASAJYCAAwACQl0HWASAJYCAAAA.Heilung:BAABLgAECn86AAIiAAkJ1hN/CwD5AQloDAAACABEAGkMAAAHACcAawwAAAcAKgBqDAAACAA9AGwMAAAIAFAAbQwAAAYAJwDqDAAACAA4AG4MAAAFADoAbwwAAAEACgAiAAkJ1hN/CwD5AQloDAAACABEAGkMAAAHACcAawwAAAcAKgBqDAAACAA9AGwMAAAIAFAAbQwAAAYAJwDqDAAACAA4AG4MAAAFADoAbwwAAAEACgAAAA==.Hellstar:BAAALgAECgEJAQAAAA==.',
Hi='Hirradee:BAACLgAFFH8PAAIRAAUJPgu9QAD3AAVoDAAABAAjAGkMAAADABkAawwAAAIACABqDAAAAQATAOoMAAAFAC0AEQAFCT4LvUAA9wAFaAwAAAQAIwBpDAAAAwAZAGsMAAACAAgAagwAAAEAEwDqDAAABQAtAC4ABAp/JQADEQAJCRobXSwATQIAEQAJCRobXSwATQIAHwACCSgMqiQATQAAAAA=.',
Ho='Holyroach:BAAALgAECgQJBQAAAA==.',
Hu='Hubelez:BAAALgAECgYJEgAAAA==.Hugebubbles:BAAALgADCgcJCQAAAA==.',
Hy='Hyacine:BAAALgAECgIJAgAAAA==.',
Ic='Icecweam:BAAALgAECgIJAgAAAA==.Ichigo:BAAALgAECgQJBAAAAA==.',
Il='Illuminus:BAAALgAECgQJCAAAAA==.Ilovenikki:BAAALgADCgcJDQAAAA==.',
Im='Image:BAAALgADCgcJBwAAAA==.Impending:BAAALgADCgQJBAAAAA==.Imsomanly:BAAALgAECgQJBAAAAA==.',
In='Incarnate:BAAALgAECgUJBQABLgAFFAUJDwARAD4LAA==.Inktown:BAAALgAECgIJAgAAAA==.',
Ir='Iruden:BAABLgAECn8WAAIUAAcJWBYEcgCjAQdoDAAABABHAGkMAAADAEEAawwAAAQANgBqDAAABABQAGwMAAACAEUA6gwAAAQANABuDAAAAQAeABQABwlYFgRyAKMBB2gMAAAEAEcAaQwAAAMAQQBrDAAABAA2AGoMAAAEAFAAbAwAAAIARQDqDAAABAA0AG4MAAABAB4AAAA=.',
Ja='Jakiichan:BAABLgAECn8XAAMjAAcJ3hOEJgBQAQdoDAAABQA8AGkMAAAFAEAAawwAAAQAOABqDAAAAgAxAGwMAAACAB4A6gwAAAQARQBuDAAAAQAXACMABwl8EoQmAFABB2gMAAAEADwAaQwAAAMAQABrDAAAAgA4AGoMAAABADEAbAwAAAEACQDqDAAAAwBFAG4MAAABABcAEgAGCYQLX0AA2AAGaAwAAAEAEwBpDAAAAgAiAGsMAAACAB8AagwAAAEAGwBsDAAAAQAeAOoMAAABAB8AAAA=.',
Ji='Jiangshi:BAAALgAECgIJAgAAAA==.Jipper:BAAALgAECgUJBgAAAA==.',
Jj='Jjpearl:BAAALgAFFAMJBAAAAA==.',
Jr='Jrwriter:BAAALgAECgYJEAABLgAFFAUJEAAUAGkbAA==.',
Jy='Jym:BAABLgAECn8XAAIRAAgJXxf+QwCXAQhoDAAABAA1AGkMAAAEADcAawwAAAQASgBqDAAAAwAzAGwMAAACAEIAbQwAAAIAOgDqDAAAAgAuAG4MAAACAEAAEQAICV8X/kMAlwEIaAwAAAQANQBpDAAABAA3AGsMAAAEAEoAagwAAAMAMwBsDAAAAgBCAG0MAAACADoA6gwAAAIALgBuDAAAAgBAAAAA.',
Ka='Kaijin:BAABLgAECn8qAAIjAAkJhBqlEAAaAgloDAAABgBPAGkMAAAGAE0AawwAAAYATwBqDAAABQBKAGwMAAAFAEIAbQwAAAMALgDqDAAABgBDAG4MAAAEAE0AbwwAAAEALwAjAAkJhBqlEAAaAgloDAAABgBPAGkMAAAGAE0AawwAAAYATwBqDAAABQBKAGwMAAAFAEIAbQwAAAMALgDqDAAABgBDAG4MAAAEAE0AbwwAAAEALwAAAA==.Kalypsö:BAAALgADCgEJAQAAAA==.Kandrianna:BAAALgAECgQJBAAAAA==.Kateriny:BAAALgADCgEJAQAAAA==.',
Ke='Keb:BAAALgADCgEJAQAAAA==.Kelaya:BAAALgAECgMJBwAAAA==.Kenpachi:BAAALgADCgcJCQAAAA==.Kernuckle:BAAALgAECgQJBwAAAA==.',
Kh='Khristine:BAAALgADCgEJAQABLgAFFAIJAwANAAAAAA==.',
Ki='Kilrav:BAAALgAECgEJAQAAAA==.Kimberlee:BAABLgAECn8YAAIEAAYJvAWdpQC2AAZoDAAABQAfAGkMAAAGAA0AawwAAAQACQBqDAAAAgAEAG0MAAABAAAA6gwAAAYAEgAEAAYJvAWdpQC2AAZoDAAABQAfAGkMAAAGAA0AawwAAAQACQBqDAAAAgAEAG0MAAABAAAA6gwAAAYAEgAAAA==.Kiryanna:BAABLgAECn8UAAIRAAgJABPZQwCYAQhoDAAABABJAGkMAAADAEIAawwAAAMAJABqDAAAAgAgAGwMAAACACMAbQwAAAEAKQDqDAAABAAyAG4MAAABACQAEQAICQAT2UMAmAEIaAwAAAQASQBpDAAAAwBCAGsMAAADACQAagwAAAIAIABsDAAAAgAjAG0MAAABACkA6gwAAAQAMgBuDAAAAQAkAAAA.Kitiara:BAAALgADCgkJCQAAAA==.',
Kl='Klayah:BAAALgAECgUJBgAAAA==.Klayana:BAAALgAECgYJDAAAAA==.',
Kr='Krombopulös:BAABLgAECn8bAAIEAAgJ2httIQAyAghoDAAABABGAGkMAAAEAFAAawwAAAQASgBqDAAABABMAGwMAAADAEYAbQwAAAIAVgDqDAAABAAuAG4MAAACAEYABAAICdobbSEAMgIIaAwAAAQARgBpDAAABABQAGsMAAAEAEoAagwAAAQATABsDAAAAwBGAG0MAAACAFYA6gwAAAQALgBuDAAAAgBGAAAA.',
La='Lawloo:BAACLgAFFH8JAAIkAAQJtxXhAwBPAQRoDAAAAwBXAGkMAAADADsAawwAAAEACgDqDAAAAgBBACQABAm3FeEDAE8BBGgMAAADAFcAaQwAAAMAOwBrDAAAAQAKAOoMAAACAEEALgAECn8dAAIkAAgJ9CE0CADIAgAkAAgJ9CE0CADIAgAAAA==.Lawltwo:BAAALgAECgMJAwAAAA==.',
Le='Legothas:BAABLgAECn8hAAMFAAkJjxqlCQCuAQloDAAABQA8AGkMAAAFAFEAawwAAAUAOgBqDAAAAwBHAGwMAAAEAEAAbQwAAAMAWwDqDAAABABLAG4MAAACAEEAbwwAAAIALgAFAAgJxBulCQCuAQhoDAAABQA8AGkMAAAFAFEAawwAAAUAOgBqDAAAAwBHAGwMAAAEAEAAbQwAAAMAWwDqDAAABABLAG4MAAACAEEABAABCR0SGuAASAABbwwAAAIALgAAAA==.',
Li='Lifestyle:BAAALgAECgEJAQAAAA==.Lintlickerr:BAAALgAFFAEJAQAAAA==.Littledirk:BAACLgAFFH8HAAIZAAMJVgQQIQDNAANoDAAAAwAGAGkMAAACABIA6gwAAAIACAAZAAMJVgQQIQDNAANoDAAAAwAGAGkMAAACABIA6gwAAAIACAAuAAQKfyYAAhkACQlDDpwVAMgBABkACQlDDpwVAMgBAAAA.',
Ll='Llillies:BAAALgAECgUJEAAAAA==.',
Lo='Longstalker:BAAALgADCgcJCQAAAA==.',
Lu='Lugnuts:BAAALgAECgQJBwAAAA==.Luxiss:BAAALgADCgIJAgAAAA==.',
Ma='Maak:BAABLgAECn8fAAMdAAkJwSAaCgCeAgloDAAABgBZAGkMAAAFAFQAawwAAAQATQBqDAAAAwBEAGwMAAACAEwAbQwAAAIAUgDqDAAAAwBNAG4MAAAFAGEAbwwAAAEAVAAdAAkJwSAaCgCeAgloDAAABgBZAGkMAAAEAFQAawwAAAMATQBqDAAAAgBEAGwMAAACAEwAbQwAAAIAUgDqDAAAAgBNAG4MAAAFAGEAbwwAAAEAVAAlAAQJcwhPIwDSAARpDAAAAQAfAGsMAAABABIAagwAAAEAKADqDAAAAQAOAAAA.Madcuzbad:BAAALgAECgUJBQAAAA==.Magebuff:BAACLgAFFH8FAAIVAAMJmRQGYAD0AANoDAAAAwBLAGkMAAABAEIA6gwAAAEAEAAVAAMJmRQGYAD0AANoDAAAAwBLAGkMAAABAEIA6gwAAAEAEAAuAAQKfyUAAhUACQkwILoSAM4CABUACQkwILoSAM4CAAAA.Malzgatoth:BAAALgADCgEJAQAAAA==.Maplesyrup:BAAALgADCgQJBwAAAA==.',
Mc='Mcheals:BAABLgAECn8mAAIkAAkJLxMBFAAOAgloDAAABwBMAGkMAAAGADsAawwAAAYAQABqDAAABABNAGwMAAAFADQAbQwAAAIAEQDqDAAABgBFAG4MAAABAA0AbwwAAAEACQAkAAkJLxMBFAAOAgloDAAABwBMAGkMAAAGADsAawwAAAYAQABqDAAABABNAGwMAAAFADQAbQwAAAIAEQDqDAAABgBFAG4MAAABAA0AbwwAAAEACQAAAA==.',
Me='Meanìe:BAAALgADCgEJAQAAAA==.Medellia:BAAALgAECgkJAwAAAA==.Media:BAAALgADCgkJGQAAAA==.Meihunglo:BAAALgAECgEJAQABLgAFFAUJDwARAD4LAA==.Mezcal:BAAALgAECgEJAQAAAA==.',
Mi='Miasma:BAAALgADCgEJAQABLgAECggJIQAcAKMVAA==.Midgetitis:BAAALgADCgUJBgAAAA==.',
Mo='Monsunami:BAAALgAFFAEJAgAAAA==.Moonmonk:BAAALgADCgMJAwAAAA==.Moonwings:BAAALgADCgMJAwAAAA==.Mooseleigh:BAAALgAECgQJBAAAAA==.Morkra:BAABLgAECn8VAAIdAAYJUBmXQQCeAQZoDAAABQBCAGkMAAADAEMAawwAAAMANgBqDAAAAQAfAGwMAAABADUA6gwAAAgAUAAdAAYJUBmXQQCeAQZoDAAABQBCAGkMAAADAEMAawwAAAMANgBqDAAAAQAfAGwMAAABADUA6gwAAAgAUAAAAA==.Morogh:BAAALgADCgcJCwAAAA==.Morte:BAAALgAECgYJDgAAAA==.Moònflower:BAAALgAECgYJDwAAAA==.',
Mu='Mundungus:BAAALgADCgYJBgAAAA==.Mushroom:BAAALgAECggJEwABLgAECgkJKgAjAKQWAA==.',
['Më']='Mëlfina:BAAALgADCgEJAQAAAA==.',
['Mø']='Møøn:BAAALgAECgQJBQAAAA==.Møøse:BAABLgAECn85AAIhAAgJaRwUGQBSAghoDAAACABKAGkMAAAIAC8AawwAAAgAUQBqDAAABwBQAGwMAAAIAFoAbQwAAAUASADqDAAACABPAG4MAAAFADcAIQAICWkcFBkAUgIIaAwAAAgASgBpDAAACAAvAGsMAAAIAFEAagwAAAcAUABsDAAACABaAG0MAAAFAEgA6gwAAAgATwBuDAAABQA3AAAA.',
Na='Narcyon:BAABLgAECn8pAAMkAAkJOhpsDQBkAgloDAAACABjAGkMAAAIAFUAawwAAAYAWQBqDAAABABEAGwMAAAEAEoAbQwAAAEAJQDqDAAACABGAG4MAAABACkAbwwAAAEAJAAkAAgJdxtsDQBkAghoDAAACABjAGkMAAAIAFUAawwAAAYAWQBqDAAABABEAGwMAAAEAEoAbQwAAAEAJQDqDAAABwBGAG8MAAABACQAJgACCe8WJlQAhAAC6gwAAAEARgBuDAAAAQAuAAAA.',
Ni='Nibiru:BAAALgAECgYJBwAAAA==.',
No='Nokkoh:BAAALgADCgcJCQAAAA==.Notmaxxie:BAAALgAECggJCwAAAA==.',
Nu='Nutellala:BAAALgAECgQJBQAAAA==.',
['Nì']='Nìck:BAAALgAECgIJAgAAAA==.',
Ob='Obz:BAAALgAECgEJAwAAAA==.',
Oe='Oexx:BAABLgAECn8WAAInAAYJFR3oDwDRAQZoDAAABABZAGkMAAAEAEYAawwAAAQARQBqDAAAAwBFAGwMAAADAEgA6gwAAAQARQAnAAYJFR3oDwDRAQZoDAAABABZAGkMAAAEAEYAawwAAAQARQBqDAAAAwBFAGwMAAADAEgA6gwAAAQARQAAAA==.',
Oo='Oonara:BAAALgAECgIJBAAAAA==.',
Oz='Ozmodius:BAAALgADCgMJAwAAAA==.',
Pa='Padhi:BAABLgAECn8dAAIOAAkJ4RlGEQBcAgloDAAABQBdAGkMAAADAD8AawwAAAMAPgBqDAAABABQAGwMAAADADsAbQwAAAEASADqDAAABgBNAG4MAAADADgAbwwAAAEAHgAOAAkJ4RlGEQBcAgloDAAABQBdAGkMAAADAD8AawwAAAMAPgBqDAAABABQAGwMAAADADsAbQwAAAEASADqDAAABgBNAG4MAAADADgAbwwAAAEAHgAAAA==.Palaadin:BAAALgAECgYJDwAAAA==.Pandicated:BAEBLgAECn8bAAMSAAkJtxElFwDNAQloDAAABABJAGkMAAADAEEAawwAAAMAQgBqDAAABAA+AGwMAAACACsAbQwAAAEACwDqDAAABQBAAG4MAAADABwAbwwAAAIACAASAAkJtxElFwDNAQloDAAABABJAGkMAAADAEEAawwAAAMAQgBqDAAAAwA+AGwMAAABACsAbQwAAAEACwDqDAAAAwBAAG4MAAADABwAbwwAAAIACAAjAAMJtRI2WQB4AANqDAAAAQAEAGwMAAABACEA6gwAAAIAPgAAAA==.',
Pe='Pennlad:BAAALgAECgEJAQAAAA==.Peppermint:BAECLgAFFH8WAAIMAAUJ9hNWFwBhAQVoDAAABwBJAGkMAAAGAEEAawwAAAMAIgBqDAAAAQALAOoMAAAFAEUADAAFCfYTVhcAYQEFaAwAAAcASQBpDAAABgBBAGsMAAADACIAagwAAAEACwDqDAAABQBFAC4ABAp/JQACDAAICU4i9gwA1QIADAAICU4i9gwA1QIAAAA=.',
Ph='Pheelix:BAAALgAECgEJAQAAAA==.Phlufy:BAABLgAECn8XAAIMAAcJKxfHMQDjAQdoDAAABQBFAGkMAAAFADQAawwAAAQASgBqDAAAAQA8AGwMAAABADkAbQwAAAEAIADqDAAABgBEAAwABwkrF8cxAOMBB2gMAAAFAEUAaQwAAAUANABrDAAABABKAGoMAAABADwAbAwAAAEAOQBtDAAAAQAgAOoMAAAGAEQAAAA=.',
Pi='Piemur:BAAALgADCgcJBwAAAA==.',
Po='Poenah:BAAALgADCggJEAAAAA==.Pollix:BAAALgAECgYJDQAAAA==.Ponsi:BAABLgAECn8mAAQWAAgJixxuEAAOAghoDAAABgA5AGkMAAAGAEwAawwAAAYAUwBqDAAABQBGAGwMAAAGAFwAbQwAAAIAVgDqDAAABgBEAG4MAAABAC4AFgAHCRAYbhAADgIHaAwAAAIAOQBpDAAAAgA4AGsMAAACAD4AbAwAAAIAMwBtDAAAAgBWAOoMAAACAEQAbgwAAAEALgAEAAYJDx0AQQCsAQZoDAAAAwA2AGkMAAADAEwAawwAAAMAUwBqDAAABQBGAGwMAAADAFwA6gwAAAMAQQAFAAUJPQZFXQDNAAVoDAAAAQAXAGkMAAABAA8AawwAAAEAFwBsDAAAAQAJAOoMAAABAAcAAAA=.',
Pr='Prettypatty:BAAALgAECgIJAgAAAA==.Preying:BAAALgADCgEJAQABLgAECgMJAwANAAAAAA==.Prìdè:BAAALgADCgcJBwAAAA==.Prídè:BAAALgAECggJEAAAAA==.',
Qu='Quj:BAAALgAECgIJAgAAAA==.',
Ra='Raejiisa:BAAALgADCgcJBwAAAA==.Rakoth:BAAALgAECgMJCgAAAA==.Rantharot:BAAALgADCgEJAQAAAA==.Rathmá:BAAALgAECgcJAQAAAA==.Ravenwolf:BAABLgAECn8WAAIMAAYJ6A3OWQAHAQZoDAAABAAYAGkMAAAEACwAawwAAAUALgBqDAAAAwAhAGwMAAADABsA6gwAAAMAJgAMAAYJ6A3OWQAHAQZoDAAABAAYAGkMAAAEACwAawwAAAUALgBqDAAAAwAhAGwMAAADABsA6gwAAAMAJgAAAA==.Raveñna:BAAALgAECgUJCQAAAA==.Rawrina:BAABLgAECn8UAAIJAAkJSQ1VLQCZAQloDAAAAwAeAGkMAAADADEAawwAAAMASABqDAAAAgAoAGwMAAACACUAbQwAAAIAGwDqDAAAAwAYAG4MAAABABAAbwwAAAEADQAJAAkJSQ1VLQCZAQloDAAAAwAeAGkMAAADADEAawwAAAMASABqDAAAAgAoAGwMAAACACUAbQwAAAIAGwDqDAAAAwAYAG4MAAABABAAbwwAAAEADQAAAA==.',
Re='Redlitesaber:BAAALgAECgEJAQAAAA==.Rejoice:BAAALgADCgIJAgAAAA==.',
Ri='Riptide:BAABLgAECn8wAAIVAAkJWRjVLQBCAgloDAAABwBVAGkMAAAHAEgAawwAAAcAVABqDAAABQA1AGwMAAAFAEoAbQwAAAQAIgDqDAAABwBDAG4MAAAEAC0AbwwAAAIAIQAVAAkJWRjVLQBCAgloDAAABwBVAGkMAAAHAEgAawwAAAcAVABqDAAABQA1AGwMAAAFAEoAbQwAAAQAIgDqDAAABwBDAG4MAAAEAC0AbwwAAAIAIQABLgAECgMJAwANAAAAAA==.Risto:BAABLgAECn8rAAITAAgJKCTQDwC0AghoDAAABwBiAGkMAAAHAF8AawwAAAcAXABqDAAABgBjAGwMAAAFAFwAbQwAAAIAWgDqDAAABgBhAG4MAAADAFEAEwAICSgk0A8AtAIIaAwAAAcAYgBpDAAABwBfAGsMAAAHAFwAagwAAAYAYwBsDAAABQBcAG0MAAACAFoA6gwAAAYAYQBuDAAAAwBRAAAA.',
Ro='Rodandwen:BAAALgADCgMJAwAAAA==.Ronzertnin:BAABLgAECn8rAAInAAgJRxYVBwC1AQhoDAAABwBNAGkMAAAHADIAawwAAAcAOQBqDAAABgAuAGwMAAAFADMAbQwAAAIAIwDqDAAABgBKAG4MAAADADMAJwAICUcWFQcAtQEIaAwAAAcATQBpDAAABwAyAGsMAAAHADkAagwAAAYALgBsDAAABQAzAG0MAAACACMA6gwAAAYASgBuDAAAAwAzAAAA.Roody:BAAALgAECggJDQABLgAECgkJMwAMAMsVAA==.Rouein:BAAALgAECgEJAwAAAA==.',
Ry='Ryaala:BAAALgADCgYJCwAAAA==.Ryöshun:BAAALgADCgIJAgAAAA==.',
Sa='Sabreus:BAAALgADCgEJAQAAAA==.Sagong:BAAALgADCgEJAQAAAA==.Samel:BAAALgAECgEJAQAAAA==.Samelly:BAAALgADCgYJBgAAAA==.Samellyfox:BAAALgADCgYJBgAAAA==.San:BAAALgAFFAIJAgAAAA==.Sanctify:BAAALgADCgYJBgAAAA==.Sandrea:BAAALgAECgIJAgAAAA==.Sandroin:BAAALgAECgYJDgAAAA==.Sarah:BAAALgADCgIJAgABLgAFFAQJCgAGAJAVAA==.',
Sc='Scarf:BAAALgAECgEJAgAAAA==.Schnee:BAAALgADCgEJAQAAAA==.Schrimp:BAAALgAECgEJAQABLgAECgYJDgANAAAAAA==.',
Se='Serrasin:BAAALgADCgIJAgAAAA==.',
Sh='Shinerbock:BAABLgAECn8mAAIEAAkJ+RLWMADrAQloDAAABQAmAGkMAAAEADIAawwAAAQAKABqDAAAAwAcAGwMAAAGADoAbQwAAAQAQwDqDAAABwA1AG4MAAADACQAbwwAAAIAKwAEAAkJ+RLWMADrAQloDAAABQAmAGkMAAAEADIAawwAAAQAKABqDAAAAwAcAGwMAAAGADoAbQwAAAQAQwDqDAAABwA1AG4MAAADACQAbwwAAAIAKwAAAA==.Shock:BAABLgAECn8aAAIHAAgJBSLICwB/AghoDAAABABLAGkMAAAFAFkAawwAAAMAXQBqDAAAAwBaAGwMAAADAFwAbQwAAAEATgDqDAAABgBeAG4MAAABAFcABwAICQUiyAsAfwIIaAwAAAQASwBpDAAABQBZAGsMAAADAF0AagwAAAMAWgBsDAAAAwBcAG0MAAABAE4A6gwAAAYAXgBuDAAAAQBXAAAA.',
Si='Sighty:BAAALgADCgcJDQAAAA==.Sixxam:BAAALgAECgEJAQAAAA==.',
Sk='Skipuscales:BAAALgAFFAIJAwAAAA==.',
Sn='Snowgo:BAAALgAECgEJAQABLgAECgIJAgANAAAAAA==.',
So='Solbind:BAAALgADCgYJBgAAAA==.Sonk:BAAALgAFFAIJAgAAAA==.Soul:BAABLgAECn86AAIJAAkJcyBsBgDNAgloDAAABwBbAGkMAAAIAF0AawwAAAgAWABqDAAABwBJAGwMAAAHAE8AbQwAAAYAWADqDAAABwBfAG4MAAAFAEEAbwwAAAMAPgAJAAkJcyBsBgDNAgloDAAABwBbAGkMAAAIAF0AawwAAAgAWABqDAAABwBJAGwMAAAHAE8AbQwAAAYAWADqDAAABwBfAG4MAAAFAEEAbwwAAAMAPgAAAA==.Sovietpanda:BAAALgAECgkJEQAAAA==.',
Sp='Spanksalot:BAAALgAECgEJAQAAAA==.Spanky:BAAALgAECggJDwAAAA==.Spankyohs:BAAALgADCgcJBwAAAA==.Spawnite:BAAALgAECgEJAgAAAA==.Spiritgun:BAAALgAECgIJBAABLgAFFAUJEAAUAGkbAA==.Spumungus:BAAALgADCgMJAwAAAA==.',
St='Staahcked:BAAALgAECgYJCQAAAA==.',
Su='Summon:BAABLgAECn8gAAITAAkJvBj9MgBAAgloDAAABQBUAGkMAAAEAEkAawwAAAQAQABqDAAAAwAtAGwMAAADAE4AbQwAAAIAKQDqDAAABgBQAG4MAAAEAC8AbwwAAAEAJQATAAkJvBj9MgBAAgloDAAABQBUAGkMAAAEAEkAawwAAAQAQABqDAAAAwAtAGwMAAADAE4AbQwAAAIAKQDqDAAABgBQAG4MAAAEAC8AbwwAAAEAJQAAAA==.Sumtingwong:BAAALgAECgEJAQAAAA==.Sutures:BAAALgADCgEJAwAAAA==.',
Sw='Swig:BAAALgADCgIJAgAAAA==.',
['Sö']='Sönja:BAABLgAECn8hAAICAAkJ7Q78HAAjAQloDAAABQAfAGkMAAAEAD8AawwAAAQANABqDAAABAAYAGwMAAADAB4AbQwAAAEABADqDAAABgA2AG4MAAAEADQAbwwAAAIAEgACAAkJ7Q78HAAjAQloDAAABQAfAGkMAAAEAD8AawwAAAQANABqDAAABAAYAGwMAAADAB4AbQwAAAEABADqDAAABgA2AG4MAAAEADQAbwwAAAIAEgAAAA==.',
Ta='Taek:BAEBLgAFFH8QAAIUAAQJ0hntNQBVAQRoDAAABABTAGkMAAAEAD0AawwAAAQANwDqDAAABAA/ABQABAnSGe01AFUBBGgMAAAEAFMAaQwAAAQAPQBrDAAABAA3AOoMAAAEAD8AAAA=.Talinang:BAAALgADCgQJAwAAAA==.Taterbiscuts:BAAALgADCgMJAwAAAA==.Tazmo:BAABLgAECn8bAAIVAAgJPRfLQAD8AQhoDAAABABJAGkMAAAEAD4AawwAAAQALQBqDAAAAwAhAGwMAAADAFEAbQwAAAIANADqDAAABAAzAG4MAAADAC8AFQAICT0Xy0AA/AEIaAwAAAQASQBpDAAABAA+AGsMAAAEAC0AagwAAAMAIQBsDAAAAwBRAG0MAAACADQA6gwAAAQAMwBuDAAAAwAvAAAA.',
Te='Tehblink:BAAALgAECgYJCQAAAA==.Terah:BAAALgADCgEJAwAAAA==.Terofyin:BAAALgAECgEJAQAAAA==.Terralithia:BAAALgADCgEJAQAAAA==.',
Th='Thamúz:BAAALgAECgMJBgAAAA==.Thathnda:BAAALgADCgEJAQAAAA==.Thorgan:BAAALgAECgEJAgAAAA==.Thèpaladin:BAAALgAECgYJBgAAAA==.',
Ti='Tiika:BAAALgADCgEJAgAAAA==.',
To='Toomez:BAAALgADCgEJAQAAAA==.Tormxnted:BAAALgADCgcJDAAAAA==.',
Tr='Tranquiill:BAABLgAECn8UAAMMAAYJohw0VQAWAQZoDAAABgBhAGkMAAAFAGIAawwAAAQATQBqDAAAAwBHAGwMAAABADsA6gwAAAEAJAAMAAQJ2Bc0VQAWAQRrDAAAAgBNAGoMAAADAEcAbAwAAAEAOwDqDAAAAQAkAAkAAwkZDodUAIgAA2gMAAAGADMAaQwAAAUAGwBrDAAAAgAcAAAA.Trea:BAAALgAECgIJAgAAAA==.Tripsalot:BAAALgADCgcJDQAAAA==.Tro:BAAALgADCgEJAQAAAA==.',
Tu='Tupkiss:BAABLgAECn8rAAImAAkJQCBCBwC9AgloDAAABwBdAGkMAAAHAFUAawwAAAYAWQBqDAAABQBUAGwMAAAEAFgAbQwAAAEAOgDqDAAACQBYAG4MAAADAFgAbwwAAAEARQAmAAkJQCBCBwC9AgloDAAABwBdAGkMAAAHAFUAawwAAAYAWQBqDAAABQBUAGwMAAAEAFgAbQwAAAEAOgDqDAAACQBYAG4MAAADAFgAbwwAAAEARQAAAA==.',
Tw='Twilight:BAAALgADCgUJBQAAAA==.',
Ty='Tygrand:BAAALgADCgYJEAAAAA==.Tylernol:BAAALgAECgcJDQAAAA==.',
Un='Unknwndemon:BAAALgAECggJCwAAAA==.',
Wa='Wafflepop:BAABLgAECn8kAAMbAAgJHxz2BgCAAghoDAAABQBSAGkMAAAGAE4AawwAAAYARQBqDAAABQBaAGwMAAAFAFgAbQwAAAMAOwDqDAAABABRAG4MAAACAC0AGwAICRMc9gYAgAIIaAwAAAMAUgBpDAAABABOAGsMAAADAEUAagwAAAIAWgBsDAAAAwBYAG0MAAACADoA6gwAAAIAUQBuDAAAAgAtAAgABwnaFhIwAEUBB2gMAAACAEAAaQwAAAIANQBrDAAAAwBBAGoMAAADADoAbAwAAAIANgBtDAAAAQA7AOoMAAACADUAAAA=.Warpfiend:BAABLgAECn8nAAIHAAgJayAHDgBiAghoDAAACABRAGkMAAAIAFgAawwAAAYAUQBqDAAABABRAGwMAAADAFIAbQwAAAEAOwDqDAAABgBdAG4MAAADAF4ABwAICWsgBw4AYgIIaAwAAAgAUQBpDAAACABYAGsMAAAGAFEAagwAAAQAUQBsDAAAAwBSAG0MAAABADsA6gwAAAYAXQBuDAAAAwBeAAAA.',
We='Weid:BAAALgAECggJDQAAAA==.',
Wh='Whammy:BAABLgAECn8UAAIHAAUJoQkuYACOAAVoDAAABQAUAGkMAAAFAB4AawwAAAUAEABqDAAAAQAMAOoMAAAEAB4ABwAFCaEJLmAAjgAFaAwAAAUAFABpDAAABQAeAGsMAAAFABAAagwAAAEADADqDAAABAAeAAAA.Wheresmypet:BAAALgADCgYJBgAAAA==.Whipkream:BAAALgAECgQJBAAAAA==.',
Wi='Wine:BAAALgADCgkJCQAAAA==.',
Wo='Woodymcwood:BAAALgAECgQJBAAAAA==.',
Wu='Wurmz:BAAALgADCgMJAwAAAA==.',
Xe='Xenovia:BAAALgADCgkJEAAAAA==.',
Za='Zandragon:BAAALgADCgYJBwAAAA==.',
Ze='Zeldris:BAAALgADCgYJBgAAAA==.Zenbo:BAAALgAECgEJAQAAAA==.Zensu:BAAALgAECgMJAwAAAA==.',
Zo='Zoêy:BAAALgAECgQJCgAAAA==.',
Zz='Zzin:BAAALgAECgQJCAAAAA==.Zzturtlezz:BAABLgAECn8XAAIMAAcJ0A7vSgA9AQdoDAAABAAkAGkMAAAEADgAawwAAAMAJQBqDAAABAAlAGwMAAACACYAbQwAAAEAIQDqDAAABQAXAAwABwnQDu9KAD0BB2gMAAAEACQAaQwAAAQAOABrDAAAAwAlAGoMAAAEACUAbAwAAAIAJgBtDAAAAQAhAOoMAAAFABcAAAA=.',
['Än']='Änorack:BAAALgAECgMJBAAAAA==.',
['Ço']='Çountèr:BAACLgAFFH8UAAIRAAUJCRjDEABJAQVoDAAABgBBAGkMAAAEACEAawwAAAMAPABqDAAAAQBXAOoMAAAGAFUAEQAFCQkYwxAASQEFaAwAAAYAQQBpDAAABAAhAGsMAAADADwAagwAAAEAVwDqDAAABgBVAC4ABAp/LwACEQAICTEfwh4APAIAEQAICTEfwh4APAIAAAA=.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
