local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Mage-Frost','Mage-Arcane','Evoker-Augmentation','Evoker-Preservation','Evoker-Devastation','Warlock-Affliction','Warlock-Demonology','Warlock-Destruction','Shaman-Enhancement','Shaman-Elemental','Shaman-Restoration','Paladin-Retribution','Druid-Restoration','Mage-Fire','DemonHunter-Devourer','Druid-Balance','Hunter-BeastMastery','DemonHunter-Havoc','DemonHunter-Vengeance','Unknown-Unknown','DeathKnight-Blood','Priest-Discipline','DeathKnight-Unholy','Hunter-Marksmanship','Druid-Feral','Priest-Shadow','Paladin-Holy','Rogue-Subtlety','Rogue-Outlaw','Monk-Mistweaver','Monk-Windwalker','Paladin-Protection','Hunter-Survival','Druid-Guardian','Priest-Holy','Warrior-Fury','Warrior-Protection','DeathKnight-Frost',}
local provider = {region='US',realm='Dunemaul',name='US',type='daily',zone=46,date='2026-06-14',data={Aa='Aaletaa:BAAALgADCgUJBQABLgAFFAUJDQABADAQAA==.',
Al='Alalange:BAAALgADCgQJBAAAAA==.Alendrael:BAAALgAECgIJAgAAAA==.Allice:BAABLgAECn8fAAMCAAcJwBxfAwA8AgdoDAAABwBdAGkMAAAEAFwAawwAAAQAVABqDAAAAgASAGwMAAADAEEAbQwAAAIAFgDqDAAACQBSAAIABwlrHF8DADwCB2gMAAAGAF0AaQwAAAMAXABrDAAABABUAGoMAAACABIAbAwAAAMAQQBtDAAAAQARAOoMAAAIAFIAAQAECaEMtA0BlAAEaAwAAAEAHQBpDAAAAQAgAG0MAAABABYA6gwAAAEALAAAAA==.Alsheyra:BAAALgAECgcJCwAAAA==.Alterion:BAAALgAECgMJBAAAAA==.Altimusprime:BAAALgAFFAIJAgAAAA==.',
An='Anastasija:BAAALgAECgEJAgAAAA==.Antitww:BAAALgADCgkJCQAAAA==.Anxious:BAAALgADCgYJDgAAAA==.',
Ar='Arahwn:BAAALgAECgUJBQAAAA==.',
As='Astaru:BAAALgAECgQJBwABLgAECgkJKAABAEAMAA==.',
Au='Aughyst:BAAALgAECgQJBAAAAA==.Augnyxia:BAABLgAECn8sAAQDAAcJnxOuJACYAQdoDAAACQA4AGkMAAAJAEkAawwAAAcAPABqDAAABwBSAGwMAAAFAC4AbQwAAAEACQDqDAAABgA2AAMABwm7Ea4kAJgBB2gMAAAHADgAaQwAAAgASQBrDAAABwA8AGoMAAAEAFIAbAwAAAMAEQBtDAAAAQAJAOoMAAAFADYABAAECSAEZy0AfAAEaAwAAAEACwBpDAAAAQAPAGoMAAABAAgAbAwAAAEABgAFAAQJ8Q6SHABmAARoDAAAAQAoAGoMAAACAC0AbAwAAAEALgDqDAAAAQAbAAAA.Augtism:BAABLgAECn8zAAQGAAkJXCJtAgCrAgloDAAACABfAGkMAAAIAFoAawwAAAgAWgBqDAAABgBeAGwMAAAFAFwAbQwAAAEASQDqDAAACABhAG4MAAAFAEMAbwwAAAIAYAAGAAgJqSFtAgCrAghoDAAAAgBVAGkMAAACAEsAawwAAAIAWgBqDAAAAgBcAGwMAAACAFwA6gwAAAMAXwBuDAAAAwBDAG8MAAABAGAABwAJCYMffSgAOQIJaAwAAAYAXwBpDAAABgBaAGsMAAAGAFoAagwAAAMAXgBsDAAAAwBaAG0MAAABAEkA6gwAAAUAYQBuDAAAAgAwAG8MAAABADsACAABCQAA110AVQABagwAAAEASAAAAA==.',
Av='Avengedfoldz:BAAALgAECgMJBAAAAA==.Avengedmunk:BAAALgADCgUJBQAAAA==.Avengedx:BAAALgAECgMJBAAAAA==.Avengeseven:BAAALgADCgYJBgAAAA==.',
Ay='Aylaa:BAAALgADCgMJAwAAAA==.',
Ba='Balsamicvinn:BAAALgAECgMJAwAAAA==.Bamfp:BAAALgAECgUJCAAAAA==.Bandobras:BAAALgAECgUJCgAAAA==.Bangtwinkdh:BAAALgAFFAMJAwABLgAFFAkJIQAFAMgfAA==.',
Be='Beefquake:BAAALgAECggJDwAAAA==.Belfdelphine:BAAALgAECgYJCwAAAA==.Berafii:BAAALgAECgEJAQAAAA==.Bersh:BAABLgAECn8xAAQJAAkJFR0KBwBeAgloDAAABwBPAGkMAAAHAE8AawwAAAcAUQBqDAAACQBTAGwMAAAGAFgAbQwAAAIAQQDqDAAABgBQAG4MAAAEAFcAbwwAAAEAIQAJAAkJFxwKBwBeAgloDAAAAwBPAGkMAAACAE0AawwAAAIAPgBqDAAAAwBOAGwMAAAFAFgAbQwAAAIAQQDqDAAAAgBQAG4MAAAEAFcAbwwAAAEAIQAKAAYJuhc2QgAoAQZoDAAABABFAGkMAAAFAE8AawwAAAUAUQBqDAAABQBTAGwMAAABAAkA6gwAAAQAQAALAAEJAQiMngAyAAFqDAAAAQAUAAAA.',
Bi='Bigstankyy:BAAALgADCgQJCAAAAA==.',
Bl='Blarn:BAAALgAECgQJBAAAAA==.Bloodjury:BAABLgAECn8bAAIMAAgJvxrWUgDPAQhoDAAABgBJAGkMAAAGAFgAawwAAAYAMQBqDAAAAgBZAGwMAAACAEQAbQwAAAEAOgDqDAAAAwBCAG4MAAABAEoADAAICb8a1lIAzwEIaAwAAAYASQBpDAAABgBYAGsMAAAGADEAagwAAAIAWQBsDAAAAgBEAG0MAAABADoA6gwAAAMAQgBuDAAAAQBKAAAA.Bloom:BAAALgADCgYJBgAAAA==.Blossom:BAABLgAECn8VAAINAAgJpxhBKwD8AQhoDAAAAwBcAGkMAAADACsAawwAAAIASABqDAAAAwBNAGwMAAACACIAbQwAAAEAKgDqDAAABABIAG4MAAADAEQADQAICacYQSsA/AEIaAwAAAMAXABpDAAAAwArAGsMAAACAEgAagwAAAMATQBsDAAAAgAiAG0MAAABACoA6gwAAAQASABuDAAAAwBEAAAA.Bluespirit:BAAALgADCgEJAQAAAA==.',
Bo='Booghur:BAAALgADCgUJBQAAAA==.Boonktown:BAABLgAECn8rAAMBAAkJnw0kYgC4AQloDAAABgArAGkMAAAFACUAawwAAAQAIwBqDAAABgAyAGwMAAAGAB4AbQwAAAMAOADqDAAABgAhAG4MAAAFAB0AbwwAAAIADAABAAkJQA0kYgC4AQloDAAAAwAjAGkMAAACACUAawwAAAEAIwBqDAAAAwAyAGwMAAADAB4AbQwAAAMAOADqDAAAAwAhAG4MAAADAB0AbwwAAAIADAAOAAcJuQn5BAB9AQdoDAAAAwArAGkMAAADABsAawwAAAMAEgBqDAAAAwAsAGwMAAADABMA6gwAAAMAEgBuDAAAAgAVAAAA.Booschlock:BAAALgAECgMJAwAAAA==.',
Br='Brambles:BAAALgAECgYJDgAAAA==.Bruceleela:BAAALgAECgYJCwABLgAECgcJIQAPAH4VAA==.Brunarr:BAAALgAECgQJEQAAAA==.',
Bu='Bushetti:BAABLgAECn8dAAMNAAgJCBXfSwBdAQhoDAAABgBIAGkMAAAFADgAawwAAAMAVgBqDAAAAwA+AGwMAAADACMAbQwAAAEAFwDqDAAABgBGAG4MAAACABcADQAICQgV30sAXQEIaAwAAAYASABpDAAABQA4AGsMAAADAFYAagwAAAMAPgBsDAAAAgAjAG0MAAABABcA6gwAAAUARgBuDAAAAQAXABAAAwmbGAZoAHsAA2wMAAABACUA6gwAAAEAUgBuDAAAAQBEAAEuAAUUAwkNAAsA1x8A.',
Ca='Candlemass:BAAALgAECgQJBQAAAA==.Canelor:BAAALgADCgEJAQAAAA==.Casperface:BAABLgAECn8dAAMKAAkJYBElJQDoAQloDAAABABBAGkMAAAFADYAawwAAAUARABqDAAABAAlAGwMAAAEACoAbQwAAAEADADqDAAABAA0AG4MAAABABQAbwwAAAEAJgAKAAkJYBElJQDoAQloDAAAAwBBAGkMAAAEADYAawwAAAQARABqDAAAAwAlAGwMAAADACoAbQwAAAEADADqDAAAAwA0AG4MAAABABQAbwwAAAEAJgALAAYJDxUnVgBaAQZoDAAAAQBYAGkMAAABAD8AawwAAAEAKQBqDAAAAQAyAGwMAAABACkA6gwAAAEAJQAAAA==.Catawampus:BAAALgADCgQJBAAAAA==.Caylo:BAAALgAECgUJCAAAAA==.Cazisham:BAABLgAECn8jAAIJAAkJSQbeGAA8AQloDAAABgAHAGkMAAAGAA8AawwAAAYADgBqDAAAAwAIAGwMAAAFABcAbQwAAAEABADqDAAABgAiAG4MAAABAAkAbwwAAAEAEgAJAAkJSQbeGAA8AQloDAAABgAHAGkMAAAGAA8AawwAAAYADgBqDAAAAwAIAGwMAAAFABcAbQwAAAEABADqDAAABgAiAG4MAAABAAkAbwwAAAEAEgAAAA==.',
Ce='Cevianne:BAABLgAECn8sAAIRAAgJjRMsOADNAQhoDAAABgBBAGkMAAAGACoAawwAAAYAJgBqDAAABgBCAGwMAAAGADsAbQwAAAQAOADqDAAABgA9AG4MAAAEABoAEQAICY0TLDgAzQEIaAwAAAYAQQBpDAAABgAqAGsMAAAGACYAagwAAAYAQgBsDAAABgA7AG0MAAAEADgA6gwAAAYAPQBuDAAABAAaAAAA.',
Ch='Chama:BAAALgADCgEJAQAAAA==.Chamhealeon:BAAALgAECgIJAgAAAA==.Chanok:BAAALgADCgMJBgAAAA==.Chaoticsaint:BAABLgAECn8XAAISAAgJEBHJLwAFAQhoDAAABAA8AGkMAAAEADQAawwAAAQAMQBqDAAAAwAhAGwMAAABABoAbQwAAAEAHgDqDAAABQA3AG4MAAABAB4AEgAICRARyS8ABQEIaAwAAAQAPABpDAAABAA0AGsMAAAEADEAagwAAAMAIQBsDAAAAQAaAG0MAAABAB4A6gwAAAUANwBuDAAAAQAeAAAA.Chingatumaga:BAAALgADCgIJAgAAAA==.Chronoblade:BAAALgAECgMJBAAAAA==.',
Cl='Claros:BAAALgAECggJDAAAAA==.',
Co='Coal:BAABLgAECn81AAMPAAkJuCPYCAAFAwloDAAACABhAGkMAAAIAF0AawwAAAkAUQBqDAAABgBgAGwMAAAGAFsAbQwAAAIAVADqDAAACQBiAG4MAAAEAFkAbwwAAAEAXgAPAAkJuCPYCAAFAwloDAAABwBhAGkMAAAHAF0AawwAAAgAUQBqDAAABQBgAGwMAAAFAFsAbQwAAAIAVADqDAAACABiAG4MAAADAFkAbwwAAAEAXgATAAcJ5xsHCQDcAQdoDAAAAQBTAGkMAAABAEUAawwAAAEALABqDAAAAQBgAGwMAAABAFQA6gwAAAEAVwBuDAAAAQA7AAAA.Coalesce:BAAALgADCgQJBAABLgAECgkJNQAPALgjAA==.Coltonater:BAABLgAECn8+AAIBAAgJ7iHvJACHAghoDAAACABZAGkMAAAIAFwAawwAAAkAUABqDAAACgBUAGwMAAAHAGEAbQwAAAYAWgDqDAAACQBUAG4MAAAFAEgAAQAICe4h7yQAhwIIaAwAAAgAWQBpDAAACABcAGsMAAAJAFAAagwAAAoAVABsDAAABwBhAG0MAAAGAFoA6gwAAAkAVABuDAAABQBIAAAA.Corlieb:BAAALgAECgQJBAAAAA==.',
Cu='Cuh:BAAALgAECgcJBwAAAA==.Curlyfrys:BAAALgADCgQJBAAAAA==.',
['Cá']='Cáséy:BAACLgAFFH8TAAIBAAQJDh7wQgBmAQRoDAAABgBcAGkMAAAGAFkAawwAAAMAHgDqDAAABABfAAEABAkOHvBCAGYBBGgMAAAGAFwAaQwAAAYAWQBrDAAAAwAeAOoMAAAEAF8ALgAECn8jAAIBAAkJnh1sOAA1AgABAAkJnh1sOAA1AgAAAA==.',
['Cä']='Cäsey:BAAALgAECgUJCQABLgAFFAUJEwABAA4eAA==.',
Da='Daktari:BAAALgADCgYJBgABLgAECgkJLgANAAocAA==.Dampening:BAAALgAECgMJAwABLgAECgUJBQAUAAAAAA==.Danbi:BAACLgAFFH8GAAMDAAQJzAdXPADRAARoDAAAAgAfAGkMAAACABQAawwAAAEABQDqDAAAAQAVAAMABAnMB1c8ANEABGgMAAABAB8AaQwAAAEAFABrDAAAAQAFAOoMAAABABUABAACCfsIKiYAXgACaAwAAAEAIwBpDAAAAQAKAC4ABAp/NQAEBAAJCZQXyw0A8AEABAAICUQXyw0A8AEAAwAJCfYT6BwA7gEABQAECbYPjhcAnQAAAAA=.Darkshroud:BAAALgAECgIJAgAAAA==.',
De='Deathdylan:BAACLgAFFH8QAAIVAAQJyQlhJQDEAARoDAAABwArAGkMAAAEACEAawwAAAEABADqDAAABAASABUABAnJCWElAMQABGgMAAAHACsAaQwAAAQAIQBrDAAAAQAEAOoMAAAEABIALgAECn8wAAIVAAkJQB4fCgBvAgAVAAkJQB4fCgBvAgAAAA==.Deathra:BAAALgADCgYJBgAAAA==.Deathseer:BAABLgAECn8hAAIPAAcJfhVyYgBhAQdoDAAABQAtAGkMAAAFADwAawwAAAUANgBqDAAABQA4AGwMAAAGAEgAbQwAAAEADQDqDAAABgBUAA8ABwl+FXJiAGEBB2gMAAAFAC0AaQwAAAUAPABrDAAABQA2AGoMAAAFADgAbAwAAAYASABtDAAAAQANAOoMAAAGAFQAAAA=.Deathshaq:BAAALgADCggJGQAAAA==.Delice:BAAALgAECgEJAQAAAA==.Demi:BAAALgADCgYJBgAAAA==.Demiev:BAAALgAECgEJAQAAAA==.Demítríus:BAAALgADCgYJDQAAAA==.Dethh:BAAALgADCgYJCQAAAA==.Dethpally:BAAALgADCgYJBgAAAA==.',
Di='Dionarose:BAAALgADCgYJBgAAAA==.Dionos:BAAALgAECgEJAQAAAA==.',
Do='Dourwolf:BAAALgADCgUJBAAAAA==.',
Dr='Dragman:BAAALgAECgUJBQAAAA==.Dragonlord:BAAALgAECgYJBgAAAA==.Draugr:BAAALgADCgUJBQAAAA==.Dravyn:BAABLgAECn8oAAIBAAkJQAy8ZwCrAQloDAAABgAVAGkMAAAFADUAawwAAAUADwBqDAAABAAfAGwMAAAEACoAbQwAAAMAIQDqDAAACAATAG4MAAADACcAbwwAAAIAGAABAAkJQAy8ZwCrAQloDAAABgAVAGkMAAAFADUAawwAAAUADwBqDAAABAAfAGwMAAAEACoAbQwAAAMAIQDqDAAACAATAG4MAAADACcAbwwAAAIAGAAAAA==.Drfiredumper:BAABLgAECn8iAAIBAAgJmhxNNQCeAghoDAAABQBJAGkMAAAFAFgAawwAAAUAXABqDAAABQBKAGwMAAAGAFoAbQwAAAEASADqDAAABgBDAG4MAAABABwAAQAICZocTTUAngIIaAwAAAUASQBpDAAABQBYAGsMAAAFAFwAagwAAAUASgBsDAAABgBaAG0MAAABAEgA6gwAAAYAQwBuDAAAAQAcAAAA.Druqz:BAACLgAFFH8QAAIBAAQJAwRxdQD0AARoDAAABgAUAGkMAAADAAcAawwAAAEACADqDAAABgAEAAEABAkDBHF1APQABGgMAAAGABQAaQwAAAMABwBrDAAAAQAIAOoMAAAGAAQALgAECn8ZAAIBAAgJngqnmwBAAQABAAgJngqnmwBAAQAAAA==.Drævn:BAABLgAECn84AAMOAAcJAxjJBQBmAQdoDAAACwBNAGkMAAAMADoAawwAAAoARQBqDAAACABDAGwMAAAIAD0AbQwAAAEAIgDqDAAABgBDAAEABwmvFAt8AH0BB2gMAAAEADMAaQwAAAUAMABrDAAABgA1AGoMAAAHADIAbAwAAAYAPQBtDAAAAQAiAOoMAAAFAEMADgAGCXYYyQUAZgEGaAwAAAcATQBpDAAABwA6AGsMAAAEAEUAagwAAAEAQwBsDAAAAgA1AOoMAAABADYAAAA=.',
Du='Ducky:BAAALgADCgEJAQAAAA==.Dum:BAACLgAFFH8aAAMPAAcJqB1RFAAFAgdoDAAABgBcAGkMAAAGAGIAawwAAAQAQQBqDAAAAgBeAGwMAAABAE8AbQwAAAEAJADqDAAABgBSAA8ABwmoHVEUAAUCB2gMAAAGAFwAaQwAAAUAYgBrDAAAAwBBAGoMAAACAF4AbAwAAAEATwBtDAAAAQAkAOoMAAAGAFIAEwACCUILRw0AbgACaQwAAAEADgBrDAAAAQArAC4ABAp/KQACDwAJCW8kUAYAJAMADwAJCW8kUAYAJAMAAAA=.Duragon:BAAALgAECgcJDQAAAA==.',
Dw='Dwimbear:BAAALgAECgEJAQAAAA==.Dwimhoof:BAAALgAECgEJAwAAAA==.',
Ed='Ediconegoen:BAAALgAECgEJAgAAAA==.',
Ei='Eiir:BAAALgADCgQJAwAAAA==.',
El='Eldin:BAACLgAFFH8QAAIWAAQJqRxYHgBcAQRoDAAABQBOAGkMAAAFAFIAawwAAAEAKADqDAAABQBbABYABAmpHFgeAFwBBGgMAAAFAE4AaQwAAAUAUgBrDAAAAQAoAOoMAAAFAFsALgAECn8bAAIWAAkJAB/7DwA/AgAWAAkJAB/7DwA/AgAAAA==.Elunadorei:BAAALgAECgMJBAAAAA==.',
Em='Emancipation:BAAALgAECgYJDgAAAA==.',
En='Enchantress:BAABLgAECn8hAAMBAAkJ0gsjbgCcAQloDAAABgAyAGkMAAAFACMAawwAAAYAKABqDAAAAwAiAGwMAAADABkAbQwAAAMAEADqDAAABAAnAG4MAAACABQAbwwAAAEADgABAAkJ0gsjbgCcAQloDAAABQAyAGkMAAAFACMAawwAAAUAKABqDAAAAwAiAGwMAAADABkAbQwAAAMAEADqDAAABAAnAG4MAAACABQAbwwAAAEADgACAAIJOgZTGQBNAAJoDAAAAQAWAGsMAAABAAkAAAA=.Endofdays:BAAALgAFFAMJAwAAAA==.Enro:BAACLgAFFH8IAAISAAQJiQxSEwAIAQRoDAAAAgAbAGkMAAADACUAawwAAAEAKgDqDAAAAgAUABIABAmJDFITAAgBBGgMAAACABsAaQwAAAMAJQBrDAAAAQAqAOoMAAACABQALgAECn9AAAMSAAkJqh+ZBQDjAgASAAkJqh+ZBQDjAgAPAAQJqgd+tQCdAAAAAA==.',
Er='Erovia:BAACLgAFFH8HAAIRAAMJoQNHcQCzAANoDAAAAwAKAGkMAAACAAwA6gwAAAIABAARAAMJoQNHcQCzAANoDAAAAwAKAGkMAAACAAwA6gwAAAIABAAuAAQKfyMAAhEACQlXCdt+AD4BABEACQlXCdt+AD4BAAAA.',
Es='Esclipse:BAAALgAECgcJCgAAAA==.',
Et='Etc:BAAALgADCgIJAgAAAA==.',
Fa='Farruq:BAAALgAFFAEJAQAAAA==.',
Fe='Felony:BAABLgAECn8zAAISAAkJGCSRAwAaAwloDAAACABeAGkMAAAIAGIAawwAAAcAXQBqDAAABQBfAGwMAAAGAGMAbQwAAAEATgDqDAAACQBdAG4MAAAGAF0AbwwAAAEAVgASAAkJGCSRAwAaAwloDAAACABeAGkMAAAIAGIAawwAAAcAXQBqDAAABQBfAGwMAAAGAGMAbQwAAAEATgDqDAAACQBdAG4MAAAGAF0AbwwAAAEAVgAAAA==.Feyri:BAAALgADCgMJAwAAAA==.',
Fl='Flavaflare:BAAALgAECgEJAQABLgAECggJGwAQADEdAA==.Flavah:BAABLgAECn8bAAIQAAgJMR2YHAAdAghoDAAABgBVAGkMAAAFAE4AawwAAAUATQBqDAAAAwA8AGwMAAADAEwAbQwAAAEAQADqDAAAAwBSAG4MAAABADoAEAAICTEdmBwAHQIIaAwAAAYAVQBpDAAABQBOAGsMAAAFAE0AagwAAAMAPABsDAAAAwBMAG0MAAABAEAA6gwAAAMAUgBuDAAAAQA6AAAA.Flavahflav:BAAALgAECgYJCgAAAA==.Floormatt:BAABLgAECn8wAAMXAAkJqBMvWgC2AQloDAAABgBEAGkMAAAGADIAawwAAAYARgBqDAAACAAkAGwMAAAHADMAbQwAAAIACQDqDAAABwA7AG4MAAAFADUAbwwAAAEAJgAXAAkJqBMvWgC2AQloDAAABQBEAGkMAAAFADIAawwAAAUARgBqDAAABwAkAGwMAAAGADMAbQwAAAIACQDqDAAABgA7AG4MAAAEADUAbwwAAAEAJgAVAAcJDQRbPACdAAdoDAAAAQAIAGkMAAABAAcAawwAAAEAHQBqDAAAAQADAGwMAAABAAcA6gwAAAEABABuDAAAAQAEAAAA.Flower:BAABLgAFFH8FAAIRAAMJRxbKVgDyAANoDAAAAgBaAGkMAAACAEkA6gwAAAEABwARAAMJRxbKVgDyAANoDAAAAgBaAGkMAAACAEkA6gwAAAEABwAAAA==.',
Fo='Foodex:BAAALgAECgcJEQAAAA==.Fourleaf:BAACLgAFFH8RAAIYAAQJMxu4EABTAQRoDAAABgA/AGkMAAAFAFIAawwAAAIAKADqDAAABABcABgABAkzG7gQAFMBBGgMAAAGAD8AaQwAAAUAUgBrDAAAAgAoAOoMAAAEAFwALgAECn86AAIYAAkJQiHaAQDrAgAYAAkJQiHaAQDrAgAAAA==.',
Fr='Frydayx:BAAALgAECgMJBAAAAA==.',
Fu='Furral:BAACLgAFFH8KAAIZAAMJRxn3CwDnAANoDAAABABFAGkMAAAFADoA6gwAAAEAQQAZAAMJRxn3CwDnAANoDAAABABFAGkMAAAFADoA6gwAAAEAQQAuAAQKfyEAAhkACQk3HwgEAMUCABkACQk3HwgEAMUCAAAA.',
Ga='Gaeth:BAABLgAECn8jAAINAAkJUBAIQgCZAQloDAAABQAzAGkMAAAFAEEAawwAAAUANgBqDAAABAAnAGwMAAAFACwAbQwAAAEAGADqDAAABgA8AG4MAAADAA8AbwwAAAEAEwANAAkJUBAIQgCZAQloDAAABQAzAGkMAAAFAEEAawwAAAUANgBqDAAABAAnAGwMAAAFACwAbQwAAAEAGADqDAAABgA8AG4MAAADAA8AbwwAAAEAEwAAAA==.',
Ge='Gelys:BAAALgAECgQJBAABLgAFFAQJBwAaAF8LAA==.',
Gh='Gheal:BAAALgAECgUJBQAAAA==.',
Gl='Gleg:BAABLgAFFH8NAAILAAMJ1x84NQAIAQNoDAAABgBKAGkMAAADAFQA6gwAAAQAVQALAAMJ1x84NQAIAQNoDAAABgBKAGkMAAADAFQA6gwAAAQAVQAAAA==.',
Gn='Gnomeagedon:BAAALgAFFAIJAgAAAA==.',
Go='Goopdawg:BAAALgAECgQJDAAAAA==.Goregon:BAAALgAECgYJBwAAAA==.',
Gr='Grimthebrave:BAAALgAECgEJAQAAAA==.Grimthecruel:BAABLgAECn8WAAIPAAcJwxfGWwByAQdoDAAABABBAGkMAAAEAD4AawwAAAQAOwBqDAAAAwAnAGwMAAACADMAbQwAAAIAMgDqDAAAAwBMAA8ABwnDF8ZbAHIBB2gMAAAEAEEAaQwAAAQAPgBrDAAABAA7AGoMAAADACcAbAwAAAIAMwBtDAAAAgAyAOoMAAADAEwAAAA=.Grimthedread:BAAALgADCgYJBgAAAA==.Grimvess:BAAALgAECggJCQAAAA==.Griselden:BAAALgAFFAIJAwAAAA==.Grungle:BAAALgADCgIJAgAAAA==.',
Ha='Hamburgler:BAAALgADCgYJBgABLgAECgkJIAARAKchAA==.Hammerobby:BAAALgAECgYJCgABLgAECgcJIQAPAH4VAA==.Handlebar:BAAALgAECgUJCgABLgAECgcJIQAPAH4VAA==.Hannsollo:BAAALgADCgEJAQAAAA==.',
He='Heavenfall:BAAALgADCgMJAwAAAA==.Hellomon:BAAALgAFFAEJAQAAAA==.Hellspawn:BAAALgADCgUJBQAAAA==.',
Ho='Holycowherd:BAABLgAECn8gAAIMAAkJERGoXwCwAQloDAAABgBTAGkMAAAGADYAawwAAAYAPgBqDAAABAAcAGwMAAACACAAbQwAAAEAGgDqDAAAAwAiAG4MAAACACAAbwwAAAIAGAAMAAkJERGoXwCwAQloDAAABgBTAGkMAAAGADYAawwAAAYAPgBqDAAABAAcAGwMAAACACAAbQwAAAEAGgDqDAAAAwAiAG4MAAACACAAbwwAAAIAGAAAAA==.Holycrem:BAAALgADCgEJAQAAAA==.Holyshock:BAABLgAECn8YAAMMAAYJmgTuDwGjAAZoDAAABQAXAGkMAAAFAAYAawwAAAUACQBqDAAAAwAOAGwMAAADAAsA6gwAAAMABwAMAAYJmgTuDwGjAAZoDAAABAAXAGkMAAAEAAYAawwAAAQACQBqDAAAAwAOAGwMAAADAAsA6gwAAAIABwAbAAQJPgJ/cgBrAARoDAAAAQAGAGkMAAABAAQAawwAAAEACADqDAAAAQAEAAAA.',
Hu='Hungsu:BAAALgAECgEJAQAAAA==.',
Hy='Hyournmaru:BAAALgAECgYJBAAAAA==.',
['Hâ']='Hâmburger:BAAALgADCgQJAwAAAA==.',
Ia='Iamapally:BAAALgAECgEJAQAAAA==.',
Id='Idris:BAAALgADCgYJBgAAAA==.',
Il='Ilkkarid:BAABLgAECn8bAAMcAAgJIBLEGwC2AQhoDAAABAAbAGkMAAAEAC4AawwAAAQANABqDAAABAAkAGwMAAAEAC0AbQwAAAIAKADqDAAAAwA+AG4MAAACADIAHAAICfwRxBsAtgEIaAwAAAEAGABpDAAAAQAuAGsMAAABADQAagwAAAEAJABsDAAAAgAtAG0MAAACACgA6gwAAAEAPgBuDAAAAgAyAB0ABgkGCjgSAOYABmgMAAADABsAaQwAAAMAHABrDAAAAwAeAGoMAAADABEAbAwAAAIAEgDqDAAAAgAXAAAA.',
In='Incarcerated:BAAALgADCgQJBAAAAA==.Infêstus:BAAALgAECgQJBAAAAA==.',
Ir='Iridessa:BAABLgAECn8ZAAIaAAcJpQpvQwAAAQdoDAAABAAjAGkMAAAEACAAawwAAAQAIABqDAAAAwAmAGwMAAADAAkAbQwAAAEABQDqDAAABgAvABoABwmlCm9DAAABB2gMAAAEACMAaQwAAAQAIABrDAAABAAgAGoMAAADACYAbAwAAAMACQBtDAAAAQAFAOoMAAAGAC8AAAA=.',
Is='Ishpoo:BAABLgAECn8vAAIMAAkJ0xD1VQDHAQloDAAABwAlAGkMAAAGACQAawwAAAcAIQBqDAAABgAvAGwMAAAHAD8AbQwAAAQAOwDqDAAABQAdAG4MAAADACcAbwwAAAIALAAMAAkJ0xD1VQDHAQloDAAABwAlAGkMAAAGACQAawwAAAcAIQBqDAAABgAvAGwMAAAHAD8AbQwAAAQAOwDqDAAABQAdAG4MAAADACcAbwwAAAIALAAAAA==.',
Ja='Jaellen:BAAALgAECgQJBgABLgAECggJIgABAJocAA==.Janasong:BAAALgAECgMJBAAAAA==.',
Je='Jecht:BAAALgADCgEJAQAAAA==.Jelqer:BAABLgAECn8VAAMFAAYJsCCaEgC4AQZoDAAABQBbAGkMAAAEAFQAawwAAAQAWABqDAAAAwBDAGwMAAACAEwA6gwAAAMATAAFAAYJsCCaEgC4AQZoDAAABABbAGkMAAACAFQAawwAAAIAWABqDAAAAQABAGwMAAABAEwA6gwAAAMATAADAAUJZBQXMABFAQVoDAAAAQBCAGkMAAACADwAawwAAAIAJABqDAAAAgBDAGwMAAABACwAAAA=.Jennybunbun:BAAALgADCgcJBwAAAA==.',
Ji='Jimmycooks:BAAALgADCgMJAwAAAA==.',
Jl='Jlaworz:BAABLgAECn8qAAINAAkJOR21FACiAgloDAAABgBQAGkMAAAGAFsAawwAAAYAVABqDAAABAAxAGwMAAAEAFsAbQwAAAMAWgDqDAAABgBQAG4MAAAFAEMAbwwAAAIAJAANAAkJOR21FACiAgloDAAABgBQAGkMAAAGAFsAawwAAAYAVABqDAAABAAxAGwMAAAEAFsAbQwAAAMAWgDqDAAABgBQAG4MAAAFAEMAbwwAAAIAJAAAAA==.Jlawzzs:BAAALgAECgMJAgAAAA==.',
Jo='Job:BAACLgAFFH8iAAMPAAgJ5R0KCgBuAghoDAAACABeAGkMAAAHAFwAawwAAAQATQBqDAAAAgA+AGwMAAABAFUAbQwAAAEAOwDqDAAACgBgAG4MAAABAB0ADwAICWkdCgoAbgIIaAwAAAcAXgBpDAAABgBTAGsMAAAEAE0AagwAAAIAPgBsDAAAAQBVAG0MAAABADsA6gwAAAgAYABuDAAAAQAdABIAAwk2Ip8OAC0BA2gMAAABAFYAaQwAAAEAXADqDAAAAgBUAC4ABAp/PAADDwAJCaIklAQAPAMADwAJCaIklAQAPAMAEgAHCb8g2CMAngEAAAA=.',
Ju='Juanweasley:BAAALgAFFAEJAQAAAA==.Judoriel:BAAALgAECgcJDAAAAA==.Junkyard:BAAALgAECgQJCgAAAA==.',
Ka='Kahsindre:BAABLgAECn8oAAIRAAkJuRqbHgBsAgloDAAABgA1AGkMAAAFAFoAawwAAAUAWwBqDAAABQBNAGwMAAAFAEAAbQwAAAQAIADqDAAABQBaAG4MAAAEAFgAbwwAAAEAIwARAAkJuRqbHgBsAgloDAAABgA1AGkMAAAFAFoAawwAAAUAWwBqDAAABQBNAGwMAAAFAEAAbQwAAAQAIADqDAAABQBaAG4MAAAEAFgAbwwAAAEAIwAAAA==.Kaimin:BAABLgAECn9MAAIXAAkJHCFBDgD4AgloDAAADABfAGkMAAALAFgAawwAAAwAXgBqDAAACABgAGwMAAAHAEsAbQwAAAMATgDqDAAADQBcAG4MAAAHAEsAbwwAAAMATQAXAAkJHCFBDgD4AgloDAAADABfAGkMAAALAFgAawwAAAwAXgBqDAAACABgAGwMAAAHAEsAbQwAAAMATgDqDAAADQBcAG4MAAAHAEsAbwwAAAMATQAAAA==.Karthas:BAAALgAECgIJBQAAAA==.',
Ke='Kellenved:BAAALgADCgEJAQABLgAECgcJAQAUAAAAAA==.Kennypowers:BAAALgAECgQJCAAAAA==.Kezeshi:BAABLgAECn8xAAMWAAkJdRgTEABuAgloDAAACABDAGkMAAAIAEwAawwAAAgAOgBqDAAABgA4AGwMAAAFAEkAbQwAAAMAMwDqDAAABwAyAG4MAAADAFgAbwwAAAEAKAAWAAkJdRgTEABuAgloDAAABwBDAGkMAAAHAEwAawwAAAcAOgBqDAAABgA4AGwMAAAFAEkAbQwAAAMAMwDqDAAABwAyAG4MAAADAFgAbwwAAAEAKAAaAAMJFAPIVQBqAANoDAAAAQAHAGkMAAABAAQAawwAAAEACwAAAA==.',
Kh='Khaidralulz:BAABLgAECn8yAAMLAAkJ8xCQPgCxAQloDAAACAAnAGkMAAAHAEQAawwAAAcAFQBqDAAABgAdAGwMAAAHAB4AbQwAAAQAOgDqDAAABgAmAG4MAAADADEAbwwAAAIANQALAAkJ8xCQPgCxAQloDAAACAAnAGkMAAAGAEQAawwAAAYAFQBqDAAABQAdAGwMAAAGAB4AbQwAAAQAOgDqDAAABgAmAG4MAAADADEAbwwAAAIANQAJAAQJfApQKwCYAARpDAAAAQAXAGsMAAABACUAagwAAAEAIABsDAAAAQATAAAA.Khonsu:BAAALgAECgcJDAAAAA==.',
Ki='Kiba:BAABLgAECn8kAAMeAAcJwg8WQwBbAQdoDAAABgAwAGkMAAAIACoAawwAAAYANwBqDAAABgAqAGwMAAAFACAAbQwAAAEAFQDqDAAABAAoAB4ABwnCDxZDAFsBB2gMAAAGADAAaQwAAAcAKgBrDAAABQA3AGoMAAAGACoAbAwAAAQAIABtDAAAAQAVAOoMAAADACgAHwAECaYKrFkAqgAEaQwAAAEAFwBrDAAAAQAZAGwMAAABAA4A6gwAAAEALQAAAA==.Kiliko:BAAALgADCgEJAQAAAA==.Killershammy:BAABLgAECn8gAAILAAgJ2Rh1IwA3AghoDAAABQA4AGkMAAAFAEAAawwAAAQASgBqDAAABQBTAGwMAAAEAEwAbQwAAAIAJgDqDAAABQA7AG4MAAACADcACwAICdkYdSMANwIIaAwAAAUAOABpDAAABQBAAGsMAAAEAEoAagwAAAUAUwBsDAAABABMAG0MAAACACYA6gwAAAUAOwBuDAAAAgA3AAAA.',
Kn='Knubboi:BAAALgADCgcJBwAAAA==.',
Ko='Kowadin:BAAALgADCgEJAQAAAA==.Koy:BAAALgADCgIJAwAAAA==.',
Kr='Kraegen:BAABLgAECn8lAAIgAAkJkQvbGgA/AQloDAAABgAtAGkMAAAGACwAawwAAAYALwBqDAAABAAcAGwMAAADABEAbQwAAAMAKgDqDAAABQAUAG4MAAADAAcAbwwAAAEACQAgAAkJkQvbGgA/AQloDAAABgAtAGkMAAAGACwAawwAAAYALwBqDAAABAAcAGwMAAADABEAbQwAAAMAKgDqDAAABQAUAG4MAAADAAcAbwwAAAEACQAAAA==.',
Ku='Kushiea:BAAALgADCgIJAgAAAA==.',
Ky='Kyofu:BAACLgAFFH8TAAIeAAUJFRMqIwBKAQVoDAAABgA8AGkMAAAFADcAawwAAAQAKgBqDAAAAQARAOoMAAADAEMAHgAFCRUTKiMASgEFaAwAAAYAPABpDAAABQA3AGsMAAAEACoAagwAAAEAEQDqDAAAAwBDAC4ABAp/PAADHgAJCRAh5AYAMQMAHgAJCRAh5AYAMQMAHwADCXcOYmQAjAAAAAA=.',
La='Larethiana:BAACLgAFFH8FAAINAAUJhgouLAABAQVoDAAAAQBcAGkMAAABAAAAawwAAAEADABqDAAAAQASAOoMAAABAAsADQAFCYYKLiwAAQEFaAwAAAEAXABpDAAAAQAAAGsMAAABAAwAagwAAAEAEgDqDAAAAQALAC4ABAp/FAADDQAICekUokwAcQEADQAHCYwVokwAcQEAEAAGCfUWADUAagEAAAA=.',
Le='Leafmochi:BAAALgAECgYJBwAAAA==.Lennytwotoes:BAAALgAECgYJBQAAAA==.Leorick:BAAALgADCgMJAwAAAA==.Lexibelle:BAABLgAECn8UAAMbAAYJXQMfagDSAAZoDAAABAAVAGkMAAAEAAIAawwAAAQADQBqDAAAAwACAGwMAAACAAQA6gwAAAMACAAbAAYJXQMfagDSAAZoDAAAAwAVAGkMAAADAAIAawwAAAMADQBqDAAAAwACAGwMAAACAAQA6gwAAAIACAAMAAQJRQGAIQFbAARoDAAAAQACAGkMAAABAAQAawwAAAEAAwDqDAAAAQACAAAA.',
Li='Lightbright:BAACLgAFFH8MAAIMAAQJ6BxzKgBeAQRoDAAABQBWAGkMAAADAE0AawwAAAEALQDqDAAAAwBWAAwABAnoHHMqAF4BBGgMAAAFAFYAaQwAAAMATQBrDAAAAQAtAOoMAAADAFYALgAECn8jAAIMAAkJVSSXBwBaAwAMAAkJVSSXBwBaAwAAAA==.Lilbeefcake:BAAALgAECgMJAwAAAA==.Lildab:BAABLgAECn8qAAIaAAcJlB5IFgAYAgdoDAAACABbAGkMAAAHAEgAawwAAAcAQgBqDAAABgAzAGwMAAAGAFMAbQwAAAEAQQDqDAAABwBaABoABwmUHkgWABgCB2gMAAAIAFsAaQwAAAcASABrDAAABwBCAGoMAAAGADMAbAwAAAYAUwBtDAAAAQBBAOoMAAAHAFoAAAA=.Linnasha:BAABLgAECn8rAAINAAgJwBi3LwDiAQhoDAAACABJAGkMAAAFACsAawwAAAUAQABqDAAABQA7AGwMAAAGAFYAbQwAAAUALQDqDAAABwBTAG4MAAACADIADQAICcAYty8A4gEIaAwAAAgASQBpDAAABQArAGsMAAAFAEAAagwAAAUAOwBsDAAABgBWAG0MAAAFAC0A6gwAAAcAUwBuDAAAAgAyAAAA.Litlefoot:BAAALgAECgkJEwAAAA==.',
Lo='Lornzap:BAABLgAFFH8MAAIKAAMJNBu7KADuAANoDAAABQBCAGkMAAADAC8A6gwAAAQAXwAKAAMJNBu7KADuAANoDAAABQBCAGkMAAADAC8A6gwAAAQAXwAAAA==.Lostwanderer:BAABLgAECn8dAAMeAAgJBRhzHQApAghoDAAAAwBEAGkMAAADAEMAawwAAAQAUABqDAAABABAAGwMAAAEAEYAbQwAAAMAJADqDAAABgA/AG4MAAACACcAHgAICQUYcx0AKQIIaAwAAAMARABpDAAAAwBDAGsMAAADAFAAagwAAAQAQABsDAAABABGAG0MAAADACQA6gwAAAQAPwBuDAAAAgAnAB8AAgmsBb2NAEEAAmsMAAABABYA6gwAAAIABgAAAA==.Lot:BAAALgAFFAEJAQABLgAFFAgJIgAPAOUdAA==.Lowcowlorie:BAAALgAECgEJAQAAAA==.',
Ma='Machine:BAACLgAFFH8GAAIhAAMJqRLLHQDgAANoDAAAAwAtAGkMAAACADoA6gwAAAEAJgAhAAMJqRLLHQDgAANoDAAAAwAtAGkMAAACADoA6gwAAAEAJgAuAAQKfx8AAiEACQlfEiESABkCACEACQlfEiESABkCAAAA.Magtharas:BAAALgAECgYJDAAAAA==.Magzul:BAAALgADCggJCAAAAA==.Maki:BAAALgAECgUJCgAAAA==.Malacoda:BAABLgAECn8xAAISAAkJ3xbsEQAKAgloDAAACQBBAGkMAAAIAD0AawwAAAgAQABqDAAABgBUAGwMAAAGAEcAbQwAAAMANQDqDAAABgBHAG4MAAACACwAbwwAAAEAIgASAAkJ3xbsEQAKAgloDAAACQBBAGkMAAAIAD0AawwAAAgAQABqDAAABgBUAGwMAAAGAEcAbQwAAAMANQDqDAAABgBHAG4MAAACACwAbwwAAAEAIgAAAA==.Manamontana:BAAALgAECgEJAQAAAA==.Manawurm:BAAALgAECgEJAQAAAA==.Mannanan:BAAALgAECgcJDgAAAA==.Marble:BAAALgAECgUJCAAAAA==.Marshboa:BAAALgAECgUJBQAAAA==.Marymo:BAAALgADCgUJBQAAAA==.',
Me='Meatrocketxd:BAAALgAECgcJAQAAAA==.Meddicare:BAAALgADCgUJBQAAAA==.',
Mi='Mindra:BAABLgAECn8xAAQRAAkJziBBEgC9AgloDAAACABjAGkMAAAIAGIAawwAAAgAXwBqDAAABgBdAGwMAAAGAFcAbQwAAAMAUQDqDAAABgBdAG4MAAADACUAbwwAAAEATgARAAkJziBBEgC9AgloDAAACABjAGkMAAAIAGIAawwAAAgAXwBqDAAABgBdAGwMAAADAFcAbQwAAAMAUQDqDAAABgBdAG4MAAABACUAbwwAAAEATgAhAAIJPRCLTgB0AAJsDAAAAwBMAG4MAAABAAYAGAABCYcMSz0ALgABbgwAAAEAIAAAAA==.Minyaura:BAAALgADCgQJBAAAAA==.Minyholy:BAAALgAECgQJBAAAAA==.Minymoney:BAAALgADCgcJBwAAAA==.Mirañda:BAAALgADCgEJAQAAAA==.Miridian:BAAALgAECgcJDwAAAA==.Miromoney:BAAALgADCgUJBQAAAA==.Mitsuri:BAAALgAECggJDgAAAA==.',
Mo='Moatie:BAAALgAECgYJDgAAAA==.Moogician:BAAALgAECgIJBgABLgAECgkJIAARAKchAA==.Moolasses:BAAALgAECgEJAgAAAA==.Moonsïnd:BAABLgAECn8rAAMNAAkJZA0YQACQAQloDAAABwAdAGkMAAAFACEAawwAAAUAJQBqDAAABAArAGwMAAAGADkAbQwAAAQAFADqDAAACAAhAG4MAAADABsAbwwAAAEAGQANAAkJZA0YQACQAQloDAAABwAdAGkMAAAFACEAawwAAAUAJQBqDAAABAArAGwMAAAGADkAbQwAAAQAFADqDAAABwAhAG4MAAACABsAbwwAAAEAGQAZAAIJehJOOQBvAALqDAAAAQA4AG4MAAABACUAAAA=.Moonwren:BAAALgAECgkJAQAAAA==.Mooradin:BAAALgADCgQJAwAAAA==.Morgrin:BAAALgAECgQJBgAAAA==.Morguen:BAAALgAECgYJCwAAAA==.',
Mu='Mustachiopaw:BAABLgAECn8iAAIcAAgJAhObIQCGAQhoDAAABwBSAGkMAAAGAD8AawwAAAYAMQBqDAAABABbAGwMAAAEAC8AbQwAAAMAJgDqDAAAAwArAG4MAAABAA8AHAAICQITmyEAhgEIaAwAAAcAUgBpDAAABgA/AGsMAAAGADEAagwAAAQAWwBsDAAABAAvAG0MAAADACYA6gwAAAMAKwBuDAAAAQAPAAAA.',
My='Mydira:BAAALgAECgkJDAAAAA==.Mysha:BAAALgAECgMJAwAAAA==.',
['Mò']='Mòomòo:BAAALgAECgEJAQAAAA==.',
Na='Nalth:BAACLgAFFH8GAAINAAMJdQbjSwCKAANoDAAAAgAKAGkMAAACABAA6gwAAAIAFQANAAMJdQbjSwCKAANoDAAAAgAKAGkMAAACABAA6gwAAAIAFQAuAAQKfxkABA0ACQmnGHUVAJsCAA0ACQmnGHUVAJsCACIAAgn4B59sADoAABAAAQmXCumQACwAAAAA.Nalthexon:BAAALgAECgYJBgABLgAFFAMJBgANAHUGAA==.Navysis:BAAALgAECgMJAQAAAA==.Nazra:BAAALgAECgEJAQAAAA==.',
Ne='Negativeone:BAAALgADCgYJAgAAAA==.Neko:BAAALgAFFAEJAQAAAA==.Neverender:BAAALgAECgUJBwAAAA==.Nexxus:BAAALgADCgcJDAAAAA==.Nezan:BAAALgADCgQJBAAAAA==.Nezin:BAAALgADCgUJBQABLgAECgkJGAAbANscAA==.',
Ni='Niavanith:BAAALgAECgYJEgAAAA==.Nights:BAAALgAECgcJEgABLgAFFAMJBgAhAKkSAA==.Nike:BAAALgAECgEJAQAAAA==.Nitwp:BAACLgAFFH8SAAMFAAQJdB3hAgBPAQRoDAAABwBTAGkMAAAFAE8AawwAAAIARQDqDAAABABFAAUABAl0HeECAE8BBGgMAAAGAFMAaQwAAAQATwBrDAAAAQBFAOoMAAADAEUAAwAECa0PejEA+AAEaAwAAAEAQgBpDAAAAQAxAGsMAAABABEA6gwAAAEAGwAuAAQKf0IAAwUACQnUI8YAACgDAAUACQnUI8YAACgDAAQABQnUFb4YAEUBAAAA.Nizo:BAABLgAECn8uAAINAAkJChwvDgDlAgloDAAABQBJAGkMAAAHAFIAawwAAAcAWwBqDAAABgBTAGwMAAAGAEgAbQwAAAMARADqDAAABwBMAG4MAAAEAEsAbwwAAAEAFwANAAkJChwvDgDlAgloDAAABQBJAGkMAAAHAFIAawwAAAcAWwBqDAAABgBTAGwMAAAGAEgAbQwAAAMARADqDAAABwBMAG4MAAAEAEsAbwwAAAEAFwAAAA==.',
No='Noblitz:BAACLgAFFH8HAAMaAAQJXwvNHQD+AARoDAAAAQAoAGkMAAABABgAawwAAAEAEgDqDAAABAAgABoABAlfC80dAP4ABGgMAAABACgAaQwAAAEAGABrDAAAAQASAOoMAAACACAAIwABCTcVODUAOwAB6gwAAAIANgAuAAQKfxsAAxoACQlWGAgQAF0CABoACQlWGAgQAF0CACMABgnWGGgmAI4BAAAA.Novastrike:BAABLgAECn8mAAMLAAgJoheLQgCgAQhoDAAABgBEAGkMAAAGAD0AawwAAAYAQwBqDAAABABGAGwMAAAEADkAbQwAAAMAEQDqDAAABwBcAG4MAAACADAACwAICaIXi0IAoAEIaAwAAAEARABpDAAAAgA9AGsMAAACAEMAagwAAAEARgBsDAAAAgA5AG0MAAACABEA6gwAAAUAXABuDAAAAQAwAAoACAnfC9RZANQACGgMAAAFACsAaQwAAAQAJwBrDAAABAAuAGoMAAADADgAbAwAAAIAEABtDAAAAQAeAOoMAAACABQAbgwAAAEADwAAAA==.',
Ny='Nyrif:BAACLgAFFH8QAAIVAAQJJRtZFgAzAQRoDAAABQBHAGkMAAAFAEsAawwAAAEALQDqDAAABQBWABUABAklG1kWADMBBGgMAAAFAEcAaQwAAAUASwBrDAAAAQAtAOoMAAAFAFYALgAECn8iAAIVAAkJ8xqkEAD/AQAVAAkJ8xqkEAD/AQAAAA==.',
Oj='Ojoon:BAABLgAECn8UAAIBAAcJOgr0rQAiAQdoDAAABAAWAGkMAAAEACoAawwAAAMAEwBqDAAAAwAdAGwMAAABAAsA6gwAAAIAIgBuDAAAAwAaAAEABwk6CvStACIBB2gMAAAEABYAaQwAAAQAKgBrDAAAAwATAGoMAAADAB0AbAwAAAEACwDqDAAAAgAiAG4MAAADABoAAAA=.',
Om='Omnisllash:BAACLgAFFH8GAAIBAAMJ+QlyhgDPAANoDAAAAwAlAGkMAAACABwA6gwAAAEACQABAAMJ+QlyhgDPAANoDAAAAwAlAGkMAAACABwA6gwAAAEACQAuAAQKfxcAAgEACAl0FKVUANwBAAEACAl0FKVUANwBAAAA.',
Or='Orisana:BAACLgAFFH8TAAMhAAQJoxvoDgBKAQRoDAAABgBOAGkMAAAGAFkAawwAAAIAMwDqDAAABQA/ACEABAmjG+gOAEoBBGgMAAAEAE4AaQwAAAQAWQBrDAAAAgAzAOoMAAAFAD8AEQACCTcVuIUAiwACaAwAAAIAPwBpDAAAAgAtAC4ABAp/TgAEIQAJCUIhhgUAzQIAGAAJCcAaeQwA5QIAIQAJCd4fhgUAzQIAEQAFCYwZ3n8APAEAAAA=.',
Pa='Pallamb:BAAALgADCgYJBwAAAA==.Palleberry:BAAALgADCgEJAQAAAA==.Panzerfaust:BAAALgADCgQJBAAAAA==.',
Pe='Penjamin:BAAALgADCgEJAQAAAA==.Petal:BAABLgAFFH8YAAMEAAUJAQydFwAVAQVoDAAABQA7AGkMAAAFAB0AawwAAAUAFABqDAAAAwANAOoMAAAGAB0ABAAFCQEMnRcAFQEFaAwAAAQAOwBpDAAABQAdAGsMAAAFABQAagwAAAMADQDqDAAABgAdAAMAAQmXCLVkADgAAWgMAAABABUAAAA=.Pewpewbang:BAAALgAECgQJBAAAAA==.',
Ph='Phoenìx:BAAALgAECgEJAgAAAA==.Phyter:BAAALgAECgIJBQAAAA==.',
Pi='Pillin:BAABLgAECn8WAAMdAAcJjxcdCQCaAQdoDAAAAgAxAGkMAAACADwAawwAAAQAOABqDAAAAQAmAGwMAAAFAEMA6gwAAAQASABuDAAABAA3AB0ABwlmFx0JAJoBB2gMAAACADEAaQwAAAIAPABrDAAAAwA4AGoMAAABACYAbAwAAAUAQwDqDAAABABIAG4MAAACADUAHAACCUcQoVcARAACawwAAAEAGwBuDAAAAgA3AAAA.Pillroller:BAAALgADCgYJBgAAAA==.',
Po='Pock:BAAALgADCgIJAgAAAA==.Poochew:BAABLgAECn8hAAMkAAkJcB3iFgA3AgloDAAABQBUAGkMAAAHAFcAawwAAAcAUwBqDAAAAgBMAGwMAAACAFYAbQwAAAEANADqDAAABgBTAG4MAAABACwAbwwAAAIAUAAkAAkJcB3iFgA3AgloDAAABQBUAGkMAAAHAFcAawwAAAcAUwBqDAAAAgBMAGwMAAACAFYAbQwAAAEANADqDAAABgBTAG4MAAABACwAbwwAAAEAUAAlAAEJ7AiVUQA0AAFvDAAAAQAWAAAA.Powerwordmoo:BAAALgAECgEJAQABLgAECgkJIAARAKchAA==.',
Pr='Prilo:BAAALgADCgcJBwAAAA==.Prina:BAAALgADCgUJBQAAAA==.Provi:BAAALgAECggJDAAAAA==.',
Ps='Psyffe:BAAALgAECgUJCgAAAA==.Psyrge:BAAALgAECgYJBgAAAA==.',
Qu='Queue:BAABLgAECn86AAIVAAkJcw+jGgCHAQloDAAACQAZAGkMAAAJAC8AawwAAAgAMgBqDAAABgBJAGwMAAAGAEYAbQwAAAIAKADqDAAACQApAG4MAAAHABoAbwwAAAIADgAVAAkJcw+jGgCHAQloDAAACQAZAGkMAAAJAC8AawwAAAgAMgBqDAAABgBJAGwMAAAGAEYAbQwAAAIAKADqDAAACQApAG4MAAAHABoAbwwAAAIADgAAAA==.',
Re='Rebeccayaros:BAAALgAECgUJDwAAAA==.Redle:BAABLgAECn8aAAIMAAgJzQvnnQA5AQhoDAAABQAmAGkMAAAEACgAawwAAAMAIABqDAAAAgATAGwMAAADABIAbQwAAAEABwDqDAAABQAqAG4MAAADACAADAAICc0L550AOQEIaAwAAAUAJgBpDAAABAAoAGsMAAADACAAagwAAAIAEwBsDAAAAwASAG0MAAABAAcA6gwAAAUAKgBuDAAAAwAgAAAA.Rendarc:BAAALgADCgIJAgAAAA==.',
Rh='Rhordric:BAECLgAFFH8TAAQhAAQJKRiODgBMAQRoDAAABwArAGkMAAAFADQAawwAAAIAUgDqDAAABQBDACEABAkpGI4OAEwBBGgMAAAGACsAaQwAAAQANABrDAAAAgBSAOoMAAAFAEMAGAABCbYHECoASAABaAwAAAEAEwARAAEJFAMNqwA8AAFpDAAAAQAHAC4ABAp/NAADIQAJCbEfPwYAvgIAIQAJCU4ePwYAvgIAGAAICRIWAB4ANgIAAAA=.',
Ro='Rokkitok:BAAALgAECgcJEAAAAA==.Ronindots:BAAALgADCgMJAwAAAA==.',
Ru='Rulnic:BAAALgAECgEJAQAAAA==.',
['Rà']='Ràwrshàk:BAAALgAECgYJDQAAAA==.',
['Rå']='Råwrshåk:BAABLgAECn8mAAIRAAkJqBr9KQAzAgloDAAABQBPAGkMAAAGAE4AawwAAAYAVQBqDAAABgBNAGwMAAAGAFoAbQwAAAIASwDqDAAABQBJAG4MAAABAAYAbwwAAAEANwARAAkJqBr9KQAzAgloDAAABQBPAGkMAAAGAE4AawwAAAYAVQBqDAAABgBNAGwMAAAGAFoAbQwAAAIASwDqDAAABQBJAG4MAAABAAYAbwwAAAEANwAAAA==.',
['Rú']='Rúmi:BAAALgAECgUJCgABLgAFFAEJAQAUAAAAAA==.',
Se='Sea:BAACLgAFFH8iAAILAAYJ6h1mCwARAgZoDAAACABjAGkMAAAIADwAawwAAAMAVABqDAAABQAuAGwMAAAEAEYA6gwAAAYAYgALAAYJ6h1mCwARAgZoDAAACABjAGkMAAAIADwAawwAAAMAVABqDAAABQAuAGwMAAAEAEYA6gwAAAYAYgAuAAQKfyMAAgsACQmyIOYBAG4DAAsACQmyIOYBAG4DAAAA.Seniri:BAAALgAECgMJCAAAAA==.',
Sh='Shadowaurora:BAAALgAECgkJDwAAAA==.Shadowrose:BAABLgAECn8xAAMZAAkJahkHDAD1AQloDAAABwBJAGkMAAAHAFAAawwAAAcAOgBqDAAABwBTAGwMAAAGAEMAbQwAAAMAOgDqDAAABwBEAG4MAAAEABEAbwwAAAEAXwAZAAgJuhcHDAD1AQhoDAAABwBJAGkMAAAHAFAAawwAAAcAOgBqDAAABwBTAGwMAAAGAEMAbQwAAAIAOgDqDAAABgBEAG4MAAACABEADQAECYUNGnoAxwAEbQwAAAEADwDqDAAAAQAqAG4MAAACADEAbwwAAAEAHgAAAA==.Shaide:BAAALgADCgIJAgAAAA==.Shaihulud:BAABLgAECn8YAAIHAAkJuBQ3NgAAAgloDAAABAAwAGkMAAAEADUAawwAAAQASABqDAAAAgAvAGwMAAACAFEAbQwAAAIALADqDAAAAwAzAG4MAAACACUAbwwAAAEAIgAHAAkJuBQ3NgAAAgloDAAABAAwAGkMAAAEADUAawwAAAQASABqDAAAAgAvAGwMAAACAFEAbQwAAAIALADqDAAAAwAzAG4MAAACACUAbwwAAAEAIgAAAA==.Shamanic:BAAALgADCgQJBAAAAA==.Shamanistix:BAAALgAECgEJAwAAAA==.Shane:BAAALgADCgcJBwABLgAECgQJBAAUAAAAAA==.Shiemi:BAAALgAECgcJBgAAAA==.Shootingbo:BAAALgAECgEJAQAAAA==.Shunsui:BAACLgAFFH8JAAIHAAQJfAsIXgAIAQRoDAAABAAjAGkMAAACACAAawwAAAEADwDqDAAAAgAhAAcABAl8CwheAAgBBGgMAAAEACMAaQwAAAIAIABrDAAAAQAPAOoMAAACACEALgAECn8uAAMHAAkJXBsfHgBvAgAHAAkJXBsfHgBvAgAIAAEJAAAkbwA3AAAAAA==.',
Si='Silchas:BAAALgAECgcJAQAAAA==.Silentomen:BAAALgADCgkJCQAAAA==.Siley:BAABLgAECn8YAAIbAAkJ2xzDFABrAgloDAAAAwBMAGkMAAAEAEcAawwAAAMAXQBqDAAAAgAtAGwMAAACAFEAbQwAAAEASADqDAAABgBgAG4MAAACAFoAbwwAAAEAJQAbAAkJ2xzDFABrAgloDAAAAwBMAGkMAAAEAEcAawwAAAMAXQBqDAAAAgAtAGwMAAACAFEAbQwAAAEASADqDAAABgBgAG4MAAACAFoAbwwAAAEAJQAAAA==.Sinnister:BAAALgAFFAIJAgAAAA==.Sixsixsicks:BAAALgAECgcJCwAAAA==.Sizurp:BAAALgAECgYJCwAAAA==.',
Sk='Skullmonkêy:BAAALgAFFAMJAwABLgAFFAQJCQAHAHwLAA==.',
Sl='Sleepytree:BAAALgAECgcJDwAAAA==.Slugo:BAAALgADCgcJCAAAAA==.',
Sn='Snail:BAAALgAECgMJAwAAAA==.Sneakytrix:BAABLgAFFH8GAAIcAAEJWxtXOQBVAAFoDAAABgBGABwAAQlbG1c5AFUAAWgMAAAGAEYAAAA=.',
So='Sooner:BAACLgAFFH8SAAMXAAQJMx+MSgBYAQRoDAAABwBaAGkMAAAFAFgAawwAAAEALADqDAAABQBfABcABAkzH4xKAFgBBGgMAAAGAFoAaQwAAAQAWABrDAAAAQAsAOoMAAAEAF8AJgADCV0UyBYAzgADaAwAAAEAJQBpDAAAAQBGAOoMAAABADAALgAECn8ZAAMmAAcJex3xBAD8AQAmAAYJdCDxBAD8AQAXAAUJDBz4ggB8AQAAAA==.Sorcerix:BAAALgADCgQJBAAAAA==.Soror:BAAALgAECgIJAgAAAA==.',
Sq='Squeaky:BAAALgAECgcJEQAAAA==.',
St='Starar:BAAALgADCgkJDwAAAA==.Stickylicky:BAAALgADCgIJAgAAAA==.',
Su='Suina:BAAALgAECgYJEAAAAA==.Sungodess:BAAALgAECgEJAQAAAA==.',
Sy='Syrupp:BAAALgAECgkJDgAAAA==.',
Ta='Tanya:BAAALgAECgYJCgAAAA==.Tayn:BAAALgAECgMJBQAAAA==.',
Te='Tealeaf:BAAALgAECgQJBAAAAA==.Temporary:BAAALgAECgIJAgAAAA==.Tenka:BAAALgADCgMJAwAAAA==.',
Th='Thackery:BAAALgADCgMJBAAAAA==.Theblackdk:BAAALgADCgQJAwAAAA==.',
Ti='Tisiphone:BAAALgADCgYJBgAAAA==.',
To='Tortus:BAAALgAECgEJAQAAAA==.Toxicrumor:BAAALgAFFAMJAwAAAA==.',
Tr='Triplenine:BAAALgAECgIJAgABLgAFFAgJIAABAG4bAA==.',
Ts='Tsavò:BAAALgADCgQJBgAAAA==.Tsavø:BAAALgAECgQJBQAAAA==.',
Tu='Tucktoo:BAAALgAECgYJCQAAAA==.',
Ty='Tyundric:BAAALgADCgYJCgAAAA==.',
Un='Unholysage:BAACLgAFFH8RAAMaAAQJvw8iGwAPAQRoDAAABgA9AGkMAAAFACEAawwAAAIAHwDqDAAABAAiABoABAm/DyIbAA8BBGgMAAAGAD0AaQwAAAMAIQBrDAAAAgAfAOoMAAABACIAFgACCUQFVkEAbwACaQwAAAIACQDqDAAAAwARAC4ABAp/LwADGgAJCeYWAhYAGwIAGgAJCeYWAhYAGwIAFgAECUgILlAAwAAAAAA=.',
Uw='Uwurailme:BAABLgAECn8VAAQIAAcJNg8KMgDwAAdoDAAABQAZAGkMAAADADEAawwAAAMAMABqDAAAAgAfAGwMAAADADoAbQwAAAEACQDqDAAABAApAAcABglxDGuLAEIBBmgMAAADABkAaQwAAAEAMQBqDAAAAQAfAGwMAAACACYAbQwAAAEACQDqDAAAAgAkAAgABQkcCgoyAPAABWgMAAACABMAaQwAAAIAEgBrDAAAAwAwAGoMAAABABIA6gwAAAEAEAAGAAIJrRN5HQCGAAJsDAAAAQA6AOoMAAABACkAAAA=.',
Va='Valenix:BAACLgAFFH8OAAMfAAQJuwYcJgC2AARoDAAABAAiAGkMAAAFAAgAawwAAAEABQDqDAAABAAUAB8ABAm7BhwmALYABGgMAAABACIAaQwAAAIACABrDAAAAQAFAOoMAAABABQAHgADCUsK7kQAiAADaAwAAAMAIQBpDAAAAwAQAOoMAAADAB0ALgAECn8fAAMfAAkJZhDKQQD2AAAfAAcJQxDKQQD2AAAeAAgJ6xHhbADKAAAAAA==.Valkryi:BAAALgAECgEJAQAAAA==.Varys:BAAALgADCgMJAwAAAA==.Vaxis:BAAALgADCgcJDgAAAA==.Vaxîs:BAAALgAECgMJAwAAAA==.',
Ve='Velagosa:BAAALgADCgMJAwAAAA==.Venetrazat:BAAALgAECgUJBgAAAA==.',
Vo='Vo:BAAALgAECgYJEgAAAA==.',
Vu='Vulasity:BAAALgAECgcJBwAAAA==.',
Wa='Warder:BAABLgAECn8cAAIkAAgJABeWIgDeAQhoDAAABAAxAGkMAAAEAEgAawwAAAQAOwBqDAAABABNAGwMAAADADQA6gwAAAYATQBuDAAAAgA3AG8MAAABACwAJAAICQAXliIA3gEIaAwAAAQAMQBpDAAABABIAGsMAAAEADsAagwAAAQATQBsDAAAAwA0AOoMAAAGAE0AbgwAAAIANwBvDAAAAQAsAAAA.Warp:BAAALgAECgcJEwAAAA==.',
Wh='Whiteshaq:BAAALgAECgYJCwAAAA==.Whiteypingus:BAAALgADCgYJBgAAAA==.',
Wi='Wiigo:BAAALgAFFAIJAwAAAA==.Wincks:BAABLgAECn8ZAAMIAAcJsRyfDABzAQdoDAAABgBbAGkMAAAEAEsAawwAAAQASwBqDAAAAgBKAGwMAAACAFQAbQwAAAEAMQDqDAAABgBBAAgABgkgHp8MAHMBBmgMAAADAFsAaQwAAAIASwBrDAAABABLAGoMAAACAEoAbAwAAAEAVADqDAAAAgA7AAcABQk1Fjh8AEABBWgMAAADADMAaQwAAAIANQBsDAAAAQBAAG0MAAABADEA6gwAAAQAQQAAAA==.',
Xa='Xana:BAAALgADCgUJBQABLgAFFAQJBwAaAF8LAA==.',
Xe='Xenosaga:BAAALgAECgIJAgAAAA==.',
Ya='Yaltar:BAAALgAECgUJCgAAAA==.',
Za='Zachthemage:BAABLgAECn8nAAICAAkJjxVvAgAuAgloDAAABgBCAGkMAAAGAEUAawwAAAcARgBqDAAABAA/AGwMAAAEAEYAbQwAAAMALgDqDAAABwBKAG4MAAABABIAbwwAAAEAGQACAAkJjxVvAgAuAgloDAAABgBCAGkMAAAGAEUAawwAAAcARgBqDAAABAA/AGwMAAAEAEYAbQwAAAMALgDqDAAABwBKAG4MAAABABIAbwwAAAEAGQAAAA==.Zackman:BAACLgAFFH8TAAIbAAQJRwfILADEAARoDAAACAAEAGkMAAAFACgAawwAAAIACADqDAAABAAUABsABAlHB8gsAMQABGgMAAAIAAQAaQwAAAUAKABrDAAAAgAIAOoMAAAEABQALgAECn9DAAIbAAkJGBNwGQA6AgAbAAkJGBNwGQA6AgAAAA==.',
Zh='Zhimer:BAAALgADCgIJAgAAAA==.',
Zi='Zinagos:BAAALgAFFAIJAgABLgAFFAQJDgAfALsGAA==.',
Zo='Zolttor:BAAALgAECgYJCQAAAA==.Zombie:BAAALgAFFAIJAgAAAA==.Zosos:BAAALgAECgEJAgAAAA==.',
Zu='Zulrea:BAAALgAECgcJCgAAAA==.Zuri:BAAALgAECgUJCgAAAA==.Zushi:BAAALgADCgYJCwAAAA==.',
['Ùn']='Ùncleíroh:BAAALgADCgcJBwABLgAFFAEJAQAUAAAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
