local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Druid-Balance','Hunter-BeastMastery','DeathKnight-Unholy','Druid-Restoration','Unknown-Unknown','Rogue-Outlaw','Monk-Windwalker','Monk-Mistweaver','Monk-Brewmaster','Paladin-Retribution','Shaman-Restoration','Shaman-Enhancement','Paladin-Holy','Warlock-Demonology','Warlock-Destruction','Hunter-Survival','Rogue-Assassination','Mage-Frost','Mage-Arcane','Mage-Fire','DemonHunter-Havoc','DeathKnight-Blood','Priest-Holy','Priest-Shadow','Evoker-Preservation','DemonHunter-Devourer','Shaman-Elemental','Warrior-Protection','Warlock-Affliction','Hunter-Marksmanship','Evoker-Devastation','Evoker-Augmentation','Druid-Feral','Rogue-Subtlety','Druid-Guardian','Paladin-Protection','Priest-Discipline','Warrior-Fury','Warrior-Arms',}
local provider = {region='US',realm='Maiev',name='US',type='daily',zone=46,date='2026-05-14',data={Aa='Aaurum:BAEALgAECgYJBgABLgAFFAYJEQABAF0iAA==.',
Ab='Abadizzo:BAAALgAECgcJBwAAAA==.Abadizzoo:BAABLgAECn8qAAICAAkJuCHtBQDxAgloDAAABQBbAGkMAAAFAF4AawwAAAUAXwBqDAAABQBGAGwMAAAFAFgAbQwAAAUAVQDqDAAABgBOAG4MAAADAFMAbwwAAAMASQACAAkJuCHtBQDxAgloDAAABQBbAGkMAAAFAF4AawwAAAUAXwBqDAAABQBGAGwMAAAFAFgAbQwAAAUAVQDqDAAABgBOAG4MAAADAFMAbwwAAAMASQAAAA==.Abilities:BAAALgAECgUJBgAAAA==.',
Ac='Ace:BAAALgAECgQJBgAAAA==.',
Ae='Aeon:BAAALgAECgYJEgAAAA==.',
Ag='Agathe:BAAALgAECgYJEQABLgAECggJHAADALsPAA==.Agilio:BAABLgAECn8pAAIEAAkJDST8AwBDAwloDAAABgBdAGkMAAAGAFwAawwAAAYAXwBqDAAABgBiAGwMAAAFAGIAbQwAAAIAUADqDAAABQBfAG4MAAAEAGEAbwwAAAEATgAEAAkJDST8AwBDAwloDAAABgBdAGkMAAAGAFwAawwAAAYAXwBqDAAABgBiAGwMAAAFAGIAbQwAAAIAUADqDAAABQBfAG4MAAAEAGEAbwwAAAEATgAAAA==.',
Ah='Ahkimbo:BAAALgAECgIJAgAAAA==.',
Ai='Airhorns:BAAALgAECgQJAQAAAA==.Airwrecka:BAACLgAFFH8FAAIBAAMJFRSaGwDnAANoDAAAAgBJAGkMAAABABIA6gwAAAIAPQABAAMJFRSaGwDnAANoDAAAAgBJAGkMAAABABIA6gwAAAIAPQAuAAQKfzEAAgEACQnEHlgFALYCAAEACQnEHlgFALYCAAAA.Airyxana:BAAALgADCgEJAQABLgAECgUJBQAFAAAAAA==.',
Al='Alexian:BAABLgAECn8XAAIGAAYJnBKTCAAvAQZoDAAABQApAGkMAAAFAC8AawwAAAUARgBqDAAAAgBQAGwMAAACACsA6gwAAAQAIwAGAAYJnBKTCAAvAQZoDAAABQApAGkMAAAFAC8AawwAAAUARgBqDAAAAgBQAGwMAAACACsA6gwAAAQAIwAAAA==.Alorin:BAAALgADCgcJCAAAAA==.Altlas:BAAALgAECgYJEAAAAA==.',
Am='Amebeliever:BAABLgAECn8fAAQHAAgJiB8ZFQBDAghoDAAABgBWAGkMAAAFAFEAawwAAAQARwBqDAAABABXAGwMAAACAFgAbQwAAAEAXQDqDAAABwBZAG4MAAACADYABwAHCbgeGRUAQwIHaAwAAAQAVgBpDAAAAgBRAGsMAAABAEcAagwAAAEAVwBsDAAAAQBYAOoMAAAFAFkAbgwAAAIANgAIAAcJAgi/NwAMAQdoDAAAAQAIAGkMAAACACEAawwAAAIAIABqDAAAAgAXAGwMAAABAAoAbQwAAAEACADqDAAAAgAaAAkABAn+CYFMAIUABGgMAAABABUAaQwAAAEAFABrDAAAAQAiAGoMAAABACgAAAA=.',
An='Andari:BAAALgAECgYJDAAAAA==.Anywhere:BAAALgADCgQJBAAAAA==.',
Ar='Arahgon:BAABLgAECn8UAAIKAAcJLRQ+ZwA/AQdoDAAABQArAGkMAAAEAD8AawwAAAMAPABqDAAAAgA2AGwMAAACAEkAbQwAAAEAKQDqDAAAAwAbAAoABwktFD5nAD8BB2gMAAAFACsAaQwAAAQAPwBrDAAAAwA8AGoMAAACADYAbAwAAAIASQBtDAAAAQApAOoMAAADABsAAS4ABAoFCQMABQAAAAA=.Arixana:BAAALgAECgUJBQAAAA==.Aryxana:BAAALgADCgEJAQABLgAECgUJBQAFAAAAAA==.',
As='Asher:BAAALgAECgQJBAAAAA==.Asphodelos:BAAALgAECgYJBgABLgAECggJIAADAJUhAA==.Asukà:BAABLgAECn8kAAMLAAgJxhTZGgAIAghoDAAABgBSAGkMAAAGAEMAawwAAAYATwBqDAAABAA6AGwMAAAEABEAbQwAAAIAIADqDAAABQAgAG4MAAADADcACwAICcYU2RoACAIIaAwAAAMAUgBpDAAAAwBDAGsMAAADAE8AagwAAAIAOgBsDAAAAgARAG0MAAACACAA6gwAAAIAIABuDAAAAwA3AAwABgnsCh4XAE8BBmgMAAADACMAaQwAAAMAIwBrDAAAAwAcAGoMAAACABcAbAwAAAIAGADqDAAAAwAPAAAA.',
At='Attero:BAAALgAECgEJAQAAAA==.',
Au='Auchenile:BAAALgADCgYJBgABLgAECgYJFgANAB0jAA==.',
Av='Aveliese:BAAALgAECgYJDgAAAA==.',
Aw='Awilix:BAAALgAECgcJCgAAAA==.',
['Aé']='Aéd:BAAALgADCgEJAQABLgAECgUJDwAFAAAAAA==.',
Be='Beans:BAAALgAECgEJAQAAAA==.Bearhugzz:BAAALgAECgcJEwABLgAFFAIJAgAFAAAAAA==.Bellarg:BAABLgAECn8yAAMOAAcJfRpnLwDGAQdoDAAACQA+AGkMAAAJAEUAawwAAAkASwBqDAAABwBXAGwMAAAGAFAA6gwAAAkATABuDAAAAQArAA4ABwl9GmcvAMYBB2gMAAAJAD4AaQwAAAkARQBrDAAABABLAGoMAAAFAFcAbAwAAAUAUADqDAAACQBMAG4MAAABACsADwADCd8HrUgAlAADawwAAAUAHwBqDAAAAgAaAGwMAAABAAgAAAA=.Belobog:BAAALgAECgUJCAABLgAECggJHAADALsPAA==.Belyn:BAAALgAECgUJCwAAAA==.Benmage:BAAALgAECgEJAQAAAA==.Benzo:BAAALgAECgUJDAAAAA==.Beoworgen:BAAALgADCgIJAgAAAA==.',
Bi='Bifesor:BAAALgAECgYJCQAAAA==.Bigfaust:BAABLgAECn8YAAQJAAcJph+sHQBoAQdoDAAABQA3AGkMAAAFAF0AawwAAAQAUwBqDAAAAgBcAGwMAAACAFAAbQwAAAEAUQDqDAAABQBbAAkABQmnH6wdAGgBBWgMAAACADcAaQwAAAIAXQBrDAAAAgBTAGoMAAABAEwA6gwAAAMAWwAIAAUJARu/LgBDAQVoDAAAAwBDAGkMAAADADMAawwAAAIAWABtDAAAAQA7AOoMAAACAE0ABwACCUUfCFMAxQACagwAAAEAXABsDAAAAgBQAAAA.',
Bl='Blackbudro:BAABLgAECn8oAAIQAAkJzRWNCABEAgloDAAABwBMAGkMAAAGAD0AawwAAAcAVABqDAAABQBSAGwMAAAEAC0AbQwAAAEAIgDqDAAABgBEAG4MAAADAB8AbwwAAAEALAAQAAkJzRWNCABEAgloDAAABwBMAGkMAAAGAD0AawwAAAcAVABqDAAABQBSAGwMAAAEAC0AbQwAAAEAIgDqDAAABgBEAG4MAAADAB8AbwwAAAEALAAAAA==.Blocka:BAAALgADCgIJAgAAAA==.Bloodadinz:BAAALgAECgcJEgAAAA==.Bluespider:BAAALgAECgIJBAAAAA==.',
Bo='Bonedaddy:BAAALgADCgMJAwAAAA==.',
Br='Bratlax:BAAALgAECgcJEgABLgAFFAYJDQAEADIWAA==.Brawnie:BAAALgAECgYJBgAAAA==.Bro:BAAALgAECgQJBwAAAA==.Brokai:BAAALgAECgEJAQABLgAECgQJBwAFAAAAAA==.Brolich:BAAALgAECgcJDgABLgAECgQJBwAFAAAAAA==.',
Bu='Bumpus:BAAALgAECgIJAgAAAA==.',
Ca='Caarcus:BAAALgAECgcJDAAAAA==.Calculusx:BAABLgAECn8tAAIRAAkJUiNqAAA5AwloDAAACABhAGkMAAAIAF8AawwAAAYAXwBqDAAABABdAGwMAAAFAFYAbQwAAAQAXADqDAAABgBhAG4MAAADAE8AbwwAAAEATgARAAkJUiNqAAA5AwloDAAACABhAGkMAAAIAF8AawwAAAYAXwBqDAAABABdAGwMAAAFAFYAbQwAAAQAXADqDAAABgBhAG4MAAADAE8AbwwAAAEATgAAAA==.Cass:BAAALgAECgMJAwAAAA==.',
Ce='Cellice:BAACLgAFFH8cAAMSAAYJURpBBAAtAgZoDAAABgBTAGkMAAAEAEkAawwAAAUAPQBqDAAABQBaAGwMAAABACkA6gwAAAcATAASAAYJBRpBBAAtAgZoDAAABQBPAGkMAAADAEkAawwAAAUAPQBqDAAABQBaAGwMAAABACkA6gwAAAcATAATAAIJmRtQAQC1AAJoDAAAAQBTAGkMAAABADkALgAECn82AAQSAAkJKyYLBQCxAwASAAkJ+yULBQCxAwAUAAgJEiLhAgAFAgATAAMJvyJmCADFAAAAAA==.',
Ch='Champu:BAAALgADCgEJAQAAAA==.Charlotte:BAAALgAECgcJDgAAAA==.Cheatus:BAAALgADCgMJAwAAAA==.Checkursix:BAAALgAECgcJBgAAAA==.Chipcoffey:BAAALgADCgEJAQAAAA==.Chris:BAAALgAECgQJBAAAAA==.Chuckborris:BAABLgAECn8kAAIJAAgJPB7xCABeAghoDAAABgA+AGkMAAAFAFEAawwAAAUASQBqDAAABgBXAGwMAAAFAFgAbQwAAAIAUADqDAAABABNAG4MAAADAE4ACQAICTwe8QgAXgIIaAwAAAYAPgBpDAAABQBRAGsMAAAFAEkAagwAAAYAVwBsDAAABQBYAG0MAAACAFAA6gwAAAQATQBuDAAAAwBOAAEuAAUUAgkCAAUAAAAA.Chuttbeeks:BAAALgAECgIJBAABLgAECgYJCwAFAAAAAA==.',
Cl='Claytnbigsby:BAAALgADCgMJAwAAAA==.Cloúd:BAAALgAECgUJDAAAAA==.',
Co='Coleco:BAABLgAECn8XAAIDAAgJ1BgTSQAYAghoDAAABABKAGkMAAADADwAawwAAAMAPQBqDAAAAwAvAGwMAAADAEQAbQwAAAIAOwDqDAAAAwBZAG4MAAACAB8AAwAICdQYE0kAGAIIaAwAAAQASgBpDAAAAwA8AGsMAAADAD0AagwAAAMALwBsDAAAAwBEAG0MAAACADsA6gwAAAMAWQBuDAAAAgAfAAEuAAQKCQkJAAUAAAAA.Combatboots:BAABLgAECn8mAAIVAAgJywtPFwBPAQhoDAAABgAiAGkMAAAGACoAawwAAAYAHQBqDAAABQAmAGwMAAAFABkAbQwAAAIADQDqDAAABgAYAG4MAAACACkAFQAICcsLTxcATwEIaAwAAAYAIgBpDAAABgAqAGsMAAAGAB0AagwAAAUAJgBsDAAABQAZAG0MAAACAA0A6gwAAAYAGABuDAAAAgApAAAA.',
Cr='Crosshairs:BAAALgAECgEJAQAAAA==.',
Da='Daddydimes:BAABLgAECn8aAAMJAAYJ2Rs0LwCaAQZoDAAABQBLAGkMAAAEAFMAawwAAAQATABqDAAABABSAGwMAAADADYA6gwAAAYAQQAJAAUJGhw0LwCaAQVoDAAAAgA+AGkMAAACAFMAawwAAAIATABqDAAAAQBSAOoMAAACAEEABwAGCbEUoTcAQAEGaAwAAAMASwBpDAAAAgBPAGsMAAACAAcAagwAAAMALgBsDAAAAwA2AOoMAAAEAC8AAAA=.',
De='Deamonprince:BAAALgADCgkJFQAAAA==.Deathless:BAABLgAECn8jAAIWAAcJECNCBwBQAgdoDAAABgBaAGkMAAAGAFwAawwAAAYAWQBqDAAABABUAGwMAAAEAFoA6gwAAAUAXABuDAAABABTABYABwkQI0IHAFACB2gMAAAGAFoAaQwAAAYAXABrDAAABgBZAGoMAAAEAFQAbAwAAAQAWgDqDAAABQBcAG4MAAAEAFMAAAA=.Debra:BAACLgAFFH8FAAIVAAMJlAuvDQDZAANoDAAAAgApAGkMAAABAAoA6gwAAAIAJQAVAAMJlAuvDQDZAANoDAAAAgApAGkMAAABAAoA6gwAAAIAJQAuAAQKfy0AAhUACQnCG10HAFMCABUACQnCG10HAFMCAAAA.Debz:BAAALgAECgcJCAAAAA==.Deegee:BAABLgAECn8WAAMXAAYJgSFiDwAYAgZoDAAABABbAGkMAAAEAF0AawwAAAQARQBqDAAAAwBYAGwMAAADAFAA6gwAAAQAWwAXAAYJgSFiDwAYAgZoDAAAAgBbAGkMAAACAF0AawwAAAIARQBqDAAAAgBYAGwMAAACAFAA6gwAAAIAWwAYAAYJvBjTJgChAQZoDAAAAgA3AGkMAAACAD4AawwAAAIAPABqDAAAAQA0AGwMAAABAEkA6gwAAAIAQAAAAA==.Deliveryboy:BAAALgAECgEJAQAAAA==.Delphist:BAAALgAECgEJAQAAAA==.Demiize:BAAALgAECgEJAQAAAA==.Demize:BAAALgAECgQJBAAAAA==.Demonflame:BAABLgAECn8hAAIPAAkJuBU+AwAYAgloDAAAAwBLAGkMAAADAEIAawwAAAUAOwBqDAAABAArAGwMAAAEAEQAbQwAAAMAFwDqDAAABgBDAG4MAAADAC8AbwwAAAIAIwAPAAkJuBU+AwAYAgloDAAAAwBLAGkMAAADAEIAawwAAAUAOwBqDAAABAArAGwMAAAEAEQAbQwAAAMAFwDqDAAABgBDAG4MAAADAC8AbwwAAAIAIwAAAA==.Deshield:BAAALgADCgQJBAABLgAFFAQJEgALAGslAA==.Deus:BAABLgAECn8ZAAISAAgJKRKuWACAAQhoDAAABAAwAGkMAAAEADcAawwAAAMAMQBqDAAAAwAgAGwMAAADADIAbQwAAAEAJwDqDAAABQA4AG4MAAACABgAEgAICSkSrlgAgAEIaAwAAAQAMABpDAAABAA3AGsMAAADADEAagwAAAMAIABsDAAAAwAyAG0MAAABACcA6gwAAAUAOABuDAAAAgAYAAAA.Dewry:BAAALgAECgYJDQAAAA==.',
Dh='Dhudamuthi:BAABLgAECn8qAAIJAAkJciTNAQAhAwloDAAABwBiAGkMAAAHAGEAawwAAAYAYQBqDAAABQBcAGwMAAAEAF4AbQwAAAMAVQDqDAAABgBbAG4MAAADAGAAbwwAAAEAVQAJAAkJciTNAQAhAwloDAAABwBiAGkMAAAHAGEAawwAAAYAYQBqDAAABQBcAGwMAAAEAF4AbQwAAAMAVQDqDAAABgBbAG4MAAADAGAAbwwAAAEAVQAAAA==.',
Di='Dimes:BAAALgAECgIJAgAAAA==.Direwoof:BAAALgAECgYJDAAAAA==.Dizzo:BAAALgAECgkJAQAAAA==.',
Do='Donnajuan:BAABLgAECn8nAAINAAgJthleEAA9AghoDAAABwBaAGkMAAAGAD8AawwAAAUAUwBqDAAABQBDAGwMAAAFAFIAbQwAAAMAMgDqDAAABgA6AG4MAAACAB8ADQAICbYZXhAAPQIIaAwAAAcAWgBpDAAABgA/AGsMAAAFAFMAagwAAAUAQwBsDAAABQBSAG0MAAADADIA6gwAAAYAOgBuDAAAAgAfAAAA.Dornath:BAABLgAECn8lAAIKAAcJyA3xZgBAAQdoDAAABwAtAGkMAAAHAEgAawwAAAcAKABqDAAABQAyAGwMAAAFABQAbQwAAAEACwDqDAAABQAWAAoABwnIDfFmAEABB2gMAAAHAC0AaQwAAAcASABrDAAABwAoAGoMAAAFADIAbAwAAAUAFABtDAAAAQALAOoMAAAFABYAAAA=.',
Dr='Draaxelro:BAABLgAECn8ZAAICAAgJVhLoQgBqAQhoDAAAAwAsAGkMAAADACwAawwAAAMAOwBqDAAAAwAqAGwMAAADAD8AbQwAAAEADwDqDAAABgAyAG4MAAADADMAAgAICVYS6EIAagEIaAwAAAMALABpDAAAAwAsAGsMAAADADsAagwAAAMAKgBsDAAAAwA/AG0MAAABAA8A6gwAAAYAMgBuDAAAAwAzAAAA.Dragonboufas:BAAALgADCgYJBgABLgAFFAQJEgALAGslAA==.Dragontiddys:BAABLgAECn8ZAAIZAAgJjB3WBQBaAghoDAAAAwAyAGkMAAADAFIAawwAAAMATABqDAAAAgBDAGwMAAADAE4AbQwAAAIAUADqDAAABQBeAG4MAAAEAEsAGQAICYwd1gUAWgIIaAwAAAMAMgBpDAAAAwBSAGsMAAADAEwAagwAAAIAQwBsDAAAAwBOAG0MAAACAFAA6gwAAAUAXgBuDAAABABLAAAA.Drew:BAEALgADCgUJBQABLgAECgYJCgAFAAAAAA==.',
Du='Durge:BAAALgAECgEJAQAAAA==.',
El='Eldread:BAAALgADCgEJAQAAAA==.Elias:BAAALgADCgQJBAAAAA==.Elimere:BAABLgAECn8mAAIYAAkJzQluHgBvAQloDAAABgAXAGkMAAAGABUAawwAAAYAJwBqDAAABQArAGwMAAAFACYAbQwAAAIAEgDqDAAABAAXAG4MAAADABkAbwwAAAEACAAYAAkJzQluHgBvAQloDAAABgAXAGkMAAAGABUAawwAAAYAJwBqDAAABQArAGwMAAAFACYAbQwAAAIAEgDqDAAABAAXAG4MAAADABkAbwwAAAEACAAAAA==.Elinalise:BAAALgAFFAEJAgABLgAFFAYJGAAaAIwNAA==.Elminstér:BAAALgAECgQJCQAAAA==.Elvarg:BAAALgADCgEJAQAAAA==.Elywen:BAACLgAFFH8FAAICAAIJkRNYIQBeAAJoDAAABABPAGkMAAABABUAAgACCZETWCEAXgACaAwAAAQATwBpDAAAAQAVAC4ABAp/LgACAgAICSQgxA4AxQIAAgAICSQgxA4AxQIAAAA=.',
Em='Embertal:BAAALgAECgYJCgAAAA==.Emvoi:BAAALgADCgUJBQAAAA==.',
En='Ena:BAAALgADCgYJBgAAAA==.Enfuegó:BAAALgAECggJDgAAAA==.Enry:BAAALgAECgYJDgAAAA==.Enshaendor:BAAALgAECgYJCQAAAA==.Enzo:BAAALgAECgEJAQAAAA==.',
Ev='Evién:BAABLgAECn8UAAMbAAYJNxZEOQBrAQZoDAAABQA7AGkMAAAEAC0AawwAAAQANwBqDAAAAgAxAGwMAAABADUA6gwAAAQARQAbAAYJNxZEOQBrAQZoDAAABAA7AGkMAAADAC0AawwAAAMANwBqDAAAAQAxAGwMAAABADUA6gwAAAMARQALAAUJthF4VgDcAAVoDAAAAQArAGkMAAABACMAawwAAAEAQABqDAAAAQARAOoMAAABAEEAAAA=.Evve:BAAALgADCgIJAgAAAA==.',
Ex='Executè:BAAALgAECgEJAQABLgAECggJGAAVAD8jAA==.',
Fa='Fanforlife:BAAALgADCgcJDQAAAA==.',
Fe='Felgus:BAAALgADCgYJBgAAAA==.Feyre:BAABLgAECn8mAAIKAAYJgwiykgDsAAZoDAAACAASAGkMAAAHABwAawwAAAcAGABqDAAABQAfAGwMAAAEAA8A6gwAAAcAFQAKAAYJgwiykgDsAAZoDAAACAASAGkMAAAHABwAawwAAAcAGABqDAAABQAfAGwMAAAEAA8A6gwAAAcAFQAAAA==.',
Fi='Fiammetta:BAECLgAFFH8HAAIcAAQJpR3bBgD4AARoDAAAAgBbAGkMAAABAEQAawwAAAEARADqDAAAAwBMABwABAmlHdsGAPgABGgMAAACAFsAaQwAAAEARABrDAAAAQBEAOoMAAADAEwALgAECn8YAAIcAAkJZyPnBgBEAgAcAAkJZyPnBgBEAgABLgAFFAYJFAAJAEkhAA==.Fiddlesticks:BAAALgAECgYJDgABLgAECgcJDAAFAAAAAA==.Finke:BAABLgAECn8bAAISAAcJZhzrZwAHAgdoDAAABwBXAGkMAAAEAEwAawwAAAMAQwBqDAAABABfAGwMAAACAFkAbQwAAAEAIQDqDAAABgBSABIABwlmHOtnAAcCB2gMAAAHAFcAaQwAAAQATABrDAAAAwBDAGoMAAAEAF8AbAwAAAIAWQBtDAAAAQAhAOoMAAAGAFIAAAA=.Fishmärket:BAABLgAECn8eAAIMAAkJeQuxCQCnAQloDAAABAAkAGkMAAAEABwAawwAAAQALgBqDAAABQA5AGwMAAAFADMAbQwAAAEAEADqDAAABAAYAG4MAAACABMAbwwAAAEACgAMAAkJeQuxCQCnAQloDAAABAAkAGkMAAAEABwAawwAAAQALgBqDAAABQA5AGwMAAAFADMAbQwAAAEAEADqDAAABAAYAG4MAAACABMAbwwAAAEACgAAAA==.',
Fl='Flickerbeat:BAAALgAECgUJBAAAAA==.',
Fo='Forestclaw:BAAALgADCgMJBAAAAA==.',
Fr='Freakbeast:BAAALgAECgEJAgAAAA==.Frostie:BAAALgAFFAIJAgABLgAFFAQJBwANAI4PAA==.Frís:BAAALgAECggJEwABLgAFFAMJAwAFAAAAAA==.',
Fu='Furryfist:BAAALgADCgcJBwAAAA==.',
Ga='Galarine:BAABLgAECn8lAAIOAAkJcBeKGgA1AgloDAAABgBPAGkMAAAGADcAawwAAAYAQQBqDAAABAAzAGwMAAAFAEQAbQwAAAIAPgDqDAAABAA/AG4MAAADADEAbwwAAAEAIgAOAAkJcBeKGgA1AgloDAAABgBPAGkMAAAGADcAawwAAAYAQQBqDAAABAAzAGwMAAAFAEQAbQwAAAIAPgDqDAAABAA/AG4MAAADADEAbwwAAAEAIgAAAA==.Galas:BAAALgADCgEJAQAAAA==.',
Gi='Gigazapper:BAAALgADCgcJCAABLgAFFAIJAgAFAAAAAA==.Gilrathor:BAAALgAECgcJCgAAAA==.Gizzlit:BAABLgAECn8eAAIMAAgJ2hrhBQATAghoDAAABgBUAGkMAAAFAEoAawwAAAUAQgBqDAAABABIAGwMAAADAEwAbQwAAAEAHwDqDAAABQBIAG4MAAABAEsADAAICdoa4QUAEwIIaAwAAAYAVABpDAAABQBKAGsMAAAFAEIAagwAAAQASABsDAAAAwBMAG0MAAABAB8A6gwAAAUASABuDAAAAQBLAAAA.',
Gl='Glovez:BAAALgAECgMJAwAAAA==.',
Go='Gobiasinds:BAAALgAECgEJAQAAAA==.Gofetch:BAABLgAECn8hAAICAAkJrxvDEgBkAgloDAAABgBVAGkMAAAEAEsAawwAAAUAUwBqDAAABAAjAGwMAAAEACkAbQwAAAMAUgDqDAAABABUAG4MAAACAC8AbwwAAAEAQQACAAkJrxvDEgBkAgloDAAABgBVAGkMAAAEAEsAawwAAAUAUwBqDAAABAAjAGwMAAAEACkAbQwAAAMAUgDqDAAABABUAG4MAAACAC8AbwwAAAEAQQAAAA==.Golffwangg:BAAALgADCgUJBQAAAA==.Goomei:BAAALgADCgcJDwAAAA==.Goopzy:BAAALgAECgIJAgABLgAECgUJDAAFAAAAAA==.',
Gr='Grandwiz:BAAALgAECgMJBQAAAA==.Grissum:BAABLgAECn8jAAMCAAcJgh4BIAAFAgdoDAAABwA/AGkMAAAGAFcAawwAAAYAUgBqDAAABQBQAGwMAAAEAEkA6gwAAAYAWABuDAAAAQBJAAIABwmCHgEgAAUCB2gMAAAEAD8AaQwAAAQAVwBrDAAABABSAGoMAAAFAFAAbAwAAAMASQDqDAAABABYAG4MAAABAEkAEAAFCfoS+RgAPwEFaAwAAAMALwBpDAAAAgA8AGsMAAACADYAbAwAAAEAHADqDAAAAgA0AAAA.',
Gu='Gutcassidy:BAAALgADCgkJCQAAAA==.',
Ha='Hac:BAAALgAECgcJDQAAAA==.Hackacracka:BAAALgAECgYJDgABLgAECgcJDQAFAAAAAA==.Halotwo:BAAALgAECgYJCQAAAA==.Harold:BAAALgAECgYJCQAAAA==.Harper:BAAALgAECgYJBgAAAA==.Harpull:BAAALgADCgYJEAABLgAECgYJBgAFAAAAAA==.Harpö:BAAALgAECgEJAQABLgAECgYJBgAFAAAAAA==.',
He='Healingkiss:BAABLgAECn8XAAIXAAYJ8AG2OwCoAAZoDAAABAAIAGkMAAAEAAQAawwAAAQABABqDAAABQAEAGwMAAADAAQA6gwAAAMAAgAXAAYJ8AG2OwCoAAZoDAAABAAIAGkMAAAEAAQAawwAAAQABABqDAAABQAEAGwMAAADAAQA6gwAAAMAAgAAAA==.Heatup:BAABLgAECn8aAAISAAgJfiMzFQApAwhoDAAABABfAGkMAAAEAFgAawwAAAQAVwBqDAAAAgBZAGwMAAACAFsAbQwAAAIAYADqDAAABQBZAG4MAAADAFgAEgAICX4jMxUAKQMIaAwAAAQAXwBpDAAABABYAGsMAAAEAFcAagwAAAIAWQBsDAAAAgBbAG0MAAACAGAA6gwAAAUAWQBuDAAAAwBYAAAA.Helper:BAAALgAECgcJEgAAAA==.',
Ho='Holymages:BAABLgAECn8fAAISAAcJ6hujRgCzAQdoDAAABgBLAGkMAAAGAEUAawwAAAUAUQBqDAAABQBHAGwMAAAEAE0A6gwAAAQAPwBuDAAAAQA9ABIABwnqG6NGALMBB2gMAAAGAEsAaQwAAAYARQBrDAAABQBRAGoMAAAFAEcAbAwAAAQATQDqDAAABAA/AG4MAAABAD0AAAA=.Homtardy:BAAALgAECgYJBwAAAA==.',
Hu='Huhknee:BAAALgADCgEJAQAAAA==.',
Il='Ilyanna:BAABLgAECn8bAAMdAAkJoRz7AgAfAgloDAAABABMAGkMAAAEAEYAawwAAAQASQBqDAAAAwBCAGwMAAADAFIAbQwAAAIARwDqDAAAAwBQAG4MAAADAEAAbwwAAAEAQwAdAAkJoRz7AgAfAgloDAAABABMAGkMAAAEAEYAawwAAAQASQBqDAAAAwBCAGwMAAADAFIAbQwAAAEARwDqDAAAAwBQAG4MAAADAEAAbwwAAAEAQwAOAAEJXxDXCwFFAAFtDAAAAQApAAAA.',
Im='Im:BAACLgAFFH8YAAQQAAcJvRYNAwCYAQdoDAAABgBbAGkMAAAEAFAAawwAAAMAJgBqDAAAAwAwAGwMAAACABAAbQwAAAEAKwDqDAAABQBOAB4ABgkBGooGALcBBmgMAAAEAFsAaQwAAAIAUABrDAAAAgAmAGoMAAACADAAbQwAAAEAKwDqDAAAAgBOABAABgmeDg0DAJgBBmgMAAACAD4AaQwAAAEAGABrDAAAAQATAGoMAAABABsAbAwAAAIAEADqDAAAAwA/AAIAAQk9E9oiAFoAAWkMAAABADEALgAECn8lAAIeAAgJsiQ4BgA5AwAeAAgJsiQ4BgA5AwAAAA==.Imabadshot:BAAALgADCgUJBQAAAA==.Imscary:BAAALgADCgMJAwAAAA==.',
In='Incandescent:BAAALgADCgcJCwABLgAECgYJBwAFAAAAAA==.Incarnate:BAAALgADCgYJBgABLgAECggJJgAVAMsLAA==.',
Ja='Ja:BAAALgADCgYJCQAAAA==.',
Je='Jenn:BAAALgAECgcJDAAAAA==.',
Jh='Jhalse:BAAALgAECgEJAQAAAA==.Jhoppss:BAABLgAECn8WAAMfAAYJlx1rDwDkAQZoDAAABQBRAGkMAAAEAE0AawwAAAQAQwBqDAAAAwBFAGwMAAACAFMA6gwAAAQARQAfAAYJlx1rDwDkAQZoDAAABABRAGkMAAAEAE0AawwAAAMAQwBqDAAAAgBAAGwMAAACAFMA6gwAAAMARQAgAAQJjQ+lSgCVAARoDAAAAQAwAGsMAAABACgAagwAAAEARQDqDAAAAQAeAAAA.',
Ji='Jiinxx:BAAALgAECgIJAwAAAA==.Jillià:BAAALgAFFAEJAgAAAA==.Jirachi:BAAALgADCgYJBgAAAA==.',
Jo='Jokervenom:BAAALgADCgYJBAAAAA==.',
Ka='Kaidia:BAAALgAECgQJBAAAAA==.Kaiyann:BAAALgADCgcJBwAAAA==.Karls:BAAALgAECgYJDQAAAA==.',
Ke='Keez:BAAALgAECgcJDgAAAA==.Keezey:BAAALgAECggJEQAAAA==.Kej:BAAALgAECgIJAgAAAA==.Kerafyrm:BAABLgAECn8rAAMZAAgJwx8NAwDUAghoDAAACAAwAGkMAAAHAFgAawwAAAYAVQBqDAAABgBUAGwMAAAFAEwAbQwAAAMAXADqDAAABwBZAG4MAAABAFUAGQAICcMfDQMA1AIIaAwAAAcAMABpDAAABgBYAGsMAAAGAFUAagwAAAYAVABsDAAABQBMAG0MAAADAFwA6gwAAAcAWQBuDAAAAQBVACAAAglyH91fAEoAAmgMAAABAFoAaQwAAAEARgAAAA==.Kerrigan:BAACLgAFFH8YAAIaAAYJjA3XFQBvAQZoDAAABQAsAGkMAAAGACwAawwAAAUAEwBqDAAAAwAaAGwMAAABABsA6gwAAAQAJgAaAAYJjA3XFQBvAQZoDAAABQAsAGkMAAAGACwAawwAAAUAEwBqDAAAAwAaAGwMAAABABsA6gwAAAQAJgAuAAQKfzMAAhoACQn4HiMLAKUCABoACQn4HiMLAKUCAAAA.',
Ki='Kiezn:BAAALgADCgEJAQABLgAECgYJFgANAB0jAA==.Kirithan:BAAALgAECgEJAQAAAA==.',
Ko='Kookler:BAABLgAECn8iAAMEAAkJaBd5JAAoAgloDAAABAA3AGkMAAAFAEEAawwAAAUAUgBqDAAABABSAGwMAAAEAEAAbQwAAAMAMgDqDAAABQBOAG4MAAADACgAbwwAAAEAFAAEAAkJaBd5JAAoAgloDAAABAA3AGkMAAAEAEEAawwAAAUAUgBqDAAABABSAGwMAAAEAEAAbQwAAAMAMgDqDAAABQBOAG4MAAADACgAbwwAAAEAFAAhAAEJPRBUMQA+AAFpDAAAAQApAAAA.Kozand:BAAALgADCgIJAgABLgAECgUJDwAFAAAAAA==.Kozari:BAAALgAECgYJEQAAAA==.',
Ku='Kushmon:BAAALgADCggJEgAAAA==.',
Ky='Kyirr:BAABLgAECn8fAAMfAAkJgxlNDAAWAgloDAAABgBDAGkMAAAFAFIAawwAAAYAUQBqDAAABQBHAGwMAAACACsAbQwAAAEARgDqDAAAAwA6AG4MAAACADQAbwwAAAEAQgAfAAcJQRpNDAAWAgdoDAAABQBDAGkMAAADAFIAawwAAAQAUQBqDAAABQBHAGwMAAACACsAbQwAAAEARgDqDAAAAwA6ACAABQkXGKssABkBBWgMAAABADAAaQwAAAIASwBrDAAAAgBBAG4MAAACADQAbwwAAAEAQgAAAA==.Kyralen:BAABLgAECn8WAAMNAAYJHSPEGABMAgZoDAAABABGAGkMAAAEAFwAawwAAAQAXABqDAAAAwBiAGwMAAADAF8A6gwAAAQAWgANAAYJHSPEGABMAgZoDAAAAwBGAGkMAAADAFwAawwAAAQAXABqDAAAAwBiAGwMAAADAF8A6gwAAAQAWgAKAAIJVxP42QB3AAJoDAAAAQAnAGkMAAABADsAAAA=.',
La='Labamba:BAAALgADCgYJCwAAAA==.Lazerbeampew:BAABLgAECn8XAAIMAAkJiRVRCgAsAgloDAAAAwBEAGkMAAADAE8AawwAAAMAQQBqDAAAAgBAAGwMAAACAC4AbQwAAAEAEADqDAAABABIAG4MAAADACwAbwwAAAIALwAMAAkJiRVRCgAsAgloDAAAAwBEAGkMAAADAE8AawwAAAMAQQBqDAAAAgBAAGwMAAACAC4AbQwAAAEAEADqDAAABABIAG4MAAADACwAbwwAAAIALwAAAA==.',
Li='Lilchithead:BAAALgAECgYJCgAAAA==.Lilium:BAAALgADCgEJAQAAAA==.Lilli:BAECLgAFFH8UAAIJAAYJSSHmAgDuAQZoDAAABABTAGkMAAAEAFwAawwAAAMAYABqDAAAAwBZAGwMAAACAEYA6gwAAAQAUwAJAAYJSSHmAgDuAQZoDAAABABTAGkMAAAEAFwAawwAAAMAYABqDAAAAwBZAGwMAAACAEYA6gwAAAQAUwAuAAQKfyUAAgkACQl1JSUBAK0DAAkACQl1JSUBAK0DAAAA.Lividea:BAAALgADCgUJBwAAAA==.Livinglover:BAAALgADCgUJAwAAAA==.',
Ll='Llela:BAAALgAECgUJBgAAAA==.Llynryn:BAABLgAECn8UAAIYAAcJOA+EMwBLAQdoDAAAAwApAGkMAAADACEAawwAAAIAHgBqDAAAAgAPAGwMAAACACoA6gwAAAUAMQBuDAAAAwAjABgABwk4D4QzAEsBB2gMAAADACkAaQwAAAMAIQBrDAAAAgAeAGoMAAACAA8AbAwAAAIAKgDqDAAABQAxAG4MAAADACMAAAA=.',
Lo='Locktua:BAAALgAECgcJCAAAAA==.',
Ly='Lympha:BAABLgAFFH8IAAMLAAMJch0QGwAZAQNoDAAABABhAGkMAAABACYA6gwAAAMAWgALAAMJch0QGwAZAQNoDAAAAwBhAGkMAAABACYA6gwAAAMAWgAMAAEJowFSDAA3AAFoDAAAAQAEAAAA.Lyn:BAAALgAECgUJCAAAAA==.',
Ma='Magicae:BAAALgADCgUJBQABLgAFFAcJFAAaAHUbAA==.Magicmanzz:BAAALgAECgYJDQAAAA==.Magnifuso:BAAALgAECgYJEAAAAA==.Maguapa:BAAALgAECgQJBwAAAA==.Malgata:BAAALgADCgkJFgAAAA==.Margarita:BAAALgAECgQJCQAAAA==.Martineh:BAAALgADCgcJDAAAAA==.Martoc:BAAALgADCgQJBAAAAA==.Martoche:BAAALgADCgEJAQAAAA==.Mastab:BAACLgAFFH8GAAINAAMJIRddHADiAANoDAAAAgBKAGkMAAABADQA6gwAAAMAMwANAAMJIRddHADiAANoDAAAAgBKAGkMAAABADQA6gwAAAMAMwAuAAQKfy4AAw0ACQnbH+cOAE8CAA0ABwkNH+cOAE8CAAoACAntGe0gACsCAAAA.',
Mc='Mcplucky:BAAALgAECgQJBAAAAA==.Mcziggles:BAAALgAECgcJCwAAAA==.',
Me='Meg:BAAALgAECgIJAgAAAA==.',
Mi='Mikio:BAABLgAECn8bAAIBAAgJYg5oHwBcAQhoDAAABgAxAGkMAAAGACgAawwAAAUAJABqDAAAAwAWAGwMAAACABUAbQwAAAEAGQDqDAAAAwA7AG4MAAABABgAAQAICWIOaB8AXAEIaAwAAAYAMQBpDAAABgAoAGsMAAAFACQAagwAAAMAFgBsDAAAAgAVAG0MAAABABkA6gwAAAMAOwBuDAAAAQAYAAAA.Miliani:BAAALgAECgIJAgAAAA==.Milinka:BAABLgAECn8nAAIXAAkJcxfbDwARAgloDAAABgBBAGkMAAAGAD4AawwAAAYALQBqDAAABQAwAGwMAAAFADYAbQwAAAIAOwDqDAAABQBVAG4MAAADADwAbwwAAAEAOwAXAAkJcxfbDwARAgloDAAABgBBAGkMAAAGAD4AawwAAAYALQBqDAAABQAwAGwMAAAFADYAbQwAAAIAOwDqDAAABQBVAG4MAAADADwAbwwAAAEAOwAAAA==.',
Mo='Moardottz:BAABLgAECn8XAAIOAAYJPxW+cgB5AQZoDAAABAAqAGkMAAAEADEAawwAAAQAPABqDAAAAwAsAGwMAAADAEAA6gwAAAUANgAOAAYJPxW+cgB5AQZoDAAABAAqAGkMAAAEADEAawwAAAQAPABqDAAAAwAsAGwMAAADAEAA6gwAAAUANgABLgAECgUJBQAFAAAAAA==.Moiryn:BAACLgAFFH8LAAILAAQJoRDeGgAaAQRoDAAABQBOAGkMAAADAAkAawwAAAEAJQDqDAAAAgAtAAsABAmhEN4aABoBBGgMAAAFAE4AaQwAAAMACQBrDAAAAQAlAOoMAAACAC0ALgAECn8pAAMLAAgJ/RvsFwAhAgALAAgJ/RvsFwAhAgAbAAEJcQ+YcAAzAAAAAA==.Monkmonk:BAAALgAECgEJAQAAAA==.Mortine:BAAALgADCgYJDwAAAA==.',
My='Mythesesgrey:BAAALgADCgUJCQAAAA==.',
Na='Naturals:BAAALgAECgEJAwAAAA==.Navillus:BAACLgAFFH8aAAIZAAYJxBBgCACxAQZoDAAABQA8AGkMAAAGAC0AawwAAAYAIgBqDAAAAwAmAGwMAAABABMA6gwAAAUAOQAZAAYJxBBgCACxAQZoDAAABQA8AGkMAAAGAC0AawwAAAYAIgBqDAAAAwAmAGwMAAABABMA6gwAAAUAOQAuAAQKf0AAAxkACQnvFMEMAGoCABkACQnvFMEMAGoCAB8ABwmbIdwIAFUCAAAA.',
No='Norasoul:BAABLgAECn8lAAIaAAkJVRtSDQCLAgloDAAABgBQAGkMAAAGAFQAawwAAAQAUwBqDAAABQBZAGwMAAAFAE0AbQwAAAIASQDqDAAABQBVAG4MAAADACYAbwwAAAEAJAAaAAkJVRtSDQCLAgloDAAABgBQAGkMAAAGAFQAawwAAAQAUwBqDAAABQBZAGwMAAAFAE0AbQwAAAIASQDqDAAABQBVAG4MAAADACYAbwwAAAEAJAAAAA==.',
Og='Ogron:BAACLgAFFH8SAAMLAAQJayUSCAC3AQRoDAAABgBiAGkMAAAFAFwAawwAAAMAXQDqDAAABABiAAsABAlrJRIIALcBBGgMAAACAGIAaQwAAAUAXABrDAAAAwBdAOoMAAAEAGIAGwABCXMfxRsAUwABaAwAAAQAUAAuAAQKfzgAAxsACQl8JRAEAF4DABsACQl8JRAEAF4DAAsAAwkoIGJjAK0AAAAA.',
Oh='Ohmna:BAAALgAECgQJCAAAAA==.Ohshyt:BAAALgAECgYJBgAAAA==.Ohsowitchy:BAAALgADCgQJBAAAAA==.',
Op='Ophindis:BAAALgAECgYJDgAAAA==.',
Or='Orwenya:BAAALgAECgUJDwAAAA==.',
Os='Osten:BAAALgAECgYJDQAAAA==.',
Ou='Ourkelly:BAAALgAECgYJDQAAAA==.',
Pa='Pagoda:BAAALgAECgkJCQAAAA==.',
Pe='Pewpop:BAAALgAECgYJCgABLgAECgcJEwAFAAAAAA==.',
Ph='Philzeey:BAAALgADCgYJCAAAAA==.Phrall:BAAALgAECgEJAQAAAA==.',
Py='Pylon:BAAALgAECggJCAAAAA==.',
Qp='Qpti:BAAALgAECgQJDQAAAA==.',
Ra='Raphael:BAAALgADCgcJCwAAAA==.Ravness:BAAALgAECgEJAQAAAA==.Razorclaw:BAAALgAECgYJBwAAAA==.',
Rc='Rckola:BAAALgADCgcJBwAAAA==.',
Re='Reddacted:BAAALgADCgcJDAAAAA==.Redgrave:BAAALgADCggJCwAAAA==.Rejectlol:BAAALgAECgcJCgAAAA==.Remake:BAAALgAECgMJAQAAAA==.Rennx:BAACLgAFFH8cAAIBAAgJ1hjtAgD1AQhoDAAABABeAGkMAAAEAE8AawwAAAUAXABqDAAABQBCAGwMAAABAA8AbQwAAAEAIADqDAAABwBVAG4MAAABACwAAQAICdYY7QIA9QEIaAwAAAQAXgBpDAAABABPAGsMAAAFAFwAagwAAAUAQgBsDAAAAQAPAG0MAAABACAA6gwAAAcAVQBuDAAAAQAsAC4ABAp/OQACAQAJCasmLwAAjAMAAQAJCasmLwAAjAMAAAA=.Rexam:BAAALgAECgIJAgABLgAECgcJEgAaAAkgAA==.Reznik:BAAALgAECgUJBwAAAA==.',
Ri='Ringmasta:BAABLgAECn8ZAAIiAAcJnxoKEQC+AQdoDAAABABWAGkMAAAEAEIAawwAAAQARQBqDAAABQBTAGwMAAADAEQAbQwAAAEAPgDqDAAABAA4ACIABwmfGgoRAL4BB2gMAAAEAFYAaQwAAAQAQgBrDAAABABFAGoMAAAFAFMAbAwAAAMARABtDAAAAQA+AOoMAAAEADgAAAA=.',
Ro='Roger:BAAALgADCgUJBQAAAA==.Rowen:BAABLgAECn8ZAAIiAAcJjB1zDQDvAQdoDAAABQBRAGkMAAAFAFEAawwAAAQAPQBqDAAAAwBSAGwMAAADAEIAbQwAAAEARwDqDAAABABbACIABwmMHXMNAO8BB2gMAAAFAFEAaQwAAAUAUQBrDAAABAA9AGoMAAADAFIAbAwAAAMAQgBtDAAAAQBHAOoMAAAEAFsAAAA=.',
Ru='Rucket:BAAALgAFFAEJAQAAAA==.Rutroraggy:BAABLgAECn8VAAMTAAYJ5A8zCQBZAQZoDAAABAAyAGkMAAAEACkAawwAAAQALwBqDAAAAwAZAGwMAAADACgA6gwAAAMAFwATAAYJ5A8zCQBZAQZoDAAAAwAyAGkMAAADACkAawwAAAMALwBqDAAAAgAZAGwMAAACACgA6gwAAAIAFwASAAYJ/QjJmgD5AAZoDAAAAQAfAGkMAAABABwAawwAAAEAGQBqDAAAAQAYAGwMAAABABYA6gwAAAEABgAAAA==.',
['Rè']='Rènza:BAAALgAFFAIJAwAAAA==.',
Sa='Saelybrosa:BAAALgAECgYJCQAAAA==.',
Se='Selmama:BAAALgAECgMJAgAAAA==.Serenìty:BAAALgAECgUJBQAAAA==.',
Sh='Shabit:BAAALgADCgUJBgABLgAFFAEJAgAFAAAAAA==.Shadda:BAAALgAECgYJDgAAAA==.Shadowsbane:BAAALgADCgUJBQAAAA==.Shamoon:BAABLgAFFH8GAAIbAAIJOQxzKACPAAJoDAAAAwAbAOoMAAADACMAGwACCTkMcygAjwACaAwAAAMAGwDqDAAAAwAjAAAA.Sharkattack:BAAALgADCgEJAQABLgAECgUJDAAFAAAAAA==.Shinru:BAABLgAECn8WAAMNAAkJbhjzGwDJAQloDAAAAgAuAGkMAAACAEsAawwAAAIAUABqDAAAAgA+AGwMAAADAEcAbQwAAAIAWgDqDAAAAwA3AG4MAAAEABcAbwwAAAIANwANAAgJCxfzGwDJAQhoDAAAAgAuAGkMAAACAEsAawwAAAIAUABqDAAAAQA+AGwMAAABAEcA6gwAAAIANwBuDAAAAQAXAG8MAAABADcACgAGCZUeO1sAXAEGagwAAAEASQBsDAAAAgBXAG0MAAACAFgA6gwAAAEAXQBuDAAAAwA+AG8MAAABADsAAAA=.Shioraven:BAAALgADCgMJAwAAAA==.Shrikedk:BAAALgAFFAMJAwAAAA==.',
Si='Sickdayze:BAABLgAECn8bAAINAAgJ9SBUCQCgAghoDAAABQBdAGkMAAAEAGIAawwAAAQAYABqDAAAAgBaAGwMAAACAEQAbQwAAAEAJADqDAAABgBhAG4MAAADAF0ADQAICfUgVAkAoAIIaAwAAAUAXQBpDAAABABiAGsMAAAEAGAAagwAAAIAWgBsDAAAAgBEAG0MAAABACQA6gwAAAYAYQBuDAAAAwBdAAAA.Sickkungfu:BAAALgADCgcJDAAAAA==.Sickshifts:BAAALgADCgYJBgAAAA==.Sicktides:BAAALgADCgcJCwAAAA==.Sine:BAAALgAECgIJAgAAAA==.',
Sk='Skydaddy:BAAALgADCgcJBwABLgAECgYJEAAFAAAAAA==.Skyrain:BAAALgADCgcJEgAAAA==.',
Sl='Slootin:BAAALgAECgEJAQAAAA==.Slyxxar:BAACLgAFFH8HAAILAAMJTg2ZLgC9AANoDAAAAwAgAGkMAAACAD4A6gwAAAIABwALAAMJTg2ZLgC9AANoDAAAAwAgAGkMAAACAD4A6gwAAAIABwAuAAQKfxsABAwABwk5GPgLAHEBAAwABwk5GPgLAHEBABsABgnBEexRAP8AAAsAAQl4AVWrAB8AAAAA.',
Sm='Smashtokhan:BAAALgAECgUJCAAAAA==.',
So='Socks:BAAALgAECgQJAQAAAA==.Soow:BAAALgAECgEJAQAAAA==.Soowwrr:BAAALgAECgQJCQAAAA==.Soph:BAACLgAFFH8NAAIEAAYJMhbIBwDiAQZoDAAAAwBcAGkMAAADAEAAawwAAAIAFwBqDAAAAgBBAGwMAAABABQA6gwAAAIASgAEAAYJMhbIBwDiAQZoDAAAAwBcAGkMAAADAEAAawwAAAIAFwBqDAAAAgBBAGwMAAABABQA6gwAAAIASgAuAAQKfxgAAwQABwlrIlgnABkCAAQABwlrIlgnABkCAAEAAgmjFlldAEAAAAAA.Sophie:BAACLgAFFH8KAAMKAAQJ9RvpGABVAQRoDAAABABAAGkMAAACAEQAawwAAAIAUADqDAAAAgBIAAoABAn1G+kYAFUBBGgMAAADAEAAaQwAAAIARABrDAAAAgBQAOoMAAACAEgADQABCdsNqDUAOQABaAwAAAEAIwAuAAQKfxsAAwoACAmrHOs7ADQCAAoACAmrHOs7ADQCAA0ABgkuDlNKAE8BAAEuAAUUBgkNAAQAMhYA.Sophievokie:BAAALgAECgQJCwABLgAFFAYJDQAEADIWAA==.Sophisticate:BAABLgAFFH8IAAIQAAQJSRdYCABaAQRoDAAAAgA2AGkMAAACADUAawwAAAIASgDqDAAAAgA3ABAABAlJF1gIAFoBBGgMAAACADYAaQwAAAIANQBrDAAAAgBKAOoMAAACADcAAS4ABRQGCQ0ABAAyFgA=.Sophiz:BAAALgAECgYJDwABLgAFFAYJDQAEADIWAA==.Sophlax:BAACLgAFFH8TAAIXAAUJLyRmAgDqAQVoDAAABgBjAGkMAAAFAFkAawwAAAQAYQBqDAAAAQBXAOoMAAADAFkAFwAFCS8kZgIA6gEFaAwAAAYAYwBpDAAABQBZAGsMAAAEAGEAagwAAAEAVwDqDAAAAwBZAC4ABAp/GQACFwAJCdQgDwQAFAMAFwAJCdQgDwQAFAMAAS4ABRQGCQ0ABAAyFgA=.Sophs:BAAALgAFFAIJAgABLgAFFAYJDQAEADIWAA==.Soulslug:BAAALgAECgEJAQAAAA==.Sox:BAACLgAFFH8FAAIjAAMJmBrABgDzAANoDAAAAgBGAGkMAAABAEAA6gwAAAIARQAjAAMJmBrABgDzAANoDAAAAgBGAGkMAAABAEAA6gwAAAIARQAuAAQKfzAAAiMACQknITEBAA0DACMACQknITEBAA0DAAAA.Soyeon:BAAALgAFFAEJAQAAAA==.Soyganchgar:BAAALgADCgUJCgAAAA==.Soyonagasaki:BAAALgAECgEJAgABLgAFFAMJAwAFAAAAAA==.',
Sp='Spicynoodle:BAAALgAECgkJCwAAAA==.Spiderknight:BAAALgADCgYJCwAAAA==.Spookyougi:BAABLgAECn8ZAAIYAAUJUSWKFwCpAQVoDAAABQBhAGkMAAAEAF8AawwAAAYAYgBqDAAABABjAOoMAAAGAFsAGAAFCVElihcAqQEFaAwAAAUAYQBpDAAABABfAGsMAAAGAGIAagwAAAQAYwDqDAAABgBbAAAA.',
Sq='Squattinchop:BAABLgAECn8XAAIHAAYJaiD3FQA6AgZoDAAABQBeAGkMAAAEAFoAawwAAAQATQBqDAAAAwBVAGwMAAADAFMA6gwAAAQARAAHAAYJaiD3FQA6AgZoDAAABQBeAGkMAAAEAFoAawwAAAQATQBqDAAAAwBVAGwMAAADAFMA6gwAAAQARAAAAA==.Squattinzaps:BAAALgADCgUJBQABLgAECgYJFwAHAGogAA==.',
St='Stiffcrit:BAAALgAECgkJBwAAAA==.Stinkydh:BAABLgAECn8SAAIaAAYJMhHCcADcAAZoDAAABABBAGkMAAADAC8AawwAAAMAKQBqDAAAAwBAAGwMAAADACQA6gwAAAIAHgAaAAYJMhHCcADcAAZoDAAABABBAGkMAAADAC8AawwAAAMAKQBqDAAAAwBAAGwMAAADACQA6gwAAAIAHgAAAA==.Stryx:BAAALgADCgcJBwABLgAECgYJEAAFAAAAAA==.',
Su='Suji:BAABLgAECn8hAAIDAAgJgyAYEACiAghoDAAABgBbAGkMAAAFAFcAawwAAAUAWwBqDAAABABYAGwMAAADAFgAbQwAAAEAMwDqDAAABgBSAG4MAAADAFoAAwAICYMgGBAAogIIaAwAAAYAWwBpDAAABQBXAGsMAAAFAFsAagwAAAQAWABsDAAAAwBYAG0MAAABADMA6gwAAAYAUgBuDAAAAwBaAAAA.Sumiko:BAAALgADCgQJBAABLgADCgYJBgAFAAAAAA==.Supergogeta:BAABLgAECn8tAAQEAAgJUiFyDgDGAghoDAAACABhAGkMAAAIAGMAawwAAAYAYwBqDAAABwBcAGwMAAAFAF8AbQwAAAIAJADqDAAACABhAG4MAAABAEAABAAHCXwicg4AxgIHaAwAAAgAYQBpDAAABwBjAGsMAAAGAGMAagwAAAcAXABsDAAABQBfAG0MAAABACQA6gwAAAgAYQABAAIJ+A4uTgBpAAJpDAAAAQAYAG4MAAABADQAIwABCYkEPTcAGgABbQwAAAEACwAAAA==.',
Sy='Sylvie:BAAALgAECgcJDwAAAA==.Synistër:BAAALgADCgMJAwAAAA==.Synthesis:BAAALgADCgMJAwAAAA==.',
Ta='Takoda:BAAALgADCgYJBgAAAA==.Taks:BAAALgADCgIJAgAAAA==.Talauyia:BAAALgAECgYJDQAAAA==.Tankyou:BAAALgAECgEJAQAAAA==.Tater:BAAALgADCgEJAQAAAA==.Tavik:BAAALgAECgMJAwAAAA==.',
Te='Teestri:BAAALgADCgcJBwAAAA==.Temporë:BAAALgAECgIJBQAAAA==.',
Th='Thorish:BAABLgAECn8kAAIkAAkJ5CGrAwDbAgloDAAABQBdAGkMAAAFAEoAawwAAAUAXgBqDAAABQBaAGwMAAAEAFwAbQwAAAMATQDqDAAABABdAG4MAAADAFIAbwwAAAIAVgAkAAkJ5CGrAwDbAgloDAAABQBdAGkMAAAFAEoAawwAAAUAXgBqDAAABQBaAGwMAAAEAFwAbQwAAAMATQDqDAAABABdAG4MAAADAFIAbwwAAAIAVgAAAA==.',
Ti='Tiddyweaver:BAAALgAECgUJDgABLgAECgkJGQAZAIwdAA==.Timbit:BAABLgAECn8jAAIHAAgJfQmAKwD+AAhoDAAABgAjAGkMAAAGABsAawwAAAYAKABqDAAABQAVAGwMAAAEABEAbQwAAAEAEADqDAAABQAWAG4MAAACAAkABwAICX0JgCsA/gAIaAwAAAYAIwBpDAAABgAbAGsMAAAGACgAagwAAAUAFQBsDAAABAARAG0MAAABABAA6gwAAAUAFgBuDAAAAgAJAAAA.Tinfoiltotem:BAAALgADCgYJAQAAAA==.Tinybubbles:BAABLgAECn8fAAMLAAgJDhZ8MACAAQhoDAAABgBMAGkMAAAFAFIAawwAAAUARQBqDAAABABRAGwMAAADACsAbQwAAAEAEQDqDAAABgBBAG4MAAABAA0ACwAICQ4WfDAAgAEIaAwAAAUATABpDAAABABSAGsMAAAEAEUAagwAAAQAUQBsDAAAAwArAG0MAAABABEA6gwAAAUAQQBuDAAAAQANABsABAkrDZdfAMUABGgMAAABACcAaQwAAAEAHgBrDAAAAQAzAOoMAAABAA0AAAA=.Tinyfeet:BAAALgAECgUJCgAAAA==.Tiriandrel:BAAALgADCgYJBgABLgAECgYJDgAFAAAAAA==.',
To='Token:BAAALgADCgIJAwAAAA==.Torio:BAABLgAECn8bAAMlAAgJRBkDEgDqAQhoDAAABABGAGkMAAAEAFcAawwAAAMAOQBqDAAAAwA+AGwMAAADAE4AbQwAAAEADwDqDAAABgBdAG4MAAADADUAJQAICUQZAxIA6gEIaAwAAAQARgBpDAAABABXAGsMAAADADkAagwAAAMAPgBsDAAAAwBOAG0MAAABAA8A6gwAAAUAXQBuDAAAAwA1ABgAAQm/B59jACwAAeoMAAABABMAAAA=.',
Tr='Trooth:BAAALgADCgYJBgABLgAECgUJDAAFAAAAAA==.Tròybòy:BAABLgAECn8gAAIDAAgJlSFGFwBsAghoDAAABQBaAGkMAAAFAFwAawwAAAUAWgBqDAAABABaAGwMAAAEAEQAbQwAAAIAXADqDAAABQBMAG4MAAACAFsAAwAICZUhRhcAbAIIaAwAAAUAWgBpDAAABQBcAGsMAAAFAFoAagwAAAQAWgBsDAAABABEAG0MAAACAFwA6gwAAAUATABuDAAAAgBbAAAA.Trölololollo:BAAALgADCgUJCAAAAA==.',
Tu='Turboidiot:BAAALgAECgYJCQAAAA==.',
Tw='Twofow:BAAALgADCgkJCgAAAA==.Twylla:BAAALgAECgEJAQABLgAECgkJPgAfAIQlAA==.',
Ty='Tyrrlol:BAAALgAECgUJCAAAAA==.Tyê:BAAALgAECgcJEwAAAA==.',
['Té']='Témalabécane:BAAALgADCgEJAQAAAA==.',
Va='Vael:BAAALgAECgYJEwAAAA==.Vaelric:BAAALgADCgEJAQAAAA==.Vale:BAABLgAECn8lAAMWAAcJaBXSGgAeAQdoDAAACABAAGkMAAAHAEQAawwAAAYALwBqDAAABAA3AGwMAAAEACkA6gwAAAcAOwBuDAAAAQAvAAMABgnnFd+PAGABBmgMAAAFAEAAaQwAAAQARABrDAAAAwAuAGoMAAACADcAbAwAAAEAKQDqDAAABAA7ABYABwn1D9IaAB4BB2gMAAADACQAaQwAAAMALABrDAAAAwAvAGoMAAACACkAbAwAAAMAGwDqDAAAAwApAG4MAAABAC8AAAA=.Valériana:BAAALgADCgEJAQAAAA==.',
Ve='Vee:BAABLgAECn8fAAMmAAgJ+CMZBwChAghoDAAABgBiAGkMAAAGAFQAawwAAAUAVwBqDAAAAwBRAGwMAAADAF8AbQwAAAIAXgDqDAAABQBhAG4MAAABAFYAJgAICfgjGQcAoQIIaAwAAAYAYgBpDAAABgBUAGsMAAAFAFcAagwAAAMAUQBsDAAAAgBfAG0MAAACAF4A6gwAAAUAYQBuDAAAAQBWACcAAQmcFeY7AEEAAWwMAAABADcAAAA=.Veyla:BAEALgADCgcJDgABLgAECgYJBwAFAAAAAA==.',
Vo='Voiddemon:BAAALgAECgIJAgAAAA==.Voltage:BAAALgAECgcJEwAAAA==.Vore:BAAALgADCgEJAQAAAA==.',
Vu='Vult:BAABLgAECn8jAAIDAAkJwxWPUwBlAQloDAAABAA7AGkMAAAEADUAawwAAAQAJgBqDAAAAwAYAGwMAAAFAEoAbQwAAAMAHQDqDAAABAA8AG4MAAAFAEgAbwwAAAMAOAADAAkJwxWPUwBlAQloDAAABAA7AGkMAAAEADUAawwAAAQAJgBqDAAAAwAYAGwMAAAFAEoAbQwAAAMAHQDqDAAABAA8AG4MAAAFAEgAbwwAAAMAOAAAAA==.',
Wa='Warkdom:BAAALgAECgUJCAAAAA==.',
We='Wehttam:BAAALgAECgIJAgAAAA==.Welgo:BAABLgAECn8iAAIcAAcJhiNYBgBTAgdoDAAABgBgAGkMAAAGAGAAawwAAAYAXQBqDAAABQBcAGwMAAAFAF8A6gwAAAUAWgBuDAAAAQBIABwABwmGI1gGAFMCB2gMAAAGAGAAaQwAAAYAYABrDAAABgBdAGoMAAAFAFwAbAwAAAUAXwDqDAAABQBaAG4MAAABAEgAAAA=.',
Wh='Wheelchair:BAEALgADCgYJBgABLgAECgYJBwAFAAAAAA==.',
Wi='Wickeddemon:BAABLgAECn8YAAIVAAcJkxF0GABBAQdoDAAABAA0AGkMAAAEADAAawwAAAQALgBqDAAABQA6AGwMAAADAC4AbQwAAAEAGwDqDAAAAwAxABUABwmTEXQYAEEBB2gMAAAEADQAaQwAAAQAMABrDAAABAAuAGoMAAAFADoAbAwAAAMALgBtDAAAAQAbAOoMAAADADEAAAA=.Wiseoaktree:BAAALgADCgcJCAAAAA==.Wizzie:BAAALgAECgMJAwAAAA==.',
['Wì']='Wìzzqt:BAABLgAECn8iAAINAAkJxhQnGgDYAQloDAAABQAsAGkMAAAFACwAawwAAAUALQBqDAAABQA+AGwMAAAEACAAbQwAAAEANADqDAAABQA8AG4MAAADADgAbwwAAAEATwANAAkJxhQnGgDYAQloDAAABQAsAGkMAAAFACwAawwAAAUALQBqDAAABQA+AGwMAAAEACAAbQwAAAEANADqDAAABQA8AG4MAAADADgAbwwAAAEATwAAAA==.',
Xa='Xanthel:BAAALgADCgcJCwABLgAECgkJIgAEAGgXAA==.',
Xe='Xenk:BAAALgADCgEJAQAAAA==.Xerra:BAABLgAECn8mAAIaAAkJPB9tCQC8AgloDAAABQBPAGkMAAAFAFQAawwAAAYAVQBqDAAABQBVAGwMAAAEAEoAbQwAAAMAUwDqDAAABQBQAG4MAAAEAFQAbwwAAAEAQwAaAAkJPB9tCQC8AgloDAAABQBPAGkMAAAFAFQAawwAAAYAVQBqDAAABQBVAGwMAAAEAEoAbQwAAAMAUwDqDAAABQBQAG4MAAAEAFQAbwwAAAEAQwAAAA==.',
Ye='Yeast:BAAALgADCgEJAQAAAA==.',
Yi='Yia:BAACLgAFFH8SAAIhAAUJdx24AACxAQVoDAAABABVAGkMAAAFAFwAawwAAAMASQBqDAAAAwBZAOoMAAADADIAIQAFCXcduAAAsQEFaAwAAAQAVQBpDAAABQBcAGsMAAADAEkAagwAAAMAWQDqDAAAAwAyAC4ABAp/FgACIQAICcMicgQA1QIAIQAICcMicgQA1QIAAAA=.',
Yr='Yralka:BAAALgAECgMJAwAAAA==.',
Yu='Yuqi:BAAALgADCgcJBwAAAA==.',
Za='Zaftenpuff:BAAALgAECgQJBAAAAA==.Zandashami:BAAALgAECggJCAAAAA==.Zarya:BAAALgAECgUJDwAAAA==.',
Ze='Zelgie:BAABLgAECn8nAAMkAAcJ+BL7EQBAAQdoDAAACAAxAGkMAAAHAC0AawwAAAcAQABqDAAABQAlAGwMAAAEADMA6gwAAAcAOQBuDAAAAQAWACQABwn4EvsRAEABB2gMAAAHADEAaQwAAAYALQBrDAAABgBAAGoMAAAFACUAbAwAAAMAMwDqDAAABgA5AG4MAAABABYADQAFCegQVToA/gAFaAwAAAEAMwBpDAAAAQAjAGsMAAABABkAbAwAAAEAOQDqDAAAAQAuAAAA.',
Zo='Zorsse:BAAALgAECgQJAwABLgAECggJHwAmAN0XAA==.',
Zu='Zulu:BAAALgAECgYJEQAAAA==.',
['Zâ']='Zâkârum:BAAALgADCgcJBwAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
