local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Unknown-Unknown','Mage-Arcane','Mage-Frost','Mage-Fire','Priest-Holy','Warrior-Protection','Shaman-Restoration','Shaman-Elemental','DeathKnight-Unholy','Warrior-Fury','Hunter-Survival','Hunter-BeastMastery','DeathKnight-Blood','Rogue-Outlaw','Druid-Restoration','Druid-Balance','Druid-Feral','Druid-Guardian','Hunter-Marksmanship','Paladin-Holy','DemonHunter-Devourer','Warlock-Demonology','Warlock-Affliction','Paladin-Retribution','DemonHunter-Havoc','DemonHunter-Vengeance','Monk-Windwalker','Warlock-Destruction','Warrior-Arms','Rogue-Subtlety','Priest-Shadow','DeathKnight-Frost','Paladin-Protection','Shaman-Enhancement','Monk-Mistweaver',}
local provider = {region='US',realm='EchoIsles',name='US',type='daily',zone=46,date='2026-05-11',data={Aa='Aaelless:BAAALgAECgEJAQAAAA==.',
Ab='Abeblinkin:BAAALgADCgQJBwAAAA==.Abrakadavar:BAAALgAECgQJBQAAAA==.Abräxis:BAAALgADCgkJCQABLgAECgMJAwABAAAAAA==.',
Ae='Aeless:BAAALgAECggJDgAAAA==.Aelless:BAAALgAECgMJBQAAAA==.Aenest:BAAALgADCggJCAAAAA==.',
Ai='Aithinne:BAAALgADCgkJKAAAAA==.',
Ak='Akanah:BAAALgADCgcJBwAAAA==.',
Al='Alfira:BAAALgAECgYJCgAAAA==.Alghul:BAAALgAECgEJAQABLgAECgUJCgABAAAAAA==.',
Am='Amalthea:BAAALgADCgcJBwAAAA==.Amoredis:BAAALgADCgYJBgAAAA==.',
An='Anklbiterkat:BAAALgADCgQJBAAAAA==.Anume:BAAALgADCgQJDgAAAA==.',
Ar='Aravis:BAAALgAECgcJBwAAAA==.Arese:BAABLgAECn8bAAQCAAYJTiZ/AwA0AgZoDAAABgBjAGkMAAAFAGIAawwAAAUAYQBqDAAAAwBbAGwMAAADAF8A6gwAAAUAYwACAAUJTiZ/AwA0AgVoDAAABABjAGkMAAAEAGIAawwAAAUAYQBsDAAAAwBfAOoMAAAFAGMAAwADCZck7hIB2AADaAwAAAIAYQBpDAAAAQBaAGoMAAABADwABAABCQAAUwwAaQABagwAAAIAWwAAAA==.Aron:BAAALgADCgMJAgAAAA==.',
As='Ashandra:BAAALgADCgkJDwAAAA==.Ashlyssra:BAABLgAECn8VAAIFAAgJBB0aBgCqAghoDAAAAgBfAGkMAAADAGAAawwAAAMAXQBqDAAAAwAxAGwMAAADADgAbQwAAAIAJQDqDAAABABcAG4MAAABAEgABQAICQQdGgYAqgIIaAwAAAIAXwBpDAAAAwBgAGsMAAADAF0AagwAAAMAMQBsDAAAAwA4AG0MAAACACUA6gwAAAQAXABuDAAAAQBIAAAA.',
Aw='Awsomesause:BAAALgAECgQJBgAAAA==.',
Az='Azuri:BAAALgAECgQJBQAAAA==.Azzif:BAAALgAECgkJDAAAAA==.Azzraell:BAAALgADCgEJAQAAAA==.',
Ba='Babaorumm:BAAALgADCgUJBQAAAA==.Babasha:BAAALgAFFAIJAgAAAA==.Babybluz:BAAALgAECgQJBgAAAA==.Baconloaf:BAAALgAECgUJCQAAAA==.Baldilocks:BAAALgADCgQJDAAAAA==.Bat:BAAALgADCgEJAQAAAA==.',
Be='Beauriley:BAABLgAECn8rAAIGAAkJJBF1CwDAAQloDAAABwA9AGkMAAAHADYAawwAAAcALABqDAAABQAzAGwMAAAEACYAbQwAAAMAFgDqDAAABgA0AG4MAAADACMAbwwAAAEAKQAGAAkJJBF1CwDAAQloDAAABwA9AGkMAAAHADYAawwAAAcALABqDAAABQAzAGwMAAAEACYAbQwAAAMAFgDqDAAABgA0AG4MAAADACMAbwwAAAEAKQAAAA==.Behomethan:BAABLgAECn8mAAMHAAkJZBtJKgDlAQloDAAABgBUAGkMAAAGAFQAawwAAAYAWABqDAAABAArAGwMAAAEABsAbQwAAAMATADqDAAABQA9AG4MAAADAEUAbwwAAAEAXgAHAAgJOBpJKgDlAQhoDAAABABUAGkMAAAEAFQAawwAAAQAWABqDAAAAwArAGwMAAACABsAbQwAAAMATADqDAAABAA9AG4MAAABAEUACAAICQAUIxYAsQEIaAwAAAIAQQBpDAAAAgA4AGsMAAACAD4AagwAAAEAQgBsDAAAAgAnAOoMAAABACkAbgwAAAIAQwBvDAAAAQAaAAAA.Beyonsláy:BAAALgADCgIJAgAAAA==.',
Bh='Bhipbookie:BAAALgAECgEJAwAAAA==.',
Bi='Billbetaray:BAAALgADCgMJAwAAAA==.',
Bl='Bluerift:BAAALgADCgEJAQAAAA==.',
Bo='Bobbyb:BAAALgAECgYJEQAAAA==.Bombchele:BAAALgAECgYJBgABLgAECggJFwAJAI4aAA==.Boneulngtime:BAAALgADCgUJCgAAAA==.Boon:BAAALgAECgIJAgAAAA==.Bowlofwrong:BAAALgAECgYJBwAAAA==.',
Br='Bratticusrex:BAABLgAECn8YAAIKAAYJnAmnNQD9AAZoDAAABAAlAGkMAAAEABkAawwAAAQAKQBqDAAABAAGAGwMAAAEAAoA6gwAAAQACAAKAAYJnAmnNQD9AAZoDAAABAAlAGkMAAAEABkAawwAAAQAKQBqDAAABAAGAGwMAAAEAAoA6gwAAAQACAAAAA==.Bresowar:BAAALgAECgYJBwAAAA==.',
Bu='Bunnylicious:BAABLgAECn8aAAIHAAgJryTABQDqAghoDAAABABhAGkMAAAEAF8AawwAAAQAXwBqDAAAAgBeAGwMAAACAFwAbQwAAAMAXwDqDAAABABeAG4MAAADAFUABwAICa8kwAUA6gIIaAwAAAQAYQBpDAAABABfAGsMAAAEAF8AagwAAAIAXgBsDAAAAgBcAG0MAAADAF8A6gwAAAQAXgBuDAAAAwBVAAAA.Bunnymedic:BAAALgAECgYJDAABLgAECggJGgAHAK8kAA==.',
Ca='Caebrylla:BAABLgAECn8dAAILAAcJpAzYFwBgAQdoDAAABwAdAGkMAAAFAC0AawwAAAQAHwBqDAAABAAYAGwMAAADACoA6gwAAAUAHABuDAAAAQARAAsABwmkDNgXAGABB2gMAAAHAB0AaQwAAAUALQBrDAAABAAfAGoMAAAEABgAbAwAAAMAKgDqDAAABQAcAG4MAAABABEAAAA=.Calistie:BAAALgAECgIJAgAAAA==.Camigatu:BAAALgADCgQJBAAAAA==.Camil:BAAALgAECgEJAQABLgAECggJIgAMAMwWAA==.Cang:BAAALgAECgIJAgAAAA==.Capulin:BAABLgAECn8eAAIKAAgJmRWiFQDKAQhoDAAABAA7AGkMAAAFADQAawwAAAUATABqDAAAAwA+AGwMAAADAEgAbQwAAAEAJQDqDAAACAA+AG4MAAABABgACgAICZkVohUAygEIaAwAAAQAOwBpDAAABQA0AGsMAAAFAEwAagwAAAMAPgBsDAAAAwBIAG0MAAABACUA6gwAAAgAPgBuDAAAAQAYAAAA.Catdurid:BAAALgADCgYJBgAAAA==.',
Ce='Cecilbrown:BAAALgADCgMJAwAAAA==.Cecimorte:BAABLgAECn8dAAINAAcJpxfGDwCKAQdoDAAABwBIAGkMAAAFAEcAawwAAAQAOABqDAAABABDAGwMAAADADQA6gwAAAUAUgBuDAAAAQAbAA0ABwmnF8YPAIoBB2gMAAAHAEgAaQwAAAUARwBrDAAABAA4AGoMAAAEAEMAbAwAAAMANADqDAAABQBSAG4MAAABABsAAAA=.Cephalopod:BAABLgAECn8UAAIOAAgJ1RV0BQB5AQhoDAAABABWAGkMAAADAEMAawwAAAIAMABqDAAAAwBNAGwMAAACACoAbQwAAAIAOgDqDAAAAwA/AG8MAAABABgADgAICdUVdAUAeQEIaAwAAAQAVgBpDAAAAwBDAGsMAAACADAAagwAAAMATQBsDAAAAgAqAG0MAAACADoA6gwAAAMAPwBvDAAAAQAYAAAA.',
Ch='Chargeasap:BAAALgAECgMJAwAAAA==.Charttopper:BAAALgAECgYJCQAAAA==.Chibby:BAAALgADCgIJAgAAAA==.Chonker:BAABLgAECn8uAAMPAAgJaiFvBgD7AghoDAAABwBhAGkMAAAHAF4AawwAAAcAUQBqDAAABgBVAGwMAAAFAE4AbQwAAAMARQDqDAAABwBfAG4MAAAEAFEADwAICWohbwYA+wIIaAwAAAYAYQBpDAAABwBeAGsMAAAHAFEAagwAAAYAVQBsDAAABQBOAG0MAAABAEUA6gwAAAcAXwBuDAAAAwBRABAAAwl7CmlNAF4AA2gMAAABACoAbQwAAAIAEwBuDAAAAQASAAAA.Chorelock:BAAALgADCgEJAQAAAA==.Chronormu:BAAALgADCgEJAQAAAA==.Chuckforrest:BAAALgAECgQJBAAAAA==.Chultis:BAABLgAECn8VAAQRAAYJMxX7FQBYAQZoDAAABQApAGkMAAAEAEAAawwAAAQAPQBqDAAAAwAXAGwMAAACACoA6gwAAAMAPQARAAYJMxX7FQBYAQZoDAAABAApAGkMAAAEAEAAawwAAAQAPQBqDAAAAgAXAGwMAAACACoA6gwAAAMAPQAQAAEJ2wH3jgAeAAFoDAAAAQAEAA8AAQkCAsXpABsAAWoMAAABAAUAAAA=.',
Ci='Cihato:BAABLgAECn8tAAISAAkJZBihBABDAgloDAAABwBPAGkMAAAHAFQAawwAAAcAUABqDAAABgA5AGwMAAAFADYAbQwAAAMAPgDqDAAABgBNAG4MAAADACwAbwwAAAEAEAASAAkJZBihBABDAgloDAAABwBPAGkMAAAHAFQAawwAAAcAUABqDAAABgA5AGwMAAAFADYAbQwAAAMAPgDqDAAABgBNAG4MAAADACwAbwwAAAEAEAAAAA==.',
Cl='Claxious:BAABLgAECn8XAAITAAgJLhUbBgDIAQhoDAAABAA8AGkMAAAEAEQAawwAAAQAPABqDAAAAgAwAGwMAAACABoAbQwAAAEALgDqDAAAAwAuAG4MAAADAEYAEwAICS4VGwYAyAEIaAwAAAQAPABpDAAABABEAGsMAAAEADwAagwAAAIAMABsDAAAAgAaAG0MAAABAC4A6gwAAAMALgBuDAAAAwBGAAAA.Claye:BAACLgAFFH8JAAIHAAMJOQ2UKgC+AANoDAAABAAiAGkMAAADADEA6gwAAAIAEQAHAAMJOQ2UKgC+AANoDAAABAAiAGkMAAADADEA6gwAAAIAEQAuAAQKfyMAAgcACQkiFlEmAPoBAAcACQkiFlEmAPoBAAAA.',
Co='Coldshoulder:BAABLgAECn8dAAIDAAcJ3hroNgDVAQdoDAAABwBMAGkMAAAFAEwAawwAAAQAPwBqDAAABABFAGwMAAADAEcA6gwAAAUASwBuDAAAAQAxAAMABwneGug2ANUBB2gMAAAHAEwAaQwAAAUATABrDAAABAA/AGoMAAAEAEUAbAwAAAMARwDqDAAABQBLAG4MAAABADEAAAA=.Corelas:BAAALgAECgYJEwAAAA==.Corfellyn:BAAALgAECggJBAAAAA==.Couchdad:BAAALgAECgUJCgAAAA==.',
Cr='Crazymadman:BAAALgAECgEJAgAAAA==.Crushingblow:BAAALgAECgkJAwAAAA==.',
Cy='Cyon:BAAALgADCgEJAQAAAA==.',
Da='Daalaria:BAAALgADCgEJAQAAAA==.Darkone:BAAALgADCgUJBQAAAA==.Dawnson:BAABLgAECn8fAAIUAAcJDx46DwA3AgdoDAAABgBhAGkMAAAFAFoAawwAAAUAXwBqDAAABQA3AGwMAAADAEQA6gwAAAUAWwBuDAAAAgAnABQABwkPHjoPADcCB2gMAAAGAGEAaQwAAAUAWgBrDAAABQBfAGoMAAAFADcAbAwAAAMARADqDAAABQBbAG4MAAACACcAAAA=.',
De='Deadzexcs:BAAALgAECgUJDQAAAA==.Deathsnear:BAAALgAECgEJAQAAAA==.Demogless:BAAALgAECgYJDAAAAA==.Devyn:BAAALgADCgUJBQAAAA==.',
Dh='Dharknight:BAAALgADCgQJCAAAAA==.',
Di='Didimissfire:BAEBLgAECn8sAAIMAAgJaxQ9KQC7AQhoDAAABgBEAGkMAAAHADMAawwAAAcAKwBqDAAABgA3AGwMAAAFADIAbQwAAAMAJwDqDAAABgBJAG4MAAAEACgADAAICWsUPSkAuwEIaAwAAAYARABpDAAABwAzAGsMAAAHACsAagwAAAYANwBsDAAABQAyAG0MAAADACcA6gwAAAYASQBuDAAABAAoAAAA.',
Do='Donaghy:BAAALgAECgEJAQAAAA==.Dooms:BAAALgADCgcJBwAAAA==.',
Dp='Dpsmaster:BAAALgAECgUJEQAAAA==.',
Dr='Dranalis:BAAALgAECgYJBwAAAA==.Drdrake:BAAALgADCgcJFAAAAA==.Dredlok:BAAALgADCgkJFQAAAA==.Drufiyo:BAAALgAECgUJBQABLgAECgkJJgAVANERAA==.',
Du='Dumonster:BAAALgAECgYJCQAAAA==.',
['Dø']='Døll:BAAALgADCgYJBgAAAA==.',
Ea='Eamishal:BAAALgADCgEJAQAAAA==.',
Ei='Eightace:BAAALgADCgYJBgAAAA==.Eirenne:BAAALgAECgYJBwAAAA==.',
Ek='Ekaru:BAAALgADCgEJAQAAAA==.',
El='Elethryia:BAAALgAECgIJBAAAAA==.Elev:BAAALgADCgYJCgAAAA==.Elindril:BAAALgAECgYJDwAAAA==.',
En='Enoth:BAAALgAECgUJCAAAAA==.',
Eo='Eowynn:BAABLgAECn8XAAIHAAgJTxZHJQCkAQhoDAAABQBSAGkMAAAEAE8AawwAAAMASQBqDAAAAgAgAGwMAAABABkAbQwAAAEALQDqDAAABABOAG4MAAADACcABwAICU8WRyUApAEIaAwAAAUAUgBpDAAABABPAGsMAAADAEkAagwAAAIAIABsDAAAAQAZAG0MAAABAC0A6gwAAAQATgBuDAAAAwAnAAAA.',
Es='Estella:BAABLgAECn8cAAIDAAYJUQtDhgAVAQZoDAAABgAeAGkMAAAGAB0AawwAAAYAGwBqDAAAAwATAGwMAAACACYA6gwAAAUAEgADAAYJUQtDhgAVAQZoDAAABgAeAGkMAAAGAB0AawwAAAYAGwBqDAAAAwATAGwMAAACACYA6gwAAAUAEgAAAA==.',
Ev='Eventhorizon:BAAALgAECgkJBgAAAA==.Evielli:BAAALgADCgUJBQAAAA==.',
Fa='Faeriefire:BAAALgADCgQJBQAAAA==.Fanna:BAAALgADCgMJAwAAAA==.Fatbox:BAABLgAECn8bAAIKAAgJhhwEMwDfAQhoDAAAAwBfAGkMAAAEAFQAawwAAAQAUgBqDAAAAwBBAGwMAAADAEkAbQwAAAIALQDqDAAABgBVAG4MAAACACwACgAICYYcBDMA3wEIaAwAAAMAXwBpDAAABABUAGsMAAAEAFIAagwAAAMAQQBsDAAAAwBJAG0MAAACAC0A6gwAAAYAVQBuDAAAAgAsAAAA.Faythh:BAABLgAECn8rAAIFAAgJ3B+NBgCfAghoDAAABwBbAGkMAAAHAFoAawwAAAcAWgBqDAAABgBWAGwMAAAFAFsAbQwAAAMATgDqDAAABQBHAG4MAAADADMABQAICdwfjQYAnwIIaAwAAAcAWwBpDAAABwBaAGsMAAAHAFoAagwAAAYAVgBsDAAABQBbAG0MAAADAE4A6gwAAAUARwBuDAAAAwAzAAAA.',
Fe='Fearblade:BAAALgADCgcJDgAAAA==.Fedoran:BAABLgAECn8ZAAMRAAgJgx+nCABTAghoDAAABABhAGkMAAAEAFoAawwAAAQAUQBqDAAAAgBiAGwMAAACAFEAbQwAAAMAQQDqDAAABABcAG4MAAACADcAEQAGCaoipwgAUwIGaAwAAAMAYQBpDAAAAwBaAGsMAAADAFEAagwAAAIAYgBsDAAAAgBRAOoMAAADAFwAEAAGCZgcV04A8AAGaAwAAAEATABpDAAAAQBKAGsMAAABAE8AbQwAAAMAQQDqDAAAAQBYAG4MAAACADcAAAA=.Felasap:BAAALgAECgEJAQAAAA==.Fenastic:BAABLgAECn8bAAMWAAcJGAfOcAD1AAdoDAAABQASAGkMAAAFABQAawwAAAUAEABqDAAAAwAYAGwMAAADACIA6gwAAAUACABuDAAAAQAKABYABwl1Bs5wAPUAB2gMAAAEABIAaQwAAAQADwBrDAAAAwALAGoMAAADABgAbAwAAAMAIgDqDAAABQAIAG4MAAABAAoAFwADCRAGLBwAkQADaAwAAAEACQBpDAAAAQAUAGsMAAACABAAAAA=.Fenrisúlfur:BAAALgAECgUJDQAAAA==.Feyrah:BAAALgAECgMJAwABLgAECggJFwAHAE8WAA==.',
Fi='Filthy:BAAALgAECgkJCQAAAA==.Fiobhe:BAAALgAECgYJEQAAAA==.Fixeruper:BAABLgAECn8XAAIFAAgJQwGhNQC9AAhoDAAABQACAGkMAAADAAMAawwAAAUAAgBqDAAAAwAEAGwMAAACAAIAbQwAAAEAAgDqDAAAAwAFAG4MAAABAAIABQAICUMBoTUAvQAIaAwAAAUAAgBpDAAAAwADAGsMAAAFAAIAagwAAAMABABsDAAAAgACAG0MAAABAAIA6gwAAAMABQBuDAAAAQACAAAA.',
Fl='Flaggedname:BAAALgADCgMJAwAAAA==.Flubberduck:BAAALgADCggJEAAAAA==.Fluffybeer:BAABLgAECn8eAAIJAAgJTh0IGABOAghoDAAABgBRAGkMAAAFAE8AawwAAAUARQBqDAAABABeAGwMAAACAEsAbQwAAAMAVwDqDAAAAwBHAG4MAAACADsACQAICU4dCBgATgIIaAwAAAYAUQBpDAAABQBPAGsMAAAFAEUAagwAAAQAXgBsDAAAAgBLAG0MAAADAFcA6gwAAAMARwBuDAAAAgA7AAAA.',
Fo='Fonz:BAAALgAECgUJBQABLgAECgcJGgAUAHYQAA==.Footdig:BAABLgAECn8aAAIPAAcJ2CIfCwCqAgdoDAAABQBiAGkMAAAFAGMAawwAAAUAYwBqDAAABABgAGwMAAACAFIAbQwAAAEAOQDqDAAABABZAA8ABwnYIh8LAKoCB2gMAAAFAGIAaQwAAAUAYwBrDAAABQBjAGoMAAAEAGAAbAwAAAIAUgBtDAAAAQA5AOoMAAAEAFkAAAA=.',
Fu='Fuquan:BAAALgAECgMJBAAAAA==.',
Fw='Fwd:BAAALgADCgIJAgAAAA==.',
Ga='Gadzook:BAAALgADCggJFQAAAA==.Gatolun:BAAALgADCgUJBQAAAA==.',
Gi='Giline:BAAALgAECgEJAQAAAA==.Gimp:BAAALgADCgEJAQAAAA==.Ginja:BAAALgADCgIJAgAAAA==.',
Gl='Glenlizzo:BAEALgADCgUJCQABLgAECgUJCAABAAAAAA==.Glenroyce:BAEALgAECgUJCAAAAA==.Gless:BAAALgADCgkJOAAAAA==.',
Go='Goodfine:BAAALgADCgcJDwAAAA==.Goss:BAAALgADCgcJBwAAAA==.',
Gr='Grandcross:BAAALgADCgMJAwAAAA==.',
Gu='Gungnir:BAAALgAECgYJDAAAAA==.Gush:BAAALgADCgQJBAAAAA==.Guttertrash:BAAALgAECgIJAgAAAA==.',
Ha='Hae:BAAALgADCgEJAQAAAA==.Haenus:BAAALgADCgcJCQAAAA==.Haill:BAAALgAECgYJBwAAAA==.Hamhock:BAAALgAECgUJCAABLgAECggJGwAKAIYcAA==.Hammered:BAEALgADCgUJBQABLgAECgUJCAABAAAAAA==.Hardtobepro:BAAALgAECgcJBwAAAA==.Harleydk:BAAALgADCgUJBQAAAA==.',
He='Heartsong:BAAALgAECgcJBgAAAA==.',
Ho='Holycrusader:BAABLgAECn8YAAIYAAgJVxIYTwBrAQhoDAAABAA+AGkMAAADABsAawwAAAMATgBqDAAAAwA8AGwMAAADABMAbQwAAAIAMgDqDAAABAAoAG4MAAACADEAGAAICVcSGE8AawEIaAwAAAQAPgBpDAAAAwAbAGsMAAADAE4AagwAAAMAPABsDAAAAwATAG0MAAACADIA6gwAAAQAKABuDAAAAgAxAAAA.',
Ih='Ihatepallys:BAAALgADCgcJEAAAAA==.',
Ii='Iikeomgikr:BAAALgADCgEJAQAAAA==.',
Il='Ilduca:BAAALgADCgQJBAAAAA==.Ilidank:BAAALgAECgYJDAAAAA==.Ilya:BAAALgAECgUJBQABLgAECggJFwAYAHYYAA==.',
Im='Impotence:BAAALgADCgMJAwAAAA==.',
In='Indigo:BAABLgAECn8sAAIHAAgJ1B5oCAC2AghoDAAABwBfAGkMAAAHAGMAawwAAAcATABqDAAABQBCAGwMAAAFAF0AbQwAAAMASwDqDAAABwBhAG4MAAADABsABwAICdQeaAgAtgIIaAwAAAcAXwBpDAAABwBjAGsMAAAHAEwAagwAAAUAQgBsDAAABQBdAG0MAAADAEsA6gwAAAcAYQBuDAAAAwAbAAAA.Innax:BAAALgADCgEJAQAAAA==.Innron:BAABLgAECn8lAAIZAAgJ7xAiEACVAQhoDAAABwA3AGkMAAAGADAAawwAAAYAJgBqDAAABAA9AGwMAAAFAEIAbQwAAAEADQDqDAAABgA6AG4MAAACABUAGQAICe8QIhAAlQEIaAwAAAcANwBpDAAABgAwAGsMAAAGACYAagwAAAQAPQBsDAAABQBCAG0MAAABAA0A6gwAAAYAOgBuDAAAAgAVAAAA.',
Ir='Irisblue:BAAALgADCgQJDgAAAA==.',
Is='Isyclic:BAAALgAECgYJBgABLgAECggJIAAGADshAA==.',
Iy='Iyahli:BAAALgAECgUJDQAAAA==.',
Ja='Jaedia:BAAALgADCgMJAwAAAA==.Jarclian:BAACLgAFFH8IAAIDAAMJvRBaTwD2AANoDAAABAA6AGkMAAABABUA6gwAAAMAMAADAAMJvRBaTwD2AANoDAAABAA6AGkMAAABABUA6gwAAAMAMAAuAAQKfzgAAgMACQnRIsgEADQDAAMACQnRIsgEADQDAAAA.Jaymonk:BAAALgAECgEJAQAAAA==.Jazmon:BAAALgAECgIJAgAAAA==.',
Je='Jezzea:BAAALgADCgQJCwAAAA==.',
Ji='Jimlaheys:BAAALgAECgYJDgAAAA==.Jitt:BAAALgAECgQJBAAAAA==.',
['Jâ']='Jâtens:BAACLgAFFH8GAAMVAAQJYxJkIgAvAQRoDAAAAgA5AGkMAAABACcAawwAAAEAPwDqDAAAAgAcABUABAljEmQiAC8BBGgMAAACADkAaQwAAAEAJwBrDAAAAQA/AOoMAAABABwAGgABCQIEqAoAJwAB6gwAAAEACgAuAAQKfxoAAhUACAmMHUMTADUCABUACAmMHUMTADUCAAAA.',
Ka='Kaelía:BAAALgAECgUJBQAAAA==.Kair:BAABLgAECn8mAAIbAAkJ/Qh6GgBfAQloDAAABgAWAGkMAAAFABQAawwAAAUAEABqDAAABQAVAGwMAAAFACAAbQwAAAMAEgDqDAAABQAfAG4MAAADABEAbwwAAAEAGAAbAAkJ/Qh6GgBfAQloDAAABgAWAGkMAAAFABQAawwAAAUAEABqDAAABQAVAGwMAAAFACAAbQwAAAMAEgDqDAAABQAfAG4MAAADABEAbwwAAAEAGAAAAA==.Kairring:BAAALgAECggJDgAAAA==.Kamehameha:BAAALgAFFAEJAQAAAA==.Kami:BAABLgAECn8sAAIbAAgJpRFbFQCTAQhoDAAABwAuAGkMAAAHADcAawwAAAcAOQBqDAAABgA7AGwMAAAFACIAbQwAAAMAKgDqDAAABgAjAG4MAAADACwAGwAICaURWxUAkwEIaAwAAAcALgBpDAAABwA3AGsMAAAHADkAagwAAAYAOwBsDAAABQAiAG0MAAADACoA6gwAAAYAIwBuDAAAAwAsAAAA.Kapslock:BAAALgAECgYJBwAAAA==.Karii:BAAALgADCgEJAQAAAA==.Karma:BAAALgADCgcJHAAAAA==.Katsicle:BAAALgAECgYJCQAAAA==.Katteya:BAAALgADCgkJMQAAAA==.Kattia:BAABLgAECn8jAAIMAAgJ0Q0wMgCUAQhoDAAABQAgAGkMAAAFAB4AawwAAAYAGABqDAAABAATAGwMAAAEACIAbQwAAAMASgDqDAAABQAeAG4MAAADABUADAAICdENMDIAlAEIaAwAAAUAIABpDAAABQAeAGsMAAAGABgAagwAAAQAEwBsDAAABAAiAG0MAAADAEoA6gwAAAUAHgBuDAAAAwAVAAAA.',
Kh='Khalico:BAAALgADCgEJAQAAAA==.Khellendros:BAAALgADCgUJBQABLgAECgYJCgABAAAAAA==.Khir:BAAALgAECgQJBwAAAA==.',
Ki='Kinomihime:BAABLgAECn8tAAIDAAkJJg8jMgDoAQloDAAABwAxAGkMAAAHAC8AawwAAAcAIgBqDAAABgAzAGwMAAAFACIAbQwAAAMAKADqDAAABgA7AG4MAAADACAAbwwAAAEACgADAAkJJg8jMgDoAQloDAAABwAxAGkMAAAHAC8AawwAAAcAIgBqDAAABgAzAGwMAAAFACIAbQwAAAMAKADqDAAABgA7AG4MAAADACAAbwwAAAEACgAAAA==.Kirajoy:BAABLgAECn8rAAIcAAgJDQW2DgD3AAhoDAAABwAWAGkMAAAHABMAawwAAAYACgBqDAAABQAKAGwMAAAFAAsAbQwAAAMABADqDAAABwASAG4MAAADAAMAHAAICQ0Ftg4A9wAIaAwAAAcAFgBpDAAABwATAGsMAAAGAAoAagwAAAUACgBsDAAABQALAG0MAAADAAQA6gwAAAcAEgBuDAAAAwADAAAA.Kirel:BAAALgADCgEJAQAAAA==.',
Kn='Knyghtt:BAABLgAECn8YAAIKAAYJ7wuiMwAGAQZoDAAABAAaAGkMAAAEACMAawwAAAQAHgBqDAAAAwARAGwMAAADAB4A6gwAAAYAHgAKAAYJ7wuiMwAGAQZoDAAABAAaAGkMAAAEACMAawwAAAQAHgBqDAAAAwARAGwMAAADAB4A6gwAAAYAHgAAAA==.',
Ko='Kogwyn:BAAALgAECggJDAAAAA==.Kogy:BAAALgADCgcJBgABLgAECggJDAABAAAAAA==.',
Kr='Kraviz:BAAALgAECgMJAwAAAA==.Krombopolous:BAAALgADCgkJGQABLgAECggJHwAMAJsLAA==.Krystle:BAABLgAECn8ZAAIMAAgJvRdVHAADAghoDAAABABZAGkMAAAEAC0AawwAAAQAKQBqDAAAAwBXAGwMAAADADYAbQwAAAEAQwDqDAAABQAzAG4MAAABAEwADAAICb0XVRwAAwIIaAwAAAQAWQBpDAAABAAtAGsMAAAEACkAagwAAAMAVwBsDAAAAwA2AG0MAAABAEMA6gwAAAUAMwBuDAAAAQBMAAAA.',
Ky='Kydormu:BAAALgADCgEJAQAAAA==.',
Le='Leftyloose:BAAALgADCgkJBAAAAA==.',
Li='Lilfonz:BAABLgAECn8aAAMUAAcJdhBzJQBrAQdoDAAABgAoAGkMAAAFACoAawwAAAUAOwBqDAAAAgAzAGwMAAADABIA6gwAAAQARgBuDAAAAQALABQABwl2EHMlAGsBB2gMAAABACgAaQwAAAEAKgBrDAAAAQA7AGoMAAABADMAbAwAAAEAEgDqDAAAAQBGAG4MAAABAAsAGAAGCbMYiHYAEgEGaAwAAAUARwBpDAAABABTAGsMAAAEADQAagwAAAEAMwBsDAAAAgBAAOoMAAADACwAAAA=.Livik:BAAALgAECgcJEgAAAA==.',
Lo='Lockofdeath:BAAALgADCgYJBwAAAA==.Lockywolf:BAAALgAECgUJBgAAAA==.Logarth:BAAALgAECgUJCAAAAA==.Longbrew:BAAALgADCgEJAQAAAA==.Loppsang:BAAALgAECgQJBgAAAA==.Lorcan:BAABLgAECn8sAAIdAAkJsRkoBABfAgloDAAABwBQAGkMAAAHAEoAawwAAAcAQgBqDAAABQBWAGwMAAAFACsAbQwAAAMAOADqDAAABgBHAG4MAAADAE4AbwwAAAEANgAdAAkJsRkoBABfAgloDAAABwBQAGkMAAAHAEoAawwAAAcAQgBqDAAABQBWAGwMAAAFACsAbQwAAAMAOADqDAAABgBHAG4MAAADAE4AbwwAAAEANgAAAA==.',
Lr='Lroye:BAABLgAFFH8GAAIeAAMJXBXkFQD4AANoDAAAAwBDAGkMAAACACcA6gwAAAEAOAAeAAMJXBXkFQD4AANoDAAAAwBDAGkMAAACACcA6gwAAAEAOAAAAA==.',
Ls='Lsdarko:BAAALgAECgEJAQAAAA==.',
Lu='Luckyleet:BAAALgADCgQJCwAAAA==.Lucyfer:BAAALgAECgUJCgABLgAECggJHAAMAFMMAA==.Lucyferr:BAAALgADCggJCAABLgAECggJHAAMAFMMAA==.Ludicrispeed:BAAALgADCgQJDgAAAA==.Luliak:BAACLgAFFH8LAAILAAQJNiLaAgCUAQRoDAAABABjAGkMAAADAEwAawwAAAEAWADqDAAAAwBWAAsABAk2ItoCAJQBBGgMAAAEAGMAaQwAAAMATABrDAAAAQBYAOoMAAADAFYALgAECn8VAAILAAgJlR+pCQBEAgALAAgJlR+pCQBEAgAAAA==.Lunabren:BAABLgAECn8YAAMQAAcJwwd8KwD8AAdoDAAABAASAGkMAAAEAB0AawwAAAQAGwBqDAAABAAlAGwMAAADAAwAbQwAAAEABwDqDAAABAAXABAABwnDB3wrAPwAB2gMAAAEABIAaQwAAAQAHQBrDAAABAAbAGoMAAAEACUAbAwAAAIADABtDAAAAQAHAOoMAAADABcADwACCaEGB44ASAACbAwAAAEABADqDAAAAQAdAAAA.Lunamina:BAAALgADCgkJLwAAAA==.',
Ly='Lynvala:BAAALgADCgQJBQAAAA==.Lysdexíc:BAABLgAECn8XAAIVAAgJaBG6NwBnAQhoDAAABABBAGkMAAAEAEUAawwAAAMAPwBqDAAAAgAxAGwMAAACABcAbQwAAAIAEADqDAAABAA7AG4MAAACAA4AFQAICWgRujcAZwEIaAwAAAQAQQBpDAAABABFAGsMAAADAD8AagwAAAIAMQBsDAAAAgAXAG0MAAACABAA6gwAAAQAOwBuDAAAAgAOAAAA.',
['Lì']='Lìllith:BAABLgAECn8ZAAMFAAgJFRmQHQDyAQhoDAAABABaAGkMAAAEAFEAawwAAAQASABqDAAAAwA9AGwMAAADAFEAbQwAAAEADwDqDAAABQA5AG4MAAABADUABQAICRUZkB0A8gEIaAwAAAMAWgBpDAAABABRAGsMAAADAEgAagwAAAMAPQBsDAAAAwBRAG0MAAABAA8A6gwAAAQAOQBuDAAAAQA1AB8AAwktCd9OAJcAA2gMAAABABEAawwAAAEAGgDqDAAAAQAZAAEuAAQKCQkxABgAuRkA.',
Ma='Majika:BAAALgADCgYJBQAAAA==.Mariophra:BAABLgAECn8dAAIHAAcJphuOFQAcAgdoDAAABwBYAGkMAAAFAEYAawwAAAQAKgBqDAAABABKAGwMAAADAFMA6gwAAAUAVQBuDAAAAQAyAAcABwmmG44VABwCB2gMAAAHAFgAaQwAAAUARgBrDAAABAAqAGoMAAAEAEoAbAwAAAMAUwDqDAAABQBVAG4MAAABADIAAAA=.Marvelious:BAAALgAFFAEJAQAAAA==.Mattlen:BAAALgADCgYJCAAAAA==.Maximumswag:BAAALgADCgkJCQABLgAECggJHwAMAJsLAA==.Maxmugruith:BAAALgADCgQJBwAAAA==.',
Me='Meatshiéld:BAAALgAECgYJCgAAAA==.',
Mi='Midopamos:BAAALgADCgEJAQAAAA==.Mikki:BAAALgADCgQJBQAAAA==.Missconduct:BAAALgADCgYJBgAAAA==.Misstorgo:BAAALgAECgUJCAAAAA==.',
Mo='Monfro:BAAALgAECgUJCgAAAA==.Moogatoo:BAAALgAECgYJCAAAAA==.Moonbane:BAABLgAECn8sAAIcAAgJTyBHAQCLAghoDAAABwBhAGkMAAAHAFMAawwAAAcAVQBqDAAABgBUAGwMAAAFAFcAbQwAAAMALQDqDAAABgBeAG4MAAADAFQAHAAICU8gRwEAiwIIaAwAAAcAYQBpDAAABwBTAGsMAAAHAFUAagwAAAYAVABsDAAABQBXAG0MAAADAC0A6gwAAAYAXgBuDAAAAwBUAAAA.Moonfanda:BAAALgADCgIJAgAAAA==.Moonmist:BAAALgADCgEJAQABLgAECgYJBwABAAAAAA==.Moor:BAAALgAECgEJAQAAAA==.',
Mu='Mumferd:BAAALgADCgQJBAAAAA==.',
My='Myaquean:BAAALgADCgQJDgAAAA==.Mystogan:BAAALgADCgUJCQAAAA==.Myth:BAAALgADCgUJBQAAAA==.',
Na='Nakeefa:BAABLgAECn8bAAMWAAkJMxM7IgDxAQloDAAABQA7AGkMAAAEADUAawwAAAQALABqDAAAAwA/AGwMAAADAD0AbQwAAAEAKQDqDAAABQA2AG4MAAABAC8AbwwAAAEAHgAWAAkJMxM7IgDxAQloDAAABQA7AGkMAAAEADUAawwAAAQALABqDAAAAQA/AGwMAAADAD0AbQwAAAEAKQDqDAAABQA2AG4MAAABAC8AbwwAAAEAHgAcAAEJAAA7cgAzAAFqDAAAAgATAAAA.Natsuu:BAABLgAECn8aAAIMAAgJohqlJgDIAQhoDAAABAAsAGkMAAAEAFIAawwAAAQAMQBqDAAAAgBRAGwMAAACAEkAbQwAAAMAWADqDAAABQBcAG4MAAACAC4ADAAICaIapSYAyAEIaAwAAAQALABpDAAABABSAGsMAAAEADEAagwAAAIAUQBsDAAAAgBJAG0MAAADAFgA6gwAAAUAXABuDAAAAgAuAAAA.Naturewolf:BAABLgAECn8eAAIRAAgJWhZECQCoAQhoDAAABQBDAGkMAAAFAEYAawwAAAUAOQBqDAAABAArAGwMAAADADEAbQwAAAEANADqDAAABQA8AG4MAAACACoAEQAICVoWRAkAqAEIaAwAAAUAQwBpDAAABQBGAGsMAAAFADkAagwAAAQAKwBsDAAAAwAxAG0MAAABADQA6gwAAAUAPABuDAAAAgAqAAAA.',
Ne='Nefertiti:BAAALgAECgQJAwAAAA==.Nekona:BAABLgAECn8VAAQWAAgJTwuCiQBGAQhoDAAABQAhAGkMAAAEACIAawwAAAMAEABqDAAAAgAmAGwMAAABADMAbQwAAAEADwDqDAAABAAoAG4MAAABAAsAFgAICU8LgokARgEIaAwAAAMAIQBpDAAABAAiAGsMAAACABAAagwAAAIAJgBsDAAAAQAzAG0MAAABAA8A6gwAAAQAKABuDAAAAQALABwAAgkKCaxbAFwAAmgMAAABAB4AawwAAAEADwAXAAEJlwWVNAAzAAFoDAAAAQAOAAAA.Neron:BAABLgAECn8xAAIYAAkJuRm0FQBdAgloDAAABwBDAGkMAAAHAFoAawwAAAcATABqDAAABgBRAGwMAAAGAFsAbQwAAAQAKgDqDAAABwBNAG4MAAAEAD0AbwwAAAEAEwAYAAkJuRm0FQBdAgloDAAABwBDAGkMAAAHAFoAawwAAAcATABqDAAABgBRAGwMAAAGAFsAbQwAAAQAKgDqDAAABwBNAG4MAAAEAD0AbwwAAAEAEwAAAA==.Nethertusk:BAABLgAECn8pAAMWAAgJkBf5KADOAQhoDAAABwA5AGkMAAAGAEAAawwAAAYARwBqDAAABQAoAGwMAAAEADUAbQwAAAMAMADqDAAABwBLAG4MAAADADMAFgAICZAX+SgAzgEIaAwAAAcAOQBpDAAABgBAAGsMAAAFAEcAagwAAAEAIgBsDAAABAA1AG0MAAADADAA6gwAAAcASwBuDAAAAwAzABwAAglhA/RZAGEAAmsMAAABAAgAagwAAAQAKAAAAA==.',
Nh='Nhancecntrl:BAAALgAECggJEgAAAA==.',
Ni='Niany:BAAALgAECgUJBwAAAA==.Nightbréaker:BAAALgADCgcJFQAAAA==.Nilospite:BAABLgAECn8aAAIGAAcJqBk4CwDFAQdoDAAABQBKAGkMAAAEAFMAawwAAAQARgBqDAAABABHAGwMAAADADsAbQwAAAEAGADqDAAABQBSAAYABwmoGTgLAMUBB2gMAAAFAEoAaQwAAAQAUwBrDAAABABGAGoMAAAEAEcAbAwAAAMAOwBtDAAAAQAYAOoMAAAFAFIAAS4ABRQFCRIADQBKFQA=.Nimposter:BAABLgAECn8bAAIJAAcJTBKUTQBkAQdoDAAABQBCAGkMAAAFADwAawwAAAUALgBqDAAAAwApAGwMAAADACQA6gwAAAUAMwBuDAAAAQATAAkABwlMEpRNAGQBB2gMAAAFAEIAaQwAAAUAPABrDAAABQAuAGoMAAADACkAbAwAAAMAJADqDAAABQAzAG4MAAABABMAAAA=.',
Nj='Njoror:BAAALgADCgQJBAAAAA==.',
No='Noodle:BAAALgADCgEJAQAAAA==.Nottapally:BAAALgAECgcJEAAAAA==.',
Nu='Nullea:BAAALgAECgYJCAAAAA==.',
Ny='Nyxthos:BAAALgADCggJCAAAAA==.',
Ob='Obizi:BAAALgADCgcJBwAAAA==.',
Oc='Ocatarineta:BAAALgADCgIJAgAAAA==.',
Od='Odito:BAAALgAECgUJCgAAAA==.',
Oo='Oopslol:BAAALgAECgYJDAAAAA==.',
Os='Osdavalmarro:BAAALgADCgYJGQAAAA==.',
Ot='Othaerion:BAABLgAECn8UAAIUAAgJtQ8OHwCeAQhoDAAAAwBSAGkMAAACADoAawwAAAMAJQBqDAAABAAiAGwMAAADAC0AbQwAAAEACgDqDAAAAgAWAG4MAAACAB8AFAAICbUPDh8AngEIaAwAAAMAUgBpDAAAAgA6AGsMAAADACUAagwAAAQAIgBsDAAAAwAtAG0MAAABAAoA6gwAAAIAFgBuDAAAAgAfAAAA.',
Ou='Outerlimits:BAABLgAECn8kAAIgAAcJwhreBACrAQdoDAAABwBPAGkMAAAHAE4AawwAAAYARABqDAAABQA8AGwMAAAEAFIA6gwAAAUAQQBuDAAAAgAjACAABwnCGt4EAKsBB2gMAAAHAE8AaQwAAAcATgBrDAAABgBEAGoMAAAFADwAbAwAAAQAUgDqDAAABQBBAG4MAAACACMAAAA=.',
Pa='Paindore:BAAALgAECgQJBAAAAA==.Pamboo:BAABLgAECn8oAAIUAAgJhRBzGwC8AQhoDAAABgBIAGkMAAAGACQAawwAAAYAJQBqDAAABQBDAGwMAAAEAB0AbQwAAAIAEQDqDAAABwA1AG4MAAAEABcAFAAICYUQcxsAvAEIaAwAAAYASABpDAAABgAkAGsMAAAGACUAagwAAAUAQwBsDAAABAAdAG0MAAACABEA6gwAAAcANQBuDAAABAAXAAAA.',
Pe='Pearle:BAABLgAECn8gAAINAAgJPh3dCgDeAQhoDAAABQBcAGkMAAAFAFwAawwAAAUAVABqDAAAAwBQAGwMAAADAEgAbQwAAAMAPwDqDAAABQBRAG4MAAADACQADQAICT4d3QoA3gEIaAwAAAUAXABpDAAABQBcAGsMAAAFAFQAagwAAAMAUABsDAAAAwBIAG0MAAADAD8A6gwAAAUAUQBuDAAAAwAkAAAA.',
Ph='Phyg:BAAALgAECgQJBQABLgAECgUJBwABAAAAAA==.',
Po='Pokimane:BAAALgADCggJDwAAAA==.Polyasap:BAAALgADCgQJBAAAAA==.',
Pr='Proximal:BAAALgAECgcJBwAAAA==.',
Pu='Pukka:BAAALgADCgcJEQABLgAECggJIQAFAIUaAA==.Punk:BAAALgAFFAEJAQAAAA==.',
Qa='Qahnaarin:BAAALgADCgEJAQAAAA==.',
Ra='Rajax:BAAALgAECgYJBgAAAA==.Ralphthedh:BAAALgAECggJBQAAAA==.Ramindizzle:BAABLgAECn8tAAITAAgJcxWTBQDcAQhoDAAABwA8AGkMAAAHAEIAawwAAAcALwBqDAAABgBHAGwMAAAFAEoAbQwAAAIAIgDqDAAABwBGAG4MAAAEAB8AEwAICXMVkwUA3AEIaAwAAAcAPABpDAAABwBCAGsMAAAHAC8AagwAAAYARwBsDAAABQBKAG0MAAACACIA6gwAAAcARgBuDAAABAAfAAAA.Rangewolf:BAAALgADCgcJDgAAAA==.',
Re='Rejuvasap:BAABLgAECn8WAAMQAAgJLxpTKQC1AQhoDAAABABOAGkMAAADAEcAawwAAAQASgBqDAAAAwAhAGwMAAACAEoAbQwAAAEAPADqDAAABABFAG4MAAABACcAEAAICS8aUykAtQEIaAwAAAQATgBpDAAAAQBHAGsMAAADAEoAagwAAAEAIQBsDAAAAQBKAG0MAAABADwA6gwAAAMARQBuDAAAAQAnAA8ABQnfHO4oAJsBBWkMAAACADYAawwAAAEAXQBqDAAAAgBbAGwMAAABAFAA6gwAAAEAMgAAAA==.Reliri:BAAALgADCgMJAwAAAA==.Remlin:BAAALgADCgcJCAAAAA==.Retsall:BAAALgADCgUJBQAAAA==.Reâper:BAAALgAECgYJCgAAAA==.',
Ri='Rikal:BAAALgADCgQJCgAAAA==.',
Ro='Rook:BAABLgAECn8sAAITAAkJNgykBwCaAQloDAAABwAhAGkMAAAHADEAawwAAAcAHgBqDAAABgAeAGwMAAAFABsAbQwAAAMAJQDqDAAABgAjAG4MAAACABIAbwwAAAEAEQATAAkJNgykBwCaAQloDAAABwAhAGkMAAAHADEAawwAAAcAHgBqDAAABgAeAGwMAAAFABsAbQwAAAMAJQDqDAAABgAjAG4MAAACABIAbwwAAAEAEQAAAA==.Roye:BAACLgAFFH8MAAIYAAQJog0BIgA3AQRoDAAABAAkAGkMAAACABEAawwAAAIANwDqDAAABAAeABgABAmiDQEiADcBBGgMAAAEACQAaQwAAAIAEQBrDAAAAgA3AOoMAAAEAB4ALgAECn8eAAIYAAkJdR21GgDJAgAYAAkJdR21GgDJAgAAAA==.',
Ru='Ruffiyo:BAABLgAECn8mAAMVAAkJ0RFXLwCJAQloDAAABgAnAGkMAAAGADYAawwAAAYANABqDAAABAA/AGwMAAAEADgAbQwAAAMANgDqDAAABQA6AG4MAAADABgAbwwAAAEAGAAVAAgJuhFXLwCJAQhoDAAABQAnAGkMAAAEADAAawwAAAMANABqDAAAAgAzAGwMAAADADgAbQwAAAMANgDqDAAABAArAG4MAAACABYAGQAICd0PiS0AXwEIaAwAAAEAGQBpDAAAAgA2AGsMAAADADAAagwAAAIAPwBsDAAAAQAwAOoMAAABADoAbgwAAAEAGABvDAAAAQAYAAAA.Rugrahfreaky:BAABLgAECn8fAAIPAAkJSBx0BwDmAgloDAAABABYAGkMAAAEAD4AawwAAAQATABqDAAABABKAGwMAAADAEcAbQwAAAMAPgDqDAAABABEAG4MAAADAE4AbwwAAAIARQAPAAkJSBx0BwDmAgloDAAABABYAGkMAAAEAD4AawwAAAQATABqDAAABABKAGwMAAADAEcAbQwAAAMAPgDqDAAABABEAG4MAAADAE4AbwwAAAIARQAAAA==.Rugrahh:BAABLgAECn8gAAITAAkJrx5JDwDGAgloDAAABgBUAGkMAAAFAFkAawwAAAUAVgBqDAAABAA6AGwMAAADAFUAbQwAAAEAVwDqDAAABQBcAG4MAAACADgAbwwAAAEALAATAAkJrx5JDwDGAgloDAAABgBUAGkMAAAFAFkAawwAAAUAVgBqDAAABAA6AGwMAAADAFUAbQwAAAEAVwDqDAAABQBcAG4MAAACADgAbwwAAAEALAAAAA==.Ruthen:BAAALgAECgQJBQAAAA==.Ruìn:BAAALgAECgMJAwAAAA==.',
Sa='Sabermore:BAAALgAECgQJCAAAAA==.Sabina:BAABLgAECn8tAAIIAAkJgAn8IABZAQloDAAABwApAGkMAAAHABsAawwAAAcAGQBqDAAABgATAGwMAAAFAAsAbQwAAAMAJQDqDAAABgAiAG4MAAADAAcAbwwAAAEACAAIAAkJgAn8IABZAQloDAAABwApAGkMAAAHABsAawwAAAcAGQBqDAAABgATAGwMAAAFAAsAbQwAAAMAJQDqDAAABgAiAG4MAAADAAcAbwwAAAEACAAAAA==.Sadako:BAAALgAECgYJBgABLgAECggJHAAMAFMMAA==.Sadness:BAAALgADCgkJNgAAAA==.Sadorick:BAAALgADCgkJLwAAAA==.Safira:BAAALgAECgQJBgABLgAECgkJMQAYALkZAA==.Sageguy:BAAALgADCgkJIwAAAA==.Sango:BAABLgAECn8oAAMZAAgJzxFnDwCgAQhoDAAABgAwAGkMAAAGAD0AawwAAAYAKwBqDAAABQA0AGwMAAAFADcAbQwAAAMAJwDqDAAABgAyAG4MAAADABMAGQAICc8RZw8AoAEIaAwAAAUAMABpDAAABAA9AGsMAAAEACsAagwAAAUANABsDAAABQA3AG0MAAADACcA6gwAAAQAMgBuDAAAAwATABUABAnaAozBAHwABGgMAAABAAMAaQwAAAIACgBrDAAAAgAFAOoMAAACAAkAAAA=.Saucewalker:BAAALgAECgIJAgAAAA==.Savagelykill:BAAALgAECgQJDgAAAA==.',
Sc='Scotch:BAABLgAECn8jAAMYAAgJzRotKADxAQhoDAAABABGAGkMAAAFAFQAawwAAAUASgBqDAAABABNAGwMAAAEAD0AbQwAAAMAQgDqDAAABwBYAG4MAAADACMAGAAICc0aLSgA8QEIaAwAAAQARgBpDAAABQBUAGsMAAAEAEoAagwAAAMAMQBsDAAABAA9AG0MAAADAEIA6gwAAAcAWABuDAAAAwAjACEAAglxEccxAIcAAmsMAAABACwAagwAAAEATQAAAA==.Scotchnwater:BAAALgAECgUJCAAAAA==.Scrubyheals:BAAALgADCgQJBwAAAA==.',
Se='Sendio:BAAALgAECgQJBAAAAA==.Senji:BAAALgADCgQJBAAAAA==.',
Sg='Sgtpayne:BAAALgADCgIJAgAAAA==.',
Sh='Shadowcrwlr:BAAALgAECgMJBgAAAA==.Shadowlock:BAAALgAECggJEwAAAA==.Shadowmane:BAAALgADCgQJBAAAAA==.Shaeixia:BAAALgADCgcJBwAAAA==.Shamangroo:BAAALgADCggJCQABLgAECgMJAwABAAAAAA==.Shammying:BAAALgAECgMJAwAAAA==.Shamsham:BAAALgADCgIJAgAAAA==.Sharaaz:BAAALgADCgUJBQAAAA==.Shivalry:BAAALgADCgkJCwAAAA==.Shmiggy:BAAALgAECgMJAwAAAA==.',
Si='Silverywine:BAAALgADCgkJCQAAAA==.Silverywolfe:BAAALgADCgkJLwAAAA==.Simony:BAABLgAECn8XAAIYAAYJ1QYblQDYAAZoDAAABQAZAGkMAAAFABgAawwAAAUAEwBqDAAABAAhAGwMAAADAAkA6gwAAAEABwAYAAYJ1QYblQDYAAZoDAAABQAZAGkMAAAFABgAawwAAAUAEwBqDAAABAAhAGwMAAADAAkA6gwAAAEABwABLgAECggJHAAMAFMMAA==.Sinton:BAAALgADCgIJAgAAAA==.',
Sk='Skorpyoh:BAAALgADCgYJBgAAAA==.Skovak:BAAALgAECgYJEAAAAA==.Skybright:BAAALgAECgEJAQAAAA==.',
So='Soggy:BAAALgAECgcJBwAAAA==.Sorayae:BAABLgAECn8hAAIFAAgJhRr0EwA/AghoDAAABQBRAGkMAAAFAFYAawwAAAUAUgBqDAAABAA9AGwMAAAEAC0AbQwAAAIANQDqDAAABQBSAG4MAAADADEABQAICYUa9BMAPwIIaAwAAAUAUQBpDAAABQBWAGsMAAAFAFIAagwAAAQAPQBsDAAABAAtAG0MAAACADUA6gwAAAUAUgBuDAAAAwAxAAAA.',
Sp='Specialk:BAAALgADCgkJKAAAAA==.Spinnykat:BAAALgADCggJCAAAAA==.',
St='Starmist:BAAALgADCgMJAwAAAA==.Stinkfoot:BAAALgAECgIJAgAAAA==.Stoo:BAAALgADCgkJHAAAAA==.Stormkissed:BAAALgAECgUJCAAAAA==.',
Su='Sunil:BAABLgAECn8kAAIFAAgJexSPEAD1AQhoDAAABgBMAGkMAAAGAFYAawwAAAYAPQBqDAAABAAmAGwMAAAEACYAbQwAAAIAFQDqDAAABgBPAG4MAAACABEABQAICXsUjxAA9QEIaAwAAAYATABpDAAABgBWAGsMAAAGAD0AagwAAAQAJgBsDAAABAAmAG0MAAACABUA6gwAAAYATwBuDAAAAgARAAAA.Suviqhabo:BAAALgAECggJDwAAAA==.',
Sv='Svala:BAAALgADCgYJBgAAAA==.',
Sy='Syclone:BAABLgAECn8gAAIGAAgJOyGeAwCTAghoDAAABQBUAGkMAAAFAGMAawwAAAQAYgBqDAAAAwBgAGwMAAAEAFEAbQwAAAMAUADqDAAABQBhAG4MAAADADYABgAICTshngMAkwIIaAwAAAUAVABpDAAABQBjAGsMAAAEAGIAagwAAAMAYABsDAAABABRAG0MAAADAFAA6gwAAAUAYQBuDAAAAwA2AAAA.Syladen:BAAALgAECgYJEgAAAA==.Syleste:BAAALgAECgQJBAABLgAECggJIAAGADshAA==.Syvi:BAAALgAECgYJBQABLgAECggJDAABAAAAAA==.',
Ta='Tahwe:BAAALgADCgUJBQAAAA==.Tattianna:BAAALgAECgMJAwAAAA==.Tavendar:BAAALgAECgMJAwABLgAFFAMJCQAHADkNAA==.Tavil:BAAALgADCgMJAwAAAA==.Taírn:BAAALgAECgYJEAAAAA==.',
Te='Techie:BAAALgAECgcJDgAAAA==.Terradactyl:BAAALgADCgMJAwAAAA==.',
Th='Thunderslate:BAAALgAECgYJBwAAAA==.Thôrin:BAAALgADCgkJFQAAAA==.',
Ti='Tigerlillee:BAAALgADCgcJDQAAAA==.Tigreth:BAABLgAECn8sAAMYAAkJxhLSKADuAQloDAAABgBTAGkMAAAHAD4AawwAAAcAIgBqDAAABgA3AGwMAAAFADcAbQwAAAMAJwDqDAAABgA2AG4MAAADABsAbwwAAAEAGwAYAAkJxhLSKADuAQloDAAABgBTAGkMAAAHAD4AawwAAAcAIgBqDAAABQA3AGwMAAAEADcAbQwAAAMAJwDqDAAABgA2AG4MAAADABsAbwwAAAEAGwAhAAIJlhSuNgBoAAJqDAAAAQAtAGwMAAABADQAAAA=.Timotheus:BAAALgAECgQJBgAAAA==.',
To='Tonï:BAAALgADCggJCAAAAA==.',
Tr='Tragik:BAABLgAECn8fAAIiAAgJZwzbCgB3AQhoDAAABQAdAGkMAAAFACUAawwAAAUAIwBqDAAABQAlAGwMAAADADMAbQwAAAEAFADqDAAABQAjAG4MAAACAAwAIgAICWcM2woAdwEIaAwAAAUAHQBpDAAABQAlAGsMAAAFACMAagwAAAUAJQBsDAAAAwAzAG0MAAABABQA6gwAAAUAIwBuDAAAAgAMAAAA.',
Tt='Ttrouble:BAAALgADCgUJBQAAAA==.',
Tu='Tuugadark:BAABLgAECn8pAAIWAAgJZB12HAARAghoDAAABgBOAGkMAAAGAFMAawwAAAYATABqDAAABQBMAGwMAAAEAFIAbQwAAAMAWgDqDAAABwA/AG4MAAAEADQAFgAICWQddhwAEQIIaAwAAAYATgBpDAAABgBTAGsMAAAGAEwAagwAAAUATABsDAAABABSAG0MAAADAFoA6gwAAAcAPwBuDAAABAA0AAAA.Tuugashox:BAAALgAECgUJBQAAAA==.',
Ul='Ulyaoth:BAABLgAECn8bAAIWAAYJEQZSkQCxAAZoDAAABgAcAGkMAAAFAAQAawwAAAUACQBqDAAAAwAXAGwMAAADAAkA6gwAAAUAGQAWAAYJEQZSkQCxAAZoDAAABgAcAGkMAAAFAAQAawwAAAUACQBqDAAAAwAXAGwMAAADAAkA6gwAAAUAGQAAAA==.',
Un='Unnerfable:BAAALgAECgQJBgAAAA==.',
Uw='Uwa:BAAALgADCgMJAwAAAA==.',
Uy='Uy:BAAALgAECgYJDwAAAA==.',
Va='Valakha:BAAALgAECgQJCQAAAA==.Valkyrie:BAAALgAECgQJBgAAAA==.',
Ve='Vedros:BAAALgADCgQJBwAAAA==.',
Vi='Viktoros:BAAALgAECgIJAgAAAA==.Violetra:BAAALgADCgMJAwAAAA==.',
Vo='Vorcan:BAAALgADCgYJBgAAAA==.Vorukh:BAAALgAECggJEgAAAA==.',
Vr='Vrave:BAAALgADCgQJBQAAAA==.',
Vy='Vyhlet:BAAALgADCgkJOAABLgAECggJLAAHANQeAA==.',
Wa='Warriorgroo:BAAALgAECgMJAwAAAA==.',
We='Wendish:BAAALgAECgEJBwAAAA==.Wertyda:BAABLgAECn8ZAAIUAAkJsxR1FAD8AQloDAAABABWAGkMAAAFAEsAawwAAAQASwBqDAAAAgAwAGwMAAACAC8AbQwAAAIADwDqDAAABAA3AG4MAAABACIAbwwAAAEAJQAUAAkJsxR1FAD8AQloDAAABABWAGkMAAAFAEsAawwAAAQASwBqDAAAAgAwAGwMAAACAC8AbQwAAAIADwDqDAAABAA3AG4MAAABACIAbwwAAAEAJQAAAA==.',
Wh='Whácker:BAABLgAECn8UAAMdAAgJOwp1EwA2AQhoDAAABQA7AGkMAAADACMAawwAAAMAIgBqDAAAAgAmAGwMAAACAAoAbQwAAAIAEwDqDAAAAQAJAG4MAAACAA4AHQAICTsKdRMANgEIaAwAAAQAOwBpDAAAAgAjAGsMAAACACIAagwAAAIAJgBsDAAAAgAKAG0MAAACABMA6gwAAAEACQBuDAAAAgAOAAYAAwmsCC05AIEAA2gMAAABABEAaQwAAAEAGABrDAAAAQAXAAEuAAQKBgkQAAEAAAAA.',
Wi='Wickedslicks:BAABLgAECn8jAAIQAAgJcx9BBwB1AghoDAAABgBQAGkMAAAHAEcAawwAAAYAUABqDAAABQBCAGwMAAAFAEwAbQwAAAEAWwDqDAAAAwBRAG4MAAACAFIAEAAICXMfQQcAdQIIaAwAAAYAUABpDAAABwBHAGsMAAAGAFAAagwAAAUAQgBsDAAABQBMAG0MAAABAFsA6gwAAAMAUQBuDAAAAgBSAAAA.Wildthangg:BAAALgAECgIJAgAAAA==.',
Wo='Wooddchipper:BAAALgADCgYJBgAAAA==.',
Wr='Wreckshop:BAABLgAECn8XAAIJAAgJjhqeNAC4AQhoDAAABABaAGkMAAAEAF4AawwAAAQATwBqDAAAAwBbAGwMAAADAEkAbQwAAAEANwDqDAAAAwBAAG4MAAABABIACQAICY4anjQAuAEIaAwAAAQAWgBpDAAABABeAGsMAAAEAE8AagwAAAMAWwBsDAAAAwBJAG0MAAABADcA6gwAAAMAQABuDAAAAQASAAAA.',
Wt='Wtfoxtrot:BAAALgADCgkJDAAAAA==.',
Xe='Xenøcide:BAAALgAECgcJEwAAAA==.',
Xx='Xxlockz:BAAALgAECgcJEwAAAA==.Xxpallyz:BAAALgAECgEJAwABLgAECgcJEwABAAAAAA==.',
Yi='Yinger:BAAALgADCgcJEAAAAA==.Yinglang:BAAALgADCgEJAQAAAA==.Yingling:BAABLgAECn8mAAIJAAgJRxk1LwDPAQhoDAAABgBLAGkMAAAGAE0AawwAAAYAOQBqDAAABQAuAGwMAAAFAFEAbQwAAAEAEADqDAAABwBNAG4MAAACAEMACQAICUcZNS8AzwEIaAwAAAYASwBpDAAABgBNAGsMAAAGADkAagwAAAUALgBsDAAABQBRAG0MAAABABAA6gwAAAcATQBuDAAAAgBDAAAA.',
Yo='Yohh:BAAALgAECgMJCAAAAA==.',
Yu='Yukara:BAAALgADCgYJBgAAAA==.Yuriko:BAABLgAECn8tAAIjAAkJkRF1EwDXAQloDAAABwArAGkMAAAHAEQAawwAAAcAPgBqDAAABgAzAGwMAAAFADMAbQwAAAMAJQDqDAAABgAeAG4MAAADACIAbwwAAAEAGAAjAAkJkRF1EwDXAQloDAAABwArAGkMAAAHAEQAawwAAAcAPgBqDAAABgAzAGwMAAAFADMAbQwAAAMAJQDqDAAABgAeAG4MAAADACIAbwwAAAEAGAAAAA==.',
Za='Zaidan:BAAALgADCgcJDgAAAA==.Zanpaktu:BAAALgAECgQJBwAAAA==.Zaraha:BAAALgADCgEJAQAAAA==.Zata:BAAALgAECgUJBwAAAA==.',
Ze='Zeref:BAAALgAECgYJDAAAAA==.Zeur:BAAALgAECgEJAQAAAA==.Zevgrip:BAAALgAECgQJBQAAAA==.',
Zh='Zhia:BAAALgAECgQJBQAAAA==.',
Zi='Zippitydooda:BAAALgADCgQJBAABLgAECgYJBwABAAAAAA==.',
Zo='Zodiacc:BAABLgAECn8uAAISAAgJbhzKBAA8AghoDAAABwBTAGkMAAAHAFQAawwAAAcAXwBqDAAABgBRAGwMAAAFAFAAbQwAAAMALQDqDAAABwBIAG4MAAAEAC8AEgAICW4cygQAPAIIaAwAAAcAUwBpDAAABwBUAGsMAAAHAF8AagwAAAYAUQBsDAAABQBQAG0MAAADAC0A6gwAAAcASABuDAAABAAvAAAA.Zornhealer:BAAALgADCggJEAABLgAECgUJCgABAAAAAA==.',
['Zö']='Zölä:BAAALgAECgMJAwAAAA==.',
['Ât']='Âtomic:BAAALgADCgYJAgABLgAECgYJEAABAAAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
