local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Priest-Discipline','Unknown-Unknown','Priest-Holy','Mage-Frost','Monk-Mistweaver','Priest-Shadow','Warrior-Fury','Paladin-Holy','Monk-Windwalker','Druid-Restoration','Warlock-Demonology','DeathKnight-Unholy','DeathKnight-Frost','Mage-Arcane','Paladin-Retribution','Monk-Brewmaster','Druid-Feral','Evoker-Augmentation','Evoker-Devastation','DeathKnight-Blood','Warrior-Arms','DemonHunter-Devourer','Hunter-Survival','Hunter-BeastMastery','Hunter-Marksmanship','Shaman-Enhancement','Shaman-Restoration','Shaman-Elemental','DemonHunter-Vengeance','Evoker-Preservation','Druid-Guardian','Druid-Balance','Mage-Fire','Warrior-Protection','Paladin-Protection',}
local provider = {region='US',realm='Gundrak',name='US',type='daily',zone=46,date='2026-05-10',data={Ad='Adelyne:BAAALgAECgQJCgABLgAFFAUJDgABAG0SAA==.Adera:BAAALgAECgYJBwAAAA==.Adria:BAAALgAECgEJAgAAAA==.',
Af='Aff:BAAALgADCgYJBgAAAA==.',
Ag='Agony:BAAALgAECgEJAQAAAA==.',
Ah='Ahkanon:BAAALgADCgEJAQAAAA==.',
Ai='Aiden:BAAALgAECgEJAgABLgAECgIJAgACAAAAAA==.Aidendk:BAAALgADCgIJAgABLgAECgIJAgACAAAAAA==.Aidenp:BAAALgADCgIJAgABLgAECgIJAgACAAAAAA==.Air:BAAALgADCgcJBwABLgAFFAYJGQADAP0dAA==.',
Ak='Aku:BAAALgADCgIJBAAAAA==.',
Al='Aleniastra:BAAALgAECgUJDQAAAA==.Alexyss:BAAALgAECgUJDgAAAA==.Alykard:BAABLgAECn8lAAIEAAkJNw60MwDaAQloDAAABgAyAGkMAAAFAC0AawwAAAUAMgBqDAAABQAxAGwMAAAEADEAbQwAAAIAGwDqDAAABQAcAG4MAAADABYAbwwAAAIAEAAEAAkJNw60MwDaAQloDAAABgAyAGkMAAAFAC0AawwAAAUAMgBqDAAABQAxAGwMAAAEADEAbQwAAAIAGwDqDAAABQAcAG4MAAADABYAbwwAAAIAEAAAAA==.',
Am='Amyara:BAAALgADCgEJAQAAAA==.',
An='Andronicas:BAAALgAECgcJDgAAAA==.Aneira:BAABLgAFFH8GAAIEAAIJRgQ5cgCRAAJoDAAABAAGAOoMAAACAA8ABAACCUYEOXIAkQACaAwAAAQABgDqDAAAAgAPAAAA.',
Ap='Apexis:BAAALgADCgYJCQAAAA==.',
Ar='Ariaa:BAAALgAECgIJBAAAAA==.Arieyri:BAAALgADCgcJBwAAAA==.Artpop:BAAALgAFFAEJAQABLgAFFAUJDQAFAJATAA==.',
As='Ash:BAAALgADCgcJCwAAAA==.Aspect:BAAALgADCgcJDgABLgAECgEJAQACAAAAAA==.Astarael:BAABLgAECn8hAAMGAAgJGhZbDgDzAQhoDAAABQBKAGkMAAAFADsAawwAAAQALABqDAAABABHAGwMAAAEADUAbQwAAAMAJQDqDAAABgBPAG4MAAACAC8ABgAICRoWWw4A8wEIaAwAAAUASgBpDAAABAA7AGsMAAADACwAagwAAAMARwBsDAAAAwA1AG0MAAACACUA6gwAAAYATwBuDAAAAQAvAAMABgljD+BaAMgABmkMAAABABcAawwAAAEAHQBqDAAAAQAgAGwMAAABACwAbQwAAAEAOQBuDAAAAQAyAAAA.',
Av='Avi:BAABLgAECn8XAAIBAAgJkRD5EADTAQhoDAAAAwAoAGkMAAADAC8AawwAAAMAJwBqDAAABAAqAGwMAAAEADAAbQwAAAEAGgDqDAAABABBAG4MAAABAB0AAQAICZEQ+RAA0wEIaAwAAAMAKABpDAAAAwAvAGsMAAADACcAagwAAAQAKgBsDAAABAAwAG0MAAABABoA6gwAAAQAQQBuDAAAAQAdAAEuAAQKCQlpAAcAFx4A.',
Ba='Babygurl:BAABLgAECn9tAAIIAAkJ7SV0AACtAwloDAAADwBjAGkMAAAOAGMAawwAAA8AYwBqDAAADgBjAGwMAAAOAFwAbQwAAAsAYgDqDAAADgBgAG4MAAAHAFwAbwwAAAUAYAAIAAkJ7SV0AACtAwloDAAADwBjAGkMAAAOAGMAawwAAA8AYwBqDAAADgBjAGwMAAAOAFwAbQwAAAsAYgDqDAAADgBgAG4MAAAHAFwAbwwAAAUAYAAAAA==.Baragas:BAAALgAECgUJCQAAAA==.Barney:BAAALgADCgEJAQAAAA==.Battosaî:BAAALgAECgQJBAAAAA==.',
Be='Beeny:BAACLgAFFH8sAAIFAAYJJyNHAgBSAgZoDAAABwBfAGkMAAAKAGAAawwAAAcASgBqDAAABwBVAGwMAAAEAGEA6gwAAAkAWgAFAAYJJyNHAgBSAgZoDAAABwBfAGkMAAAKAGAAawwAAAcASgBqDAAABwBVAGwMAAAEAGEA6gwAAAkAWgAuAAQKfz8AAwUACAmUI4UIAMwCAAUABwmlJIUIAMwCAAkAAQlsEJBcADoAAAAA.Berat:BAAALgADCgIJAgAAAA==.Berzerker:BAAALgADCgcJEwAAAA==.',
Bg='Bgc:BAAALgADCgUJBQAAAA==.',
Bi='Binari:BAAALgAECgMJAwABLgAFFAMJBQAHACoUAA==.Binlock:BAAALgAECgQJBAABLgAFFAMJBQAHACoUAA==.',
Bl='Bl:BAAALgAECgMJAwAAAA==.Bladebear:BAABLgAECn82AAIEAAkJUhUqIgAoAgloDAAACABNAGkMAAAHAD4AawwAAAcAQgBqDAAABwBKAGwMAAAHAFAAbQwAAAQAKgDqDAAABwA3AG4MAAAEAB8AbwwAAAMAEwAEAAkJUhUqIgAoAgloDAAACABNAGkMAAAHAD4AawwAAAcAQgBqDAAABwBKAGwMAAAHAFAAbQwAAAQAKgDqDAAABwA3AG4MAAAEAB8AbwwAAAMAEwAAAA==.',
Bo='Boose:BAAALgAECgYJBgAAAA==.Bootybreaker:BAAALgADCgcJBwAAAA==.',
Br='Brat:BAAALgAECgEJBAAAAA==.Bréwmaster:BAAALgAECgEJAQABLgAECggJIQAGABoWAA==.',
Bu='Bubbleez:BAAALgADCgUJBQAAAA==.Bucklord:BAABLgAECn8iAAMGAAgJjRn+FgAuAghoDAAABQBMAGkMAAAFAFEAawwAAAYAUQBqDAAABQBMAGwMAAAGAFUAbQwAAAEABADqDAAABQBSAG4MAAABAC4ABgAICY0Z/hYALgIIaAwAAAUATABpDAAABQBRAGsMAAAGAFEAagwAAAUATABsDAAABgBVAG0MAAABAAQA6gwAAAQAUgBuDAAAAQAuAAMAAQkAGbVLAEEAAeoMAAABAEAAAAA=.Budin:BAAALgAECggJEgAAAA==.Bullmann:BAAALgADCgQJBAAAAA==.',
Ca='Cannibal:BAABLgAECn8dAAIKAAgJ0xu7DgByAghoDAAABQBDAGkMAAAEAEEAawwAAAUAVQBqDAAABABDAGwMAAAEAFYAbQwAAAEARwDqDAAABQBTAG4MAAABACsACgAICdMbuw4AcgIIaAwAAAUAQwBpDAAABABBAGsMAAAFAFUAagwAAAQAQwBsDAAABABWAG0MAAABAEcA6gwAAAUAUwBuDAAAAQArAAAA.Caplock:BAABLgAECn8VAAILAAYJoRFlhABRAQZoDAAABAA/AGkMAAAEAB0AawwAAAQALABqDAAAAwAnAGwMAAADACgA6gwAAAMALgALAAYJoRFlhABRAQZoDAAABAA/AGkMAAAEAB0AawwAAAQALABqDAAAAwAnAGwMAAADACgA6gwAAAMALgAAAA==.Capri:BAAALgAECgUJDQAAAA==.',
Ce='Cellun:BAAALgAECgUJEAAAAA==.Centipede:BAAALgAECgYJBgABLgAECgYJEQACAAAAAA==.Ceredis:BAAALgAECgUJCwAAAA==.',
Ch='Choomoo:BAAALgADCgcJCwABLgAFFAMJCAAFAOEJAA==.',
Cl='Cleankarma:BAAALgADCgEJAwAAAA==.',
Co='Comet:BAAALgAECgEJAQAAAA==.Cool:BAAALgAFFAIJAgAAAA==.Corwiggs:BAAALgAECgYJCwAAAA==.',
Cr='Crikey:BAAALgAECgUJBwAAAA==.Crimínal:BAAALgADCgcJCwAAAA==.Cripsee:BAAALgADCgIJAgAAAA==.',
Cu='Curbie:BAAALgAECgIJAwAAAA==.',
['Cô']='Cônvict:BAAALgADCgYJBgAAAA==.',
De='Deacknight:BAABLgAECn8cAAMMAAgJwRuMLgB+AghoDAAAAwBLAGkMAAADAFgAawwAAAMAXwBqDAAABABPAGwMAAAFAGEAbQwAAAQAJQDqDAAABQBRAG4MAAABABUADAAICcEbjC4AfgIIaAwAAAMASwBpDAAAAgBYAGsMAAADAF8AagwAAAQATwBsDAAABQBhAG0MAAAEACUA6gwAAAUAUQBuDAAAAQAVAA0AAQmKDYAXADIAAWkMAAABACIAAS4AAwoGCQcAAgAAAAA=.Deacmonk:BAAALgADCgYJBgABLgADCgYJBwACAAAAAA==.Definitely:BAACLgAFFH8LAAIEAAMJAxteNgC+AANoDAAABgBfAGkMAAAEAEAA6gwAAAEALwAEAAMJAxteNgC+AANoDAAABgBfAGkMAAAEAEAA6gwAAAEALwAuAAQKfysAAwQACAmaI8AMAMECAAQACAmaI8AMAMECAA4AAQkPICobAD8AAAAA.Deki:BAEALgAECgYJBgAAAA==.Dementiaous:BAAALgAECgIJAwAAAA==.Desariana:BAABLgAECn8fAAIPAAgJ9RDmPwCQAQhoDAAAAwA3AGkMAAAFADEAawwAAAUAMABqDAAABABCAGwMAAAEADQAbQwAAAEAEgDqDAAABgAqAG4MAAADACUADwAICfUQ5j8AkAEIaAwAAAMANwBpDAAABQAxAGsMAAAFADAAagwAAAQAQgBsDAAABAA0AG0MAAABABIA6gwAAAYAKgBuDAAAAwAlAAAA.',
Di='Diggitie:BAAALgAECgEJAQAAAA==.',
Do='Dormas:BAAALgAECgYJEQAAAA==.Doug:BAAALgADCgEJAQAAAA==.',
Dr='Drakeon:BAAALgAECgUJBgABLgAECgkJaQAHABceAA==.',
Ee='Eeryxx:BAAALgAECgEJAQAAAA==.',
El='Eldh:BAABLgAECn8ZAAIQAAgJVAsVHgBKAQhoDAAABQAaAGkMAAAEACYAawwAAAQAJgBqDAAAAwAkAGwMAAADACoAbQwAAAEABwDqDAAABAAXAG4MAAABABoAEAAICVQLFR4ASgEIaAwAAAUAGgBpDAAABAAmAGsMAAAEACYAagwAAAMAJABsDAAAAwAqAG0MAAABAAcA6gwAAAQAFwBuDAAAAQAaAAAA.Eleison:BAAALgADCgMJAwAAAA==.Elendrial:BAAALgAECgIJAgAAAA==.Elendril:BAAALgADCgcJFQAAAA==.Elisoly:BAABLgAECn8ZAAIIAAYJohmjHwCWAQZoDAAABABXAGkMAAAEAEQAawwAAAUAPgBqDAAABABNAGwMAAADAC0A6gwAAAUANAAIAAYJohmjHwCWAQZoDAAABABXAGkMAAAEAEQAawwAAAUAPgBqDAAABABNAGwMAAADAC0A6gwAAAUANAAAAA==.',
Em='Emrald:BAAALgAECgYJEwAAAA==.',
En='Endlessly:BAACLgAFFH8JAAIRAAMJpBasBAATAQNoDAAABABOAGkMAAADADUA6gwAAAIAKgARAAMJpBasBAATAQNoDAAABABOAGkMAAADADUA6gwAAAIAKgAuAAQKfyIAAhEACAmfIukDAOsCABEACAmfIukDAOsCAAAA.Enerchi:BAAALgADCgMJAwAAAA==.',
Er='Erivoker:BAAALgAECgYJBwABLgAECgYJEgACAAAAAA==.Errimage:BAAALgAECgYJEgAAAA==.Errishoot:BAAALgAECgUJBwABLgAECgYJEgACAAAAAA==.Ervinia:BAAALgADCgYJCgABLgAECgUJDQACAAAAAA==.',
Ev='Evelinar:BAAALgAECgMJAwAAAA==.Evoslex:BAABLgAECn8wAAMSAAkJwSN4AQBHAwloDAAABgBeAGkMAAAGAF8AawwAAAYAXABqDAAABgBhAGwMAAAGAF8AbQwAAAQAYQDqDAAABwBVAG4MAAAEAFQAbwwAAAMAVwASAAkJwSN4AQBHAwloDAAABABeAGkMAAAFAF8AawwAAAUAXABqDAAABQBhAGwMAAAFAF8AbQwAAAQAYQDqDAAABQBVAG4MAAAEAFQAbwwAAAMAVwATAAYJzx1wEwCsAQZoDAAAAgBMAGkMAAABAFQAawwAAAEAVABqDAAAAQBCAGwMAAABADgA6gwAAAIATwAAAA==.',
Ex='Exo:BAECLgAFFH8ZAAIUAAUJbhrZCABIAQVoDAAABwBYAGkMAAAFAGAAawwAAAUAMQBqDAAAAgAYAOoMAAAGACMAFAAFCW4a2QgASAEFaAwAAAcAWABpDAAABQBgAGsMAAAFADEAagwAAAIAGADqDAAABgAjAC4ABAp/IgACFAAJCfwcLgYA1QIAFAAJCfwcLgYA1QIAAAA=.',
Fa='Facerolleh:BAACLgAFFH8pAAMVAAYJiCKKAQDbAQZoDAAABgBfAGkMAAAMAGAAawwAAAoAWQBqDAAABAAuAGwMAAADAEEA6gwAAAYAXwAVAAYJFSKKAQDbAQZoDAAAAgBdAGkMAAAIAGAAawwAAAkAWQBqDAAABAAuAGwMAAADAEEA6gwAAAEAWgAHAAQJZiGKBgCGAQRoDAAABABfAGkMAAAEAE4AawwAAAEASADqDAAABQBfAC4ABAp/PwADBwAICUkmzgQAXAMABwAICfYlzgQAXAMAFQAHCR4hiwgAKwIAAAA=.Fatedx:BAAALgADCgEJAQAAAA==.',
Fe='Feelgoodinc:BAAALgADCgkJFAAAAA==.',
Fi='Fidah:BAAALgADCgEJAQAAAA==.Firemagemain:BAAALgADCgUJBQABLgAFFAMJBQAHACoUAA==.',
Fl='Flop:BAAALgAECgUJCQABLgAECggJFwAEAOseAA==.',
Fr='Frostmere:BAAALgADCggJGQAAAA==.',
Fu='Fuknazum:BAAALgAECgEJAQAAAA==.Furcht:BAAALgAECgYJEQAAAA==.',
Ga='Galadar:BAAALgADCgUJBQAAAA==.',
Gi='Gitèff:BAAALgAFFAIJAwAAAA==.Giveroflife:BAAALgADCgcJBwAAAA==.',
Go='Gourdin:BAAALgAECgQJBQABLgAECgYJCAACAAAAAA==.',
Gr='Gramnpa:BAAALgADCgUJBQAAAA==.Gravepriest:BAAALgAECgEJAQAAAA==.Grimtysha:BAAALgAECgYJBwAAAA==.Grimveil:BAAALgAECgYJBgAAAA==.Gromit:BAAALgAECgQJCQAAAA==.',
Ha='Harafar:BAAALgAFFAEJAQAAAA==.',
He='Hellbourne:BAABLgAECn8ZAAIWAAgJzRavNABtAQhoDAAABQBBAGkMAAAEAEAAawwAAAQALQBqDAAAAwAgAGwMAAADAEUAbQwAAAEAHgDqDAAABABJAG4MAAABADsAFgAICc0WrzQAbQEIaAwAAAUAQQBpDAAABABAAGsMAAAEAC0AagwAAAMAIABsDAAAAwBFAG0MAAABAB4A6gwAAAQASQBuDAAAAQA7AAAA.',
Hi='Himmel:BAAALgADCgcJCQAAAA==.',
Ho='Hopnhorsé:BAAALgADCgEJAQAAAA==.Hotchoq:BAAALgAFFAIJAwAAAA==.',
Hu='Huntchoq:BAABLgAFFH8JAAQXAAQJKw9nCgBBAQRoDAAAAgA1AGkMAAACACIAawwAAAIAFQDqDAAAAwAsABcABAl+DGcKAEEBBGgMAAABADUAaQwAAAEAEABrDAAAAgAVAOoMAAACACQAGAACCVUIvEUAlQACaAwAAAEABwBpDAAAAQAiABkAAQmUEcwcAEsAAeoMAAABACwAAAA=.Huxley:BAAALgADCgMJAwAAAA==.',
Ik='Ikan:BAAALgAECgUJBgAAAA==.',
In='Infest:BAAALgAECgQJCAAAAA==.Inzolethys:BAAALgADCgcJBwAAAA==.',
It='Itchy:BAAALgADCgEJAgAAAA==.Itskiohte:BAABLgAECn8ZAAIaAAgJXA1sCQCRAQhoDAAAAwAwAGkMAAADAD8AawwAAAMALwBqDAAAAwAOAGwMAAADABoAbQwAAAIADADqDAAABAAcAG4MAAAEAA0AGgAICVwNbAkAkQEIaAwAAAMAMABpDAAAAwA/AGsMAAADAC8AagwAAAMADgBsDAAAAwAaAG0MAAACAAwA6gwAAAQAHABuDAAABAANAAAA.',
Ja='Jaggernut:BAAALgADCgUJBQAAAA==.',
Jo='Johnny:BAAALgAECgIJAgABLgAECgkJMAASAMEjAA==.',
Ju='Judeau:BAAALgADCgEJAQAAAA==.',
Ka='Kaelthuzzad:BAAALgADCgEJAQAAAA==.Kaitza:BAAALgAECgYJCwAAAA==.Kalzaketh:BAABLgAECn83AAMSAAgJ8go1JQArAQhoDAAACwAhAGkMAAAJACIAawwAAAkAJwBqDAAABgAMAGwMAAAGACAAbQwAAAEAEQDqDAAACAASAG4MAAAFABMAEgAICfIKNSUAKwEIaAwAAAcAIQBpDAAABwAiAGsMAAAHACcAagwAAAYADABsDAAABgAgAG0MAAABABEA6gwAAAgAEgBuDAAABQATABMAAwnlBIgzAHkAA2gMAAAEAAUAaQwAAAIADgBrDAAAAgASAAAA.Kashari:BAAALgAECgEJAwABLgAECgkJaQAGAAgbAA==.Katali:BAAALgAECgMJBAAAAA==.Kazuggar:BAACLgAFFH8PAAIbAAQJNB+KEABMAQRoDAAABQBVAGkMAAAFAEAAawwAAAIATQDqDAAAAwBcABsABAk0H4oQAEwBBGgMAAAFAFUAaQwAAAUAQABrDAAAAgBNAOoMAAADAFwALgAECn8qAAMbAAgJUSVuAgBcAwAbAAgJUSVuAgBcAwAcAAMJXhpNXQDOAAAAAA==.Kazzn:BAAALgAECgYJBgAAAA==.',
Ke='Kedar:BAAALgAECgYJCwAAAA==.Keg:BAAALgAECgIJAgAAAA==.Kelabar:BAAALgADCgQJBAAAAA==.',
Ki='Kick:BAAALgADCgQJBAABLgAFFAUJDwAEAOcOAA==.Kiffs:BAAALgAECgcJCgAAAA==.Kill:BAAALgAECgIJAgABLgAECggJBAACAAAAAA==.Kirâ:BAAALgAECggJEAAAAA==.',
Kr='Kregnar:BAABLgAECn8YAAIVAAgJ/xLBEABOAQhoDAAABgAeAGkMAAAEAD0AawwAAAQAMABqDAAAAgAjAGwMAAACAE0AbQwAAAEAMwDqDAAABAA4AG4MAAABAA0AFQAICf8SwRAATgEIaAwAAAYAHgBpDAAABAA9AGsMAAAEADAAagwAAAIAIwBsDAAAAgBNAG0MAAABADMA6gwAAAQAOABuDAAAAQANAAAA.Kresh:BAAALgAECgcJCwAAAA==.',
Ku='Kucabara:BAAALgAECgEJAgAAAA==.Kuraiwiggs:BAAALgADCgYJDAAAAA==.',
Kw='Kwichang:BAABLgAECn8UAAIEAAcJkw5ZXQBgAQdoDAAABAAuAGkMAAAEACcAawwAAAQAKgBqDAAAAgA/AGwMAAACAB4AbQwAAAEAFwDqDAAAAwApAAQABwmTDlldAGABB2gMAAAEAC4AaQwAAAQAJwBrDAAABAAqAGoMAAACAD8AbAwAAAIAHgBtDAAAAQAXAOoMAAADACkAAAA=.',
['Ké']='Kélpo:BAAALgADCgMJBAAAAA==.',
La='Lasagne:BAAALgADCgMJAwAAAA==.',
Li='Lickynose:BAABLgAECn8hAAIEAAgJFiGiEQCWAghoDAAABQBbAGkMAAAEAFkAawwAAAQATwBqDAAABABaAGwMAAAEAFYAbQwAAAMAPwDqDAAABgBdAG4MAAADAFgABAAICRYhohEAlgIIaAwAAAUAWwBpDAAABABZAGsMAAAEAE8AagwAAAQAWgBsDAAABABWAG0MAAADAD8A6gwAAAYAXQBuDAAAAwBYAAAA.Lips:BAAALgAECgEJAQAAAA==.',
Ls='Ls:BAABLgAECn8aAAMdAAgJmiFzBwCEAQhoDAAABABhAGkMAAADAF0AawwAAAMAVQBqDAAAAwBdAGwMAAADAEkAbQwAAAIARgDqDAAABQBaAG4MAAADAFsAFgAICZohoykAnQEIaAwAAAMAYQBpDAAAAgBdAGsMAAACAFUAagwAAAIAXQBsDAAAAgBJAG0MAAABAEYA6gwAAAQAWgBuDAAAAwBbAB0ABwliFXMHAIQBB2gMAAABAF4AaQwAAAEAIQBrDAAAAQBIAGoMAAABAB0AbAwAAAEAKQBtDAAAAQAdAOoMAAABADgAAAA=.',
Ma='Madarabia:BAAALgAECgYJDQAAAA==.Magnius:BAAALgAECgMJAwAAAA==.Mamut:BAAALgAECgEJAQAAAA==.Mantisar:BAACLgAFFH8FAAIPAAMJ8A3cNQDwAANoDAAAAgBBAGkMAAABABAA6gwAAAIAGAAPAAMJ8A3cNQDwAANoDAAAAgBBAGkMAAABABAA6gwAAAIAGAAuAAQKfxkAAg8ABglVHYwyAL0BAA8ABglVHYwyAL0BAAAA.Maxsm:BAABLgAECn8XAAIcAAgJrhmRIQACAghoDAAABABWAGkMAAAEAFcAawwAAAMAWABqDAAAAwA0AGwMAAADAEEAbQwAAAEAHgDqDAAABABgAG4MAAABAAQAHAAICa4ZkSEAAgIIaAwAAAQAVgBpDAAABABXAGsMAAADAFgAagwAAAMANABsDAAAAwBBAG0MAAABAB4A6gwAAAQAYABuDAAAAQAEAAAA.',
Me='Melanippe:BAABLgAECn8XAAIKAAYJDxttPQCuAQZoDAAABAA9AGkMAAAEAEcAawwAAAQAOwBqDAAAAwBEAGwMAAADAFAA6gwAAAUASQAKAAYJDxttPQCuAQZoDAAABAA9AGkMAAAEAEcAawwAAAQAOwBqDAAAAwBEAGwMAAADAFAA6gwAAAUASQAAAA==.Meleefox:BAAALgADCgUJBQAAAA==.Melethron:BAABLgAECn81AAIPAAkJWxwTCwC2AgloDAAACABUAGkMAAAHAE0AawwAAAcAWQBqDAAABwBcAGwMAAAHAFIAbQwAAAMAPQDqDAAABwBEAG4MAAAEAE4AbwwAAAMAJQAPAAkJWxwTCwC2AgloDAAACABUAGkMAAAHAE0AawwAAAcAWQBqDAAABwBcAGwMAAAHAFIAbQwAAAMAPQDqDAAABwBEAG4MAAAEAE4AbwwAAAMAJQAAAA==.Melioknky:BAAALgAECgYJBgAAAA==.',
Mi='Mid:BAAALgADCgYJBgAAAA==.Mightymage:BAABLgAECn8hAAIEAAgJ4Q3aSACUAQhoDAAABQAnAGkMAAAFACAAawwAAAUAMABqDAAAAwAxAGwMAAADAB8AbQwAAAEAHQDqDAAABgA1AG4MAAAFAA0ABAAICeEN2kgAlAEIaAwAAAUAJwBpDAAABQAgAGsMAAAFADAAagwAAAMAMQBsDAAAAwAfAG0MAAABAB0A6gwAAAYANQBuDAAABQANAAAA.Milliondruid:BAAALgAECgMJBAAAAA==.Millionsm:BAAALgADCgQJBQAAAA==.Mirrorimage:BAAALgAECgMJBQABLgAFFAUJDwAGANgUAA==.Mirrorx:BAACLgAFFH8PAAIGAAUJ2BQsCwBRAQVoDAAABQBBAGkMAAADAD0AawwAAAIAGgBqDAAAAQAjAOoMAAAEADwABgAFCdgULAsAUQEFaAwAAAUAQQBpDAAAAwA9AGsMAAACABoAagwAAAEAIwDqDAAABAA8AC4ABAp/KgACBgAICSAguAcAXgIABgAICSAguAcAXgIAAAA=.Miy:BAAALgAECgEJAQAAAA==.',
Mo='Mongon:BAAALgAECgYJBgAAAA==.Moogle:BAAALgAECgIJBAAAAA==.Moomie:BAABLgAECn8cAAIKAAgJ0RTSOwC1AQhoDAAABABJAGkMAAAFAEYAawwAAAUARABqDAAABAAqAGwMAAADACwAbQwAAAIAGADqDAAABAAwAG4MAAABADYACgAICdEU0jsAtQEIaAwAAAQASQBpDAAABQBGAGsMAAAFAEQAagwAAAQAKgBsDAAAAwAsAG0MAAACABgA6gwAAAQAMABuDAAAAQA2AAAA.Moosfel:BAABLgAECn8UAAIRAAYJWBY1FADsAAZoDAAABQBSAGkMAAAEAEMAawwAAAMAJQBqDAAAAgAIAGwMAAADAC8A6gwAAAMAMgARAAYJWBY1FADsAAZoDAAABQBSAGkMAAAEAEMAawwAAAMAJQBqDAAAAgAIAGwMAAADAC8A6gwAAAMAMgAAAA==.',
Mt='Mtzz:BAAALgAECgUJBQABLgAECgYJCAACAAAAAA==.',
Mu='Mudcake:BAAALgAECgEJAQAAAA==.',
My='Mygravebroke:BAAALgADCggJCQAAAA==.Mystdragon:BAACLgAFFH8OAAIeAAQJCh/TCwBiAQRoDAAABQBjAGkMAAAEAEcAawwAAAMANgDqDAAAAgBcAB4ABAkKH9MLAGIBBGgMAAAFAGMAaQwAAAQARwBrDAAAAwA2AOoMAAACAFwALgAECn8oAAIeAAgJUyD/BQDmAgAeAAgJUyD/BQDmAgABLgAFFAcJHwAFAHMeAA==.Mystweaverr:BAACLgAFFH8fAAIFAAcJcx6tAQByAgdoDAAABABHAGkMAAAGAFEAawwAAAYAWwBqDAAABgA5AGwMAAACAEUAbQwAAAEATADqDAAABgBiAAUABwlzHq0BAHICB2gMAAAEAEcAaQwAAAYAUQBrDAAABgBbAGoMAAAGADkAbAwAAAIARQBtDAAAAQBMAOoMAAAGAGIALgAECn8sAAMFAAgJLCGACQC5AgAFAAgJLCGACQC5AgAJAAIJIyJlMgDFAAAAAA==.',
['Mö']='Mörae:BAAALgADCgEJAQABLgAECgYJFwAKAA8bAA==.',
Na='Naddar:BAACLgAFFH8NAAIIAAUJRhYiCgCJAQVoDAAAAwA5AGkMAAADACgAawwAAAMAQQBqDAAAAQA8AOoMAAADAD0ACAAFCUYWIgoAiQEFaAwAAAMAOQBpDAAAAwAoAGsMAAADAEEAagwAAAEAPADqDAAAAwA9AC4ABAp/LQACCAAICaUfSQUA3gIACAAICaUfSQUA3gIAAAA=.Namadgi:BAABLgAECn8ZAAIKAAgJ+hkFFAA0AghoDAAAAwBGAGkMAAADAEgAawwAAAMARQBqDAAAAwA1AGwMAAADAD0AbQwAAAMAJwDqDAAABQBeAG4MAAACAEYACgAICfoZBRQANAIIaAwAAAMARgBpDAAAAwBIAGsMAAADAEUAagwAAAMANQBsDAAAAwA9AG0MAAADACcA6gwAAAUAXgBuDAAAAgBGAAAA.Nathria:BAAALgAECgIJAwAAAA==.',
Ne='Netalis:BAABLgAECn8eAAIKAAgJsxG5JgCiAQhoDAAABQBAAGkMAAAEACQAawwAAAQALQBqDAAABAA0AGwMAAAEADoAbQwAAAIAGwDqDAAABgA1AG4MAAABABgACgAICbMRuSYAogEIaAwAAAUAQABpDAAABAAkAGsMAAAEAC0AagwAAAQANABsDAAABAA6AG0MAAACABsA6gwAAAYANQBuDAAAAQAYAAAA.',
Ni='Nikonii:BAAALgADCgQJBAAAAA==.',
Nu='Nurckers:BAAALgAECgcJCAAAAA==.',
Oa='Oakinelf:BAAALgADCgcJAQAAAA==.',
Om='Omnishifts:BAAALgADCgQJBAAAAA==.',
Or='Oramo:BAABLgAECn8aAAMUAAgJCSMmBQDwAghoDAAABgBWAGkMAAAEAFwAawwAAAMAYgBqDAAAAgBAAGwMAAACAGEAbQwAAAIAUQDqDAAABQBfAG4MAAACAEsAFAAICcUiJgUA8AIIaAwAAAQAUQBpDAAAAgBcAGsMAAABAGIAagwAAAEAQABsDAAAAQBhAG0MAAACAFEA6gwAAAMAXwBuDAAAAgBLAAwABgnhHfKSAFoBBmgMAAACAFYAaQwAAAIAVABrDAAAAgBSAGoMAAABAAMAbAwAAAEAMQDqDAAAAgBPAAAA.',
Pa='Paradisya:BAAALgADCggJDgAAAA==.',
Pe='Perceptor:BAAALgAECgEJAQABLgAECgkJKQAfAJQhAA==.Pets:BAAALgAECgEJAQABLgAECgEJBAACAAAAAA==.',
Pl='Placebo:BAAALgAECgUJBQABLgAFFAMJCQARAKQWAA==.',
Pr='Prothero:BAABLgAFFH8NAAMEAAQJoR+4GQCBAQRoDAAABABUAGkMAAAEAGIAawwAAAIAPQDqDAAAAwBPAAQABAmhH7gZAIEBBGgMAAAEAFQAaQwAAAQAYgBrDAAAAgA9AOoMAAACAE8ADgABCWUZ/AEAWwAB6gwAAAEAQQAAAA==.Proyo:BAAALgADCgUJBQAAAA==.',
['På']='Påthor:BAACLgAFFH8FAAIgAAIJ4AxnIgCTAAJoDAAABAAnAOoMAAABABoAIAACCeAMZyIAkwACaAwAAAQAJwDqDAAAAQAaAC4ABAp/GgADIAAHCRYaPCEA8wEAIAAHCRYaPCEA8wEAHwADCRISAAAAAAAAAAA=.',
Ra='Raikonnen:BAAALgAECgEJAQAAAA==.Rawtoor:BAACLgAFFH8VAAIWAAUJth1MDABxAQVoDAAABQBTAGkMAAAFAF8AawwAAAMALQBqDAAAAwBBAOoMAAAFAE4AFgAFCbYdTAwAcQEFaAwAAAUAUwBpDAAABQBfAGsMAAADAC0AagwAAAMAQQDqDAAABQBOAC4ABAp/GwACFgAICTgh0ScAZQIAFgAICTgh0ScAZQIAAAA=.',
Re='Rebelsister:BAAALgADCgcJEAAAAA==.Refridgerate:BAAALgADCgUJBwAAAA==.',
Ri='Riddagain:BAABLgAECn8VAAMdAAYJeA/1FAAHAQZoDAAABAAZAGkMAAADADMAawwAAAMAJgBqDAAAAgAMAGwMAAACACwA6gwAAAcAJQAdAAYJTw/1FAAHAQZoDAAAAwAZAGkMAAADADMAawwAAAMAJgBqDAAAAgAMAGwMAAACACwA6gwAAAQAIwAWAAIJwAsiwwAtAAJoDAAAAQAWAOoMAAADACUAAAA=.Ridgemonk:BAABLgAECn8hAAMQAAkJJh4TBQCcAgloDAAABABfAGkMAAAFAEcAawwAAAUAUgBqDAAAAwBQAGwMAAAEADsAbQwAAAMAUwDqDAAABQBSAG4MAAADAEwAbwwAAAEAQwAQAAkJJh4TBQCcAgloDAAAAwBfAGkMAAAEAEcAawwAAAQAUgBqDAAAAwBQAGwMAAAEADsAbQwAAAMAUwDqDAAABABSAG4MAAADAEwAbwwAAAEAQwAFAAQJQAGZYABMAARoDAAAAQAEAGkMAAABAAIAawwAAAEAAADqDAAAAQAEAAAA.Riggsdk:BAAALgADCgcJBwABLgAFFAcJGAAYAP8jAA==.Riggse:BAAALgAECggJCgABLgAFFAcJGAAYAP8jAA==.Riggshunt:BAACLgAFFH8YAAQYAAcJ/yPTAACrAQdoDAAABQBjAGkMAAAFAGEAawwAAAQAVwBqDAAAAwA2AGwMAAABAFYAbQwAAAEAUwDqDAAABQBjABcABgksJJkAAPsBBmgMAAAEAGMAaQwAAAQAYQBrDAAAAwBSAGoMAAACADYAbAwAAAEAVgDqDAAABABhABgABQk/ItMAAKsBBWgMAAABAGIAaQwAAAEARgBrDAAAAQBXAG0MAAABAFMA6gwAAAEAYwAZAAEJAAC6KABKAAFqDAAAAQAPAC4ABAp/GgAEGAAICasmvggABwMAGAAHCZgmvggABwMAFwAICWwkkQMA7AIAGQABCYIcZn0ATwAAAAA=.Riggzs:BAAALgAECgQJBAABLgAFFAcJGAAYAP8jAA==.',
Ro='Roadkill:BAABLgAECn8gAAIUAAgJnSM4BAALAwhoDAAABQBhAGkMAAAFAF8AawwAAAUAXQBqDAAABABcAGwMAAAEAFAAbQwAAAIAWADqDAAABQBiAG4MAAACAFUAFAAICZ0jOAQACwMIaAwAAAUAYQBpDAAABQBfAGsMAAAFAF0AagwAAAQAXABsDAAABABQAG0MAAACAFgA6gwAAAUAYgBuDAAAAgBVAAAA.Rolltoor:BAAALgAFFAIJAwAAAA==.Roonate:BAAALgADCgUJBQAAAA==.Rosemary:BAAALgAECgQJBAAAAA==.',
Ry='Ryujin:BAAALgAECgQJCQAAAA==.',
Sa='Saiko:BAAALgAFFAMJBAAAAA==.Sansa:BAACLgAFFH8RAAIXAAYJ7hkyBAB7AQZoDAAABABaAGkMAAAEAFUAawwAAAIAPABqDAAAAgBcAGwMAAABAAAA6gwAAAQAXgAXAAYJ7hkyBAB7AQZoDAAABABaAGkMAAAEAFUAawwAAAIAPABqDAAAAgBcAGwMAAABAAAA6gwAAAQAXgAuAAQKfyEAAhcACAlmJF0CABwDABcACAlmJF0CABwDAAAA.Saso:BAACLgAFFH8QAAIEAAUJFhuXIwBmAQVoDAAABABAAGkMAAAEAEkAawwAAAMAOQBqDAAAAQBOAOoMAAAEAFEABAAFCRYblyMAZgEFaAwAAAQAQABpDAAABABJAGsMAAADADkAagwAAAEATgDqDAAABABRAC4ABAp/KgAEBAAICdkjMhMAiQIABAAICdkjMhMAiQIADgADCQMfSAwADQEAIQACCcQIsAsAdwAAAAA=.Sastroll:BAAALgAECgUJBQAAAA==.',
Sc='Scorn:BAAALgADCgcJCAAAAA==.Scroll:BAAALgAECggJEgAAAA==.',
Se='Seluvis:BAAALgAECgYJEQAAAA==.Sentai:BAAALgADCgcJBwAAAA==.Serapayne:BAAALgAECgcJAQAAAA==.',
Sh='Shadow:BAACLgAFFH8GAAIWAAUJ7A5+JQAiAQVoDAAAAQBAAGkMAAABAB8AawwAAAEAEgBqDAAAAgAcAOoMAAABACUAFgAFCewOfiUAIgEFaAwAAAEAQABpDAAAAQAfAGsMAAABABIAagwAAAIAHADqDAAAAQAlAC4ABAp/SgACFgAICX4j7AUA1QIAFgAICX4j7AUA1QIAAAA=.Shandrilah:BAAALgADCgQJBAAAAA==.Shapeshift:BAAALgADCgUJBQABLgAECgIJAgACAAAAAA==.Shialebuff:BAABLgAECn8pAAQDAAgJ3yCeFwAfAghoDAAABgBXAGkMAAAHAGMAawwAAAcAVQBqDAAABQBAAGwMAAAFAFUAbQwAAAIATwDqDAAABgBaAG4MAAADAFEAAwAICd8gnhcAHwIIaAwAAAMAVwBpDAAABABjAGsMAAAEAFUAagwAAAQAQABsDAAAAwBVAG0MAAACAE8A6gwAAAMAWgBuDAAAAQBRAAYABwnfGRMRAM8BB2gMAAADAFMAaQwAAAMATQBrDAAAAwA+AGoMAAABAEIAbAwAAAEAQgDqDAAAAwA0AG4MAAACADUAAQABCZMGxEkANAABbAwAAAEAEAAAAA==.Shijin:BAAALgAECgQJBQAAAA==.Shortfuze:BAAALgAECgYJCwAAAA==.',
Si='Sindar:BAAALgADCgUJBQAAAA==.Sinfall:BAAALgAECgUJBwAAAA==.Siscomp:BAABLgAECn9pAAIHAAkJFx4yBgCWAgloDAAADgBWAGkMAAANAFwAawwAAA8ASgBqDAAADQBDAGwMAAANAEwAbQwAAAoALADqDAAADQBOAG4MAAAJAFQAbwwAAAUATQAHAAkJFx4yBgCWAgloDAAADgBWAGkMAAANAFwAawwAAA8ASgBqDAAADQBDAGwMAAANAEwAbQwAAAoALADqDAAADQBOAG4MAAAJAFQAbwwAAAUATQAAAA==.Sixth:BAAALgAECgYJEQAAAA==.Sizzle:BAAALgADCgMJAwAAAA==.',
Sk='Skateboard:BAAALgADCgEJAQAAAA==.Sky:BAACLgAFFH8WAAIBAAcJUA7KBAAfAgdoDAAABQArAGkMAAADABgAawwAAAQAMwBqDAAABAAqAGwMAAACABYAbQwAAAEAFgDqDAAAAwAvAAEABwlQDsoEAB8CB2gMAAAFACsAaQwAAAMAGABrDAAABAAzAGoMAAAEACoAbAwAAAIAFgBtDAAAAQAWAOoMAAADAC8ALgAECn8UAAMBAAgJcROQHACwAQABAAcJWRKQHACwAQADAAUJ8g+ITAAGAQAAAA==.',
Sl='Sleck:BAAALgAECgYJDAAAAA==.',
Sn='Snappa:BAAALgADCgYJCwAAAA==.Sniped:BAAALgAFFAEJAQAAAA==.Snugglepuff:BAAALgAECggJDQAAAA==.',
So='Soapfidas:BAAALgADCggJCgAAAA==.Sonarius:BAABLgAECn8XAAMEAAgJ6x4oPACHAghoDAAABABaAGkMAAAEAFgAawwAAAQATgBqDAAAAwBMAGwMAAADAEgAbQwAAAEARQDqDAAAAwBYAG4MAAABAEIABAAICeseKDwAhwIIaAwAAAMAWgBpDAAABABYAGsMAAAEAE4AagwAAAMATABsDAAAAwBIAG0MAAABAEUA6gwAAAMAWABuDAAAAQBCACEAAQmyEhAPADwAAWgMAAABAC8AAAA=.',
Su='Su:BAABLgAECn8yAAIFAAcJ4yVlBwDiAgdoDAAACwBhAGkMAAAKAGMAawwAAAoAYQBqDAAACABiAGwMAAAFAGEA6gwAAAUAYQBuDAAAAQBaAAUABwnjJWUHAOICB2gMAAALAGEAaQwAAAoAYwBrDAAACgBhAGoMAAAIAGIAbAwAAAUAYQDqDAAABQBhAG4MAAABAFoAAAA=.Sudno:BAAALgAECgQJCAAAAA==.Sundae:BAABLgAECn8nAAQDAAgJHCPRAgAPAwhoDAAABgBfAGkMAAAGAFgAawwAAAYAXQBqDAAABQBTAGwMAAAEAFoAbQwAAAIATgDqDAAABgBhAG4MAAAEAFsAAwAICRwj0QIADwMIaAwAAAQAXwBpDAAAAwBYAGsMAAAEAF0AagwAAAUAUwBsDAAABABaAG0MAAACAE4A6gwAAAUAYQBuDAAABABbAAEABAkUGcAtADABBGgMAAABAD0AaQwAAAIASgBrDAAAAQBTAOoMAAABACQABgADCdwWQjEA2wADaAwAAAEAMABpDAAAAQBIAGsMAAABADYAAAA=.Sunwukong:BAAALgAECgUJCAAAAA==.Supersinpe:BAAALgAECgIJAgAAAA==.',
Sv='Svendlefyre:BAAALgADCgcJDgABLgAECggJLQARAMIZAA==.Svholydrag:BAAALgADCgEJAQAAAA==.Svmishima:BAAALgAECgEJAQAAAA==.',
Sy='Sylvie:BAAALgAECgkJEwAAAA==.',
['Sý']='Sýlvanas:BAAALgAECgQJDQAAAA==.',
Te='Tealç:BAABLgAECn8gAAIiAAcJphchEwA8AQdoDAAABgBWAGkMAAAGAFAAawwAAAYARQBqDAAABAAxAGwMAAAEACsAbQwAAAEACQDqDAAABQBKACIABwmmFyETADwBB2gMAAAGAFYAaQwAAAYAUABrDAAABgBFAGoMAAAEADEAbAwAAAQAKwBtDAAAAQAJAOoMAAAFAEoAAS4ABRQECQwAIgDoFwA=.Tekk:BAAALgAECgEJAQAAAA==.Tekkys:BAAALgAECgEJAgAAAA==.Tertle:BAAALgADCgUJBQAAAA==.',
Ti='Tiafinia:BAAALgAECgEJAgAAAA==.Tiggerstripe:BAAALgADCgEJAQABLgAECggJLAAaAA0QAA==.Timur:BAAALgAECgEJAgAAAA==.Tinara:BAAALgADCgUJBQAAAA==.',
Tr='Trigger:BAAALgAECgIJAgAAAA==.',
Tu='Turlesblows:BAABLgAECn8dAAMHAAcJLCFcJAA0AgdoDAAABQBTAGkMAAAFAFEAawwAAAMAUQBqDAAABABEAGwMAAAGAFoAbQwAAAIAUgDqDAAABABZAAcABwksIVwkADQCB2gMAAAFAFMAaQwAAAUAUQBrDAAAAwBRAGoMAAAEAEQAbAwAAAYAWgBtDAAAAgBSAOoMAAADAFkAIgABCTsVmkQAOwAB6gwAAAEANgAAAA==.',
Tw='Twityy:BAAALgADCgEJAgAAAA==.Twofiveyd:BAAALgAECgkJCQABLgAFFAYJFAAVAGcYAA==.',
Ty='Tyladrhas:BAABLgAECn8qAAIdAAgJgh82AgBsAghoDAAABwBOAGkMAAAGAFkAawwAAAYASgBqDAAABgA+AGwMAAAEAE0AbQwAAAMAXADqDAAACQBRAG4MAAABAEQAHQAICYIfNgIAbAIIaAwAAAcATgBpDAAABgBZAGsMAAAGAEoAagwAAAYAPgBsDAAABABNAG0MAAADAFwA6gwAAAkAUQBuDAAAAQBEAAAA.Tyrismaximus:BAAALgAECgMJAwAAAA==.',
Ul='Ulkina:BAAALgADCgYJCQAAAA==.',
Va='Vaelith:BAAALgAECgIJAgAAAA==.Valerine:BAABLgAECn8YAAIEAAcJlw3yaQBEAQdoDAAABAAqAGkMAAAEACcAawwAAAQAOQBqDAAABQAnAGwMAAAEAC8AbQwAAAEABwDqDAAAAgAOAAQABwmXDfJpAEQBB2gMAAAEACoAaQwAAAQAJwBrDAAABAA5AGoMAAAFACcAbAwAAAQALwBtDAAAAQAHAOoMAAACAA4AAAA=.Vanoran:BAAALgAECgMJBAAAAA==.Varang:BAAALgAECgIJAgAAAA==.Varina:BAAALgAECgcJEgAAAA==.',
Ve='Venki:BAAALgADCgcJDAAAAA==.',
Vo='Voidnova:BAABLgAFFH8GAAIEAAIJqBKNRQClAAJoDAAAAwBBAGkMAAADAB4ABAACCagSjUUApQACaAwAAAMAQQBpDAAAAwAeAAAA.Voidphayze:BAAALgAECgUJDAABLgAECgkJHAAMAHAYAA==.',
Vu='Vulken:BAABLgAECn9iAAIYAAkJECUWAgAyAwloDAAADQBhAGkMAAALAF4AawwAAA0AXgBqDAAADQBQAGwMAAANAFoAbQwAAAoAXQDqDAAADQBfAG4MAAAHAGAAbwwAAAUAYAAYAAkJECUWAgAyAwloDAAADQBhAGkMAAALAF4AawwAAA0AXgBqDAAADQBQAGwMAAANAFoAbQwAAAoAXQDqDAAADQBfAG4MAAAHAGAAbwwAAAUAYAAAAA==.',
['Vê']='Vê:BAAALgAECgkJEQAAAA==.',
Wa='Wallace:BAAALgAECgcJDAAAAA==.Walterlight:BAAALgAECgYJDgAAAA==.Watto:BAAALgAFFAEJAQAAAA==.',
We='Wemongin:BAAALgADCgUJBQAAAA==.',
Wh='Whimsical:BAAALgAECgYJEQAAAA==.',
Wi='Winnìng:BAABLgAECn8eAAIjAAgJ2gr8FQD6AAhoDAAABQA3AGkMAAAEABgAawwAAAQAIQBqDAAABAAgAGwMAAAEAAsAbQwAAAIAEgDqDAAABQAmAG4MAAACAAwAIwAICdoK/BUA+gAIaAwAAAUANwBpDAAABAAYAGsMAAAEACEAagwAAAQAIABsDAAABAALAG0MAAACABIA6gwAAAUAJgBuDAAAAgAMAAAA.',
Wu='Wugong:BAAALgADCgEJAQAAAA==.',
['Wó']='Wórkwórk:BAACLgAFFH8FAAIHAAMJKhRLFwCsAANoDAAAAgA8AGkMAAACAEAA6gwAAAEAHgAHAAMJKhRLFwCsAANoDAAAAgA8AGkMAAACAEAA6gwAAAEAHgAuAAQKfxsAAwcACQk6GxU3AMsBAAcABwnRGRU3AMsBABUAAwnsGr8fAO8AAAAA.',
Zi='Zich:BAAALgADCgMJAwAAAA==.Zihon:BAAALgAECgQJEwAAAA==.',
Zo='Zodiiak:BAABLgAECn88AAIaAAgJKR1ZBwDFAQhoDAAACgBOAGkMAAAKAFUAawwAAAgAVgBqDAAABwA+AGwMAAAJAFEAbQwAAAQAPQDqDAAACABMAG4MAAAEADQAGgAICSkdWQcAxQEIaAwAAAoATgBpDAAACgBVAGsMAAAIAFYAagwAAAcAPgBsDAAACQBRAG0MAAAEAD0A6gwAAAgATABuDAAABAA0AAAA.',
Zu='Zubb:BAAALgADCgMJAwABLgAECggJEAACAAAAAA==.Zuhh:BAAALgAECgEJAQABLgAECggJEAACAAAAAA==.Zupp:BAAALgAECggJEAAAAA==.',
Zx='Zx:BAAALgADCgYJBgAAAA==.',
['Ér']='Ér:BAAALgAECgkJBQAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
