local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Unknown-Unknown','Evoker-Augmentation','Mage-Fire','Mage-Frost','DeathKnight-Unholy','Hunter-Marksmanship','Evoker-Preservation','Evoker-Devastation','Shaman-Restoration','Warlock-Demonology','Warlock-Destruction','Druid-Guardian','DemonHunter-Devourer','Rogue-Outlaw','Monk-Brewmaster','Paladin-Holy','Hunter-BeastMastery','Rogue-Subtlety','Warrior-Fury','Shaman-Elemental','Monk-Mistweaver','Monk-Windwalker','Priest-Holy','Priest-Discipline','Priest-Shadow','DeathKnight-Frost','DeathKnight-Blood','Druid-Restoration','DemonHunter-Vengeance','Warrior-Arms','Warrior-Protection','Rogue-Assassination','Mage-Arcane','Paladin-Retribution','Paladin-Protection','Druid-Balance','DemonHunter-Havoc',}
local provider = {region='US',realm='MoonGuard',name='US',type='subscribers',zone=46,date='2026-06-13',data={Ad='Advvy:BAEALgAECgUJEgAAAA==.',
Ag='Ageregressor:BAEALgAECgcJBwAAAA==.',
Ai='Aihime:BAEALgADCgYJBgABLgAECgEJAQABAAAAAA==.',
Al='Alcean:BAEBLgAECn8+AAICAAkJiCJcBQAJAwloDAAACQBdAGkMAAAIAFgAawwAAAgAWwBqDAAABgBPAGwMAAAGAFYAbQwAAAUATQDqDAAACgBVAG4MAAAGAFoAbwwAAAQAXQACAAkJiCJcBQAJAwloDAAACQBdAGkMAAAIAFgAawwAAAgAWwBqDAAABgBPAGwMAAAGAFYAbQwAAAUATQDqDAAACgBVAG4MAAAGAFoAbwwAAAQAXQAAAA==.Algebra:BAECLgAFFH8bAAMDAAYJwiTFAACZAQZoDAAABwBfAGkMAAAGAGEAawwAAAUAYwBqDAAAAwBaAGwMAAABAFkA6gwAAAUAWQAEAAYJfiTeIgDxAQZoDAAABgBbAGkMAAAFAGEAawwAAAQAYwBqDAAAAgBaAGwMAAABAFkA6gwAAAQAWQADAAUJxSTFAACZAQVoDAAAAQBfAGkMAAABAF8AawwAAAEAYQBqDAAAAQBUAOoMAAABAFgALgAECn8dAAIEAAkJoSShCgAiAwAEAAkJoSShCgAiAwAAAA==.Aléyna:BAEALgAECgEJAgAAAA==.',
Ar='Araakki:BAEALgAECgcJDwAAAA==.Aradell:BAEBLgAFFH8FAAIFAAQJlgWmmwDYAARoDAAAAQAVAGkMAAABAAMAawwAAAEABADqDAAAAgAbAAUABAmWBaabANgABGgMAAABABUAaQwAAAEAAwBrDAAAAQAEAOoMAAACABsAAAA=.Arteron:BAEALgAFFAIJAwABLgAFFAcJFAAGAGweAA==.',
Ay='Ayoade:BAECLgAFFH8hAAIHAAUJSRdnEgBkAQVoDAAACAAzAGkMAAAIAD0AawwAAAgATgBqDAAAAQAfAOoMAAAIAEsABwAFCUkXZxIAZAEFaAwAAAgAMwBpDAAACAA9AGsMAAAIAE4AagwAAAEAHwDqDAAACABLAC4ABAp/GAADBwAICWkcnQoAjAIABwAICWkcnQoAjAIACAACCREV4zEAhwAAAS4ABRQICTQACQB9IAA=.',
Az='Azzurel:BAEBLgAECn8ZAAMKAAkJ7BMXTwCtAQloDAAABAAxAGkMAAAEACkAawwAAAMAOABqDAAAAwAwAGwMAAADADwAbQwAAAIAEADqDAAAAwAwAG4MAAACADYAbwwAAAEAUAAKAAkJ7BMXTwCtAQloDAAABAAxAGkMAAAEACkAawwAAAMAOABqDAAAAgAwAGwMAAADADwAbQwAAAIAEADqDAAAAwAwAG4MAAACADYAbwwAAAEAUAALAAEJAAA+cgAzAAFqDAAAAQAUAAAA.',
Ba='Bareskin:BAEBLgAFFH8FAAIMAAUJawoqGwCxAAVoDAAAAQAyAGkMAAABAAkAawwAAAEAGwBqDAAAAQAiAOoMAAABABMADAAFCWsKKhsAsQAFaAwAAAEAMgBpDAAAAQAJAGsMAAABABsAagwAAAEAIgDqDAAAAQATAAEuAAUUBgkTAA0A8RMA.',
Bl='Bloodroyal:BAEALgADCgcJBwABLgAFFAMJEAAOAEsdAA==.',
Bo='Bobbysan:BAECLgAFFH8fAAIPAAgJnhhHBwAQAghoDAAABgBQAGkMAAAFAEwAawwAAAQASQBqDAAABABAAGwMAAACACgAbQwAAAEAGwDqDAAACABWAG4MAAABADgADwAICZ4YRwcAEAIIaAwAAAYAUABpDAAABQBMAGsMAAAEAEkAagwAAAQAQABsDAAAAgAoAG0MAAABABsA6gwAAAgAVgBuDAAAAQA4AC4ABAp/LwACDwAJCRghmAoA4AIADwAJCRghmAoA4AIAAAA=.Bonemommyxo:BAECLgAFFH8UAAIFAAYJEiMYCQCIAQZoDAAABQBhAGkMAAAFAGMAawwAAAMAXQBqDAAAAQApAG0MAAABADsA6gwAAAUAYwAFAAYJEiMYCQCIAQZoDAAABQBhAGkMAAAFAGMAawwAAAMAXQBqDAAAAQApAG0MAAABADsA6gwAAAUAYwAuAAQKfysAAgUACQmQJRwCALsDAAUACQmQJRwCALsDAAAA.',
Br='Brigbala:BAEALgAECgMJBgAAAA==.',
Bu='Buttlustplz:BAEALgAFFAEJAwABLgAFFAMJCQAQANgfAA==.',
Ch='Chunghús:BAEALgAECgYJBgABLgAFFAgJIQAHANcOAA==.',
Co='Coggettle:BAEALgAECgYJBgABLgAECggJKAARANMgAA==.',
Cr='Crustome:BAEBLgAECn8qAAISAAgJHg8KHgCiAQhoDAAACAAYAGkMAAAIACcAawwAAAcAMgBqDAAABQAaAGwMAAAEAD0AbQwAAAMAGwDqDAAABAAdAG4MAAADACUAEgAICR4PCh4AogEIaAwAAAgAGABpDAAACAAnAGsMAAAHADIAagwAAAUAGgBsDAAABAA9AG0MAAADABsA6gwAAAQAHQBuDAAAAwAlAAAA.Crustorc:BAEBLgAECn8fAAITAAkJzgnpLwCNAQloDAAABAAeAGkMAAAEABYAawwAAAQAGABqDAAABAAXAGwMAAAEABwAbQwAAAIAFQDqDAAABQAiAG4MAAADABEAbwwAAAEAFQATAAkJzgnpLwCNAQloDAAABAAeAGkMAAAEABYAawwAAAQAGABqDAAABAAXAGwMAAAEABwAbQwAAAIAFQDqDAAABQAiAG4MAAADABEAbwwAAAEAFQABLgAECggJKgASAB4PAA==.',
Cu='Cubed:BAEALgAFFAEJAQABLgAFFAYJGwADAMIkAA==.',
Da='Darkstrand:BAEALgAECgcJCAABLgAFFAMJEAAOAEsdAA==.Daylea:BAECLgAFFH8mAAICAAkJ2h7PAQAqAwloDAAABgBgAGkMAAAGAGMAawwAAAgAYABqDAAABABfAGwMAAADAF8AbQwAAAIATQDqDAAABwBjAG4MAAABAAcAbwwAAAEAPAACAAkJ2h7PAQAqAwloDAAABgBgAGkMAAAGAGMAawwAAAgAYABqDAAABABfAGwMAAADAF8AbQwAAAIATQDqDAAABwBjAG4MAAABAAcAbwwAAAEAPAAuAAQKfyUAAwIACQnGJWgBALQDAAIACQnGJWgBALQDAAgABAm3IU8PABIBAAAA.',
De='Deathhealher:BAEALgADCgIJAgABLgAECgcJHAANAO0JAA==.Deathhunterz:BAEBLgAECn8cAAINAAcJ7QlXkQD5AAdoDAAABQAoAGkMAAAFABMAawwAAAYAFABqDAAAAwAaAGwMAAAEACcAbQwAAAEACwDqDAAABAAUAA0ABwntCVeRAPkAB2gMAAAFACgAaQwAAAUAEwBrDAAABgAUAGoMAAADABoAbAwAAAQAJwBtDAAAAQALAOoMAAAEABQAAAA=.Demagogué:BAECLgAFFH8QAAMUAAgJyRbDDQC+AQhoDAAAAwBHAGkMAAABAEkAawwAAAEACQBqDAAAAQAlAGwMAAACAGAAbQwAAAEAJwDqDAAABgBBAG4MAAABADQAFAAHCU0Uww0AvgEHaAwAAAIARwBpDAAAAQBJAGsMAAABAAkAagwAAAEAJQBtDAAAAQAnAOoMAAAFAEEAbgwAAAEANAAJAAMJGhUsQgDXAANoDAAAAQAcAGwMAAACADIA6gwAAAEAUwAuAAQKfycAAxQACAn7I30JAMMCABQACAn7I30JAMMCAAkABwmRHFY2ANMBAAEuAAUUCAkhAAcA1w4A.Demonipryde:BAEALgAECgMJAwAAAA==.Denrote:BAEALgAECgYJCAABLgAFFAYJIQASAFoeAA==.',
Di='Digitalwior:BAEALgADCgIJAwABLgAECggJKQAVACIXAA==.',
Dr='Dreamspun:BAECLgAFFH8QAAIOAAMJSx3+BwD9AANoDAAABgBGAGkMAAADAEoA6gwAAAcAUAAOAAMJSx3+BwD9AANoDAAABgBGAGkMAAADAEoA6gwAAAcAUAAuAAQKfzoAAg4ACQkbI38AAEQDAA4ACQkbI38AAEQDAAAA.Drunkenqrow:BAEALgAECgYJDQABLgAECggJEAABAAAAAA==.',
Du='Dubsii:BAECLgAFFH8YAAIVAAYJ5iBPDAAzAgZoDAAABQBTAGkMAAAFAGAAawwAAAYAXABqDAAAAwBdAGwMAAACAC4A6gwAAAMAXQAVAAYJ5iBPDAAzAgZoDAAABQBTAGkMAAAFAGAAawwAAAYAXABqDAAAAwBdAGwMAAACAC4A6gwAAAMAXQAuAAQKfxcAAxUACAmLIZwGAPMCABUACAmLIZwGAPMCABYAAQl/Jr9wAGsAAAEuAAUUCAk0AAkAfSAA.Dubsy:BAECLgAFFH80AAIJAAgJfSB/AAA2AghoDAAACwBQAGkMAAALAF8AawwAAAgAWwBqDAAACQBjAGwMAAABAEMAbQwAAAEALADqDAAACgBWAG4MAAABAGQACQAICX0gfwAANgIIaAwAAAsAUABpDAAACwBfAGsMAAAIAFsAagwAAAkAYwBsDAAAAQBDAG0MAAABACwA6gwAAAoAVgBuDAAAAQBkAC4ABAp/MwADCQAJCdAllgAAtAMACQAJCdAllgAAtAMAFAAECbUjIi4AhgEAAAA=.',
Eh='Ehanee:BAEALgAFFAIJAwAAAA==.',
Ei='Eibm:BAEALgAECgEJAQAAAA==.',
Er='Ereshin:BAEBLgAECn8YAAIJAAgJXB84DQDqAghoDAAABQBjAGkMAAADAGAAawwAAAQAWQBqDAAAAwBKAGwMAAACAE8AbQwAAAEAEgDqDAAAAwBYAG4MAAADAGAACQAICVwfOA0A6gIIaAwAAAUAYwBpDAAAAwBgAGsMAAAEAFkAagwAAAMASgBsDAAAAgBPAG0MAAABABIA6gwAAAMAWABuDAAAAwBgAAAA.',
Ev='Evieari:BAECLgAFFH8aAAMXAAYJfh8gBgDvAQZoDAAABQBTAGkMAAAFAGMAawwAAAUAUgBqDAAABAAlAGwMAAABAGAA6gwAAAYAUgAXAAUJ1CIgBgDvAQVoDAAAAwBTAGkMAAACAGMAawwAAAIAUgBsDAAAAQBgAOoMAAAEAFIAGAAFCVAMCCEAPwEFaAwAAAIAJQBpDAAAAwAYAGsMAAADAC8AagwAAAQAJQDqDAAAAgAKAC4ABAp/GQADGAAJCdYaPh0A4QEAGAAGCaYcPh0A4QEAFwAHCbkZmCkApQEAAS4ABRQGCQUAFwBKHwA=.Evielyssa:BAEBLgAFFH8JAAIXAAUJGRJlEgAyAQVoDAAAAgAZAGkMAAACACUAawwAAAIAMQBqDAAAAQBMAOoMAAACACoAFwAFCRkSZRIAMgEFaAwAAAIAGQBpDAAAAgAlAGsMAAACADEAagwAAAEATADqDAAAAgAqAAEuAAUUBgkFABcASh8A.Evierari:BAEBLgAFFH8FAAMXAAIJSh8mJACVAAJoDAAAAwBQAGkMAAACAE8AFwACCUofJiQAlQACaAwAAAIAUABpDAAAAgBPABkAAQkgAb8XADwAAWgMAAABAAIAAAA=.',
Fa='Fappimeal:BAECLgAFFH8nAAMFAAYJkyTbHAD3AQZoDAAACQBiAGkMAAAJAGEAawwAAAcAWgBqDAAABABVAGwMAAABAFEA6gwAAAkAYwAFAAYJkyTbHAD3AQZoDAAABwBiAGkMAAAHAGEAawwAAAUAWgBqDAAAAgBVAGwMAAABAFEA6gwAAAYAYwAaAAUJtBZhDAAxAQVoDAAAAgAtAGkMAAACADwAawwAAAIAPQBqDAAAAgAkAOoMAAADAEAALgAECn9AAAMFAAkJMCZ3AgC0AwAFAAkJMCZ3AgC0AwAaAAYJlh1tCwC+AQAAAA==.Fappisham:BAEALgAECgkJEgABLgAFFAYJJwAFAJMkAA==.',
Fe='Felshins:BAEALgADCgMJBgABLgAECggJGAAJAFwfAA==.',
Fo='Fofer:BAECLgAFFH8FAAIPAAQJkx/hFAB0AQRoDAAAAQBWAGkMAAABADoAawwAAAEAWwDqDAAAAgBXAA8ABAmTH+EUAHQBBGgMAAABAFYAaQwAAAEAOgBrDAAAAQBbAOoMAAACAFcALgAECn8nAAIPAAcJASaXCQCWAgAPAAcJASaXCQCWAgABLgAFFAgJIAAbAEIfAA==.Foil:BAEALgADCgkJGwABLgAECgkJXwAcAMglAA==.',
Fr='Froshin:BAEALgADCgUJCwABLgAECggJGAAJAFwfAA==.',
Fs='Fshi:BAEALgAFFAIJBAAAAA==.',
Fu='Funkey:BAECLgAFFH8TAAMNAAYJ8RM5NwBAAQZoDAAABQBDAGkMAAAFAFoAawwAAAIAFABqDAAAAgAWAGwMAAABACYA6gwAAAQAJgANAAYJuA45NwBAAQZoDAAAAwAhAGkMAAAEADgAawwAAAIAFABqDAAAAgAWAGwMAAABACYA6gwAAAQAJgAdAAIJth6eAgCjAAJoDAAAAgBDAGkMAAABAFoALgAECn8nAAMdAAkJnyDEAQD8AgAdAAgJsyLEAQD8AgANAAYJfhZ0VACGAQAAAA==.',
Gr='Greatares:BAEBLgAFFH8JAAMeAAMJogudKQC/AANoDAAAAwAZAGkMAAADABIA6gwAAAMALQAeAAMJdAudKQC/AANoDAAAAwAZAGkMAAACABAA6gwAAAMALQAfAAEJGQdHLAA3AAFpDAAAAQASAAAA.Greathades:BAEALgAECgkJAgABLgAFFAMJCQAeAKILAA==.Greatmonkey:BAEALgAECgcJBgABLgAFFAMJCQAeAKILAA==.Greatodin:BAEALgAECgkJBAABLgAFFAMJCQAeAKILAA==.Greatosiris:BAEALgAECgkJAgABLgAFFAMJCQAeAKILAA==.Greatra:BAEALgADCgEJAQABLgAFFAMJCQAeAKILAA==.Grummel:BAECLgAFFH8NAAISAAMJACLeIgAFAQNoDAAABwBbAGkMAAACAE8A6gwAAAQAWgASAAMJACLeIgAFAQNoDAAABwBbAGkMAAACAE8A6gwAAAQAWgAuAAQKfycAAxIACQk8IH8JAPkCABIACQk8IH8JAPkCACAAAQlwFGwdAEAAAAAA.',
Hb='Hbcarter:BAEBLgAFFH8HAAIcAAMJSxTdNwDIAANoDAAAAwBVAGkMAAABAB8A6gwAAAMAJgAcAAMJSxTdNwDIAANoDAAAAwBVAGkMAAABAB8A6gwAAAMAJgABLgAFFAgJNAAJAH0gAA==.',
Ia='Iambuns:BAEALgAECgcJBwABLgAFFAYJJwAFAJMkAA==.',
Il='Illiyania:BAEALgAECgEJAQAAAA==.Ilnarya:BAEALgAECgEJAQABLgAECgkJHgANALIRAA==.',
Im='Imquitelarge:BAEBLgAECn8VAAIeAAkJWhbVDgD8AQloDAAAAgAuAGkMAAACADIAawwAAAIAJwBqDAAAAgA8AGwMAAACACIAbQwAAAIAIwDqDAAAAwBVAG4MAAAEAFEAbwwAAAIAVQAeAAkJWhbVDgD8AQloDAAAAgAuAGkMAAACADIAawwAAAIAJwBqDAAAAgA8AGwMAAACACIAbQwAAAIAIwDqDAAAAwBVAG4MAAAEAFEAbwwAAAIAVQAAAA==.',
Iz='Izapotato:BAECLgAFFH8TAAINAAUJMxgjCQCXAQVoDAAABABUAGkMAAAEACoAawwAAAQANABqDAAAAwBDAOoMAAAEAEQADQAFCTMYIwkAlwEFaAwAAAQAVABpDAAABAAqAGsMAAAEADQAagwAAAMAQwDqDAAABABEAC4ABAp/IgACDQAHCaElpB8AVAIADQAHCaElpB8AVAIAAS4ABRQICSEABwDXDgA=.',
Ja='Jail:BAEBLgAECn8sAAMhAAkJgyM/AABNAwloDAAACABiAGkMAAAGAGEAawwAAAcAXwBqDAAABQBiAGwMAAAEAF8AbQwAAAMAUgDqDAAABQBgAG4MAAAEAGIAbwwAAAIAPgAhAAkJgyM/AABNAwloDAAABgBiAGkMAAAFAGEAawwAAAUAXwBqDAAABABiAGwMAAADAF8AbQwAAAIAUgDqDAAAAwBgAG4MAAACAGIAbwwAAAEAPgAEAAkJbRUGPQAkAgloDAAAAgA4AGkMAAABADwAawwAAAIAMQBqDAAAAQBEAGwMAAABACMAbQwAAAEAMwDqDAAAAgBMAG4MAAACAEAAbwwAAAEALQAAAA==.',
Ka='Katekicks:BAEBLgAECn8hAAIWAAkJWyC/BAAJAwloDAAABQBfAGkMAAAEAFoAawwAAAQAWwBqDAAABQBhAGwMAAAGAF0AbQwAAAEAUgDqDAAAAgBaAG4MAAAEAFkAbwwAAAIAHQAWAAkJWyC/BAAJAwloDAAABQBfAGkMAAAEAFoAawwAAAQAWwBqDAAABQBhAGwMAAAGAF0AbQwAAAEAUgDqDAAAAgBaAG4MAAAEAFkAbwwAAAIAHQAAAA==.Katestinks:BAECLgAFFH8SAAMFAAUJfR9SOACEAQVoDAAABABZAGkMAAAEAFkAawwAAAMALgBqDAAAAgARAOoMAAAFAGEABQAECX0fUjgAhAEEaAwAAAQAWQBpDAAABABZAGsMAAADAC4A6gwAAAUAYQAbAAEJAADlXwAAAAFqDAAAAgARAC4ABAp/KwADBQAJCdAjZgYAQwMABQAJCdAjZgYAQwMAGwABCbYK8F4AKQAAAS4ABAoJCSEAFgBbIAA=.',
Ke='Kelandrea:BAECLgAFFH8IAAIiAAMJ2w9pbgDOAANoDAAAAwAWAGkMAAABAD0A6gwAAAQAJgAiAAMJ2w9pbgDOAANoDAAAAwAWAGkMAAABAD0A6gwAAAQAJgAuAAQKfx8ABCIACQmrG9giAJ4CACIACQmrG9giAJ4CABAAAgnSEPeBAHAAACMAAgkzF8BJAD8AAAEuAAUUBAkFAAUAlgUA.',
Ki='Kirkh:BAEALgAECgcJDAABLgAECgkJJgAZAEobAA==.Kirkpriest:BAEBLgAECn8mAAIZAAkJSht8BwAQAwloDAAABQBbAGkMAAAFAFkAawwAAAUAXABqDAAABQBPAGwMAAAFAFcAbQwAAAQAMADqDAAABQBaAG4MAAADADEAbwwAAAEACQAZAAkJSht8BwAQAwloDAAABQBbAGkMAAAFAFkAawwAAAUAXABqDAAABQBPAGwMAAAFAFcAbQwAAAQAMADqDAAABQBaAG4MAAADADEAbwwAAAEACQAAAA==.Kitowatt:BAEALgAECgYJCgABLgAECggJJgAkAGQfAA==.',
Kr='Kregazi:BAECLgAFFH8QAAIbAAQJkRveFABAAQRoDAAABQBBAGkMAAAFAEkAawwAAAIAXADqDAAABAAyABsABAmRG94UAEABBGgMAAAFAEEAaQwAAAUASQBrDAAAAgBcAOoMAAAEADIALgAECn86AAIbAAkJEyPfBADgAgAbAAkJEyPfBADgAgAAAA==.',
Ky='Kyriste:BAEBLgAECn8aAAIXAAcJZiEIDwB0AgdoDAAABQBbAGkMAAAFAFoAawwAAAQAWABqDAAAAwBVAGwMAAADAEAA6gwAAAQAWwBuDAAAAgBXABcABwlmIQgPAHQCB2gMAAAFAFsAaQwAAAUAWgBrDAAABABYAGoMAAADAFUAbAwAAAMAQADqDAAABABbAG4MAAACAFcAAS4ABRQGCSEAEgBaHgA=.',
La='Larissaqt:BAECLgAFFH8lAAIZAAgJxRPPBAAtAghoDAAABwBTAGkMAAAGAEoAawwAAAcAHQBqDAAABgAgAGwMAAACADEAbQwAAAEAFADqDAAABgBQAG4MAAACAA8AGQAICcUTzwQALQIIaAwAAAcAUwBpDAAABgBKAGsMAAAHAB0AagwAAAYAIABsDAAAAgAxAG0MAAABABQA6gwAAAYAUABuDAAAAgAPAC4ABAp/MgACGQAJCQ4j3AIAOAMAGQAJCQ4j3AIAOAMAAAA=.',
Li='Lilygloom:BAEALgAECgUJBQABLgAFFAQJCAATAGgVAA==.Lilyish:BAEALgAECgEJAQABLgAFFAQJCAATAGgVAA==.Lilylock:BAEALgAECgEJAgABLgAFFAQJCAATAGgVAA==.Lilyweave:BAECLgAFFH8IAAITAAQJaBUMGwBAAQRoDAAAAgAhAGkMAAACAFMAawwAAAIAQQDqDAAAAgAlABMABAloFQwbAEABBGgMAAACACEAaQwAAAIAUwBrDAAAAgBBAOoMAAACACUALgAECn8dAAQTAAkJFx0WFQBGAgATAAkJFx0WFQBGAgAfAAIJDQ88PQBjAAAeAAEJNwzCQgAzAAAAAA==.Lioshi:BAEALgAFFAQJBAABLgAFFAQJFgAEAC4cAA==.',
Ma='Maildaddy:BAECLgAFFH8hAAIHAAgJ1w7FCQAHAghoDAAABgAwAGkMAAAGAEMAawwAAAYAMABqDAAABQBDAGwMAAABAAoAbQwAAAEACADqDAAABwAxAG4MAAABAAQABwAICdcOxQkABwIIaAwAAAYAMABpDAAABgBDAGsMAAAGADAAagwAAAUAQwBsDAAAAQAKAG0MAAABAAgA6gwAAAcAMQBuDAAAAQAEAC4ABAp/JAAEBwAICYkc3wkAQwIABwAHCSUg3wkAQwIAAgAFCSgRKjcAGwEACAADCRwc3ycA4gAAAAA=.Maxxy:BAEBLgAECn8cAAIcAAkJtR2gFgCBAgloDAAABQBdAGkMAAAEAFwAawwAAAQAXwBqDAAAAwA6AGwMAAADAEoAbQwAAAEARQDqDAAABQBUAG4MAAACAE8AbwwAAAEAJAAcAAkJtR2gFgCBAgloDAAABQBdAGkMAAAEAFwAawwAAAQAXwBqDAAAAwA6AGwMAAADAEoAbQwAAAEARQDqDAAABQBUAG4MAAACAE8AbwwAAAEAJAAAAA==.',
Mc='Mckellen:BAECLgAFFH8PAAMXAAQJyhpBEgAzAQRoDAAABABFAGkMAAAEADgAawwAAAMAPADqDAAABABXABcABAnKGkESADMBBGgMAAAEAEUAaQwAAAMAOABrDAAAAwA8AOoMAAADAFcAGAACCREJAhQAlgACaQwAAAEAGgDqDAAAAQAUAC4ABAp/HQADGAAICc4ZmQwAbgIAGAAICc4ZmQwAbgIAFwAECSYMg1wAwQAAAS4ABRQICTQACQB9IAA=.',
Me='Medranden:BAEALgADCgcJBwABLgAECgcJHAANAO0JAA==.Merakkii:BAEBLgAECn8nAAINAAcJ9h3cLQAMAgdoDAAABQBcAGkMAAAGAF0AawwAAAkAWQBqDAAACQBiAGwMAAAEAFoAbQwAAAEAAQDqDAAABQBdAA0ABwn2HdwtAAwCB2gMAAAFAFwAaQwAAAYAXQBrDAAACQBZAGoMAAAJAGIAbAwAAAQAWgBtDAAAAQABAOoMAAAFAF0AAAA=.Merarite:BAEALgAFFAIJAgAAAA==.',
Mi='Militee:BAEALgADCgMJBAAAAA==.',
Mo='Mordraius:BAEALgAECggJEQABLgAFFAQJFgAEAC4cAA==.',
My='Myceliums:BAEALgAECgUJDgAAAA==.',
Na='Nadasa:BAECLgAFFH8aAAIiAAYJ6hjIGwCSAQZoDAAABgAzAGkMAAAFAD4AawwAAAQAOgBqDAAAAwAxAGwMAAABAEEA6gwAAAcAUQAiAAYJ6hjIGwCSAQZoDAAABgAzAGkMAAAFAD4AawwAAAQAOgBqDAAAAwAxAGwMAAABAEEA6gwAAAcAUQAuAAQKf1IAAiIACQnrIRgKABUDACIACQnrIRgKABUDAAAA.Naramonria:BAEALgADCgcJCAAAAA==.',
Nh='Nhylia:BAEBLgAFFH8FAAIiAAMJihTkXwDpAANoDAAAAgAtAGkMAAABAB4A6gwAAAIAUQAiAAMJihTkXwDpAANoDAAAAgAtAGkMAAABAB4A6gwAAAIAUQABLgAFFAQJBQAFAJYFAA==.',
Ni='Nixaanu:BAEALgAECgEJAQABLgAECggJFAAUAH8aAA==.Nixei:BAEBLgAECn8UAAIUAAgJfxpEGABTAghoDAAAAgAyAGkMAAACAEIAawwAAAIATwBqDAAAAgA3AGwMAAAEAFAAbQwAAAMARwDqDAAAAgA3AG4MAAADAEYAFAAICX8aRBgAUwIIaAwAAAIAMgBpDAAAAgBCAGsMAAACAE8AagwAAAIANwBsDAAABABQAG0MAAADAEcA6gwAAAIANwBuDAAAAwBGAAAA.',
Ny='Nyriaa:BAECLgAFFH8KAAIXAAQJeRv9EQA2AQRoDAAAAwBOAGkMAAADAFEAawwAAAIAOgDqDAAAAgA+ABcABAl5G/0RADYBBGgMAAADAE4AaQwAAAMAUQBrDAAAAgA6AOoMAAACAD4ALgAECn8eAAIXAAkJvSPgBAAuAwAXAAkJvSPgBAAuAwAAAA==.',
['Ní']='Nítedragon:BAEALgAECgEJAQABLgAECgcJFAAHAFAgAA==.',
Ow='Owlenjoyer:BAECLgAFFH8GAAIkAAMJRxXBLgDDAANoDAAAAwAiAGkMAAACADQA6gwAAAEATAAkAAMJRxXBLgDDAANoDAAAAwAiAGkMAAACADQA6gwAAAEATAAuAAQKfx8AAiQACQmGGhoNAIQCACQACQmGGhoNAIQCAAEuAAQKCQkhABYAWyAA.',
Pa='Palashin:BAEBLgAECn8ZAAIQAAYJHx6gHgALAgZoDAAABgBgAGkMAAAFAE4AawwAAAUAVABqDAAAAwBHAGwMAAABADAA6gwAAAUAUwAQAAYJHx6gHgALAgZoDAAABgBgAGkMAAAFAE4AawwAAAUAVABqDAAAAwBHAGwMAAABADAA6gwAAAUAUwABLgAECggJGAAJAFwfAA==.',
Pe='Personnelkid:BAEALgAECgcJDQABLgAECgkJNwAXALUZAA==.',
Ph='Pheiro:BAEBLgAECn8cAAIEAAgJcQ1wiADBAQhoDAAABQBSAGkMAAAFAC0AawwAAAQAJQBqDAAAAgAXAGwMAAACABAAbQwAAAQADwDqDAAABQAmAG4MAAABAAUABAAICXENcIgAwQEIaAwAAAUAUgBpDAAABQAtAGsMAAAEACUAagwAAAIAFwBsDAAAAgAQAG0MAAAEAA8A6gwAAAUAJgBuDAAAAQAFAAAA.',
Pl='Platedaddy:BAEALgAECgYJDgABLgAFFAgJIQAHANcOAA==.',
Pu='Punchweagle:BAEBLgAECn82AAMPAAkJNhCAIQCZAQloDAAACAAzAGkMAAAHAEAAawwAAAgAOgBqDAAABgAoAGwMAAAGADkAbQwAAAUAEQDqDAAABgAwAG4MAAAFAA0AbwwAAAMAEwAPAAkJ8Q6AIQCZAQloDAAABAAzAGkMAAAEADQAawwAAAQAMwBqDAAABAAZAGwMAAAEADkAbQwAAAUAEQDqDAAABAAqAG4MAAAFAA0AbwwAAAMAEwAWAAYJUxRGMgBbAQZoDAAABAAyAGkMAAADAEAAawwAAAQAOgBqDAAAAgAoAGwMAAACACUA6gwAAAIAMAABLgAFFAIJAgABAAAAAA==.',
Qr='Qrowdrake:BAEALgAECgQJBQABLgAECggJEAABAAAAAA==.Qrowfather:BAEALgAECggJEAAAAA==.Qrowsunny:BAEALgAECgQJBQABLgAECggJEAABAAAAAA==.',
Ra='Raveglaive:BAEALgAECgUJAwAAAA==.',
Re='Redvine:BAEALgADCgUJBQABLgAFFAYJEwANAPETAA==.Rexpanda:BAEALgAECgQJBgABLgAECgUJBQABAAAAAA==.Rextank:BAEALgAECgEJAQABLgAECgUJBQABAAAAAA==.',
Ro='Roogies:BAECLgAFFH8hAAISAAYJWh7jCwDHAQZoDAAACQBcAGkMAAAJAFUAawwAAAYASgBqDAAAAwBdAGwMAAABACgA6gwAAAUAXgASAAYJWh7jCwDHAQZoDAAACQBcAGkMAAAJAFUAawwAAAYASgBqDAAAAwBdAGwMAAABACgA6gwAAAUAXgAuAAQKf0EAAxIACQmIJVoFANwCABIACQlZJVoFANwCACAAAgmdGCEVAKgAAAAA.',
Ru='Rumpy:BAEALgAFFAIJBAABLgAFFAMJDQASAAAiAA==.',
['Ræ']='Ræx:BAEALgAECgUJBQAAAA==.',
Se='Serenytey:BAEALgAECgcJDQAAAA==.',
Sh='Shiins:BAEALgAECgIJAwABLgAECggJGAAJAFwfAA==.Shinthyr:BAEBLgAECn8YAAIXAAcJ5R4eFQA0AgdoDAAABQBTAGkMAAAEAFUAawwAAAQAXQBqDAAAAwBHAGwMAAACAFUA6gwAAAQASwBuDAAAAgA6ABcABwnlHh4VADQCB2gMAAAFAFMAaQwAAAQAVQBrDAAABABdAGoMAAADAEcAbAwAAAIAVQDqDAAABABLAG4MAAACADoAAS4ABAoICRgACQBcHwA=.',
Si='Sizzlefox:BAEALgAECgEJAQABLgAECgcJDwABAAAAAA==.',
St='Stygianfox:BAEALgAECgIJBAABLgAECgcJDwABAAAAAA==.',
Ta='Tahune:BAEBLgAECn9fAAQcAAkJyCXoAADXAwloDAAADQBdAGkMAAAMAGIAawwAAAwAYgBqDAAADABhAGwMAAALAGIAbQwAAAkAYQDqDAAADABhAG4MAAAIAFoAbwwAAAYAYQAcAAkJyCXoAADXAwloDAAACgBdAGkMAAALAGIAawwAAAkAYgBqDAAACwBhAGwMAAAKAGIAbQwAAAgAYQDqDAAACwBhAG4MAAAHAFoAbwwAAAUAYQAMAAkJlyHgAgABAwloDAAAAQBbAGkMAAABAFsAawwAAAEAWgBqDAAAAQBXAGwMAAABAFoAbQwAAAEAUwDqDAAAAQBYAG4MAAABAE0AbwwAAAEASQAkAAIJhiE1XwCWAAJoDAAAAgBWAGsMAAACAFUAAAA=.Taso:BAEBLgAECn8dAAIPAAgJVhEbLgBKAQhoDAAABgA/AGkMAAAFAEMAawwAAAUASgBqDAAABQBPAGwMAAABAAAAbQwAAAEAAADqDAAABQBBAG4MAAABACYADwAICVYRGy4ASgEIaAwAAAYAPwBpDAAABQBDAGsMAAAFAEoAagwAAAUATwBsDAAAAQAAAG0MAAABAAAA6gwAAAUAQQBuDAAAAQAmAAEuAAUUBQkaABsA6CAA.',
Th='Therapygap:BAEBLgAECn83AAQXAAkJtRlYDQCNAgloDAAACQBMAGkMAAAKADwAawwAAAYATABqDAAABwA7AGwMAAAKAEoAbQwAAAMALwDqDAAABwA8AG4MAAACADkAbwwAAAEATQAXAAkJtRlYDQCNAgloDAAABgBMAGkMAAAGADwAawwAAAUATABqDAAABgA7AGwMAAAIAEoAbQwAAAMALwDqDAAABgA8AG4MAAABADkAbwwAAAEATQAZAAYJKwq3XACgAAZoDAAAAwAnAGkMAAAEABUAawwAAAEAEgBqDAAAAQAHAGwMAAACACkA6gwAAAEACAAYAAEJfANEhgAhAAFuDAAAAQAIAAAA.',
Tr='Triboon:BAEALgADCgMJAwABLgAFFAgJFwAVAKQaAA==.Trèantdaddy:BAEALgAFFAEJAgABLgAFFAgJIQAHANcOAA==.',
Tw='Twomonk:BAEALgAFFAEJAQABLgAFFAIJBgAWAL4hAA==.',
Un='Unsown:BAEALgAFFAEJAQABLgAFFAMJEAAOAEsdAA==.',
Us='Usurah:BAECLgAFFH8aAAIiAAgJvBQKDwDqAQhoDAAABgBOAGkMAAAGAFYAawwAAAMAQQBqDAAAAwA8AGwMAAACABsAbQwAAAEACADqDAAABAA+AG4MAAABACoAIgAICbwUCg8A6gEIaAwAAAYATgBpDAAABgBWAGsMAAADAEEAagwAAAMAPABsDAAAAgAbAG0MAAABAAgA6gwAAAQAPgBuDAAAAQAqAC4ABAp/KwADIgAJCYAixAkAQwMAIgAJCYAixAkAQwMAIwAFCVgcphsANgEAAAA=.',
Vi='Vindh:BAECLgAFFH8SAAMNAAUJugd7WQDcAAVoDAAABgAXAGkMAAAEABUAawwAAAMACABqDAAAAQAJAOoMAAAEABgADQAFCboHe1kA3AAFaAwAAAYAFwBpDAAABAAVAGsMAAADAAgAagwAAAEACQDqDAAAAwAYAB0AAQkOBtgTACkAAeoMAAABAA8ALgAECn8oAAQNAAkJtxVdPQD/AQANAAkJtxVdPQD/AQAdAAIJOgOVMAA9AAAlAAEJAADchQAAAAAAAA==.',
Vy='Vyndraennis:BAEBLgAECn8eAAINAAkJshG9QwC5AQloDAAABQAhAGkMAAAFAEUAawwAAAUAOQBqDAAAAwAyAGwMAAADABwAbQwAAAEALQDqDAAABQA1AG4MAAACADEAbwwAAAEAGQANAAkJshG9QwC5AQloDAAABQAhAGkMAAAFAEUAawwAAAUAOQBqDAAAAwAyAGwMAAADABwAbQwAAAEALQDqDAAABQA1AG4MAAACADEAbwwAAAEAGQAAAA==.',
['Vî']='Vîtâl:BAEALgADCgMJAwABLgAFFAUJEQAVAB0cAA==.',
Ya='Yaav:BAEBLgAECn8XAAIFAAkJxhAIWQC4AQloDAAABAA2AGkMAAAEADoAawwAAAMAJgBqDAAAAwBLAGwMAAADACMAbQwAAAEAKADqDAAAAgA0AG4MAAACACQAbwwAAAEAGwAFAAkJxhAIWQC4AQloDAAABAA2AGkMAAAEADoAawwAAAMAJgBqDAAAAwBLAGwMAAADACMAbQwAAAEAKADqDAAAAgA0AG4MAAACACQAbwwAAAEAGwAAAA==.',
Yu='Yufia:BAEBLgAECn8ZAAIKAAkJXR5GCgAsAwloDAAABABQAGkMAAAEAF8AawwAAAQAWABqDAAAAwBdAGwMAAACAFgAbQwAAAEAQgDqDAAABQBjAG4MAAABABEAbwwAAAEAVgAKAAkJXR5GCgAsAwloDAAABABQAGkMAAAEAF8AawwAAAQAWABqDAAAAwBdAGwMAAACAFgAbQwAAAEAQgDqDAAABQBjAG4MAAABABEAbwwAAAEAVgAAAA==.',
Za='Zatum:BAEBLgAECn8mAAMkAAgJZB+5DgBvAghoDAAABgBTAGkMAAAGAFYAawwAAAUAUABqDAAABABLAGwMAAAGAFMAbQwAAAIASgDqDAAABgBUAG4MAAADAEYAJAAICWQfuQ4AbwIIaAwAAAYAUwBpDAAABgBWAGsMAAAFAFAAagwAAAQASwBsDAAABQBTAG0MAAABAEoA6gwAAAUAVABuDAAAAwBGABwAAwmYCYubAHcAA2wMAAABACIAbQwAAAEAHQDqDAAAAQAJAAAA.',
Zh='Zhuröng:BAECLgAFFH8WAAIEAAQJLhwiRwBbAQRoDAAABwBZAGkMAAAHAE4AawwAAAUAKgDqDAAAAwBPAAQABAkuHCJHAFsBBGgMAAAHAFkAaQwAAAcATgBrDAAABQAqAOoMAAADAE8ALgAECn8nAAIEAAkJrh/KTQBNAgAEAAkJrh/KTQBNAgAAAA==.',
Zo='Zomb:BAECLgAFFH8aAAIbAAUJ6CCZEQBnAQVoDAAACABbAGkMAAAHAEQAawwAAAQAXQBqDAAAAgBMAOoMAAAFAFQAGwAFCeggmREAZwEFaAwAAAgAWwBpDAAABwBEAGsMAAAEAF0AagwAAAIATADqDAAABQBUAC4ABAp/JQACGwAICY4haQQABQMAGwAICY4haQQABQMAAAA=.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
