local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Paladin-Retribution','Rogue-Assassination','Shaman-Elemental','Mage-Frost','DemonHunter-Devourer','Mage-Fire','Druid-Feral','Priest-Shadow','Priest-Discipline','Shaman-Restoration','Unknown-Unknown','Warlock-Destruction','Warlock-Demonology','Hunter-BeastMastery','Hunter-Marksmanship','DeathKnight-Unholy','DemonHunter-Havoc','DeathKnight-Blood','Monk-Brewmaster','Druid-Restoration','Monk-Windwalker','DeathKnight-Frost','Rogue-Subtlety','Paladin-Protection','Priest-Holy','DemonHunter-Vengeance','Rogue-Outlaw','Warlock-Affliction','Hunter-Survival','Druid-Balance','Warrior-Arms','Paladin-Holy','Warrior-Fury','Shaman-Enhancement','Warrior-Protection','Monk-Mistweaver','Evoker-Devastation',}
local provider = {region='US',realm='KirinTor',name='US',type='daily',zone=46,date='2026-06-07',data={Ac='Acallia:BAAALgAECgQJCwAAAA==.Achkmed:BAABLgAECn8YAAIBAAcJfhg2bQCjAQdoDAAABABJAGkMAAAFAFEAawwAAAQASABqDAAABABeAGwMAAADAEQAbQwAAAIADwDqDAAAAgBBAAEABwl+GDZtAKMBB2gMAAAEAEkAaQwAAAUAUQBrDAAABABIAGoMAAAEAF4AbAwAAAMARABtDAAAAgAPAOoMAAACAEEAAAA=.',
Ae='Aelynis:BAABLgAECn8mAAICAAkJOw+VCADFAQloDAAABwBSAGkMAAAFADMAawwAAAUAMwBqDAAAAwAXAGwMAAADADEAbQwAAAIAEQDqDAAABwAfAG4MAAAEAAoAbwwAAAIAEQACAAkJOw+VCADFAQloDAAABwBSAGkMAAAFADMAawwAAAUAMwBqDAAAAwAXAGwMAAADADEAbQwAAAIAEQDqDAAABwAfAG4MAAAEAAoAbwwAAAIAEQAAAA==.',
Ak='Akalon:BAABLgAECn83AAIDAAgJ+gmdRwAHAQhoDAAACgAlAGkMAAAGACMAawwAAAgAEwBqDAAABgASAGwMAAAIABcAbQwAAAYADgDqDAAABQAZAG4MAAAGABcAAwAICfoJnUcABwEIaAwAAAoAJQBpDAAABgAjAGsMAAAIABMAagwAAAYAEgBsDAAACAAXAG0MAAAGAA4A6gwAAAUAGQBuDAAABgAXAAAA.',
Al='Alara:BAAALgADCgEJAQABLgAECggJLgAEAGgfAA==.Aldrus:BAAALgADCgYJBgAAAA==.Allfrost:BAAALgAECgQJDAAAAA==.',
Am='Amanthelia:BAAALgADCgUJBQAAAA==.Amberina:BAAALgADCgkJEgAAAA==.',
An='Annerose:BAABLgAECn8oAAIFAAgJpgMcsQC5AAhoDAAABwAHAGkMAAAHAA0AawwAAAYACABqDAAABAAPAGwMAAAEAA4AbQwAAAEABQDqDAAABwAFAG4MAAAEAAoABQAICaYDHLEAuQAIaAwAAAcABwBpDAAABwANAGsMAAAGAAgAagwAAAQADwBsDAAABAAOAG0MAAABAAUA6gwAAAcABQBuDAAABAAKAAAA.Anthir:BAAALgADCgEJAgAAAA==.',
Ao='Aoeina:BAABLgAECn89AAMEAAkJDhpALgBaAgloDAAACQBEAGkMAAAIADoAawwAAAgAQgBqDAAACABBAGwMAAAIAFUAbQwAAAUALQDqDAAACQBOAG4MAAAEAD4AbwwAAAIARAAEAAkJDhpALgBaAgloDAAACQBEAGkMAAAIADoAawwAAAgAQgBqDAAACABBAGwMAAAIAFUAbQwAAAUALQDqDAAACQBOAG4MAAADAD4AbwwAAAIARAAGAAEJiAOdFAAlAAFuDAAAAQAJAAAA.',
Ap='Apollo:BAAALgAFFAEJAQAAAA==.',
Aq='Aquinas:BAAALgAECgQJBAABLgAECgcJGgAHAIogAA==.',
Ar='Arcanelotus:BAAALgAECgIJAgAAAA==.Arcás:BAAALgADCgYJBgAAAA==.Arette:BAAALgADCgEJAQABLgAECgYJFgAIAKwCAA==.Ariaves:BAABLgAECn8kAAMIAAkJGRfaGwD+AQloDAAACABVAGkMAAAFAEYAawwAAAUAPgBqDAAABAAuAGwMAAADAEYAbQwAAAIAJgDqDAAABAA3AG4MAAADADwAbwwAAAIAHQAIAAkJGRfaGwD+AQloDAAABwBVAGkMAAAEAEYAawwAAAQAPgBqDAAABAAuAGwMAAADAEYAbQwAAAIAJgDqDAAAAwA3AG4MAAADADwAbwwAAAIAHQAJAAQJugjVPgC3AARoDAAAAQA1AGkMAAABAA0AawwAAAEABADqDAAAAQARAAAA.Arilea:BAAALgAECgMJAwAAAA==.Arioriaa:BAABLgAECn8sAAIKAAgJ1wtcUQBgAQhoDAAABwBDAGkMAAAHACEAawwAAAYAFQBqDAAABgAZAGwMAAAGABcAbQwAAAEABADqDAAABwAXAG4MAAAEACoACgAICdcLXFEAYAEIaAwAAAcAQwBpDAAABwAhAGsMAAAGABUAagwAAAYAGQBsDAAABgAXAG0MAAABAAQA6gwAAAcAFwBuDAAABAAqAAAA.Arlind:BAAALgAECgYJDQAAAA==.',
As='Asenath:BAAALgADCgEJAQAAAA==.Asoeclya:BAAALgADCgIJAgAAAA==.Assuutu:BAAALgADCgMJAwAAAA==.',
At='Atanatari:BAAALgAECgEJAQABLgAECgYJEAALAAAAAA==.Attonix:BAAALgAECgEJAQAAAA==.',
Az='Azarine:BAAALgADCggJCQAAAA==.Azem:BAAALgADCggJEwAAAA==.Azixarid:BAAALgAECgMJAwAAAA==.Azurdrache:BAAALgAECgEJAgAAAA==.',
Ba='Baldur:BAAALgADCgcJDAAAAA==.Bassotan:BAABLgAECn8lAAIBAAkJ1hjYLQBAAgloDAAABABCAGkMAAAEAEgAawwAAAQAOQBqDAAABABJAGwMAAAEADYAbQwAAAIAOADqDAAABgBDAG4MAAAFAEEAbwwAAAQAQwABAAkJ1hjYLQBAAgloDAAABABCAGkMAAAEAEgAawwAAAQAOQBqDAAABABJAGwMAAAEADYAbQwAAAIAOADqDAAABgBDAG4MAAAFAEEAbwwAAAQAQwAAAA==.Battleares:BAAALgAECgYJEAAAAA==.',
Be='Beardalorian:BAAALgAECgUJBgAAAA==.Beasttoken:BAAALgADCgUJBQAAAA==.Beleva:BAABLgAECn8sAAIMAAcJVwwxFAABAQdoDAAACQAzAGkMAAAIAB4AawwAAAcAIgBqDAAABwAUAGwMAAAFABAA6gwAAAYAJgBuDAAAAgASAAwABwlXDDEUAAEBB2gMAAAJADMAaQwAAAgAHgBrDAAABwAiAGoMAAAHABQAbAwAAAUAEADqDAAABgAmAG4MAAACABIAAAA=.',
Bi='Bigboom:BAAALgAECgEJAQABLgAECgQJBwALAAAAAA==.Bigstan:BAAALgAECgcJDwAAAA==.Bilbobagging:BAAALgAECgMJBAABLgAFFAYJCwAEAGoVAA==.Bilx:BAAALgAECgYJCwAAAA==.Biromong:BAAALgAECgYJDwAAAA==.',
Bl='Blackendmoon:BAAALgAECgQJCgAAAA==.Blackløtus:BAAALgAECgYJAgAAAA==.Bloodknight:BAAALgADCgEJAQAAAA==.Bloodnight:BAAALgAECgIJBQAAAA==.Bluebeary:BAAALgAECgQJBAAAAA==.Bluebubbles:BAAALgADCgkJCQAAAA==.Bluelocks:BAACLgAFFH8GAAIMAAQJRgGNEACnAARoDAAAAgAFAGkMAAABAAUAawwAAAEAAADqDAAAAgABAAwABAlGAY0QAKcABGgMAAACAAUAaQwAAAEABQBrDAAAAQAAAOoMAAACAAEALgAECn8rAAMMAAgJjRDXDABhAQAMAAgJjRDXDABhAQANAAEJTgJlUQEkAAAAAA==.Blufoot:BAAALgAECgUJBQAAAA==.Bluéyes:BAAALgAECgQJBwAAAA==.Blvckscvl:BAABLgAECn8hAAMOAAgJvBzsFgCBAghoDAAABgBSAGkMAAAFAFEAawwAAAUAVgBqDAAABQBeAGwMAAACAFoAbQwAAAEAGgDqDAAABwBKAG4MAAACAEgADgAICbwc7BYAgQIIaAwAAAYAUgBpDAAABQBRAGsMAAAFAFYAagwAAAUAXgBsDAAAAgBaAG0MAAABABoA6gwAAAYASgBuDAAAAgBIAA8AAQk1BH2RACkAAeoMAAABAAoAAAA=.Blynna:BAAALgAECgYJCQAAAA==.',
Bo='Bohemond:BAAALgADCgcJBwAAAA==.Borrne:BAAALgAECgEJAQAAAA==.',
Br='Broadleaf:BAAALgAECgQJCQAAAA==.Brujha:BAAALgAECgYJDAABLgAECgkJOAAFABQaAA==.',
Bu='Burnttoast:BAAALgADCgMJAwABLgAECgkJGAABAH4YAA==.',
Ca='Caledra:BAAALgAECgEJAQAAAA==.Calinai:BAAALgAECgIJAgAAAA==.Cambrus:BAAALgADCgkJCQAAAA==.Catastrophi:BAAALgADCgEJAQAAAA==.Catastrophie:BAABLgAECn8wAAIQAAgJABOOYQCeAQhoDAAACQBNAGkMAAAJADIAawwAAAgAFwBqDAAABgAmAGwMAAAFADUAbQwAAAEAEwDqDAAACAAtAG4MAAACAEYAEAAICQATjmEAngEIaAwAAAkATQBpDAAACQAyAGsMAAAIABcAagwAAAYAJgBsDAAABQA1AG0MAAABABMA6gwAAAgALQBuDAAAAgBGAAAA.',
Ce='Cellturin:BAAALgAECgkJEQAAAA==.',
Ch='Chelais:BAAALgAECgQJBAABLgABCgMJAwALAAAAAA==.Chiarakai:BAAALgADCgkJHgAAAA==.Chobits:BAAALgAECgUJBgAAAA==.Choc:BAAALgADCgMJAwAAAA==.',
Cl='Claudeena:BAAALgADCgkJEgAAAA==.',
Co='Corvany:BAAALgAECgEJAQABLgAECgQJBwALAAAAAA==.Coswell:BAAALgAECgMJAwAAAA==.',
Cr='Creeder:BAABLgAECn8jAAIBAAkJuRADdACTAQloDAAABgA2AGkMAAAEAE0AawwAAAQAIwBqDAAAAwAiAGwMAAADABsAbQwAAAIAEQDqDAAABwA0AG4MAAAEACcAbwwAAAIAJQABAAkJuRADdACTAQloDAAABgA2AGkMAAAEAE0AawwAAAQAIwBqDAAAAwAiAGwMAAADABsAbQwAAAIAEQDqDAAABwA0AG4MAAAEACcAbwwAAAIAJQAAAA==.Crixus:BAAALgADCgcJBwAAAA==.Crm:BAAALgADCgUJBQAAAA==.',
Cy='Cynise:BAAALgADCgcJDQAAAA==.',
Da='Dagoland:BAAALgAECgMJAwAAAA==.Darthmeep:BAAALgAECgIJAgAAAA==.',
De='Deaanor:BAABLgAECn8bAAIRAAcJagcMNgDTAAdoDAAABgAiAGkMAAAFABEAawwAAAUADwBqDAAAAwAhAGwMAAACABEA6gwAAAUAEQBuDAAAAQALABEABwlqBww2ANMAB2gMAAAGACIAaQwAAAUAEQBrDAAABQAPAGoMAAADACEAbAwAAAIAEQDqDAAABQARAG4MAAABAAsAAAA=.Deathcòw:BAACLgAFFH8GAAIQAAMJDBiOfwD4AANoDAAABABjAGkMAAABAB8A6gwAAAEANQAQAAMJDBiOfwD4AANoDAAABABjAGkMAAABAB8A6gwAAAEANQAuAAQKfzwAAxAACQnWI3AKABYDABAACQnWI3AKABYDABIAAgmaCQg+AFkAAAAA.Deathpanthr:BAAALgAECgEJAQABLgAECgIJAgALAAAAAA==.Demonhunter:BAAALgAECgIJAgAAAA==.Demonia:BAAALgADCgYJBgAAAA==.Detective:BAABLgAECn8XAAITAAkJFQvTOgBdAQloDAAABAApAGkMAAADACUAawwAAAMALQBqDAAAAgAQAGwMAAACACAAbQwAAAEABQDqDAAABQAiAG4MAAACAA0AbwwAAAEAEQATAAkJFQvTOgBdAQloDAAABAApAGkMAAADACUAawwAAAMALQBqDAAAAgAQAGwMAAACACAAbQwAAAEABQDqDAAABQAiAG4MAAACAA0AbwwAAAEAEQAAAA==.Deween:BAAALgADCgYJBgAAAA==.',
Di='Diamond:BAAALgADCgkJGQAAAA==.Dilligafehno:BAAALgADCgkJEgAAAA==.Dionysuz:BAAALgADCgEJAQAAAA==.Discord:BAAALgADCgYJBgAAAA==.',
Do='Dojoro:BAABLgAECn8wAAITAAkJzBl4DgBJAgloDAAACgBDAGkMAAAIAFUAawwAAAcASgBqDAAABQBKAGwMAAADADYAbQwAAAIAOwDqDAAACQBTAG4MAAADACsAbwwAAAEAOgATAAkJzBl4DgBJAgloDAAACgBDAGkMAAAIAFUAawwAAAcASgBqDAAABQBKAGwMAAADADYAbQwAAAIAOwDqDAAACQBTAG4MAAADACsAbwwAAAEAOgAAAA==.Dora:BAAALgAECgEJAQAAAA==.',
Dp='Dpshut:BAAALgAECgUJBQABLgAECgkJGAABAH4YAA==.',
Dr='Draann:BAAALgADCggJBwABLgAECgQJBwALAAAAAA==.Draegare:BAABLgAECn8qAAIBAAgJqCXlBQBuAwhoDAAABwBjAGkMAAAHAGEAawwAAAYAYABqDAAABQBkAGwMAAAEAGAAbQwAAAMAVgDqDAAABgBjAG4MAAAEAGMAAQAICagl5QUAbgMIaAwAAAcAYwBpDAAABwBhAGsMAAAGAGAAagwAAAUAZABsDAAABABgAG0MAAADAFYA6gwAAAYAYwBuDAAABABjAAAA.Drdeer:BAABLgAECn8fAAIUAAkJRRG3LADuAQloDAAABgA5AGkMAAAFADUAawwAAAQAOgBqDAAAAgAfAGwMAAABACUAbQwAAAIAIADqDAAABgA0AG4MAAAEADwAbwwAAAEADwAUAAkJRRG3LADuAQloDAAABgA5AGkMAAAFADUAawwAAAQAOgBqDAAAAgAfAGwMAAABACUAbQwAAAIAIADqDAAABgA0AG4MAAAEADwAbwwAAAEADwAAAA==.Dread:BAAALgADCgUJBwAAAA==.Drittsz:BAAALgADCgIJBAAAAA==.Drumheller:BAAALgAECgMJAwAAAA==.',
Du='Duskraven:BAAALgAECgUJBQAAAA==.',
Ec='Ecclesiarchy:BAAALgADCgkJCQAAAA==.',
Ed='Edwar:BAAALgADCgYJBgAAAA==.',
Ee='Eekumbokum:BAAALgAECgEJAQAAAA==.Eelecurb:BAABLgAFFH8FAAMVAAMJwQ1zLACJAANoDAAAAgAkAGkMAAABACwA6gwAAAIAGAAVAAIJwA9zLACJAAJoDAAAAgAkAGkMAAABACwAEwABCcQJcFgANgAB6gwAAAIAGAAAAA==.',
El='Eligorra:BAAALgADCgEJAQAAAA==.',
Ep='Epicfury:BAAALgADCgEJAQAAAA==.',
Es='Eshmun:BAAALgAECgUJDQAAAA==.',
Et='Eternalx:BAAALgAECgQJBQAAAA==.Ethidris:BAAALgADCgQJBAABLgAECgkJGAABAH4YAA==.',
Ev='Evang:BAABLgAECn8qAAIOAAgJcxHbTgCrAQhoDAAABwAiAGkMAAAHADoAawwAAAYAMQBqDAAABQBBAGwMAAAFADEAbQwAAAEAGgDqDAAABwA7AG4MAAAEACIADgAICXMR204AqwEIaAwAAAcAIgBpDAAABwA6AGsMAAAGADEAagwAAAUAQQBsDAAABQAxAG0MAAABABoA6gwAAAcAOwBuDAAABAAiAAAA.Eve:BAAALgAFFAMJBAABLgAFFAYJCgABAFwaAA==.Everd:BAABLgAECn84AAIBAAkJkxQJPwAAAgloDAAACAAjAGkMAAAIAD8AawwAAAgAQgBqDAAACAA7AGwMAAAHACIAbQwAAAQAOwDqDAAABgA9AG4MAAAGACEAbwwAAAEAQwABAAkJkxQJPwAAAgloDAAACAAjAGkMAAAIAD8AawwAAAgAQgBqDAAACAA7AGwMAAAHACIAbQwAAAQAOwDqDAAABgA9AG4MAAAGACEAbwwAAAEAQwAAAA==.Evren:BAAALgAFFAIJAwAAAA==.',
Fa='Faelilia:BAAALgADCgUJBQAAAA==.',
Fe='Felorana:BAAALgADCgYJBgAAAA==.Felzup:BAAALgAECgMJAwAAAA==.Feârless:BAAALgAECgYJBgAAAA==.',
Fi='Fiametta:BAABLgAECn8/AAIMAAgJSyLUAQCuAghoDAAACwBiAGkMAAAKAFsAawwAAAkAVgBqDAAACABMAGwMAAAHAEwAbQwAAAUASADqDAAACABdAG4MAAAFAGAADAAICUsi1AEArgIIaAwAAAsAYgBpDAAACgBbAGsMAAAJAFYAagwAAAgATABsDAAABwBMAG0MAAAFAEgA6gwAAAgAXQBuDAAABQBgAAAA.Finruil:BAAALgADCgYJCQAAAA==.Fireburst:BAAALgAECgIJAgAAAA==.',
Fl='Flameward:BAAALgAECgQJBAAAAA==.Flent:BAABLgAECn8bAAMPAAgJKgvfEgAkAQhoDAAABAAYAGkMAAAEAA4AawwAAAQAIQBqDAAABAA1AGwMAAAEABsAbQwAAAIAJQDqDAAAAgAsAG4MAAADABEADwAICSoL3xIAJAEIaAwAAAQAGABpDAAABAAOAGsMAAAEACEAagwAAAQANQBsDAAABAAbAG0MAAACACUA6gwAAAIALABuDAAAAgARAA4AAQmpBr0xAS4AAW4MAAABABEAAAA=.Florisá:BAAALgADCgQJBAABLgAECgMJAwALAAAAAA==.',
Fo='Forkingidiot:BAAALgADCgEJAQAAAA==.',
Fu='Funsize:BAAALgAECgUJCgAAAA==.',
Ga='Gabagoop:BAAALgAECggJEwAAAA==.Galindlianid:BAABLgAECn8jAAIBAAkJAASBvgD/AAloDAAABgAJAGkMAAAGABIAawwAAAYACABqDAAABAAaAGwMAAAEAAYAbQwAAAEACQDqDAAAAgADAG4MAAAFAAkAbwwAAAEADwABAAkJAASBvgD/AAloDAAABgAJAGkMAAAGABIAawwAAAYACABqDAAABAAaAGwMAAAEAAYAbQwAAAEACQDqDAAAAgADAG4MAAAFAAkAbwwAAAEADwAAAA==.Gazzlok:BAAALgAECgIJAgAAAA==.',
Ge='Gernik:BAAALgAECgEJAQAAAA==.Geryn:BAAALgADCgMJAwAAAA==.Gesen:BAAALgAECgIJBAAAAA==.',
Gh='Ghuldan:BAAALgAECgEJAQAAAA==.',
Gi='Gigaweenie:BAAALgAFFAIJBAAAAA==.',
Gl='Glavien:BAABLgAECn8xAAIBAAkJmA5oaACUAQloDAAACgA4AGkMAAAIADoAawwAAAcAIgBqDAAABQBAAGwMAAADABQAbQwAAAIAJQDqDAAACQAlAG4MAAAEACIAbwwAAAEAEwABAAkJmA5oaACUAQloDAAACgA4AGkMAAAIADoAawwAAAcAIgBqDAAABQBAAGwMAAADABQAbQwAAAIAJQDqDAAACQAlAG4MAAAEACIAbwwAAAEAEwAAAA==.Global:BAAALgADCgkJCQABLgAECgYJDAALAAAAAA==.',
Go='Gobtjr:BAAALgADCgMJAwAAAA==.',
Gr='Grandstorm:BAAALgADCgQJBAAAAA==.Greg:BAAALgADCgYJCAAAAA==.Grienke:BAAALgADCgQJBAABLgAECgkJMgAWADMgAA==.Grumpolbolt:BAABLgAECn8eAAIXAAgJ9RkuJwC/AQhoDAAABgBTAGkMAAAFAEgAawwAAAUATgBqDAAAAwBHAGwMAAAEAEAAbQwAAAEAIwDqDAAABQBNAG4MAAABADcAFwAICfUZLicAvwEIaAwAAAYAUwBpDAAABQBIAGsMAAAFAE4AagwAAAMARwBsDAAABABAAG0MAAABACMA6gwAAAUATQBuDAAAAQA3AAAA.',
Ha='Haenin:BAAALgAECgEJAwAAAA==.Haplo:BAAALgAECgQJBQAAAA==.Harnessme:BAAALgADCggJCwABLgAECggJHQAMAFQOAA==.Harps:BAAALgADCgYJBgAAAA==.',
He='Hellmet:BAAALgAECgQJBgAAAA==.Hey:BAACLgAFFH8IAAIKAAIJphqOFQCsAAJoDAAABQBNAOoMAAADADsACgACCaYajhUArAACaAwAAAUATQDqDAAAAwA7AC4ABAp/UQACCgAJCSci2wUASwMACgAJCSci2wUASwMAAAA=.',
Hi='Hidatix:BAAALgADCgEJAQAAAA==.Hinamori:BAAALgAECggJCgAAAA==.',
Ho='Homble:BAAALgADCgQJBAAAAA==.Horadin:BAAALgAECgMJAwAAAA==.',
Hu='Huntmeister:BAABLgAECn8qAAIOAAgJtyEEDQDWAghoDAAACQBhAGkMAAAKAGAAawwAAAgAYABqDAAAAgBUAGwMAAADAFIAbQwAAAIAOQDqDAAABgBhAG4MAAACAEwADgAICbchBA0A1gIIaAwAAAkAYQBpDAAACgBgAGsMAAAIAGAAagwAAAIAVABsDAAAAwBSAG0MAAACADkA6gwAAAYAYQBuDAAAAgBMAAAA.',
Ic='Iceehawt:BAABLgAECn8hAAIQAAgJuiInIQB9AghoDAAABwBhAGkMAAAFAGEAawwAAAUAYQBqDAAABABhAGwMAAACAEYAbQwAAAEAUwDqDAAABwBhAG4MAAACAE8AEAAICboiJyEAfQIIaAwAAAcAYQBpDAAABQBhAGsMAAAFAGEAagwAAAQAYQBsDAAAAgBGAG0MAAABAFMA6gwAAAcAYQBuDAAAAgBPAAAA.',
Il='Ilharra:BAABLgAECn8VAAMIAAUJ5Q1kTgDOAAVoDAAABQAjAGkMAAAFACYAawwAAAUAHABqDAAAAgAZAOoMAAAEACgACAAFCeUNZE4AzgAFaAwAAAQAIwBpDAAABAAmAGsMAAAEABwAagwAAAEAGQDqDAAAAgAoAAkABQmyAsJWAJIABWgMAAABAAQAaQwAAAEACABrDAAAAQAEAGoMAAABAAwA6gwAAAIABAAAAA==.Ilililili:BAAALgAECgQJBQAAAA==.Illee:BAAALgAECgcJEgAAAA==.Illuminara:BAAALgADCgYJEQAAAA==.',
Im='Imdrood:BAAALgADCgMJAwABLgAFFAMJCAASAFEgAA==.Imturtle:BAACLgAFFH8IAAMSAAMJUSCZFwAYAQNoDAAAAwBZAGkMAAACAEcA6gwAAAMAVwASAAMJUSCZFwAYAQNoDAAAAwBZAGkMAAACAEcA6gwAAAIAVwAQAAEJLBMt/ABEAAHqDAAAAQAxAC4ABAp/RgADEgAJCXAjngIAHgMAEgAJCXAjngIAHgMAEAAHCf8Us6cAGQEAAAA=.',
In='Insømniadk:BAABLgAFFH8JAAIQAAMJwiCYggDyAANoDAAAAwBOAGkMAAACAFgA6gwAAAQAVAAQAAMJwiCYggDyAANoDAAAAwBOAGkMAAACAFgA6gwAAAQAVAABLgAFFAYJHAAQAOkgAA==.',
Is='Isshiny:BAABLgAECn8ZAAIBAAgJGxnnSQDfAQhoDAAABABbAGkMAAAEAEIAawwAAAQAQQBqDAAAAwBYAGwMAAACADYA6gwAAAUATwBuDAAAAgA0AG8MAAABACcAAQAICRsZ50kA3wEIaAwAAAQAWwBpDAAABABCAGsMAAAEAEEAagwAAAMAWABsDAAAAgA2AOoMAAAFAE8AbgwAAAIANABvDAAAAQAnAAAA.Isweat:BAAALgAECgMJAwABLgAECgQJBQALAAAAAA==.',
Iu='Iupiter:BAAALgAECgcJEwAAAA==.',
Iv='Ivelos:BAAALgADCgIJAwAAAA==.',
Iy='Iyahlieairia:BAAALgAECgUJBQAAAA==.',
Iz='Izabeth:BAABLgAECn8eAAIEAAgJPg29dgCGAQhoDAAABgAoAGkMAAAEACEAawwAAAUAHwBqDAAABAAXAGwMAAADABoAbQwAAAEAMQDqDAAABgAiAG8MAAABABQABAAICT4NvXYAhgEIaAwAAAYAKABpDAAABAAhAGsMAAAFAB8AagwAAAQAFwBsDAAAAwAaAG0MAAABADEA6gwAAAYAIgBvDAAAAQAUAAAA.',
Ja='Jacaar:BAAALgADCgUJBQAAAA==.Jamella:BAABLgAECn8sAAIYAAgJDA9JFwBaAQhoDAAABwA4AGkMAAAHADcAawwAAAYAEQBqDAAABgA2AGwMAAAGAC0AbQwAAAEAEgDqDAAABwA0AG4MAAAEABgAGAAICQwPSRcAWgEIaAwAAAcAOABpDAAABwA3AGsMAAAGABEAagwAAAYANgBsDAAABgAtAG0MAAABABIA6gwAAAcANABuDAAABAAYAAAA.',
Je='Jessabella:BAAALgADCgQJBAAAAA==.Jesyikaxyz:BAAALgAECgkJCgAAAA==.',
Ji='Jifycornbred:BAAALgAECgMJAwAAAA==.Jigles:BAAALgAECgEJAQAAAA==.',
['Jä']='Jägermeister:BAAALgAECgIJBAABLgAECgUJBQALAAAAAA==.',
Ka='Kaelynia:BAAALgADCgYJCgAAAA==.Kagosi:BAAALgAECgQJBwAAAA==.Kairn:BAAALgADCgcJBwAAAA==.Kalivath:BAAALgADCgUJCAAAAA==.Kalypso:BAAALgADCgkJCQAAAA==.Kardaa:BAAALgADCgEJAQAAAA==.Kat:BAABLgAECn8gAAIKAAkJzQV4XwAOAQloDAAAAwASAGkMAAADAAUAawwAAAQABgBqDAAAAwAIAGwMAAAGAD0AbQwAAAMABQDqDAAABgAMAG4MAAADAAYAbwwAAAEACAAKAAkJzQV4XwAOAQloDAAAAwASAGkMAAADAAUAawwAAAQABgBqDAAAAwAIAGwMAAAGAD0AbQwAAAMABQDqDAAABgAMAG4MAAADAAYAbwwAAAEACAAAAA==.Kawi:BAAALgADCgEJAQAAAA==.Kazakusan:BAAALgAECgUJBgAAAA==.',
Ki='Kialla:BAAALgADCgYJCQABLgAECgkJGAABAH4YAA==.Kiraneem:BAABLgAECn8sAAMOAAkJUBpTJgA9AgloDAAABwBNAGkMAAAGAEAAawwAAAUAMgBqDAAABwBRAGwMAAAGAE0AbQwAAAMARQDqDAAABgBRAG4MAAACACQAbwwAAAIAUQAOAAkJUBpTJgA9AgloDAAABgBNAGkMAAAGAEAAawwAAAUAMgBqDAAABwBRAGwMAAAGAE0AbQwAAAMARQDqDAAABgBRAG4MAAACACQAbwwAAAIAUQAPAAEJ2wGjlwAgAAFoDAAAAQAEAAAA.Kittie:BAABLgAECn9DAAMKAAkJHBY9HQBYAgloDAAACQA1AGkMAAAJAEMAawwAAAkATwBqDAAACQA8AGwMAAAJADUAbQwAAAYAPgDqDAAACAAoAG4MAAAEAD4AbwwAAAQAHQAKAAkJHBY9HQBYAgloDAAACQA1AGkMAAAHAEMAawwAAAcATwBqDAAABwA8AGwMAAAHADUAbQwAAAYAPgDqDAAACAAoAG4MAAAEAD4AbwwAAAQAHQADAAQJZgx2cACKAARpDAAAAgAhAGsMAAACACYAagwAAAIALgBsDAAAAgAWAAAA.',
Ko='Kongfupanda:BAAALgAECgYJBgAAAA==.Kotenok:BAAALgAECgYJBgAAAA==.',
Kr='Kreyaa:BAABLgAECn8XAAIEAAgJchARfgB2AQhoDAAABQAqAGkMAAAEADUAawwAAAMAKQBqDAAAAwA1AGwMAAABABgAbQwAAAIAOQDqDAAABAA2AG4MAAABABQABAAICXIQEX4AdgEIaAwAAAUAKgBpDAAABAA1AGsMAAADACkAagwAAAMANQBsDAAAAQAYAG0MAAACADkA6gwAAAQANgBuDAAAAQAUAAAA.Krinj:BAABLgAECn8oAAIQAAkJZh2NRADvAQloDAAACABRAGkMAAAFAFUAawwAAAUARwBqDAAABABhAGwMAAADAFAAbQwAAAIAPQDqDAAABwBJAG4MAAAEAE8AbwwAAAIARAAQAAkJZh2NRADvAQloDAAACABRAGkMAAAFAFUAawwAAAUARwBqDAAABABhAGwMAAADAFAAbQwAAAIAPQDqDAAABwBJAG4MAAAEAE8AbwwAAAIARAAAAA==.Kristov:BAAALgAECgIJAgAAAA==.',
Kt='Ktariani:BAAALgAECgQJBAAAAA==.',
Ky='Kyarla:BAABLgAECn8jAAIZAAUJ6hWGNgAYAQVoDAAACQBDAGkMAAAJAFAAawwAAAoAJwBqDAAABQA2AGwMAAACACUAGQAFCeoVhjYAGAEFaAwAAAkAQwBpDAAACQBQAGsMAAAKACcAagwAAAUANgBsDAAAAgAlAAAA.Kydo:BAACLgAFFH8HAAIEAAMJfQlKgQDRAANoDAAAAgAYAGkMAAACACEA6gwAAAMADwAEAAMJfQlKgQDRAANoDAAAAgAYAGkMAAACACEA6gwAAAMADwAuAAQKfyYAAgQABwm9GGNkAK8BAAQABwm9GGNkAK8BAAAA.Kythera:BAAALgAECgQJBwAAAA==.',
['Kø']='Køe:BAAALgADCgQJBAABLgAECgEJAQALAAAAAA==.',
La='Lamp:BAAALgAECgQJBQAAAA==.',
Le='Ledani:BAABLgAECn82AAMIAAkJTRSXFwAEAgloDAAACgA+AGkMAAAJAC8AawwAAAgARQBqDAAABgA9AGwMAAAEACEAbQwAAAMANgDqDAAACQA+AG4MAAAEACgAbwwAAAEALgAIAAkJTRSXFwAEAgloDAAACgA+AGkMAAAJAC8AawwAAAgARQBqDAAABgA9AGwMAAAEACEAbQwAAAMANgDqDAAACQA+AG4MAAADACgAbwwAAAEALgAZAAEJpQprdAAgAAFuDAAAAQAbAAAA.Leøna:BAAALgADCgEJAQAAAA==.',
Li='Liberi:BAAALgADCgEJAQAAAA==.Lightwràth:BAAALgADCgMJAwAAAA==.Lincecum:BAAALgAECggJEAABLgAECgkJMgAWADMgAA==.Lioni:BAAALgADCgkJCQAAAA==.Listen:BAABLgAECn9bAAIXAAkJoR4UCQCJAgloDAAAEQBIAGkMAAAMAE0AawwAAAwAUwBqDAAACgBKAGwMAAALAFMAbQwAAAgAQADqDAAACgBaAG4MAAAJAE4AbwwAAAIATAAXAAkJoR4UCQCJAgloDAAAEQBIAGkMAAAMAE0AawwAAAwAUwBqDAAACgBKAGwMAAALAFMAbQwAAAgAQADqDAAACgBaAG4MAAAJAE4AbwwAAAIATAAAAA==.',
Lo='Loachapoka:BAAALgADCgYJDQAAAA==.Lohith:BAAALgAECgQJBAAAAA==.Lonedawg:BAAALgAECgQJBQAAAA==.Lovécoil:BAAALgAECgEJAQAAAA==.Loweform:BAAALgADCgEJAQAAAA==.',
Lu='Lunâ:BAABLgAECn80AAIJAAkJvxnkCwClAgloDAAACgBJAGkMAAAIAE4AawwAAAcASQBqDAAABgBGAGwMAAAEAFYAbQwAAAMAOgDqDAAACQBMAG4MAAAEADAAbwwAAAEAGgAJAAkJvxnkCwClAgloDAAACgBJAGkMAAAIAE4AawwAAAcASQBqDAAABgBGAGwMAAAEAFYAbQwAAAMAOgDqDAAACQBMAG4MAAAEADAAbwwAAAEAGgAAAA==.Luwud:BAAALgADCgcJEAAAAA==.',
Ly='Lyrei:BAABLgAECn8kAAQFAAkJGBkaLgAEAgloDAAACABLAGkMAAAFADwAawwAAAQAMgBqDAAAAwA/AGwMAAACADkAbQwAAAIARQDqDAAABwBTAG4MAAAEAD4AbwwAAAEANgAFAAkJlxYaLgAEAgloDAAACABLAGkMAAAEAAkAawwAAAMAMgBqDAAAAwA/AGwMAAABADkAbQwAAAIARQDqDAAABwBTAG4MAAADAD4AbwwAAAEANgARAAMJ7BEFPwCqAANpDAAAAQA8AGsMAAABADIAbAwAAAEAGgAaAAEJZw7IMQAyAAFuDAAAAQAkAAAA.',
['Lë']='Lëw:BAAALgAFFAEJAQAAAA==.',
Ma='Macfrost:BAAALgADCgUJBgABLgAECgEJBQALAAAAAA==.Machiavelli:BAAALgADCgUJBQAAAA==.Maddox:BAABLgAECn8ZAAIbAAgJLwqADABDAQhoDAAAAwAYAGkMAAADABgAawwAAAMAFABqDAAAAwAaAGwMAAAFABwAbQwAAAIAHADqDAAABAAfAG4MAAACABkAGwAICS8KgAwAQwEIaAwAAAMAGABpDAAAAwAYAGsMAAADABQAagwAAAMAGgBsDAAABQAcAG0MAAACABwA6gwAAAQAHwBuDAAAAgAZAAAA.Magichandz:BAAALgAECgYJCQAAAA==.Maikakx:BAAALgAECgEJAQAAAA==.Marsyx:BAABLgAECn8gAAIZAAkJBR9rCgC1AgloDAAABwBeAGkMAAAEAE0AawwAAAQAYABqDAAAAgBjAGwMAAACAEsAbQwAAAIAJADqDAAABgBdAG4MAAADAGAAbwwAAAIAKwAZAAkJBR9rCgC1AgloDAAABwBeAGkMAAAEAE0AawwAAAQAYABqDAAAAgBjAGwMAAACAEsAbQwAAAIAJADqDAAABgBdAG4MAAADAGAAbwwAAAIAKwAAAA==.Masfonos:BAAALgADCgEJAQAAAA==.Mayael:BAAALgAECgcJEAAAAA==.Maíkeru:BAAALgADCgEJAQAAAA==.',
Mc='Mcguffinss:BAACLgAFFH8FAAMcAAMJVRnGGABXAANoDAAAAwBaAGkMAAABAEoA6gwAAAEAHgANAAIJhReihwClAAJoDAAAAwBaAOoMAAABAB4AHAABCfMcxhgAVwABaQwAAAEASgAuAAQKfx0AAw0ACQl4JYw4ACkCAA0ABwnEJYw4ACkCAAwAAwm6InEnACYBAAAA.',
Me='Medreaux:BAABLgAECn9NAAIZAAkJuhyXCQDDAgloDAAADgBMAGkMAAAKAFoAawwAAAoAWABqDAAACABTAGwMAAAKAE8AbQwAAAYAVADqDAAACABRAG4MAAAJADkAbwwAAAIAFAAZAAkJuhyXCQDDAgloDAAADgBMAGkMAAAKAFoAawwAAAoAWABqDAAACABTAGwMAAAKAE8AbQwAAAYAVADqDAAACABRAG4MAAAJADkAbwwAAAIAFAAAAA==.Metalknyte:BAABLgAECn8sAAISAAkJRxB6GACTAQloDAAABwBJAGkMAAAGACIAawwAAAUAGwBqDAAABwBKAGwMAAAGAEAAbQwAAAMAHwDqDAAABgAaAG4MAAACABsAbwwAAAIALwASAAkJRxB6GACTAQloDAAABwBJAGkMAAAGACIAawwAAAUAGwBqDAAABwBKAGwMAAAGAEAAbQwAAAMAHwDqDAAABgAaAG4MAAACABsAbwwAAAIALwAAAA==.',
Mi='Miniknyte:BAABLgAECn8fAAIUAAkJBAyHSwBYAQloDAAABQA9AGkMAAADABsAawwAAAMAHwBqDAAABQAXAGwMAAAEABwAbQwAAAMAJADqDAAABAAaAG4MAAACABUAbwwAAAIAFQAUAAkJBAyHSwBYAQloDAAABQA9AGkMAAADABsAawwAAAMAHwBqDAAABQAXAGwMAAAEABwAbQwAAAMAJADqDAAABAAaAG4MAAACABUAbwwAAAIAFQAAAA==.Minotauren:BAAALgADCgYJBQAAAA==.Misskitty:BAABLgAECn8aAAIHAAcJiiD9CQAVAgdoDAAABgBhAGkMAAAFAGAAawwAAAQAXwBqDAAAAwBXAGwMAAACAEEA6gwAAAUAYQBuDAAAAQAvAAcABwmKIP0JABUCB2gMAAAGAGEAaQwAAAUAYABrDAAABABfAGoMAAADAFcAbAwAAAIAQQDqDAAABQBhAG4MAAABAC8AAAA=.',
Mo='Modnoc:BAAALgAECgYJDAAAAA==.Mogden:BAAALgAFFAEJAQABLgAECgkJIAAFAIIgAA==.Mollog:BAAALgAECgMJAwAAAA==.Mommii:BAAALgADCgEJAQABLgAECgEJAQALAAAAAA==.Moondanas:BAAALgADCgMJAwAAAA==.Moonshine:BAAALgADCgUJCAAAAA==.Moonsz:BAAALgADCgkJSwAAAA==.Morghulis:BAAALgAECgUJBQAAAA==.',
Mu='Mugmug:BAAALgADCgUJBgAAAA==.Mukakin:BAAALgADCgEJAQAAAA==.',
My='Mychelle:BAABLgAECn83AAMdAAkJVRZvEAAoAgloDAAACwBOAGkMAAAJAEEAawwAAAgAOQBqDAAABgBMAGwMAAAEADAAbQwAAAMAOgDqDAAACQBJAG4MAAAEADEAbwwAAAEAGgAdAAkJ3hJvEAAoAgloDAAAAgA7AGkMAAACAC8AawwAAAIAOQBqDAAAAgA6AGwMAAACADAAbQwAAAIAMQDqDAAAAgAvAG4MAAACADEAbwwAAAEAGgAPAAgJ3hUdCwCqAQhoDAAACQBOAGkMAAAHAEEAawwAAAYAMgBqDAAABABMAGwMAAACACIAbQwAAAEAOgDqDAAABwBJAG4MAAACAB8AAAA=.',
['Mø']='Møgwai:BAAALgAECgEJAQAAAA==.',
Na='Nakryn:BAABLgAECn84AAIEAAgJ6Qk+jQBYAQhoDAAACQAvAGkMAAAIABgAawwAAAgAHQBqDAAACAAZAGwMAAAHACIAbQwAAAUAEADqDAAACQARAG4MAAACAAYABAAICekJPo0AWAEIaAwAAAkALwBpDAAACAAYAGsMAAAIAB0AagwAAAgAGQBsDAAABwAiAG0MAAAFABAA6gwAAAkAEQBuDAAAAgAGAAAA.Naluai:BAAALgADCgEJAQAAAA==.Nandami:BAAALgADCgIJAgAAAA==.Nary:BAAALgAECgkJCgAAAA==.Naryeth:BAAALgAECggJCAAAAA==.Narysham:BAAALgADCgIJAgAAAA==.',
Ne='Neazth:BAAALgADCgEJAQABLgAECgUJDAALAAAAAA==.Nezaeth:BAAALgAECgUJDAAAAA==.Nezum:BAAALgADCggJEAABLgAECgUJDAALAAAAAA==.',
Ni='Nickoli:BAAALgAECgQJBAAAAA==.Nightshade:BAAALgADCgkJEgAAAA==.',
No='Nohnehn:BAAALgAECgEJBQAAAA==.Nojomo:BAAALgAECgMJAwAAAA==.Nojomoto:BAAALgAECgIJBAAAAA==.Norabel:BAAALgAECgYJDQAAAA==.',
Ny='Nyra:BAABLgAECn8qAAIOAAkJ6B7LEADCAgloDAAACABcAGkMAAAFAFEAawwAAAUATgBqDAAABgBOAGwMAAAFAEcAbQwAAAMAXQDqDAAABwBXAG4MAAACAEUAbwwAAAEAOgAOAAkJ6B7LEADCAgloDAAACABcAGkMAAAFAFEAawwAAAUATgBqDAAABgBOAGwMAAAFAEcAbQwAAAMAXQDqDAAABwBXAG4MAAACAEUAbwwAAAEAOgAAAA==.',
['Nø']='Nøxxi:BAABLgAECn89AAMMAAkJbh3sAQCpAgloDAAACwBaAGkMAAAJAEwAawwAAAoATQBqDAAACQBCAGwMAAAHAEsAbQwAAAQAPADqDAAABwBXAG4MAAACADgAbwwAAAIATQAMAAkJbh3sAQCpAgloDAAACgBaAGkMAAAIAEwAawwAAAkATQBqDAAACABCAGwMAAAGAEsAbQwAAAQAPADqDAAABgBXAG4MAAACADgAbwwAAAIATQANAAYJ2AuJowD1AAZoDAAAAQAXAGkMAAABAC8AawwAAAEAEgBqDAAAAQAOAGwMAAABACEA6gwAAAEAHAAAAA==.',
Oc='Ocon:BAAALgADCgUJBQAAAA==.',
Ok='Okbloomer:BAABLgAECn8fAAMeAAkJ2B7MDwBZAgloDAAABABaAGkMAAAEAF0AawwAAAQAWgBqDAAABABCAGwMAAAEAFkAbQwAAAUATQDqDAAABABgAG4MAAABABoAbwwAAAEAQgAeAAkJ2B7MDwBZAgloDAAAAwBaAGkMAAADAF0AawwAAAMAWgBqDAAAAwBCAGwMAAADAFkAbQwAAAQATQDqDAAAAwBgAG4MAAABABoAbwwAAAEAQgAUAAcJLQ4qXwA0AQdoDAAAAQBGAGkMAAABAAMAawwAAAEAGABqDAAAAQAIAGwMAAABACIAbQwAAAEAIQDqDAAAAQBNAAEuAAUUAwkFAAQAQAQA.',
Ol='Oldben:BAABLgAFFH8GAAIBAAIJhwarkACCAAJoDAAAAwAOAGkMAAADABMAAQACCYcGq5AAggACaAwAAAMADgBpDAAAAwATAAAA.',
Op='Optometrist:BAAALgADCgcJBwAAAA==.',
Or='Orckeferal:BAAALgADCgYJCQABLgAFFAgJJAAfAJAfAA==.Oriel:BAABLgAECn8sAAIJAAkJXQpZJACgAQloDAAABwAjAGkMAAAGACoAawwAAAUAHABqDAAABwARAGwMAAAGAC4AbQwAAAMAEwDqDAAABgARAG4MAAACAA8AbwwAAAIADgAJAAkJXQpZJACgAQloDAAABwAjAGkMAAAGACoAawwAAAUAHABqDAAABwARAGwMAAAGAC4AbQwAAAMAEwDqDAAABgARAG4MAAACAA8AbwwAAAIADgAAAA==.Orthein:BAAALgAECgQJBgABLgAECgcJEAALAAAAAA==.',
Pa='Paleblueeye:BAAALgAECgEJAgAAAA==.Pawarwar:BAAALgADCgMJAwAAAA==.',
Pe='Pedrita:BAAALgADCgQJBAAAAA==.',
Ph='Phindin:BAABLgAECn84AAMDAAkJHRNLIwC/AQloDAAACAA9AGkMAAAHACUAawwAAAcAOABqDAAABwBAAGwMAAAHACEAbQwAAAUAJwDqDAAACAA9AG4MAAAEAC8AbwwAAAMANQADAAkJHRNLIwC/AQloDAAABwA9AGkMAAAGACUAawwAAAYAOABqDAAABgBAAGwMAAAGACEAbQwAAAQAJwDqDAAABwA9AG4MAAAEAC8AbwwAAAMANQAKAAcJxwWKdQDuAAdoDAAAAQAHAGkMAAABAAYAawwAAAEAGgBqDAAAAQAHAGwMAAABAC4AbQwAAAEABADqDAAAAQAEAAAA.',
Pi='Pixystix:BAAALgADCgkJCQABLgAECgkJNwAdAFUWAA==.',
Po='Poc:BAABLgAECn8kAAIHAAgJHBEzFABvAQhoDAAABAA3AGkMAAAFADIAawwAAAYAJABqDAAAAwAsAGwMAAADACMAbQwAAAEAIQDqDAAABwAoAG4MAAAHADYABwAICRwRMxQAbwEIaAwAAAQANwBpDAAABQAyAGsMAAAGACQAagwAAAMALABsDAAAAwAjAG0MAAABACEA6gwAAAcAKABuDAAABwA2AAAA.Pokoko:BAAALgADCgUJBgAAAA==.',
Pr='Priblet:BAAALgAECgkJCwAAAA==.Primo:BAAALgAECgYJDAAAAA==.Prinsana:BAABLgAECn8sAAIYAAkJsBJjEACyAQloDAAABwA7AGkMAAAGADIAawwAAAUARQBqDAAABwAxAGwMAAAGADIAbQwAAAMANQDqDAAABgAzAG4MAAACACIAbwwAAAIADQAYAAkJsBJjEACyAQloDAAABwA7AGkMAAAGADIAawwAAAUARQBqDAAABwAxAGwMAAAGADIAbQwAAAMANQDqDAAABgAzAG4MAAACACIAbwwAAAIADQAAAA==.',
Pu='Puddytat:BAAALgADCgMJAwAAAA==.Purged:BAABLgAECn8gAAIKAAkJOAb6WgA/AQloDAAABAAaAGkMAAAEAA4AawwAAAQAEwBqDAAAAwAHAGwMAAAEAB4AbQwAAAIABgDqDAAABwAJAG4MAAACAAQAbwwAAAIAFgAKAAkJOAb6WgA/AQloDAAABAAaAGkMAAAEAA4AawwAAAQAEwBqDAAAAwAHAGwMAAAEAB4AbQwAAAIABgDqDAAABwAJAG4MAAACAAQAbwwAAAIAFgAAAA==.Purquis:BAAALgAECgEJAQAAAA==.',
Py='Pya:BAAALgAECgEJAQAAAA==.',
Ra='Ragnus:BAAALgADCgEJAQAAAA==.Raidwipe:BAAALgADCgIJAgABLgAECgcJEAALAAAAAA==.Ralphie:BAAALgADCgcJAQAAAA==.Rasen:BAAALgAECgIJAgABLgAECgUJBQALAAAAAA==.Ratheer:BAABLgAFFH8FAAIFAAIJSRUWcwCIAAJoDAAAAgA8AOoMAAADADAABQACCUkVFnMAiAACaAwAAAIAPADqDAAAAwAwAAEuAAUUAwkFABwAVRkA.Rawfalafel:BAAALgAECggJEwAAAA==.',
Re='Reaperlord:BAABLgAECn8sAAIgAAgJ1huGEQCAAghoDAAABwBYAGkMAAAHAEQAawwAAAYAUwBqDAAABgBTAGwMAAAGAEgAbQwAAAEAKgDqDAAABwBHAG4MAAAEADsAIAAICdYbhhEAgAIIaAwAAAcAWABpDAAABwBEAGsMAAAGAFMAagwAAAYAUwBsDAAABgBIAG0MAAABACoA6gwAAAcARwBuDAAABAA7AAAA.',
Rh='Rhoana:BAAALgADCgcJBwAAAA==.',
Rl='Rllybuffnerd:BAAALgAECgIJAgAAAA==.',
Ro='Rodikus:BAACLgAFFH8KAAIZAAQJkRi4EAA4AQRoDAAAAwBUAGkMAAACAB0AawwAAAEANwDqDAAABABSABkABAmRGLgQADgBBGgMAAADAFQAaQwAAAIAHQBrDAAAAQA3AOoMAAAEAFIALgAECn89AAMZAAkJ8yFLEABZAgAZAAgJXSJLEABZAgAIAAkJmBXtFQAUAgAAAA==.Rootbeer:BAAALgADCgYJBgAAAA==.Rorax:BAABLgAECn8jAAIFAAgJxRmKNADpAQhoDAAABQBIAGkMAAAFAEcAawwAAAUALgBqDAAABQBYAGwMAAAFAFAAbQwAAAEAOwDqDAAABgBHAG4MAAADADwABQAICcUZijQA6QEIaAwAAAUASABpDAAABQBHAGsMAAAFAC4AagwAAAUAWABsDAAABQBQAG0MAAABADsA6gwAAAYARwBuDAAAAwA8AAAA.Rosanna:BAAALgAECgQJBQAAAA==.',
Rp='Rprunner:BAAALgAECgUJBQABLgAECgcJFgAVAJwPAA==.',
Ru='Rukus:BAAALgADCgQJBAAAAA==.',
['Rä']='Räwry:BAAALgAFFAQJBAABLgAFFAMJCAAJAAoMAA==.',
Sa='Saiaa:BAAALgAECgkJEQAAAA==.Sakeena:BAAALgAECgQJBQAAAA==.Samará:BAAALgAECgIJBgAAAA==.Sarleigh:BAABLgAECn8WAAIIAAYJrAL4YACIAAZoDAAABQAEAGkMAAAFAA4AawwAAAUABgBqDAAAAgAMAGwMAAABAAMA6gwAAAQABAAIAAYJrAL4YACIAAZoDAAABQAEAGkMAAAFAA4AawwAAAUABgBqDAAAAgAMAGwMAAABAAMA6gwAAAQABAAAAA==.Sattia:BAABLgAECn9DAAIUAAkJzAZ3WQAjAQloDAAACgATAGkMAAAJABsAawwAAAoAEABqDAAACAAXAGwMAAAHABUAbQwAAAUACADqDAAACQATAG4MAAAHAAsAbwwAAAIACAAUAAkJzAZ3WQAjAQloDAAACgATAGkMAAAJABsAawwAAAoAEABqDAAACAAXAGwMAAAHABUAbQwAAAUACADqDAAACQATAG4MAAAHAAsAbwwAAAIACAAAAA==.',
Sc='Scampington:BAAALgAECgUJBgAAAA==.',
Se='Sertzert:BAABLgAECn8WAAIHAAYJXhj+GQAtAQZoDAAABQBJAGkMAAAEAD8AawwAAAMANgBqDAAABABQAGwMAAACADcA6gwAAAQAQQAHAAYJXhj+GQAtAQZoDAAABQBJAGkMAAAEAD8AawwAAAMANgBqDAAABABQAGwMAAACADcA6gwAAAQAQQAAAA==.',
Sh='Sharokk:BAAALgAECgcJBwABLgAECggJIwAFAMUZAA==.Sharrow:BAAALgAECgMJAwAAAA==.Shiggy:BAAALgAECgIJAgAAAA==.Shinokami:BAABLgAECn8sAAMTAAgJURIgJgB2AQhoDAAABwAoAGkMAAAHADoAawwAAAYAJgBqDAAABgA1AGwMAAAGADUAbQwAAAEALwDqDAAABwAxAG4MAAAEACgAEwAICWcRICYAdgEIaAwAAAcAKABpDAAABwA6AGsMAAAGACYAagwAAAYANQBsDAAABgA1AG0MAAABAC8A6gwAAAcAMQBuDAAAAgAXABUAAQm6D3KSADQAAW4MAAACACgAAAA=.Shoto:BAAALgADCgEJAQAAAA==.',
Si='Silentninjaa:BAABLgAECn81AAIhAAkJUBx1DwB5AgloDAAABwAyAGkMAAAHAFEAawwAAAcAVwBqDAAABgA4AGwMAAAGAE4AbQwAAAUAVQDqDAAABwBNAG4MAAAFADkAbwwAAAMAPQAhAAkJUBx1DwB5AgloDAAABwAyAGkMAAAHAFEAawwAAAcAVwBqDAAABgA4AGwMAAAGAE4AbQwAAAUAVQDqDAAABwBNAG4MAAAFADkAbwwAAAMAPQAAAA==.Simphunter:BAEBLgAECn83AAIFAAkJfB4iEAC5AgloDAAACABZAGkMAAAIAFEAawwAAAgAWABqDAAABgA4AGwMAAAGAFcAbQwAAAQARgDqDAAACABOAG4MAAAFAEkAbwwAAAIANQAFAAkJfB4iEAC5AgloDAAACABZAGkMAAAIAFEAawwAAAgAWABqDAAABgA4AGwMAAAGAFcAbQwAAAQARgDqDAAACABOAG4MAAAFAEkAbwwAAAIANQAAAA==.Sinchan:BAAALgADCgEJAQAAAA==.Sindaea:BAAALgADCgYJBgAAAA==.Sinfel:BAABLgAECn8xAAIRAAkJPA5sGwCUAQloDAAACgA7AGkMAAAIADcAawwAAAcAGABqDAAABQAiAGwMAAADACQAbQwAAAIADwDqDAAACQA8AG4MAAAEABQAbwwAAAEAEwARAAkJPA5sGwCUAQloDAAACgA7AGkMAAAIADcAawwAAAcAGABqDAAABQAiAGwMAAADACQAbQwAAAIADwDqDAAACQA8AG4MAAAEABQAbwwAAAEAEwAAAA==.Sit:BAAALgAECgcJEAAAAA==.',
Sk='Skall:BAAALgAECgEJAQAAAA==.Skoree:BAABLgAECn8gAAIFAAkJgiC/GQC6AgloDAAABgBiAGkMAAAEAF8AawwAAAQAUQBqDAAAAwBbAGwMAAADAF0AbQwAAAIASgDqDAAABQBfAG4MAAADADsAbwwAAAIAQwAFAAkJgiC/GQC6AgloDAAABgBiAGkMAAAEAF8AawwAAAQAUQBqDAAAAwBbAGwMAAADAF0AbQwAAAIASgDqDAAABQBfAG4MAAADADsAbwwAAAIAQwAAAA==.',
Sl='Slït:BAAALgADCgIJAgAAAA==.',
Sm='Smellme:BAAALgAECgMJAwAAAA==.Smothbran:BAAALgADCgIJAwAAAA==.',
Sn='Snapdragon:BAAALgAECgQJBgAAAA==.',
So='Soluna:BAAALgAECgQJBAAAAA==.Someonelse:BAAALgAECgMJAwAAAA==.Sonett:BAAALgAECgQJBQAAAA==.',
Sp='Splunk:BAAALgAECgkJEQABLgAECgkJFwATABULAA==.Spânky:BAAALgAECgYJEQAAAA==.Spíké:BAAALgADCgkJCQAAAA==.',
Sq='Squiggles:BAABLgAECn8jAAIPAAkJxxO2CADkAQloDAAABQBNAGkMAAAGADkAawwAAAMAGgBqDAAABQA7AGwMAAAFACIAbQwAAAMAPQDqDAAABAAxAG4MAAACABcAbwwAAAIASQAPAAkJxxO2CADkAQloDAAABQBNAGkMAAAGADkAawwAAAMAGgBqDAAABQA7AGwMAAAFACIAbQwAAAMAPQDqDAAABAAxAG4MAAACABcAbwwAAAIASQAAAA==.',
St='Staggerdaddy:BAAALgADCgYJBgAAAA==.Stariya:BAAALgAECgQJBQAAAA==.Stillwing:BAAALgADCgIJAgAAAA==.Stormkraa:BAAALgAECgkJBgAAAA==.Strawyà:BAAALgADCgQJBwABLgAECgkJOgAYANAbAA==.Strawyæ:BAABLgAECn86AAIYAAkJ0BvFBwBUAgloDAAABwBNAGkMAAAHAFIAawwAAAcAUwBqDAAABgBGAGwMAAAHAE8AbQwAAAYAQwDqDAAACABGAG4MAAAGADEAbwwAAAQAOgAYAAkJ0BvFBwBUAgloDAAABwBNAGkMAAAHAFIAawwAAAcAUwBqDAAABgBGAGwMAAAHAE8AbQwAAAYAQwDqDAAACABGAG4MAAAGADEAbwwAAAQAOgAAAA==.Strike:BAAALgAECgYJCAABLgAFFAUJEgAgAGYUAA==.',
Su='Succubi:BAAALgADCgIJAgAAAA==.Sugerfree:BAAALgAECgYJDAAAAA==.Suttercane:BAAALgAECgYJCQAAAA==.',
['Sì']='Sìrocco:BAAALgAECgYJBwAAAA==.',
Ta='Taleranor:BAAALgAECgcJEwAAAA==.Tallaeya:BAAALgAECgIJAgAAAA==.Tamerizer:BAABLgAECn8sAAMdAAkJhRMPEgAXAgloDAAABgAlAGkMAAAFADIAawwAAAUALgBqDAAABAA1AGwMAAAFADIAbQwAAAMAJADqDAAABgAtAG4MAAAHAFUAbwwAAAMALwAdAAkJZxEPEgAXAgloDAAAAgAfAGkMAAACADAAawwAAAIAGQBqDAAAAwA1AGwMAAAEADIAbQwAAAMAJADqDAAAAwAfAG4MAAAHAFUAbwwAAAMALwAPAAYJ8xAkRABFAQZoDAAABAAlAGkMAAADADIAawwAAAMALgBqDAAAAQAbAGwMAAABACQA6gwAAAMALQAAAA==.',
Te='Tealera:BAAALgAECgMJAwAAAA==.Teejrath:BAAALgAECgYJCAAAAA==.Teekeez:BAABLgAECn8bAAIEAAgJmQgqvQAKAQhoDAAABAAhAGkMAAAEACcAawwAAAQAFwBqDAAABAAdAGwMAAAFAA8AbQwAAAEAAwDqDAAABAAbAG4MAAABAAsABAAICZkIKr0ACgEIaAwAAAQAIQBpDAAABAAnAGsMAAAEABcAagwAAAQAHQBsDAAABQAPAG0MAAABAAMA6gwAAAQAGwBuDAAAAQALAAAA.Terup:BAAALgADCgUJBQAAAA==.',
Th='Theodorel:BAAALgAECgIJAgAAAA==.Thillarys:BAAALgAECgEJAQAAAA==.Thirge:BAABLgAECn83AAIhAAkJAhfVGQAZAgloDAAACwA9AGkMAAAJAFIAawwAAAgAMwBqDAAABgBDAGwMAAAEADcAbQwAAAIAIwDqDAAACgBBAG4MAAAEAD8AbwwAAAEANgAhAAkJAhfVGQAZAgloDAAACwA9AGkMAAAJAFIAawwAAAgAMwBqDAAABgBDAGwMAAAEADcAbQwAAAIAIwDqDAAACgBBAG4MAAAEAD8AbwwAAAEANgAAAA==.Thorek:BAAALgADCgkJGQAAAA==.Thrushbeard:BAAALgADCgkJHwAAAA==.Thunderracks:BAAALgAECgEJAQAAAA==.',
To='Tokas:BAAALgAECgIJAgAAAA==.Tolak:BAAALgAECgUJCwAAAA==.Torturousôwl:BAAALgAECgkJEAAAAA==.',
Tr='Traaze:BAAALgAECgYJDAABLgAFFAYJCwAEAGoVAA==.Tralle:BAAALgAECgMJAwAAAA==.Trapology:BAAALgAECgEJAgAAAA==.Trisky:BAABLgAECn8rAAMgAAkJ1BjvGwAbAgloDAAABwBFAGkMAAAHAD4AawwAAAcAOwBqDAAABwA/AGwMAAAFAFIAbQwAAAEAWQDqDAAABgA/AG4MAAACABQAbwwAAAEAPgAgAAgJjxfvGwAbAghoDAAABgBFAGkMAAAGAD4AawwAAAYAOwBqDAAABgA/AGwMAAAEAFIA6gwAAAYAPwBuDAAAAQAUAG8MAAABAD4AAQAHCTUOTZoANgEHaAwAAAEAJQBpDAAAAQAvAGsMAAABACYAagwAAAEAIgBsDAAAAQAaAG0MAAABABYAbgwAAAEALgAAAA==.Trissa:BAAALgADCgcJEQAAAA==.Trolldax:BAAALgADCgUJBwABLgAECgMJAwALAAAAAA==.Trydént:BAAALgAECgQJBQAAAA==.',
Tu='Tunip:BAAALgAECgIJAgAAAA==.Turtle:BAABLgAECn8dAAMNAAYJzhpaWACPAQZoDAAACABBAGkMAAAGAE4AawwAAAUARgBqDAAAAwBGAGwMAAADADAA6gwAAAQATwANAAYJzhpaWACPAQZoDAAABwBBAGkMAAAGAE4AawwAAAUARgBqDAAAAgAxAGwMAAADADAA6gwAAAQATwAMAAIJmwb9QQAiAAJoDAAAAQAQAGoMAAABAEYAAS4ABRQDCQgAEgBRIAA=.',
Ul='Ulric:BAAALgADCgkJEgAAAA==.',
Un='Unhenged:BAAALgADCgQJBAAAAA==.',
Va='Vaceriss:BAAALgADCgYJBgAAAA==.Valatar:BAAALgADCgcJCgAAAA==.Valdrakkquin:BAABLgAECn8sAAIiAAkJCyEBBgBzAgloDAAACQBcAGkMAAAGAFsAawwAAAYAVABqDAAABABZAGwMAAADAE8AbQwAAAIAVQDqDAAACABTAG4MAAAEAFIAbwwAAAIATAAiAAkJCyEBBgBzAgloDAAACQBcAGkMAAAGAFsAawwAAAYAVABqDAAABABZAGwMAAADAE8AbQwAAAIAVQDqDAAACABTAG4MAAAEAFIAbwwAAAIATAAAAA==.Valtreya:BAAALgADCgYJBgAAAA==.',
Ve='Vegito:BAABLgAECn8zAAIhAAgJfAVRTAAOAQhoDAAACgARAGkMAAAJABEAawwAAAgADQBqDAAACAASAGwMAAAGAAwAbQwAAAEADgDqDAAABwANAG4MAAACAAgAIQAICXwFUUwADgEIaAwAAAoAEQBpDAAACQARAGsMAAAIAA0AagwAAAgAEgBsDAAABgAMAG0MAAABAA4A6gwAAAcADQBuDAAAAgAIAAAA.Veramoon:BAAALgADCgYJBgAAAA==.',
Vi='Victoriia:BAAALgADCggJCAAAAA==.Vincente:BAAALgAECgIJAgAAAA==.Vistus:BAAALgAECgcJCwAAAA==.',
Vo='Void:BAAALgADCgQJBAABLgAECgkJNwAdAFUWAA==.Voidmeister:BAABLgAECn8WAAIFAAYJ+RLVkwDsAAZoDAAABAAiAGkMAAAFADQAawwAAAUALwBqDAAAAgANAGwMAAACACIA6gwAAAQASQAFAAYJ+RLVkwDsAAZoDAAABAAiAGkMAAAFADQAawwAAAUALwBqDAAAAgANAGwMAAACACIA6gwAAAQASQABLgAECggJKgAOALchAA==.Voin:BAABLgAECn9aAAMjAAkJkSTmAQAwAwloDAAADgBjAGkMAAAMAGAAawwAAAsAXQBqDAAACgBbAGwMAAAJAF8AbQwAAAYAXwDqDAAAEABfAG4MAAAKAFgAbwwAAAIAVAAjAAkJkSTmAQAwAwloDAAACwBjAGkMAAAJAGAAawwAAAkAXQBqDAAACgBbAGwMAAAJAF8AbQwAAAYAXwDqDAAACwBfAG4MAAAKAFgAbwwAAAIAVAAhAAQJfRuAUQD8AARoDAAAAwBEAGkMAAADAEsAawwAAAIAUgDqDAAABQA2AAAA.Vorpine:BAABLgAECn8zAAMIAAkJQBdOHgDnAQloDAAABgA+AGkMAAAGAFIAawwAAAYASgBqDAAABgBPAGwMAAAGAFYAbQwAAAUAFgDqDAAACABAAG4MAAAFADQAbwwAAAMAHgAIAAcJkBlOHgDnAQdoDAAABQA+AGkMAAAFAFIAawwAAAUASgBqDAAABQBPAGwMAAADAFYAbQwAAAEAFgDqDAAABABAAAkACQmkDCUgAMABCWgMAAABAAkAaQwAAAEAFgBrDAAAAQAUAGoMAAABAAgAbAwAAAMAOQBtDAAABAAbAOoMAAAEACsAbgwAAAUALgBvDAAAAwA4AAAA.',
Vs='Vs:BAACLgAFFH8HAAIQAAMJ3RJHJQABAQNoDAAAAgArAGkMAAABAAUA6gwAAAQAYAAQAAMJ3RJHJQABAQNoDAAAAgArAGkMAAABAAUA6gwAAAQAYAAuAAQKfxUAAhAACAnYIKhSAPoBABAACAnYIKhSAPoBAAEuAAUUCQk6AAUAJCIA.',
Wa='Wallach:BAAALgAECgUJCgAAAA==.Warcockeh:BAAALgADCgUJBQAAAA==.Watermelon:BAABLgAECn8cAAMkAAgJZxawIwDxAQhoDAAABQA4AGkMAAAEAEMAawwAAAQAQgBqDAAABABfAGwMAAADAEEAbQwAAAIAEADqDAAABAA/AG4MAAACABoAJAAICWcWsCMA8QEIaAwAAAUAOABpDAAABABDAGsMAAAEAEIAagwAAAQAXwBsDAAAAwBBAG0MAAACABAA6gwAAAMAPwBuDAAAAgAaABUAAQkeBiStACEAAeoMAAABAA8AAAA=.',
Wi='Winterberrie:BAAALgADCgYJBAAAAA==.Wirhl:BAABLgAECn8WAAIOAAYJ0RDgiQAgAQZoDAAABAA3AGkMAAAEACcAawwAAAQAHwBqDAAAAwA+AGwMAAACACUA6gwAAAUAMgAOAAYJ0RDgiQAgAQZoDAAABAA3AGkMAAAEACcAawwAAAQAHwBqDAAAAwA+AGwMAAACACUA6gwAAAUAMgAAAA==.',
Wo='Wolfrik:BAAALgAECgUJAwAAAA==.Worthatry:BAABLgAFFH8OAAIBAAQJQyC5IgBqAQRoDAAAAwBTAGkMAAAEAFIAawwAAAMAUADqDAAABABUAAEABAlDILkiAGoBBGgMAAADAFMAaQwAAAQAUgBrDAAAAwBQAOoMAAAEAFQAAAA=.',
Wy='Wyn:BAABLgAECn8jAAIBAAgJRB+oMQAwAghoDAAABgBeAGkMAAAGAFUAawwAAAYAUABqDAAABgBgAGwMAAAEAEwAbQwAAAEATQDqDAAABQBeAG4MAAABADMAAQAICUQfqDEAMAIIaAwAAAYAXgBpDAAABgBVAGsMAAAGAFAAagwAAAYAYABsDAAABABMAG0MAAABAE0A6gwAAAUAXgBuDAAAAQAzAAAA.',
Xa='Xalbit:BAABLgAECn8rAAIKAAkJkhu5EQC2AgloDAAABwA/AGkMAAAGAF4AawwAAAUAQQBqDAAABwBYAGwMAAAGAEYAbQwAAAIAQADqDAAABgBWAG4MAAACADUAbwwAAAIAMQAKAAkJkhu5EQC2AgloDAAABwA/AGkMAAAGAF4AawwAAAUAQQBqDAAABwBYAGwMAAAGAEYAbQwAAAIAQADqDAAABgBWAG4MAAACADUAbwwAAAIAMQAAAA==.Xanae:BAAALgAECggJBgAAAA==.Xanthrash:BAAALgAECgcJEAAAAA==.Xantia:BAABLgAECn85AAIUAAkJJBbmHQBOAgloDAAACABUAGkMAAAIADgAawwAAAgAPgBqDAAABwBSAGwMAAAHAFAAbQwAAAUAIQDqDAAACABCAG4MAAAEABEAbwwAAAIAGgAUAAkJJBbmHQBOAgloDAAACABUAGkMAAAIADgAawwAAAgAPgBqDAAABwBSAGwMAAAHAFAAbQwAAAUAIQDqDAAACABCAG4MAAAEABEAbwwAAAIAGgAAAA==.Xaraena:BAABLgAECn8fAAIOAAkJfRr2KAATAgloDAAABQBcAGkMAAAEAFYAawwAAAQAUQBqDAAAAwA0AGwMAAADAE4AbQwAAAIAOQDqDAAABQBAAG4MAAADACIAbwwAAAIALgAOAAkJfRr2KAATAgloDAAABQBcAGkMAAAEAFYAawwAAAQAUQBqDAAAAwA0AGwMAAADAE4AbQwAAAIAOQDqDAAABQBAAG4MAAADACIAbwwAAAIALgAAAA==.Xaraimarra:BAAALgADCgQJBAAAAA==.Xariz:BAAALgAECgcJEgAAAA==.',
Xe='Xedd:BAAALgAECgQJBgAAAA==.Xenlo:BAAALgAECgcJDwABLgAFFAQJEQAgAKIdAA==.',
Xy='Xyndrä:BAAALgADCgYJBgAAAA==.',
Yu='Yungun:BAAALgAECgEJAQAAAA==.',
Za='Zaizel:BAAALgADCgUJBQABLgAFFAYJGAAlAH8YAA==.Zathennyx:BAAALgADCgYJBgABLgAECgMJAwALAAAAAA==.',
Ze='Zercus:BAABLgAFFH8MAAIBAAQJXQlbTwACAQRoDAAABAAbAGkMAAAEAB4AawwAAAIAEQDqDAAAAgATAAEABAldCVtPAAIBBGgMAAAEABsAaQwAAAQAHgBrDAAAAgARAOoMAAACABMAAAA=.',
Zh='Zhryla:BAAALgADCgUJCQAAAA==.',
Zl='Zleakara:BAAALgADCgQJBAAAAA==.Zleako:BAAALgADCgMJAwAAAA==.',
Zo='Zoel:BAAALgADCgcJCwABLgAECggJMAAZAFYTAA==.',
['Ðr']='Ðread:BAABLgAECn8hAAMWAAgJog7NDwBqAQhoDAAABgA0AGkMAAAFACUAawwAAAQALQBqDAAABQA6AGwMAAAGACsAbQwAAAEADgDqDAAABQAfAG4MAAABACUAFgAICVEOzQ8AagEIaAwAAAEANABpDAAAAQAfAGsMAAABAC0AagwAAAIAOgBsDAAAAQArAG0MAAABAA4A6gwAAAIAHwBuDAAAAQAlABAABgkRDNG7APwABmgMAAAFABgAaQwAAAQAJQBrDAAAAwAjAGoMAAADACQAbAwAAAUAJQDqDAAAAwATAAAA.',
['ßß']='ßßq:BAAALgAECgEJAQAAAA==.ßßqñüt:BAAALgAECgEJAQAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
