local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Mage-Frost','Monk-Brewmaster','Druid-Restoration','DeathKnight-Unholy','Mage-Arcane','Shaman-Restoration','Paladin-Retribution','Warrior-Fury','Warrior-Arms','Warlock-Affliction','Shaman-Enhancement','Priest-Holy','Warlock-Destruction','Warlock-Demonology','DeathKnight-Blood','Unknown-Unknown','Hunter-Survival','Hunter-Marksmanship','DeathKnight-Frost','DemonHunter-Devourer','Paladin-Protection','DemonHunter-Havoc','Shaman-Elemental','DemonHunter-Vengeance','Priest-Discipline','Hunter-BeastMastery','Priest-Shadow','Monk-Windwalker','Monk-Mistweaver','Warrior-Protection','Paladin-Holy','Evoker-Augmentation',}
local provider = {region='US',realm='Smolderthorn',name='US',type='daily',zone=46,date='2026-06-08',data={Ac='Achoo:BAABLgAECn8UAAIBAAcJEAQj1gDlAAdoDAAAAwAGAGkMAAAEAAwAawwAAAQACABqDAAAAgAPAGwMAAACAAgA6gwAAAQAEgBuDAAAAQAHAAEABwkQBCPWAOUAB2gMAAADAAYAaQwAAAQADABrDAAABAAIAGoMAAACAA8AbAwAAAIACADqDAAABAASAG4MAAABAAcAAAA=.Acorn:BAAALgADCgMJBAAAAA==.',
Ai='Aitnd:BAAALgAECgMJAwAAAA==.Aitns:BAAALgADCgUJBQAAAA==.',
Ak='Akabara:BAAALgAECgMJAwAAAA==.',
Al='Alatyr:BAAALgAECgUJBQABLgAECgkJGQACAHEYAA==.Alduinn:BAAALgADCggJEAAAAA==.',
Am='Amilde:BAAALgAECgkJEQABLgAFFAMJCAADAGkSAA==.Amongor:BAABLgAECn8YAAIEAAYJ3h95UAAAAgZoDAAABABUAGkMAAAEAFoAawwAAAQAUABqDAAABABaAGwMAAAEAEcA6gwAAAQAUQAEAAYJ3h95UAAAAgZoDAAABABUAGkMAAAEAFoAawwAAAQAUABqDAAABABaAGwMAAAEAEcA6gwAAAQAUQAAAA==.',
An='Anarisa:BAABLgAECn9XAAMBAAkJfR2nGADAAgloDAAADABTAGkMAAALAFEAawwAAAsARQBqDAAACgBdAGwMAAAJAEUAbQwAAAcAVQDqDAAADABAAG4MAAAJAFQAbwwAAAYAQAABAAkJfR2nGADAAgloDAAACQBTAGkMAAAIAFEAawwAAAgARQBqDAAACABdAGwMAAAJAEUAbQwAAAcAVQDqDAAACgBAAG4MAAAJAFQAbwwAAAYAQAAFAAUJcRGGCwAeAQVoDAAAAwA2AGkMAAADACwAawwAAAMAMwBqDAAAAgAkAOoMAAACABsAAAA=.',
Aq='Aquatide:BAAALgAECgYJBgABLgAFFAcJIAAGAHAdAA==.',
Ar='Artoria:BAAALgADCgkJCwAAAA==.',
At='Athorama:BAAALgAECgUJCwAAAA==.Atra:BAAALgAECgEJAQAAAA==.',
Av='Avelise:BAABLgAECn8UAAIBAAcJkBelaQADAgdoDAAABABPAGkMAAADAEcAawwAAAMAQABqDAAAAwBYAGwMAAADADQAbQwAAAEAGgDqDAAAAwBDAAEABwmQF6VpAAMCB2gMAAAEAE8AaQwAAAMARwBrDAAAAwBAAGoMAAADAFgAbAwAAAMANABtDAAAAQAaAOoMAAADAEMAAS4ABRQDCQgAAwBpEgA=.Averse:BAACLgAFFH8WAAIEAAQJzh+kQABmAQRoDAAABwBeAGkMAAAGAFYAawwAAAQATADqDAAABQBEAAQABAnOH6RAAGYBBGgMAAAHAF4AaQwAAAYAVgBrDAAABABMAOoMAAAFAEQALgAECn81AAIEAAkJNB41FwC2AgAEAAkJNB41FwC2AgAAAA==.',
Az='Azazygos:BAAALgAECgMJAwAAAA==.',
Ba='Baeloth:BAAALgADCgcJDAAAAA==.Barkknight:BAEALgAECgkJBQABLgAFFAQJDwAHAO8PAA==.Barley:BAAALgAECgUJBQAAAA==.Bauce:BAAALgAECgYJBgAAAA==.',
Be='Bearretheon:BAAALgADCgEJAQAAAA==.Benchtally:BAAALgAECgYJDAAAAA==.Bepizo:BAACLgAFFH8LAAMIAAQJrx0GKAAGAQRoDAAAAwBhAGkMAAADAF8AawwAAAIAJADqDAAAAwBKAAgAAwkfGgYoAAYBA2gMAAADAGEAawwAAAEAHQDqDAAAAwBKAAkAAgnZGT8pALEAAmkMAAADAF8AawwAAAEAJAAuAAQKf0YAAwkACQndJNMJAEcCAAkABgnSItMJAEcCAAgABwmzItUpABICAAAA.',
Bl='Bluetide:BAACLgAFFH8gAAIGAAcJcB3hBQBNAgdoDAAABwBdAGkMAAAHAEQAawwAAAUAQABqDAAAAwBaAGwMAAABADkAbQwAAAEAPgDqDAAACABbAAYABwlwHeEFAE0CB2gMAAAHAF0AaQwAAAcARABrDAAABQBAAGoMAAADAFoAbAwAAAEAOQBtDAAAAQA+AOoMAAAIAFsALgAECn8pAAIGAAkJjiZwAADjAwAGAAkJjiZwAADjAwAAAA==.',
Br='Brokemav:BAABLgAECn8vAAIKAAcJESGWAgCTAgdoDAAACABaAGkMAAAIAFsAawwAAAgAXwBqDAAABwBhAGwMAAAGAFAAbQwAAAMAPgDqDAAABwBWAAoABwkRIZYCAJMCB2gMAAAIAFoAaQwAAAgAWwBrDAAACABfAGoMAAAHAGEAbAwAAAYAUABtDAAAAwA+AOoMAAAHAFYAAAA=.Brooklin:BAABLgAECn8yAAIBAAkJnh7dKwDDAgloDAAABwBfAGkMAAAHAFgAawwAAAUAVABqDAAABgBFAGwMAAAGAFIAbQwAAAUAWgDqDAAABwBPAG4MAAAFAC8AbwwAAAIAOwABAAkJnh7dKwDDAgloDAAABwBfAGkMAAAHAFgAawwAAAUAVABqDAAABgBFAGwMAAAGAFIAbQwAAAUAWgDqDAAABwBPAG4MAAAFAC8AbwwAAAIAOwAAAA==.',
Bu='Busky:BAABLgAECn8lAAMGAAkJAhVaKwDfAQloDAAABgAoAGkMAAAGAD4AawwAAAYAQABqDAAABQBJAGwMAAAEACgAbQwAAAIANQDqDAAABQA7AG4MAAACAEIAbwwAAAEAFwAGAAkJAhVaKwDfAQloDAAABQAoAGkMAAAFAD4AawwAAAUAQABqDAAABABJAGwMAAADACgAbQwAAAIANQDqDAAABAA7AG4MAAABAEIAbwwAAAEAFwALAAcJkhEwFgBSAQdoDAAAAQApAGkMAAABADEAawwAAAEANwBqDAAAAQAmAGwMAAABAB4A6gwAAAEAKgBuDAAAAQAyAAAA.',
Ca='Carboncredit:BAABLgAECn8iAAILAAkJrRAICgAyAgloDAAABQApAGkMAAAEADUAawwAAAQAPgBqDAAABAA4AGwMAAAEADAAbQwAAAQAHQDqDAAABAAuAG4MAAAEACoAbwwAAAEADwALAAkJrRAICgAyAgloDAAABQApAGkMAAAEADUAawwAAAQAPgBqDAAABAA4AGwMAAAEADAAbQwAAAQAHQDqDAAABAAuAG4MAAAEACoAbwwAAAEADwAAAA==.Cassiopea:BAABLgAECn8ZAAIMAAgJ7hpqFwAJAghoDAAABQBDAGkMAAAFAF0AawwAAAMAPwBqDAAAAgA4AGwMAAACAFsAbQwAAAEAOgDqDAAABgBWAG4MAAABACEADAAICe4aahcACQIIaAwAAAUAQwBpDAAABQBdAGsMAAADAD8AagwAAAIAOABsDAAAAgBbAG0MAAABADoA6gwAAAYAVgBuDAAAAQAhAAAA.Caysia:BAABLgAFFH8IAAIDAAMJaRIwPQC3AANoDAAAAwAwAGkMAAACACoA6gwAAAMAMgADAAMJaRIwPQC3AANoDAAAAwAwAGkMAAACACoA6gwAAAMAMgAAAA==.',
Ce='Cellcept:BAABLgAECn8XAAINAAUJGh5VDQBcAQVoDAAABABOAGkMAAAEAEwAawwAAAQASwBqDAAABQA2AOoMAAAGAE0ADQAFCRoeVQ0AXAEFaAwAAAQATgBpDAAABABMAGsMAAAEAEsAagwAAAUANgDqDAAABgBNAAAA.',
Ch='Chareth:BAABLgAECn8oAAIBAAkJNgoIawChAQloDAAABwAkAGkMAAAGACAAawwAAAYAIABqDAAAAwAaAGwMAAAEABYAbQwAAAMAEgDqDAAABQAaAG4MAAAFABMAbwwAAAEAFQABAAkJNgoIawChAQloDAAABwAkAGkMAAAGACAAawwAAAYAIABqDAAAAwAaAGwMAAAEABYAbQwAAAMAEgDqDAAABQAaAG4MAAAFABMAbwwAAAEAFQAAAA==.Charlee:BAAALgADCgcJBwAAAA==.Chaunticleer:BAAALgAECgcJCwAAAA==.Chesumadre:BAAALgADCgEJAgAAAA==.Chinchillada:BAABLgAECn8fAAIBAAcJARb8ZwCoAQdoDAAABQBLAGkMAAAGADEAawwAAAcAKgBqDAAABQBGAGwMAAAFAEcAbQwAAAEAIADqDAAAAgBBAAEABwkBFvxnAKgBB2gMAAAFAEsAaQwAAAYAMQBrDAAABwAqAGoMAAAFAEYAbAwAAAUARwBtDAAAAQAgAOoMAAACAEEAAAA=.',
Ci='Cinderfal:BAAALgAECgEJAgAAAA==.',
Cl='Claggor:BAAALgAECgMJAwAAAA==.',
Co='Coldbrewed:BAAALgAECgYJBgAAAA==.Cowladin:BAAALgADCgYJBgABLgAECggJFwAOALYeAA==.',
Cr='Crossover:BAAALgADCgYJBgAAAA==.',
['Cà']='Càss:BAAALgAECgQJBQABLgAECggJGQAMAO4aAA==.',
Da='Dabajabaza:BAABLgAECn80AAIPAAkJ1Qp/IQA/AQloDAAABgAaAGkMAAAHADkAawwAAAcAGwBqDAAABwAcAGwMAAAIAAwAbQwAAAEABQDqDAAACgAqAG4MAAAEACgAbwwAAAIACQAPAAkJ1Qp/IQA/AQloDAAABgAaAGkMAAAHADkAawwAAAcAGwBqDAAABwAcAGwMAAAIAAwAbQwAAAEABQDqDAAACgAqAG4MAAAEACgAbwwAAAIACQAAAA==.Dabergerak:BAACLgAFFH8JAAIIAAMJXCH4KQD8AANoDAAABABYAGkMAAADAFAA6gwAAAIAVgAIAAMJXCH4KQD8AANoDAAABABYAGkMAAADAFAA6gwAAAIAVgAuAAQKfysAAggACQmcJfkCADwDAAgACQmcJfkCADwDAAAA.Daenys:BAAALgAECgMJAwABLgAFFAgJLAAKAA0bAA==.Daggart:BAAALgAECgkJDgAAAA==.Dagrimreaper:BAAALgADCgcJBgABLgAECgcJEAAQAAAAAA==.Dakrus:BAACLgAFFH8FAAIRAAMJmg1KHwDNAANoDAAAAwAtAGkMAAABAB4A6gwAAAEAHAARAAMJmg1KHwDNAANoDAAAAwAtAGkMAAABAB4A6gwAAAEAHAAuAAQKfyUAAxIACQkwGVIgACMCABIACAmpFlIgACMCABEABgk9Dj4rAEYBAAAA.Darthßsaber:BAAALgADCgUJBQAAAA==.Dax:BAAALgADCgYJBgAAAA==.',
De='Deadazz:BAABLgAECn8aAAMTAAcJCQ06FAAxAQdoDAAABgAjAGkMAAAEABwAawwAAAQAJABqDAAABQAYAGwMAAAEACoAbQwAAAEAJADqDAAAAgATABMABwkJDToUADEBB2gMAAABACMAaQwAAAEAHABrDAAAAQAkAGoMAAABAA8AbAwAAAEAKgBtDAAAAQAkAOoMAAABABMADwAGCQoEWEAAhgAGaAwAAAUABwBpDAAAAwAPAGsMAAADABMAagwAAAQAGABsDAAAAwAEAOoMAAABAAQAAS4ABRQFCQoADgCyDwA=.Deadputz:BAAALgAECggJEwABLgAFFAMJBwAUAFYaAA==.Deeiinnduh:BAAALgAECgYJBgAAAA==.Dein:BAAALgAECgcJEQAAAA==.Dejanira:BAABLgAECn8gAAIDAAkJzhGUPgCRAQloDAAABAAwAGkMAAAEAC8AawwAAAQAUwBqDAAAAwA6AGwMAAAEADMAbQwAAAMAKgDqDAAABgAtAG4MAAADABgAbwwAAAEACAADAAkJzhGUPgCRAQloDAAABAAwAGkMAAAEAC8AawwAAAQAUwBqDAAAAwA6AGwMAAAEADMAbQwAAAMAKgDqDAAABgAtAG4MAAADABgAbwwAAAEACAAAAA==.Demonslayerr:BAAALgADCgQJBAAAAA==.Demotope:BAAALgADCgcJDAABLgAECgYJDAAQAAAAAA==.',
Di='Diddily:BAABLgAECn8VAAMVAAgJWxUTHwAQAQhoDAAAAgAZAGkMAAACADgAawwAAAIAKgBqDAAAAgAUAGwMAAAGAEwAbQwAAAIASQDqDAAABAA0AG4MAAABADcAFQAICVsVEx8AEAEIaAwAAAIAGQBpDAAAAgA4AGsMAAACACoAagwAAAEAFABsDAAABgBMAG0MAAACAEkA6gwAAAIANABuDAAAAQA3AAcAAgntA7KxASIAAmoMAAABABAA6gwAAAIACgAAAA==.Diesverdi:BAAALgAECgMJAwAAAA==.Dirtylilskin:BAAALgADCgkJHQAAAA==.',
Do='Dookie:BAAALgAECgQJBAAAAA==.',
Dr='Draconae:BAABLgAECn8bAAIWAAYJWQdAOwC8AAZoDAAACgAVAGkMAAAFABoAawwAAAMAEgBqDAAAAgARAGwMAAACAAsA6gwAAAUADwAWAAYJWQdAOwC8AAZoDAAACgAVAGkMAAAFABoAawwAAAMAEgBqDAAAAgARAGwMAAACAAsA6gwAAAUADwAAAA==.Dracotope:BAAALgAECgYJDAAAAA==.Dragonjoy:BAABLgAECn8kAAIPAAkJORaXFQC3AQloDAAABgBCAGkMAAAFAEsAawwAAAUAPgBqDAAABAAuAGwMAAAEADUAbQwAAAMAIQDqDAAABAA1AG4MAAAEAFEAbwwAAAEAHAAPAAkJORaXFQC3AQloDAAABgBCAGkMAAAFAEsAawwAAAUAPgBqDAAABAAuAGwMAAAEADUAbQwAAAMAIQDqDAAABAA1AG4MAAAEAFEAbwwAAAEAHAAAAA==.Drathier:BAAALgAECgIJAgAAAA==.Dridarok:BAABLgAECn8gAAIIAAkJqQyLKwCiAQloDAAABQAsAGkMAAAFABsAawwAAAUAKABqDAAABAATAGwMAAAEABwAbQwAAAIAIADqDAAABAAqAG4MAAACABgAbwwAAAEAFAAIAAkJqQyLKwCiAQloDAAABQAsAGkMAAAFABsAawwAAAUAKABqDAAABAATAGwMAAAEABwAbQwAAAIAIADqDAAABAAqAG4MAAACABgAbwwAAAEAFAAAAA==.',
['Dâ']='Dâwn:BAAALgAECggJDwAAAA==.',
Ei='Eighttyhd:BAAALgADCgQJBAAAAA==.Eightyhd:BAAALgADCgIJAgAAAA==.Eirny:BAAALgAECgMJBAAAAA==.',
El='Element:BAAALgADCgEJAQABLgAFFAQJCwAIAK8dAA==.Elise:BAABLgAECn8kAAMNAAkJQhckCQAvAgloDAAABQBXAGkMAAAFAEUAawwAAAUAPgBqDAAABAAkAGwMAAAEAEwAbQwAAAIAEADqDAAABgBMAG4MAAAEACUAbwwAAAEAMQANAAgJzBckCQAvAghoDAAAAwBXAGkMAAADAEUAawwAAAMAPgBqDAAAAwAkAGwMAAADAEwAbQwAAAIAEADqDAAAAwBMAG4MAAACACUACgAICQER+A4AQQEIaAwAAAIANgBpDAAAAgAXAGsMAAACADcAagwAAAEABgBsDAAAAQAUAOoMAAADAD8AbgwAAAIAJABvDAAAAQAxAAAA.Elstrid:BAABLgAECn8XAAIOAAgJth43PAAcAghoDAAAAwBUAGkMAAAEAFMAawwAAAMATABqDAAAAwBVAGwMAAADAFEAbQwAAAIAOgDqDAAAAwBYAG4MAAACAE4ADgAICbYeNzwAHAIIaAwAAAMAVABpDAAABABTAGsMAAADAEwAagwAAAMAVQBsDAAAAwBRAG0MAAACADoA6gwAAAMAWABuDAAAAgBOAAAA.',
Er='Erzaflame:BAAALgADCgEJAQAAAA==.',
Eu='Euphoria:BAAALgAECgMJAwABLgAECgkJNAAXACMlAA==.',
Ev='Evochre:BAAALgAECgUJCQAAAA==.',
Fa='Faerine:BAAALgADCgcJBwAAAA==.Fantasy:BAABLgAECn80AAIXAAkJIyXqAgA+AwloDAAABwBiAGkMAAAHAGMAawwAAAcAYwBqDAAABgBjAGwMAAAHAGIAbQwAAAQAYQDqDAAACQBiAG4MAAAEAFEAbwwAAAEAVgAXAAkJIyXqAgA+AwloDAAABwBiAGkMAAAHAGMAawwAAAcAYwBqDAAABgBjAGwMAAAHAGIAbQwAAAQAYQDqDAAACQBiAG4MAAAEAFEAbwwAAAEAVgAAAA==.',
Fe='Felbourn:BAACLgAFFH8IAAIWAAMJvxm1FADtAANoDAAABABPAGkMAAADAE0A6gwAAAEAKQAWAAMJvxm1FADtAANoDAAABABPAGkMAAADAE0A6gwAAAEAKQAuAAQKfyAABBYACQlkIY4IANkCABYACAmJIY4IANkCABgAAgktFpEgAI0AABQAAgm7CW/MAF0AAAAA.Fendraim:BAAALgAECgYJCwABLgAECgcJEQAQAAAAAA==.',
Fi='Figurefour:BAAALgAECgkJDwAAAA==.',
Fo='Foedris:BAAALgADCgUJBQAAAA==.Foxfire:BAAALgAECgQJCAAAAA==.',
Fr='Frailboosy:BAACLgAFFH8OAAIHAAQJ0RZ7OwApAQRoDAAABQAqAGkMAAAEAE8AawwAAAEAMwDqDAAABAA8AAcABAnRFns7ACkBBGgMAAAFACoAaQwAAAQATwBrDAAAAQAzAOoMAAAEADwALgAECn9bAAIHAAkJGCLwCgAIAwAHAAkJGCLwCgAIAwAAAA==.Fri:BAAALgADCgkJCQAAAA==.Frigamortis:BAAALgAECgYJDQAAAA==.',
Ge='Gemini:BAAALgAECgQJBAAAAA==.',
Gi='Gilferno:BAAALgAECgQJBAAAAA==.',
Gl='Glitz:BAABLgAFFH8FAAIBAAUJawStcQD0AAVoDAAAAQAPAGkMAAABAA8AawwAAAEABABqDAAAAQANAOoMAAABAAkAAQAFCWsErXEA9AAFaAwAAAEADwBpDAAAAQAPAGsMAAABAAQAagwAAAEADQDqDAAAAQAJAAEuAAUUBgkRABkAzAYA.',
Gn='Gnarfok:BAAALgAECgQJDwAAAA==.',
Go='Goopster:BAAALgADCgcJCQAAAA==.',
Gr='Graamps:BAAALgAECgYJDQAAAA==.Gravedigger:BAACLgAFFH8NAAMPAAQJQBrQFQArAQRoDAAABQA2AGkMAAACAEgAawwAAAEAPADqDAAABQBSAA8ABAlAGtAVACsBBGgMAAAFADYAaQwAAAIASABrDAAAAQA8AOoMAAAEAFIAEwABCWQASykAKAAB6gwAAAEAAAAuAAQKfzQAAg8ACQncH1sJAHcCAA8ACQncH1sJAHcCAAAA.',
Gu='Gunde:BAAALgAECgkJBQAAAA==.Gust:BAAALgAECgQJDwAAAA==.',
Ha='Hatredx:BAAALgADCgIJAgAAAA==.',
He='Heisenberg:BAAALgAECgQJCAABLgAFFAQJCwAaAHsRAA==.',
Ho='Holywagyu:BAAALgAECgYJBgAAAA==.',
Hy='Hyllinia:BAAALgADCgEJAQAAAA==.Hyõrinmaru:BAAALgAECgMJAwAAAA==.',
Ih='Iheal:BAAALgAECgEJAQAAAA==.',
In='Inarios:BAABLgAECn8qAAQZAAkJhxu+DACZAgloDAAABgBbAGkMAAAGAGEAawwAAAcAVABqDAAABQBVAGwMAAAHAFQAbQwAAAEAOQDqDAAABwBIAG4MAAACACgAbwwAAAEAFAAZAAgJ/h2+DACZAghoDAAABgBbAGkMAAAGAGEAawwAAAcAVABqDAAABQBVAGwMAAAFAFQAbQwAAAEAOQDqDAAABABIAG4MAAABACgAGwAECZYVgDwAGgEEbAwAAAIATgDqDAAAAgBAAG4MAAABABwAbwwAAAEAMQAMAAEJtwyFcQAkAAHqDAAAAQAgAAAA.Inshape:BAAALgAECgYJEwAAAA==.',
Ir='Ironnman:BAAALgAECgEJAQABLgAECgkJGQACAHEYAA==.Ironnmonk:BAABLgAECn8ZAAQCAAkJcRiBGwAnAgloDAAABQBNAGkMAAADAD0AawwAAAMASQBqDAAAAgArAGwMAAADAD4AbQwAAAIAPADqDAAAAwA8AG4MAAADAFYAbwwAAAEAEQACAAkJcRiBGwAnAgloDAAABABNAGkMAAADAD0AawwAAAMASQBqDAAAAgArAGwMAAACAD4AbQwAAAIAPADqDAAAAwA8AG4MAAADAFYAbwwAAAEAEQAcAAEJihFVlQAyAAFsDAAAAQAsAB0AAQlSBDB1ABwAAWgMAAABAAsAAAA=.',
Ja='Javlin:BAAALgAECgYJEAAAAA==.',
Jo='Joltarin:BAAALgAECgEJAQABLgAECggJFwAOALYeAA==.',
Ju='Jujufya:BAAALgAECgIJAgABLgAECgcJEAAQAAAAAA==.Jujukni:BAAALgAECgUJCwABLgAECgcJEAAQAAAAAA==.Jujumon:BAAALgAECgcJEAAAAA==.Jujuzul:BAAALgADCgUJBgABLgAECgcJEAAQAAAAAA==.Justimp:BAACLgAFFH8GAAIOAAMJTQgMgAC5AANoDAAAAwAhAGkMAAACABoA6gwAAAEABAAOAAMJTQgMgAC5AANoDAAAAwAhAGkMAAACABoA6gwAAAEABAAuAAQKfyQAAg4ACQl4FO1AANQBAA4ACQl4FO1AANQBAAAA.',
Ka='Kanon:BAABLgAECn8WAAIeAAkJBxO1EQDFAQloDAAAAgA5AGkMAAADACwAawwAAAMAOgBqDAAAAwAtAGwMAAAFADgAbQwAAAEAKADqDAAAAwA7AG4MAAABACEAbwwAAAEAJgAeAAkJBxO1EQDFAQloDAAAAgA5AGkMAAADACwAawwAAAMAOgBqDAAAAwAtAGwMAAAFADgAbQwAAAEAKADqDAAAAwA7AG4MAAABACEAbwwAAAEAJgAAAA==.Kanook:BAAALgAECgMJAwAAAA==.Karlek:BAABLgAFFH8GAAMfAAMJ2gTZNACSAANoDAAAAgAIAGkMAAACABYA6gwAAAIABQAfAAMJ2gTZNACSAANoDAAAAgAIAGkMAAACABYA6gwAAAEABQAHAAEJ6AE1vwAxAAHqDAAAAQAEAAAA.',
Ki='Kikily:BAAALgADCgkJCQAAAA==.',
Ko='Konsistency:BAABLgAECn8fAAIUAAcJlA6icgBNAQdoDAAABwAzAGkMAAAGACkAawwAAAQALQBqDAAABQAmAGwMAAADACAA6gwAAAUAIABuDAAAAQAUABQABwmUDqJyAE0BB2gMAAAHADMAaQwAAAYAKQBrDAAABAAtAGoMAAAFACYAbAwAAAMAIADqDAAABQAgAG4MAAABABQAAAA=.Konviction:BAABLgAECn8fAAMHAAkJ/RFrgwBfAQloDAAABQA3AGkMAAAFAEEAawwAAAQAQABqDAAAAwATAGwMAAADACEAbQwAAAEAEwDqDAAABwA8AG4MAAACADEAbwwAAAEAEwAHAAkJ/RFrgwBfAQloDAAABQA3AGkMAAAFAEEAawwAAAQAQABqDAAAAwATAGwMAAACACEAbQwAAAEAEwDqDAAABgA8AG4MAAACADEAbwwAAAEAEwAVAAIJZwIhVgAcAAJsDAAAAQAIAOoMAAABAAMAAAA=.',
Kr='Kreel:BAAALgADCggJCAAAAA==.Krogg:BAAALgADCgcJBwAAAA==.',
La='Lalana:BAABLgAECn8gAAIaAAcJUw+mawBiAQdoDAAABQAuAGkMAAAHAC0AawwAAAcAJwBqDAAABQAaAGwMAAAFABQAbQwAAAEANQDqDAAAAgAdABoABwlTD6ZrAGIBB2gMAAAFAC4AaQwAAAcALQBrDAAABwAnAGoMAAAFABoAbAwAAAUAFABtDAAAAQA1AOoMAAACAB0AAAA=.Lan:BAAALgAECgcJBwAAAA==.Landin:BAAALgAECgcJBwAAAA==.',
Li='Liari:BAEBLgAECn8cAAIBAAgJKwoHiwBeAQhoDAAABAARAGkMAAAEAB0AawwAAAQAFABqDAAABAAPAGwMAAADACsAbQwAAAMAFgDqDAAABAAdAG4MAAACABMAAQAICSsKB4sAXgEIaAwAAAQAEQBpDAAABAAdAGsMAAAEABQAagwAAAQADwBsDAAAAwArAG0MAAADABYA6gwAAAQAHQBuDAAAAgATAAEuAAUUBAkPAAcA7w8A.Libra:BAAALgADCgEJAQAAAA==.Lilith:BAACLgAFFH8RAAMZAAYJzAbHCABRAQZoDAAABAAeAGkMAAADABQAawwAAAMADgBqDAAAAwAPAGwMAAABAAQA6gwAAAMAEgAZAAYJzAbHCABRAQZoDAAAAgAeAGkMAAACABQAawwAAAMADgBqDAAAAgAPAGwMAAABAAQA6gwAAAIAEgAbAAQJcwk0JQC9AARoDAAAAgAMAGkMAAABAB0AagwAAAEADQDqDAAAAQAeAC4ABAp/IQADGQAJCakYbhIAIQIAGQAICTQZbhIAIQIAGwAHCZUcRyEAzgEAAAA=.Lithari:BAAALgADCggJCAAAAA==.',
Lo='Lofwyr:BAACLgAFFH8FAAIgAAMJyQGeSwCJAANoDAAAAgADAGkMAAACAAYA6gwAAAEABAAgAAMJyQGeSwCJAANoDAAAAgADAGkMAAACAAYA6gwAAAEABAAuAAQKfy8AAiAACQmzESoeAOABACAACQmzESoeAOABAAAA.Lootadots:BAAALgAECgEJAQABLgAECgYJGAAIAF4UAA==.',
Lu='Lumes:BAAALgAECgUJBQAAAA==.Lumie:BAABLgAECn8mAAMMAAkJAyCgCADCAgloDAAABgBcAGkMAAAGAF0AawwAAAUAVQBqDAAABQBdAGwMAAAEAF0AbQwAAAIAPwDqDAAABgBUAG4MAAADADMAbwwAAAEAUQAMAAkJAyCgCADCAgloDAAABABcAGkMAAAEAF0AawwAAAQAVQBqDAAABABdAGwMAAADAF0AbQwAAAIAPwDqDAAABQBUAG4MAAACADMAbwwAAAEAUQAbAAcJ4BGAMgBKAQdoDAAAAgAwAGkMAAACADkAawwAAAEANABqDAAAAQAjAGwMAAABABoA6gwAAAEAIgBuDAAAAQA2AAEuAAUUAwkHAAMAzA8A.Lumiea:BAAALgAECgYJBgABLgAFFAMJBwADAMwPAA==.Lunar:BAAALgADCgIJAgABLgAFFAYJEQAZAMwGAA==.Lunie:BAACLgAFFH8HAAIDAAMJzA8zPgC0AANoDAAAAgAxAGkMAAABAAgA6gwAAAQAPwADAAMJzA8zPgC0AANoDAAAAgAxAGkMAAABAAgA6gwAAAQAPwAuAAQKfx0AAgMACAnTHoMRAL0CAAMACAnTHoMRAL0CAAAA.',
Ma='Magadeoz:BAABLgAECn8UAAIBAAcJ6QodrQAjAQdoDAAAAwA5AGkMAAAEAAsAawwAAAMAFgBqDAAAAgAgAGwMAAACABgA6gwAAAUAIQBuDAAAAQAQAAEABwnpCh2tACMBB2gMAAADADkAaQwAAAQACwBrDAAAAwAWAGoMAAACACAAbAwAAAIAGADqDAAABQAhAG4MAAABABAAAAA=.Magicshow:BAACLgAFFH8GAAIBAAMJpQc5hQDKAANoDAAAAwANAGkMAAABABIA6gwAAAIAGgABAAMJpQc5hQDKAANoDAAAAwANAGkMAAABABIA6gwAAAIAGgAuAAQKfx0AAgEACAn1EPyUAKoBAAEACAn1EPyUAKoBAAAA.Malachite:BAAALgADCgQJBAABLgAFFAYJEQAZAMwGAA==.Malzahar:BAAALgADCgEJAgAAAA==.',
Mc='Mcdracula:BAAALgAECgcJEgAAAA==.',
Mi='Milfred:BAAALgAFFAEJAQAAAA==.Mistrniceguy:BAAALgAECgEJAQAAAA==.',
Mo='Moarticia:BAAALgAECgYJCwABLgAFFAIJBQAgAFkRAA==.Moonbelle:BAAALgAECgcJDAABLgAFFAYJEQAZAMwGAA==.',
Mu='Murthius:BAAALgAECgYJDwAAAA==.Musky:BAAALgAECgEJAgAAAA==.',
My='Myoushi:BAAALgADCgEJAQAAAA==.',
Na='Naâmah:BAAALgAECgUJBQAAAA==.',
Ne='Necromachine:BAACLgAFFH8LAAIEAAQJOQvEcgATAQRoDAAABAAnAGkMAAACABcAawwAAAEACgDqDAAABAApAAQABAk5C8RyABMBBGgMAAAEACcAaQwAAAIAFwBrDAAAAQAKAOoMAAAEACkALgAECn8cAAMEAAkJmBc0dgBxAQAEAAkJmBc0dgBxAQAPAAIJVwZ/PgBWAAAAAA==.Neiry:BAAALgADCgcJBwAAAA==.Neon:BAAALgAECgYJCwABLgAECgkJNAAXACMlAA==.',
No='Noctislucis:BAACLgAFFH8FAAIUAAQJnAGvcwCKAARoDAAAAgAHAGkMAAABAAAAawwAAAEABQDqDAAAAQACABQABAmcAa9zAIoABGgMAAACAAcAaQwAAAEAAABrDAAAAQAFAOoMAAABAAIALgAECn8gAAQYAAkJ/gr2GADMAAAUAAcJpAlklgDpAAAYAAcJBgr2GADMAAAWAAEJcgB5fgACAAAAAA==.Noj:BAAALgADCgUJBQAAAA==.Noobdk:BAABLgAFFH8GAAIPAAIJVCW1MABoAAJqDAAAAwAyAOoMAAADAF8ADwACCVQltTAAaAACagwAAAMAMgDqDAAAAwBfAAEuAAUUBgkaAAIA8yIA.Noobmonkey:BAACLgAFFH8aAAICAAYJ8yLCAwBRAgZoDAAABwBiAGkMAAAHAGIAawwAAAUAYQBsDAAAAQBFAG0MAAABAE8A6gwAAAUAXAACAAYJ8yLCAwBRAgZoDAAABwBiAGkMAAAHAGIAawwAAAUAYQBsDAAAAQBFAG0MAAABAE8A6gwAAAUAXAAuAAQKfzMAAgIACQn4JQQBAGQDAAIACQn4JQQBAGQDAAAA.Noobwarr:BAAALgAECgYJBgABLgAFFAYJGgACAPMiAA==.Novax:BAAALgAECgMJAwAAAA==.',
Nu='Numeral:BAABLgAFFH8GAAMMAAIJtw32DQCOAAJoDAAAAwApAOoMAAADABwADAACCbcN9g0AjgACaAwAAAIAKQDqDAAAAQAcABsAAgmwEQQsAIkAAmgMAAABADwA6gwAAAIAHgAAAA==.',
Ol='Olegregg:BAAALgADCgUJCAAAAA==.',
On='Onzynn:BAAALgADCgcJCAAAAA==.',
Pa='Paracelsus:BAAALgAECgYJCwAAAA==.',
Pe='Pepka:BAAALgAECgYJCwAAAA==.',
Ph='Phillcollins:BAABLgAECn8jAAMGAAYJfhtxNwDHAQZoDAAABgAWAGkMAAAHAGEAawwAAAYAVABqDAAABABiAGwMAAAGADAA6gwAAAYARgAGAAYJfhtxNwDHAQZoDAAABQAWAGkMAAAGAGEAawwAAAUAVABqDAAAAwBiAGwMAAAEADAA6gwAAAUARgAXAAYJphKkQwAZAQZoDAAAAQApAGkMAAABACoAawwAAAEAMwBqDAAAAQAtAGwMAAACACcA6gwAAAEAPwABLgAECgcJFwAgAEwUAA==.',
Pi='Pinktide:BAAALgAECgYJDAABLgAFFAcJIAAGAHAdAA==.',
Po='Pouka:BAAALgAECggJCAABLgAECgkJNAAOALslAA==.Power:BAAALgADCgcJBwAAAA==.',
Pr='Prettypoison:BAABLgAECn8vAAIaAAgJrxh7NgD7AQhoDAAACABLAGkMAAAHAFEAawwAAAkATABqDAAABgBRAGwMAAAIAD0AbQwAAAIALQDqDAAABgAuAG4MAAABADYAGgAICa8YezYA+wEIaAwAAAgASwBpDAAABwBRAGsMAAAJAEwAagwAAAYAUQBsDAAACAA9AG0MAAACAC0A6gwAAAYALgBuDAAAAQA2AAAA.',
Pu='Putz:BAACLgAFFH8HAAIUAAMJVhqbSwD+AANoDAAABABhAGkMAAABACMA6gwAAAIARQAUAAMJVhqbSwD+AANoDAAABABhAGkMAAABACMA6gwAAAIARQAuAAQKf0gAAxQACQmcI7AGABoDABQACQmcI7AGABoDABgAAQnqERcyADIAAAAA.',
Ra='Raditz:BAAALgADCgYJBgABLgAFFAcJIAAGAHAdAA==.Rainbow:BAABLgAECn8vAAIdAAkJWx8xCQD7AgloDAAABQBSAGkMAAAGAFkAawwAAAYASwBqDAAABwBQAGwMAAAHAFgAbQwAAAEANADqDAAACQBZAG4MAAAEAFMAbwwAAAIAUAAdAAkJWx8xCQD7AgloDAAABQBSAGkMAAAGAFkAawwAAAYASwBqDAAABwBQAGwMAAAHAFgAbQwAAAEANADqDAAACQBZAG4MAAAEAFMAbwwAAAIAUAABLgAECgkJNAAXACMlAA==.Rastasham:BAAALgAECggJDgAAAA==.Ratfondler:BAACLgAFFH8IAAMcAAMJah5AFwAHAQNoDAAAAwBJAGkMAAACAFMA6gwAAAMASwAcAAMJah5AFwAHAQNoDAAAAgBJAGkMAAACAFMA6gwAAAMASwAdAAEJcwaxXQAuAAFoDAAAAQAQAC4ABAp/LAADHAAJCUwjVAMAKAMAHAAJCUwjVAMAKAMAHQAECVIPbmgAxgAAAAA=.',
Re='Reialaleigh:BAAALgAECgUJCAAAAA==.',
Ri='Ricanthetank:BAAALgAECgQJBAAAAA==.',
Ry='Rysho:BAAALgAECgEJAQAAAA==.',
Sa='Sabeam:BAACLgAFFH8VAAIUAAUJTBefCQCQAQVoDAAABwBEAGkMAAADAC4AawwAAAMANABqDAAAAgAPAOoMAAAGAEYAFAAFCUwXnwkAkAEFaAwAAAcARABpDAAAAwAuAGsMAAADADQAagwAAAIADwDqDAAABgBGAC4ABAp/MAACFAAJCfAfzgcATQMAFAAJCfAfzgcATQMAAAA=.Saberdiva:BAABLgAECn8xAAIHAAgJdhGtjQBNAQhoDAAABwA6AGkMAAAHACUAawwAAAQAIQBqDAAABgA6AGwMAAAGADgAbQwAAAMAGADqDAAACwA5AG4MAAAFACwABwAICXYRrY0ATQEIaAwAAAcAOgBpDAAABwAlAGsMAAAEACEAagwAAAYAOgBsDAAABgA4AG0MAAADABgA6gwAAAsAOQBuDAAABQAsAAAA.Sabersidious:BAAALgADCgUJBQAAAA==.Saberthyr:BAAALgADCgkJEQAAAA==.Saberwookie:BAAALgADCgUJBQAAAA==.Sabs:BAAALgAFFAIJAgABLgAFFAUJFQAUAEwXAA==.Sagesteppe:BAAALgAECgYJEQAAAA==.Santhon:BAAALgAECgEJAwAAAA==.',
Sc='Scotticus:BAABLgAECn8jAAIEAAgJKg+GigBJAQhoDAAACAAvAGkMAAAIADcAawwAAAYAMwBqDAAABABGAGwMAAADAD0AbQwAAAEACQDqDAAABAAjAG4MAAABAAsABAAICSoPhooASQEIaAwAAAgALwBpDAAACAA3AGsMAAAGADMAagwAAAQARgBsDAAAAwA9AG0MAAABAAkA6gwAAAQAIwBuDAAAAQALAAAA.',
Se='Seditionist:BAABLgAECn8eAAIXAAcJXgXYWwDFAAdoDAAABgAJAGkMAAAGAA4AawwAAAUACQBqDAAABAAQAGwMAAAGACMAbQwAAAEACQDqDAAAAgAEABcABwleBdhbAMUAB2gMAAAGAAkAaQwAAAYADgBrDAAABQAJAGoMAAAEABAAbAwAAAYAIwBtDAAAAQAJAOoMAAACAAQAAAA=.Sellis:BAAALgADCgEJAQAAAA==.',
Sh='Shakira:BAAALgADCgkJCQABLgAECgUJCAAQAAAAAA==.Shammywow:BAAALgADCgEJAQAAAA==.Shamon:BAAALgAECgkJBQAAAA==.Shinju:BAAALgAECgEJAQAAAA==.Shåtheed:BAAALgADCgYJBgAAAA==.',
Si='Sidthekid:BAAALgAECgYJDgAAAA==.Sinayion:BAABLgAECn8hAAIVAAgJdgQtKQDFAAhoDAAABQASAGkMAAAFAA8AawwAAAUADwBqDAAAAwAEAGwMAAAHAAsAbQwAAAIABADqDAAABQAGAG4MAAABAAgAFQAICXYELSkAxQAIaAwAAAUAEgBpDAAABQAPAGsMAAAFAA8AagwAAAMABABsDAAABwALAG0MAAACAAQA6gwAAAUABgBuDAAAAQAIAAAA.',
Sl='Sluggina:BAAALgAECgIJAwAAAA==.',
St='Stepdemonh:BAAALgADCgkJEwAAAA==.Stepsis:BAAALgAFFAEJAQABLgAECggJGQAMAO4aAA==.Stinkoman:BAAALgAECgQJBwABLgAECgQJCAAQAAAAAA==.',
Su='Sunarena:BAABLgAECn8fAAIHAAkJJg9VhQBcAQloDAAABQApAGkMAAAEACUAawwAAAQAFwBqDAAAAwAaAGwMAAAEAEEAbQwAAAEADwDqDAAAAwAcAG4MAAAFADQAbwwAAAIALgAHAAkJJg9VhQBcAQloDAAABQApAGkMAAAEACUAawwAAAQAFwBqDAAAAwAaAGwMAAAEAEEAbQwAAAEADwDqDAAAAwAcAG4MAAAFADQAbwwAAAIALgAAAA==.',
Ta='Tankobell:BAABLgAECn8bAAIHAAkJBhE4VgDAAQloDAAAAwAyAGkMAAADACgAawwAAAQAKQBqDAAABABKAGwMAAADADEAbQwAAAEAMADqDAAABQApAG4MAAADACsAbwwAAAEAIQAHAAkJBhE4VgDAAQloDAAAAwAyAGkMAAADACgAawwAAAQAKQBqDAAABABKAGwMAAADADEAbQwAAAEAMADqDAAABQApAG4MAAADACsAbwwAAAEAIQAAAA==.Tavius:BAAALgADCgEJAQAAAA==.',
Te='Terrible:BAEALgAECgcJAgABLgAFFAYJGgAIAIEeAA==.',
Th='Thannatos:BAAALgAECgEJAQAAAA==.Thejuiciest:BAAALgADCgEJAgAAAA==.',
To='Tommet:BAAALgADCgUJBQAAAA==.Toukadh:BAAALgAECgYJAgAAAA==.',
Tr='Truart:BAAALgAECgQJCQAAAA==.',
Tu='Tuerjoie:BAABLgAECn8mAAIBAAgJQhiYTQDuAQhoDAAABwBWAGkMAAAFADEAawwAAAUANwBqDAAABQBMAGwMAAAHAEkAbQwAAAEAMQDqDAAABwBRAG4MAAABACUAAQAICUIYmE0A7gEIaAwAAAcAVgBpDAAABQAxAGsMAAAFADcAagwAAAUATABsDAAABwBJAG0MAAABADEA6gwAAAcAUQBuDAAAAQAlAAAA.',
Tw='Twíla:BAAALgADCgYJCwAAAA==.',
Ty='Tywin:BAAALgAECgMJAwAAAA==.',
Ug='Ugooboom:BAAALgAECgEJAQAAAA==.',
Uh='Uh:BAAALgADCgYJDAAAAA==.',
Un='Unclemagic:BAAALgADCgQJBAABLgAFFAUJCgAOALIPAA==.',
Ut='Utopia:BAAALgAECgQJAwAAAA==.',
Va='Valesko:BAAALgAFFAEJAQAAAA==.Varfus:BAACLgAFFH8gAAIYAAcJwSJ5AABUAgdoDAAABwBgAGkMAAAHAGMAawwAAAUAWwBqDAAAAwBPAGwMAAABAGAAbQwAAAEANQDqDAAACABhABgABwnBInkAAFQCB2gMAAAHAGAAaQwAAAcAYwBrDAAABQBbAGoMAAADAE8AbAwAAAEAYABtDAAAAQA1AOoMAAAIAGEALgAECn8zAAIYAAkJSiZjAABeAwAYAAkJSiZjAABeAwAAAA==.',
Ve='Velentre:BAAALgAECgYJCAAAAA==.',
Vi='Vichy:BAAALgAECgYJCQAAAA==.Vikstyn:BAAALgAECgEJBAAAAA==.',
Vu='Vulquin:BAAALgAECgUJBQAAAA==.',
We='Weather:BAAALgAECgYJCAAAAA==.',
Wi='Wigskid:BAAALgADCgEJAQAAAA==.Winney:BAABLgAECn8jAAIHAAkJniQxBgA7AwloDAAABABbAGkMAAAFAF8AawwAAAYAYQBqDAAABABhAGwMAAAFAFcAbQwAAAQAYADqDAAABQBjAG4MAAABAFQAbwwAAAEAYQAHAAkJniQxBgA7AwloDAAABABbAGkMAAAFAF8AawwAAAYAYQBqDAAABABhAGwMAAAFAFcAbQwAAAQAYADqDAAABQBjAG4MAAABAFQAbwwAAAEAYQAAAA==.',
Wo='Wolfjob:BAAALgADCgUJBQAAAA==.Wouka:BAABLgAECn80AAQOAAkJuyWRAwBVAwloDAAABgBiAGkMAAAGAGIAawwAAAcAYgBqDAAABwBhAGwMAAAHAGMAbQwAAAYAYADqDAAABQBhAG4MAAAGAF8AbwwAAAIAWQAOAAkJqSWRAwBVAwloDAAABQBiAGkMAAAEAGAAawwAAAYAYgBqDAAAAwAyAGwMAAAGAGMAbQwAAAUAYADqDAAABABhAG4MAAAGAF8AbwwAAAIAWQAKAAYJqiPVAwBQAgZoDAAAAQBZAGkMAAACAGIAawwAAAEAXQBqDAAAAwBhAGwMAAABAFkA6gwAAAEAVQANAAIJsiOvKQBoAAJqDAAAAQBaAG0MAAABAFsAAAA=.',
Wu='Wukong:BAAALgADCgMJAwAAAA==.',
Ya='Yarlyah:BAAALgADCgkJDgAAAA==.',
Yo='Yoyomba:BAAALgAECgUJBQABLgAECggJJQAcALgaAA==.',
Za='Zargonia:BAAALgAECgEJAQAAAA==.Zaria:BAAALgADCgUJBQAAAA==.',
Ze='Zendetra:BAAALgADCgUJBQABLgAECgQJCwAQAAAAAA==.Zeposo:BAABLgAECn8jAAMMAAgJuhyNDQCEAghoDAAACQBOAGkMAAAGAFQAawwAAAUARwBqDAAAAgA9AGwMAAAFAFYAbQwAAAEAMgDqDAAABgBMAG4MAAABAE8ADAAICbocjQ0AhAIIaAwAAAkATgBpDAAABgBUAGsMAAAFAEcAagwAAAIAPQBsDAAABABWAG0MAAABADIA6gwAAAYATABuDAAAAQBPABsAAQnIBNyNACUAAWwMAAABAAwAAS4ABAoJCVEABgAvHQA=.Zeppo:BAAALgAECgIJAwABLgAECgkJUQAGAC8dAA==.Zeptide:BAABLgAECn9RAAMGAAkJLx15CwD5AgloDAAADwBiAGkMAAAOAGIAawwAAAwARwBqDAAACQBJAGwMAAAHAEsAbQwAAAQAGgDqDAAADABhAG4MAAAGADoAbwwAAAIASAAGAAkJLx15CwD5AgloDAAACgBiAGkMAAAIAGIAawwAAAcARwBqDAAABwBJAGwMAAAEAEsAbQwAAAMAGgDqDAAACgBhAG4MAAABADoAbwwAAAIASAAXAAgJ5xOjJgCrAQhoDAAABQBAAGkMAAAGAD0AawwAAAUAOQBqDAAAAgAXAGwMAAADAEsAbQwAAAEAGQDqDAAAAgAQAG4MAAAFADcAAAA=.Zervish:BAAALgAECgEJAQAAAA==.',
Zo='Zoli:BAAALgAECggJEQAAAA==.',
Zr='Zrichfu:BAAALgADCgIJAgABLgAFFAMJBQAOALoFAA==.',
Zu='Zugnuts:BAAALgAECgcJBwAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
