local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Warlock-Demonology','Warlock-Affliction','DemonHunter-Devourer','Druid-Balance','Druid-Restoration','Paladin-Holy','Paladin-Retribution','Paladin-Protection','Shaman-Restoration','Unknown-Unknown','Monk-Brewmaster','Hunter-BeastMastery','Hunter-Survival','Shaman-Elemental','DeathKnight-Unholy','DeathKnight-Blood','Mage-Frost','Priest-Shadow','Shaman-Enhancement','Evoker-Preservation','Evoker-Augmentation','Warlock-Destruction','Mage-Arcane','DemonHunter-Havoc','Druid-Guardian','Monk-Windwalker','Warrior-Fury','Priest-Discipline','Priest-Holy','Druid-Feral','Monk-Mistweaver','Rogue-Subtlety','Mage-Fire','DeathKnight-Frost','Warrior-Protection','Warrior-Arms','DemonHunter-Vengeance',}
local provider = {region='US',realm="Shu'halo",name='US',type='daily',zone=46,date='2026-05-24',data={Ab='Abelothh:BAABLgAECn8aAAMBAAgJNQtXbABPAQhoDAAABQAlAGkMAAAEACoAawwAAAQAKwBqDAAAAgAmAGwMAAACAA0AbQwAAAIAGgDqDAAABQAUAG4MAAACAA8AAQAICY8JV2wATwEIaAwAAAIAGABpDAAAAgAqAGsMAAACAB4AagwAAAIAJgBsDAAAAgANAG0MAAACABoA6gwAAAIAEQBuDAAAAgAPAAIABAk7DfgTAPAABGgMAAADACUAaQwAAAIAIQBrDAAAAgArAOoMAAADABQAAAA=.Aborted:BAAALgADCgEJAQAAAA==.',
Ad='Adialin:BAAALgADCgQJBwAAAA==.',
Ae='Aelirra:BAABLgAECn8VAAIDAAcJyBqmMgAvAgdoDAAABgBYAGkMAAAEAFEAawwAAAMAPQBqDAAAAQBYAGwMAAABAEgAbQwAAAIAKQDqDAAABABCAAMABwnIGqYyAC8CB2gMAAAGAFgAaQwAAAQAUQBrDAAAAwA9AGoMAAABAFgAbAwAAAEASABtDAAAAgApAOoMAAAEAEIAAAA=.',
Ag='Agarmon:BAAALgAECgUJBgAAAA==.Agarne:BAABLgAECn8YAAMEAAgJ7hOMLwA1AQhoDAAABAAsAGkMAAAEACkAawwAAAQAOABqDAAAAgAaAGwMAAACABwAbQwAAAIALwDqDAAABQA8AG4MAAABAE0ABAAFCfAVjC8ANQEFaAwAAAMALABpDAAABAApAGsMAAAEADgA6gwAAAMAPABuDAAAAQBNAAUABQk8D1hrANQABWgMAAABAAgAagwAAAIAOwBsDAAAAgA2AG0MAAACABkA6gwAAAIALwAAAA==.Agman:BAAALgADCgkJCQAAAA==.',
Ai='Aimster:BAAALgAECgkJBwAAAA==.Aiyania:BAAALgADCgMJAwAAAA==.',
Ak='Akhta:BAABLgAECn8eAAMGAAkJ1BzdCwCuAgloDAAABABeAGkMAAAFAEsAawwAAAUATgBqDAAAAwBDAGwMAAAEAE8AbQwAAAMALQDqDAAABABCAG4MAAABAFsAbwwAAAEAPwAGAAkJ1BzdCwCuAgloDAAAAwBeAGkMAAAEAEsAawwAAAQATgBqDAAAAgBDAGwMAAADAE8AbQwAAAMALQDqDAAAAwBCAG4MAAABAFsAbwwAAAEAPwAHAAYJeAzPrAAEAQZoDAAAAQARAGkMAAABACUAawwAAAEAGwBqDAAAAQAPAGwMAAABAC4A6gwAAAEAHwAAAA==.Akoni:BAAALgAECgYJCgABLgAECgcJGwAIAKUjAA==.',
Al='Allaris:BAABLgAECn8ZAAIBAAYJAAWxtwDBAAZoDAAABQAFAGkMAAAFABMAawwAAAQADgBqDAAAAwAaAGwMAAADAAkA6gwAAAUADwABAAYJAAWxtwDBAAZoDAAABQAFAGkMAAAFABMAawwAAAQADgBqDAAAAwAaAGwMAAADAAkA6gwAAAUADwAAAA==.Allíesin:BAAALgAECgUJCAAAAA==.Altryn:BAAALgAECgMJBgAAAA==.Alundrablaze:BAABLgAECn8mAAIJAAgJ8hfUHQA0AghoDAAABwBaAGkMAAAHAC4AawwAAAcALQBqDAAABQA/AGwMAAADAFIAbQwAAAEAIgDqDAAABwAzAG4MAAABAEwACQAICfIX1B0ANAIIaAwAAAcAWgBpDAAABwAuAGsMAAAHAC0AagwAAAUAPwBsDAAAAwBSAG0MAAABACIA6gwAAAcAMwBuDAAAAQBMAAEuAAQKCAkoAAEA3hIA.',
Am='Amarixa:BAAALgADCgcJCgABLgAECgUJBwAKAAAAAA==.',
An='Angerissue:BAAALgADCgYJEQAAAA==.Anithaya:BAAALgADCgcJBwAAAA==.Anoint:BAACLgAFFH8OAAILAAQJyxkzGAA2AQRoDAAABQBMAGkMAAAFAFUAawwAAAEAIwDqDAAAAwBCAAsABAnLGTMYADYBBGgMAAAFAEwAaQwAAAUAVQBrDAAAAQAjAOoMAAADAEIALgAECn84AAILAAkJayF9BQDNAgALAAkJayF9BQDNAgAAAA==.Anrraakk:BAAALgADCgYJBgAAAA==.',
Ap='Apollis:BAAALgADCgcJBwAAAA==.',
Ar='Aram:BAAALgAECggJCAAAAA==.Aranthino:BAAALgAECggJDgAAAA==.Aryabhatta:BAABLgAECn8iAAMMAAgJHx29JAAlAghoDAAABgBeAGkMAAAGAFAAawwAAAUATwBqDAAABAA8AGwMAAAEAFIAbQwAAAIAOADqDAAABQBUAG4MAAACACsADAAICR8dvSQAJQIIaAwAAAUAXgBpDAAABQBQAGsMAAAFAE8AagwAAAQAPABsDAAAAwBSAG0MAAABADgA6gwAAAMAVABuDAAAAQArAA0ABgnhEAkfAIcBBmgMAAABADQAaQwAAAEAQQBsDAAAAQAfAG0MAAABABUA6gwAAAIARABuDAAAAQATAAAA.',
As='Ashrom:BAAALgAECgEJAgAAAA==.Asrai:BAAALgADCgEJAQAAAA==.Astel:BAAALgAECggJCQAAAA==.',
At='Athellios:BAAALgADCgcJBwAAAA==.Athenarelia:BAABLgAECn8ZAAIJAAgJjBAtOwCUAQhoDAAABQA2AGkMAAAFAEEAawwAAAUAMwBqDAAAAgAuAGwMAAABABoAbQwAAAEAEgDqDAAABQBBAG4MAAABAAkACQAICYwQLTsAlAEIaAwAAAUANgBpDAAABQBBAGsMAAAFADMAagwAAAIALgBsDAAAAQAaAG0MAAABABIA6gwAAAUAQQBuDAAAAQAJAAAA.',
Ba='Backbush:BAAALgAECgQJBwAAAA==.Baelskrim:BAABLgAECn8WAAIOAAcJUR0gHgDHAQdoDAAAAwBMAGkMAAADAFQAawwAAAMAVQBqDAAAAwA2AGwMAAADAEoA6gwAAAYAVwBuDAAAAQAqAA4ABwlRHSAeAMcBB2gMAAADAEwAaQwAAAMAVABrDAAAAwBVAGoMAAADADYAbAwAAAMASgDqDAAABgBXAG4MAAABACoAAAA=.Ballofsoy:BAAALgAECgEJAQAAAA==.Ballrogg:BAAALgADCgYJBgAAAA==.Bamdk:BAABLgAECn9HAAMPAAkJfSDBFwCZAgloDAAACgBaAGkMAAAIAEwAawwAAAkAVgBqDAAACABRAGwMAAAJAFYAbQwAAAkATADqDAAACQBYAG4MAAAGAFkAbwwAAAMARQAPAAkJ3B/BFwCZAgloDAAACQBaAGkMAAAIAEwAawwAAAkAVgBqDAAACABRAGwMAAAGAFYAbQwAAAcAQADqDAAACQBYAG4MAAAGAFkAbwwAAAMARQAQAAMJng5YQABhAANoDAAAAQAPAGwMAAADABMAbQwAAAIATAAAAA==.',
Be='Beansination:BAACLgAFFH8FAAIJAAIJrB19QwCqAAJoDAAAAgBNAOoMAAADAEoACQACCawdfUMAqgACaAwAAAIATQDqDAAAAwBKAC4ABAp/FgADDgAJCa0XrhsA2wEADgAJCa0XrhsA2wEACQAFCcgU+VEAPQEAAAA=.Beefsupriem:BAAALgAECggJEwAAAA==.Bellatrïx:BAAALgAECgEJAgABLgAECgUJCAAKAAAAAA==.Belliaz:BAAALgAECgUJBwAAAA==.',
Bi='Biamdon:BAAALgADCgYJBgAAAA==.Bigcheese:BAAALgAECgEJAQAAAA==.Bigfinger:BAAALgAECgEJAQAAAA==.Biohazard:BAAALgAECgYJDgABLgAFFAMJBgAGADkTAA==.',
Bl='Bloodlyfrost:BAABLgAECn8sAAIRAAkJCAYDdAB3AQloDAAABgARAGkMAAAGABYAawwAAAYAFgBqDAAABQAMAGwMAAAFAA4AbQwAAAMADQDqDAAABgALAG4MAAAFAAoAbwwAAAIACQARAAkJCAYDdAB3AQloDAAABgARAGkMAAAGABYAawwAAAYAFgBqDAAABQAMAGwMAAAFAA4AbQwAAAMADQDqDAAABgALAG4MAAAFAAoAbwwAAAIACQAAAA==.Bloodwell:BAAALgAECgUJBQAAAA==.Bloodyguthix:BAAALgAECgcJCwAAAA==.',
Bo='Bonekrusha:BAAALgADCgYJBgAAAA==.Boombostic:BAAALgADCgcJBwAAAA==.',
Br='Brallaghan:BAAALgADCgEJAQAAAA==.Bramblegrove:BAAALgAECgYJCQABLgAFFAMJDwASAOkRAA==.Breaknasweat:BAAALgAECgIJAgAAAA==.Breakstuff:BAAALgAECgEJAQAAAA==.Brewsandboos:BAAALgADCgYJBgAAAA==.Bruzera:BAAALgADCgYJBgAAAA==.Bréwtality:BAAALgAECgEJAQABLgAFFAQJCwAPAOocAA==.',
['Bò']='Bòóberry:BAAALgAECgMJAwAAAA==.',
Ca='Candyquartz:BAAALgADCgcJFwAAAA==.Caylda:BAAALgAECgUJBQAAAA==.',
Ce='Celladorne:BAAALgAECgcJCwAAAA==.',
Ch='Chibi:BAACLgAFFH8QAAITAAQJ5gK6CADrAARoDAAABgAIAGkMAAAFAAgAawwAAAIABQDqDAAAAwAHABMABAnmAroIAOsABGgMAAAGAAgAaQwAAAUACABrDAAAAgAFAOoMAAADAAcALgAECn8qAAITAAkJ1RLJDwC8AQATAAkJ1RLJDwC8AQAAAA==.Chronokite:BAABLgAECn8YAAMUAAgJtAlvGwAFAQhoDAAABQAZAGkMAAADABkAawwAAAMADgBqDAAAAgAUAGwMAAACAA0AbQwAAAEABADqDAAABgAVAG4MAAACAEkAFAAHCQIHbxsABQEHaAwAAAMAGQBpDAAAAgAZAGsMAAACAA4AagwAAAEAFABsDAAAAQANAG0MAAABAAQA6gwAAAMAFQAVAAcJcwkDQQABAQdoDAAAAgAPAGkMAAABABEAawwAAAEAHABqDAAAAQAZAGwMAAABABkA6gwAAAMAFgBuDAAAAgAkAAAA.',
Co='Colair:BAAALgAECgQJBQAAAA==.',
Cp='Cpr:BAAALgAECgQJDgAAAA==.',
Cr='Crushed:BAABLgAECn8UAAMWAAYJbRpgEwCwAQZoDAAABQBTAGkMAAAEAFMAawwAAAMANQBqDAAAAgBCAGwMAAACADgA6gwAAAQAPAAWAAYJbRpgEwCwAQZoDAAAAwBTAGkMAAAEAFMAawwAAAMANQBqDAAAAgBCAGwMAAACADgA6gwAAAMAPAABAAIJQQv45ABsAAJoDAAAAgAcAOoMAAABAB0AAAA=.',
Cy='Cybele:BAABLgAECn8XAAMJAAcJvBJkRgBoAQdoDAAABABDAGkMAAAEADYAawwAAAQAOwBqDAAAAwAcAGwMAAADADMAbQwAAAEAGwDqDAAABAAvAAkABwm8EmRGAGgBB2gMAAADAEMAaQwAAAMANgBrDAAAAwA7AGoMAAACABwAbAwAAAMAMwBtDAAAAQAbAOoMAAADAC8ADgAFCccHrGcApAAFaAwAAAEAKgBpDAAAAQAVAGsMAAABAAQAagwAAAEAAgDqDAAAAQALAAEuAAQKCAkYABQAtAkA.',
Da='Da:BAAALgADCgUJBQAAAA==.Dantioch:BAAALgADCgMJAwAAAA==.Darafragen:BAABLgAECn82AAIGAAkJahpiDACnAgloDAAABwBXAGkMAAAHAD0AawwAAAcANABqDAAABwBCAGwMAAAHAFYAbQwAAAUARADqDAAABwBZAG4MAAAEAEwAbwwAAAMAEwAGAAkJahpiDACnAgloDAAABwBXAGkMAAAHAD0AawwAAAcANABqDAAABwBCAGwMAAAHAFYAbQwAAAUARADqDAAABwBZAG4MAAAEAEwAbwwAAAMAEwAAAA==.Darkfuse:BAAALgAECgIJAgAAAA==.Darkliter:BAAALgADCgcJBwAAAA==.Darrethuzad:BAAALgADCgUJBQAAAA==.Daveycrocket:BAAALgADCgUJBQAAAA==.Dayman:BAABLgAECn8YAAIHAAYJKRxDWgChAQZoDAAABwBQAGkMAAAFAFQAawwAAAYATwBqDAAABAAwAOoMAAABACoAbgwAAAEASQAHAAYJKRxDWgChAQZoDAAABwBQAGkMAAAFAFQAawwAAAYATwBqDAAABAAwAOoMAAABACoAbgwAAAEASQAAAA==.',
Db='Dbk:BAAALgAECgYJEgAAAA==.',
De='Deader:BAAALgAECggJDwAAAA==.Deadlyydot:BAABLgAECn8WAAISAAYJ5gaNQwDZAAZoDAAABAARAGkMAAAGABYAawwAAAgAEwBqDAAAAQAEAOoMAAACAA8AbgwAAAEADQASAAYJ5gaNQwDZAAZoDAAABAARAGkMAAAGABYAawwAAAgAEwBqDAAAAQAEAOoMAAACAA8AbgwAAAEADQAAAA==.Deadlyykiss:BAABLgAECn8cAAIXAAYJywZACQDPAAZoDAAACQAVAGkMAAAHABgAawwAAAcAEwBqDAAAAgAUAGwMAAACAAwA6gwAAAEACQAXAAYJywZACQDPAAZoDAAACQAVAGkMAAAHABgAawwAAAcAEwBqDAAAAgAUAGwMAAACAAwA6gwAAAEACQAAAA==.Deathhowl:BAAALgAECgMJBAAAAA==.Demonsaber:BAABLgAECn8VAAIDAAcJaQO/xQBuAAdoDAAABAANAGkMAAADAAgAawwAAAQABgBqDAAABAAHAGwMAAABAAkA6gwAAAQACQBuDAAAAQAEAAMABwlpA7/FAG4AB2gMAAAEAA0AaQwAAAMACABrDAAABAAGAGoMAAAEAAcAbAwAAAEACQDqDAAABAAJAG4MAAABAAQAAAA=.Demonseed:BAAALgAECgYJBwAAAA==.Demonslice:BAABLgAECn8ZAAMYAAYJago7MADNAAZoDAAABgAlAGkMAAAFABcAawwAAAUACwBqDAAAAwBNAGwMAAACACgA6gwAAAQAFAAYAAYJago7MADNAAZoDAAAAwAlAGkMAAADABcAawwAAAMACwBqDAAAAwBNAGwMAAACACgA6gwAAAIAFAADAAQJ2wTdwgB0AARoDAAAAwAKAGkMAAACABMAawwAAAIACgDqDAAAAgAIAAAA.Derrf:BAAALgADCgMJAwAAAA==.Derrickalen:BAAALgADCgIJAgAAAA==.',
Di='Dinhdinh:BAAALgAECgQJBAAAAA==.Dire:BAAALgAECgMJBQAAAA==.Dirtydotz:BAAALgADCgUJBgAAAA==.Disengage:BAABLgAECn8tAAIMAAgJ1w92TwCIAQhoDAAABwBKAGkMAAAHAC0AawwAAAcAIgBqDAAABQAZAGwMAAAFADEAbQwAAAIACADqDAAACgAtAG4MAAACABoADAAICdcPdk8AiAEIaAwAAAcASgBpDAAABwAtAGsMAAAHACIAagwAAAUAGQBsDAAABQAxAG0MAAACAAgA6gwAAAoALQBuDAAAAgAaAAAA.Displace:BAAALgAECgYJCwAAAA==.Divinewords:BAAALgADCgEJAQAAAA==.Divish:BAABLgAECn8qAAMUAAkJMRzbBQCQAgloDAAABQBKAGkMAAAFAEgAawwAAAUAUABqDAAABQBJAGwMAAAGAFEAbQwAAAMAPADqDAAACABEAG4MAAADADwAbwwAAAIATgAUAAkJMRzbBQCQAgloDAAABQBKAGkMAAAFAEgAawwAAAUAUABqDAAABABJAGwMAAAGAFEAbQwAAAMAPADqDAAACABEAG4MAAADADwAbwwAAAIATgAVAAEJAACWjwAAAAFqDAAAAQArAAAA.',
Do='Dogan:BAAALgAECgQJBAAAAA==.Dommymommy:BAAALgADCgMJAwAAAA==.Dorim:BAAALgADCgQJBQAAAA==.Dotaldtrump:BAAALgAECgIJAgAAAA==.',
Dr='Dragkin:BAAALgADCgYJBgAAAA==.Dragonrunner:BAAALgAECgEJAQAAAA==.Dragoon:BAAALgADCgQJBAAAAA==.Drenne:BAAALgADCgIJAgAAAA==.Dreyvia:BAAALgADCgUJBQAAAA==.Drfelgood:BAAALgADCgYJBgAAAA==.Drillanne:BAAALgAECgYJDQAAAA==.Dropdeath:BAAALgAECgUJBQAAAA==.Druecc:BAABLgAECn8eAAIRAAgJZxCQZwCTAQhoDAAABQAeAGkMAAAGADEAawwAAAQAOwBqDAAABAATAGwMAAAEADcAbQwAAAEAEQDqDAAABQA3AG4MAAABABkAEQAICWcQkGcAkwEIaAwAAAUAHgBpDAAABgAxAGsMAAAEADsAagwAAAQAEwBsDAAABAA3AG0MAAABABEA6gwAAAUANwBuDAAAAQAZAAAA.Druidlord:BAABLgAECn8ZAAIZAAgJpAICNwCGAAhoDAAABQAGAGkMAAAEAAgAawwAAAQABgBqDAAAAwAIAGwMAAACAAcAbQwAAAIABwDqDAAABAAIAG4MAAABAAMAGQAICaQCAjcAhgAIaAwAAAUABgBpDAAABAAIAGsMAAAEAAYAagwAAAMACABsDAAAAgAHAG0MAAACAAcA6gwAAAQACABuDAAAAQADAAAA.Drág:BAAALgADCgMJAwAAAA==.',
Du='Duckie:BAAALgAECggJCQAAAA==.Dumplíng:BAAALgAECgQJBAABLgAECggJGAAEAO4TAA==.',
Dy='Dyrre:BAAALgADCgEJAQABLgAECgMJBQAKAAAAAA==.',
Dz='Dzhunter:BAAALgAECgkJAQAAAA==.',
Ed='Edgerallen:BAABLgAECn8bAAMLAAgJFBCYJwBXAQhoDAAABAAiAGkMAAAEAC4AawwAAAQALQBqDAAABAAdAGwMAAADACoAbQwAAAIAKgDqDAAABAAnAG4MAAACACUACwAICRQQmCcAVwEIaAwAAAMAIgBpDAAAAwAuAGsMAAADAC0AagwAAAMAHQBsDAAAAgAqAG0MAAACACoA6gwAAAMAJwBuDAAAAgAlABoABgmuAv9hAIcABmgMAAABAAQAaQwAAAEAAwBrDAAAAQAPAGoMAAABAAcAbAwAAAEACADqDAAAAQACAAAA.',
El='Elchronomagi:BAAALgADCgIJAgABLgAECggJGAAUALQJAA==.Elcuh:BAAALgADCgEJAQAAAA==.Eldenringtwo:BAAALgAECgUJCQAAAA==.Elereeste:BAAALgAECgcJCgAAAA==.Elianaa:BAAALgADCgMJBgAAAA==.Ellennia:BAAALgAECgUJBwAAAA==.',
Er='Era:BAABLgAECn8hAAIbAAcJCxuYIwC1AQdoDAAABwBYAGkMAAAGAEAAawwAAAYASQBqDAAABABIAGwMAAADADYAbQwAAAIASQDqDAAABQA8ABsABwkLG5gjALUBB2gMAAAHAFgAaQwAAAYAQABrDAAABgBJAGoMAAAEAEgAbAwAAAMANgBtDAAAAgBJAOoMAAAFADwAAAA=.',
Ex='Executions:BAAALgAECgUJBgAAAA==.',
Fa='Fanara:BAAALgAECgUJDgAAAA==.Fangtazia:BAAALgADCgQJBAAAAA==.Fartbiscuits:BAAALgADCgcJDQAAAA==.Farty:BAABLgAECn8aAAQJAAgJCB6+EgCNAghoDAAABQBPAGkMAAAEAE8AawwAAAQASABqDAAAAgBUAGwMAAADAFsAbQwAAAEASQDqDAAABgBEAG4MAAABAEIACQAICQgevhIAjQIIaAwAAAMATwBpDAAABABPAGsMAAADAEgAagwAAAIAVABsDAAAAwBbAG0MAAABAEkA6gwAAAYARABuDAAAAQBCAA4AAQmCCnaVACcAAWgMAAACABoAEwABCR0A8jYABAABawwAAAEAAAAAAA==.Fathuman:BAAALgAECgYJBwAAAA==.',
Fe='Feff:BAAALgADCgQJBgABLgAECgEJAQAKAAAAAA==.Felbládes:BAAALgAECgMJBQAAAA==.Felrushu:BAAALgAECgMJAwAAAA==.Fenaly:BAAALgADCgUJBQAAAA==.Fenryumei:BAAALgADCgUJBQAAAA==.Fensdead:BAABLgAECn8kAAIaAAgJzRc4GADKAQhoDAAABgBPAGkMAAAGAEcAawwAAAUAQQBqDAAABAA/AGwMAAAEADQAbQwAAAEARADqDAAACQBUAG4MAAABAAQAGgAICc0XOBgAygEIaAwAAAYATwBpDAAABgBHAGsMAAAFAEEAagwAAAQAPwBsDAAABAA0AG0MAAABAEQA6gwAAAkAVABuDAAAAQAEAAAA.Fentarus:BAAALgADCggJCAAAAA==.',
Fi='Finluzzertok:BAAALgADCgQJBAABLgAECgkJJwARAKgDAA==.Fitua:BAABLgAECn8gAAIPAAkJjwu3fgCGAQloDAAABwAyAGkMAAAEADIAawwAAAQAMgBqDAAABAAuAGwMAAAFACQAbQwAAAIACQDqDAAABAAfAG4MAAABAAEAbwwAAAEABgAPAAkJjwu3fgCGAQloDAAABwAyAGkMAAAEADIAawwAAAQAMgBqDAAABAAuAGwMAAAFACQAbQwAAAIACQDqDAAABAAfAG4MAAABAAEAbwwAAAEABgAAAA==.Fizzbann:BAAALgAECgYJDgABLgAECgcJGwAIAKUjAA==.',
Fk='Fkingbeast:BAAALgAFFAgJAQAAAA==.',
Fl='Flowercat:BAAALgADCgcJDgAAAA==.',
Fo='Fordemocracy:BAAALgAECggJDgAAAA==.Foutre:BAABLgAECn8cAAIEAAgJEgqoMQApAQhoDAAABQAmAGkMAAAFABwAawwAAAQAHABqDAAABAAnAGwMAAADABEAbQwAAAIAGADqDAAABAAaAG4MAAABABEABAAICRIKqDEAKQEIaAwAAAUAJgBpDAAABQAcAGsMAAAEABwAagwAAAQAJwBsDAAAAwARAG0MAAACABgA6gwAAAQAGgBuDAAAAQARAAAA.',
Fr='Froghugger:BAAALgAECgUJBQAAAA==.Fruntstabba:BAAALgAECgEJAQAAAA==.',
Fu='Fudgefisting:BAAALgAECgEJAQAAAA==.Fuzzytotems:BAAALgAECgUJCAAAAA==.',
['Få']='Fång:BAAALgAECggJEAAAAA==.',
Ga='Galadenn:BAAALgADCgEJAQAAAA==.Garo:BAABLgAECn88AAITAAkJ8x9VAgDcAgloDAAACQBbAGkMAAAJAFkAawwAAAoAVABqDAAABgBdAGwMAAAIAFIAbQwAAAMAVwDqDAAACQBQAG4MAAAEAFAAbwwAAAIAOgATAAkJ8x9VAgDcAgloDAAACQBbAGkMAAAJAFkAawwAAAoAVABqDAAABgBdAGwMAAAIAFIAbQwAAAMAVwDqDAAACQBQAG4MAAAEAFAAbwwAAAIAOgAAAA==.',
Ge='Getlnmyvan:BAABLgAECn8qAAIHAAkJuCDYDADlAgloDAAABwBVAGkMAAAHAFwAawwAAAcAXABqDAAABABfAGwMAAAFAFoAbQwAAAMAYQDqDAAABgBYAG4MAAACADwAbwwAAAEAPgAHAAkJuCDYDADlAgloDAAABwBVAGkMAAAHAFwAawwAAAcAXABqDAAABABfAGwMAAAFAFoAbQwAAAMAYQDqDAAABgBYAG4MAAACADwAbwwAAAEAPgAAAA==.',
Gh='Ghanima:BAAALgAECgEJAQABLgAECgYJEAAKAAAAAA==.Ghoulgranny:BAAALgADCgMJAwAAAA==.Ghoulie:BAAALgAECgQJCAAAAA==.',
Gi='Gigglebytes:BAAALgADCgEJAQAAAA==.Gigipi:BAAALgAECgEJAQAAAA==.Gile:BAAALgAECgIJAQABLgAECgkJIAAPAI8LAA==.',
Gl='Glert:BAABLgAECn8YAAIRAAgJyw8cngCaAQhoDAAABAA4AGkMAAAEADIAawwAAAMALgBqDAAAAgARAGwMAAADACoAbQwAAAEAHgDqDAAABQAxAG4MAAACAAcAEQAICcsPHJ4AmgEIaAwAAAQAOABpDAAABAAyAGsMAAADAC4AagwAAAIAEQBsDAAAAwAqAG0MAAABAB4A6gwAAAUAMQBuDAAAAgAHAAAA.',
Go='Goinpriest:BAABLgAECn8lAAQSAAkJcAb/LgA9AQloDAAABgAPAGkMAAAFABIAawwAAAUAEwBqDAAABQAWAGwMAAAEABUAbQwAAAMACgDqDAAABQAXAG4MAAADAAwAbwwAAAEACQASAAkJcAb/LgA9AQloDAAABAAPAGkMAAADABIAawwAAAMAEwBqDAAAAwAWAGwMAAACABUAbQwAAAMACgDqDAAAAwAXAG4MAAADAAwAbwwAAAEACQAcAAYJAwS8NQD3AAZoDAAAAQALAGkMAAABAAUAawwAAAEACABqDAAAAQAQAGwMAAABAAQA6gwAAAEADwAdAAYJUAIxVQDiAAZoDAAAAQAJAGkMAAABAAQAawwAAAEAAwBqDAAAAQAIAGwMAAABAAIA6gwAAAEABgAAAA==.Goinsolo:BAABLgAECn8fAAMMAAkJgRHFMADwAQloDAAABAAsAGkMAAAEAD4AawwAAAQAOgBqDAAABAAvAGwMAAADABMAbQwAAAMAPQDqDAAAAwAmAG4MAAADACEAbwwAAAMAKAAMAAkJgRHFMADwAQloDAAAAgAsAGkMAAADAD4AawwAAAIAOgBqDAAAAwAvAGwMAAACABMAbQwAAAMAPQDqDAAAAgAmAG4MAAADACEAbwwAAAMAKAANAAYJ4wJmOgC+AAZoDAAAAgAEAGkMAAABAAgAawwAAAIACgBqDAAAAQAQAGwMAAABAAYA6gwAAAEABwAAAA==.Goonergizmo:BAAALgADCgYJBgAAAA==.Gorbon:BAABLgAECn8kAAMFAAgJzBnyHwBCAghoDAAABQBLAGkMAAAHAE8AawwAAAcAVQBqDAAABQAuAGwMAAAFAEYAbQwAAAIAQgDqDAAABABFAG4MAAABACMABQAICcwZ8h8AQgIIaAwAAAQASwBpDAAABgBPAGsMAAAGAFUAagwAAAMALgBsDAAAAwBGAG0MAAACAEIA6gwAAAQARQBuDAAAAQAjAAQABQl5Dp5NAPMABWgMAAABACUAaQwAAAEAAwBrDAAAAQAvAGoMAAACACUAbAwAAAIAPAAAAA==.Gorecrush:BAAALgADCgEJAQABLgAFFAMJDwASAOkRAA==.Gorvax:BAABLgAECn8kAAMQAAgJYhbtFACbAQhoDAAABgBdAGkMAAAHAEMAawwAAAUAQQBqDAAABQA4AGwMAAAFADgAbQwAAAEAKQDqDAAABQA4AG4MAAACABQAEAAICWIW7RQAmwEIaAwAAAYAXQBpDAAABgBDAGsMAAAFAEEAagwAAAQAOABsDAAABAA4AG0MAAABACkA6gwAAAUAOABuDAAAAgAUAA8AAwnjEDX/AHUAA2kMAAABADMAagwAAAEAKABsDAAAAQAiAAAA.',
Gr='Grimnyx:BAAALgADCgYJCwAAAA==.Grimstout:BAAALgAECgEJAQAAAA==.Gripe:BAAALgAECgEJAQAAAA==.Groguk:BAAALgAECgIJAgAAAA==.',
Gu='Gummymagic:BAAALgAECgcJEgABLgAFFAUJHQAMAMMgAA==.',
Gw='Gwenledyr:BAABLgAECn8+AAQCAAkJWB47AwBZAgloDAAACABUAGkMAAAIAFcAawwAAAgAVQBqDAAACABMAGwMAAAIAFAAbQwAAAYAPgDqDAAACABIAG4MAAAFAFUAbwwAAAMAPQACAAgJmB07AwBZAghoDAAAAgBUAGkMAAACAFcAawwAAAEAQwBqDAAABABMAGwMAAADAEUAbQwAAAEAPgDqDAAAAgBIAG4MAAABAFUAAQAJCc8VAzIA+wEJaAwAAAYATwBpDAAABQBMAGsMAAAGADcAagwAAAIAMABsDAAAAgAzAG0MAAADACMA6gwAAAYAOABuDAAAAgAdAG8MAAADAD0AFgAGCSgZQw4ALwEGaQwAAAEAKQBrDAAAAQBVAGoMAAACAD0AbAwAAAMAUABtDAAAAgAzAG4MAAACAD4AAAA=.',
Ha='Hairydeer:BAAALgADCgUJBQAAAA==.Hamrinuranus:BAAALgAECgEJAgAAAA==.Hazee:BAAALgADCgEJAQAAAA==.',
He='Heimei:BAAALgADCgEJAQABLgAECgYJEAAKAAAAAA==.Heimthrall:BAABLgAECn80AAIHAAkJpw0QVgCsAQloDAAABwAjAGkMAAAHAFIAawwAAAcALQBqDAAABwAgAGwMAAAHABYAbQwAAAUADwDqDAAABgAoAG4MAAAEABQAbwwAAAIAEAAHAAkJpw0QVgCsAQloDAAABwAjAGkMAAAHAFIAawwAAAcALQBqDAAABwAgAGwMAAAHABYAbQwAAAUADwDqDAAABgAoAG4MAAAEABQAbwwAAAIAEAAAAA==.Hekatee:BAAALgAECgYJDgAAAA==.Hekkruk:BAAALgAECgMJAwABLgAFFAQJCgAeAEIeAA==.Hekus:BAAALgAECgQJBAABLgAECgcJDgAKAAAAAA==.Hemesia:BAAALgAECgEJAgAAAA==.Henshin:BAABLgAECn8kAAMFAAgJ0CI6FwBsAghoDAAABwBhAGkMAAAGAF4AawwAAAUASwBqDAAABABdAGwMAAAEAFoAbQwAAAEAUQDqDAAABwBWAG4MAAACAFwABQAHCTojOhcAbAIHaAwAAAUAYQBpDAAABABeAGsMAAADAEsAagwAAAIAXQBsDAAAAgBaAOoMAAAFAFYAbgwAAAIAXAAEAAcJ/RQQJgBwAQdoDAAAAgA3AGkMAAACADwAawwAAAIAPABqDAAAAgAvAGwMAAACADwAbQwAAAEAKgDqDAAAAgAqAAAA.Herak:BAABLgAECn8hAAINAAcJxwu5JQBRAQdoDAAABwA9AGkMAAAHABcAawwAAAYAGABqDAAABAASAGwMAAADAA8A6gwAAAUAFwBuDAAAAQAgAA0ABwnHC7klAFEBB2gMAAAHAD0AaQwAAAcAFwBrDAAABgAYAGoMAAAEABIAbAwAAAMADwDqDAAABQAXAG4MAAABACAAAAA=.Hermiecrabbs:BAAALgAECgMJAwAAAA==.',
Hi='Highchairjr:BAABLgAECn8nAAMWAAgJZhoAEAAYAQhoDAAACABJAGkMAAAGAEMAawwAAAcASgBqDAAABAA8AGwMAAAEAFcAbQwAAAEALQDqDAAACABEAG4MAAABADgAAQAFCXwZi3wALQEFaAwAAAgASQBpDAAABABDAGsMAAAFAEoAbAwAAAEAKwDqDAAABABEABYABwkAFwAQABgBB2kMAAACADQAawwAAAIAQABqDAAABAA8AGwMAAADAFcAbQwAAAEALQDqDAAABAAuAG4MAAABADgAAAA=.Hildaelf:BAAALgAECgYJDQABLgAECgcJGwAIAKUjAA==.',
Ho='Hojdeeznuts:BAABLgAECn8vAAMGAAgJSx4iEQBrAghoDAAACABYAGkMAAAIADwAawwAAAgAVgBqDAAABwBHAGwMAAAEAFgAbQwAAAEAPADqDAAACABHAG4MAAADAF0ABgAICUseIhEAawIIaAwAAAcAWABpDAAABwA8AGsMAAAHAFYAagwAAAYARwBsDAAABABYAG0MAAABADwA6gwAAAcARwBuDAAAAQBdAAcABgnqBhzCAOQABmgMAAABABIAaQwAAAEAFgBrDAAAAQASAGoMAAABAEoA6gwAAAEADgBuDAAAAgANAAAA.Holyfudge:BAAALgAECgMJAwAAAA==.Holysatan:BAAALgAECgQJBAAAAA==.Holytyr:BAAALgAECgMJBgAAAA==.Horazi:BAAALgAECgEJAQABLgAECgkJHgAGANQcAA==.Horohöro:BAAALgAFFAQJBAABLgAFFAQJDgALAMsZAA==.',
Hu='Huehue:BAAALgADCgYJBwAAAA==.',
Hy='Hybrid:BAAALgADCgkJGwAAAA==.',
['Hé']='Héaler:BAAALgADCgUJBwAAAA==.',
Ib='Ibuprofen:BAAALgADCgcJBwAAAA==.',
Ii='Iil:BAABLgAECn8lAAMRAAcJOhZ6aACRAQdoDAAABwBUAGkMAAAHAD4AawwAAAcAMABqDAAABQA5AGwMAAADAC8AbQwAAAIAMwDqDAAABgAvABEABwk6FnpoAJEBB2gMAAAGAFQAaQwAAAcAPgBrDAAABwAwAGoMAAAFADkAbAwAAAMALwBtDAAAAgAzAOoMAAAGAC8AFwABCRUUlhsAPQABaAwAAAEAMwAAAA==.',
Im='Imabustmommy:BAAALgAECgQJBwAAAA==.Imperator:BAAALgADCgUJBQAAAA==.',
Iq='Iqsamurai:BAAALgADCgQJAwAAAA==.',
Ir='Irwarrioryo:BAAALgADCgMJAwABLgAECgcJJQARADoWAA==.',
Is='Istor:BAAALgAECgUJCgAAAA==.',
Ja='Jaxxia:BAABLgAECn8lAAIGAAcJug5CMQBuAQdoDAAACQBLAGkMAAAGADMAawwAAAYALgBqDAAABQAcAGwMAAADABsAbQwAAAEADgDqDAAABwAUAAYABwm6DkIxAG4BB2gMAAAJAEsAaQwAAAYAMwBrDAAABgAuAGoMAAAFABwAbAwAAAMAGwBtDAAAAQAOAOoMAAAHABQAAAA=.',
Jb='Jblaze:BAAALgAECgYJDQAAAA==.',
Je='Jellzilla:BAAALgAECgEJAQAAAA==.Jenjas:BAAALgADCgYJCwAAAA==.Jenjaz:BAABLgAECn8XAAIaAAgJDBWYHACjAQhoDAAABQBKAGkMAAADADkAawwAAAQAPwBqDAAAAgBHAGwMAAADAC0AbQwAAAEAPwDqDAAABAAwAG4MAAABABcAGgAICQwVmBwAowEIaAwAAAUASgBpDAAAAwA5AGsMAAAEAD8AagwAAAIARwBsDAAAAwAtAG0MAAABAD8A6gwAAAQAMABuDAAAAQAXAAAA.Jenzo:BAAALgADCgcJCAAAAA==.',
Jh='Jhalicistu:BAAALgAECgIJAgAAAA==.',
Jo='Joesphkony:BAAALgADCgUJBQAAAA==.Jorick:BAABLgAECn8VAAIHAAYJPQc5zADVAAZoDAAAAwAfAGkMAAAEABsAawwAAAQACABqDAAAAwATAGwMAAADABAA6gwAAAQABwAHAAYJPQc5zADVAAZoDAAAAwAfAGkMAAAEABsAawwAAAQACABqDAAAAwATAGwMAAADABAA6gwAAAQABwAAAA==.',
Ju='Ju:BAABLgAECn8VAAIfAAYJoBaDMABtAQZoDAAABQA9AGkMAAAFAEcAawwAAAQAKABqDAAAAgAqAGwMAAACADwA6gwAAAMARgAfAAYJoBaDMABtAQZoDAAABQA9AGkMAAAFAEcAawwAAAQAKABqDAAAAgAqAGwMAAACADwA6gwAAAMARgAAAA==.Juzodots:BAAALgAECgEJAgAAAA==.Juzomido:BAACLgAFFH8WAAINAAUJ+xSxDABJAQVoDAAABwBZAGkMAAAFACgAawwAAAMAEgBqDAAAAgBHAOoMAAAFAEIADQAFCfsUsQwASQEFaAwAAAcAWQBpDAAABQAoAGsMAAADABIAagwAAAIARwDqDAAABQBCAC4ABAp/JwACDQAJCWwceQQA0wIADQAJCWwceQQA0wIAAAA=.',
Ka='Kaidre:BAAALgADCgQJBAAAAA==.Kaijhin:BAABLgAECn8yAAIaAAgJOhkUFAD1AQhoDAAACABWAGkMAAAJAEMAawwAAAgAPQBqDAAABwBTAGwMAAAHAEEAbQwAAAEAOADqDAAABwBFAG4MAAADAC0AGgAICToZFBQA9QEIaAwAAAgAVgBpDAAACQBDAGsMAAAIAD0AagwAAAcAUwBsDAAABwBBAG0MAAABADgA6gwAAAcARQBuDAAAAwAtAAAA.Kaline:BAABLgAECn8XAAIZAAgJ4xqoBgBbAghoDAAABABJAGkMAAAEAEwAawwAAAQASQBqDAAAAwBIAGwMAAADAFAAbQwAAAEANQDqDAAAAwBRAG4MAAABACoAGQAICeMaqAYAWwIIaAwAAAQASQBpDAAABABMAGsMAAAEAEkAagwAAAMASABsDAAAAwBQAG0MAAABADUA6gwAAAMAUQBuDAAAAQAqAAAA.Karupted:BAABLgAECn8XAAIMAAYJHAjBjwDxAAZoDAAABQAfAGkMAAAFABUAawwAAAUAEgBqDAAAAwAaAGwMAAADABYA6gwAAAIACQAMAAYJHAjBjwDxAAZoDAAABQAfAGkMAAAFABUAawwAAAUAEgBqDAAAAwAaAGwMAAADABYA6gwAAAIACQAAAA==.Katianna:BAABLgAECn8sAAIJAAkJvB1sCgDpAgloDAAABQBQAGkMAAAFAE0AawwAAAUAUwBqDAAABgBXAGwMAAAHAEYAbQwAAAUARADqDAAABQBPAG4MAAAEAFIAbwwAAAIANAAJAAkJvB1sCgDpAgloDAAABQBQAGkMAAAFAE0AawwAAAUAUwBqDAAABgBXAGwMAAAHAEYAbQwAAAUARADqDAAABQBPAG4MAAAEAFIAbwwAAAIANAAAAA==.Kayfitz:BAAALgAECgcJAgAAAA==.',
Ke='Keallach:BAABLgAECn8gAAIHAAgJGQ9MawB6AQhoDAAABwAlAGkMAAAGADMAawwAAAUALwBqDAAAAwAlAGwMAAACACMAbQwAAAIAHgDqDAAABgAcAG4MAAABACcABwAICRkPTGsAegEIaAwAAAcAJQBpDAAABgAzAGsMAAAFAC8AagwAAAMAJQBsDAAAAgAjAG0MAAACAB4A6gwAAAYAHABuDAAAAQAnAAAA.Keola:BAAALgAECgUJBQABLgAECgkJBgAKAAAAAA==.Kerra:BAAALgADCgMJAwAAAA==.',
Kh='Khalli:BAABLgAECn8oAAMdAAgJJxkKGADoAQhoDAAABwBXAGkMAAAHAEYAawwAAAYAUQBqDAAABQBBAGwMAAAFADIAbQwAAAIAIwDqDAAABgA0AG4MAAACAEcAHQAHCcQYChgA6AEHaAwAAAcAVwBpDAAABwBGAGsMAAAGAFEAagwAAAUAQQBsDAAABQAyAG0MAAACACMA6gwAAAYANAASAAEJJQdIeAAqAAFuDAAAAgASAAAA.Khalwena:BAAALgAECgEJAQAAAA==.Khapri:BAAALgADCgEJAQAAAA==.Khirah:BAAALgADCgUJBgAAAA==.Khora:BAAALgADCgUJCAAAAA==.',
Ki='Kinddurid:BAAALgADCgEJAQAAAA==.Kindmonk:BAAALgADCgMJAwAAAA==.Kindpaladin:BAABLgAECn8ZAAMHAAcJVRKcdQBlAQdoDAAABQBMAGkMAAAGADoAawwAAAYAMwBqDAAAAwA0AGwMAAABABoA6gwAAAIACABuDAAAAgA7AAcABwlVEpx1AGUBB2gMAAAFAEwAaQwAAAUAOgBrDAAABQAzAGoMAAADADQAbAwAAAEAGgDqDAAAAgAIAG4MAAACADsACAACCdMAQUsAHQACaQwAAAEAAgBrDAAAAQACAAAA.Kissesnhugs:BAAALgADCgUJBwAAAA==.Kittycatlj:BAAALgADCgUJBQAAAA==.Kiwirage:BAAALgAECgUJBQAAAA==.Kizent:BAAALgAECgMJBAAAAA==.',
Ko='Koraena:BAAALgAECgUJCgAAAA==.Koronuss:BAAALgAFFAIJAgAAAA==.',
Kr='Krivgar:BAAALgAECgcJDwAAAA==.Krivgarr:BAAALgADCgEJAQAAAA==.Krongar:BAAALgADCgEJAQAAAA==.Kronoz:BAAALgAECgQJBQAAAA==.',
Ku='Kulrig:BAACLgAFFH8PAAQSAAMJ6RHLGgDwAANoDAAABQApAGkMAAAGAC0A6gwAAAQAMgASAAMJ6RHLGgDwAANoDAAAAwApAGkMAAADAC0A6gwAAAMAMgAdAAMJ/gUoHQCmAANoDAAAAQAUAGkMAAACAA8A6gwAAAEACQAcAAIJ3QK1NABdAAJoDAAAAQANAGkMAAABAAAALgAECn9GAAQSAAgJhhvqEQAiAgASAAgJhhvqEQAiAgAdAAcJcRdeHwDmAQAcAAEJDQZJbgAlAAAAAA==.Kurwa:BAAALgADCgcJCAAAAA==.Kushisgreat:BAAALgADCgEJAQAAAA==.',
['Ká']='Kám:BAAALgAECgUJBQAAAA==.',
['Kï']='Kïkîëzz:BAAALgADCggJDAAAAA==.',
La='Landrei:BAAALgAECgEJAQABLgAECgcJGQAMADcPAA==.Lanlong:BAAALgADCgcJCgABLgAECgYJEAAKAAAAAA==.Lastmark:BAAALgADCgcJDgAAAA==.',
Le='Lesrak:BAAALgADCgcJDQAAAA==.',
Li='Lightjohn:BAAALgADCgkJFgAAAA==.Liliac:BAAALgADCgEJAQAAAA==.',
Lo='Lockitdownz:BAAALgAECgEJAQAAAA==.Loryian:BAAALgADCgYJBgAAAA==.Loww:BAAALgAECgEJAQAAAA==.',
Lu='Luminnas:BAAALgAECgYJCwABLgAECgcJGwAIAKUjAA==.Lunaari:BAAALgAECgYJBgAAAA==.Lunalei:BAAALgAECgIJAgAAAA==.',
Ly='Lysius:BAAALgADCgMJBAAAAA==.',
Ma='Madeye:BAAALgADCgUJBQAAAA==.Maesunrays:BAAALgAECgEJAQAAAA==.Mahoraga:BAABLgAECn8cAAIgAAkJmB3IFwBKAgloDAAABQBTAGkMAAAFAF0AawwAAAQAWQBqDAAABABRAGwMAAACAFUAbQwAAAEAMADqDAAAAgBaAG4MAAADAFIAbwwAAAIAIQAgAAkJmB3IFwBKAgloDAAABQBTAGkMAAAFAF0AawwAAAQAWQBqDAAABABRAGwMAAACAFUAbQwAAAEAMADqDAAAAgBaAG4MAAADAFIAbwwAAAIAIQAAAA==.Malach:BAAALgADCgEJAgAAAA==.Malganon:BAABLgAECn8pAAIHAAgJihrUOgD5AQhoDAAABwA8AGkMAAAGAE0AawwAAAYATwBqDAAABgA9AGwMAAAFAEsAbQwAAAIAOADqDAAABwBKAG4MAAACADMABwAICYoa1DoA+QEIaAwAAAcAPABpDAAABgBNAGsMAAAGAE8AagwAAAYAPQBsDAAABQBLAG0MAAACADgA6gwAAAcASgBuDAAAAgAzAAAA.Marcille:BAAALgAECgEJAQAAAA==.Margarrann:BAAALgAECgIJAgABLgAFFAMJDwASAOkRAA==.Martheiran:BAAALgAECgYJCgAAAA==.Marzanna:BAAALgADCgMJAwAAAA==.Mashpewtater:BAAALgAECgcJEgAAAA==.Mathelmana:BAABLgAECn8oAAMBAAgJ3hInZABiAQhoDAAABwApAGkMAAAHADcAawwAAAYAOQBqDAAABQAwAGwMAAAFAC4AbQwAAAIAJwDqDAAABgAqAG4MAAACADcAAQAHCSMRJ2QAYgEHaAwAAAYAJQBpDAAABgA3AGsMAAADACoAagwAAAMAMABsDAAABAAuAG0MAAABACcA6gwAAAYAKgACAAcJ6g+UEwD7AAdoDAAAAQApAGkMAAABABYAawwAAAMAOQBqDAAAAgArAGwMAAABAB0AbQwAAAEAJQBuDAAAAgA3AAAA.Mawika:BAAALgAECgQJBQAAAA==.',
Me='Mellwin:BAAALgAECgQJBAAAAA==.Mezthyr:BAAALgADCggJCAAAAA==.',
Mi='Miliandra:BAAALgADCgYJDwAAAA==.Minervasande:BAAALgADCgIJAgAAAA==.Minshara:BAAALgADCgEJAQAAAA==.Mintcocoa:BAABLgAECn8pAAISAAkJCRIoGADjAQloDAAABgAYAGkMAAAFADIAawwAAAUAMQBqDAAABAAhAGwMAAAEACQAbQwAAAIAIwDqDAAACAA0AG4MAAAGAC8AbwwAAAEASAASAAkJCRIoGADjAQloDAAABgAYAGkMAAAFADIAawwAAAUAMQBqDAAABAAhAGwMAAAEACQAbQwAAAIAIwDqDAAACAA0AG4MAAAGAC8AbwwAAAEASAAAAA==.Miseral:BAABLgAECn87AAIYAAkJDyDeBADPAgloDAAACQBZAGkMAAAIAFQAawwAAAgATQBqDAAABwBTAGwMAAAHAFwAbQwAAAUAQQDqDAAACABYAG4MAAAFAEwAbwwAAAIAUwAYAAkJDyDeBADPAgloDAAACQBZAGkMAAAIAFQAawwAAAgATQBqDAAABwBTAGwMAAAHAFwAbQwAAAUAQQDqDAAACABYAG4MAAAFAEwAbwwAAAIAUwAAAA==.Missfrost:BAAALgAECgIJBwAAAA==.Mitzy:BAAALgAECgUJCAAAAA==.',
Mo='Moganchee:BAABLgAECn8dAAMRAAkJtgTOggBYAQloDAAABQAMAGkMAAAEABQAawwAAAQACgBqDAAAAwAQAGwMAAADABUAbQwAAAEABQDqDAAABAAJAG4MAAAEAAYAbwwAAAEACQARAAkJtgTOggBYAQloDAAAAgAMAGkMAAACABQAawwAAAIACgBqDAAAAgAQAGwMAAACABUAbQwAAAEABQDqDAAAAwAJAG4MAAADAAYAbwwAAAEACQAhAAcJCgJmCADiAAdoDAAAAwAEAGkMAAACAAYAawwAAAIABwBqDAAAAQAIAGwMAAABAAcA6gwAAAEABABuDAAAAQABAAAA.Mooeck:BAAALgAECgEJAQAAAA==.Mordakka:BAAALgAFFAEJAQABLgAFFAMJDwASAOkRAA==.Morghella:BAABLgAECn85AAIMAAkJbh58EACmAgloDAAABwBRAGkMAAAIAFQAawwAAAgAVwBqDAAACABFAGwMAAAIAD0AbQwAAAUAUgDqDAAABgBXAG4MAAAEAEgAbwwAAAMAQgAMAAkJbh58EACmAgloDAAABwBRAGkMAAAIAFQAawwAAAgAVwBqDAAACABFAGwMAAAIAD0AbQwAAAUAUgDqDAAABgBXAG4MAAAEAEgAbwwAAAMAQgAAAA==.Morticiaa:BAAALgAECgEJAQAAAA==.Mortician:BAAALgADCgcJBwAAAA==.Mourningwood:BAAALgADCggJCAAAAA==.Moána:BAAALgADCgQJBAAAAA==.',
My='Mynadshealu:BAAALgADCgUJCgAAAA==.Mythros:BAAALgAECgcJBwAAAA==.Mythweaver:BAAALgADCgYJBQAAAA==.',
Na='Nasman:BAAALgADCggJCwAAAA==.',
Ne='Needswowaa:BAAALgAECgcJDgAAAA==.Nesmae:BAAALgAECggJEQABLgAFFAQJCgAMAP4aAA==.',
Ni='Nightwitch:BAAALgAECgMJBAAAAA==.Ninjetta:BAAALgADCgEJAQAAAA==.',
No='Noirra:BAACLgAFFH8KAAIMAAQJ/hpKIgBEAQRoDAAABABYAGkMAAAEAFUAawwAAAEAHwDqDAAAAQBGAAwABAn+GkoiAEQBBGgMAAAEAFgAaQwAAAQAVQBrDAAAAQAfAOoMAAABAEYALgAECn8wAAIMAAkJHCN8DADcAgAMAAkJHCN8DADcAgAAAA==.Nokzul:BAAALgADCgYJCQAAAA==.Noobtube:BAAALgADCgUJCQAAAA==.Nosferatuss:BAAALgADCgIJAgAAAA==.Novajiin:BAAALgADCgQJBQAAAA==.Noxxival:BAAALgAECgEJAQAAAA==.',
Ny='Nyakalii:BAAALgAECggJDQAAAA==.Nyxiana:BAAALgADCgYJCgAAAA==.',
Oc='Ocktuupas:BAAALgAECgYJCgAAAA==.',
Ol='Oleyinka:BAAALgAECgcJDgAAAA==.',
Om='Omnissiah:BAABLgAECn8sAAIdAAgJhRWxGADiAQhoDAAACABIAGkMAAAIAEAAawwAAAcARgBqDAAABQA/AGwMAAAFAFAAbQwAAAEAEADqDAAABwA2AG4MAAADABIAHQAICYUVsRgA4gEIaAwAAAgASABpDAAACABAAGsMAAAHAEYAagwAAAUAPwBsDAAABQBQAG0MAAABABAA6gwAAAcANgBuDAAAAwASAAAA.',
On='Once:BAAALgAECgcJEwAAAA==.Oneyedemon:BAAALgADCggJCQAAAA==.Oneyeshoter:BAAALgADCgEJAQABLgAECgYJFwAMABwIAA==.',
Op='Opaths:BAABLgAECn8nAAMPAAgJJiEvGQCQAghoDAAABgBSAGkMAAAFAFAAawwAAAUAVgBqDAAABAA2AGwMAAAEAFUAbQwAAAEASADqDAAACABZAG4MAAAGAGEADwAICSYhLxkAkAIIaAwAAAYAUgBpDAAABQBQAGsMAAAFAFYAagwAAAQANgBsDAAABABVAG0MAAABAEgA6gwAAAgAWQBuDAAABQBhACIAAQlyDfcqADUAAW4MAAABACIAAAA=.',
Or='Orcnick:BAAALgADCgYJBgAAAA==.',
Ov='Overfrosty:BAABLgAECn8kAAIIAAgJkSFTBACWAghoDAAABwBeAGkMAAAGAFoAawwAAAUAUABqDAAABABeAGwMAAAEAFUAbQwAAAIATQDqDAAABgBWAG4MAAACAFYACAAICZEhUwQAlgIIaAwAAAcAXgBpDAAABgBaAGsMAAAFAFAAagwAAAQAXgBsDAAABABVAG0MAAACAE0A6gwAAAYAVgBuDAAAAgBWAAAA.',
Pe='Peng:BAABLgAECn8UAAQjAAgJhg5HIwDvAAhoDAAAAgAuAGkMAAADABgAawwAAAUALABqDAAAAgAlAGwMAAACADcAbQwAAAIAKgDqDAAAAgARAG4MAAACAB0AIwAHCQsPRyMA7wAHaAwAAAIALgBpDAAAAwAYAGsMAAAFACwAagwAAAIAJQBsDAAAAgA3AG0MAAACACoA6gwAAAIAEQAkAAEJYwtnYQAxAAFuDAAAAQAdABsAAQmFAiWZACEAAW4MAAABAAYAAAA=.',
Po='Popedope:BAAALgAECgUJDAABLgAFFAMJBgAGADkTAA==.Potatospud:BAAALgADCgIJAwAAAA==.',
Pr='Priedorei:BAAALgADCgIJAgAAAA==.Prodagy:BAAALgADCgYJBgAAAA==.Prìde:BAAALgAECgcJBwAAAA==.',
Ps='Psyberollin:BAAALgAECgcJBwABLgAECgkJBgAKAAAAAA==.',
Pu='Punishedbill:BAAALgAECgYJBgAAAA==.Purgedfire:BAAALgAECgEJAgAAAA==.',
Pv='Pvp:BAABLgAECn8UAAIGAAgJ1hJ1IwDGAQhoDAAAAgA2AGkMAAACAE4AawwAAAIAMgBqDAAAAwBLAGwMAAADAB8AbQwAAAIAEQDqDAAAAwAxAG4MAAADABwABgAICdYSdSMAxgEIaAwAAAIANgBpDAAAAgBOAGsMAAACADIAagwAAAMASwBsDAAAAwAfAG0MAAACABEA6gwAAAMAMQBuDAAAAwAcAAAA.',
Ra='Raal:BAAALgAECgIJAwAAAA==.Rahtas:BAAALgADCgYJCQAAAA==.Rangi:BAAALgAECgYJDAAAAA==.Ransus:BAAALgAECgEJAQAAAA==.Ratings:BAABLgAECn8XAAMfAAgJmiN0BQApAwhoDAAAAwBgAGkMAAADAGAAawwAAAMAYQBqDAAAAwBcAGwMAAADAFgAbQwAAAMASwDqDAAABABfAG4MAAABAFYAHwAICZojdAUAKQMIaAwAAAMAYABpDAAAAgBgAGsMAAACAGEAagwAAAMAXABsDAAAAwBYAG0MAAADAEsA6gwAAAQAXwBuDAAAAQBWABoAAgnTBUV3AEEAAmkMAAABAAsAawwAAAEAEgAAAA==.Ravon:BAAALgADCgcJDAAAAA==.Rayda:BAABLgAECn8lAAIGAAkJPhlQFABJAgloDAAABwBSAGkMAAAFAEEAawwAAAYATgBqDAAAAwBaAGwMAAAEAF4AbQwAAAIARgDqDAAABgBBAG4MAAADABgAbwwAAAEACQAGAAkJPhlQFABJAgloDAAABwBSAGkMAAAFAEEAawwAAAYATgBqDAAAAwBaAGwMAAAEAF4AbQwAAAIARgDqDAAABgBBAG4MAAADABgAbwwAAAEACQAAAA==.Raydoink:BAAALgAECgYJBgAAAA==.',
Re='Reighan:BAAALgADCgUJBwAAAA==.Remiel:BAAALgAECgEJAQAAAA==.Renka:BAAALgAECgQJCAAAAA==.Revolting:BAABLgAFFH8SAAIDAAUJgQ4BOQAVAQVoDAAABAArAGkMAAAEABoAawwAAAMAHwBqDAAAAgAiAOoMAAAFAC8AAwAFCYEOATkAFQEFaAwAAAQAKwBpDAAABAAaAGsMAAADAB8AagwAAAIAIgDqDAAABQAvAAAA.Reze:BAAALgAECgEJAQABLgAFFAMJAwAKAAAAAA==.Rezme:BAAALgADCgkJFAAAAA==.',
Rh='Rhaeny:BAAALgADCgEJAQAAAA==.',
Ri='Rianne:BAAALgAECgUJCwAAAA==.Rizeen:BAAALgAECgYJEAAAAA==.',
Ro='Rowanbow:BAAALgAECgQJDAAAAA==.',
Ru='Rumi:BAAALgADCgcJBwAAAA==.',
['Ré']='Rédd:BAABLgAECn8zAAMFAAkJ8RqBDwC7AgloDAAACABYAGkMAAAHAFsAawwAAAcAUgBqDAAABwBBAGwMAAAFAEUAbQwAAAMALgDqDAAACABAAG4MAAAFAEgAbwwAAAEAJwAFAAkJ8RqBDwC7AgloDAAACABYAGkMAAAGAFsAawwAAAYAUgBqDAAABQBBAGwMAAAEAEUAbQwAAAMALgDqDAAACABAAG4MAAAEAEgAbwwAAAEAJwAEAAUJsAcPVwCGAAVpDAAAAQAAAGsMAAABACgAagwAAAIAHgBsDAAAAQAMAG4MAAABABoAAAA=.',
Sa='Saberhawk:BAABLgAECn8UAAIMAAcJWQ7wYQBXAQdoDAAAAwAvAGkMAAADABcAawwAAAMAKgBqDAAAAwAtAGwMAAACABgA6gwAAAUANgBuDAAAAQAaAAwABwlZDvBhAFcBB2gMAAADAC8AaQwAAAMAFwBrDAAAAwAqAGoMAAADAC0AbAwAAAIAGADqDAAABQA2AG4MAAABABoAAAA=.Sadness:BAAALgADCgEJAgAAAA==.Safaera:BAAALgAECgQJBQAAAA==.Sakurazuka:BAABLgAECn8lAAIBAAcJxhBCZQBgAQdoDAAACAAqAGkMAAAHAEEAawwAAAcAIwBqDAAABAA9AGwMAAAEADAAbQwAAAIAGADqDAAABQApAAEABwnGEEJlAGABB2gMAAAIACoAaQwAAAcAQQBrDAAABwAjAGoMAAAEAD0AbAwAAAQAMABtDAAAAgAYAOoMAAAFACkAAAA=.Salaminizer:BAAALgAECgEJBAAAAA==.Samidudu:BAABLgAECn8YAAIZAAcJSRVQGQBJAQdoDAAABQBGAGkMAAAFAD0AawwAAAMANABqDAAAAwAtAGwMAAADADIAbQwAAAIAEQDqDAAAAwBJABkABwlJFVAZAEkBB2gMAAAFAEYAaQwAAAUAPQBrDAAAAwA0AGoMAAADAC0AbAwAAAMAMgBtDAAAAgARAOoMAAADAEkAAAA=.Sanath:BAABLgAECn8kAAIVAAkJwQ5mJACaAQloDAAABQAqAGkMAAAFACwAawwAAAUALQBqDAAABQAnAGwMAAAFAB0AbQwAAAIALwDqDAAABAAiAG4MAAAEACgAbwwAAAEAEQAVAAkJwQ5mJACaAQloDAAABQAqAGkMAAAFACwAawwAAAUALQBqDAAABQAnAGwMAAAFAB0AbQwAAAIALwDqDAAABAAiAG4MAAAEACgAbwwAAAEAEQAAAA==.Sanctusdeus:BAAALgAFFAEJAQAAAA==.Sandbag:BAAALgAECgMJAwAAAA==.Sardenn:BAAALgAECgEJAQABLgAECgkJNAANAJgXAA==.Sarelyn:BAAALgADCgEJAQAAAA==.',
Sc='Scarydream:BAABLgAECn8dAAIEAAcJdiRQHwAFAgdoDAAAAwBfAGkMAAAEAF8AawwAAAIAXABqDAAABQBhAGwMAAAGAF0A6gwAAAgAYwBuDAAAAQBTAAQABwl2JFAfAAUCB2gMAAADAF8AaQwAAAQAXwBrDAAAAgBcAGoMAAAFAGEAbAwAAAYAXQDqDAAACABjAG4MAAABAFMAAAA=.Scoobyxdooby:BAAALgADCgUJBQAAAA==.Scottcooney:BAABLgAECn8oAAITAAgJJyJgAwCtAghoDAAABwBZAGkMAAAHAFoAawwAAAYAXABqDAAABQBTAGwMAAAFAFYAbQwAAAIAUQDqDAAABgBcAG4MAAACAE4AEwAICSciYAMArQIIaAwAAAcAWQBpDAAABwBaAGsMAAAGAFwAagwAAAUAUwBsDAAABQBWAG0MAAACAFEA6gwAAAYAXABuDAAAAgBOAAAA.',
Se='Secondiceage:BAAALgADCgMJAwAAAA==.Serge:BAAALgAECgEJAQABLgAFFAMJDwASAOkRAA==.Sevotharte:BAAALgAECgIJAgAAAA==.',
Sg='Sgtmoose:BAAALgADCgYJBgAAAA==.',
Sh='Shadobread:BAAALgAECgcJEwAAAA==.Shadowglider:BAAALgAECgQJBgAAAA==.Shammhammer:BAAALgADCgEJAQAAAA==.Shaoxing:BAAALgAECgEJAQAAAA==.Sharindlar:BAACLgAFFH8SAAIJAAMJayT8IAAvAQNoDAAABQBVAGkMAAAFAGAA6gwAAAgAYQAJAAMJayT8IAAvAQNoDAAABQBVAGkMAAAFAGAA6gwAAAgAYQAuAAQKfyYAAgkACQnRJD0BAK4DAAkACQnRJD0BAK4DAAAA.Shmastus:BAAALgADCgUJBQAAAA==.Shockandrawr:BAAALgAECgYJCgAAAA==.Shokanu:BAABLgAECn8eAAIeAAkJHRkvBwA5AgloDAAABQBNAGkMAAAFAEgAawwAAAUARQBqDAAAAwA3AGwMAAADAEYAbQwAAAIAPADqDAAAAwBOAG4MAAADACwAbwwAAAEAKQAeAAkJHRkvBwA5AgloDAAABQBNAGkMAAAFAEgAawwAAAUARQBqDAAAAwA3AGwMAAADAEYAbQwAAAIAPADqDAAAAwBOAG4MAAADACwAbwwAAAEAKQAAAA==.',
Si='Sib:BAAALgAECgEJAgAAAA==.Silkysmooth:BAAALgADCgMJBgAAAA==.Sissyo:BAAALgADCgYJDQAAAA==.',
Sk='Skeets:BAAALgADCgcJDwAAAA==.Skeëts:BAAALgADCgUJBgAAAA==.',
Sl='Sliceschmax:BAAALgAECgQJCwAAAA==.',
Sn='Snakie:BAABLgAECn8dAAIHAAgJmBfgQQDkAQhoDAAABgBOAGkMAAAFAEwAawwAAAUALQBqDAAAAwBaAGwMAAAEADIAbQwAAAEAOwDqDAAABABGAG4MAAABACkABwAICZgX4EEA5AEIaAwAAAYATgBpDAAABQBMAGsMAAAFAC0AagwAAAMAWgBsDAAABAAyAG0MAAABADsA6gwAAAQARgBuDAAAAQApAAAA.Snke:BAAALgADCgcJBwABLgAECggJHQAHAJgXAA==.',
So='Sofieeus:BAAALgADCgcJCQAAAA==.Sokorag:BAABLgAECn8tAAIPAAkJvR+tHgDJAgloDAAABwBiAGkMAAAFAFsAawwAAAcAXABqDAAABQBOAGwMAAAFAFUAbQwAAAIASwDqDAAABwBYAG4MAAAFAFEAbwwAAAIAIgAPAAkJvR+tHgDJAgloDAAABwBiAGkMAAAFAFsAawwAAAcAXABqDAAABQBOAGwMAAAFAFUAbQwAAAIASwDqDAAABwBYAG4MAAAFAFEAbwwAAAIAIgAAAA==.Sonofgods:BAABLgAECn8YAAIMAAYJ5REhegAfAQZoDAAABABHAGkMAAAEACcAawwAAAQAJABqDAAAAwBMAGwMAAAEACUA6gwAAAUALAAMAAYJ5REhegAfAQZoDAAABABHAGkMAAAEACcAawwAAAQAJABqDAAAAwBMAGwMAAAEACUA6gwAAAUALAAAAA==.Soulscape:BAAALgADCgkJJAAAAA==.Soulsnack:BAAALgAECgEJAgABLgAECgYJGwADACAOAA==.',
Sp='Spectrahl:BAABLgAECn8mAAIOAAgJQRJ0KQB7AQhoDAAABQA2AGkMAAAFADEAawwAAAYAIgBqDAAABQArAGwMAAAFAFIAbQwAAAMAJwDqDAAABgAmAG4MAAADABwADgAICUESdCkAewEIaAwAAAUANgBpDAAABQAxAGsMAAAGACIAagwAAAUAKwBsDAAABQBSAG0MAAADACcA6gwAAAYAJgBuDAAAAwAcAAEuAAUUBAkKAAwA/hoA.Spedspidspud:BAAALgAECgcJEwAAAA==.Spooky:BAAALgAECgEJAQAAAA==.Spoone:BAAALgAECgEJAgAAAA==.Sprinkler:BAAALgAECgUJBQAAAA==.',
Sq='Squee:BAAALgADCgEJAQABLgAECgkJLAASAE0QAA==.',
St='Starrbuck:BAABLgAECn8nAAMFAAgJ+weebADQAAhoDAAABwAVAGkMAAAHABIAawwAAAYADwBqDAAABQASAGwMAAAFAAgAbQwAAAIABgDqDAAABgANAG4MAAABADwABQAHCcMFnmwA0AAHaAwAAAcAFQBpDAAABwASAGsMAAAGAA8AagwAAAUAEgBsDAAABQAIAG0MAAACAAYA6gwAAAYADQAEAAEJrwLfjAAZAAFuDAAAAQAGAAAA.Stephii:BAAALgADCgYJBgAAAA==.Strongarrow:BAABLgAECn8YAAINAAgJfRL7GQCxAQhoDAAAAwBQAGkMAAAEACkAawwAAAQAKABqDAAAAwBIAGwMAAAEADoAbQwAAAEAFADqDAAAAwBCAG4MAAACABYADQAICX0S+xkAsQEIaAwAAAMAUABpDAAABAApAGsMAAAEACgAagwAAAMASABsDAAABAA6AG0MAAABABQA6gwAAAMAQgBuDAAAAgAWAAAA.Stryke:BAABLgAECn8cAAIdAAcJYRgEGgDUAQdoDAAABgBQAGkMAAAFAE0AawwAAAUAOQBqDAAAAwBEAGwMAAACADMAbQwAAAEAIADqDAAABgBDAB0ABwlhGAQaANQBB2gMAAAGAFAAaQwAAAUATQBrDAAABQA5AGoMAAADAEQAbAwAAAIAMwBtDAAAAQAgAOoMAAAGAEMAAAA=.',
Su='Sunfury:BAAALgAECgQJBQAAAA==.Supersack:BAAALgADCgIJAgAAAA==.Sushii:BAAALgAECgMJBQAAAA==.Suterareta:BAABLgAECn8dAAMlAAgJ6RNzDABmAQhoDAAABgBKAGkMAAAFAD4AawwAAAUAOQBqDAAAAwAyAGwMAAACABMAbQwAAAIANQDqDAAABQAqAG4MAAABAC4AJQAICbAQcwwAZgEIaAwAAAQANgBpDAAABAAwAGsMAAADADkAagwAAAIAMgBsDAAAAgATAG0MAAABACAA6gwAAAQAKQBuDAAAAQAuABgABglvFY8/AP0ABmgMAAACAEoAaQwAAAEAPgBrDAAAAgAoAGoMAAABACQAbQwAAAEANQDqDAAAAQAqAAAA.',
Sy='Sylareith:BAAALgAECgYJDgAAAA==.Syntara:BAABLgAECn81AAITAAkJPCDCAgDHAgloDAAABwBXAGkMAAAHAGEAawwAAAcAXgBqDAAABwBIAGwMAAAHAFMAbQwAAAUAVADqDAAABgBNAG4MAAAEAE8AbwwAAAMAOAATAAkJPCDCAgDHAgloDAAABwBXAGkMAAAHAGEAawwAAAcAXgBqDAAABwBIAGwMAAAHAFMAbQwAAAUAVADqDAAABgBNAG4MAAAEAE8AbwwAAAMAOAAAAA==.',
['Sí']='Síelys:BAAALgAECgYJCgAAAA==.',
Ta='Taggalongg:BAAALgADCgYJBgAAAA==.Taksun:BAABLgAECn8vAAIZAAgJkBmZDADhAQhoDAAACABKAGkMAAAHAEkAawwAAAYAQwBqDAAABgAzAGwMAAAGAEQAbQwAAAMANQDqDAAACABCAG4MAAADADYAGQAICZAZmQwA4QEIaAwAAAgASgBpDAAABwBJAGsMAAAGAEMAagwAAAYAMwBsDAAABgBEAG0MAAADADUA6gwAAAgAQgBuDAAAAwA2AAAA.Tankque:BAAALgAECgEJAQAAAA==.Tauntindeath:BAABLgAECn80AAIQAAkJzg0RGgBgAQloDAAACAAbAGkMAAAHADQAawwAAAYALQBqDAAABgA1AGwMAAAGAD4AbQwAAAMAFQDqDAAABwAVAG4MAAAGABMAbwwAAAMAHwAQAAkJzg0RGgBgAQloDAAACAAbAGkMAAAHADQAawwAAAYALQBqDAAABgA1AGwMAAAGAD4AbQwAAAMAFQDqDAAABwAVAG4MAAAGABMAbwwAAAMAHwAAAA==.Tav:BAABLgAFFH8HAAMkAAMJaxhBGgDRAANoDAAAAwBPAGkMAAADADgA6gwAAAEAMwAkAAMJahBBGgDRAANoDAAAAQAsAGkMAAACAB4A6gwAAAEAMwAjAAIJnxq6GgCVAAJoDAAAAgBPAGkMAAABADgAAAA=.',
Th='Thaia:BAAALgADCgEJAQAAAA==.Thaladrin:BAABLgAECn8bAAMIAAcJpSM9BwBCAgdoDAAABwBUAGkMAAAFAGEAawwAAAUAVABqDAAAAwBgAGwMAAACAFsAbQwAAAEAYQDqDAAABABcAAgABwmlIz0HAEICB2gMAAAFAFQAaQwAAAQAYQBrDAAABABUAGoMAAACAGAAbAwAAAIAWwBtDAAAAQBhAOoMAAADAFwABwAFCTwR+LoA7gAFaAwAAAIAQQBpDAAAAQApAGsMAAABACYAagwAAAEAUADqDAAAAQAfAAAA.Thalard:BAAALgADCgEJAQAAAA==.Thawnos:BAAALgADCggJCgAAAA==.Thewarwithin:BAAALgADCggJCAAAAA==.',
Ti='Tianara:BAACLgAFFH8GAAMGAAMJORNAJADUAANoDAAAAwAoAGkMAAABAE8A6gwAAAIAGwAGAAMJORNAJADUAANoDAAAAQAoAGkMAAABAE8A6gwAAAEAGwAHAAIJtRmfZACmAAJoDAAAAgAyAOoMAAABAFEALgAECn8XAAMGAAgJjSHyBAAdAwAGAAgJjSHyBAAdAwAIAAQJPhVsKgC4AAAAAA==.Titania:BAAALgADCgQJBAAAAA==.',
Tj='Tjismyname:BAAALgAECgYJDwAAAA==.',
To='Toasteon:BAAALgADCgYJBwAAAA==.Todesbär:BAAALgADCgcJCwAAAA==.Tok:BAAALgAECgMJBAAAAA==.Tokens:BAAALgAECgEJAQAAAA==.Tolerabull:BAABLgAECn8qAAQGAAgJtR0jFgA3AghoDAAABwBJAGkMAAAHAEEAawwAAAcAWgBqDAAABgBAAGwMAAAFAFEAbQwAAAIARQDqDAAABgBLAG4MAAACAFcABgAHCQwdIxYANwIHaAwAAAYASQBpDAAABgBBAGsMAAAGAFoAagwAAAYAQABsDAAABABRAG0MAAABAEUA6gwAAAUASwAIAAYJjwh0IgDTAAZoDAAAAQAMAGkMAAABABYAawwAAAEAIQBsDAAAAQAVAG0MAAABAB4A6gwAAAEACwAHAAEJng2RXAE1AAFuDAAAAgAiAAAA.',
Tr='Tralynna:BAAALgADCgIJAwAAAA==.Trixxe:BAABLgAECn8yAAIDAAkJWBoAHgBFAgloDAAACABLAGkMAAAHAEUAawwAAAcARgBqDAAABwBHAGwMAAAGADYAbQwAAAQAQgDqDAAABwBGAG4MAAADADsAbwwAAAEASAADAAkJWBoAHgBFAgloDAAACABLAGkMAAAHAEUAawwAAAcARgBqDAAABwBHAGwMAAAGADYAbQwAAAQAQgDqDAAABwBGAG4MAAADADsAbwwAAAEASAAAAA==.Trojaan:BAABLgAECn8VAAIbAAkJMgVhUQDdAAloDAAAAgAeAGkMAAACAB8AawwAAAMADABqDAAAAwAOAGwMAAADABIAbQwAAAMAAQDqDAAAAwAFAG4MAAABAAEAbwwAAAEABQAbAAkJMgVhUQDdAAloDAAAAgAeAGkMAAACAB8AawwAAAMADABqDAAAAwAOAGwMAAADABIAbQwAAAMAAQDqDAAAAwAFAG4MAAABAAEAbwwAAAEABQAAAA==.Trulisha:BAAALgAECgYJEAAAAA==.',
Tw='Twolip:BAAALgAECgMJBwAAAA==.',
Ty='Tyleinthrel:BAAALgAECgIJAgAAAA==.',
Ue='Uelfaen:BAAALgADCgYJBwAAAA==.',
Un='Undolf:BAAALgADCgMJAwAAAA==.',
Uo='Uog:BAAALgADCgIJAgAAAA==.',
Ur='Urgott:BAABLgAECn8kAAIQAAkJkQbXIwAJAQloDAAABAAdAGkMAAAEABcAawwAAAQAEwBqDAAABQAIAGwMAAAFAA8AbQwAAAMADgDqDAAABQAQAG4MAAAEAAsAbwwAAAIABAAQAAkJkQbXIwAJAQloDAAABAAdAGkMAAAEABcAawwAAAQAEwBqDAAABQAIAGwMAAAFAA8AbQwAAAMADgDqDAAABQAQAG4MAAAEAAsAbwwAAAIABAAAAA==.Urmaria:BAAALgAECgYJBgAAAA==.Ursalaisis:BAAALgAECgcJEwAAAA==.',
Va='Vaderon:BAAALgAECgYJCgAAAA==.Vaelanar:BAAALgAECgYJBgAAAA==.Vajaina:BAAALgADCgEJAQAAAA==.Valalerie:BAAALgADCgYJBgAAAA==.Valentyn:BAAALgAECgEJAgAAAA==.Vayine:BAACLgAFFH8QAAIIAAQJfwcPCQC5AARoDAAABgAbAGkMAAAFAAcAawwAAAIACwDqDAAAAwAeAAgABAl/Bw8JALkABGgMAAAGABsAaQwAAAUABwBrDAAAAgALAOoMAAADAB4ALgAECn8rAAIIAAkJMRSiFQB2AQAIAAkJMRSiFQB2AQAAAA==.Vaynitee:BAAALgADCgcJDQAAAA==.',
Ve='Venmo:BAAALgAECgYJCAABLgAECggJJAAQAGIWAA==.Veridesh:BAAALgAECgcJCwABLgAFFAMJDwASAOkRAA==.',
Vi='Vinceoffer:BAAALgADCgkJDAAAAA==.Visenya:BAAALgAECgcJDAAAAA==.Vitrovius:BAAALgAECgEJAQAAAA==.',
Vo='Voidset:BAAALgADCgMJAwAAAA==.Voladus:BAAALgAECgYJBgABLgAECgkJLwAJAOwkAA==.Volaire:BAAALgAECgMJBAAAAA==.',
Vu='Vuskar:BAABLgAECn8gAAIQAAkJQhM0EwCxAQloDAAABQAvAGkMAAAEAEwAawwAAAQASQBqDAAABAA6AGwMAAAFAB4AbQwAAAEALQDqDAAABgBPAG4MAAACABwAbwwAAAEACwAQAAkJQhM0EwCxAQloDAAABQAvAGkMAAAEAEwAawwAAAQASQBqDAAABAA6AGwMAAAFAB4AbQwAAAEALQDqDAAABgBPAG4MAAACABwAbwwAAAEACwAAAA==.',
Vy='Vynlash:BAAALgADCgMJAQAAAA==.',
['Vì']='Vìcious:BAABLgAECn8tAAMMAAgJNxVDOgDMAQhoDAAACQBCAGkMAAAIACwAawwAAAgAPABqDAAABgBaAGwMAAADAEYAbQwAAAIAHADqDAAABwBEAG4MAAACACkADAAICTcVQzoAzAEIaAwAAAcAQgBpDAAABgAsAGsMAAAGADwAagwAAAQAWgBsDAAAAgBGAG0MAAACABwA6gwAAAYARABuDAAAAgApAA0ABglFDwkoAD8BBmgMAAACACoAaQwAAAIAIwBrDAAAAgAgAGoMAAACAAkAbAwAAAEALADqDAAAAQAnAAAA.',
Wa='Wangwingwong:BAAALgADCgMJAwABLgAECgcJEwAKAAAAAA==.',
Wh='Whozyerdaddy:BAAALgADCgMJAwAAAA==.',
Wi='Wicks:BAAALgAECgYJBgAAAA==.Wigglyears:BAABLgAECn8sAAMSAAkJTRD/HAC5AQloDAAABwAsAGkMAAAFACoAawwAAAUAIABqDAAABQAtAGwMAAAFAEIAbQwAAAMAFgDqDAAABwAtAG4MAAAEADIAbwwAAAMAHgASAAkJTRD/HAC5AQloDAAABAAsAGkMAAADACoAawwAAAMAIABqDAAABAAtAGwMAAAFAEIAbQwAAAIAFgDqDAAABAAtAG4MAAADADIAbwwAAAMAHgAcAAcJwQ8iKQBOAQdoDAAAAwBDAGkMAAACAEMAawwAAAIAIABqDAAAAQAnAG0MAAABAAgA6gwAAAMAOABuDAAAAQAKAAAA.Wildberd:BAAALgADCgEJAQAAAA==.Winwings:BAAALgADCgQJBwAAAA==.',
Ws='Wselfwulf:BAAALgAECgUJDwABLgAECgcJGwAIAKUjAA==.',
Xa='Xanadaria:BAAALgAECgUJCgABLgAECgkJCAAKAAAAAA==.Xanalluna:BAAALgAECgIJAgABLgAECgkJCAAKAAAAAA==.Xandrelyra:BAAALgADCgMJAwABLgAECgkJCAAKAAAAAA==.Xanvarani:BAAALgAECgkJCAAAAA==.',
Xe='Xeriirado:BAAALgAECgcJBwAAAA==.Xeril:BAAALgAECgQJBAAAAA==.',
Xx='Xxluminati:BAAALgADCgMJAwAAAA==.',
Ya='Yagermeister:BAAALgADCgcJBwABLgAECgQJCAAKAAAAAA==.Yakushimaru:BAABLgAECn8yAAIEAAkJmiCGBQDmAgloDAAACQBfAGkMAAAIAFoAawwAAAYAXQBqDAAABQBVAGwMAAAGAEgAbQwAAAMASADqDAAABwBbAG4MAAAFAEQAbwwAAAEAUQAEAAkJmiCGBQDmAgloDAAACQBfAGkMAAAIAFoAawwAAAYAXQBqDAAABQBVAGwMAAAGAEgAbQwAAAMASADqDAAABwBbAG4MAAAFAEQAbwwAAAEAUQAAAA==.Yasil:BAAALgADCgIJAgAAAA==.',
Yi='Yishan:BAAALgAECgMJBQAAAA==.',
Yo='Yos:BAAALgAECgEJAQAAAA==.',
Yu='Yuengling:BAAALgADCgEJAQAAAA==.Yuk:BAAALgAECgIJAwAAAA==.',
Za='Zaare:BAAALgAECgEJAQAAAA==.',
Ze='Zefren:BAABLgAFFH8HAAIHAAMJOhILUADmAANoDAAAAwAwAGkMAAABABcA6gwAAAMARAAHAAMJOhILUADmAANoDAAAAwAwAGkMAAABABcA6gwAAAMARAAAAA==.Zeith:BAABLgAECn8mAAIjAAkJXRaCDAD/AQloDAAABAAZAGkMAAAFAEwAawwAAAUATgBqDAAABABAAGwMAAAFADUAbQwAAAMALADqDAAABgBAAG4MAAAEACkAbwwAAAIASQAjAAkJXRaCDAD/AQloDAAABAAZAGkMAAAFAEwAawwAAAUATgBqDAAABABAAGwMAAAFADUAbQwAAAMALADqDAAABgBAAG4MAAAEACkAbwwAAAIASQAAAA==.Zev:BAAALgAECgIJAgAAAA==.',
Zh='Zhe:BAAALgADCgYJBgAAAA==.',
Zi='Zildon:BAAALgAECgYJCwAAAA==.',
Zu='Zurik:BAACLgAFFH8KAAIeAAQJQh7TAgB3AQRoDAAABABUAGkMAAADAFQAawwAAAEATgDqDAAAAgA+AB4ABAlCHtMCAHcBBGgMAAAEAFQAaQwAAAMAVABrDAAAAQBOAOoMAAACAD4ALgAECn8sAAIeAAkJCiA0AgDvAgAeAAkJCiA0AgDvAgAAAA==.',
Zy='Zyphoros:BAAALgADCgkJCwAAAA==.',
['Äz']='Äzúlà:BAAALgAECgMJBQAAAA==.',
['Ça']='Çaptainçhaos:BAAALgADCgMJAwAAAA==.',
['Ér']='Érodar:BAABLgAECn8UAAIHAAcJ9weBqwAGAQdoDAAABAAXAGkMAAAEABUAawwAAAMAGgBqDAAAAgAgAGwMAAACAAsA6gwAAAMAFABuDAAAAgASAAcABwn3B4GrAAYBB2gMAAAEABcAaQwAAAQAFQBrDAAAAwAaAGoMAAACACAAbAwAAAIACwDqDAAAAwAUAG4MAAACABIAAAA=.',
['Ìt']='Ìta:BAAALgAECgEJAQAAAA==.',
['Ðe']='Ðeadlymyth:BAAALgAECgQJBAAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
