local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Warrior-Arms','Evoker-Augmentation','Evoker-Devastation','Evoker-Preservation','Paladin-Protection','Paladin-Retribution','Monk-Mistweaver','Monk-Brewmaster','Monk-Windwalker','Warlock-Affliction','Warlock-Demonology','Unknown-Unknown','Mage-Frost','Druid-Guardian','Hunter-Survival','Hunter-BeastMastery','Hunter-Marksmanship','DeathKnight-Unholy','Paladin-Holy','Druid-Restoration','Druid-Balance','Shaman-Restoration','DemonHunter-Devourer','Priest-Holy','Priest-Discipline','Priest-Shadow','Warlock-Destruction','Warrior-Fury','Warrior-Protection','Rogue-Subtlety','DeathKnight-Frost','DeathKnight-Blood','Shaman-Enhancement','DemonHunter-Vengeance',}
local provider = {region='US',realm='TheUnderbog',name='US',type='daily',zone=46,date='2026-06-23',data={Ab='Abeteon:BAAALgAECgEJAQAAAA==.',
Ac='Acinovanth:BAAALgAECgEJAQAAAA==.Acousticjeff:BAAALgAECgYJBgAAAA==.',
Ad='Adwill:BAABLgAECn8vAAIBAAgJ6B8VCgBKAghoDAAACABYAGkMAAAHAFUAawwAAAcAVQBqDAAABwBVAGwMAAAGAFUAbQwAAAQARwDqDAAABwBSAG4MAAABAEgAAQAICegfFQoASgIIaAwAAAgAWABpDAAABwBVAGsMAAAHAFUAagwAAAcAVQBsDAAABgBVAG0MAAAEAEcA6gwAAAcAUgBuDAAAAQBIAAAA.',
Ae='Aelvoker:BAACLgAFFH8ZAAQCAAcJuhqLFwCtAQdoDAAABQBSAGkMAAAFAEAAawwAAAMAOQBqDAAAAwAzAGwMAAABAFEAbQwAAAEAHQDqDAAABwBfAAIABwmwFYsXAK0BB2gMAAADAFIAaQwAAAMAQABrDAAAAQAbAGoMAAACADMAbAwAAAEAUQBtDAAAAQAdAOoMAAABAC8AAwAECT4VDQQACQEEaAwAAAEAPwBpDAAAAQABAGsMAAACADkA6gwAAAUAXwAEAAQJ7gaBEwCQAARoDAAAAQAsAGkMAAABAAwAagwAAAEACwDqDAAAAQADAC4ABAp/FwAEAwAJCUUfUQcAdwIAAwAGCSQjUQcAdwIABAAHCZ0RiRoAtwEAAgACCd0a0UoAqQAAAAA=.',
Ai='Aindra:BAAALgAECggJEAAAAA==.Airen:BAAALgAECgYJDQAAAA==.',
An='Antidead:BAABLgAECn8gAAMFAAgJOR50BQCfAghoDAAABQBOAGkMAAAFAE8AawwAAAUARABqDAAABAA4AGwMAAAEAFIAbQwAAAIAUgDqDAAABQBSAG4MAAACAEMABQAICTkedAUAnwIIaAwAAAQATgBpDAAABABPAGsMAAAEAEQAagwAAAMAOABsDAAAAwBSAG0MAAABAFIA6gwAAAQAUgBuDAAAAQBDAAYACAnXEzR4AH4BCGgMAAABADoAaQwAAAEAKQBrDAAAAQA3AGoMAAABACoAbAwAAAEAMwBtDAAAAQAyAOoMAAABAC4AbgwAAAEANAAAAA==.',
Ap='Apachaler:BAABLgAECn8nAAQHAAkJ+xodEQCZAgloDAAACABSAGkMAAAGAF0AawwAAAUAUgBqDAAABABPAGwMAAAEAEQAbQwAAAEANgDqDAAABwBMAG4MAAADADgAbwwAAAEAGwAHAAkJ+xodEQCZAgloDAAABwBSAGkMAAAGAF0AawwAAAUAUgBqDAAABABPAGwMAAAEAEQAbQwAAAEANgDqDAAABwBMAG4MAAACADgAbwwAAAEAGwAIAAEJNhlAhQBCAAFoDAAAAQBAAAkAAQkiCTCkACwAAW4MAAABABcAAAA=.',
Ar='Arathael:BAAALgADCgIJAgAAAA==.Ardyce:BAAALgADCgIJAgAAAA==.Arrae:BAAALgAECgUJAwAAAA==.Arreuws:BAAALgAECgQJBAAAAA==.',
As='Asiansmoliv:BAACLgAFFH8VAAMKAAQJSB+IAwBeAQRoDAAACABWAGkMAAAEAFIAawwAAAEARADqDAAACABSAAoABAlIH4gDAF4BBGgMAAAEAFYAaQwAAAQAUgBrDAAAAQBEAOoMAAABAFIACwACCeceZTIArgACaAwAAAQAVQDqDAAABwBIAC4ABAp/NAADCgAJCSAlagAAUQMACgAJCSAlagAAUQMACwAFCbofJlUAnQEAAAA=.',
Az='Azriel:BAAALgADCgMJBAAAAA==.Azshan:BAAALgADCgQJBAABLgAECgQJCwAMAAAAAA==.',
Ba='Babymager:BAABLgAECn8iAAINAAcJ5QtPuQATAQdoDAAABwApAGkMAAAGACcAawwAAAUAIABqDAAAAwAqAGwMAAADABcA6gwAAAcAIQBuDAAAAwAMAA0ABwnlC0+5ABMBB2gMAAAHACkAaQwAAAYAJwBrDAAABQAgAGoMAAADACoAbAwAAAMAFwDqDAAABwAhAG4MAAADAAwAAAA=.Babyshamz:BAAALgAECgYJBgAAAA==.Barranphalnx:BAAALgAECgMJBQAAAA==.',
Bb='Bbldrizzy:BAAALgADCgEJAQAAAA==.',
Be='Beartwige:BAAALgADCgYJBgAAAA==.Beefydomo:BAAALgADCgIJAgABLgAECgEJAQAMAAAAAA==.Belladonnà:BAAALgAECgYJDQABLgAECggJIAAOACMRAA==.Betsy:BAAALgAECgQJBAAAAA==.',
Bh='Bhal:BAAALgAECgEJAQAAAA==.',
Bi='Bigpopapump:BAACLgAFFH8WAAIPAAQJxR0bDgBUAQRoDAAACABhAGkMAAAGAEYAawwAAAMAVADqDAAABQA0AA8ABAnFHRsOAFQBBGgMAAAIAGEAaQwAAAYARgBrDAAAAwBUAOoMAAAFADQALgAECn88AAIPAAkJ0SUUAQBgAwAPAAkJ0SUUAQBgAwAAAA==.Bishop:BAAALgADCgMJAwAAAA==.',
Bl='Blackgarden:BAAALgAECgYJDgAAAA==.Bloodhorde:BAAALgAECgEJAQAAAA==.Bloodydak:BAEALgAECgcJBwABLgAECgcJEAAMAAAAAA==.Bluchu:BAEALgAECgEJAQABLgAECgcJEAAMAAAAAA==.',
Bo='Bombasharna:BAAALgAECgIJBAAAAA==.Bonkzx:BAAALgADCgMJAwAAAA==.Booze:BAAALgAECgkJDwAAAA==.',
Br='Brigne:BAAALgADCgYJCwAAAA==.',
Bu='Buddeez:BAACLgAFFH8dAAINAAgJzB3bDwBtAghoDAAABwBjAGkMAAADAFEAawwAAAUAKgBqDAAAAwA5AGwMAAABAFkAbQwAAAEANwDqDAAACABZAG4MAAABAEsADQAICcwd2w8AbQIIaAwAAAcAYwBpDAAAAwBRAGsMAAAFACoAagwAAAMAOQBsDAAAAQBZAG0MAAABADcA6gwAAAgAWQBuDAAAAQBLAC4ABAp/KwACDQAJCT8lTQoAcQMADQAJCT8lTQoAcQMAAAA=.Buddiez:BAAALgADCgEJAQAAAA==.Built:BAABLgAECn8eAAQPAAkJ9CBYDAAJAgloDAAABQBfAGkMAAAFAF8AawwAAAUAWgBqDAAAAwA4AGwMAAADAFsAbQwAAAEATQDqDAAABQBZAG4MAAACADEAbwwAAAEAVAAPAAgJASFYDAAJAghoDAAABABfAGkMAAAEAF8AawwAAAUAWgBqDAAAAwA4AGwMAAADAFsA6gwAAAQAUwBuDAAAAgAxAG8MAAABAFQAEAADCUwYvn8A6AADaAwAAAEAEwBtDAAAAQBNAOoMAAABAFkAEQABCdoYaIEAQQABaQwAAAEAPwAAAA==.',
Ca='Cabbage:BAAALgADCgEJAQAAAA==.Carrot:BAAALgAECgIJAgAAAA==.',
Ce='Cenwen:BAACLgAFFH8VAAINAAQJYBorSwBKAQRoDAAABgBgAGkMAAAGAFIAawwAAAIAEwDqDAAABwBGAA0ABAlgGitLAEoBBGgMAAAGAGAAaQwAAAYAUgBrDAAAAgATAOoMAAAHAEYALgAECn8nAAINAAkJlR5qQgAUAgANAAkJlR5qQgAUAgAAAA==.',
Ch='Chaos:BAACLgAFFH8FAAIPAAMJhxpdHADuAANoDAAAAgBTAGkMAAABAEIA6gwAAAIANgAPAAMJhxpdHADuAANoDAAAAgBTAGkMAAABAEIA6gwAAAIANgAuAAQKf08AAg8ACQluJegAAGgDAA8ACQluJegAAGgDAAAA.Chonk:BAAALgAECgYJBgAAAA==.Chugginjizz:BAAALgAECgEJAQABLgAFFAgJJgASADEWAA==.',
Cl='Clawreece:BAAALgAECgQJCQAAAA==.',
Co='Conta:BAAALgAECgYJCQAAAA==.',
Cr='Cryingtears:BAABLgAECn8pAAQTAAgJ9A8eOgBiAQhoDAAACAA7AGkMAAAHAEAAawwAAAcAOwBqDAAABQArAGwMAAAEACEAbQwAAAEABADqDAAABQA2AG4MAAAEAAgAEwAICfQPHjoAYgEIaAwAAAYAOwBpDAAABQBAAGsMAAAFADsAagwAAAIAKwBsDAAAAgAhAG0MAAABAAQA6gwAAAMANgBuDAAAAgAIAAYABwmpBgjpANMAB2gMAAACABwAaQwAAAIAFABrDAAAAgARAGoMAAADABEAbAwAAAIADwDqDAAAAgAMAG4MAAABAAgABQABCQABPFsAGAABbgwAAAEAAgAAAA==.',
Cu='Cuchicu:BAABLgAECn9DAAMUAAkJLxytDwDVAgloDAAACwBcAGkMAAALAFsAawwAAAoAVgBqDAAABwBMAGwMAAAHAFIAbQwAAAUALQDqDAAADABXAG4MAAACACgAbwwAAAIALQAUAAkJLxytDwDVAgloDAAACgBcAGkMAAAKAFsAawwAAAkAVgBqDAAABwBMAGwMAAAHAFIAbQwAAAQALQDqDAAACgBXAG4MAAACACgAbwwAAAIALQAVAAUJEhJYOgApAQVoDAAAAQAqAGkMAAABADkAawwAAAEAIwBtDAAAAQAXAOoMAAACAEcAAAA=.',
Da='Dakkonix:BAEALgAECgcJEAAAAA==.Dakkonixx:BAEALgAECgUJBgABLgAECgcJEAAMAAAAAA==.Damagexx:BAAALgAECgMJBgAAAA==.Darkaged:BAAALgADCgYJBgAAAA==.Darklords:BAAALgAECgMJAwAAAA==.Daviid:BAAALgADCgYJBgAAAA==.',
De='Demigodd:BAAALgADCgIJAgAAAA==.Demonasa:BAAALgADCgIJAgAAAA==.Desim:BAABLgAECn8WAAISAAcJsx6EMwBoAgdoDAAABABcAGkMAAAEAFgAawwAAAQAVQBqDAAAAgBbAGwMAAACAEUA6gwAAAUAUwBuDAAAAQA0ABIABwmzHoQzAGgCB2gMAAAEAFwAaQwAAAQAWABrDAAABABVAGoMAAACAFsAbAwAAAIARQDqDAAABQBTAG4MAAABADQAAAA=.Dextt:BAABLgAECn8dAAIWAAcJLCIrDgCpAgdoDAAABQBcAGkMAAAFAGMAawwAAAUAYgBqDAAABQBbAGwMAAADAFsAbQwAAAIAKgDqDAAABABhABYABwksIisOAKkCB2gMAAAFAFwAaQwAAAUAYwBrDAAABQBiAGoMAAAFAFsAbAwAAAMAWwBtDAAAAgAqAOoMAAAEAGEAAAA=.Dez:BAACLgAFFH8GAAITAAMJnQoACgBoAANoDAAABAAlAGkMAAABAAwA6gwAAAEAHwATAAMJnQoACgBoAANoDAAABAAlAGkMAAABAAwA6gwAAAEAHwAuAAQKfyYAAhMACQnJFcUZADgCABMACQnJFcUZADgCAAAA.',
Dk='Dkamp:BAAALgADCgkJGQAAAA==.',
Dm='Dmoney:BAAALgAECgYJBgAAAA==.',
Do='Dondiablo:BAAALgAECgYJDQAAAA==.Doylock:BAAALgAECgUJBQAAAA==.',
Dr='Dragnaballs:BAEALgAECgcJEgABLgAFFAkJRwANAHAjAA==.Drdot:BAAALgAECgEJBAABLgAECggJHwASALsaAA==.Drehd:BAACLgAFFH8KAAIWAAMJvCQlMQAdAQNoDAAABQBfAGkMAAADAF8A6gwAAAIAWgAWAAMJvCQlMQAdAQNoDAAABQBfAGkMAAADAF8A6gwAAAIAWgAuAAQKfy0AAhYACAnVJF4JAB0DABYACAnVJF4JAB0DAAAA.Drewbear:BAAALgAFFAEJAQABLgAFFAQJDAAXANUaAA==.Drewcifer:BAACLgAFFH8MAAIXAAQJ1RphDAABAQRoDAAABABRAGkMAAADADoAagwAAAEAOQDqDAAABABCABcABAnVGmEMAAEBBGgMAAAEAFEAaQwAAAMAOgBqDAAAAQA5AOoMAAAEAEIALgAECn8tAAIXAAkJRSLfCwDoAgAXAAkJRSLfCwDoAgABLgAFFAQJDAAXANUaAA==.Drewwar:BAAALgAECgEJAQABLgAFFAQJDAAXANUaAA==.Dripps:BAAALgAECgYJBgAAAA==.',
Du='Dumalshadows:BAAALgAECgUJBQAAAA==.Dumper:BAAALgADCgEJAQAAAA==.Dumps:BAAALgAECgMJAwAAAA==.',
['Dó']='Dóom:BAAALgAECgUJCQABLgAFFAMJAwAMAAAAAA==.',
['Dü']='Düsk:BAAALgADCgUJBQABLgAECgMJCgAMAAAAAA==.',
Eg='Egoon:BAAALgAECgQJBgAAAA==.',
El='Elarial:BAAALgADCgEJAQAAAA==.Elmerfud:BAAALgAECgYJBwAAAA==.',
En='Enrèk:BAAALgADCgYJBgAAAA==.',
Fa='Falafel:BAACLgAFFH8kAAISAAYJ4CCsIQDqAQZoDAAABwBfAGkMAAAHAFQAawwAAAcAXABqDAAABQBWAGwMAAADADkA6gwAAAcAWgASAAYJ4CCsIQDqAQZoDAAABwBfAGkMAAAHAFQAawwAAAcAXABqDAAABQBWAGwMAAADADkA6gwAAAcAWgAuAAQKfygAAhIACQlOIuwSAAoDABIACQlOIuwSAAoDAAAA.',
Fi='Fidely:BAAALgADCgEJAQAAAA==.',
Fl='Flop:BAAALgADCgIJAgAAAA==.',
Fo='Fomo:BAAALgADCgYJBgAAAA==.Fornax:BAAALgAECgQJBwABLgAECgcJFwANAA8MAA==.Fotmtrash:BAACLgAFFH8XAAQYAAQJYR5aFgANAQRoDAAACABCAGkMAAAFAFUAawwAAAQAPgDqDAAABgBhABkABAlMF1AmABgBBGgMAAACADIAaQwAAAIARQBrDAAABAA+AOoMAAACADgAGAADCWwgWhYADQEDaAwAAAUAQgBpDAAAAwBVAOoMAAADAGEAGgACCeIEHjQAcgACaAwAAAEADgDqDAAAAQAKAC4ABAp/NAAEGQAJCTgj+AUAJQMAGQAJCf4f+AUAJQMAGAAICRki7wcAzAIAGgACCScJYVoATgAAAAA=.Foxxydots:BAABLgAECn82AAILAAkJ5RjxMAAVAgloDAAACABNAGkMAAAIAFAAawwAAAgAPgBqDAAABwA8AGwMAAAHAEcAbQwAAAUANgDqDAAACABBAG4MAAACACcAbwwAAAEAOgALAAkJ5RjxMAAVAgloDAAACABNAGkMAAAIAFAAawwAAAgAPgBqDAAABwA8AGwMAAAHAEcAbQwAAAUANgDqDAAACABBAG4MAAACACcAbwwAAAEAOgAAAA==.',
Fr='Frostitoot:BAABLgAECn8XAAINAAcJDwwMtwAXAQdoDAAABAAnAGkMAAAEABwAawwAAAQAMABqDAAAAwAcAGwMAAADAB0A6gwAAAQAJABuDAAAAQADAA0ABwkPDAy3ABcBB2gMAAAEACcAaQwAAAQAHABrDAAABAAwAGoMAAADABwAbAwAAAMAHQDqDAAABAAkAG4MAAABAAMAAAA=.',
Fu='Fupa:BAAALgAECgEJAQAAAA==.',
Ga='Galbsadi:BAABLgAECn8rAAMbAAgJnRTUEgAeAQhoDAAABgA6AGkMAAAGADwAawwAAAcAMwBqDAAABgA5AGwMAAAFADwAbQwAAAQAJADqDAAABQA+AG4MAAAEACcAGwAHCbUP1BIAHgEHaQwAAAEAGgBrDAAAAQAyAGoMAAADACsAbAwAAAEAKABtDAAAAQAaAOoMAAABAD4AbgwAAAEAJAALAAgJNhIhBwCtAAhoDAAABgA6AGkMAAAFADwAawwAAAYAMwBqDAAAAwA5AGwMAAAEADwAbQwAAAMAJADqDAAABAASAG4MAAADACcAAAA=.Garrius:BAAALgADCgQJBAAAAA==.',
Ge='Gelfdar:BAAALgAECgEJAQAAAA==.Genie:BAAALgAECgEJAQAAAA==.Gethendriel:BAAALgAECgUJDAAAAA==.Getsuga:BAAALgAECggJCwABLgAECgkJQwASABgiAA==.',
Gh='Ghostmonk:BAABLgAFFH8IAAIJAAMJiwqhBAC7AANoDAAAAwAXAGkMAAACAB4A6gwAAAMAGwAJAAMJiwqhBAC7AANoDAAAAwAXAGkMAAACAB4A6gwAAAMAGwABLgAFFAcJLQASALodAA==.',
Gl='Glaia:BAAALgADCgYJDQAAAA==.',
Go='Goel:BAAALgAECgEJAgAAAA==.',
Gr='Graf:BAABLgAECn8mAAQcAAkJhSHcHABnAgloDAAABwBjAGkMAAAFAFcAawwAAAYATwBqDAAABABVAGwMAAAFAF8AbQwAAAEAUADqDAAABwBjAG4MAAACAE4AbwwAAAEAQwAcAAcJQyLcHABnAgdoDAAABQBjAGkMAAADAFcAawwAAAQATwBqDAAAAwBTAGwMAAADAFIA6gwAAAYAYwBuDAAAAQBOAAEABgk9GAUbABkBBmgMAAABAE0AaQwAAAEANABrDAAAAQAQAOoMAAABAFEAbgwAAAEATQBvDAAAAQBDAB0ABgmyGg8xALoABmgMAAABADIAaQwAAAEAKgBrDAAAAQBJAGoMAAABAFUAbAwAAAIAXwBtDAAAAQBQAAAA.Grafbear:BAAALgADCgQJBAAAAA==.Graflock:BAAALgAECgUJBQAAAA==.Grimzorath:BAAALgAECgYJBgAAAA==.Grox:BAABLgAECn8UAAIcAAYJmg+qTgBsAQZoDAAABAA+AGkMAAAEAC4AawwAAAQAKgBqDAAAAwAlAGwMAAACABMA6gwAAAMAHAAcAAYJmg+qTgBsAQZoDAAABAA+AGkMAAAEAC4AawwAAAQAKgBqDAAAAwAlAGwMAAACABMA6gwAAAMAHAAAAA==.Grudge:BAAALgADCgMJBQAAAA==.',
Gu='Gulpan:BAAALgAFFAEJAQAAAA==.',
Ha='Hackensack:BAAALgAECggJEAAAAA==.Hamtaro:BAAALgAECgYJDAAAAA==.Hawthorne:BAACLgAFFH8HAAIHAAQJygjlEgCCAARoDAAAAgAQAGkMAAACAA8AbQwAAAEADQDqDAAAAgAsAAcABAnKCOUSAIIABGgMAAACABAAaQwAAAIADwBtDAAAAQANAOoMAAACACwALgAECn8jAAIHAAkJpB2TFAB2AgAHAAkJpB2TFAB2AgAAAA==.',
Hi='Hiyabusa:BAABLgAECn8UAAIeAAcJ4BBDLQCWAQdoDAAABABLAGkMAAAEADgAawwAAAMAIQBqDAAAAwAiAGwMAAADAEQA6gwAAAIAEgBuDAAAAQAGAB4ABwngEEMtAJYBB2gMAAAEAEsAaQwAAAQAOABrDAAAAwAhAGoMAAADACIAbAwAAAMARADqDAAAAgASAG4MAAABAAYAAAA=.',
Ho='Hollowboi:BAABLgAECn88AAIIAAkJMiIKBAAJAwloDAAACQBZAGkMAAAJAFkAawwAAAkAUwBqDAAABwBTAGwMAAAHAFUAbQwAAAQAVwDqDAAACABYAG4MAAAFAFsAbwwAAAIAVAAIAAkJMiIKBAAJAwloDAAACQBZAGkMAAAJAFkAawwAAAkAUwBqDAAABwBTAGwMAAAHAFUAbQwAAAQAVwDqDAAACABYAG4MAAAFAFsAbwwAAAIAVAAAAA==.Holygraf:BAAALgAECgcJDgAAAA==.',
Ia='Iamyama:BAAALgAECgUJCQAAAA==.',
Il='Illgaz:BAAALgAECgEJAQAAAA==.',
Io='Ionna:BAAALgADCgcJBwABLgAECgkJQwASABgiAA==.',
Jd='Jdvance:BAAALgAECgYJBgAAAA==.',
Jh='Jhouska:BAAALgAECgcJEAAAAA==.',
Jo='Jormunngandr:BAACLgAFFH8mAAQSAAgJMRZwGAAdAghoDAAABgBTAGkMAAAHAE4AawwAAAYAQwBqDAAABQA7AG0MAAACABMA6gwAAAoAXwBuDAAAAQAXAG8MAAABABwAEgAHCTEWcBgAHQIHaAwAAAYAUwBpDAAABwBOAGsMAAAFAEMAbQwAAAIAEwDqDAAACgBfAG4MAAABABcAbwwAAAEAHAAfAAEJ4AYhCQBMAAFrDAAAAQARACAAAQkAADgVAEYAAWoMAAAFADsALgAECn8fAAISAAkJvSCtEQASAwASAAkJvSCtEQASAwAAAA==.',
Ju='Judgynomnom:BAACLgAFFH8KAAITAAQJmhn8IwABAQRoDAAAAwBhAGkMAAADAFMAawwAAAIAGQDqDAAAAgA4ABMABAmaGfwjAAEBBGgMAAADAGEAaQwAAAMAUwBrDAAAAgAZAOoMAAACADgALgAECn8cAAITAAgJaCbcCQDUAgATAAgJaCbcCQDUAgAAAA==.',
Jy='Jyggles:BAABLgAECn8oAAIgAAgJ+AHMAwCLAAhoDAAABgAEAGkMAAAGAAkAawwAAAUABABqDAAABgAHAGwMAAAGAAQAbQwAAAIAAwDqDAAABQAFAG4MAAAEAAIAIAAICfgBzAMAiwAIaAwAAAYABABpDAAABgAJAGsMAAAFAAQAagwAAAYABwBsDAAABgAEAG0MAAACAAMA6gwAAAUABQBuDAAABAACAAAA.',
Ka='Kavdh:BAACLgAFFH8OAAIXAAUJrBzeBwBKAQVoDAAABABHAGkMAAAEAEwAawwAAAEARABqDAAAAQA4AOoMAAAEAE0AFwAFCawc3gcASgEFaAwAAAQARwBpDAAABABMAGsMAAABAEQAagwAAAEAOADqDAAABABNAC4ABAp/LAACFwAJCTwkiAMATwMAFwAJCTwkiAMATwMAAAA=.',
Ke='Kenpachip:BAAALgAECgUJBQAAAA==.Keyaesh:BAAALgAECgEJAQAAAA==.',
Ki='Kirax:BAAALgAECgEJAQAAAA==.',
Ko='Konataizumi:BAAALgADCgcJCwAAAA==.',
Kr='Kruhks:BAAALgAECgYJCAABLgAFFAMJCgAWALwkAA==.',
Ks='Kshot:BAABLgAECn89AAIPAAkJmR+PBgC4AgloDAAACQBZAGkMAAAIAF4AawwAAAgATwBqDAAACABZAGwMAAAJAFYAbQwAAAUASADqDAAACABcAG4MAAAEAE8AbwwAAAIANAAPAAkJmR+PBgC4AgloDAAACQBZAGkMAAAIAF4AawwAAAgATwBqDAAACABZAGwMAAAJAFYAbQwAAAUASADqDAAACABcAG4MAAAEAE8AbwwAAAIANAAAAA==.',
La='Lagdalen:BAABLgAECn8aAAIYAAYJExw+HwDKAQZoDAAABQBfAGkMAAAGAEgAawwAAAYAXABqDAAAAQAZAOoMAAAHAEkAbgwAAAEARwAYAAYJExw+HwDKAQZoDAAABQBfAGkMAAAGAEgAawwAAAYAXABqDAAAAQAZAOoMAAAHAEkAbgwAAAEARwAAAA==.Lanachan:BAABLgAECn9IAAIcAAkJ7RgbEwBZAgloDAAACQA2AGkMAAAKAEkAawwAAAoARwBqDAAACgBbAGwMAAAJAFMAbQwAAAYASADqDAAACgBBAG4MAAAEACsAbwwAAAQALQAcAAkJ7RgbEwBZAgloDAAACQA2AGkMAAAKAEkAawwAAAoARwBqDAAACgBbAGwMAAAJAFMAbQwAAAYASADqDAAACgBBAG4MAAAEACsAbwwAAAQALQAAAA==.',
Ld='Ldn:BAABLgAECn9GAAINAAkJBxWbAwB6AQloDAAACwBIAGkMAAAKADoAawwAAAoAKgBqDAAACgAvAGwMAAAJAEEAbQwAAAUAMwDqDAAACgBPAG4MAAAEADEAbwwAAAEADAANAAkJBxWbAwB6AQloDAAACwBIAGkMAAAKADoAawwAAAoAKgBqDAAACgAvAGwMAAAJAEEAbQwAAAUAMwDqDAAACgBPAG4MAAAEADEAbwwAAAEADAAAAA==.',
Le='Lep:BAAALgAECgUJBQAAAA==.',
Li='Lightofdawn:BAAALgAECgEJAQAAAA==.Likai:BAAALgADCgUJBQAAAA==.Lisa:BAAALgADCgcJAQAAAA==.Liz:BAACLgAFFH8GAAIQAAMJYQJ5GgB2AANoDAAABAAFAGkMAAABAAUA6gwAAAEABwAQAAMJYQJ5GgB2AANoDAAABAAFAGkMAAABAAUA6gwAAAEABwAuAAQKfzsAAhAACQm8CrJdAI0BABAACQm8CrJdAI0BAAAA.',
Ly='Lylieth:BAABLgAECn87AAILAAkJyBN/PgDiAQloDAAACABJAGkMAAAHAC0AawwAAAgAMgBqDAAABwBAAGwMAAAHADsAbQwAAAUALgDqDAAACAA1AG4MAAAGACwAbwwAAAMAIQALAAkJyBN/PgDiAQloDAAACABJAGkMAAAHAC0AawwAAAgAMgBqDAAABwBAAGwMAAAHADsAbQwAAAUALgDqDAAACAA1AG4MAAAGACwAbwwAAAMAIQAAAA==.Lyndyn:BAAALgADCgIJAgAAAA==.',
Ma='Mather:BAAALgAECgEJAgAAAA==.Mayzel:BAAALgAECgMJBAAAAA==.',
Mi='Microsqueeze:BAAALgADCgkJCQAAAA==.Miriko:BAAALgADCgkJCQAAAA==.',
Mo='Mock:BAACLgAFFH8IAAICAAMJaQKWUgB/AANoDAAAAwAEAGkMAAACAAsA6gwAAAMAAwACAAMJaQKWUgB/AANoDAAAAwAEAGkMAAACAAsA6gwAAAMAAwAuAAQKfyIAAgIACQntDnsCAO8AAAIACQntDnsCAO8AAAEuAAQKCQkjABkAqgwA.Mogera:BAAALgADCgMJBQAAAA==.Mouthyhusky:BAABLgAFFH8GAAIQAAQJDgOaXwDlAARoDAAAAgALAGkMAAACAAUAawwAAAEACQDqDAAAAQAEABAABAkOA5pfAOUABGgMAAACAAsAaQwAAAIABQBrDAAAAQAJAOoMAAABAAQAAAA=.',
Ni='Ninluv:BAAALgAECgQJDgAAAA==.',
Ny='Nyancat:BAAALgAECgEJAQAAAA==.',
Ol='Olaho:BAAALgADCgYJBgAAAA==.',
Om='Omenz:BAAALgADCgIJAgAAAA==.Omey:BAAALgAECgEJBAAAAA==.',
Oo='Oojni:BAAALgADCgYJBgAAAA==.',
Or='Oraine:BAAALgAECgUJBQAAAA==.Ortrazzarn:BAAALgAECgEJAQABLgAECgkJPAAIADIiAA==.',
Pa='Pazzman:BAAALgADCgYJBwAAAA==.',
Pe='Perc:BAAALgAECgQJBAAAAA==.',
Ph='Pharhar:BAABLgAECn81AAMTAAkJWiEpEACXAgloDAAACABcAGkMAAAIAGMAawwAAAgAYQBqDAAABgBQAGwMAAAGAEAAbQwAAAQARwDqDAAABgBRAG4MAAAFAFsAbwwAAAIAWQATAAkJWiEpEACXAgloDAAAAwBcAGkMAAAFAGMAawwAAAcAYQBqDAAABQBQAGwMAAAGAEAAbQwAAAQARwDqDAAABgBRAG4MAAACAFsAbwwAAAIAWQAGAAUJHRskpgAuAQVoDAAABQBAAGkMAAADAEAAawwAAAEANwBqDAAAAQAqAG4MAAADAFwAAAA=.',
Po='Poppachàdson:BAABLgAECn8dAAIhAAcJ+CDTCABPAgdoDAAABABbAGkMAAAFAFwAawwAAAUAVwBqDAAABQBFAGwMAAACAEQA6gwAAAYAYQBuDAAAAgBFACEABwn4INMIAE8CB2gMAAAEAFsAaQwAAAUAXABrDAAABQBXAGoMAAAFAEUAbAwAAAIARADqDAAABgBhAG4MAAACAEUAAS4ABRQDCQYAIQAaFQA=.Poppadadson:BAACLgAFFH8GAAIhAAMJGhXtDwDHAANoDAAAAwAsAGkMAAABACUA6gwAAAIAUAAhAAMJGhXtDwDHAANoDAAAAwAsAGkMAAABACUA6gwAAAIAUAAuAAQKfxwAAiEABwmBH4kGAI0CACEABwmBH4kGAI0CAAAA.Poppadotson:BAAALgAECgMJAwABLgAFFAMJBgAhABoVAA==.',
Pr='Priceless:BAAALgAECgkJCQAAAA==.',
Pu='Puscifer:BAAALgAECgkJCQAAAA==.',
Qu='Quarrior:BAAALgADCgEJAQABLgAECgMJCgAMAAAAAA==.Quellazaire:BAAALgADCgcJDAAAAA==.Quincar:BAAALgADCgEJAQABLgAECgMJCgAMAAAAAA==.',
Ra='Rafayel:BAAALgAECgIJAgABLgAECgkJQwAUAC8cAA==.Raizel:BAAALgAECgEJAQABLgAECgkJQwAUAC8cAA==.Ravister:BAAALgAECgUJBQABLgAFFAgJIQAaAGkgAA==.',
Re='Rebecknight:BAAALgADCgkJCQABLgAECgkJPAAIADIiAA==.Relic:BAACLgAFFH8iAAQfAAcJ4xF2BAC7AQdoDAAACABUAGkMAAAGAEwAawwAAAYAJgBqDAAABQAmAGwMAAABAA0AbQwAAAEAEQDqDAAABwAtAB8ABgmkEXYEALsBBmgMAAAIAFQAaQwAAAYATABrDAAABgAmAGwMAAABAA0AbQwAAAEAEQDqDAAABQApABIAAQmcEQMVAT4AAeoMAAABAC0AIAACCcUL/UIAKAACagwAAAUAJgDqDAAAAQAeAC4ABAp/KQADHwAJCYQdkwIAjAIAHwAJCYQdkwIAjAIAEgAGCZsXhYIAXgEAAAA=.Renk:BAABLgAECn8vAAISAAkJACYPBQBUAwloDAAACQBhAGkMAAAJAGMAawwAAAgAYABqDAAABQBjAGwMAAAFAF0AbQwAAAEAYADqDAAABgBhAG4MAAADAGIAbwwAAAEAYgASAAkJACYPBQBUAwloDAAACQBhAGkMAAAJAGMAawwAAAgAYABqDAAABQBjAGwMAAAFAF0AbQwAAAEAYADqDAAABgBhAG4MAAADAGIAbwwAAAEAYgAAAA==.Renka:BAAALgAECgUJBQABLgAECgkJLwASAAAmAA==.',
Ro='Ronald:BAABLgAECn8UAAIGAAYJZRrhlgBPAQZoDAAAAgBIAGkMAAACAEsAawwAAAIATgBqDAAAAQAPAOoMAAAHAEMAbgwAAAYAKwAGAAYJZRrhlgBPAQZoDAAAAgBIAGkMAAACAEsAawwAAAIATgBqDAAAAQAPAOoMAAAHAEMAbgwAAAYAKwAAAA==.Rowdyrebel:BAAALgAECgkJBwAAAA==.Roykevious:BAAALgAECgEJAwAAAA==.',
Sa='Saeyl:BAAALgAECgYJDAABLgAECgkJIAAZAB0KAA==.Saihu:BAAALgADCgEJAQABLgAECgkJQwASABgiAA==.Sammie:BAEALgAECgUJCAABLgAECgcJEAAMAAAAAA==.Sarix:BAAALgAECgQJBAAAAA==.Sarromand:BAAALgAECgUJBQABLgAECgkJPAAIADIiAA==.Savant:BAAALgAECgMJAwAAAA==.Sayl:BAABLgAECn8gAAMZAAkJHQpyNwA1AQloDAAABAAjAGkMAAADABIAawwAAAMAGwBqDAAAAwAqAGwMAAADABEAbQwAAAIAJQDqDAAABwAQAG4MAAAFAA4AbwwAAAIAFQAZAAgJjAlyNwA1AQhoDAAABAAjAGkMAAADABIAawwAAAMAGwBqDAAAAwAqAGwMAAACABEA6gwAAAYAEABuDAAAAgAOAG8MAAABABUAGgAFCTMIG1kAsAAFbAwAAAEAEwBtDAAAAgARAOoMAAABABUAbgwAAAMAHgBvDAAAAQAPAAAA.',
Sc='Scallywinkle:BAAALgAECgcJEAAAAA==.Scrap:BAABLgAECn8aAAMLAAkJ4hqLPgATAgloDAAABABSAGkMAAADAFUAawwAAAMARABqDAAAAwBBAGwMAAADAEIAbQwAAAIAQQDqDAAABABFAG4MAAADAEUAbwwAAAEAKwALAAgJcBqLPgATAghoDAAABABSAGkMAAADAFUAawwAAAEAPQBsDAAAAQA/AG0MAAABAEEA6gwAAAQARQBuDAAAAwBFAG8MAAABACsAGwAECXkU4CsAEAEEawwAAAIARABqDAAAAwBBAGwMAAACAEIAbQwAAAEAFgAAAA==.',
Se='Senova:BAAALgAECgIJAgAAAA==.',
Sh='Shadowghoul:BAABLgAECn8WAAIaAAgJbwrSNgA6AQhoDAAAAwAmAGkMAAADABkAawwAAAMAJgBqDAAAAwArAGwMAAACAB0AbQwAAAEACADqDAAABgATAG4MAAABABoAGgAICW8K0jYAOgEIaAwAAAMAJgBpDAAAAwAZAGsMAAADACYAagwAAAMAKwBsDAAAAgAdAG0MAAABAAgA6gwAAAYAEwBuDAAAAQAaAAAA.Shadowydern:BAABLgAECn8oAAMaAAkJlSACCgCuAgloDAAABgBhAGkMAAAGAFUAawwAAAUAVABqDAAABABgAGwMAAAEAF4AbQwAAAIAWADqDAAABgBTAG4MAAAFAEcAbwwAAAIAPQAaAAkJlSACCgCuAgloDAAABgBhAGkMAAAGAFUAawwAAAQAVABqDAAABABgAGwMAAAEAF4AbQwAAAIAWADqDAAABgBTAG4MAAAFAEcAbwwAAAIAPQAYAAEJ/RBpfwAzAAFrDAAAAQArAAAA.Shamewow:BAACLgAFFH8aAAIWAAcJ8RVEEwDMAQdoDAAABgBLAGkMAAAFAEAAawwAAAIAPwBqDAAAAwA4AGwMAAABADsA6gwAAAgAQgBuDAAAAQAHABYABwnxFUQTAMwBB2gMAAAGAEsAaQwAAAUAQABrDAAAAgA/AGoMAAADADgAbAwAAAEAOwDqDAAACABCAG4MAAABAAcALgAECn8zAAIWAAkJSBzWFgCTAgAWAAkJSBzWFgCTAgAAAA==.Sharkbite:BAAALgAECgQJCwAAAA==.Shrimpboat:BAAALgAECgYJBQAAAA==.',
Si='Sicknnasty:BAACLgAFFH8dAAIgAAYJmBUFEgBqAQZoDAAACABMAGkMAAAHAE0AawwAAAQALwBqDAAAAgBLAGwMAAABABEA6gwAAAcAOQAgAAYJmBUFEgBqAQZoDAAACABMAGkMAAAHAE0AawwAAAQALwBqDAAAAgBLAGwMAAABABEA6gwAAAcAOQAuAAQKf0oAAyAACQkMIuYHAJoCACAACQkMIuYHAJoCABIACAlRFqlaALYBAAAA.Sicsickly:BAAALgAFFAEJAQAAAA==.',
Sl='Slayerz:BAAALgAECgYJBgAAAA==.',
Sn='Snattch:BAAALgADCgEJAQAAAA==.Snookismalls:BAABLgAECn8jAAMZAAkJqgx5IQDCAQloDAAABQA3AGkMAAAFAB0AawwAAAUAGwBqDAAABQAgAGwMAAAFADUAbQwAAAMAEwDqDAAABQARAG4MAAABABMAbwwAAAEAJAAZAAkJqgx5IQDCAQloDAAAAgA3AGkMAAACAB0AawwAAAEAGwBqDAAAAgAgAGwMAAACADUAbQwAAAEAEwDqDAAABAARAG4MAAABABMAbwwAAAEAJAAaAAcJXwdgRgD2AAdoDAAAAwAQAGkMAAADACAAawwAAAQAGABqDAAAAwATAGwMAAADABIAbQwAAAIADwDqDAAAAQAGAAAA.',
So='Solarian:BAAALgADCgMJAwAAAA==.Solitary:BAABLgAECn8fAAISAAgJuxrwMAA7AghoDAAABQBbAGkMAAAGAFkAawwAAAYATQBqDAAABABIAGwMAAADAEkAbQwAAAEADADqDAAABQBWAG4MAAABAC8AEgAICbsa8DAAOwIIaAwAAAUAWwBpDAAABgBZAGsMAAAGAE0AagwAAAQASABsDAAAAwBJAG0MAAABAAwA6gwAAAUAVgBuDAAAAQAvAAAA.Sos:BAAALgAECgEJAQAAAA==.',
Sp='Sparkyboo:BAAALgAECgEJAQAAAA==.Speed:BAAALgAECgYJCwAAAA==.Spinach:BAAALgAECgMJAQABLgAECgYJBQAMAAAAAA==.',
St='Starshopping:BAABLgAECn8aAAIXAAgJmiGgAQCWAQhoDAAAAwBhAGkMAAAEAFgAawwAAAQAWABqDAAABABaAGwMAAAEAFoAbQwAAAIAUwDqDAAAAwBPAG4MAAACAEoAFwAICZohoAEAlgEIaAwAAAMAYQBpDAAABABYAGsMAAAEAFgAagwAAAQAWgBsDAAABABaAG0MAAACAFMA6gwAAAMATwBuDAAAAgBKAAEuAAUUAwkFAA8AhxoA.',
Su='Sunari:BAAALgADCgQJBAAAAA==.',
Ta='Taewryn:BAABLgAFFH8FAAMdAAQJQA/YGgDAAARoDAAAAQAvAGkMAAABABoAawwAAAEAIQDqDAAAAgAvAB0ABAlAD9gaAMAABGgMAAABAC8AaQwAAAEAGgBrDAAAAQAhAOoMAAABAC8AHAABCWIFmFcAOwAB6gwAAAEADQABLgAFFAkJOgAIAA8mAA==.Talrip:BAABLgAECn8eAAIiAAkJVR3YBgAgAgloDAAABQA4AGkMAAAFAFsAawwAAAUAUgBqDAAAAwAyAGwMAAADAFEAbQwAAAEAWgDqDAAABQA8AG4MAAACAFIAbwwAAAEANwAiAAkJVR3YBgAgAgloDAAABQA4AGkMAAAFAFsAawwAAAUAUgBqDAAAAwAyAGwMAAADAFEAbQwAAAEAWgDqDAAABQA8AG4MAAACAFIAbwwAAAEANwAAAA==.Taxiplease:BAAALgAECggJBwAAAA==.',
Th='Thicctrix:BAAALgADCgcJDAAAAA==.Thornhub:BAAALgAECgUJBQAAAA==.Thundon:BAAALgADCgcJCQAAAA==.',
To='Toatem:BAAALgAECgYJCwAAAA==.Toro:BAACLgAFFH8gAAIcAAgJgxwuAwBYAghoDAAABwBhAGkMAAAGAGAAawwAAAUANwBqDAAAAwAsAGwMAAABACIAbQwAAAEARQDqDAAACABiAG4MAAABADoAHAAICYMcLgMAWAIIaAwAAAcAYQBpDAAABgBgAGsMAAAFADcAagwAAAMALABsDAAAAQAiAG0MAAABAEUA6gwAAAgAYgBuDAAAAQA6AC4ABAp/KwACHAAJCXckZQUAUAMAHAAJCXckZQUAUAMAAAA=.',
Tr='Traitor:BAAALgADCgEJAQAAAA==.Trappynomnom:BAAALgAFFAIJAgAAAA==.Tree:BAACLgAFFH8PAAIUAAQJBiSZGACaAQRoDAAABQBiAGkMAAADAGMAawwAAAEASQDqDAAABgBiABQABAkGJJkYAJoBBGgMAAAFAGIAaQwAAAMAYwBrDAAAAQBJAOoMAAAGAGIALgAECn8WAAIUAAYJmSNYHgBMAgAUAAYJmSNYHgBMAgAAAA==.Treegrundler:BAAALgAECgYJEwAAAA==.Treeus:BAAALgAECgYJCQAAAA==.Trixulous:BAAALgADCgkJJQAAAA==.',
Tw='Twiigee:BAABLgAECn8XAAIIAAYJWSANIAABAgZoDAAABQBfAGkMAAAFAFMAawwAAAQAVABqDAAAAgAxAGwMAAACAEMA6gwAAAUAUwAIAAYJWSANIAABAgZoDAAABQBfAGkMAAAFAFMAawwAAAQAVABqDAAAAgAxAGwMAAACAEMA6gwAAAUAUwAAAA==.',
Tz='Tzungxie:BAABLgAECn8tAAIeAAkJWR3qDQBJAgloDAAACABRAGkMAAAIAEEAawwAAAcASgBqDAAAAwA/AGwMAAAFAEkAbQwAAAIAUwDqDAAACABTAG4MAAACAFoAbwwAAAIAMQAeAAkJWR3qDQBJAgloDAAACABRAGkMAAAIAEEAawwAAAcASgBqDAAAAwA/AGwMAAAFAEkAbQwAAAIAUwDqDAAACABTAG4MAAACAFoAbwwAAAIAMQAAAA==.',
Un='Unholylord:BAACLgAFFH8hAAIaAAgJaSBSAgCPAghoDAAACQBhAGkMAAAGAGMAawwAAAQAYABqDAAAAgAvAGwMAAACAGAAbQwAAAEAMwDqDAAACABZAG4MAAABADIAGgAICWkgUgIAjwIIaAwAAAkAYQBpDAAABgBjAGsMAAAEAGAAagwAAAIALwBsDAAAAgBgAG0MAAABADMA6gwAAAgAWQBuDAAAAQAyAC4ABAp/IgACGgAJCa0jygQARwMAGgAJCa0jygQARwMAAAA=.',
Va='Vae:BAAALgAECgMJAwAAAA==.Vagbadge:BAAALgAECgkJEgABLgAFFAgJIQAaAGkgAA==.Varroww:BAAALgAECgYJEQAAAA==.',
Vo='Vosxo:BAAALgAECgEJAQAAAA==.',
['Ví']='Vígo:BAABLgAECn9IAAIBAAkJ1gwCAQAzAQloDAAADAAxAGkMAAALACgAawwAAAsAKQBqDAAACQAeAGwMAAAIABQAbQwAAAYAIwDqDAAACgAnAG4MAAAEAAwAbwwAAAEAFgABAAkJ1gwCAQAzAQloDAAADAAxAGkMAAALACgAawwAAAsAKQBqDAAACQAeAGwMAAAIABQAbQwAAAYAIwDqDAAACgAnAG4MAAAEAAwAbwwAAAEAFgAAAA==.',
Wa='Wado:BAAALgAECgEJAQAAAA==.',
We='Wellíngton:BAAALgAECgEJAQAAAA==.',
Wh='Whack:BAAALgAECgEJAQAAAA==.',
Wi='Wicke:BAAALgADCgQJBAABLgAECgEJAgAMAAAAAA==.',
Wo='Wolfthetree:BAAALgAECgUJCAAAAA==.',
Wy='Wystarr:BAAALgADCgIJAgAAAA==.',
Xa='Xamael:BAAALgADCgMJAwAAAA==.',
Xe='Xerkz:BAAALgAECgEJAQAAAA==.',
Ys='Ystarian:BAACLgAFFH8RAAMDAAUJQRQgBAAuAQVoDAAABAA7AGkMAAAEAEsAawwAAAMAIQBqDAAAAgBVAOoMAAAEACYAAwAFCeYSIAQALgEFaAwAAAMAOwBpDAAABABLAGsMAAACACEAagwAAAIAVQDqDAAAAwAZAAIAAwkgDXJHAKsAA2gMAAABAB8AawwAAAEAHgDqDAAAAQAmAC4ABAp/RgAEAwAJCZsefQIAlgIAAwAJCZsefQIAlgIAAgAICYwVHB0A3gEABAABCRsB804AIAAAAAA=.',
Za='Zaptik:BAAALgAECgEJAgAAAA==.',
['Ël']='Ëlëmëntary:BAAALgAECgcJBgAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
