local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Rogue-Subtlety','Hunter-Marksmanship','Hunter-Survival','DemonHunter-Devourer','DemonHunter-Vengeance','Unknown-Unknown','Warlock-Affliction','Warlock-Demonology','Shaman-Elemental','Rogue-Assassination','Monk-Brewmaster','Shaman-Restoration','DeathKnight-Unholy','Mage-Frost','Warlock-Destruction','Paladin-Retribution','Hunter-BeastMastery','DemonHunter-Havoc','Evoker-Augmentation','Evoker-Preservation','Warrior-Protection','Priest-Shadow','Druid-Guardian','Druid-Restoration','Druid-Balance','Shaman-Enhancement','Paladin-Holy','Priest-Holy','Monk-Windwalker','Rogue-Outlaw','Monk-Mistweaver','DeathKnight-Blood','Druid-Feral','Warrior-Fury','Warrior-Arms','Mage-Fire','Mage-Arcane',}
local provider = {region='US',realm='Jaedenar',name='US',type='daily',zone=46,date='2026-05-11',data={Ag='Agonie:BAAALgAECgEJAQAAAA==.',
Al='Aladia:BAAALgAECgEJAQABLgAECggJGgABAJkgAA==.Alaina:BAAALgADCgIJAgAAAA==.Aleive:BAAALgAECgEJAQAAAA==.Alion:BAAALgAECgYJBwAAAA==.Alphachik:BAAALgADCggJEwAAAA==.Alruna:BAAALgADCgIJAgAAAA==.',
Am='Amarafar:BAACLgAFFH8HAAICAAMJuSGxEQAfAQNoDAAABABLAGkMAAACAFgA6gwAAAEAXwACAAMJuSGxEQAfAQNoDAAABABLAGkMAAACAFgA6gwAAAEAXwAuAAQKfxUAAwIACAl+H/kPAL8CAAIACAl+H/kPAL8CAAMAAgnjGeMkAKIAAAAA.Amoteph:BAAALgADCgQJBAAAAA==.',
An='Anoiche:BAABLgAECn8QAAIEAAgJ0xonOgAMAghoDAAAAQBFAGkMAAABAC4AawwAAAEATQBqDAAAAgA/AGwMAAACAFIAbQwAAAIALQDqDAAABQBTAG4MAAACAEsABAAICdMaJzoADAIIaAwAAAEARQBpDAAAAQAuAGsMAAABAE0AagwAAAIAPwBsDAAAAgBSAG0MAAACAC0A6gwAAAUAUwBuDAAAAgBLAAAA.',
As='Asmodeus:BAACLgAFFH8MAAIEAAUJ9RRRIQAzAQVoDAAAAwA2AGkMAAADACYAawwAAAIAMABqDAAAAQASAOoMAAADAEgABAAFCfUUUSEAMwEFaAwAAAMANgBpDAAAAwAmAGsMAAACADAAagwAAAEAEgDqDAAAAwBIAC4ABAp/KAACBAAHCSUenR8A3AEABAAHCSUenR8A3AEAAAA=.',
At='Atilia:BAAALgAECgEJAQABLgAECggJLwAFAHYkAA==.Atlastrasz:BAAALgADCggJGAABLgADCgkJGAAGAAAAAA==.',
Av='Avanzo:BAAALgAECgMJAwAAAA==.',
Ax='Axeldaur:BAAALgADCgMJAwAAAA==.Axelrod:BAAALgAECgkJDgAAAA==.',
Az='Azucena:BAAALgAECgMJAwAAAA==.',
Ba='Bananos:BAACLgAFFH8IAAMHAAQJKQzfAgDdAARoDAAABAA7AGkMAAACAAcAawwAAAEACwDqDAAAAQAtAAcAAwmqDt8CAN0AA2gMAAAEADsAaQwAAAIABwDqDAAAAQAtAAgAAQmmBNiJADsAAWsMAAABAAsALgAECn8dAAMHAAgJOBzzAQC1AgAHAAgJOBzzAQC1AgAIAAMJNwit1gA9AAAAAA==.',
Bd='Bdog:BAAALgADCgMJAwAAAA==.Bdogg:BAAALgADCgQJBAAAAA==.',
Be='Bearback:BAAALgAFFAIJAgAAAA==.Bertram:BAABLgAECn8bAAIJAAYJ5wQTPwDAAAZoDAAABgAPAGkMAAAFABQAawwAAAUACwBqDAAABAASAGwMAAADAAYA6gwAAAQACQAJAAYJ5wQTPwDAAAZoDAAABgAPAGkMAAAFABQAawwAAAUACwBqDAAABAASAGwMAAADAAYA6gwAAAQACQAAAA==.',
Bi='Bialalilia:BAAALgADCgMJAwAAAA==.Billie:BAAALgAECgQJBAAAAA==.',
Bl='Blender:BAAALgADCgMJAwAAAA==.Blightforged:BAAALgADCgUJCQAAAA==.',
Bo='Boojum:BAAALgAECgUJCgAAAA==.Booze:BAABLgAECn8aAAMBAAgJmSDvCAAfAghoDAAABABQAGkMAAADAF0AawwAAAMAPQBqDAAAAwBfAGwMAAADAFcAbQwAAAMAWQDqDAAABQBgAG4MAAACAEoAAQAHCU8g7wgAHwIHaAwAAAQAUABpDAAAAwBdAGsMAAACAD0AagwAAAMAXwBtDAAAAwBZAOoMAAAFAGAAbgwAAAIASgAKAAIJzRwiEQCxAAJrDAAAAQA7AGwMAAADAFcAAAA=.Borgar:BAAALgAECgQJBwABLgAFFAMJBAAEAE4TAA==.',
Ch='Chillsunwell:BAAALgADCgkJCQAAAA==.Chivasaurus:BAABLgAECn8cAAILAAgJCAQlLAD7AAhoDAAABQASAGkMAAAFAAoAawwAAAQADQBqDAAAAgAFAGwMAAAEABAAbQwAAAEABADqDAAABQAHAG4MAAACAAIACwAICQgEJSwA+wAIaAwAAAUAEgBpDAAABQAKAGsMAAAEAA0AagwAAAIABQBsDAAABAAQAG0MAAABAAQA6gwAAAUABwBuDAAAAgACAAEuAAUUBAkMAAkA8AwA.',
Ci='Cirrce:BAAALgAECgcJCAAAAA==.',
Cl='Cluëless:BAAALgAECgMJBgAAAA==.',
Co='Cokenoice:BAAALgAECgEJAQAAAA==.Covenant:BAAALgAECgYJDgAAAA==.',
Cr='Craig:BAAALgADCgYJBgAAAA==.',
Cy='Cynide:BAAALgAECgYJCgAAAA==.',
Da='Darktarus:BAAALgADCgIJAgAAAA==.',
De='Demonz:BAAALgADCgMJAwAAAA==.Dengeng:BAAALgAECgIJAwAAAA==.Depally:BAAALgAECgMJBAAAAA==.Devastata:BAAALgADCgcJBwAAAA==.Devilsburn:BAAALgAECgYJBwAAAA==.',
Di='Disruptive:BAAALgAECgYJCAAAAA==.',
Dl='Dleifroom:BAAALgADCgMJAwAAAA==.',
Do='Domry:BAAALgADCgQJBAAAAA==.Dorim:BAABLgAECn8WAAMJAAgJ3RLkIwBGAQhoDAAAAwAsAGkMAAADADAAawwAAAMAIwBqDAAAAwAcAGwMAAADAC4AbQwAAAMAKQDqDAAAAwAoAG4MAAABAFAACQAHCcIQ5CMARgEHaAwAAAMALABpDAAAAwAwAGsMAAADACMAagwAAAMAHABsDAAAAgAuAG0MAAACACkA6gwAAAMAKAAMAAMJ9QbOaAB4AANsDAAAAQAZAG0MAAABABcAbgwAAAEABAAAAA==.',
Du='Duuhwat:BAAALgADCgYJBgAAAA==.',
Ec='Eclipse:BAACLgAFFH8LAAINAAQJkhA3HAAzAQRoDAAAAgA4AGkMAAADAC4AawwAAAIADQDqDAAABAAzAA0ABAmSEDccADMBBGgMAAACADgAaQwAAAMALgBrDAAAAgANAOoMAAAEADMALgAECn8iAAINAAgJ6CAGHADWAgANAAgJ6CAGHADWAgAAAA==.Eco:BAACLgAFFH8LAAIOAAQJyxyqIQBrAQRoDAAABAAuAGkMAAADAEsAawwAAAEATwDqDAAAAwBdAA4ABAnLHKohAGsBBGgMAAAEAC4AaQwAAAMASwBrDAAAAQBPAOoMAAADAF0ALgAECn8dAAIOAAkJ9B+yIgAtAgAOAAkJ9B+yIgAtAgAAAA==.',
Ed='Edeith:BAAALgAECgYJEwAAAA==.',
Eh='Ehanoko:BAAALgADCgYJBgABLgAECgYJFwABAPccAA==.',
El='Elmono:BAACLgAFFH8XAAIOAAYJQBgvEAC6AQZoDAAABQA/AGkMAAAGADAAawwAAAMAKABqDAAAAwA3AGwMAAABAEkA6gwAAAUAUwAOAAYJQBgvEAC6AQZoDAAABQA/AGkMAAAGADAAawwAAAMAKABqDAAAAwA3AGwMAAABAEkA6gwAAAUAUwAuAAQKfzUAAg4ACQnyId8UACsDAA4ACQnyId8UACsDAAAA.Elusivepanda:BAABLgAECn8VAAIPAAgJ3yIpBwBXAghoDAAAAgBdAGkMAAACAE0AawwAAAIAUgBqDAAAAgBYAGwMAAAEAGAAbQwAAAIAYgDqDAAABgBiAG4MAAABAE4ADwAICd8iKQcAVwIIaAwAAAIAXQBpDAAAAgBNAGsMAAACAFIAagwAAAIAWABsDAAABABgAG0MAAACAGIA6gwAAAYAYgBuDAAAAQBOAAAA.',
En='Enii:BAAALgAECgYJEAAAAA==.',
Er='Eravia:BAABLgAECn8YAAIQAAkJPBMNHQArAgloDAAAAgBBAGkMAAADACcAawwAAAQAQwBqDAAAAgAUAGwMAAADAGIAbQwAAAMAIADqDAAAAwAhAG4MAAACACQAbwwAAAIAEwAQAAkJPBMNHQArAgloDAAAAgBBAGkMAAADACcAawwAAAQAQwBqDAAAAgAUAGwMAAADAGIAbQwAAAMAIADqDAAAAwAhAG4MAAACACQAbwwAAAIAEwAAAA==.Erodria:BAAALgAECgQJCwAAAA==.Erther:BAACLgAFFH8NAAIRAAUJGxPCDAD8AAVoDAAABAA0AGkMAAADAEMAawwAAAEABABqDAAAAQBaAOoMAAAEAEcAEQAFCRsTwgwA/AAFaAwAAAQANABpDAAAAwBDAGsMAAABAAQAagwAAAEAWgDqDAAABABHAC4ABAp/KgAEEQAICUwkSAQASwMAEQAICUwkSAQASwMAAgAGCZMOO00AHAEAAwACCYAWXS8AlQAAAAA=.',
Es='Espresso:BAAALgADCgcJBwAAAA==.',
Eu='Eucharistica:BAACLgAFFH8OAAIEAAYJWhi9CgCtAQZoDAAAAwAxAGkMAAADAEUAawwAAAIAOQBqDAAAAwBWAGwMAAABACgA6gwAAAIAXQAEAAYJWhi9CgCtAQZoDAAAAwAxAGkMAAADAEUAawwAAAIAOQBqDAAAAwBWAGwMAAABACgA6gwAAAIAXQAuAAQKf0QAAgQACQlJI1gCADkDAAQACQlJI1gCADkDAAAA.',
Ex='Exeter:BAAALgAECgQJCgAAAA==.',
Ey='Eyegor:BAAALgAECgMJAwAAAA==.',
Fa='Faelyssa:BAABLgAECn8dAAISAAcJch+0DADJAQdoDAAABQBbAGkMAAAHAFoAawwAAAUAWABqDAAAAwBPAGwMAAADADoA6gwAAAQAWwBuDAAAAgA9ABIABwlyH7QMAMkBB2gMAAAFAFsAaQwAAAcAWgBrDAAABQBYAGoMAAADAE8AbAwAAAMAOgDqDAAABABbAG4MAAACAD0AAS4ABRQDCQQABABOEwA=.Fake:BAAALgAECgMJAQAAAA==.Far:BAACLgAFFH8LAAMRAAUJnRJbIAAnAQVoDAAAAwBPAGkMAAADADcAawwAAAEAKABqDAAAAgAQAOoMAAACAA8AEQAECdMNWyAAJwEEaAwAAAIATwBpDAAAAgARAGsMAAABACgA6gwAAAEAAwADAAQJ4Q06EQD5AARoDAAAAQAjAGkMAAABADcAagwAAAIAEADqDAAAAQAPAC4ABAp/KgAEEQAICfggFhEAsQIAEQAICecgFhEAsQIAAwAHCZUciAsA+gEAAgAECaMO7VkA3AAAAAA=.Fathergoose:BAABLgAECn8rAAMTAAgJYhr+DgCGAghoDAAABwBQAGkMAAAHAFAAawwAAAYATABqDAAABQBKAGwMAAAFAEsAbQwAAAMAIgDqDAAABwBFAG4MAAADADcAEwAICWIa/g4AhgIIaAwAAAUAUABpDAAABgBQAGsMAAAFAEwAagwAAAQASgBsDAAAAwBLAG0MAAADACIA6gwAAAQARQBuDAAAAgA3ABQABwkDFNwLAJ0BB2gMAAACAD0AaQwAAAEAMgBrDAAAAQA2AGoMAAABACoAbAwAAAIAPwDqDAAAAwAuAG4MAAABACgAAAA=.',
Fi='Fistweavin:BAAALgAECgEJAQAAAA==.',
Fo='Foxpaw:BAAALgAECgMJAwAAAA==.',
Fr='Freakinout:BAAALgADCgUJBgAAAA==.Freekin:BAABLgAECn8oAAISAAkJPSRPAQAdAwloDAAABwBiAGkMAAAGAGEAawwAAAYAYABqDAAABgBaAGwMAAAFAFoAbQwAAAEAUQDqDAAABgBWAG4MAAACAF4AbwwAAAEAXwASAAkJPSRPAQAdAwloDAAABwBiAGkMAAAGAGEAawwAAAYAYABqDAAABgBaAGwMAAAFAFoAbQwAAAEAUQDqDAAABgBWAG4MAAACAF4AbwwAAAEAXwAAAA==.',
Fu='Fuddytotem:BAABLgAECn8cAAMMAAYJGCG1IgAPAgZoDAAABgBeAGkMAAAFAFQAawwAAAYAYwBqDAAAAgBMAGwMAAADAFEA6gwAAAYASAAMAAYJGCG1IgAPAgZoDAAABABeAGkMAAADAFQAawwAAAUAYwBqDAAAAQBMAGwMAAACAFEA6gwAAAUASAAJAAYJgRFTTQASAQZoDAAAAgAvAGkMAAACAEkAawwAAAEASgBqDAAAAQAoAGwMAAABAAMA6gwAAAEAGQABLgAECggJFQAVAPwNAA==.Funnelcake:BAAALgADCgcJBwAAAA==.Furmoo:BAAALgAECgEJAQAAAA==.',
Fz='Fzy:BAABLgAECn8VAAIVAAgJ/A1aFADGAQhoDAAAAwAxAGkMAAADACQAawwAAAMAMwBqDAAAAwBQAGwMAAADABIAbQwAAAEADwDqDAAAAwA1AG4MAAACABgAFQAICfwNWhQAxgEIaAwAAAMAMQBpDAAAAwAkAGsMAAADADMAagwAAAMAUABsDAAAAwASAG0MAAABAA8A6gwAAAMANQBuDAAAAgAYAAAA.Fzymage:BAAALgADCgEJAQABLgAECggJFQAVAPwNAA==.Fzyy:BAAALgADCgMJAwABLgAECggJFQAVAPwNAA==.',
Ga='Galvatron:BAAALgAECgIJAwAAAA==.',
Ge='Gearshot:BAAALgADCgcJDQAAAA==.Gergnome:BAAALgADCgYJBgAAAA==.',
Gh='Ghroxx:BAAALgAECgQJBQABLgAFFAMJBAAEAE4TAA==.',
Go='Goodra:BAAALgAFFAIJAgAAAA==.Goosetopher:BAABLgAECn8jAAIWAAgJlRfeDgD0AQhoDAAABwBXAGkMAAAFADUAawwAAAUANQBqDAAAAwA8AGwMAAAEAD0AbQwAAAMANwDqDAAABQA9AG4MAAADADEAFgAICZUX3g4A9AEIaAwAAAcAVwBpDAAABQA1AGsMAAAFADUAagwAAAMAPABsDAAABAA9AG0MAAADADcA6gwAAAUAPQBuDAAAAwAxAAAA.Goril:BAACLgAFFH8EAAIEAAMJThOuNgDoAANoDAAAAgBLAGkMAAABAEMA6gwAAAEABQAEAAMJThOuNgDoAANoDAAAAgBLAGkMAAABAEMA6gwAAAEABQAuAAQKfxMAAgQABwlOGj4fAN4BAAQABwlOGj4fAN4BAAAA.Goryious:BAACLgAFFH8HAAINAAMJowpTLQDmAANoDAAABAAeAGkMAAACABIA6gwAAAEAIQANAAMJowpTLQDmAANoDAAABAAeAGkMAAACABIA6gwAAAEAIQAuAAQKfx4AAg0ACQmeFhVAADgCAA0ACQmeFhVAADgCAAEuAAUUBQkNAAIAHRwA.',
Gw='Gweg:BAABLgAECn8iAAMRAAgJTx4GIgA5AghoDAAABQBOAGkMAAAFAFcAawwAAAUAXwBqDAAABABWAGwMAAAEAEoAbQwAAAIAWADqDAAABwBXAG4MAAACAB8AEQAICcAcBiIAOQIIaAwAAAIAQwBpDAAAAQBKAGsMAAABAFwAagwAAAEAJgBsDAAAAQBKAG0MAAACAFgA6gwAAAMAVwBuDAAAAQAdAAMABwk7HPoLAPMBB2gMAAADAE4AaQwAAAQAVwBrDAAABABfAGoMAAADAFYAbAwAAAMAPQDqDAAABABQAG4MAAABAB8AAAA=.',
Ha='Halarda:BAABLgAECn8dAAMRAAcJuBu+LgCjAQdoDAAABQBKAGkMAAAFAEYAawwAAAUAYABqDAAABABfAGwMAAAEAEkAbQwAAAIAJQDqDAAABABJABEABwm4G74uAKMBB2gMAAAEAEoAaQwAAAQARgBrDAAABABgAGoMAAAEAF8AbAwAAAQASQBtDAAAAQAlAOoMAAADAEkAAgAFCQIQslAACwEFaAwAAAEASQBpDAAAAQA9AGsMAAABAB8AbQwAAAEAEgDqDAAAAQAUAAAA.Harantor:BAAALgADCgkJGAAAAA==.',
Hi='Him:BAAALgADCgcJBwAAAA==.Hitthefloor:BAABLgAECn8wAAIMAAgJdR7SBwDBAghoDAAACQBaAGkMAAAHAFIAawwAAAkAXQBqDAAABwBCAGwMAAAGAFcAbQwAAAIAGADqDAAABgBVAG4MAAACAF0ADAAICXUe0gcAwQIIaAwAAAkAWgBpDAAABwBSAGsMAAAJAF0AagwAAAcAQgBsDAAABgBXAG0MAAACABgA6gwAAAYAVQBuDAAAAgBdAAAA.',
Ho='Hooves:BAACLgAFFH8ZAAIXAAYJxBURAgCCAQZoDAAABgBLAGkMAAAGAFEAawwAAAQASgBqDAAAAwAEAGwMAAABAAUA6gwAAAUAKQAXAAYJxBURAgCCAQZoDAAABgBLAGkMAAAGAFEAawwAAAQASgBqDAAAAwAEAGwMAAABAAUA6gwAAAUAKQAuAAQKfzQAAhcACQkVI/UAAGQDABcACQkVI/UAAGQDAAAA.',
Ic='Icphunter:BAAALgAECgkJAQAAAA==.',
Im='Imàdrood:BAABLgAECn8tAAMYAAkJJRydGAAQAgloDAAABwBWAGkMAAAGAFYAawwAAAYAUwBqDAAABgBQAGwMAAAFAEkAbQwAAAMAJgDqDAAABgBLAG4MAAAFACQAbwwAAAEAVwAYAAgJZRudGAAQAghoDAAABgBWAGkMAAAGAFYAawwAAAYAUwBqDAAABQBQAGwMAAADAEkAbQwAAAEAJgDqDAAABQBLAG4MAAADACQAGQAHCRASihsAawEHaAwAAAEANwBqDAAAAQA7AGwMAAACAE4AbQwAAAIANgDqDAAAAQAAAG4MAAACAB0AbwwAAAEAOwAAAA==.',
In='Inukari:BAAALgADCgcJBwAAAA==.Invincible:BAAALgADCgcJCwAAAA==.',
Is='Iscorpiusi:BAAALgAECgMJBAAAAA==.',
Ja='Jaelana:BAABLgAECn89AAMMAAgJsxJ8IQC/AQhoDAAACwAmAGkMAAAKADIAawwAAAkANQBqDAAABwAtAGwMAAAIAFYAbQwAAAQAIADqDAAACAA4AG4MAAAEABEADAAICbMSfCEAvwEIaAwAAAUAJgBpDAAABAAyAGsMAAAEADUAagwAAAMALQBsDAAABABWAG0MAAABACAA6gwAAAQAOABuDAAAAQARABoACAmSCNYLAGQBCGgMAAAGACEAaQwAAAYAFgBrDAAABQAbAGoMAAAEABgAbAwAAAQADwBtDAAAAwASAOoMAAAEABUAbgwAAAMADwAAAA==.Jaenerys:BAAALgADCgcJBwABLgAECgEJAQAGAAAAAA==.Jaguarinsito:BAAALgAECgkJBwAAAA==.Janoski:BAAALgADCgEJAQAAAA==.',
Je='Jerrwolf:BAAALgADCggJGQAAAA==.',
Jo='Jorkinit:BAAALgAECgUJCQABLgAFFAEJAQAGAAAAAA==.',
Jp='Jpl:BAAALgAECgkJCwAAAA==.',
Ju='Justuss:BAAALgAECgEJAQAAAA==.',
Ka='Kafka:BAAALgADCgMJAwABLgAECgcJEQAGAAAAAA==.Kamideath:BAAALgAECgQJCAABLgAECgcJOgAOAPAkAA==.Kamidh:BAAALgADCgkJFQABLgAECgcJOgAOAPAkAA==.Kamihunt:BAAALgADCgQJBAABLgAECgcJOgAOAPAkAA==.Kamikozy:BAABLgAECn86AAIOAAcJ8CSiFACEAgdoDAAACgBjAGkMAAAJAGEAawwAAAoAXwBqDAAACABiAGwMAAAIAFsA6gwAAAgAYwBuDAAABQBTAA4ABwnwJKIUAIQCB2gMAAAKAGMAaQwAAAkAYQBrDAAACgBfAGoMAAAIAGIAbAwAAAgAWwDqDAAACABjAG4MAAAFAFMAAAA=.Kasharas:BAABLgAECn8ZAAMMAAgJ1gzkMQBdAQhoDAAABAArAGkMAAADABoAawwAAAQAHgBqDAAAAgAaAGwMAAAEACUAbQwAAAMAPgDqDAAABAAgAG4MAAABAAQADAAICdYM5DEAXQEIaAwAAAMAKwBpDAAAAwAaAGsMAAAEAB4AagwAAAIAGgBsDAAABAAlAG0MAAADAD4A6gwAAAQAIABuDAAAAQAEAAkAAQnpBbWTACMAAWgMAAABAA8AAAA=.Katalena:BAABLgAECn8aAAMQAAcJvyPYHAC9AgdoDAAABQBfAGkMAAAFAF0AawwAAAQAYABqDAAAAwBaAGwMAAADAFsAbQwAAAMASQDqDAAAAwBiABAABwm/I9gcAL0CB2gMAAAEAF8AaQwAAAUAXQBrDAAABABgAGoMAAADAFoAbAwAAAMAWwBtDAAAAgBJAOoMAAADAGIAGwACCRIF7oUAYQACaAwAAAEAEQBtDAAAAQAIAAAA.',
Ke='Keybinds:BAAALgAFFAEJAQAAAA==.',
Kh='Khain:BAAALgAECgEJAQAAAA==.Khealer:BAABLgAECn8VAAIcAAcJPA3uJQAtAQdoDAAABAAeAGkMAAADACAAawwAAAMALQBqDAAAAwA4AGwMAAADABAAbQwAAAEAJgDqDAAABAAQABwABwk8De4lAC0BB2gMAAAEAB4AaQwAAAMAIABrDAAAAwAtAGoMAAADADgAbAwAAAMAEABtDAAAAQAmAOoMAAAEABAAAAA=.Khunter:BAAALgADCgcJBwAAAA==.',
Ki='Kindi:BAABLgAECn8YAAIbAAYJiSL8DgA7AgZoDAAABgBiAGkMAAAEAFcAawwAAAQAXABqDAAABABRAGwMAAADAFAA6gwAAAMAWgAbAAYJiSL8DgA7AgZoDAAABgBiAGkMAAAEAFcAawwAAAQAXABqDAAABABRAGwMAAADAFAA6gwAAAMAWgAAAA==.Kitymeowmeow:BAACLgAFFH8PAAIdAAUJ4iKrAwCFAQVoDAAABABiAGkMAAAEAE0AawwAAAQAWwBqDAAAAQBJAOoMAAACAFkAHQAFCeIiqwMAhQEFaAwAAAQAYgBpDAAABABNAGsMAAAEAFsAagwAAAEASQDqDAAAAgBZAC4ABAp/KwACHQAJCSEmSgIAfAMAHQAJCSEmSgIAfAMAAAA=.',
Kl='Klausnomi:BAACLgAFFH8MAAIJAAQJ8AynFAAbAQRoDAAABAAkAGkMAAADACoAawwAAAIADwDqDAAAAwAmAAkABAnwDKcUABsBBGgMAAAEACQAaQwAAAMAKgBrDAAAAgAPAOoMAAADACYALgAECn8zAAIJAAkJvxcoGgBCAgAJAAkJvxcoGgBCAgAAAA==.',
Ko='Kowalzky:BAAALgAECgQJCAAAAA==.',
Kr='Krow:BAABLgAECn8VAAILAAYJHR9iFwCJAQZoDAAABABSAGkMAAAGAFYAawwAAAQATABqDAAABABbAGwMAAABAFQA6gwAAAIARAALAAYJHR9iFwCJAQZoDAAABABSAGkMAAAGAFYAawwAAAQATABqDAAABABbAGwMAAABAFQA6gwAAAIARAAAAA==.',
Ku='Kuup:BAAALgAECgUJBQAAAA==.',
Ky='Kyrieherbing:BAAALgADCgIJAwAAAA==.Kyruptôs:BAAALgADCgEJAQAAAA==.',
La='Lalisaa:BAAALgAECggJCAABLgAECggJHgAOAJ8bAA==.Lasina:BAAALgADCgMJBQAAAA==.Lastdance:BAAALgAECgYJCwAAAA==.',
Li='Lilithe:BAAALgADCgkJCQAAAA==.Lillyvera:BAAALgAECgEJAQAAAA==.Lilpsycho:BAAALgADCgYJDwAAAA==.',
Lo='Lokie:BAAALgAECgUJDQAAAA==.',
Lu='Lucia:BAABLgAECn8bAAIQAAgJtBFjOgCoAQhoDAAABgAlAGkMAAAFACoAawwAAAUAPABqDAAAAwAtAGwMAAACADUAbQwAAAEAMQDqDAAABAAjAG4MAAABACYAEAAICbQRYzoAqAEIaAwAAAYAJQBpDAAABQAqAGsMAAAFADwAagwAAAMALQBsDAAAAgA1AG0MAAABADEA6gwAAAQAIwBuDAAAAQAmAAAA.',
Ly='Lynth:BAAALgADCgMJAwAAAA==.',
Ma='Magnusbane:BAAALgADCgYJBgABLgAECgcJHAAGAAAAAQ==.Maidokasa:BAAALgADCgUJBwAAAA==.Maja:BAABLgAECn8rAAMBAAgJRR2cBQBuAghoDAAACABTAGkMAAAHAFcAawwAAAkAXQBqDAAAAwAyAGwMAAAGAFAAbQwAAAEAMQDqDAAABgBTAG4MAAADAC0AAQAICUUdnAUAbgIIaAwAAAQAUwBpDAAABABXAGsMAAAEAF0AagwAAAMAMgBsDAAABABQAG0MAAABADEA6gwAAAQAUwBuDAAAAwAtAB4ABQlcFroGAEsBBWgMAAAEAEkAaQwAAAMAQABrDAAABQA+AGwMAAACADQA6gwAAAIAIAAAAA==.Malaqor:BAABLgAECn8vAAIFAAgJdiSlAQAEAwhoDAAABwBiAGkMAAAHAF8AawwAAAcAYABqDAAABgBaAGwMAAAGAFIAbQwAAAQAWQDqDAAABgBdAG4MAAAEAGAABQAICXYkpQEABAMIaAwAAAcAYgBpDAAABwBfAGsMAAAHAGAAagwAAAYAWgBsDAAABgBSAG0MAAAEAFkA6gwAAAYAXQBuDAAABABgAAAA.Malla:BAAALgAECgQJBwAAAA==.Mamagoose:BAAALgADCgcJBwABLgAECggJKwATAGIaAA==.Maylida:BAAALgAECgQJBAABLgAFFAUJBwACALkhAA==.',
Mc='Mcflÿ:BAAALgADCgEJAQAAAA==.',
Me='Megryn:BAAALgAECgMJAwAAAA==.',
Mi='Mistynyxy:BAAALgAECgUJBQAAAA==.',
Mo='Mojojuice:BAABLgAECn8dAAIJAAgJHiQ3BADJAghoDAAABQBeAGkMAAAFAF8AawwAAAQAWgBqDAAABABiAGwMAAADAF8AbQwAAAIAWwDqDAAABABgAG4MAAACAFMACQAICR4kNwQAyQIIaAwAAAUAXgBpDAAABQBfAGsMAAAEAFoAagwAAAQAYgBsDAAAAwBfAG0MAAACAFsA6gwAAAQAYABuDAAAAgBTAAAA.Montar:BAABLgAECn8cAAIRAAYJLCT1GwAFAgZoDAAABgBhAGkMAAAFAFwAawwAAAUAWABqDAAABABdAGwMAAADAFcA6gwAAAUAYQARAAYJLCT1GwAFAgZoDAAABgBhAGkMAAAFAFwAawwAAAUAWABqDAAABABdAGwMAAADAFcA6gwAAAUAYQAAAA==.Moonjuice:BAABLgAECn8kAAMYAAkJ9xF2OQBAAQloDAAABgA1AGkMAAAGADIAawwAAAYANgBqDAAABAAwAGwMAAAEACsAbQwAAAEACADqDAAABgA8AG4MAAACAA4AbwwAAAEATQAYAAgJaBB2OQBAAQhoDAAABQA1AGkMAAAFADIAawwAAAUANgBqDAAAAwAwAGwMAAADACsAbQwAAAEACADqDAAABQA8AG4MAAACAA4AGQAHCagIKysA/gAHaAwAAAEAJQBpDAAAAQAXAGsMAAABAAwAagwAAAEADQBsDAAAAQAAAOoMAAABACkAbwwAAAEAEgAAAA==.Moonlightt:BAAALgAECgQJBAAAAA==.',
Na='Nahaii:BAACLgAFFH8GAAINAAMJRQ26VwDwAANoDAAAAwAcAGkMAAACADYA6gwAAAEAEgANAAMJRQ26VwDwAANoDAAAAwAcAGkMAAACADYA6gwAAAEAEgAuAAQKfyQAAg0ACAmkGnomAPgBAA0ACAmkGnomAPgBAAEuAAUUBQkLABEAnRIA.Nanalli:BAAALgADCgIJAgAAAA==.',
Ne='Nelos:BAABLgAECn8sAAIfAAgJ6hqhCgBUAghoDAAABwBKAGkMAAAHAEoAawwAAAcATwBqDAAABgBOAGwMAAAFADsAbQwAAAMANADqDAAABwBLAG4MAAACADgAHwAICeoaoQoAVAIIaAwAAAcASgBpDAAABwBKAGsMAAAHAE8AagwAAAYATgBsDAAABQA7AG0MAAADADQA6gwAAAcASwBuDAAAAgA4AAAA.Neovisus:BAAALgAFFAEJAQAAAA==.',
Ni='Nia:BAAALgAECggJEgAAAA==.Nineline:BAAALgADCgEJAQABLgAECgYJHQALAOUcAA==.',
No='Nozarashi:BAABLgAECn8bAAINAAYJpR4jNQC2AQZoDAAABgBSAGkMAAAFAFYAawwAAAUASwBqDAAAAwBYAGwMAAACAEAA6gwAAAYAUwANAAYJpR4jNQC2AQZoDAAABgBSAGkMAAAFAFYAawwAAAUASwBqDAAAAwBYAGwMAAACAEAA6gwAAAYAUwAAAA==.',
Ob='Obzen:BAACLgAFFH8FAAILAAMJbBGvIwDbAANoDAAAAwBJAGkMAAABACsA6gwAAAEAEQALAAMJbBGvIwDbAANoDAAAAwBJAGkMAAABACsA6gwAAAEAEQAuAAQKfy0AAgsACQnvHV0TAHYCAAsACQnvHV0TAHYCAAAA.',
Om='Omegalul:BAAALgAECgMJAwABLgAFFAYJFwAOAEAYAA==.',
Oo='Oopsikeelu:BAAALgAECgEJAQAAAA==.',
Pe='Pepperdogs:BAAALgAECgQJBAAAAA==.',
Pi='Pinkember:BAAALgADCgcJBwAAAA==.',
Po='Poisontips:BAAALgAECgMJBAAAAA==.',
Pr='Preast:BAAALgAECgEJAQAAAA==.',
Qk='Qkslvr:BAABLgAECn8kAAIRAAgJ5B1TEQBYAghoDAAABwBUAGkMAAAHAFsAawwAAAYAVQBqDAAABABLAGwMAAAEAFkAbQwAAAEAFQDqDAAABQBcAG4MAAACAEYAEQAICeQdUxEAWAIIaAwAAAcAVABpDAAABwBbAGsMAAAGAFUAagwAAAQASwBsDAAABABZAG0MAAABABUA6gwAAAUAXABuDAAAAgBGAAAA.',
Qu='Quackster:BAAALgAFFAIJAgABLgAFFAUJBwACALkhAA==.',
Ra='Randlidan:BAABLgAECn8YAAISAAgJ+x90CQDLAghoDAAABABYAGkMAAADAFsAawwAAAMAWABqDAAAAwBAAGwMAAAEAEsAbQwAAAMANQDqDAAAAgBWAG4MAAACAFoAEgAICfsfdAkAywIIaAwAAAQAWABpDAAAAwBbAGsMAAADAFgAagwAAAMAQABsDAAABABLAG0MAAADADUA6gwAAAIAVgBuDAAAAgBaAAAA.Randomcow:BAABLgAECn8gAAINAAYJkA7fhgDmAAZoDAAACQAvAGkMAAAHACkAawwAAAcAHwBqDAAAAwAqAGwMAAACABAA6gwAAAQAMQANAAYJkA7fhgDmAAZoDAAACQAvAGkMAAAHACkAawwAAAcAHwBqDAAAAwAqAGwMAAACABAA6gwAAAQAMQAAAA==.',
Re='Reidai:BAAALgAECgIJBAAAAA==.Remixedk:BAAALgAECgcJCgAAAA==.',
Ro='Roargorr:BAAALgAECgUJDgAAAA==.',
Ru='Rutabaga:BAAALgAECgIJAwAAAA==.',
Sa='Sadeas:BAAALgADCgQJBAAAAA==.Sadler:BAAALgADCgcJEwAAAA==.Sanctu:BAAALgAECgUJDgABLgAFFAUJDAAEAPUUAA==.',
Sc='Scarletnight:BAAALgADCgUJBQAAAA==.',
Se='Servusnape:BAAALgAECgEJAQAAAA==.',
Si='Silicos:BAAALgADCgIJAgABLgAECgEJAQAGAAAAAA==.',
Sk='Skywarp:BAAALgAECgcJBwAAAA==.',
Sl='Slapnchop:BAAALgAECgMJAwAAAA==.Slimjaedy:BAAALgAECgEJAQAAAA==.',
Sm='Smightful:BAABLgAECn8UAAIcAAgJRA1xIABWAQhoDAAAAwAfAGkMAAADADwAawwAAAMAJQBqDAAAAwApAGwMAAADADcAbQwAAAEACADqDAAAAwAZAG4MAAABAAsAHAAICUQNcSAAVgEIaAwAAAMAHwBpDAAAAwA8AGsMAAADACUAagwAAAMAKQBsDAAAAwA3AG0MAAABAAgA6gwAAAMAGQBuDAAAAQALAAAA.Smol:BAABLgAECn8XAAIOAAYJuwuchQAWAQZoDAAABQAnAGkMAAAEABcAawwAAAQAFwBqDAAAAwAzAGwMAAACACEA6gwAAAUAHQAOAAYJuwuchQAWAQZoDAAABQAnAGkMAAAEABcAawwAAAQAFwBqDAAAAwAzAGwMAAACACEA6gwAAAUAHQAAAA==.',
St='Stan:BAAALgADCgYJCAABLgAECgcJEQAGAAAAAA==.Strexxi:BAAALgADCgMJBAAAAA==.',
Su='Summerdawn:BAAALgADCgcJGgAAAA==.Supersayan:BAAALgAECgMJAwABLgAFFAEJAQAGAAAAAA==.Superspike:BAACLgAFFH8PAAIOAAUJGx4qIgBqAQVoDAAABABQAGkMAAADAEsAawwAAAMANgBqDAAAAQAZAOoMAAAEAGEADgAFCRseKiIAagEFaAwAAAQAUABpDAAAAwBLAGsMAAADADYAagwAAAEAGQDqDAAABABhAC4ABAp/KwACDgAJCYsjJBgAGgMADgAJCYsjJBgAGgMAAAA=.Surshock:BAABLgAECn8dAAIJAAgJ4RQ7KQDLAQhoDAAABQBCAGkMAAAFAEQAawwAAAUASwBqDAAAAwA7AGwMAAADACYAbQwAAAEAFADqDAAABQA5AG4MAAACAC0ACQAICeEUOykAywEIaAwAAAUAQgBpDAAABQBEAGsMAAAFAEsAagwAAAMAOwBsDAAAAwAmAG0MAAABABQA6gwAAAUAOQBuDAAAAgAtAAAA.',
Sy='Sylaz:BAAALgAECgYJCAAAAA==.',
Ta='Taekay:BAABLgAFFH8GAAMgAAMJ4iAZDAAiAQNoDAAAAgBUAGkMAAACAEYA6gwAAAIAYQAgAAMJ4iAZDAAiAQNoDAAAAQBUAGkMAAABAEYA6gwAAAIAYQANAAIJsgqIigCSAAJoDAAAAQAXAGkMAAABAB8AAS4ABRQHCSAACwDnIQA=.Takamine:BAABLgAECn8kAAIhAAgJRg34CgCGAQhoDAAABQAlAGkMAAAFACAAawwAAAUALwBqDAAABQAnAGwMAAAFADAAbQwAAAMAEgDqDAAABQAhAG4MAAADABMAIQAICUYN+AoAhgEIaAwAAAUAJQBpDAAABQAgAGsMAAAFAC8AagwAAAUAJwBsDAAABQAwAG0MAAADABIA6gwAAAUAIQBuDAAAAwATAAAA.Talath:BAABLgAECn8VAAITAAYJMBWDLQBWAQZoDAAABABAAGkMAAAEAEkAawwAAAMAMQBqDAAABABLAGwMAAAEACwA6gwAAAIAJwATAAYJMBWDLQBWAQZoDAAABABAAGkMAAAEAEkAawwAAAMAMQBqDAAABABLAGwMAAAEACwA6gwAAAIAJwAAAA==.Talos:BAABLgAECn8SAAIEAAgJAAmDgQAmAQhoDAAAAwAPAGkMAAADACgAawwAAAMAJQBqDAAAAgAEAGwMAAACABkAbQwAAAEACwDqDAAAAwAbAG4MAAABAAMABAAICQAJg4EAJgEIaAwAAAMADwBpDAAAAwAoAGsMAAADACUAagwAAAIABABsDAAAAgAZAG0MAAABAAsA6gwAAAMAGwBuDAAAAQADAAAA.',
Te='Terraluna:BAAALgADCgYJBgAAAA==.',
To='Totembutter:BAAALgADCgMJAwAAAA==.',
Tw='Twotswat:BAABLgAECn8kAAQiAAgJpB33DAAqAghoDAAABgBcAGkMAAAFAFcAawwAAAcAWABqDAAABABUAGwMAAAGAE0AbQwAAAEAJQDqDAAABgBgAG4MAAABADIAIgAICVQd9wwAKgIIaAwAAAUAXABpDAAABABXAGsMAAAFAFgAagwAAAQAVABsDAAAAwBHAG0MAAABACUA6gwAAAYAYABuDAAAAQAyABUAAwn8DSwnAJEAA2gMAAABABcAaQwAAAEAIwBrDAAAAQAvACMAAgmtFwAtAI0AAmsMAAABACsAbAwAAAMATQAAAA==.Twysted:BAAALgAECggJDgAAAA==.',
Ug='Ugin:BAAALgADCgYJCAAAAA==.',
Um='Umdrah:BAAALgADCgEJAQAAAA==.',
Va='Valsong:BAAALgADCgcJCwAAAA==.Vanillalatte:BAABLgAECn8aAAIkAAgJNR8RAgBMAghoDAAABABeAGkMAAAEAFYAawwAAAQAVgBqDAAABABQAGwMAAADAFIAbQwAAAEAUwDqDAAABQBXAG4MAAABACUAJAAICTUfEQIATAIIaAwAAAQAXgBpDAAABABWAGsMAAAEAFYAagwAAAQAUABsDAAAAwBSAG0MAAABAFMA6gwAAAUAVwBuDAAAAQAlAAAA.Vanillarista:BAAALgAECggJEQAAAA==.Varwyn:BAAALgADCgMJAwAAAA==.',
Vo='Vonhance:BAAALgAECgEJAQAAAA==.Vonwrath:BAAALgAECgEJAQAAAA==.',
Vy='Vynne:BAAALgADCgcJAQAAAA==.',
Wa='Wakingdeath:BAABLgAECn8UAAINAAYJxBraWwA+AQZoDAAABABQAGkMAAADAD0AawwAAAQAOgBqDAAAAwBXAGwMAAACAE0A6gwAAAQAQQANAAYJxBraWwA+AQZoDAAABABQAGkMAAADAD0AawwAAAQAOgBqDAAAAwBXAGwMAAACAE0A6gwAAAQAQQAAAA==.',
We='Weeple:BAAALgADCgYJBgAAAA==.Wesdarian:BAAALgAECgUJBQAAAA==.',
Wh='Whatdoisay:BAAALgADCgYJBgAAAA==.Whoami:BAABLgAECn8UAAIYAAgJYhGjVABVAQhoDAAAAgBLAGkMAAACAB8AawwAAAIANgBqDAAAAgAoAGwMAAAEAEUAbQwAAAEAFADqDAAABgAuAG4MAAABABEAGAAICWIRo1QAVQEIaAwAAAIASwBpDAAAAgAfAGsMAAACADYAagwAAAIAKABsDAAABABFAG0MAAABABQA6gwAAAYALgBuDAAAAQARAAAA.',
Xe='Xer:BAABLgAECn8UAAIOAAUJuA2MoADkAAVoDAAABAAiAGkMAAAGACMAawwAAAQALQBqDAAAAgAeAOoMAAAEABgADgAFCbgNjKAA5AAFaAwAAAQAIgBpDAAABgAjAGsMAAAEAC0AagwAAAIAHgDqDAAABAAYAAAA.',
Xi='Xirious:BAAALgAFFAIJAwAAAA==.',
Xo='Xor:BAAALgADCgQJBAAAAA==.',
Xu='Xur:BAABLgAECn8oAAIEAAgJ9BxKEABTAghoDAAABwBfAGkMAAAGAFMAawwAAAYARABqDAAABQBcAGwMAAAEADoAbQwAAAIANQDqDAAABwBgAG4MAAADAEAABAAICfQcShAAUwIIaAwAAAcAXwBpDAAABgBTAGsMAAAGAEQAagwAAAUAXABsDAAABAA6AG0MAAACADUA6gwAAAcAYABuDAAAAwBAAAAA.',
Yo='Yonko:BAABLgAECn8hAAMdAAgJBRt+FABJAghoDAAABwBXAGkMAAAFAEEAawwAAAYALwBqDAAAAwBFAGwMAAADAD0A6gwAAAcAUgBuDAAAAQA6AG8MAAABAFAAHQAICQUbfhQASQIIaAwAAAQAVwBpDAAAAwBBAGsMAAAEAC8AagwAAAMARQBsDAAAAwA9AOoMAAAFAFIAbgwAAAEAOgBvDAAAAQBQAAsABAmICy1AAKQABGgMAAADADMAaQwAAAIAIABrDAAAAgATAOoMAAACAA4AAAA=.',
Ys='Ys:BAAALgADCgcJCwABLgAECgYJFwABAPccAA==.',
Ze='Zev:BAAALgADCggJCAAAAA==.',
Zu='Zulgathar:BAAALgADCgYJBgAAAA==.',
['Ís']='Ísolde:BAABLgAECn8eAAQOAAgJnxsHKgAJAghoDAAABQBXAGkMAAAFAEsAawwAAAUASQBqDAAAAwA4AGwMAAAEAF8AbQwAAAIAKQDqDAAABQBQAG4MAAABACkADgAICZ8bByoACQIIaAwAAAUAVwBpDAAABABLAGsMAAAEAEkAagwAAAMAOABsDAAABABfAG0MAAACACkA6gwAAAUAUABuDAAAAQApACUAAQmcGWkMAEwAAWsMAAABAEEAJAABCTwJTwwAMAABaQwAAAEAFwAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
