local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Priest-Discipline','Warlock-Demonology','Warlock-Affliction','DemonHunter-Devourer','DeathKnight-Unholy','Evoker-Augmentation','Druid-Guardian','Druid-Restoration','Paladin-Retribution','Monk-Windwalker','Mage-Frost','Shaman-Elemental','Shaman-Restoration','DeathKnight-Blood','Priest-Shadow','Monk-Mistweaver','Rogue-Subtlety','Warlock-Destruction','Unknown-Unknown','Hunter-Marksmanship','DemonHunter-Vengeance','Evoker-Preservation','Warrior-Fury','Hunter-BeastMastery','Evoker-Devastation','Shaman-Enhancement','Paladin-Holy','Druid-Feral','Rogue-Outlaw','Priest-Holy','Druid-Balance','Mage-Arcane','Paladin-Protection','Monk-Brewmaster','Rogue-Assassination','DeathKnight-Frost',}
local provider = {region='US',realm='Andorhal',name='US',type='daily',zone=46,date='2026-06-17',data={Ad='Adelyne:BAAALgAECgQJAwABLgAFFAUJEgABABkcAA==.Adorablepine:BAABLgAECn8ZAAMCAAcJuANOxQDEAAdoDAAABAAJAGkMAAAEABAAawwAAAQACQBqDAAABAAPAGwMAAAEAAcAbQwAAAIABgDqDAAAAwAGAAIABwmsA07FAMQAB2gMAAAEAAkAaQwAAAQAEABrDAAAAwAIAGoMAAAEAA8AbAwAAAQABwBtDAAAAgAGAOoMAAADAAYAAwABCaoD1UUAIAABawwAAAEACQAAAA==.',
Ag='Agaze:BAACLgAFFH8ZAAIEAAcJESClHADOAQdoDAAABABeAGkMAAADAFIAawwAAAQAWwBqDAAABgBSAGwMAAADAD8AbQwAAAEAUQDqDAAABABPAAQABwkRIKUcAM4BB2gMAAAEAF4AaQwAAAMAUgBrDAAABABbAGoMAAAGAFIAbAwAAAMAPwBtDAAAAQBRAOoMAAAEAE8ALgAECn8WAAIEAAgJEyIAGQC/AgAEAAgJEyIAGQC/AgAAAA==.',
Ai='Aiedel:BAAALgAECgUJCQAAAA==.',
Al='Allesa:BAAALgAECgEJAQAAAA==.',
Ao='Aoise:BAAALgAECgkJCQAAAA==.',
Ap='Applejuuice:BAABLgAFFH8HAAIFAAMJexbumQDbAANoDAAAAwAoAGkMAAADADQA6gwAAAEATwAFAAMJexbumQDbAANoDAAAAwAoAGkMAAADADQA6gwAAAEATwABLgAFFAQJBwAGAMAKAA==.',
Ar='Aratre:BAAALgADCgEJAQAAAA==.Archblade:BAAALgAECgQJBwAAAA==.Arelith:BAAALgAECgMJBwAAAA==.Ariggs:BAAALgAECgEJAQAAAA==.Ariosx:BAABLgAFFH8GAAMHAAIJDAdVNwBIAAJoDAAAAwAIAOoMAAADABsABwACCQwHVTcASAACaAwAAAEACADqDAAAAwAbAAgAAQmzAuJ8ACYAAWgMAAACAAYAAS4ABRQECQ4ACQCGHQA=.Arlen:BAABLgAECn8rAAIJAAkJoBhcMgA3AgloDAAABwBMAGkMAAAGAD8AawwAAAUAVABqDAAABQA3AGwMAAAFADwAbQwAAAMAPADqDAAABQAvAG4MAAAFADIAbwwAAAIAPAAJAAkJoBhcMgA3AgloDAAABwBMAGkMAAAGAD8AawwAAAUAVABqDAAABQA3AGwMAAAFADwAbQwAAAMAPADqDAAABQAvAG4MAAAFADIAbwwAAAIAPAAAAA==.Arma:BAABLgAECn8cAAIKAAgJjiNGBQAwAwhoDAAABABhAGkMAAAEAGEAawwAAAQAWwBqDAAAAwBgAGwMAAADAFsAbQwAAAIAUADqDAAABQBeAG4MAAADAFUACgAICY4jRgUAMAMIaAwAAAQAYQBpDAAABABhAGsMAAAEAFsAagwAAAMAYABsDAAAAwBbAG0MAAACAFAA6gwAAAUAXgBuDAAAAwBVAAEuAAUUBgkZAAsAsyAA.Armadro:BAABLgAFFH8ZAAILAAYJsyAiKQDQAQZoDAAABQBIAGkMAAAFAFcAawwAAAYAQwBqDAAAAwBbAGwMAAABAFwA6gwAAAUAYwALAAYJsyAiKQDQAQZoDAAABQBIAGkMAAAFAFcAawwAAAYAQwBqDAAAAwBbAGwMAAABAFwA6gwAAAUAYwAAAA==.',
Au='Aurky:BAAALgAECgEJAwAAAA==.',
Ba='Bald:BAAALgADCgYJBgAAAA==.Balob:BAACLgAFFH8cAAMMAAgJOxkSEACrAQhoDAAABgBEAGkMAAAFAFoAawwAAAQAUgBqDAAAAQAXAGwMAAABAD4AbQwAAAEAHADqDAAACQBbAG4MAAABABsADAAHCWEZEhAAqwEHaAwAAAYARABpDAAABQBaAGsMAAAEAFIAagwAAAEAFwBtDAAAAQAcAOoMAAAJAFsAbgwAAAEAGwANAAEJvwLmfgA9AAFsDAAAAQAHAC4ABAp/JQACDAAICWolegQAVAMADAAICWolegQAVAMAAAA=.Bandar:BAAALgADCgcJBwAAAA==.',
Be='Beardlylegal:BAAALgAECgEJAQAAAA==.Behodius:BAAALgAECgMJBAAAAA==.Bellafists:BAAALgAECgYJBgAAAA==.Benchwong:BAAALgAFFAEJAQABLgAFFAgJHAAMADsZAA==.',
Bl='Blacksteve:BAAALgAECgIJAgAAAA==.Bloodngore:BAABLgAECn8nAAIOAAkJTxu4CgBlAgloDAAABAA3AGkMAAAEAE4AawwAAAUATABqDAAABQAyAGwMAAAFAFQAbQwAAAUAXQDqDAAABABDAG4MAAAFACkAbwwAAAIAPQAOAAkJTxu4CgBlAgloDAAABAA3AGkMAAAEAE4AawwAAAUATABqDAAABQAyAGwMAAAFAFQAbQwAAAUAXQDqDAAABABDAG4MAAAFACkAbwwAAAIAPQAAAA==.Blumoon:BAAALgAECgEJAQAAAA==.',
Bm='Bmxdh:BAAALgAECgYJDwAAAA==.',
Bo='Bonecollectr:BAAALgAECgkJDgAAAA==.',
Br='Brewswayne:BAAALgAECgEJAQAAAA==.Broku:BAAALgAECggJDQABLgAECgkJLgAJAMcXAA==.Brudah:BAAALgAECgEJAQAAAA==.Brutus:BAAALgAFFAMJBAAAAA==.',
Bu='Bubblelove:BAABLgAECn8kAAIPAAkJTA37JQCcAQloDAAABQAuAGkMAAAGAB8AawwAAAUAJABqDAAABAAYAGwMAAADABoAbQwAAAMAHADqDAAABgAvAG4MAAADACEAbwwAAAEAFgAPAAkJTA37JQCcAQloDAAABQAuAGkMAAAGAB8AawwAAAUAJABqDAAABAAYAGwMAAADABoAbQwAAAMAHADqDAAABgAvAG4MAAADACEAbwwAAAEAFgAAAA==.Bubbly:BAABLgAECn8uAAIJAAkJxxdeQwD8AQloDAAABwA2AGkMAAAHAEoAawwAAAYARQBqDAAABQA/AGwMAAAGADgAbQwAAAMAKADqDAAABwBVAG4MAAAEAFEAbwwAAAEAGAAJAAkJxxdeQwD8AQloDAAABwA2AGkMAAAHAEoAawwAAAYARQBqDAAABQA/AGwMAAAGADgAbQwAAAMAKADqDAAABwBVAG4MAAAEAFEAbwwAAAEAGAAAAA==.Butes:BAAALgAECgkJDwAAAA==.',
Ca='Caelum:BAAALgAECgMJAwAAAA==.Callmepappy:BAAALgADCgUJBQAAAA==.Canníbal:BAAALgAECggJDwAAAA==.',
Ce='Censored:BAAALgADCgIJAgAAAA==.',
Ch='Chopsy:BAACLgAFFH8VAAIKAAQJaCHFCgB0AQRoDAAACABeAGkMAAAFAFIAawwAAAIAUQDqDAAABgBUAAoABAloIcUKAHQBBGgMAAAIAF4AaQwAAAUAUgBrDAAAAgBRAOoMAAAGAFQALgAECn9aAAMKAAkJRyUZAgBQAwAKAAkJRyUZAgBQAwAQAAIJxAvdXgBSAAAAAA==.Chris:BAAALgAECgUJDgAAAA==.Chucklez:BAAALgAFFAIJBAAAAA==.Chulobulo:BAABLgAECn8bAAIRAAkJxxWoFQDxAQloDAAABgAzAGkMAAAFAD4AawwAAAMAKABqDAAAAwAaAGwMAAACAD8AbQwAAAEANADqDAAAAwAvAG4MAAACAEsAbwwAAAIANQARAAkJxxWoFQDxAQloDAAABgAzAGkMAAAFAD4AawwAAAMAKABqDAAAAwAaAGwMAAACAD8AbQwAAAEANADqDAAAAwAvAG4MAAACAEsAbwwAAAIANQAAAA==.Chulosdck:BAAALgAECgYJDwABLgAECgkJGwARAMcVAA==.',
Ci='Cinnabons:BAAALgAFFAEJAQABLgAFFAQJBwAGAMAKAA==.',
Cl='Cleopatrick:BAAALgADCgkJEAAAAA==.',
Co='Cobgoblin:BAAALgAECgEJAQAAAA==.Codingsocks:BAAALgADCgEJAgAAAA==.',
Cr='Crekton:BAAALgAECgMJAwAAAA==.Cronnos:BAAALgAECgYJBwAAAA==.',
Cu='Cudlemonster:BAABLgAECn89AAIBAAkJbAx4JQCjAQloDAAACQAmAGkMAAAJADIAawwAAAkAHQBqDAAABwAfAGwMAAAHAEAAbQwAAAYADgDqDAAABgAhAG4MAAAFAAoAbwwAAAMADQABAAkJbAx4JQCjAQloDAAACQAmAGkMAAAJADIAawwAAAkAHQBqDAAABwAfAGwMAAAHAEAAbQwAAAYADgDqDAAABgAhAG4MAAAFAAoAbwwAAAMADQAAAA==.Cursed:BAACLgAFFH8OAAIDAAQJOxixAwBXAQRoDAAABABOAGkMAAAEADQAawwAAAIAIwDqDAAABABRAAMABAk7GLEDAFcBBGgMAAAEAE4AaQwAAAQANABrDAAAAgAjAOoMAAAEAFEALgAECn9KAAQDAAkJnyFEAQD0AgADAAkJjyFEAQD0AgASAAQJ9hxyDgBVAQACAAMJZQ9w2QClAAAAAA==.',
Da='Dabz:BAABLgAECn8XAAICAAgJhhq7NAAGAghoDAAABQBXAGkMAAAEAEQAawwAAAMAPQBqDAAAAwBgAGwMAAACAEUAbQwAAAEAUADqDAAABAA1AG4MAAABADYAAgAICYYauzQABgIIaAwAAAUAVwBpDAAABABEAGsMAAADAD0AagwAAAMAYABsDAAAAgBFAG0MAAABAFAA6gwAAAQANQBuDAAAAQA2AAAA.Daddyslaps:BAAALgAECgUJBQAAAA==.Daghma:BAAALgAECgYJBgAAAA==.Danyel:BAAALgADCgYJBwAAAA==.Darmok:BAABLgAECn81AAMNAAkJ3yMLBQBjAwloDAAACABjAGkMAAAIAGIAawwAAAcAYgBqDAAABwBhAGwMAAAHAGEAbQwAAAQAUgDqDAAABwBhAG4MAAAEAEkAbwwAAAEAUQANAAkJ3yMLBQBjAwloDAAACABjAGkMAAAIAGIAawwAAAcAYgBqDAAABwBhAGwMAAAHAGEAbQwAAAQAUgDqDAAABwBhAG4MAAADAEkAbwwAAAEAUQAMAAEJbBo1mwBBAAFuDAAAAQBDAAAA.Darzamat:BAAALgADCgEJAQAAAA==.Dawtie:BAAALgAECgQJBQABLgAECgkJDgATAAAAAA==.',
De='Demonbubble:BAACLgAFFH8YAAIEAAcJKw9QJQCYAQdoDAAABAAbAGkMAAAFAEMAawwAAAQAJABqDAAAAwAnAGwMAAABABIAbQwAAAEAGQDqDAAABgA4AAQABwkrD1AlAJgBB2gMAAAEABsAaQwAAAUAQwBrDAAABAAkAGoMAAADACcAbAwAAAEAEgBtDAAAAQAZAOoMAAAGADgALgAECn8tAAIEAAkJvBawLgAMAgAEAAkJvBawLgAMAgAAAA==.Dezric:BAAALgADCgYJDAABLgAECgYJBgATAAAAAA==.Dezruf:BAAALgAECgYJBgAAAA==.',
Do='Dotomic:BAABLgAFFH8LAAICAAUJEx5FNAB1AQVoDAAAAgBbAGkMAAACAGEAawwAAAIAJABqDAAAAQAXAOoMAAAEAFMAAgAFCRMeRTQAdQEFaAwAAAIAWwBpDAAAAgBhAGsMAAACACQAagwAAAEAFwDqDAAABABTAAEuAAUUCAkgABQAiB8A.',
Dr='Drejan:BAAALgAECgcJCQAAAA==.Drfe:BAAALgADCgYJBgAAAA==.Drifthook:BAAALgAECgkJCQAAAA==.Drowarchon:BAAALgADCgIJAgABLgAECgQJBAATAAAAAA==.Drownix:BAAALgAECgQJBAAAAA==.Drowzy:BAAALgADCgYJBAABLgAECgQJBAATAAAAAA==.',
['Dä']='Dämonjäger:BAAALgADCggJCAAAAA==.',
Eb='Ebon:BAAALgADCgMJAwAAAA==.',
Ec='Ecaed:BAABLgAECn8bAAIVAAkJ1gaTEwAZAQloDAAABAAVAGkMAAAEABYAawwAAAQADgBqDAAAAwAKAGwMAAACAAQAbQwAAAEABgDqDAAABgAoAG4MAAACABAAbwwAAAEADQAVAAkJ1gaTEwAZAQloDAAABAAVAGkMAAAEABYAawwAAAQADgBqDAAAAwAKAGwMAAACAAQAbQwAAAEABgDqDAAABgAoAG4MAAACABAAbwwAAAEADQAAAA==.',
Ei='Eisenhørn:BAAALgADCgYJDgAAAA==.',
El='Elektriss:BAAALgAECgQJBAAAAA==.Elnaris:BAABLgAECn8jAAIJAAgJhA22iABeAQhoDAAABgANAGkMAAAGABwAawwAAAUAJABqDAAAAgAIAGwMAAAEABcA6gwAAAcAMwBuDAAAAwAzAG8MAAACACQACQAICYQNtogAXgEIaAwAAAYADQBpDAAABgAcAGsMAAAFACQAagwAAAIACABsDAAABAAXAOoMAAAHADMAbgwAAAMAMwBvDAAAAgAkAAAA.Elohime:BAAALgADCgYJCAAAAA==.',
Eo='Eon:BAAALgAECgIJCQAAAA==.',
Er='Erikkak:BAAALgADCgQJBAAAAA==.Eriu:BAAALgAECgEJAQABLgAFFAQJDgAJAIYdAA==.Erõs:BAAALgAECgYJCwABLgAECgYJFQAWADUZAA==.',
Fe='Fenixbinkle:BAAALgAECgQJBAAAAA==.',
Fi='Fiero:BAAALgAECggJDQABLgAECgkJDgATAAAAAA==.Fire:BAAALgAECgUJBQABLgAFFAYJFQAGAGUbAA==.',
Fr='Fragga:BAABLgAECn8cAAIXAAYJaBbBQgA6AQZoDAAAAwAkAGkMAAAGAEsAawwAAAYANABqDAAAAwAhAGwMAAACACcA6gwAAAgAUgAXAAYJaBbBQgA6AQZoDAAAAwAkAGkMAAAGAEsAawwAAAYANABqDAAAAwAhAGwMAAACACcA6gwAAAgAUgAAAA==.',
Fu='Fullflavor:BAAALgADCgIJAgAAAA==.',
['Fü']='Füran:BAAALgADCgIJAgAAAA==.',
Ga='Ganryu:BAAALgADCgYJCgAAAA==.',
Gb='Gboybalili:BAAALgADCgcJDAAAAA==.',
Gi='Gitzi:BAACLgAFFH8NAAIYAAQJlQsjSwAVAQRoDAAABQAqAGkMAAADACoAawwAAAIAEADqDAAAAwARABgABAmVCyNLABUBBGgMAAAFACoAaQwAAAMAKgBrDAAAAgAQAOoMAAADABEALgAECn9LAAIYAAkJWR0xHABdAgAYAAkJWR0xHABdAgAAAA==.',
Gl='Glaciea:BAAALgADCgMJAwABLgAECggJHgAZAKciAA==.',
Gr='Grayl:BAAALgAECgkJCQAAAA==.Greenrage:BAAALgADCgQJBAAAAA==.Griever:BAAALgAECgYJCQAAAA==.Grizzly:BAAALgAECgUJBgABLgAECggJJwAFAIMOAA==.Groovexgroov:BAABLgAECn8dAAIPAAkJOxhNEQBMAgloDAAAAwBGAGkMAAADAEEAawwAAAMAQQBqDAAABAAsAGwMAAAEAFIAbQwAAAQAQwDqDAAAAwA6AG4MAAADACgAbwwAAAIALgAPAAkJOxhNEQBMAgloDAAAAwBGAGkMAAADAEEAawwAAAMAQQBqDAAABAAsAGwMAAAEAFIAbQwAAAQAQwDqDAAAAwA6AG4MAAADACgAbwwAAAIALgAAAA==.',
Ha='Harlowe:BAAALgADCgYJBQAAAA==.',
He='Healrog:BAAALgAECgYJBgAAAA==.Hellraiser:BAAALgAECgQJBQAAAA==.',
Hi='Highfive:BAAALgADCgIJAgAAAA==.',
Ho='Holyfiero:BAAALgAECgQJBAABLgAECgkJDgATAAAAAA==.Holynight:BAAALgADCgMJBAABLgAECggJJwAFAIMOAA==.Hordend:BAAALgAECgUJEAAAAA==.Hozru:BAAALgADCgEJAQAAAA==.',
Hu='Hulkfists:BAABLgAECn8UAAMMAAYJownMSgAcAQZoDAAABAAaAGkMAAAEAB8AawwAAAQAHwBqDAAAAwAcAGwMAAACAAsA6gwAAAMAFQAMAAYJownMSgAcAQZoDAAAAgAaAGkMAAACAB8AawwAAAIAHwBqDAAAAgAcAGwMAAABAAsA6gwAAAEAFQAaAAYJ3gLVHgDiAAZoDAAAAgAEAGkMAAACAAsAawwAAAIADwBqDAAAAQAEAGwMAAABAAEA6gwAAAIABAAAAA==.',
Hy='Hydration:BAAALgADCgMJAwAAAA==.',
['Hâ']='Hâruka:BAAALgAECgcJBgAAAA==.',
Im='Imcepsy:BAABLgAECn81AAIBAAkJ7BkJDACuAgloDAAACQBhAGkMAAAIAEoAawwAAAgAPwBqDAAABQBTAGwMAAAEAB8AbQwAAAMAJwDqDAAACwBXAG4MAAAEAD4AbwwAAAEAOgABAAkJ7BkJDACuAgloDAAACQBhAGkMAAAIAEoAawwAAAgAPwBqDAAABQBTAGwMAAAEAB8AbQwAAAMAJwDqDAAACwBXAG4MAAAEAD4AbwwAAAEAOgAAAA==.',
Io='Iownzuu:BAAALgADCgMJAwAAAA==.',
Is='Istari:BAAALgAECgIJAgAAAA==.Istark:BAAALgAECgMJAwAAAA==.',
Ja='Jayjay:BAACLgAFFH8KAAILAAQJ7RQSXQAlAQRoDAAAAwAoAGkMAAACACgAawwAAAEAPwDqDAAABABFAAsABAntFBJdACUBBGgMAAADACgAaQwAAAIAKABrDAAAAQA/AOoMAAAEAEUALgAECn8iAAILAAkJsRw6JgCCAgALAAkJsRw6JgCCAgAAAA==.',
Je='Jethroy:BAABLgAECn8VAAIbAAgJbRG9NwBuAQhoDAAAAwAzAGkMAAADADkAawwAAAQASwBqDAAAAgAwAGwMAAABABEAbQwAAAEAEQDqDAAABgA+AG4MAAABABoAGwAICW0RvTcAbgEIaAwAAAMAMwBpDAAAAwA5AGsMAAAEAEsAagwAAAIAMABsDAAAAQARAG0MAAABABEA6gwAAAYAPgBuDAAAAQAaAAAA.',
Jf='Jfkwspvpfldg:BAAALgAECgYJBgAAAA==.',
Ji='Jimmie:BAABLgAECn8aAAIRAAgJuiAkEQCYAghoDAAABQBXAGkMAAAEAGEAawwAAAQAVgBqDAAAAgAlAGwMAAACAEsAbQwAAAMASwDqDAAABQBSAG4MAAABAFIAEQAICbogJBEAmAIIaAwAAAUAVwBpDAAABABhAGsMAAAEAFYAagwAAAIAJQBsDAAAAgBLAG0MAAADAEsA6gwAAAUAUgBuDAAAAQBSAAAA.',
Jo='Johnparstina:BAAALgAECgYJDgAAAA==.Jolty:BAACLgAFFH8KAAIaAAQJNx+XBgBQAQRoDAAABQBhAGkMAAABAFMAawwAAAEALgDqDAAAAwBbABoABAk3H5cGAFABBGgMAAAFAGEAaQwAAAEAUwBrDAAAAQAuAOoMAAADAFsALgAECn8hAAIaAAkJqyMjAgAFAwAaAAkJqyMjAgAFAwAAAA==.',
Jr='Jrbacnchee:BAAALgAECgEJAQAAAA==.Jrbcncheze:BAAALgAECggJEgAAAA==.',
Ka='Kainicus:BAACLgAFFH8TAAIVAAQJURPUBQAIAQRoDAAABgBWAGkMAAAFABAAawwAAAIAJQDqDAAABgA4ABUABAlRE9QFAAgBBGgMAAAGAFYAaQwAAAUAEABrDAAAAgAlAOoMAAAGADgALgAECn9ZAAIVAAkJwRmWBQBKAgAVAAkJwRmWBQBKAgAAAA==.Kainigal:BAAALgADCgYJCwAAAA==.Kainisham:BAAALgADCgcJBwAAAA==.',
Ke='Kelador:BAABLgAECn8mAAIcAAkJQgonGgA8AQloDAAABwAUAGkMAAAHABoAawwAAAYAGgBqDAAAAwARAGwMAAAEABMAbQwAAAEAJgDqDAAABgARAG4MAAADABoAbwwAAAEAIgAcAAkJQgonGgA8AQloDAAABwAUAGkMAAAHABoAawwAAAYAGgBqDAAAAwARAGwMAAAEABMAbQwAAAEAJgDqDAAABgARAG4MAAADABoAbwwAAAEAIgAAAA==.Keoni:BAAALgAECgEJAQAAAA==.Kerrykoppene:BAAALgAECgIJAgAAAA==.',
Kh='Khappucino:BAAALgAECgcJCQAAAA==.Kharibou:BAAALgAECgQJBAAAAA==.Khellendros:BAAALgADCgYJCgAAAA==.Khrism:BAAALgADCgQJBAAAAA==.',
Ki='Kibbi:BAAALgADCgcJBwAAAA==.Kitsyune:BAABLgAECn8fAAIdAAkJ7BeCBQALAgloDAAABQBDAGkMAAAEAC4AawwAAAQAPABqDAAAAwBBAGwMAAAEAEkAbQwAAAIAQADqDAAABgA+AG4MAAACAEAAbwwAAAEAMQAdAAkJ7BeCBQALAgloDAAABQBDAGkMAAAEAC4AawwAAAQAPABqDAAAAwBBAGwMAAAEAEkAbQwAAAIAQADqDAAABgA+AG4MAAACAEAAbwwAAAEAMQAAAA==.',
Kj='Kjartan:BAAALgAECgUJBgAAAA==.',
Kl='Kløey:BAACLgAFFH8GAAIRAAMJ5gtTKgDbAANoDAAAAwArAGkMAAACACUA6gwAAAEACgARAAMJ5gtTKgDbAANoDAAAAwArAGkMAAACACUA6gwAAAEACgAuAAQKfxQAAhEABgnZFMsuAI0BABEABgnZFMsuAI0BAAAA.',
La='Laethys:BAAALgADCggJCAABLgAECgkJIQALAEIeAA==.',
Li='Lithini:BAAALgAECgQJCQAAAA==.',
Lo='Lowtech:BAAALgAECgMJAwAAAA==.',
Lu='Luminusrayne:BAACLgAFFH8PAAIeAAMJYQXqJwCEAANoDAAABwARAGkMAAAEAA0A6gwAAAQACgAeAAMJYQXqJwCEAANoDAAABwARAGkMAAAEAA0A6gwAAAQACgAuAAQKf0YAAwEACQm8DQMiAIQBAAEACAn8CgMiAIQBAB4ACQk+DIgyAD8BAAAA.Lussypipz:BAABLgAFFH8GAAIfAAMJLwX/OQCSAANoDAAAAgALAGkMAAACAAoA6gwAAAIAEQAfAAMJLwX/OQCSAANoDAAAAgALAGkMAAACAAoA6gwAAAIAEQABLgAFFAMJBgARAOYLAA==.',
Ma='Mahwe:BAAALgAECggJDgAAAA==.Manafest:BAAALgAECgMJCgAAAA==.Maros:BAABLgAECn8kAAMLAAkJWhajOQAyAgloDAAABQA/AGkMAAAEAE8AawwAAAQAMwBqDAAABQBBAGwMAAAFADwAbQwAAAQAPQDqDAAABQA2AG4MAAADAC8AbwwAAAEAJgALAAkJWhajOQAyAgloDAAABAA/AGkMAAAEAE8AawwAAAQAMwBqDAAABQBBAGwMAAAFADwAbQwAAAQAPQDqDAAABQA2AG4MAAADAC8AbwwAAAEAJgAgAAEJJA+2FgA2AAFoDAAAAQAmAAAA.',
Me='Meheret:BAACLgAFFH8GAAILAAMJwADXqQCAAANoDAAABAACAGkMAAABAAIA6gwAAAEAAAALAAMJwADXqQCAAANoDAAABAACAGkMAAABAAIA6gwAAAEAAAAuAAQKf0EAAgsACQlmBqOsACcBAAsACQlmBqOsACcBAAAA.Melissenia:BAAALgAECgQJBAAAAA==.Menious:BAAALgAECgEJAQAAAA==.Mepha:BAAALgAECggJDwAAAA==.',
Mi='Mint:BAABLgAECn8hAAILAAkJQh5dIwDlAgloDAAABgBXAGkMAAAFAF8AawwAAAUAWQBqDAAABABcAGwMAAAEAFcAbQwAAAIASQDqDAAABABcAG4MAAACACgAbwwAAAEANQALAAkJQh5dIwDlAgloDAAABgBXAGkMAAAFAF8AawwAAAUAWQBqDAAABABcAGwMAAAEAFcAbQwAAAIASQDqDAAABABcAG4MAAACACgAbwwAAAEANQAAAA==.',
Mo='Mokth:BAAALgADCgMJAwAAAA==.Mom:BAAALgAECgIJAgAAAA==.Mooby:BAABLgAECn8XAAIRAAgJjRocGABHAghoDAAAAwBBAGkMAAADAD8AawwAAAMATgBqDAAAAwA9AGwMAAADAEwAbQwAAAIAQwDqDAAAAwBJAG4MAAADADIAEQAICY0aHBgARwIIaAwAAAMAQQBpDAAAAwA/AGsMAAADAE4AagwAAAMAPQBsDAAAAwBMAG0MAAACAEMA6gwAAAMASQBuDAAAAwAyAAAA.Moomu:BAAALgAECgUJBQAAAA==.Moonfury:BAAALgAECgEJAQAAAA==.Moonleigh:BAAALgADCgMJBAAAAA==.Morganthe:BAAALgAECgIJAwAAAA==.Moria:BAAALgAECgUJBgAAAA==.',
Mu='Munt:BAAALgAECgQJBAABLgAECgkJIQALAEIeAA==.',
My='Mypriiest:BAAALgAECgQJBAAAAA==.Myroguëë:BAAALgADCgUJBQAAAA==.Mystx:BAABLgAFFH8KAAILAAIJBhg4mACbAAJoDAAABQA3AOoMAAAFAEMACwACCQYYOJgAmwACaAwAAAUANwDqDAAABQBDAAEuAAUUBAkOAAkAhh0A.Mythx:BAACLgAFFH8LAAIXAAQJgh7cFgBZAQRoDAAABABDAGkMAAACAF0AawwAAAEASADqDAAABABOABcABAmCHtwWAFkBBGgMAAAEAEMAaQwAAAIAXQBrDAAAAQBIAOoMAAAEAE4ALgAECn83AAIXAAkJmSYwAQBzAwAXAAkJmSYwAQBzAwABLgAFFAQJDgAJAIYdAA==.Mywarr:BAAALgADCgMJAwAAAA==.',
Na='Naturemage:BAAALgAECgUJBwAAAA==.Natâsi:BAACLgAFFH8KAAIbAAMJZxQ6LQDGAANoDAAABAAmAGkMAAACACoA6gwAAAQASwAbAAMJZxQ6LQDGAANoDAAABAAmAGkMAAACACoA6gwAAAQASwAuAAQKfy8AAhsACQmkGV0ZADwCABsACQmkGV0ZADwCAAAA.',
Ne='Nerazul:BAABLgAECn8VAAQDAAYJph/GBQAKAgZoDAAABQBaAGkMAAAEAFEAawwAAAQASgBqDAAAAgA7AGwMAAACAEgA6gwAAAQAVAADAAYJph/GBQAKAgZoDAAAAwBaAGkMAAADAFEAawwAAAMASgBqDAAAAgA7AGwMAAACAEgA6gwAAAQAVAACAAMJ3wqC4wCTAANoDAAAAQAdAGkMAAABABwAawwAAAEAGQASAAEJ/AgReAAsAAFoDAAAAQAXAAAA.Netharec:BAAALgADCgEJAQABLgAFFAYJFwAPAPgcAA==.Nevai:BAABLgAECn8YAAIbAAkJCxIDIgD0AQloDAAAAwA5AGkMAAADAFAAawwAAAMANgBqDAAAAwAjAGwMAAACAAcAbQwAAAEAIQDqDAAABgA9AG4MAAACAEIAbwwAAAEAEwAbAAkJCxIDIgD0AQloDAAAAwA5AGkMAAADAFAAawwAAAMANgBqDAAAAwAjAGwMAAACAAcAbQwAAAEAIQDqDAAABgA9AG4MAAACAEIAbwwAAAEAEwAAAA==.',
Ni='Nielas:BAABLgAECn8UAAIFAAgJ7yAAKQBdAghoDAAABABiAGkMAAADAE0AawwAAAMAOQBqDAAAAgBjAGwMAAACAFUAbQwAAAIAWADqDAAAAwBYAG4MAAABAF4ABQAICe8gACkAXQIIaAwAAAQAYgBpDAAAAwBNAGsMAAADADkAagwAAAIAYwBsDAAAAgBVAG0MAAACAFgA6gwAAAMAWABuDAAAAQBeAAAA.Nihilus:BAACLgAFFH8SAAIFAAYJJxuTCACMAQZoDAAAAwBNAGkMAAACACcAawwAAAMALwBqDAAAAQAVAOoMAAAIAFoAbgwAAAEAXAAFAAYJJxuTCACMAQZoDAAAAwBNAGkMAAACACcAawwAAAMALwBqDAAAAQAVAOoMAAAIAFoAbgwAAAEAXAAuAAQKfxUAAgUABwkWJLkvAHkCAAUABwkWJLkvAHkCAAAA.Nilari:BAABLgAECn8UAAIhAAYJIQl7MACkAAZoDAAABAAWAGkMAAADACsAawwAAAMAGgBqDAAAAwAQAGwMAAACAAkA6gwAAAUADgAhAAYJIQl7MACkAAZoDAAABAAWAGkMAAADACsAawwAAAMAGgBqDAAAAwAQAGwMAAACAAkA6gwAAAUADgAAAA==.Nine:BAAALgADCgYJBgABLgAFFAQJFQAKAGghAA==.',
No='Noctazari:BAAALgADCgUJBQAAAA==.Noctium:BAABLgAECn8eAAIZAAgJpyL5AgB7AghoDAAABABTAGkMAAAFAFkAawwAAAUAUQBqDAAABABXAGwMAAADAGEAbQwAAAMAXwDqDAAABQBZAG4MAAABAFQAGQAICaci+QIAewIIaAwAAAQAUwBpDAAABQBZAGsMAAAFAFEAagwAAAQAVwBsDAAAAwBhAG0MAAADAF8A6gwAAAUAWQBuDAAAAQBUAAAA.Nostrildamus:BAAALgAECgYJEQABLgAECgkJGAAJADYYAA==.',
Nz='Nzoth:BAAALgADCgYJBgAAAA==.',
Of='Officimeeg:BAAALgAECgEJAQAAAA==.',
Ow='Owlaf:BAAALgAECgIJAgABLgAFFAYJHgABAB8aAA==.Owlchi:BAACLgAFFH8FAAIQAAQJ8wwZNgDQAARoDAAAAQAQAGkMAAABABsAawwAAAEAKQDqDAAAAgAuABAABAnzDBk2ANAABGgMAAABABAAaQwAAAEAGwBrDAAAAQApAOoMAAACAC4ALgAECn8WAAMQAAcJLR22GQBKAgAQAAcJLR22GQBKAgAiAAUJkQ/hTADLAAABLgAFFAYJHgABAB8aAA==.Owls:BAACLgAFFH8eAAIBAAYJHxp5FADhAQZoDAAABwBNAGkMAAAHAEMAawwAAAUAPgBqDAAAAwBRAGwMAAABABcA6gwAAAcAWAABAAYJHxp5FADhAQZoDAAABwBNAGkMAAAHAEMAawwAAAUAPgBqDAAAAwBRAGwMAAABABcA6gwAAAcAWAAuAAQKfzkAAwEACQkWIyIHAAoDAAEACQmGICIHAAoDAB4ABwkbJPcKAJ8CAAEuAAUUBgkeAAEAHxoA.',
Pa='Pallywhacker:BAAALgAECgUJBQAAAA==.Panconcaca:BAAALgAFFAcJAwAAAA==.Pantsokay:BAAALgADCgEJAQAAAA==.',
Pe='Peach:BAABLgAECn8cAAMjAAgJ4Q3sCwBwAQhoDAAABAA0AGkMAAAEAD8AawwAAAQAJABqDAAABAA7AGwMAAAEACMAbQwAAAIAEADqDAAABAAcAG4MAAACAA0AIwAICeEN7AsAcAEIaAwAAAMANABpDAAABAA/AGsMAAADACQAagwAAAIAOwBsDAAAAgAjAG0MAAACABAA6gwAAAMAHABuDAAAAQANABEABglQAZ5LAM0ABmgMAAABAAMAawwAAAEAAgBqDAAAAgAEAGwMAAACAAcA6gwAAAEAAgBuDAAAAQABAAAA.Peaches:BAAALgAECgEJAgAAAA==.Petsmart:BAAALgAECgQJBQAAAA==.',
Pi='Pinesol:BAAALgADCgcJBwAAAA==.',
Po='Potatoeshot:BAAALgAECgQJBQAAAA==.',
Pr='Praisethesun:BAAALgAECgQJCQAAAA==.Prayxx:BAAALgAECgYJCQAAAA==.Pretzel:BAACLgAFFH8SAAIFAAUJKSXUMACkAQVoDAAABABgAGkMAAAEAF4AawwAAAMAWQBqDAAAAgBVAOoMAAAFAGMABQAFCSkl1DAApAEFaAwAAAQAYABpDAAABABeAGsMAAADAFkAagwAAAIAVQDqDAAABQBjAC4ABAp/NAADBQAJCWMlngQAigMABQAJCWMlngQAigMAJAABCTkhqjEAVgAAAAA=.Proved:BAABLgAECn9NAAIeAAkJkR1CCgDDAgloDAAADQBjAGkMAAALAEUAawwAAAoAXQBqDAAACwBaAGwMAAAKAFcAbQwAAAUANwDqDAAACwBdAG4MAAAFAFAAbwwAAAEADAAeAAkJkR1CCgDDAgloDAAADQBjAGkMAAALAEUAawwAAAoAXQBqDAAACwBaAGwMAAAKAFcAbQwAAAUANwDqDAAACwBdAG4MAAAFAFAAbwwAAAEADAAAAA==.',
Ps='Psillycybin:BAAALgAECgcJDQABLgAECgkJQgAeAP0JAA==.',
Pu='Puddingface:BAAALgADCgkJCQAAAA==.Puggar:BAAALgADCgQJBgAAAA==.Pulpp:BAAALgAECgIJAgAAAA==.Pumpspotter:BAAALgAECgkJEgAAAA==.',
Qu='Quiescence:BAAALgADCgYJBgAAAA==.',
Ra='Rakkór:BAAALgAECgEJAgAAAA==.Ranas:BAAALgADCgIJAgAAAA==.Ranessandi:BAAALgAECgEJAQAAAA==.Ratlemebonez:BAAALgAECgEJAQAAAA==.Ravèn:BAAALgAECgcJEQAAAA==.Rayana:BAAALgADCgYJBgAAAA==.Razeal:BAAALgAECgYJDwAAAA==.',
Re='Regerax:BAAALgAFFAIJAwABLgAFFAQJDgAJAIYdAA==.Rene:BAEALgAECggJCgAAAA==.Rev:BAAALgADCgEJAQAAAA==.',
Rh='Rhysan:BAACLgAFFH8NAAINAAQJUBtoKQA/AQRoDAAAAwAcAGkMAAAEAD0AawwAAAIAXwDqDAAABABdAA0ABAlQG2gpAD8BBGgMAAADABwAaQwAAAQAPQBrDAAAAgBfAOoMAAAEAF0ALgAECn87AAINAAkJvReFNgDWAQANAAkJvReFNgDWAQAAAA==.Rhyuk:BAAALgADCgQJBAAAAA==.',
Ri='Rimzak:BAAALgAECgMJAwABLgAECgkJDgATAAAAAA==.Ristria:BAAALgADCgYJEAABLgAECgYJHwAJADgSAA==.Rizy:BAABLgAECn8iAAIFAAkJpA9yTQDaAQloDAAABQAuAGkMAAAFACcAawwAAAUAHwBqDAAABAA9AGwMAAADAB8AbQwAAAIAJQDqDAAABQA5AG4MAAADACkAbwwAAAIAIgAFAAkJpA9yTQDaAQloDAAABQAuAGkMAAAFACcAawwAAAUAHwBqDAAABAA9AGwMAAADAB8AbQwAAAIAJQDqDAAABQA5AG4MAAADACkAbwwAAAIAIgAAAA==.',
Ro='Robonord:BAAALgAECgIJAgAAAA==.Rokki:BAAALgADCgIJAgAAAA==.',
Ru='Rude:BAAALgADCgcJCwAAAA==.',
Ry='Rynhart:BAAALgADCgUJBQAAAA==.Ryntard:BAAALgAECgYJBgAAAA==.Ryushi:BAACLgAFFH8UAAIEAAQJ4hS3RAAZAQRoDAAABwBEAGkMAAAFADIAawwAAAIAHwDqDAAABgBAAAQABAniFLdEABkBBGgMAAAHAEQAaQwAAAUAMgBrDAAAAgAfAOoMAAAGAEAALgAECn9IAAIEAAkJxiAoGgB3AgAEAAkJxiAoGgB3AgAAAA==.',
Sa='Sacerdote:BAABLgAECn8UAAICAAYJPiFoTgCvAQZoDAAABABLAGkMAAAEAFoAawwAAAQAXQBqDAAAAQBOAGwMAAABAE0A6gwAAAYAVwACAAYJPiFoTgCvAQZoDAAABABLAGkMAAAEAFoAawwAAAQAXQBqDAAAAQBOAGwMAAABAE0A6gwAAAYAVwAAAA==.Sakari:BAAALgADCgcJEAAAAA==.Sandara:BAAALgADCgYJBgAAAA==.Sangre:BAAALgADCgIJAgABLgAECgMJBAATAAAAAA==.Sarasara:BAAALgADCgUJBQAAAA==.Sathicus:BAAALgAECgMJAwAAAA==.',
Sc='Scoots:BAAALgAECgUJCAABLgAFFAQJFQAKAGghAA==.Scratster:BAAALgAECgcJCAAAAA==.',
Se='Sebnoth:BAABLgAECn8zAAIFAAkJtCDBEwDRAgloDAAACQBTAGkMAAAIAFkAawwAAAgAVQBqDAAABgBYAGwMAAAGAFsAbQwAAAIAUgDqDAAABgBGAG4MAAAEAFgAbwwAAAIATQAFAAkJtCDBEwDRAgloDAAACQBTAGkMAAAIAFkAawwAAAgAVQBqDAAABgBYAGwMAAAGAFsAbQwAAAIAUgDqDAAABgBGAG4MAAAEAFgAbwwAAAIATQAAAA==.',
Sh='Shadowspark:BAAALgAECgYJCgAAAA==.Shalashaska:BAAALgADCgEJAQAAAA==.Shamantastik:BAAALgAECgMJAwAAAA==.Shiden:BAAALgAECgYJDwAAAA==.Shift:BAAALgADCgkJCQAAAA==.Shiift:BAAALgADCgYJBwAAAA==.Shockblocked:BAAALgADCgQJBAAAAA==.',
Si='Sidepiece:BAAALgADCgcJCAAAAA==.Sillyderek:BAACLgAFFH8GAAIhAAIJSghGFQBQAAJoDAAABQAjAOoMAAABAAYAIQACCUoIRhUAUAACaAwAAAUAIwDqDAAAAQAGAC4ABAp/HQACIQAHCacN8yEABQEAIQAHCacN8yEABQEAAAA=.',
Sl='Slashology:BAAALgAECgYJDAAAAA==.',
Sm='Smallpally:BAABLgAECn8UAAIJAAcJBRVjfwBwAQdoDAAABQBHAGkMAAAFAEMAawwAAAMAPQBqDAAAAQBVAGwMAAABAAYAbQwAAAEALADqDAAABABHAAkABwkFFWN/AHABB2gMAAAFAEcAaQwAAAUAQwBrDAAAAwA9AGoMAAABAFUAbAwAAAEABgBtDAAAAQAsAOoMAAAEAEcAAAA=.',
So='Soarsha:BAAALgAECgIJAgAAAA==.Solarida:BAABLgAECn8mAAIJAAgJShq1RAD4AQhoDAAABQBDAGkMAAAFAEUAawwAAAUANwBqDAAABQBNAGwMAAAFAEAAbQwAAAEASgDqDAAACQBHAG4MAAADAEQACQAICUoatUQA+AEIaAwAAAUAQwBpDAAABQBFAGsMAAAFADcAagwAAAUATQBsDAAABQBAAG0MAAABAEoA6gwAAAkARwBuDAAAAwBEAAAA.',
Sr='Srsawyer:BAABLgAECn8bAAICAAgJSA/nYACnAQhoDAAABAA9AGkMAAAEACcAawwAAAUAKABqDAAABABLAGwMAAADAEEAbQwAAAIAGwDqDAAABAAjAG4MAAABAAQAAgAICUgP52AApwEIaAwAAAQAPQBpDAAABAAnAGsMAAAFACgAagwAAAQASwBsDAAAAwBBAG0MAAACABsA6gwAAAQAIwBuDAAAAQAEAAAA.',
St='Staralfur:BAAALgADCgcJBwAAAA==.Stevokerjobs:BAABLgAECn8VAAQWAAYJNRnzGQA4AQZoDAAABABRAGkMAAAEAFQAawwAAAQAPABqDAAAAgAwAGwMAAABAD0A6gwAAAYAMQAWAAQJBRvzGQA4AQRoDAAAAgBRAGkMAAABAFQAawwAAAEAPADqDAAAAQAxABkABglrElAgACsBBmgMAAABADcAaQwAAAEAKwBrDAAAAQADAGoMAAACAC8AbAwAAAEANADqDAAABABQAAYABAlEE+lQAOsABGgMAAABAB0AaQwAAAIAMgBrDAAAAgAjAOoMAAABAFEAAAA=.Stormshäde:BAAALgAFFAEJAwAAAA==.Stratos:BAAALgADCgcJBwAAAA==.',
Su='Sumlkithot:BAAALgAECgQJAQAAAA==.Sunwa:BAACLgAFFH8OAAMJAAQJhh2FKQBmAQRoDAAABgBQAGkMAAABAFkAawwAAAEAOQDqDAAABgBKAAkABAmGHYUpAGYBBGgMAAAGAFAAaQwAAAEAWQBrDAAAAQA5AOoMAAAEAEoAIQABCY8DshwAIAAB6gwAAAIACQAuAAQKfyEAAwkACAlZIFA6ABoCAAkACAlZIFA6ABoCACEABgnxCsssALgAAAAA.',
['Sï']='Sïmba:BAAALgAECgMJCQAAAA==.',
Ta='Talyashamwow:BAAALgADCgYJBgAAAA==.',
Te='Terzhull:BAAALgADCgIJAgAAAA==.',
Th='Thepride:BAAALgAECggJDwAAAA==.',
Ti='Timmytim:BAAALgAECgQJCAAAAA==.Tired:BAAALgAECgUJBgAAAA==.',
To='Tool:BAACLgAFFH8ZAAILAAgJHBvBAADdAghoDAAAAwBjAGkMAAAFAGEAawwAAAUAWwBqDAAABABFAGwMAAABAB8AbQwAAAEAIQDqDAAABQBjAG4MAAABACAACwAICRwbwQAA3QIIaAwAAAMAYwBpDAAABQBhAGsMAAAFAFsAagwAAAQARQBsDAAAAQAfAG0MAAABACEA6gwAAAUAYwBuDAAAAQAgAC4ABAp/JgACCwAJCeskYwIA2AMACwAJCeskYwIA2AMAAS4ABRQJCS8ABAARJQA=.Tooms:BAAALgAECgcJBwAAAA==.Touchi:BAAALgAECggJDAABLgAECgkJKQAcABkcAA==.',
Tr='Troljin:BAAALgADCgEJAQAAAA==.',
Tu='Tuo:BAABLgAECn8pAAIcAAkJGRzuBQCNAgloDAAACABeAGkMAAAGAFMAawwAAAYASwBqDAAABABYAGwMAAADAD0AbQwAAAMARADqDAAABQBEAG4MAAAFAEEAbwwAAAEAOwAcAAkJGRzuBQCNAgloDAAACABeAGkMAAAGAFMAawwAAAYASwBqDAAABABYAGwMAAADAD0AbQwAAAMARADqDAAABQBEAG4MAAAFAEEAbwwAAAEAOwAAAA==.Turbid:BAABLgAECn9EAAIEAAkJvhf6JwArAgloDAAACQBKAGkMAAAIAEcAawwAAAgAPgBqDAAACAA0AGwMAAAIADkAbQwAAAcAPADqDAAABwAzAG4MAAAHADcAbwwAAAYANAAEAAkJvhf6JwArAgloDAAACQBKAGkMAAAIAEcAawwAAAgAPgBqDAAACAA0AGwMAAAIADkAbQwAAAcAPADqDAAABwAzAG4MAAAHADcAbwwAAAYANAAAAA==.',
Ty='Ty:BAAALgAECgUJDAAAAA==.Tytank:BAAALgADCgMJBAAAAA==.',
Uh='Uhavemyrice:BAAALgADCgIJAgAAAA==.',
Ve='Velkin:BAAALgAECgEJAQAAAA==.',
Vi='Vivia:BAAALgADCgQJBAAAAA==.Viviann:BAAALgADCgMJAwAAAA==.Vivians:BAAALgADCggJCgAAAA==.',
Vo='Voutecomer:BAAALgADCggJDAAAAA==.',
Wa='Walls:BAABLgAECn8YAAIJAAkJNhg7MwAzAgloDAAABABEAGkMAAAEAFgAawwAAAQAVABqDAAAAgBJAGwMAAACADcAbQwAAAIAIADqDAAAAwArAG4MAAACAFQAbwwAAAEAJQAJAAkJNhg7MwAzAgloDAAABABEAGkMAAAEAFgAawwAAAQAVABqDAAAAgBJAGwMAAACADcAbQwAAAIAIADqDAAAAwArAG4MAAACAFQAbwwAAAEAJQAAAA==.Warrach:BAAALgADCgQJBAAAAA==.',
We='Welchnut:BAAALgADCgEJAQAAAA==.Wennoe:BAAALgADCgIJAgAAAA==.Westirras:BAABLgAECn8iAAMJAAgJHRBgeAB9AQhoDAAABwAdAGkMAAAGADEAawwAAAUAHABqDAAAAwAjAGwMAAAFACoAbQwAAAEAIQDqDAAABAA2AG4MAAADADIACQAICR0QYHgAfQEIaAwAAAcAHQBpDAAABgAxAGsMAAAFABwAagwAAAMAIwBsDAAABQAqAG0MAAABACEA6gwAAAMANgBuDAAAAgAyABsAAglNCIp/AE0AAuoMAAABACQAbgwAAAEABgAAAA==.',
Wo='Wobblepox:BAAALgAECgkJCAAAAA==.',
Ya='Yarrow:BAAALgAECgMJBgAAAA==.',
Yo='Yogurt:BAAALgAECgcJEgABLgAECgkJLgAJAMcXAA==.',
Yu='Yusuke:BAABLgAECn8WAAMiAAcJfhF1KwBcAQdoDAAABABEAGkMAAAEACoAawwAAAQASgBqDAAAAwAXAGwMAAADABoA6gwAAAMAJABuDAAAAQATACIABwl+EXUrAFwBB2gMAAACAEQAaQwAAAIAKgBrDAAAAgBKAGoMAAACABcAbAwAAAIAGgDqDAAAAgAkAG4MAAABABMAEAAGCT0JckAA4AAGaAwAAAIAHQBpDAAAAgAnAGsMAAACABkAagwAAAEABQBsDAAAAQANAOoMAAABABsAAS4ABAoJCScADgBPGwA=.',
Za='Zabuzabuza:BAAALgAECgIJAgABLgAECgYJFQAWADUZAA==.Zazabandit:BAAALgADCgUJBQAAAA==.',
Zo='Zolleta:BAAALgAECgQJBAAAAA==.',
Zu='Zuesulty:BAAALgADCgYJBgAAAA==.Zunden:BAABLgAECn8YAAMWAAgJWg9WEwCUAQhoDAAABAAmAGkMAAAEABsAawwAAAQAOQBqDAAABAAeAGwMAAACACQAbQwAAAEAHgDqDAAABAA+AG4MAAABAB8AFgAICVoPVhMAlAEIaAwAAAQAJgBpDAAABAAbAGsMAAAEADkAagwAAAMAHgBsDAAAAgAkAG0MAAABAB4A6gwAAAQAPgBuDAAAAQAfAAYAAQkAAD2qAAAAAWoMAAABAB8AAAA=.',
['Éz']='Ézon:BAAALgADCggJCAAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
