local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Warlock-Demonology','Warlock-Affliction','Warlock-Destruction','Paladin-Retribution','Rogue-Subtlety','Mage-Arcane','Druid-Balance','Unknown-Unknown','DemonHunter-Vengeance','Warrior-Fury','Warrior-Protection','DemonHunter-Devourer','Priest-Holy','Priest-Discipline','Shaman-Restoration','Shaman-Elemental','Warrior-Arms','Monk-Mistweaver','DeathKnight-Frost','Hunter-Survival','Hunter-Marksmanship','Hunter-BeastMastery','DemonHunter-Havoc','Mage-Frost','Druid-Restoration','Priest-Shadow','Paladin-Holy','Monk-Brewmaster','Monk-Windwalker','Shaman-Enhancement','Druid-Guardian','Druid-Feral','DeathKnight-Unholy','Evoker-Preservation','DeathKnight-Blood','Mage-Fire','Evoker-Augmentation','Evoker-Devastation',}
local provider = {region='US',realm='Muradin',name='US',type='daily',zone=46,date='2026-06-03',data={Aa='Aandra:BAABLgAECn8wAAQBAAkJLiDlFwDFAgloDAAABwBcAGkMAAAHAE4AawwAAAcAWABqDAAABQBfAGwMAAADAEEAbQwAAAMAUADqDAAACQBZAG4MAAAFAFMAbwwAAAIATwABAAkJLiDlFwDFAgloDAAABgBcAGkMAAAHAE4AawwAAAYAWABqDAAABQBfAGwMAAADAEEAbQwAAAMAUADqDAAACABZAG4MAAAFAFMAbwwAAAIATwACAAIJGxY+HACRAAJoDAAAAQAfAOoMAAABAFEAAwABCQQDA34AHgABawwAAAEABwAAAA==.',
Ab='Abc:BAAALgAECgYJCgAAAA==.',
Ad='Addely:BAAALgAECgYJBgAAAA==.Adelyy:BAAALgAECgEJAQAAAA==.',
Ae='Aeliena:BAAALgAECgUJDAAAAA==.Aenstar:BAAALgADCgMJAwAAAA==.',
Ag='Agwyon:BAABLgAECn8eAAIEAAcJqRqucACbAQdoDAAABwBdAGkMAAAGAE0AawwAAAYAQQBqDAAAAgA+AGwMAAAEABsA6gwAAAQAWABuDAAAAQA5AAQABwmpGq5wAJsBB2gMAAAHAF0AaQwAAAYATQBrDAAABgBBAGoMAAACAD4AbAwAAAQAGwDqDAAABABYAG4MAAABADkAAAA=.',
Ai='Aithis:BAEALgAECgQJEQAAAA==.',
Al='Alerion:BAABLgAECn8sAAIFAAkJKhk7CwBgAgloDAAABgBLAGkMAAAGADgAawwAAAUAMgBqDAAABQBNAGwMAAAFAFMAbQwAAAQARgDqDAAABwBIAG4MAAAFAEUAbwwAAAEAJgAFAAkJKhk7CwBgAgloDAAABgBLAGkMAAAGADgAawwAAAUAMgBqDAAABQBNAGwMAAAFAFMAbQwAAAQARgDqDAAABwBIAG4MAAAFAEUAbwwAAAEAJgAAAA==.Allan:BAABLgAECn8rAAIGAAkJbiHhAADMAgloDAAABgBUAGkMAAAFAFMAawwAAAUAWQBqDAAABQBIAGwMAAAFAF4AbQwAAAQAWQDqDAAABwBNAG4MAAAEAEgAbwwAAAIAXAAGAAkJbiHhAADMAgloDAAABgBUAGkMAAAFAFMAawwAAAUAWQBqDAAABQBIAGwMAAAFAF4AbQwAAAQAWQDqDAAABwBNAG4MAAAEAEgAbwwAAAIAXAAAAA==.Alligatorjoe:BAAALgADCgEJAQAAAA==.',
Am='Amaneeda:BAABLgAECn8uAAIHAAgJFA4lLQBbAQhoDAAACAAgAGkMAAAGADYAawwAAAYAJQBqDAAABQAgAGwMAAAHACUAbQwAAAIAHgDqDAAABwAkAG4MAAAFABcABwAICRQOJS0AWwEIaAwAAAgAIABpDAAABgA2AGsMAAAGACUAagwAAAUAIABsDAAABwAlAG0MAAACAB4A6gwAAAcAJABuDAAABQAXAAAA.Amazonia:BAAALgAECgQJBQAAAA==.Aminea:BAAALgAFFAIJAgAAAA==.Amphi:BAAALgADCgMJAwABLgAECgUJCAAIAAAAAA==.Amphibibi:BAAALgAECgUJCAAAAA==.Amphoo:BAAALgAECgYJCAAAAA==.',
An='Andúril:BAAALgAECgYJBgAAAA==.Angyfabio:BAACLgAFFH8HAAIJAAIJHhXsCgB6AAJoDAAABQBEAOoMAAACACcACQACCR4V7AoAegACaAwAAAUARADqDAAAAgAnAC4ABAp/LwACCQAICSEiaQMAlQIACQAICSEiaQMAlQIAAAA=.Angyrain:BAAALgAECgUJBgABLgAFFAIJBwAJAB4VAA==.Annerila:BAAALgAECgEJAQAAAA==.Antagonis:BAABLgAECn8YAAIDAAcJsQ4lEgAUAQdoDAAABAAbAGkMAAAEADYAawwAAAQAJwBqDAAAAwAaAGwMAAACABIA6gwAAAUALABuDAAAAgAoAAMABwmxDiUSABQBB2gMAAAEABsAaQwAAAQANgBrDAAABAAnAGoMAAADABoAbAwAAAIAEgDqDAAABQAsAG4MAAACACgAAAA=.',
Ap='Apexchi:BAAALgAECgUJDwAAAA==.Apeximmortal:BAAALgAECgkJCQAAAA==.Apexlight:BAAALgAECgkJEQAAAA==.Apexwar:BAAALgAECgEJAQAAAA==.',
Ar='Arashe:BAAALgAECgUJDAAAAA==.Arewen:BAAALgADCggJEQAAAA==.Arganos:BAABLgAECn8wAAMKAAkJtSZZAQBmAwloDAAABwBjAGkMAAAHAGMAawwAAAcAYgBqDAAABgBjAGwMAAAGAGIAbQwAAAIAYgDqDAAABwBiAG4MAAAFAGMAbwwAAAEAYwAKAAkJtSZZAQBmAwloDAAABgBjAGkMAAAGAGMAawwAAAYAYgBqDAAABQBjAGwMAAAFAGIAbQwAAAIAYgDqDAAABgBiAG4MAAAFAGMAbwwAAAEAYwALAAYJFxsvFwB6AQZoDAAAAQA3AGkMAAABAEoAawwAAAEASABqDAAAAQBAAGwMAAABAD8A6gwAAAEATwAAAA==.Arisiana:BAAALgADCgYJCwAAAA==.Arkburn:BAABLgAECn8WAAIMAAcJ6wS/rgC2AAdoDAAABAAYAGkMAAAEAA8AawwAAAQACQBqDAAABAAPAGwMAAABAAoA6gwAAAQACQBuDAAAAQAEAAwABwnrBL+uALYAB2gMAAAEABgAaQwAAAQADwBrDAAABAAJAGoMAAAEAA8AbAwAAAEACgDqDAAABAAJAG4MAAABAAQAAAA=.Arkstrife:BAAALgADCgEJAQAAAA==.Artherüs:BAAALgADCgEJAQAAAA==.Arwyn:BAAALgADCgEJAQAAAA==.',
At='Athen:BAAALgADCgkJOwAAAA==.Atheîst:BAABLgAECn9AAAMNAAkJdyXMAQBaAwloDAAACgBjAGkMAAAKAGEAawwAAAkAXwBqDAAACABiAGwMAAAHAGMAbQwAAAQAXwDqDAAACQBhAG4MAAAGAFgAbwwAAAEAWQANAAkJdyXMAQBaAwloDAAACABjAGkMAAAIAGEAawwAAAcAXwBqDAAABwBiAGwMAAAGAGMAbQwAAAQAXwDqDAAACABhAG4MAAAGAFgAbwwAAAEAWQAOAAYJCyMtEABdAgZoDAAAAgBZAGkMAAACAFcAawwAAAIAVgBqDAAAAQBbAGwMAAABAFoA6gwAAAEAXAAAAA==.Atmos:BAAALgAECgEJAQAAAA==.Atsuni:BAABLgAECn9JAAMPAAkJaR/tFgCBAgloDAAADABgAGkMAAAMAFgAawwAAAwAXABqDAAABwBPAGwMAAAGAEgAbQwAAAIAPgDqDAAAEABHAG4MAAAEAEUAbwwAAAIAWQAPAAgJ9B7tFgCBAghoDAAACQBgAGkMAAAKAFgAawwAAAkAXABqDAAABABPAGwMAAAFAEgAbQwAAAIAPgDqDAAACwBHAG4MAAADAEUAEAAICYgbqBQANAIIaAwAAAMAWgBpDAAAAgBQAGsMAAADAFMAagwAAAMAXABsDAAAAQA3AOoMAAAFAFYAbgwAAAEAJABvDAAAAgA8AAAA.Atulash:BAAALgADCgEJAQAAAA==.',
Au='Aurite:BAAALgAFFAYJEwAAAQ==.',
Av='Aveldea:BAAALgAECggJEAAAAA==.Aventon:BAAALgADCggJDAABLgAECgkJMAAKALUmAA==.',
Az='Azalanasath:BAAALgADCgMJAwAAAA==.Azrand:BAABLgAECn8cAAMRAAcJuRqVEwC0AQdoDAAABABWAGkMAAAEAFoAawwAAAQAMQBqDAAABABZAGwMAAACACoA6gwAAAcAUwBuDAAAAwA5ABEABwm5GpUTALQBB2gMAAAEAFYAaQwAAAQAWgBrDAAABAAxAGoMAAADAFkAbAwAAAIAKgDqDAAAAwBTAG4MAAADADkACgACCaUQ8pMAbwACagwAAAEAGQDqDAAABAAqAAAA.',
Ba='Baconlittle:BAABLgAECn8fAAISAAYJ9RV8NwByAQZoDAAABwA5AGkMAAAGAE8AawwAAAUANgBqDAAABAAyAGwMAAADACEA6gwAAAYAPgASAAYJ9RV8NwByAQZoDAAABwA5AGkMAAAGAE8AawwAAAUANgBqDAAABAAyAGwMAAADACEA6gwAAAYAPgAAAA==.Baelanoth:BAABLgAECn8sAAITAAgJEh52BQBHAghoDAAABwBZAGkMAAAHAFQAawwAAAcAQABqDAAABQBUAGwMAAAFAE0AbQwAAAMATQDqDAAABgBGAG4MAAAEAEsAEwAICRIedgUARwIIaAwAAAcAWQBpDAAABwBUAGsMAAAHAEAAagwAAAUAVABsDAAABQBNAG0MAAADAE0A6gwAAAYARgBuDAAABABLAAAA.Bakunarreia:BAAALgAECgEJAQAAAA==.Balerion:BAAALgAECgEJAQAAAA==.Balkazaar:BAAALgAECggJEQAAAA==.Bammbamm:BAABLgAECn8oAAIEAAgJIwgqoQAnAQhoDAAACAAZAGkMAAAHACIAawwAAAcAIQBqDAAABQAmAGwMAAAEABIAbQwAAAEAEADqDAAABwAJAG4MAAABAAcABAAICSMIKqEAJwEIaAwAAAgAGQBpDAAABwAiAGsMAAAHACEAagwAAAUAJgBsDAAABAASAG0MAAABABAA6gwAAAcACQBuDAAAAQAHAAAA.Banewreak:BAACLgAFFH8FAAIBAAEJ7BHdsQBHAAHqDAAABQAtAAEAAQnsEd2xAEcAAeoMAAAFAC0ALgAECn83AAIBAAkJwheSIgBOAgABAAkJwheSIgBOAgAAAA==.Banu:BAAALgAECgEJAQAAAA==.Baradin:BAAALgAECgYJEQAAAA==.Barind:BAABLgAECn8yAAQUAAkJFh3UBwCZAgloDAAABwBSAGkMAAAGAEQAawwAAAYAPwBqDAAABgBBAGwMAAAGAFEAbQwAAAUAPQDqDAAACABUAG4MAAAEAFkAbwwAAAIAPgAUAAkJmRzUBwCZAgloDAAAAgBPAGkMAAADAD0AawwAAAMAPwBqDAAABABBAGwMAAADAFEAbQwAAAQAPQDqDAAABABUAG4MAAAEAFkAbwwAAAIAPgAVAAcJIxqYJAADAgdoDAAABQBSAGkMAAABADkAawwAAAMANABqDAAAAQApAGwMAAADAEkAbQwAAAEAMwDqDAAABABTABYAAgm5Gs6fAI8AAmkMAAACAEQAagwAAAEAMAAAAA==.',
Bd='Bdawg:BAAALgAECgMJBgAAAA==.',
Be='Benneel:BAAALgADCgcJBwAAAA==.Berñy:BAAALgAECgQJBwAAAA==.Betrayer:BAACLgAFFH8GAAIXAAMJAxaqFADZAANoDAAAAgAtAGkMAAABAD0A6gwAAAMAPgAXAAMJAxaqFADZAANoDAAAAgAtAGkMAAABAD0A6gwAAAMAPgAuAAQKfyIAAhcACQnuIV0DABADABcACQnuIV0DABADAAAA.Beve:BAAALgADCgUJBQAAAA==.',
Bi='Bietony:BAAALgAECggJEAAAAA==.Biggydtauren:BAAALgADCgUJBAAAAA==.Bigkruu:BAAALgADCgYJBgAAAA==.Biqdonk:BAAALgAECgUJDAAAAA==.',
Bl='Bleak:BAAALgADCggJCwAAAA==.Blindpenzu:BAAALgAECgMJBQAAAA==.Bloodhornz:BAAALgAECgEJAQAAAA==.',
Bo='Bobo:BAAALgAECgQJBQAAAA==.Boomerkillz:BAAALgAECgUJBQAAAA==.Bossbeast:BAAALgADCgcJDQABLgADCgYJCwAIAAAAAA==.Bossdk:BAAALgADCgEJAQABLgADCgYJCwAIAAAAAA==.Bossdwarf:BAAALgADCgcJCwABLgADCgYJCwAIAAAAAA==.Bossguy:BAAALgADCgYJCwAAAA==.Bossmonk:BAAALgADCgcJEAAAAA==.',
Br='Brietta:BAAALgAECgEJAgAAAA==.',
Bu='Bubbleosévèn:BAAALgADCggJDQABLgAECgkJQAANAHclAA==.',
['Bú']='Búbblés:BAAALgAECgcJDQAAAA==.',
Ca='Caatia:BAAALgAECggJCQAAAA==.Calintha:BAAALgADCgcJDwAAAA==.Carryharder:BAAALgAECgEJAQABLgAECgkJIwABAAwVAA==.Carthel:BAABLgAECn8fAAIYAAgJMiBYMQCtAghoDAAABgBWAGkMAAAFAF4AawwAAAUAWgBqDAAABABVAGwMAAADAFEAbQwAAAIAXADqDAAABABcAG4MAAACACYAGAAICTIgWDEArQIIaAwAAAYAVgBpDAAABQBeAGsMAAAFAFoAagwAAAQAVQBsDAAAAwBRAG0MAAACAFwA6gwAAAQAXABuDAAAAgAmAAAA.Carthell:BAAALgAECgIJAgAAAA==.Cathedryal:BAAALgADCggJDgAAAA==.',
Ce='Cerisi:BAAALgAECgEJAQAAAA==.Cerrydwyn:BAAALgADCgkJCQAAAA==.',
Ch='Charley:BAAALgAECgYJCQAAAA==.Chasseresse:BAAALgAECgQJBQAAAA==.Cherry:BAAALgADCgQJBAAAAA==.Chi:BAAALgAECgEJAQAAAA==.Chimarr:BAABLgAECn8cAAIZAAgJFiJiDwDNAghoDAAABQBdAGkMAAAEAFsAawwAAAQAXQBqDAAABABbAGwMAAADAF8AbQwAAAIAQQDqDAAABQBcAG4MAAABAEsAGQAICRYiYg8AzQIIaAwAAAUAXQBpDAAABABbAGsMAAAEAF0AagwAAAQAWwBsDAAAAwBfAG0MAAACAEEA6gwAAAUAXABuDAAAAQBLAAAA.Chosso:BAAALgADCgUJCQAAAA==.',
Cl='Clantis:BAAALgADCgMJAwAAAA==.',
Co='Coldsploder:BAABLgAECn8qAAIYAAkJARfJMQBHAgloDAAABQBDAGkMAAAFADgAawwAAAYALABqDAAABQBMAGwMAAAFAEMAbQwAAAUAOwDqDAAABwBKAG4MAAADAD8AbwwAAAEAJQAYAAkJARfJMQBHAgloDAAABQBDAGkMAAAFADgAawwAAAYALABqDAAABQBMAGwMAAAFAEMAbQwAAAUAOwDqDAAABwBKAG4MAAADAD8AbwwAAAEAJQAAAA==.',
Cr='Crackmonkéy:BAABLgAECn8aAAQOAAgJ2Bi+JwCAAQhoDAAABQBdAGkMAAAEAD8AawwAAAMARgBqDAAAAwBVAGwMAAADAEAAbQwAAAEAJgDqDAAABAAvAG4MAAADAC0ADgAHCTQUvicAgAEHaAwAAAEAIQBpDAAAAgA/AGsMAAACAEYAagwAAAEAJQBsDAAAAwBAAOoMAAACAC8AbgwAAAMALQANAAQJkRlWTwD7AARoDAAAAwBdAGkMAAABACwAagwAAAIAVQBtDAAAAQAmABoABAl0EDhBAO8ABGgMAAABACgAaQwAAAEANQBrDAAAAQAoAOoMAAACACIAAS4ABRQDCQMACAAAAAA=.Cranknspank:BAAALgAECgYJBwAAAA==.Cronoz:BAABLgAECn8mAAMQAAkJbgufPgAmAQloDAAABgAWAGkMAAAFABAAawwAAAUAHABqDAAABAAUAGwMAAAEABYAbQwAAAEAOQDqDAAABwARAG4MAAAFADEAbwwAAAEAEwAQAAgJ0wmfPgAmAQhoDAAABQAWAGkMAAADABAAawwAAAMAHABqDAAAAwAUAGwMAAADABYA6gwAAAUAEQBuDAAABAAxAG8MAAABABMADwAICVAH21kAIQEIaAwAAAEAOgBpDAAAAgAJAGsMAAACAAgAagwAAAEAFQBsDAAAAQAPAG0MAAABAAUA6gwAAAIADwBuDAAAAQAOAAAA.Crotchshot:BAABLgAECn8jAAIWAAgJ5RBuTACtAQhoDAAABgAkAGkMAAAFADkAawwAAAUAKgBqDAAABAAqAGwMAAAFABsAbQwAAAMARQDqDAAABAAjAG4MAAADACEAFgAICeUQbkwArQEIaAwAAAYAJABpDAAABQA5AGsMAAAFACoAagwAAAQAKgBsDAAABQAbAG0MAAADAEUA6gwAAAQAIwBuDAAAAwAhAAAA.Crushbone:BAAALgADCgUJBQAAAA==.',
Cu='Culodevour:BAAALgAECgYJBgAAAA==.Cursess:BAACLgAFFH8LAAIBAAMJsRmLXgDyAANoDAAABQBQAGkMAAABACoA6gwAAAUASQABAAMJsRmLXgDyAANoDAAABQBQAGkMAAABACoA6gwAAAUASQAuAAQKfzUAAgEACQlxIkQLAO0CAAEACQlxIkQLAO0CAAAA.',
['Có']='Cózmik:BAABLgAECn8UAAIWAAcJ3Ra5VACVAQdoDAAABQBEAGkMAAAFAEUAawwAAAQAPgBqDAAAAgA6AGwMAAABAC8AbQwAAAEAPwDqDAAAAgAnABYABwndFrlUAJUBB2gMAAAFAEQAaQwAAAUARQBrDAAABAA+AGoMAAACADoAbAwAAAEALwBtDAAAAQA/AOoMAAACACcAAAA=.',
Da='Dace:BAAALgAECgEJAQAAAA==.Daliela:BAABLgAECn8oAAIBAAgJ7Q9cXQCAAQhoDAAABwA7AGkMAAAGAEEAawwAAAYALABqDAAABQAwAGwMAAAFAB8AbQwAAAMAGwDqDAAABQAcAG4MAAADABsAAQAICe0PXF0AgAEIaAwAAAcAOwBpDAAABgBBAGsMAAAGACwAagwAAAUAMABsDAAABQAfAG0MAAADABsA6gwAAAUAHABuDAAAAwAbAAAA.Dalya:BAAALgAECggJCgAAAA==.Dander:BAAALgADCgMJAwAAAA==.Dani:BAAALgAECgEJAgABLgAECgQJBQAIAAAAAA==.Darkage:BAAALgADCgEJAQAAAA==.Darkfiff:BAAALgADCgQJBAAAAA==.Darkridder:BAAALgAECgEJAQAAAA==.Darkängal:BAAALgAECgUJDgAAAA==.Dayel:BAAALgAECgYJEQAAAA==.',
De='Deathnorris:BAAALgAECgIJAQAAAA==.Deathratellr:BAAALgADCgEJAQAAAA==.Deemaius:BAAALgADCgUJCQAAAA==.Dekard:BAAALgAECggJEQAAAA==.Dekariusly:BAAALgAECgQJBAABLgAECggJEQAIAAAAAA==.Demonatrixx:BAAALgAECgYJCQAAAA==.Demonhugger:BAAALgAECgEJAgABLgAECgUJBQAIAAAAAA==.Demonspookie:BAAALgADCgMJAwABLgAECgkJHwACAFwZAA==.Destinÿ:BAABLgAECn8jAAILAAgJPRdUFQCOAQhoDAAABgAsAGkMAAAGAEUAawwAAAYAPABqDAAABAAyAGwMAAADACwAbQwAAAEARwDqDAAABwA/AG4MAAACAD0ACwAICT0XVBUAjgEIaAwAAAYALABpDAAABgBFAGsMAAAGADwAagwAAAQAMgBsDAAAAwAsAG0MAAABAEcA6gwAAAcAPwBuDAAAAgA9AAAA.Devourer:BAABLgAECn8pAAIMAAgJGBvXKAAbAghoDAAACABJAGkMAAAHAE4AawwAAAcAPwBqDAAABQBBAGwMAAAFAEMAbQwAAAEAPADqDAAABwBYAG4MAAABADYADAAICRgb1ygAGwIIaAwAAAgASQBpDAAABwBOAGsMAAAHAD8AagwAAAUAQQBsDAAABQBDAG0MAAABADwA6gwAAAcAWABuDAAAAQA2AAAA.',
Di='Disploder:BAABLgAECn8lAAINAAcJOhP8JgB7AQdoDAAABgAhAGkMAAAFADMAawwAAAUAOABqDAAABQBBAGwMAAAGAC4AbQwAAAMALgDqDAAABwAsAA0ABwk6E/wmAHsBB2gMAAAGACEAaQwAAAUAMwBrDAAABQA4AGoMAAAFAEEAbAwAAAYALgBtDAAAAwAuAOoMAAAHACwAAAA=.Dist:BAAALgAECgkJDgAAAA==.',
Do='Doctafuzz:BAAALgAECgcJDAAAAA==.',
Dr='Drakentales:BAAALgADCgUJCAAAAA==.Drawnn:BAAALgAECgEJAQABLgAECgEJAgAIAAAAAA==.Drawwn:BAAALgAECgEJAgAAAA==.Dreathhammer:BAABLgAECn8uAAIbAAkJ1SIgAwBnAwloDAAABwBTAGkMAAAEAFEAawwAAAUAYgBqDAAABgBgAGwMAAAFAFUAbQwAAAUAUwDqDAAACABdAG4MAAAEAFoAbwwAAAIAWwAbAAkJ1SIgAwBnAwloDAAABwBTAGkMAAAEAFEAawwAAAUAYgBqDAAABgBgAGwMAAAFAFUAbQwAAAUAUwDqDAAACABdAG4MAAAEAFoAbwwAAAIAWwAAAA==.Drogo:BAAALgAFFAMJAwAAAA==.Drureds:BAAALgAECgMJBQAAAA==.Dryad:BAAALgAECgQJBAABLgAFFAgJHwAbAIIgAA==.',
Du='Duckcox:BAAALgAECgQJBwAAAA==.Dunadin:BAABLgAECn8WAAQSAAYJ/RnSLACrAQZoDAAABQA/AGkMAAAFAEMAawwAAAMAOgBqDAAAAwBIAGwMAAACAEAA6gwAAAQASAASAAYJ/RnSLACrAQZoDAAABAA/AGkMAAAEAEMAawwAAAMAOgBqDAAAAwBIAGwMAAACAEAA6gwAAAMASAAcAAIJ4xKCZAB1AAJoDAAAAQA0AGkMAAABACwAHQABCbYVToUAPwAB6gwAAAEANwABLgAECgkJPQAJAK4mAA==.Dundyrn:BAABLgAECn89AAIJAAkJriYmAAB4AwloDAAACQBjAGkMAAAIAGIAawwAAAkAYwBqDAAACABjAGwMAAAIAGIAbQwAAAQAYwDqDAAACABiAG4MAAAGAGIAbwwAAAEAYwAJAAkJriYmAAB4AwloDAAACQBjAGkMAAAIAGIAawwAAAkAYwBqDAAACABjAGwMAAAIAGIAbQwAAAQAYwDqDAAACABiAG4MAAAGAGIAbwwAAAEAYwAAAA==.',
Dv='Dvera:BAAALgADCgMJAwAAAA==.',
Dy='Dynarc:BAAALgADCgEJAQABLgAECgkJPQAJAK4mAA==.',
Ec='Ecks:BAAALgAECgMJAwABLgAFFAYJEAALAOkbAA==.',
Ed='Edmunin:BAEALgAECgYJAwABLgAECgcJAQAIAAAAAA==.',
El='Elememetal:BAABLgAECn8oAAIQAAkJvxioGQAFAgloDAAABgBFAGkMAAAGAEkAawwAAAYAOwBqDAAABQBCAGwMAAAEADkAbQwAAAIAOgDqDAAABQBQAG4MAAAEAC8AbwwAAAIAOwAQAAkJvxioGQAFAgloDAAABgBFAGkMAAAGAEkAawwAAAYAOwBqDAAABQBCAGwMAAAEADkAbQwAAAIAOgDqDAAABQBQAG4MAAAEAC8AbwwAAAIAOwAAAA==.Elfyparker:BAAALgAECgEJAQAAAA==.Elliott:BAAALgADCgIJAgAAAA==.',
En='Enigmä:BAAALgAECgIJBAAAAA==.',
Fa='Fanmir:BAAALgAECgEJAQAAAA==.Fatpao:BAAALgAECgYJDAAAAA==.Faultless:BAAALgADCggJDQAAAA==.',
Fe='Felbrand:BAAALgAECgEJAQAAAA==.Feloth:BAAALgADCgMJBQAAAA==.Felruby:BAAALgADCgEJAQAAAA==.Fengg:BAABLgAECn8dAAIPAAcJXQs/WQAjAQdoDAAABQAuAGkMAAAFACEAawwAAAYAGQBqDAAABQAbAGwMAAADAC4A6gwAAAQAFQBuDAAAAQADAA8ABwldCz9ZACMBB2gMAAAFAC4AaQwAAAUAIQBrDAAABgAZAGoMAAAFABsAbAwAAAMALgDqDAAABAAVAG4MAAABAAMAAAA=.Fenix:BAAALgADCgEJAgABLgAECggJLAAaAI8UAA==.',
Fi='Filbert:BAABLgAECn8dAAIHAAkJUyGDBgDiAgloDAAABABSAGkMAAAEAFYAawwAAAQAXQBqDAAAAgA7AGwMAAACAE0AbQwAAAEASADqDAAACABZAG4MAAADAFsAbwwAAAEAWQAHAAkJUyGDBgDiAgloDAAABABSAGkMAAAEAFYAawwAAAQAXQBqDAAAAgA7AGwMAAACAE0AbQwAAAEASADqDAAACABZAG4MAAADAFsAbwwAAAEAWQAAAA==.',
Fl='Flyttanth:BAAALgADCgMJBgAAAA==.',
Fo='Foldyholds:BAAALgADCgMJAwAAAA==.Fomy:BAAALgAECgEJAQABLgAECgkJGwAHAKANAA==.Foodvendor:BAAALgAECgEJAQABLgAECgQJDgAIAAAAAA==.',
Fr='Fraw:BAAALgADCggJDAAAAA==.Frizzel:BAAALgAECgQJBAAAAA==.Frostynaps:BAAALgAECgYJCQAAAA==.',
Fu='Funkdooby:BAAALgAECgEJAwAAAA==.Fuzzyhunter:BAAALgAECgEJAQABLgAECggJLAAaAI8UAA==.',
['Fá']='Fálola:BAABLgAECn88AAMPAAgJrxffKADsAQhoDAAACQBVAGkMAAAJADwAawwAAAkAQQBqDAAABwApAGwMAAAIAEcAbQwAAAUAHwDqDAAACQBcAG4MAAAEACQADwAICa8X3ygA7AEIaAwAAAcAVQBpDAAABwA8AGsMAAAHAEEAagwAAAUAKQBsDAAABwBHAG0MAAAFAB8A6gwAAAcAXABuDAAABAAkABAABgnDAylnAJ0ABmgMAAACAAoAaQwAAAIAEABrDAAAAgAIAGoMAAACAAYAbAwAAAEACADqDAAAAgAEAAAA.',
Ga='Galestina:BAAALgAECgEJAQAAAA==.Gamblex:BAAALgAECgUJDgAAAA==.Garviel:BAABLgAECn8eAAIRAAgJlRruCwAWAghoDAAABgBLAGkMAAAGAFEAawwAAAQAMwBqDAAAAwBDAGwMAAAEAEMAbQwAAAEAUwDqDAAAAwBDAG4MAAADADIAEQAICZUa7gsAFgIIaAwAAAYASwBpDAAABgBRAGsMAAAEADMAagwAAAMAQwBsDAAABABDAG0MAAABAFMA6gwAAAMAQwBuDAAAAwAyAAAA.',
Ge='Geeplague:BAAALgADCgMJAwABLgAECggJGQABABMWAA==.Geethatlock:BAABLgAECn8ZAAIBAAgJExbgQgDLAQhoDAAABQBQAGkMAAAFADYAawwAAAUAPABqDAAAAgA2AGwMAAACAEoAbQwAAAEAHwDqDAAABAAyAG4MAAABACsAAQAICRMW4EIAywEIaAwAAAUAUABpDAAABQA2AGsMAAAFADwAagwAAAIANgBsDAAAAgBKAG0MAAABAB8A6gwAAAQAMgBuDAAAAQArAAAA.',
Gh='Ghlaircan:BAAALgADCgkJCQAAAA==.',
Gi='Gimleia:BAABLgAECn8cAAIVAAYJ7BZNDwBUAQZoDAAABgA/AGkMAAAFADwAawwAAAYANABqDAAABABNAGwMAAADADcA6gwAAAQAPAAVAAYJ7BZNDwBUAQZoDAAABgA/AGkMAAAFADwAawwAAAYANABqDAAABABNAGwMAAADADcA6gwAAAQAPAAAAA==.',
Gl='Glanth:BAAALgAECgcJDgAAAA==.',
Go='Goobgobbler:BAAALgADCgYJCwAAAA==.Gorgonzolas:BAAALgAECgUJCAAAAA==.',
Gr='Gravewake:BAAALgADCgcJDwAAAA==.Gravlocks:BAAALgADCgEJAQAAAA==.Grebeci:BAAALgADCgMJAwAAAA==.Greensoul:BAABLgAECn8bAAIPAAgJ8RtRHQBQAghoDAAABQBUAGkMAAAEAE4AawwAAAQASgBqDAAABABUAGwMAAAEAF4AbQwAAAIAPgDqDAAAAwBPAG4MAAABAA4ADwAICfEbUR0AUAIIaAwAAAUAVABpDAAABABOAGsMAAAEAEoAagwAAAQAVABsDAAABABeAG0MAAACAD4A6gwAAAMATwBuDAAAAQAOAAAA.Grifflyn:BAAALgAECgEJAQAAAA==.Grogu:BAABLgAECn8dAAIYAAcJBQpHpwAlAQdoDAAABAAbAGkMAAAEACIAawwAAAQAGwBqDAAABQAwAGwMAAACABgA6gwAAAcAHABuDAAAAwALABgABwkFCkenACUBB2gMAAAEABsAaQwAAAQAIgBrDAAABAAbAGoMAAAFADAAbAwAAAIAGADqDAAABwAcAG4MAAADAAsAAAA=.Gromnah:BAAALgADCgIJAgAAAA==.Gruxx:BAAALgAECgEJAgAAAA==.',
Gu='Gummies:BAAALgAECgEJBAAAAA==.Gundyr:BAAALgADCgkJHgAAAA==.',
Ha='Hahaha:BAAALgAFFAMJAwAAAA==.Haranir:BAAALgAECgEJAgAAAA==.',
He='Helkyrie:BAAALgADCgcJJAAAAA==.Helleer:BAAALgADCgcJBwAAAA==.Hexappeal:BAAALgADCgcJEAAAAA==.',
Hi='Hikdh:BAAALgAECgMJAwABLgAECgkJLgAeAL0fAA==.Hiksham:BAABLgAECn8uAAMeAAkJvR+QBACZAgloDAAABwBQAGkMAAAGAFMAawwAAAYAWwBqDAAABwBHAGwMAAAGAE8AbQwAAAMAUwDqDAAABgBTAG4MAAAEAEcAbwwAAAEATQAeAAkJnB+QBACZAgloDAAABABQAGkMAAAEAFMAawwAAAQAWwBqDAAAAwBHAGwMAAAEAE8AbQwAAAIAUADqDAAABABTAG4MAAADAEcAbwwAAAEATQAQAAgJBw2WNgBMAQhoDAAAAwAeAGkMAAACAB8AawwAAAIAIABqDAAABAA3AGwMAAACAA8AbQwAAAEAUwDqDAAAAgAVAG4MAAABABIAAAA=.',
Ho='Holycheeze:BAAALgADCgcJCgAAAA==.Holyhoof:BAAALgAECgEJAQAAAA==.Honeybutter:BAAALgADCgEJAQABLgAECgkJIwABAAwVAA==.Hotsanddots:BAAALgAECgcJCAAAAA==.',
Hu='Huuan:BAAALgAECgEJAQABLgAECgcJGQAPAGwVAA==.',
Ia='Iamreggi:BAAALgAECgQJBgAAAA==.',
Ih='Ihealzufool:BAABLgAECn8sAAIaAAgJjxT9HQDIAQhoDAAABwBFAGkMAAAHADsAawwAAAcAQgBqDAAABQA5AGwMAAAGAD8AbQwAAAMAGQDqDAAABQA/AG4MAAAEABQAGgAICY8U/R0AyAEIaAwAAAcARQBpDAAABwA7AGsMAAAHAEIAagwAAAUAOQBsDAAABgA/AG0MAAADABkA6gwAAAUAPwBuDAAABAAUAAAA.',
Il='Illistia:BAAALgADCgYJBgAAAA==.',
Im='Im:BAAALgAECgEJAQAAAA==.Imded:BAAALgAECgQJBAAAAA==.',
Ir='Irisi:BAAALgADCgUJBQAAAA==.',
Ja='Jalene:BAAALgAECgUJDwAAAA==.Jargyn:BAAALgAECgYJEQABLgAECggJGwAfALsWAA==.Jarlyss:BAABLgAECn8bAAIfAAgJuxYcEQDCAQhoDAAABAA9AGkMAAAEAEcAawwAAAQASQBqDAAABQBKAGwMAAAEADMAbQwAAAEAKwDqDAAABABDAG4MAAABACYAHwAICbsWHBEAwgEIaAwAAAQAPQBpDAAABABHAGsMAAAEAEkAagwAAAUASgBsDAAABAAzAG0MAAABACsA6gwAAAQAQwBuDAAAAQAmAAAA.Javieraa:BAABLgAECn8gAAIMAAkJYRoaIwA5AgloDAAABAA1AGkMAAAEAE8AawwAAAUAVQBqDAAABABOAGwMAAADAAoAbQwAAAIAUwDqDAAABQBQAG4MAAADAEAAbwwAAAIAUQAMAAkJYRoaIwA5AgloDAAABAA1AGkMAAAEAE8AawwAAAUAVQBqDAAABABOAGwMAAADAAoAbQwAAAIAUwDqDAAABQBQAG4MAAADAEAAbwwAAAIAUQAAAA==.',
Jd='Jdai:BAABLgAECn8ZAAIPAAcJbBUVOAC8AQdoDAAABABPAGkMAAAEABMAawwAAAYASABqDAAAAwBFAGwMAAACACYAbQwAAAEAIgDqDAAABQBFAA8ABwlsFRU4ALwBB2gMAAAEAE8AaQwAAAQAEwBrDAAABgBIAGoMAAADAEUAbAwAAAIAJgBtDAAAAQAiAOoMAAAFAEUAAAA=.',
Jo='Jorschwa:BAAALgAECgEJAgAAAA==.',
Ju='Juglight:BAAALgAECgcJEAAAAA==.Jugtonic:BAAALgAECgIJAgAAAA==.Junovay:BAAALgADCgQJBAAAAA==.',
Ka='Kaelithra:BAAALgADCgYJBgAAAA==.',
Ke='Kenny:BAAALgADCgEJAQAAAA==.',
Kh='Khaiv:BAACLgAFFH8cAAIMAAcJaB77DQAaAgdoDAAABQBbAGkMAAAGAGAAawwAAAQAUwBqDAAAAgAvAGwMAAABAEMAbQwAAAEALgDqDAAACQBRAAwABwloHvsNABoCB2gMAAAFAFsAaQwAAAYAYABrDAAABABTAGoMAAACAC8AbAwAAAEAQwBtDAAAAQAuAOoMAAAJAFEALgAECn9DAAIMAAkJZCTwAwBAAwAMAAkJZCTwAwBAAwAAAA==.Khanen:BAAALgAECgMJAwAAAA==.',
Ki='Kielann:BAABLgAECn8uAAIXAAgJ5AyGIwBDAQhoDAAACQA0AGkMAAAIACcAawwAAAgAHABqDAAABgA0AGwMAAAFABcAbQwAAAEAFwDqDAAACAAsAG4MAAABABMAFwAICeQMhiMAQwEIaAwAAAkANABpDAAACAAnAGsMAAAIABwAagwAAAYANABsDAAABQAXAG0MAAABABcA6gwAAAgALABuDAAAAQATAAAA.Kikyo:BAAALgAECgYJEgAAAA==.Kimmi:BAAALgAECgUJDAAAAA==.Kinzen:BAABLgAECn8xAAIeAAcJhSBZDADZAQdoDAAACgBjAGkMAAAJAFkAawwAAAkAUgBqDAAABwBhAGwMAAAGAFkAbQwAAAIANADqDAAABgBUAB4ABwmFIFkMANkBB2gMAAAKAGMAaQwAAAkAWQBrDAAACQBSAGoMAAAHAGEAbAwAAAYAWQBtDAAAAgA0AOoMAAAGAFQAAAA=.',
Ku='Kulthosano:BAABLgAECn8dAAIgAAYJAyEjDQDmAQZoDAAABABSAGkMAAAEAFoAawwAAAQATwBqDAAAAwBVAGwMAAACAE8A6gwAAAwAWgAgAAYJAyEjDQDmAQZoDAAABABSAGkMAAAEAFoAawwAAAQATwBqDAAAAwBVAGwMAAACAE8A6gwAAAwAWgAAAA==.',
La='Labubu:BAABLgAECn8jAAIYAAgJPApqhQBhAQhoDAAABgAgAGkMAAAGACUAawwAAAYAEwBqDAAABgApAGwMAAAFACMAbQwAAAEADgDqDAAABAASAG4MAAABABkAGAAICTwKaoUAYQEIaAwAAAYAIABpDAAABgAlAGsMAAAGABMAagwAAAYAKQBsDAAABQAjAG0MAAABAA4A6gwAAAQAEgBuDAAAAQAZAAAA.Larra:BAAALgAECgIJAgAAAA==.Lasadin:BAAALgADCgEJAQAAAA==.Lawhityy:BAAALgAECgIJAgABLgAECgkJOwAOADYdAA==.',
Le='Lechwe:BAABLgAECn8pAAIPAAgJpBqJGAB0AghoDAAABwBOAGkMAAAHAEoAawwAAAcASQBqDAAAAwBRAGwMAAACAEsA6gwAAAkAVABuDAAABQAzAG8MAAABABkADwAICaQaiRgAdAIIaAwAAAcATgBpDAAABwBKAGsMAAAHAEkAagwAAAMAUQBsDAAAAgBLAOoMAAAJAFQAbgwAAAUAMwBvDAAAAQAZAAAA.Legonator:BAAALgAECgUJCAAAAA==.Lenry:BAAALgAFFAEJAQAAAA==.',
Li='Lichmajor:BAABLgAECn8nAAIhAAkJ6BjDQQDyAQloDAAABgBbAGkMAAAFAFAAawwAAAUAPQBqDAAABQA9AGwMAAAEAEMAbQwAAAMAOwDqDAAABgBFAG4MAAADAC0AbwwAAAIAIgAhAAkJ6BjDQQDyAQloDAAABgBbAGkMAAAFAFAAawwAAAUAPQBqDAAABQA9AGwMAAAEAEMAbQwAAAMAOwDqDAAABgBFAG4MAAADAC0AbwwAAAIAIgAAAA==.Lilleymage:BAAALgADCgEJAQAAAA==.Lingmi:BAAALgADCgUJBQAAAA==.Littlefang:BAAALgAECgQJBAAAAA==.',
Lo='Lopus:BAAALgADCgcJEQAAAA==.Lostchi:BAABLgAECn8eAAISAAcJAiG1FABdAgdoDAAABABWAGkMAAAEAFUAawwAAAUAWwBqDAAABABVAGwMAAACAFUA6gwAAAgAUwBuDAAAAwBJABIABwkCIbUUAF0CB2gMAAAEAFYAaQwAAAQAVQBrDAAABQBbAGoMAAAEAFUAbAwAAAIAVQDqDAAACABTAG4MAAADAEkAAAA=.Lovepet:BAABLgAECn8/AAMWAAkJ9x0eFgCTAgloDAAACgBXAGkMAAAJAFoAawwAAAkAQwBqDAAACABSAGwMAAAIAD8AbQwAAAQAQwDqDAAACABNAG4MAAAGAEkAbwwAAAEAVQAWAAkJ9x0eFgCTAgloDAAABgBXAGkMAAAGAFoAawwAAAYAQwBqDAAABgBSAGwMAAAGAD8AbQwAAAQAQwDqDAAABgBNAG4MAAAGAEkAbwwAAAEAVQAVAAYJCQdyUwD+AAZoDAAABAAXAGkMAAADACIAawwAAAMACQBqDAAAAgAPAGwMAAACAA0A6gwAAAIACgAAAA==.',
Lt='Ltlesunshine:BAAALgAECgYJCgAAAA==.',
Lu='Lucy:BAAALgADCgEJAQAAAA==.Lunal:BAABLgAECn83AAIYAAkJbiCxHgCbAgloDAAACABcAGkMAAAIAF4AawwAAAgAXgBqDAAABQBMAGwMAAAEAEwAbQwAAAQASwDqDAAACwBXAG4MAAAFAEwAbwwAAAIAQgAYAAkJbiCxHgCbAgloDAAACABcAGkMAAAIAF4AawwAAAgAXgBqDAAABQBMAGwMAAAEAEwAbQwAAAQASwDqDAAACwBXAG4MAAAFAEwAbwwAAAIAQgAAAA==.Lunavis:BAAALgAECgEJAQABLgAECgkJGAAZAPUNAA==.',
Ly='Lyda:BAABLgAECn8uAAIZAAgJfhsfGQBwAghoDAAACQBbAGkMAAAIAEkAawwAAAgASwBqDAAABgBHAGwMAAAFAF8AbQwAAAEANQDqDAAACABLAG4MAAABABkAGQAICX4bHxkAcAIIaAwAAAkAWwBpDAAACABJAGsMAAAIAEsAagwAAAYARwBsDAAABQBfAG0MAAABADUA6gwAAAgASwBuDAAAAQAZAAAA.',
Ma='Magice:BAABLgAECn8XAAIYAAUJ+wIQCAGNAAVoDAAABwAGAGkMAAAGAAsAawwAAAYABgBqDAAAAwAIAGwMAAABAAcAGAAFCfsCEAgBjQAFaAwAAAcABgBpDAAABgALAGsMAAAGAAYAagwAAAMACABsDAAAAQAHAAAA.Magmara:BAAALgADCgkJEgAAAA==.Malibubarbie:BAABLgAECn8nAAINAAgJ/g1dKABxAQhoDAAACABJAGkMAAAHACkAawwAAAcAGABqDAAABQAiAGwMAAADAD0AbQwAAAEADgDqDAAABwAcAG4MAAABAAcADQAICf4NXSgAcQEIaAwAAAgASQBpDAAABwApAGsMAAAHABgAagwAAAUAIgBsDAAAAwA9AG0MAAABAA4A6gwAAAcAHABuDAAAAQAHAAAA.Malthael:BAAALgAECgEJAQAAAA==.Malystron:BAAALgAECgkJEgAAAA==.Maneevent:BAABLgAECn8ZAAQWAAYJGRfAewA3AQZoDAAABQA5AGkMAAAEADYAawwAAAQAOgBqDAAABAA/AGwMAAAEAEkA6gwAAAQAMwAWAAYJGRfAewA3AQZoDAAABQA5AGkMAAACADYAawwAAAQAOgBqDAAABAA/AGwMAAAEAEkA6gwAAAQAMwAUAAEJ1wTvYgAsAAFpDAAAAQAMABUAAQlVA2OVACQAAWkMAAABAAgAAAA=.Mariscylla:BAAALgAECgEJAQAAAA==.Materesa:BAABLgAECn87AAMOAAkJNh2nBgAGAwloDAAACQBIAGkMAAAIAEwAawwAAAkAWQBqDAAACABXAGwMAAAIAGEAbQwAAAQATQDqDAAABgBJAG4MAAAGAEAAbwwAAAEAIgAOAAkJNh2nBgAGAwloDAAABgBIAGkMAAAGAEwAawwAAAcAWQBqDAAABwBXAGwMAAAHAGEAbQwAAAQATQDqDAAABQBJAG4MAAAGAEAAbwwAAAEAIgAaAAYJbgz2NQA8AQZoDAAAAwAwAGkMAAACABoAawwAAAIAIwBqDAAAAQAQAGwMAAABACkA6gwAAAEABwAAAA==.Maysty:BAABLgAECn8+AAIWAAkJFgpmSgCzAQloDAAACQAbAGkMAAAJAC4AawwAAAkAGQBqDAAACAAiAGwMAAAIABwAbQwAAAQACwDqDAAACAATAG4MAAAGABkAbwwAAAEAFgAWAAkJFgpmSgCzAQloDAAACQAbAGkMAAAJAC4AawwAAAkAGQBqDAAACAAiAGwMAAAIABwAbQwAAAQACwDqDAAACAATAG4MAAAGABkAbwwAAAEAFgAAAA==.',
Me='Melidra:BAAALgAECgEJAQAAAA==.Menapaws:BAACLgAFFH8WAAQgAAYJvRvPAQC0AQZoDAAAAwAxAGkMAAAFAFoAawwAAAMANgBqDAAAAgAuAG0MAAABAD0A6gwAAAgAYgAgAAUJTxvPAQC0AQVoDAAAAgAsAGkMAAAFAFoAawwAAAMANgBtDAAAAQA9AOoMAAAHAGIABwACCXwdCD8AVwACagwAAAIALgDqDAAAAQBLAB8AAQmHE+gGADoAAWgMAAABADEALgAECn8qAAQgAAkJIiPkAQANAwAgAAkJIiPkAQANAwAfAAEJMSGNKQBUAAAHAAEJKhXMegBBAAAAAA==.Meraxion:BAAALgAECgYJCAAAAA==.Meriel:BAABLgAECn8zAAINAAkJfQ8RHwC4AQloDAAACgBFAGkMAAAJADgAawwAAAkAQgBqDAAABQAnAGwMAAADABsAbQwAAAIADwDqDAAACQAqAG4MAAADAB0AbwwAAAEACgANAAkJfQ8RHwC4AQloDAAACgBFAGkMAAAJADgAawwAAAkAQgBqDAAABQAnAGwMAAADABsAbQwAAAIADwDqDAAACQAqAG4MAAADAB0AbwwAAAEACgAAAA==.',
Mi='Midnightstar:BAABLgAECn8VAAIZAAYJqxJbTABPAQZoDAAABAAxAGkMAAAEADkAawwAAAMANABqDAAAAwAfAGwMAAADACQA6gwAAAQAOwAZAAYJqxJbTABPAQZoDAAABAAxAGkMAAAEADkAawwAAAMANABqDAAAAwAfAGwMAAADACQA6gwAAAQAOwAAAA==.Milk:BAAALgAECgEJAQABLgAECgYJCgAIAAAAAA==.Mimolette:BAAALgADCgUJBQAAAA==.Mirabel:BAAALgAECgMJAwAAAA==.Miseree:BAAALgAECgcJBwAAAA==.',
Mo='Modest:BAAALgAECgUJBQAAAA==.Monika:BAAALgAECgIJAgAAAA==.Monlee:BAAALgAECgEJAQAAAA==.Moonbayne:BAABLgAECn8rAAIHAAgJGhpMFwADAghoDAAACABEAGkMAAAHAEkAawwAAAUAQwBqDAAAAwBDAGwMAAAHAE4AbQwAAAIALgDqDAAACQBUAG4MAAACAC8ABwAICRoaTBcAAwIIaAwAAAgARABpDAAABwBJAGsMAAAFAEMAagwAAAMAQwBsDAAABwBOAG0MAAACAC4A6gwAAAkAVABuDAAAAgAvAAAA.Mooszer:BAABLgAECn8dAAIEAAgJTgQKzADoAAhoDAAABwAOAGkMAAAGAA8AawwAAAYACQBqDAAAAwAKAGwMAAADABAAbQwAAAEACQDqDAAAAgAGAG4MAAABAAQABAAICU4ECswA6AAIaAwAAAcADgBpDAAABgAPAGsMAAAGAAkAagwAAAMACgBsDAAAAwAQAG0MAAABAAkA6gwAAAIABgBuDAAAAQAEAAAA.Morder:BAAALgADCgYJCgAAAA==.Moritz:BAAALgADCgcJDgAAAA==.',
Mu='Muaythighs:BAAALgAECgIJBwAAAA==.Mushu:BAABLgAECn8tAAIiAAkJSBqCBQCwAgloDAAABQBCAGkMAAAFAD4AawwAAAQATgBqDAAABQBKAGwMAAAEAE4AbQwAAAYAQgDqDAAABwBZAG4MAAAIADYAbwwAAAEAIgAiAAkJSBqCBQCwAgloDAAABQBCAGkMAAAFAD4AawwAAAQATgBqDAAABQBKAGwMAAAEAE4AbQwAAAYAQgDqDAAABwBZAG4MAAAIADYAbwwAAAEAIgAAAA==.',
Mv='Mvmt:BAAALgADCgYJBgAAAA==.',
My='Mycheeksclap:BAAALgAECgEJAQAAAA==.',
['Mà']='Màc:BAAALgADCgMJAwAAAA==.',
Na='Namielle:BAAALgADCgUJDAAAAA==.Nasta:BAAALgAECgQJCwAAAA==.Natre:BAAALgADCgIJAgAAAA==.',
Ne='Nepharim:BAAALgAECgYJCwAAAA==.Nephlim:BAACLgAFFH8aAAMhAAcJFB91EQAWAgdoDAAABgBiAGkMAAAEAFoAawwAAAQARwBqDAAAAgBEAGwMAAABADcAbQwAAAEATADqDAAACABVACEABgkUH3URABYCBmgMAAAGAGIAaQwAAAQAWgBrDAAABABHAGwMAAABADcAbQwAAAEATADqDAAACABVACMAAQkAAAFKAAAAAWoMAAACAEQALgAECn8xAAIhAAkJ5iHEBgBsAwAhAAkJ5iHEBgBsAwAAAA==.Nergal:BAAALgADCgMJAwAAAA==.',
Ni='Ninobrown:BAAALgAECgYJEwAAAA==.Niny:BAAALgAECgEJAwABLgAECgkJNwAYAG4gAA==.Ninzerp:BAAALgAECgEJAQABLgAECgkJNwAYAG4gAA==.Nizano:BAABLgAECn8aAAIEAAcJ4AtUqQAaAQdoDAAABAAuAGkMAAAEACsAawwAAAQAFABqDAAABAAuAGwMAAACABsA6gwAAAUAGQBuDAAAAwASAAQABwngC1SpABoBB2gMAAAEAC4AaQwAAAQAKwBrDAAABAAUAGoMAAAEAC4AbAwAAAIAGwDqDAAABQAZAG4MAAADABIAAAA=.',
No='Noleyprays:BAAALgAECgEJAQABLgAECgMJCAAIAAAAAA==.Noryaa:BAABLgAECn8aAAIWAAYJpQVLqQDcAAZoDAAABQAOAGkMAAAFAA4AawwAAAQADwBqDAAABAADAGwMAAADABAA6gwAAAUACwAWAAYJpQVLqQDcAAZoDAAABQAOAGkMAAAFAA4AawwAAAQADwBqDAAABAADAGwMAAADABAA6gwAAAUACwAAAA==.Notabat:BAAALgADCgUJBQAAAA==.Notavoidelf:BAAALgADCgMJAwAAAA==.Notfurry:BAAALgAECgIJAgAAAA==.',
Nu='Nuadå:BAABLgAECn8gAAMZAAcJrw5QTQBLAQdoDAAABQBGAGkMAAAFAB4AawwAAAUAIQBqDAAABAASAGwMAAACABcA6gwAAAgAPwBuDAAAAwAXABkABwmvDlBNAEsBB2gMAAAEAEYAaQwAAAQAHgBrDAAABAAhAGoMAAAEABIAbAwAAAIAFwDqDAAABwA/AG4MAAADABcABwAECW4FjGoAdwAEaAwAAAEAGABpDAAAAQADAGsMAAABAAEA6gwAAAEAGQAAAA==.',
Og='Oggi:BAAALgADCgcJBwAAAA==.',
Om='Om:BAAALgAECggJDQAAAA==.',
On='Onthrox:BAAALgADCgEJAQAAAA==.',
Oo='Oorlian:BAABLgAECn8UAAMaAAUJJBGyQwDyAAVoDAAABgAwAGkMAAAFAD8AawwAAAUAHgBqDAAAAwATAGwMAAABACEAGgAFCSQRskMA8gAFaAwAAAUAMABpDAAABAA/AGsMAAAEAB4AagwAAAEAEwBsDAAAAQAhAA0ABAnbCEdOAJIABGgMAAABAB8AaQwAAAEADABrDAAAAQAOAGoMAAACACAAAAA=.',
Op='Opheleia:BAAALgADCgIJAgAAAA==.',
Or='Orallius:BAAALgADCgEJAQABLgAECggJHAAZABYiAA==.Orkid:BAAALgAECgEJAQAAAA==.',
Pa='Pawsome:BAAALgAECgQJBAABLgAECggJLQAQAEcXAA==.',
Ph='Phelyx:BAAALgAFFAIJAgAAAA==.',
Po='Pogo:BAABLgAECn8fAAIUAAkJdiR9AgAbAwloDAAABABiAGkMAAAEAF8AawwAAAQAYABqDAAAAwBiAGwMAAADAF0AbQwAAAIAWQDqDAAABQBhAG4MAAAFAFEAbwwAAAEAXQAUAAkJdiR9AgAbAwloDAAABABiAGkMAAAEAF8AawwAAAQAYABqDAAAAwBiAGwMAAADAF0AbQwAAAIAWQDqDAAABQBhAG4MAAAFAFEAbwwAAAEAXQAAAA==.Pogolock:BAAALgADCgEJAgABLgAECgkJHwAUAHYkAA==.',
Pr='Pricedd:BAAALgADCgcJCAAAAA==.Prosperina:BAAALgADCgQJBAAAAA==.Prozac:BAAALgAECgMJCAAAAA==.',
Ps='Psiberian:BAABLgAECn8lAAMDAAgJdQj4GQDGAAhoDAAABQAaAGkMAAAGABoAawwAAAYAGQBqDAAABgAgAGwMAAAFABUAbQwAAAEAAgDqDAAABgAkAG4MAAACAAsAAQAICYYHvo4AFwEIaAwAAAMAFwBpDAAAAwAYAGsMAAADABYAagwAAAMAIABsDAAAAgAVAG0MAAABAAIA6gwAAAMAHABuDAAAAgALAAMABgm8CvgZAMYABmgMAAACABoAaQwAAAMAGgBrDAAAAwAZAGoMAAADAA8AbAwAAAMAFQDqDAAAAwAkAAAA.',
Qu='Quetzani:BAAALgAECgEJAQAAAA==.',
Ra='Ranoa:BAAALgADCgkJCQAAAA==.Rastapopulos:BAAALgAECggJCgAAAA==.',
Re='Redmage:BAAALgADCgcJDwABLgAECgkJPwAWAPcdAA==.Redrocket:BAAALgAECgEJAgABLgAECgQJBwAIAAAAAA==.Remixed:BAAALgAECgMJAwAAAA==.Reptilectric:BAAALgAECgQJBAAAAA==.Retxd:BAAALgADCgEJAQABLgAECgQJBQAIAAAAAA==.',
Ri='Rikaku:BAABLgAECn8uAAIWAAcJ6xHiPgCzAQdoDAAACwA+AGkMAAAIADcAawwAAAkAPgBqDAAABwBFAGwMAAAFAC0AbQwAAAIABgDqDAAABAApABYABwnrEeI+ALMBB2gMAAALAD4AaQwAAAgANwBrDAAACQA+AGoMAAAHAEUAbAwAAAUALQBtDAAAAgAGAOoMAAAEACkAAAA=.',
Ro='Roastbeef:BAAALgAECgEJAQAAAA==.Ronananna:BAAALgADCgkJDwABLgADCgYJBgAIAAAAAA==.Rosemery:BAAALgAECgYJBwAAAA==.',
['Rä']='Räpodac:BAABLgAECn8qAAIXAAcJlg15KAAeAQdoDAAABwAdAGkMAAAHACUAawwAAAcAIQBqDAAABgAcAGwMAAAEABkA6gwAAAgAMgBuDAAAAwAfABcABwmWDXkoAB4BB2gMAAAHAB0AaQwAAAcAJQBrDAAABwAhAGoMAAAGABwAbAwAAAQAGQDqDAAACAAyAG4MAAADAB8AAAA=.',
Sa='Sagaba:BAAALgAECgYJCwAAAA==.Saphil:BAAALgADCgkJFAAAAA==.Saramus:BAAALgAECgEJAQAAAA==.',
Sc='Schizo:BAACLgAFFH8IAAIhAAIJtxokvQCQAAJoDAAAAgBDAOoMAAAGAEUAIQACCbcaJL0AkAACaAwAAAIAQwDqDAAABgBFAC4ABAp/HQACIQAHCeAh80AANQIAIQAHCeAh80AANQIAAAA=.Schmaladin:BAAALgADCgUJCAAAAA==.',
Se='Searena:BAAALgAECgEJAgAAAA==.Sefiroth:BAACLgAFFH8FAAIMAAMJfwphZgCmAANoDAAAAQAkAGkMAAABAAMA6gwAAAMAKAAMAAMJfwphZgCmAANoDAAAAQAkAGkMAAABAAMA6gwAAAMAKAAuAAQKfy4AAgwABwnTFXxVAHgBAAwABwnTFXxVAHgBAAAA.Selillea:BAAALgAECgYJBwAAAA==.Semarius:BAAALgAECgEJAwABLgAECgkJNwAXAKQhAA==.Semdorii:BAABLgAECn83AAIXAAkJpCG5AwAHAwloDAAACQBcAGkMAAAIAF0AawwAAAgAUwBqDAAABwBhAGwMAAAHAFoAbQwAAAQAUADqDAAABwBRAG4MAAAEAEYAbwwAAAEAYQAXAAkJpCG5AwAHAwloDAAACQBcAGkMAAAIAF0AawwAAAgAUwBqDAAABwBhAGwMAAAHAFoAbQwAAAQAUADqDAAABwBRAG4MAAAEAEYAbwwAAAEAYQAAAA==.Sephywrath:BAABLgAECn8+AAIkAAkJoRvdAQBTAgloDAAACQBRAGkMAAAJAD4AawwAAAkATwBqDAAACABRAGwMAAAIAE0AbQwAAAMATgDqDAAACQBBAG4MAAAFADIAbwwAAAIARwAkAAkJoRvdAQBTAgloDAAACQBRAGkMAAAJAD4AawwAAAkATwBqDAAACABRAGwMAAAIAE0AbQwAAAMATgDqDAAACQBBAG4MAAAFADIAbwwAAAIARwAAAA==.Seralith:BAABLgAECn9BAAIhAAkJkyVhAgBzAwloDAAABwBiAGkMAAAJAGAAawwAAAkAXQBqDAAACABjAGwMAAAIAGIAbQwAAAYAYQDqDAAACQBgAG4MAAAGAFsAbwwAAAMAYQAhAAkJkyVhAgBzAwloDAAABwBiAGkMAAAJAGAAawwAAAkAXQBqDAAACABjAGwMAAAIAGIAbQwAAAYAYQDqDAAACQBgAG4MAAAGAFsAbwwAAAMAYQAAAA==.Seranight:BAACLgAFFH8QAAMjAAQJtiTdCwCQAQRoDAAABwBfAGkMAAAEAFoAawwAAAIAXgDqDAAAAwBeACMABAm2JN0LAJABBGgMAAAHAF8AaQwAAAQAWgBrDAAAAgBeAOoMAAACAF4AIQABCScBdQUBKgAB6gwAAAEAAgAuAAQKf0MAAiMACQl8JnQAAHUDACMACQl8JnQAAHUDAAAA.Seven:BAAALgAECgIJBAABLgAECgkJIwABAAwVAA==.Sevenpaws:BAAALgAECgYJCAABLgAECgkJQAANAHclAA==.',
Sh='Shadowchi:BAAALgAECgQJBQAAAA==.Shaidon:BAAALgAECgYJBgAAAQ==.Shaly:BAABLgAECn8jAAIYAAgJPwZsnQA2AQhoDAAABgAWAGkMAAAGABIAawwAAAYADgBqDAAABgAgAGwMAAAFABIAbQwAAAEACQDqDAAABAAKAG4MAAABABEAGAAICT8GbJ0ANgEIaAwAAAYAFgBpDAAABgASAGsMAAAGAA4AagwAAAYAIABsDAAABQASAG0MAAABAAkA6gwAAAQACgBuDAAAAQARAAAA.Shattwrath:BAAALgAECgEJAQAAAA==.Shinjihirako:BAAALgAECgQJBAAAAA==.Shirohige:BAABLgAECn8XAAIfAAUJ1w/kOACnAAVoDAAABwA0AGkMAAAGAC0AawwAAAYAKQBqDAAAAwAcAGwMAAABABYAHwAFCdcP5DgApwAFaAwAAAcANABpDAAABgAtAGsMAAAGACkAagwAAAMAHABsDAAAAQAWAAAA.Shlonglord:BAAALgADCgIJAgAAAA==.Shylan:BAAALgAFFAEJAgAAAA==.',
Si='Simmer:BAAALgADCgMJAwAAAA==.',
Sm='Smasha:BAAALgAECgQJDgAAAA==.',
Sn='Snaarf:BAAALgADCgEJAQABLgAECgUJFAAlANIDAA==.Snayre:BAACLgAFFH8GAAIUAAMJ1hkqFwAHAQNoDAAAAwBfAGkMAAACADUA6gwAAAEAMQAUAAMJ1hkqFwAHAQNoDAAAAwBfAGkMAAACADUA6gwAAAEAMQAuAAQKfzUAAhQACQlxHgoFANECABQACQlxHgoFANECAAAA.Snipêr:BAABLgAECn8cAAIWAAgJtBNRPwDWAQhoDAAABAA+AGkMAAAEAC8AawwAAAQAPABqDAAAAwArAGwMAAAFAD8AbQwAAAEAEgDqDAAABgBMAG4MAAABABcAFgAICbQTUT8A1gEIaAwAAAQAPgBpDAAABAAvAGsMAAAEADwAagwAAAMAKwBsDAAABQA/AG0MAAABABIA6gwAAAYATABuDAAAAQAXAAAA.Snowlia:BAACLgAFFH8JAAIPAAMJahN9RgC6AANoDAAABAAzAGkMAAABADEA6gwAAAQAMAAPAAMJahN9RgC6AANoDAAABAAzAGkMAAABADEA6gwAAAQAMAAuAAQKfyEAAw8ACQkxE/A1AKsBAA8ACQkxE/A1AKsBABAAAQk3D6ecAC0AAAAA.',
So='Soularis:BAAALgAECgYJCAAAAA==.Soulslice:BAEALgAECggJCAABLgAECgQJEQAIAAAAAA==.Sovrano:BAAALgADCgEJAQAAAA==.',
Sp='Spectrê:BAAALgADCgMJAwAAAA==.Spiralpad:BAAALgADCgYJCgABLgAECggJHgAEAKkaAA==.Spybro:BAAALgAECgcJEgAAAA==.',
Sq='Squidtechnic:BAAALgAECgUJEAAAAA==.',
St='Stalkingwolf:BAABLgAECn8gAAIjAAcJ1xacGwBtAQdoDAAABQBLAGkMAAAFAEcAawwAAAUANABqDAAABABKAGwMAAACABIA6gwAAAgAPwBuDAAAAwBFACMABwnXFpwbAG0BB2gMAAAFAEsAaQwAAAUARwBrDAAABQA0AGoMAAAEAEoAbAwAAAIAEgDqDAAACAA/AG4MAAADAEUAAAA=.',
Su='Suz:BAAALgADCgEJAQAAAA==.Suzuya:BAAALgAECgYJEAAAAA==.',
Sy='Sylailia:BAACLgAFFH8GAAIHAAMJRArxLgCoAANoDAAAAwAkAGkMAAACABkA6gwAAAEAEQAHAAMJRArxLgCoAANoDAAAAwAkAGkMAAACABkA6gwAAAEAEQAuAAQKfzQAAgcACQliHDALAJICAAcACQliHDALAJICAAAA.Syleta:BAAALgADCgMJBAAAAA==.',
['Sí']='Síenna:BAAALgAECgEJAgAAAA==.',
Ta='Tamatoa:BAAALgAECgIJAgABLgAFFAMJBAAIAAAAAA==.',
Tc='Tcon:BAABLgAECn8UAAIUAAcJRBVnHwCXAQdoDAAABABAAGkMAAADAEYAawwAAAMAPABqDAAAAgBBAGwMAAACADYAbQwAAAEACQDqDAAABQBDABQABwlEFWcfAJcBB2gMAAAEAEAAaQwAAAMARgBrDAAAAwA8AGoMAAACAEEAbAwAAAIANgBtDAAAAQAJAOoMAAAFAEMAAAA=.',
Td='Tdragon:BAAALgADCgkJEgABLgAECggJLAAaAI8UAA==.',
Te='Tearany:BAAALgADCgUJBgAAAA==.',
Th='Thissa:BAABLgAECn8uAAMHAAgJrx/YDwBRAghoDAAACABVAGkMAAAHAFQAawwAAAcAWgBqDAAABgBJAGwMAAAGAFMAbQwAAAIAQwDqDAAABwBaAG4MAAADAEEABwAICa8f2A8AUQIIaAwAAAcAVQBpDAAABwBUAGsMAAAHAFoAagwAAAYASQBsDAAABgBTAG0MAAACAEMA6gwAAAcAWgBuDAAAAwBBACAAAQlIGbgzADMAAWgMAAABAEAAAS4ABRQDCQMACAAAAAA=.Thundarah:BAAALgADCgcJFwAAAA==.Thundruid:BAAALgADCgUJCgAAAA==.Thuniellas:BAAALgADCggJGQAAAA==.',
Ti='Tiarcis:BAABLgAECn8xAAIWAAkJbBhIHgBiAgloDAAABgBEAGkMAAAGAFEAawwAAAYASQBqDAAABgA5AGwMAAAGACMAbQwAAAIARQDqDAAACAA2AG4MAAAGADQAbwwAAAMAQAAWAAkJbBhIHgBiAgloDAAABgBEAGkMAAAGAFEAawwAAAYASQBqDAAABgA5AGwMAAAGACMAbQwAAAIARQDqDAAACAA2AG4MAAAGADQAbwwAAAMAQAAAAA==.',
To='Toeknee:BAAALgAECgMJAwAAAA==.Tostitos:BAAALgADCgkJCQABLgAECggJLAAaAI8UAA==.Totemsalot:BAACLgAFFH8MAAIPAAQJjBskIwBAAQRoDAAABQBNAGkMAAADAEIAawwAAAIARwDqDAAAAgBCAA8ABAmMGyQjAEABBGgMAAAFAE0AaQwAAAMAQgBrDAAAAgBHAOoMAAACAEIALgAECn8bAAIPAAkJxiP5AgCHAwAPAAkJxiP5AgCHAwAAAA==.',
Tr='Treesummoner:BAABLgAECn8tAAQBAAkJjRiKJwA1AgloDAAABgBFAGkMAAAGAE8AawwAAAYALgBqDAAABQBJAGwMAAAGAEUAbQwAAAIAPwDqDAAABwBAAG4MAAAFAD8AbwwAAAIALgABAAkJjRiKJwA1AgloDAAABQBFAGkMAAAEAE8AawwAAAMALgBqDAAAAgBJAGwMAAAEAEUAbQwAAAIAPwDqDAAABgBAAG4MAAAFAD8AbwwAAAIALgADAAUJ6wpwLAAMAQVpDAAAAQAIAGsMAAACACAAagwAAAMAOgBsDAAAAgA0AOoMAAABABIAAgADCaEL0RoAoAADaAwAAAEADQBpDAAAAQAsAGsMAAABAB8AAAA=.Trialboost:BAAALgADCggJCQAAAA==.Tritanks:BAABLgAECn86AAIJAAkJ+B0bBAB1AgloDAAACQBPAGkMAAAIAE8AawwAAAkAVABqDAAABwBYAGwMAAAHAFAAbQwAAAUASQDqDAAACABeAG4MAAAEAEwAbwwAAAEALQAJAAkJ+B0bBAB1AgloDAAACQBPAGkMAAAIAE8AawwAAAkAVABqDAAABwBYAGwMAAAHAFAAbQwAAAUASQDqDAAACABeAG4MAAAEAEwAbwwAAAEALQAAAA==.Troy:BAAALgAECgIJAwAAAA==.',
Tu='Tutsee:BAAALgADCggJFAAAAA==.',
['Tå']='Tåbi:BAAALgADCgcJCwABLgAECgUJBQAIAAAAAA==.',
Un='Unbantam:BAAALgAECgUJBgAAAA==.',
Va='Valeq:BAAALgADCgkJCAAAAA==.Valeyka:BAABLgAECn8UAAIaAAcJpgzHNgAsAQdoDAAAAwAaAGkMAAADACYAawwAAAMAFQBqDAAAAQAVAGwMAAACACYA6gwAAAYAKwBuDAAAAgAaABoABwmmDMc2ACwBB2gMAAADABoAaQwAAAMAJgBrDAAAAwAVAGoMAAABABUAbAwAAAIAJgDqDAAABgArAG4MAAACABoAAAA=.Valiente:BAAALgAECgIJAgAAAA==.Valkah:BAAALgAECgEJAQAAAA==.Vasilia:BAABLgAECn8uAAIjAAgJDhfHEwDEAQhoDAAACQBQAGkMAAAIAEoAawwAAAgATQBqDAAABgBFAGwMAAAFADcAbQwAAAEAEgDqDAAACABUAG4MAAABABYAIwAICQ4XxxMAxAEIaAwAAAkAUABpDAAACABKAGsMAAAIAE0AagwAAAYARQBsDAAABQA3AG0MAAABABIA6gwAAAgAVABuDAAAAQAWAAAA.',
Ve='Velanna:BAAALgAECgIJAgAAAA==.Vexara:BAAALgAECgEJAgAAAA==.',
Vi='Viego:BAAALgAECgMJBAAAAA==.Viradi:BAAALgAECgYJCQAAAA==.',
Vo='Voclus:BAAALgAECgYJEAAAAA==.',
Wa='Wall:BAAALgAECgYJEAAAAA==.Warlodshenu:BAAALgADCgYJBgAAAA==.Warptouched:BAAALgADCgYJBgAAAA==.',
Wh='Whatapal:BAAALgAECgUJBwAAAA==.',
Wi='Wightfire:BAAALgADCgEJAQAAAA==.Wightknight:BAAALgADCgYJBgAAAA==.Wightranger:BAAALgADCgYJCwAAAA==.Wightwarrior:BAAALgADCgcJCgAAAA==.',
Wu='Wuwindtang:BAAALgAECgUJDAAAAA==.',
Xa='Xalatoes:BAAALgADCgQJBAAAAA==.',
Xe='Xeniuz:BAAALgADCgMJAwAAAA==.',
Xi='Xianfei:BAAALgAECgQJBQAAAA==.Xiles:BAABLgAECn8XAAIKAAYJqQVrZAC2AAZoDAAABAAJAGkMAAAEAAcAawwAAAQAEQBqDAAABAAMAGwMAAACABUA6gwAAAUAEAAKAAYJqQVrZAC2AAZoDAAABAAJAGkMAAAEAAcAawwAAAQAEQBqDAAABAAMAGwMAAACABUA6gwAAAUAEAAAAA==.Xiletank:BAAALgAECgUJBQAAAA==.',
Za='Zachxd:BAABLgAECn84AAIMAAcJ6RlNTQCQAQdoDAAACgBYAGkMAAAKAEMAawwAAAoAUABqDAAACAAoAGwMAAAJAE0AbQwAAAEAAQDqDAAACABSAAwABwnpGU1NAJABB2gMAAAKAFgAaQwAAAoAQwBrDAAACgBQAGoMAAAIACgAbAwAAAkATQBtDAAAAQABAOoMAAAIAFIAAS4ABRQCCQgAIQC3GgA=.Zanthe:BAAALgAECgQJDgAAAA==.Zapanese:BAAALgADCgMJBAAAAA==.Zapt:BAAALgAECgIJAgAAAA==.Zaptism:BAABLgAECn8xAAMNAAkJVB9XCwCaAgloDAAABgBhAGkMAAAGAF8AawwAAAcAXgBqDAAABQBYAGwMAAAGAFoAbQwAAAQATwDqDAAACABTAG4MAAAEACkAbwwAAAMAMgANAAkJVB9XCwCaAgloDAAABQBhAGkMAAADAF8AawwAAAcAXgBqDAAABQBYAGwMAAAEAFoAbQwAAAQATwDqDAAABQBTAG4MAAACACkAbwwAAAMAMgAOAAUJZgzTQwDhAAVoDAAAAQAMAGkMAAADAB4AbAwAAAIANQDqDAAAAwAUAG4MAAACACgAAAA=.Zapunch:BAAALgADCgEJAQAAAA==.Zarissaa:BAAALgADCgkJEAAAAA==.Zatha:BAAALgADCgkJJgAAAA==.',
Ze='Zerowins:BAAALgADCgcJCAAAAA==.',
Zh='Zhanaug:BAAALgAECgYJEAABLgAFFAIJBwAJAB4VAA==.Zhanbear:BAAALgAECgUJBQABLgAFFAIJBwAJAB4VAA==.Zhanbrew:BAACLgAFFH8IAAIcAAMJhh1ZJQAFAQNoDAAABABEAGkMAAABAFwA6gwAAAMAQQAcAAMJhh1ZJQAFAQNoDAAABABEAGkMAAABAFwA6gwAAAMAQQAuAAQKfx4AAhwACQknHhwHALoCABwACQknHhwHALoCAAEuAAUUAgkHAAkAHhUA.Zhanfury:BAAALgAFFAEJAQABLgAFFAIJBwAJAB4VAA==.',
Zi='Zinder:BAABLgAECn8nAAMlAAgJTQjFQwALAQhoDAAABgASAGkMAAAGABcAawwAAAYAIQBqDAAABQAZAGwMAAAFACYAbQwAAAIABwDqDAAABgATAG4MAAADAAcAJQAICU0IxUMACwEIaAwAAAYAEgBpDAAABgAXAGsMAAAGACEAagwAAAUAGQBsDAAABQAmAG0MAAACAAcA6gwAAAUAEwBuDAAAAwAHACYAAQksA3woACEAAeoMAAABAAgAAAA=.Zipit:BAABLgAECn8nAAIDAAkJjRfqBAAVAgloDAAABgBaAGkMAAAFAEYAawwAAAUAQABqDAAABQAwAGwMAAAEACgAbQwAAAQAGgDqDAAABgBNAG4MAAADADgAbwwAAAEANgADAAkJjRfqBAAVAgloDAAABgBaAGkMAAAFAEYAawwAAAUAQABqDAAABQAwAGwMAAAEACgAbQwAAAQAGgDqDAAABgBNAG4MAAADADgAbwwAAAEANgAAAA==.',
Zy='Zyae:BAAALgAECgEJBAAAAA==.Zyrinthia:BAAALgADCgYJBgAAAA==.',
['Æn']='Ænder:BAAALgADCgMJAwABLgAECggJGwAfALsWAA==.',
['Öb']='Öboron:BAACLgAFFH8JAAMUAAQJVgPsGQDxAARoDAAABAAEAGkMAAACAAQAawwAAAEABADqDAAAAgAUABQABAlWA+wZAPEABGgMAAACAAQAaQwAAAIABABrDAAAAQAEAOoMAAACABQAFQABCcsBkzQALAABaAwAAAIABAAuAAQKfy4ABBQACQmMF60NAEQCABQACQknFq0NAEQCABUACAlWECgqANoBABYABgkpFTJTAG8BAAAA.',
['Üz']='Üz:BAABLgAECn8kAAIXAAgJvhY0FgDBAQhoDAAABgBQAGkMAAAGAE4AawwAAAYAPQBqDAAABgBWAGwMAAAFAD8AbQwAAAEAHwDqDAAABQA9AG4MAAABAB4AFwAICb4WNBYAwQEIaAwAAAYAUABpDAAABgBOAGsMAAAGAD0AagwAAAYAVgBsDAAABQA/AG0MAAABAB8A6gwAAAUAPQBuDAAAAQAeAAAA.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
