local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Paladin-Holy','Evoker-Preservation','Unknown-Unknown','Evoker-Augmentation','Evoker-Devastation','Monk-Brewmaster','Warlock-Demonology','Warlock-Destruction','Paladin-Protection','Warrior-Arms','Warrior-Fury','Warrior-Protection','Shaman-Elemental','DemonHunter-Devourer','DemonHunter-Havoc','DemonHunter-Vengeance','Priest-Shadow','Priest-Discipline','Druid-Guardian','Rogue-Subtlety','Mage-Frost','Rogue-Assassination','Paladin-Retribution','Hunter-BeastMastery','Rogue-Outlaw','DeathKnight-Blood','Monk-Windwalker','Monk-Mistweaver','Shaman-Restoration','Priest-Holy','Warlock-Affliction','DeathKnight-Unholy','Druid-Feral','Hunter-Marksmanship','Mage-Fire','Mage-Arcane','Druid-Balance',}
local provider = {region='US',realm='BleedingHollow',name='US',type='subscribers',zone=46,date='2026-06-14',data={Ad='Addex:BAEBLgAFFH8NAAIBAAYJjxM5BQCKAQZoDAAAAwA0AGkMAAACAD0AawwAAAIADQBqDAAAAgAiAGwMAAABACsA6gwAAAMAXgABAAYJjxM5BQCKAQZoDAAAAwA0AGkMAAACAD0AawwAAAIADQBqDAAAAgAiAGwMAAABACsA6gwAAAMAXgABLgAFFAkJQwACALwjAA==.',
Ae='Aeveracy:BAEALgADCgMJAwABLgAECgIJAgADAAAAAA==.',
Am='Ambient:BAECLgAFFH9DAAMCAAkJvCMPAAC7AwloDAAACgBhAGkMAAAKAGMAawwAAAkAXwBqDAAACQBjAGwMAAAIAGMAbQwAAAQAVADqDAAACgBjAG4MAAAEAFgAbwwAAAMAOwACAAkJvCMPAAC7AwloDAAACABhAGkMAAAKAGMAawwAAAkAXwBqDAAACQBjAGwMAAAIAGMAbQwAAAQAVADqDAAACgBjAG4MAAAEAFgAbwwAAAMAOwAEAAEJPxd+IABQAAFoDAAAAgA7AC4ABAp/HQADAgAJCXMjvgQAAwMAAgAICSsjvgQAAwMABQABCYgT1joARAAAAAA=.',
Av='Avarat:BAEALgADCgMJAwABLgAFFAgJHAAGAK8iAA==.',
Br='Briéè:BAEBLgAECn8aAAMHAAkJNBX4SgC5AQloDAAABQBLAGkMAAAEADMAawwAAAQALwBqDAAAAwAuAGwMAAADAD8AbQwAAAEAPADqDAAAAwAWAG4MAAACAD4AbwwAAAEAMQAHAAgJKBP4SgC5AQhoDAAAAwAvAGkMAAADACQAagwAAAEAKgBsDAAAAwA/AG0MAAABADwA6gwAAAMAFgBuDAAAAgA+AG8MAAABADEACAAECc4W3SAApAAEaAwAAAIASwBpDAAAAQAzAGsMAAAEAC8AagwAAAIALgAAAA==.Bruwon:BAECLgAFFH82AAIGAAgJtiGfAABJAghoDAAACQBcAGkMAAAJAGMAawwAAAkAWgBqDAAACABIAGwMAAAHAGIAbQwAAAEATwDqDAAACgBeAG4MAAABADIABgAICbYhnwAASQIIaAwAAAkAXABpDAAACQBjAGsMAAAJAFoAagwAAAgASABsDAAABwBiAG0MAAABAE8A6gwAAAoAXgBuDAAAAQAyAC4ABAp/IQACBgAJCUAhxwQAPgMABgAJCUAhxwQAPgMAAAA=.',
Ch='Charzie:BAEBLgAFFH8FAAIJAAUJRxiBBgAUAQVoDAAAAQBOAGkMAAABAEkAawwAAAEAOQBqDAAAAQAzAOoMAAABACcACQAFCUcYgQYAFAEFaAwAAAEATgBpDAAAAQBJAGsMAAABADkAagwAAAEAMwDqDAAAAQAnAAEuAAUUCAk2AAYAtiEA.Chme:BAECLgAFFH8WAAMKAAYJVxV+DQBzAQZoDAAABgAjAGkMAAAFAFUAawwAAAQALQBqDAAAAgAxAGwMAAABABYA6gwAAAQAUwAKAAYJVxV+DQBzAQZoDAAABAAjAGkMAAAEAFUAawwAAAQALQBqDAAAAgAxAGwMAAABABYA6gwAAAQAUwALAAIJpQWnSAB7AAJoDAAAAgAKAGkMAAABABIALgAECn8ZAAQKAAkJJyIlDAAiAgAKAAgJWx4lDAAiAgAMAAcJGiBLEwC3AQALAAUJ1Q05bAAFAQAAAA==.Chmevoker:BAEALgAECgUJBQABLgAFFAYJFgAKAFcVAA==.',
Ci='Ciprox:BAEBLgAECn8VAAINAAgJpx7lFgAtAghoDAAAAwBVAGkMAAADAEcAawwAAAMAXABqDAAAAwBQAGwMAAADAGAAbQwAAAIAOADqDAAAAwBcAG4MAAABADcADQAICace5RYALQIIaAwAAAMAVQBpDAAAAwBHAGsMAAADAFwAagwAAAMAUABsDAAAAwBgAG0MAAACADgA6gwAAAMAXABuDAAAAQA3AAEuAAUUCAkcAA4A/BgA.',
Cy='Cyprexdh:BAECLgAFFH8cAAMOAAgJ/BgBDwA0AghoDAAABwBjAGkMAAAFAFoAawwAAAQASwBqDAAABABbAGwMAAABAB0AbQwAAAEADwDqDAAABQBbAG4MAAABAC0ADgAICQ0XAQ8ANAIIaAwAAAQAQABpDAAABABaAGsMAAADAEsAagwAAAQAWwBsDAAAAQAdAG0MAAABAA8A6gwAAAQAWwBuDAAAAQAtAA8ABAl/Ge8BAHsBBGgMAAADAGMAaQwAAAEABQBrDAAAAQBBAOoMAAABAFoALgAECn8aAAQPAAgJ8CU5AwBSAwAPAAgJWyU5AwBSAwAOAAMJsiSZewA1AQAQAAEJAAC2LQApAAAAAA==.',
Da='Danilynn:BAEALgADCggJFAABLgAECggJKwARAL8DAA==.Danitsia:BAEBLgAECn8rAAMRAAgJvwMTTADdAAhoDAAABwAKAGkMAAAHAAwAawwAAAcACQBqDAAABgAUAGwMAAAGAAsAbQwAAAIABwDqDAAABwAIAG4MAAABAAYAEQAICb8DE0wA3QAIaAwAAAcACgBpDAAABwAMAGsMAAAGAAkAagwAAAYAFABsDAAABQALAG0MAAACAAcA6gwAAAYACABuDAAAAQAGABIAAwnjAHVRAEYAA2sMAAABAAIAbAwAAAEAAwDqDAAAAQAAAAAA.',
De='Delabrand:BAEALgAECgYJCQABLgAFFAgJJQAMAIkmAA==.Delajuv:BAEBLgAFFH8JAAITAAUJrx5HCQBXAQVoDAAAAgBTAGkMAAACAEwAawwAAAIATQBqDAAAAQAJAOoMAAACAEwAEwAFCa8eRwkAVwEFaAwAAAIAUwBpDAAAAgBMAGsMAAACAE0AagwAAAEACQDqDAAAAgBMAAEuAAUUCAklAAwAiSYA.Delarage:BAECLgAFFH8lAAIMAAgJiSaDAAACAwhoDAAABwBjAGkMAAAFAGMAawwAAAUAYwBqDAAABgBiAGwMAAAEAGQAbQwAAAMAYQDqDAAABgBjAG4MAAABAF4ADAAICYkmgwAAAgMIaAwAAAcAYwBpDAAABQBjAGsMAAAFAGMAagwAAAYAYgBsDAAABABkAG0MAAADAGEA6gwAAAYAYwBuDAAAAQBeAC4ABAp/IQACDAAJCf4m/QAAkAMADAAJCf4m/QAAkAMAAAA=.Deleerious:BAECLgAFFH8UAAIUAAYJniVkDQCzAQZoDAAABQBiAGkMAAAFAGEAawwAAAIAXgBqDAAAAQBdAGwMAAABAF4A6gwAAAYAYAAUAAYJniVkDQCzAQZoDAAABQBiAGkMAAAFAGEAawwAAAIAXgBqDAAAAQBdAGwMAAABAF4A6gwAAAYAYAAuAAQKfyoAAhQACAkdJKIFADgDABQACAkdJKIFADgDAAAA.',
Do='Doriel:BAEALgAECgMJBAABLgAFFAUJHAAVAEkdAA==.',
Du='Dubsstree:BAEALgADCgYJBgABLgAFFAcJHgAHANgZAA==.',
Dw='Dwarfwarloc:BAEBLgAECn8bAAIHAAgJKSKiGACPAghoDAAABABgAGkMAAAEAFMAawwAAAQAWgBqDAAABABgAGwMAAADAGEAbQwAAAEARADqDAAABgBfAG8MAAABAE4ABwAICSkiohgAjwIIaAwAAAQAYABpDAAABABTAGsMAAAEAFoAagwAAAQAYABsDAAAAwBhAG0MAAABAEQA6gwAAAYAXwBvDAAAAQBOAAAA.',
Eg='Egirlarmpits:BAEALgAFFAMJAwABLgAFFAYJDgANAOgOAA==.',
Em='Emellious:BAECLgAFFH8bAAIUAAgJwRPnBwAeAghoDAAABgBPAGkMAAAFAFsAawwAAAMAGgBqDAAAAwA6AGwMAAABAA0AbQwAAAIAIADqDAAABgBXAG4MAAABABcAFAAICcET5wcAHgIIaAwAAAYATwBpDAAABQBbAGsMAAADABoAagwAAAMAOgBsDAAAAQANAG0MAAACACAA6gwAAAYAVwBuDAAAAQAXAC4ABAp/HAADFAAICQQhoQwAzgIAFAAICQQhoQwAzgIAFgABCZALgh8ANQAAAAA=.',
Fe='Feetsmeller:BAEALgADCgIJAgABLgAFFAgJHAAGAK8iAA==.',
Fr='Freddyfletch:BAEALgADCgUJBQAAAA==.',
Fu='Funkaroused:BAEBLgAECn8vAAILAAgJmRouJgDHAQhoDAAABwBbAGkMAAAHAEcAawwAAAcAQABqDAAABgBFAGwMAAAHAEsAbQwAAAEAMADqDAAACABKAG4MAAAEADIACwAICZkaLiYAxwEIaAwAAAcAWwBpDAAABwBHAGsMAAAHAEAAagwAAAYARQBsDAAABwBLAG0MAAABADAA6gwAAAgASgBuDAAABAAyAAAA.',
Gi='Giantmagic:BAEBLgAECn8bAAIVAAcJQR19XQAiAgdoDAAABABOAGkMAAAEAFIAawwAAAQAWwBqDAAABgBOAGwMAAACAD4AbQwAAAIAQgDqDAAABQBEABUABwlBHX1dACICB2gMAAAEAE4AaQwAAAQAUgBrDAAABABbAGoMAAAGAE4AbAwAAAIAPgBtDAAAAgBCAOoMAAAFAEQAAS4ABAoICSMAFwAEJAA=.',
Gj='Gjlo:BAECLgAFFH8VAAMLAAQJSxMzIgAoAQRoDAAACABGAGkMAAAFACgAawwAAAIAGwDqDAAABgA7AAsABAlLEzMiACgBBGgMAAAGAEYAaQwAAAQAKABrDAAAAgAbAOoMAAAGADsADAACCaQDKA4AZQACaAwAAAIAEQBpDAAAAQAAAC4ABAp/XQADCwAJCQ4iLQUADwMACwAJCdYhLQUADwMADAAHCVgW3xkAaQEAAS4ABRQFCRYAGAAjIAA=.',
Gr='Gragh:BAEALgAECgcJDAABLgAFFAUJHAAVAEkdAA==.Gronknose:BAEBLgAECn8WAAIZAAcJ0iHgAQCcAgdoDAAAAwBVAGkMAAAEAFwAawwAAAQATABqDAAAAwBeAGwMAAACAFcAbQwAAAEAUgDqDAAABQBfABkABwnSIeABAJwCB2gMAAADAFUAaQwAAAQAXABrDAAABABMAGoMAAADAF4AbAwAAAIAVwBtDAAAAQBSAOoMAAAFAF8AAS4ABRQDCQUABgB4HAA=.',
Ha='Hakdh:BAEALgAECgYJBgABLgAFFAYJGwAaAAcQAA==.Hakdk:BAECLgAFFH8bAAIaAAYJBxD+BQA7AQZoDAAABgAlAGkMAAADACMAawwAAAMAJwBqDAAABgAaAG0MAAABAAMA6gwAAAgAWQAaAAYJBxD+BQA7AQZoDAAABgAlAGkMAAADACMAawwAAAMAJwBqDAAABgAaAG0MAAABAAMA6gwAAAgAWQAuAAQKfxkAAhoACAmlHtMKAGoCABoACAmlHtMKAGoCAAAA.Hakgek:BAEBLgAFFH8KAAITAAUJFAwUCgBKAQVoDAAAAgAlAGkMAAACACgAawwAAAIAJgBsDAAAAwAdAG4MAAABAAgAEwAFCRQMFAoASgEFaAwAAAIAJQBpDAAAAgAoAGsMAAACACYAbAwAAAMAHQBuDAAAAQAIAAEuAAUUBgkbABoABxAA.Hakmonk:BAEBLgAFFH8GAAIGAAQJSxHODQAWAQRoDAAAAgAmAGkMAAACAEsAawwAAAEAEQDqDAAAAQAuAAYABAlLEc4NABYBBGgMAAACACYAaQwAAAIASwBrDAAAAQARAOoMAAABAC4AAS4ABRQGCRsAGgAHEAA=.Haksham:BAEALgAECgkJDQABLgAFFAYJGwAaAAcQAA==.Hakwar:BAEALgAECgUJBQABLgAFFAYJGwAaAAcQAA==.Halosbrew:BAECLgAFFH8JAAIGAAQJqhnoDwADAQRoDAAAAgBLAGkMAAADAFYAawwAAAEAGgDqDAAAAwBKAAYABAmqGegPAAMBBGgMAAACAEsAaQwAAAMAVgBrDAAAAQAaAOoMAAADAEoALgAECn8UAAMGAAgJRx4TFQBjAgAGAAcJzSETFQBjAgAbAAUJaRO9PAAoAQAAAA==.Halosdk:BAEBLgAFFH8YAAIaAAUJZiJsDwCDAQVoDAAABQBTAGkMAAAEAFkAawwAAAQAUABqDAAAAwBAAOoMAAAIAGIAGgAFCWYibA8AgwEFaAwAAAUAUwBpDAAABABZAGsMAAAEAFAAagwAAAMAQADqDAAACABiAAEuAAUUBQkJAAYAqhkA.Halosmage:BAEALgAECggJDgABLgAFFAUJCQAGAKoZAA==.',
He='Heavensfeel:BAECLgAFFH8KAAICAAQJPCChEQB1AQRoDAAABABgAGkMAAABAE4AawwAAAEAPgDqDAAABABdAAIABAk8IKERAHUBBGgMAAAEAGAAaQwAAAEATgBrDAAAAQA+AOoMAAAEAF0ALgAECn87AAQCAAkJEx8MCAC7AgACAAkJEx8MCAC7AgAEAAkJhB1lCgCxAgAFAAYJQRlGBwDIAQABLgAFFAUJCQAGAKoZAA==.',
In='Inaríus:BAEBLgAECn8jAAIXAAgJBCSPEQDaAghoDAAABwBaAGkMAAAGAFoAawwAAAUAVwBqDAAABABRAGwMAAAEAGEA6gwAAAUAYQBuDAAAAgBUAG8MAAACAGAAFwAICQQkjxEA2gIIaAwAAAcAWgBpDAAABgBaAGsMAAAFAFcAagwAAAQAUQBsDAAABABhAOoMAAAFAGEAbgwAAAIAVABvDAAAAgBgAAAA.Initiative:BAEBLgAECn8nAAQcAAkJQx4qEQCTAgloDAAABQBXAGkMAAAFAFwAawwAAAYAXwBqDAAABAA8AGwMAAAFAEYAbQwAAAIASQDqDAAABgBRAG4MAAADAD0AbwwAAAMASQAcAAgJcB4qEQCTAghoDAAAAgBXAGkMAAACAFwAawwAAAMAXwBqDAAAAgA8AGwMAAACAEYAbQwAAAIASQDqDAAAAgBRAG4MAAABAD0AGwAICSMiWxoADQIIaAwAAAEAWQBpDAAAAQBdAGsMAAABAF4AagwAAAEAVQBsDAAAAwBgAOoMAAADAFIAbgwAAAIASgBvDAAAAwBSAAYABQl0IoMjAI0BBWgMAAACAFYAaQwAAAIAVQBrDAAAAgBbAGoMAAABADkA6gwAAAEAWAAAAA==.',
It='Itsgrippy:BAEALgAECgYJDgAAAA==.',
Ke='Keeflan:BAECLgAFFH8OAAINAAYJ6A60EgCEAQZoDAAAAwA8AGkMAAADABoAawwAAAIAMgBtDAAAAQAKAOoMAAAEAEUAbgwAAAEACwANAAYJ6A60EgCEAQZoDAAAAwA8AGkMAAADABoAawwAAAIAMgBtDAAAAQAKAOoMAAAEAEUAbgwAAAEACwAuAAQKfxsAAw0ACAkhILkrALoBAA0ABwlPILkrALoBAB0ABwlGDa1AAH4BAAAA.',
Ku='Kungfupander:BAEALgADCgMJAwABLgAECggJIwAXAAQkAA==.',
Le='Lewinskibidi:BAEBLgAFFH8NAAIEAAYJ/hZZHQBuAQZoDAAAAwBMAGkMAAADAEUAawwAAAIARQBqDAAAAQATAOoMAAADAEMAbgwAAAEACwAEAAYJ/hZZHQBuAQZoDAAAAwBMAGkMAAADAEUAawwAAAIARQBqDAAAAQATAOoMAAADAEMAbgwAAAEACwABLgAFFAkJMwARAPAgAA==.',
Li='Lilsoup:BAEBLgAECn8WAAIeAAkJXxTVIgCqAQloDAAABABNAGkMAAAEAEEAawwAAAQANgBqDAAAAgAqAGwMAAACACUAbQwAAAIAKwDqDAAAAgA9AG4MAAABAB4AbwwAAAEAOQAeAAkJXxTVIgCqAQloDAAABABNAGkMAAAEAEEAawwAAAQANgBqDAAAAgAqAGwMAAACACUAbQwAAAIAKwDqDAAAAgA9AG4MAAABAB4AbwwAAAEAOQABLgAFFAYJGgAdAG0OAA==.',
Ma='Madtheaug:BAECLgAFFH8NAAIEAAYJehc7GgCKAQZoDAAAAgA1AGkMAAADAFUAawwAAAMANgBqDAAAAQAtAG0MAAABABsA6gwAAAMAUAAEAAYJehc7GgCKAQZoDAAAAgA1AGkMAAADAFUAawwAAAMANgBqDAAAAQAtAG0MAAABABsA6gwAAAMAUAAuAAQKfxYAAwUACAmTIDMSAL4BAAUABwmzGDMSAL4BAAQABQmBIXIgAL0BAAEuAAUUCQlBAAcAKCYA.Madthehunt:BAEALgAFFAEJAQABLgAFFAkJQQAHACgmAA==.Madthelock:BAECLgAFFH9BAAQHAAkJKCZAAABxAwloDAAACABjAGkMAAAJAGMAawwAAAkAZABqDAAACgBhAGwMAAAIAGQAbQwAAAQAYgDqDAAACQBhAG4MAAAEAFoAbwwAAAQAXgAHAAkJuyVAAABxAwloDAAABgBiAGkMAAAEAGMAawwAAAIAYwBqDAAABABhAGwMAAAFAGMAbQwAAAMAXADqDAAABQBhAG4MAAAEAFoAbwwAAAQAXgAIAAcJiSY4AACWAgdoDAAAAQBjAGkMAAADAGMAawwAAAUAZABqDAAAAwBYAGwMAAACAGEAbQwAAAEAYgDqDAAAAwBhAB8ABgmCJoYAAB8CBmgMAAABAGEAaQwAAAIAYwBrDAAAAgBjAGoMAAADAF0AbAwAAAEAZADqDAAAAQBgAC4ABAp/KgAEBwAJCbImGwQATQMABwAJCU4mGwQATQMAHwAICWYmKAEA+wIACAAGCRwmXQoAGQIAAAA=.Magolli:BAEALgAECgQJBgABLgAFFAUJHAAVAEkdAA==.Magølli:BAECLgAFFH8cAAIVAAUJSR0hSABXAQVoDAAABwBWAGkMAAAHAFEAawwAAAUAPQBqDAAAAwBLAOoMAAAGAEYAFQAFCUkdIUgAVwEFaAwAAAcAVgBpDAAABwBRAGsMAAAFAD0AagwAAAMASwDqDAAABgBGAC4ABAp/LwACFQAJCTch7RoAtwIAFQAJCTch7RoAtwIAAAA=.',
Me='Megachud:BAEALgAFFAEJAQABLgAFFAYJDgANAOgOAA==.',
Mi='Minbä:BAEALgAECgYJEgABLgAFFAcJHgAHANgZAA==.Minigun:BAEALgAECgcJCgAAAQ==.Minipala:BAECLgAFFH8UAAIBAAYJ/hXjEgCSAQZoDAAABgBPAGkMAAAEADMAawwAAAMASwBqDAAAAgAaAGwMAAABABsA6gwAAAQATQABAAYJ/hXjEgCSAQZoDAAABgBPAGkMAAAEADMAawwAAAMASwBqDAAAAgAaAGwMAAABABsA6gwAAAQATQAuAAQKfx0AAwEACAk4IoIGAAMDAAEACAk4IoIGAAMDABcABQnnD0SzAB4BAAEuAAUUBwkeAAcA2BkA.Miniss:BAECLgAFFH8eAAQHAAcJ2BkzHgDQAQdoDAAABwBeAGkMAAAGAE8AawwAAAQAUgBqDAAABABXAGwMAAACABoAbQwAAAEADwDqDAAABgBhAAcABwnYGTMeANABB2gMAAAHAF4AaQwAAAMATwBrDAAAAwBSAGoMAAAEAFcAbAwAAAIAGgBtDAAAAQAPAOoMAAAFAGEACAACCYANTA0AowACaQwAAAIAHgBrDAAAAQAmAB8AAgl0D6cQAIgAAmkMAAABABMA6gwAAAEAPAAuAAQKf0EABB8ACQkjJu8AAA0DAAcACQnnJYMFAGMDAB8ACQk4Je8AAA0DAAgAAgkRIEVBALAAAAAA.',
Mo='Mobes:BAECLgAFFH8SAAITAAQJ7BHsEgDmAARoDAAABgAmAGkMAAAFACUAawwAAAMAIgDqDAAABABIABMABAnsEewSAOYABGgMAAAGACYAaQwAAAUAJQBrDAAAAwAiAOoMAAAEAEgALgAECn88AAITAAkJThl9DAAWAgATAAkJThl9DAAWAgAAAA==.Moosclemommy:BAECLgAFFH8cAAIGAAgJryLAAQCrAghoDAAABwBaAGkMAAAEAFgAawwAAAQAWQBqDAAAAgA1AGwMAAACAE0AbQwAAAEAWgDqDAAABwBfAG4MAAABAFkABgAICa8iwAEAqwIIaAwAAAcAWgBpDAAABABYAGsMAAAEAFkAagwAAAIANQBsDAAAAgBNAG0MAAABAFoA6gwAAAcAXwBuDAAAAQBZAC4ABAp/JwACBgAICU4lvgUALAMABgAICU4lvgUALAMAAAA=.Mowry:BAEALgAECgYJBwABLgAFFAUJHgARAKYZAA==.',
My='Mythicalhobo:BAEALgADCgUJCAAAAA==.Mythmaker:BAEALgAECgUJDQABLgAECggJIwAXAAQkAA==.',
Na='Nargrodamus:BAEBLgAECn80AAIgAAkJVBpPHQCWAgloDAAABwBGAGkMAAAIAFYAawwAAAcASQBqDAAACABbAGwMAAAGAFMAbQwAAAIAGADqDAAACABSAG4MAAAFAFAAbwwAAAEAJgAgAAkJVBpPHQCWAgloDAAABwBGAGkMAAAIAFYAawwAAAcASQBqDAAACABbAGwMAAAGAFMAbQwAAAIAGADqDAAACABSAG4MAAAFAFAAbwwAAAEAJgAAAA==.',
Ni='Nindragosa:BAEBLgAFFH8HAAIEAAQJfQcRPADSAARoDAAAAgAYAGkMAAACABIAawwAAAEABwDqDAAAAgAaAAQABAl9BxE8ANIABGgMAAACABgAaQwAAAIAEgBrDAAAAQAHAOoMAAACABoAAS4ABRQICSEAGAB/GQA=.Nindë:BAEBLgAFFH8JAAIhAAMJLQl+EACsAANoDAAAAwAeAGkMAAADABwA6gwAAAMACwAhAAMJLQl+EACsAANoDAAAAwAeAGkMAAADABwA6gwAAAMACwABLgAFFAgJIQAYAH8ZAA==.Niniane:BAECLgAFFH8hAAMYAAgJfxm4CgANAghoDAAABwBOAGkMAAAGAF8AawwAAAYATQBqDAAABAAWAGwMAAABAAoAbQwAAAEAOADqDAAABwBJAG4MAAABAEAAGAAHCQcduAoADQIHaAwAAAYATgBpDAAABgBfAGsMAAAEAE0AagwAAAIAFgBtDAAAAQA4AOoMAAAHAEkAbgwAAAEAQAAiAAQJCQQiGQDDAARoDAAAAQAKAGsMAAACAAkAagwAAAIAEQBsDAAAAQAKAC4ABAp/JwADGAAJCRwjaRAAtgIAGAAJCRwjaRAAtgIAIgAGCVIKtFYA7gAAAAA=.',
No='Nordsense:BAEALgAECgEJAQAAAA==.Novebear:BAEBLgAFFH8HAAITAAIJYRsCIgCQAAJoDAAABABCAOoMAAADAEkAEwACCWEbAiIAkAACaAwAAAQAQgDqDAAAAwBJAAEuAAUUAwkPAAwAwiUA.Novelus:BAECLgAFFH8PAAIMAAMJwiX3AwBHAQNoDAAABgBhAGkMAAAEAF4A6gwAAAUAYgAMAAMJwiX3AwBHAQNoDAAABgBhAGkMAAAEAF4A6gwAAAUAYgAuAAQKfzYAAgwACQkAJtMBADgDAAwACQkAJtMBADgDAAAA.',
Ol='Oldbronze:BAECLgAFFH8SAAIMAAYJEBi1DQBMAQZoDAAABQBLAGkMAAAEAEkAawwAAAIAKABqDAAAAQBIAGwMAAABACIA6gwAAAUAUwAMAAYJEBi1DQBMAQZoDAAABQBLAGkMAAAEAEkAawwAAAIAKABqDAAAAQBIAGwMAAABACIA6gwAAAUAUwAuAAQKf0IAAgwACAkSJiwDAAYDAAwACAkSJiwDAAYDAAAA.',
On='Onenjen:BAEBLgAECn8oAAIWAAgJewRyEgD9AAhoDAAACAAPAGkMAAAIAAgAawwAAAgAFwBqDAAABAANAGwMAAAEAAgAbQwAAAEABQDqDAAABQAMAG4MAAACAAgAFgAICXsEchIA/QAIaAwAAAgADwBpDAAACAAIAGsMAAAIABcAagwAAAQADQBsDAAABAAIAG0MAAABAAUA6gwAAAUADABuDAAAAgAIAAAA.',
['Oñ']='Oññayu:BAEALgAECgIJAgAAAA==.',
Pa='Parkercannon:BAECLgAFFH8zAAIRAAkJ8CBfAAA7AwloDAAACABhAGkMAAAHAGIAawwAAAgAVQBqDAAACQBJAGwMAAAFAF4AbQwAAAQAVwDqDAAABwBjAG4MAAABADcAbwwAAAIANwARAAkJ8CBfAAA7AwloDAAACABhAGkMAAAHAGIAawwAAAgAVQBqDAAACQBJAGwMAAAFAF4AbQwAAAQAVwDqDAAABwBjAG4MAAABADcAbwwAAAIANwAuAAQKfy0AAhEACQmUJO4AANADABEACQmUJO4AANADAAAA.Patrennessy:BAECLgAFFH8FAAIGAAMJeByNJQAQAQNoDAAAAwBeAGkMAAABACYA6gwAAAEAVQAGAAMJeByNJQAQAQNoDAAAAwBeAGkMAAABACYA6gwAAAEAVQAuAAQKfz4AAgYACQnBJDsCAD0DAAYACQnBJDsCAD0DAAAA.',
Ra='Ramsama:BAEALgAFFAIJAgAAAA==.Ramsdh:BAEBLgAFFH8JAAIOAAUJdBaePQArAQVoDAAAAgBKAGkMAAABAFYAawwAAAIAJwBqDAAAAgAiAOoMAAACAB4ADgAFCXQWnj0AKwEFaAwAAAIASgBpDAAAAQBWAGsMAAACACcAagwAAAIAIgDqDAAAAgAeAAEuAAUUBwkbABQA1x0A.Ramsx:BAECLgAFFH8bAAMUAAcJ1x11AwDEAQdoDAAABwBcAGkMAAAGAF8AawwAAAQAUgBqDAAAAgAuAGwMAAABACkA6gwAAAYAVgBuDAAAAQA7ABQABgmJIHUDAMQBBmgMAAAHAFwAaQwAAAQAXwBrDAAAAwBSAGoMAAACAC4A6gwAAAUAVgBuDAAAAQA7ABYABAlLEmgCABYBBGkMAAACADoAawwAAAEAOgBsDAAAAQApAOoMAAABABwALgAECn8XAAMUAAcJyiXcFABrAgAUAAcJyiXcFABrAgAWAAEJOCSAIQBUAAAAAA==.Rarelinelk:BAEALgAECgIJAgABLgAFFAcJHAAgAMAjAA==.',
Re='Recursively:BAECLgAFFH84AAQHAAkJiBzAAgDhAgloDAAACgBhAGkMAAAJAFkAawwAAAkAUQBqDAAABQBOAGwMAAADAFoAbQwAAAQAGwDqDAAACgBjAG4MAAADADcAbwwAAAMAKgAHAAkJSxvAAgDhAgloDAAACgBhAGkMAAADAEAAawwAAAcAUQBqDAAABABOAGwMAAADAFoAbQwAAAIAGwDqDAAACABjAG4MAAADADcAbwwAAAMAKgAIAAQJlRHYAwBaAQRpDAAAAQAsAGsMAAACAEIAbQwAAAIAGwDqDAAAAgApAB8AAgnpIq8UAGkAAmkMAAAFAFkAagwAAAEAJQAuAAQKfyoABAcACQltI/QMABIDAAcACQlNI/QMABIDAAgABgkKIoQIADoCAB8AAQkAANgiAGYAAAAA.Redxr:BAEALgAECgYJDQABLgAFFAgJEwASAEEZAA==.Releira:BAEBLgAFFH8FAAIgAAIJXQsp6gB8AAJoDAAAAQAOAOoMAAAEACsAIAACCV0LKeoAfAACaAwAAAEADgDqDAAABAArAAEuAAUUBQkcABUASR0A.Resika:BAEALgAFFAEJAQABLgAFFAIJAgADAAAAAA==.',
Ru='Ruwondk:BAEALgAECgIJAgABLgAFFAgJNgAGALYhAA==.',
Sh='Sharrq:BAECLgAFFH8cAAIjAAYJiB20AACrAQZoDAAACABUAGkMAAAHADcAawwAAAUAWgBqDAAAAgBNAGwMAAABAD0A6gwAAAUAVgAjAAYJiB20AACrAQZoDAAACABUAGkMAAAHADcAawwAAAUAWgBqDAAAAgBNAGwMAAABAD0A6gwAAAUAVgAuAAQKfyMAAyMACQmPI6gAABIDACMACQmPI6gAABIDACQAAQkrCVkeADQAAAAA.Shotgunarms:BAEALgAECgQJBAABLgAECgkJJwAcAEMeAA==.',
Si='Silversoph:BAEALgADCgcJCgAAAA==.Sivvychuckle:BAEALgAECgIJAwABLgAECgcJCwADAAAAAA==.Sivvygrows:BAEALgAECgcJBwABLgAECgcJCwADAAAAAA==.Sivvyrawr:BAEALgAECgcJCwAAAA==.',
Sl='Slammybreath:BAECLgAFFH8RAAMEAAUJDBgKHQBwAQVoDAAABQBMAGkMAAAFAEwAawwAAAQAMABsDAAAAQAsAOoMAAACADwABAAFCQwYCh0AcAEFaAwAAAQATABpDAAABQBMAGsMAAAEADAAbAwAAAEALADqDAAAAgA8AAUAAQk2AR4MAEMAAWgMAAABAAMALgAECn8kAAMEAAgJuBfXQQAgAQAEAAYJfxfXQQAgAQAFAAgJ2hP7LAC0AAABLgAFFAgJHAAGAK8iAA==.',
Sp='Spicyhotwing:BAECLgAFFH8UAAMCAAgJEA2KAwDOAQhoDAAAAwAKAGkMAAADAAsAawwAAAMAGwBqDAAABAAhAGwMAAABAAUAbQwAAAEAWQDqDAAABAAqAG4MAAABAC0AAgAGCaEIigMAzgEGaAwAAAEACgBpDAAAAQALAGsMAAABABsAagwAAAQAIQBsDAAAAQAFAOoMAAAEACoABAAFCUgUdRkAkQEFaAwAAAIATwBpDAAAAgBgAGsMAAACAEYAbQwAAAEABABuDAAAAQAJAC4ABAp/GAAEAgAICesSQBQAAgIAAgAICesSQBQAAgIABAAECbQkWjsAOwEABQABCX0efjgAVQAAAS4ABRQICRwABgCvIgA=.',
Ta='Tauntinitis:BAECLgAFFH8IAAIGAAQJ1gY8MQDgAARoDAAAAgATAGkMAAACAA8AawwAAAEABADqDAAAAwAdAAYABAnWBjwxAOAABGgMAAACABMAaQwAAAIADwBrDAAAAQAEAOoMAAADAB0ALgAECn8UAAIGAAkJ5AaCMQA6AQAGAAkJ5AaCMQA6AQABLgAFFAUJFgAYACMgAA==.',
Te='Tendeyaloran:BAEBLgAECn8cAAIBAAYJuxJtPABUAQZoDAAABgA/AGkMAAAGADEAawwAAAUAHgBqDAAAAwAuAGwMAAADAEIA6gwAAAUAHwABAAYJuxJtPABUAQZoDAAABgA/AGkMAAAGADEAawwAAAUAHgBqDAAAAwAuAGwMAAADAEIA6gwAAAUAHwAAAA==.',
Th='Thanala:BAECLgAFFH8cAAIBAAcJKCBxCgAEAgdoDAAABgBSAGkMAAAGAGEAawwAAAQAWABqDAAAAwBLAGwMAAABAGEAbQwAAAEAKwDqDAAABwBbAAEABwkoIHEKAAQCB2gMAAAGAFIAaQwAAAYAYQBrDAAABABYAGoMAAADAEsAbAwAAAEAYQBtDAAAAQArAOoMAAAHAFsALgAECn8jAAIBAAgJKh98FABuAgABAAgJKh98FABuAgAAAA==.',
Tr='Trintu:BAEALgAECgkJAwABLgAFFAYJGwAaAAcQAA==.',
Wo='Wormdropper:BAEBLgAECn8XAAMNAAcJqBBlTwD2AAdoDAAABAAwAGkMAAAEADEAawwAAAQAOgBqDAAABAAcAGwMAAADADQAbQwAAAEAEgDqDAAAAwAdAA0ABwmoEGVPAPYAB2gMAAAEADAAaQwAAAMAMQBrDAAAAwA6AGoMAAAEABwAbAwAAAMANABtDAAAAQASAOoMAAADAB0AHQACCSoGpJAAVwACaQwAAAEADABrDAAAAQATAAEuAAUUAwkGAAQAbgkA.Wormthyr:BAEBLgAFFH8GAAMEAAMJbgkJSQCiAANoDAAAAwAgAGkMAAACACAA6gwAAAEABwAEAAMJbgkJSQCiAANoDAAAAgAgAGkMAAACACAA6gwAAAEABwAFAAEJoATRDwA7AAFoDAAAAQALAAAA.',
Yo='Yoktuah:BAEBLgAFFH8GAAMBAAQJ6gPGDQD9AARoDAAAAwAAAGkMAAABABwAawwAAAEACgDqDAAAAQAAAAEABAnqA8YNAP0ABGgMAAABAAAAaQwAAAEAHABrDAAAAQAKAOoMAAABAAAAFwABCRgRnTEAUgABaAwAAAIAKwABLgAFFAYJDgANAOgOAA==.',
Yu='Yungdh:BAEBLgAECn8cAAIOAAcJ+xx7OQDeAQdoDAAABAA8AGkMAAAEAEwAawwAAAUAUgBqDAAABABOAGwMAAAEAEkAbQwAAAEAPADqDAAABgBbAA4ABwn7HHs5AN4BB2gMAAAEADwAaQwAAAQATABrDAAABQBSAGoMAAAEAE4AbAwAAAQASQBtDAAAAQA8AOoMAAAGAFsAAS4ABRQICSEAJQAPJQA=.Yungdrood:BAECLgAFFH8hAAIlAAgJDyWxAgCnAghoDAAABgBjAGkMAAAHAGMAawwAAAYAYwBqDAAABQBhAGwMAAACAF4AbQwAAAEAXADqDAAABQBiAG4MAAABAE8AJQAICQ8lsQIApwIIaAwAAAYAYwBpDAAABwBjAGsMAAAGAGMAagwAAAUAYQBsDAAAAgBeAG0MAAABAFwA6gwAAAUAYgBuDAAAAQBPAC4ABAp/NgACJQAJCdYmQQIAnwMAJQAJCdYmQQIAnwMAAAA=.Yungmonk:BAEALgAECgQJBAABLgAFFAgJIQAlAA8lAA==.Yungwizard:BAEBLgAECn8WAAIVAAYJ2iXfOQCOAgZoDAAABABfAGkMAAAEAGIAawwAAAQAXwBqDAAAAwBhAGwMAAAEAGEA6gwAAAMAYQAVAAYJ2iXfOQCOAgZoDAAABABfAGkMAAAEAGIAawwAAAQAXwBqDAAAAwBhAGwMAAAEAGEA6gwAAAMAYQABLgAFFAgJIQAlAA8lAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
