local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Rogue-Outlaw','Warrior-Fury','Monk-Mistweaver','Monk-Windwalker','Druid-Balance','Evoker-Devastation','Unknown-Unknown','DemonHunter-Havoc','Shaman-Enhancement','Hunter-BeastMastery','Evoker-Preservation','Paladin-Protection','Paladin-Retribution','Shaman-Elemental','Shaman-Restoration','DeathKnight-Frost','Monk-Brewmaster','Druid-Guardian','Druid-Restoration','DeathKnight-Blood','Paladin-Holy','Druid-Feral','Mage-Arcane','Mage-Frost','DeathKnight-Unholy','Priest-Holy','Priest-Shadow','Warlock-Demonology','DemonHunter-Devourer','Rogue-Subtlety','Warlock-Affliction','Warlock-Destruction','Warrior-Protection','Evoker-Augmentation','Warrior-Arms','Hunter-Marksmanship','Hunter-Survival','Priest-Discipline','DemonHunter-Vengeance',}
local provider = {region='US',realm='Misha',name='US',type='daily',zone=46,date='2026-06-08',data={Ac='Acidburn:BAABLgAECn8WAAIBAAcJ0BroAwDvAQdoDAAABABPAGkMAAAEACgAawwAAAQAWwBqDAAAAwAzAGwMAAADAE8A6gwAAAMAUABuDAAAAQAoAAEABwnQGugDAO8BB2gMAAAEAE8AaQwAAAQAKABrDAAABABbAGoMAAADADMAbAwAAAMATwDqDAAAAwBQAG4MAAABACgAAAA=.',
Ae='Aea:BAAALgAECgIJBgAAAA==.Aevie:BAAALgAECgYJEgAAAA==.',
Af='Afterlìfe:BAAALgAECggJEgAAAA==.',
Ai='Ailis:BAAALgADCgQJBAAAAA==.',
Al='Alendria:BAAALgADCgYJBgAAAA==.Alizë:BAAALgADCgQJAwAAAA==.Alluna:BAAALgADCgEJAQAAAA==.Alorillan:BAAALgAECggJEgAAAA==.Altabrew:BAAALgAECgQJBAAAAA==.Altair:BAAALgAECgUJDwABLgAECgkJIQACABMhAA==.',
An='Andelynn:BAAALgAECgIJAgAAAA==.',
Ap='Applejuic:BAACLgAFFH8FAAIDAAMJtgp9PgCRAANoDAAAAgAVAGkMAAABABMA6gwAAAIAKAADAAMJtgp9PgCRAANoDAAAAgAVAGkMAAABABMA6gwAAAIAKAAuAAQKfxQAAwMACQlKFsUZADwCAAMACQlKFsUZADwCAAQAAQk1EFSaAC0AAAAA.Appless:BAAALgAECgQJBwAAAA==.',
Ar='Araylia:BAABLgAECn8fAAIFAAkJjAypNQA1AQloDAAABQA8AGkMAAAFABsAawwAAAUAGABqDAAABAAgAGwMAAAEACcAbQwAAAEABQDqDAAABAA8AG4MAAACAB4AbwwAAAEACQAFAAkJjAypNQA1AQloDAAABQA8AGkMAAAFABsAawwAAAUAGABqDAAABAAgAGwMAAAEACcAbQwAAAEABQDqDAAABAA8AG4MAAACAB4AbwwAAAEACQAAAA==.Aridella:BAABLgAECn8VAAIGAAYJRA6fEwDIAAZoDAAABAAwAGkMAAAEAC0AawwAAAQAHgBqDAAABQAlAGwMAAADADIAbgwAAAEABwAGAAYJRA6fEwDIAAZoDAAABAAwAGkMAAAEAC0AawwAAAQAHgBqDAAABQAlAGwMAAADADIAbgwAAAEABwAAAA==.Ariellaa:BAAALgAECgYJBgAAAA==.Artamayis:BAAALgAECgQJBAAAAA==.',
As='Ashaly:BAAALgADCgUJBQAAAA==.Ashlei:BAAALgAECgQJCAAAAA==.',
At='Atomseve:BAAALgADCgQJBAABLgAECggJEwAHAAAAAA==.',
Au='Aurafarmer:BAAALgADCgEJAQAAAA==.Autopsia:BAAALgADCgYJBgABLgAECgkJOQAIANQYAA==.Autumn:BAAALgADCgUJBwAAAA==.',
Av='Avalorne:BAAALgAECgMJAwABLgAECgkJIQACABMhAA==.Avena:BAAALgADCgEJAgAAAA==.',
Az='Azaizel:BAAALgAECgYJCwAAAA==.Azusie:BAABLgAECn81AAIJAAkJehdZCQAfAgloDAAACABEAGkMAAAIAD4AawwAAAgATgBqDAAABgBBAGwMAAAGADQAbQwAAAQATgDqDAAABgA5AG4MAAAGADAAbwwAAAEAIQAJAAkJehdZCQAfAgloDAAACABEAGkMAAAIAD4AawwAAAgATgBqDAAABgBBAGwMAAAGADQAbQwAAAQATgDqDAAABgA5AG4MAAAGADAAbwwAAAEAIQAAAA==.',
Ba='Baddate:BAABLgAECn8fAAIKAAcJ3A9PaQBnAQdoDAAABgAyAGkMAAAFACkAawwAAAQALABqDAAABAAgAGwMAAAFADAA6gwAAAQAIQBuDAAAAwAYAAoABwncD09pAGcBB2gMAAAGADIAaQwAAAUAKQBrDAAABAAsAGoMAAAEACAAbAwAAAUAMADqDAAABAAhAG4MAAADABgAAAA=.Baddragøn:BAABLgAECn84AAMLAAkJBRYaDQD6AQloDAAABwBLAGkMAAAHAEYAawwAAAcAOQBqDAAABgAtAGwMAAAIAEMAbQwAAAUAIADqDAAABwAwAG4MAAAGADIAbwwAAAMAPAALAAgJ0xUaDQD6AQhoDAAABgBLAGkMAAAGAEYAawwAAAYAOQBqDAAABQAtAGwMAAAHAEMAbQwAAAUAIADqDAAABgAwAG4MAAADADIABgAICcYPcQkAiAEIaAwAAAEAJQBpDAAAAQAyAGsMAAABACoAagwAAAEANgBsDAAAAQAbAOoMAAABADYAbgwAAAMAFwBvDAAAAwAuAAAA.Balthaas:BAABLgAECn82AAMMAAkJyhhECgAeAgloDAAACQA6AGkMAAAIAFoAawwAAAcAUQBqDAAABgBUAGwMAAAGACcAbQwAAAMALQDqDAAACABPAG4MAAAEAEcAbwwAAAMAKQAMAAkJyhhECgAeAgloDAAACQA6AGkMAAAIAFoAawwAAAcAUQBqDAAABgBUAGwMAAAGACcAbQwAAAMALQDqDAAABwBPAG4MAAAEAEcAbwwAAAMAKQANAAEJewdjUQErAAHqDAAAAQATAAAA.Bangen:BAAALgAECgcJDwAAAA==.Bastria:BAAALgAECgYJDAAAAA==.Baulters:BAAALgAECgYJCAAAAA==.',
Be='Beenn:BAAALgAECgYJBgAAAA==.',
Bh='Bharko:BAAALgADCgcJCgABLgAFFAYJDgAKADodAA==.',
Bi='Billyblastin:BAAALgADCgMJAwABLgAECgkJJQAOAFgZAA==.Billywitchdr:BAABLgAECn8lAAMOAAkJWBkoGAAXAgloDAAABQA0AGkMAAAFAEkAawwAAAQAKwBqDAAABAAvAGwMAAAFADsAbQwAAAMASADqDAAABgBKAG4MAAADAEUAbwwAAAIASgAOAAkJWBkoGAAXAgloDAAABQA0AGkMAAAFAEkAawwAAAQAKwBqDAAABAAvAGwMAAAFADsAbQwAAAMASADqDAAABgBKAG4MAAADAEUAbwwAAAEASgAPAAEJFgaK0gArAAFvDAAAAQAPAAAA.Biocryo:BAAALgADCgYJBgABLgAECggJEAAHAAAAAA==.',
Bl='Blazingpanda:BAAALgAECgMJBAAAAA==.Blizeatsass:BAAALgADCgMJAwAAAA==.Bluedomino:BAAALgAECgMJCAAAAA==.Bluetoykawi:BAABLgAECn87AAIQAAgJXBfsCQDWAQhoDAAACABBAGkMAAAIAEAAawwAAAgAOQBqDAAABwAtAGwMAAAIAEQAbQwAAAYAKADqDAAACAA9AG4MAAAGADwAEAAICVwX7AkA1gEIaAwAAAgAQQBpDAAACABAAGsMAAAIADkAagwAAAcALQBsDAAACABEAG0MAAAGACgA6gwAAAgAPQBuDAAABgA8AAAA.',
Bo='Boats:BAAALgADCgIJAgAAAA==.Boltspark:BAAALgADCgMJAwAAAA==.Borgo:BAAALgAECgYJBgAAAA==.Bowlenciaga:BAABLgAECn8YAAIKAAgJnAlpZQBwAQhoDAAABAATAGkMAAAEABoAawwAAAQAIgBqDAAAAwATAGwMAAADABIAbQwAAAEAGwDqDAAABAAPAG4MAAABAB8ACgAICZwJaWUAcAEIaAwAAAQAEwBpDAAABAAaAGsMAAAEACIAagwAAAMAEwBsDAAAAwASAG0MAAABABsA6gwAAAQADwBuDAAAAQAfAAAA.Bozilla:BAAALgADCgMJAwAAAA==.',
Br='Braelia:BAAALgADCgcJCAAAAA==.Brainfart:BAAALgADCgUJBQABLgAECggJGwAKABcWAA==.Breloom:BAAALgADCgEJAQAAAA==.Bruithis:BAAALgADCgIJAgAAAA==.',
Bu='Burdan:BAAALgADCgQJBAAAAA==.Buttermebuns:BAAALgADCgcJCAAAAA==.',
Ca='Cariandria:BAAALgAECgUJBgAAAA==.',
Cc='Cc:BAAALgAECgEJAgAAAA==.',
Ch='Chahaein:BAAALgAECgYJDwAAAA==.Charbaby:BAAALgAFFAMJAwABLgAFFAUJFwARABYfAA==.Charhartt:BAACLgAFFH8FAAISAAMJJw+fHQCZAANoDAAAAgAmAGkMAAACACkA6gwAAAEAJAASAAMJJw+fHQCZAANoDAAAAgAmAGkMAAACACkA6gwAAAEAJAAuAAQKfxUAAxIABgljF7YeAEkBABIABgljF7YeAEkBABMAAQlXB3njACMAAAEuAAUUBQkXABEAFh8A.Charita:BAAALgAECgMJBAABLgAFFAUJFwARABYfAA==.Charizard:BAAALgAECgEJAQABLgAFFAUJFwARABYfAA==.Charming:BAACLgAFFH8XAAIRAAUJFh/3GABPAQVoDAAABwBTAGkMAAAGAF0AawwAAAQAQABqDAAAAwA/AOoMAAADAEwAEQAFCRYf9xgATwEFaAwAAAcAUwBpDAAABgBdAGsMAAAEAEAAagwAAAMAPwDqDAAAAwBMAC4ABAp/IAACEQAICdcZxRwAHQIAEQAICdcZxRwAHQIAAAA=.Charmonic:BAAALgAFFAIJAgABLgAFFAUJFwARABYfAA==.Chelseah:BAAALgAECgYJEAABLgAECgcJDwAHAAAAAA==.',
Ci='Cinderlight:BAAALgAECgEJAQAAAA==.',
Cl='Clanker:BAAALgAECgkJEgAAAA==.Clémentine:BAAALgAECgEJAQAAAA==.',
Co='Coldknight:BAABLgAECn8eAAMQAAcJjQIvJwCHAAdoDAAABQAHAGkMAAAGAAgAawwAAAYABwBqDAAABAAJAGwMAAADAAYA6gwAAAUABABuDAAAAQADABAABwlYAi8nAIcAB2gMAAADAAQAaQwAAAMACABrDAAAAwAHAGoMAAADAAkAbAwAAAMABgDqDAAAAgAEAG4MAAABAAMAFAAFCegBT0wAVgAFaAwAAAIABwBpDAAAAwAEAGsMAAADAAMAagwAAAEAAwDqDAAAAwAEAAAA.Conien:BAAALgADCgQJBAAAAA==.Conifer:BAABLgAECn8WAAITAAcJEhp1KQABAgdoDAAABgBNAGkMAAAFADkAawwAAAMAQwBqDAAAAgBJAGwMAAACADQA6gwAAAMATQBuDAAAAQA8ABMABwkSGnUpAAECB2gMAAAGAE0AaQwAAAUAOQBrDAAAAwBDAGoMAAACAEkAbAwAAAIANADqDAAAAwBNAG4MAAABADwAAAA=.Coniption:BAAALgADCgEJAQAAAA==.Contrlurself:BAAALgAECgYJBgABLgAECgkJJAAFAF4VAA==.Copium:BAAALgAECgQJBwAAAA==.Cornpop:BAAALgAECgYJDQAAAA==.Cowret:BAABLgAECn9BAAMVAAkJ0yFyAgB+AwloDAAACQBiAGkMAAAJAGEAawwAAAkAYwBqDAAACABjAGwMAAAIAGEAbQwAAAUAYADqDAAACQBfAG4MAAAFADsAbwwAAAMAJAAVAAkJ0yFyAgB+AwloDAAACQBiAGkMAAAJAGEAawwAAAkAYwBqDAAABwBjAGwMAAAIAGEAbQwAAAUAYADqDAAACQBfAG4MAAAFADsAbwwAAAMAJAANAAEJAAC/xQEAAAFqDAAAAQAaAAAA.',
Cr='Crystalwolf:BAABLgAECn8VAAIWAAYJiwW0LACkAAZoDAAABAALAGkMAAAEABEAawwAAAQADwBqDAAAAwATAGwMAAACAAkA6gwAAAQAEAAWAAYJiwW0LACkAAZoDAAABAALAGkMAAAEABEAawwAAAQADwBqDAAAAwATAGwMAAACAAkA6gwAAAQAEAAAAA==.',
Cu='Curze:BAAALgAECgMJAwAAAA==.',
Cy='Cyonna:BAAALgADCgQJBAAAAA==.',
Da='Darc:BAABLgAECn8XAAICAAQJXCXUPgCpAQRoDAAABABfAGkMAAAGAGAAawwAAAIAWgDqDAAACwBjAAIABAlcJdQ+AKkBBGgMAAAEAF8AaQwAAAYAYABrDAAAAgBaAOoMAAALAGMAAAA=.Darkfoxgrime:BAAALgAECgkJCQABLgAECgkJJAAEAHkQAA==.Darkjager:BAABLgAECn8rAAIKAAkJHR6CKwAnAgloDAAABgBJAGkMAAAFAE0AawwAAAUARABqDAAABQBWAGwMAAAGAE0AbQwAAAQAWQDqDAAABwBPAG4MAAADAFIAbwwAAAIARQAKAAkJHR6CKwAnAgloDAAABgBJAGkMAAAFAE0AawwAAAUARABqDAAABQBWAGwMAAAGAE0AbQwAAAQAWQDqDAAABwBPAG4MAAADAFIAbwwAAAIARQAAAA==.Darkways:BAAALgAECgcJAQAAAA==.Darlah:BAABLgAECn8hAAIXAAgJqxJNBACsAQhoDAAABgA1AGkMAAAGAEAAawwAAAYAOwBqDAAAAwA2AGwMAAAEAD0AbQwAAAQAIwDqDAAAAwAlAG4MAAABABYAFwAICasSTQQArAEIaAwAAAYANQBpDAAABgBAAGsMAAAGADsAagwAAAMANgBsDAAABAA9AG0MAAAEACMA6gwAAAMAJQBuDAAAAQAWAAAA.Darnalin:BAAALgAECgEJAgABLgAECgkJOQAIANQYAA==.Dayva:BAAALgAECgQJBgAAAA==.Dayyva:BAAALgAECgQJDgAAAA==.',
De='Deadcobra:BAABLgAECn8pAAIYAAkJrASPoQA2AQloDAAABQAKAGkMAAAFAA8AawwAAAYAGwBqDAAABAAvAGwMAAAFAAkAbQwAAAMABwDqDAAABQAKAG4MAAAGAAcAbwwAAAIACAAYAAkJrASPoQA2AQloDAAABQAKAGkMAAAFAA8AawwAAAYAGwBqDAAABAAvAGwMAAAFAAkAbQwAAAMABwDqDAAABQAKAG4MAAAGAAcAbwwAAAIACAAAAA==.Deathbean:BAAALgADCgQJBAABLgAECgUJDwAHAAAAAA==.Debtknight:BAABLgAECn84AAIZAAkJ6h90FQDBAgloDAAACQBYAGkMAAAIAFwAawwAAAgASgBqDAAABwBVAGwMAAAGAEIAbQwAAAUAUwDqDAAACABZAG4MAAAEAEoAbwwAAAEAVAAZAAkJ6h90FQDBAgloDAAACQBYAGkMAAAIAFwAawwAAAgASgBqDAAABwBVAGwMAAAGAEIAbQwAAAUAUwDqDAAACABZAG4MAAAEAEoAbwwAAAEAVAAAAA==.Deelo:BAAALgAECgEJAQAAAA==.Dehumidifier:BAABLgAECn8oAAMaAAkJlx6/EABVAgloDAAABgBIAGkMAAAGAEIAawwAAAYAUQBqDAAABQBaAGwMAAAFAF8AbQwAAAIAXwDqDAAABQBSAG4MAAADADUAbwwAAAIARAAaAAkJlx6/EABVAgloDAAABQBIAGkMAAAFAEIAawwAAAUAUQBqDAAABABaAGwMAAAEAF8AbQwAAAEAXwDqDAAABABSAG4MAAACADUAbwwAAAEARAAbAAkJQw0OJQCcAQloDAAAAQA1AGkMAAABABMAawwAAAEAJwBqDAAAAQAlAGwMAAABADMAbQwAAAEAHwDqDAAAAQAeAG4MAAABABQAbwwAAAEAGQAAAA==.Deltria:BAAALgAECggJEgAAAA==.Demonrot:BAABLgAECn8XAAIcAAgJZAsAcwBQAQhoDAAAAwAeAGkMAAADAB4AawwAAAMAHgBqDAAAAgAiAGwMAAACABwAbQwAAAEAHQDqDAAABgAlAG4MAAADABEAHAAICWQLAHMAUAEIaAwAAAMAHgBpDAAAAwAeAGsMAAADAB4AagwAAAIAIgBsDAAAAgAcAG0MAAABAB0A6gwAAAYAJQBuDAAAAwARAAAA.Dervin:BAAALgADCgQJBAABLgAECggJCAAHAAAAAA==.Deviltank:BAAALgADCgYJDAAAAA==.Devohsup:BAABLgAECn8dAAIdAAgJlB+UHgBVAghoDAAABABTAGkMAAAEAF4AawwAAAQAVwBqDAAABAA/AGwMAAAEAFIAbQwAAAMARADqDAAABAA6AG4MAAACAFsAHQAICZQflB4AVQIIaAwAAAQAUwBpDAAABABeAGsMAAAEAFcAagwAAAQAPwBsDAAABABSAG0MAAADAEQA6gwAAAQAOgBuDAAAAgBbAAAA.Devussi:BAABLgAECn8mAAIdAAkJyBQjRgCrAQloDAAABgBAAGkMAAAGAEUAawwAAAYARABqDAAABQA4AGwMAAAEADUAbQwAAAEAJgDqDAAABAAuAG4MAAAEADUAbwwAAAIAHgAdAAkJyBQjRgCrAQloDAAABgBAAGkMAAAGAEUAawwAAAYARABqDAAABQA4AGwMAAAEADUAbQwAAAEAJgDqDAAABAAuAG4MAAAEADUAbwwAAAIAHgABLgAECgUJBQAHAAAAAA==.',
Di='Dienva:BAAALgAECgUJBQAAAA==.Digmyearth:BAAALgAECgUJCAAAAA==.Dilea:BAAALgAECgUJBQAAAA==.',
Dk='Dksakp:BAAALgADCgkJGAAAAA==.',
Do='Dominateelf:BAAALgADCgQJBAABLgAECgMJBAAHAAAAAA==.Dotero:BAAALgAECgUJDgAAAA==.',
Dr='Dracreina:BAABLgAECn8oAAMGAAgJmxOvBwC0AQhoDAAACABEAGkMAAAIAEIAawwAAAgANgBqDAAAAwAvAGwMAAACACQAbQwAAAEAJADqDAAACQA7AG4MAAABAB0ABgAICZsTrwcAtAEIaAwAAAgARABpDAAACABCAGsMAAAIADYAagwAAAIALwBsDAAAAgAkAG0MAAABACQA6gwAAAkAOwBuDAAAAQAdAAsAAQlBBoQ+ACUAAWoMAAABABAAAAA=.Dreouss:BAAALgAECgQJBgAAAA==.Driver:BAAALgAFFAIJAwABLgAFFAUJDwAcALYLAA==.',
Du='Dumeslayer:BAAALgADCgcJCQAAAA==.Durzoe:BAABLgAECn8WAAIeAAcJlwoFOQBNAQdoDAAAAwAYAGkMAAADAB4AawwAAAMAFABqDAAAAwAfAGwMAAABAAgA6gwAAAgAQABvDAAAAQAOAB4ABwmXCgU5AE0BB2gMAAADABgAaQwAAAMAHgBrDAAAAwAUAGoMAAADAB8AbAwAAAEACADqDAAACABAAG8MAAABAA4AAAA=.',
Dv='Dvsmage:BAAALgAECgUJDwAAAA==.',
Eg='Egaik:BAAALgAECgYJBgAAAA==.',
El='Elarred:BAAALgADCgkJFAAAAA==.Elfkr:BAAALgAECgkJAwAAAA==.Elissauna:BAABLgAECn8VAAIYAAkJ/RLBQQASAgloDAAAAwAfAGkMAAACADQAawwAAAIAMABqDAAAAgBWAGwMAAACAD8AbQwAAAEAHwDqDAAABgBLAG4MAAACAB0AbwwAAAEAOAAYAAkJ/RLBQQASAgloDAAAAwAfAGkMAAACADQAawwAAAIAMABqDAAAAgBWAGwMAAACAD8AbQwAAAEAHwDqDAAABgBLAG4MAAACAB0AbwwAAAEAOAAAAA==.Elylea:BAABLgAECn8fAAICAAgJvRqLHQD+AQhoDAAAAwA3AGkMAAAFAFcAawwAAAUAVwBqDAAABAA4AGwMAAAFAFYAbQwAAAEAJADqDAAABgBGAG4MAAACADYAAgAICb0aix0A/gEIaAwAAAMANwBpDAAABQBXAGsMAAAFAFcAagwAAAQAOABsDAAABQBWAG0MAAABACQA6gwAAAYARgBuDAAAAgA2AAAA.',
En='Enorme:BAAALgADCgQJBAAAAA==.',
Eu='Eunice:BAAALgADCgIJAgAAAA==.',
Ez='Ezili:BAAALgAECgEJAQAAAA==.',
Fa='Failure:BAAALgAECgIJAwAAAA==.Falabala:BAAALgAECgYJCgAAAA==.Fanghür:BAAALgADCgcJDgAAAA==.',
Fe='Feeloow:BAAALgADCgcJCwAAAA==.Felhound:BAAALgAECggJDwAAAA==.Felussi:BAAALgAECgUJBQAAAA==.Feorahir:BAAALgAECgQJBQAAAA==.Fermitorok:BAAALgADCgEJAQAAAA==.',
Ff='Ff:BAAALgAECgQJBAAAAA==.',
Fi='Finhead:BAABLgAECn8zAAIKAAkJXQ4ySQC9AQloDAAACAAZAGkMAAAHADgAawwAAAcALgBqDAAABgAsAGwMAAAGABoAbQwAAAUALgDqDAAABwApAG4MAAAEABkAbwwAAAEAGAAKAAkJXQ4ySQC9AQloDAAACAAZAGkMAAAHADgAawwAAAcALgBqDAAABgAsAGwMAAAGABoAbQwAAAUALgDqDAAABwApAG4MAAAEABkAbwwAAAEAGAAAAA==.Fionna:BAAALgAECgcJDAAAAA==.Firereina:BAAALgADCggJGQABLgAECggJKAAGAJsTAA==.Fishbone:BAAALgAECgMJAwAAAA==.',
Fl='Fleurminator:BAABLgAECn8gAAICAAkJBxHNLQCWAQloDAAABgA+AGkMAAAFAD4AawwAAAUALABqDAAABAA2AGwMAAAEADYAbQwAAAEAGgDqDAAABAAvAG4MAAACACEAbwwAAAEAEAACAAkJBxHNLQCWAQloDAAABgA+AGkMAAAFAD4AawwAAAUALABqDAAABAA2AGwMAAAEADYAbQwAAAEAGgDqDAAABAAvAG4MAAACACEAbwwAAAEAEAAAAA==.Fluffybaby:BAAALgADCgMJAwAAAA==.',
Fo='Fondadix:BAABLgAECn8lAAIUAAkJpyFECQB4AgloDAAABQBBAGkMAAAFAF0AawwAAAQAWgBqDAAABABKAGwMAAAFAFMAbQwAAAMAUQDqDAAABgBZAG4MAAADAGAAbwwAAAIAVwAUAAkJpyFECQB4AgloDAAABQBBAGkMAAAFAF0AawwAAAQAWgBqDAAABABKAGwMAAAFAFMAbQwAAAMAUQDqDAAABgBZAG4MAAADAGAAbwwAAAIAVwAAAA==.',
Fr='Frieia:BAABLgAECn8cAAITAAgJ3wcHYgAHAQhoDAAABgASAGkMAAAGACAAawwAAAYAIABqDAAAAgAdAGwMAAABAA4AbQwAAAEABgDqDAAABQARAG4MAAABAAgAEwAICd8HB2IABwEIaAwAAAYAEgBpDAAABgAgAGsMAAAGACAAagwAAAIAHQBsDAAAAQAOAG0MAAABAAYA6gwAAAUAEQBuDAAAAQAIAAAA.Frostiilocks:BAAALgAECggJCQAAAA==.Frostitutte:BAAALgAECgYJEQAAAA==.',
Fu='Fuze:BAAALgAECgYJCwAAAA==.',
Ga='Galakrosh:BAACLgAFFH8HAAMfAAMJASHrDACnAANoDAAAAwBgAGkMAAACAEkA6gwAAAIAUwAcAAMJASEHawDgAANoDAAAAgBgAGkMAAABAEkA6gwAAAIAUwAfAAIJ9B/rDACnAAJoDAAAAQBaAGkMAAABAEgALgAECn8qAAQfAAgJGCQLBQAzAgAcAAgJcB0+FwDJAgAfAAgJaSILBQAzAgAgAAEJAACBYwBIAAAAAA==.Galarína:BAABLgAECn83AAMDAAkJFCLXCwDQAgloDAAACQBgAGkMAAAJAFwAawwAAAgAVwBqDAAABgBWAGwMAAAGAFwAbQwAAAMATgDqDAAABwBcAG4MAAAEAD4AbwwAAAMAXwADAAgJqSHXCwDQAghoDAAABQBgAGkMAAAFAFwAawwAAAUAVwBqDAAABABWAGwMAAADAFwAbQwAAAEATgDqDAAABABcAG4MAAABAD4ABAAJCfEdcAsAhQIJaAwAAAQAUABpDAAABABZAGsMAAADAEgAagwAAAIAUQBsDAAAAwBRAG0MAAACAFIA6gwAAAMASwBuDAAAAwBIAG8MAAADADsAAAA=.Gandora:BAABLgAECn8gAAMZAAkJwxYdSgDfAQloDAAABQBUAGkMAAAFAFMAawwAAAUASABqDAAABAA0AGwMAAAEACcAbQwAAAEADgDqDAAABABHAG4MAAADADcAbwwAAAEAKwAZAAkJwxYdSgDfAQloDAAABQBUAGkMAAAFAFMAawwAAAUASABqDAAABAA0AGwMAAAEACcAbQwAAAEADgDqDAAABABHAG4MAAACADcAbwwAAAEAKwAQAAEJ/wMWPQAkAAFuDAAAAQAKAAAA.Gardrius:BAAALgADCgEJAQAAAA==.',
Ge='Gene:BAAALgADCgcJBwAAAA==.Gentonord:BAABLgAECn8cAAMCAAgJJhoDQQChAQhoDAAABwBSAGkMAAAGAEwAawwAAAIALQBqDAAAAQAvAGwMAAACAE4AbQwAAAIAQwDqDAAABQA1AG4MAAADAD8AAgAICQUXA0EAoQEIaAwAAAMANABpDAAAAgBFAGsMAAABABsAagwAAAEALwBsDAAAAgBOAG0MAAABAEMA6gwAAAMANQBuDAAAAgA/ACEABglcF2sgAD0BBmgMAAAEAFIAaQwAAAQATABrDAAAAQAtAG0MAAABADMA6gwAAAIAKABuDAAAAQA9AAAA.',
Gi='Gingerports:BAAALgADCgEJAQAAAA==.',
Gk='Gkmc:BAABLgAFFH8GAAIZAAYJ3gbfRwBWAQZoDAAAAQAKAGkMAAABABEAawwAAAEAGwBqDAAAAQAJAGwMAAABAAoA6gwAAAEAFgAZAAYJ3gbfRwBWAQZoDAAAAQAKAGkMAAABABEAawwAAAEAGwBqDAAAAQAJAGwMAAABAAoA6gwAAAEAFgABLgAFFAgJKAAYANAjAA==.',
Gl='Glomps:BAAALgAFFAMJAwABLgAFFAUJBgAiAFkEAA==.',
Go='Gonaldduck:BAAALgAECgYJBgAAAA==.',
Gr='Greasemunkey:BAABLgAECn8vAAIWAAkJCBVzCgANAgloDAAACQA/AGkMAAAIADQAawwAAAgAMQBqDAAABAAoAGwMAAAEADoAbQwAAAEAHgDqDAAACwBNAG4MAAABABMAbwwAAAEATwAWAAkJCBVzCgANAgloDAAACQA/AGkMAAAIADQAawwAAAgAMQBqDAAABAAoAGwMAAAEADoAbQwAAAEAHgDqDAAACwBNAG4MAAABABMAbwwAAAEATwAAAA==.Greentea:BAAALgADCggJCwAAAA==.Griiv:BAACLgAFFH8FAAINAAIJBB2ogQCYAAJoDAAAAQBDAOoMAAAEAFEADQACCQQdqIEAmAACaAwAAAEAQwDqDAAABABRAC4ABAp/IwACDQAICc0hIRYA5AIADQAICc0hIRYA5AIAAAA=.Grislytotem:BAAALgADCgYJCAAAAQ==.Grislywolf:BAAALgAECgUJBQAAAA==.',
Ha='Hakunamatata:BAAALgAECgUJBwAAAA==.Hamburger:BAABLgAECn8ZAAIbAAcJWxV3KgB4AQdoDAAABABRAGkMAAAEACcAawwAAAQAOABqDAAABAAvAGwMAAAEADYAbQwAAAEAJwDqDAAABAA5ABsABwlbFXcqAHgBB2gMAAAEAFEAaQwAAAQAJwBrDAAABAA4AGoMAAAEAC8AbAwAAAQANgBtDAAAAQAnAOoMAAAEADkAAAA=.Hammerhard:BAAALgADCgYJCgAAAA==.Hampter:BAAALgAECgYJCQABLgAECgkJJQAbAMgaAA==.Hanita:BAAALgAECgEJAgAAAA==.Haymáker:BAAALgADCgIJAgAAAA==.',
He='Heights:BAAALgAECgUJDgAAAA==.Heliosan:BAAALgAECgEJBAAAAA==.Heyu:BAAALgAECgUJCAABLgAECggJGwAKABcWAA==.',
Hi='Himoe:BAAALgADCgcJDgAAAA==.',
Ho='Holybean:BAAALgADCgkJGAABLgAECgUJDwAHAAAAAA==.Holyhench:BAAALgAECgUJBQAAAA==.Honkeykong:BAAALgADCgIJAgAAAA==.Hoochix:BAAALgAECgQJCQAAAA==.',
Hr='Hrsho:BAAALgADCgQJBAAAAA==.Hrshoo:BAAALgAFFAIJAgAAAA==.',
Hu='Humzashaind:BAABLgAECn8eAAMjAAgJtREIOQDYAAhoDAAABgAuAGkMAAAEABgAawwAAAQAKgBqDAAABABQAGwMAAAFADwAbQwAAAIAKADqDAAAAwA8AG4MAAACACkAAgAHCXIN2E8AAwEHaAwAAAIAHwBpDAAAAQAHAGsMAAADACoAagwAAAMAUABsDAAABQA8AG0MAAACACgA6gwAAAIAFwAjAAYJeA8IOQDYAAZoDAAABAAuAGkMAAADABgAawwAAAEAGABqDAAAAQAyAOoMAAABADwAbgwAAAIAKQAAAA==.Huntinrabits:BAAALgADCgIJAgAAAA==.Huntt:BAAALgAECgEJAQAAAA==.Huzzyy:BAAALgAECggJCgABLgAECgkJHwAVAN0bAA==.',
Hy='Hyphira:BAAALgAECgQJCgABLgAECgUJDQAHAAAAAA==.',
In='Inferbloom:BAAALgAECggJCAABLgAFFAQJDwAHAAAAAA==.Infernum:BAAALgAFFAQJDwAAAQ==.Insomnia:BAAALgAECgUJBQAAAA==.',
Ir='Irayvia:BAAALgADCgIJAgAAAA==.',
Ja='Jackyvoker:BAABLgAECn8qAAMLAAkJfCLRAQBqAwloDAAACABhAGkMAAAGAF8AawwAAAYAWABqDAAABABiAGwMAAAEAFYAbQwAAAMAVADqDAAABQBTAG4MAAAEAEMAbwwAAAIAXAALAAkJfCLRAQBqAwloDAAABwBhAGkMAAAFAF8AawwAAAUAWABqDAAABABiAGwMAAAEAFYAbQwAAAMAVADqDAAABQBTAG4MAAAEAEMAbwwAAAIAXAAGAAMJqRmCJwDlAANoDAAAAQBNAGkMAAABAD8AawwAAAEANwAAAA==.Jaezzon:BAAALgADCgQJBwAAAA==.Janessah:BAAALgADCgEJAQAAAA==.',
Je='Jeannaah:BAAALgAECgQJBAABLgAECgcJDwAHAAAAAA==.Jetaime:BAAALgAECgUJBQAAAA==.',
Jh='Jharia:BAAALgADCgMJAgAAAA==.',
Ji='Jinksey:BAAALgAECgcJDQABLgAECgcJEQAdABETAA==.',
Jo='Johndoom:BAAALgAECgYJDgAAAA==.Johnfist:BAAALgAECgEJBAAAAA==.Johngrippy:BAAALgAECgEJAwAAAA==.Johnrend:BAAALgAECgEJAQAAAA==.',
Ju='Juicybottoms:BAAALgADCgMJAgAAAA==.',
Ka='Kairstia:BAAALgAECgMJAwABLgAECggJKAAGAJsTAA==.Kalidormi:BAAALgAECgYJCgAAAA==.Kalzious:BAAALgADCgkJHAAAAA==.Kamikaze:BAAALgAECgcJBQAAAA==.Kayelalynn:BAABLgAECn8kAAMFAAkJXhX3GgDpAQloDAAABABQAGkMAAAFAD8AawwAAAYASQBqDAAABQAoAGwMAAAFADUAbQwAAAIAHgDqDAAAAwAtAG4MAAAEAC8AbwwAAAIAKgAFAAkJXhX3GgDpAQloDAAAAwBQAGkMAAAFAD8AawwAAAYASQBqDAAAAwAoAGwMAAAFADUAbQwAAAIAHgDqDAAAAgAtAG4MAAAEAC8AbwwAAAIAKgATAAMJNgEowgBDAANoDAAAAQABAGoMAAACAAQA6gwAAAEAAgAAAA==.',
Kd='Kd:BAAALgAECgEJAgAAAA==.',
Ke='Kegpaw:BAAALgAFFAEJAQAAAA==.Keiri:BAAALgADCgYJBgAAAA==.Kelana:BAABLgAECn8lAAIRAAkJxB9xCACmAgloDAAABQBHAGkMAAAFAFAAawwAAAUAXABqDAAABABBAGwMAAAEAF0AbQwAAAIAVQDqDAAABgBbAG4MAAAEAEYAbwwAAAIAQQARAAkJxB9xCACmAgloDAAABQBHAGkMAAAFAFAAawwAAAUAXABqDAAABABBAGwMAAAEAF0AbQwAAAIAVQDqDAAABgBbAG4MAAAEAEYAbwwAAAIAQQAAAA==.Kendô:BAAALgAECgcJDAAAAA==.Ketdealer:BAAALgAECgcJDQAAAA==.Ketzendk:BAAALgAECgYJBQAAAA==.Keyahi:BAACLgAFFH8RAAIdAAUJ+RmCNwA3AQVoDAAABAA0AGkMAAAEAFgAawwAAAMAJABqDAAAAQAkAOoMAAAFAFgAHQAFCfkZgjcANwEFaAwAAAQANABpDAAABABYAGsMAAADACQAagwAAAEAJADqDAAABQBYAC4ABAp/HQACHQAJCTQcmCEARAIAHQAJCTQcmCEARAIAAS4ABAoBCQEABwAAAAA=.',
Kh='Khaean:BAAALgADCgkJCQAAAA==.Khety:BAAALgAECgQJBAAAAA==.',
Ki='Kickandpunch:BAAALgAECgYJDgAAAA==.Kicsi:BAAALgAECgIJAwAAAA==.Kilan:BAABLgAECn8gAAMNAAgJXRSmeQByAQhoDAAABgBKAGkMAAAGAC8AawwAAAYAMQBqDAAAAgA3AGwMAAACADMAbQwAAAEALwDqDAAACABIAG4MAAABABYADQAHCY4TpnkAcgEHaAwAAAYASgBpDAAABgAvAGsMAAAGADEAagwAAAIANwBtDAAAAQAvAOoMAAAHADsAbgwAAAEAFgAMAAIJNBjBNACFAAJsDAAAAgAzAOoMAAABAEgAAAA=.Killinrage:BAAALgAECgYJDgAAAA==.Kissofpaine:BAAALgADCgIJAgAAAA==.Kitsuney:BAAALgADCgMJAwAAAA==.Kizaru:BAAALgAECgcJCAAAAA==.',
Ko='Korz:BAAALgADCgcJBwABLgAECgcJFQAYAOEXAA==.',
Kp='Kpop:BAAALgAECgEJAQAAAA==.',
Kr='Krutree:BAAALgAECgcJCQAAAA==.Krynj:BAAALgAFFAEJAwAAAA==.',
Ku='Kumokiri:BAAALgAECgIJAgAAAA==.Kuromu:BAAALgAFFAIJBAAAAA==.Kurzzon:BAAALgADCgMJAwAAAA==.',
Ky='Kyleata:BAABLgAECn85AAIKAAgJIR4sLQAgAghoDAAACQBZAGkMAAAIAFEAawwAAAgAUQBqDAAACABGAGwMAAAHAEUAbQwAAAQAQgDqDAAACABFAG4MAAAFAFIACgAICSEeLC0AIAIIaAwAAAkAWQBpDAAACABRAGsMAAAIAFEAagwAAAgARgBsDAAABwBFAG0MAAAEAEIA6gwAAAgARQBuDAAABQBSAAAA.Kyleigh:BAAALgAECgQJBQABLgAECgcJDwAHAAAAAA==.Kyokin:BAACLgAFFH8FAAINAAIJnxLbhQCRAAJoDAAAAgAcAOoMAAADAEIADQACCZ8S24UAkQACaAwAAAIAHADqDAAAAwBCAC4ABAp/NgADDQAJCfgUl0MA8wEADQAICTgXl0MA8wEADAAICfAGsjAAmgAAAAA=.Kyzula:BAABLgAECn8tAAIPAAcJ5RZNNADWAQdoDAAACQA/AGkMAAAIAEIAawwAAAcATwBqDAAABgBMAGwMAAAGACoA6gwAAAcANQBuDAAAAgAcAA8ABwnlFk00ANYBB2gMAAAJAD8AaQwAAAgAQgBrDAAABwBPAGoMAAAGAEwAbAwAAAYAKgDqDAAABwA1AG4MAAACABwAAAA=.',
['Kê']='Kêndo:BAAALgAECgEJAgAAAA==.',
La='Lace:BAAALgADCgMJAwAAAA==.Launam:BAAALgAECgMJBAAAAA==.Laytone:BAAALgADCgYJBwAAAA==.',
Le='Legcurl:BAAALgAECgEJAwAAAA==.Lepotko:BAAALgAECgQJBAAAAA==.',
Li='Lightbear:BAAALgADCgMJBQAAAA==.Lilchub:BAAALgAECgIJAwAAAA==.Lilylocks:BAAALgAECgcJCQAAAA==.Lilyrocks:BAAALgAECgUJCQAAAA==.Literallad:BAAALgADCgcJBgAAAA==.Littlelo:BAAALgAECgYJDAAAAA==.',
Ll='Llortdnaz:BAAALgADCgEJAgAAAA==.',
Lo='Lockology:BAAALgAFFAEJAQAAAA==.Lokarg:BAAALgADCgIJAgAAAA==.Loudcry:BAACLgAFFH8IAAIXAAQJJxQQAQA4AQRoDAAAAgBFAGkMAAABAB0AbAwAAAEAJwDqDAAABABDABcABAknFBABADgBBGgMAAACAEUAaQwAAAEAHQBsDAAAAQAnAOoMAAAEAEMALgAECn8zAAMXAAkJbx60AQCpAgAXAAgJACG0AQCpAgAYAAMJtBAY9QC3AAABLgAFFAUJCwACAJscAA==.',
Lu='Lunaeria:BAAALgADCggJCAAAAA==.',
Ly='Lyanah:BAACLgAFFH8cAAITAAUJXgkyKAAZAQVoDAAACQAXAGkMAAAIABsAawwAAAQACQBqDAAAAQAfAOoMAAAGABwAEwAFCV4JMigAGQEFaAwAAAkAFwBpDAAACAAbAGsMAAAEAAkAagwAAAEAHwDqDAAABgAcAC4ABAp/LAACEwAJCbcWTyMAKAIAEwAJCbcWTyMAKAIAAAA=.Lydia:BAAALgADCgQJBAAAAA==.Lyniah:BAAALgAECgQJBQAAAA==.',
Ma='Machete:BAAALgAECgQJCQAAAA==.Maelius:BAABLgAECn8yAAIVAAkJRhsvDQC3AgloDAAABwBMAGkMAAAHAFAAawwAAAcAVQBqDAAABgBPAGwMAAAGAFcAbQwAAAMANADqDAAABgBVAG4MAAAFAD4AbwwAAAMAEwAVAAkJRhsvDQC3AgloDAAABwBMAGkMAAAHAFAAawwAAAcAVQBqDAAABgBPAGwMAAAGAFcAbQwAAAMANADqDAAABgBVAG4MAAAFAD4AbwwAAAMAEwAAAA==.Maggrus:BAABLgAECn8bAAIKAAgJFxb1UQCkAQhoDAAABgA7AGkMAAAGAEoAawwAAAUAMwBqDAAAAgBKAGwMAAADAEgAbQwAAAEAPgDqDAAAAwBCAG4MAAABAAkACgAICRcW9VEApAEIaAwAAAYAOwBpDAAABgBKAGsMAAAFADMAagwAAAIASgBsDAAAAwBIAG0MAAABAD4A6gwAAAMAQgBuDAAAAQAJAAAA.Malavel:BAAALgADCggJCAAAAA==.Malically:BAABLgAECn8gAAMkAAkJaRDsEQAyAQloDAAABAA9AGkMAAADACgAawwAAAQAOQBqDAAABQA8AGwMAAAEADoAbQwAAAMAKwDqDAAABAAdAG4MAAAEABgAbwwAAAEAEgAkAAgJghHsEQAyAQhoDAAAAwA6AGkMAAADACgAawwAAAMAOQBqDAAABAAvAGwMAAAEADoAbQwAAAMAKwDqDAAAAwAdAG4MAAADABgACgAGCe0Lx44AGAEGaAwAAAEAPQBrDAAAAQAoAGoMAAABADwA6gwAAAEAEABuDAAAAQAOAG8MAAABABIAAAA=.Manshoon:BAAALgADCgcJCwAAAA==.Marlory:BAAALgADCgUJBQAAAA==.Math:BAAALgAFFAEJAQABLgAFFAYJCwAiAAYPAA==.Matheney:BAABLgAFFH8QAAISAAcJCA7ABACmAQdoDAAAAwBJAGkMAAADAD0AawwAAAIAKABsDAAAAwAKAG0MAAABAA8A6gwAAAMAJwBuDAAAAQALABIABwkIDsAEAKYBB2gMAAADAEkAaQwAAAMAPQBrDAAAAgAoAGwMAAADAAoAbQwAAAEADwDqDAAAAwAnAG4MAAABAAsAAS4ABRQGCQsAIgAGDwA=.Maxnem:BAAALgADCggJCAABLgAECggJHwAFADMPAA==.',
Mc='Mcrib:BAAALgADCggJBQAAAA==.Mctubby:BAAALgADCgUJBQABLgADCgUJBgAHAAAAAA==.Mctubmonk:BAAALgADCgUJBgAAAA==.',
Me='Meatpopsicle:BAAALgADCgEJAQAAAA==.Meigz:BAAALgAECgQJCwAAAA==.Melicious:BAAALgAECgQJBAAAAA==.Melidin:BAAALgAECgkJEgAAAA==.Melinda:BAAALgAFFAEJAQAAAA==.Melindorei:BAAALgAECgEJAgAAAA==.Melledrus:BAAALgAECgEJAQAAAA==.Mememo:BAAALgAECgMJAwAAAA==.Menöpaws:BAEALgAFFAMJAwAAAA==.Merithrá:BAAALgAECgMJAwAAAA==.',
Mi='Mikaeljayfox:BAAALgAECgcJDwAAAQ==.Mikros:BAAALgAECgMJAwAAAA==.Milenzha:BAABLgAECn8kAAIKAAgJNBaMRADLAQhoDAAABgBFAGkMAAAGAE4AawwAAAYAPQBqDAAABQA6AGwMAAADADIAbQwAAAIADQDqDAAABwBSAG4MAAABACsACgAICTQWjEQAywEIaAwAAAYARQBpDAAABgBOAGsMAAAGAD0AagwAAAUAOgBsDAAAAwAyAG0MAAACAA0A6gwAAAcAUgBuDAAAAQArAAAA.Milkymaiden:BAAALgADCgMJBQABLgADCgYJCQAHAAAAAA==.Mimachote:BAABLgAECn8VAAISAAkJMg5qGgBsAQloDAAAAwAxAGkMAAADAC0AawwAAAQAKQBqDAAABAAsAGwMAAADAEIAbQwAAAEAHQDqDAAAAQAiAG4MAAABAAQAbwwAAAEAEgASAAkJMg5qGgBsAQloDAAAAwAxAGkMAAADAC0AawwAAAQAKQBqDAAABAAsAGwMAAADAEIAbQwAAAEAHQDqDAAAAQAiAG4MAAABAAQAbwwAAAEAEgAAAA==.',
Mo='Monetta:BAAALgADCgIJAgAAAA==.Monk:BAAALgAECggJEAAAAA==.Moonblood:BAAALgADCggJEAAAAA==.Moonfighter:BAAALgAECgEJAgAAAA==.Moontann:BAAALgADCgkJIAAAAA==.Morcombe:BAAALgAECgEJAQAAAA==.Moreia:BAAALgAECgMJAwAAAA==.Motown:BAAALgAECgYJCwAAAA==.Mousse:BAAALgAECgYJEgAAAA==.',
Mu='Murdalok:BAABLgAECn8ZAAITAAgJshWdNQDSAQhoDAAABAA3AGkMAAAEAFIAawwAAAQAQQBqDAAAAwAtAGwMAAADADgAbQwAAAIAJgDqDAAAAwA5AG4MAAACACoAEwAICbIVnTUA0gEIaAwAAAQANwBpDAAABABSAGsMAAAEAEEAagwAAAMALQBsDAAAAwA4AG0MAAACACYA6gwAAAMAOQBuDAAAAgAqAAAA.',
My='Mysharona:BAAALgAECgEJAQAAAA==.Mystahmurdah:BAAALgAECgEJAQABLgAECgcJFQAlAM4TAA==.Mysterioñ:BAAALgAECgQJDQAAAA==.',
['Má']='Mákla:BAAALgAECgMJAwAAAA==.',
['Mâ']='Mâstermînd:BAAALgAECgUJDgAAAA==.',
Na='Nahte:BAAALgADCgYJCQAAAA==.Naiana:BAAALgADCgMJAwAAAA==.Nasine:BAAALgAECgYJCAABLgAECgkJGgAOAO0dAA==.Natstryker:BAABLgAECn9AAAQRAAkJGyaCAAB7AwloDAAACQBiAGkMAAAJAGMAawwAAAkAYwBqDAAACABjAGwMAAAIAGMAbQwAAAQAYwDqDAAACQBjAG4MAAAGAGMAbwwAAAIAVQARAAkJGyaCAAB7AwloDAAABABiAGkMAAAEAGMAawwAAAQAYwBqDAAAAwBjAGwMAAADAGMAbQwAAAMAYwDqDAAABQBjAG4MAAAEAGMAbwwAAAIAVQAEAAgJ8CJMFQBCAghoDAAABABWAGkMAAADAF0AawwAAAMAVwBqDAAABABQAGwMAAAEAF0AbQwAAAEAUQDqDAAAAwBbAG4MAAABAFsAAwAHCTERqz8AXAEHaAwAAAEAJwBpDAAAAgAZAGsMAAACACAAagwAAAEAHABsDAAAAQA+AOoMAAABADQAbgwAAAEAQwAAAA==.Naturemyth:BAAALgAFFAEJAwAAAA==.Nazu:BAAALgADCgUJCgAAAA==.',
Ne='Neeró:BAABLgAECn8iAAMdAAYJphXydwAnAQZoDAAACAAyAGkMAAAHAEgAawwAAAUAQgBqDAAABAApAGwMAAAGACAA6gwAAAQANgAdAAYJphXydwAnAQZoDAAACAAyAGkMAAAFAEgAawwAAAUAQgBqDAAABAApAGwMAAAGACAA6gwAAAQANgAIAAEJtxRHYQA+AAFpDAAAAgA1AAAA.Nelthon:BAAALgADCgYJBgAAAA==.',
Ni='Nishastraza:BAAALgAECgEJAwABLgAECgcJDwAHAAAAAA==.',
No='Nonaha:BAAALgADCgkJEQAAAA==.Notsoda:BAAALgAECgQJCQAAAA==.',
Nu='Nuciferas:BAAALgADCgUJBQAAAA==.',
Oa='Oaf:BAAALgAECgYJBgAAAA==.',
Om='Omcmoneyshot:BAAALgADCgEJAQAAAA==.',
Oo='Oolong:BAAALgAECgQJBQAAAA==.',
Or='Organa:BAABLgAECn8jAAICAAgJoAooPABQAQhoDAAACAAmAGkMAAAHACcAawwAAAYAGwBqDAAAAwAnAGwMAAACABQAbQwAAAEAFwDqDAAABwAfAG4MAAABAAgAAgAICaAKKDwAUAEIaAwAAAgAJgBpDAAABwAnAGsMAAAGABsAagwAAAMAJwBsDAAAAgAUAG0MAAABABcA6gwAAAcAHwBuDAAAAQAIAAAA.',
Ou='Outofthedark:BAAALgAECgIJAgAAAA==.',
Pa='Pakkan:BAAALgAECgEJAQAAAA==.Pallyqb:BAAALgADCgEJAQAAAA==.Pandariam:BAAALgAECgYJCgAAAA==.Pauladeenx:BAAALgAECgIJAwABLgAECgUJDgAHAAAAAA==.',
Pe='Petal:BAAALgAECgYJBwABLgAECggJEAAHAAAAAA==.',
Pl='Playwitwe:BAAALgAECgUJCAAAAA==.Plowmcballs:BAABLgAECn8ZAAINAAYJtxIzfgB+AQZoDAAABQA+AGkMAAAEAC0AawwAAAQANgBqDAAAAwBMAGwMAAAEABwA6gwAAAUALwANAAYJtxIzfgB+AQZoDAAABQA+AGkMAAAEAC0AawwAAAQANgBqDAAAAwBMAGwMAAAEABwA6gwAAAUALwAAAA==.Plugley:BAABLgAECn8dAAMYAAkJqBgeOQAwAgloDAAABQBNAGkMAAAEAFcAawwAAAQAUABqDAAAAwBLAGwMAAACAFYAbQwAAAEAOADqDAAABgBCAG4MAAADAB4AbwwAAAEAFAAYAAkJqBgeOQAwAgloDAAABABNAGkMAAAEAFcAawwAAAQAUABqDAAAAwBLAGwMAAACAFYAbQwAAAEAOADqDAAABgBCAG4MAAADAB4AbwwAAAEAFAAXAAEJARSGHAA6AAFoDAAAAQAzAAAA.',
Po='Polaris:BAAALgAECgEJAQAAAA==.Poober:BAABLgAECn8hAAMaAAkJbx+yCwCiAgloDAAAAwBNAGkMAAAEAEkAawwAAAQAUgBqDAAABABgAGwMAAAEAFwAbQwAAAEAVwDqDAAACQBaAG4MAAADAFUAbwwAAAEAJgAaAAgJeCGyCwCiAghoDAAAAwBNAGkMAAAEAEkAawwAAAQAUgBqDAAAAwBgAGwMAAADAFwAbQwAAAEAVwDqDAAABwBaAG4MAAADAFUAJgAECTQZtzQAOwEEagwAAAEASgBsDAAAAQBJAOoMAAACAEcAbwwAAAEAJgAAAA==.Potooòooóoo:BAABLgAECn8dAAIQAAcJVhhmFAAvAQdoDAAABwBPAGkMAAAGAEAAawwAAAYAPQBqDAAAAQA+AGwMAAACACIA6gwAAAYAPQBuDAAAAQBIABAABwlWGGYUAC8BB2gMAAAHAE8AaQwAAAYAQABrDAAABgA9AGoMAAABAD4AbAwAAAIAIgDqDAAABgA9AG4MAAABAEgAAAA=.',
Pr='Pren:BAAALgAFFAEJAQAAAA==.Privet:BAAALgAECgEJAwAAAA==.',
Pu='Purebeef:BAAALgAECgIJAgAAAA==.',
Py='Pygos:BAABLgAECn8ZAAInAAgJ5BiJBwANAghoDAAABABIAGkMAAAEADYAawwAAAQATABqDAAAAwBEAGwMAAADADwAbQwAAAIALgDqDAAAAwBaAG4MAAACACwAJwAICeQYiQcADQIIaAwAAAQASABpDAAABAA2AGsMAAAEAEwAagwAAAMARABsDAAAAwA8AG0MAAACAC4A6gwAAAMAWgBuDAAAAgAsAAAA.',
['Pë']='Përdü:BAAALgAECggJEgAAAA==.',
Qu='Quigglay:BAAALgAECgYJBgAAAA==.',
Ra='Raegnarok:BAABLgAECn8hAAIVAAgJ/ROxIQDuAQhoDAAABQBAAGkMAAAFADIAawwAAAUAPQBqDAAABgA1AGwMAAACACEAbQwAAAEAFQDqDAAABwBIAG4MAAACADUAFQAICf0TsSEA7gEIaAwAAAUAQABpDAAABQAyAGsMAAAFAD0AagwAAAYANQBsDAAAAgAhAG0MAAABABUA6gwAAAcASABuDAAAAgA1AAAA.Raelessa:BAAALgAECgQJCQABLgAECgcJDwAHAAAAAA==.Raigeki:BAAALgADCgQJBQAAAA==.Ralf:BAAALgAECgEJAQAAAA==.Ralphie:BAAALgAECgIJAgAAAA==.Ratapew:BAABLgAECn8VAAIdAAgJzxSGUQCIAQhoDAAAAgBdAGkMAAAEAEgAawwAAAQAGABqDAAABAA0AGwMAAACADgAbQwAAAEAEADqDAAAAwBCAG4MAAABACsAHQAICc8UhlEAiAEIaAwAAAIAXQBpDAAABABIAGsMAAAEABgAagwAAAQANABsDAAAAgA4AG0MAAABABAA6gwAAAMAQgBuDAAAAQArAAAA.Ratheen:BAABLgAECn8dAAINAAgJtA7HlABBAQhoDAAABQA3AGkMAAAFACQAawwAAAUAKwBqDAAABAAoAGwMAAADACYAbQwAAAEAEwDqDAAABQA2AG4MAAABAA8ADQAICbQOx5QAQQEIaAwAAAUANwBpDAAABQAkAGsMAAAFACsAagwAAAQAKABsDAAAAwAmAG0MAAABABMA6gwAAAUANgBuDAAAAQAPAAAA.Raytar:BAABLgAECn8gAAMFAAkJNB95DwBgAgloDAAABQBZAGkMAAAFAF4AawwAAAUAVgBqDAAABABfAGwMAAACAEwAbQwAAAEAPQDqDAAABABgAG4MAAAEAEMAbwwAAAIAQgAFAAgJPyB5DwBgAghoDAAABQBZAGkMAAAFAF4AawwAAAQAVgBqDAAABABfAGwMAAACAEwA6gwAAAMAYABuDAAABABDAG8MAAACAEIAEwADCfUbAZsAlgADawwAAAEAVgBtDAAAAQBDAOoMAAABADwAAAA=.',
Re='Rekkirin:BAAALgAECgUJBQABLgAECgkJOAALAAUWAA==.Relyk:BAAALgADCgUJBQAAAA==.',
Ri='Riyo:BAAALgAFFAIJAwAAAA==.',
Ro='Roachie:BAAALgAECgYJDgAAAA==.Rockandstone:BAAALgADCgEJAQAAAA==.Roesira:BAAALgAECgEJAQAAAA==.Rogun:BAAALgAECgkJAQAAAA==.Ros:BAAALgAECgMJBAAAAA==.',
Ru='Rug:BAAALgADCgYJBgAAAA==.Rustybray:BAABLgAECn81AAIOAAkJhgetPwApAQloDAAABgAOAGkMAAAGABEAawwAAAYAEgBqDAAABgAQAGwMAAAIABwAbQwAAAUAEADqDAAABwAfAG4MAAAGAAkAbwwAAAMAEQAOAAkJhgetPwApAQloDAAABgAOAGkMAAAGABEAawwAAAYAEgBqDAAABgAQAGwMAAAIABwAbQwAAAUAEADqDAAABwAfAG4MAAAGAAkAbwwAAAMAEQAAAA==.Ruu:BAAALgAECgkJBQABLgAFFAQJDgAlAAQRAA==.',
Ry='Ryvulz:BAABLgAECn8eAAIbAAgJHRWsGAAcAghoDAAABQBAAGkMAAAFAEEAawwAAAUAOABqDAAABABCAGwMAAAEAEYAbQwAAAEAEADqDAAABQBJAG4MAAABACAAGwAICR0VrBgAHAIIaAwAAAUAQABpDAAABQBBAGsMAAAFADgAagwAAAQAQgBsDAAABABGAG0MAAABABAA6gwAAAUASQBuDAAAAQAgAAAA.',
Sa='Salomicum:BAAALgADCgEJAQAAAA==.Sappollo:BAAALgADCgMJAwAAAA==.Sarabi:BAABLgAECn8nAAIDAAgJlBXUJADsAQhoDAAACAA9AGkMAAAIAEIAawwAAAgAPABqDAAABABMAGwMAAACACkAbQwAAAEALQDqDAAABwA6AG4MAAABACAAAwAICZQV1CQA7AEIaAwAAAgAPQBpDAAACABCAGsMAAAIADwAagwAAAQATABsDAAAAgApAG0MAAABAC0A6gwAAAcAOgBuDAAAAQAgAAAA.Sarena:BAAALgADCgMJAwAAAA==.Sarkoth:BAAALgADCgEJAQAAAA==.',
Sc='Schnee:BAAALgADCgYJCgAAAA==.Schutzhund:BAAALgAECgMJAgAAAA==.Scrapster:BAAALgAECgUJCwAAAA==.',
Se='Seifer:BAAALgADCgEJAQAAAA==.Sekha:BAAALgAECgQJBgABLgAECggJIQAFAOoXAA==.Serbero:BAAALgAECgEJAQAAAA==.Seshiro:BAAALgAECgQJBAABLgAECgkJNQAMANkjAA==.',
Sh='Shadoweave:BAACLgAFFH8bAAMaAAUJ9BdWDgBYAQVoDAAABwBXAGkMAAAHAE8AawwAAAQAGwBqDAAAAgA4AOoMAAAHADgAGgAFCfQXVg4AWAEFaAwAAAUAVwBpDAAABQBPAGsMAAAEABsAagwAAAIAOADqDAAABwA4ABsAAglIDcIsAIYAAmgMAAACABUAaQwAAAIALgAuAAQKfxkAAhoACQkoGHkSAEACABoACQkoGHkSAEACAAEuAAUUCAkuAAoA/RgA.Shalalia:BAABLgAECn8bAAIKAAcJNw7pbQBcAQdoDAAABAAuAGkMAAAFACYAawwAAAQAJABqDAAAAwAqAGwMAAACACMA6gwAAAQAJABuDAAABQAYAAoABwk3DultAFwBB2gMAAAEAC4AaQwAAAUAJgBrDAAABAAkAGoMAAADACoAbAwAAAIAIwDqDAAABAAkAG4MAAAFABgAAAA=.Shambean:BAAALgADCgEJAQABLgAECgUJDwAHAAAAAA==.Shammywitch:BAAALgAFFAEJAQABLgAECgQJCgAHAAAAAA==.Shentsu:BAABLgAECn8YAAIDAAkJ0CD7BQD/AgloDAAAAwBhAGkMAAADAFwAawwAAAMAWgBqDAAAAwBTAGwMAAACAFQAbQwAAAMAVADqDAAAAwBfAG4MAAADAEwAbwwAAAEAMwADAAkJ0CD7BQD/AgloDAAAAwBhAGkMAAADAFwAawwAAAMAWgBqDAAAAwBTAGwMAAACAFQAbQwAAAMAVADqDAAAAwBfAG4MAAADAEwAbwwAAAEAMwAAAA==.Shhanks:BAAALgAECgEJAQAAAA==.Shinmen:BAAALgADCgkJCQAAAA==.Shinsha:BAAALgADCgIJAwAAAA==.Shnizelnazee:BAABLgAECn8WAAINAAgJDwwrrAAbAQhoDAAAAwA7AGkMAAADAB4AawwAAAQAFwBqDAAAAgA/AGwMAAACACMAbQwAAAEAEQDqDAAABgAnAG4MAAABAAoADQAICQ8MK6wAGwEIaAwAAAMAOwBpDAAAAwAeAGsMAAAEABcAagwAAAIAPwBsDAAAAgAjAG0MAAABABEA6gwAAAYAJwBuDAAAAQAKAAAA.Shortonheals:BAAALgAECgMJAwAAAA==.',
Si='Siege:BAAALgAECgUJBQAAAA==.Silie:BAAALgADCgEJAQAAAA==.Silik:BAAALgADCgcJBwAAAA==.Simpforsale:BAAALgAECgYJCQAAAA==.',
Sk='Skybladee:BAAALgAECgIJAgAAAA==.',
Sm='Smokeyb:BAACLgAFFH8IAAINAAMJ+AmLbgDHAANoDAAABAAeAGkMAAABABYA6gwAAAMAFwANAAMJ+AmLbgDHAANoDAAABAAeAGkMAAABABYA6gwAAAMAFwAuAAQKfywAAg0ACAlrFgxUAMUBAA0ACAlrFgxUAMUBAAAA.',
Sn='Sneevie:BAAALgAECggJCgAAAA==.Snorehees:BAABLgAECn8sAAMKAAkJwQ9SSADAAQloDAAABwAjAGkMAAAHADYAawwAAAYAKgBqDAAABQAoAGwMAAAGACIAbQwAAAIAFADqDAAABgAuAG4MAAAEADYAbwwAAAEAIQAKAAkJwQ9SSADAAQloDAAABgAjAGkMAAAGADYAawwAAAUAKgBqDAAABQAoAGwMAAAFACIAbQwAAAIAFADqDAAABgAuAG4MAAAEADYAbwwAAAEAIQAkAAQJMwJeNABEAARoDAAAAQALAGkMAAABAAYAawwAAAEAAwBsDAAAAQAAAAAA.',
So='Songarrow:BAAALgAECgYJBgAAAA==.Songstar:BAABLgAECn8qAAIKAAkJaiPGDgDTAgloDAAABgBeAGkMAAAFAF8AawwAAAYAXwBqDAAABABaAGwMAAAFAFAAbQwAAAMAWADqDAAABQBfAG4MAAAFAFQAbwwAAAMAWgAKAAkJaiPGDgDTAgloDAAABgBeAGkMAAAFAF8AawwAAAYAXwBqDAAABABaAGwMAAAFAFAAbQwAAAMAWADqDAAABQBfAG4MAAAFAFQAbwwAAAMAWgAAAA==.Soullraven:BAAALgADCgkJMQAAAA==.',
Sp='Spy:BAAALgAECgEJBQAAAA==.',
Sq='Squingledorf:BAAALgAECgMJAwAAAA==.',
St='Staavon:BAABLgAECn8mAAIYAAgJ0QlEiwBdAQhoDAAABwAmAGkMAAAHABsAawwAAAcAKwBqDAAABQATAGwMAAADABQAbQwAAAEAFADqDAAABQAMAG4MAAADAA0AGAAICdEJRIsAXQEIaAwAAAcAJgBpDAAABwAbAGsMAAAHACsAagwAAAUAEwBsDAAAAwAUAG0MAAABABQA6gwAAAUADABuDAAAAwANAAAA.Stacy:BAAALgAECgEJAQABLgAECgQJCAAHAAAAAA==.Stalvis:BAAALgADCgUJBQAAAA==.Starblaze:BAAALgAECgYJCQAAAA==.Starseek:BAABLgAECn8VAAInAAcJLhDLEABDAQdoDAAABAAlAGkMAAADADYAawwAAAMATgBqDAAAAwA6AGwMAAADAB4A6gwAAAMAFQBuDAAAAgAZACcABwkuEMsQAEMBB2gMAAAEACUAaQwAAAMANgBrDAAAAwBOAGoMAAADADoAbAwAAAMAHgDqDAAAAwAVAG4MAAACABkAAAA=.Steelboats:BAAALgADCgkJGQAAAA==.',
Su='Sugarbow:BAAALgADCgMJAwAAAA==.Sugarhoof:BAAALgAECgQJBAAAAA==.Sugarlick:BAABLgAECn8jAAIUAAgJPRtaFgCuAQhoDAAABgBgAGkMAAAGAFQAawwAAAYAWQBqDAAABQBQAGwMAAAEACsAbQwAAAEAMQDqDAAABgBEAG4MAAABADgAFAAICT0bWhYArgEIaAwAAAYAYABpDAAABgBUAGsMAAAGAFkAagwAAAUAUABsDAAABAArAG0MAAABADEA6gwAAAYARABuDAAAAQA4AAAA.Sugarpop:BAACLgAFFH8GAAIVAAMJNw3YMQCjAANoDAAAAwA2AGkMAAACABQA6gwAAAEAGgAVAAMJNw3YMQCjAANoDAAAAwA2AGkMAAACABQA6gwAAAEAGgAuAAQKfygAAhUACQnXHIISAH4CABUACQnXHIISAH4CAAEuAAUUBAkKAA8ApBsA.Sunraku:BAAALgAECgIJAwAAAA==.Suplazindh:BAAALgAFFAIJAgABLgAFFAkJPQAQAJIhAA==.',
Sw='Swethort:BAAALgADCgcJBgAAAA==.',
Sy='Synman:BAAALgADCgYJBgAAAA==.Syntheria:BAAALgADCgcJCQAAAA==.Syrebriel:BAABLgAECn8VAAImAAcJCxEBJABzAQdoDAAAAwA4AGkMAAADADgAawwAAAQAMQBqDAAAAwAaAGwMAAADABQAbQwAAAEAEQDqDAAABABOACYABwkLEQEkAHMBB2gMAAADADgAaQwAAAMAOABrDAAABAAxAGoMAAADABoAbAwAAAMAFABtDAAAAQARAOoMAAAEAE4AAAA=.',
['Sí']='Sílíbrítí:BAAALgAECgYJDQABLgAFFAMJCQADABILAA==.',
Ta='Taediah:BAAALgAECgcJDQAAAA==.Tamius:BAAALgADCgEJAQAAAA==.Tanthanalas:BAAALgAECgQJBAAAAA==.',
Th='Thefalsehope:BAAALgADCgcJBwAAAA==.Theoutcast:BAAALgAECgQJDgAAAA==.Thesarius:BAABLgAECn8ZAAIhAAgJXxmXDQAxAghoDAAABABPAGkMAAAEAE0AawwAAAQATABqDAAAAwBVAGwMAAADADkAbQwAAAIALwDqDAAAAwBIAG4MAAACACsAIQAICV8Zlw0AMQIIaAwAAAQATwBpDAAABABNAGsMAAAEAEwAagwAAAMAVQBsDAAAAwA5AG0MAAACAC8A6gwAAAMASABuDAAAAgArAAAA.Thortor:BAAALgADCgIJAgABLgADCggJEAAHAAAAAA==.Thumbzie:BAAALgAECgMJAwAAAA==.',
Ti='Tiestto:BAAALgAECgcJDgAAAA==.Tinkermid:BAAALgADCgEJAQAAAA==.Tinymeatgang:BAAALgADCggJCQAAAA==.',
To='Tobalwl:BAAALgADCgUJBQAAAA==.Tockley:BAABLgAECn8hAAIYAAgJQwaE2QDhAAhoDAAABgAeAGkMAAAFAAgAawwAAAUAEgBqDAAABQAiAGwMAAAFABkAbQwAAAEAAgDqDAAABQAaAG4MAAABAAEAGAAICUMGhNkA4QAIaAwAAAYAHgBpDAAABQAIAGsMAAAFABIAagwAAAUAIgBsDAAABQAZAG0MAAABAAIA6gwAAAUAGgBuDAAAAQABAAAA.Toetagger:BAABLgAECn8dAAIZAAgJbA/4aQCMAQhoDAAABAA0AGkMAAAGADUAawwAAAYAGABqDAAABQAvAGwMAAACADMA6gwAAAQAJgBuDAAAAQAjAG8MAAABABMAGQAICWwP+GkAjAEIaAwAAAQANABpDAAABgA1AGsMAAAGABgAagwAAAUALwBsDAAAAgAzAOoMAAAEACYAbgwAAAEAIwBvDAAAAQATAAAA.Tofino:BAAALgAECggJDwAAAA==.Tohner:BAAALgADCgMJAwAAAA==.Tolidron:BAAALgADCgEJAQAAAA==.Tonimâster:BAAALgAFFAEJAQAAAA==.Tonydmaster:BAAALgAECgEJAQAAAA==.Toyotama:BAAALgAECgUJDQAAAA==.',
Tr='Trashiepanda:BAAALgAECgUJDgAAAA==.Trenbologna:BAAALgAECgEJAQAAAA==.Tristah:BAAALgAECgUJDwABLgAECgcJDwAHAAAAAA==.Trzlawd:BAAALgADCgEJAQAAAA==.',
Ty='Tyindron:BAAALgAECgYJBwAAAA==.Tyrrial:BAABLgAECn8xAAINAAgJbRcRTgDVAQhoDAAACQBYAGkMAAAJAEYAawwAAAoAKwBqDAAABgAuAGwMAAADADUAbQwAAAEAJwDqDAAACABVAG4MAAADACgADQAICW0XEU4A1QEIaAwAAAkAWABpDAAACQBGAGsMAAAKACsAagwAAAYALgBsDAAAAwA1AG0MAAABACcA6gwAAAgAVQBuDAAAAwAoAAAA.Tyshus:BAAALgAECgYJDQAAAA==.',
Ud='Udntknwme:BAAALgAFFAIJAwAAAA==.',
Un='Unbral:BAAALgADCgEJAQAAAA==.Unicood:BAAALgADCgYJBgAAAA==.Unlockbot:BAAALgADCgEJAwABLgAECgcJDwAHAAAAAA==.Unwholey:BAAALgAECggJCAAAAA==.',
Ut='Uthgardt:BAAALgAECgYJBgABLgAECgYJCwAHAAAAAA==.',
Va='Valarion:BAABLgAECn8mAAIjAAgJ4RIOFgCkAQhoDAAABwA7AGkMAAAGAE4AawwAAAYAPgBqDAAABQA7AGwMAAAEAA4A6gwAAAUAKABuDAAABAArAG8MAAABACgAIwAICeESDhYApAEIaAwAAAcAOwBpDAAABgBOAGsMAAAGAD4AagwAAAUAOwBsDAAABAAOAOoMAAAFACgAbgwAAAQAKwBvDAAAAQAoAAAA.Valcaryn:BAAALgADCgYJBgAAAA==.Validimus:BAABLgAECn8aAAMNAAgJnQcurQAaAQhoDAAABQAhAGkMAAAFABEAawwAAAUAFgBqDAAAAgAWAGwMAAACAAwAbQwAAAEAEwDqDAAABAALAG4MAAACABMADQAICfAGLq0AGgEIaAwAAAUAIQBpDAAABQARAGsMAAAFABYAagwAAAIAFgBsDAAAAgAMAG0MAAABABMA6gwAAAMACABuDAAAAQAJAAwAAgn5BdZJADoAAuoMAAABAAsAbgwAAAEAEwAAAA==.Valinis:BAAALgAECgQJBAAAAA==.Valinius:BAAALgADCgYJCQAAAA==.Valorían:BAABLgAECn9AAAQhAAkJayTbAQAyAwloDAAACQBbAGkMAAAJAGAAawwAAAkAYQBqDAAACABhAGwMAAAIAGIAbQwAAAQAWwDqDAAACQBbAG4MAAAGAFwAbwwAAAIAVgAhAAkJiSPbAQAyAwloDAAAAgBaAGkMAAADAGAAawwAAAMAYQBqDAAAAQBhAGwMAAABAGIAbQwAAAEAWwDqDAAAAwBbAG4MAAADAFwAbwwAAAEARQACAAkJ+iHTCgC0AgloDAAABwBbAGkMAAAGAFcAawwAAAYAWQBqDAAABwBhAGwMAAAGAGEAbQwAAAMAVQDqDAAABgBIAG4MAAACAFUAbwwAAAEAVgAjAAIJAiBJQQC5AAJsDAAAAQBTAG4MAAABAFAAAAA=.Valtaa:BAAALgADCgUJBwAAAA==.Vanza:BAAALgADCgEJAQAAAA==.Varthayn:BAABLgAECn9DAAIYAAkJ4iDEGADAAgloDAAACABdAGkMAAAIAFQAawwAAAgAUgBqDAAACABcAGwMAAAKAFcAbQwAAAUAVADqDAAACABQAG4MAAAJAEkAbwwAAAMAVgAYAAkJ4iDEGADAAgloDAAACABdAGkMAAAIAFQAawwAAAgAUgBqDAAACABcAGwMAAAKAFcAbQwAAAUAVADqDAAACABQAG4MAAAJAEkAbwwAAAMAVgAAAA==.',
Ve='Vecna:BAAALgAECgMJAwABLgAECgYJCAAHAAAAAA==.Velandriel:BAAALgADCgkJCwABLgAECgkJOQAIANQYAA==.Vengfuhl:BAAALgAECgQJAwAAAA==.Verra:BAAALgAECgEJAQAAAA==.Vet:BAAALgAECgEJAQAAAA==.',
Vo='Voidwa:BAAALgAECgYJDgAAAA==.Volbain:BAABLgAECn8tAAQIAAgJmhttEAAWAghoDAAACQBGAGkMAAAJAF8AawwAAAkASgBqDAAAAwBGAGwMAAACACsAbQwAAAEAPQDqDAAACgBLAG4MAAACAEkACAAICZobbRAAFgIIaAwAAAgARgBpDAAACABfAGsMAAAHAEoAagwAAAMARgBsDAAAAgArAG0MAAABAD0A6gwAAAoASwBuDAAAAgBJACcAAwnkESweAKAAA2gMAAABAB4AaQwAAAEANABrDAAAAQA2AB0AAQnTAjsrARwAAWsMAAABAAcAAAA=.Volklin:BAABLgAECn8pAAMlAAkJqhQFIQCSAQloDAAACAA7AGkMAAAEAEUAawwAAAQAMABqDAAABgAlAGwMAAAFACYAbQwAAAIARQDqDAAABwAzAG4MAAACACIAbwwAAAMAMwAlAAkJow4FIQCSAQloDAAABAA7AGkMAAABABUAawwAAAEABQBqDAAAAgAjAGwMAAACACYAbQwAAAIARQDqDAAAAgAzAG4MAAACACIAbwwAAAIAEwAKAAcJaRTeTQB/AQdoDAAABAA6AGkMAAADAEUAawwAAAMAMABqDAAABAAlAGwMAAADACIA6gwAAAUAMQBvDAAAAQAzAAAA.Voltagex:BAABLgAECn8dAAIdAAcJfRz1UgCEAQdoDAAABQBbAGkMAAAEAFEAawwAAAUAXwBqDAAACABbAGwMAAADAFEA6gwAAAMAUwBuDAAAAQADAB0ABwl9HPVSAIQBB2gMAAAFAFsAaQwAAAQAUQBrDAAABQBfAGoMAAAIAFsAbAwAAAMAUQDqDAAAAwBTAG4MAAABAAMAAAA=.',
Vu='Vulpsinculta:BAABLgAECn8kAAIcAAgJ6RTKSAC7AQhoDAAABwA6AGkMAAAHADoAawwAAAcASABqDAAAAwBDAGwMAAACAC4AbQwAAAEAJwDqDAAACABCAG4MAAABACEAHAAICekUykgAuwEIaAwAAAcAOgBpDAAABwA6AGsMAAAHAEgAagwAAAMAQwBsDAAAAgAuAG0MAAABACcA6gwAAAgAQgBuDAAAAQAhAAAA.',
['Vï']='Vïrùs:BAABLgAECn8jAAIFAAcJeg1aPABDAQdoDAAABwAhAGkMAAAHADEAawwAAAcALABqDAAAAwASAGwMAAADABQAbQwAAAEABQDqDAAABwA1AAUABwl6DVo8AEMBB2gMAAAHACEAaQwAAAcAMQBrDAAABwAsAGoMAAADABIAbAwAAAMAFABtDAAAAQAFAOoMAAAHADUAAAA=.',
Wa='Wanda:BAAALgAECgYJBgAAAA==.',
Wi='Wichita:BAABLgAECn80AAMZAAkJsA+/XQCqAQloDAAABgA0AGkMAAAGAC8AawwAAAYAOwBqDAAABgAsAGwMAAAIAA8AbQwAAAUAGwDqDAAABwAvAG4MAAAFACUAbwwAAAMAIQAZAAgJEhG/XQCqAQhoDAAABgA0AGkMAAAGAC8AawwAAAYAOwBqDAAABgAsAG0MAAAFABsA6gwAAAcALwBuDAAABQAlAG8MAAADACEAFAABCQUG8GAAIAABbAwAAAgADwAAAA==.Wildkitty:BAAALgAFFAEJAQAAAA==.',
Wo='Wolfyze:BAAALgADCgEJAQAAAA==.',
Wr='Wrâth:BAAALgAECgEJAgAAAA==.',
Wt='Wtfartemis:BAAALgAECgQJBAAAAA==.Wtfguën:BAABLgAECn8pAAISAAgJ7gtqKAAFAQhoDAAACQAiAGkMAAAJACYAawwAAAkAIwBqDAAAAwAmAGwMAAACAA8AbQwAAAEAIwDqDAAABwAnAG4MAAABAA4AEgAICe4LaigABQEIaAwAAAkAIgBpDAAACQAmAGsMAAAJACMAagwAAAMAJgBsDAAAAgAPAG0MAAABACMA6gwAAAcAJwBuDAAAAQAOAAAA.Wtftäzmikell:BAAALgADCgYJCQABLgAECggJKQASAO4LAA==.',
Wu='Wutäng:BAAALgADCgYJCgAAAA==.',
Xe='Xera:BAAALgADCgYJBgAAAA==.',
Xo='Xondra:BAAALgAECgYJDQAAAA==.',
Xr='Xravo:BAAALgADCgkJCQAAAA==.',
Xz='Xzairi:BAABLgAECn8hAAIFAAgJ6hdaIwCkAQhoDAAABQA/AGkMAAAFAE4AawwAAAUASQBqDAAABAA5AGwMAAADACsAbQwAAAEAEADqDAAACABRAG8MAAACAEcABQAICeoXWiMApAEIaAwAAAUAPwBpDAAABQBOAGsMAAAFAEkAagwAAAQAOQBsDAAAAwArAG0MAAABABAA6gwAAAgAUQBvDAAAAgBHAAAA.',
Ya='Yarria:BAAALgADCgIJAgAAAA==.',
Yi='Yinh:BAAALgADCgcJDAAAAA==.',
Yo='Yoiki:BAAALgAECgEJAQABLgAECgEJAQAHAAAAAA==.',
Yu='Yuck:BAAALgAECgIJBAAAAA==.',
Yy='Yy:BAAALgAECgUJDAAAAA==.',
Ze='Zeuzco:BAAALgAECgkJEQAAAA==.',
Zo='Zorell:BAAALgAECgYJDAAAAA==.Zovaal:BAAALgAECgQJBAAAAA==.',
['Ál']='Áltá:BAABLgAECn8uAAMcAAkJURk4JQBEAgloDAAABwBQAGkMAAAHAFoAawwAAAcANgBqDAAABQBDAGwMAAAFAD0AbQwAAAIAUADqDAAABwBSAG4MAAAEACwAbwwAAAIAFgAcAAkJURk4JQBEAgloDAAABgBQAGkMAAAGAFoAawwAAAcANgBqDAAABQBDAGwMAAAFAD0AbQwAAAIAUADqDAAABwBSAG4MAAAEACwAbwwAAAIAFgAgAAIJNwxGMQBSAAJoDAAAAQAZAGkMAAABACUAAAA=.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
