local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'DeathKnight-Frost','DeathKnight-Unholy','Warlock-Demonology','Unknown-Unknown','Shaman-Elemental','DemonHunter-Devourer','DemonHunter-Havoc','Monk-Brewmaster','Paladin-Holy','Evoker-Augmentation','Evoker-Preservation','Druid-Restoration','Warrior-Protection','Warrior-Arms','Paladin-Retribution','Paladin-Protection','Rogue-Outlaw','Hunter-BeastMastery','Hunter-Marksmanship','Shaman-Restoration','Shaman-Enhancement','Mage-Frost','Warlock-Destruction','DeathKnight-Blood','Warrior-Fury','Hunter-Survival','Priest-Shadow','Priest-Holy','Monk-Windwalker','Druid-Balance','Priest-Discipline','Druid-Guardian','Druid-Feral','Monk-Mistweaver','Warlock-Affliction','DemonHunter-Vengeance','Rogue-Subtlety','Rogue-Assassination','Evoker-Devastation',}
local provider = {region='US',realm='Undermine',name='US',type='daily',zone=46,date='2026-06-09',data={Ab='Abaddon:BAABLgAECn8tAAMBAAkJTB+1BgAsAgloDAAABwBaAGkMAAAHAFIAawwAAAYAUwBqDAAABgBLAGwMAAAFAE4AbQwAAAMAOgDqDAAABgBVAG4MAAAEAEYAbwwAAAEAXAABAAgJ6R21BgAsAghoDAAABQBaAGkMAAAFAFIAawwAAAQAUwBqDAAAAQBCAGwMAAADAE4AbQwAAAEALQDqDAAABgBVAG4MAAADAEYAAgAICawcc0EA+wEIaAwAAAIAVABpDAAAAgBQAGsMAAACAEMAagwAAAUASwBsDAAAAgBGAG0MAAACADoAbgwAAAEAOwBvDAAAAQBcAAAA.Abessedge:BAAALgAECgUJBQAAAA==.',
Ac='Acidtears:BAAALgAECgEJAQAAAA==.Ackris:BAABLgAECn8uAAIDAAkJ/BwHCgAuAwloDAAABQBjAGkMAAAFAEwAawwAAAYAWwBqDAAABgBfAGwMAAAGAFwAbQwAAAYANgDqDAAACABfAG4MAAACACoAbwwAAAIAKQADAAkJ/BwHCgAuAwloDAAABQBjAGkMAAAFAEwAawwAAAYAWwBqDAAABgBfAGwMAAAGAFwAbQwAAAYANgDqDAAACABfAG4MAAACACoAbwwAAAIAKQAAAA==.Ackrisa:BAAALgAECgUJCAAAAA==.Acris:BAAALgAECgYJCwABLgAECgkJLgADAPwcAA==.',
Ae='Aedimus:BAAALgADCgcJCQAAAA==.',
Al='Aleathris:BAEALgADCgcJBwABLgAECgQJBAAEAAAAAA==.Alistan:BAAALgAECgEJAQAAAA==.Alka:BAAALgADCgEJAQAAAA==.Alor:BAAALgAECgIJBAABLgAECgkJNAAFAJgMAA==.Alpyne:BAAALgAECgcJEgAAAA==.',
Am='Amaimon:BAABLgAECn8aAAMGAAgJDhUVVACCAQhoDAAAAwAvAGkMAAAEAEcAawwAAAQANQBqDAAAAwAyAGwMAAADAEMAbQwAAAIALgDqDAAABAA1AG4MAAADACQABgAICQ4VFVQAggEIaAwAAAMALwBpDAAABABHAGsMAAAEADUAagwAAAMAMgBsDAAAAwBDAG0MAAACAC4A6gwAAAQANQBuDAAAAgAkAAcAAQlrDBtqAC8AAW4MAAABAB8AAS4ABRQICRwABQAqEwA=.Amalthaea:BAAALgAECgcJEwABLgAECgkJLgAIAGMWAA==.Amnoon:BAABLgAECn80AAIJAAkJ+BcVEwByAgloDAAACQBSAGkMAAAIADoAawwAAAgAQwBqDAAABwBIAGwMAAAGAEUAbQwAAAQAJQDqDAAACABLAG4MAAABADcAbwwAAAEAIAAJAAkJ+BcVEwByAgloDAAACQBSAGkMAAAIADoAawwAAAgAQwBqDAAABwBIAGwMAAAGAEUAbQwAAAQAJQDqDAAACABLAG4MAAABADcAbwwAAAEAIAAAAA==.Amri:BAACLgAFFH8ZAAMKAAUJPhAcMAD5AAVoDAAABgArAGkMAAAGADUAawwAAAQAFABqDAAAAwAYAOoMAAAGADAACgAFCT4QHDAA+QAFaAwAAAYAKwBpDAAABgA1AGsMAAAEABQAagwAAAMAGADqDAAABQAwAAsAAQlgAgYuACUAAeoMAAABAAYALgAECn8fAAMKAAgJcRagFQAtAgAKAAgJcRagFQAtAgALAAYJQA2NIQDcAAAAAA==.',
An='Andarnáurram:BAAALgAECgIJAgAAAA==.Angelfox:BAAALgAECgQJAgAAAA==.',
Aq='Aquas:BAAALgAECgQJBwAAAA==.',
Ar='Ardrhys:BAAALgAECgcJDgAAAA==.Arthurcarrot:BAAALgAECgQJBwAAAA==.Artikin:BAAALgAECgkJCwABLgAFFAYJEgAHAJcVAA==.',
As='Assasinateu:BAAALgADCgMJAwAAAA==.Asûná:BAAALgAECgcJDwAAAA==.',
At='Atreus:BAABLgAECn8mAAMHAAkJ7Bx3DQBDAgloDAAACABXAGkMAAAGAEMAawwAAAYAVABqDAAAAwAzAGwMAAACAFMAbQwAAAEADADqDAAABwBcAG4MAAADAFcAbwwAAAIATQAHAAkJ7Bx3DQBDAgloDAAABwBXAGkMAAAGAEMAawwAAAYAVABqDAAAAwAzAGwMAAACAFMAbQwAAAEADADqDAAABwBcAG4MAAADAFcAbwwAAAIATQAGAAEJVAsuFQEqAAFoDAAAAQAcAAAA.Atzalan:BAABLgAECn8UAAIMAAYJpwnpcwD7AAZoDAAAAwAgAGkMAAAFAA0AawwAAAQAIABqDAAAAwARAGwMAAACAAwA6gwAAAMAKAAMAAYJpwnpcwD7AAZoDAAAAwAgAGkMAAAFAA0AawwAAAQAIABqDAAAAwARAGwMAAACAAwA6gwAAAMAKAAAAA==.',
Au='Automagic:BAAALgAECgEJAgAAAA==.',
Av='Avondwella:BAABLgAECn8rAAMNAAkJZw+sHABJAQloDAAAAwAzAGkMAAAGAC4AawwAAAYAOQBqDAAABgA0AGwMAAAGAC8AbQwAAAIAFADqDAAACgA7AG4MAAACABMAbwwAAAIADAANAAkJZw+sHABJAQloDAAAAwAzAGkMAAAGAC4AawwAAAYAOQBqDAAABgA0AGwMAAAGAC8AbQwAAAIAFADqDAAACQA7AG4MAAACABMAbwwAAAIADAAOAAEJ+wnERAAvAAHqDAAAAQAZAAAA.',
Az='Azrikam:BAAALgAECgYJCAAAAA==.',
Ba='Baku:BAAALgAECgYJBgABLgAFFAYJEgAHAJcVAA==.Baldyguy:BAAALgADCgcJCgAAAA==.Balm:BAABLgAECn8xAAIMAAkJCBrpIAA5AgloDAAABgA+AGkMAAAGAE0AawwAAAYARgBqDAAABQBDAGwMAAAHAFIAbQwAAAQAPwDqDAAACABWAG4MAAAFAC4AbwwAAAIAKwAMAAkJCBrpIAA5AgloDAAABgA+AGkMAAAGAE0AawwAAAYARgBqDAAABQBDAGwMAAAHAFIAbQwAAAQAPwDqDAAACABWAG4MAAAFAC4AbwwAAAIAKwAAAA==.Balton:BAAALgAECgIJAwAAAA==.Barbsimpsonn:BAAALgAECgEJAQAAAA==.Bashalot:BAAALgAECgUJBgAAAA==.',
Be='Beastcloud:BAAALgAECgIJAgABLgAECgkJJgAHAOwcAA==.Bermin:BAAALgADCgUJAwAAAA==.',
Bi='Biblepimp:BAAALgAFFAEJAQAAAA==.Bigwilliam:BAAALgADCgEJAQAAAA==.',
Bl='Blackmarker:BAABLgAECn8cAAICAAgJ/BSVWgCzAQhoDAAABgBGAGkMAAAFAEIAawwAAAUANgBqDAAAAwAnAGwMAAACAEUAbQwAAAIAJADqDAAABAAsAG8MAAABACIAAgAICfwUlVoAswEIaAwAAAYARgBpDAAABQBCAGsMAAAFADYAagwAAAMAJwBsDAAAAgBFAG0MAAACACQA6gwAAAQALABvDAAAAQAiAAAA.',
Bm='Bmo:BAABLgAECn8VAAIPAAcJZSB1SAAJAgdoDAAAAwBcAGkMAAAEAFQAawwAAAQAWgBqDAAAAgBMAGwMAAACAEIAbQwAAAEARgDqDAAABQBcAA8ABwllIHVIAAkCB2gMAAADAFwAaQwAAAQAVABrDAAABABaAGoMAAACAEwAbAwAAAIAQgBtDAAAAQBGAOoMAAAFAFwAAAA=.',
Bo='Bodyguardwyn:BAAALgAECgEJAQAAAA==.Bogle:BAACLgAFFH8FAAMPAAIJOQzJnQBwAAJoDAAAAwAlAOoMAAACABkADwACCVAFyZ0AcAACaAwAAAIAFwDqDAAAAQADABAAAgk5DA4IADYAAmgMAAABACUA6gwAAAEAGQAuAAQKfy8AAxAACQnYI4ECAAIDABAACQnYI4ECAAIDAA8AAwnyFn3bANsAAAAA.Bonedmuch:BAAALgAECgcJDQABLgAECgkJLgAIAGMWAA==.Bow:BAAALgAECgIJAwAAAA==.',
Br='Brasi:BAAALgAECgIJAgAAAA==.Bratton:BAABLgAECn8aAAIRAAcJ6wYAEwDUAAdoDAAABgAUAGkMAAAEABQAawwAAAQADwBqDAAAAgATAGwMAAADAA8AbQwAAAEACwDqDAAABgAWABEABwnrBgATANQAB2gMAAAGABQAaQwAAAQAFABrDAAABAAPAGoMAAACABMAbAwAAAMADwBtDAAAAQALAOoMAAAGABYAAAA=.Breadria:BAAALgAECgEJAgABLgAFFAMJBwASAH0FAA==.Bremitin:BAAALgADCggJCAABLgAECgkJMwAQALcPAA==.Bremitus:BAAALgADCgkJCQABLgAECgkJMwAQALcPAA==.Brewcrew:BAAALgAECgkJBwAAAA==.Brewey:BAAALgAFFAEJAQAAAA==.Brewmongster:BAAALgAECgQJBQAAAA==.Brimscythe:BAABLgAECn8bAAIGAAgJ5B+wNwAXAghoDAAABQBeAGkMAAAEAFMAawwAAAMARgBqDAAAAwBcAGwMAAADAFYAbQwAAAEAOgDqDAAABwBaAG8MAAABAFcABgAICeQfsDcAFwIIaAwAAAUAXgBpDAAABABTAGsMAAADAEYAagwAAAMAXABsDAAAAwBWAG0MAAABADoA6gwAAAcAWgBvDAAAAQBXAAAA.Brud:BAAALgAECgMJCwAAAA==.Brunstan:BAACLgAFFH8TAAITAAUJfh84EABTAQVoDAAABgBWAGkMAAAFAFwAawwAAAIAMwBqDAAAAQAdAOoMAAAFAFsAEwAFCX4fOBAAUwEFaAwAAAYAVgBpDAAABQBcAGsMAAACADMAagwAAAEAHQDqDAAABQBbAC4ABAp/GQACEwAJCeMghgIAvwIAEwAJCeMghgIAvwIAAAA=.',
Bu='Bubbastump:BAAALgAECgQJBAAAAA==.',
By='Byakugan:BAACLgAFFH8cAAMFAAgJKhN1BQCDAQhoDAAABgAzAGkMAAAGAEgAawwAAAQAIQBqDAAABAAjAGwMAAABAC4AbQwAAAEAMQDqDAAABQA7AG4MAAABAB0ABQAGCUcTdQUAgwEGaAwAAAYAMwBpDAAABgBIAGsMAAAEACEAagwAAAQAIwDqDAAABAA7AG4MAAABAB0AFAADCRIJo0YAxQADbAwAAAEAJwBtDAAAAQAYAOoMAAABAAUALgAECn8gAAQFAAkJLR+aDwCvAgAFAAkJLR+aDwCvAgAVAAEJvhe/KQBBAAAUAAEJBwEFqQAlAAAAAA==.',
['Bø']='Bønitalèè:BAABLgAECn8jAAIWAAgJiQnBjgBWAQhoDAAABgAUAGkMAAAGACsAawwAAAYAFQBqDAAAAwAOAGwMAAAEABYAbQwAAAEAEwDqDAAABwAPAG4MAAACABsAFgAICYkJwY4AVgEIaAwAAAYAFABpDAAABgArAGsMAAAGABUAagwAAAMADgBsDAAABAAWAG0MAAABABMA6gwAAAcADwBuDAAAAgAbAAAA.',
Ca='Cain:BAAALgADCgkJDwAAAA==.Calvisi:BAAALgAECgcJDgAAAA==.Calvisichaos:BAABLgAECn88AAIXAAkJhBdfBAAxAgloDAAACQBJAGkMAAAJAEcAawwAAAkAOgBqDAAACAApAGwMAAAHAC4AbQwAAAUAIQDqDAAACgBMAG4MAAACAEIAbwwAAAEANwAXAAkJhBdfBAAxAgloDAAACQBJAGkMAAAJAEcAawwAAAkAOgBqDAAACAApAGwMAAAHAC4AbQwAAAUAIQDqDAAACgBMAG4MAAACAEIAbwwAAAEANwAAAA==.Cantero:BAAALgADCgUJBQAAAA==.Canthen:BAAALgAECggJDwAAAA==.Carcarnisa:BAAALgAECgQJBgAAAA==.Carm:BAAALgAECgQJBAAAAA==.',
Ce='Cenobia:BAAALgADCgUJCQAAAA==.',
Ch='Chaire:BAAALgADCgcJBgAAAA==.Chrysophylax:BAAALgAECgYJBgAAAA==.',
Co='Conky:BAAALgAECgMJBgAAAA==.Corndog:BAAALgADCgEJAQAAAA==.Cornix:BAAALgADCgEJAQAAAA==.Cosmicspark:BAAALgAECgYJEgAAAA==.',
Cr='Crentist:BAAALgAECgEJAQAAAA==.Critoliz:BAAALgAFFAMJAQAAAA==.Cropala:BAABLgAECn8oAAIPAAkJCBVoOwAOAgloDAAABgA8AGkMAAAGAEAAawwAAAYAPABqDAAABAAwAGwMAAAFAEwAbQwAAAMAFwDqDAAABQA4AG4MAAADAD8AbwwAAAIAFwAPAAkJCBVoOwAOAgloDAAABgA8AGkMAAAGAEAAawwAAAYAPABqDAAABAAwAGwMAAAFAEwAbQwAAAMAFwDqDAAABQA4AG4MAAADAD8AbwwAAAIAFwAAAA==.Cruelcodex:BAAALgAECgEJAQAAAA==.',
['Cà']='Càtfish:BAAALgADCgEJAQAAAA==.',
Da='Daca:BAAALgADCgMJAwAAAA==.Darkrequiem:BAAALgADCgkJCwAAAA==.Darkwingduck:BAAALgAECgQJBQAAAA==.Dave:BAAALgADCgQJBAAAAA==.Davros:BAAALgAECgMJCAAAAA==.',
De='Decapitator:BAAALgAECgMJAwAAAA==.Dednburied:BAAALgAECgIJAgAAAA==.Deleto:BAABLgAECn8rAAMBAAgJDRVqDQCWAQhoDAAABgBLAGkMAAAGAD8AawwAAAgAMQBqDAAABgBRAGwMAAAFADoAbQwAAAEAEADqDAAACABAAG4MAAADADEAAQAICdgRag0AlgEIaAwAAAQARgBpDAAABAAxAGsMAAAEACwAagwAAAQAJgBsDAAABAAtAG0MAAABABAA6gwAAAIALQBuDAAAAwAxAAIABglgGOWQAD8BBmgMAAACAEsAaQwAAAIAPwBrDAAABAAxAGoMAAACAFEAbAwAAAEAOgDqDAAABgBAAAAA.Dellandre:BAABLgAECn8aAAIYAAgJQQufJwAPAQhoDAAABAAaAGkMAAAEAB8AawwAAAQAJQBqDAAAAwAyAGwMAAACACQAbQwAAAIABgDqDAAABgApAG4MAAABABUAGAAICUELnycADwEIaAwAAAQAGgBpDAAABAAfAGsMAAAEACUAagwAAAMAMgBsDAAAAgAkAG0MAAACAAYA6gwAAAYAKQBuDAAAAQAVAAEuAAQKCQk0ABAA2AoA.Delta:BAABLgAECn8XAAIGAAgJ+QfhggARAQhoDAAAAgAWAGkMAAAEACAAawwAAAQAFABqDAAAAwASAGwMAAAEABsAbQwAAAEACQDqDAAAAwAQAG4MAAACAA0ABgAICfkH4YIAEQEIaAwAAAIAFgBpDAAABAAgAGsMAAAEABQAagwAAAMAEgBsDAAABAAbAG0MAAABAAkA6gwAAAMAEABuDAAAAgANAAAA.Delti:BAAALgAECgUJBgABLgAECgkJHwAGAFcWAA==.Demondozer:BAAALgAECgMJBAABLgAECgUJCQAEAAAAAA==.Demony:BAAALgAECgEJAQABLgAFFAEJAQAEAAAAAA==.Denard:BAAALgAECgUJBgAAAA==.',
Di='Diabolist:BAACLgAFFH8FAAIDAAIJ+gZFpAB+AAJoDAAAAgAUAOoMAAADAA4AAwACCfoGRaQAfgACaAwAAAIAFADqDAAAAwAOAC4ABAp/GAACAwAJCWAIvWYAbAEAAwAJCWAIvWYAbAEAAAA=.Digichowder:BAACLgAFFH8PAAMZAAQJTyBTHAA2AQRoDAAABQBXAGkMAAAEAF8AawwAAAEANADqDAAABQBeABkAAwk9JFMcADYBA2gMAAAFAFcAaQwAAAQAXwDqDAAABQBeAA4AAQmGFFo7AEgAAWsMAAABADQALgAECn8mAAMOAAkJsSPwAwDfAgAOAAgJDiHwAwDfAgAZAAUJjR7kNwBkAQAAAA==.Dirtygiri:BAAALgADCgEJAgAAAA==.',
Do='Doktaga:BAAALgAECgYJDgAAAA==.',
Dr='Draex:BAAALgADCgEJAQAAAA==.Dragonzord:BAAALgADCgEJAQAAAA==.Drbubbles:BAAALgADCgYJCAABLgAECgQJCQAEAAAAAA==.Drredd:BAAALgAECgQJBAAAAA==.',
['Dä']='Därkrävèn:BAAALgAECgYJDAAAAA==.',
Ea='Eama:BAAALgADCgIJAwAAAA==.',
Ed='Edin:BAAALgAECgcJBwABLgAFFAUJGQAKAD4QAA==.',
Eg='Eggfield:BAAALgAECgUJBgAAAA==.',
El='Eladora:BAAALgADCgEJAQAAAA==.Eldarr:BAABLgAECn83AAMXAAkJaCE2AQDhAgloDAAACABcAGkMAAAIAFkAawwAAAgAVwBqDAAABQBFAGwMAAAHAFcAbQwAAAQAWADqDAAACABiAG4MAAAFAEQAbwwAAAIARwAXAAkJaCE2AQDhAgloDAAABwBcAGkMAAAHAFkAawwAAAcAVwBqDAAABQBFAGwMAAAHAFcAbQwAAAQAWADqDAAACABiAG4MAAACAEQAbwwAAAEARwADAAUJ+hG3iQAkAQVoDAAAAQAIAGkMAAABAEgAawwAAAEARQBuDAAAAwA3AG8MAAABABcAAAA=.Eldhe:BAAALgAECgYJDwAAAA==.Eleos:BAAALgADCgMJBgAAAA==.Elistrae:BAABLgAECn8fAAMaAAkJ2RWcGADbAQloDAAAAwA7AGkMAAAFADgAawwAAAUATQBqDAAABAA2AGwMAAADAD0AbQwAAAIALwDqDAAABgA5AG4MAAACADYAbwwAAAEAIAAaAAkJlQycGADbAQloDAAAAQAQAGkMAAACACQAawwAAAIAOQBqDAAAAQAkAGwMAAABABUAbQwAAAEACQDqDAAAAQA1AG4MAAABAB0AbwwAAAEAIAATAAgJKRc0MwCgAQhoDAAAAgA7AGkMAAADADgAawwAAAMATQBqDAAAAwA2AGwMAAACAD0AbQwAAAEALwDqDAAABQA5AG4MAAABADYAAAA=.',
Em='Emorri:BAAALgAECgYJBgAAAA==.',
En='Enazen:BAABLgAECn8fAAILAAkJWRpBBQC+AgloDAAABQBIAGkMAAAFAFcAawwAAAUAQQBqDAAAAwBIAGwMAAADADgAbQwAAAMATgDqDAAABABUAG4MAAACADQAbwwAAAEAJAALAAkJWRpBBQC+AgloDAAABQBIAGkMAAAFAFcAawwAAAUAQQBqDAAAAwBIAGwMAAADADgAbQwAAAMATgDqDAAABABUAG4MAAACADQAbwwAAAEAJAAAAA==.Endlol:BAABLgAECn8vAAMbAAkJFyEeCADLAgloDAAABwBhAGkMAAAGAFYAawwAAAUAVQBqDAAABgBdAGwMAAAFAFMAbQwAAAQATwDqDAAACABVAG4MAAAFAFMAbwwAAAEASwAbAAkJFyEeCADLAgloDAAABwBhAGkMAAAGAFYAawwAAAUAVQBqDAAABgBdAGwMAAAFAFMAbQwAAAEATwDqDAAACABVAG4MAAAFAFMAbwwAAAEASwAcAAEJUh/SXwBTAAFtDAAAAwBQAAEuAAUUAgkDAAQAAAAA.',
Er='Eredaria:BAAALgAFFAEJAQAAAA==.Ereshkigal:BAAALgADCgYJCwAAAA==.Ergo:BAACLgAFFH8ZAAIWAAgJ7RDsGAAZAghoDAAABgBJAGkMAAACADMAawwAAAMAMQBqDAAABAAnAGwMAAABADgAbQwAAAEACgDqDAAABwA5AG4MAAABAAQAFgAICe0Q7BgAGQIIaAwAAAYASQBpDAAAAgAzAGsMAAADADEAagwAAAQAJwBsDAAAAQA4AG0MAAABAAoA6gwAAAcAOQBuDAAAAQAEAC4ABAp/JgACFgAJCa4iGyMA5gIAFgAJCa4iGyMA5gIAAAA=.Eronel:BAABLgAECn8eAAICAAcJ7Rp1ZQCYAQdoDAAABgA/AGkMAAAEAFEAawwAAAQAPwBqDAAABABaAGwMAAAEAEoAbQwAAAMANADqDAAABQBNAAIABwntGnVlAJgBB2gMAAAGAD8AaQwAAAQAUQBrDAAABAA/AGoMAAAEAFoAbAwAAAQASgBtDAAAAwA0AOoMAAAFAE0AAAA=.',
Es='Esv:BAABLgAFFH8HAAINAAMJ3we0IACEAANoDAAABAAkAGkMAAABAAsA6gwAAAIADAANAAMJ3we0IACEAANoDAAABAAkAGkMAAABAAsA6gwAAAIADAABLgAFFAQJGQAWACgUAA==.',
Ex='Excido:BAAALgAECgEJAgAAAA==.Exodiagold:BAAALgAECgEJAQAAAA==.',
Fa='Fadedharanir:BAAALgAECgIJAwAAAA==.Fadedheart:BAAALgAECgQJBwABLgAECgkJNAACAPIfAA==.Fadedmystic:BAAALgAECgQJBAAAAA==.Fadednight:BAABLgAECn80AAMCAAkJ8h8bFwC4AgloDAAABwBeAGkMAAAHAFYAawwAAAYAWwBqDAAABQBTAGwMAAAHAFcAbQwAAAQATQDqDAAACQBhAG4MAAAFADwAbwwAAAIAOwACAAkJ8h8bFwC4AgloDAAABwBeAGkMAAAHAFYAawwAAAYAWwBqDAAABQBTAGwMAAAHAFcAbQwAAAQATQDqDAAACABhAG4MAAAFADwAbwwAAAIAOwAYAAEJ1QG6aQARAAHqDAAAAQAEAAAA.Faeyir:BAACLgAFFH8TAAIWAAQJIA93XQAqAQRoDAAABgA+AGkMAAAFABYAawwAAAMAMgDqDAAABQATABYABAkgD3ddACoBBGgMAAAGAD4AaQwAAAUAFgBrDAAAAwAyAOoMAAAFABMALgAECn8iAAIWAAkJwx0/UABGAgAWAAkJwx0/UABGAgAAAA==.Fallingmoon:BAABLgAECn8nAAMSAAkJqCA5DgDZAgloDAAABgBWAGkMAAAFAFwAawwAAAUAUABqDAAABABXAGwMAAAEAFIAbQwAAAMAOQDqDAAABgBVAG4MAAAEAF4AbwwAAAIAWQASAAkJqCA5DgDZAgloDAAABQBWAGkMAAAFAFwAawwAAAUAUABqDAAABABXAGwMAAAEAFIAbQwAAAMAOQDqDAAABgBVAG4MAAAEAF4AbwwAAAIAWQATAAEJKRDmigAwAAFoDAAAAQApAAAA.Fangrage:BAAALgAECgYJBAAAAA==.Fatherlode:BAACLgAFFH8KAAIWAAMJwBg3ewDgAANoDAAABgBJAGkMAAABAD0A6gwAAAMANgAWAAMJwBg3ewDgAANoDAAABgBJAGkMAAABAD0A6gwAAAMANgAuAAQKfysAAhYACQmUIfEbAK8CABYACQmUIfEbAK8CAAAA.',
Fe='Feltpen:BAAALgAECgUJBQAAAA==.Femcelibate:BAAALgADCgcJCAAAAA==.Fentenjoyer:BAAALgAECgcJDwAAAA==.Fernfondler:BAAALgAFFAIJAwAAAA==.',
Fl='Flashylights:BAAALgADCgYJBgAAAA==.',
Fo='Fontane:BAAALgADCgYJBwAAAA==.Forcebolt:BAAALgADCgMJAwAAAA==.',
Fr='Fredgoffin:BAAALgAECgIJAgAAAA==.Freecookies:BAAALgAECgYJCQAAAA==.Frostybop:BAAALgAECgMJBAABLgAECgIJAgAEAAAAAA==.Frostybreath:BAAALgAECgIJAgAAAA==.Frostybrews:BAAALgAECgEJAQABLgAECgIJAgAEAAAAAA==.Frostydh:BAAALgAECgMJAwABLgAECgIJAgAEAAAAAA==.Frostytotems:BAAALgAECgQJBgAAAA==.Fróstblight:BAAALgAECgkJCAAAAA==.',
Fu='Furryiosa:BAAALgADCgYJBgAAAA==.',
Ga='Gauntodimm:BAAALgAECgYJCgAAAA==.',
Gi='Gilberticus:BAAALgAECgYJEwABLgAECgkJTgAdAMUiAA==.Gishmou:BAABLgAECn8fAAIUAAkJwRiuJAApAgloDAAABQBdAGkMAAAEAFAAawwAAAQAVwBqDAAABAAuAGwMAAADACQAbQwAAAEAOwDqDAAABgBOAG4MAAADAEkAbwwAAAEADgAUAAkJwRiuJAApAgloDAAABQBdAGkMAAAEAFAAawwAAAQAVwBqDAAABAAuAGwMAAADACQAbQwAAAEAOwDqDAAABgBOAG4MAAADAEkAbwwAAAEADgAAAA==.',
Go='Goldblade:BAABLgAECn8gAAIPAAgJWhdqUADQAQhoDAAABAA1AGkMAAAEADsAawwAAAQALgBqDAAABQBSAGwMAAAFAEIAbQwAAAEAHADqDAAABQBSAG4MAAAEAFEADwAICVoXalAA0AEIaAwAAAQANQBpDAAABAA7AGsMAAAEAC4AagwAAAUAUgBsDAAABQBCAG0MAAABABwA6gwAAAUAUgBuDAAABABRAAAA.',
Gr='Grayhair:BAAALgAECgQJCAAAAA==.Greyoll:BAAALgAECgYJCAAAAA==.Grimling:BAAALgAFFAEJAQABLgAFFAYJEgAHAJcVAA==.Grindlewald:BAAALgAECgIJAgAAAA==.',
Gu='Gutted:BAACLgAFFH8gAAMYAAgJCyO0AgCEAghoDAAABwBgAGkMAAAGAGEAawwAAAQAYQBqDAAABABaAGwMAAABAFUAbQwAAAEAWADqDAAACABiAG4MAAABAEAAGAAICQsjtAIAhAIIaAwAAAcAYABpDAAABgBhAGsMAAAEAGEAagwAAAQAWgBsDAAAAQBVAG0MAAABAFgA6gwAAAcAYgBuDAAAAQBAAAIAAQnFDIIFAUAAAeoMAAABACAALgAECn8dAAIYAAkJGSa9AQBnAwAYAAkJGSa9AQBnAwAAAA==.',
['Gä']='Gärin:BAAALgADCggJFAAAAA==.',
Ha='Hanna:BAAALgAFFAEJAQABLgAFFAgJIAAYAAsjAA==.Harleyswar:BAAALgADCgEJAQAAAA==.',
He='Hellmaw:BAAALgAECgYJCwAAAA==.',
Hi='Highly:BAAALgADCgcJCwAAAA==.',
Ho='Holianna:BAAALgAECgIJAgAAAA==.Hollowheart:BAABLgAECn8vAAIUAAkJjhixIQA8AgloDAAABwBCAGkMAAAGAC0AawwAAAYAOwBqDAAABQBLAGwMAAAFAE4AbQwAAAQANwDqDAAABgBPAG4MAAAFAEYAbwwAAAMAIgAUAAkJjhixIQA8AgloDAAABwBCAGkMAAAGAC0AawwAAAYAOwBqDAAABQBLAGwMAAAFAE4AbQwAAAQANwDqDAAABgBPAG4MAAAFAEYAbwwAAAMAIgAAAA==.Holycourtney:BAAALgADCgkJEQAAAA==.Holyknight:BAAALgADCgEJAQAAAA==.Hotsausage:BAAALgAECgMJAwAAAA==.Hoved:BAAALgADCgEJAQAAAA==.',
Hu='Huang:BAAALgAECgMJAwAAAA==.',
Hy='Hylanna:BAAALgAECgYJCgAAAA==.Hyorinmaru:BAAALgAFFAEJAgAAAA==.',
['Hó']='Hónor:BAAALgADCgMJAwABLgAECgkJMwAQALcPAA==.',
Ic='Ici:BAABLgAECn8zAAMPAAkJAAhrhABfAQloDAAACQATAGkMAAAIABYAawwAAAgAGQBqDAAABgAkAGwMAAAGABsAbQwAAAIADADqDAAACQAWAG4MAAACAA4AbwwAAAEAEwAPAAkJAAhrhABfAQloDAAACAATAGkMAAAHABYAawwAAAcAGQBqDAAABQAkAGwMAAAGABsAbQwAAAIADADqDAAACQAWAG4MAAACAA4AbwwAAAEAEwAJAAQJuA63WgDDAARoDAAAAQAjAGkMAAABAA8AawwAAAEAMwBqDAAAAQAwAAAA.',
If='Iffybacon:BAAALgAECgIJAgABLgAECgQJCwAEAAAAAA==.',
Ik='Ikilledkeny:BAAALgAFFAMJAQAAAA==.',
Im='Imlerith:BAAALgADCgQJBgAAAA==.',
In='Intensifies:BAAALgAECgcJEgAAAA==.',
Ip='Ippo:BAAALgADCgEJAQAAAA==.',
Is='Isabellà:BAAALgAECggJDAABLgAECgkJJwAeAL4MAA==.Iskothar:BAABLgAECn8xAAIQAAkJQSF/AgACAwloDAAABgBRAGkMAAAGAFwAawwAAAYAXABqDAAABgBZAGwMAAAHAFwAbQwAAAUASgDqDAAACABOAG4MAAAEAFEAbwwAAAEAVwAQAAkJQSF/AgACAwloDAAABgBRAGkMAAAGAFwAawwAAAYAXABqDAAABgBZAGwMAAAHAFwAbQwAAAUASgDqDAAACABOAG4MAAAEAFEAbwwAAAEAVwAAAA==.',
Iv='Ivarboneless:BAABLgAECn8UAAIJAAYJgSFSGQA0AgZoDAAABABaAGkMAAAEAFYAawwAAAUASQBqDAAAAQBQAGwMAAADAF0A6gwAAAMAWgAJAAYJgSFSGQA0AgZoDAAABABaAGkMAAAEAFYAawwAAAUASQBqDAAAAQBQAGwMAAADAF0A6gwAAAMAWgAAAA==.',
Ja='Jackz:BAAALgAECgkJCQAAAA==.Jackzlock:BAAALgAECgkJAQAAAA==.Jakethemage:BAAALgADCgUJCAAAAA==.Jankball:BAAALgAFFAMJAQAAAA==.Jatkal:BAAALgAECgkJEQAAAA==.Jayreezy:BAAALgAECgMJAwAAAA==.',
Je='Jefftrep:BAAALgAECgQJAwAAAA==.Jerihatrix:BAAALgAECgEJAQAAAA==.',
Ji='Jimmylahey:BAAALgAECgMJAwAAAA==.',
Jo='Jonah:BAAALgADCgEJAQAAAA==.',
Ka='Kaina:BAAALgADCgYJCQAAAA==.Kakidruid:BAAALgAECgIJAwAAAA==.Kalfu:BAABLgAECn8UAAMbAAkJygyXKACEAQloDAAAAgAsAGkMAAACAAMAawwAAAIAHgBqDAAAAgATAGwMAAACABwAbQwAAAIAJgDqDAAAAwAMAG4MAAACADMAbwwAAAMANAAbAAkJygyXKACEAQloDAAAAQAsAGkMAAABAAMAawwAAAEAHgBqDAAAAQATAGwMAAABABwAbQwAAAEAJgDqDAAAAQAMAG4MAAACADMAbwwAAAIANAAfAAgJFwnILgBeAQhoDAAAAQAGAGkMAAABABUAawwAAAEAKABqDAAAAQACAGwMAAABABgAbQwAAAEAOADqDAAAAgAPAG8MAAABABIAAAA=.',
Ke='Ketesh:BAABLgAECn88AAIgAAkJzSA7AwDvAgloDAAACQBdAGkMAAAHAFwAawwAAAYAWwBqDAAACABXAGwMAAAHAFkAbQwAAAUATgDqDAAACgBVAG4MAAAHAFMAbwwAAAEAOgAgAAkJzSA7AwDvAgloDAAACQBdAGkMAAAHAFwAawwAAAYAWwBqDAAACABXAGwMAAAHAFkAbQwAAAUATgDqDAAACgBVAG4MAAAHAFMAbwwAAAEAOgABLgAFFAUJGQAKAD4QAA==.',
Ki='Kilorean:BAAALgAECgcJCAAAAA==.Kirae:BAAALgADCgkJGQABLgAECgkJMQAQAEEhAA==.',
Kl='Kleanse:BAAALgAFFAMJAQAAAA==.',
Kn='Knastey:BAABLgAECn8VAAQeAAYJ4BdPNAA9AQZoDAAAAwBBAGkMAAADADoAawwAAAIARABqDAAABQBEAGwMAAADADoA6gwAAAUANwAeAAYJ4BdPNAA9AQZoDAAAAQBBAGkMAAABADoAawwAAAEARABqDAAABABEAGwMAAACADoA6gwAAAEANwAMAAYJZAqbcQABAQZoDAAAAgAZAGkMAAACAC8AawwAAAEACQBqDAAAAQAcAGwMAAABABYA6gwAAAIAGQAhAAEJWxKCMgA3AAHqDAAAAgAuAAAA.Knasty:BAAALgADCgEJAQAAAA==.',
Ko='Kodera:BAABLgAECn8gAAIKAAYJQQWVYwClAAZoDAAACAALAGkMAAAHABkAawwAAAYACQBqDAAABAASAGwMAAACAAgA6gwAAAUADAAKAAYJQQWVYwClAAZoDAAACAALAGkMAAAHABkAawwAAAYACQBqDAAABAASAGwMAAACAAgA6gwAAAUADAAAAA==.',
Kr='Krej:BAABLgAECn8XAAIYAAkJMBxgDgAdAgloDAAAAwBEAGkMAAADAFYAawwAAAIAQgBqDAAAAQBDAGwMAAABADEAbQwAAAIATQDqDAAAAwBNAG4MAAAEAEcAbwwAAAQAUAAYAAkJMBxgDgAdAgloDAAAAwBEAGkMAAADAFYAawwAAAIAQgBqDAAAAQBDAGwMAAABADEAbQwAAAIATQDqDAAAAwBNAG4MAAAEAEcAbwwAAAQAUAABLgAFFAYJEgAHAJcVAA==.Krisskringle:BAAALgAECgMJBgAAAA==.',
Ku='Kuromori:BAAALgADCgYJBgAAAA==.',
Ky='Kyronix:BAAALgAECgMJBwAAAA==.',
['Kê']='Kênpachi:BAAALgAECgYJDgAAAA==.',
La='Landrey:BAAALgADCgkJCQAAAA==.Langarde:BAABLgAECn8fAAINAAkJCxDlFQCQAQloDAAABQAuAGkMAAAFADYAawwAAAUAMQBqDAAAAwAoAGwMAAADADAAbQwAAAMAIgDqDAAABAAeAG4MAAACACMAbwwAAAEAHQANAAkJCxDlFQCQAQloDAAABQAuAGkMAAAFADYAawwAAAUAMQBqDAAAAwAoAGwMAAADADAAbQwAAAMAIgDqDAAABAAeAG4MAAACACMAbwwAAAEAHQAAAA==.Laoghaire:BAABLgAECn8YAAIHAAcJ+AM9PwCsAAdoDAAABQAIAGkMAAAFAA8AawwAAAQACwBqDAAAAwALAGwMAAACAAgAbQwAAAEACADqDAAABAAJAAcABwn4Az0/AKwAB2gMAAAFAAgAaQwAAAUADwBrDAAABAALAGoMAAADAAsAbAwAAAIACABtDAAAAQAIAOoMAAAEAAkAAAA=.',
Le='Leonz:BAACLgAFFH8bAAIZAAgJDhuPAgBRAghoDAAABQBSAGkMAAAFAFsAawwAAAMAXwBqDAAABABXAGwMAAABAFQAbQwAAAEAMQDqDAAABwA8AG4MAAABABMAGQAICQ4bjwIAUQIIaAwAAAUAUgBpDAAABQBbAGsMAAADAF8AagwAAAQAVwBsDAAAAQBUAG0MAAABADEA6gwAAAcAPABuDAAAAQATAC4ABAp/LgACGQAJCZoksQQAFgMAGQAJCZoksQQAFgMAAAA=.Leonzs:BAAALgAECggJEAAAAA==.Letharanos:BAEBLgAECn8nAAMCAAkJdBnDQAD9AQloDAAABgBEAGkMAAAFAFYAawwAAAQAPwBqDAAABQBIAGwMAAAFAEwAbQwAAAMATgDqDAAABgBCAG4MAAAEADQAbwwAAAEAHQACAAkJdBnDQAD9AQloDAAABgBEAGkMAAAFAFYAawwAAAQAPwBqDAAABQBIAGwMAAAFAEwAbQwAAAMATgDqDAAABQBCAG4MAAAEADQAbwwAAAEAHQAYAAEJew4JXQApAAHqDAAAAQAlAAAA.',
Li='Liraffemynn:BAACLgAFFH8TAAIiAAUJiBe5HABtAQVoDAAABgBHAGkMAAAFAFgAawwAAAIAPwBqDAAAAQAKAOoMAAAFAEMAIgAFCYgXuRwAbQEFaAwAAAYARwBpDAAABQBYAGsMAAACAD8AagwAAAEACgDqDAAABQBDAC4ABAp/PgACIgAJCY4jfwMAfAMAIgAJCY4jfwMAfAMAAAA=.Liralynn:BAAALgADCgUJBQAAAA==.',
Lk='Lkynyx:BAAALgADCgYJAQAAAA==.',
Lo='Lonranir:BAAALgAECgYJCwAAAA==.Lostinlight:BAAALgAECgYJBgAAAA==.',
Lu='Lucii:BAAALgADCgEJAQABLgAFFAgJIAAYAAsjAA==.Luckylucy:BAABLgAECn8XAAIcAAYJhhb5LABbAQZoDAAABQBVAGkMAAAFABUAawwAAAMANQBqDAAAAgA0AGwMAAADAEMA6gwAAAUAQQAcAAYJhhb5LABbAQZoDAAABQBVAGkMAAAFABUAawwAAAMANQBqDAAAAgA0AGwMAAADAEMA6gwAAAUAQQAAAA==.',
Ma='Madarauchiha:BAABLgAECn8ZAAICAAYJpBpwggB+AQZoDAAACwBQAGkMAAAFAFUAawwAAAIALQBqDAAAAQBOAGwMAAABACoA6gwAAAUAVwACAAYJpBpwggB+AQZoDAAACwBQAGkMAAAFAFUAawwAAAIALQBqDAAAAQBOAGwMAAABACoA6gwAAAUAVwAAAA==.Magus:BAAALgADCgkJEQABLgAECgMJCAAEAAAAAA==.Maldran:BAABLgAECn8jAAIUAAcJjh3sKAARAgdoDAAABgBGAGkMAAAGAE0AawwAAAYAUABqDAAABQBSAGwMAAAEAFUAbQwAAAMARADqDAAABQBBABQABwmOHewoABECB2gMAAAGAEYAaQwAAAYATQBrDAAABgBQAGoMAAAFAFIAbAwAAAQAVQBtDAAAAwBEAOoMAAAFAEEAAAA=.Maling:BAAALgAECgEJAQAAAA==.Manderpants:BAABLgAECn8fAAISAAcJCApYfQA8AQdoDAAABgAgAGkMAAAGABgAawwAAAYAIQBqDAAABAAjAGwMAAADABMA6gwAAAQAFQBuDAAAAgAVABIABwkIClh9ADwBB2gMAAAGACAAaQwAAAYAGABrDAAABgAhAGoMAAAEACMAbAwAAAMAEwDqDAAABAAVAG4MAAACABUAAAA=.Marien:BAABLgAECn8fAAIYAAkJHBmsDAA5AgloDAAABQA5AGkMAAAFAEoAawwAAAUAQQBqDAAAAwBCAGwMAAADAFEAbQwAAAMAOwDqDAAABABKAG4MAAACADIAbwwAAAEAMQAYAAkJHBmsDAA5AgloDAAABQA5AGkMAAAFAEoAawwAAAUAQQBqDAAAAwBCAGwMAAADAFEAbQwAAAMAOwDqDAAABABKAG4MAAACADIAbwwAAAEAMQAAAA==.Marty:BAAALgAECgIJAwAAAA==.Maxus:BAAALgADCgUJBQAAAA==.',
Mb='Mbbin:BAACLgAFFH8LAAIWAAMJFyVaTgBCAQNoDAAABgBiAGkMAAAEAFkA6gwAAAEAYAAWAAMJFyVaTgBCAQNoDAAABgBiAGkMAAAEAFkA6gwAAAEAYAAuAAQKfygAAhYACQmmIRweAKMCABYACQmmIRweAKMCAAAA.',
Me='Mehuman:BAABLgAECn8VAAIPAAYJ6Q0PvQAEAQZoDAAABQA1AGkMAAAFACwAawwAAAYAIQBqDAAAAQAtAGwMAAABABYA6gwAAAMAFwAPAAYJ6Q0PvQAEAQZoDAAABQA1AGkMAAAFACwAawwAAAYAIQBqDAAAAQAtAGwMAAABABYA6gwAAAMAFwAAAA==.Mehumanhuntr:BAAALgAECgUJBgAAAA==.Mehumanlock:BAABLgAECn8jAAIXAAkJ+xFLCQCoAQloDAAABQBIAGkMAAAEACwAawwAAAQAJQBqDAAABAAqAGwMAAAGACoAbQwAAAIAHwDqDAAABgBAAG4MAAADAB8AbwwAAAEAKgAXAAkJ+xFLCQCoAQloDAAABQBIAGkMAAAEACwAawwAAAQAJQBqDAAABAAqAGwMAAAGACoAbQwAAAIAHwDqDAAABgBAAG4MAAADAB8AbwwAAAEAKgAAAA==.Merlinn:BAAALgADCgkJCwAAAA==.Merran:BAAALgADCgEJAQAAAA==.Metal:BAAALgADCgQJBAAAAA==.Meworgendk:BAAALgAECgYJDgAAAA==.',
Mh='Mhoo:BAAALgADCgcJBwAAAA==.',
Mi='Miriym:BAAALgADCgEJAQAAAA==.Miräj:BAAALgAECgcJDAAAAA==.Mistyblue:BAAALgADCgEJAQAAAA==.Miya:BAAALgADCgcJDQAAAA==.',
Mo='Moonscale:BAAALgAECgMJBAAAAA==.Mordaci:BAAALgADCgQJBQABLgAFFAEJAQAEAAAAAA==.Mordekrieg:BAAALgAFFAMJBAAAAA==.Mortstan:BAAALgAECgcJDQAAAA==.',
My='Myash:BAAALgAECgcJBgAAAA==.',
['Må']='Månni:BAAALgADCgYJBwAAAA==.',
['Mé']='Mélusine:BAAALgADCgEJAQAAAA==.',
Na='Nailia:BAAALgAECgUJCQAAAA==.Nailz:BAABLgAECn8fAAIGAAkJVxaJTACXAQloDAAABQBeAGkMAAAEADsAawwAAAQAKwBqDAAABAAzAGwMAAADADAAbQwAAAEAKQDqDAAABgA0AG4MAAADAEoAbwwAAAEAKwAGAAkJVxaJTACXAQloDAAABQBeAGkMAAAEADsAawwAAAQAKwBqDAAABAAzAGwMAAADADAAbQwAAAEAKQDqDAAABgA0AG4MAAADAEoAbwwAAAEAKwAAAA==.Nakama:BAAALgADCgYJBgABLgAECgkJNAAFAJgMAA==.Nardog:BAAALgAECgEJAQAAAA==.Narie:BAAALgAECggJCQAAAA==.Nasaug:BAAALgAECgUJCwABLgAECgkJMwAQALcPAA==.',
Ne='Ned:BAAALgAECgEJAQAAAA==.Neuse:BAAALgAECggJEwAAAA==.',
Ni='Nightlion:BAABLgAECn8YAAIgAAYJiw9oLwDgAAZoDAAABQAyAGkMAAAFADQAawwAAAYAGQBqDAAAAQASAGwMAAADACkA6gwAAAQAHQAgAAYJiw9oLwDgAAZoDAAABQAyAGkMAAAFADQAawwAAAYAGQBqDAAAAQASAGwMAAADACkA6gwAAAQAHQAAAA==.Nillius:BAAALgADCgIJAgAAAA==.Nisu:BAAALgAECgEJAQAAAA==.',
No='Noahdh:BAAALgAECgMJAwABLgAFFAgJHwADABAYAA==.Noahpriest:BAAALgAECgMJAwABLgAFFAgJHwADABAYAA==.Noahvoker:BAAALgAECggJEQABLgAFFAgJHwADABAYAA==.Noahwarlock:BAACLgAFFH8fAAQDAAgJEBjfGwDLAQhoDAAABgBhAGkMAAAHAF8AawwAAAQAHABqDAAAAwA6AGwMAAABAFgAbQwAAAEAGwDqDAAACABWAG4MAAABAAYAAwAGCU4d3xsAywEGaAwAAAYAYQBpDAAABgBfAGoMAAADADoAbAwAAAEAWADqDAAABQBWAG4MAAABAAYAFwADCV8RJgoA7QADawwAAAQAHABtDAAAAQAbAOoMAAADAE0AIwABCZEj9B0AUgABaQwAAAEAWwAuAAQKfzEABAMACQmFJIUEAEQDAAMACAlsJIUEAEQDABcABAl0IkEaAHsBACMAAwmsI4IWAM0AAAAA.Nonsensical:BAAALgADCgUJBQABLgAECgYJIgAiAEYiAA==.Nook:BAAALgADCgUJBgAAAA==.Nowere:BAAALgADCgcJBwAAAA==.Noxander:BAAALgAECgEJAQAAAA==.',
Ny='Nym:BAAALgAECgkJEQAAAA==.',
['Nâ']='Nârenth:BAAALgADCgMJAwAAAA==.',
Oa='Oaths:BAAALgAECgcJEQAAAA==.',
Oh='Ohmylantä:BAABLgAECn8dAAIWAAgJPg35hQBnAQhoDAAABAAmAGkMAAAEADQAawwAAAQAJgBqDAAABAAeAGwMAAAEACYAbQwAAAEADQDqDAAABQAmAG4MAAADABEAFgAICT4N+YUAZwEIaAwAAAQAJgBpDAAABAA0AGsMAAAEACYAagwAAAQAHgBsDAAABAAmAG0MAAABAA0A6gwAAAUAJgBuDAAAAwARAAAA.Ohmylantå:BAAALgADCgUJCAAAAA==.',
On='Ondeane:BAAALgADCgEJAQAAAA==.Onumae:BAABLgAECn8XAAIPAAkJcRp1LwA7AgloDAAAAgBfAGkMAAACAAIAawwAAAIAUgBqDAAAAwBXAGwMAAADADUAbQwAAAEAMQDqDAAABgBbAG4MAAADAFMAbwwAAAEAUQAPAAkJcRp1LwA7AgloDAAAAgBfAGkMAAACAAIAawwAAAIAUgBqDAAAAwBXAGwMAAADADUAbQwAAAEAMQDqDAAABgBbAG4MAAADAFMAbwwAAAEAUQAAAA==.',
Op='Oprime:BAAALgADCgMJAwAAAA==.',
Or='Orbeck:BAAALgAECggJCAABLgAFFAgJHQAIAIocAA==.Ormond:BAABLgAECn8cAAMJAAcJbRSFKQC7AQdoDAAABQBAAGkMAAAFAEYAawwAAAUAKQBqDAAABAA9AGwMAAAFAEMA6gwAAAMAEQBuDAAAAQArAAkABwltFIUpALsBB2gMAAAEAEAAaQwAAAQARgBrDAAABAApAGoMAAADAD0AbAwAAAUAQwDqDAAAAgARAG4MAAABACsADwAFCTwFRRMBlwAFaAwAAAEADwBpDAAAAQAPAGsMAAABAAkAagwAAAEADgDqDAAAAQAMAAAA.Orochinchin:BAAALgAECgUJBQABLgAFFAgJIAAYAAsjAA==.',
Os='Oscarmike:BAAALgADCgcJDQAAAA==.',
Oz='Ozlon:BAAALgAECgcJEwAAAA==.',
['Oâ']='Oâth:BAABLgAECn8nAAMkAAkJdgzEDwBGAQloDAAABQApAGkMAAAEADEAawwAAAUAHwBqDAAABQAnAGwMAAAGAC8AbQwAAAIABQDqDAAABgAnAG4MAAADABUAbwwAAAMAEQAkAAkJdgzEDwBGAQloDAAABQApAGkMAAAEADEAawwAAAUAHwBqDAAABAAnAGwMAAAFAC8AbQwAAAIABQDqDAAABQAnAG4MAAADABUAbwwAAAMAEQAHAAMJRgYDYABCAANqDAAAAQAGAGwMAAABAAkA6gwAAAEAFgAAAA==.',
Pa='Pachane:BAAALgAECgQJCwAAAA==.Paldozer:BAAALgAECgUJCQABLgAECgUJCQAEAAAAAA==.Pallywacker:BAABLgAECn8xAAIQAAgJ2hLTEwCGAQhoDAAACQA+AGkMAAAIADUAawwAAAcAIgBqDAAABwAnAGwMAAAGABsAbQwAAAMAJwDqDAAABwBSAG4MAAACACYAEAAICdoS0xMAhgEIaAwAAAkAPgBpDAAACAA1AGsMAAAHACIAagwAAAcAJwBsDAAABgAbAG0MAAADACcA6gwAAAcAUgBuDAAAAgAmAAAA.Pankins:BAAALgAECgMJAwAAAA==.Panzerkan:BAAALgAECgEJAQAAAA==.Panzerkìn:BAAALgAECgcJCAAAAA==.',
Pe='Percymorris:BAAALgADCgYJBwAAAA==.Peythilly:BAAALgAECgQJBAAAAA==.',
Pi='Pigishdog:BAABLgAECn9RAAMDAAkJ/hymFQCeAgloDAAADQBeAGkMAAALAFMAawwAAAsAPQBqDAAACgBMAGwMAAAIAFMAbQwAAAUASgDqDAAADgBUAG4MAAAIADIAbwwAAAEAPAADAAkJ/hymFQCeAgloDAAADQBeAGkMAAALAFMAawwAAAoAPQBqDAAACgBMAGwMAAAIAFMAbQwAAAUASgDqDAAADgBUAG4MAAAIADIAbwwAAAEAPAAXAAEJ1REWOwA3AAFrDAAAAQAtAAAA.Pikon:BAAALgADCgkJDQAAAA==.',
Po='Pokeabear:BAAALgAECgYJEAABLgAECgcJEAAEAAAAAA==.Pokethedruid:BAAALgAECgEJAQABLgAECgEJBwAEAAAAAA==.Pokethemonk:BAAALgAECgEJBwAAAA==.Poshingtang:BAABLgAECn8pAAQUAAkJqQxPQgCbAQloDAAABwA+AGkMAAAGABUAawwAAAYAOABqDAAABAAsAGwMAAAEAC0AbQwAAAMADwDqDAAABwASAG4MAAADABIAbwwAAAEACAAUAAkJqQxPQgCbAQloDAAAAwA+AGkMAAADABUAawwAAAIAOABqDAAAAgAsAGwMAAACAC0AbQwAAAIADwDqDAAAAwASAG4MAAACABIAbwwAAAEACAAFAAgJHhG8NgB4AQhoDAAAAgAsAGkMAAACADoAawwAAAMALQBqDAAAAgAhAGwMAAACABcAbQwAAAEAEQDqDAAABABNAG4MAAABACYAFQADCUsD/iUAdwADaAwAAAIADABpDAAAAQAJAGsMAAABAAMAAAA=.',
Pu='Pulsar:BAAALgAECgMJAwAAAA==.Punchies:BAAALgADCggJDQAAAA==.',
Qu='Quatrain:BAABLgAECn80AAMFAAkJmAykNgBUAQloDAAACgAWAGkMAAAJAC8AawwAAAYAFQBqDAAABAAZAGwMAAAIADEAbQwAAAIACgDqDAAACgAuAG4MAAACACoAbwwAAAEAEgAFAAgJ1g2kNgBUAQhoDAAAAQAWAGkMAAABAC8AawwAAAEAFQBqDAAAAQAZAGwMAAABADEA6gwAAAIALgBuDAAAAQAqAG8MAAABABIAFAAICa8QaVkARwEIaAwAAAkAOQBpDAAACAAxAGsMAAAFAB8AagwAAAMAMgBsDAAABwAnAG0MAAACAB8A6gwAAAgAMABuDAAAAQAgAAAA.Quintessence:BAAALgAECgMJAwAAAA==.',
Ra='Rabidbutt:BAAALgAFFAMJBAABLgAFFAYJFwALAA0jAA==.Ragerunner:BAAALgADCgkJEwAAAA==.Rakarg:BAABLgAECn8ZAAICAAUJDBjdxwDtAAVoDAAACAA4AGkMAAAGADoAawwAAAQARgBqDAAAAQA7AOoMAAAGADwAAgAFCQwY3ccA7QAFaAwAAAgAOABpDAAABgA6AGsMAAAEAEYAagwAAAEAOwDqDAAABgA8AAAA.Ravenus:BAAALgAECgEJAQAAAA==.',
Re='React:BAAALgAECggJCAABLgAFFAIJAwAEAAAAAA==.Redemptor:BAAALgAECgUJBQAAAA==.Refund:BAAALgAECgEJAQAAAA==.Regalbacon:BAAALgAECgMJAwAAAA==.Reygina:BAABLgAECn8ZAAIJAAYJygKfXQC3AAZoDAAABQAGAGkMAAAFAAkAawwAAAQABABqDAAABAAJAGwMAAADAAgA6gwAAAQABAAJAAYJygKfXQC3AAZoDAAABQAGAGkMAAAFAAkAawwAAAQABABqDAAABAAJAGwMAAADAAgA6gwAAAQABAAAAA==.',
Ri='Rickÿ:BAAALgAECgEJAQAAAA==.Rikku:BAAALgAECggJCAABLgAFFAgJHAAFACoTAA==.Ripndip:BAAALgAFFAMJAQAAAA==.Riprock:BAAALgAECgIJAQABLgAFFAMJAQAEAAAAAA==.Rixas:BAAALgAECgEJAQABLgAECgkJLgADAPwcAA==.',
Rn='Rn:BAACLgAFFH8FAAIOAAQJShirFwAXAQRoDAAAAQBCAGkMAAABABcAawwAAAEAWgDqDAAAAgBFAA4ABAlKGKsXABcBBGgMAAABAEIAaQwAAAEAFwBrDAAAAQBaAOoMAAACAEUALgAECn8eAAMOAAkJJSJBAQBGAwAOAAkJCCJBAQBGAwAZAAcJLyMkKQAXAgABLgAFFAgJIgAOAIMkAA==.',
Ro='Rodeo:BAAALgAECgMJAwAAAA==.Roguehiro:BAABLgAECn8oAAIQAAgJxSGlBQCMAghoDAAABwBhAGkMAAAGAF8AawwAAAYAWQBqDAAABQBZAGwMAAAGAFoAbQwAAAIAOQDqDAAABABYAG4MAAAEAFYAEAAICcUhpQUAjAIIaAwAAAcAYQBpDAAABgBfAGsMAAAGAFkAagwAAAUAWQBsDAAABgBaAG0MAAACADkA6gwAAAQAWABuDAAABABWAAAA.Rooter:BAACLgAFFH8XAAILAAYJDSMuBgBIAgZoDAAABQBWAGkMAAAEAGIAawwAAAMAYwBqDAAAAgBgAG0MAAABAEQA6gwAAAgAWAALAAYJDSMuBgBIAgZoDAAABQBWAGkMAAAEAGIAawwAAAMAYwBqDAAAAgBgAG0MAAABAEQA6gwAAAgAWAAuAAQKfz0AAwsACQkRJAgBAKIDAAsACQkRJAgBAKIDAAoABwnsGS4kALQBAAAA.Rosalynñ:BAABLgAECn8pAAIXAAgJMgpbEwAOAQhoDAAABwAVAGkMAAAHACIAawwAAAYAGABqDAAABAARAGwMAAAEABgAbQwAAAMABwDqDAAACAAYAG4MAAACAC4AFwAICTIKWxMADgEIaAwAAAcAFQBpDAAABwAiAGsMAAAGABgAagwAAAQAEQBsDAAABAAYAG0MAAADAAcA6gwAAAgAGABuDAAAAgAuAAAA.',
Ru='Ruikhai:BAAALgADCgMJBQABLgADCgkJBwAEAAAAAA==.Ruto:BAAALgAECgEJAQABLgAFFAMJAQAEAAAAAA==.',
Sa='Saelis:BAACLgAFFH8VAAIMAAUJnhZHHgBcAQVoDAAABwBIAGkMAAAFADwAawwAAAIAMQBqDAAAAQApAOoMAAAGAEEADAAFCZ4WRx4AXAEFaAwAAAcASABpDAAABQA8AGsMAAACADEAagwAAAEAKQDqDAAABgBBAC4ABAp/HwADDAAJCd8gdwsAAAMADAAJCd8gdwsAAAMAIQAGCfAZGRMAfwEAAAA=.Salen:BAAALgADCgQJAwAAAA==.Samshara:BAAALgADCgcJDAABLgAECgkJQgAaAH4dAA==.Saptapper:BAAALgAECgIJAgAAAA==.Saracenio:BAAALgADCgEJAQAAAA==.',
Sc='Schnem:BAAALgAECggJCgAAAA==.Scrawni:BAAALgAECgcJCAABLgAFFAYJEgAHAJcVAA==.Scrounge:BAAALgAFFAEJAQABLgAFFAIJBQADAPoGAA==.',
Se='Securìty:BAAALgAECgQJBQAAAA==.Selyane:BAAALgADCgkJCQAAAA==.Seong:BAACLgAFFH8dAAIIAAgJihynBAA7AghoDAAABgBcAGkMAAAFAGEAawwAAAQARgBqDAAABAAqAGwMAAABADAAbQwAAAEAPQDqDAAABwBeAG4MAAABAC0ACAAICYocpwQAOwIIaAwAAAYAXABpDAAABQBhAGsMAAAEAEYAagwAAAQAKgBsDAAAAQAwAG0MAAABAD0A6gwAAAcAXgBuDAAAAQAtAC4ABAp/IQACCAAJCYAiBQUAOQMACAAJCYAiBQUAOQMAAAA=.Seongdh:BAAALgAECggJDQABLgAFFAgJHQAIAIocAA==.Seongwar:BAAALgAECgMJAwAAAA==.Seraphinà:BAAALgAECgYJDAABLgAECgkJJwAeAL4MAA==.',
Sh='Shadowdooms:BAABLgAECn8WAAMCAAgJFBkfYQDQAQhoDAAABABMAGkMAAADAFMAawwAAAMAPwBqDAAAAwAjAGwMAAACAD0AbQwAAAEAFQDqDAAABAA5AG4MAAACAFQAAgAICRQZH2EA0AEIaAwAAAQATABpDAAAAgBTAGsMAAADAD8AagwAAAMAIwBsDAAAAgA9AG0MAAABABUA6gwAAAQAOQBuDAAAAgBUAAEAAQlLF/YUAEUAAWkMAAABADsAAAA=.Shadowfur:BAAALgAECggJCAABLgAECgkJPAAJAN8eAA==.Shamynna:BAAALgAECgMJBAAAAA==.Sharreth:BAAALgAECgIJAgAAAA==.Shii:BAAALgADCgUJBQAAAA==.Shimera:BAABLgAECn8yAAISAAkJNhMrOgDvAQloDAAACABFAGkMAAAHADsAawwAAAcAMABqDAAABwBDAGwMAAAGADIAbQwAAAQALADqDAAACABKAG4MAAACABwAbwwAAAEAEwASAAkJNhMrOgDvAQloDAAACABFAGkMAAAHADsAawwAAAcAMABqDAAABwBDAGwMAAAGADIAbQwAAAQALADqDAAACABKAG4MAAACABwAbwwAAAEAEwAAAA==.Shish:BAAALgAECggJCwAAAA==.Shizukura:BAAALgADCgEJAQAAAA==.Shockawar:BAACLgAFFH8WAAIZAAUJeRwxAwDEAQVoDAAABgBZAGkMAAAFAEAAawwAAAQASgBqDAAAAgAUAOoMAAAFAD4AGQAFCXkcMQMAxAEFaAwAAAYAWQBpDAAABQBAAGsMAAAEAEoAagwAAAIAFADqDAAABQA+AC4ABAp/GQACGQAJCaseZhgAiAIAGQAJCaseZhgAiAIAAAA=.Shooter:BAAALgADCgIJAgAAAA==.Shootrmcgavn:BAACLgAFFH8eAAQSAAYJ8yJKHgB7AQZoDAAABwBhAGkMAAAHAFMAawwAAAUAVQBqDAAAAwBbAGwMAAABAFMA6gwAAAcAYQASAAUJrx9KHgB7AQVoDAAAAgBPAGkMAAACAD0AawwAAAEAVQBqDAAAAwBbAOoMAAACAGEAGgAECUUhDQsAYwEEaAwAAAQAWwBpDAAABABTAGsMAAAEAE0A6gwAAAQAVwATAAQJNiDGEAAqAQRoDAAAAQBhAGkMAAABAD8AbAwAAAEAUwDqDAAAAQBVAC4ABAp/GwAEEgAICTwh0xUAiQIAEgAHCfEh0xUAiQIAEwAHCUohyhoAUwIAGgADCbchpzAAIwEAAAA=.Shu:BAAALgAFFAIJAgAAAA==.Shuletaa:BAAALgAECgIJBAAAAA==.Shïsh:BAAALgADCgcJBwABLgAECggJCwAEAAAAAA==.',
Si='Silverwolf:BAAALgADCgEJAQAAAA==.Sinestra:BAAALgAECgEJAQAAAA==.',
Sk='Skibidi:BAAALgAECgcJBwABLgAFFAMJEAAWABcfAA==.',
Sl='Slagscar:BAAALgAFFAIJAQAAAA==.Slaughterhse:BAABLgAECn8XAAIWAAYJ5gPH8wC5AAZoDAAABQAPAGkMAAAFAAgAawwAAAYACABqDAAAAwANAGwMAAACAAkA6gwAAAIABwAWAAYJ5gPH8wC5AAZoDAAABQAPAGkMAAAFAAgAawwAAAYACABqDAAAAwANAGwMAAACAAkA6gwAAAIABwAAAA==.Slootar:BAABLgAECn8UAAQMAAcJ5xuIJAAoAgdoDAAABABgAGkMAAADAFkAawwAAAMANwBqDAAAAwBEAGwMAAADAD8AbQwAAAEANgDqDAAAAwBHAAwABwnnG4gkACgCB2gMAAACAGAAaQwAAAEAWQBrDAAAAQA3AGoMAAADAEQAbAwAAAMAPwBtDAAAAQA2AOoMAAADAEcAHgACCbsQX2wAbgACaAwAAAIALQBpDAAAAQAoACEAAgkwBmdRACwAAmkMAAABAAcAawwAAAIAGAAAAA==.Slugs:BAAALgAECgUJCAAAAA==.',
Sn='Snqwflake:BAABLgAECn8VAAIiAAgJ7xb8FQAUAghoDAAABAA5AGkMAAAEADYAawwAAAMARgBqDAAAAgBGAGwMAAACAEMAbQwAAAEAMADqDAAABABQAG4MAAABABQAIgAICe8W/BUAFAIIaAwAAAQAOQBpDAAABAA2AGsMAAADAEYAagwAAAIARgBsDAAAAgBDAG0MAAABADAA6gwAAAQAUABuDAAAAQAUAAAA.',
So='Solareth:BAAALgAECgEJAgAAAA==.Solthin:BAAALgAFFAMJAQAAAA==.Somebeotch:BAAALgADCgYJBgAAAA==.Somerled:BAABLgAECn9CAAIaAAkJfh39BwCdAgloDAAACgBRAGkMAAAKAE4AawwAAAoAVQBqDAAACABZAGwMAAAIAD8AbQwAAAUAOgDqDAAABwBNAG4MAAAGAEcAbwwAAAIAVgAaAAkJfh39BwCdAgloDAAACgBRAGkMAAAKAE4AawwAAAoAVQBqDAAACABZAGwMAAAIAD8AbQwAAAUAOgDqDAAABwBNAG4MAAAGAEcAbwwAAAIAVgAAAA==.',
Sp='Spyroid:BAAALgAECgUJAQAAAA==.',
St='Static:BAAALgADCgcJBwABLgAECgYJCgAEAAAAAA==.',
Su='Sunstrike:BAAALgAECgEJAgAAAA==.',
Sy='Sylvanna:BAAALgADCgQJBAAAAA==.',
Ta='Tabul:BAAALgADCgUJBAAAAA==.Takka:BAABLgAECn8aAAIUAAgJHR3tFgCKAghoDAAABQBfAGkMAAAFAF0AawwAAAUAUgBqDAAAAQAtAGwMAAABAEgAbQwAAAIAVQDqDAAABQBaAG4MAAACAB8AFAAICR0d7RYAigIIaAwAAAUAXwBpDAAABQBdAGsMAAAFAFIAagwAAAEALQBsDAAAAQBIAG0MAAACAFUA6gwAAAUAWgBuDAAAAgAfAAAA.Talden:BAABLgAECn9FAAMPAAkJMhzVHQCMAgloDAAACgBdAGkMAAAIAFQAawwAAAcAVABqDAAACgBcAGwMAAAHAFgAbQwAAAUALADqDAAADgBeAG4MAAAHADkAbwwAAAEAHQAPAAkJMhzVHQCMAgloDAAACgBdAGkMAAAIAFQAawwAAAcAVABqDAAACQBcAGwMAAAHAFgAbQwAAAUALADqDAAADABeAG4MAAAGADkAbwwAAAEAHQAQAAMJzRC8QwBMAANqDAAAAQBEAOoMAAACAEYAbgwAAAEADwAAAA==.Talkamar:BAABLgAECn8iAAIdAAkJ6RCDHwCpAQloDAAABAAXAGkMAAAFAC8AawwAAAUANABqDAAABAApAGwMAAAFACoAbQwAAAIAPgDqDAAABgA4AG4MAAABAAsAbwwAAAIAMQAdAAkJ6RCDHwCpAQloDAAABAAXAGkMAAAFAC8AawwAAAUANABqDAAABAApAGwMAAAFACoAbQwAAAIAPgDqDAAABgA4AG4MAAABAAsAbwwAAAIAMQAAAA==.Taylorswift:BAABLgAECn83AAIWAAkJ8xjqKgBpAgloDAAACABRAGkMAAAIAEwAawwAAAgASwBqDAAACABUAGwMAAAHAFUAbQwAAAUAVADqDAAACQA4AG4MAAABABkAbwwAAAEAGAAWAAkJ8xjqKgBpAgloDAAACABRAGkMAAAIAEwAawwAAAgASwBqDAAACABUAGwMAAAHAFUAbQwAAAUAVADqDAAACQA4AG4MAAABABkAbwwAAAEAGAAAAA==.Tazzaar:BAAALgAECgMJAwAAAA==.',
Th='Thaelios:BAAALgADCgEJAQAAAA==.Thekourge:BAABLgAECn80AAIQAAkJ2Ao2GgA+AQloDAAACgArAGkMAAAJACQAawwAAAkALABqDAAABgAUAGwMAAAFACYAbQwAAAMAGQDqDAAACAASAG4MAAABAAUAbwwAAAEACQAQAAkJ2Ao2GgA+AQloDAAACgArAGkMAAAJACQAawwAAAkALABqDAAABgAUAGwMAAAFACYAbQwAAAMAGQDqDAAACAASAG4MAAABAAUAbwwAAAEACQAAAA==.Thenard:BAABLgAECn8jAAISAAgJPBPGUQCmAQhoDAAABQBQAGkMAAAFACMAawwAAAQAJgBqDAAABgBEAGwMAAAFADMAbQwAAAMAOwDqDAAABQA4AG4MAAACABYAEgAICTwTxlEApgEIaAwAAAUAUABpDAAABQAjAGsMAAAEACYAagwAAAYARABsDAAABQAzAG0MAAADADsA6gwAAAUAOABuDAAAAgAWAAAA.Thukunaenhan:BAAALgAECgQJBAABLgAFFAMJEAAWABcfAA==.Thukunamage:BAACLgAFFH8QAAIWAAMJFx8FawAMAQNoDAAABwBPAGkMAAAEAFIA6gwAAAUATAAWAAMJFx8FawAMAQNoDAAABwBPAGkMAAAEAFIA6gwAAAUATAAuAAQKfyoAAhYACQmyIMsfAJsCABYACQmyIMsfAJsCAAAA.',
Ti='Tibarius:BAAALgADCgkJEgAAAA==.Tili:BAAALgADCgkJDQAAAA==.Tinaraeda:BAAALgAECgMJAwAAAA==.',
To='Tomislav:BAABLgAECn8eAAQDAAkJrxLJUAClAQloDAAABQBEAGkMAAAEAC4AawwAAAQAOwBqDAAAAwBIAGwMAAADACkAbQwAAAIALQDqDAAABQA0AG4MAAABABIAbwwAAAMAMgADAAcJzRLJUAClAQdoDAAABABEAGkMAAADAC4AawwAAAQAOwBsDAAAAwApAOoMAAAFADQAbgwAAAEAEgBvDAAAAwAyABcAAwlEFUxPAIAAA2gMAAABAD8AagwAAAMASABtDAAAAgAtACMAAQmUDoU5ADgAAWkMAAABACUAAAA=.Tomuchmakeup:BAAALgAECgEJAQAAAA==.Touritos:BAABLgAECn8eAAIFAAkJdRHtKACeAQloDAAABABLAGkMAAAFACwAawwAAAUAOgBqDAAAAQAWAGwMAAABAAAAbQwAAAIALQDqDAAACQBFAG4MAAACAB4AbwwAAAEAIAAFAAkJdRHtKACeAQloDAAABABLAGkMAAAFACwAawwAAAUAOgBqDAAAAQAWAGwMAAABAAAAbQwAAAIALQDqDAAACQBFAG4MAAACAB4AbwwAAAEAIAAAAA==.',
Tr='Trimblestein:BAAALgAECgMJBQAAAA==.Troyka:BAAALgAECgEJAQAAAA==.Truefitt:BAAALgAECgYJEwAAAA==.',
Tu='Tulikettwo:BAAALgAECgEJAQAAAA==.Tulirenpo:BAAALgAECgUJBQAAAA==.Tunk:BAAALgAFFAMJAQAAAA==.Tuskal:BAAALgAECgIJAwAAAA==.',
Tw='Twogora:BAAALgAECgYJCQAAAA==.Twohoofy:BAAALgADCgcJBgAAAA==.',
Ty='Tydes:BAABLgAECn8bAAMlAAgJ6RbMEwB4AghoDAAABwBTAGkMAAAFAEoAawwAAAUATQBqDAAAAgBQAGwMAAABACMAbQwAAAIAIgDqDAAABABCAG4MAAABACUAJQAICekWzBMAeAIIaAwAAAcAUwBpDAAABABKAGsMAAAFAE0AagwAAAIAUABsDAAAAQAjAG0MAAACACIA6gwAAAQAQgBuDAAAAQAlACYAAQm2C0EdAEEAAWkMAAABAB0AAAA=.Tydru:BAAALgAFFAMJAQAAAA==.Tyler:BAACLgAFFH8LAAIGAAQJfhXYDwBPAQRoDAAABAA7AGkMAAADADwAawwAAAIAPwDqDAAAAgAkAAYABAl+FdgPAE8BBGgMAAAEADsAaQwAAAMAPABrDAAAAgA/AOoMAAACACQALgAECn8bAAIGAAgJDh04HACpAgAGAAgJDh04HACpAgAAAA==.Tystin:BAAALgADCgQJBQABLgADCgkJBwAEAAAAAA==.',
Ud='Uddermilk:BAABLgAECn8UAAIeAAQJrQqBVwCpAARoDAAABQAqAGkMAAAFABIAawwAAAUAGADqDAAABQAXAB4ABAmtCoFXAKkABGgMAAAFACoAaQwAAAUAEgBrDAAABQAYAOoMAAAFABcAAAA=.',
Um='Umariel:BAAALgAFFAMJAQAAAA==.',
Va='Valina:BAAALgADCgIJAgAAAA==.Valissar:BAAALgAECgMJBgAAAA==.Valkyrja:BAAALgAECgEJAQAAAA==.Valr:BAABLgAECn8zAAIQAAkJtw8qFgBqAQloDAAABwA1AGkMAAAGADQAawwAAAYAOABqDAAABQAWAGwMAAAHABcAbQwAAAQAJADqDAAACQAlAG4MAAAFACgAbwwAAAIAFQAQAAkJtw8qFgBqAQloDAAABwA1AGkMAAAGADQAawwAAAYAOABqDAAABQAWAGwMAAAHABcAbQwAAAQAJADqDAAACQAlAG4MAAAFACgAbwwAAAIAFQAAAA==.Vancliffe:BAAALgAECgQJBAABLgAFFAYJEgAHAJcVAA==.Vandreu:BAAALgADCgUJBQAAAA==.',
Ve='Verpally:BAAALgADCgMJAwAAAA==.',
Vi='Viparia:BAAALgAECgkJAgAAAA==.Virulent:BAAALgAECgMJAwAAAA==.',
Vo='Voloaura:BAAALgADCgMJAwAAAA==.',
Vs='Vse:BAACLgAFFH8ZAAIWAAQJKBQRUgA8AQRoDAAACQBBAGkMAAAHAD4AawwAAAMAIQDqDAAABgArABYABAkoFBFSADwBBGgMAAAJAEEAaQwAAAcAPgBrDAAAAwAhAOoMAAAGACsALgAECn8uAAIWAAgJfBuhRQAGAgAWAAgJfBuhRQAGAgAAAA==.Vsesosorry:BAABLgAFFH8VAAIUAAQJZxQDMgAKAQRoDAAABwBKAGkMAAAFAC4AawwAAAIAJADqDAAABwAzABQABAlnFAMyAAoBBGgMAAAHAEoAaQwAAAUALgBrDAAAAgAkAOoMAAAHADMAAS4ABRQECRkAFgAoFAA=.Vsè:BAAALgADCgUJBQABLgAFFAQJGQAWACgUAA==.',
Vy='Vyke:BAAALgAECgkJEQABLgAFFAgJHQAIAIocAA==.',
['Ví']='Ví:BAAALgAECgYJBgAAAA==.',
Wa='Wammo:BAAALgAECgYJCgAAAA==.Waq:BAAALgADCgMJAwAAAA==.Wardozer:BAAALgAECgUJCQAAAA==.Warlockedin:BAAALgAECgYJDQAAAA==.',
We='Weierstrass:BAAALgAFFAEJAQABLgAFFAgJIAAYAAsjAA==.',
Wo='Worgenkrantz:BAABLgAECn8nAAMeAAkJvgx7KACEAQloDAAABgAlAGkMAAAFACwAawwAAAUAJABqDAAAAwAVAGwMAAAEACMAbQwAAAMADADqDAAABwA0AG4MAAAEAAsAbwwAAAIAHQAeAAkJvgx7KACEAQloDAAABAAlAGkMAAADACwAawwAAAMAJABqDAAAAQAVAGwMAAACACMAbQwAAAIADADqDAAABQA0AG4MAAAEAAsAbwwAAAIAHQAMAAcJeAJQkgCrAAdoDAAAAgANAGkMAAACAAQAawwAAAIABABqDAAAAgAHAGwMAAACAAUAbQwAAAEAAwDqDAAAAgAEAAAA.',
Wr='Wrathlor:BAAALgADCgcJBQAAAA==.Wrenlyn:BAACLgAFFH8SAAMHAAYJlxVQEAAVAQZoDAAABQBDAGkMAAAEAEkAawwAAAIAKwBqDAAAAQAkAGwMAAABADQA6gwAAAUAJwAHAAUJ5RVQEAAVAQVoDAAABQBDAGkMAAAEAEkAawwAAAIAKwBqDAAAAQAkAOoMAAAEACcABgACCSkM2nUAhwACbAwAAAEANADqDAAAAQAKAC4ABAp/MAADBwAICWwj7w0APAIABwAICe0f7w0APAIAJAACCUITJSQAcgAAAAA=.',
Wu='Wukain:BAAALgADCgEJAQAAAA==.',
Xa='Xanatas:BAAALgAECgYJCQABLgAECgkJMQAQAEEhAA==.',
Xo='Xolòtl:BAABLgAECn8gAAINAAgJUBcZFADLAQhoDAAABABUAGkMAAAEAEoAawwAAAUAOABqDAAABQA4AGwMAAAFADMAbQwAAAIAKQDqDAAAAwBAAG4MAAAEAC0ADQAICVAXGRQAywEIaAwAAAQAVABpDAAABABKAGsMAAAFADgAagwAAAUAOABsDAAABQAzAG0MAAACACkA6gwAAAMAQABuDAAABAAtAAEuAAUUBgkSAAcAlxUA.Xoss:BAAALgAFFAMJAQAAAA==.',
Yg='Yggdrasali:BAAALgAECgQJBgABLgAFFAIJBQAWAJIaAA==.',
Yi='Yin:BAAALgAECgcJCAAAAA==.',
Yo='Yourhero:BAAALgAECgEJAQAAAA==.',
Ys='Yserra:BAAALgAECgcJDAAAAA==.',
Za='Zaerine:BAAALgAECgYJBgAAAA==.Zakuso:BAAALgAECgQJCQAAAA==.Zalatha:BAAALgADCgEJAQAAAA==.Zalyia:BAABLgAECn8uAAIbAAkJlA2DJACgAQloDAAABwAfAGkMAAAGABkAawwAAAYAMABqDAAABQAXAGwMAAAGAC0AbQwAAAQAHADqDAAACAAqAG4MAAADABcAbwwAAAEAIAAbAAkJlA2DJACgAQloDAAABwAfAGkMAAAGABkAawwAAAYAMABqDAAABQAXAGwMAAAGAC0AbQwAAAQAHADqDAAACAAqAG4MAAADABcAbwwAAAEAIAAAAA==.',
Ze='Zephinar:BAABLgAECn8ZAAIWAAgJcBVpaQADAghoDAAABABHAGkMAAAEAEYAawwAAAQATgBqDAAAAwBQAGwMAAADAEAAbQwAAAEAGQDqDAAABQBHAG4MAAABAAMAFgAICXAVaWkAAwIIaAwAAAQARwBpDAAABABGAGsMAAAEAE4AagwAAAMAUABsDAAAAwBAAG0MAAABABkA6gwAAAUARwBuDAAAAQADAAAA.Zexpert:BAABLgAECn8cAAQnAAgJSReiDQAAAghoDAAABQBQAGkMAAAEADwAawwAAAQAQgBqDAAABAA/AGwMAAADAE4AbQwAAAEAFgDqDAAABQBBAG4MAAACACoAJwAHCSIYog0AAAIHaAwAAAIATQBpDAAAAgA8AGsMAAACAEIAagwAAAIAPwBsDAAAAgBOAG0MAAABABYA6gwAAAQAQQAKAAcJnhUvKAB8AQdoDAAAAQBQAGkMAAABADcAawwAAAEAOwBqDAAAAQAlAGwMAAABAC0A6gwAAAEAMABuDAAAAgAqAAsABAl+DAU0AM0ABGgMAAACADAAaQwAAAEAKQBrDAAAAQATAGoMAAABABIAAAA=.',
Zq='Zquestion:BAAALgAECgIJBAABLgAECggJHAAnAEkXAA==.',
Zu='Zulblade:BAABLgAECn8SAAIGAAgJORqFMAA5AghoDAAAAQBbAGkMAAADAFYAawwAAAQASwBqDAAAAwBAAGwMAAADAE4AbQwAAAIANQDqDAAAAQA+AG4MAAABABUABgAICTkahTAAOQIIaAwAAAEAWwBpDAAAAwBWAGsMAAAEAEsAagwAAAMAQABsDAAAAwBOAG0MAAACADUA6gwAAAEAPgBuDAAAAQAVAAAA.Zulpally:BAABLgAECn8aAAQPAAUJQBb4wwD7AAVoDAAABQBAAGkMAAAFADYAawwAAAYAPgBsDAAABQAfAOoMAAAFAEcADwAECcYY+MMA+wAEaAwAAAMAQABpDAAAAgA2AGsMAAAFAD4A6gwAAAMARwAJAAMJyRCQcgCxAANoDAAAAQBKAGkMAAABACwA6gwAAAIACQAQAAQJ+QiuMQCIAARoDAAAAQAhAGkMAAACAAkAawwAAAEAEgBsDAAABQAfAAAA.',
['Zô']='Zôrt:BAAALgAECggJEAAAAA==.',
['Àn']='Àngron:BAAALgADCgYJDAAAAA==.',
['Âr']='Ârtemis:BAAALgAECgYJDAAAAA==.',
['Èo']='Èomer:BAAALgAECgEJAQAAAA==.',
['Öh']='Öhmylanta:BAAALgADCgMJAwAAAA==.',
['Öâ']='Öâth:BAAALgAECgIJAgAAAA==.',
['ßa']='ßaroness:BAAALgAECgEJAQAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
