local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Evoker-Augmentation','Warrior-Arms','Warrior-Fury','Priest-Holy','Priest-Shadow','DeathKnight-Blood','Unknown-Unknown','Warlock-Demonology','Mage-Frost','Hunter-Marksmanship','Paladin-Retribution','Monk-Brewmaster','Hunter-BeastMastery','Evoker-Preservation','Evoker-Devastation','Warrior-Protection','Paladin-Holy','Warlock-Destruction','DeathKnight-Unholy','Shaman-Elemental','Shaman-Restoration','Monk-Windwalker','DemonHunter-Devourer','Warlock-Affliction','DemonHunter-Vengeance','Priest-Discipline','Druid-Guardian','Druid-Restoration','Hunter-Survival','Shaman-Enhancement','DemonHunter-Havoc','Paladin-Protection','Druid-Feral','DeathKnight-Frost','Druid-Balance','Monk-Mistweaver','Mage-Arcane',}
local provider = {region='US',realm='ShatteredHand',name='US',type='daily',zone=46,date='2026-05-10',data={Ab='Abchi:BAAALgAECgMJAwAAAA==.Abelladanger:BAAALgADCgYJBgAAAA==.Absorption:BAAALgAECggJDAABLgAECggJIQABAFYXAA==.',
Ac='Ackerw:BAABLgAFFH8JAAMCAAQJkws1BAD3AARoDAAAAgAKAGkMAAACABoAawwAAAEACgDqDAAABABGAAIABAmTCzUEAPcABGgMAAACAAoAaQwAAAIAGgBrDAAAAQAKAOoMAAADAEYAAwABCWkELSQATAAB6gwAAAEACwAAAA==.',
Ad='Addilyn:BAABLgAECn8aAAMEAAgJPxT0HgBaAQhoDAAABQA5AGkMAAAEADUAawwAAAQAOgBqDAAAAwATAGwMAAACAE0AbQwAAAIAPwDqDAAABAA1AG4MAAACAB4ABAAICT8U9B4AWgEIaAwAAAMAOQBpDAAAAwA1AGsMAAADADoAagwAAAIAEwBsDAAAAQBNAG0MAAACAD8A6gwAAAMANQBuDAAAAQAeAAUABwlyC0UgAEcBB2gMAAACABkAaQwAAAEAHABrDAAAAQAcAGoMAAABACUAbAwAAAEAGwDqDAAAAQAXAG4MAAABACkAAAA=.',
Ah='Ahminous:BAABLgAECn8aAAIGAAgJ2BOcDgCUAQhoDAAABQBCAGkMAAAEAEgAawwAAAQANABqDAAAAwA/AGwMAAACACUAbQwAAAIAJwDqDAAABABDAG4MAAACABMABgAICdgTnA4AlAEIaAwAAAUAQgBpDAAABABIAGsMAAAEADQAagwAAAMAPwBsDAAAAgAlAG0MAAACACcA6gwAAAQAQwBuDAAAAgATAAAA.Ahroo:BAAALgAECgcJGQABLgAECgkJDQAHAAAAAQ==.Ahrue:BAAALgAECgkJDQAAAQ==.',
Ai='Airc:BAAALgAECgYJDwAAAA==.Aiurman:BAAALgADCgkJCQAAAA==.',
Al='Alfster:BAABLgAECn8dAAIIAAgJcgcyTABJAQhoDAAAAgAKAGkMAAAEAAoAawwAAAQAEgBqDAAAAwAZAGwMAAAHACkAbQwAAAEAEgDqDAAABgATAG4MAAACAA8ACAAICXIHMkwASQEIaAwAAAIACgBpDAAABAAKAGsMAAAEABIAagwAAAMAGQBsDAAABwApAG0MAAABABIA6gwAAAYAEwBuDAAAAgAPAAAA.Allessiae:BAAALgAECgYJBgAAAA==.Alvar:BAABLgAECn8XAAIIAAgJsRIDMwCdAQhoDAAAAgA1AGkMAAACABoAawwAAAMALABqDAAAAgAiAGwMAAAFAE4AbQwAAAIAIwDqDAAABQAvAG4MAAACADAACAAICbESAzMAnQEIaAwAAAIANQBpDAAAAgAaAGsMAAADACwAagwAAAIAIgBsDAAABQBOAG0MAAACACMA6gwAAAUALwBuDAAAAgAwAAAA.',
Ar='Arcadium:BAABLgAECn8VAAIJAAUJWCKUbwD1AQVoDAAAAwBgAGkMAAAFAFwAawwAAAQATQBqDAAAAwBhAOoMAAAGAFUACQAFCVgilG8A9QEFaAwAAAMAYABpDAAABQBcAGsMAAAEAE0AagwAAAMAYQDqDAAABgBVAAAA.Arêos:BAABLgAECn8dAAIEAAkJZh0/CAB0AgloDAAABgBSAGkMAAAFAFcAawwAAAUAVgBqDAAAAwBOAGwMAAACAFUAbQwAAAEAPQDqDAAABQBcAG4MAAABAEYAbwwAAAEAHwAEAAkJZh0/CAB0AgloDAAABgBSAGkMAAAFAFcAawwAAAUAVgBqDAAAAwBOAGwMAAACAFUAbQwAAAEAPQDqDAAABQBcAG4MAAABAEYAbwwAAAEAHwAAAA==.',
As='Asunaish:BAAALgAECgcJEwAAAA==.',
At='Atiko:BAAALgADCgQJBAAAAA==.Atomicrednax:BAABLgAFFH8UAAIKAAcJQh74AgAlAgdoDAAAAgBbAGkMAAAEAFIAawwAAAMAWgBqDAAAAwBDAGwMAAACAEoAbQwAAAEAJwDqDAAABQBVAAoABwlCHvgCACUCB2gMAAACAFsAaQwAAAQAUgBrDAAAAwBaAGoMAAADAEMAbAwAAAIASgBtDAAAAQAnAOoMAAAFAFUAAAA=.Atropos:BAAALgADCgcJBwAAAA==.',
Ay='Ayisen:BAAALgAECgQJBQAAAA==.',
Az='Azarite:BAABLgAECn8kAAILAAgJ1RJaQwCFAQhoDAAABgA8AGkMAAAGAEEAawwAAAUAPQBqDAAABQAjAGwMAAAEACkAbQwAAAMAKQDqDAAABQAtAG4MAAACABUACwAICdUSWkMAhQEIaAwAAAYAPABpDAAABgBBAGsMAAAFAD0AagwAAAUAIwBsDAAABAApAG0MAAADACkA6gwAAAUALQBuDAAAAgAVAAAA.',
Ba='Babybilly:BAAALgAECgQJBAAAAA==.Badassbum:BAAALgAECgYJEgAAAA==.Bahoodies:BAAALgAECgYJBQAAAA==.Balgorath:BAAALgAECgQJBwAAAA==.Balthazar:BAAALgADCgUJBgAAAA==.Bananastand:BAAALgADCgMJAwAAAA==.Banree:BAAALgAECgEJAgAAAA==.Bassa:BAAALgADCgYJBgAAAA==.Battman:BAAALgADCgcJDAAAAA==.Battousaiha:BAABLgAECn8cAAILAAgJABomIAARAghoDAAABQBRAGkMAAAEADwAawwAAAUAWgBqDAAAAwAsAGwMAAACADgAbQwAAAIAKADqDAAABQBRAG4MAAACADYACwAICQAaJiAAEQIIaAwAAAUAUQBpDAAABAA8AGsMAAAFAFoAagwAAAMALABsDAAAAgA4AG0MAAACACgA6gwAAAUAUQBuDAAAAgA2AAAA.',
Be='Bera:BAAALgAECgIJAwAAAA==.',
Bi='Bigmustard:BAACLgAFFH8hAAIMAAYJSyCeAwDEAQZoDAAABgBJAGkMAAAHAGEAawwAAAYATgBqDAAABQBFAGwMAAADAFQA6gwAAAYATwAMAAYJSyCeAwDEAQZoDAAABgBJAGkMAAAHAGEAawwAAAYATgBqDAAABQBFAGwMAAADAFQA6gwAAAYATwAuAAQKfywAAgwACQkvJfUDAFADAAwACQkvJfUDAFADAAAA.Bignut:BAAALgAECgYJBQAAAA==.',
Bo='Boojum:BAAALgAECgYJDgAAAA==.Borticuss:BAAALgAECgMJAwABLgAECgcJIAAMAOsZAA==.Bortikus:BAAALgAECgQJBwABLgAECgcJIAAMAOsZAA==.Boskos:BAAALgADCgQJBAABLgAECgQJBgAHAAAAAA==.Bossnugg:BAAALgADCgYJCAABLgAECgQJBgAHAAAAAA==.',
Br='Brasputin:BAAALgADCgQJBAAAAA==.Breez:BAAALgADCgIJAgAAAA==.',
Bu='Bul:BAAALgADCgcJBwABLgAECggJFAANABAUAA==.Bullshifting:BAAALgAECgcJEwAAAA==.Bumbaloo:BAAALgAECgQJBQAAAA==.Burgi:BAAALgAECgQJBQAAAA==.Burney:BAABLgAECn8gAAMOAAgJFx4mAwCwAghoDAAABQBXAGkMAAAFAFsAawwAAAUAVABqDAAABABTAGwMAAADAFUAbQwAAAIAQQDqDAAABgBaAG4MAAACABwADgAICRceJgMAsAIIaAwAAAUAVwBpDAAABQBbAGsMAAAFAFQAagwAAAQAUwBsDAAAAwBVAG0MAAACAEEA6gwAAAUAWgBuDAAAAQAcAA8AAglwC8ESAGYAAuoMAAABACUAbgwAAAEAFQAAAA==.',
['Bò']='Bònesaw:BAABLgAECn8lAAIQAAkJ0SGtAgC1AgloDAAABgBaAGkMAAAFAGEAawwAAAUAXABqDAAABQBhAGwMAAAFAFUAbQwAAAMAQwDqDAAABABdAG4MAAADAF8AbwwAAAEARgAQAAkJ0SGtAgC1AgloDAAABgBaAGkMAAAFAGEAawwAAAUAXABqDAAABQBhAGwMAAAFAFUAbQwAAAMAQwDqDAAABABdAG4MAAADAF8AbwwAAAEARgAAAA==.',
Ca='Calibrium:BAAALgAECgYJDwAAAA==.Cannaboss:BAAALgAECgQJBgAAAA==.Carll:BAACLgAFFH8IAAIRAAMJgA9AHADSAANoDAAAAwAbAGkMAAAEADUA6gwAAAEAJQARAAMJgA9AHADSAANoDAAAAwAbAGkMAAAEADUA6gwAAAEAJQAuAAQKfx8AAhEACAlsFL4mAPQBABEACAlsFL4mAPQBAAAA.Catleesei:BAAALgAFFAEJAQAAAA==.',
Ch='Chables:BAAALgADCgcJBwAAAA==.Chai:BAAALgAECgYJCwAAAA==.Chaosmage:BAAALgAECgQJBAAAAA==.Chickyn:BAAALgAECgMJBQAAAA==.Choppa:BAAALgAECgQJCAAAAA==.',
Cl='Clyde:BAAALgAECgIJAgAAAA==.',
Co='Cocodruid:BAAALgAECgEJAQABLgAECgEJAgAHAAAAAA==.Coldxlxsoul:BAABLgAECn8WAAMPAAcJqhQNFAClAQdoDAAABABJAGkMAAAEADoAawwAAAMATABqDAAAAwBAAGwMAAADACgA6gwAAAQAOwBuDAAAAQAJAA8ABwkNEg0UAKUBB2gMAAADAEkAaQwAAAMAOgBrDAAAAgBMAGoMAAACAEAAbAwAAAIAHwDqDAAAAwAcAG4MAAABAAkAAQAGCVgRPS4AUAEGaAwAAAEAFABpDAAAAQA0AGsMAAABADAAagwAAAEAIABsDAAAAQAoAOoMAAABADsAAAA=.Condrius:BAAALgADCgUJBgAAAA==.Convict:BAAALgAECgMJBQAAAA==.',
Cr='Crappylock:BAAALgAECgQJBAAAAA==.Criotor:BAAALgAECgIJBAAAAA==.Critster:BAAALgAECgQJBwAAAA==.',
Da='Daddy:BAACLgAFFH8LAAIIAAUJgQrhHAARAQVoDAAAAgAGAGkMAAADABEAawwAAAIAMABqDAAAAQAQAOoMAAADACMACAAFCYEK4RwAEQEFaAwAAAIABgBpDAAAAwARAGsMAAACADAAagwAAAEAEADqDAAAAwAjAC4ABAp/IAADCAAICTgZ9CgAbQIACAAICaQY9CgAbQIAEgAHCVoUmxgAhgEAAAA=.Darkportal:BAAALgAECgQJCQABLgAECgcJEwAHAAAAAA==.Datnagablu:BAAALgAECgQJBQAAAA==.',
De='Deathsrain:BAABLgAECn8kAAITAAgJ2x+9NABkAghoDAAABgBdAGkMAAAGAGAAawwAAAUAUABqDAAAAwBcAGwMAAAFAFQAbQwAAAEAPgDqDAAABwBZAG4MAAADAD4AEwAICdsfvTQAZAIIaAwAAAYAXQBpDAAABgBgAGsMAAAFAFAAagwAAAMAXABsDAAABQBUAG0MAAABAD4A6gwAAAcAWQBuDAAAAwA+AAAA.Decimez:BAABLgAECn8aAAIUAAgJMiBmBwBzAghoDAAABQBbAGkMAAAEAFIAawwAAAQATwBqDAAAAwBVAGwMAAACAFcAbQwAAAIAUADqDAAABABZAG4MAAACAEEAFAAICTIgZgcAcwIIaAwAAAUAWwBpDAAABABSAGsMAAAEAE8AagwAAAMAVQBsDAAAAgBXAG0MAAACAFAA6gwAAAQAWQBuDAAAAgBBAAAA.Decimock:BAAALgAECggJCQAAAA==.Dellinsane:BAAALgAECgEJAQAAAA==.Devour:BAAALgAFFAIJAwAAAA==.',
Di='Dingiswayo:BAAALgAECgcJEgAAAA==.Dipz:BAAALgAECgYJCQAAAA==.',
Do='Donyolerberz:BAAALgAECgYJBQAAAA==.',
Dr='Draeno:BAABLgAECn8UAAINAAgJEBQuPQBcAQhoDAAAAwAmAGkMAAADADkAawwAAAQATgBqDAAAAgAlAGwMAAADADoAbQwAAAEAKwDqDAAAAwAsAG4MAAABACUADQAICRAULj0AXAEIaAwAAAMAJgBpDAAAAwA5AGsMAAAEAE4AagwAAAIAJQBsDAAAAwA6AG0MAAABACsA6gwAAAMALABuDAAAAQAlAAAA.Dragonflyy:BAAALgAECgEJAQAAAA==.Dragonips:BAAALgADCgYJBgAAAA==.Drbonedaddy:BAAALgAECgYJBgABLgAECgcJBQAHAAAAAA==.Drinkyds:BAABLgAFFH8HAAIVAAUJ5RZIBwCtAQVoDAAAAQBfAGkMAAABAFUAawwAAAEAMABqDAAAAQAhAOoMAAADAB8AFQAFCeUWSAcArQEFaAwAAAEAXwBpDAAAAQBVAGsMAAABADAAagwAAAEAIQDqDAAAAwAfAAAA.',
Du='Duggnut:BAAALgAECgMJAwAAAA==.Durgi:BAABLgAECn8XAAIRAAcJUhs+JQD8AQdoDAAAAgBBAGkMAAAFAGAAawwAAAQAVABqDAAABQBFAGwMAAADAC4A6gwAAAMAVQBuDAAAAQAoABEABwlSGz4lAPwBB2gMAAACAEEAaQwAAAUAYABrDAAABABUAGoMAAAFAEUAbAwAAAMALgDqDAAAAwBVAG4MAAABACgAAAA=.Durtrim:BAAALgADCgIJAgAAAA==.',
Ed='Ederen:BAAALgAECgEJAQAAAA==.',
Ee='Eepic:BAABLgAECn8pAAILAAgJjREKQwCGAQhoDAAABgApAGkMAAAGAEAAawwAAAYAPABqDAAABQAoAGwMAAAFADEAbQwAAAIAEADqDAAABwAvAG4MAAAEACMACwAICY0RCkMAhgEIaAwAAAYAKQBpDAAABgBAAGsMAAAGADwAagwAAAUAKABsDAAABQAxAG0MAAACABAA6gwAAAcALwBuDAAABAAjAAAA.',
Ei='Eightmile:BAAALgAECgcJBwAAAA==.Eisenhorn:BAAALgADCgcJDAABLgAECgcJFgAPAKoUAA==.',
El='Elementfrost:BAAALgAECgEJAQAAAA==.Ellio:BAAALgADCgcJBwABLgAFFAUJEgANAGAcAA==.',
Em='Embar:BAAALgADCgIJAwAAAA==.Emrys:BAACLgAFFH8FAAIMAAIJQSK2JgDGAAJoDAAAAgBgAOoMAAADAE8ADAACCUEitiYAxgACaAwAAAIAYADqDAAAAwBPAC4ABAp/FQADDAAHCS8kNRgAQwIADAAHCS8kNRgAQwIAFgAECbwMFFIAygAAAAA=.',
Ep='Epinephrine:BAAALgAECggJDgAAAA==.',
Er='Eriebus:BAABLgAECn8aAAIXAAgJ5gskRgAvAQhoDAAABQApAGkMAAAEAB4AawwAAAQALwBqDAAAAwA0AGwMAAACAA8AbQwAAAIAHQDqDAAABAAbAG4MAAACABUAFwAICeYLJEYALwEIaAwAAAUAKQBpDAAABAAeAGsMAAAEAC8AagwAAAMANABsDAAAAgAPAG0MAAACAB0A6gwAAAQAGwBuDAAAAgAVAAAA.Erona:BAAALgAECgUJBQAAAA==.',
Es='Escorpiøn:BAACLgAFFH8KAAITAAQJJxuDJgBXAQRoDAAABABHAGkMAAADADMAawwAAAEAQQDqDAAAAgBZABMABAknG4MmAFcBBGgMAAAEAEcAaQwAAAMAMwBrDAAAAQBBAOoMAAACAFkALgAECn8iAAITAAgJZiD+LACFAgATAAgJZiD+LACFAgAAAA==.',
Ev='Evenstar:BAAALgAECgEJAQAAAA==.',
Fa='Faling:BAAALgADCgYJEQAAAA==.Falkor:BAAALgAECgcJEAABLgAECgcJEwAHAAAAAA==.Fartcloud:BAAALgAECgQJBAAAAA==.Fatigued:BAAALgAECggJDQAAAA==.',
Fe='Feech:BAAALgAECgUJCwABLgAFFAMJCAAYAFobAA==.Felagain:BAABLgAECn8cAAIZAAgJ6AonCwAkAQhoDAAABQAcAGkMAAAFABIAawwAAAQAKgBqDAAABAArAGwMAAADAB0AbQwAAAEAFgDqDAAABQAeAG4MAAABABcAGQAICegKJwsAJAEIaAwAAAUAHABpDAAABQASAGsMAAAEACoAagwAAAQAKwBsDAAAAwAdAG0MAAABABYA6gwAAAUAHgBuDAAAAQAXAAAA.Felslizer:BAAALgAECgMJAwAAAA==.Ferrous:BAAALgAECgEJAQAAAA==.',
Fl='Flankshot:BAABLgAECn8cAAIJAAkJFQ28UgB7AQloDAAABQApAGkMAAAEACUAawwAAAQAKABqDAAAAwAbAGwMAAADABoAbQwAAAIAHQDqDAAAAwAfAG4MAAADACwAbwwAAAEAEQAJAAkJFQ28UgB7AQloDAAABQApAGkMAAAEACUAawwAAAQAKABqDAAAAwAbAGwMAAADABoAbQwAAAIAHQDqDAAAAwAfAG4MAAADACwAbwwAAAEAEQAAAA==.Flo:BAAALgADCgUJBgABLgAECgYJBQAHAAAAAA==.Flõ:BAAALgAECgQJBAAAAA==.',
Fo='Foops:BAACLgAFFH8bAAIJAAcJDBcpBAAvAgdoDAAABQBbAGkMAAAFAEkAawwAAAQATgBqDAAAAwBOAGwMAAACACIAbQwAAAEAAADqDAAABwBLAAkABwkMFykEAC8CB2gMAAAFAFsAaQwAAAUASQBrDAAABABOAGoMAAADAE4AbAwAAAIAIgBtDAAAAQAAAOoMAAAHAEsALgAECn8XAAIJAAgJYR0iRgBlAgAJAAgJYR0iRgBlAgAAAA==.Foopsadin:BAAALgAECgYJDQABLgAFFAcJGwAJAAwXAA==.',
Fu='Fumin:BAAALgAECgQJBwAAAA==.',
Ga='Galibuk:BAAALgADCgYJBgAAAA==.',
Ge='Geezuss:BAAALgAECgEJBAABLgAECgYJGQAaAJUfAA==.Genohbreaker:BAAALgADCgUJBAAAAA==.Getrkt:BAAALgAECgQJBAAAAA==.',
Gh='Ghouliver:BAABLgAECn8mAAITAAgJPhhzLADVAQhoDAAABwBMAGkMAAAGAEQAawwAAAYASwBqDAAABQBTAGwMAAAFAEAAbQwAAAIAJwDqDAAABQA1AG4MAAACADgAEwAICT4YcywA1QEIaAwAAAcATABpDAAABgBEAGsMAAAGAEsAagwAAAUAUwBsDAAABQBAAG0MAAACACcA6gwAAAUANQBuDAAAAgA4AAAA.',
Gi='Gigasushi:BAAALgAECgQJBAAAAA==.Gimblie:BAABLgAECn8aAAIEAAcJ2hZGGQCMAQdoDAAABQBGAGkMAAAFAFEAawwAAAUASABqDAAAAwAsAGwMAAADACQA6gwAAAQAPwBuDAAAAQAoAAQABwnaFkYZAIwBB2gMAAAFAEYAaQwAAAUAUQBrDAAABQBIAGoMAAADACwAbAwAAAMAJADqDAAABAA/AG4MAAABACgAAAA=.Gimermonty:BAABLgAECn8jAAINAAkJnxurEABUAgloDAAABgBQAGkMAAAFAE4AawwAAAUASQBqDAAABABDAGwMAAAEAC8AbQwAAAMAQADqDAAABABOAG4MAAADAFkAbwwAAAEANQANAAkJnxurEABUAgloDAAABgBQAGkMAAAFAE4AawwAAAUASQBqDAAABABDAGwMAAAEAC8AbQwAAAMAQADqDAAABABOAG4MAAADAFkAbwwAAAEANQAAAA==.Ging:BAAALgADCgcJCAAAAA==.',
Gl='Glorfindel:BAAALgAECgcJCAAAAA==.',
Go='Goblinkicker:BAAALgAECgMJBAAAAA==.Gothegg:BAAALgAECgEJAgAAAA==.Gothmommy:BAABLgAECn8eAAIIAAgJTQqlRgBaAQhoDAAABQAjAGkMAAAFACIAawwAAAUAGgBqDAAABAAiAGwMAAAEACAAbQwAAAEAEQDqDAAABAAVAG4MAAACAA8ACAAICU0KpUYAWgEIaAwAAAUAIwBpDAAABQAiAGsMAAAFABoAagwAAAQAIgBsDAAABAAgAG0MAAABABEA6gwAAAQAFQBuDAAAAgAPAAAA.',
Gr='Gronk:BAAALgAECgIJAgAAAA==.',
Gu='Guldanshower:BAABLgAECn8hAAMSAAgJlRpDDgDjAQhoDAAABgBXAGkMAAAGAEUAawwAAAUAVQBqDAAABABPAGwMAAADAEgAbQwAAAMAOQDqDAAABABIAG4MAAACAB8AEgAGCSccQw4A4wEGaAwAAAMAVwBpDAAAAwBFAGsMAAAEAFUAagwAAAQATwBsDAAAAQAuAOoMAAABAEgACAAHCagWlCcAzwEHaAwAAAMARwBpDAAAAwBFAGsMAAABADoAbAwAAAIASABtDAAAAwA5AOoMAAADACwAbgwAAAIAHwAAAA==.',
Ha='Habusaki:BAAALgAECgQJBgAAAA==.Hakal:BAABLgAECn8cAAIbAAgJshX+CgB9AQhoDAAABQBIAGkMAAAEADUAawwAAAQAMABqDAAAAwAxAGwMAAADACwAbQwAAAUANQDqDAAAAwA6AG4MAAABADoAGwAICbIV/goAfQEIaAwAAAUASABpDAAABAA1AGsMAAAEADAAagwAAAMAMQBsDAAAAwAsAG0MAAAFADUA6gwAAAMAOgBuDAAAAQA6AAAA.Halvor:BAAALgAECgQJCAAAAA==.Hangbladz:BAAALgAECgcJEwAAAA==.Hardwarë:BAAALgADCgcJCAAAAA==.Harrygazm:BAAALgADCgQJBAAAAA==.',
Hu='Hukdemon:BAABLgAECn8aAAIZAAgJNSQXAQDMAghoDAAABQBgAGkMAAAEAGEAawwAAAQAYQBqDAAAAwBiAGwMAAACAGIAbQwAAAIATgDqDAAABABbAG4MAAACAFkAGQAICTUkFwEAzAIIaAwAAAUAYABpDAAABABhAGsMAAAEAGEAagwAAAMAYgBsDAAAAgBiAG0MAAACAE4A6gwAAAQAWwBuDAAAAgBZAAAA.',
Ic='Iceandfire:BAAALgAECgEJAQAAAA==.',
Il='Illiyana:BAAALgAECgUJBQAAAA==.',
In='Inviteme:BAAALgADCgMJAwABLgAECggJIQATACcaAA==.',
Ja='Jakesterwars:BAAALgADCgEJAQAAAA==.Jaldore:BAAALgADCgcJBwAAAA==.',
Je='Jeaine:BAAALgADCgEJAgAAAA==.',
Jh='Jhamin:BAACLgAFFH8HAAIVAAMJfgnhKgC1AANoDAAAAwAXAGkMAAABACIA6gwAAAMADgAVAAMJfgnhKgC1AANoDAAAAwAXAGkMAAABACIA6gwAAAMADgAuAAQKfx4AAxUACAmjFXMiABACABUACAmjFXMiABACABQABAmNGM8zAOwAAAAA.',
Ji='Jiveturkey:BAAALgAECgQJAwAAAA==.',
Ju='Jubeiskyfang:BAAALgAECgcJCAABLgAFFAQJBQALAEMPAA==.Julkaal:BAAALgAECgEJAQAAAA==.Junlelon:BAAALgAECgEJAQAAAA==.',
Ka='Kaedrelyn:BAAALgAECgEJAQAAAA==.Kai:BAAALgAECgYJBwAAAA==.Karnage:BAAALgAECgUJBgAAAA==.Karney:BAAALgAECgEJAgAAAA==.Kazam:BAAALgAECgYJBgAAAA==.Kazik:BAABLgAECn8ZAAIXAAcJaBt4IwC9AQdoDAAABQBVAGkMAAAEAFIAawwAAAQAOwBqDAAABABdAGwMAAADAD0AbQwAAAEAOADqDAAABABMABcABwloG3gjAL0BB2gMAAAFAFUAaQwAAAQAUgBrDAAABAA7AGoMAAAEAF0AbAwAAAMAPQBtDAAAAQA4AOoMAAAEAEwAAAA=.',
Ke='Kelrath:BAABLgAECn8lAAIcAAgJvw6gKQCRAQhoDAAABgARAGkMAAAFAC4AawwAAAUAHABqDAAABQBWAGwMAAAFAB0AbQwAAAIAEgDqDAAABgA1AG4MAAADABYAHAAICb8OoCkAkQEIaAwAAAYAEQBpDAAABQAuAGsMAAAFABwAagwAAAUAVgBsDAAABQAdAG0MAAACABIA6gwAAAYANQBuDAAAAwAWAAAA.Kelthugan:BAAALgADCgIJAgAAAA==.Kendeez:BAAALgADCgcJCwAAAA==.Kenparrchi:BAAALgAECgIJAwAAAA==.Kensei:BAAALgADCgIJAgABLgAECgkJFQALAA4UAA==.Ketheric:BAAALgADCgYJCAAAAA==.',
Ki='Kindinos:BAAALgAECgYJDwAAAA==.',
Kl='Kllcky:BAABLgAECn8WAAILAAgJZyLABwDdAghoDAAAAwBbAGkMAAADAF8AawwAAAQAXgBqDAAAAgBjAGwMAAADAGAA6gwAAAMAXgBuDAAAAwBjAG8MAAABACwACwAICWciwAcA3QIIaAwAAAMAWwBpDAAAAwBfAGsMAAAEAF4AagwAAAIAYwBsDAAAAwBgAOoMAAADAF4AbgwAAAMAYwBvDAAAAQAsAAEuAAUUAwkIABgAWhsA.Klorox:BAAALgAECgIJAgAAAA==.',
Kr='Kraoptix:BAAALgADCgYJCAAAAA==.Kratøs:BAAALgADCgMJAwAAAA==.Kraun:BAABLgAECn8fAAMdAAcJnSHUCwATAgdoDAAABQBaAGkMAAAGAFgAawwAAAYAWgBqDAAABQBVAGwMAAAEAFEAbQwAAAEATADqDAAABABYAB0ABglUItQLABMCBmgMAAAFAFoAaQwAAAUAWABrDAAABABaAGoMAAAFAFUAbAwAAAQAUQDqDAAABABYAA0AAwltHjtaAAMBA2kMAAABAFEAawwAAAIASwBtDAAAAQBMAAAA.Kreig:BAAALgADCgIJAgAAAA==.Kroo:BAAALgAECgYJDQABLgAECggJIQABAFYXAA==.Krythas:BAAALgADCgIJAgAAAA==.',
Ku='Kuwabara:BAAALgADCgUJBQAAAA==.',
Kv='Kvothè:BAAALgAECgYJDAAAAA==.',
Ky='Kyi:BAABLgAECn8eAAIWAAkJhBE2FgCEAQloDAAABQA+AGkMAAAEACkAawwAAAQAOgBqDAAABABCAGwMAAAEADYAbQwAAAIADQDqDAAAAwAeAG4MAAADADwAbwwAAAEAJQAWAAkJhBE2FgCEAQloDAAABQA+AGkMAAAEACkAawwAAAQAOgBqDAAABABCAGwMAAAEADYAbQwAAAIADQDqDAAAAwAeAG4MAAADADwAbwwAAAEAJQAAAA==.',
['Kî']='Kîrîto:BAAALgAECgIJBQABLgAECggJFAAJAGMeAA==.',
La='Lactosetwo:BAAALgAECgEJAgAAAA==.Lammlock:BAAALgAECgIJAgAAAA==.Landar:BAABLgAECn8zAAIcAAkJbxNDGgD+AQloDAAABwBCAGkMAAAHADsAawwAAAcARwBqDAAABgBDAGwMAAAGADkAbQwAAAUAFgDqDAAABwAuAG4MAAAEACgAbwwAAAIADwAcAAkJbxNDGgD+AQloDAAABwBCAGkMAAAHADsAawwAAAcARwBqDAAABgBDAGwMAAAGADkAbQwAAAUAFgDqDAAABwAuAG4MAAAEACgAbwwAAAIADwAAAA==.Lathindra:BAAALgAECgEJAgAAAA==.Lazerpony:BAAALgAECgEJAwABLgAECgQJBwAHAAAAAA==.',
Le='Lefordini:BAAALgAECgEJAQAAAA==.Leggomyâggro:BAAALgAECgcJDwABLgAFFAQJDwANALkSAA==.Lexicon:BAAALgAECgMJAwAAAA==.',
Li='Liara:BAABLgAECn8fAAIdAAgJHw3EDwC4AQhoDAAABAAZAGkMAAAEACEAawwAAAQAJgBqDAAABAAiAGwMAAAEABgAbQwAAAIADwDqDAAABQAfAG4MAAAEAEMAHQAICR8NxA8AuAEIaAwAAAQAGQBpDAAABAAhAGsMAAAEACYAagwAAAQAIgBsDAAABAAYAG0MAAACAA8A6gwAAAUAHwBuDAAABABDAAAA.Lireesa:BAABLgAECn8jAAISAAgJmRD3BgCEAQhoDAAABgAeAGkMAAAGAC8AawwAAAYAMwBqDAAABAATAGwMAAAEADgAbQwAAAIADADqDAAABgA6AG4MAAABACgAEgAICZkQ9wYAhAEIaAwAAAYAHgBpDAAABgAvAGsMAAAGADMAagwAAAQAEwBsDAAABAA4AG0MAAACAAwA6gwAAAYAOgBuDAAAAQAoAAAA.Lithiandriel:BAAALgAECgYJEgAAAA==.Liçk:BAAALgAECgMJAwABLgAECggJHAAcADkcAA==.',
Lo='Lockonyou:BAAALgAECgYJEQAAAA==.Logeofford:BAAALgADCgYJBQAAAA==.Lolola:BAAALgAECgQJBAAAAA==.Losthack:BAAALgAECgEJAQAAAA==.',
Lu='Lucker:BAAALgAECgEJAQAAAA==.Lunn:BAABLgAECn8YAAIKAAcJug+lDQAZAQdoDAAAAwAkAGkMAAAFADgAawwAAAQALwBqDAAAAwA3AGwMAAAEACgA6gwAAAQAKABuDAAAAQAUAAoABwm6D6UNABkBB2gMAAADACQAaQwAAAUAOABrDAAABAAvAGoMAAADADcAbAwAAAQAKADqDAAABAAoAG4MAAABABQAAAA=.Lurac:BAAALgAECgEJAQABLgAFFAEJAQAHAAAAAA==.',
Ma='Madhi:BAAALgADCgcJDQAAAA==.Mahk:BAABLgAECn8UAAILAAcJixUVQQCMAQdoDAAABQA3AGkMAAADAD8AawwAAAQARgBqDAAAAgAqAGwMAAACADMAbQwAAAEABQDqDAAAAwBTAAsABwmLFRVBAIwBB2gMAAAFADcAaQwAAAMAPwBrDAAABABGAGoMAAACACoAbAwAAAIAMwBtDAAAAQAFAOoMAAADAFMAAAA=.Majin:BAAALgAECgMJAwABLgAECgkJFQALAA4UAA==.Mangreese:BAABLgAECn8cAAIeAAkJ7g4lBwDMAQloDAAABAAmAGkMAAAEACoAawwAAAQALQBqDAAABAAwAGwMAAADABYAbQwAAAEABADqDAAABQA0AG4MAAACACkAbwwAAAEAOQAeAAkJ7g4lBwDMAQloDAAABAAmAGkMAAAEACoAawwAAAQALQBqDAAABAAwAGwMAAADABYAbQwAAAEABADqDAAABQA0AG4MAAACACkAbwwAAAEAOQAAAA==.Matelk:BAAALgAECgEJAgAAAA==.',
Me='Meekseek:BAAALgAECgQJDgAAAA==.Meltdown:BAAALgADCgQJBAAAAA==.Memoo:BAAALgADCgUJBQAAAA==.',
Mi='Miahealifa:BAABLgAECn8YAAMaAAcJOQvcJwD8AAdoDAAABQATAGkMAAAFACMAawwAAAQAEgBqDAAAAwAuAGwMAAADACMAbQwAAAIAEQDqDAAAAgAbAAQABgmACVtHABwBBmgMAAACABMAaQwAAAEAFQBrDAAAAQAJAGoMAAACAC4AbAwAAAEAFADqDAAAAgAbABoABgksCdwnAPwABmgMAAADAA8AaQwAAAQAIwBrDAAAAwASAGoMAAABABEAbAwAAAIAIwBtDAAAAgARAAAA.Milim:BAAALgAECgUJBQAAAA==.Miloh:BAAALgAECgEJAwAAAA==.Mistabubbles:BAAALgAECgYJBgAAAA==.Mistmia:BAAALgADCgUJBQAAAA==.Mixmasterg:BAABLgAECn8eAAIXAAgJFgy/PwBDAQhoDAAABQAxAGkMAAAEABkAawwAAAQAFQBqDAAABAA5AGwMAAAEACgAbQwAAAEAEQDqDAAABgAhAG4MAAACABsAFwAICRYMvz8AQwEIaAwAAAUAMQBpDAAABAAZAGsMAAAEABUAagwAAAQAOQBsDAAABAAoAG0MAAABABEA6gwAAAYAIQBuDAAAAgAbAAAA.',
Mo='Mograinez:BAACLgAFFH8ZAAITAAcJdCVyAACEAgdoDAAABABiAGkMAAAFAGMAawwAAAMAXwBqDAAAAwBfAGwMAAACAFoAbQwAAAEAXADqDAAABwBjABMABwl0JXIAAIQCB2gMAAAEAGIAaQwAAAUAYwBrDAAAAwBfAGoMAAADAF8AbAwAAAIAWgBtDAAAAQBcAOoMAAAHAGMALgAECn8VAAITAAgJfSajHADTAgATAAgJfSajHADTAgAAAA==.Monkeyman:BAAALgADCgIJAgAAAA==.Moosebreath:BAAALgAECgQJBAABLgAECgcJFQAaAFwfAA==.',
Mu='Murderer:BAAALgAECgMJBgAAAA==.',
My='Mythunrus:BAABLgAECn8YAAIfAAYJIhI9MgBDAQZoDAAABgBAAGkMAAAGAC0AawwAAAQALABqDAAAAwAUAGwMAAADACYA6gwAAAIAJwAfAAYJIhI9MgBDAQZoDAAABgBAAGkMAAAGAC0AawwAAAQALABqDAAAAwAUAGwMAAADACYA6gwAAAIAJwAAAA==.',
['Mó']='Móñk:BAAALgAECgcJEgAAAA==.',
['Mö']='Mörgana:BAAALgADCgQJBAAAAA==.',
Na='Narofu:BAAALgADCgQJBAAAAA==.Nazurasar:BAAALgAECgMJAwAAAA==.',
Ne='Nejìre:BAAALgADCgYJCQAAAA==.Neteyam:BAAALgAECgEJAQAAAA==.Neutron:BAAALgAECgIJBAAAAA==.',
No='Norolock:BAABLgAECn8aAAIIAAgJlRY1JgDWAQhoDAAABQBNAGkMAAAEACgAawwAAAQAPgBqDAAAAwA+AGwMAAACACAAbQwAAAIAOQDqDAAABABBAG4MAAACAEMACAAICZUWNSYA1gEIaAwAAAUATQBpDAAABAAoAGsMAAAEAD4AagwAAAMAPgBsDAAAAgAgAG0MAAACADkA6gwAAAQAQQBuDAAAAgBDAAAA.Notbreeze:BAAALgADCgYJBgAAAA==.Notsure:BAAALgAECgcJBwAAAA==.',
Nu='Nuero:BAAALgAFFAIJAgAAAA==.Nukashine:BAAALgADCgYJCAAAAA==.Nuuro:BAAALgAECgcJEgAAAA==.',
Ny='Ny:BAAALgADCgUJBQAAAA==.Nyverra:BAAALgADCgQJBAAAAA==.',
['Nã']='Nãrcissus:BAACLgAFFH8IAAMYAAMJWhtZAwBfAANoDAAAAwArAGkMAAADAE4A6gwAAAIAWAAIAAIJrxniWACkAAJoDAAAAwArAOoMAAACAFgAGAABCa8eWQMAXwABaQwAAAMATgAuAAQKfyYABAgACAnNH+EpAMQBAAgABglgH+EpAMQBABIABAkoF3MuAAIBABgAAwnQIDAWANEAAAAA.',
Ol='Oldshotz:BAAALgAECgYJDAAAAA==.',
Om='Omgsteak:BAAALgAECgUJCQAAAA==.',
On='Onapalehorse:BAAALgADCgUJCgAAAA==.Onger:BAAALgADCgEJAQAAAA==.Onlybusa:BAAALgAECgEJAwAAAA==.Ons:BAAALgAECgQJBAAAAA==.',
Ow='Owl:BAAALgAECgEJAQABLgAECgcJGQALAJMTAA==.',
Pa='Panpots:BAAALgADCgYJBgAAAA==.Panzerdox:BAAALgAECgUJBQAAAA==.Panzerwolf:BAECLgAFFH8WAAIQAAQJLCVmAgC5AQRoDAAABwBhAGkMAAAGAFwAawwAAAMAXADqDAAABgBhABAABAksJWYCALkBBGgMAAAHAGEAaQwAAAYAXABrDAAAAwBcAOoMAAAGAGEALgAECn9PAAMQAAkJESZkAADQAwAQAAkJESZkAADQAwADAAUJhgdqbwD6AAAAAA==.Patchnotes:BAAALgAECgYJCwAAAA==.',
Pe='Peepaw:BAAALgAFFAIJAgAAAA==.',
Po='Poorclass:BAAALgADCgcJCAAAAA==.',
Pr='Prayforme:BAABLgAECn8bAAIaAAgJAhx2BgCZAghoDAAABQBRAGkMAAAEAFQAawwAAAQATQBqDAAABABdAGwMAAAEAEsAbQwAAAEAIADqDAAABABSAG4MAAABAC0AGgAICQIcdgYAmQIIaAwAAAUAUQBpDAAABABUAGsMAAAEAE0AagwAAAQAXQBsDAAABABLAG0MAAABACAA6gwAAAQAUgBuDAAAAQAtAAAA.Prettynails:BAAALgAECggJDwAAAA==.Prise:BAABLgAECn8WAAMSAAcJOREEGwB1AQdoDAAABAA4AGkMAAADADMAawwAAAMALgBqDAAAAwAoAGwMAAACACoAbQwAAAEADgDqDAAABgA1ABIABwm+EAQbAHUBB2gMAAADADgAaQwAAAIAMwBrDAAAAgAuAGoMAAACAAMAbAwAAAEAKgBtDAAAAQAOAOoMAAADAC4ACAAGCUcOEo8ArwAGaAwAAAEAIABpDAAAAQAlAGsMAAABABQAagwAAAEAKABsDAAAAQAmAOoMAAADADUAAAA=.',
Ps='Psilocybic:BAABLgAECn8aAAMVAAkJdQmoSQBbAQloDAAAAwAfAGkMAAADAB4AawwAAAMACABqDAAAAwAWAGwMAAADABUAbQwAAAIABADqDAAABQASAG4MAAADAC8AbwwAAAEAIAAVAAkJdQmoSQBbAQloDAAAAgAfAGkMAAACAB4AawwAAAIACABqDAAAAgAWAGwMAAACABUAbQwAAAEABADqDAAABQASAG4MAAADAC8AbwwAAAEAIAAUAAYJ4wfoTwAHAQZoDAAAAQADAGkMAAABABEAawwAAAEAMgBqDAAAAQAOAGwMAAABABkAbQwAAAEABAAAAA==.',
Qw='Qweh:BAAALgAECgYJDwAAAA==.',
Ra='Rahnko:BAAALgAECgQJAgAAAA==.Rakkasei:BAACLgAFFH8FAAIBAAIJWweSMgCJAAJoDAAAAwARAOoMAAACABQAAQACCVsHkjIAiQACaAwAAAMAEQDqDAAAAgAUAC4ABAp/HgADAQAJCbkXtgwACwIAAQAJCbkXtgwACwIADwADCf4E9TIAfgAAAAA=.Ralthas:BAAALgAECgQJBAAAAA==.Randark:BAABLgAECn8nAAQCAAgJhRr3CgD0AQhoDAAABgBaAGkMAAAGAD8AawwAAAYARwBqDAAABQBMAGwMAAAGAEUAbQwAAAEAGgDqDAAABQBSAG4MAAAEAEYAAgAGCQsd9woA9AEGaAwAAAMAWgBpDAAABAA/AGsMAAADAEAAagwAAAIATADqDAAAAwBSAG4MAAADAEYAAwAHCdIPN08AagEHaAwAAAIASABpDAAAAQAnAGsMAAACAAkAagwAAAIASgBsDAAAAwBEAG0MAAABABoA6gwAAAIAGgAQAAYJOxQjFwANAQZoDAAAAQAsAGkMAAABADYAawwAAAEARwBqDAAAAQApAGwMAAADAEUAbgwAAAEAEgAAAA==.Ravenoth:BAAALgAECgEJAQAAAA==.Razkal:BAAALgAECgYJDQAAAA==.Razzlock:BAAALgADCgcJBwAAAA==.',
Re='Reshiiram:BAAALgAECgEJAQAAAA==.Retneprac:BAAALgADCgQJBAAAAA==.Revirginator:BAABLgAECn8bAAMgAAcJ3Ab8JADgAAdoDAAABgAoAGkMAAAFABMAawwAAAQAEQBqDAAAAwAYAGwMAAADAAYAbQwAAAEABADqDAAABQARACAABwk+BvwkAOAAB2gMAAAGACgAaQwAAAUAEwBrDAAABAARAGoMAAADABgAbAwAAAMABgBtDAAAAQAEAOoMAAACAAgACwABCeQGMVIBKwAB6gwAAAMAEQAAAA==.Revna:BAAALgAECgEJAwAAAA==.',
Rh='Rhagnar:BAAALgAECgQJBAAAAA==.',
Ri='Richandfamus:BAAALgAECgUJCwAAAA==.Riftstalker:BAAALgAECgcJEwAAAA==.',
Rn='Rngesus:BAACLgAFFH8FAAIIAAMJbApyTgDEAANoDAAAAwAvAGkMAAABAAYA6gwAAAEAGQAIAAMJbApyTgDEAANoDAAAAwAvAGkMAAABAAYA6gwAAAEAGQAuAAQKfyUAAwgACQl4HtsSAFMCAAgACQl4HtsSAFMCABIAAgliBsBWAGoAAAAA.',
Ro='Rocmaul:BAAALgADCgkJCQAAAA==.',
Ru='Rushem:BAAALgAECggJEwAAAA==.Ruwa:BAAALgADCgUJBQAAAA==.',
Ry='Ryft:BAABLgAECn8XAAITAAgJzBaIZAAmAQhoDAAABABEAGkMAAAEAEMAawwAAAUAOwBqDAAAAgA1AGwMAAACAE0AbQwAAAEAJgDqDAAAAwA1AG4MAAACACsAEwAICcwWiGQAJgEIaAwAAAQARABpDAAABABDAGsMAAAFADsAagwAAAIANQBsDAAAAgBNAG0MAAABACYA6gwAAAMANQBuDAAAAgArAAAA.Ryhaz:BAAALgADCgcJBwAAAA==.',
Sa='Saenen:BAABLgAECn8WAAIhAAcJuQv0EQALAQdoDAAABQAmAGkMAAAFACcAawwAAAQAGgBqDAAAAwAnAGwMAAACAC4AbQwAAAEADgDqDAAAAgAOACEABwm5C/QRAAsBB2gMAAAFACYAaQwAAAUAJwBrDAAABAAaAGoMAAADACcAbAwAAAIALgBtDAAAAQAOAOoMAAACAA4AAAA=.Sandrozarke:BAABLgAECn8hAAQBAAgJVhc4EQBmAghoDAAABQBOAGkMAAAFAEIAawwAAAUATQBqDAAABABdAGwMAAAEADsAbQwAAAMAIQDqDAAABQAwAG4MAAACADYAAQAICT8XOBEAZgIIaAwAAAUATgBpDAAABQBCAGsMAAAFAE0AagwAAAQAXQBsDAAABAA7AG0MAAACACEA6gwAAAQALgBuDAAAAgA2AA8AAQn5Elc8ADwAAeoMAAABADAADgABCcoCakcAOAABbQwAAAEABwAAAA==.Sarah:BAAALgAECgIJAgABLgAECgkJMgAaALkdAA==.',
Sc='Scrublet:BAAALgAECgYJDgAAAA==.',
Se='Seldara:BAABLgAECn8fAAMTAAgJzwV/jQDTAAhoDAAABgAcAGkMAAAGABMAawwAAAYADwBqDAAABAAOAGwMAAADAAUAbQwAAAEABADqDAAABAAZAG4MAAABAAQAEwAICWkDf40A0wAIaAwAAAMACwBpDAAAAwAQAGsMAAAEAAgAagwAAAQADgBsDAAAAwAFAG0MAAABAAQA6gwAAAIACQBuDAAAAQAEACIABAnDCKcOALkABGgMAAADABwAaQwAAAMAEwBrDAAAAgAPAOoMAAACABkAAAA=.Seraphic:BAAALgAECgkJAwAAAA==.Serenity:BAABLgAECn8XAAIaAAQJZyHYGAB7AQRoDAAABgBXAGkMAAAFAFcAawwAAAUAVgDqDAAABwBRABoABAlnIdgYAHsBBGgMAAAGAFcAaQwAAAUAVwBrDAAABQBWAOoMAAAHAFEAAAA=.Sergeyred:BAAALgADCgUJBQAAAA==.Serlyn:BAAALgAECgYJEAAAAA==.Seseria:BAABLgAECn8kAAMgAAkJ0RO5EgCfAQloDAAABgBGAGkMAAAFAEIAawwAAAUAQgBqDAAABQAwAGwMAAAFAB4AbQwAAAIAGgDqDAAABAArAG4MAAADABAAbwwAAAEAVAAgAAgJ6xG5EgCfAQhoDAAABgBGAGkMAAAFAEIAawwAAAUAQgBqDAAABAAwAGwMAAAEAB4AbQwAAAIAGgDqDAAAAwArAG4MAAABABAAEQAFCWIVcSoARwEFagwAAAEAKgBsDAAAAQAmAOoMAAABADQAbgwAAAIATgBvDAAAAQA+AAAA.Sevinofnine:BAAALgAECgEJAQAAAA==.',
Sh='Shalamar:BAAALgAECgEJBAAAAA==.Shanic:BAABLgAECn8YAAIjAAgJ0xd/DgDyAQhoDAAABABEAGkMAAAEADQAawwAAAQAQgBqDAAAAwAoAGwMAAACAD8AbQwAAAIAOwDqDAAAAwA2AG4MAAACAD0AIwAICdMXfw4A8gEIaAwAAAQARABpDAAABAA0AGsMAAAEAEIAagwAAAMAKABsDAAAAgA/AG0MAAACADsA6gwAAAMANgBuDAAAAgA9AAAA.Shiddybill:BAAALgAECgQJBAAAAA==.Shiftor:BAAALgADCgYJBgABLgAECgEJAQAHAAAAAA==.Shiftyslice:BAAALgAECgEJAgAAAA==.Shihiro:BAAALgADCgIJAQAAAA==.',
Si='Siberianbull:BAAALgADCgEJAQAAAA==.Siena:BAAALgAECgEJAQAAAA==.',
Sl='Slaveman:BAAALgADCgYJBgAAAA==.Slitherina:BAAALgADCgYJBgAAAA==.Slåkritisk:BAABLgAECn8XAAIdAAgJaA1PEgCdAQhoDAAABAAqAGkMAAADACsAawwAAAIALABqDAAAAgAgAGwMAAACABMAbQwAAAEAEgDqDAAABQA1AG4MAAAEABIAHQAICWgNTxIAnQEIaAwAAAQAKgBpDAAAAwArAGsMAAACACwAagwAAAIAIABsDAAAAgATAG0MAAABABIA6gwAAAUANQBuDAAABAASAAAA.',
Sm='Smitervane:BAAALgADCgcJDQAAAA==.Smogy:BAAALgAECgMJAwAAAA==.',
Sn='Snipyterror:BAAALgADCgEJAQAAAA==.Snoodly:BAABLgAECn8VAAIkAAgJhxBDGACdAQhoDAAABAA0AGkMAAADAEEAawwAAAMAJABqDAAAAgAwAGwMAAABACIAbQwAAAIADADqDAAABAAyAG4MAAACACUAJAAICYcQQxgAnQEIaAwAAAQANABpDAAAAwBBAGsMAAADACQAagwAAAIAMABsDAAAAQAiAG0MAAACAAwA6gwAAAQAMgBuDAAAAgAlAAAA.',
So='Solarice:BAABLgAECn8YAAMJAAgJxxyMGwBOAghoDAAABQBUAGkMAAAFAE0AawwAAAQATwBqDAAAAgBjAGwMAAACADEA6gwAAAQAVgBuDAAAAQBYAG8MAAABADAACQAICY0cjBsATgIIaAwAAAQAUABpDAAABQBNAGsMAAAEAE8AagwAAAIAYwBsDAAAAgAxAOoMAAAEAFYAbgwAAAEAWABvDAAAAQAwACUAAQnmIGQZAEwAAWgMAAABAFQAAAA=.Soletaken:BAAALgADCgQJBwAAAA==.Solunais:BAABLgAECn8iAAIIAAkJuwtNLgCwAQloDAAABQAwAGkMAAAEADMAawwAAAUAGQBqDAAABAAgAGwMAAAEABkAbQwAAAIAEwDqDAAABgAaAG4MAAADAB8AbwwAAAEACwAIAAkJuwtNLgCwAQloDAAABQAwAGkMAAAEADMAawwAAAUAGQBqDAAABAAgAGwMAAAEABkAbQwAAAIAEwDqDAAABgAaAG4MAAADAB8AbwwAAAEACwAAAA==.Soramor:BAAALgADCgcJCAAAAA==.Sorynn:BAAALgAECgEJAQAAAA==.',
Sp='Spirallidan:BAABLgAECn8WAAIXAAkJDRMmSwDIAQloDAAAAwA3AGkMAAADADMAawwAAAMAMgBqDAAAAwApAGwMAAADADYAbQwAAAEAIADqDAAAAgA9AG4MAAADAEAAbwwAAAEAEwAXAAkJDRMmSwDIAQloDAAAAwA3AGkMAAADADMAawwAAAMAMgBqDAAAAwApAGwMAAADADYAbQwAAAEAIADqDAAAAgA9AG4MAAADAEAAbwwAAAEAEwAAAA==.Spy:BAAALgADCgQJBAAAAA==.',
St='Stardor:BAAALgAECgkJBwAAAA==.Staticprot:BAABLgAFFH8FAAIQAAQJzgsbEADGAARoDAAAAQAXAGkMAAABABkAagwAAAEAFgDqDAAAAgApABAABAnOCxsQAMYABGgMAAABABcAaQwAAAEAGQBqDAAAAQAWAOoMAAACACkAAAA=.Staticsrexar:BAAALgADCgcJBwABLgAFFAQJBQAQAM4LAA==.Stature:BAAALgAECgUJBQAAAA==.Stepbro:BAABLgAECn8hAAITAAgJJxpjHgAdAghoDAAABAA2AGkMAAAGAEcAawwAAAUASABqDAAAAwBOAGwMAAAGAFoAbQwAAAEAEgDqDAAABgBbAG4MAAACAEQAEwAICScaYx4AHQIIaAwAAAQANgBpDAAABgBHAGsMAAAFAEgAagwAAAMATgBsDAAABgBaAG0MAAABABIA6gwAAAYAWwBuDAAAAgBEAAAA.Stinksauce:BAACLgAFFH8OAAIOAAQJTR7vCwBgAQRoDAAABABNAGkMAAAEAEoAawwAAAMARgDqDAAAAwBXAA4ABAlNHu8LAGABBGgMAAAEAE0AaQwAAAQASgBrDAAAAwBGAOoMAAADAFcALgAECn8aAAQOAAkJBxptDQBgAgAOAAkJBxptDQBgAgABAAEJdAbOYQA1AAAPAAEJrweAPwAyAAAAAA==.Stormvetra:BAAALgAECgQJBQAAAA==.',
Su='Supabox:BAAALgAECgcJEgABLgAFFAUJEwAMAKkjAA==.Superchunk:BAAALgAECgEJAQAAAA==.Suryoudie:BAAALgADCgQJBAAAAA==.Sutra:BAABLgAECn8YAAIEAAcJYwvfJgAdAQdoDAAABAA3AGkMAAAEAB4AawwAAAQAHgBqDAAABAAgAGwMAAADABIAbQwAAAEABgDqDAAABAAeAAQABwljC98mAB0BB2gMAAAEADcAaQwAAAQAHgBrDAAABAAeAGoMAAAEACAAbAwAAAMAEgBtDAAAAQAGAOoMAAAEAB4AAAA=.',
Sw='Swiftmend:BAAALgAECgYJBgABLgAECggJDQAHAAAAAA==.',
Sy='Sylmarillion:BAABLgAECn8bAAIRAAgJlhZaEwAEAghoDAAABQBJAGkMAAAFAEwAawwAAAQAUgBqDAAABABNAGwMAAADACgAbQwAAAEAEADqDAAABABKAG4MAAABABMAEQAICZYWWhMABAIIaAwAAAUASQBpDAAABQBMAGsMAAAEAFIAagwAAAQATQBsDAAAAwAoAG0MAAABABAA6gwAAAQASgBuDAAAAQATAAAA.',
['Sø']='Sørry:BAABLgAECn8XAAIMAAcJkRn0EADHAQdoDAAAAwA8AGkMAAAFAFIAawwAAAQARgBqDAAAAwA3AGwMAAADAEcA6gwAAAQAQwBuDAAAAQAnAAwABwmRGfQQAMcBB2gMAAADADwAaQwAAAUAUgBrDAAABABGAGoMAAADADcAbAwAAAMARwDqDAAABABDAG4MAAABACcAAAA=.',
Ta='Talgulen:BAABLgAECn8sAAIPAAkJXh3iAADCAgloDAAABwBeAGkMAAAGAFgAawwAAAYARgBqDAAABgBWAGwMAAAGAE8AbQwAAAMAPwDqDAAABgBdAG4MAAADADYAbwwAAAEAOAAPAAkJXh3iAADCAgloDAAABwBeAGkMAAAGAFgAawwAAAYARgBqDAAABgBWAGwMAAAGAE8AbQwAAAMAPwDqDAAABgBdAG4MAAADADYAbwwAAAEAOAAAAA==.Tankytauren:BAABLgAECn8kAAMTAAgJ9RJvMwC3AQhoDAAABQA1AGkMAAAFADoAawwAAAUAMwBqDAAABQA1AGwMAAAFADEAbQwAAAQAMADqDAAABAAoAG4MAAADACUAEwAICRUSbzMAtwEIaAwAAAMANQBpDAAAAwA6AGsMAAADACMAagwAAAMANQBsDAAAAwAxAG0MAAAEADAA6gwAAAIAKABuDAAAAwAlACIABglFD7AIAFoBBmgMAAACAB0AaQwAAAIAMgBrDAAAAgAzAGoMAAACAB0AbAwAAAIAJgDqDAAAAgAaAAAA.Tarquinius:BAABLgAECn8mAAIfAAkJUQ/eDQCwAQloDAAABwA+AGkMAAAGADUAawwAAAUALQBqDAAABAAoAGwMAAAEACYAbQwAAAMAFADqDAAABgAsAG4MAAACABEAbwwAAAEAHgAfAAkJUQ/eDQCwAQloDAAABwA+AGkMAAAGADUAawwAAAUALQBqDAAABAAoAGwMAAAEACYAbQwAAAMAFADqDAAABgAsAG4MAAACABEAbwwAAAEAHgAAAA==.Tatianasoles:BAAALgAECgEJAQAAAA==.Taxii:BAAALgAECgUJCQABLgAECgkJLQADADYlAA==.',
Te='Telanastre:BAAALgAECgQJBwAAAA==.',
Th='Tharos:BAAALgADCgEJAgAAAA==.Theat:BAAALgAECgQJDAAAAA==.Theoeicke:BAAALgAECgYJBgABLgAECgkJHgAWAIQRAA==.Thibbledor:BAAALgADCgkJFAABLgAECgYJFAAUAOUSAA==.',
Ti='Tifferny:BAAALgAECgIJAwAAAA==.Tiffèrny:BAAALgADCgUJBQAAAA==.Tinydrunk:BAAALgADCggJCAAAAA==.',
To='Tondra:BAAALgAECgYJCQAAAA==.Tone:BAABLgAECn8XAAMjAAgJ+xNYLQCZAQhoDAAAAwA6AGkMAAADAD8AawwAAAQAPwBqDAAABAAzAGwMAAACACQAbQwAAAIADwDqDAAAAgA7AG4MAAADADwAIwAHCWkTWC0AmQEHaAwAAAIAOgBpDAAAAgA/AGsMAAACAD8AagwAAAEAMwBsDAAAAQAkAG0MAAABAA8AbgwAAAIAPAAcAAgJHw29YQAsAQhoDAAAAQAnAGkMAAABAAQAawwAAAIAUABqDAAAAwA+AGwMAAABAAoAbQwAAAEABQDqDAAAAgA2AG4MAAABAAsAAAA=.Tonkatruck:BAAALgAECgUJBAAAAA==.Totemlycool:BAABLgAECn8gAAQUAAgJGxWvIAAKAghoDAAABQBEAGkMAAAFAFUAawwAAAUATABqDAAABAAsAGwMAAAEADQAbQwAAAIACADqDAAABQAsAG4MAAACACoAFAAICQkUryAACgIIaAwAAAEAOABpDAAAAQBVAGsMAAABAEwAagwAAAEALABsDAAAAQAtAG0MAAABAAgA6gwAAAEALABuDAAAAgAqAB4ABgmVFwQSAJYBBmgMAAAEAEQAaQwAAAQARwBrDAAABABIAGoMAAADACMAbAwAAAMANADqDAAAAwAkABUAAgmEAZeTAE0AAm0MAAABAAQA6gwAAAEAAwABLgAECggJIQABAFYXAA==.',
Tr='Trappress:BAAALgAECgcJBwABLgAECgkJPAAcAIsbAA==.Treehuggër:BAAALgAECgIJAgAAAA==.Trowa:BAAALgAECgIJAgABLgAFFAEJAQAHAAAAAA==.Trowaz:BAAALgAFFAEJAQAAAA==.Truffles:BAAALgADCgQJBAABLgAECggJIQASAJUaAA==.Tryrah:BAABLgAFFH8TAAIjAAYJ3RNGBQCeAQZoDAAABAA4AGkMAAADACsAawwAAAQAQABqDAAAAwAZAGwMAAACAAYA6gwAAAMAUgAjAAYJ3RNGBQCeAQZoDAAABAA4AGkMAAADACsAawwAAAQAQABqDAAAAwAZAGwMAAACAAYA6gwAAAMAUgAAAA==.',
Tw='Twinsons:BAAALgADCgEJAQAAAA==.Twisty:BAAALgAECgQJBQABLgAFFAEJAQAHAAAAAA==.Twîsty:BAAALgAECgUJBgABLgAFFAEJAQAHAAAAAA==.',
Ty='Tygron:BAAALgADCgQJBAAAAA==.Tyleroth:BAABLgAECn8gAAIXAAkJYhKbKACiAQloDAAABQBIAGkMAAAFAD0AawwAAAUANwBqDAAABABJAGwMAAAEADIAbQwAAAEAEgDqDAAABAAyAG4MAAADACwAbwwAAAEAFgAXAAkJYhKbKACiAQloDAAABQBIAGkMAAAFAD0AawwAAAUANwBqDAAABABJAGwMAAAEADIAbQwAAAEAEgDqDAAABAAyAG4MAAADACwAbwwAAAEAFgAAAA==.Tyrasia:BAAALgAECgEJAgAAAA==.Tyrith:BAABLgAECn8WAAMDAAgJsxhFPgCrAQhoDAAABABMAGkMAAADAD8AawwAAAMASABqDAAAAwBVAGwMAAACAC4AbQwAAAIAJgDqDAAABABWAG4MAAABADsAAwAHCeIYRT4AqwEHaAwAAAQATABpDAAAAQA7AGsMAAABAD4AagwAAAMAVQBtDAAAAgAmAOoMAAAEAFYAbgwAAAEAOwACAAMJrRebIQDAAANpDAAAAgA/AGsMAAACAEgAbAwAAAIALgAAAA==.',
['Tö']='Töömis:BAABLgAECn8ZAAILAAcJkxOFfACBAQdoDAAABQA9AGkMAAAFADgAawwAAAQANwBqDAAABAA2AGwMAAADAC8AbQwAAAEAGADqDAAAAwA1AAsABwmTE4V8AIEBB2gMAAAFAD0AaQwAAAUAOABrDAAABAA3AGoMAAAEADYAbAwAAAMALwBtDAAAAQAYAOoMAAADADUAAAA=.',
Ug='Ugotgotpal:BAAALgAECgcJCAAAAA==.',
Ul='Ulazain:BAABLgAECn8sAAIDAAkJDx8XBADKAgloDAAABwBDAGkMAAAGAF8AawwAAAYAXQBqDAAABgBBAGwMAAAGADsAbQwAAAMAUwDqDAAABgBcAG4MAAADAD0AbwwAAAEAUgADAAkJDx8XBADKAgloDAAABwBDAGkMAAAGAF8AawwAAAYAXQBqDAAABgBBAGwMAAAGADsAbQwAAAMAUwDqDAAABgBcAG4MAAADAD0AbwwAAAEAUgAAAA==.',
Ur='Urza:BAAALgADCgYJDQAAAA==.',
Us='Usdaprime:BAABLgAECn8dAAIhAAgJqA03CgCNAQhoDAAAAgARAGkMAAAEABUAawwAAAQAMABqDAAAAwAWAGwMAAAHADoAbQwAAAEAHADqDAAABgAZAG4MAAACAC0AIQAICagNNwoAjQEIaAwAAAIAEQBpDAAABAAVAGsMAAAEADAAagwAAAMAFgBsDAAABwA6AG0MAAABABwA6gwAAAYAGQBuDAAAAgAtAAAA.',
Va='Valarjar:BAAALgADCgIJAgABLgADCgQJBAAHAAAAAA==.Vandene:BAAALgADCgEJAgAAAA==.',
Ve='Velderen:BAAALgAECgQJBAAAAA==.Vengance:BAAALgADCgMJAwAAAA==.Verstappen:BAAALgADCgEJAQAAAA==.',
Vi='Viì:BAABLgAECn8YAAILAAcJXgiPkADZAAdoDAAABQAXAGkMAAAFABoAawwAAAQAFwBqDAAAAwAPAGwMAAADABEAbQwAAAIACQDqDAAAAgAcAAsABwleCI+QANkAB2gMAAAFABcAaQwAAAUAGgBrDAAABAAXAGoMAAADAA8AbAwAAAMAEQBtDAAAAgAJAOoMAAACABwAAAA=.',
Vo='Volsunga:BAAALgAECgQJBwAAAA==.',
Wi='Wildling:BAAALgADCgMJAwAAAA==.Winda:BAAALgADCggJCQAAAA==.',
Wr='Wrease:BAAALgADCgQJBQAAAA==.',
Xa='Xam:BAAALgAECgYJEgAAAA==.Xaphyre:BAAALgADCgEJAQAAAA==.Xarthas:BAAALgAECgMJBAAAAA==.Xavia:BAABLgAECn8YAAIIAAgJixM/KADMAQhoDAAABQAoAGkMAAAEAD8AawwAAAQAPABqDAAAAgBXAGwMAAACADEAbQwAAAEAGADqDAAABQAxAG4MAAABADwACAAICYsTPygAzAEIaAwAAAUAKABpDAAABAA/AGsMAAAEADwAagwAAAIAVwBsDAAAAgAxAG0MAAABABgA6gwAAAUAMQBuDAAAAQA8AAAA.',
Xy='Xylazel:BAABLgAECn8fAAITAAkJqxX+GABAAgloDAAABABMAGkMAAAEAE4AawwAAAQAKgBqDAAABABMAGwMAAAEAEgAbQwAAAMAOgDqDAAABAAzAG4MAAADACwAbwwAAAEAEwATAAkJqxX+GABAAgloDAAABABMAGkMAAAEAE4AawwAAAQAKgBqDAAABABMAGwMAAAEAEgAbQwAAAMAOgDqDAAABAAzAG4MAAADACwAbwwAAAEAEwAAAA==.',
Ya='Yasmina:BAAALgAECgYJDgAAAA==.',
Yv='Yvana:BAABLgAECn8UAAIRAAQJ9htyMAAgAQRoDAAABQBEAGkMAAAEADoAawwAAAQAVwDqDAAABwBHABEABAn2G3IwACABBGgMAAAFAEQAaQwAAAQAOgBrDAAABABXAOoMAAAHAEcAAAA=.',
Za='Zaradrela:BAAALgAECgEJAQAAAA==.',
Zu='Zugmaster:BAAALgADCgEJAQAAAA==.',
Zz='Zzephyrdruid:BAACLgAFFH8ZAAIjAAcJdiDJAABcAgdoDAAABQBiAGkMAAAEAEoAawwAAAQAYgBqDAAAAwBIAGwMAAACAD4AbQwAAAEAUADqDAAABgBUACMABwl2IMkAAFwCB2gMAAAFAGIAaQwAAAQASgBrDAAABABiAGoMAAADAEgAbAwAAAIAPgBtDAAAAQBQAOoMAAAGAFQALgAECn8cAAIjAAgJxCWVDQDBAgAjAAgJxCWVDQDBAgAAAA==.Zzephyrev:BAAALgAECgYJDwABLgAFFAcJGQAjAHYgAA==.',
['Âs']='Âsunâ:BAABLgAECn8cAAIcAAgJORxnDwBqAghoDAAABwBcAGkMAAADAFYAawwAAAMAVwBqDAAABQBZAGwMAAADAFIAbQwAAAIAMgDqDAAABAAzAG4MAAABACYAHAAICTkcZw8AagIIaAwAAAcAXABpDAAAAwBWAGsMAAADAFcAagwAAAUAWQBsDAAAAwBSAG0MAAACADIA6gwAAAQAMwBuDAAAAQAmAAAA.',
['Ôä']='Ôäk:BAAALgADCgYJCwABLgAECgcJGgAcANcOAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
