local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Evoker-Augmentation','Warrior-Arms','Warrior-Fury','Priest-Holy','Priest-Shadow','DeathKnight-Blood','Unknown-Unknown','Warlock-Demonology','Mage-Frost','DeathKnight-Unholy','Hunter-Marksmanship','Paladin-Retribution','Monk-Brewmaster','Hunter-BeastMastery','Evoker-Preservation','Evoker-Devastation','Warrior-Protection','Paladin-Holy','Warlock-Destruction','Shaman-Elemental','Shaman-Restoration','Monk-Windwalker','DemonHunter-Devourer','Warlock-Affliction','DemonHunter-Vengeance','Priest-Discipline','Druid-Guardian','DemonHunter-Havoc','Druid-Restoration','Hunter-Survival','Shaman-Enhancement','Paladin-Protection','Druid-Feral','DeathKnight-Frost','Druid-Balance','Monk-Mistweaver','Mage-Arcane',}
local provider = {region='US',realm='ShatteredHand',name='US',type='daily',zone=46,date='2026-05-14',data={Ab='Abchi:BAAALgAECgMJAwAAAA==.Abelladanger:BAAALgADCgYJBgAAAA==.Absorption:BAAALgAECggJDAABLgAECggJIQABAFYXAA==.',
Ac='Ackerw:BAABLgAFFH8JAAMCAAQJkws1BAD3AARoDAAAAgAKAGkMAAACABoAawwAAAEACgDqDAAABABGAAIABAmTCzUEAPcABGgMAAACAAoAaQwAAAIAGgBrDAAAAQAKAOoMAAADAEYAAwABCWkELyQATAAB6gwAAAEACwAAAA==.',
Ad='Addilyn:BAABLgAECn8aAAMEAAgJPxTuIgBTAQhoDAAABQA5AGkMAAAEADUAawwAAAQAOgBqDAAAAwATAGwMAAACAE0AbQwAAAIAPwDqDAAABAA1AG4MAAACAB4ABAAICT8U7iIAUwEIaAwAAAMAOQBpDAAAAwA1AGsMAAADADoAagwAAAIAEwBsDAAAAQBNAG0MAAACAD8A6gwAAAMANQBuDAAAAQAeAAUABwlyC54lADkBB2gMAAACABkAaQwAAAEAHABrDAAAAQAcAGoMAAABACUAbAwAAAEAGwDqDAAAAQAXAG4MAAABACkAAAA=.',
Ah='Ahminous:BAABLgAECn8aAAIGAAgJ2BMGEgCGAQhoDAAABQBCAGkMAAAEAEgAawwAAAQANABqDAAAAwA/AGwMAAACACUAbQwAAAIAJwDqDAAABABDAG4MAAACABMABgAICdgTBhIAhgEIaAwAAAUAQgBpDAAABABIAGsMAAAEADQAagwAAAMAPwBsDAAAAgAlAG0MAAACACcA6gwAAAQAQwBuDAAAAgATAAAA.Ahroo:BAAALgAECgkJGQAAAQ==.Ahrue:BAAALgAECgkJDQABLgAECgkJGQAHAAAAAQ==.',
Ai='Airc:BAAALgAECgYJDwAAAA==.Aiurman:BAAALgADCgkJCQAAAA==.',
Al='Alfster:BAABLgAECn8eAAIIAAgJkwfDWQA6AQhoDAAAAgAKAGkMAAAEAAoAawwAAAQAEgBqDAAAAwAZAGwMAAAHACkAbQwAAAEAEgDqDAAABgATAG4MAAADABEACAAICZMHw1kAOgEIaAwAAAIACgBpDAAABAAKAGsMAAAEABIAagwAAAMAGQBsDAAABwApAG0MAAABABIA6gwAAAYAEwBuDAAAAwARAAAA.Allessiae:BAAALgAECgYJBgAAAA==.Alvar:BAABLgAECn8XAAIIAAgJsRJQPgCMAQhoDAAAAgA1AGkMAAACABoAawwAAAMALABqDAAAAgAiAGwMAAAFAE4AbQwAAAIAIwDqDAAABQAvAG4MAAACADAACAAICbESUD4AjAEIaAwAAAIANQBpDAAAAgAaAGsMAAADACwAagwAAAIAIgBsDAAABQBOAG0MAAACACMA6gwAAAUALwBuDAAAAgAwAAAA.',
Ar='Arcadium:BAABLgAECn8VAAIJAAUJWCKWbwD1AQVoDAAAAwBgAGkMAAAFAFwAawwAAAQATQBqDAAAAwBhAOoMAAAGAFUACQAFCVgilm8A9QEFaAwAAAMAYABpDAAABQBcAGsMAAAEAE0AagwAAAMAYQDqDAAABgBVAAAA.Arkhan:BAAALgAECgQJBAAAAA==.Arêos:BAABLgAECn8eAAIEAAkJZh3TBwCXAgloDAAABgBSAGkMAAAFAFcAawwAAAUAVgBqDAAAAwBOAGwMAAADAFUAbQwAAAEAPQDqDAAABQBcAG4MAAABAEYAbwwAAAEAHwAEAAkJZh3TBwCXAgloDAAABgBSAGkMAAAFAFcAawwAAAUAVgBqDAAAAwBOAGwMAAADAFUAbQwAAAEAPQDqDAAABQBcAG4MAAABAEYAbwwAAAEAHwAAAA==.',
As='Asunaish:BAABLgAECn8YAAIKAAgJThsaJwAMAghoDAAABwBgAGkMAAAFAFgAawwAAAQAWABqDAAAAgBMAGwMAAABAAkA6gwAAAMARwBuDAAAAQBbAG8MAAABACwACgAICU4bGicADAIIaAwAAAcAYABpDAAABQBYAGsMAAAEAFgAagwAAAIATABsDAAAAQAJAOoMAAADAEcAbgwAAAEAWwBvDAAAAQAsAAAA.',
At='Atiko:BAAALgADCgQJBAAAAA==.Atomicrednax:BAABLgAFFH8ZAAILAAcJAB9HAQA2AgdoDAAAAwBbAGkMAAAFAF0AawwAAAQAWwBqDAAABABcAGwMAAACAEoAbQwAAAEAJwDqDAAABgBVAAsABwkAH0cBADYCB2gMAAADAFsAaQwAAAUAXQBrDAAABABbAGoMAAAEAFwAbAwAAAIASgBtDAAAAQAnAOoMAAAGAFUAAAA=.Atropos:BAAALgADCgcJBwAAAA==.',
Ay='Ayisen:BAAALgAECgQJBgAAAA==.',
Az='Azarite:BAABLgAECn8sAAIMAAkJrRHbOgC6AQloDAAABwA8AGkMAAAHAEEAawwAAAYAPQBqDAAABgAkAGwMAAAFACkAbQwAAAMAKQDqDAAABgAtAG4MAAADABUAbwwAAAEAGAAMAAkJrRHbOgC6AQloDAAABwA8AGkMAAAHAEEAawwAAAYAPQBqDAAABgAkAGwMAAAFACkAbQwAAAMAKQDqDAAABgAtAG4MAAADABUAbwwAAAEAGAAAAA==.',
Ba='Babybilly:BAAALgAECgQJBwAAAA==.Badassbum:BAAALgAECgYJEgAAAA==.Bahoodies:BAAALgAECgYJBQAAAA==.Balgorath:BAAALgAECgQJBwAAAA==.Balthazar:BAAALgADCgUJBgAAAA==.Bananastand:BAAALgADCgMJAwAAAA==.Banree:BAAALgAECgEJAwAAAA==.Bassa:BAAALgADCgYJBgAAAA==.Battman:BAAALgADCgcJDAABLgAECgEJAQAHAAAAAA==.Battousaiha:BAABLgAECn8cAAIMAAgJABoNKgD9AQhoDAAABQBRAGkMAAAEADwAawwAAAUAWgBqDAAAAwAsAGwMAAACADgAbQwAAAIAKADqDAAABQBRAG4MAAACADYADAAICQAaDSoA/QEIaAwAAAUAUQBpDAAABAA8AGsMAAAFAFoAagwAAAMALABsDAAAAgA4AG0MAAACACgA6gwAAAUAUQBuDAAAAgA2AAAA.',
Be='Bera:BAAALgAECgIJAwAAAA==.',
Bi='Bigmustard:BAACLgAFFH8iAAINAAcJUx8eAgANAgdoDAAABgBJAGkMAAAHAGEAawwAAAYATgBqDAAABQBFAGwMAAADAFQAbQwAAAEAQwDqDAAABgBPAA0ABwlTHx4CAA0CB2gMAAAGAEkAaQwAAAcAYQBrDAAABgBOAGoMAAAFAEUAbAwAAAMAVABtDAAAAQBDAOoMAAAGAE8ALgAECn8sAAINAAkJLyX0AwBQAwANAAkJLyX0AwBQAwAAAA==.Bignut:BAAALgAECgYJBQAAAA==.',
Bo='Boojum:BAAALgAECgYJDgAAAA==.Borticuss:BAAALgAECgMJAwABLgAECgcJJQANAA8aAA==.Bortikus:BAAALgAECgQJBwABLgAECgcJJQANAA8aAA==.Boskos:BAAALgADCgQJBAABLgAECgQJCQAHAAAAAA==.Bossnugg:BAAALgADCgYJCAABLgAECgQJCQAHAAAAAA==.',
Br='Brasputin:BAAALgADCgQJBAAAAA==.Breez:BAAALgADCgIJAgAAAA==.',
Bu='Bul:BAAALgADCgcJBwABLgAECggJFAAOABAUAA==.Bullshifting:BAAALgAECgcJEwAAAA==.Bumbaloo:BAAALgAECgQJBQAAAA==.Burgi:BAAALgAECgQJBQAAAA==.Burney:BAABLgAECn8sAAMPAAgJRSJGAgAGAwhoDAAABwBXAGkMAAAGAFsAawwAAAYAVABqDAAABgBXAGwMAAAFAFoAbQwAAAQAVgDqDAAABwBaAG4MAAADAFUADwAICUUiRgIABgMIaAwAAAcAVwBpDAAABgBbAGsMAAAGAFQAagwAAAYAVwBsDAAABQBaAG0MAAAEAFYA6gwAAAYAWgBuDAAAAgBVABAAAglwC70UAGYAAuoMAAABACUAbgwAAAEAFQAAAA==.',
['Bò']='Bònesaw:BAACLgAFFH8FAAIRAAIJuCJ7EQDGAAJoDAAAAwBZAGkMAAACAFgAEQACCbgiexEAxgACaAwAAAMAWQBpDAAAAgBYAC4ABAp/LQACEQAJCXQiCgIA8wIAEQAJCXQiCgIA8wIAAAA=.',
Ca='Calibrium:BAAALgAECgYJDwAAAA==.Cannaboss:BAAALgAECgQJCQAAAA==.Carll:BAACLgAFFH8IAAISAAMJgA8LIADGAANoDAAAAwAbAGkMAAAEADUA6gwAAAEAJQASAAMJgA8LIADGAANoDAAAAwAbAGkMAAAEADUA6gwAAAEAJQAuAAQKfx8AAhIACAlsFL4mAPQBABIACAlsFL4mAPQBAAAA.Catleesei:BAABLgAECn8bAAIBAAkJVRCwFQDCAQloDAAABAAuAGkMAAAEAD8AawwAAAQALwBqDAAAAwAnAGwMAAADACwAbQwAAAMAIwDqDAAAAgAnAG4MAAADABQAbwwAAAEAJQABAAkJVRCwFQDCAQloDAAABAAuAGkMAAAEAD8AawwAAAQALwBqDAAAAwAnAGwMAAADACwAbQwAAAMAIwDqDAAAAgAnAG4MAAADABQAbwwAAAEAJQAAAA==.',
Ch='Chables:BAAALgADCgcJBwAAAA==.Chai:BAAALgAECgYJEQAAAA==.Chaosmage:BAAALgAECgQJBAAAAA==.Charizard:BAAALgAECgIJAwAAAA==.Chickyn:BAAALgAECgMJBQAAAA==.Chinsei:BAAALgAECgEJAQAAAA==.Choppa:BAAALgAECgQJCAAAAA==.',
Cl='Clyde:BAAALgAECgIJAgAAAA==.',
Co='Cocodruid:BAAALgAECgUJBQAAAA==.Coldxlxsoul:BAABLgAECn8WAAMQAAcJqhQNFAClAQdoDAAABABJAGkMAAAEADoAawwAAAMATABqDAAAAwBAAGwMAAADACgA6gwAAAQAOwBuDAAAAQAJABAABwkNEg0UAKUBB2gMAAADAEkAaQwAAAMAOgBrDAAAAgBMAGoMAAACAEAAbAwAAAIAHwDqDAAAAwAcAG4MAAABAAkAAQAGCVgRPy4AUAEGaAwAAAEAFABpDAAAAQA0AGsMAAABADAAagwAAAEAIABsDAAAAQAoAOoMAAABADsAAAA=.Condrius:BAAALgADCgUJBgAAAA==.Convict:BAAALgAECgMJBQAAAA==.',
Cr='Crappylock:BAAALgAECgQJBAAAAA==.Criotor:BAAALgAECgIJBAAAAA==.Critster:BAAALgAECgQJBwAAAA==.Crud:BAAALgADCgMJAwAAAA==.',
Da='Daddy:BAACLgAFFH8NAAIIAAYJ6QtRGgBmAQZoDAAAAgAGAGkMAAADABEAawwAAAIAMABqDAAAAQAQAGwMAAABAA4A6gwAAAQAQgAIAAYJ6QtRGgBmAQZoDAAAAgAGAGkMAAADABEAawwAAAIAMABqDAAAAQAQAGwMAAABAA4A6gwAAAQAQgAuAAQKfyUAAwgACAk0GvYoAG0CAAgACAn1GfYoAG0CABMABwlaFJsYAIYBAAAA.Darkportal:BAAALgAECgQJCQABLgAECggJGAAKAE4bAA==.Datnagablu:BAAALgAECgQJBQAAAA==.',
De='Deathsrain:BAABLgAECn8kAAIKAAgJ2x/DNABkAghoDAAABgBdAGkMAAAGAGAAawwAAAUAUABqDAAAAwBcAGwMAAAFAFQAbQwAAAEAPgDqDAAABwBZAG4MAAADAD4ACgAICdsfwzQAZAIIaAwAAAYAXQBpDAAABgBgAGsMAAAFAFAAagwAAAMAXABsDAAABQBUAG0MAAABAD4A6gwAAAcAWQBuDAAAAwA+AAAA.Decimez:BAABLgAECn8aAAIUAAgJMiCaCgBdAghoDAAABQBbAGkMAAAEAFIAawwAAAQATwBqDAAAAwBVAGwMAAACAFcAbQwAAAIAUADqDAAABABZAG4MAAACAEEAFAAICTIgmgoAXQIIaAwAAAUAWwBpDAAABABSAGsMAAAEAE8AagwAAAMAVQBsDAAAAgBXAG0MAAACAFAA6gwAAAQAWQBuDAAAAgBBAAAA.Decimock:BAAALgAECggJCQAAAA==.Delisa:BAAALgAECgYJBgAAAA==.Dellinsane:BAAALgAECgEJAQAAAA==.Devour:BAAALgAFFAIJAwAAAA==.',
Di='Dingiswayo:BAAALgAECgcJEgAAAA==.Dipz:BAAALgAECgYJCQAAAA==.',
Do='Donyolerberz:BAAALgAECgYJBQAAAA==.',
Dr='Draeno:BAABLgAECn8UAAIOAAgJEBRIRgBfAQhoDAAAAwAmAGkMAAADADkAawwAAAQATgBqDAAAAgAlAGwMAAADADoAbQwAAAEAKwDqDAAAAwAsAG4MAAABACUADgAICRAUSEYAXwEIaAwAAAMAJgBpDAAAAwA5AGsMAAAEAE4AagwAAAIAJQBsDAAAAwA6AG0MAAABACsA6gwAAAMALABuDAAAAQAlAAAA.Dragonflyy:BAAALgAECgEJAQAAAA==.Dragonips:BAAALgADCgYJBgAAAA==.Drbonedaddy:BAAALgAECgYJBgABLgAECgcJBQAHAAAAAA==.Drinkyds:BAABLgAFFH8HAAIVAAUJ5RahCQCkAQVoDAAAAQBfAGkMAAABAFUAawwAAAEAMABqDAAAAQAhAOoMAAADAB8AFQAFCeUWoQkApAEFaAwAAAEAXwBpDAAAAQBVAGsMAAABADAAagwAAAEAIQDqDAAAAwAfAAAA.',
Du='Duggnut:BAAALgAECgMJAwAAAA==.Durgi:BAABLgAECn8aAAISAAcJUhs+JQD8AQdoDAAAAwBBAGkMAAAGAGAAawwAAAUAVABqDAAABQBFAGwMAAADAC4A6gwAAAMAVQBuDAAAAQAoABIABwlSGz4lAPwBB2gMAAADAEEAaQwAAAYAYABrDAAABQBUAGoMAAAFAEUAbAwAAAMALgDqDAAAAwBVAG4MAAABACgAAAA=.Durtrim:BAAALgADCgIJAgAAAA==.',
Ed='Ederen:BAAALgAECgEJAQAAAA==.',
Ee='Eepic:BAABLgAECn8sAAIMAAkJPhGeOADBAQloDAAABgApAGkMAAAGAEAAawwAAAYAPABqDAAABQAoAGwMAAAFADEAbQwAAAIAEADqDAAACAAvAG4MAAAFACoAbwwAAAEAHwAMAAkJPhGeOADBAQloDAAABgApAGkMAAAGAEAAawwAAAYAPABqDAAABQAoAGwMAAAFADEAbQwAAAIAEADqDAAACAAvAG4MAAAFACoAbwwAAAEAHwAAAA==.',
Ei='Eightmile:BAAALgAECgcJCAAAAA==.Eisenhorn:BAAALgADCgcJDAABLgAECgcJFgAQAKoUAA==.',
El='Elementfrost:BAAALgAECgEJAQAAAA==.Ellio:BAAALgADCgcJBwABLgAFFAYJFAAOAOMcAA==.',
Em='Embar:BAAALgADCgIJAwAAAA==.Emrys:BAACLgAFFH8IAAMNAAIJ1CSCJQDXAAJoDAAABABgAOoMAAAEAFwADQACCdQkgiUA1wACaAwAAAMAYADqDAAABABcABYAAQmzCQgnAEQAAWgMAAABABgALgAECn8YAAMNAAcJLyQ2GABDAgANAAcJLyQ2GABDAgAWAAQJzhAXUgDKAAAAAA==.',
Ep='Epinephrine:BAAALgAECggJDgAAAA==.',
Er='Eriebus:BAABLgAECn8aAAIXAAgJ5gs1UgApAQhoDAAABQApAGkMAAAEAB4AawwAAAQALwBqDAAAAwA0AGwMAAACAA8AbQwAAAIAHQDqDAAABAAbAG4MAAACABUAFwAICeYLNVIAKQEIaAwAAAUAKQBpDAAABAAeAGsMAAAEAC8AagwAAAMANABsDAAAAgAPAG0MAAACAB0A6gwAAAQAGwBuDAAAAgAVAAAA.Erona:BAAALgAECgYJBgAAAA==.',
Es='Escorpiøn:BAACLgAFFH8OAAIKAAQJyB04KQBZAQRoDAAABQBHAGkMAAAEAE4AawwAAAIAQQDqDAAAAwBZAAoABAnIHTgpAFkBBGgMAAAFAEcAaQwAAAQATgBrDAAAAgBBAOoMAAADAFkALgAECn8oAAIKAAgJHSQiDADJAgAKAAgJHSQiDADJAgAAAA==.',
Ev='Evenstar:BAAALgAECgEJAQAAAA==.',
Fa='Faling:BAAALgADCgYJEQAAAA==.Falkor:BAAALgAECgcJEAABLgAECggJGAAKAE4bAA==.Fartcloud:BAAALgAECgQJBAAAAA==.Fatigued:BAAALgAECggJDQAAAA==.',
Fe='Feech:BAAALgAECgUJDAABLgAFFAMJCQAYAFobAA==.Feerz:BAAALgAECgIJAgAAAA==.Felagain:BAABLgAECn8jAAIZAAgJ6Ap/DAAkAQhoDAAABgAcAGkMAAAGABIAawwAAAUAKgBqDAAABQArAGwMAAAEAB0AbQwAAAIAFgDqDAAABgAeAG4MAAABABcAGQAICegKfwwAJAEIaAwAAAYAHABpDAAABgASAGsMAAAFACoAagwAAAUAKwBsDAAABAAdAG0MAAACABYA6gwAAAYAHgBuDAAAAQAXAAAA.Felslizer:BAAALgAECgMJAwAAAA==.Fentuul:BAAALgADCgkJCQAAAA==.Ferrous:BAAALgAECgEJAQAAAA==.',
Fl='Flankshot:BAACLgAFFH8FAAIJAAIJuwbGdwCXAAJoDAAAAwANAGkMAAACABQACQACCbsGxncAlwACaAwAAAMADQBpDAAAAgAUAC4ABAp/JAACCQAJCRMOZj0A0AEACQAJCRMOZj0A0AEAAAA=.Flo:BAAALgADCgUJBgABLgAECgYJBQAHAAAAAA==.Flõ:BAAALgAECgQJBAAAAA==.',
Fo='Foops:BAACLgAFFH8gAAIJAAcJHRgoBAAvAgdoDAAABgBbAGkMAAAGAFkAawwAAAUATgBqDAAABABOAGwMAAACACIAbQwAAAEAAADqDAAACABLAAkABwkdGCgEAC8CB2gMAAAGAFsAaQwAAAYAWQBrDAAABQBOAGoMAAAEAE4AbAwAAAIAIgBtDAAAAQAAAOoMAAAIAEsALgAECn8XAAIJAAgJYR0kRgBlAgAJAAgJYR0kRgBlAgAAAA==.Foopsadin:BAAALgAECgYJDQABLgAFFAcJIAAJAB0YAA==.',
Fr='Frinek:BAAALgADCgkJCQAAAA==.',
Fu='Fumin:BAAALgAECgQJCgAAAA==.',
Ga='Galibuk:BAAALgADCgYJBgAAAA==.',
Ge='Geezuss:BAAALgAECgEJBAABLgAFFAMJBQAaAJUIAA==.Genohbreaker:BAAALgAECgEJAQAAAA==.Genosaur:BAAALgAECgEJAQABLgAECgEJAQAHAAAAAA==.Getrkt:BAAALgAECgQJBAAAAA==.',
Gh='Ghouliver:BAABLgAECn8rAAIKAAkJrhf4MgDWAQloDAAABwBMAGkMAAAGAEQAawwAAAYASwBqDAAABQBTAGwMAAAGAEAAbQwAAAMAJwDqDAAABgBAAG4MAAADADgAbwwAAAEAKAAKAAkJrhf4MgDWAQloDAAABwBMAGkMAAAGAEQAawwAAAYASwBqDAAABQBTAGwMAAAGAEAAbQwAAAMAJwDqDAAABgBAAG4MAAADADgAbwwAAAEAKAAAAA==.',
Gi='Gigasushi:BAAALgAECgQJBAAAAA==.Gimblie:BAABLgAECn8dAAIEAAgJ5RQ9GACwAQhoDAAABQBGAGkMAAAFAFEAawwAAAUASABqDAAAAwAsAGwMAAAEACQAbQwAAAEAEgDqDAAABQA/AG4MAAABACgABAAICeUUPRgAsAEIaAwAAAUARgBpDAAABQBRAGsMAAAFAEgAagwAAAMALABsDAAABAAkAG0MAAABABIA6gwAAAUAPwBuDAAAAQAoAAAA.Gimermonty:BAACLgAFFH8FAAIOAAIJeRfPQgCmAAJoDAAAAwA+AGkMAAACADkADgACCXkXz0IApgACaAwAAAMAPgBpDAAAAgA5AC4ABAp/KwACDgAJCZcdCAoAuQIADgAJCZcdCAoAuQIAAAA=.Ging:BAAALgADCgcJCAAAAA==.',
Gl='Glorfindel:BAAALgAECgcJCAAAAA==.',
Go='Goblinkicker:BAAALgAECgMJBAAAAA==.Gothegg:BAAALgAECgEJAgAAAA==.Gothmommy:BAABLgAECn8eAAIIAAgJTQo1VABJAQhoDAAABQAjAGkMAAAFACIAawwAAAUAGgBqDAAABAAiAGwMAAAEACAAbQwAAAEAEQDqDAAABAAVAG4MAAACAA8ACAAICU0KNVQASQEIaAwAAAUAIwBpDAAABQAiAGsMAAAFABoAagwAAAQAIgBsDAAABAAgAG0MAAABABEA6gwAAAQAFQBuDAAAAgAPAAAA.',
Gr='Gregiously:BAAALgAECgkJCQAAAA==.Gronk:BAAALgAECgIJAgAAAA==.',
Gu='Guldanshower:BAABLgAECn8hAAMTAAgJlRpCDgDjAQhoDAAABgBXAGkMAAAGAEUAawwAAAUAVQBqDAAABABPAGwMAAADAEgAbQwAAAMAOQDqDAAABABIAG4MAAACAB8AEwAGCSccQg4A4wEGaAwAAAMAVwBpDAAAAwBFAGsMAAAEAFUAagwAAAQATwBsDAAAAQAuAOoMAAABAEgACAAHCagW/zAAvwEHaAwAAAMARwBpDAAAAwBFAGsMAAABADoAbAwAAAIASABtDAAAAwA5AOoMAAADACwAbgwAAAIAHwAAAA==.',
Ha='Habusaki:BAAALgAECgQJBgAAAA==.Hakal:BAABLgAECn8jAAIbAAgJRhiKCQDPAQhoDAAABgBIAGkMAAAFAD8AawwAAAUAPgBqDAAABAA1AGwMAAAEADcAbQwAAAYANQDqDAAABABFAG4MAAABADoAGwAICUYYigkAzwEIaAwAAAYASABpDAAABQA/AGsMAAAFAD4AagwAAAQANQBsDAAABAA3AG0MAAAGADUA6gwAAAQARQBuDAAAAQA6AAAA.Halvor:BAAALgAECgQJCAAAAA==.Hangbladz:BAAALgAECgcJEwAAAA==.Hardwarë:BAAALgAECgEJAQAAAA==.Harrygazm:BAAALgADCgQJBAAAAA==.',
He='Healista:BAAALgADCgYJBgABLgAECgkJJAAcADUbAA==.',
Hu='Hukdemon:BAABLgAECn8aAAIZAAgJNSR6AQDFAghoDAAABQBgAGkMAAAEAGEAawwAAAQAYQBqDAAAAwBiAGwMAAACAGIAbQwAAAIATgDqDAAABABbAG4MAAACAFkAGQAICTUkegEAxQIIaAwAAAUAYABpDAAABABhAGsMAAAEAGEAagwAAAMAYgBsDAAAAgBiAG0MAAACAE4A6gwAAAQAWwBuDAAAAgBZAAAA.',
Ic='Iceandfire:BAAALgAECgEJAQAAAA==.',
Il='Illiyana:BAAALgAECgcJBwAAAA==.',
In='Inviteme:BAAALgADCgMJAwABLgAECggJIgAKAN8aAA==.',
Ja='Jakesterwars:BAAALgADCgEJAQAAAA==.Jaldore:BAAALgADCgcJBwAAAA==.',
Je='Jeaine:BAAALgADCgEJAgAAAA==.',
Jh='Jhamin:BAACLgAFFH8MAAMUAAMJXxGVHQDbAANoDAAABQAeAGkMAAADACoA6gwAAAQAPAAUAAMJXxGVHQDbAANoDAAAAQAeAGkMAAACACoA6gwAAAEAPAAVAAMJfgmcMAC1AANoDAAABAAXAGkMAAABACIA6gwAAAMADgAuAAQKfx4AAxUACAmjFXMiABACABUACAmjFXMiABACABQABAmNGME6AOAAAAAA.',
Ji='Jiveturkey:BAAALgAECgQJAwAAAA==.',
Ju='Jubeiskyfang:BAAALgAECgcJCAABLgAFFAQJBQAMAEMPAA==.Julkaal:BAAALgAECgEJAQAAAA==.Junlelon:BAAALgAECgEJAQAAAA==.',
Ka='Kaedrelyn:BAAALgAECgEJAQAAAA==.Kai:BAAALgAECgYJBwAAAA==.Karnage:BAAALgAECgcJCAAAAA==.Karney:BAAALgAECgEJAwAAAA==.Kazam:BAAALgAECgYJBgAAAA==.Kazik:BAABLgAECn8ZAAIXAAcJaBuOLQCwAQdoDAAABQBVAGkMAAAEAFIAawwAAAQAOwBqDAAABABdAGwMAAADAD0AbQwAAAEAOADqDAAABABMABcABwloG44tALABB2gMAAAFAFUAaQwAAAQAUgBrDAAABAA7AGoMAAAEAF0AbAwAAAMAPQBtDAAAAQA4AOoMAAAEAEwAAAA=.',
Ke='Kelrath:BAABLgAECn8lAAIdAAgJvw6OLwCIAQhoDAAABgARAGkMAAAFAC4AawwAAAUAHABqDAAABQBWAGwMAAAFAB0AbQwAAAIAEgDqDAAABgA1AG4MAAADABYAHQAICb8Oji8AiAEIaAwAAAYAEQBpDAAABQAuAGsMAAAFABwAagwAAAUAVgBsDAAABQAdAG0MAAACABIA6gwAAAYANQBuDAAAAwAWAAAA.Kelthugan:BAAALgADCgIJAgAAAA==.Kendeez:BAAALgADCgcJCwAAAA==.Kenparrchi:BAAALgAECgIJAwAAAA==.Kensei:BAAALgADCgIJAgABLgAECgkJFQAMAA4UAA==.Ketheric:BAAALgADCgYJCAAAAA==.',
Ki='Kindinos:BAABLgAECn8WAAMOAAYJXxGYVgAtAQZoDAAABwA2AGkMAAAFAC0AawwAAAUANwBqDAAAAQABAGwMAAABABoA6gwAAAMAKQAOAAUJXxGYVgAtAQVoDAAAAgA2AGkMAAACAC0AawwAAAMANwBsDAAAAQAaAOoMAAABACkACwAFCSIN/xUAuAAFaAwAAAUAKQBpDAAAAwAfAGsMAAACACwAagwAAAEAAQDqDAAAAgAQAAAA.',
Kl='Kllcky:BAABLgAECn8aAAIMAAgJSCNxCADsAghoDAAABABhAGkMAAAEAGIAawwAAAUAYwBqDAAAAgBjAGwMAAADAGAA6gwAAAQAXwBuDAAAAwBjAG8MAAABACwADAAICUgjcQgA7AIIaAwAAAQAYQBpDAAABABiAGsMAAAFAGMAagwAAAIAYwBsDAAAAwBgAOoMAAAEAF8AbgwAAAMAYwBvDAAAAQAsAAEuAAUUAwkJABgAWhsA.Klorox:BAAALgAECgIJAgAAAA==.',
Kr='Kraoptix:BAAALgADCgYJDgAAAA==.Kratøs:BAAALgADCgMJAwAAAA==.Kraun:BAABLgAECn8nAAMeAAcJviHxCwATAgdoDAAABgBaAGkMAAAHAFgAawwAAAcAWgBqDAAABgBVAGwMAAAGAFEAbQwAAAIATgDqDAAABQBYAB4ABglUIvELABMCBmgMAAAGAFoAaQwAAAYAWABrDAAABQBaAGoMAAAGAFUAbAwAAAYAUQDqDAAABQBYAA4AAwmvHrdpAPsAA2kMAAABAFEAawwAAAIASwBtDAAAAgBOAAAA.Kreig:BAAALgADCgIJAgAAAA==.Kroo:BAAALgAECgYJDQABLgAECggJIQABAFYXAA==.Krythas:BAAALgADCgIJAgAAAA==.',
Ku='Kuwabara:BAAALgADCgUJBQAAAA==.',
Kv='Kvothè:BAAALgAECgcJDwAAAA==.',
Ky='Kyi:BAACLgAFFH8FAAIWAAIJ8wlGHgCIAAJoDAAAAwAmAGkMAAACAAsAFgACCfMJRh4AiAACaAwAAAMAJgBpDAAAAgALAC4ABAp/IAACFgAJCR8TLhMAwQEAFgAJCR8TLhMAwQEAAAA=.',
['Kî']='Kîrîto:BAAALgAECgIJBQABLgAECggJFAAJAGMeAA==.',
La='Lactosetwo:BAAALgAECgQJBQABLgAECgUJBQAHAAAAAA==.Lammlock:BAAALgAECgIJAgAAAA==.Landar:BAABLgAECn88AAIdAAkJJRb3EgBbAgloDAAACABCAGkMAAAIADsAawwAAAgARwBqDAAABwBDAGwMAAAHADkAbQwAAAYAFwDqDAAACAA1AG4MAAAFAFsAbwwAAAMAEgAdAAkJJRb3EgBbAgloDAAACABCAGkMAAAIADsAawwAAAgARwBqDAAABwBDAGwMAAAHADkAbQwAAAYAFwDqDAAACAA1AG4MAAAFAFsAbwwAAAMAEgAAAA==.Lathindra:BAAALgAECgEJAgAAAA==.Lazerpony:BAAALgAECgEJAwABLgAECgQJBwAHAAAAAA==.',
Le='Lefordini:BAAALgAECgQJBAAAAA==.Leggomyâggro:BAAALgAECgcJDwABLgAFFAcJIwAUAAQjAA==.Legun:BAAALgADCgMJAwAAAA==.Lexicon:BAAALgAECgMJAwAAAA==.',
Li='Liara:BAABLgAECn8iAAIeAAkJHw5qDQD3AQloDAAABAAZAGkMAAAEACEAawwAAAQAJgBqDAAABAAiAGwMAAAEABgAbQwAAAIADwDqDAAABgAoAG4MAAAFAEMAbwwAAAEALAAeAAkJHw5qDQD3AQloDAAABAAZAGkMAAAEACEAawwAAAQAJgBqDAAABAAiAGwMAAAEABgAbQwAAAIADwDqDAAABgAoAG4MAAAFAEMAbwwAAAEALAAAAA==.Lireesa:BAABLgAECn8jAAITAAgJmRCPCABrAQhoDAAABgAeAGkMAAAGAC8AawwAAAYAMwBqDAAABAATAGwMAAAEADgAbQwAAAIADADqDAAABgA6AG4MAAABACgAEwAICZkQjwgAawEIaAwAAAYAHgBpDAAABgAvAGsMAAAGADMAagwAAAQAEwBsDAAABAA4AG0MAAACAAwA6gwAAAYAOgBuDAAAAQAoAAAA.Lithiandriel:BAAALgAECgYJEgAAAA==.Liçk:BAAALgAECgMJAwABLgAECggJHAAdADkcAA==.',
Lo='Lockonyou:BAAALgAECgYJEQAAAA==.Logeofford:BAAALgADCgYJBQAAAA==.Lolola:BAAALgAECgQJBAAAAA==.Losthack:BAAALgAECgEJAQAAAA==.',
Lu='Lucker:BAAALgAECgEJAQAAAA==.Lunn:BAABLgAECn8YAAILAAcJug/VDwACAQdoDAAAAwAkAGkMAAAFADgAawwAAAQALwBqDAAAAwA3AGwMAAAEACgA6gwAAAQAKABuDAAAAQAUAAsABwm6D9UPAAIBB2gMAAADACQAaQwAAAUAOABrDAAABAAvAGoMAAADADcAbAwAAAQAKADqDAAABAAoAG4MAAABABQAAAA=.Lurac:BAAALgAECgEJAQABLgAFFAEJAQAHAAAAAA==.',
Ma='Madhi:BAAALgADCgcJDQAAAA==.Mahk:BAABLgAECn8UAAIMAAcJixX/TQB/AQdoDAAABQA3AGkMAAADAD8AawwAAAQARgBqDAAAAgAqAGwMAAACADMAbQwAAAEABQDqDAAAAwBTAAwABwmLFf9NAH8BB2gMAAAFADcAaQwAAAMAPwBrDAAABABGAGoMAAACACoAbAwAAAIAMwBtDAAAAQAFAOoMAAADAFMAAAA=.Majin:BAAALgAECgMJAwABLgAECgkJFQAMAA4UAA==.Mangreese:BAABLgAECn8dAAIfAAkJ7g48CQCwAQloDAAABAAmAGkMAAAEACoAawwAAAQALQBqDAAABAAwAGwMAAADABYAbQwAAAEABADqDAAABgA0AG4MAAACACkAbwwAAAEAOQAfAAkJ7g48CQCwAQloDAAABAAmAGkMAAAEACoAawwAAAQALQBqDAAABAAwAGwMAAADABYAbQwAAAEABADqDAAABgA0AG4MAAACACkAbwwAAAEAOQAAAA==.Matelk:BAAALgAECgEJAgAAAA==.',
Me='Meekseek:BAAALgAECgQJDgAAAA==.Meltdown:BAAALgADCgQJBAAAAA==.Memoo:BAAALgADCgUJBQAAAA==.',
Mi='Miahealifa:BAABLgAECn8YAAMaAAcJOQv9LQDyAAdoDAAABQATAGkMAAAFACMAawwAAAQAEgBqDAAAAwAuAGwMAAADACMAbQwAAAIAEQDqDAAAAgAbAAQABgmACVpHABwBBmgMAAACABMAaQwAAAEAFQBrDAAAAQAJAGoMAAACAC4AbAwAAAEAFADqDAAAAgAbABoABgksCf0tAPIABmgMAAADAA8AaQwAAAQAIwBrDAAAAwASAGoMAAABABEAbAwAAAIAIwBtDAAAAgARAAAA.Milim:BAAALgAECgUJBQAAAA==.Miloh:BAAALgAECgQJCQAAAA==.Mistabubbles:BAAALgAECgYJBgAAAA==.Mistmia:BAAALgADCgYJBgAAAA==.Mixmasterg:BAABLgAECn8fAAIXAAgJFgxGTAA7AQhoDAAABQAxAGkMAAAEABkAawwAAAQAFQBqDAAABAA5AGwMAAAEACgAbQwAAAEAEQDqDAAABgAhAG4MAAADABsAFwAICRYMRkwAOwEIaAwAAAUAMQBpDAAABAAZAGsMAAAEABUAagwAAAQAOQBsDAAABAAoAG0MAAABABEA6gwAAAYAIQBuDAAAAwAbAAAA.',
Mo='Mograinez:BAACLgAFFH8eAAIKAAcJpCVyAACEAgdoDAAABQBiAGkMAAAGAGMAawwAAAQAYgBqDAAABABjAGwMAAACAFoAbQwAAAEAXADqDAAACABjAAoABwmkJXIAAIQCB2gMAAAFAGIAaQwAAAYAYwBrDAAABABiAGoMAAAEAGMAbAwAAAIAWgBtDAAAAQBcAOoMAAAIAGMALgAECn8VAAIKAAgJfSalHADTAgAKAAgJfSalHADTAgAAAA==.Monkeyman:BAAALgADCgIJAgAAAA==.Moosebreath:BAAALgAECgQJBAABLgAFFAUJBQAaAEgHAA==.',
Mu='Murderer:BAAALgAECgMJBgAAAA==.',
My='Mythunrus:BAABLgAECn8YAAIcAAYJIhI+MgBDAQZoDAAABgBAAGkMAAAGAC0AawwAAAQALABqDAAAAwAUAGwMAAADACYA6gwAAAIAJwAcAAYJIhI+MgBDAQZoDAAABgBAAGkMAAAGAC0AawwAAAQALABqDAAAAwAUAGwMAAADACYA6gwAAAIAJwAAAA==.',
['Mó']='Móñk:BAAALgAECgcJEgAAAA==.',
['Mö']='Mörgana:BAAALgADCgQJBAAAAA==.',
Na='Narofu:BAAALgADCgQJBAAAAA==.Nazurasar:BAAALgAECgMJAwAAAA==.',
Ne='Nejìre:BAAALgADCgYJCQAAAA==.Neteyam:BAAALgAECgYJCAAAAA==.Neutron:BAAALgAECgMJBQAAAA==.',
No='Norolock:BAABLgAECn8aAAIIAAgJlRauLwDFAQhoDAAABQBNAGkMAAAEACgAawwAAAQAPgBqDAAAAwA+AGwMAAACACAAbQwAAAIAOQDqDAAABABBAG4MAAACAEMACAAICZUWri8AxQEIaAwAAAUATQBpDAAABAAoAGsMAAAEAD4AagwAAAMAPgBsDAAAAgAgAG0MAAACADkA6gwAAAQAQQBuDAAAAgBDAAAA.Notbreeze:BAAALgADCgYJBgAAAA==.Notsure:BAAALgAECgcJBwAAAA==.',
Nu='Nuero:BAAALgAFFAIJBAAAAA==.Nukashine:BAAALgADCgYJCAAAAA==.Nuuro:BAAALgAECgcJEgAAAA==.',
Ny='Ny:BAAALgADCgUJBQAAAA==.Nyverra:BAAALgADCgQJBAAAAA==.',
['Nã']='Nãrcissus:BAACLgAFFH8JAAMYAAMJWhtZAwBfAANoDAAABAArAGkMAAADAE4A6gwAAAIAWAAIAAIJrxkWYgCiAAJoDAAABAArAOoMAAACAFgAGAABCa8eWQMAXwABaQwAAAMATgAuAAQKfy0ABAgACAkHIK8pAOABAAgABgn4H68pAOABABMABAkoF3IuAAIBABgAAwnQIDAWANEAAAAA.',
Ol='Oldshotz:BAAALgAECgYJDAAAAA==.',
Om='Omgsteak:BAAALgAECgYJDwAAAA==.',
On='Onapalehorse:BAAALgADCgcJEAAAAA==.Onger:BAAALgADCgEJAQAAAA==.Onlybusa:BAAALgAECgEJAwAAAA==.Ons:BAAALgAECgQJBAAAAA==.',
Ow='Owl:BAAALgAECgEJAQABLgAECgcJGQAMAJMTAA==.',
Pa='Panpots:BAAALgADCgYJBgAAAA==.Panzerdox:BAAALgAECgcJBwAAAA==.Panzerwolf:BAECLgAFFH8WAAIRAAQJLCUxAwCxAQRoDAAABwBhAGkMAAAGAFwAawwAAAMAXADqDAAABgBhABEABAksJTEDALEBBGgMAAAHAGEAaQwAAAYAXABrDAAAAwBcAOoMAAAGAGEALgAECn9ZAAMRAAkJZSY2AAB8AwARAAkJZSY2AAB8AwADAAUJhgdqbwD6AAAAAA==.Patchnotes:BAAALgAECgYJCwAAAA==.',
Pe='Peepaw:BAAALgAFFAIJAgAAAA==.',
Po='Poorclass:BAAALgAECgEJAQAAAA==.',
Pr='Prayforme:BAABLgAECn8gAAMaAAgJAhx9CACKAghoDAAABgBRAGkMAAAFAFQAawwAAAUATQBqDAAABQBdAGwMAAAEAEsAbQwAAAEAIADqDAAABQBSAG4MAAABAC0AGgAICQIcfQgAigIIaAwAAAUAUQBpDAAABABUAGsMAAAEAE0AagwAAAUAXQBsDAAABABLAG0MAAABACAA6gwAAAQAUgBuDAAAAQAtAAUABAngE04wAPkABGgMAAABACwAaQwAAAEALABrDAAAAQA/AOoMAAABADMAAAA=.Prettynails:BAAALgAECggJDwAAAA==.Prise:BAACLgAFFH8FAAMIAAMJVA+nZACdAANoDAAAAgAsAGkMAAACAAEA6gwAAAEARwAIAAIJoBanZACdAAJoDAAAAgAsAOoMAAABAEcAEwABCb0AWBwAKwABaQwAAAIAAQAuAAQKfxYAAxMABwk5EQQbAHUBABMABwm+EAQbAHUBAAgABglHDtOcAKwAAAAA.',
Ps='Psilocybic:BAABLgAECn8aAAMVAAkJdQmpSQBbAQloDAAAAwAfAGkMAAADAB4AawwAAAMACABqDAAAAwAWAGwMAAADABUAbQwAAAIABADqDAAABQASAG4MAAADAC8AbwwAAAEAIAAVAAkJdQmpSQBbAQloDAAAAgAfAGkMAAACAB4AawwAAAIACABqDAAAAgAWAGwMAAACABUAbQwAAAEABADqDAAABQASAG4MAAADAC8AbwwAAAEAIAAUAAYJ4wfqTwAHAQZoDAAAAQADAGkMAAABABEAawwAAAEAMgBqDAAAAQAOAGwMAAABABkAbQwAAAEABAAAAA==.',
Qw='Qweh:BAAALgAECgYJDwAAAA==.',
Ra='Rahnko:BAAALgAECgQJAgAAAA==.Rakkasei:BAACLgAFFH8FAAIBAAIJWwfzNwCCAAJoDAAAAwARAOoMAAACABQAAQACCVsH8zcAggACaAwAAAMAEQDqDAAAAgAUAC4ABAp/HgADAQAJCbkX7RAA+QEAAQAJCbkX7RAA+QEAEAADCf4E9TIAfgAAAAA=.Ralthas:BAAALgAECgQJBwAAAA==.Randark:BAABLgAECn8nAAQCAAgJhRr5CgD0AQhoDAAABgBaAGkMAAAGAD8AawwAAAYARwBqDAAABQBMAGwMAAAGAEUAbQwAAAEAGgDqDAAABQBSAG4MAAAEAEYAAgAGCQsd+QoA9AEGaAwAAAMAWgBpDAAABAA/AGsMAAADAEAAagwAAAIATADqDAAAAwBSAG4MAAADAEYAAwAHCdIPN08AagEHaAwAAAIASABpDAAAAQAnAGsMAAACAAkAagwAAAIASgBsDAAAAwBEAG0MAAABABoA6gwAAAIAGgARAAYJOxSVGgAAAQZoDAAAAQAsAGkMAAABADYAawwAAAEARwBqDAAAAQApAGwMAAADAEUAbgwAAAEAEgAAAA==.Ravenoth:BAAALgAECgEJAQAAAA==.Razkal:BAAALgAECgYJDQAAAA==.Razzlock:BAAALgADCgcJBwAAAA==.',
Re='Reshiiram:BAAALgAECgEJAQAAAA==.Retneprac:BAAALgADCgQJBAAAAA==.Revirginator:BAABLgAECn8hAAMgAAcJewn8JADgAAdoDAAACAAoAGkMAAAHADIAawwAAAYAGgBqDAAAAwAYAGwMAAADAAYAbQwAAAEABADqDAAABQARACAABwk+BvwkAOAAB2gMAAAGACgAaQwAAAUAEwBrDAAABAARAGoMAAADABgAbAwAAAMABgBtDAAAAQAEAOoMAAACAAgADAAECdELvb0ApwAEaAwAAAIAGQBpDAAAAgAyAGsMAAACABoA6gwAAAMAEQAAAA==.Revna:BAAALgAECgEJAwAAAA==.',
Rh='Rhagnar:BAAALgAECgQJBAAAAA==.',
Ri='Richandfamus:BAABLgAECn8XAAIKAAUJzB9VUwBmAQVoDAAABgBhAGkMAAAFAFcAawwAAAYATwBqDAAABABEAOoMAAACAD0ACgAFCcwfVVMAZgEFaAwAAAYAYQBpDAAABQBXAGsMAAAGAE8AagwAAAQARADqDAAAAgA9AAAA.Riftstalker:BAABLgAECn8XAAMeAAcJCBcqGAB4AQdoDAAABABOAGkMAAAEAFkAawwAAAUASQBqDAAAAQBIAGwMAAABAAQA6gwAAAYATABuDAAAAgAeAB4ABwkIFyoYAHgBB2gMAAAEAE4AaQwAAAQAWQBrDAAABQBJAGoMAAABAEgAbAwAAAEABADqDAAABQBMAG4MAAACAB4ADgABCfsNH9EANQAB6gwAAAEAIwAAAA==.',
Rn='Rngesus:BAACLgAFFH8JAAIIAAMJ/BBYSgDeAANoDAAABQBFAGkMAAADACIA6gwAAAEAGQAIAAMJ/BBYSgDeAANoDAAABQBFAGkMAAADACIA6gwAAAEAGQAuAAQKfyUAAwgACQl4HvsYAEACAAgACQl4HvsYAEACABMAAgliBsNWAGoAAAAA.',
Ro='Rocmaul:BAAALgADCgkJCQAAAA==.',
Ru='Rushem:BAAALgAECggJEwAAAA==.Ruwa:BAAALgADCgUJBQAAAA==.',
Ry='Ryft:BAABLgAECn8XAAIKAAgJzBYbegCQAQhoDAAABABEAGkMAAAEAEMAawwAAAUAOwBqDAAAAgA1AGwMAAACAE0AbQwAAAEAJgDqDAAAAwA1AG4MAAACACsACgAICcwWG3oAkAEIaAwAAAQARABpDAAABABDAGsMAAAFADsAagwAAAIANQBsDAAAAgBNAG0MAAABACYA6gwAAAMANQBuDAAAAgArAAAA.Ryhaz:BAAALgADCgcJBwAAAA==.',
Sa='Saenen:BAABLgAECn8WAAIhAAcJuQveFAABAQdoDAAABQAmAGkMAAAFACcAawwAAAQAGgBqDAAAAwAnAGwMAAACAC4AbQwAAAEADgDqDAAAAgAOACEABwm5C94UAAEBB2gMAAAFACYAaQwAAAUAJwBrDAAABAAaAGoMAAADACcAbAwAAAIALgBtDAAAAQAOAOoMAAACAA4AAAA=.Sandrozarke:BAABLgAECn8hAAQBAAgJVhc7EQBlAghoDAAABQBOAGkMAAAFAEIAawwAAAUATQBqDAAABABdAGwMAAAEADsAbQwAAAMAIQDqDAAABQAwAG4MAAACADYAAQAICT8XOxEAZQIIaAwAAAUATgBpDAAABQBCAGsMAAAFAE0AagwAAAQAXQBsDAAABAA7AG0MAAACACEA6gwAAAQALgBuDAAAAgA2ABAAAQn5Elc8ADwAAeoMAAABADAADwABCcoCbUcAOAABbQwAAAEABwAAAA==.Sarah:BAAALgAECgIJAgABLgAECgkJMwAaALIfAA==.',
Sc='Scorchi:BAAALgAECgEJAQABLgAECgEJAwAHAAAAAA==.Scrublet:BAAALgAECgYJEAAAAA==.',
Se='Seldara:BAABLgAECn8lAAMiAAgJzwWnDgC5AAhoDAAABwAcAGkMAAAHABMAawwAAAcADwBqDAAABQAOAGwMAAAEAAUAbQwAAAEABADqDAAABQAZAG4MAAABAAQACgAICWkDuqIAwgAIaAwAAAQACwBpDAAABAAQAGsMAAAFAAgAagwAAAUADgBsDAAABAAFAG0MAAABAAQA6gwAAAMACQBuDAAAAQAEACIABAnDCKcOALkABGgMAAADABwAaQwAAAMAEwBrDAAAAgAPAOoMAAACABkAAAA=.Seraphic:BAAALgAECgkJBAAAAA==.Serenity:BAABLgAECn8bAAIaAAUJUCF9EwDXAQVoDAAABwBhAGkMAAAGAFcAawwAAAYAVgBsDAAAAQBKAOoMAAAHAFEAGgAFCVAhfRMA1wEFaAwAAAcAYQBpDAAABgBXAGsMAAAGAFYAbAwAAAEASgDqDAAABwBRAAAA.Sergeyred:BAAALgADCgUJBQAAAA==.Serlyn:BAAALgAECgYJEAAAAA==.Seseria:BAACLgAFFH8FAAMSAAIJNA2sKgB7AAJoDAAAAwARAGkMAAACADIAEgACCTQNrCoAewACaAwAAAEAEQBpDAAAAQAyACAAAgkgBI8MAFMAAmgMAAACABAAaQwAAAEABAAuAAQKfywAAyAACQmQFUwOAHgBACAACAnpE0wOAHgBABIABQliFbMvADsBAAAA.Sevinofnine:BAAALgAECgEJAQAAAA==.',
Sh='Shalamar:BAAALgAECgEJBAAAAA==.Shanic:BAABLgAECn8YAAIjAAgJ0xdIEgDfAQhoDAAABABEAGkMAAAEADQAawwAAAQAQgBqDAAAAwAoAGwMAAACAD8AbQwAAAIAOwDqDAAAAwA2AG4MAAACAD0AIwAICdMXSBIA3wEIaAwAAAQARABpDAAABAA0AGsMAAAEAEIAagwAAAMAKABsDAAAAgA/AG0MAAACADsA6gwAAAMANgBuDAAAAgA9AAAA.Shiddybill:BAAALgAECgQJBAAAAA==.Shiftor:BAAALgADCgYJBgABLgAECgEJAQAHAAAAAA==.Shiftyslice:BAAALgAECgEJAgAAAA==.Shihiro:BAAALgADCgIJAQAAAA==.',
Si='Siberianbull:BAAALgADCgEJAQAAAA==.Siena:BAAALgAECgEJAgAAAA==.',
Sl='Slaveman:BAAALgAECgIJAgAAAA==.Slitherina:BAAALgADCgYJBgAAAA==.Slåkritisk:BAABLgAECn8XAAIeAAgJaA1bEgCdAQhoDAAABAAqAGkMAAADACsAawwAAAIALABqDAAAAgAgAGwMAAACABMAbQwAAAEAEgDqDAAABQA1AG4MAAAEABIAHgAICWgNWxIAnQEIaAwAAAQAKgBpDAAAAwArAGsMAAACACwAagwAAAIAIABsDAAAAgATAG0MAAABABIA6gwAAAUANQBuDAAABAASAAAA.',
Sm='Smitervane:BAAALgADCgcJDQAAAA==.Smogy:BAAALgAECgMJAwAAAA==.',
Sn='Snipyterror:BAAALgADCgEJAQAAAA==.Snoodly:BAABLgAECn8VAAIkAAgJhxCaHQCRAQhoDAAABAA0AGkMAAADAEEAawwAAAMAJABqDAAAAgAwAGwMAAABACIAbQwAAAIADADqDAAABAAyAG4MAAACACUAJAAICYcQmh0AkQEIaAwAAAQANABpDAAAAwBBAGsMAAADACQAagwAAAIAMABsDAAAAQAiAG0MAAACAAwA6gwAAAQAMgBuDAAAAgAlAAAA.',
So='Solarice:BAABLgAECn8gAAMJAAkJWB6TDADZAgloDAAABgBUAGkMAAAGAFYAawwAAAUAVABqDAAAAwBjAGwMAAADAEgAbQwAAAEARQDqDAAABQBWAG4MAAACAFgAbwwAAAEAMAAJAAkJJR6TDADZAgloDAAABQBQAGkMAAAGAFYAawwAAAUAVABqDAAAAwBjAGwMAAADAEgAbQwAAAEARQDqDAAABQBWAG4MAAACAFgAbwwAAAEAMAAlAAEJ5iBkGQBMAAFoDAAAAQBUAAAA.Soletaken:BAAALgADCgQJBwAAAA==.Solunais:BAABLgAECn8iAAIIAAkJuwuxOQCdAQloDAAABQAwAGkMAAAEADMAawwAAAUAGQBqDAAABAAgAGwMAAAEABkAbQwAAAIAEwDqDAAABgAaAG4MAAADAB8AbwwAAAEACwAIAAkJuwuxOQCdAQloDAAABQAwAGkMAAAEADMAawwAAAUAGQBqDAAABAAgAGwMAAAEABkAbQwAAAIAEwDqDAAABgAaAG4MAAADAB8AbwwAAAEACwAAAA==.Soramor:BAAALgADCgcJCAAAAA==.Sorynn:BAAALgAECgEJAQAAAA==.',
Sp='Spirallidan:BAACLgAFFH8EAAIXAAIJGAO7XgByAAJoDAAAAgAHAGkMAAACAAgAFwACCRgDu14AcgACaAwAAAIABwBpDAAAAgAIAC4ABAp/FgACFwAJCQ0TJksAyAEAFwAJCQ0TJksAyAEAAAA=.Spy:BAAALgADCgQJBAAAAA==.',
St='Stardor:BAAALgAECgkJBwAAAA==.Staticprot:BAABLgAFFH8FAAIRAAQJzgtiEgC7AARoDAAAAQAXAGkMAAABABkAagwAAAEAFgDqDAAAAgApABEABAnOC2ISALsABGgMAAABABcAaQwAAAEAGQBqDAAAAQAWAOoMAAACACkAAAA=.Staticsrexar:BAAALgADCgcJBwABLgAFFAQJBQARAM4LAA==.Stature:BAAALgAECgcJBwAAAA==.Stepbro:BAABLgAECn8iAAIKAAgJ3xq0JQATAghoDAAABAA2AGkMAAAGAEcAawwAAAUASABqDAAAAwBOAGwMAAAGAFoAbQwAAAEAEgDqDAAABgBbAG4MAAADAFEACgAICd8atCUAEwIIaAwAAAQANgBpDAAABgBHAGsMAAAFAEgAagwAAAMATgBsDAAABgBaAG0MAAABABIA6gwAAAYAWwBuDAAAAwBRAAAA.Stinksauce:BAACLgAFFH8OAAIPAAQJTR5IDQBXAQRoDAAABABNAGkMAAAEAEoAawwAAAMARgDqDAAAAwBXAA8ABAlNHkgNAFcBBGgMAAAEAE0AaQwAAAQASgBrDAAAAwBGAOoMAAADAFcALgAECn8aAAQPAAkJBxpuDQBgAgAPAAkJBxpuDQBgAgABAAEJdAbUYQA1AAAQAAEJrweAPwAyAAAAAA==.Stormvetra:BAAALgAECgQJBQAAAA==.',
Su='Supabox:BAAALgAECgcJEgABLgAFFAUJFQANACElAA==.Superchunk:BAAALgAECgEJAQAAAA==.Supermann:BAAALgAECgEJAQAAAA==.Suryoudie:BAAALgADCgQJBAAAAA==.Sutra:BAABLgAECn8YAAIEAAcJYwsSKwAXAQdoDAAABAA3AGkMAAAEAB4AawwAAAQAHgBqDAAABAAgAGwMAAADABIAbQwAAAEABgDqDAAABAAeAAQABwljCxIrABcBB2gMAAAEADcAaQwAAAQAHgBrDAAABAAeAGoMAAAEACAAbAwAAAMAEgBtDAAAAQAGAOoMAAAEAB4AAAA=.',
Sw='Swiftmend:BAAALgAECgYJBgABLgAECggJDQAHAAAAAA==.',
Sy='Sylmarillion:BAABLgAECn8jAAISAAgJrxq/EAA5AghoDAAABgBJAGkMAAAGAEwAawwAAAUAUgBqDAAABQBNAGwMAAAEACgAbQwAAAIAIwDqDAAABQBKAG4MAAACAFQAEgAICa8avxAAOQIIaAwAAAYASQBpDAAABgBMAGsMAAAFAFIAagwAAAUATQBsDAAABAAoAG0MAAACACMA6gwAAAUASgBuDAAAAgBUAAAA.',
['Sø']='Sørry:BAABLgAECn8XAAINAAcJkRlUFAC8AQdoDAAAAwA8AGkMAAAFAFIAawwAAAQARgBqDAAAAwA3AGwMAAADAEcA6gwAAAQAQwBuDAAAAQAnAA0ABwmRGVQUALwBB2gMAAADADwAaQwAAAUAUgBrDAAABABGAGoMAAADADcAbAwAAAMARwDqDAAABABDAG4MAAABACcAAAA=.',
Ta='Talgulen:BAABLgAECn8vAAIQAAkJXh0wAQC0AgloDAAABwBeAGkMAAAGAFgAawwAAAYARgBqDAAABgBWAGwMAAAGAE8AbQwAAAMAPwDqDAAABwBdAG4MAAAEADYAbwwAAAIAOAAQAAkJXh0wAQC0AgloDAAABwBeAGkMAAAGAFgAawwAAAYARgBqDAAABgBWAGwMAAAGAE8AbQwAAAMAPwDqDAAABwBdAG4MAAAEADYAbwwAAAIAOAAAAA==.Tankytauren:BAABLgAECn8lAAMKAAkJJBLgQQCdAQloDAAABQA1AGkMAAAFADoAawwAAAUAMwBqDAAABQA1AGwMAAAFADEAbQwAAAQAMADqDAAABAAoAG4MAAADACUAbwwAAAEAHwAKAAgJFRLgQQCdAQhoDAAAAwA1AGkMAAADADoAawwAAAMAIwBqDAAAAwA1AGwMAAADADEAbQwAAAQAMADqDAAAAgAoAG4MAAADACUAIgAHCcwOsAgAWgEHaAwAAAIAHQBpDAAAAgAyAGsMAAACADMAagwAAAIAHQBsDAAAAgAmAOoMAAACABoAbwwAAAEAHwAAAA==.Tarquinius:BAABLgAECn8nAAIcAAkJUQ+HEQCXAQloDAAABwA+AGkMAAAGADUAawwAAAUALQBqDAAABAAoAGwMAAAEACYAbQwAAAMAFADqDAAABwAsAG4MAAACABEAbwwAAAEAHgAcAAkJUQ+HEQCXAQloDAAABwA+AGkMAAAGADUAawwAAAUALQBqDAAABAAoAGwMAAAEACYAbQwAAAMAFADqDAAABwAsAG4MAAACABEAbwwAAAEAHgAAAA==.Tatianasoles:BAAALgAECgEJAQAAAA==.Taxii:BAAALgAECgUJCQABLgAECgkJLwADAGMlAA==.Taylorswifft:BAAALgAECgcJAQAAAA==.',
Te='Telanastre:BAAALgAECgQJBwAAAA==.',
Th='Tharos:BAAALgADCgEJAgAAAA==.Theat:BAAALgAECgQJDAAAAA==.Theoeicke:BAAALgAECgcJDAABLgAFFAIJBQAWAPMJAA==.Thibbledor:BAAALgADCgkJFAABLgAECgYJFAAUAOUSAA==.',
Ti='Tifferny:BAAALgAECgIJBQAAAA==.Tiffèrny:BAAALgAECgYJBgAAAA==.Tinydrunk:BAAALgADCggJCAAAAA==.',
To='Tondra:BAAALgAECgYJCQAAAA==.Tone:BAABLgAECn8YAAMjAAgJ+xNaLQCZAQhoDAAAAwA6AGkMAAADAD8AawwAAAQAPwBqDAAABAAzAGwMAAACACQAbQwAAAIADwDqDAAAAwA7AG4MAAADADwAIwAHCWkTWi0AmQEHaAwAAAIAOgBpDAAAAgA/AGsMAAACAD8AagwAAAEAMwBsDAAAAQAkAG0MAAABAA8AbgwAAAIAPAAdAAgJHw2/YQAsAQhoDAAAAQAnAGkMAAABAAQAawwAAAIAUABqDAAAAwA+AGwMAAABAAoAbQwAAAEABQDqDAAAAwA2AG4MAAABAAsAAAA=.Tonkatruck:BAAALgAECgUJBAAAAA==.Totemlycool:BAABLgAECn8gAAQUAAgJGxWwIAAKAghoDAAABQBEAGkMAAAFAFUAawwAAAUATABqDAAABAAsAGwMAAAEADQAbQwAAAIACADqDAAABQAsAG4MAAACACoAFAAICQkUsCAACgIIaAwAAAEAOABpDAAAAQBVAGsMAAABAEwAagwAAAEALABsDAAAAQAtAG0MAAABAAgA6gwAAAEALABuDAAAAgAqAB8ABgmVFwQSAJYBBmgMAAAEAEQAaQwAAAQARwBrDAAABABIAGoMAAADACMAbAwAAAMANADqDAAAAwAkABUAAgmEAZaTAE0AAm0MAAABAAQA6gwAAAEAAwABLgAECggJIQABAFYXAA==.',
Tr='Trappress:BAAALgAECgcJDAABLgAECgkJPAAdAIsbAA==.Treehuggër:BAAALgAECgkJDQAAAA==.Trowa:BAAALgAECgIJAgABLgAFFAEJAQAHAAAAAA==.Trowaz:BAAALgAFFAEJAQAAAA==.Truffles:BAAALgADCgQJBAABLgAECggJIQATAJUaAA==.Tryrah:BAABLgAFFH8VAAIjAAcJaxbSAgD5AQdoDAAABAA4AGkMAAADACsAawwAAAQAQABqDAAAAwAZAGwMAAACAAYAbQwAAAEAWgDqDAAABABSACMABwlrFtICAPkBB2gMAAAEADgAaQwAAAMAKwBrDAAABABAAGoMAAADABkAbAwAAAIABgBtDAAAAQBaAOoMAAAEAFIAAAA=.',
Tw='Twinsons:BAAALgADCgEJAQAAAA==.Twisty:BAAALgAECgQJBQABLgAFFAEJAQAHAAAAAA==.Twîsty:BAAALgAECgUJBgABLgAFFAEJAQAHAAAAAA==.',
Ty='Tygron:BAAALgADCgQJBAAAAA==.Tyleroth:BAABLgAECn8gAAIXAAkJYhLHMgCYAQloDAAABQBIAGkMAAAFAD0AawwAAAUANwBqDAAABABJAGwMAAAEADIAbQwAAAEAEgDqDAAABAAyAG4MAAADACwAbwwAAAEAFgAXAAkJYhLHMgCYAQloDAAABQBIAGkMAAAFAD0AawwAAAUANwBqDAAABABJAGwMAAAEADIAbQwAAAEAEgDqDAAABAAyAG4MAAADACwAbwwAAAEAFgAAAA==.Tyrasia:BAAALgAECgEJAgAAAA==.Tyrith:BAABLgAECn8WAAMDAAgJsxhHPgCrAQhoDAAABABMAGkMAAADAD8AawwAAAMASABqDAAAAwBVAGwMAAACAC4AbQwAAAIAJgDqDAAABABWAG4MAAABADsAAwAHCeIYRz4AqwEHaAwAAAQATABpDAAAAQA7AGsMAAABAD4AagwAAAMAVQBtDAAAAgAmAOoMAAAEAFYAbgwAAAEAOwACAAMJrRcNIgDcAANpDAAAAgA/AGsMAAACAEgAbAwAAAIALgAAAA==.',
['Tö']='Töömis:BAABLgAECn8ZAAIMAAcJkxOFfACBAQdoDAAABQA9AGkMAAAFADgAawwAAAQANwBqDAAABAA2AGwMAAADAC8AbQwAAAEAGADqDAAAAwA1AAwABwmTE4V8AIEBB2gMAAAFAD0AaQwAAAUAOABrDAAABAA3AGoMAAAEADYAbAwAAAMALwBtDAAAAQAYAOoMAAADADUAAAA=.',
Ug='Ugotgotpal:BAAALgAECgcJCAAAAA==.',
Ul='Ulazain:BAABLgAECn8vAAIDAAkJDx/MBgCmAgloDAAABwBDAGkMAAAGAF8AawwAAAYAXQBqDAAABgBBAGwMAAAGADsAbQwAAAMAUwDqDAAABwBcAG4MAAAEAD0AbwwAAAIAUgADAAkJDx/MBgCmAgloDAAABwBDAGkMAAAGAF8AawwAAAYAXQBqDAAABgBBAGwMAAAGADsAbQwAAAMAUwDqDAAABwBcAG4MAAAEAD0AbwwAAAIAUgAAAA==.',
Ur='Urza:BAAALgADCgYJEwAAAA==.',
Us='Usdaprime:BAABLgAECn8eAAIhAAgJbQ4VDACHAQhoDAAAAgARAGkMAAAEABUAawwAAAQAMABqDAAAAwAWAGwMAAAHADoAbQwAAAEAHADqDAAABgAZAG4MAAADADsAIQAICW0OFQwAhwEIaAwAAAIAEQBpDAAABAAVAGsMAAAEADAAagwAAAMAFgBsDAAABwA6AG0MAAABABwA6gwAAAYAGQBuDAAAAwA7AAAA.',
Va='Valarjar:BAAALgADCgIJAgABLgAECgYJBgAHAAAAAA==.Vandene:BAAALgADCgEJAgAAAA==.',
Ve='Velderen:BAAALgAECgQJBAAAAA==.Vengance:BAAALgADCgMJAwAAAA==.Verstappen:BAAALgADCgEJAQAAAA==.',
Vi='Viì:BAABLgAECn8YAAIMAAcJXghWpADPAAdoDAAABQAXAGkMAAAFABoAawwAAAQAFwBqDAAAAwAPAGwMAAADABEAbQwAAAIACQDqDAAAAgAcAAwABwleCFakAM8AB2gMAAAFABcAaQwAAAUAGgBrDAAABAAXAGoMAAADAA8AbAwAAAMAEQBtDAAAAgAJAOoMAAACABwAAAA=.',
Vo='Volsunga:BAAALgAECgQJCgAAAA==.',
Vy='Vyndori:BAAALgAECgUJBQAAAA==.',
Wi='Wildling:BAAALgADCgMJAwAAAA==.Winda:BAAALgADCggJCQAAAA==.',
Wr='Wrease:BAAALgADCgQJBQAAAA==.',
Xa='Xam:BAAALgAECgYJEgAAAA==.Xaphyre:BAAALgADCgEJAQAAAA==.Xarthas:BAAALgAECgMJBAAAAA==.Xavia:BAABLgAECn8fAAIIAAgJahZ7KQDhAQhoDAAABgAzAGkMAAAFAD8AawwAAAUAPABqDAAAAwBXAGwMAAADAEMAbQwAAAIAJADqDAAABgA+AG4MAAABADwACAAICWoWeykA4QEIaAwAAAYAMwBpDAAABQA/AGsMAAAFADwAagwAAAMAVwBsDAAAAwBDAG0MAAACACQA6gwAAAYAPgBuDAAAAQA8AAAA.',
Xy='Xylazel:BAABLgAECn8nAAIKAAkJ1BVEHwA1AgloDAAABQBNAGkMAAAFAE4AawwAAAUAKwBqDAAABQBMAGwMAAAFAEgAbQwAAAQAOgDqDAAABQAzAG4MAAAEACwAbwwAAAEAEwAKAAkJ1BVEHwA1AgloDAAABQBNAGkMAAAFAE4AawwAAAUAKwBqDAAABQBMAGwMAAAFAEgAbQwAAAQAOgDqDAAABQAzAG4MAAAEACwAbwwAAAEAEwAAAA==.',
Ya='Yasmina:BAAALgAECgYJDgAAAA==.',
Yv='Yvana:BAABLgAECn8YAAISAAUJGxxlJgB5AQVoDAAABgBcAGkMAAAFAEAAawwAAAUAVwBsDAAAAQArAOoMAAAHAEcAEgAFCRscZSYAeQEFaAwAAAYAXABpDAAABQBAAGsMAAAFAFcAbAwAAAEAKwDqDAAABwBHAAAA.',
Za='Zaradrela:BAAALgAECgEJAQAAAA==.',
Zu='Zugmaster:BAAALgADCgEJAQAAAA==.',
Zz='Zzephyrdruid:BAACLgAFFH8eAAIjAAcJtSKrAACHAgdoDAAABgBiAGkMAAAFAGEAawwAAAUAYgBqDAAABABIAGwMAAACAD4AbQwAAAEAUADqDAAABwBfACMABwm1IqsAAIcCB2gMAAAGAGIAaQwAAAUAYQBrDAAABQBiAGoMAAAEAEgAbAwAAAIAPgBtDAAAAQBQAOoMAAAHAF8ALgAECn8cAAIjAAgJxCWXDQDBAgAjAAgJxCWXDQDBAgAAAA==.Zzephyrev:BAAALgAECgYJDwABLgAFFAcJHgAjALUiAA==.Zzephyrmage:BAAALgAFFAEJAQABLgAFFAcJHgAjALUiAA==.',
['Âs']='Âsunâ:BAABLgAECn8cAAIdAAgJORxIEgBkAghoDAAABwBcAGkMAAADAFYAawwAAAMAVwBqDAAABQBZAGwMAAADAFIAbQwAAAIAMgDqDAAABAAzAG4MAAABACYAHQAICTkcSBIAZAIIaAwAAAcAXABpDAAAAwBWAGsMAAADAFcAagwAAAUAWQBsDAAAAwBSAG0MAAACADIA6gwAAAQAMwBuDAAAAQAmAAAA.',
['Ôä']='Ôäk:BAAALgADCgYJCwABLgAECgcJIAAdAMwPAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

provider.splitId = 0
provider.splitCount = 1
provider.splitType = 'none'

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
